### ISSUE TITLE
Misleading import suggestion for function supposed to work as implicit conversion

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#10004]
## Minimized code

```Scala
object Foo {
    implicit val implicitLength: String => Int = _.length
}

object Bar {
    val l: Int = "qwerty"
}
```

## Output

```scala
val l: Int = "qwerty"
             ^^^^^^^^
             Found:    ("qwerty" : String)
             Required: Int

             The following import might fix the problem:

               import Foo.implicitLength
```

## Expectation

As in Scala 3 implicit function values don't work as implicit conversions anymore, the import suggestion should not be displayed. Alternatively it might suggest both adding the import and changing the implicit value from an instance of Function2 to a Conversion (although this solution should be probably taken only when compiling with `-source:3.0-migration` flag).

## Reproduction tips

For me this happens only in REPL. When I compile it with sbt, I don't get the import suggestion at all, even if the conversion is defined as it should be to work in Scala 3 (implicit def or implicit value of Conversion type) and implicit conversions are explicitly enabled.

**Comment by odersky** [comment]
No action since october. Is this important enough to fix? Please re-open if you think so and have a solution.
