### ISSUE TITLE
Tasty-reflect documentation links to out-of-date repository

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#10023]
http://dotty.epfl.ch/docs/reference/metaprogramming/tasty-reflect.html links to https://github.com/nicolasstucki/tasty-reflection-exercise which hasn't been updated in a while, I guess that link should be removed and replaced by a link to the new macro tutorial?

**Comment by smarter** [comment]
Should we just remove the link?

**Comment by nicolasstucki** [comment]
We can remove it. I'll add it back in the tutorial when I have the time to update the project.
