### ISSUE TITLE
Tuple’s apply method fails at runtime unless its result type is explicitly provided

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#10033]
## Minimized code

```Scala
val t = (1, true)

val x = t(0)
val y = t(1)
val z = t(2)
```

## Output

The code compiles but fails at runtime when `val z` is evaluated, with an error “index out of bounds: 2”.

## Expectation

The code should fail at compile-time.

It is worth noting that if the expected result type is explicitly provided, we get a compilation error:

```Scala
val t = (1, true)

val z: String = t(2)
```

~~~ text
Type Mismatch:
  Found:    scala.Tuple.Elem[scala.Tuple$package.EmptyTuple.type, (0 : Int)]
  Required: String
~~~

(We could probably also improve the error message)

**Comment by griggt** [comment]
Perhaps I'm missing something, but it looks like a compilation error?

```scala
[info] Compiling 1 Scala source to /src/dotty-issues/i10033/target/scala-3.0.0-M1/classes ...
[error] -- Error: /src/dotty-issues/versions/src/main/scala/i10033.scala:5:10 ----------
[error] 5 |val z = t(2)
[error]   |          ^
[error]   |          index out of bounds: 2
[error]   | This location contains code that was inlined from i10033.scala:5
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 5 s, completed Oct 19, 2020, 12:02:24 AM
```

using `Scala 3.0.0-M1-bin-20201018-bdf634c-NIGHTLY`

**Comment by julienrf** [comment]
Oops, indeed I’m sorry, I tried this in a REPL and didn’t distinguish well between compilation and runtime errors :)
