### ISSUE TITLE
Make `'[...]` syntax useful

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10036]
### Syntax proposal
The incentive for this change is to use `'[..]` for something useful.

```diff
- def singletonListExpr[T](x: Expr[T])(using Type[T])(using QuoteContext): Expr[List[T]]

+ def singletonListExpr[T](x: Expr[T])(using '[T])(using QuoteContext): Expr[List[T]]
```
This would read as `using T in quotes` instead of `using type of type T`. 

This would also fix all ambiguities with `Reflection.Type` that we always end up having when importing `qctx.reflect._`.

For this to work, we would need to change the parser and allow type quote syntax `'[..]`. This is quite similar to the parsing rules we already have for expressions `'[..]`.

In the library, we could define the type itself using an escaped `'`. Such as `class `'`[T <: AnyKind]` or `type `'`[T <: AnyKind]`.
It could also be an alias to a more explicit name such as `type `'`[T <: AnyKind] = TypeUsedInExpr[T]`.

The limitation is that with this simple syntax change we would not be able to use context bounds with the new syntax.
```scala
def singletonListExpr[T: '](x: Expr[T])(using QuoteContext): Expr[List[T]] // error
def singletonListExpr[T: `'`](x: Expr[T])(using QuoteContext): Expr[List[T]]
```
Though we can always use it with backticks or define an alias for it to work.
But the changes proposed in #8940 might make it impossible to use context-bounds anyway, therefore this might not even be an issue.

### Old syntax
The `'[..]` syntax for creation is redundant as stated in #9486.
-  `'[...]` could be written as `summon['[...]]`
- The use of `'[...]` usually indicates that the program is doing something wrong or in a non-optimal way.

The `$t` syntax for splicing a `t: Type[X]` is redundant as stated in #9486.
-  `$t` should be written as `X` or `t.T` (`$t` is desugared to `t.T`).
- The use of `$t` is allowed at any level where `T` is known. This breaks the level counting 

We remove disallow `'[..]` and `$t` as a way to create quoted types to encourage users to use the abstraction the correct way.
Giving them a shorthand that can only be used to write the wrong is a detriment for usability and understanding of the API.

### Previous mistake
Originally we mistakenly thought that there should be a symmetry between expressions `'{ ... }` and types `'[...]` as this gave some simple rules of splice/quote cancelation. We thought that we could track the level by counting quoted and splices both on expressions and type. We then discovered that this was only true for expressions,  types behave differently.

The actual symmetry:
- `'{..}` and `${...}` do have the expected symmetry and cancel each other. 
- `'[X]` must contain a type that is known in any previous level and`$t` (or the preferred `X` or `t.T`) can be used at any

Expressions have a kind of symmetry on levels but types have a kind of antisymmetry on levels.

**Comment by smarter** [comment]
I'm fine with removing `'[...]` as it exists currently if it's not optimal, but I disagree about having a class named `'`, this is too confusing and doesn't really provide any benefits compared to writing `Type[T]` (ok, there's an ambiguity with Reflection.Type, but I'm sure we can come up with a different name that isn't a single character).

**Comment by nicolasstucki** [comment]
Then we would need to rename `scala.quoted.Type`. I have proposed for a long time, but nobody agrees of what name to use for it. What name should we use instead?

**Comment by smarter** [comment]
`ExprType`, to remind people of `Expr` ? Though renaming the other one to be longer might make more sense since it's less commonly used.

**Comment by nicolasstucki** [comment]
Hm, `ExprType` sounds good. It is a name that would make it simple to relate to `Expr` and explain.

**Comment by nicolasstucki** [comment]
Another option is `Repr`

**Comment by LPTK** [comment]
Squid uses `Code`/`CodeType` for the typed interface, and `Rep`/`TypeRep` for the untyped representation. But I've always found `CodeType` too verbose. Why don't you pick `Expr`/`Type` and `Term`/`TermType`?

**Comment by nicolasstucki** [comment]
We tough about `TypeRep` for the `Reflection.Type`. Instead of `TermType` it would need to be `TreeType` as we have other kinds of type, but we already have `TypeTree` and don't want to lead to confusions there.
