### ISSUE TITLE
Maybe warn when trying to summon from Context Fn upper bound

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10040]
## Minimized code

```Scala
object CtxFns {

  abstract class Context:
    def puts[T](t: T): Unit

  class CtxBox[Contextual <: [T] =>> Context ?=> T] {
    def puts[T](t: T): Contextual[Unit] = summon[Context].puts(t)
  }

}
```

## Output

```scala
-- Error: CtxFns.scala:9:57 -------------------------------
9 |    def puts[T](t: T): Contextual[Unit] = summon[Context].puts(t)
  |                                                         ^
  |no implicit argument of type tastytest.CtxFns.Context was found for parameter x of method summon in object DottyPredef
```

## Expectation
either it works, or the bound means that it is impossible to guarantee Context in scope and so perhaps a warning?

**Comment by LPTK** [comment]
We have `Contextual[Unit] <: Context ?=> Unit`, but the abstract type `Contextual[Unit]` it may be _more precise_ than that (say, it could actually end up being instantiated to `Any ?=> Unit` or even `Nothing`), so we can't give a value for it.

Also note the error if the function type is made explicit:

```scala
  class CtxBox[Contextual[T] <: Context => T] {
    def puts[T](t: T): Contextual[Unit] = x => x.puts(t)
  }
```

`Contextual[Unit] is not a legal SAM type since it is not a concrete type`

**Comment by bishabosha** [comment]
thanks, that makes sense :)

**Comment by LPTK** [comment]
I guess you could raise a warning when the expected type is a type _related_ to an implicit function type (but not itself one) _and_ when the body contains an implicit-not-found error. But I'm not sure it'd be worth the effort.

**Comment by neko-kai** [comment]
Adaptation to context function does not work even if the type is lower-bounded, not upper:

```scala
object CtxFns {

  abstract class Context:
    def puts[T](t: T): Unit

  class CtxBox[Contextual[T] >: (Context ?=> T)] {
    def puts[T](t: T): Contextual[Unit] = (summon[Context].puts(t): Context ?=> Unit)
  }

  class CtxBox2[Contextual[T] >: (Context ?=> T) <: (Context ?=> T)] {
    def puts[T](t: T): Contextual[Unit] = (summon[Context].puts(t): Context ?=> Unit)
  }

}
```

**Comment by odersky** [comment]
I think a warning would be too tricky. Or please re-open if you have a workable fix.
