### ISSUE TITLE
Context function literal with anonymous parameters

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10057]
## Minimized code

```Scala
def m = (using Int) => summon[Int]
```

## Output

```scala
1 |def m = (using Int) => summon[Int]
  |               ^^^
  |               Missing parameter type
  |
  |               I could not infer the type of the parameter Int.
```

## Expectation

Debatable if this should follow the meaning of using clauses

**Comment by bishabosha** [comment]
Looking back I would say that this syntax is exactly equivalent to just having an expected type of context function and no binders - so probably not worth it

**Comment by odersky** [comment]
Yes, I think we leave it as it is. We have to decide which part is optional: the type or the parameter name. I believe the analogy with normal closures where the type is optional is the stronger one here.
