### ISSUE TITLE
Should there be only one context function literal syntax?

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10056]
## Minimized example

```Scala
val m = (x: Int) ?=> x       // query style, mirrors type
val n = (using x: Int) ?=> x // mixing styles
val o = (using x: Int) => x  // used by the MOOC
```

## Output

they all compile

## Expectation

Only one of these should be accepted I assume. Looking at the [syntax](https://dotty.epfl.ch/docs/internals/syntax.html) these are all legitimate, but the [docs](https://dotty.epfl.ch/docs/reference/contextual/context-functions.html) uses the third kind

**Comment by OlivierBlanvillain** [comment]
Yes! I vote for the last one.

**Comment by odersky** [comment]
Yes, it was an oversight that the old syntax was not removed. I'll get to it.
