### ISSUE TITLE
Weird case of double-parentheses impacting type inference in List.apply

### ISSUE THREAD

**Issue by neko-kai** [lampepfl/dotty#10062]
## Minimized code

```Scala
class X

object X {
  extension (x: List[X]) { def isNull = x.head == null }
}

@main def test = List(null: X).isNull
```
https://scastie.scala-lang.org/He9Pm96ySZCBCziHLktlXg

## Output

Error:

```scala
Found:    X
Required: Any*
```

## Expectation

Should compile. If a _redundant_ second set of parentheses is added in `List((null: X))`, then the example compiles:

```scala
class X

object X {
  extension (x: List[X]) { def isNull = x.head == null }
}

@main def test = List((null: X)).isNull
```
https://scastie.scala-lang.org/dwFH7NAsQyqKpoXHuzAWiA

**Comment by som-snytt** [comment]
```
scala> List(null: String)
1 |List(null: String)
  |     ^^^^^^^^^^^^
  |     Found:    String
  |     Required: Any*

scala> List("": String)
val res4: List[String] = List("")

scala> List((null: Seq[String]): _*)
java.lang.NullPointerException: Cannot invoke "scala.collection.IterableOnce.knownSize()" because "prefix" is null
```

**Comment by neko-kai** [comment]
@som-snytt 
Hmm, works for me on Scala 2.13.3, your first repl command & scastie (https://scastie.scala-lang.org/yYKd7yxWTdSeKF1wezvFYQ).

```scala
class X

object App extends App {
  val test = List(null: X)
  println(test)
}
```

Is your repl printout from 2.12?

**Comment by som-snytt** [comment]
Sorry I didn't add commentary. It's `null` sequence arg that is the problem for scala 2, which scala 3 handles the same as if it were `null: Seq[_]`.

I was curious why it says `Any*` is required. The sequence arg annotation is just an ascription that can only be applied to the last argument in an application. I was curious about other positional problems and opened the linked ticket.

The other point was that the error here happens on `List(null: String)`, which scala 2 is fine with. Maybe scala 3 already checked `null <:< Seq[_]`? I would think you have to look at `_*` even to understand what the application is, see the linked ticket.
