### ISSUE TITLE
Value + is not a member of Int

### ISSUE THREAD

**Issue by Somainer** [lampepfl/dotty#10082]
Inspired by [Context Functions](http://dotty.epfl.ch/docs/reference/contextual/context-functions.html), I decided to practice my bad taste on simulating the `it` anonymous function parameter. But it doesn't work.

## Minimized code

```Scala
object Kotlin:
  def it[T](using t: T) = t
  def fun[T, U](fn: T ?=> U)(x: T): U = fn(using x)

import Kotlin.{fun, it}
List(1).map(fun(it + 1))
```

## Output

```
|List(1).map(fun(it + 1))
  |                ^^^^
  |value + is not a member of Int, but could be made available as an extension method.
  |
  |One of the following imports might fix the problem:
  |
  |  import math.BigDecimal.int2bigDecimal
  |  import math.BigInt.int2bigInt
  |  import math.Numeric.BigDecimalAsIfIntegral.mkNumericOps
  |  import math.Numeric.BigDecimalIsFractional.mkNumericOps
  |  import math.Numeric.BigIntIsIntegral.mkNumericOps
  |  import math.Numeric.IntIsIntegral.mkNumericOps
  |  import Long.long2double
  |  import math.BigDecimal.long2bigDecimal
  |  import Long.long2float
  |  import math.BigInt.long2bigInt
  |

```

## Expectation
This code should compile as `it` has already been inferred as `Int`.

## Workaround
Providing type arguments to `fun` works.

```scala
List(1).map(fun[Int, Int](it + 1))
```

**Comment by liufengyun** [comment]
The following works:

```Scala
object Kotlin:
  class Ctx[T, U](val x: T) extends AnyVal

  def fun[T, U](fn: Ctx[T, U] ?=> U): T => U = (x: T) => fn(using new Ctx(x))
  def it[T, U](using ctx: Ctx[T, U]) = ctx.x


import Kotlin._

@main def Test =
  val res = List(1).map(fun(it + 1))
  assert(res == List(2))
```

**Comment by liufengyun** [comment]
> value + is not a member of Int

The reason is that from the program we only know that `T :> Int`, which is correct. By wrapping the parameter in a non-variant class `Ctx`, the compiler may infer `T = Int`.

**Comment by Somainer** [comment]
Thank you, it worked.
However, the warning message is very confusing. And I think users like me are not able to find out the reason with the message _value + is not a member of Int_.

**Comment by liufengyun** [comment]
We do need to improve the error message. I'll make another PR to fix that.
