### ISSUE TITLE
Decide on the syntax of `given` in patterns

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#10087]
Currently the syntax for given in patterns looks like:
```scala
  def f1[T](x: Ordering[T]) = (x, x) match {
    case (given y: Ordering[T], _) => new TreeSet[T]
  }
  def f4[T](x: Ordering[T]) = {
    val xs = List(x, x, x)
    for given _: Ordering[T] <- xs
    yield new TreeSet[T]
  }
```

Which is different from the expression syntax where we write `given Type` or `given name as Type`, aligning ourselves would be nice, although the `as` syntax isn't so useful since we can use pattern bindings `name @ given Type` or `name as given Type` after https://github.com/lampepfl/dotty/pull/9837, so we could support only the `given Type` syntax.

**Comment by odersky** [comment]
In the Dotty meeting the consensus was to keep only the anonymous `given Type` syntax. If a name is desired, it can be added with a `as` binder as in other patterns. I.e. the example would be 
```
def f1[T](x: Ordering[T]) = (x, x) match {
    case (given Ordering[T], _) => new TreeSet[T]
  }
  def f4[T](x: Ordering[T]) = {
    val xs = List(x, x, x)
    for given Ordering[T] <- xs
    yield new TreeSet[T]
    for x as given Ordering[T] <- xs
    yield new TreeSet[T]
  }
