### ISSUE TITLE
inline if error suggests it expects a literal expression

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#10107]
## Minimized code

Say we make a simple macro that just returns the value `true`.
```Scala
object Proc {
  inline def isTrue: Boolean = ${ isTrueImpl }
  def isTrueImpl(using qctx: QuoteContext) = {
    Expr(true) // even tried: Literal(Constant(true).seal.asExprOf[Boolean])
  }
}
```
Now if we use that with an inline if statement:
```scala
  inline def oneOf(): String = {
    inline if (isTrue)
      "foo"
    else
      "bar"
  }
```
Then when I run that:
```scala
oneOf()
```
The following error happens...

## Output

```
[error]    |    cannot reduce inline if
[error]    |     its condition   miniquill.ListProc.isTrue
[error]    |     is not a constant value
```

## Expectation
I think this should be more intelligent about looking at the AST and detecting if there is a constant value. I even tried making `oneOf` return `Literal(Constant(true))` but it still did not work.

**Comment by bishabosha** [comment]
this does not work because inline if looks at the static type of the expression - if you make `isTrue` a `transparent inline def` it works

**Comment by bishabosha** [comment]
perhaps the error is misleading

**Comment by deusaquilus** [comment]
Thanks @bishabosha! The message “it needs to be a constant” conveys the correct high-level understanding “(and this expects a literal type)” in parenthesis would be a good addition though.

**Comment by nicolasstucki** [comment]
Actually, it is a shame to fail on a `true: Boolean`. We can easily handle those cases.
