### ISSUE TITLE
compileTimeOnly does not work on a trait/class

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10122]
## Minimized code

```Scala
@annotation.compileTimeOnly("Foo should be erased") trait Foo
@annotation.compileTimeOnly("Bar should be erased") class Bar
val foo = new Foo {}
val bar = new Bar {}
```

## Output

compiles ok

## Expectation

error `Foo should be erased`, `Bar should be erased`, as in Scala 2.13

**Comment by odersky** [comment]
Not sure we need to have the same behavior here. `compileTimeOnly` is not specced anywhere as far as I know. And it will be replaced by `erased`, or so we hope.
