### ISSUE TITLE
REPL: sealed traits cannot be extended

### ISSUE THREAD

**Issue by unkarjedy** [lampepfl/dotty#10145]
Running the following statements one by one in REPL fails with "Cannot extend sealed trait A in a different source file"

## Minimized Code

```scala
scala> sealed trait T                                                                                                   
// defined trait T

scala> case class A() extends T  
```

## Error

```scala
scala> case class A() extends T                                                                                         
1 |case class A() extends T
  |           ^
  |           Cannot extend sealed trait T in a different source file
```

leads to: https://github.com/lampepfl/dotty/issues/5545

**Comment by bishabosha** [comment]
this is allowed in Scala 2.13 repl, but not allowed in ammonite

**Comment by dwijnand** [comment]
Related: https://github.com/scala/bug/issues/11229.  Being able to subclass a sealed type in the REPL is making the exhaustivity analyser a liar.  My guess is that it accidentally works and making it not do it any more would avoid such differences of compiler/repl opinion.

**Comment by Jasper-M** [comment]
If the REPL doesn't allow this it should definitely have a good `:paste` mode. I think that now the only options are

- putting the sealed trait and all its descendants on one line
- wrapping them in an object
- typing them in a separate notepad and actually pasting them into the REPL

**Comment by bishabosha** [comment]
decided in the dotty meeting that this should not be supported

**Comment by som-snytt** [comment]
I was just responding to a scala 2 thing about REPL and parser reporting and had a thought:

I'd actually like my repl session to be like a line editor, but with the runtime semantics we expect. (Previous results are not re-evaluated.)

That is, a line editor view onto a worksheet, but if I edit a line, only re-evaluate the edit. I might augment the worksheet with values but also types. So I'd also like the compiletime semantics we expect.

**Comment by dwijnand** [comment]
While I don't have a problem with "extending a sealed trait in another command" not being supported, I think it's a problem that @Jasper-M's list are all the available options, i.e. it's a PITA to define a sealed hierarchy in the REPL.  Should I open a new ticket?
