### ISSUE TITLE
Allow comments to be cooked from TASTy

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#10147]
In the doctool, we need to implement resolve Scaladoc comment variables (`@define`) - see https://docs.scala-lang.org/overviews/scaladoc/for-library-authors.html#macros for the only documentation I'm aware of.

Dottydoc resolved those under `YcookComments` flag, but the result of that was not serialised to TASTy. We anyway came to the conclusion that for design reasons, we want to avoid adding expanded comments to TASTy.

This means that we need to investigate whether the code responsible for "cooking" comments could also be ran when classes are loaded from TASTy.

**Comment by abgruszecki** [comment]
@bishabosha I gave the problem some thought and I believe the best time to get started on this would be after https://github.com/lampepfl/dotty/issues/10143 is fixed, since stdlib is the best test case for this issue.

**Comment by bishabosha** [comment]
@abgruszecki ok thanks, I'll take a look then

**Comment by abgruszecki** [comment]
Done.
