### ISSUE TITLE
If a method foo overrides a method foo(), then it cannot be called as foo()

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1017]
This is valid in Scala 2 but not in Dotty:

``` scala
class A {
  def foo(): Int = 1
}
class B extends A {
  override def foo: Int = 2
}

object Test {
  def main(args: Array[String]): Unit = {
    val b = new B
    println(b.foo())
  }
}
```

@odersky : Do you think this should be legal in Dotty? Otherwise, should we at least support it in Scala 2 mode ?

**Comment by sjrd** [comment]
If the override itself is legal, then so should the call `b.foo()`.

Overriding a 0-arg method with a getter-style def is mainly meant for Java interop, as I see it. People want to be able to `override def toString`, for example, not `override def toString()`. It is for the same reason that `x.toString` itself is valid, IMO. In pure Scala such things should never have been needed.

**Comment by odersky** [comment]
It would be hard to allow this, even in Scala 2 mode. def foo() and def foo have the same signatures
so we keep the overriding one as the only truth. I think it's OK to leave it as is. The reasoning would be: If I intentionally override `def foo()` with `def foo` then it's because I intend `foo` to be called without
`()`. So this intention should be honored by the callers.

**Comment by odersky** [comment]
I am not against supporting it in Scala2 mode, if we can do so easily. But right now it does not look like we can.

**Comment by sjrd** [comment]
The combination of 1) allowing the `override def foo` but 2) only allowing calling `x.foo` in that case, is, IMO, very dangerous. It will break a lot of code *in dependencies of libraries down the line*.

Let's say I have a codebase in library A, where the coding style is to remove the `()` for all non-side-effecting "getters", including those from Java, and including in overridings. The new interpretation would not cause harm to library itself. It would still compile, its tests would pass, and it would get published.

Now, a project B which used to depend on library A is updated. In B's codebase, the coding style is to be very strict about keeping the `()` at all times if they were defined as such (e.g., from Java), event at call site. Now B's code referring to methods from A breaks! And A never had any idea this would break its users.

I think this is a bad situation.

IMO we should either 1) keep Scala 2's behavior (as much as I dislike it) or 2) *disallow* overriding a method with `()` with a method without `()`. Note that the second proposition is *also* subject to the "A is fine but B is broken" problem, but much less often so: it requires B to actually extend classes from A (not just use them). The decision in the middle is asking for trouble.

**Comment by odersky** [comment]
2) is clearly unworkable as it would mean that we cannot ever define a `def toString` method. So 1) is really the only option except doing nothing. And it seems really difficult to fit into our architecture for overloading/overriding. I'll have to give this some more thought.

**Comment by smarter** [comment]
The override is no longer legal so this can be closed. See discussion and associated PRs of https://github.com/lampepfl/dotty/issues/2571
