### ISSUE TITLE
`val 1 = 0` in the REPL should `MatchError` (SI-4939 redux)

### ISSUE THREAD

**Issue by SethTisue** [lampepfl/dotty#10214]
Scala 2 behavior is correct, as per scala/bug#4939

```scala
scala 2.13.3> val 1 = 0
scala.MatchError: 0 (of class java.lang.Integer)
```
but in Scala 3.0.0-M1:

```scala
scala> val 1 = 0

scala>                                                                                                                  
```

gitter today:

> Michael Pilquist @mpilquist 12:21
> out of curiosity, why does val 1 = 0 not throw a match error or otherwise fail in dotty repl?

> Guillaume Martres @smarter 12:22
> that's definitely a bug
> the exception must be caught and ignored somewhere

**Comment by mpilquist** [comment]
Note the test case from the linked issue fails too:

```scala
scala> object O { val 1 = 2; def x = 1 }
// defined object O

scala> O.x
scala.MatchError: 2 (of class java.lang.Integer)
	at rs$line$1$O$.<clinit>(rs$line$1:1)
	at rs$line$2$.<clinit>(rs$line$2:1)
	at rs$line$2.res0(rs$line$2)
```

**Comment by SethTisue** [comment]
@mpilquist I think that test case (which was mine, almost a decade ago) was misconceived. That behavior is actually correct; the `def x` is a red herring. It boils down to:

```
scala 2.13.3> object O { val 1 = 2 }
object O

scala 2.13.3> O
scala.MatchError: 2 (of class java.lang.Integer)
```

which Dotty already handles correctly.

so I think this isn't actually scala/bug#4939 returning; it's merely the REPL-only scala/bug#4950 returning.

**Comment by som-snytt** [comment]
The ~old~ Scala 2 REPL had two objects, one to wrap user code and a second to pull values out and compose a string to display. The second object was endowed with a reference to the first, to ensure initialization in the absence of members. This is currently done reflectively. I mean currently in Scala 3.
