### ISSUE TITLE
Document interaction of implicit resolution and macros

### ISSUE THREAD

**Issue by rnd4222** [lampepfl/dotty#10213]
It is not very clear how implicit resolution works in presence of (possibly failing) macro expansions.

Example:

```scala
implicit inline def eqGenInt: Eq[Int] = ${ ... } // throws on expansion, so not actually overlapping
implicit def eqInt: Eq[Int] = new Eq[Int] { ... }
```

For now it seems that failing expansion is ignored and implicit resolution proceeds to other instances, even if they are "overlapping" (modulo expansion failures).

Can I rely on this behaviour?
If so, it would be great to have it documented somewhere.

**Comment by nicolasstucki** [comment]
The behavior will slightly change after #9984.

In the current behavior, a failure to expand an `implicit inline def` when looking for implicit will only let the implicit search know that this is not the implicit it is looking for. Then implicit search continues looking and the error is not emitted.

After #9984 `implicit transparent inline def` will keep the current behavior. On the other hand, non-transparent ones will finish the implicit search on that method if the signature agrees and then it will emit the error.
