### ISSUE TITLE
Rename `dotty` to `scala.tools.dotty`

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10227]
Maybe we should move the compiler root package `dotty` to `scala.tools.dotty` and follow the same naming scheme as in Scala 2 (`scala.tools.nsc`).

This would make it possible to access package-private members of the library within the compiler. There are some use cases within the metaprogramming API where this might help to remove unnecessary classes from the library (see #10222).

**Comment by odersky** [comment]
But then it would be `scala.tools.dotty.tools.dotc`. Or would we have `scala.tools.dotc` directly, and also have `repl` and `backend` in `scala.tools`?

The dotty compiler does not necessarily need to live inside the scala package. For instance `javac` still lives in `com.sun.tools`.

**Comment by smarter** [comment]
Java doesn't have nested packages though. We want to allow the scala 2 and scala 3 compiler jar to coexist on the same classpath, so if we were to move, we'd have to put everything in `scala.dotc` or `scala.tools.dotc`.

**Comment by som-snytt** [comment]
Plus one for `scala.tools.dotc`, speaking as someone who just moved code from Scala 2 and had to pick a package.

It's worth adding that Scala 2 has a much richer ecosystem of `util` packages. I think I'm being sarcastic, but I can't be sure.

Also plus one for `scala.tools.repl` in the hope that eventually there will be a common front end with variant backend implementations.

As a caveat, "Where does my test file go in Scala 3?" is still a minor research project for me, so my take is necessarily naive.

**Comment by dwijnand** [comment]
> This would make it possible to access package-private members of the library within the compiler.

On the other hand that adds yet-another external users of scala's package privates...

**Comment by odersky** [comment]
We decided not to act on this right now.
