### ISSUE TITLE
Misleading compile error when erased value is used (error message suggests that the 

### ISSUE THREAD

**Issue by jatcwang** [lampepfl/dotty#10223]
Version: `3.0.0-M2-bin-20201106-312a420-NIGHTLY` (and 3.0.0-M1)

## Minimized code

```Scala
import scala.compiletime.{erasedValue, error}

@main
def main: Unit = {
  inline def lol[I] = {
    erasedValue[I] match {
      case i: Int => println("hello")
      case _ => error("custom type match failed")
    }
  }

  lol[Int]  
}

```

## Output

Compile error: `custom type match failed`

## Expectation

Compile error `erasedValue is declared as erased, but is in fact used`

I think the error here is slight misleading - the real issue is that erasedValue is being used but the compile error returned seems to indicate that w/e type match we're doing failed.

Further minimization:
This returns the same `custom type match failed` compile error.

```
  erasedValue[Int] match {
    case i: Int => println("hello")
    case _ => error("custom type match failed")
  }
```

**Comment by bishabosha** [comment]
if you take the original code but use a wildcard and not `case i: Int =>` then you still get the custom error.
In the second example, if you put it in an inline method then you get `unreachable case` for the error branch

**Comment by odersky** [comment]
I think the reported error is correct.
