### ISSUE TITLE
Ycheck that trees are in place where they make sense

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1023]
Motivated by https://github.com/lampepfl/dotty/issues/939
Currently dotty allows different trees to be in places where they shouldn't. Examples that I know are
- TypeTree can be a qualifier of a Select node;
- TypeTree can be a statement in Block.

I am pretty sure that other examples exist. 
It would be great to trigger errors early in Ycheck, indicating which phase introduced such trees.

**Comment by dwijnand** [comment]
@odersky in #4960 you said:

> I fear this would ossify our compiler infrastructure. For instance, we might very well create matches with type trees. So my preference is to hold off with this until we are feature complete, and development slows.

Would you be happy to see an updated version of that PR land now?

**Comment by nicolasstucki** [comment]
It seems that now we could revisit these checks. Adding this would also be extremely helpful to users of the reflection API.
