### ISSUE TITLE
Safari renders links at screen height in the sidebar

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10245]
https://scala3doc.s3.eu-central-1.amazonaws.com/pr-master/stdLib/main/index.html ~does not show anything~ shows screen height size links in the sidebar with safari (`Version 14.0 (15610.1.28.1.9, 15610)`), seems to be fine in Chrome

**Comment by smarter** [comment]
This is higher-priority now that http://dotty.epfl.ch/docs is rendered using scala3doc.

**Comment by bishabosha** [comment]
Ive also noticed that all the links are in the sidebar, just that each one fills all the vertical space. This seems to be a issue generally with Dokka, as seen here: https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-cbor/kotlinx-serialization-cbor/index.html

**Comment by bishabosha** [comment]
@romanowski thank you its perfect

(fixed by #10463)
