### ISSUE TITLE
No code completion for extension methods

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#10264]
## Minimized code

```scala
object Bar

extension (bar: Bar.type) def xxxx: Int = 1

implicit class BarOps(bar: Bar.type) {
  def yyyy: Int = 2
}
```

```scala
Bar.xx
```

## Output

When pressing TAB in REPL, the method `xxxx` is not suggested.

## Expectation

`Bar.xx` should expand to `Bar.xxxx` just as `Bar.yy` expands to `Bar.yyyy`. The issue is not specific to REPL however. This doesn't work with Metals either.

**Comment by odersky** [comment]
@prolativ Can you suggest someone to take this on?
