### ISSUE TITLE
Standard code on HList works but inline version fails with ClassCastException

### ISSUE THREAD

**Issue by hmf** [lampepfl/dotty#10284]
## Minimized code

```Scala
  sealed trait HList
  case class HCons[+HD, TL <: HList](hd: HD, tl: TL) extends HList
  case object HNil extends HList

  type Inverse[X <: HList] <: HList = X match {
    case HCons[x, t] => InverseB[t, HCons[x, HNil.type]]
    case HNil.type => HNil.type
  }
  type InverseB[X <: HList, Y <: HList] <: HList = X match {
    case HCons[x, t] => InverseB[t, HCons[x, Y]]
    case HNil.type => Y
  }

  def reverseLoopX[Xs <: HList, Ys <: HList](xs: Xs, ys: Ys): Inverse[Xs] = {
    xs match {
      case HNil =>
        ys
      case HCons(h,t) =>
        reverseLoopX(t, HCons(h,ys))
    }
  }.asInstanceOf

  def reverse[Xs <: HList](expr: Xs): Inverse[Xs] = {
    reverseLoopX(expr, HNil)
  }.asInstanceOf

  summon[Inverse[HCons[1,HCons[2,HCons[3, HNil.type]]]] =:= HCons[3,HCons[2,HCons[1, HNil.type]]]]

  val ihl1: HCons[(String, Int), HCons[(String, Int), HCons[(String, Int), Recorder.HNil.type]]] = reverseLoopX(hl1, HNil)

```

The code above compiles and executes correctly. 

```Scala
  sealed trait HList
  case class HCons[+HD, TL <: HList](hd: HD, tl: TL) extends HList
  case object HNil extends HList

  type Inverse[X <: HList] <: HList = X match {
    case HCons[x, t] => InverseB[t, HCons[x, HNil.type]]
    case HNil.type => HNil.type
  }
  type InverseB[X <: HList, Y <: HList] <: HList = X match {
    case HCons[x, t] => InverseB[t, HCons[x, Y]]
    case HNil.type => Y
  }

  transparent inline def reverseLoopX[Xs <: HList, Ys <: HList](inline xs: Xs, ys: Ys): Inverse[Xs] = {
    inline xs match {
      case HNil =>
        ys
      case HCons(h,t) =>
        reverseLoopX(t, HCons(h,ys))
    }
  }.asInstanceOf

  transparent inline def reverse[Xs <: HList](inline expr: Xs): Inverse[Xs] = {
    reverseLoopX(expr, HNil)
  }.asInstanceOf

  summon[Inverse[HCons[1,HCons[2,HCons[3, HNil.type]]]] =:= HCons[3,HCons[2,HCons[1, HNil.type]]]]

  val ihl1: HCons[(String, Int), HCons[(String, Int), HCons[(String, Int), Recorder.HNil.type]]] = reverseLoopX(hl1, HNil)

```
The code above fails with this exception:

## Output

```scala
Exception in thread "main" java.lang.ClassCastException: class automl.Recorder$HCons cannot be cast to class automl.Recorder$HNil$ (automl.Recorder$HCons and automl.Recorder$HNil$ are in unnamed module of loader 'app')
```

## Expectation

I expect both version to have the same behavior. I placed `println`s in the function and see that each step is executed as expected, however the error seems to occur when the value is assigned to a variable. 

I also copy & pasted the inlined results to see if I could get any insight into the problem, but I am not able to compile it. 

This was tested using the latest Scala3 release and JDK 11.

Any way I can circumvent this?

**Comment by smarter** [comment]
Before we look at anything else: don't write `asInstanceOf` without a type parameter, it could be inferred to `Nothing` for example which would crash at runtime, and especially when combined with `inline` it's hard to know what it's going to do.

**Comment by hmf** [comment]
@smarter Understood. I picked this up from the dotty tests (HList concat). However I must confess I don't know  what to use in the type parameters. Would I be correct in saying that I must use an `asInstanceOf` per case? Do you have any suggestions I can make to run the test again? 

Having said that, I did used the macros `show` to see what code was generated. It looks like the types are correctly inferred. The last part of the output shows:

```
      }.asInstanceOf[automl.Recorder.HNil.type]
    }.asInstanceOf[automl.Recorder.HCons[scala.Tuple2[java.lang.String, scala.Int], automl.Recorder.HNil]]
  }.asInstanceOf[automl.Recorder.HCons[scala.Tuple2[java.lang.String, scala.Int], automl.Recorder.HCons[scala.Tuple2[java.lang.String, scala.Int], automl.Recorder.HNil]]]
}.asInstanceOf[automl.Recorder.HCons[scala.Tuple2[java.lang.String, scala.Int], automl.Recorder.HCons[scala.Tuple2[java.lang.String, scala.Int], automl.Recorder.HCons[scala.Tuple2[java.lang.String, scala.Int], automl.Recorder.HNil]]]]

```

Thank you

**Comment by smarter** [comment]
if the result type is `Inverse[Xs]`, write `.asInstanceOf[Inverse[Xs]]` instead of `.asInstanceOf`.

**Comment by hmf** [comment]
Ahh, of course. Did it. I ran the test again and got the same result :-(
Thanks for the info.

**Comment by smarter** [comment]
```scala
  transparent inline def reverseLoopX[Xs <: HList, Ys <: HList](inline xs: Xs, ys: Ys): Inverse[Xs] = {
    inline xs match {
      case HNil =>
        ys
      case HCons(h,t) =>
        reverseLoopX(t, HCons(h,ys))
    }
  }.asInstanceOf
```
This code is just incorrect, and the cast masks it, if I write `reverseLoopX(HNil, HCons(...)`, the result will be `HCons(...)`, but the result type is `Inverse[HNil.type]` which reduces to `HNil.type`, hence the ClassCastException.

**Comment by hmf** [comment]
Yep, need someone @smarter to point out the error :-). I guess because the standard non-inline version worked, led me astray. Thanks.
