### ISSUE TITLE
Imports from unstable prefixes should not be allowed

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#10295]
I don't think this is intentionally allowed, it only works when the def returns a singleton type:

```Scala
scala> def get: 1 = { println("hi"); 1 }
def get: 1

scala> import get._

scala> toLong
hi
val res0: Long = 1

scala> toLong
hi
val res1: Long = 1
```

(if one really wants to pretend a prefix is stable, there's an `@uncheckedStable` annotation, though it's implemented by Scala 2 but not Dotty)

**Comment by nicolasstucki** [comment]
We need this in some for to be able to support imports for contextual abstractions. This feature allows us to import the contents of the context parameter without naming it.

```scala
trait M:
  type X
  object X:
    def foo(): X

def m(using m: M): m.type = m

def doSomething(body: M ?=> Unit) = ...

doSomething {
  val x: m.X = m.X.foo()
  ...
}
// or with an import 
doSomething {
  import m._
  val x: X = X.foo() // Consice and clear
  ...
}
// without this feature we would need an extra line in each call site
doSomething {
  // not ideal
  val myM = m // or summon[M] 
  import myM._
  val x: X = X.foo()
}


def f(using M)(x: m.X) = m.X.foo()
```

**Comment by odersky** [comment]
@nicolasstucki Can `m` be an inline function?

**Comment by abgruszecki** [comment]
Note that the way this is used in reflection API as follows:

```
   def qctx(using qctx: QuoteContext): qctx.type = qctx
   …
   def f(using QuoteContext)(tree: qctx.reflect.Tree): qctx.reflect.Position
```

It's also possible to use `qctx as a singleton type:

```
  def f(using QuoteContext): qctx.type = qctx
```

To an extent, I'm fine with this being an idiom. It'd feel less like a hack if `qctx` was required to be an `inline def` - it's _somewhat_ unexpected that `qctx.type` isn't actually the type of `qctx`. If we come to the conclusion that we want to support this, I think we should be explicit about that in the docs (of either `given/using` or `inline`) and we should have tests for both of the above.

**Comment by nicolasstucki** [comment]
We also do the same with `ctx` in the compiler.

**Comment by nicolasstucki** [comment]
Also for [`summon`](https://github.com/lampepfl/dotty/blob/master/library/src/dotty/DottyPredef.scala#L74) which is `inline`.
