### ISSUE TITLE
misleading info regarding windows installation

### ISSUE THREAD

**Issue by amitport** [lampepfl/dotty#10300]
Currently, in the ["getting started" guide](https://dotty.epfl.ch/#getting-started) it says:

> If you are a Linux or **Windows** user, download the latest release. Optionally add path of the folder bin/ to the system environment variable PATH.
> 
> Now you can compile Scala source code:
> `scalac hello.scala`

This does not seem to be the case. On windows, it seems that one needs to setup bash (and JAVA_HOME set to ???<=JDK<=13) (I know, it seems trivial to scala developers, but, the instructions are annoying for someone who hasn't used it in a while and just want to checkout dotty/scala3 as a new language)

**Comment by michelou** [comment]
@amitport This is indeed not the case. Currently the Scala 3 distribution doesn't provide batch commands to Windows users. For now I suggest you to follow one of the two paths :
- *the short path* : install the following [batch files](https://github.com/michelou/dotty-examples/tree/master/bin/3.0.0) into the `bin\` directory of your Scala 3 installation.
- *the long path* : read my GitHub page [Running and building Scala 3 on Windows](https://github.com/michelou/dotty-examples).

**Comment by amitport** [comment]
Hey, thanks, I'm running on wsl and it's working fine. I just posted this issue because I feel that the documention should reflect the current situation more clearly.

**Comment by b-studios** [comment]
Does the explanation provided on this page work better for you?

https://docs.scala-lang.org/scala3/getting-started.html

If yes, then we could "backport" the explanations to the old dotty.epfl.ch page.

**Comment by amitport** [comment]
@b-studios I think it's still missing parts about running with bash environment or the bat scripts in https://github.com/michelou/dotty-examples/tree/master/bin/3.0.0

(I haven't tried to install again recently, I'm not really developing anything in scala 3 just experimented with it at the time, and back then I used WSL to make it work)

**Comment by b-studios** [comment]
@amitport I would have assumed that the missing bat scripts are taken care of by coursier?  Sadly, I do not have a windows installation available where I could test this appropriately.

**Comment by b-studios** [comment]
@amitport I updated the landing page in #11032 to mention that we recommend some bash-like environment. I think at the current point this is easier then also asking to install the necessary scripts. What do you think?

**Comment by amitport** [comment]
Looks much better. It's important that it doesn't hide the complexity involved. Thank's, can be closed IMO
