### ISSUE TITLE
Scala3doc: extension methods are not grouped properly

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#10329]
See https://scala3doc.virtuslab.com/pr-master/scala3/api/scala/opaques/array-ops/index.html.

Grouping extensions was based on positions. Since we implemented it, the implementation of extension methods was changed, so perhaps that is where the problem is?

**Comment by odersky** [comment]
The grouping should be based on the position of the leading parameter section. The leading parameter is the first parameter, except for right-associative methods, where it is the second parameter. See method `extensionParam` in SymDenotations.scala.

The compiler also has code that depends on the grouping. See `isLocalExtensionMethodRef` in Typer.scala.

**Comment by pikinier20** [comment]
@abgruszecki Prevoiously we were groupping by position, but I see that currently we are groupping by DRI of extended symbol (which changed recently)  which is not quite good, because in `arrayOps` extensions on `IArray[ConcreteType]` are groupped in our docs. I'm gonna make a fix for this.

**Comment by abgruszecki** [comment]
Reopening, the issues is still there.

**Comment by abgruszecki** [comment]
Correction: there's no bug on Scala3doc side, it merely duplicates the original source structure (which has a separate `extension` clause for each definition). My bad.
