### ISSUE TITLE
Infinity loop on compileIncremental stage after switching to 3.0.0-M1

### ISSUE THREAD

**Issue by catap** [lampepfl/dotty#10345]
I'm switching one project to 3.0.0-M1 from 0.27.0-RC1.

The steps:
 1. update sbt plugin from `0.4.2` to `0.4.6`
 2. update scala version from `0.27.0-RC1` to `3.0.0-M1`

After the first step everything is fine, but when I switched to `3.0.0-M1` sbt is stuck on `compileIncremental` phase.

This project compiles for dozen of seconds, like 10-15, so I start panic after a few minutes of `compileIncremental`.

I've attached a few pictures from attached JProfile to show where it is looping.

![Screenshot 2020-11-16 at 16 42 49](https://user-images.githubusercontent.com/37775/99274617-d7408780-282a-11eb-9630-043d0120eb21.png)

![Screenshot 2020-11-16 at 16 42 56](https://user-images.githubusercontent.com/37775/99274637-dc9dd200-282a-11eb-82ec-6748d17db0b0.png)

**Comment by bishabosha** [comment]
Hello, please may you try and find the smallest set of code that triggers this issue and update this issue with the code

**Comment by odersky** [comment]
That stacktrace looks familiar... I think it is already fixed by https://github.com/lampepfl/dotty/pull/10271.

@catap Would it be possible to try this with the current nightly?

**Comment by catap** [comment]
@odersky yes and testing a night-build is much better idea than start to cutting a lot of code to discover that is broking the compiler.

**Comment by odersky** [comment]
Do you by any chance have union types with many alternatives? That's what borke in the other issue.

**Comment by catap** [comment]
@odersky this is code that is cross compiling to 2.11, 2.12, 2.13 and now 3.0.0/0.27, so, not any union types or new features from scala3.

And I'd like to confirm that `3.0.0-M2-bin-20201115-3c04f9b-NIGHTLY` is fixing the issue.

**Comment by catap** [comment]
At my case it is triggered by creation a a field inside an `BytesStream` that looks like:
```
val DESERIALIZERS: Map[BytesStream.Kind, DeserializableBytesStream[_ <: SerializableBytesStream]] = Map(
...
)
```

`BytesStream.Kind` is type for `Enumeration.Value` and each value at the map is object at the same package like:
```
object XXX extends DeserializableBytesStream[XXX] {
 ....
 override val bytesStreamKind: BytesStream.Kind = BytesStream.Kinds.XXX
}
``` 

Yes, `XXX` is the same name of object and enum's value.

If the map has 20 or more elements, it is triggered infinity loop.
