### ISSUE TITLE
Undefined behaviour for inline match

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#10374]
## Minimized code

This is rather minor issue, but I am not sure how should I treat a situation like this:

```Scala
    val kind = ""
    def inline(a : String) = a + "1"
    inline(kind) match {
      case x: String => (x, x)
      case x: Double => x
    }

```

## Output

`inline match can only be used in an inline method`

## Expectation

("1", "1")

**Comment by bishabosha** [comment]
I don't think theres much to do here except escape `inline` before the match

**Comment by abgruszecki** [comment]
We had a similar issue with `extension` some time ago. If we really wanted to, we could try to add some hacks to the parser to make the above work, but IIRC it wasn't clear if the gain was worth it. Like @bishabosha says, if we wrap `inline(kind)` in parentheses the code should compile.

Perhaps we could just explicitly mention that in the error message, something like "if inline match is not what you intended, consider wrapping the scrutinee in parentheses" perhaps?

**Comment by tgodzik** [comment]
The only problem I see is when beginning user gets that error message and they have no idea what inline is, which is an advanced concept. Advanced concepts should not interfere with a basic usage of the language. The problem here is much smaller than in case of `extension`, but it would be good to explicitly decide what should happen in this case. 

And really this is a problem only in case of inline matches.

**Comment by odersky** [comment]
If a Scala developer does not know what the keywords in Scala are, there are going to be surprises, inevitably. I'd like to see someone actually tripping up over this, in which case we should revisit this issue.
