### ISSUE TITLE
Templates using `dotty` name need to be updated to `scala3`

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10387]
We still have the `dotty` name in [dotty-example-project](https://github.com/lampepfl/dotty-example-project), [dotty.g8](https://github.com/lampepfl/dotty.g8), [dotty-cross.g8](https://github.com/lampepfl/dotty-cross.g8), [dotty-staging.g8](https://github.com/lampepfl/dotty-staging.g8) and [dotty-tasty-inspector.g8](https://github.com/lampepfl/dotty-tasty-inspector.g8).

They should be named `scala3-example-project`, `scala3.g8`, `scala3-cross.g8`, `scala3-staging.g8` and `scala3-tasty-inspector.g8`.

Not sure if we can rename the projects without breaking the previous links. If we can't rename we can just create copies with the new names.

**Comment by SethTisue** [comment]
You are welcome to move them to the scala organization on GitHub, if you like.

**Comment by anatoliykmetyuk** [comment]
"I don't have permission to create public repos on `scala`", so it won't allow me to move.

**Comment by anatoliykmetyuk** [comment]
Repos renamed. `sbt new` resolves old names correctly to the new names. Old links are also resolved correctly. I'll move them to `scala` upon the availability of permissions.

**Comment by SethTisue** [comment]
I just added you to https://github.com/orgs/scala/teams/admins/members , so I think you should now have the permissions you need.

**Comment by anatoliykmetyuk** [comment]
Accepted the invite, still the same error.

**Comment by nicolasstucki** [comment]
@anatoliykmetyuk did you rename those in the docs as well?

**Comment by SethTisue** [comment]
@anatoliykmetyuk try again, I granted you "owner" access via https://github.com/orgs/scala/people

**Comment by nicolasstucki** [comment]
@anatoliykmetyuk you will also need to update Travis as it stoped running tests due to the name change

**Comment by anatoliykmetyuk** [comment]
It worked, thanks @SethTisue.
@nicolasstucki yep, need to do that all as well. I hope I'll find some time on Friday.
