### ISSUE TITLE
Remove `TupledFunction` from the library of `3.0`?

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10411]
Should we remove `TupledFunction` from the library of `3.0`? We used to have methods that depended on it in `scala.quoted` but we removed them to improve error messages.

https://github.com/lampepfl/dotty/blob/master/docs/docs/reference/other-new-features/tupled-function.md

This feature could be added in a `3.1` or later.

**Comment by liufengyun** [comment]
If it can be added later, it might be preferable to do so --- better to be late and have a solution based on a better understanding of concrete need.

**Comment by nicolasstucki** [comment]
Removed in #10416
