### ISSUE TITLE
Rename `Eql` to `CanEqual`

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#10415]
`Eql` is a typeclass used in multi-versal equality to check that regular universal equality `==` is allowed. I believe therefore that `CanEqual` is a better name. That way, we do not raise the expectation that this is some sort of equality typeclass. And we avoid confusion and possible nameclashes if oneone we want to introduce an equality typeclass ourselves.

**Comment by sjrd** [comment]
This probably deserves a Contributors post, this late. Or at least tagging library maintainers who may have a skin in that game?

**Comment by odersky** [comment]
No code in the community build seems to have used this yet.
