### ISSUE TITLE
reduce name collisions

### ISSUE THREAD

**Issue by aappddeevv** [lampepfl/dotty#10425]
## Minimized example

```Scala
trait Props extends js.Object { var basename: js.UndefOr[String] = js.undefined }

def basename(bname: js.UndefOr[String], children: ReactNode*) =
   createElement(JS, new Props { basename = bname }, children: _*)
```

## Output

```sh
 [error] |Reference to basename is ambiguous
```

## Expectation
Expectation is that this error should only occur if the name collision is because the name can be assigned to. Otherwise, it should assume that `basename` belongs to the data structure.

**Comment by prolativ** [comment]
Minimized without external dependencies:

```scala
trait Props { var basename: String = "" }
def basename(bname: String) = new Props { basename = bname }
```
@smarter do we want this to work without `thisbasename = bname`? You mentioned on gitter that dotty had got somehow stricter in such cases compared to scala2.

**Comment by smarter** [comment]
Yes, we're intentional stricter since https://github.com/lampepfl/dotty/pull/8622, but it's possible we could still get this example to work since only one of the two `basename` in scope are setters.

**Comment by odersky** [comment]
I'd rather not complicate the pec with fine-grained distinctions like that.

**Comment by som-snytt** [comment]
Worth adding that named args used to cope with similar ambiguity, but in the end opted for stricter syntax because it's easier to read.

Alternatively, the compiler could ship with a special plugin that enables puzzlers.
