### ISSUE TITLE
scala.reflect.Manifest is not synthesized by typer

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1042]
```
class ArrayBuffer[T: Manifest] {}
val a = new ArrayBuffer[Int]()

benchmark/Benchmark.scala:73: error: no implicit argument of type
 scala.reflect.Manifest[Int] found for parameter evidence$1
 of constructor ArrayBuffer in class ArrayBuffer
```

**Comment by sjrd** [comment]
The question is: do we care?

Manifests have been deprecated since 2.10. Hopefully we can remove them in scalac even before dotty becomes standard/mainstream/etc.

**Comment by smarter** [comment]
Manifest haven't died in scalac yet, but there's no plan to implement in Dotty.
