### ISSUE TITLE
Remove old CLA check

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10424]
We replaced the CLA check with a GitHub workflow but we still need to remove the old CLA check. Currently, all PRs stay with incomplete checks.

**Comment by sjrd** [comment]
OK, I think I did it.

**Comment by nicolasstucki** [comment]
It seems to be working. What did you do?

**Comment by sjrd** [comment]
I went to Settings | Branches | Edit for `master` | uncheck "CLA" and check the new one called "check".
