### ISSUE TITLE
Relativiaze pickled source paths based on rootsource

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10430]
We should relativize all source paths to the `sourceroot` as we did in  #10385.
We are missing this in [PositionPickler.scala#L63](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/tasty/PositionPickler.scala#L63) where we always use the `cwd`.

**Comment by sjrd** [comment]
What's `sourceroot` exactly? In general, source files often come from *several* "root" source directories. For example `src/main/scala` and `src/main/scala-3`.

**Comment by liufengyun** [comment]
> What's `sourceroot` exactly? In general, source files often come from _several_ "root" source directories. For example `src/main/scala` and `src/main/scala-3`.

From the code, the default value is the current working directory of the compilation process:

```Scala
  val sourceroot: Setting[String] = PathSetting("-sourceroot", "Specify workspace root directory.", ".")
```

**Comment by sjrd** [comment]
In that case, it's not very useful as a base to relativize source file names. We should have a different option for that. In sbt it should be filled in by default with the contents of `(TheConfig / sourceDirectories).value`.

**Comment by liufengyun** [comment]
> In that case, it's not very useful as a base to relativize source file names.

IIUC, currently the main motivation to relativize the path is to address the concern about _privacy_.

When the tasty is read, no assumptions can be made about the path: the reference point (`sourceroot`) is unknown, and even it's known, the source may not exist.

It seems to me that having _one reference point_ (instead of multiple reference points) makes potential tools that take advantage of the relative paths easier. @sjrd Could you elaborate a little more about your point below?

> In that case, it's not very useful as a base to relativize source file names. We should have a different option for that. In sbt it should be filled in by default with the contents of (TheConfig / sourceDirectories).value.

**Comment by sjrd** [comment]
When you consume TASTy from somewhere else, you're most likely consuming it from a .jar. That .jar can have an associated *source jar*. And sources will be stored in the stored jar as relativized to the entries in `sourceDirectories`. Therefore, if you also relativize the paths in TASTy wrt. the entries in `sourceDirectories`, tools will be able to reliably relate to the sources in the source jars.

**Comment by liufengyun** [comment]
> When you consume TASTy from somewhere else, you're most likely consuming it from a .jar. That .jar can have an associated _source jar_. And sources will be stored in the stored jar as relativized to the entries in `sourceDirectories`. Therefore, if you also relativize the paths in TASTy wrt. the entries in `sourceDirectories`, tools will be able to reliably relate to the sources in the source jars.

Thanks for the explanation. There seems to be one inconvenience with multiple reference points:

```
src/root1/util.scala
src/root2/util.scala
``` 

If we have both `src/root1` and `src/root2` as reference points, we will lose the ability to distinguish the two files.

**Comment by sjrd** [comment]
Yes. You shouldn't do that anyway, because they will erase each other in source jars.

**Comment by liufengyun** [comment]
> Yes. You shouldn't do that anyway, because they will erase each other in source jars.

For the compiler, it has no concept of source jars. That means for the compiler to handle it properly, it has to check the multiple reference points for potential conflicts. That seems to complicate the compiler unnecessarily.

**Comment by liufengyun** [comment]
A bit of more context about `-sourceroot`, it's added in [4a3071f](https://github.com/lampepfl/dotty/pull/7379/commits/4a3071f38298dcd5fb0a7a80af134e04e308699b) to generate relative paths for SemanticDB usage in IDE.

I'm still digging how scala2 handles relative path.

**Comment by liufengyun** [comment]
In a private conversation, @sjrd explained that the _multiple reference points scheme_ in Scala source jars dates back to java source jars.

In Scala2, it stores only the file name, and the tools seem to have no problem with source jars. If that is the case, we don't have to worry too much about the tools, as with the _single reference point scheme_, it contains more information to correlate the path in source jars than in Scala 2. This way, we can avoid pushing the complexity to the compiler.

/cc: @romanowski @tgodzik @bishabosha  Are you aware of any special needs that the _single reference point scheme_ fails to satisfy but are not a problem in Scala2? Thanks.

**Comment by romanowski** [comment]
Scala3doc defines yet another similar setting called `-sourcepath` that is used map source to its location within the repository.
```  
-doc-source-url <url>                       A URL pattern used to link to the source file, with some variables supported: 
For example, for `scala.collection.Seq` €{TPL_NAME} gives `Seq`, €{TPL_OWNER} gives `scala.collection`, €{FILE_PATH} gives `scala/collection/Seq`, €{FILE_EXT} gives `.scala`, €{FILE_PATH_EXT} gives `scala/collection/Seq.scala`, and €{FILE_LINE} gives `25` (without the backquotes). 
To obtain a relative path for €{FILE_PATH} and €{FILE_PATH_EXT} instead of an absolute one, use the -sourcepath setting.
```

This leaves us with 2 slightly different settings one that will provide relative paths within source jar (`-sourceroot`) and another to provide relative path within repository (`-sourcepath', doctool specific).

if we aim to use *single reference point scheme* it should have a semantic similar to `-sourcepath` otherwise representing a project with e.g. generated sources may be really problematic (often `target` directory in sbt is not placed withn `baseDirectory` for given sbt project and e.g. generated sources are placed there)

**Comment by liufengyun** [comment]
Thanks @romanowski .

> This leaves us with 2 slightly different settings one that will provide relative paths within source jar (-sourceroot) and another to provide relative path within repository (`-sourcepath', doctool specific).

Currently, the default value for the Dotty compiler option `-sourceroot` is relative to the repository root (`.`):

- It aligns with the semantics of `-sourcepath` used in the doc tool
- It aligns with the usage of relative path in semanticDB (4a3071f )

Indeed, it helps a lot for tools that add links to source files in git repositories a lot.

**Comment by liufengyun** [comment]
> Scala3doc defines yet another similar setting called -sourcepath that is used map source to its location within the repository.

@romanowski I couldn't find the option `-sourcepath` in scala3doc, could you please give me a pointer?  In Dotty, there is also a `-sourcepath` option in `ScalaSettings.scala`, but I think you don't mean that one.

**Comment by romanowski** [comment]
> I couldn't find the option -sourcepath in scala3doc,

It is not implemented yet, for now (similar to compiler) we are using CWD instead.

**Comment by liufengyun** [comment]
> > I couldn't find the option -sourcepath in scala3doc,
> 
> It is not implemented yet, for now we are using CWD instead.

Thanks, I see. Is it possibble to reuse the compiler option `-sourceroot`,  since they have the same semantic, and the same default value (the repository root directory)?

**Comment by tgodzik** [comment]
`sourceroot` is mostly used for semanticdb, which does't really deal with jars, but does need to be able to find files within a workspace. Essentially there might be different files that would have the same package.name, but would go to different jars, so we do need to have the full relative path. It might be better to use a separate setting here and relativize from source roots.

**Comment by tgodzik** [comment]
Essentially what I am trying to say is that we could reuse sourceroot and just set it to the actual `main/src` and Metals should be able to work with that really. We would only need to change Bloop's behaviour.

**Comment by tgodzik** [comment]
Although, since we can have multiple source directories I am not sure how we could set it properly. Or we would need indeed a new setting like `sources-roots`

**Comment by liufengyun** [comment]
> EDIT: although we could just use different target roots also, so it is possible to change semanticdb's behaviour to have different sourceroots for each configuration. Might actually not influence any current functionality.

Thanks for the clarification @tgodzik . I think it's better to keep the single reference point scheme (the same as in SemanticDB), as it's conceptually and technically much simpler.

As mentioned by @romanowski , the single reference point scheme makes features like links to GitHub repo file much simpler.

The potential inconvenience is about source jars. I don't know how Scala2 solves the problem, since it only stores file names, not relative path. We are in a better situation than Scala2 in this respect.

> Although, since we can have multiple source directories I am not sure how we could set it properly. Or we would need indeed a new setting like `sources-roots`

Will metals work fine if we only have a single `-sourceroot`, which is set to the root of the workspace? I'm curious about how metals handle Scala2 source jars, given that the symbols there only contain file name (not relative path).

**Comment by tgodzik** [comment]
> Will metals work fine if we only have a single -sourceroot, which is set to the root of the workspace? I'm curious about how metals handle Scala2 source jars, given that the symbols there only contain file name (not relative path).

That's how it works currently, we relativize based on the workspace root and then read semanticdb from `targetroot/relative-path`. That's both Scala 3 and 2. We do not read semanticdb files from jars, so that's not a problem.

**Comment by liufengyun** [comment]
> That's how it works currently, we relativize based on the workspace root and then read semanticdb from targetroot/relative-path. That's both Scala 3 and 2. We do not read semanticdb files from jars, so that's not a problem.

If metals is going to support jumping to a library definition by using source jars. Conceptually, are there any difficulties in implementing the feature in Scala2?

**Comment by tgodzik** [comment]
We infer the actual path from the package structure, so it's not at all related to sourceroot. The only problem is the java modules, which currently only work for JDK

**Comment by liufengyun** [comment]
> We infer the actual path from the package structure, so it's not at all related to sourceroot. The only problem is the java modules, which currently only work for JDK

Thanks a lot for the explanation, it's very helpful. Then I suggest we go foward with the _single reference point_ scheme:

- it is much simpler to support features such as links to git repo in scala doc tools
- it is much simpler than the _multiple reference point_ scheme, conceptually and implementation-wise
- source jars is not an issue as explained by @tgodzik above (and we are in a better situation than Scala2)
- consistency with scala doc tool setting & semanticDB setting

WDYT @sjrd @nicolasstucki @romanowski @tgodzik ?

**Comment by sjrd** [comment]
If tools are OK with this, I'm OK with it.

**Comment by romanowski** [comment]
I am also fine.
