### ISSUE TITLE
Should @infix and @mixin be soft modifiers?

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#10446]
The question is what kind of effects we want an annotation to have. I did a survey of existing Scala annotations to find out. There emerge two broad categories:

 1. tighten or relax error checking or warnings, or customize error messages

     - Scala 2
       ```
        @compiletimeOnly  @implicitAmbiguous   @implicitNotFound   @nowarn   @showAsInfix  
        @switch   @tailrec   @unused   @uncheckedStable  @uncheckedVariance   @deprecated... 
        @unchecked 
       ```
    - Scala 3 additions
      ```
      @constructorOnly
      ```

 2. influence code generation and run-time behavior

    - Scala 2
       ```
        @elidable   @strictfp    @specialized   @unspecialized   @varargs   @inline  @noinline 
        @native  @throws   @transient   @volatile
      ```

     - Scala 3 additions
       ```
       @main   @static   @targetName  @threadUnsafe
       ```

There are only two annotatiions that do not fit into this categorization. 

   - @infix  Changes the way a method can be used
   - @mixin  Changes the way types are inferred

I believe it is a good idea to have clear guidelines what annotations can and cannot do, and to keep to these guidelines in our own distribution. Otherwise we'll risk a "broken window" effect where soon enough annotations are free to change or influence anything so that no categorization is possible anymore. This will be particularly important to set expectations what an eventual annotation macro design should accomplish. 

With that in mind there's a good case to be made to make `infix` and `mixin` soft modifiers instead. I can't really see a downside to doing this. But we have to do it quickly, before we release Scala 3.

**Comment by arturopala** [comment]
What's a difference between annotation and code modifier? If the presence of an annotation can affect validity of the code and result of its tests, then it is clearly a modifier, not mere annotation.

**Comment by som-snytt** [comment]
Is there a word for an effect that is "surfaced in the language" or "is fundamental to correctness" and is not an implementation detail or due to interop? I would also distinguish `@volatile` and perhaps `@strictfp` from the second category on that basis.

If my third-party compiler fails to `@inline` or `@nowarn`, I can still reason about correctness. If it doesn't emit deprecation warnings, that's OK, I probably would have ignored them anyway.

In contrast, "validity of the code" and test results may depend on runtime features that are implementation details, such as specialization. So "validity" can be construed in a broad sense or narrowly. But I don't know the word for this narrow sense, in which, if I write a program using `@volatile`, then I also rely on it for correctness; it is not merely "supplemental."

**Comment by odersky** [comment]
Here's a more fine-grained categorization:

 1. tighten or relax error checking or warnings, or customize error messages

     - Restrict the way certain constructs are used or written
       ```
        @compiletimeOnly  @switch   @tailrec   @constructorOnly
       ```
       @compileTimeOnly is different from the others since it affects the public API. Hopefully @compileTimeOnly will at some point be retired and replaces  by `erased`.

    -  Assert a property without checking, suppress error checks:
       ```
       @unchecked  @uncheckedStable  @uncheckedVariance  
       ```

    -  Customize error messages or warnings
       ```
        @implicitAmbiguous   @implicitNotFound   @nowarn   @showAsInfix  @unused   @deprecated... 
       ```

 2. influence code generation and run-time behavior

    - Influence runtime behavior in an observable way
       ```
       @strictfp  @transient   @volatile   @threadUnsafe   @elidable  
      ```
    - Optimization hints or directives; should not be observable
      ```
      @specialized   @unspecialized   @inline  @noinline 
      ```
    - Tailor embedding in host environment and interoperability
      ```
        @varargs   @native  @throws   @main   @static   @targetName  
      ```

**Comment by sjrd** [comment]
Can we please keep the discussion in one place? I suggest to keep it in Contributors.

**Comment by odersky** [comment]
OK. I'll copy my comment there.

**Comment by anatoliykmetyuk** [comment]
> Can we please keep the discussion in one place? I suggest to keep it in Contributors.
> OK. I'll copy my comment there.

Does that mean we can close this issue?

**Comment by odersky** [comment]
Resolution: @mixin is renamed to `transparent`, `infix` is now a soft modifier.

**Comment by SethTisue** [comment]
Discourse thread was https://contributors.scala-lang.org/t/should-infix-and-mixin-be-soft-modifiers/4651
