### ISSUE TITLE
Qualified private is not simply private

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#10440]
## Minimized code

```Scala
➜  snips ~/scala3-3.0.0-M1/bin/scala
Starting scala3 REPL...
scala> class C { private[C] def f = 42 }
// defined class C

scala> class D extends C { override def f = 17 }
// defined class D

scala> D().f
val res0: Int = 17

scala>
```

## Output in Scala 2

```scala
Welcome to Scala 2.13.3 (OpenJDK 64-Bit Server VM, Java 11.0.7).
Type in expressions for evaluation. Or try :help.

scala> class C { private[C] def f = 42 }
class C

scala> class D extends C { override def f = 17 }
                                        ^
       error: method f overrides nothing

scala>
```

## Expectation

Although qualified private is dicey, we expect qualified private to immediately enclosing class to be exactly the same as private to immediately enclosing class, private tout court.

This is extracted from https://github.com/scala/bug/issues/2568.

An alternative coping mechanism might be a warning and Scalafix for "redundant qualified private".

This gibes with removing `private[this]`; possibly `private[C]` where C is the immediately enclosing class should be disallowed.

**Comment by odersky** [comment]
> Although qualified private is dicey, we expect qualified private to immediately enclosing class to be exactly the same as private to immediately enclosing class, private tout court.

I contest that. They are not the same. You can only make them the same by making qualified private to the immediately enclosing class fundamentally different from qualified private to an outer class. And that's clearly undesirable. 

In fact, qualified private to the immediately enclosing class is pretty useless. We could forbid it. But then, why spend the effort of detecting that case if nobody sane would actually write it, and it's just another annoying rule we have to add to the spec?

**Comment by som-snytt** [comment]
> They are not the same.

I don't understand why; I thought it was just syntax; later, I will spend some time with the spec and googling old threads.

> fundamentally different ... And that's clearly undesirable.

I'm missing something obvious, so I'll spend more time with qualified private. This is like that math textbook expression, "It is obvious that...", which, when it is not obvious, suggests you re-read the previous material.

> We could forbid it.

The use case would be that you start with an inner class and refactor so that the `private[C]` is redundant.

As a lint, it need not be in the spec, but just a "style" check. (Note to self.)

> nobody sane would actually write it

OK, I'll cop to that.

**Comment by som-snytt** [comment]
@sjrd Special thanks for that insight. It qualifies down as well as up. There doesn't seem to be an emoji for mind blown? 🤯 OK, I thought that was Hannibal Lecter victim. Some of the renderings of this emoji look more like the Pillsbury Doughboy.

**Comment by som-snytt** [comment]
The spec language for inheritance changed in https://github.com/scala/scala/pull/4512
