### ISSUE TITLE
opaque types and boxing

### ISSUE THREAD

**Issue by amsayk** [lampepfl/dotty#10443]
I noticed an unexpected boxing inconsistency when using opaque. Not sure if this is a bug.

## Code 1: opaque types box

```Scala
object types {
  
  opaque type Positive = Int
  
  def tag(i: Int): Positive = i
}


@main def main = 
  println(types.tag(3).getClass) // class java.lang.Integer
  println(Seq(types.tag(3))(0).getClass) // class java.lang.Integer

  def funOpaque(i: types.Positive) = println(i.getClass)

  funOpaque(types.tag(10)) // class java.lang.Integer

  def funInt(i: Int) = println(i.getClass)

  funInt(10) // int


```

## Output 1

```scala
class java.lang.Integer
class java.lang.Integer
class java.lang.Integer
int
```

## Code 2: tagged opaque types don't box (except as function arguments)

```scala

object types {
  
  opaque type Positive = Int
  
  def tag(i: Int): Int & Positive = i // tagging with Int changes boxing
}


@main def main = 
  println(types.tag(3).getClass) // int
  println(Seq(types.tag(3))(0).getClass) // int

  def funOpaque(i: types.Positive) = println(i.getClass)

  funOpaque(types.tag(10)) // class java.lang.Integer

  def funInt(i: Int) = println(i.getClass)

  funInt(10) // int


```

## Output 2

```scala
int
int
class java.lang.Integer
int
```

## Expectation

In both cases, we'd expect the following:

```scala
int
int
int
int
```

**Comment by sjrd** [comment]
Using `getClass` is not an appropriate way to determine whether something boxes or not. `getClass` should always return the boxed class for primitives. For historical reasons, it returns the primitive type if it knows `statically` that the receiver is one of the primitive types. In a world where `getClass` always did the right thing, all your examples would print `java.lang.Integer`.

To determine whether something boxes, you have to look at the bytecode. There, you will see that the opposite type alias boxes exactly in the places as `Int`.

Also, replace Ints by Strings on your snippets, and you'll see `java.lang.String` everywhere.

**Comment by amsayk** [comment]
Thanks @sjrd. I learned something new about boxing. I will closed this.
