### ISSUE TITLE
Website pages 404, the links broken.

### ISSUE THREAD

**Issue by counter2015** [lampepfl/dotty#10465]
In the website

https://dotty.epfl.ch/docs/reference/new-types/intersection-types.html

The bottom link `More detail` should link to spec reference, but it will return 404.

The correct page is store at `https://dotty.epfl.ch/docs/reference/new-types/intersection-types-spec.html` 

However, the link is `http://dotty.epfl.ch/docs/reference/new-types/intersection-types-spec.md`

https://github.com/lampepfl/dotty/blob/master/docs/docs/reference/new-types/intersection-types.md#L69

The same is true for other spec pages.

Here are part of result from https://www.drlinkcheck.com/

![image](https://user-images.githubusercontent.com/13608862/100046868-159dfe00-2e4c-11eb-90e0-8b55d9cc4a08.png)

I'm afraid all links which ends with "md" have this problem

BTW: Two weeks ago, the link is correct , that is, ends with "html", it seems a recent change about doc generation cause it.

**Comment by abgruszecki** [comment]
@counter2015 Thanks for raising the issue! We'll be taking a look shortly.

**Comment by romanowski** [comment]
The fix can be tested [here](https://scala3doc.virtuslab.com/pr-10470/scala3/docs/reference/new-types/intersection-types.html?query=Intersection%20Types)

**Comment by griggt** [comment]
The fixes are now live at https://dotty.epfl.ch

**Comment by counter2015** [comment]
The most of links fixed, but there still have some broken links.

`super traits` in https://dotty.epfl.ch/docs/reference/enums/desugarEnums.html which link to 
https://dotty.epfl.ch/docs/reference/other-new-features/mixin-traits.md is broken.

`Given Instances` in https://dotty.epfl.ch/docs/reference/features-classification.html which link to 
https://dotty.epfl.ch/docs/reference/contextual/delegates.md is broken.

`Given Clauses` in https://dotty.epfl.ch/docs/reference/features-classification.html which link to 
https://dotty.epfl.ch/docs/reference/contextual/given-clauses.md is broken.

**Comment by griggt** [comment]
Thanks for re-checking!  Those links actually seem to be broken in the source documents.

**Comment by romanowski** [comment]
@b-studios is checking, fixing and reorganaizing documentation so those links should be fixed in future.

**Comment by nicolasstucki** [comment]
To detect regressions on this, we could revive https://github.com/nicolasstucki/dotty-website-linkcheck
