### ISSUE TITLE
Ycheck that all methods have either MethodicType or PolyType(MethodicType)

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1046]

**Comment by liufengyun** [comment]
I just checked, it seems that methods without `()` may not take a `MethodType`:


- `def test() = id(5)` takes following type:

```
MethodType(List(), List(), TypeRef(ThisType(TypeRef(NoPrefix,scala)),Int))
```

- `def test = id(5)` takes following type:

```
ExprType(TypeRef(ThisType(TypeRef(NoPrefix,scala)),Int))
```

So if I understand well, the check need to make an exception for methods like `def test = id(5)`?

**Comment by DarkDimius** [comment]
Isn't `ExprType` a `MethodicType`?

**Comment by liufengyun** [comment]
Yes for `MethodicType`, I was thinking to check for `MethodType`. Thanks for clarification.
