### ISSUE TITLE
cats-effect-* is broken in the community build after bump to 3.0.0-RC1

### ISSUE THREAD

**Issue by griggt** [lampepfl/dotty#10478]
Looks  like a flaw in the build files somewhere, I have not looked further

```
Error:  scala.MatchError: 3.0.0-RC1-bin-SNAPSHOT (of class java.lang.String)
Error:  Use 'last' for the full log.
Error:  Test dotty.communitybuild.CommunityBuildTestB.catsEffect2 failed
```

**Comment by griggt** [comment]
It seems as if the bug is in the `sbt-spiewak` plugin.  Should we just disable these two projects in the CB until it's fixed?

`3.0.0-RC1-bin-SNAPSHOT` isn't handled by:

https://github.com/djspiewak/sbt-spiewak/blob/c438ee9552d0382b4ef14eb9d13011cc0dc208e7/core/src/main/scala/sbtspiewak/FullScalaVersion.scala#L20-L47

**Comment by griggt** [comment]
Daniel kindly cut a new  `0.18.1` release of `sbt-spiewak` containing a fix, however it's built with sbt 1.4.x (as are all versions >= 0.16.0)

@smarter are there still blockers on updating the build to use sbt 1.4?

**Comment by anatoliykmetyuk** [comment]
Currently, we are a bit overloaded by the final push for RC1. So far dropping Cats is the easiest solution FTTB. If there are indeed blockers for 1.4, bump to 1.4 before RC1 would unlikely be a priority. External help and PRs are always welcome ;)

**Comment by smarter** [comment]
I'm working on the 1.4 upgrade.

**Comment by smarter** [comment]
I took care of the 1.4 upgrade but I don't plan to work on restoring cats-effect in the community build, @anatoliykmetyuk is still the maintainer of the community build.

**Comment by griggt** [comment]
I've opened https://github.com/dotty-staging/cats-effect/pull/2 to demonstrate the change needed to permit re-enabling cats-effect-2 in the community build.  It's as simple as updating the version of the sbt-spiewak-sonatype plugin.  The same can be done for cats-effect-3.

**Comment by smarter** [comment]
Sounds good to me, but if we can we might as well update cats-effect-2/3 to the latest upstream which should already have the updated plugins. If you want to give it a try I've given you write access to dotty-staging.

**Comment by griggt** [comment]
Sure.  Upstream has moved to using Dotty built artifacts for most of its dependencies (cats-core, cats-laws, discipline-munit), which aren't (yet) in the community build.  I don't think we want to take on adding all of those projects right now, so they'll just get the `withDottyCompat` treatment.

**Comment by smarter** [comment]
Ah that might complicate things, we should look into adding these projects in our build (cats especially would be very useful) though if withDottyCompat works that's ok for now too.
