### ISSUE TITLE
Scala3doc not generating documentation for vals

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10481]
None of the `val`s (such as [val Literal](https://github.com/lampepfl/dotty/blob/master/library/src/scala/quoted/Quotes.scala#L615)) appear in the docs http://dotty.epfl.ch/-scala%203/-a-p-i/scala/quoted/-quotes/-reflection.html.

**Comment by bishabosha** [comment]
@nicolasstucki It seems there is a tab for Value members where you'll find it

**Comment by nicolasstucki** [comment]
Oh, indeed

**Comment by abgruszecki** [comment]
@nicolasstucki is there some other problem, or can we close this issue then?

**Comment by nicolasstucki** [comment]
We can close it.
