### ISSUE TITLE
Tasty could not load type and object pair if type is defined in package object

### ISSUE THREAD

**Issue by romanowski** [lampepfl/dotty#10499]
## Minimized code

```Scala
package example

// Ala fails Ola does not
package object typeAndObjects:
  type Ala

package typeAndObjects {
  object Ala
}

type Ola
object Ola
```

## Output

To reproduce run `scala3doc/generateTestcasesDocumentation` on [this commit](https://github.com/romanowski/dotty/tree/tasty/packageObjectProblem).

Scala3doc will fail with:

```
class example.typeAndObjects.Ala cannot be unpickled because no class file was found
```

This construct is used e.g. in zio (IO class) and prevents `scala3doc` in documenting it.

## Expectation

Tasy should be loaded without a failure

**Comment by bishabosha** [comment]
compiling this code and then trying to use `scalac -decompile example/typeAndObjects/Ala.tasty` fails with the same error
