### ISSUE TITLE
Improve `using` parameter docs generation

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10525]
The current issues with `using` parameters are
 * We print the synthetic name
 * We do not print `using`

```scala
extension [T](self: Expr[T]):
  def unlift(using Unliftable[T]): Option[T] = ...
```
https://github.com/lampepfl/dotty/blob/master/library/src/scala/quoted/Quotes.scala#L41

<img width="468" alt="Screenshot 2020-11-27 at 09 31 58" src="https://user-images.githubusercontent.com/3648029/100427889-6d7a7600-3093-11eb-9517-c8f4eadd5268.png">

**Comment by abgruszecki** [comment]
Already fixed, result can be seen here: http://dotty.epfl.ch/api/scala/quoted/Quotes.html.
