### ISSUE TITLE
Missing line break at `-Yindent-colons` gives off the wrong error

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#10536]
## Minimized code

```Scala
  def times(num : Int)(block : => Unit) : Unit = ()
  times(10): println("ah")
```

## Output

```
Term-dependent types are experimental,
they must be enabled with a `experimental.dependent` language import or setting
```

## Expectation
It would be cool if a line break would not be required, but if indeed it does, the error message is wrong.

**Comment by LPTK** [comment]
I don't think the error is wrong. A colon followed by code is a type ascription, and the code is treated like a type.

What would be cool is to have a way to avoid using braces and parens other than `:`. For instance, using `@` as in:

```scala
times(10) @ println("ah")

times(10) @
  println("ah")

xs.map @ x =>
  println(x)
  x + 1
```

If it's right-associative (as it probably should), we could even write:

```scala
times(10) @ println @ "ah"
```
