### ISSUE TITLE
Remove language.experimental.dependent parser support or move it under a flag

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#10546]
Right now If I write:
```scala
def foo: Set(Int) = Set(1)
```
I get:
```scala
1 |def foo: Set(Int) = Set(1)
  |         ^^^^^^^
  |Term-dependent types are experimental,
  |they must be enabled with a `experimental.dependent` language import or setting
```
And then if I enable the feature I get:
```scala
-- Error: try/foo.scala:1:9 ----------------------------------------------------
1 |def foo: Set(Int) = Set(1)
  |         ^^^^^^^
  |         Not yet implemented: T(...)
```
This confuses users and send them down the wrong path when they just accidentally used parens instead of brackets. Given that this feature is not anywhere close to being implemented I propose simply removing it from the parser, or keeping it under a -Y flag if we don't want to delete the code,.

**Comment by soronpo** [comment]
Also see issue #10536 that suffers from the same confusing error message
