### ISSUE TITLE
Can I create a "given" instance in a "for comprehension"?

### ISSUE THREAD

**Issue by bilal-fazlani** [lampepfl/dotty#10545]
Is it possible to create a given instance inside a for comprehension and use it as well. 

For example

```scala
for {
  t <- token()
  given x <- abc(t)
  c <- ghj() //uses x
  g <- yh() // uses x
}
yield g
```

**Comment by amsayk** [comment]
This is possible. See section *Pattern-Bound Given Instances* here: https://dotty.epfl.ch/docs/reference/contextual/givens.html

However, I think the best place to ask questions like this is on the Contributors forum: https://contributors.scala-lang.org/

**Comment by smarter** [comment]
Yes, this is an issue tracker, not a user forum.

**Comment by bilal-fazlani** [comment]
Thank you
