### ISSUE TITLE
Missing `soft-modifier` section in References

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10562]
<img width="302" alt="Screenshot 2020-11-30 at 17 17 23" src="https://user-images.githubusercontent.com/3648029/100634794-03cac800-3330-11eb-9233-9280292bacdd.png">

<img width="274" alt="Screenshot 2020-11-30 at 17 18 16" src="https://user-images.githubusercontent.com/3648029/100634833-10e7b700-3330-11eb-8e13-e5229bf7e6c8.png">

http://dotty.epfl.ch/docs/reference/soft-modifier.html

**Comment by romanowski** [comment]
Dotty documentation uses [`sidebar.yaml`](https://github.com/lampepfl/dotty/blob/master/docs/sidebar.yml#L119-L153) to define what ends up on the left so `soft-modifier.md` should be added there as well.
