### ISSUE TITLE
Property handling in enum is confusing

### ISSUE THREAD

**Issue by amsayk** [lampepfl/dotty#10585]
The behavior of an enum property is different based on where it is defined.

## Property defined on enum constructor is not accessible as a field

```scala

enum HttpStatusCode(code: Int): // code is not a field since val is not used
  case OK extends HttpStatusCode(200)
  case NotModified extends HttpStatusCode(304)
  case Forbidden extends HttpStatusCode(404)

extension (s: HttpStatusCode) def isSuccess = s.code >= 200 && s.code < 300 // error: value code cannot be accessed as a member of (s : HttpStatusCode) 

```

## But a property defined on a case constructor is considered a field

```Scala

enum Opt[+T]:
  case Some(x: T)
  case None()

extension [T](opt: Opt.Some[T]) def printSome = println(opt.x) // ok x is a field even though no val

```

I find this a little surprising. It makes enum more similar to plain classes than to case classes.

## Expectation

The two should be the same. `code` should be accessible field even though it is not defined as a `val`

**Comment by bishabosha** [comment]
@odersky should primary constructor arguments of the base class become public fields of an enum?

**Comment by b-studios** [comment]
@bishabosha Yes, I think it is consistent with the declaration of parameters on the individual cases (as this issue illustrates). As a user, when working with enums, I do not want to think about classes and fields, but more about ADTs. Information hiding (that is, not making it a public field) is an aspect that I would consider when explicitly working with traits and classes.

**Comment by odersky** [comment]
I am in the no camp here. 

 1. Less rules to specify. 
 2. We can already make it a field, just add a `val`
 3. We might not want to retain the field; it could be some private info.

So, I think fields should be restricted to case classes and cases only.

**Comment by sjrd** [comment]
I'll add to @odersky's answer: the parameters to the `case` have no choice but to be public, since they are the ones being extracted via pattern matching. The same cannot be said for the parameters to the `enum`, which cannot be extracted via pattern matching, and hence don't have to be public.
