### ISSUE TITLE
Support @ _* syntax under -language:Scala2

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1059]
Dotty requires `x : _*` syntax for repeated types, though scala required `xs @ _*`.
It would be good to add support for old syntax under compatibility flag and issue a warning.
Also see https://github.com/lampepfl/dotty/issues/1048

**Comment by liufengyun** [comment]
@DarkDimius I'd like to work on this issue.

To be clear, scala supports both `xs @ _*` and `_*`, so we need to support both in dotty as well, or just `xs @ _*`?
