### ISSUE TITLE
Incorrect "no implicit view" error message when an implicit of a subtype of => is missing

### ISSUE THREAD

**Issue by neko-kai** [lampepfl/dotty#10603]
## Minimized code

```Scala
scala> implicitly[List[Boolean]]
1 |implicitly[List[Boolean]]
  |                         ^
  |                         No implicit view available from Int => Boolean.
```

## Expectation

Expected an error like

```
no implicit argument of type List[Boolean] was found for parameter e of method implicitly in object Predef
```

**Comment by prolativ** [comment]
That's because `Function1` is defined like this
```
@annotation.implicitNotFound(msg = "No implicit view available from ${T1} => ${R}.")
trait Function1[@specialized(Specializable.Arg) -T1, @specialized(Specializable.Return) +R] ...
```
As `implicitNotFound` annotation is by design inherited by subclasses, `List` is annotated with this message as well. As in scala 3 functions will not work as implicit conversions anymore (unless with `-source:3.0-migration` flag) it makes sense to get rid of this message. However we can't really modify the definition of `Function1` because it's a part of stdlib, which is defined in scala 2.13.
The solution that comes to my mind might be a bit dirty but seems quite simple. We could make `Function1` a special case while propagating `implicitNotFound` annotation to subclasses. That should be a one-liner. @smarter what do you think?

**Comment by smarter** [comment]
> e. We could make Function1 a special case while propagating implicitNotFound annotation to subclasses. 

Sounds good to me. We could even ignore that annotation when calling implicitNotFound on Function1 itself.

**Comment by neko-kai** [comment]
Scala 2 does print the message, but also prints the precise type alongside it in this case:
```
scala> implicitly[List[Int]]
                 ^
       error: could not find implicit value for parameter e: List[Int] (No implicit view available from Int => Int.)
```

**Comment by prolativ** [comment]
@neko-kai it looks like in scala 3 in general the default error message for a missing implicit is not printed when a specific message is provided via an annotation.
@smarter should this be changed only when not using `-source:3.0-migration` or always?

**Comment by smarter** [comment]
> it looks like in scala 3 in general the default error message for a missing implicit is not printed when a specific message is provided via an annotation.

Hmm, maybe we should match what Scala 2 does since people wrote their implicitNotFound message with this in mind.

> should this be changed only when not using -source:3.0-migration or always?

As you wish, it's not a big deal to not care about the migration mode here I'd say.

**Comment by prolativ** [comment]
Actually it looks like in scala 2 the behaviour depends on whether the annotation is placed directly on the type we want to summon or on its supertype! But messages are never combined if you annotate a parameter of a method (and this at least seems to be consistent with `implicitNotFound`'s documentation)
```
scala> implicitly[List[String]]
                 ^
       error: could not find implicit value for parameter e: List[String] (No implicit view available from Int => String.)

scala> implicitly[Int => String]
                 ^
       error: No implicit view available from Int => String.

scala> def foo[A](implicit @annotation.implicitNotFound("Custom error") a: A) = {}
def foo[A](implicit a: A): Unit

scala> foo[List[String]]
          ^
       error: Custom error

scala> foo[Int => String]
          ^
       error: Custom error
```
So showing always just one message seems somehow more consistent. Also I've always thought that one of the points of allowing people to define their custom message for when an implicit of their type was not found was to get rid of this default message as the custom one should be more informative.

**Comment by smarter** [comment]
OK, sounds good.
