### ISSUE TITLE
Naming a class Con crashes/loops the compiler on Windows

### ISSUE THREAD

**Issue by Sporarum** [lampepfl/dotty#10610]
When running sbt from the windows 10 command line, compiling code that contains a class named by a windows reserved keyword (Aux, Con, ...)  the compiler either crashes with the log below, or keeps running forever and refuses to be stopped with `ctrl + C`.

## Minimized code

```Scala
class Con
```

## Output

if crashes:
```
[error] java.nio.file.FileSystemException: E:\Documents\EPFL\1stSemesterMaster\Godel_Recursivity\PrimRec\target\scala-3.0.0-M2\classes\Con.tasty: Fonction incorrecte.
[error] 
[error] 	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
[error] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[error] 	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[error] 	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
[error] 	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
[error] 	at java.nio.file.Files.newOutputStream(Files.java:216)
[error] 	at dotty.tools.io.File.outputStream(File.scala:56)
.
.
.
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (Compile / compileIncremental) java.nio.file.FileSystemException: E:\Documents\EPFL\1stSemesterMaster\Godel_Recursivity\PrimRec\target\scala-3.0.0-M2\classes\Con.tasty: Fonction incorrecte.
[error] Total time: 8 s, completed 2 déc. 2020 16:42:33
```
full log [here](https://pastebin.com/QcTE5ePv)

if loops:
```
[Warn] Canceling execution...

  | => root / Compile / compileIncremental 552s
```

## Expectation
The class name should be valid as it conforms to the [Scala Syntax](http://dotty.epfl.ch/docs/internals/syntax.html?query=Scala%20Syntax%20Summary).

## Specs
Windows 10 Professional
Version: 1903
OS Version: 18362.1082

command: `sbt` -> `compile` or `sbt compile`
or compilation from inside Metals (never crashed, always looped)

build.sbt:
```scala
val dottyVersion = "3.0.0-M2"

lazy val root = project
  .in(file("."))
  .settings(
    name := "dotty-simple",
    version := "0.1.0",

    scalaVersion := dottyVersion,

    libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % "test"
  )

```

**Comment by som-snytt** [comment]
https://github.com/scala/bug/issues/220

**Comment by abgruszecki** [comment]
Thanks for raising the issue, @Sporarum.

This is (as the PR linked by @som-snytt explains) due to `con` being a magickal filename on Windows.

**Comment by smarter** [comment]
Yep, nothing we can do except maybe warn if we emit a filename that is known to be invalid on Windows, but someone would have to come up with a list of those.

**Comment by Sporarum** [comment]
@smarter Wouldn't it be possible to rename invalid filenames ?
(for example hashing the file and postfixing the hash to the filename: `con` -> `con_<hash>` )

The list seems to be this one:
"Do not use the following reserved names for the name of a file:
CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9."
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN

**Comment by smarter** [comment]
>  (for example hashing the file and postfixing the hash to the filename: con -> con_<hash> )

No, on the JVM the name of the class must match the name of the classfile.

**Comment by som-snytt** [comment]
This is similar to class names that different only in case, which may not be supported by the file system.

A workaround is to compile to a jar file, `-d out.jar`. I don't know if anyone bothers to do that, or if sbt has a happy path.
