### ISSUE TITLE
Represent `summonFrom` using a partial function

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10624]
Try to represent summonFrom in the compiler as as `summonFrom(x => x match { case ... })`.

This would mean that we would not have a special kind of `Match` tree in TASTy to represent it and we could remove `reflect.SummonFrom`.

**Comment by abgruszecki** [comment]
During the meeting, I had the impression we aren't going to do this. Do we want to keep this issue around?

**Comment by nicolasstucki** [comment]
Indeed. I wanted to confirm that tomorrow before closing it.

**Comment by nicolasstucki** [comment]
We will keep the current representation in TASTy and in the reflection API.
