### ISSUE TITLE
`<empty>` listed in docs

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10649]
http://dotty.epfl.ch/api/index.html is listing `<empty>` as a package. We should filter that one out.

<img width="426" alt="Screenshot 2020-12-04 at 13 01 42" src="https://user-images.githubusercontent.com/3648029/101161374-dd0ed900-3630-11eb-830b-729e2aae2b24.png">

**Comment by abgruszecki** [comment]
@romanowski Can we just skip packages that have no members? We probably want that anyway, and implementing that would fix this problem as well.

I'm not 100% certain if we don't ever want to display the magick `<empty>` package, since it can contain classes.

**Comment by nicolasstucki** [comment]
We should probably flatten the contents of `<empty>` into the root package.

**Comment by romanowski** [comment]
`<empty>` was introduced by dokka. The fix for now (that is also valid) is to remove all packages that does not have any members . See #10688

**Comment by abgruszecki** [comment]
Was fixed in #10688.
