### ISSUE TITLE
Wrong link to docs from main web page

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#10642]
When at https://dotty.epfl.ch/index.html clicking `Docs` in the top right corner of the screen does not open the docs page

**Comment by nicolasstucki** [comment]
The docs can be accessed directly at http://dotty.epfl.ch/docs/

**Comment by prolativ** [comment]
Yes but you need to know the link first. I guess it's not the case for people who would like to just get started with the language

**Comment by nicolasstucki** [comment]
I just meant it as a workaround while it gets fixed
