### ISSUE TITLE
Typeclass derivation can't be defined outside of the companion object

### ISSUE THREAD

**Issue by jto** [lampepfl/dotty#10674]
*Not sure if this is a bug or a feature tbh, but the current behavior is rather odd to me anyway...*

When defining TC derivation in a project cross-built for Scala 2 and 3, the definition of a typeclass may live in a shared src folder while the implementations of derivations for each Scala version are declared in separate src. 

In the following example, we declare a typeclass `MyTC` and its companion object extends a trait `TCDerivation` that implements the derivations. 

The actual definition of `TCDerivation` is different for Scala 2 (macros) and Scala 3 (TC derivation). 
Sadly in that case the derivation fails.

## Minimized code
```Scala
// In shared srcs
trait MyTC[T] {
   // whatever
}
object MyTC extends TCDerivation {
    implicit def stringTC = new MyTC[String]{}
}

// In scala 2 srcs
trait TCDerivation {
    implicit def derived[T]: MyTC[T] = ??? // magnolia OR macro impl
}

// In scala 3 srcs {
trait TCDerivation {
    inline implicit def derived[T <: Product](implicit m: Mirror.Of[T]): MyTC[T] = {
      inline m match {
        case p: Mirror.ProductOf[T] =>
          summonAll[p.MirroredElemTypes] 
          // ...
      }
    }
}

// Test in REPL
case class Foo(s: String)
MyTC.derived[Foo]
```

## Output

```scala
cannot reduce summonFrom with patterns :  case t @ _:String
```

## Expectation

The derivation should work

What seems to happens is that `p.MirroredElemTypes` will be `String *: EmptyTuple` instead of `MyTC[String] *: EmptyTuple`

**Comment by jto** [comment]
It's possible to workaround the issue by replacing `summonAll` by this:

```scala
inline def summonAllF[F[_], T <: Tuple]: Widen[T] = {
    val res =
      inline erasedValue[T] match {
        case _: EmptyTuple => EmptyTuple
        case _: (t *: ts) => summonInline[F[t]] *: summonAllF[F, ts]
      }
    res.asInstanceOf[Widen[T]]
  }
```

**Comment by bishabosha** [comment]
Hi, would you mind supplying the definition of `summonAll` in the original post? it would help to understand the issue

**Comment by jto** [comment]
I just used the one from `scala.compiletime`: https://github.com/lampepfl/dotty/blob/master/library/src/scala/compiletime/package.scala#L144-L151

**Comment by bishabosha** [comment]
@jto thank you for your answer, I thought it might be. If you were following the documentation for Type Class Derivation then they define their own `summonAll` which is similar to the 'workaround' you posted:
```scala
inline def summonAll[T <: Tuple]: List[Eq[_]] = inline erasedValue[T] match {
  case _: EmptyTuple => Nil
  case _: (t *: ts) => summonInline[Eq[t]] :: summonAll[ts]
}
```

I was confused myself reading that in the documentation so it should probably be renamed there to not confuse with the library function

**Comment by jto** [comment]
ooohhhhh ok makes sense!
 We'll I suppose I should have read the doc a little more carefully the documentation might benefit from being a little more explicit about this (use a different function name ?).

Thanks! Feels free to close the issue 👍
