### ISSUE TITLE
decide on final context function syntax

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10697]
## Minimized code

The following are both valid, I believe we should be removing the form with `using` clause based on #10487

```Scala
val f = (using x: Int) => x
val g = (x: Int) ?=> x
```

## Expectation

Only `val g = (x: Int) ?=> x` should work

**Comment by b-studios** [comment]
For what it's worth, #10484 is the issue containing the discussion of switching back to the operator style.
