### ISSUE TITLE
Selftype on package object not in scope

### ISSUE THREAD

**Issue by b-studios** [lampepfl/dotty#10704]
Arguably, this is not a big issue since package objects are deprecated.

## Minimized code

```Scala
package object foo { self =>
  trait B {
    type X = self.B
  }
}
```

## Output

```scala
[error] 68 |    type X = self.B
[error]    |             ^^^^
[error]    |             Not found: self
```

## Expectation
Code should type check or report that self-types are not allowed on package objects.

Note that replacing `self.B` with `foo.B` does type check.

**Comment by odersky** [comment]
It works with normal objects. I think there's not a lot of appetite to try to fix this given that package objects go away.
