### ISSUE TITLE
Ambiguous overload using JDK 11

### ISSUE THREAD

**Issue by noti0na1** [lampepfl/dotty#10715]
## Minimized code

The following code can be compiled using JDK 8. However, it will output ambiguous overload error when using JDK 11.

Environment: 
Ubuntu
openjdk 1.8.0_275
openjdk 11.0.9.1

```Scala
val decoderOut = java.nio.CharBuffer.allocate(1000)
val p = decoderOut.position
```

## Output

```scala
-- [E051] Reference Error: Stest.scala:7:19 ------------------------------------
7 |val p = decoderOut.position
  |        ^^^^^^^^^^^^^^^^^^^
  |Ambiguous overload. The overloaded alternatives of method position in class CharBuffer with types
  | (x$0: Int): java.nio.CharBuffer
  | (): Int
  |both match expected type <?>
```

## Expectation

The compiler shoud find and use `position(): Int` here.

**Comment by som-snytt** [comment]
Same in Scala 2, as the non-nullary method is overridden for more specific return type. Workaround:
```
Starting scala3 REPL...
scala> val decoderOut: java.nio.Buffer = java.nio.CharBuffer.allocate(5)
val decoderOut: java.nio.Buffer =

scala> val p = decoderOut.position
val p: Int = 0
```
or just use parens.

**Comment by liufengyun** [comment]
It can also be done with an explicit `()`:

```Scala
val p = decoderOut.position()
```

Thus, I don't think this needs a fix.

**Comment by smarter** [comment]
I'm not sure, we're supposed to support calling Java methods with `()`, and even if we can't for some reason, the error message here is not very clear.
