### ISSUE TITLE
Windows CI failure in scala3doc after merge

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#10713]
After https://github.com/lampepfl/dotty/pull/10682, we have one test failure in the full Windows CI (which is only run on merges):
> Error:  Test dotty.dokka.site.SiteGeneratationTest.basicTest failed: java.lang.AssertionError: Attribute href does not match for 'p a' in C:\Windows\SERVIC~1\NETWOR~1\AppData\Local\Temp\test-doc6245658558233014242\index.html (body

See https://github.com/lampepfl/dotty/runs/1516615563

**Comment by romanowski** [comment]
I think that #10719 should fix the problem however to test properly I would need to either merge the PR or change CI.

**Comment by abgruszecki** [comment]
Closing since the PR was merged.
