### ISSUE TITLE
test_sbt broken in CI: Synthetic apply in private companion object

### ISSUE THREAD

**Issue by adpi2** [lampepfl/dotty#10728]
## Minimized code

```scala
// A.scala
case class A(x: Int)
private object A
```

```scala
// B.scala
object B {
  val f: Int => A = A
  f(0)
}
```

## Output

Compile successfully with a warning

```shell
> scalac A.scala B.scala
[info] running (fork) dotty.tools.dotc.Main -classpath /home/piquerez/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.4/scala-library-2.13.4.jar:/home/piquerez/lampepfl/dotty/library/../out/bootstrap/scala3-library-bootstrapped/scala-3.0.0-M3/scala3-library_3.0.0-M3-3.0.0-M3-bin-SNAPSHOT.jar B.scala A.scal
-- Warning: B.scala:2:20 -------------------------------------------------------
2 |  val f: Int => A = A
  |                    ^
  |The method `apply` is inserted. The auto insertion will be deprecated, please write `A.apply` explicitly.
1 warning found
[success] Total time: 63 s (01:03), completed Dec 9, 2020, 10:35:11 PM
```

## Expectation

It should not compile because the apply method of the private companion object should not exist

**Comment by smarter** [comment]
Private on a top-level definition means package-private in both Scala 2 and 3, so I don't think there is a bug here.

**Comment by adpi2** [comment]
Then I don't understand how this test is supposed to work: https://github.com/lampepfl/dotty/tree/master/sbt-dotty/sbt-test/source-dependencies/synthetic-companion

**Comment by adpi2** [comment]
I guess there is an issue that is badly formulated in my previous description

**Comment by smarter** [comment]
I assume this was broken by https://github.com/lampepfl/dotty/pull/7207 /cc @liufengyun

**Comment by liufengyun** [comment]
> It should not compile because the apply method of the private companion object should not exist

The method `apply` does exist, it's synthesized. I checked Scala 2.13, the synthesized `apply` exists as well. But I don't know why it reports an error.

**Comment by smarter** [comment]
Weird indeed. Anyway we can fix the test to actually directly check the subtyping relationship so it won't be influenced by whether or not A is expanded to A.apply:
```scala
object B {
  summon[A.type <:< (Int => A)]
}
```

**Comment by liufengyun** [comment]
It seems it's Scala 2 behavior is inconsistent, the following code type checks in Scala 2:

```Scala
// A.scala
case class A(x: Int)
private object A

// B.scala
object B {
  val f: Int => A = x => A(x)          // instead of `A`
  f(0)
}
```

The only difference is eta-expansion of `A` to `x => A(x)`.

**Comment by som-snytt** [comment]
Scala 2 requires `object A extends (Int => A)` for explicit companion. That was intentional with long history, or maybe there is an open ticket about what the right thing is. Now Scala 3 is the arbiter.
