### ISSUE TITLE
partest does not show error on jenkins

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#1074]
See this output on jenkins

https://scala-ci.typesafe.com/job/dotty-master-validate-partest/1049/consoleFull

We have three tests that fail (!!), but none of them shows in the error output. Instead we get a stacktrace for an unrelated test.

**Comment by retronym** [comment]
See also https://github.com/scala/scala-partest-interface/issues/15

The individual test logs are archived, e.g.

https://scala-ci.typesafe.com/job/dotty-master-validate-partest/1049/artifact/tests/partest-generated/run/t6253b-run.log/*view*/

```
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 297795584 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/jenkins/workspace/dotty-master-validate-partest@2/hs_err_pid31684.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x0000000791700000, 297795584, 0) failed; error='Cannot allocate memory' (errno=12)
```

**Comment by smarter** [comment]
The stacktrace that we do get says "cannot allocate memory" and there are 3 JVM error logs in the build artifacts that say the same thing: https://scala-ci.typesafe.com/job/dotty-master-validate-partest/1049/artifact/

**Comment by smarter** [comment]
@retronym: we do print the transcripts in Dotty if possible, I'm not sure that we can do much better when everything falls apart because there isn't enough memory

**Comment by odersky** [comment]
Ah, OK. I mentally skipped all partest related stacktraces because they are usually just noise. After @smarter pointed me to it I do see that the problem was diagnosed at the end of the run, which is fine. Closing.
