### ISSUE TITLE
irreducible match types should be type errors

### ISSUE THREAD

**Issue by tpolecat** [lampepfl/dotty#10747]
## Minimized code

```Scala
type Foo[A] = A match {
  case Int => String
}

type B = Foo[Boolean]
```

## Output

```scala
// code compiles fine
```

## Expectation

It seems to me that the concrete instantiation `Foo[Boolean]` should be an immediate type error (as happens when an invalid type argument is provided for a bounded type parameter), ideally with an explanation of the reduction failure.

More generally it should be a type error if a term somehow (by inference) ends up with a concretely-instantiated but irreducible match type. The alternative (as now) is that nonsensical types propagate and users have few tools at their disposal to figure out what happened.

I discussed this briefly with @smarter and I understand that it's complicated, but at least in the concrete case I think the compiler could be more helpful.

**Comment by OlivierBlanvillain** [comment]
Related to https://github.com/lampepfl/dotty/pull/7951
