### ISSUE TITLE
VS Code sugessts `_empty_` on `_`

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10779]
<img width="507" alt="Screenshot 2020-12-14 at 09 20 48" src="https://user-images.githubusercontent.com/3648029/102057198-d846e380-3ded-11eb-963a-2c86e753fc97.png">

* We should not suggest `_empty_`
* We might suggest `_` to complete the import

**Comment by smarter** [comment]
Does this happen with the repl too or only metals? If the latter it should go in the metals repo.

**Comment by prolativ** [comment]
I believe suggestions marked with `abc` are not based on actual semantics of code but rather on some heuristics and they don't have to make any sense. This happens especially if you have already used some identifier somewhere else in the same file but not necessarily

**Comment by nicolasstucki** [comment]
The REPL seems to be fine.
