### ISSUE TITLE
JavaParser is skipping some annotations that ClassfileParser is picking up

### ISSUE THREAD

**Issue by Kordyjan** [lampepfl/dotty#10788]
I've encountered this behavior while I was testing #10751. When `Test_1.scala` name is changed to `Test_0.scala` [here](https://github.com/lampepfl/dotty/tree/d7069242a3f2e1a967105865918f2c4d965fcf13/tests/run/repeatable), the test started failing. It seems to be caused by `JavaParser` is skipping some annotations.

**Comment by noti0na1** [comment]
Currently, the JavaParser in dotty only parses annotations without arguments. Maybe we need to port this part from scalac.

**Comment by Kordyjan** [comment]
> Maybe we need to port this part from scalac.
That is my current plan.
