### ISSUE TITLE
Have inline extension methods been dropped????

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#10796]
## Minimized code

I used to be able to do this in M2:
```scala
  inline given Functor[List]:
    extension [A, B](inline xs: List[A])
      inline def map(inline f: A => B): List[B] = xs.map(f)
```

Now it just throws an error:
```
[error] -- Error: /Users/aleiof/git/dotty_test/src/main/scala/miniquill/TypeclassExample_Functor.scala:20:21 
[error] 20 |    extension [A, B](inline xs: List[A]) {
[error]    |                     ^
[error]    |                     `inline` must be followed by an `if` or a `match`
```

PLEASE tell me this functionality has not been dropped. I have based SOOO many plans for Quill based on it!

**Comment by griggt** [comment]
I think it's just that the syntax for givens has changed since M2: https://github.com/lampepfl/dotty/pull/10538

Try:

```diff
-  inline given Functor[List]:
+  inline given Functor[List] with
```

**Comment by deusaquilus** [comment]
Yeah, that looks like it. Phew! Almost had a panic attack there...

**Comment by deusaquilus** [comment]
I'll close but maybe this is an error-message issue. With let @nicolasstucki and @liufengyun decide.
