### ISSUE TITLE
Investigate problem in ZIO's promise

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#10808]
In `Promise.scala` in `core/shared/src/main/scala/zio` we get on error in the following line:
```scala
final class Promise[E, A] private (private val state: AtomicReference[State[E, A]], blockingOn: List[Fiber.Id])
```
We have to change `State[E, A]` to `Promise.internal.State[E, A]` to make it pass. This since the new scheme for 
constructor proxies #10784. We should find out the cause and see whether we can address it.

**Comment by odersky** [comment]
Minimization:
```scala
import Promise.internal.State

class Promise(state: State)

object Promise:
  object internal:
    trait State
```
This gives:
```
-- [E046] Cyclic Error: test.scala:4:21 ----------------------------------------
4 |class Promise(state: State)
  |                     ^
  |                     Cyclic reference involving val <import>
```

**Comment by odersky** [comment]
Here's the observed completion sequence:
```
completing val <import>
  completing val Promise
  completed Promise in object Test
  completing type Promise$
    completing val <init>
    completed <init> in object Promise
add constr app object Promise
    completing type Promise
      completing val <init>
        completing val state
          completing val <import>
Cyclic reference involving! val <import>
```
So, it tries to type the import, which means it needs to complete the `Promise` object. That means we need to complete the `Promise` class since we need to know what add constructor proxies to add. Completing the `Promise` class implies typechecking the parameters, which means we need to resolve `State`, which leads to completing the import. Hence the cycle. 
It only happens if the import comes first, and if the type `State` is two levels deep in `Promise`.

It

**Comment by odersky** [comment]
The following variants work:
```scala
  import Promise.State

  class Promise(state: State)

  object Promise:
    trait State
```
and
```scala
  object Promise:
    object internal:
      trait State

  import Promise.internal.State

  class Promise(state: State)
```
and
```scala
class Promise(state: Promise.internal.State)

object Promise:
  object internal:
    trait State
```
and
```scala
object Promise:
  object internal:
    trait State

class Promise(state: Promise.internal.State)
```

**Comment by odersky** [comment]
At this point, I don't see much we can do. I tried to delay resolving the import but that caused problems in other code. So I guess we have to live with the fact that this orderings of code and imports now gives a cycle. There are of course ways in which this could have given a cycle before, for instance if `object Promise` had extended `class Promise`. This is just one more way to produce a cycle. I believe we can live with it.

**Comment by som-snytt** [comment]
FWIW, this issue feels like a recent duplicate, but I couldn't find where I saw it. The forward-reference style of import from companion is common; the idiom always feels strange to me; maybe it's worth advertising its fragility, perhaps in the error message.

**Comment by nafg** [comment]
This seems pretty bad to me. Is there no possible solution?
