### ISSUE TITLE
Follow-up on Zinc upgrade

### ISSUE THREAD

**Issue by adpi2** [lampepfl/dotty#10816]
The purpose of this issue is to track the progress on the upgrade of Zinc that follows #10607.

The current situation is:
- `scala3-compiler` depends on `"org.scala-sbt" % "compiler-interface" % "1.3.5"` and use the deprecated API
- `scala3-sbt-bridge` depends on `"org.scala-sbt" % "compiler-interface" % "1.4.3"` and contains 2 implementations: the old `xsbt.CompilerInterface` that is used by sbt `1.3.x` and Mill, and the new `dotty.tools.xsbt.CompilerBridge` that is used by sbt `1.4.x`.

The plan is to bump the version of Zinc in `scala3-compiler` and use the new API but first we need Mill and Bloop to upgrade to Zinc `1.4.3`.

- [x] Bump the version of Zinc in Mill to `1.4.3` and use the new API
- [x] Bump the version of Mill in the community build
- [x] Bump the version of Zinc in Bloop
- [x] Bump the version of Zinc in `scala3-compiler` and use the new API (waiting on #18137)
- [ ] Remove the old `xsbt.CompilerInterface`

At the end, the `scala3-compiler` won't be compatible any more with sbt `1.3.x`, Mill `0.9.x` and Bloop `1.4.x`

**Comment by adpi2** [comment]
Mill `0.9.4-15-79937c` is now using Zinc 1.4.4.

**Comment by adpi2** [comment]
Bloop migration to Zinc 1.4.x is in progress here: https://github.com/scalacenter/bloop/pull/1477

**Comment by ckipp01** [comment]
Btw @bishabosha will this also be closed by the work you've been doing with the zinc upgrade?

**Comment by bishabosha** [comment]
At least point 3 is done, not sure if we should remove the old zinc api - it would enforce a higher minimum sbt version

**Comment by armanbilge** [comment]
Another motivation for this issue: `compiler-interface` 1.3.5 depends on an old, vulnerable version of Google Protobuf. This is being flagged up in several projects using the new [sbt-dependency-submission](https://github.com/scalacenter/sbt-dependency-submission) action.

**Comment by adpi2** [comment]
The upgrade of Zinc in the compiler is almost there: https://github.com/lampepfl/dotty/pull/18137
