### ISSUE TITLE
A final var's accessors aren't final

### ISSUE THREAD

**Issue by dwijnand** [lampepfl/dotty#10835]
## Minimized code

```Scala
class A {
  final var x = 1
}
```

## Output

```
$ javap A
Compiled from "A.scala"
public class A {
  public A();
  public int x();
  public void x_$eq(int);
}
```

## Expectation

Compared to Scala 2 (2.13.4):

```
$ javap A
Compiled from "A.scala"
public class A {
  public final int x();
  public final void x_$eq(int);
  public A();
}
```

Found this while testing how well MiMa works with the Scala 3 compiler, and I don't consider it a particularly critical issue.

**Comment by odersky** [comment]
I verified that the accessors are final when they are passed into the backend.
