### ISSUE TITLE
No doc links for quoted reflection methods

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#10836]
It is currently impossible to access the documentation of methods in the reflection API. http://dotty.epfl.ch/api/scala/quoted/Quotes$reflectModule.html

For example, `TermMethods` is listed but it is impossible to follow the link and find the docs for `Term.tpe`.

**Comment by abgruszecki** [comment]
I think this is due to a name collision between terms and types, it seems the `TermMethods` trait isn't listed at all.

/cc @romanowski
