### ISSUE TITLE
How to access showExtractors in M3?

### ISSUE THREAD

**Issue by hmf** [lampepfl/dotty#10832]
## Minimized code

```Scala
  private def unsealUnderlying[T](p:Expr[T])(using t:Type[T], qctx:Quotes): Expr[T] = {
    import qctx.reflect._

    val xTree0: Term = Term.of(p)
    xTree0 match {
      case Inlined(_, _, _) =>  
        Term.of(p).underlying.asExprOf[T]
      case _ =>
        report.throwError(s"unsealUnderlying: Expected HList reference but got ${p.show} -- (${Term.of(p).showExtractors})", p)
    }
  }

  private def unsealUnderlying2[T](p:Expr[T])(using t:Type[T], qctx:Quotes): Expr[T] = {
    import qctx.reflect._

    val xTree0: Term = p.asTerm
    xTree0 match {
      case Inlined(_, _, _) =>  
        Term.of(p).underlying.asExprOf[T]
      case _ =>
        report.throwError(s"unsealUnderlying: Expected HList reference but got ${p.show} -- (${xTree0.showExtractors})", p)
    }
  }

```

## Output

```scala
[error] 132 |        report.throwError(s"unsealUnderlying: Expected HList reference but got ${p.show} -- (${Term.of(p).showExtractors})", p)
[error]     |                                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |             value showExtractors is not a member of qctx.reflect.Term
```

## Expectation

To be able to show the extractor.  I have searched the repo for `showExtractors` and only found the documentation [here](https://dotty.epfl.ch/docs/reference/metaprogramming/tasty-reflect.html#extractors). No release note so were can I find an example? 

Tested in the latest `3.0.0-M3`

TIA

**Comment by bishabosha** [comment]
I think this should work `Printer.TreeStructure.show(xTree0)`

**Comment by abgruszecki** [comment]
@bishabosha you know, the polite thing to do is to wait until the person who raised the issue confirms that what you suggest actually solves their problem before you suddenly close the issue on them.

**Comment by bishabosha** [comment]
Oops, slip of the hand, @hmf does the snippet work for you? We should check to see if the documentation still mentions anywhere how to print extractors

**Comment by hmf** [comment]
@bishabosha Yes, I have just finished testing and it works. As for the documentation I did a search in the Github web interface and it only showed the source this link:

https://dotty.epfl.ch/docs/reference/metaprogramming/tasty-reflect.html#extractors

Thank you

**Comment by bishabosha** [comment]
yes it seems that https://github.com/lampepfl/dotty/blob/master/docs/docs/reference/metaprogramming/tasty-reflect.md should be updated to replace `showExtractors` with the new printing framework

**Comment by nicolasstucki** [comment]
```diff
- tree.showExtractors
+ tree.show(using Printer.TreeStructure)
```
or 
```diff
- tree.showExtractors
+ Printer.TreeStructure.show(tree)
```
or
```diff
- tree.showExtractors
+ given Printer[Tree] = Printer.TreeStructure
+ tree.show
```

Other printers are available in the same way under `Printer`.
