### ISSUE TITLE
[warn] bad option '-Ysemanticdb' was ignored

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#10844]
## Minimized code

On a project:

```Scala
lazy val root = project
  .in(file("."))
  .settings(
    name := "dotty-simple",
    version := "0.1.0-SNAPSHOT",
    scalaVersion := dottyVersion,
    scalacOptions += "-Ysemanticdb",
    libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % "test"
  )

```

## Output

```scala
sbt:dotty-simple> compile
[info] compiling 3 Scala sources to /home/tgodzik/Documents/workspaces/dotty-sample/target/scala-3.0.0-M3/classes ...
[warn] bad option '-Ysemanticdb' was ignored
[warn] one warning found
[warn] one warning found
```

and no semanticdb files are created.

## Expectation

No warnings are produced and semanticdb files are produced.

Please do inform us about changes, that can impact Metals. This one is particularly problematic as I need to also release Bloop for a change that fixes nothing. :/

**Comment by tgodzik** [comment]
It seems that abbreviations do not work currently, that might be the issue.

**Comment by tgodzik** [comment]
The problem seems to have been reported previously https://github.com/lampepfl/dotty/issues/10844 - it's the same bug.

**Comment by dwijnand** [comment]
> previously #10844 - it's the same bug

https://github.com/lampepfl/dotty/issues/10810

**Comment by SethTisue** [comment]
10844 is indeed the same bug :-)
