### ISSUE TITLE
ScalaSettings withAbbreviation not accepted

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10845]
## Minimized code

in this line we can see that the `-Xsemanticdb` setting has an abbreviation `-Ysemanticdb`:

https://github.com/lampepfl/dotty/blob/bfb0b8194a3e96d08abf8d96f3cba8d701febc3e/compiler/src/dotty/tools/dotc/config/ScalaSettings.scala#L138

However invoking the compiler with `-Ysemanticdb` warns that is is an invalid flag and the setting is not active.

## Output

```scala
$>scalac -Ysemanticdb
bad option '-Ysemanticdb' was ignored
Usage: scalac <options> <source files>
...

```

## Expectation

passing `-Ysemanticdb` should act like `-Xsemanticdb`

linked to #10844, but is more general than that, e.g. `-classpath` has an abbreviation `-cp` that is also not accepted

**Comment by som-snytt** [comment]
https://github.com/lampepfl/dotty/issues/10810 has a smaller issue number.

**Comment by bishabosha** [comment]
Thanks for noticing
