### ISSUE TITLE
REPL packaging

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#1085]
We should make a command (I suggest `doti`) to launch the Dotty REPL.

**Comment by smarter** [comment]
What about having a `dotty` command instead which behaves similarly to `scala` ?  (Running `dotty` without arguments brings up the REPL, running `dotty Foo` runs `Foo.class` with the correct bootclasspath and classpath).

**Comment by som-snytt** [comment]
I'll take this issue for initial repl. 

I had an old scala branch that added a "scripter" phase after parser. The purpose was to allow arbitrary plugins to replace that phase, such as repl or spark repl, to wrap snippets. I took the same approach this weekend; but Frontend is monolithic, and there's not a plugin infrastructure yet, so for now Frontend is customized.

I like the name `doti` which sounds Swiss or Hindi. The previous "generic runner" says, "give me some args and I'll figure out what you want to do," like make inferring build steps from target. The only difference between `dotc` and `doti` is that `dotc` is explicit that nothing should be executed.

The lesson from spark repl is that the general form is arbitrary untyped transforms after parsing, possibly with execute jobs at the end of compilation.

**Comment by som-snytt** [comment]
The other name is `dopler` for `dotty repl`, but that's more typing than `doti`.

**Comment by smarter** [comment]
DOPPLER could be the DOtty Precise Program LinkER /cc @DarkDimius  :)

**Comment by smarter** [comment]
On the subject of running the REPL, we should also make sure that it can be run from sbt using `sbt console` and https://github.com/smarter/dotty-bridge, this require reimplementing https://github.com/sbt/sbt/blob/0.13/compile/interface/src/main/scala/xsbt/ConsoleInterface.scala and in particular this method:

```scala
def run(args: Array[String], bootClasspathString: String, classpathString: String,
  initialCommands: String, cleanupCommands: String, loader: ClassLoader,
  bindNames: Array[String], bindValues: Array[Any], log: Logger): Unit
```
which gives a good overview of the kind of things that the REPL needs to support.

**Comment by retronym** [comment]
Note that for the purposes of interactively testing out the REPL, you can use `runMain ReplClass` with a few custom settings:

```
fork in run := true

connectInput in run := true

outputStrategy in run := Some(StdoutOutput)

addCommandAlias("repl",   "repl/compile:runMain repl.Main -usejavacp")
```

See the Scala SBT build for more details.

**Comment by DarkDimius** [comment]
@retronym, thanks!

**Comment by felixmulder** [comment]
We currently have `dotr` and `dotc` for this issue. So I'm closing this issue, it might also be good to reference this issue here: #1526
