### ISSUE TITLE
How to handle overriden equals with Matchable?

### ISSUE THREAD

**Issue by joschua-fink** [lampepfl/dotty#10855]
## Minimized example

When overriding the equals method, this is a common pattern in Scala 2:

```Scala
trait Foo {
  override def equals(obj: Any): Boolean = obj match {
    case foo: Foo =>
      ???
    case _ =>
      false
  }
}
```

## Output

Using Scala 3.0.0-M3 with `-source 3.1` I get the following warning:

```scala
[warn] 14 |      case foo: Foo =>
[warn]    |                ^^^
[warn]    |                pattern selector should be an instance of Matchable,
[warn]    |                but it has unmatchable type Any instead
```

## Question

What is the alternative for this pattern? Since according to the documentation `isInstanceOf` may also be moved into Matchable, which will make the following workaround (which is basically the way it's done in Java) inviable as well:

```scala
trait Bar {
  override def equals(obj: Any): Boolean = {
    if obj.isInstanceOf[Bar] then
      val bar = obj.asInstanceOf[Bar]
      ???
    else
      false
  }
}
```

**Comment by sjrd** [comment]
Well, that is a very good question. I have no idea what to do. This could be very damaging to the `Matchable` idea.

In a new world, I'd say we should change the type of `obj` to be `Matchable`. But doing that will break all existing code, so that's not viable.

**Comment by SethTisue** [comment]
I've resorted to `obj.asInstanceOf[Matchable] match ...`

**Comment by nafg** [comment]
This might be an argument for the original approach, where instead of making Any less concrete and adding a more concrete subtype (Matchable), we leave Any with its current semantics and add a more abstract type over it (previously called Top, though I hope it would get a better name).

**Comment by odersky** [comment]
Yes, you'll need the `asInstanceOf` in this case. The compiler does the same in the code it synthesizes for case classes.

**Comment by nafg** [comment]
Another option would be to change the official signature of equals to take
a Matchable, but to special-case so that is it's defined with Any it
accepts it with a warning. It would have the same erasure anyway no?

**Comment by sjrd** [comment]
> Yes, you'll need the `asInstanceOf` in this case. The compiler does the same in the code it synthesizes for case classes:

That is really annoying, though. It sets a precedent of *requiring* users to use an `asInstanceOf` *in well-typed, idiomatic code*.

**Comment by odersky** [comment]
No, the code is not well typed. Universal `equals` is impossible to define in a safe way once you have the `Matchable` restriction. So it's only natural that we require that this is acknowledged explicitly.

**Comment by dcsobral** [comment]
Doing `case foo: Foo =>` on equality would break opaque types. `equals` could require `Any & Matchable`, in which case opaque types could not be compared with `equals` at all, `==` and `!=` could special case opaque types, perhaps.

**Comment by rjolly** [comment]
We could overload `equals` once and for all in `Matchable` like so:

```scala
trait Matchable {
  def equals(x: Any) = x match {
    case Matchable => equals(x.asInstanceOf[Matchable])
    case _: false
  }
  def equals(x: Matchable): Boolean
}
```

**Comment by LPTK** [comment]
@dcsobral `Any & Matchable` reduces to `Matchable`.

@rjolly Maybe a good stop-gap measure, though that would break virtually every code base where `equals` is defined. But it's an improvement over requiring everyone to switch to `asInstanceOf`.

Ultimately, @nafg's suggestion may be the best, moving forward. It's looking more and more like adopting parametricity needs a big, clean break from existing practices, as it does not seem possible to meaningfully migrate to parametricity incrementally.

The current `Matchable` approach, which keeps `equals` and `hashCode` in every type, falls short. While it does prevent some unsound opaque type matches, I worry that it would just add noise and get in the way of a future big, clean break for parametricity. Would `equals` and `hashCode` eventually be removed from `Any`, or would yet another top type be introduced, making the `Any`/`Matchable` duality mostly redundant?

**Comment by Jasper-M** [comment]
IMHO this is an indication that this type of change is something that requires a lot of time and experimentation to get right. And will probably also require a pretty sweeping change in how things are done in Scala (e.g. a much more typeclassy interface over all the Java stuff) in order for this to be more than just some annoying thing that most people just `asInstanceOf` into oblivion and get on with their lives.

And both of those things seem to be way out of scope at the moment.

**Comment by rjolly** [comment]
We could pre-overload `equals` in `Matchable` like so:
```scala
trait Matchable {
  override def equals(obj: Any) = {
    if obj.isInstanceOf[Matchable] then
      equals(obj.asInstanceOf[Machable])
    else
      false
  }
  def equals(obj: Matchable): Boolean
}
```

**Comment by rjolly** [comment]
I don't think people are overriding `equals` that often. Any sane Scala developer should avoid fiddling with that pre-parametric Java stuff. Actually in years of Scala development I had never noticed that the argument type is `Any` in `equals` and not `Object` aka `AnyRef` as in Java. What we should have (even maybe backported to Scala 2) is actually:
```scala
trait AnyRef {
  def equals(obj: AnyRef) = {
    if obj.isInstanceOf[AnyRef] then equals(obj.asInstanceOf[AnyRef])
    else false
  }
  def equals(obj: AnyRef): Boolean
}
```
as I suppose `equals` in `AnyVal` is special-cased anyway.

**Comment by sjrd** [comment]
> Any sane Scala developer should avoid fiddling with that pre-parametric Java stuff.

I consider myself a sane Scala developer, and I very often have to override `equals` and `hashCode` to implement structural equality on immutable structures that are not case classes.

**Comment by rjolly** [comment]
Fair enough. Then I think rewriting from `equals(obj: Any)` to `equals(obj: AnyRef)` might be one more refactor Scala 3 will have to mandate (that is, if we don't decide to just rollback the whole `Matchable` attempt).

**Comment by LPTK** [comment]
@rjolly For `BigInt(123) == 123` to be implementable (as it currently is), `equals` has to accept `Any`, not `AnyRef`.

**Comment by rjolly** [comment]
IMO it should not. In such case we should use a typeclass, namely Equiv:
```scala
import math.Ordering.BigInt.mkOrderingOps
BigInt(123) equiv 123 // true
```

**Comment by sjrd** [comment]
> IMO it should not.

Welcome to the fight against cooperative equality. 😆

**Comment by Jasper-M** [comment]
>IMO it should not. In such case we should use a typeclass, namely Equiv:
>```
>import math.Ordering.BigInt.mkOrderingOps
>BigInt(123) equiv 123 // true
>```

Which brings us back to

>And will probably also require a pretty sweeping change in how things are done in Scala (e.g. a much more typeclassy interface over all the Java stuff) in order for this to be more than just some annoying thing that most people just asInstanceOf into oblivion and get on with their lives.

**Comment by odersky** [comment]
I think we really only have two options:

 - keep Matchable, and acknowledge that this makes universal equality a little bit dubious. I.e. universal equality is forced not to distinguish between an opaque type and its underlying type. So, let's say I put `Logarithm(10)` in a universal HashMap and query for `10` I would get a hit. To acknowledge this problem, we require an explicit cast, but only in a future language version.

 - drop opaque types, and acknowledge that Scala is a weakly typed language and will remain so forever.

I believe that the arguments that you can't get to parametric types incrementally are in effect arguments that the change is impossible, forever, even if they are not intended as such.

So, I vote to close this issue. The current solution is the only thing we could have done for 3.0.

**Comment by joschua-fink** [comment]
Personally I welcome the transition to multiversal equality. I have no issue with using `asInstanceOf[Matchable]` in the equals method as long as there is some guarantee that this cast will continue to work with future changes to Any or Matchable.

**Comment by odersky** [comment]
I have added a section on universal equality to the Matchable doc page in #10861.
