### ISSUE TITLE
Case class creates an unapply method even if one is inherited in the companion object

### ISSUE THREAD

**Issue by fserre** [lampepfl/dotty#10866]
## Minimized code

```Scala
abstract class B{
  def unapply(arg:A)={println ("Unapply from B"); true}
}

case class A()

object A extends B

A() match {case A() => println("done")}
```

## Output

```scala
done
```

## Expectation
In Scala 2.13.4, the same code would have used the unapply from B instead, and would have displayed 
```scala
Unapply from B
done
```

**Comment by odersky** [comment]
I just ran this with 2.13.1 and got the case class unapply. Is there a difference in behavior between 2.13.1 and 2.13.4?
