### ISSUE TITLE
member_= not generated for private member var

### ISSUE THREAD

**Issue by elfprince13** [lampepfl/dotty#10879]
## Minimized code

```Scala
object Test {
  private var i:Int = 0
  
  def eat2(op:Int => Unit):Unit = {
    op(2)
  }
  
  def main(args:Array[String]):Unit = {
    eat2(i_=)
    Console.println(i)
  }
}
```

## Output

```scala
Not found: i_=
```

## Expectation

Program should compile and output `2`. Removing `private` or changing it to `protected` work as expected.

**Comment by griggt** [comment]
How about:

```diff
- private var i: Int = 0
+ private[Test] var i: Int = 0
```

**Comment by som-snytt** [comment]
`private[this]` in Scala 2 is inferred in Scala 3.

It's an interesting use case, whether the reference to the setter should cause it to be generated.

**Comment by elfprince13** [comment]
@griggt - `private[Test]` indeed appears to work.

@som-snytt - It's useful when recursively traversing mutable trees to allow a subtree to unlink itself from a parent (and/or from the root-holder).

**Comment by odersky** [comment]
I think we should guarantee setter generation only for non-private variables. I am not understanding why it is needed for private ones at all?

**Comment by bishabosha** [comment]
does the use case require a setter method or can the lambda use assignment directly? e.g. `eat2(i = _)`

**Comment by som-snytt** [comment]
Interestingly `f(i = _)` is not taken as named arg, as placeholder is expanded first.

**Comment by elfprince13** [comment]
> I think we should guarantee setter generation only for non-private variables.

This would be an odd place to break compatibility with Scala 2.

> I am not understanding why it is needed for private ones at all?

Here is the simplest example I can give that isn't *totally* contrived:
```Scala
import scala.annotation.tailrec

class ListNode(head:Int, private[ListNode] var _tail:ListNode = null:ListNode) {
  @tailrec final def snipBefore(before:Int, selfRef:ListNode => Unit):MList = {
    if(head == before) {
      selfRef(null)
      new MList(this)
    } else if (tail == null) {
      throw new NoSuchElementException("Empty list")
    } else {
      _tail.snipBefore(before, _tail_=)
    }
  }
  
  def tail:ListNode = _tail
  
  override def toString:String = {
    s"$head${if(tail == null){""}else{s",${_tail.toString}"}}"
  }
}

class MList(private[MList] var _root:ListNode = null:ListNode) {
  def root:ListNode = _root
  def snipBefore(before:Int):MList = {
    if(_root == null) {
      throw new NoSuchElementException("Empty list")
    } else {
      _root.snipBefore(before, _root_=)  
    }
    
  }
  
  override def toString:String = {
    s"MList(${if(root == null){""}else{_root.toString}})"
  }
}

object MList {
  def apply(elems: Int*):MList = {
    new MList(elems.reverseIterator.foldLeft(null:ListNode){
      (tail, elem) => ListNode(elem, tail)
    })
  }
}

object Test {
  def main(args:Array[String]):Unit = {
    val list = MList(1,2,3,4,5,6)
    val backList = list.snipBefore(4)
    Console.println(list)
    Console.println(backList)
  }
}
```

It's incredibly useful for implementing mutable recursive data structures where you want to:
(a) frame the recursive cases in the most natural way
(b) control the ability of outside code to perform mutation.

Basically, it can be used the same way as `&` (address-of)  in C/C++:

```C++

class ListNode {
  int head;
  ListNode *tail;

  static snipBefore(int before, ListNode **selfRef);
}

```

**Comment by odersky** [comment]
> This would be an odd place to break compatibility with Scala 2.

Not so odd considering that we never generate accessors for `private[this]` variables and `private[this]` is now inferred.

> Here is the simplest example I can give that isn't totally contrived:

I think it's acceptable to use qualified private if getters and setters are required. Otherwise we generate a lot of extra code that does nothing useful in 99.9% of the cases.
