### ISSUE TITLE
Should we check public bounds of opaque types against external API?

### ISSUE THREAD

**Issue by mbloms** [lampepfl/dotty#10887]
## Minimized code

```Scala
Starting scala3 REPL...
scala> class BoxedBoolean[T <: Boolean](val x: T)
// defined class BoxedBoolean

scala> def unboxBoolean(box: BoxedBoolean[?]): Boolean = box.x
def unboxBoolean(box: BoxedBoolean[?]): Boolean

scala> object o:
     |   opaque type Switch = Boolean
     |   def On: Switch = true
     |   def Off: Switch = false
     |   def oh(no: Switch): BoxedBoolean[Switch] = BoxedBoolean(no)
     | 
// defined object o

scala> o.oh(o.On)
1 |o.oh(o.On)
  |^
  |Type argument o.Switch does not conform to upper bound Boolean in inferred type BoxedBoolean[o.Switch]

scala> :t o.oh(o.On)
BoxedBoolean[o.Switch]

scala> :t o.oh(o.On).x
o.Switch

scala> o.oh(o.On).toString
val res0: String = BoxedBoolean@3e5c7588

scala> unboxBoolean(o.oh(o.On))
val res1: Boolean = true
```

## Expectation
A compiler error or warning that `Switch` does not conform to `T` in `BoxedBoolean[T <: Boolean]`.

I'm not sure how big of an issue this is in practice, but it is a bit weird.
The external API of a class with an opaque type alias should be type checked with the public abstract bounds when an opaque alias is passed as a type parameter to a parametric type.

**Comment by odersky** [comment]
I am not sure this can be improved over the status quo. There cannot be an error in
```scala
def oh(no: Switch): BoxedBoolean[Switch] = BoxedBoolean(no)
```
since at that point it is known that `Switch` is `Boolean`. The knowledge is lost when the inferred type of `o.oh(o.On)` is bounds-checked. One could argue that there should be no error either at this point, but that looks hard to achieve.
