### ISSUE TITLE
Marker trait or annotation added to Scala compiled classes

### ISSUE THREAD

**Issue by pjfanning** [lampepfl/dotty#10891]
Jackson-module-scala uses the ScalaSignature annotation added to classes compiled using Scala2 compiler. It is useful in this case to differentiate Java classes from Scala classes. Jackson generally expects Java classes to have getters and setters but this is not the norm in Scala. Jackson-module-scala has in the past affected users who had a mix of Java and Scala classes - but after Jackson-module-scala started only trying to handle Scala-compiled classes and letting the core Jackson-databind classes work with Java-compiled classes, these issues have been reduced.
Checking for classes that inherit from Scala Product class will cover a lot of cases, but won't cover all.
Would it be possible to support some trait or annotation that get added to all classes generated by Scala3 compiler?

**Comment by smarter** [comment]
I don't really see why this is useful, why would you treat an empty Java class `class A {}` and an empty Scala class `class A {}` differently for example?

**Comment by pjfanning** [comment]
It's not the empty class case that is affected.
Jackson has the a class called ObjectMapper, you can create an instance and you can register the ScalaModule as an optional module. When you use the ObjectMapper instance to serialize or deserialize JSON from/to classes, the core Jackson code and the jackson-module-scala code start trying to analyse the classes (mainly using Java reflection) to try to work out the correct way to bind the class to JSON.
This is done by looking at members, methods and constructors. The norms are different between Java and Scala and we see cases where users inadvertently name the members or methods in a Java class that make it look like the class is following Scala conventions.
The current jackson-module-scala code that checks for the ScalaSignature annotation has reduced these problems. In Scala3, this check will no longer work because the annotation has been removed.
I understand that this is not necessarily a big problem for the general Scala community. If adding a marker trait or annotation is a bad idea, then feel free to close this.

**Comment by smarter** [comment]
> The naming norms are different between Java and Scala and we see cases where users inadvertently name the members or methods in a Java class that make it look like the class is following Scala conventions.

But if a Java class uses the same conventions as a Scala class, why would it be treated differently?

> If adding a marker trait or annotation is a bad idea, then feel free to close this.

I'm a bit skeptical because I can't come up with a good reason for wanting to do this.

**Comment by bishabosha** [comment]
in the classfile there is an attribute `TASTY` which would be accessible with the ASM library, is there a reason it couldn't/shouldn't become an annotation?

**Comment by smarter** [comment]
Do you mean, replacing the attribute with an annotation? It's not exactly the same thing since it's only present on top-level classes and what is being asked for here is something that is present on all classes.

**Comment by bishabosha** [comment]
> Do you mean, replacing the attribute with an annotation?

sorry, yes, that was my question

> it's only present on top-level classes

Thats a very good point, so I see it would not be helpful for this issue
