### ISSUE TITLE
Does Scala3doc really need to depend on flexmark-all?

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#10903]
flexmark-all has a lot of dependencies, for dottydoc we previously stopped using flexmark-all because it made our tarballs huge for no reason (https://github.com/lampepfl/dotty/commit/921f25a76a9feb48642f5dfdc174e00e5cf761ac), but I see that scala3doc depends on it again: https://github.com/lampepfl/dotty/blob/8acc1cbfe41dd4f39287e02cf94b928fb9361187/project/Build.scala#L1552, is this actually needed?

**Comment by abgruszecki** [comment]
IIRC flexmark-all includes all possible extensions, and we don't need them all. Should be easily fixable.
