### ISSUE TITLE
Broken source links in the API docs

### ISSUE THREAD

**Issue by mwz** [lampepfl/dotty#10908]
Hello, it appears that all the source links in the API docs point to a non-existing directory on Github, e.g.:
Going to the `Quotes` trait in `scala.quoted` [here](https://dotty.epfl.ch/api/scala/quoted/Quotes.html) and clicking on the source link takes you to the `out` directory, on the `master` branch, which doesn't exist - `https://github.com/lampepfl/dotty/blob/master/out/bootstrap/stdlib-bootstrapped/scala-3.0.0-RC1/src_managed/main/dotty-library-src/scala/quoted/Quotes.scala#L14`

I think the links should instead point to the actual source files rather than an `out` directory and they should also reference the particular tag tree rather than the master branch?

**Comment by hepin1989** [comment]
Yes, I eg: https://github.com/lampepfl/dotty/blob/master/out/bootstrap/stdlib-bootstrapped/scala-3.0.0-RC1/src_managed/main/scala-library-src/scala/annotation/nowarn.scala#L34

**Comment by abgruszecki** [comment]
@romanowski I can't find the link to sources. Do we no longer support them, or did we just stop adding them for stdlib docs?

**Comment by romanowski** [comment]
@BarkingBad fixed that (including tests to detect it) in this PR: https://github.com/lampepfl/dotty/pull/12319
