### ISSUE TITLE
ListFromExpr fails when list has inline element

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#10914]
## Minimized code
(Note: Full code sample available here: https://github.com/deusaquilus/list_inline_bug)

Let's first create some objects to hold something with non-trivial content.
```Scala
case class Entity(value: String)
case class Input(ent: Entity)
case class Container(ents: List[Entity])
```

Let's make a macro that pulls out Entity from Input assuming Input was created via the standard .apply function.
```scala
  inline def container(inline c: Input):Container = ${ containerImpl('c) }
  def containerImpl(c: Expr[Input])(using Quotes): Expr[Container] =
    import quotes.reflect._
    val entExpr = c match
      case '{ Input($ent) } => ent
      case _ => report.throwError("Cannot Extract Entity from Input")
    '{ Container(List($entExpr)) }
```
Then let's make a second function to take the result of the first, pull out the entity from the container, and then do a ListFromExpr on the list. This involves writing a FromExpr for Entity:
```scala
  given FromExpr[Entity] with
    def unapply(expr: Expr[Entity])(using Quotes) = expr match
      case '{ Entity(${Expr(value)}) } => Some(Entity(value))
      case _ => None

```
... and then the actual function that will do `list.valueOrError`.
```scala
  inline def pull(inline c: Container): Entity = ${ pullImpl('c) }
  def pullImpl(c: Expr[Container])(using Quotes): Expr[Entity] =
    import quotes.reflect._
    val inputs = c match
      case '{ Container($list) } => 
        println("List Value: " + Printer.TreeStructure.show(list.asTerm))
        list.valueOrError
      case _ => report.throwError("Cannot Extract List from Container")
    '{ Entity(${Expr(inputs.head.value)}) }
```
Now let's run the application:
```scala
  def makeEnt = Entity("foo")

  inline def input = Input(makeEnt)
  inline def contained = container(input)
  inline def output = pull(contained)

  def main(args: Array[String]): Unit = {
    println( output )
  }
```

## Output
This will fail with the following error
```
[error] 16 |    println( output )
[error]    |             ^^^^^^
[error]    |Expected a known value. 
[error]    |
[error]    |The value of: scala.List.apply[io.getquill.Entity](io.getquill.Test.makeEnt)
[error]    |could not be extracted using scala.quoted.FromExpr$ListFromExpr@3b76a5b3
[error]    | This location contains code that was inlined from Dsl.scala:17
[error]    | This location contains code that was inlined from Test.scala:13
```

The source of the problem seems to be that there is an `Inlined` node in the list apply:
```scala
Apply(TypeApply(
  Select(Ident("List"), "apply"), List(Inferred())
), List(Typed(Repeated(
    List(/* Here */ Inlined(None, Nil, Ident("makeEnt"))), Inferred()), Inferred())))
```
If I change `makeEnt` into an `inline def` then the problem will go away.

## Expectation
The code should compile and return the `Entity` object.

## Repository
Repo with full code sample available here:
https://github.com/deusaquilus/list_inline_bug

**Comment by deusaquilus** [comment]
Also note that the following slight variation will also fail with the same error:
```scala
  def makeEnt = Entity("foo")

  inline def entity = makeEnt // This case breaks to
  inline def input = Input(entity)
  inline def contained = container(input)
  inline def output = pull(contained)

  def main(args: Array[String]): Unit = {
    println( output )
  }
```

**Comment by deusaquilus** [comment]
One thing to note is that I haven't managed to solve this issue when using `.asTerm.underlyingArgument.asExpr` either.

**Comment by nicolasstucki** [comment]
The code is doing exactly what it is supposed to. The issue here is trying to get the value of an `Entity` that is not represented with its constructor. The `FromExpr[Entity]` is correctly implemented as

```scala
  given FromExpr[Entity] with
    def unapply(expr: Expr[Entity])(using Quotes) = expr match
      case '{ Entity(${Expr(value)}) } => Some(Entity(value))
      case _ => None
```

but then we ask it to unapply `'{ makeEnt }` which clearly does not match `case '{ Entity(${Expr(value)}) }`. This failure to match is propagated out to the `ListFromExpr`.
