### ISSUE TITLE
Syntax highlighting for doc pages is broken / looks weird

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#10911]
For instance:

https://dotty.epfl.ch/docs/reference/contextual/givens.html
https://dotty.epfl.ch/docs/reference/contextual/extension-methods.html
https://dotty.epfl.ch/docs/reference/enums/adts.html

What syntax highlighter is used for the doc pages? The current rendering looks slightly worse than just doing nothing. What stands out is the parameter names and parentheses in bold black whereas the rest in light blue blends away. 

Also, it seems declared identifiers, all type identifiers and keywords look the same light blue color. Keywords should certainly be highlighted differently. It would also be nice to render types differently from terms.

But if we had super-trivial highlighter that only highlights keywords that would already be an improvement over the status quo.

**Comment by odersky** [comment]
Here's another beauty:

https://dotty.epfl.ch/docs/reference/contextual/type-classes.html

Everything is painted like a keyword _except_ the hard keyword `with` following a `given`! I have the impression almost all syntax highlighters are fundamentally broken since they want to be parsers but, being based on regexes, can only be tokenizers. So they make a hash of it.

**Comment by michelou** [comment]
The generated CSS file [`https://dotty.epfl.ch/css/color-brewer.css`](https://dotty.epfl.ch/css/color-brewer.css) looks bad to me.

In particular, the following class definition (`keyword`, `name`, `type`, ... share the same color) :

```css
...
.hljs-keyword,
.hljs-selector-tag,
.hljs-title,
.hljs-section,
.hljs-built_in,
.hljs-doctag,
.hljs-type,
.hljs-tag,
.hljs-name,
.hljs-selector-id,
.hljs-selector-class,
.hljs-strong {
  color: #3182bd;
}
```

is at the origin of the weired result in the first code block on page [`contextual/type-classes.html`](https://dotty.epfl.ch/docs/reference/contextual/type-classes.html) :

```html
<code class="language-scala hljs">
    <span class="hljs-class"
        <span class="hljs-keyword">trait</span> <span class="hljs-title">SemiGroup</span>[<span class="hljs-type">T</span>]:
    </span>
    ... 
</code>
```

**Comment by michelou** [comment]
@romanowski There is no improvement on the official documention website. Please close the issue AFTER the fix is visible on the page [contextual/type-classes.html](https://dotty.epfl.ch/docs/reference/contextual/type-classes.html) !

**Comment by romanowski** [comment]
@michelou sorry, it was a result of merging #10934

**Comment by abgruszecki** [comment]
That fix should've already gone live with the latest nightly build, there may be sth going wrong with that. Strangely enough, it seems like nightly succeded: https://github.com/lampepfl/dotty/runs/1620205092?check_suite_focus=true

**Comment by abgruszecki** [comment]
After a forced refresh, the fix _is_ visible in the docs: https://dotty.epfl.ch/docs/reference/contextual/type-classes.html.

Since this issue was just about differentiating between keywords, identifiers, terms and types in the code hl, I think it can be closed. We may still want to discuss how exactly code should be hl'ed, but lets do that in a separate issue.
