### ISSUE TITLE
match expression ignores inline command

### ISSUE THREAD

**Issue by antognini** [lampepfl/dotty#10919]
## Minimized code
3.0.0-M3
```
object Inline1:
  inline def foo( i:Int): Int =
    inline if i == 0 then -1 
    else Math.abs(i)

  def bar(i:Int): Int = foo(i) // as expected, fails to compile
  //                    ^^^^^^
  // Cannot reduce `inline if` because its condition is not a constant value: i.==(0)


object Inline2:
  inline def foo( i:Int): Int =
    inline i match
      case 0     => -1
      case x:Int => Math.abs(x)
  
  def bar(i:Int): Int = foo(i) // a compilation error was expected, but none is reported
```
## Expectation
inline is a command in Scala 3.0.0, not an implementation hint:
=> `def bar()` should fail in conjunction with `inline match`, as it does with `inline if`.

**Comment by odersky** [comment]
That's not how it is specified, and a lot of code relies on this behavior.

**Comment by SethTisue** [comment]
I'd like to understand this.

I don't see any wording at https://docs.scala-lang.org/scala3/reference/metaprogramming/inline.html that justifies this behavior.

What it does say is:

> If there is enough static information to unambiguously take a branch, the expression is reduced to that branch and the type of the result is taken. If not, a compile-time error is raised that reports that the match cannot be reduced.

I don't see how the behavior here is consistent with that.

**Comment by SethTisue** [comment]
There is discussion on this over at #13774

**Comment by SethTisue** [comment]
related: https://github.com/lampepfl/dotty/issues/13774 — there is some discussion there.

I think the current behavior is comprehensible, as follows. At compile time, `case 0` isn't known to match, so the compiler proceeds to the next case, which does match.

> That's not how it is specified 

I don't think https://docs.scala-lang.org/scala3/reference/metaprogramming/inline.html is at all clear on this point.

Regardless, probably better to discuss further on 13774 unless someone thinks this ticket is definitely different.
