### ISSUE TITLE
Infix types doesn't work correctly with anonymous givens

### ISSUE THREAD

**Issue by ghost** [lampepfl/dotty#10927]
`infix` types fails with `Double definition` compile error while using with `given`s.

```scala
  trait Transition[From, To]

  infix type ==>[From, To] = Transition[From, To]

  type A = A.type
  object A

  type B = B.type
  object B

  type C = C.type
  object C

  // Compiles
  given (A ==> B) = ???

  // Compile error
  given (A ==> C) = ???

  // Compiles
  given ==>[A, C] = ??? 
```

Error:
```
Double definition:
final lazy given val given_A: 
  Transition[A, B] in object bug at line 19 and
final lazy given val given_A: 
  Transition[A, C] in object bug at line 22

  given (A ==> C) = ???
```

**Comment by odersky** [comment]
That's as specified. You need to give explicit names to the givens.

**Comment by som-snytt** [comment]
It is specified that explicit names may be required.

But it is probably an oversight that the synthesized name for the value of infix type is different from the normal form.

It means given infix clashes with simple given of the argument:
```
given A = ???    // given_A
given (A Tuple2 B) = ???  // given_A
given (A, B) = ???    // given_A_B
```

https://dotty.epfl.ch/docs/reference/contextual/givens.html
https://dotty.epfl.ch/docs/reference/contextual/relationship-implicits.html#anonymous-given-instances

```
    final lazy given val given_A: X.==>[X.A, X.B] = ???
    final lazy given val given_A: X.==>[X.A, X.C] = ???
    final lazy given val given_==>_A_C: X.==>[X.A, X.C] = ???
```

**Comment by smarter** [comment]
I think that's reasonable, it sounds like the status quo makes anonymous given basically unusable for infix types, and that should be easily fixable by adding a case for `InfixOp` in https://github.com/lampepfl/dotty/blob/8fab91c1ae8237d4ceffce611fff059d969c4ae4/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L950-L962 if I'm not mistaken, but this will need to be done before 3.0 or not at all.

**Comment by odersky** [comment]
OK, I agree that the case should be added
