### ISSUE TITLE
Type inference sometimes doesn't work with union types and extension methods

### ISSUE THREAD

**Issue by IndiscriminateCoding** [lampepfl/dotty#10922]
## Minimized example

```scala
import scala.reflect.ClassTag

type Id[a] = a

/* Higher-kinded union type */
trait Is[F[_]]
trait UnionK[+R, +A]
case class Case[F[_], A](fa: F[A])(using val ct: ClassTag[F[A]]) extends UnionK[Is[F], A]

/* list-of-int OR option-of-int OR just-int */
val lst: UnionK[Is[List] | Is[Option] | Is[Id], Int] = Case(List(42, 123))

extension [F[_], R, A](x: UnionK[Is[F] | R, A])
  /* eliminate some part of a union */
  def eliminate(f: F[A] => UnionK[R, A])(using ct: ClassTag[F[A]]): UnionK[R, A] = x match
    case x @ Case(fa) if x.ct == ct => f(fa.asInstanceOf[F[A]])
    case x => x.asInstanceOf[UnionK[R, A]]

// causes "Recursion limit exceeded" without explicit type parameter passing
//val lstLength = lst.eliminate(x => Case(Some(x.length)))

// and it is not possible to specify JUST one parameter which should be enough to guide type inference
val lstLength = lst.eliminate[List, Is[Option] | Is[Id], Int](x => Case(Some(x.length)))

@main def run = println(lstLength)

```

I'm not sure if it is possible to make type inference work here without at least *some* types specified.
However, it should be enough if only `F[_]` in `eliminate` was somehow specified, which is possible in scala2 but not in dotty:
```
extension method cannot have type parameters here, all type parameters go after `extension
```
Hopefully, this case is motivating enough to consider allowing type parameters in extension methods.

**Comment by odersky** [comment]
> Hopefully, this case is motivating enough to consider allowing type parameters in extension methods.

We have firm plans to allow them. But it's a huge implementation effort to do so since after expansion you end up with curried type parameters and type parameters interspersed with value parameters. This affects a lot of parts of the type checker and other compiler components.

**Comment by abgruszecki** [comment]
@odersky do we want to keep this issue around? I'm not sure how to classify it.

**Comment by odersky** [comment]
Type parameters are now allowed, so I think we can close.
