### ISSUE TITLE
TreeMap doesn't traverse Template class

### ISSUE THREAD

**Issue by xerial** [lampepfl/dotty#10931]
## Minimized code

```Scala
val expr = '{ trait A; new A {}  }  // This code expression will produce Template expression
new TreeMap {}.transformTree(expr.asTerm)(Symbol.spliceOwner) // This code should traverse all child nodes of Template
```

## Expectation

- scala.quoted.reflect should have Template type definition
- TreeMap traverses the child nodes of Template node

Scala 3 macro should support traversing nodes inside Template node (https://github.com/lampepfl/dotty/blob/M3/compiler/src/dotty/tools/dotc/ast/Trees.scala#L784-L794), which will be generated by the code like above. Currently, TreeMap.transformTree https://github.com/lampepfl/dotty/blob/M3/library/src/scala/quoted/Quotes.scala#L3989-L3991 has no such pattern so we cannot rewrite a tree if it contains Template node.

QuotesImpl in Scala 3.0.0-M3 also has no corresponding definition for Template node: https://github.com/lampepfl/dotty/blob/M3/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala

Related: https://github.com/lampepfl/dotty-feature-requests/issues/153

**Comment by xerial** [comment]
@nicolasstucki If you need help (e.g., creating a PR for this), let me know because I'm a stakeholder of this metaprogramming feature. Looks like adding model classes for the Template node itself is not so difficult, but I'm not yet familiar with the entire code base of dotty, so I need some advice for the direction to go.

**Comment by nicolasstucki** [comment]
@xerial, the fix should be done here https://github.com/lampepfl/dotty/blob/d0491025682da0c958c9b8e85ca356d76d550583/library/src-bootstrapped/scala/quoted/Quotes.scala#L4019

The cases above show how to transform the sub-trees.

Tests can be added in `tests/run-macros/i10931` and executed with `sbt "scala3-bootstrapped/testCompilation i10931"` or `sbt "scala3-bootstrapped/testCompilation macros"`

**Comment by xerial** [comment]
@nicolasstucki I've tried to traverse ClassDef and found we can use ClassDef.parents to rewrite 

```scala
new {}
```

https://github.com/lampepfl/dotty/blob/3.0.0-RC2/compiler/src/dotty/tools/dotc/ast/tpd.scala#L336-L357

**Comment by xerial** [comment]
Traversing details of Template type definitions itself was possible, so this is not a lack of functionality. Let me close the issue.
