### ISSUE TITLE
Strange program with incorrect type ascription compiles

### ISSUE THREAD

**Issue by LPTK** [lampepfl/dotty#10943]
## Minimized code

```Scala
object T:
  class A
  val a = new A : Int
end T

@main def m =
  println(T.a)
```

This is with options:

```scala
scalacOptions ++= Seq(
  "-deprecation",
  "-encoding", "UTF-8",
  "-feature",
  "-unchecked",
  "-Yindent-colons",
  "-Ykind-projector",
  "-language:strict",
  "-source:3.1",
)
```

https://scastie.scala-lang.org/R2s6G90oTQ2ZcE6dn4ZlPg

## Output

```scala
T$A@5b61791c
```

## Expectation

Should not compile.

**Comment by odersky** [comment]
Would be good to get a solution as well! I am getting a bit tired of code obfuscation contests.

**Comment by LPTK** [comment]
TBH this came up completely by accident (I was not trying to expose a problem), in my real-world code base, and I have no idea what's going on. Seems like this is a parser bug.

**Comment by bishabosha** [comment]
this only passes for me when using `-Yindent-colons`
