### ISSUE TITLE
Type not found when reference static type in java parent class

### ISSUE THREAD

**Issue by changvvb** [lampepfl/dotty#10956]
## Minimized code

java code
```Java
abstract class Foo {
    public static final class Inner { }
}

class Bar extends Foo {
    Inner i = new Inner();
}
```

## Output
```
-- [E006] Not Found Error: Test.java:6:4 ---------------------------------------
6 |    Inner i = new Inner();
  |    ^^^^^
  |    Not found: type Inner

longer explanation available when compiling with `-explain`
1 error found
```

## Expectation
I think this should be compiled because javac compiles the code successfully.

**Comment by changvvb** [comment]
similar with https://github.com/scala/bug/issues/9111

**Comment by odersky** [comment]
This does not need fixing. Class `Inner` is static and therefore conceptually part of the companion object of `Foo`. So it is not in scope for extending classes.

**Comment by changvvb** [comment]
I understand. But java protocol buffers use this kind of code, so scala3 can not compile the java files generated by `protoc`.
https://github.com/scala/bug/issues/9111#issuecomment-501575819

**Comment by som-snytt** [comment]
So this is for java sources only.

**Comment by changvvb** [comment]
@odersky @som-snytt Though this is for java only, it indeed affects the interoperation with `protobuf-java` and some sbt plugins like https://github.com/sbt/sbt-protobuf.

**Comment by som-snytt** [comment]
The linked Scala 2 fix already prompted an issue for Scala 3

https://github.com/lampepfl/dotty/issues/6138

Link to comment in the Scala 2 fix

https://github.com/scala/scala/pull/7671/files#diff-334a019606bce49aa3cb747735d76c2c327c883f1f8f07a0dc65f072243341ebR1440

Showing fix on Scala 2 test case and similar Scala 3 error:
```
➜  sdk use scala 2.12.10

Using scala version 2.12.10 in this shell.
➜  scalac -d /tmp test/files/pos/java-inherited-type-protobuf/*a
➜  sdk use scala 2.12.2

Using scala version 2.12.2 in this shell.
➜  scalac -d /tmp test/files/pos/java-inherited-type-protobuf/*a
test/files/pos/java-inherited-type-protobuf/Test.java:8: error: GeneratedMessage.this.Builder does not take type parameters
    GeneratedMessage(Builder<?> builder) {
                     ^
one error found
➜  sdk use scala 3.0.0-M3

Using scala version 3.0.0-M3 in this shell.
➜  scalac -d /tmp test/files/pos/java-inherited-type-protobuf/*a
-- [E053] Type Error: test/files/pos/java-inherited-type-protobuf/Test.java:8:21
8 |    GeneratedMessage(Builder<?> builder) {
  |                     ^^^^^^^^^^
  |               GeneratedMessage.this.Builder does not take type parameters
```

**Comment by changvvb** [comment]
Yes, this is duplicated with #6138 but seems no plan for the issue.
