### ISSUE TITLE
Completion.completions doesn't provides declared extension functions

### ISSUE THREAD

**Issue by sellophane** [lampepfl/dotty#10989]
For the following code file
```Scala
object Foo:
  extension (s: String):
     def double = s + s
     def double2 = s + s
  end extension
end Foo
```
`Completion.completions` does not return `double` and `double2` as valid completions for `"".doub`. However, there are visible as functions without receiver  and completion for "doub" returns both`double(s: String): String` and `double2(s: String): String`.
##

## Expectation
There should be also available as extensions

**Comment by bishabosha** [comment]
Hello, this example needs more information to be actionable. For example, does the scope where you try to fetch completions `import Foo._`, otherwise the extension method is not in scope

**Comment by sellophane** [comment]
Hi, I was running this as a test for metals using `BaseCompilationSuite.check` method. The actual tests were:
```Scala
object Foo:
  extension (s: String):
    def double = s + s
    def double2 = s + s
  end extension
  dou@@ble
 end Foo
 ```
 and
 
 ```Scala
object Foo:
  extension (s: String):
    def double = s + s
    def double2 = s + s
  end extension
  "".dou@@ble
 end Foo
 ```
 with `@@` marking the place for completion

**Comment by prolativ** [comment]
@sellophane it looks like this doesn't work because you have a syntax error in your snippets: there should be no colon after `extension (s: String)`

**Comment by nicolasstucki** [comment]
Since 3.0.0-M3 collective `extension`s do not have the `:`
