### ISSUE TITLE
Reflection API missing in generated docs

### ISSUE THREAD

**Issue by b-studios** [lampepfl/dotty#10992]
The following links, linked from the macros tutorial are currently unavailable:

*  External link http://dotty.epfl.ch/api/scala/tasty/Reflection/TreeMethods.html failed: 404 No error
*  External link http://dotty.epfl.ch/api/scala/tasty/Reflection/TypeModule.html failed: 404 No error
*  External link https://dotty.epfl.ch/api/scala/tasty/Reflection.html failed: 404 No error
*  External link https://dotty.epfl.ch/api/scala/tasty/Reflection/TermMethods.html failed: 404 No error

Members like `TreeMethods` should be part of https://dotty.epfl.ch/api/scala/quoted/Quotes$reflectModule.html but are only listed without any contents.

**Comment by nicolasstucki** [comment]
A part of this is #10836

**Comment by b-studios** [comment]
Reminder: Once this is resolved, we should partially revert https://github.com/scala/docs.scala-lang/pull/1885

**Comment by pikinier20** [comment]
@b-studios Hey, could you provide links to pages where dead links are present?
I've found this site: https://docs.scala-lang.org/scala3/guides/macros/reflection.html

**Comment by nicolasstucki** [comment]
That is the page, I already opened a PR to fix the links https://github.com/scala/docs.scala-lang/pull/1895
