### ISSUE TITLE
precedence of given pattern in 'case given Boolean: String =>'

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#10993]
## Minimized code

```Scala
def foo = true match
  case given Boolean: String => ()
```

## Output

```scala
-- Error: sandbox/match/example.scala:2:7 --------------------------------------
2 |  case given Boolean: String => ()
  |       ^^^^^^^^^^^^^^^^^^^^^
  |       cannot test if value of type Boolean is a reference of class String
```

## Expectation

syntax error

- The case is parsed as `case (given_Boolean @ _: Boolean): String` which is a valid pattern but I would expect the parser to require parens
  - e.g. `case (given Boolean): String => ()`
  - `case _: Boolean: String` is a syntax error, corrected with the following: `case (_: Boolean): String`

**Comment by odersky** [comment]
When it comes to syntax the grammar to syntax.md is the ultimate aribeter. According to that grammar this is not a syntax error. 
One could make a proposal for a different grammar, but that would be a language change that should be proposed as a gature request.
