### ISSUE TITLE
bogus Mirror evidence with restricted arity

### ISSUE THREAD

**Issue by fommil** [lampepfl/dotty#11060]
## Minimized code

```scala
  type ProductOf2[A, A1, A2] = Mirror.ProductOf[A] { type MirroredElemTypes = (A1, A2) }

  case class Foo(s: String)

  def should_not_compile_for_foo[A, A1, A2](a: A)(implicit P: ProductOf2[A, A1, A2]): A = ???

  should_not_compile_for_foo(Foo("s"))
```

## Output

compiles

## Expectation

This code should not compile because the `ProductOf2` evidence (which is hardcoded to arity 2) should not exist for a `case class` of arity 1.

**Comment by mpilquist** [comment]
This might be a duplicate of https://github.com/lampepfl/dotty/issues/7380

**Comment by fommil** [comment]
yeah, look like it is.
