### ISSUE TITLE
scala3doc adds too <br>s too often in rendered comments.

### ISSUE THREAD

**Issue by romanowski** [lampepfl/dotty#11087]
For:

```scala
/**
 * A documentation for a 
 * class that I want to document.
 * 
 * I should care about line lenght and break line often in code.
 */
class ClassToDocument
```

scala2doc will add a `<br>` before `class that` and `I should care` but should add only in latter case.

**Comment by BarkingBad** [comment]
@abgruszecki should we close it? 
![obraz](https://user-images.githubusercontent.com/32793002/108839815-d495c100-75d5-11eb-84f7-2c7917a1e128.png)
![obraz](https://user-images.githubusercontent.com/32793002/108839834-d8c1de80-75d5-11eb-86a2-0e2235dd7b1b.png)

For example:
```scala
/**
 * A documentation for a
 * class that I want to document.
 *
 * Lorem ipsum dolor sit amet, consectetur
 * adipiscing elit, sed do eiusmod tempor
 * incididunt ut labore et dolore magna aliqua.
 * Ut enim ad minim veniam, quis nostrud exercitation ullamco
 * laboris nisi ut aliquip ex ea commodo consequat.
 * Duis aute irure dolor in reprehenderit in
 * voluptate velit esse cillum dolore eu fugiat
 * nulla pariatur. Excepteur sint occaecat
 * cupidatat non proident, sunt in culpa qui
 * officia deserunt mollit anim id est laborum.
 *
 * Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
 */
class ClassToDocument
```

![obraz](https://user-images.githubusercontent.com/32793002/108840115-2f2f1d00-75d6-11eb-882c-b8242203b233.png)
![obraz](https://user-images.githubusercontent.com/32793002/108840149-381fee80-75d6-11eb-81df-55ce9bcb34a9.png)

**Comment by BarkingBad** [comment]
I assume it is completely resolved since we actually never add `<br>`s unless used `\` mark at the end of the line. Otherwise everything is inside `<p>`s. If there are any problems with text formatting please reopen this.
