### ISSUE TITLE
Link children of sealed traits more prominently

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#11093]
In Scaladoc, one could see the children of sealed traits by opening "known subclasses", but this always felt a bit hidden.

Should we instead display them more prominently, perhaps in a separate tab?

**Comment by romanowski** [comment]
I am not sure about another tab but adding information if the class is sealed and mark sealed parents in Graph, Supertypes, Known subtypes should be enough.

`cluster` also sounds promising.

**Comment by pikinier20** [comment]
Also adding closed lock for every sealed member in graph would be nice. Clusters might get ugly when sb creates sealed trait and then extend it with another sealed trait etc.

**Comment by BarkingBad** [comment]
@Katrix do you have any thoughts on that?

**Comment by abgruszecki** [comment]
With the way Scala3doc works now, we wouldn't display a separate tab, just a toggle-able section. I think that still might make sense. Really, the first thing I want to see when going to a page of a class like `Option` is the list of all of its children.

**Comment by Katrix** [comment]
Maybe make the distinction between a sealed trait an an enum. For an enum they should definitively be front and center IMO. I'd still like to keep the known subtypes section though

**Comment by BarkingBad** [comment]
I made a small prototype, how do you find it?
![obraz](https://user-images.githubusercontent.com/32793002/106010090-5cf97280-60b9-11eb-89a9-911af5f9ba85.png)

**Comment by abgruszecki** [comment]
I think the locks are really noisy, visually. I think it'd look better if the lock was displayed only next to the types which are actually sealed. If we really want to display more information than that, then perhaps we should display the inheritance arrows differently when the parent is sealed?

**Comment by BarkingBad** [comment]
> only next to the types which are actually sealed

do you mean next to `trait A` and `trait B1` in our case or next to children of `trait A` and `trait B1` or next to both parent and children? Also, it can be hard to have straightforward solution to have lock next to rectangle, the easy way to achieve that is to  appended the lock to the name.

**Comment by abgruszecki** [comment]
I understand that `trait A` and `trait B1` are the ones actually defined as sealed? If yes, then I was suggesting displaying a lock next to those.

If we can only display the lock inside the box, then maybe we should just display the `sealed` keyword?

**Comment by BarkingBad** [comment]
Yes, we can, though the idea behind graph was to reduce information about the nodes to minimum, as it will expand rectangles size greatly. Will show updated version soon.

**Comment by BarkingBad** [comment]
@abgruszecki how do you like it?
![obraz](https://user-images.githubusercontent.com/32793002/106145653-17e74600-6176-11eb-93c0-b61b85914b16.png)

**Comment by abgruszecki** [comment]
@BarkingBad I think it looks fine. It even helps a bit visually that the sealed types have larger boxes, it helps distinguish them from the rest.
