### ISSUE TITLE
Implement support for negDir

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1110]
Neg tests at the moment take expected number of errors as an argument. Since https://github.com/lampepfl/dotty/pull/1106 we can optionally mark lines where errors are expected.

I propose we change all negtests to require marked lines.
This would allow to have a neg-dir instead of test-per-neg-test. This in turn would allow to simply drop a file there and will reduce number of merge conflicts.

**Comment by odersky** [comment]
+1
