### ISSUE TITLE
Finalize static site support in Scala3doc

### ISSUE THREAD

**Issue by romanowski** [lampepfl/dotty#11109]
Static site support is stable enough to generate https://dotty.epfl.ch/ however it is not ready to be used in other projects. This is an umbrella task to summarize steps to complete static site support in scala3doc.

Steps (the list is still open, those are the tasks moved from scala3doc):

- [ ] Scala3doc should bring default styles and layouts (now those are defined only for Scala 3)
- [ ] Complete support for blog (see https://github.com/lampepfl/scala3doc/issues/160)
- [ ] ...

**Comment by dwijnand** [comment]
I think this isn't the plan anymore.
