### ISSUE TITLE
Handle relative paths properly

### ISSUE THREAD

**Issue by romanowski** [lampepfl/dotty#11110]
For now we assume that cwd is set to root of repository. Also we assume that dotty produces relative paths that starts from the same root.

~We should provide a way to override cwd with a cmd line option ( and do not depend on it)~

We should add support for sourcepath settings from a compiler

**Comment by pikinier20** [comment]
@romanowski how should -sourcepath setting work?

**Comment by pikinier20** [comment]
Sourcepath setting is accepted now in both Scala compiler and Scaladoc so I think this issue should be closed
