### ISSUE TITLE
Export of class fails with "constructor proxy ... cannot be used as a value"

### ISSUE THREAD

**Issue by ellbur** [lampepfl/dotty#11128]
With Scala 3.0.0-M3

## Minimized code

A minimal example consisting of the two source files below is [on GitHub](https://github.com/ellbur/scala-3-proxy-object-bug).

### `package.scala`

```Scala
package object foo {
  export foo.bar.Bar
}
```

### `Bar.scala`

```Scala
package foo.bar

class Bar
```

## Output

    $ sbt compile
    [error] 3 |  export foo.bar.Bar
    [error]   |         ^^^^^^^
    [error]   |         constructor proxy object Bar cannot be used as a value

## Expectation

Code should compile without errors.

**Comment by ellbur** [comment]
Tested that error is the same with 353677355f (current master).

**Comment by ellbur** [comment]
As a workaround, adding a dummy `object` prevents Scala from thinking you are referring to the constructor proxy:

### `Bar.scala`

```Scala
class Bar

object Bar
```

**Comment by bishabosha** [comment]
minimised to
```scala
package foo

object Wrap {
  export foo.Bar
}

class Bar
```

**Comment by odersky** [comment]
I believe we just need another condition on line 998 of Namer.scala

```
          else if (sym.isConstructor || sym.is(ModuleClass) || sym.is(Bridge)) SKIP
```
should be `... || sym.is(ConstructorProxy)`.
