### ISSUE TITLE
Improve view of long signatures

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/dotty#11120]
This problem is with us since change of members view:
![image](https://user-images.githubusercontent.com/48246851/104577669-08d2a500-565a-11eb-997c-1b27f89fb2bf.png)
As you can see when member has long prefix (e.g. `sealed abstract` modifier) then it hides to the left.

**Comment by dylemma** [comment]
I also noticed this while I was fiddling with color theme stuff. It seems to me like the simplest solution is to give up on presenting the signatures like a "table" (i.e. trying to make the word `def` line up with each signature), though maybe there's some opposition do doing so. Another little annoyance is how the keywords hide behind the 🔗 icon. Here's a little preview of some changes I have in my working copy, LMK what you think:
![image](https://user-images.githubusercontent.com/1355958/118922503-2bc2dd80-b908-11eb-8a12-540674f782a4.png)

**Comment by pikinier20** [comment]
TBH I like the table appearance because lined up member names makes whole documentation very clear. However, the second option might look very bad with annotations being above modifiers so I'm also not a big fan. I thought about hiding modifiers at first glance and show them after click (clicked signature would look like your first version - without lineup) but I'm not really sure if this information can be hidden (maybe it's useful to somebody).

**Comment by bishabosha** [comment]
![Screenshot 2021-05-20 at 11 32 05](https://user-images.githubusercontent.com/13436592/118955545-1331e200-b95f-11eb-84b3-adfb21eed49f.png)
it looks like for scala 2 the margin is just a lot longer, but they do also skip override flag (implied by Definition Classes entry) and annotations do not show until you expand

**Comment by pikinier20** [comment]
I think it's fixed with #13317
