### ISSUE TITLE
Cannot invoke inline method of summonFrom result

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#11156]
## Minimized code

Say that we have a trait which we use to summon something that has an inline method
```Scala
trait Foo
object Foo {
  inline given DoStuff[Foo] with {
    inline def stuff(input: Int): String = "foo:" + input
  }
}

trait DoStuff[T] {
  inline def stuff(input: Int): String
}
```
Then we create an inline method that summons that via summonFrom:
```scala
import compiletime.summonFrom

object Example {

  inline def summonStuff[T] = summonFrom {
    case ds: DoStuff[T] => ds
  }

  inline def run[T](i: Int) = {
    summonStuff[T].stuff(i)
  }
  
}
```
Then we invoke this method:
```scala
println( Example.run[Foo](123) )
```

## Output

The following error happens
```scala
[error] 7 |    println( Example.run[Foo](123) )
[error]   |             ^^^^^^^^^^^^^^^^^^^^^
[error]   |           Deferred inline method stuff in trait DoStuff cannot be invoked
```

## Expectation
The inline should be summoned and work correctly.

## Repo
You can find this example in a github repo here:
https://github.com/deusaquilus/summonFrom_inline

**Comment by nicolasstucki** [comment]
The error message is correct, `DoStuff` does not implement the method and it would be impossible to call inline it. Here we must call `stuff` on a class that does implement the inline method. `inline given DoStuff[Foo]` does not as it is a `DoStuff` and `ds` in `case ds: DoStuff[T] => ds` is also a `DoStuff`.


One possible way to fix the code would be to define `DoFoo` with the known implementation of `stuff` to be able to inline it:
```scala
trait Foo
object Foo {
  inline given DoFoo = new DoFoo

  class DoFoo extends DoStuff[Foo] {
    inline def stuff(input: Int): String = "foo:" + input
  }
}

trait DoStuff[T] {
  inline def stuff(input: Int): String
}

import compiletime.summonFrom

object Example {

  inline def summonStuff[T] = summonFrom {
    case ds: Foo.DoFoo => ds
  }

  inline def run[T](i: Int) = {
    summonStuff[T].stuff(i)
  }

}

def test = println( Example.run[Foo](123) )
```

**Comment by bishabosha** [comment]
so it is a limitation that at the point `summonStuff[Foo]` is inlined and has a concrete type `example.Foo.given_DoStuff_Foo.type` that the concrete override can't be selected instead?
