### ISSUE TITLE
reflect runtime class name using Quotes

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#11161]
## Minimized code

Let's say I create a simple enum type:
```Scala
enum Shape:
  case Square(width: Int, height: Int) extends Shape
  case Circle(radius: Int) extends Shape
```
Then I create a macro to print it's name:
```scala
import scala.quoted._
inline def showType[T]: String = ${ showTypeImpl[T] }
def showTypeImpl[T: Type](using Quotes): Expr[String] = {
  import quotes.reflect._
  Expr(TypeRepr.of[T].typeSymbol.fullName)
}
```

## Output
Then I call it:
```
showType[Shape.Circle]

// It prints:
// ".Shape$.Circle"
```

## Expectation
This is very unexpected because if I use a ClassTag/runtime-class to print the name I get the following:
```
classTag[Shape.Circle].toString
// It prints:
// "Shape$Circle"
```
This is the same as the print-out from the runtimeClass:
```
classTag[Shape.Circle].runtimeClass.getName
// It prints:
// "Shape$Circle"
```
I would expect the result from typeSymbol.fullName to be the same as runtimeClass.getName.

**Comment by bishabosha** [comment]
this seems like a weird interaction with the empty package being special cased to print as the empty string

**Comment by bishabosha** [comment]
I would disagree that fullname is meant to be the same as the runtime class name, because this is meant to be the view before erasure, where we still have type members

**Comment by deusaquilus** [comment]
> I would disagree that `fullName` is meant to be the same as the runtime class name, because this is meant to be the view before erasure, so inner classes are not yet flattened, and type members still exist

What about `TypeRepr.of[T].classSymbol.get.fullName`? Should that be the same as `runtimeClass.getName`?
I don't have a strong opinion of what the thing should be, but it should be *something* that reliably matches `runtimeClass.getName` because there are some important edge cases where I need to compare these things by name.

**Comment by deusaquilus** [comment]
The only alternative I can think of would be to have some kind of function that goes from Type[T] to ClassTag[T].

**Comment by bishabosha** [comment]
can you use `Expr.summon` to get a classtag from a type?

**Comment by deusaquilus** [comment]
That would give me an `Type[T] => Expr[ClassTag[T]]`. What I would like in that case is `Type[T] => ClassTag[T]`.

**Comment by deusaquilus** [comment]
@bishabosha Looks like I found a workaround for this particular issue. I think I'll keep this open though because the naming seems incorrect.

**Comment by bishabosha** [comment]
> That would give me an `Type[T] => Expr[ClassTag[T]]`. What I would like in that case is `Type[T] => ClassTag[T]`.

thats a great point 😂, what is the workaround?

**Comment by nicolasstucki** [comment]
It is impossible to do `Type[T]` => `ClassTag[T]` as the type we are referring to is being compiled and hence no `java.lang.Class[_]` can exist for it yet.

**Comment by nicolasstucki** [comment]
What we might have is a 
```scala
object TypeRepr {
  ...
  def classNameOf[T: Type](using Quotes): Option[String] = ...
}

TypeRepr.classNameOf[T]
```

Not sure what it would return anonymous classes or any other class with a generated name. Those names might not be stable.

**Comment by sjrd** [comment]
Have you tried:
```scala
def showTypeImpl[T: Type](using Quotes): Expr[String] = {
  import quotes.reflect._
  '{classOf[T].getName()}
}
```
?

This seems to me like the most straightforward way to get that information in a reliable way.

**Comment by bishabosha** [comment]
I think the problem is that the string needs to be compared at compiletime

**Comment by deusaquilus** [comment]
@sjrd No, I haven't actually :man_facepalming:. Thanks!

**Comment by bishabosha** [comment]
@deusaquilus but does your use case require inspecting the class name at compile time?

**Comment by gaeljw** [comment]
> ```scala
> def showTypeImpl[T: Type](using Quotes): Expr[String] = {
>   import quotes.reflect._
>   '{classOf[T].getName()}
> }
> ```
> 
> This seems to me like the most straightforward way to get that information in a reliable way.

@sjrd I was trying your suggestion in a different context but I get

```
[error] -- Error: /tmp/jodah/src/main/scala/Macros.scala:32:46 -------------------------
[error] 32 |    val classExpr : Expr[String] = '{ classOf[T].getName() }
[error]    |                                              ^
[error]    |                                              T is not a class type
```

Am I missing something? :thinking:

**Comment by gaeljw** [comment]
For anyone interested, following the suggestion of @bishabosha I've workaround the initial issue by getting a `ClassTag` rather than a string representation.
You can see the code on the following project: https://github.com/gaeljw/typetrees/blob/main/src/main/scala/io/github/gaeljw/typetrees/TypeTreeTagMacros.scala#L8

**Comment by deusaquilus** [comment]
@gaeljw That's really cool, I didn't know about `Implicits.search` or that you could use it to find a ClassTag for T. 
Could a ClassTag[T] also be summoned with Expr.summon?

**Comment by gaeljw** [comment]
> Could a Expr[ClassTag[T]] also be summoned with Expr.summon?

@deusaquilus absolutely, I just tried `Expr.summon` instead of the manual implicit search and it seems to work.

**Comment by nicolasstucki** [comment]
The canonical solution is probably something like

```scala
import scala.quoted._
import scala.reflect.ClassTag

inline def showType[T]: String = ${ showTypeImpl[T] }

private def showTypeImpl[T: Type](using Quotes): Expr[String] =
  Expr.summon[ClassTag[T]] match
      case Some(ct) => '{ $ct.runtimeClass.getName }
      case None =>
        import quotes.reflect._
        report.throwError(s"Unable to find a ClassTag for type ${Type.show[T]}", Position.ofMacroExpansion)
```

**Comment by bishabosha** [comment]
Is it still useful to inspect the future class name at compiletime, rather than waiting until runtime?
