### ISSUE TITLE
Scalac and Dotty have different earsure of tpd.cpy getter

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1118]
Dotty creates:   `public dotty.tools.dotc.ast.Trees$Instance$TreeCopier cpy();`
scalac expects: `public dotty.tools.dotc.ast.tpd$TypedTreeCopier cpy();`

Manifests itself as failure of 3 tests if tests are compiled by scalac and dotty is bootstrapped:
```
[error] Test test.transform.TreeTransformerTest.canOverwrite failed: java.lang.NoSuchMethodError: dotty.tools.dotc.ast.tpd$.cpy()Ldotty/tools/dotc/ast/tpd$TypedTreeCopier;, took 0.027 sec
[error]     at test.transform.TreeTransformerTest$$anonfun$canOverwrite$1$Transformation$1.transformValDef(TreeTransformerTest.scala:69)
....
[error] Test test.transform.TreeTransformerTest.invocationCount failed: java.lang.NoSuchMethodError: dotty.tools.dotc.ast.tpd$.cpy()Ldotty/tools/dotc/ast/tpd$TypedTreeCopier;, took 0.019 sec
[error]     at test.transform.TreeTransformerTest$$anonfun$invocationCount$1$Transformation1$2.transformLiteral(TreeTransformerTest.scala:145)
...
[error] Test test.transform.TreeTransformerTest.transformationOrder failed: java.lang.NoSuchMethodError: dotty.tools.dotc.ast.tpd$.cpy()Ldotty/tools/dotc/ast/tpd$TypedTreeCopier;, took 0.017 sec
[error]     at test.transform.TreeTransformerTest$$anonfun$transformationOrder$1$Transformation1$1.transformLiteral(TreeTransformerTest.scala:98)
```

**Comment by odersky** [comment]
That's because `cpy` is defined like this in `tpd`:

    override val cpy = new TypedTreeCopier

`dotty` picks the inherited type from `Trees.Instance` whereas `scalac` picks the rhs type. That change in behavior is intentional. We can get rid of it in this instance by writing

    override val cpy: TypedTreeCopier = new TypedTreeCopier

But I am not sure it is necessary.

**Comment by DarkDimius** [comment]
I see why this is an intended change on language level.
Can't we create a workaround on bytecode level to ensure that Dotty compiled artifacts can serve as a replacement for scalac compiled artifacts by introducing a bridge in erasure is such cases?

**Comment by odersky** [comment]
We never tried to ensure callability from Java to Dotty. If we did try to
do this I fear there are more issues than this one. For a start, we don't
generate pickling info.


On Sat, Feb 20, 2016 at 4:42 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> I see why this is an intended change on language level.
> Can't we create a workaround on bytecode level to ensure that Dotty
> compiled artifacts can serve as a replacement for scalac compiled artifacts
> by introducing a bridge in erasure is such cases?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/1118#issuecomment-186631236>.
>



-- 
Martin Odersky
EPFL
