### ISSUE TITLE
VerifyError with implicit ClassTag in companion object

### ISSUE THREAD

**Issue by hughsimpson** [lampepfl/dotty#11208]
The following throws a `VerifyError` (Tested with 3.0.0-M3)
```
import scala.reflect.ClassTag

@main def run = println(Foo)

abstract class Bar[T](implicit val thisClassTag: ClassTag[T])

class Foo
object Foo extends Bar[Foo]
```

Alternatives tried:
- Changing `abstract class Bar[T](implicit val thisClassTag: ClassTag[T])` to `abstract class Bar[T: ClassTag]{ val thisClassTag: ClassTag[T] = implicitly[ClassTag[T]] }` works
- Changing `object Foo extends Bar[Foo]` to `object Foo extends Bar()(classTag[Foo])` works
- Summoning an implicit of a different class works (only `ClassTag` specifically seems to be affected)
- Using the ClassTag of anything other than the companion class works (`object Foo extends Bar[Foo2]` seems fine)

**Comment by griggt** [comment]
This example, reported as scala/bug#473, also throws a VerifyError at runtime with 3.0.0-M3 whereas in Scala 2 it is a compile error.

```scala
class Foo(implicit val foo: Foo)

object Test extends App {
  implicit object Bar extends Foo
  Bar.foo
}
```
