### ISSUE TITLE
Dotty generated code is slower than scalac generated one.

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#1121]
After the boostrap problems got fixed (thanks @DarkDimius!) I could finally do what I was after in the first place: Measure the quality of the generated code by checking how long it takes dotty to compile itself, then how long it takes the bootstrapped dotty. Here are the numbers:

Command:

```
/Users/odersky/workspace/dotty/src/dotty/tools> time java -Xms1g -Xmx3g dotty.tools.dotc.Main -d /classes *.scala */*.scala */*/*.scala */*/*/*.scala
```

scalac generated:

```
173.962u 4.815s 0:49.75 359.3%  0+0k 9+135io 0pf+0w
```

dotc generated:

```
 191.175u 4.610s 0:56.19 348.4% 0+0k 1+126io 0pf+0w
```

Some of it might be due to the fact that we load the second compiler as separate classes from the classpath and the first from jars. But I don't think that's much. Another improvement will come once we have #1061 for generating switches in. We should watch whether this will bring the times close to each other or whether there are also other issues.

**Comment by DarkDimius** [comment]
because of #1471 reproducing this became much harder. Here's the right classpath today:
```
-cp 
    ./dotty/dotty.jar/:
    ./dotty/interfaces/target/dotty-interfaces-0.1-SNAPSHOT.jar:
    $IVY_CACHE/org.scala-lang/scala-library/jars/scala-library-2.11.5.jar:
    $IVY_CACHE/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.5.jar:
    $IVY_CACHE/org.scala-sbt/interface/jars/interface-0.13.9.jar
    ./dotty/target/scala-2.11/dotty_2.11-0.1-SNAPSHOT.jar
```

**Comment by odersky** [comment]
We are now pretty much on a par wrt code quality. Not to say that we should not look for areas of further improvement. But it does not seem worthwhile to keep this open anymore.
