### ISSUE TITLE
Typer crashes when omitting new for instance generation

### ISSUE THREAD

**Issue by ascienta** [lampepfl/dotty#11230]
Using M3, the following code crashes the typer (not in vsc but in sbt on console):

```scala
class CrashTyper(i: Int) {}
object CrashTyper {
  def init: CrashTyper = CrashTyper(0) 
}
```
The following compiles:
```scala
class CrashTyper(i: Int) {}
object CrashTyper {
  def init: CrashTyper = new CrashTyper(0) 
}
```
sbt 1.4.6, linker plugin is 0.5.1

**Comment by abgruszecki** [comment]
@ascienta can you paste the error trace?

**Comment by ascienta** [comment]
compiling 1 Scala source to C:\Users\rsasc\Documents\Development\git\agileEvents\jvm\target\scala-3.0.0-M3\classes ...
[info] compiling 1 Scala source to C:\Users\rsasc\Documents\Development\git\agileEvents\jvm\target\scala-3.0.0-M3\test-classes ...
[info] exception occurred while typechecking C:\Users\rsasc\Documents\Development\git\agileEvents\jvm\src\test\scala\com\ascienta\agileEvents\UnitTestImpl\FibonacciImpl.scala
[info] exception occurred while compiling C:\Users\rsasc\Documents\Development\git\agileEvents\jvm\src\test\scala\com\ascienta\agileEvents\UnitTestImpl\FibonacciImpl.scala
scala.MatchError: This(Ident(CrashTyper$)) (of class dotty.tools.dotc.ast.Trees$This) while compiling C:\Users\rsasc\Documents\Development\git\agileEvents\jvm\src\test\scala\com\ascienta\agileEvents\UnitTestImpl\FibonacciImpl.scala
[error] ## Exception when compiling 11 sources to C:\Users\rsasc\Documents\Development\git\agileEvents\jvm\target\scala-3.0.0-M3\test-classes
[error] scala.MatchError: This(Ident(CrashTyper$)) (of class dotty.tools.dotc.ast.Trees$This)
[error] dotty.tools.dotc.typer.Typer.newExpr$1(Typer.scala:3603)
[error] dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3639)
[error] dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2936)
[error] dotty.tools.dotc.typer.Typer.tryApply$1(Typer.scala:2849)
[error] dotty.tools.dotc.typer.Typer.tryInsertApplyOrImplicit$$anonfun$2(Typer.scala:2867)
[error] dotty.tools.dotc.typer.Typer$$Lambda$5953/00000000E53297F0.apply(Unknown Source)
[error] dotty.tools.dotc.typer.Typer.tryEither(Typer.scala:2787)
[error] dotty.tools.dotc.typer.Typer.tryInsertApplyOrImplicit(Typer.scala:2876)
[error] dotty.tools.dotc.typer.Typer.adaptToArgs$1(Typer.scala:3066)
[error] dotty.tools.dotc.typer.Typer.adapt1(Typer.scala:3640)
[error] dotty.tools.dotc.typer.Typer.adapt(Typer.scala:2936)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2659)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2663)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2779)
[error] dotty.tools.dotc.typer.Applications.realApply$1(Applications.scala:857)
[error] dotty.tools.dotc.typer.Applications.typedApply(Applications.scala:1010)
[error] dotty.tools.dotc.typer.Applications.typedApply$(Applications.scala:236)
[error] dotty.tools.dotc.typer.Typer.typedApply(Typer.scala:101)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2528)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2590)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2659)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2663)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2779)
[error] dotty.tools.dotc.typer.Typer.$anonfun$33(Typer.scala:2032)
[error] dotty.tools.dotc.typer.Typer$$Lambda$5852/00000000E52AB5A0.apply(Unknown Source)
[error] dotty.tools.dotc.typer.PrepareInlineable$.dropInlineIfError(PrepareInlineable.scala:216)
[error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:2032)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2505)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2589)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2659)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2663)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2685)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2735)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2178)
[error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2516)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2520)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2589)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2659)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2663)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2685)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2735)
[error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:2178)
[error] dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2516)
[error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2520)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2589)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2659)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2663)
[error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2685)
[error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2735)
[error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:2313)
[error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2561)
[error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2590)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2659)
[error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2663)
[error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2779)
[error] dotty.tools.dotc.typer.FrontEnd.liftedTree1$1(FrontEnd.scala:79)
[error] dotty.tools.dotc.typer.FrontEnd.typeCheck$$anonfun$1(FrontEnd.scala:84)
[error] dotty.tools.dotc.typer.FrontEnd$$Lambda$5731/00000000E50EBC80.apply$mcV$sp(Unknown Source)
[error] dotty.tools.dotc.typer.FrontEnd.monitor(FrontEnd.scala:43)
[error] dotty.tools.dotc.typer.FrontEnd.typeCheck(FrontEnd.scala:85)
[error] dotty.tools.dotc.typer.FrontEnd.runOn$$anonfun$3(FrontEnd.scala:120)
[error] dotty.tools.dotc.typer.FrontEnd$$Lambda$5730/00000000E5183A30.applyVoid(Unknown Source)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.immutable.List.foreach(List.scala:333)
[error] dotty.tools.dotc.typer.FrontEnd.runOn(FrontEnd.scala:120)
[error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:185)
[error] dotty.tools.dotc.Run$$Lambda$5585/00000000E477F110.applyVoid(Unknown Source)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
[error] dotty.tools.dotc.Run.runPhases$5(Run.scala:195)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:203)
[error] dotty.tools.dotc.Run$$Lambda$5548/00000000E4C79A30.apply$mcV$sp(Unknown Source)
[error] scala.runtime.function.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:210)
[error] dotty.tools.dotc.Run.compileSources(Run.scala:146)
[error] dotty.tools.dotc.Run.compile(Run.scala:130)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:39)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:92)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler$$Lambda$5294/00000000E461F390.apply$mcV$sp(Unknown Source)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:241)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:176)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.MixedAnalyzingCompiler$$Lambda$5290/00000000E01BE780.apply(Unknown Source)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:204)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl$$Lambda$2939/0000000000000000.apply(Unknown Source)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:174)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:172)
[error] sbt.internal.inc.Incremental$$$Lambda$3125/00000000DE73F610.apply(Unknown Source)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:459)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:261)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:414)
[error] sbt.internal.inc.Incremental$$$Lambda$3161/00000000DE0E0B00.apply(Unknown Source)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:499)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:401)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:166)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:573)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:491)
[error] sbt.internal.inc.IncrementalCompilerImpl$$Lambda$3049/00000000C8ECDFA0.apply(Unknown Source)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:420)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2177)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2134)
[error] sbt.Defaults$$$Lambda$3043/00000000E01E00C0.apply(Unknown Source)
[error] sbt.internal.io.Retry$.apply(Retry.scala:40)
[error] sbt.internal.io.Retry$.apply(Retry.scala:23)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2130)
[error] sbt.Defaults$$$Lambda$767/00000000C9194C00.apply(Unknown Source)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] scala.Function1$$Lambda$1298/0000000000000000.apply(Unknown Source)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.internal.util.$tilde$greater$$Lambda$2358/0000000000000000.apply(Unknown Source)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] sbt.Execute$$Lambda$2377/0000000000000000.apply(Unknown Source)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] sbt.Execute.work(Execute.scala:291)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] sbt.Execute$$Lambda$2367/0000000000000000.apply(Unknown Source)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.ConcurrentRestrictions$$anon$4$$Lambda$2374/0000000000000000.apply(Unknown Source)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] java.base/java.lang.Thread.run(Thread.java:834)

**Comment by ascienta** [comment]
Funny thing: when put into an object alone, it does not crash. When put into that source file 'FibonacciImpl.scala' it crashes.

**Comment by ascienta** [comment]
package com.ascienta.agileEvents.UnitTests

trait TyperCrasher {

  class CrashTyper(i: Int) {}
  object CrashTyper {
    def init: CrashTyper = CrashTyper(0) 
  }
  
  
}

This is the file completely reduced and it crashes the typer.

**Comment by ascienta** [comment]
trait TyperCrasher {

  class CrashTyper(i: Int) {}
  object CrashTyper {
    def init: CrashTyper = new CrashTyper(0) 
  }
  
  
}

class CrashTyper(i: Int) {}
object CrashTyper {
  def init: CrashTyper = CrashTyper(0) 
}

This does not crash -> the problem is the class definition inside the trait. On top level, the typer checks the code.
