### ISSUE TITLE
Anchors point to inherited documentation and don’t support overloads

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#11241]
The anchor on the left of the documentation of the method `map` of the type [`Map`](https://dotty.epfl.ch/api/scala/collection/Map.html) points to the parent type `IterableOps`.

![Screenshot from 2021-01-28 16-58-30](https://user-images.githubusercontent.com/332812/106164318-1c1d5e80-618a-11eb-8b3f-2b939cfc10b2.png)

Instead, I think it would be useful to stay in the documentation of class `Map`.

Also, I’m not sure how overloading is handled. It seems the anchor is named only after the method name, so if two methods have the same name they will have the same anchor?

**Comment by BarkingBad** [comment]
cc @pikinier20

**Comment by pikinier20** [comment]
You're right, I think we should change the anchor to point to method inside currently opened class and instead change link in `Inheriten from` section to point to method inside class that it's defined. So in this case anchor would point to Map, but `IterableOps` would lead to `map` inside `IterableOps`. What do you think?

Also we need to implement handling of overloading. We can reuse the way it's done in scaladoc or use additional information that we store in DRI to disambiguate methods with same name.

**Comment by julienrf** [comment]
> You're right, I think we should change the anchor to point to method inside currently opened class and instead change link in `Inheriten from` section to point to method inside class that it's defined. So in this case anchor would point to Map, but `IterableOps` would lead to `map` inside `IterableOps`. What do you think?

Sounds great!



> Also we need to implement handling of overloading. We can reuse the way it's done in scaladoc or use additional information that we store in DRI to disambiguate methods with same name.

The way it is currently done in scaladoc is painful to work with because URL fragments may contain parentheses and brackets, which can interfere with Markdown, when we want to share a link.

**Comment by pikinier20** [comment]
I've implemented this in [#11394](https://github.com/lampepfl/dotty/pull/11394). Now we calculate hash for each method from its params and type params. Anchors to method look like: `'method_name'-'hash'`. It should solve problem of overloaded methods. 

This PR also changed the way we link to inherited methods to the one we developed in this issue.

**Comment by julienrf** [comment]
Great work, thanks!
