### ISSUE TITLE
JUnit tests do not run in Scala.js if implemented on an abstract superclass

### ISSUE THREAD

**Issue by ekrich** [lampepfl/dotty#11276]
## Compiler version

When running JUnit tests on Scala.js `3.0.0-M3`, tests annotated on abstract super-classes do not run. When running the the same test on Scala JVM, they all run.

## Minimized code

See `YearMonthTest`. https://github.com/ekrich/sjavatime/blob/master/testSuite/shared/src/test/scala/org/scalajs/testsuite/javalib/time/YearMonthTest.scala

## Output

Running JVM tests 2.11 - 3.0.0-M3 I get 354 tests.
Running JS tests 2.11 - 2.13, 354 tests and 3.0.0-M3, 284

All the tests classes are run but if I look at one example:
`YearMonthTest` extends the abstract class `TemporalTest` which in turn extends the abstract class `TemporalAccessorTest`.

On JVM there are 36 test. On JS only 26 run and there are 26 tests on `YearMonthTest` and 6 on `TemporalTest` and 4 on `TemporalAccessorTest`.

## Expectation

All 36 tests run on Scala.js

**Comment by sjrd** [comment]
Thanks for the report!

**Comment by ekrich** [comment]
Can confirm this is fixed in RC2. Thanks.
