### ISSUE TITLE
Cannot create collective extension methods in REPL, premature error on ENTER

### ISSUE THREAD

**Issue by bjornregnell** [lampepfl/dotty#11286]
## Compiler version

Using nightly Scala 3 REPL from inside sbt
```
sbt:test> scalaVersion
[info] 3.0.0-RC1-bin-20210131-913d0a8-NIGHTLY
```

## Minimized code
The REPL does not allow for opening an indented continuation after incomplete extension declaration, hence preventing declaring colective extensions in REPL. 
```Scala
scala> extension (i: Int)
1 |extension (i: Int)
  |                  ^
  |                  Extension without extension methods
scala> extension (i: Int){
1 |extension (i: Int){
  |                   ^
  |                   `def` expected
```

## Expectation
The REPL prompts an error directly after pressing Enter on incomplete collective extension method declaration, but it **should** be possible to continue multi-line editing on a new line.
## Workaround
 Start a single extension method like this:
```
scala> object X:                                                            
     |   extension (i: Int) def +(j: Int) = i + j
     | 
// defined object X

scala>
```  
And then arrow-up and edit by inserting a line break. Then the REPL eats the collective extensions:
```
scala> object X:                                                            
     |   extension (i: Int) 
     |     def +(j: Int) = i + j
     |     def -(j: Int) = i - j
     | 
// defined object X
```

**Comment by prolativ** [comment]
Looks like a duplicate of https://github.com/lampepfl/dotty/issues/9374

**Comment by bjornregnell** [comment]
ooops sorry, missed that. Should I close this?

**Comment by bjornregnell** [comment]
maybe the information on the workaround is helpful, until it is fixed

**Comment by prolativ** [comment]
I would close this. This issue will be still accessible and linked to the original one if someone really needs to read these comments.
Secondly I would say that a more straightforward workaround would be to define multiple single extension methods at once instead of modifying an existing one (the former solution can be easily copy-pasted)

**Comment by bjornregnell** [comment]
Ok will close this.
> more straightforward workaround would be to define multiple single extension methods at once

I have no clue on how to do this as the REPL just stops parsing... after `...)`

**Comment by prolativ** [comment]
Just don't break the line when defining an extension, e.g.
```scala
scala> extension (i: Int) def doubled = i * 2                                   
def doubled(i: Int): Int

scala> extension (i: Int) def tripled = i * 3                                  
def tripled(i: Int): Int
```

**Comment by bjornregnell** [comment]
aha yes thanks; but if I have code in another editor and trying to paste it in REPL etc then compiling code will be broken in the REPL anyway; but yes breaking collective extensions into separate one-liners might be the easiest in some situations.
