### ISSUE TITLE
Extend Metals with resolving/inserting doc links

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#11283]

**Comment by ckipp01** [comment]
@tgodzik is this still something we want open here, or does having the feature request in [Metals](https://github.com/scalameta/metals-feature-requests/issues/156) good enough? If so I can link to this from there and then just close this.

**Comment by tgodzik** [comment]
I think it's enough to have it open in Metals.

**Comment by ckipp01** [comment]
Alright, that was my thinking as well. I'll go ahead and close this in favor of https://github.com/scalameta/metals-feature-requests/issues/156.
