### ISSUE TITLE
[Regression] Default value for using parameter is not taken into account anymore.

### ISSUE THREAD

**Issue by Iltotore** [lampepfl/dotty#11336]
## Compiler version
Latest (3.0.0-M3)

## Minimized code

<details>
<summary>Working code in Scala 2</summary>

```scala
def summonOption[T <: AnyRef](implicit value: T = null): Option[T] = Option(value)
```
</details>

Scala 3:
```Scala
def summonOption[T <: AnyRef](using value: T = null): Option[T] = Option(value)
```

## Output
When calling the method without findable implicit argument:
```scala
no implicit argument of type T was found for parameter value of method summonOption in object util
```
is thrown by the compiler.

## Expectation
The compiler should use the `null` parameter if no implicit argument is found (so `summonOption` should return None). The Scala 2 behavior meet expectations but not Dotty.

**Comment by odersky** [comment]
I canot reproduce this. Can you provide a full example that does not compile?

**Comment by Iltotore** [comment]
Here is a [scastie sample}(https://scastie.scala-lang.org/P7NoYCD2QuiYQqGyZ5WQFQ)

**Comment by griggt** [comment]
The linked scastie doesn't work because scastie appears not to support worksheet mode for Scala 3 (the error is `Expected a toplevel definition`)

It should work if you put the `println` inside a main method, e.g. `@main def test = println( ... )`

**Comment by Iltotore** [comment]
Effectively, it works when wrapping the code in a main method. Thank you !
