### ISSUE TITLE
Impossible to extends "Ordered" when "-Yexplicit-nulls" flag used

### ISSUE THREAD

**Issue by flomebul** [lampepfl/dotty#11341]
## Compiler version

scala version 3.0.0-M3

## Minimized code

```Scala
object Issue11341 {
  class ClsA(i: Int) extends Ordered[ClsA] {
    def compare(that: ClsA): Int = ???

    // Members declared in java.lang.Comparable
    override def compareTo(that: ClsA | UncheckedNull): Int = ???
  } 

  class ClsB(i: Int) extends Ordered[ClsB] {
    def compare(that: ClsB): Int = ???

    // Members declared in java.lang.Comparable
    override def compareTo(that: ClsB): Int = ???
  } 

  class ClsC(i: Int) extends Ordered[ClsC] {
    def compare(that: ClsC): Int = ???
  } 
}
```

## Output

```scala
def compareTo(that: asuivre.Issue11341.ClsA | UncheckedNull): Int
error overriding method compareTo in trait Ordered of type (that: asuivre.Issue11341.ClsA): Int;
  method compareTo of type (that: asuivre.Issue11341.ClsA | UncheckedNull): Int has incompatible type

class ClsB: asuivre.Issue11341.ClsB
class ClsB needs to be abstract, since def compareTo(x$0: T | UncheckedNull): Int is not defined 
(Note that T | UncheckedNull does not match asuivre.Issue11341.ClsB)

def compareTo(that: asuivre.Issue11341.ClsB): Int
error overriding method compareTo in trait Comparable of type (x$0: asuivre.Issue11341.ClsB | UncheckedNull): Int;
  method compareTo of type (that: asuivre.Issue11341.ClsB): Int has incompatible type

class ClsC: asuivre.Issue11341.ClsC
class ClsC needs to be abstract, since def compareTo(x$0: T | UncheckedNull): Int is not defined 
(Note that T | UncheckedNull does not match asuivre.Issue11341.ClsC)
```

## Expectation

I suppose that the case "ClsC" is the right one, as it is the case without the "-Yexplicit-nulls" flag.

**Comment by noti0na1** [comment]
I tested this example using the new explicit nulls PR #9884 (We no longer have `UncheckedNull`, so it need to be repleced by `Null`).

The output is:

```
    |  override def compareTo(that: ClsA | Null): Int = ???
    |               ^
    |error overriding method compareTo in trait Ordered of type (that: ClsA): Int;
    |  method compareTo of type (that: ClsA | Null): Int has incompatible type
``` 

I think this is expected in the current design. In the PR, we have a relaxed overriding rule when the overrided member is defined in Java. 

However in this case, `Ordered` is a scala trait, and it overrides the `compareTo` function. Therefore, `compareTo` becomes a scala function and the special rule doesn't apply. The only way to override `compareTo` here is `override def compareTo(that: ClsA): Int`.

In theory, we may compare an object to a null pointer, but the current standard lib is not compiled using explicit nulls, we are unable to add `| Null` to the param type. 

A workaround is to cast `that: ClsA` to `ClsA | Null` and then compare it to null.

**Comment by olhotak** [comment]
Do `ClsB` and `ClsC` compile with #9884?

I think that is the desired behaviour in this case, that `ClsB` and `ClsC` compile but `ClsA` doesn't.

**Comment by noti0na1** [comment]
@olhotak Yes, `ClsB` and `ClsC` can be compiled successfully.

**Comment by flomebul** [comment]
If `ClsC` compile, it is exactly what is expected. Thanks
