### ISSUE TITLE
Dotty seems to evaluate generical implicits in macro too early. 

### ISSUE THREAD

**Issue by Iltotore** [lampepfl/dotty#11352]
## Compiler version

Latest (3.0.0-M3)

## Minimized example

```Scala
package io.github.iltotore.scalalint

import scala.quoted._

object compileTime {
  
  inline def preEvaluate[T](inline expr: T): Option[T] = ${preEvaluateImpl('expr)}

  def preEvaluateImpl[T : Type](expr: Expr[T])(using Quotes): Expr[Option[T]] = {
    Expr(expr.value)
  }
  
}
```

## Output

<details>
<summary>Compiler error</summary>

```scala
[error] -- [E008] Not Found Error: C:\Users\rapha\IdeaProjects\ScalaLint\main\src\io\github\iltotore\scalalint\compileTime.scala:11:14 
[error] 11 |    Expr(expr.value)
[error]    |         ^^^^^^^^^^
[error]    |      value value is not a member of quoted.Expr[T].
[error]    |      An extension method was tried, but could not be fully constructed:
[error]    |
[error]    |          x$2.value[T](expr)(quoted.FromExpr.DoubleFromExpr[Nothing])
[error] -- Error: C:\Users\rapha\IdeaProjects\ScalaLint\main\src\io\github\iltotore\scalalint\compileTime.scala:11:20 
[error] 11 |    Expr(expr.value)
[error]    |                    ^
[error]    |no implicit argument of type quoted.ToExpr[Option[T]] was found for parameter x$2 of method apply in object Expr.
[error]    |I found:
[error]    |
[error]    |    quoted.ToExpr.OptionToExpr[T](evidence$1, quoted.ToExpr.BooleanToExpr[Nothing])
[error]    |
[error]    |But method BooleanToExpr in object ToExpr does not match type quoted.ToExpr[T].
```
</details>

Note: this error is produced without any `preEvaluate` call.

## Expectation
Shouldn't Dotty eval ToExpr/FromExpr only when I call the macro ?

If it is the expected behavior, how can I pass implicits FromExpr and ToExpr to `preEvaluateImpl` in order to make this method work ? How can I execute a function parameter at compile time ?

**Comment by nicolasstucki** [comment]
The error is correct, in that code we are missing a `FromExpr[T]`. 

The eval would only be called when executing the macro, but in this instance the issue is that the macro does not compile.

It is possible to pass a `ToExpr`/`FromExpr` using `def preEvaluateImpl[T : Type: ToExpr: FromExpr](...)`. But this requires the call site to be able to produce one. In this particular example, it seems impossible as we do not know the type of `T`.

**Comment by Iltotore** [comment]
> The error is correct, in that code we are missing a `FromExpr[T]` and a `ToExpr[T]`.
> 
> The eval would only be called when executing the macro, but in this instance the issue is that the macro does not compile.
> 
> It is possible to pass a `ToExpr`/`FromExpr` using `def preEvaluateImpl[T : Type: ToExpr: FromExpr](...)`. But this requires the call site to be able to produce one. In this particular example, it seems impossible as we do not know the type of `T`.

Hello,
so it is impossible to make this kind of macro generic ?

**Comment by nicolasstucki** [comment]
It is impossible to do this on the JVM. It would require an interpreter that cannot be implemented in the presence of Java interop.

What kind of expressions do you want to pre-evaluate? If they only contain calls to things you know and expect you could write an interpreter for those using quoted code patterns. I can give more details if that is the case.

**Comment by Iltotore** [comment]
> It is impossible to do this on the JVM. It would require an interpreter that cannot be implemented in the presence of Java interop.
> 
> What kind of expressions do you want to pre-evaluate? If they only contain calls to things you know and expect you could write an interpreter for those using quoted code patterns. I can give more details if that is the case.

It was a test but the final goal is to create a compile-time assertion system but I have an idea about a workaround. I will edit this message  if I find anything.

**Comment by Iltotore** [comment]
Closed as it seems to be the good behavior and I solved finally found a workaround.
