### ISSUE TITLE
Disable static site generation in sbt-dotty

### ISSUE THREAD

**Issue by ruippeixotog** [lampepfl/dotty#11363]
We're using sbt-dotty 0.5.2 with Scala 3.0.0-M2 but we're having some trouble running `sbt doc` and `sbt publishLocal` on CI. I don't quite understand the error message, but it looks to be some race conditions around Scaladoc 3's [static site generation](https://dotty.epfl.ch/docs/usage/scaladoc/staticSite.html) (e.g. https://github.com/pureconfig/pureconfig/pull/932).

Because we use sbt-microsites with `mdoc` we happen to have valid Jekyll docs in the directories Scaladoc expects; however, we want Scaladoc to only generate APi documentation like on previous versions. I tried to find documentation for the SBT plugin or around the multiple dotty repos around, but I couldn't find anything.

Is there an easy way to disable this on SBT?

**Comment by smarter** [comment]
Have you tried upgrading to M3 first? It completely replaces scaladoc.
Any way if needed you should be able to turn off scaladoc generation with `sources in (Compile, doc) := Seq()` (the static site isn't separate from the api doc stuff)

**Comment by ruippeixotog** [comment]
Upgrading to 3.0.0-M3 does the trick, thanks @smarter!
