### ISSUE TITLE
Copy method is not generated for case classes with varargs

### ISSUE THREAD

**Issue by Lasering** [lampepfl/dotty#11364]
## Compiler version

3.0.0-M3

## Minimized code

```Scala
case class Foo(actions: Int*):
  def withActions(actions: Seq[Int]): Foo = this.copy(actions = actions)
```

## Output

```scala
value copy is not a member of Foo - did you mean (Foo.this : Foo).clone?
```

## Expectation
Successful compilation

[Scastie link](https://scastie.scala-lang.org/vLZraURVT8OxjYeGABvMOA)

**Comment by smarter** [comment]
This matches the behavior of Scala 2, and there's a comment explaining why it works that way in dotty:
https://github.com/lampepfl/dotty/blob/a66eaf3db14ab478b6ac5880d7bde1ea390a7700/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L639
Perhaps supporting default arguments for repeated parameters would make sense, but someone would have to make a full proposal for that and it would be a [feature request](https://github.com/lampepfl/dotty-feature-requests) and not a bug report.
