### ISSUE TITLE
Separate compilation with value class fails due to missing companion object

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1137]
`A_1.scala`:
```scala
class A(val self: Double) extends AnyVal
```
`B_2.scala`:
```scala
object B {
  def foo: A = new A(1)
}
```
```shell
% ./bin/dotc A_1.scala
% ./bin/dotc B_2.scala
exception occurred while compiling B.scala
Exception in thread "main" java.lang.AssertionError: NoDenotation.owner
        at dotty.tools.dotc.core.SymDenotations$NoDenotation.owner(SymDenotations.scala:1799)
        at dotty.tools.dotc.ast.tpd$.ref(tpd.scala:346)
        at dotty.tools.dotc.transform.Erasure$Boxing$.cast(Erasure.scala:230)
        at dotty.tools.dotc.transform.Erasure$Boxing$$anonfun$unbox$2.apply(Erasure.scala:200)
        at dotty.tools.dotc.transform.Erasure$Boxing$$anonfun$unbox$2.apply(Erasure.scala:175)
...
```
This does not happen if I manually create a companion in `A_1.scala`:
```scala
class A(val self: Double) extends AnyVal
object A
```

**Comment by odersky** [comment]
I guess this is due to the recent changes where we create companion objects only when we know they will be needed. @DarkDimius do you agree?

**Comment by smarter** [comment]
@odersky : I tried to set `needsCompanion` to `true` in `FirstTransform` so that we always generate companions and the issue still manifest itself. @DarkDimius suggested that the issue is that `FirstTransform` only operates on trees, not types, and when we unpickle `A` we only transform its type, so we never add its missing companion.

**Comment by DarkDimius** [comment]
@odersky that's indeed independent for the recent change.
I have suggested @VladimirNik to try to move creation of symbols for companion objects to info-transformer of FirstTransform.

**Comment by odersky** [comment]
Question to clarify:

The problem arises specifically when we read a value class from another
dotty module via TASTY? It does not arise when unpickling Scala 2 value
classes?



On Thu, Mar 3, 2016 at 8:28 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> @odersky <https://github.com/odersky> that's indeed independent for the
> recent change.
> I have suggested @VladimirNik <https://github.com/VladimirNik> to try to
> move creation of symbols for companion objects to info-transformer of
> FirstTransform.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/1137#issuecomment-191925862>.
>



-- 
Martin Odersky
EPFL

**Comment by smarter** [comment]
@odersky : Just tried it, looks like compiling `A_1.scala` with scalac then `B_2.scala` with dotc works correctly.

**Comment by DarkDimius** [comment]
@odersky note that Scala2Unpicker has its own mechanism for registering class companions. 
We could indeed create a similar one in TastyUnpickler, but It will duplicate the functionality already present in `FirstTransform`. Making a small change to `FirstTransform` not to change types using side-effect-full `enteredAfter` and instead be a proper InfoTransformer seems like a better design to me.  It would additionally allow to put more phases that need companions in the same mini-phase block in future, unlike now when only phases in next blocks could rely on the guarantees of `FirstTransform`.
