### ISSUE TITLE
Default parameter is ignored, when applying unary function without '()'

### ISSUE THREAD

**Issue by marcinzh** [lampepfl/dotty#11402]
## Compiler version

3.0.0-M4-bin-20210212-0273336-NIGHTLY

## Minimized code

```Scala
def foo(n: Int = 42): Int = n
def bar(m: Int, n: Int = 42): Int = n

val x: Int = foo         // error
val y: Int = foo()       // ok
val z: Int = bar(1337)   // ok

```

## Output

```scala
Found:    Int => Int
Required: Int
```

## Expectation

Compile `val x: Int = foo` without error.

**Comment by odersky** [comment]
That's not how it's supposed to work. Default parameters are searched only if there is a parameter list.
