### ISSUE TITLE
[Incremental compilation requirement] special flag on parameters with default values

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1143]
Currently, method parameters do not have a flag to let us know if they have a default value, a comment in `Scala2Unpickler` says:

``` scala
// DefaultParameterized flag now on method, not parameter
```

This is problematic for incremental compilation where we'd like to know where default parameters are to decide what needs to be recompiled, could we set the `DefaultParameterized` flag on these parameters?

**Comment by odersky** [comment]
@smarter Parameters are not symbols anymore. Where would we set the flag?

**Comment by smarter** [comment]
Closing since we're not going to add symbols to parameters, right now there is code in ExtractAPI to get all default parameters: https://github.com/lampepfl/dotty/blob/eacb5af4537c8b25a1afd20241cf5f2e6cff9eb5/compiler/src/dotty/tools/dotc/sbt/ExtractAPI.scala#L298-L305
