### ISSUE TITLE
Question/Might be an issue: Dotc typing system seems to contain big portion of "hard-code".

### ISSUE THREAD

**Issue by Iltotore** [lampepfl/dotty#11455]
Dotc typing system code seems to contain a lot of boilerplate and hardcoded matches like in `Types.scala`. This code appear to be hard to maintain (especially when you try to add another type feature).

Is this intended ? Is it a real issue ?

**Comment by liufengyun** [comment]
The code in the compiler is carefully crafted for a balance of maintainability and performance. Close as the issue tracker is intended for compiler bugs.

**Comment by Iltotore** [comment]
Ok. Thank you for this quick answer.
