### ISSUE TITLE
Structural types can lie when combined with values of erased types

### ISSUE THREAD

**Issue by jto** [lampepfl/dotty#11473]
## Compiler version

3.0.0-M3

## Minimized code

This is an example from the documentation that has been slightly modified. 
Note the type of `val age: 12`. 

We (dynamically) assign the value `42` and then access it from an instance whose type has been refined.

```Scala
class Record(elems: (String, Any)*) extends Selectable:
  private val fields = elems.toMap
  def selectDynamic(name: String): Any = fields(name)

type Person = Record { val name: String; val age: 12 }

val person = Record("name" -> "Emma", "age" -> 42).asInstanceOf[Person]
println(s"${person.name} is ${person.age} years old.")
```

## Output

> Emma is 42 years old

## Expectation

An exception should be thrown ?

**Comment by bishabosha** [comment]
for reference, `1.asInstanceOf[12]` does not throw either

**Comment by sjrd** [comment]
How is this behavior any different than for any other type whose erasure is less strict than itself? Like a `List[Int]`, for example?

**Comment by jto** [comment]
You're right it is not different. The problem is actually more generic. I'll update the title accordingly.

However consider the point of view of a user of a library that exposes a refined type:
In your IDE (and the scaladoc) you see `Person` is a type that has a few members with precise types. 
The fact that it is implemented as a refined `Selectable` is just none of your concern.

Given that you're using Scala, a language that put emphasis on its strong type system, you'd be tempted to trust the type.
Now suddenly a `val` happily gives you a value that is *not* a member of its advertised type.

**Comment by sjrd** [comment]
There's an `asInstanceOf` in the code. This is where you lied to the compiler, and you told it "trust me, this is correct". But it was not correct. What do you expect the compiler to do when you told it to trust you with something that is simply false?

**Comment by LPTK** [comment]
For the _record_, I think the only safe way of using Dotty's new record/selectDynamic abstraction (i.e., without having to use `asInstanceOf`, which is unsafe and error-prone) is through carefully-written whitebox macros. Similar to the old [scala-records](https://github.com/scala-records/scala-records) library for Scala 2.

It's a bit unfortunate that despite the whole `Selectable` reworking, the situation has not improved and is still fundamentally the same.

**Comment by jto** [comment]
@sjrd  I did not expect the compiler to tell me it's incorrect, I would have expected, as mentioned in the `Expectation` section,  the runtime to do so. 
While I still think this situation is unfortunate I understand it's a limitation of the JVM so I will close the issue.
