### ISSUE TITLE
constructor param names are not accessible from Java reflection Contructor Params for case classes

### ISSUE THREAD

**Issue by pjfanning** [lampepfl/dotty#11486]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
case class TestCaseClass(oof: String, bar: String)

val cls = classOf[TestCaseClass]

val constructor = cls.getConstructors.head

val param1 = constructor.getParameters.head

println(s"constructor params ${constructor.getParameters.map(_.getName).toSeq}")
```

## Output

```scala
constructor params ArraySeq(arg0, arg1)
```

Java class ConstructorParameters default to using the form arg0 when the underlying name is null.

## Expectation

Same code in Scala 2.13.4 produces 

```scala
constructor params ArraySeq(oof, bar)
```

Jackson-Module-Scala currently depends on java reflection for most of its functionality and the missing names in the constructor params affect a number of use cases.

**Comment by SethTisue** [comment]
the PR with Scala 2's support for this was https://github.com/scala/scala/pull/4735 (2016)
