### ISSUE TITLE
Generic number literals miss overloaded method

### ISSUE THREAD

**Issue by rjolly** [lampepfl/dotty#11482]
## Compiler version
3.0.0-RC1
## Minimized code and output
```Scala
import scala.language.experimental.genericNumberLiterals
type BigInteger = java.math.BigInteger
given BigInteger: scala.util.FromDigits[BigInteger] with {
  def fromDigits(digits: String) = new BigInteger(digits)
  def apply(x: BigInteger) = x
  def apply(x: String) = fromDigits(x)
}
println(BigInteger(1))
        ^^^^^^^^^^
None of the overloaded alternatives of method apply in object BigInteger with types
 (x: String): BigInteger
 (x: BigInteger): BigInteger
match arguments ((1 : Int))
```
## Expectation
Should work as when there's no overload:
```Scala
given BigInteger: scala.util.FromDigits[BigInteger] with {
  def fromDigits(digits: String) = new BigInteger(digits)
  def apply(x: BigInteger) = x
}
println(BigInteger(1))
// 1
```

**Comment by odersky** [comment]
This can be expressed without givens or generic number literals:
```scala
import java.math.BigInteger
class B
object B {
  def apply(x: BigInteger): B = ???
  def apply(x: String): B = ???
}
object Test {
  val x = B(1)
}
```

```
-- [E134] Type Mismatch Error: test.scala:8:10 ---------------------------------
8 |  val x = B(1)
  |          ^
  |None of the overloaded alternatives of method apply in object B with types
  | (x: String): B
  | (x: java.math.BigInteger): B
  |match arguments ((1 : Int))
1 error found
```
`scalac` gives the same result. The problem is that implicit conversions are not applied when doing overloading resolution. I don't see a good way to fix this without letting compile times go through the roof.

Happy to revisit if someone can come up with a convincing scheme how to handle this.

**Comment by rjolly** [comment]
Yes, with `BigInt` it works:
```scala
class B
object B {
  def apply(x: BigInt): B = ???
  def apply(x: String): B = ???
}
object Test {
  val x = B(1)
}
```
So your initial comment that the problem is that implicit conversions are not applied when doing overloading resolution, seems wrong. In addition, generic number literal is a different problem (though it could be seen as a subcase of implicit conversion, as I argued in https://github.com/lampepfl/dotty/pull/7468, but let's put it aside for the moment). Note that I use Java's `BigInteger` instead of `BigInt` on purpose, to remove a level of indirection (I think it would be a good idea to generalize this to other  types like `Option|nal`  but it's yet another subject).

So I think the initial problem with generic number literals is not solved (and would be interesting to solve). The fact that the `BigInt` version does work is not telling, as it succeeds thanks to implicit conversion, not generic number literals.
