### ISSUE TITLE
The repl classloader does not handle resources

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#11495]
The repl relies on https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/repl/AbstractFileClassLoader.scala which handle classes but not resources, the Scala 2 version of this class is much more complete and should be ported over: https://github.com/scala/scala/blob/2.13.x/src/reflect/scala/reflect/internal/util/AbstractFileClassLoader.scala (there's even tests for it! https://github.com/scala/scala/blob/2.13.x/test/junit/scala/reflect/internal/util/AbstractFileClassLoaderTest.scala)

**Comment by som-snytt** [comment]
Thanks for the shout out. I'll share this with my day job boss with note, See, I can write tests. Yesterday, I re-learned how to run tests for dotty, so maybe I can try this forward port.

**Comment by Swoorup** [comment]
Could this be related to worksheet issues: https://github.com/scalameta/metals/issues/2525 ?

**Comment by smarter** [comment]
i don't know if metals' worksheets are run using the repl.
