### ISSUE TITLE
Missing semanticdb occurrence for annonymous using

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#11498]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
package a

trait Foo

def bar(using Foo) = 42
```

## Output

```
src/main/scala/Test.scala
-------------------------

Summary:
Schema => SemanticDB v4
Uri => src/main/scala/Test.scala
Text => empty
Language => Scala
Symbols => 5 entries
Occurrences => 5 entries

Symbols:
a/Foo# => trait Foo
a/Foo#`<init>`(). => primary ctor <init>
a/Test$package. => final package object a
a/Test$package.bar(). => method bar
a/Test$package.bar().(x$1) => implicit param x$1

Occurrences:
[0:8..0:9) <= a/
[2:0..2:0) <= a/Foo#`<init>`().
[2:6..2:9) <= a/Foo#
[4:0..4:0) <= a/Test$package.
[4:4..4:7) <= a/Test$package.bar().
```

## Expectation

```
src/main/scala/Test.scala
-------------------------

Summary:
Schema => SemanticDB v4
Uri => src/main/scala/Test.scala
Text => empty
Language => Scala
Symbols => 5 entries
Occurrences => 5 entries

Symbols:
a/Foo# => trait Foo
a/Foo#`<init>`(). => primary ctor <init>
a/Test$package. => final package object a
a/Test$package.bar(). => method bar
a/Test$package.bar().(x$1) => implicit param x$1

Occurrences:
[0:8..0:9) <= a/
[2:0..2:0) <= a/Foo#`<init>`().
[2:6..2:9) <= a/Foo#
[4:0..4:0) <= a/Test$package.
[4:4..4:7) <= a/Test$package.bar().
[4:14..4:17) <= a/Foo#
```

**Comment by smarter** [comment]
Can you provide more details on what's missing? Not everyone is familiar with semanticdb. Also did you mean to write "for anonymous `using`"?

**Comment by tgodzik** [comment]
> Can you provide more details on what's missing? Not everyone is familiar with semanticdb. Also did you mean to write "for anonymous `using`"?

Yes, sorry. Still somehow waking up :sweat_smile: 

The last occurrence for symbol `Foo` is missing `[4:14..4:17) <= a/Foo#`

**Comment by tgodzik** [comment]
I wanted to take a look at it (should be simple to fix I think) any idea how to run a single expect test from semanticdb?

**Comment by bishabosha** [comment]
> I wanted to take a look at it (should be simple to fix I think) any idea how to run a single expect test from semanticdb?

you can change this one line and copy the directory structure of the current test directory:
https://github.com/lampepfl/dotty/blob/5eb32588aef946e8c74f72bde6a7d26684fa08e1/project/Build.scala#L464
