### ISSUE TITLE
Extension Methods with identical name in different files do not compile

### ISSUE THREAD

**Issue by joschua-fink** [lampepfl/dotty#11500]
## Compiler version

Scala 3.0.0-M3 and Scala 3.0.0-RC1

## Minimized code

```Scala
// a.scala

extension (thiz: Int) {
  def isNumber: Boolean =
    true
}

// b.scala

extension (thiz: Long) {
  def isNumber: Boolean =
    true
}
```

## Output

```scala
[error] 9 |  def isNumber: Boolean =
[error]    |  ^
[error]    |isNumber is already defined as method isNumber in [...]
[error] 10 |    true
```

## Expectation

Compiles without error.

## Note

`@targetName` is also ignored.

Workaround is to have both extension methods in the same file.

**Comment by smarter** [comment]
Extension methods desugar into regular methods (cf https://dotty.epfl.ch/docs/reference/contextual/extension-methods.html), and overloads of top-level definition must all be defined in the same source (cf bottom of http://dotty.epfl.ch/docs/reference/dropped-features/package-objects.html), so this is working as intended.

**Comment by joschua-fink** [comment]
Thank you for the quick response. I hadn't caught that limitation when it comes to package objects.

One additional note though: I am able to get the two file variant to successfully compile by 1. having two methods in two files with different names 2. compiling 3. renaming one method, so that they have an identical name 4. compiling (wrongly) successfully. Incremental compilation doesn't seem to check for this case.

**Comment by smarter** [comment]
> Incremental compilation doesn't seem to check for this case.

Thanks for the report, I've opened a new issue to keep track of this: https://github.com/lampepfl/dotty/issues/11514
