### ISSUE TITLE
Clashing top-level methods not detected under separate compilation

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#11514]
`A.scala`:
```scala
package pkg

def foo(x: Int): Int = x
```
`B.scala`:
```scala
package pkg

def foo(x: String): String = x
```
This shouldn't compile as http://dotty.epfl.ch/docs/reference/dropped-features/package-objects.html says that "If several top-level definitions are overloaded variants with the same name, they must all come from the same source file.", and indeed under joint compilation we get:
```shell
% scalac A.scala B.scala
-- [E161] Naming Error: B.scala:3:4 ----------------------------------------
3 |def foo(x: String): String = x
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |foo is already defined as method foo in A.scala
```
But under separate compilation the error is not detected:
```shell
% mkdir out
% scalac A.scala -d out
% scalac B.scala -classpath out
```
This is problematic since when using incremental compilation with a build tool one might not detect the problem until the next time they clean their build.

**Comment by odersky** [comment]
I think this is exactly the same as for classes? Here we also detect a conflict only when compiling jointly.

**Comment by smarter** [comment]
Ah indeed, one difference is that with top-level methods one ends up with two classfiles with clashing definitions, whereas with classes one classfile gets overwritten by the other, this might lead to weird behavior from the compiler later on. It's also less intuitive that method overloads are considered to clash so the mistake is easier to make (e.g. https://github.com/lampepfl/dotty/issues/11500), but feel free to close if you don't think this is something we should fix.

**Comment by odersky** [comment]
I think it would be hard to do this reliably, since we do not know whether classfiles we read are junk or not. We might have a toplevel file with a method nobody will reference anymore in the future. That's a risk that someone _will_ reference it by accident ffor sure. But it's something else to refuse compilation because of some random class on the classpath.
