### ISSUE TITLE
Expr.summon does not work with imported givens from a class instance

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#11557]
## Compiler version

3.0.0-RC1
also on 3.0.0-RC2-bin-20210227-07d9dd2-NIGHTLY

## Minimized code

Create some kind of typeclass with an implementation inside of a class-instance
```Scala
trait MyEncoder[T] {
  def encode(t: T): String
}

class MyContext {
  given intEncoder: MyEncoder[Int] = new MyEncoder[Int] { def encode(t: Int) = s"${t}" }
}
```
Then make a macro that summons this using Expr.summon.
```scala
object MyMacro {
  inline def getAndEncode[T](t: T): String = ${ getAndEncodeImpl('t) }
  def getAndEncodeImpl[T: Type](t: Expr[T])(using qctx: Quotes): Expr[String] = {
    import qctx.reflect._
    val enc = 
      Expr.summon[MyEncoder[T]] match
        case Some(enc) => enc
        case None => report.throwError("Can't find encoder")
    '{ $enc.encode($t) }
  }
}
```
Then import the context and use the macro:
```scala
  def doEncoding: Unit = {
    val ctx = new MyContext()
    import ctx.{*, given}
    println(MyMacro.getAndEncode(123))
  }
```

## Output
Compilation fails, report error case "Can't find encoder" is hit.
```
[error] 15 |    println(MyMacro.getAndEncode(123))
[error]    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |            Can't find encoder
```

## Expectation
Compile should work and the given should be correctly summoned.

Note that if instead of using a macro I use a regular method, it will work:
```scala
  def encodeIt[T](t: T)(using enc: MyEncoder[T]) = enc.encode(t)

  def doEncoding: Unit = {
    val ctx = new MyContext()
    import ctx.{*, given}
    println(encodeIt(123))
  }
```
Why the discrepancy?

Also, note that if you declare the given directly in the doEncoding method it will work:
```scala
  def doEncoding: Unit = {
    val ctx = new MyContext()
    given intEncoder: MyEncoder[Int] = new MyEncoder[Int] { def encode(t: Int) = s"${t}" }
    println(MyMacro.getAndEncode(123))
  }
```
Why the discrepancy?

## Code
Full code sample is available here:
https://github.com/deusaquilus/expr_summon_issue

**Comment by deusaquilus** [comment]
If I'm not totally mistaken about this and it's a real issue, RC1 is totally unusable for me 😢

**Comment by deusaquilus** [comment]
Okay, so this doesn't work with object either. Say that I do this:
```scala
object Ctx {
  given intEncoder: MyEncoder[Int] = new MyEncoder[Int] { def encode(t: Int) = s"${t}" }
}
```
Then I do this:
```scala
  def doEncoding: Unit = {
    import Ctx.{given,*}
    println(MyMacro.getAndEncode(123))
  }
```
It does not work either:
```scala
[error] 20 |    println(MyMacro.getAndEncode(123))
[error]    |            ^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |            Can't find encoder
```

**Comment by deusaquilus** [comment]
@nicolasstucki @liufengyun @odersky 
This really, really scares me!
I was building just fine on the Feb 02 build (20210202-8d43a9c-NIGHTLY), then comes the RC1 release and Boom! This bug happens and everything I'm doing is completely broken.
I keep thinking, what if something like this happens in the 3.0.0 release!?

For the 3.0.0 release, can we have some kind of Scala 3 stage-gate making sure Dotty-Quill builds before the release is cut? Dotty-Quill seems to be the only thing constantly blowing up on the metaprogramming bugs in new releases. So it really needs to be double-checked.
Or maybe we bring Dotty-Quill into the Community Build ASAP and do it that way?

**Comment by nafg** [comment]
I think usually a release is an actual release candidate that has no issues
reported for a few weeks

**Comment by nicolasstucki** [comment]
Minimized 
```scala
type MyEncoder

class MyContext:
  given intEncoder: MyEncoder = ???

def doEncoding(ctx: MyContext): Unit =
  import ctx.{*, given}
  summon[MyEncoder]
  summonInlineMyEncoder()

inline def summonInlineMyEncoder(): Unit =
  compiletime.summonInline[MyEncoder]
```

**Comment by SethTisue** [comment]
> maybe we bring Dotty-Quill into the Community Build ASAP and do it that way

that certainly sounds like the right thing to do

**Comment by SethTisue** [comment]
> maybe we bring Dotty-Quill into the Community Build ASAP and do it that way

that certainly sounds like the right thing to do

it's also possible to add latest-Scala-3-nightly to your own CI
