### ISSUE TITLE
Double definition error for unnamed givens

### ISSUE THREAD

**Issue by gregghz** [lampepfl/dotty#11579]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
trait Foo[A]
object Foo {
  given Foo[Int | String] = new Foo[Int | String]{}
  given Foo[Int] = new Foo[Int]{}
}
```

## Output

```scala
Double definition:
final lazy given val given_Foo_Int: Foo[Int | String] in object Foo at line 3 and
final lazy given val given_Foo_Int: Foo[Int] in object Foo at line 4
```

## Expectation

I expected each given to generate non-conflicting names. I wanted to experiment to make sure having a given for `Int` and `Int | String` actually makes sense so I tried both naming the givens and using a type alias for `Int | String` and both seem to work fine and `summon[Foo[Int]]` uses the `Foo[Int]` instance: https://scastie.scala-lang.org/7mPYcZIUTw28EJHoePYO2A.

**Comment by bishabosha** [comment]
here is the implementation for the name generation of anonymous givens:
https://github.com/lampepfl/dotty/blob/d7bbdcd98482a5227af5fe86ed2bcc1882370877/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L991

**Comment by odersky** [comment]
That's not how it is specified and documented.
