### ISSUE TITLE
Context bound desugared at the wrong place in extension method

### ISSUE THREAD

**Issue by rjolly** [lampepfl/dotty#11586]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
trait Conv[T]

extension [T: Conv](x: T)
  def combine (y: T): T = ???
```

## Compiler output with -Xprint:typer

```scala
    extension [T >: Nothing <: Any](x: T) def combine(y: T)(
      implicit evidence$1: test.Conv[T]
    ): T = ???
```

## Expectation

```scala
    extension [T >: Nothing <: Any](x: T)(using x$2: test.Conv[T]) def combine(
      y: T
    ): T = ???
```

, obtained with "using" syntax:

```Scala
extension [T](x: T)(using Conv[T])
  def combine (y: T): T = ???
```

**Comment by odersky** [comment]
The current definition and implementation looks more useful since it allows to pass a `Conv[T]` explicitly.

**Comment by prolativ** [comment]
@odersky IMHO the suggested desugaring makes more sense and it still makes it possible to pass `Conv[T]` explicitly although the order of arguments would be different
```
"abc".combine(using given_Conv_String)("def")
```

**Comment by neko-kai** [comment]
@odersky 
Useful or not, I believe it's unintuitive, irregular and without precedent.

The precedent that `def x[T: U](a: A)` is interchangeable with `def x[T](a: A)(using U[T])` is broken with in a way that's very hard to explain when writing, teaching or even performing code reviews. How would I explain to

**Comment by rjolly** [comment]
@odersky To pass it explicitely you have the developed form `combine("abc")(using given_Conv_String)("def")`.

**Comment by rjolly** [comment]
@odersky I understand it if you don' have time for this, but can we keep the issue open so that others can take over. Thanks!
