### ISSUE TITLE
parsing of braceless for-comprehensions: unify error message for unintended code in various edge cases

### ISSUE THREAD

**Issue by unkarjedy** [lampepfl/dotty#11622]
## Compiler version
3.0.0-RC1

## Minimized code

```Scala
@main
def Main23() = {
    for x <- 0 to 1;
    x <- 0 to 1;
    do println(1)
  
    for 
        x <- 0 to 1
    y <- 0 to 1
    do println(2)
    
    for 
    x <- 0 to 1
  y <- 0 to 1
    do println(3)
}
```

## Output
Note that compilation error "yield or do expected" is only shown for the 2nd `for` and not for the  1st and 3rd

## Expectation
An error should be reported in all 3 cases or in none

![image](https://user-images.githubusercontent.com/3989292/110141864-9e7eeb00-7de6-11eb-93b0-22d987309ffb.png)

**Comment by odersky** [comment]
That's because (1) or (3) don't see an indented region.

**Comment by unkarjedy** [comment]
Still looks awkward that this code is accepted by the compiler:
![image](https://user-images.githubusercontent.com/3989292/110160421-12c48900-7dfd-11eb-9dae-b29944242a96.png)
while the example with indented first enumerator is not.

Taking into account that braceless for-expressions require do/yield keyword maybe it's worth not treating indented region inside enumerators at all?

**Comment by bishabosha** [comment]
I refer to this comment chain - where indentation is not checked when it is unambiguous what context it appears in: https://github.com/lampepfl/dotty/pull/8659#pullrequestreview-387822469
