### ISSUE TITLE
Double definition when method and constructor param have same name

### ISSUE THREAD

**Issue by lihaoyi** [lampepfl/dotty#11639]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
class Foo(length: Int) {
  def length() = ???
}
```

## Output

```scala
[error] -- [E120] Naming Error: /Users/lihaoyi/Github/upickle/core/src/upickle/core/Util.scala:109:6
[error] 109 |  def length() = ???
[error]     |      ^
[error]     |      Double definition:
[error]     |      private[this] val length: Int in class Foo at line 108 and
[error]     |      def length(): Nothing in class Foo at line 109
[error] one error found
[error] one error found
```

## Expectation

It seems to compile fine in Scala 2.13.4

**Comment by smarter** [comment]
But even in Scala 2, this fails:
```scala
class A {
  private[this] val length: Int = 1
  def length(): Int = 1
}
```
The fact that it works in Scala 2 with constructor parameters seems more like a bug than a feature to me.

**Comment by smarter** [comment]
Also you can always rename the constructor parameter to something else without affecting BC, so closing since I don't think it's worth making things more complicated here to emulate Scala 2 perfectly.

**Comment by lihaoyi** [comment]
sounds good, yeah I just renamed it on my side
