### ISSUE TITLE
Add Symbol.info to Quotes.reflect

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#11657]
We seem to have missed this method. Users have been using `sym.tree.tpe` or `sym.tree.tpt` which is not ideal.

**Comment by nicolasstucki** [comment]
To support this we also need to add `ClassInfo`

**Comment by smarter** [comment]
Can this be closed since https://github.com/lampepfl/dotty/pull/11664 was closed given we already have memberInfo?

**Comment by nicolasstucki** [comment]
Yes, I tough I had already closed it.
