### ISSUE TITLE
Removing the magic from dotty.runtime.Arrays

### ISSUE THREAD

**Issue by sjrd** [lampepfl/dotty#1167]
[`dotty.runtime.Arrays`](https://github.com/lampepfl/dotty/blob/master/src/dotty/runtime/Arrays.scala) has a bunch of magic methods, including the very magic `newRefArray`, which is one of the 3 methods that stay generic after erasure.

It is very easy to get rid of this complexity, by given an actual parameter of type `Class[T]` to `newRefArray`:
```scala
def newRefArray[T <: AnyRef](componentType: Class[T], length: Int): Array[T]
```
The back-end still needs to know about this magic method, and "assume" that `componentType` is a `Literal(Constant(tpe))` (i.e., crash if it isn't). **But then the method does not need to be generic anymore after erasure, which is a substantial win, IMO.**

We can remove even more magic by given *actual* bodies to all the `newXArray` method, leveraging `java.lang.reflect.Array.newInstance`:
```scala
def newRefArray[T <: AnyRef](componentType: Class[T], length: Int): Array[T] =
  java.lang.reflect.Array.newInstance(componentType, length).asInstanceOf[Array[T]]

def newByteArray(length: Int): Array[Byte] =
  java.lang.reflect.Array.newInstance(classOf[Byte], length).asInstanceOf[Array[Byte]]

...

def newUnitArray(length: Int): Array[Unit] =
  java.lang.reflect.Array.newInstance(classOf[BoxedUnit], length).asInstanceOf[Array[Unit]]
```
and now the back-end does not *need* to treat these methods specially. Their user-space implementation is perfectly correct.

Of course, on the JVM, that implementation is inefficient, so the JVM back-end would still specialize them. But other back-ends need not have the same problem. For example, Scala.js does not need to specialize those to get full speed, because `Array.newInstance` is intrisified by the optimizer when the `componentType` is a literal `classOf`.

**Comment by DarkDimius** [comment]
@sjrd I was proposing a similar change at one point. Btw, `newByteArray` does not need to use reflection, it could simply call new Array[Byte](n). Same with other primitives.

I do not remember why this proposal was rejected.

**Comment by odersky** [comment]
I agree it would be good to try that change.
