### ISSUE TITLE
Interactive.pathTo shows ImportType for repeated enum case.

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#11683]
## Minimized code

Running:
```scala
val pos = sourcePosition(driver, params, uri)
val trees = driver.openedTrees(uri)
val path = Interactive.pathTo(trees, pos)
val tp = Interactive.enclosingType(trees, pos)
val tpw = tp.widenTermRefExpr
```

on 

```scala
object SimpleEnum:
  enum Color:
    case Re@@d, Green, Blue
```

will produce type tree:

`val tpw = ImportType(Ident(Color))`

## Expectation

We should get a valid type representing the Color enum.

What is weird is that `Interactive.pathTo` gives us:
```scala
path.head == Import(Ident(Color),List(ImportSelector(Ident(Red),EmptyTree,EmptyTree), ImportSelector(Ident(Green),EmptyTree,EmptyTree), ImportSelector(Ident(Blue),EmptyTree,EmptyTree)))
```
while there are no actual imports.

**Comment by bishabosha** [comment]
This may be because the first statement of an enum template in the AST is an import statement of the cases, which is probably overlapping the span for the actual cases.

**Comment by smarter** [comment]
You should be able to set a zero-extent span to that tree so pathTo skips over it.
