### ISSUE TITLE
community-build : illegal file name in project Cask

### ISSUE THREAD

**Issue by michelou** [lampepfl/dotty#11710]
Assignee : @lihaoyi

The addition of the [Cask](https://github.com/com-lihaoyi/cask) project to the community build prevents git operations on a Windows machine (see  [line 229](https://github.com/lampepfl/dotty/blob/e08fd59217265fa76d50eccd5c9594d94a89e0f8/community-build/src/scala/dotty/communitybuild/projects.scala#L229) in file `communitybuild/projects.scala`.

```batch
C:\opt\Git-2.30.2\mingw64\bin\git.exe submodule update --init --recursive --jobs 7
error: invalid path 'docs/pages/1 - Cask: a Scala HTTP micro-framework.md'
Unable to checkout '93c27abe583c2b804e5ce66271440789fca0581a' in submodule path 'community-build/community-projects/cask'
```

Directory [`cask/docs/pages/`](https://github.com/com-lihaoyi/cask/tree/master/docs/pages) contains 3 Markdown files.
The name of the first file, namely `1 - Cask: a Scala HTTP micro-framework.md`, is illegal on Windows because it contains a colon character.

**PS.** Furthermore one should avoid spaces in file names (e.g. [*Is it problematic to include spaces in file names?*](https://qanda.digipres.org/1053/is-it-problematic-to-include-spaces-in-file-names)).

**Comment by eed3si9n** [comment]
Why am I assigned this?

**Comment by michelou** [comment]
> Why am I assigned this?

Sorry. My mistake.

**Comment by jodersky** [comment]
That's annoying indeed. I think it can be fixed upstream without an issue, but if this is super high prio, you can just remove the file from the community build for now.
