### ISSUE TITLE
Scala3 releases with uppercase letters (RC1) not working well with Github packages

### ISSUE THREAD

**Issue by ilijaljubicic** [lampepfl/dotty#11717]
Maven naming convection requires artifactId to be lowercase letters:
https://maven.apache.org/guides/mini/guide-naming-conventions.html

Scala3 release candidates are using upper case letters: 3.0.0-RC1

That results in any package published for scala3 also to get artifactId with the suffix that has uppercase letters.
If such a library is to be published to Github packages, that follow Maven naming convection strictly, it doesn't work.
It is not possible to publish library build for scala3-RC1 to Github packages.

Would it be possible to use lowercase letters for release candidates scala3 packages?

**Comment by sjrd** [comment]
We can't do that. The entire ecosystem of tools has been working under the assumption that any `x-y` release uses exactly `x-y` as the binary version number, and hence as artifact name. We cannot change that without breaking zillions of tools.

Also, this is not specific to Scala 3. This has been the case since forever with Scala 2 M's and RC's as well.

**Comment by SethTisue** [comment]
Is there a ticket on the GitHub side, asking if they could relax their restriction?

**Comment by ilijaljubicic** [comment]
It looks like they started to be more strict last year, the only ticket I have found in regards to it was:
https://github.community/t/error-cannot-upload-package-with-uppercase-letters-in-artifactid/136637

I haven't open any ticker myself, since I thought of trying here first as it is not a bug on their side or anything (nor there was any response in issue indicating it could change).

Anyhow, knowing that scala3 is going to be GA released soon, should be ok.
