### ISSUE TITLE
non-informative error message for a `transparent` soft keyword with multiple new lines after it

### ISSUE THREAD

**Issue by unkarjedy** [lampepfl/dotty#11712]
## Compiler version
3.0.0-RC1

## Minimized code

```Scala
def transparent = println("transparent method called")

transparent
println()
inline def f1 = 1

transparent
inline def f2 = 2

transparent
trait T1

transparent

inline def f3 = 3

transparent

def f4 = 4

transparent

trait T2
```

## Output
Ther actually IS "start of definition" though the error says that there is no

![image](https://user-images.githubusercontent.com/3989292/110936706-5f025280-8342-11eb-89b6-6c5511efabb1.png)

## Expectation
More informative message?  (maybe better parsing? not sure)

**Comment by odersky** [comment]
If there are multiple newlines after `transparent` it's an identifier, not a soft keyword.

**Comment by unkarjedy** [comment]
@odersky 
from https://dotty.epfl.ch/docs/reference/soft-modifier.html
>A soft modifier is treated as potential modifier of a definition if it is followed by a hard modifier or a keyword combination starting a definition (def, val, var, type, given, class, trait, object, enum, case class, case object). **Between the two words there may be a sequence of _newline_ tokens and _soft modifiers_.**

Which contradicts to:
>If there are multiple newlines after transparent it's an identifier, not a soft keyword.

Also, if so, why the compiler then says "expected start of definition" and doesn't treat `transparent` as a function call at those places?

```scala
object A {
  def transparent: Int = {
    println("transparent method called")
    42
  }

  transparent
  println()

  transparent
  inline def f1 = 2

  transparent

  inline def f2 = 2
  
  transparent

  def f3 = 2
}
```

![image](https://user-images.githubusercontent.com/3989292/162930501-770322eb-a855-42ca-a214-dce767b8a165.png)

It seems that implementation should be patched in any case.
And specification should probably also be reviewed.

**Comment by som-snytt** [comment]
Thanks, unkarjedy.

I had to re-read the spec (both of them). All the `[nl]` vs `{nl}` vs nl not enabled is tricky. So glad it usually just works.

I see that the language about "sequence of newline tokens and soft mods" could be misconstrued as "arbitrary sequence". Probably it just means they can be "stacked".

I agree intuitively that if `transparent` is not taken softly as a keyword, it must be an ordinary identifier.

Here, `transparent<nl><nl>` is taken as a hard error, apparently.

As an aspirational footnote, it would be nice to visualize `nl` insertion, the way IDEs will make whitespace visible.

It's worth adding that "people don't write code like this", except when they are in the middle of an edit. Extra feedback might be helpful or annoying, depending on personal preferences.

**Comment by som-snytt** [comment]
I intended to agree with you, and say the "orphan" `transparent` should bind to your definition in scope.

I also think the phrase "sequence of newlines" you pointed out in the reference should be more specific (and in the grammar). However, although I periodically re-read the rules about newlines, I never retain them; I rely just on common practices or style.

**Comment by unkarjedy** [comment]
Ok, why I am asking is that I am trying to understand whether it is ok to continue keeping this ticket as "Closed" if any clarifications in the spec are going to be made

**Comment by odersky** [comment]
@unkarjedy I think you are right, it needs a clarification or a software fix. 

Maybe it's simplest to try a software fix to accept these as soft modifiers.
