### ISSUE TITLE
TypeTest doc page missing from sidebar

### ISSUE THREAD

**Issue by dwijnand** [lampepfl/dotty#11727]
I thought I was going insane... but I finally concluded that I can never find it because it's actually missing.

https://dotty.epfl.ch/docs/reference/other-new-features/type-test.html

see the sidebar if you look at, for instance, https://dotty.epfl.ch/docs/reference/other-new-features/trait-parameters.html

**Comment by bishabosha** [comment]
will be fixed by #11679
