### ISSUE TITLE
f interpolator doesn't process backslash escapes

### ISSUE THREAD

**Issue by lrytz** [lampepfl/dotty#11750]
Scala 2:

```
scala> f"yes\\\no"
val res0: String =
yes\
o
```

Scala 3:

```
scala> f"yes\\\no"
val res0: String = yes\\\no
```

**Comment by odersky** [comment]
I don't think it's the parser. Interpolated strings do not process "\" escapes. That's for the interpolator to do. Or did I get that wrong?

**Comment by lrytz** [comment]
yes, the interpolator should handle the escapes. i haven't checked why it doesn't do so in dotty

**Comment by odersky** [comment]
Why is this a "transform" issue? Isn't the F-interpolator a macro?

**Comment by abgruszecki** [comment]
Assigning Nico, since his student worked on the interpolator.

**Comment by som-snytt** [comment]
By coincidence, my dotty repo is on the branch for https://github.com/lampepfl/dotty/issues/9939 where I've only collected examples of divergent behavior. Every 6 months or so, I intend to take a look.

**Comment by smarter** [comment]
It used to be a macro but it's been intrinsified in the compiler: https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/localopt/StringContextChecker.scala

**Comment by nicolasstucki** [comment]
We still want to port the Scala 2 implementation of the `f` interpolation checker. We should probably not fix this one and just port it, which should fix the issue.

**Comment by nicolasstucki** [comment]
Same solution as in https://github.com/lampepfl/dotty/issues/9939#issuecomment-703513897
