### ISSUE TITLE
Tuple concatination match type unexpectedly includes reference name.

### ISSUE THREAD

**Issue by esarbe** [lampepfl/dotty#11762]
## Compiler version
3.0.0-RC1

## Minimized code

```Scala
@main
def madfin() = {
  
  val f = (1,2,3)
  val g = ("a", "b")
  
  val h: 1 = f ++ g
}
```

## Output

```scala
Found:    Tuple.Concat[(Int, Int, Int), (g : (String, String))]
Required: (1 : Int)
```

## Expectation
```
Found:    Tuple.Concat[(Int, Int, Int), (String, String)]
```

I did not expect the match type to include the reference name `g`. Why would it be present for the second tuple and not for the first one?

(Is it possible to access the name of the reference in the type somehow?)

**Comment by bishabosha** [comment]
`(g : (String, String)` is the representation in errors of the type `g.type`, which means "the type of the value stored in `val g`, which is a `(String, String)`"

**Comment by esarbe** [comment]
That's interesting. Why is there no corresponding `(f : (Int, Int, Int)` in the error?
