### ISSUE TITLE
Patmat on type member loses bounds

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11783]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
  def x[A](using Quotes, Type[A]) =
    Expr.summon[Mirror.Of[A]] match {
      case Some('{ $m: Mirror.ProductOf[A] { type MirroredElemTypes = types } }) =>
        compiletime.summonAll[types]
    }
```

## Output

```
[error] 44 |        compiletime.summonAll[types]
[error]    |                              ^
[error]    |               Type argument types does not conform to upper bound Tuple
```

## Expectation

It should compile.

The signature of `summonAll` is:

```scala
  inline def summonAll[T <: Tuple]: Widen[T] =
```

and you can see in the definition of `Mirror` that `MirroredElemTypes` has an upper bound of `Tuple`:

```scala
sealed trait Mirror {

  /** The mirrored *-type */
  type MirroredMonoType

  /** The name of the type */
  type MirroredLabel <: String

  /** The names of the product elements */
  type MirroredElemLabels <: Tuple
}
```

**Comment by nicolasstucki** [comment]
You should not be using compile-time operations within the implementation of a macro as those operations are by-definition executed before we know the actual type of `types`. You need to use the `Quotes` API.

The code you need will probably be similar to [elemTypesToExprs](https://github.com/lampepfl/dotty/blob/master/tests/run-macros/quoted-ToExpr-derivation-macro/Derivation_1.scala#L17) in that example. Note that this file contains code to derive a macro implementation and some parts of it are overkill for most use-cases.

**Comment by nicolasstucki** [comment]
One way is to do 
```scala
  private def summonAllExpr[X: Type](using Quotes): List[Expr[Any]] =
    Type.of[X] match
      case '[ head *: tail ] => summonExprOrError[ToExpr[head]] :: elemTypesToExprs[tail]
      case '[ EmptyTuple ] => Nil

  private def summonExprOrError[T: Type](using Quotes): Expr[T] =
    Expr.summon[T] match
      case Some(expr) => expr
      case None =>
        quotes.reflect.report.throwError(s"Could not find implicit ${Type.show[T]}")
```

**Comment by nicolasstucki** [comment]
The other is to tell the pattern matching that we expect a tuple
```
      case Some('{ type types <: Tuple ; $m: Mirror.ProductOf[A] { type MirroredElemTypes = `types` } }) =>
```
Then you can refine the previous definition to
```scala
private def summonAllExpr[X: Type <: Tuple](using Quotes): List[Expr[Any]] =
    Type.of[X] match
      case '[ head *: tail ] => summonExprOrError[ToExpr[head]] :: elemTypesToExprs[tail]
      case '[ EmptyTuple ] => Nil
      case _ =>
        quotes.reflect.report.throwError(s"${Type.show[T]} is not fully a known tuple type")
```

**Comment by japgolly** [comment]
Big thanks for that response @nicolasstucki !

> You should not be using compile-time operations within the implementation of a macro

Do you think it would be worth having scalac detect that and emit a warning?
