### ISSUE TITLE
Can't create Expr inside quotes

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11796]
## Compiler version

3.0.0-RC2-bin-20210317-758782a-NIGHTLY

## Minimized code

```Scala
  def hmm1(i: Expr[Int])(using Quotes): Expr[Int] = {
    val j = 1
    '{ $i + ${Expr(j)} } // error
  }

  def hmm2(i: Expr[Int])(using Quotes): Expr[Int] = {
    val j = Expr(1)
    '{ $i + $j } // ok
  }
```

## Output

```scala
[error] 36 |    '{ $i + ${Expr(j)} }
[error]    |                     ^
[error]    |ambiguous implicit arguments: both parameter evidence$7 and parameter x$2 match type quoted.Quotes of parameter x$3 of method apply in object Expr
```

## Expectation

It should compile.

According to https://dotty.epfl.ch/docs/reference/contextual/derivation-macro.html it should work because there are similar examples shown like:

```scala
        val e1 = '{$x.asInstanceOf[Product].productElement(${Expr(index)})}
        val e2 = '{$y.asInstanceOf[Product].productElement(${Expr(index)})}
```

**Comment by smarter** [comment]
It won't work with `-source:3.0-migration` since that enables the Scala 2 implicit rules, are you using that option?

**Comment by japgolly** [comment]
Yes I am!

Ok I'll try without that option although if the rest of the stuff I'm cross-compiling starts failing I may cry.

**Comment by japgolly** [comment]
Yeah that does it, it compiles fine without `"-source:3.0-migration"`. Thanks @smarter !
