### ISSUE TITLE
opaque type selects different method with -from-tasty 

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#11819]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
package opaquetypes

object `package`:

  opaque type Foo = Double

  object Bar:

    class Baz(val i: Foo):
      def foo(that: Any): Boolean = that match
        // `Double.==` selected from source; `Any.==` selected `-from-tasty`
        case that1 @ (_: Baz) => Baz.this.i == that1.i
        case _ => true
```

## Expectation

`Double.==` should also be selected with `-from-tasty`, the issue arises when if you actually select `Double.==` in unpickling then the checker does not expect it

**Comment by bishabosha** [comment]
@smarter this one is a problem because at the point of pickling, `Baz.this.i.==` resolves to the symbol `Double.==`, but at the point of unpickling `qualType.findMember("==")` would find `Any.==`, same with `TreeChecker`

**Comment by smarter** [comment]
Shouldn't findMember find both and pick the one from Double since it has the correct signature?

**Comment by bishabosha** [comment]
@smarter no, it gets `NoDenotation`
```scala
def accessibleDenot(qualType: Type, name: Name, sig: Signature, target: Name) = {
  val pre = ctx.typeAssigner.maybeSkolemizePrefix(qualType, name)
  val d = qualType.findMember(name, pre).atSignature(sig, target)
  if ctx.settings.YstrictTasty.value then
    report.echo(i"$qualType.$name unpickle from select is denot $d (sig is $sig)")
  if (!d.symbol.exists || d.symbol.isAccessibleFrom(pre)) d
  else qualType.findMember(name, pre, excluded = Private).atSignature(sig, target)
}
```
we get the log message
```scala
(Baz.this.i : opaquetypes.Foo).== unpickle from select is denot NoDenotation (sig is Signature(List(scala.Double),scala.Boolean))
```

**Comment by smarter** [comment]
I think https://github.com/dotty-staging/dotty/commits/thisType-check fixes the problem, can you double-check and take care of integrating it in your PR (sameThis should probably be a method in ThisType...).

**Comment by bishabosha** [comment]
> I think https://github.com/dotty-staging/dotty/commits/thisType-check fixes the problem, can you double-check and take care of integrating it in your PR (sameThis should probably be a method in ThisType...).

I just tried and it worked, very cool
