### ISSUE TITLE
ClassSymbol API missing from Quotes API

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11811]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
// with some given type T
println(TypeRepr.of[T].classSymbol.get.getClass)
println(TypeRepr.of[T].classSymbol.get.isTrait) // doesn't compile
```

## Output

First `println` returns:
```
class dotty.tools.dotc.core.Symbols$ClassSymbol
```

Second wont compile because:

```
[error] 60 |            println(TypeRepr.of[T].classSymbol.get.isTrait)
[error]    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |                    value isTrait is not a member of x$2.reflect.Symbol
```

## Expectation

ClassSymbol API should be available. The methods in see in `scala-backend/src/reflect/scala/reflect/api/Symbols.scala` are exactly what I need to use.

**Comment by smarter** [comment]
>  The methods in see in scala-backend/src/reflect/scala/reflect/api/Symbols.scala

You're looking at the wrong file, scala-backend is a now-deleted submodule that contained the Scala 2 repository (I guess you have an old clone of dotty and submodules don't get automatically deleted when pulling changes).

Anyway you should be able to do `classSymbol.flags.is(Flags.Trait)`.

**Comment by japgolly** [comment]
Oh my bad, thanks so much @smarter
