### ISSUE TITLE
Regression: class with no object shadows outer object

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11853]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
sealed trait Children
object Children {
  sealed trait None extends Children
  sealed trait Varargs extends Children
}

sealed abstract class CtorType {
  type ChildrenType <: Children
}

object CtorType {
  final class X() extends CtorType {
    override type ChildrenType = Children.None
  }

  final class Children() extends CtorType {
    override type ChildrenType = Children.Varargs
  }
}
```

## Output

```
-- Error: x.scala:13:33 --------------------------------------------------------
13 |    override type ChildrenType = Children.None
   |                                 ^^^^^^^^
   |        Reference to creator proxy for class Children in object CtorType
   |        shadows outer reference to object Children
-- Error: x.scala:17:33 --------------------------------------------------------
17 |    override type ChildrenType = Children.Varargs
   |                                 ^^^^^^^^
   |        Reference to creator proxy for class Children in object CtorType
   |        shadows outer reference to object Children
2 errors found
```

## Expectation

It should compiles as it does in Scala 2.x.

**Comment by smarter** [comment]
The error message calls them _creator proxy_ when they're now called _constructor proxy_ so it's a bit confusing but this is a feature, not a bug: http://dotty.epfl.ch/docs/reference/other-new-features/creator-applications.html, every class gets a synthetic companion with a synthetic apply method, so the shadowing is unavoidable.

**Comment by som-snytt** [comment]
The bug may be where the spec turns to their date in the darkened theater and whispers with menacing assurance:

> and there is also no other value or method named C defined or inherited in the scope where C is defined.

**Comment by japgolly** [comment]
@smarter Damn I thought the new auto-`new`-thingy worked by synthesising `new X` at call-site, not synthesising an object with an apply method like case classes. Maybe the doc was older when I last read it or maybe I'm just misremembering. np

What do you think about saying "companion object" in the error message instead? From a user's pov I understand that a `case class` results in a synthesised `object` and now I see that in Scala 3, the same thing happens for normal classes too. No point, and a bit confusing having a different name for the synthesised `object`. I can create a PR if you're happy with such a change?

**Comment by som-snytt** [comment]
I also expected the new `new` was just `new`. I see it is rewritten early, says `-Xprint:all`.

**Comment by Jasper-M** [comment]
But "constructor proxy companions cannot be used as values by themselves".

The documentation also says:

>Scala case classes generate apply methods, so that values of case classes can be created using simple function application, without needing to write new.
>
>Scala 3 generalizes this scheme to all concrete classes.

It's nice that Scala 3 thinks of the poor StackOverflow answerers who came in after all the high-reputation answers were already taken. Some nice generalizations with enough differences to thoroughly confuse people should do the trick.
