### ISSUE TITLE
Compiler forgets that scala.scalajs.js.UndefOr is covariant

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11865]
## Compiler version

3.0.0-RC1 with Scala.JS 1.5.0

## Minimized code

This reproduction requires Scala.JS 1.5.0:

```scala
import scalajs.js.UndefOr

final class X[+A] {
  def hmmm: UndefOr[A] = ???
}
```

I tried to make a reproduction without Scala.JS (see below) but I couldn't get the bug to occur.

```scala
package object js {
  import scala.annotation.unchecked.uncheckedVariance
  sealed trait |[A, B]
  type UndefOr[+A] = (A @uncheckedVariance) | Unit
}

import js.UndefOr

final class X[+A] {
  def hmmm: UndefOr[A] = ???
}
```

## Output

```
[error] 4 |  def hmmm: UndefOr[A] = ???
[error]   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |covariant type A occurs in invariant position in type => scala.scalajs.js.UndefOr[A] of method hmmm
```

## Expectation

It should compile (and does with Scala 2.x) because `UndefOr` is covariant.

/cc @sjrd

**Comment by japgolly** [comment]
`UndefOr` declaration in Scala.JS 1.5.0: https://github.com/scala-js/scala-js/blob/v1.5.0/library/src/main/scala/scala/scalajs/js/package.scala#L85

**Comment by smarter** [comment]
I don't know what's going on here but you should try again with a nightly since we completely changed how Scala.js unions work in Scala 3 (they're regular Scala 3 unions now): https://github.com/lampepfl/dotty/blob/d4f1c261f808b185f91bb3e6f3efebd25c39646f/compiler/src/dotty/tools/dotc/sbt/ExtractAPI.scala#L619-L695

**Comment by japgolly** [comment]
@smarter You're right! This compiles no problem with `3.0.0-RC2-bin-20210322-4035f51-NIGHTLY`
