### ISSUE TITLE
wrong error for method with name `inline`: inline must be followed by an `if` or a `match`

### ISSUE THREAD

**Issue by unkarjedy** [lampepfl/dotty#11860]
## Compiler version
3.0.0-RC2-bin-20210317-758782a-NIGHTLY

## Minimized code

```Scala
object SoftModifierTests {
  def main(args: Array[String]): Unit = {
    def inline(): Unit = println("do some work...")
    inline()
  }
}
```

## Output
Error
```scala
`inline` must be followed by an `if` or a `match`
    inline()
```

## Expectation
According to the spec https://dotty.epfl.ch/docs/reference/soft-modifier.html inline should be treated as a normal identifier:
- it's not followed by `if` or `match`
- it's not followed by parameter definition
- it's not followed by hard modifier 
- it's not followed by  `class`, `trait`, etc...
- > Everywhere else a soft keyword is treated as a normal identifier

and the code should compile

![image](https://user-images.githubusercontent.com/3989292/112146527-ba5afd00-8bec-11eb-899c-ba19b72daaae.png)

**Comment by nicolasstucki** [comment]
Seems to be working on master.

**Comment by unkarjedy** [comment]
checked with:
```
scalaVersion := "3.0.0-RC2-bin-20210320-0195dff-NIGHTLY",
scalaVersion := "3.0.0-RC2-bin-20210322-4035f51-NIGHTLY",
```

seeing the same error

**Comment by nicolasstucki** [comment]
We need to fix this branch of the parser https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L2002

**Comment by odersky** [comment]
The docs promised too much here. The problem is that the parser would need unlimited lookahead to decode whether `inline` is followed by a `match`. I changed the doc page to conform to the Parser's behavior.
