### ISSUE TITLE
Unreducible application of HKT in alias to `F[F[?]]`

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11889]
## Compiler version

3.0.0-RC2-bin-20210325-eeb8340-NIGHTLY

## Minimized code

```Scala
type X1[A] = List[A]
type Y1    = X1[?]
type Z1    = List[?]

type X2[A] = List[List[A]]
type Y2    = X2[?] // error
type Z2    = List[List[?]]
```

## Output

```
[error] -- [E043] Type Error: /home/golly/scala3bug/sbt/src/main/scala/BUG.scala:6:13 --
[error] 6 |type Y2    = X2[?] // error
[error]   |             ^^^^^
[error]   |unreducible application of higher-kinded type [A] =>> List[List[A]] to wildcard arguments
```

## Expectation

It should compile.

**Comment by odersky** [comment]
It won't compile in Scala 3. Y2 is the same as `List[List[A]] forSome { type A }` which is an existential type and existential types are not supported in Scala 3. Z2 is `List[ List[A] forSome { type A } ]`, which can be represented as a Java wildcard type.
