### ISSUE TITLE
first case clause after `catch` shouldn't be parsed if `case` is indented and starts on a new line

### ISSUE THREAD

**Issue by unkarjedy** [lampepfl/dotty#11905]
## Compiler version
3.0.0-RC2-bin-20210320-0195dff-NIGHTLY

## Minimized code
When a case clause starts from a new line and `case` is unintended an error should be reported same as for `match`
```Scala
def foo = {
    try 42 catch
  case _: RuntimeException => 11
}
```

I suppose the bug is related to special single-line catch handling:
http://dotty.epfl.ch/docs/reference/other-new-features/control-syntax.html
>A catch can be followed by a single case **on the same line**. 
If there are multiple cases, these have to appear within braces (just like in Scala 2) or an indented block.

All-in-one example with `catch` and `match`:
```scala
val x = 2

object Wrapper1 {
    x match
    case 1 => print("I")
    case 2 => print("II")

    try 42 catch
    case _: RuntimeException => 11
    case _: AssertionError => 22
}


object Wrapper2 {
    x match
  case 1 => print("I")
}

object Wrapper3 {
    x match
  case 1 => print("I")
  case 2 => print("II")
}

object Wrapper4 {
    try 42 catch
  case _: RuntimeException => 11
}

object Wrapper5 {
    try 42 catch
  case _: RuntimeException => 11
  case _: AssertionError => 22
}
```

![image](https://user-images.githubusercontent.com/3989292/112624875-38aedd80-8e3f-11eb-9a4e-c835f9b111cd.png)
![image](https://user-images.githubusercontent.com/3989292/112624915-46fcf980-8e3f-11eb-96ca-24addc2386e8.png)

**Comment by unkarjedy** [comment]
Also, looks like in this example:

```scala
1 match
    case 1 => println(11)
      4 match
    case 2 => println(22)
```
some error should be shown for the nested pattern matching `4 match`
But `case 2` is parsed as it's child (even though it's unindented) and no error is shown.
If there is no code after `case  =>` the error is shown through:

![image](https://user-images.githubusercontent.com/3989292/112629613-97775580-8e45-11eb-9b4e-831917727d11.png)

```scala
1 match
    case 1 => println(11)
      println(111)
    case 2 => println(22)

1 match
    case 1 => println(11)
      4 match
    case 2 => println(22)

2 match
    case 1 => println(11)
      4 match
    case 2 => println(22)

// no code after =>
2 match
    case 1 =>
      44 match
    case 2 => println(22)

def foo = {
    444 match
  case 2 => println(22)
}
```

**Comment by odersky** [comment]
I don't think this is a bug, actually. This is indeed a catch with a single case clause, which has special syntax: 
```
try Body catch case handler
```
There's nothing in that syntax that prescribes a special indentation scheme.

**Comment by unkarjedy** [comment]
The specification says that special syntax for catch with a single case clause is only available when the case is **on the same line with catch**:
>A catch can be followed by a single case **on the same line**

So it looks like a bug.

Handling a single case on a **new line** in a special way looks quite wired.
It looks like an indentation region should be started after `catch` + `new line`, but:
when you have a single unindented case it's not an error "for some reason" 
when you have multiple unindented cases an error is shown for the second case clause

**Comment by unkarjedy** [comment]
@odersky 
Could you comment ^, please?
Seems that something should be changed: spec or impl.
