### ISSUE TITLE
Type inference fails for anonymous lambda param

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/dotty#11906]
## Compiler version

3.0.0-RC1
This problem also occurs on current master

## Minimized code

```Scala
package inference

def test(): Boolean = {
    Seq(true, false).exists(_)
}
```

## Output

```
[error] -- [E007] Type Mismatch Error: /home/fzybala/scala3bench/scala3/src/main/scala/Inference.scala:4:4 
[error] 4 |    Seq(true, false).exists(_)
[error]   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |    Found:    (Boolean => Boolean) => Boolean
[error]   |    Required: Boolean
```

## Expectation
Semantically the same code but with explicitly defined param compiles.
```Scala
package inference

def test(): Boolean = {
    Seq(true, false).exists(p => p)
}
```

**Comment by smarter** [comment]
This isn't an inference issue, the behavior of `_` is purely syntactic: `Seq(true, false).exists(_)` desugars to `x => `Seq(true, false).exists(p)`, for details on how the placeholder syntax works, see the spec: https://www.scala-lang.org/files/archive/spec/2.13/06-expressions.html#placeholder-syntax-for-anonymous-functions
