### ISSUE TITLE
Reference documentation : location of indentation-experimental.md

### ISSUE THREAD

**Issue by michelou** [lampepfl/dotty#11901]
@odersky added the Markdown file [`indentation-experimental.md`](https://github.com/lampepfl/dotty/blob/master/docs/docs/reference/other-new-features/indentation-experimental.md) to directory [`docs/reference/other-new-features/`](https://github.com/lampepfl/dotty/tree/master/docs/docs/reference/other-new-features).

It should belong to directory [`docs/reference/experimental/`](https://github.com/lampepfl/dotty/tree/master/docs/docs/reference/experimental).

My proposition : 
1) rename file `other-new-features/indentation-experimental.md` to `experimental/fewerbraces.md` (similiar to `canthrow.md`).
2) add a cross-reference to file [`other-new-features/indendation.md`](https://github.com/lampepfl/dotty/blob/master/docs/docs/reference/other-new-features/indentation.md) (your input for the wording is welcome).

*Note:* @odersky I can create a PR if you agree with the proposed change.

**Comment by odersky** [comment]
I think we can leave it where it is since it is referred to from indentation. It hopefully won't stay experimental for long.
