### ISSUE TITLE
Standarize scaladoc parameters between Scala2 and Scala3

### ISSUE THREAD

**Issue by BarkingBad** [lampepfl/dotty#11907]
We should standarize the options that can be used for scaladoc. This task is supposed to track compatibility between these two tools:

| Scala2 | Scala3 | Description | Comment | Is implemented?
| ------------- | ------------- | --- | --- | --- |
| -doc-format | _ | Selects in which format documentation is rendered. | Actually old scaladoc supports only html, so it is in some way coherent with new scaladoc, which provides only html | ❌ | 
| -doc-title | -project | The overall name of the Scaladoc site | Aliased in [#11965](https://github.com/lampepfl/dotty/issues/11965) | ✅ | 
| -doc-version | -project-version | | Aliased in [#11965](https://github.com/lampepfl/dotty/issues/11965)  | ✅ | 
| -doc-footer | _ | A footer on every Scaladoc page, by default the EPFL/Lightbend copyright notice. Can be overridden with a custom footer. | Fixed by [#11965](https://github.com/lampepfl/dotty/issues/11965) | ✅ | 
| -doc-no-compile | _ | A directory containing sources which should be parsed for docstrings without compiling (e.g. AnyRef.scala) | We don't need this as we have completely different approach to that issue using -Ydocument-synthetic-types flag for synthetic types | ✅ | 
| -doc-source-url | -source-links | A URL pattern used to link to the source file, with some variables supported... | Scala3 implementation provides richer syntax. | ✅ |
| -doc-external-doc | -external-mappings | Comma-separated list of classpath_entry_path#doc_URL pairs describing external dependencies. | Scala3 implementation provides richer syntax. | ✅ |
| -jdk-api-doc-base | -external-mappings | URL used to link Java API references. | You can specify jdk via -external-mappings since they are generalized setting. | ✅ |
| -doc-generator | _ | The fully qualified name of a doclet class, which will be used to generate the documentation | We don't need this in Scala3 |  ✅ |
| -doc-root-content | -doc-root-content | The file from which the root package documentation should be imported. | |  ✅ |
| -implicits | _ |  | We don't need this in Scala3 | ✅ |
| -implicits-debug | _ |  | We don't need this in Scala3 | ✅ |
| -implicits-show-all | _ |  | We don't need this in Scala3 |  ✅ |
| -implicits-sound-shadowing | _ |  | We don't need this in Scala3 |  ✅ |
| -implicits-hide | _ |  | We don't need this in Scala3 |  ✅ |
| -diagrams | _ |  | We don't need this in Scala3? | ✅: |
| -diagrams-debug | _ |  | We don't need this in Scala3? | ✅ |
| -diagrams-dot-path | _ |  | We don't need this in Scala3? |  ✅ |
| -diagrams-max-classes | _ |  | We don't need this in Scala3? |  ✅ |
| -diagrams-max-implicits | _ |  | We don't need this in Scala3? | ✅ |
| -diagrams-dot-timeout | _ |  | We don't need this in Scala3? | ✅ |
| -diagrams-dot-restart | _ |  | We don't need this in Scala3? |  ✅ |
| -author | _ |  | Fixed by [#11965](https://github.com/lampepfl/dotty/issues/11965) | ✅ | 
| -raw-output | _ |  | We don't need this in Scala3 | ✅ |
| -no-prefixes | _ |  | We don't need this in Scala3 | ✅ |
| -skip-packages | -skip-packages |  |  | ✅ |
| -no-link-warnings | _ | | | ✅ |
| -expand-all-types | _ | | Setting should be removed from Scala2 scaladoc | ✅ |
| -groups | _ | | ~~Implement grouping as it is in Scala3. #11909~~ Actually we support grouping, e. g. [Future](https://scala3doc.virtuslab.com/pr-master/scala3/api/scala/concurrent/Future.html). Since one is using `@group` to actually group his methods, we should consider whether this flag is necessary. Fixed by [#11965](https://github.com/lampepfl/dotty/issues/11965) | ✅ | 
| -no-java-comments | _ |  | We don't need this in Scala3 |  ✅ |
| -doc-canonical-base-url | _ |  A base URL to use as prefix and add `canonical` URLs to all pages. The canonical URL may be used by search engines to choose the URL that you want people to see in search results. If unset no canonical URLs are generated. | Fixed by [#11965](https://github.com/lampepfl/dotty/issues/11965) | ✅ | 
| -private | _ | Show all types and members. Unless specified, show only public and protected types and members. | Fixed by [#11965](https://github.com/lampepfl/dotty/issues/11965) | ✅ | 
| _ | -siteroot | | We don't migrate it | ✅ |
| _ | -project-logo | | Should we migrate it? | ✅ |
| _ | -comment-syntax | | We don't migrate it | ✅ |
| _ | -revision | | Should we migrate it? | ✅ |
| _ | -social-links | | Should we migrate it? | ✅ |
| _ | -skip-by-id | | We don't migrate it | ✅ |
| _ | -skip-by-regex | | We don't migrate it | ✅ |
| _ | -snippet-compiler-args | | We don't migrate it | ✅ |
| _ | -Ydocument-synthetic-types | Documents intrinsic types e. g. Any, Nothing. Setting is useful only for stdlib  |  | ✅ |

**Comment by BarkingBad** [comment]
More info can be found here https://contributors.scala-lang.org/t/standarization-od-scaladoc-settings/4987

**Comment by julienrf** [comment]
Would you be interested in moving the content from here to https://github.com/scala/docs.scala-lang/tree/main/_overviews/scala3-migration?

**Comment by BarkingBad** [comment]
Yeah, I can do that, however I have very little time recently, so I will postpone it for a while if you don't mind

**Comment by BarkingBad** [comment]
Updated PR at https://github.com/scala/docs.scala-lang/pull/2012

**Comment by BarkingBad** [comment]
We should implement `-no-link-warnings` flag then this issue could be closed

**Comment by BarkingBad** [comment]
Need to update docs for:
- `-no-link-warnings`
- snippet compiler
- inkuire
- `-d`
