### ISSUE TITLE
Matching strings should emit switches (as in Scala 2)

### ISSUE THREAD

**Issue by harpocrates** [lampepfl/dotty#11923]
This was initially reported in https://github.com/scala/bug/issues/11740, then fixed in https://github.com/scala/scala/pull/8451, but never ported to Dotty (perhaps because the changes collide a little without the new pattern matching).

I would expect the following to compile into a `lookupswitch` based on the `hashCode` of the cases, as it does in Scala 2 (and as Java, Kotlin, etc. also do).

```Scala
def testMatch(s: String): Int = (s: @switch) match {
  case "S0" => 123
  case "S1" => 121
  case "S2" => 193
  case "S3" => 223
  case "S4" => 423
  case "S5" => 153
  case "S6" => 143
  case "S7" => 133
}
```

To further confuse the story, [this comment](https://github.com/lampepfl/dotty/blob/c0b3fde1dbe9a8ef3b87ddfaa873ea945beafa8c/compiler/src/dotty/tools/backend/sjs/JSCodeGen.scala#L2866-L2880) from the JS codgen appears to suggest that at some point the Scala.js backend would've received and emitted a `switch` over strings (although I can't reproduce that behavior, even on Scala 2 and with `@switch` supposedly claiming a switch will be emitted).

**Comment by harpocrates** [comment]
I'm going to take a stab at this, but I'm opening an issue anyways in case I run out of steam (since this really should be addressed).

**Comment by nicolasstucki** [comment]
@sjrd should we keep those matched as `Match` trees in the `PatternMatcher` and then compile them to bytecode in the backend directly. Or, should we transform the match into a match on the `hashCode` in `PatternMatcher` and keep the switches on `Int` for the backend. What is simpler for Scala.js? I would assume the second option.

**Comment by sjrd** [comment]
We should do as Scala 2 does, i.e., keep those as `Match` trees in the `PatternMatcher`, and then compile them to bytecode in the backend directly. Scala.js has its own way of compiling those, which does *not* use the `hashCode`.

**Comment by bishabosha** [comment]
I started with ef06795d8d25ea10911fc0b7bb803ad3fe80282e but never got to refining it
