### ISSUE TITLE
Give readable error message in case required classes in Definitons are missing

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1192]
if eg, DottyPredef is absent at the classpath, you get a very nasty stacktrace:
https://gist.github.com/densh/73f4b27ae6385599aae85a4b4c81c077

Knowing the details of compiler internals, it's easy for me to see what went wrong, but it's not for someone who is just doing first steps in playing with dotty compiler.

I would be good if we reported a readable error instead and aborted compilation.
This could potentially be done even before parsing, simply to check if all the required classes are present.

**Comment by marlomajor** [comment]
When does this error happen?

**Comment by esarbe** [comment]
@marlomajor Have you been able to reproduce this?

**Comment by smarter** [comment]
This got better a while ago.
