### ISSUE TITLE
Setup mima to check for backwards- and forward- incompatible change

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#11939]
We need to add https://github.com/lightbend/mima/ to our build and run its checks as part of our CI, disallowing both backward-incompatible and forward-incompatible change (that is, `mimaCheckDirection` needs to be set to `both`), eventually we'll also need to tweak it to allow forward-incompatible changes after a minor version bump.

**Comment by smarter** [comment]
To be clear, mima should only be enabled in scala3-library, scala3-library-js, scala3-interfaces, tasty-core, for everything else we make no guarantee (and I guess we could also document this clearly by setting `versionScheme := Some("semver-spec")` in these projects, if I'm not mistaken /cc @sjrd)

**Comment by sjrd** [comment]
Well, after more time than I wish to admit, I have finally discovered that MiMa simply does not support Scala 3 artifacts at the moment. :( The fix is in main, but not released.

I have requested a release at https://github.com/lightbend/mima/issues/619
