### ISSUE TITLE
Implicit conversion not being applied when imported

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11942]
## Compiler version

`3.0.0-RC2-bin-20210328-cca5f8f-NIGHTLY`

## Minimized code

```Scala
import scala.language.`3.0`
import scala.language.implicitConversions

trait A

object KO {
  object X { inline given Conversion[A, Int] = _ => 123 }
  import X._

  val testKO: Int = (??? : A) // error
}

object OK {
  inline given Conversion[A, Int] = _ => 123

  val testOK: Int = (??? : A) // ok
}
```

## Output

```
[error] 10 |  val testKO: Int = (??? : A)
[error]    |                     ^^^^^^^
[error]    |                     Found:    A
[error]    |                     Required: Int
```

## Expectation

It should compile.

**Comment by griggt** [comment]
Isn't this just the new import rules for givens, i.e. the `_` or `*` wildcard selectors import everything *except* givens, and a `given` selector on the import brings all givens into scope?

https://dotty.epfl.ch/docs/reference/contextual/given-imports.html

**Comment by japgolly** [comment]
DAMMIT! I already hate that new rule :angry: 

It does indeed fix the problem though. Thanks @griggt for help.
