### ISSUE TITLE
Type member in subclass should shadow type member in owner

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11953]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
trait X { type M = Int }

object Y {
  type M = String

  class C extends X {
    def m: M = 123
  }
}
```

## Output

```
7 |    def m: M = 123
  |           ^
  |           Reference to M is ambiguous,
  |           it is both defined in object Y
  |           and inherited subsequently in class C
```

## Expectation

It should compile. (It does in Scala 2.x)

**Comment by smarter** [comment]
This is an intentional change in what constitutes shadowing: https://github.com/lampepfl/dotty/pull/8622 (the backstory is https://github.com/scala/bug/issues/11921)

**Comment by japgolly** [comment]
Ah ok cool thanks
