### ISSUE TITLE
Downstream error matching invariant subtype of covariant supertype

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#11956]

**Comment by japgolly** [comment]
## Compiler version

3.0.0-RC1

## Minimized code

```Scala
sealed trait X[+B]
final case class Y[B](fn: B => B) extends X[B]

final class Step3[A](initState: X[A]) {
  initState match {
    case Y(f) =>
      f: (A => A)
      (a: A) => f(a)
  }
}
```

## Output

```
-- [E007] Type Mismatch Error: x.scala:7:6 -------------------------------------
7 |      f: (A => A)
  |      ^
  |   Found:    (f : B$1 => B$1)
  |   Required: A => A
  |
  |   where:    B$1 is a type locally defined in class Step3 with bounds <: A
-- [E007] Type Mismatch Error: x.scala:8:18 ------------------------------------
8 |      (a: A) => f(a)
  |                  ^
  |   Found:    (a : A)
  |   Required: B$1
  |
  |   where:    B$1 is a type locally defined in class Step3 with bounds <: A
2 errors found
```

## Expectation

I was thinking it should compile because it compiles with Scala 2.x.

However I'm wonder about soundness of invariant `Y[B]` extending covariant `X[+B]`. Long ago I was surprised that it worked and just trusted the compiler with Scala 2.x but now that Scala 3 is turning up this error I'm not sure which is the correct behaviour.

**Comment by smarter** [comment]
Yep, you can't trust Scala 2 for GADTs, Scala 3 is right here. You'll get more precise type constraints in your pattern match if you align the variance of the type parameters in the parent and child (so either make them both covariant or both invariant).
