### ISSUE TITLE
Implement infrastructure to check emitted bytecode

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1196]
Both those pull request:
https://github.com/lampepfl/dotty/pull/1061
https://github.com/lampepfl/dotty/pull/1188

restructure code with expectation that backend would emit different bytecode instruction. 
Currently our CI lacks a way to check if it actually works.

**Comment by felixmulder** [comment]
I'm currently exploring this using a similar approach as in scalac
