### ISSUE TITLE
`@targetName` can be used on trait/class/object

### ISSUE THREAD

**Issue by griggt** [lampepfl/dotty#11969]
## Compiler version

3.0.0-RC2

## Minimized code

```Scala
import annotation.targetName

@targetName("Foo") class Bar
@targetName("Huh") object Bar
@targetName("Wow") trait OhMy
```

## Output

```
$ ls -l *.class
-rw-r--r-- 1 tgrigg tgrigg 280 Apr  1 11:15  Foo.class
-rw-r--r-- 1 tgrigg tgrigg 554 Apr  1 11:15 'Huh$.class'
-rw-r--r-- 1 tgrigg tgrigg 133 Apr  1 11:15  Wow.class
```

## Expectation

I expected this usage of `@targetName` to be disallowed.

**Comment by smarter** [comment]
Actually there's a few testcases that exercise that, and I guess it makes sense for classes that are supposed to be used infix like some hypothetical `class <+>[A, B]`: https://github.com/lampepfl/dotty/blob/master/tests/run/alpha-modules-2/7723_1.scala https://github.com/lampepfl/dotty/blob/master/tests/run/alpha-modules-1/7721_1.scala

**Comment by griggt** [comment]
Does this code need to account for `@targetName` then (it seems like it doesn't?)

https://github.com/lampepfl/dotty/blob/ea0002d4f2870a3bc1582af10023b614e094a78e/compiler/src/dotty/tools/dotc/sbt/ExtractDependencies.scala#L144-L168

**Comment by smarter** [comment]
Hmm, that may be missing indeed, along with dealing with compactified names.

**Comment by griggt** [comment]
I forgot about compactification (I did the PR!), thanks.

**Comment by griggt** [comment]
For anyone curious, this was noticed while testing WIP on `:javap` for the REPL.
