### ISSUE TITLE
Disallow open modifier on traits and abstract classes

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#11963]
As https://dotty.epfl.ch/docs/reference/other-new-features/open-classes.html mentions:
> Traits or abstract classes are always open, so open is redundant for them.

But right now `open trait Foo` and `open abstract class Foo` compile without error, they should at least emit a warning, like `final object Foo` already does.

**Comment by smarter** [comment]
We should probably also disallow open on local classes since there's no way to extend a local class from a different file anyway:
```scala
object Test {
  def foo: Any = {
    open class Bar
    new Bar
  }
}
```

**Comment by megri** [comment]
I'm working on the first part of this (excluding local classes).
The check is being done in Desugar.scala with `report.warning`. Am I on the right track?

**Comment by smarter** [comment]
I think that's fine, it might also be possible to do it in the Parser but that's not necessarily better.

**Comment by odersky** [comment]
The check should be integrated in `Checking.checkWellFormed`. That's the place we check all the other flag combinations.
