### ISSUE TITLE
Null checks with pattern matching are not reflected to the return type with `-Yexplicit-nulls`

### ISSUE THREAD

**Issue by lolgab** [lampepfl/dotty#11967]
## Compiler version

Scala 3.0.0-RC2 with `-Yexplicit-nulls`

## Minimized code

```Scala
// This works correctly
def f1(s: String | Null): String = if(s == null) "other" else s

// This fails to compile
def f(s: String | Null): String = s match {
  case null => "other"
  case s => s
}
```

## Output

```scala
  case s => s
            ^
            Found:    (s : String | Null)
            Required: String
```

## Expectation

My expectation is that what happens with `def f(s: String | Null): String = if(s == null) "other" else s` should apply to pattern matching too.

I couldn't find any open issue treating this, so I opened one.

Thank you.

**Comment by noti0na1** [comment]
Currently, the flow typing of explicit nulls only detects the NotNull cases in pattern matching (see `Nullables.matchesNotNull`). 

For example:

```scala
val s: String | Null = ???
s match {
  case _: String => println(s.length)
  case _ => println(0)
}
```

I think it would be better to detect the null case as well.

**Comment by noti0na1** [comment]
Sorry, I made a mistake. The null case is indeed detected by flow typing. 
In your example, the `s` at the case position is new variable, it will still have the original type.

If you write it in this way, then it can be compiled.

```scala
def f(s: String | Null): String = s match {
  case null => "other"
  case _ => s
}
```

**Comment by lolgab** [comment]
> In your example, the `s` at the case position is new variable, it will still have the original type.

It is a new variable yes, but it's defined after the `null` is already matched, so in theory it's type should be `String`, not `String | Null`, right?

**Comment by noti0na1** [comment]
The variables binded by the patterns are not handled by flow typing now. I agree we should consider them as well.
