### ISSUE TITLE
 Should it be possible to mark a lambda argument as given? #1229 

### ISSUE THREAD

**Issue by markus1189** [lampepfl/dotty#11976]
Hey `dotty` Team :wave: ,

while playing around with Scala 3 (RC2), I noticed a scenario where I'm not sure whether this is an intended limitation or just an oversight.

### What I'm doing
I am translating the `Transaction` code from https://www.scala-lang.org/blog/2016/12/07/implicit-function-types.html to Scala 3.

While trying to be clever / codegolf, I came up with (assuming the `import scala.util.chaining._` import)

```scala
Transaction().tap (given t => op ).commit()
```

instead of

```scala
def transaction[T](op: Transactional[T]) =
    given trans: Transaction = Transaction()
    op
    trans.commit()
```

However, that fails with:
```
[error] -- [E018] Syntax Error: Transaction.scala:33:23 
[error] 33 |    Transaction().tap (given t => op ).commit()
[error]    |                       ^^^^^
[error]    |                       expression expected but given found
```

While we still have the `implicit` keyword, I can write (note the `implicit` instead of `given`:

```scala
Transaction().tap (implicit _ => op ).commit()
```

The only Scala 3-ish way to express this I came up with, is using a pattern match + given as in:

```scala
Transaction().tap { case _ @ given Transaction => op }.commit()
```

### Question
Is there a better way, or is it planned to allow `given` in the same position as was allowed for implicit and lambda arguments in Scala 2?  

I would have liked to be able to write:

```scala
Transaction().tap (given _ => op ).commit()
```

You can find a full example here: https://gist.github.com/markus1189/b356afed7b16e46a5ecfb1a3060d3296

**Comment by odersky** [comment]
The correct syntax is `t ?=> op`

**Comment by markus1189** [comment]
If I write it like this:

```scala
  def transaction4[T](op: Transactional[T]) =
    Transaction().tap(_ ?=> op).commit()
```

it does not work either though :confused:, the error is:

```
[error] -- [E007] Type Mismatch Error: TransactionGist.scala:47:22 
[error] 47 |    Transaction().tap(_ ?=> op).commit()  
[error]    |                      ^^^^^^^^
[error]    |                      Found:    T
[error]    |                      Required: Transaction => T
```

The problem is, that the context function type `Transaction ?=> T` is not valid for `tap`s argument type, though the error does not explicitly tell that and just says `Found:  T`
