### ISSUE TITLE
Type evaluation for 'Tuple.apply()' shows surprising behavior

### ISSUE THREAD

**Issue by MRandl** [lampepfl/dotty#11977]
## Compiler version

tested on rc1 and rc2, linux and windows. Also replicates on Scastie.

## Minimized code

```Scala
def add(a : (Int, String), b : (Int, String)) : (Int, String) = (a(0) + b(0), a(1) + b(1))
```

## Output

(a(0) + b(0), ...) <- Found Long, required Int

## Expectation
You would expect this code to compile correctly and accept the fact that a(0) + b(0) is an Int and not a Long

## Workaround
Replacing a(0) + b(0) by a._1 + b._1 makes it work correctly

Anton Sviridov on Gitter greatly simplified my original problematic code

**Comment by MRandl** [comment]
Similar bug by Anton :
```scala
def add(s : (Long, String), t : (Long, String)) : (Long, String) = (s(0) + t(0), s(1) + t(1))
```
now expects a Float where we want a Long

**Comment by griggt** [comment]
Seems to be a regression in #9984.  Does not occur with `-Yforce-inline-while-typing`
