### ISSUE TITLE
function named `$`, used with curly braces causes `splice outside quotes compile error`

### ISSUE THREAD

**Issue by scalavision** [lampepfl/dotty#11992]
## Compiler version

`RC-2`

## Minimized code

```Scala
object DollarTest:
  def $ ( arg: String): Unit = println(arg)

import DollarTest.*

${ "hello world" }
```

## Output

```scala
Splice ${...} outside quotes '{...} or inline method
```

## Expectation

Should compile.

Because this works:  DollarTest.$ { "works" } 

I have a concrete dsl I am working on, where this would be very valuable. I don't think the compiler should report this error since it has `$` in scope.

**Comment by odersky** [comment]
`$` is a soft keyword that gets resolved to splice by the parser. That's before name resolution, so having things in scope or not is irrelevant. I don't think there's anything that can be done here, I am afraid. You DSL should pick another symbol.
