### ISSUE TITLE
Scalatest AnyFreeSpec does not compile

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#12004]
## Compiler version

3.0.0-RC2

## Minimized code

```Scala
class MyTest extends org.scalatest.freespec.AnyFreeSpec {
  "hello" in { }
}
```
https://scastie.scala-lang.org/dU61kxkZTHG0TkwucHAcGw

## Output

```scala
value in is not a member of String
```

## Expectation
Successful compilation

**Comment by scf37** [comment]
Does not compile because scalatest uses scala2 macros, not an issue.

**Comment by SethTisue** [comment]
indeed, removing `.withDottyCompat(scalaVersion.value)` and upgrading to ScalaTest 3.2.7 should work
