### ISSUE TITLE
`(using inline Type)` doesn't compile

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#12012]
## Compiler version

3.0.1-RC1-bin-20210406-b0061c4-NIGHTLY

## Minimized code

```Scala
inline def x(using inline ev: Int) = 1 // ok
inline def y(using inline     Int) = 1 // error
```

## Output

```
[error] 2 |inline def y(using inline     Int) = 1
[error]   |                                 ^
[error]   |                                 ':' expected, but ')' found
[error] one error found
```

## Expectation

Successful compilation.

**Comment by odersky** [comment]
It would maybe be nice if we could do this, but that's currently not foreseen. `inline` is a modifier that goes on individual parameters. It's not foreseen to put it on a type. Moving to discussions.
