### ISSUE TITLE
StackOverflowError when building expression in a loop

### ISSUE THREAD

**Issue by shawjef3** [lampepfl/dotty#12054]
## Compiler version

3.0.0-RC2

## Minimized code

```Scala
import scala.quoted.*

object RunN {
  inline def runN(inline n: Int)(inline arg: Unit): Unit = 
    ${runNImpl('n, 'arg)}
  
  def runNImpl(n:  Expr[Int], f: Expr[Unit])(using quotes: Quotes): Expr[Unit] = {
    var result: Expr[Unit] = '{()}
    for (_ <- 0 until n.valueOrError) {
      result =
        '{
          ${result}
          ${f}
        }
    }
    result
  }
}

object Main {
  def main(args: Array[String]): Unit = {
    RunN.runN(10_000) { }
  }
}
```

## Output
```
D:\Users\Jeff\IdeaProjects\macros\src\main\scala\Main.scala:3:23
Exception occurred while executing macro expansion.
java.lang.StackOverflowError


    RunN.runN(10_000) { }
```
## Expectation

Since I'm building the expression in a `for` loop with a `var`, it's not clear why this would cause a `StackOverflowError`.

**Comment by odersky** [comment]
The for loop is unrolled, so you are really building 10000 assignments in a row.

**Comment by shawjef3** [comment]
@odersky if I were to make a patch for this, I can think of a few options and I'm curious which you prefer, or maybe you have another idea.

- catch the `StackOverflowError` (in `ReTyper.typedUnadapted`?), log an error about the loop being unrolled being too large, then exit
- somehow detect that the loop is too large ahead of time, log an error, and exit
- One of the above, but instead of logging an error and exiting, don't unroll the loop.
