### ISSUE TITLE
3.0.0-RC2 Regression issue: type derivation of typed class not working well

### ISSUE THREAD

**Issue by daenenk** [lampepfl/dotty#12078]
## Compiler version

This issue popped up on scala "3.0.0-RC2" while I didn't saw it on 3.0.0-RC1

## Minimized code

```Scala
case class Box[A](a:A):
  def map[B](f: A => B): Box[B] = Box(f(a))

object T:
  box(1).map(_ + 1)
```

## Output

```
[error] 41 |  box(1).map(_ + 1)
[error]    |             ^^^^^
[error]    |             Found:    Int => Int
[error]    |             Required: Boxed[Int]#A => Int
```

## Expectation

Boxed[Int]#A  should be recognized as being equivalent to Int in this case.

**Comment by daenenk** [comment]
PS: while moving from 3.0.0-RC1 to 3.0.0-RC2 I also switched to sbt 1.5.0 i.s.o. using the dotty-plugin as recommended on https://www.scala-lang.org/blog/2021/04/08/scala-3-in-sbt.html

**Comment by bishabosha** [comment]
Thank you for opening the issue, please may you update your example so it can compile in a file

**Comment by daenenk** [comment]
Sorry, the minimized code is incomplete. And I had this on Scala 3.0.0-RC1 as well (I first though it was new). I posted the full issue already as a comment on https://github.com/lampepfl/dotty/issues/11729,
because I thought it may be strongly related.
