### ISSUE TITLE
genDocs command not found in Getting Started page

### ISSUE THREAD

**Issue by nogurenn** [lampepfl/dotty#12075]
## Compiler version
```
tasty-core / scalaVersion
	3.0.0-RC2
scala3-sbt-bridge / scalaVersion
	3.0.0-RC2
scala3-compiler / scalaVersion
	3.0.0-RC2
scala3-interfaces / scalaVersion
	3.0.0-RC2
scaladoc-nonBootstrapped / scalaVersion
	3.0.0-RC2
scala3-library / scalaVersion
	3.0.0-RC2
scalaVersion
	3.0.0-RC2
```

## Minimized example

```Scala
sbt genDocs
```

## Output
```scala
[error] Not a valid command: genDocs
[error] Not a valid project ID: genDocs
[error] Expected ':'
[error] Not a valid key: genDocs (similar: packageDoc, doc)
[error] genDocs
[error]        ^
```

## Expectation
Successful execution of command.

It may be that the command was replaced with something else, but the [Getting Started page](https://dotty.epfl.ch/docs/contributing/getting-started.html#generating-documentation) (`3.0.1-RC1-bin-20210412-69108bf-NIGHTLY`) shows `sbt genDocs`. I can submit a documentation PR if someone can confirm how it works now

**Comment by abgruszecki** [comment]
@romanowski what SBT task do we use to generate docs?

**Comment by romanowski** [comment]
There are 2 ways to generate docs: 
 - for any specific module (e.g. `scala3-compiler-bootstrapped) with `doc` task (e.g. `scala3-compiler-bootstrapped/doc`)
 - combined documentation for scala (content of [dotty.epfl.ch]) with sbt task `scaladoc/generateScalaDocumentation` or using cmd line script `genDocs` from `project/scripts`

**Comment by nogurenn** [comment]
Who do I tag in the PR for review?

**Comment by romanowski** [comment]
@abgruszecki has reviewed the PR and it looks good (beside one typo).
