### ISSUE TITLE
Type inference failure for type variable in intersection type

### ISSUE THREAD

**Issue by heaven-born** [lampepfl/dotty#12077]
## Compiler version

2.13.5 and  3.0.0-RC2

## Minimized code

This code compiles in 2.13.5  but not in 3.0.0-RC2.

```Scala
    trait Wrapper[K]
    trait Has0[T]
    
    def test[R](v: Wrapper[Has0[String] with R]):R = ???

    val zz:Wrapper[Has0[String] with Has0[Int]] = ???
    test(zz)
```

## Output

Error in 3.0.0-RC2

```scala
Found:    (zz : Wrapper[Has0[String] & Has0[Int]])
Required: Wrapper[Has0[String] & R]

where:    R is a type variable

      test(zz)

```

**Comment by heaven-born** [comment]
this issue and #12051 may have some connections

**Comment by smarter** [comment]
This is kind of a weird encoding (`Has0[String] with Has0[Int]` is an empty type like `Nothing`: because its type parameter is invariant and String is not the same type as Int, there's no value of this type), so I'm not sure how much we can or should do here. Alternatively, you could use unions:
```scala
trait Wrapper[K]
trait Has0[T]

object Test {
  def test[R](v: Wrapper[Has0[String] | R]): R = ???

  val zz: Wrapper[Has0[String] | Has0[Int]] = ???

  test(zz) // Infers R=Has0[Int]
}
```

**Comment by heaven-born** [comment]
@smarter not sure if this is an issue or not, but it seems that ZIO uses this kind of encoding now. Except that `K` is contravariant.  Like: `ZIO[Has[Env1] & Has[Evn2],..,..]`

**Comment by heaven-born** [comment]
btw, the inference works for zero-kinded types `val zz: Wrapper[Has0[String] & Int] = ???`
And  [this is example](https://github.com/gaelrenoux/tranzactio/blob/e265c0ba6c5d0b91a86d4a1f994578d682e177f5/src/main/scala/io/github/gaelrenoux/tranzactio/DatabaseOps.scala#L38) of the library that use this type trick, so it will not be able to survive the migration.
