### ISSUE TITLE
Wrong "isInstanceOf[Array[?]]"

### ISSUE THREAD

**Issue by flomebul** [lampepfl/dotty#12071]
## Compiler version

scala-3.0.0-RC2

## Minimized code

```Scala
scala> 1.isInstanceOf[Array[?]]
1 |1.isInstanceOf[Array[?]]
  |^^^^^^^^^^^^^^^^^^^^^^^^
  |cannot test if value of type Int is a reference of class Object

scala> 1.asInstanceOf[Array[?]]
val res0: Array[?] = 1

scala> (1: Any).isInstanceOf[Array[?]]
val res1: Boolean = true

scala> (1: Any).asInstanceOf[Array[?]]
val res2: Array[?] = 1
```

## Expectation

* `1.asInstanceOf[Array[?]]` should raise an exception
* `(1: Any).isInstanceOf[Array[?]]` should raise an exception or return false
* `(1: Any).isInstanceOf[Array[?]]` should raise an exception

**Comment by SethTisue** [comment]
also reported at https://github.com/scala/bug/issues/12373

**Comment by SethTisue** [comment]
```
scala> (1: Any).isInstanceOf[Array[?]]
val res1: Boolean = true
```

yes, that's a regression since Scala 2, it should return false

the others are not bugs. `isInstanceOf` should never raise an exception, and `asInstanceOf` is a promise to the compiler that you know what you're doing, that it bypasses error checking is exactly why it exists

**Comment by SethTisue** [comment]
note that autoboxing isn't the culprit here, and `Any` isn't the culprit either:

```
scala> Integer.valueOf(1).isInstanceOf[Array[?]]
val res4: Boolean = true
```

**Comment by Jasper-M** [comment]
The erasure of `Array[?]` is `Object` in Scala 2 and 3, so I guess Scala 2 does something special for arrays.

**Comment by sjrd** [comment]
This is what it does:
https://github.com/scala/scala/blob/b372fb329327cb73bf61c7ccaa162ec8c635b23f/src/library/scala/runtime/ScalaRunTime.scala#L30

**Comment by SethTisue** [comment]
Guillaume's PR: #12103
