### ISSUE TITLE
Document additional optional braces conditions

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#12090]
## Compiler version

`3.0.0-RC2`

## Minimized code

The below examples work with optional braces, but are undocumented, which caused us to skip it while implementing the parser:

```Scala
  for{ a <- 0 to 11 }
      println(a)
      println(a)
```

```Scala
  for( a <- 0 to 11 )
      println(a)
      println(a)
```

```Scala
  while( a < 10)
      a += 1
      println(a)
```

Are we missing anything?

## Expectation

We should have optional braces properly documented, otherwise it's hard to build tooling around it, but also it might cause suprises to the users.

**Comment by bishabosha** [comment]
I would say it is documented in the syntax:

```scala
Expr1             ::=  ...
                    |  ‘while’ ‘(’ Expr ‘)’ {nl} Expr
BlockExpr         ::=  <<< (CaseClauses | Block) >>>
<<< ts >>>        ::=  ‘{’ ts ‘}’
                    |  indent ts outdent
<<< ts >>>        ::=  [nl] ‘{’ ts ‘}’
                    |  `:` indent ts outdent
```

**Comment by tgodzik** [comment]
I haven't noticed it there :thinking:  and also it's still kind of weird to have the additional `do`, `then` keyword, but still be able to just not use them :(

I would however add it here for the users: http://dotty.epfl.ch/docs/reference/other-new-features/indentation.html

**Comment by tgodzik** [comment]
Ok, thanks @bishabosha for pointing me to the syntax, I haven't noticed that it's actually included there. I thought that the optional braces page was better to look at. It seems we don't have anything else besides these 3 I mentioned.

**Comment by odersky** [comment]
Good point. The optional braces after `for(..._)` are probably an oversight. At some point we allowed optional braces after 
`if (...)` as well but then we retracted since we said that was just too much choice at the boundary between new and old syntax. It seems we overlooked `for (...)`. I think we should probably be uniform and either accept indentation after `if (...)` again or drop it after `for (...)`. And among these two choices my slight tendency at the moment would be to drop it after `for (...)`. But for 3.0 everything should stay as it is, and we should get more experience what users think before making the next moves.

**Comment by tgodzik** [comment]
> Good point. The optional braces after `for(..._)` are probably an oversight. At some point we allowed optional braces after
> `if (...)` as well but then we retracted since we said that was just too much choice at the boundary between new and old syntax. 

I think that we decided that `if (cond) <indentation>` should stay at least until `3.1` ? 

This works in `3.0.0-RC2`:

```scala
  if (true)
    println(1)
    println(2)
```

We can add scalafix rules for all the syntax changes by then, so in most cases this should be straightforward to migrate.

**Comment by odersky** [comment]
Ah, yes, you are right of course. I got my versions crossed. So yes, everything behaves in the same way and we are good.

**Comment by odersky** [comment]
I actually don't see a discussion of indentation after `if (...)` in http://dotty.epfl.ch/docs/reference/other-new-features/indentation.html either. @tgodzik do you agree that we need to document that case as well?

**Comment by tgodzik** [comment]
Sure! That makes sense.
