### ISSUE TITLE
fix benchmark infrastructure

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1210]
@DarkDimius when you have time, could you please give more detailed description of this task? Thanks a lot.

Todos:

- [x] fix resultDir error (workaround in #1218 and ScalaMeter [PR](https://github.com/scalameter/scalameter/pull/163) )
- [x] ? simplify tests to just 3 groups : `Scala collections`, `dotty` and `test set` -- problem of data migration
- [x] don't use `ExponentialBackoff`, we can afford to keep result data for each day
- [x] daily backup regression data
     - added as post step: `tar -zcvf "backup/report-$(date '+%F').tar.gz" benchtmp/`
- [x] implement new UI for benchmarks
- [x] reconstruct `compileStdLib.dat` from `compileStdLib.dsv`
- [x] disable `Ycheck:all`

Two issues above involves migrate old regression data to new format, which may be quite involved.

**Comment by DarkDimius** [comment]
The main command that is used to run benchmarks:

> "dotty-bench/test:run -CscopeFilter '(pos|dotc|run|java|compileStdLib)\.*' -CresultDir benchtmp"

**Comment by DarkDimius** [comment]
https://github.com/lampepfl/dotty/pull/156 PR has link to the website generated by scalameter with published benchmarks. In order to show graphs(like here: https://goo.gl/HNJ0dt)  in pretty way, you would need to drag the "date" axis to become "x-axis". 

http://ci.d-d.me has jenkins web-interface. It runs benchmarks every night, but only if `master` branch has changed.

**Comment by liufengyun** [comment]
As an update, the benchmark infrastructure breaks because we have one corrupted serialised file in the report folder(`tests.compileStdLib.compileStdLib.dat` is `0` byte).

The simple solution is to remove the file. As we've no previous backup of the data, it means we lose the regression data for `scala collection` compilation. Now the benchmark ci is running, it should succeed.

However, I do notice another problem:

- A bug in ScalaMeter  caused command line option `-CresultDir` is ignored (workaround in #1218 ).

And I plan to make follow improvements:

- [ ] simplify tests to just 3 groups : `Scala collections`, `dotty` and `test set` -- problem of data migration
- [ ] don't use `ExponentialBackoff`, we can afford to keep result data for each day
- [ ] create `cron` job to daily backup regression data
- [ ] upgrade ScalaMeter to the latest version and use JSON for serialization -- problem of data migration
- [ ] use a fixed version of `dotty` and `test set` for benchmarks -- the objects should not change.

Two issues above involves migrate old regression data to new format, which can be quite involved. Not sure if some of the items make sense to you.

**Comment by DarkDimius** [comment]
>  - simplify tests to just 3 groups : Scala collections, dotty and test set -- problem of data migration
>  - use a fixed version of dotty and test set for benchmarks -- the objects should not change.

I'm not sure I understand what you mean. Could you please elaborate?

**Comment by liufengyun** [comment]
> simplify tests to just 3 groups

Currently we have more than 20 groups, it's a little difficult to get insight with so many groups. I mean we can merge related groups into just 3 groups: `scala collection`, `dotty` and `test set`.

> use a fixed version of dotty and test set for benchmarks

Current benchmark measures compilation time for dotty itself and also the test set. However, dotty as well as the test set are changing all the time in development, an increase in compilation time doesn't necessarily imply degradation in performance. To make benchmarks comparable and more meaningful, I think it's better to compile a fixed version of dotty.

**Comment by DarkDimius** [comment]
> As we've no previous backup of the data, it means we lost the regression data for scala collection compilation. Now the benchmark is back to normal.

https://d-d.me/tnc/dotty/tests.compileStdLib.compileStdLib.dsv - this is the backup in a different format.

**Comment by liufengyun** [comment]
Thanks @DarkDimius , the dsv has part of the information of `dat`, but it's not a serialisation(it's generated by a reporter, instead of a persistor), thus can't be used to restore the `dat` file.

**Comment by DarkDimius** [comment]
Well, for graphs we actually don't need the `dat` file, as only `dsv`s are used.
I'm not aware if it would be easy to  to make ScalaMeter append to existing `dsv` without a matching `dat` file.

**Comment by liufengyun** [comment]
That would require deep hacking of ScalaMeter, make the infrastructure difficult to maintain.

However, the `dsv` contains the most essential data of `dat`. Maybe I can try to use that information to reconstruct `dat`.

**Comment by liufengyun** [comment]
I've just reconstructed the `dat` file from `dsv` file using a short [program](https://gist.github.com/liufengyun/2fdd0abd47920eea9aba0f0c40405744).

**Comment by liufengyun** [comment]
It seems the ScalaMeter web app hasn't been maintained for 3 years. It's difficult to use or customize. I kind of want to develop our own HTMLReporter, and possibly contribute back to ScalaMeter.

I estimate it would take about 30 to 40 hours to get it working. I'm not sure if it's worth the effort.

**Comment by liufengyun** [comment]
I've spent one day rewriting the web app for benchmarks:

https://d-d.me/tnc/dotty/web/

It's a pure static web app, without any change in ScalaMeter or infrastructure, except a symbolic link to ScalaMeter HTML report files.

One small but useful feature is that you can select the charts you are interested and they are remembered in your browser.

BTW, the reconstruction of `dat` from `dsv` caused runtime type casting error between `long` and `int`. I'll investigate and propose a robust reconstruction.

**Comment by odersky** [comment]
This looks incredibly helpful! Now, do I read that right that between
december and march compile-time performance halved for most benchmarks? If
yes, is there a way to get more datapoints to identify where this comes
from?



On Sun, Apr 17, 2016 at 2:28 AM, liu fengyun <notifications@github.com>
wrote:

> I've spent one day rewriting the web app for benchmarks:
>
> https://d-d.me/tnc/dotty/web/
>
> It's a pure static web app, without any change in ScalaMeter or
> infrastructure, except a symbolic link to ScalaMeter HTML report files.
>
> One small but useful feature is that you can select the charts you are
> interested and they are remembered in your browser.
>
> BTW, the reconstruction of dat from dsv caused runtime type casting error
> between long and int. I'll investigate and propose a robust
> reconstruction.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/1210#issuecomment-210927557>
>



-- 

Martin Odersky
EPFL and Lightbend

**Comment by liufengyun** [comment]
The data points shown are all what we have. That's also the reason I propose to remove `ExponentialBackoff` and keep all data points.

**Comment by odersky** [comment]
Is it possible to re-generate the missing data points somehow? We really should find out where we have lost half the performance.

**Comment by liufengyun** [comment]
That's doable, we just write a script to loop through the changes of the period,  then run testing for each day. I'll take care of that.

**Comment by DarkDimius** [comment]
@odersky, what regression do you mean? If you mean the one that was at November, than this is the artifact of benchmark - it used to benchmark different code before(branch `bench` that's now deleted)

**Comment by odersky** [comment]
On Sun, Apr 17, 2016 at 2:50 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> @odersky <https://github.com/odersky>, what regression do you mean? If
> you mean the one that was at November, than this is the artifact of
> benchmark - it used to benchmark different code before(branch bench
> that's now deleted)
>

Ah, OK. So that means the first reliable data points are from February this
year? In that case I guess no need to check further back.

 - Martin

—
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/1210#issuecomment-211013318>
>



-- 
Prof. Martin Odersky
LAMP/IC, EPFL

**Comment by liufengyun** [comment]
@DarkDimius , I plan to write a custom `BenchTests` as follows:

``` Scala
class BenchTests extends CompilerTest {
  val defaultOutputDir = "./out/"

  implicit val defaultOptions = Nil[String]
  val scala2mode = List("-language:Scala2")

  val dottyDir  = "./dotty-src/src/dotty"
  var stdLibDir = "./scala-scala/src/scala/library"

  @Test def stdLib = compileDir(stdLibDir, ".", "-migration" :: "-deep" :: scala2mode)

  @Test def dotty = compileDir(dottyDir, ".",  List("-deep"))
}
```

The changes compared to the previous benchmark implementation are:

- It assumes a fixed version of `dotty` in the folder `dotty-src`
- It merges all `dotc` tests to one test
- It compiles all files under `src/scala/library`, instead of just files from the whitelist
- It removes all tests related to `pos`, `java`, `run`
- It removes `Ycheck:all` for fast compilation

With this simplification, we'll only have two charts in total. Of course, we can add more projects as targets of compilation.

I'm not sure if the changes make sense. Thanks.

**Comment by DarkDimius** [comment]
> It compiles all files under src/scala/library, instead of just files from the whitelist

AFAIK this isn't going to work(yet?). Classes like `scala.Boolean` break many assumptions of compiler. We need to either special case them in a lot of places in compiler or not compile them. I'd vote for the later(this is already done for some classes, like `scala.Nothing$`)

> It removes all tests related to pos, java, run 
> With this simplification, we'll only have two charts in total.

I'm not sure if that's a good idea. It means that if some change will slowdown a specific test\file we will not be able to see it. The tests that are currently in `dotc.tests` are some-kind-of unique representatives that used to cause problems.

We shouldn't overtune the dotty to compilation of stdlib and dotty iself. Those are two very unusual codebases and they may not represent the real-world use of compiler. 


BTW, very nice job.

**Comment by smarter** [comment]
> Classes like scala.Boolean break many assumptions of compiler.

`Boolean.scala` is already part of the whitelist, we already special cases primitive classes: they are only typechecked. However, other stuff is likely to not compile. @liufengyun : I suggest you try increasing the number of files in the whitelist instead.

> It removes all tests related to pos, java, run 

As an alternative, you could have a single benchmark that compiles all of `pos` at once. (A benchmark that compiles `neg` could also be useful, I have noticed that some neg test cases take very long to fail, I suspect an issue in implicit search but haven't investigated yet).

The main issue with all these tests is that they evolve which makes it harder to compare stuff. I think we should benchmark a frozen set of tests (`dotty` as of 2016-04-16, stdlib whitelist as of 2016-04-16, `pos` as of 2016-04-16, ...) _and_ also benchmark the current version of the tests.

**Comment by DarkDimius** [comment]
> `Boolean.scala` is already part of the whitelist, we already special cases primitive classes: they are only typechecked. 

@smarter even typechecking them in some cases [fails](https://gist.github.com/densh/73f4b27ae6385599aae85a4b4c81c077). This is a try to bootstrap entire library bootstrap 20 days ago.
We've found out that after primitives where removed from list-of-files-to-be-compiled, the problem went away.

**Comment by DarkDimius** [comment]
> _and_  and also benchmark the current version of the tests

The benchmarks already run for 10 hours. We can decrease this time, but we're very likely to get a lot more noise in output.

**Comment by liufengyun** [comment]
Currently the benchmark runs each test 36 times, we can reduce to 12 to have it run faster.
