### ISSUE TITLE
`Cyclic reference involving module class` in Scala3 but compiles in Scala2

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#12109]
## Compiler version

3.0.0-RC1, 3.0.0-RC2

## Minimized code

https://scastie.scala-lang.org/6NSAUSm4Qo2Y9NJbLQrxWw

## Output

```scala
Cyclic reference involving module class JsonReaderDefaultValue$
```

## Expectation

Successful compilation. 

Does not reproduce when dependent code is copy-pasted to the same Scastie session.

**Comment by griggt** [comment]
Self-contained:

#### JsonReaderDefaultValue.scala (compile with Scala 2.13)

```scala
object JsonReaderDefaultValue extends LowPriorityDefaultValue {
  class ReaderDefaultValue extends scala.annotation.StaticAnnotation
}

trait LowPriorityDefaultValue {
  @JsonReaderDefaultValue.ReaderDefaultValue
  class NoDefaultValue
}
```

#### Test.scala

```scala
object Test {
  JsonReaderDefaultValue
}
```

**Comment by realvictorprm** [comment]
I have a similar issue however for me the code compiles but as soon as I try to publish I also run into `Cyclic reference involving object GetSecretValueRequest` with the type here being from the AWS SDK lib.
I also tried the latest nightly from the 20th April but without success  :/

**Comment by smarter** [comment]
Cyclic references can have many causes, if the latest nightly doesn't fix your problem, it's likely unrelated to this and you should open a new issue.

**Comment by realvictorprm** [comment]
I came to that conclusion too. This seems to be quite complex. My tries to isolate the issue failed so far :(

**Comment by smarter** [comment]
If you can't minimize it, it can still be helpful to open an issue if you can provide a reliably way to reproduce the problem (e.g. a branch of a git repo and the command used to compile the code).
