### ISSUE TITLE
Regression: Implicit conversions aren't being provided to implicit conversions

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#12113]
## Compiler version

* 3.0.0-RC1
* 3.0.1-RC1-bin-20210412-69108bf-NIGHTLY

## Minimized code

```Scala
import scala.language.implicitConversions

object Builder {

  def apply[P] = new Step1[P]

  class Step1[P]       { def stateless: Step2[P, Unit]    = new Step2 }
  class Step2[P, S]    { def noBackend: Step3[P, S, Unit] = new Step3 }
  class Step3[P, S, B] { def blah     : S                 = ???       }

  implicit def defaultToNoState[P](b: Step1[P]): Step2[P, Unit] =
    b.stateless

  implicit def defaultToNoBackend[X, P, S](b: X)(implicit ev: X => Step2[P, S]): Step3[P, S, Unit] =
    b.noBackend
}

object Usage {
  Builder[Unit].stateless.noBackend.blah
  Builder[Unit].stateless.blah
  Builder[Unit].noBackend.blah
  Builder[Unit].blah
}
```

## Output

```
-- [E008] Not Found Error: x.scala:15:6 ----------------------------------------
15 |    b.noBackend
   |    ^^^^^^^^^^^
   |    value noBackend is not a member of X
1 error found
```

## Expectation

It should compile. It does with Scala 2.11+. This is pretty important for scalajs-react.

**Comment by odersky** [comment]
Compiling with -source 3.0-migration shows why:
```
~/workspace/dotty/tests/neg> sc ../new/test.scala -source 3.0-migration
-- Migration Warning: ../new/test.scala:15:4 -----------------------------------
15 |    b.noBackend
   |    ^
   |The conversion (ev : X => Builder.Step2[P, S]) will not be applied implicitly here in Scala 3 because only implicit methods and instances of Conversion class will continue to work as implicit views.
1 warning found
```
In 3.0, instances of `scala.Function1` are no longer available as implicit conversions. You need to use `scala.Conversion` parameter instead. This closes several glaring traps in Scala 2 implicits, for instance that someone passes a `Map` and gets an accidental conversion.

**Comment by japgolly** [comment]
@odersky That warning with `-source 3.0-migration` is great, but it should still continue to work for the sake of the migration period right? There are many other warnings that appear with `-source 3.0-migration` and they still continue to compile. This seems to be the except by warning but breaking users' code.

**Comment by som-snytt** [comment]
@japgolly The PR linked from bottom of [the doc explanation](https://dotty.epfl.ch/docs/reference/changed-features/implicit-conversions-spec.html) says `-language:Scala2` was the migration period. It also says this was a puzzler-driven change. (Maybe the assumption is that users' code was likely already broken.) The previous version of the PR has further discussion about scope. ("For the moment it's under Scala2 mode, which means: "in native dotty, never". But that might be too harsh.")
