### ISSUE TITLE
`export` to consider imported prefixes

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#12112]
## Compiler version

* 3.0.0-RC1
* 3.0.1-RC1-bin-20210411-b44cafa-NIGHTLY

## Minimized code

```Scala
object A:
  object B:
    object C

object X {
  import A.B

  B.C        // ok
  export B.C // error
}
```

## Output

```
[error] 9 |  export B.C // error
[error]   |         ^
[error]   |         Not found: B
[error] one error found
```

## Expectation

Compilation.

**Comment by bishabosha** [comment]
This is as specified: http://dotty.epfl.ch/docs/reference/other-new-features/export.html#elaboration-of-export-clauses

> Export clauses are processed when the type information of the enclosing object or class is completed. Completion so far consisted of the following steps:
> ...
>  6. Compute the types of all paths in export clauses in a context logically inside the class but not considering any imports or exports in that class.
