### ISSUE TITLE
Regression: Ambiguous implicits should error

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#12114]
## Compiler version

* 3.0.0-RC1
* 3.0.1-RC1-bin-20210412-69108bf-NIGHTLY

## Minimized code

```scala
class Singleton[A]

object Singleton {

  implicit val Unit: Singleton[Unit] =
    new Singleton

  sealed trait Not[A]
  implicit def noSingletonFor[A]: Not[A] = null
  implicit def singletonFor1[A: Singleton]: Not[A] = null
  implicit def singletonFor2[A: Singleton]: Not[A] = null

  implicitly[Singleton    [Unit]] // ok
  implicitly[Singleton.Not[Unit]] // error expected
  implicitly[Singleton.Not[Int ]] // ok
}
```

## Output

It all compiles.

## Expectation

The same error as Scala 2:

```
x.scala:14: error: ambiguous implicit values:
 both method noSingletonFor in object Singleton of type [A]Singleton.Not[A]
 and method singletonFor1 in object Singleton of type [A](implicit evidence$1: Singleton[A]): Singleton.Not[A]
 match expected type Singleton.Not[Unit]
  implicitly[Singleton.Not[Unit]] // error expected
            ^
1 error
```

**Comment by odersky** [comment]
That's an intentional and documented change:

  https://dotty.epfl.ch/docs/reference/changed-features/implicit-resolution.html


> Modified version:

> An alternative A is more specific than an alternative B if

> - the relative weight of A over B is greater than the relative weight of B over A, or
> - the relative weights are the same, and A takes no implicit parameters but B does, or
> - the relative weights are the same, both A and B take implicit parameters, and A is more specific than B if all implicit parameters in either alternative are replaced by regular parameters.

**Comment by smarter** [comment]
Note that this is what scala.util.NotGiven is for: https://github.com/lampepfl/dotty/blob/master/library/src/scala/util/NotGiven.scala

**Comment by japgolly** [comment]
@smarter Yeah thanks, I ended up using `NotGiven` already but the problem is it's incompatible with Scala 2. I couldn't cross-compile the same source anymore and had to put things in separate `scala-2` and `scala-3` directories.

@odersky  Is this not a problem for Scala 3 migration mode? This little "pattern" is all over the Scala 2 ecosystem.

And btw, what's the rule that means this is not ambiguous anymore? Is it this part below? I don't understand. The definitions are identical; either neither is more specific than each other, or both are more more specific than each other (?).

> A is more specific than B if all implicit parameters in either alternative are replaced by regular parameters.

**Comment by som-snytt** [comment]
@japgolly I think `noSingletonFor` is preferred over the other two because

> A takes no implicit parameters but B does

**Comment by joroKr21** [comment]
You can try adding a `DummyImplicit` to settle the score

**Comment by smarter** [comment]
You can still cross-compile by defining a NotGiven for Scala 2: https://github.com/typelevel/fs2/blob/main/core/shared/src/main/scala-2/fs2/compat/NotGiven.scala https://github.com/typelevel/fs2/blob/main/core/shared/src/main/scala-3/fs2/compat/NotGiven.scala (something that could be added to https://github.com/scala/scala-collection-compat perhaps?)
