### ISSUE TITLE
`inline val` of `null`

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#12177]
## Compiler version

RC3

## Minimized code

```Scala
object Test1 {
  inline val v = null
  inline def d = null
}
```

## Output

```
[error] 2 |  inline val v = null
[error]   |                 ^^^^
[error]   |                 inline value must contain a literal constant value.
[error]   |
[error]   |                 To inline more complex types consider using `inline def`
[error] one error found
```

## Expectation

Want to check that this is really desired behaviour vs an oversight. `null`'s are literal constants right? `Literal(Constant(null))` is valid in the quoting API.

**Comment by bishabosha** [comment]
I guess the error is misleading, an inline val needs to have a literal type, and there is no literal type for `null`

**Comment by som-snytt** [comment]
I would have expected null is literally the most literal type. I guess the same for unit and nothing.

**Comment by sjrd** [comment]
`Nothing` doesn't have a value, so no. But I agree that `null` and `()` should have corresponding literal types, or at least that we should be able to use them in the same capacity as other literals.

**Comment by nicolasstucki** [comment]
The current limitation for supporting `inline val n = null` and `inline val u = ()` is that we o not guarantee constant folding on them as with literal types. We would need to start with that, created #12198 to track progress on this enhancement.
