### ISSUE TITLE
Terminal colon for templates with empty bodies should be permitted

### ISSUE THREAD

**Issue by propensive** [lampepfl/dotty#12185]
## Compiler version

Scala 3.0.0-RC2

## Minimized example

```Scala
trait Foo:
```

## Output
```
Error: indented definitions expected, eof found
```

## Expectation
Template definitions which end in a `:` but have empty bodies turn out to be quite a common occurrence during development, usually because the non-compiling body gets temporarily commented out. But the presence of the `:` combined with the empty body is considered erroneous by the parser.

This creates a small but disproportionate amount of friction. Seeing as commenting-out a template's body is as simple as pressing `Ctrl+/`, it's very easy to do, but I find that I make the same mistake of forgetting to also delete the `:` over and over again. And then I also have to add the `:` back when I reinstate the template body.

I would prefer the `:` to be optional for templates with empty bodies. A compromise possibility would be to reduce it to a warning.

**Comment by propensive** [comment]
I wasn't proposing to remove the colon in all cases (and I think that was discussed at length a few months ago). But I'd agree that,
```
trait Foo:
def bar = 1
```
seems like it should really be at least a warning in all cases. In the absence of braces, the indentation shouldn't be optional. Too much flexibility around indentation is a bad thing.

**Comment by som-snytt** [comment]
You can use `end`. Not sure that is helpful for the use case.

The PSA slogan would go something like: "`end` isn't just for long things."

```
trait T:
// still not sure here
end T
```

**Comment by odersky** [comment]
I think we do not have a clear understanding how to improve this.
