### ISSUE TITLE
Pattern match over a parametrised ADT with type-constrained children no longer compiles

### ISSUE THREAD

**Issue by adamw** [lampepfl/dotty#12226]
## Compiler version

3.0.0-RC3

## Minimized code

```scala
object Test extends App {
  sealed trait P[T]
  case class C1[T <: String](c1: T) extends P[T]
  case class C2[T](c2: T) extends P[T]

  def test[T](p: P[T]): Unit = p match {
    case C1(_) => println(1)
    case C2(_) => println(2)
  }

  test(C1("x"))
  test(C2(10))
}
```

## Output

```scala
[error] -- [E057] Type Mismatch Error: Test.scala:9:9
[error] 9 |    case C1(_) => println(1)
[error]   |         ^
[error]   |         Type argument T does not conform to upper bound String
```

## Expectation

Used to compile just fine with 2.11/2.12/2.13.

**Comment by smarter** [comment]
@abgruszecki Is there a good reason for emitting an error here?

**Comment by abgruszecki** [comment]
No, I don't see a reason, much less a good one. I think this a problem with inferring type arguments to `.unapply` methods.

**Comment by adamw** [comment]
It seems that a work-around is:

```scala
  def test[T](p: P[T]): Unit = p match {
    case c1: C1[T] => println(s"1 ${c1.c1}")
    case c2: C2[T] => println(s"2 ${c2.c2}")
  }
```

which only emits a non-exhaustivity warning using 3-RC3 (no warnings or errors on 2.11/2.12/2.13), but at least compiles on all Scala versions :)

```scala
[warn] 8 |  def test[T](p: P[T]): Unit = p match {
[warn]   |                               ^
[warn]   |                               match may not be exhaustive.
[warn]   |
[warn]   |                               It would fail on pattern case: C1(_)
```

**Comment by abgruszecki** [comment]
Great, thanks for letting us know there's a workaround @adamw!

**Comment by abgruszecki** [comment]
BTW this doesn't seem to be about type arguments to `.unapply`, I thought that `P` was covariant but it is in fact invariant. I'm looking into it right now, but it seems that the problem here is instead that the context no longer has GADT constraints when it checks that `.unapply` has correct type arguments.
