### ISSUE TITLE
Inconsistency between reflect Typed and 

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#12221]
## Compiler version

3.0.0-RC3

## Issue
Both `TypeTest`s will may match the same `tpd.Typed` tree
* [TypedTypeTest.unapply](https://github.com/lampepfl/dotty/blob/master/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala#L651)
* [UnapplyTypeTest.unapply](https://github.com/lampepfl/dotty/blob/master/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala#L1432)

This makes the type hierarchy unsound.

`UnapplyTypeTest.unapply` only matches `tpd.Typed` for historical reasons. Back when trees were separated from patterns we needed to handle this specially.

##  Solution
`UnapplyTypeTest.unapply` only match `tpd.Unapply`

**Comment by Snowflake8** [comment]
I think this is what I encountered (quoted from gitter). I can provide the code if needed


> Hello I've been been working in metaprogramming with scala.reflect and have stumbled across what could be a bug. Basically I have this fuction
> ```scala
> def treePrint(tree: Tree): Unit = {
>             tree match {
>                 case body : Term => {
>                         body match 
>                            case typed: Typed =>
>                               // Point A
>                               // Code for Typed
>                         //other Terms
>                        }
>                 // case Unapply(_, _, _) => 
>                          // Point C
>                 case typed : Typed =>
>                         // Point B
>                         // This should never run
>                 // other Tree things
>             }
>         }
> ```
> When I run the function point B is sometimes reached even though Typed should always go to Point A (since Typed is a subtype of Term). Even stranger, if I uncomment the Unapply case, instead of point B getting reached, it is point C instead.
> I can provide a failing input if necessary

**Comment by nicolasstucki** [comment]
@Snowflake8 does sound like it would be caused by this bug. Could you create a minimal self-contained code example that fails with your use case. This way we can ensure that everything is properly fixed.

**Comment by Snowflake8** [comment]
@nicolasstucki You were too quick 
Here was the code for legacy purpose
https://github.com/Snowflake8/Scala_Typed_bug

**Comment by nicolasstucki** [comment]
Snowflake8 no problem, I will add that extra test or reference it in one of the related issues if it hits another bug.
