### ISSUE TITLE
Compiler generates invalid forwarders for @static fields

### ISSUE THREAD

**Issue by lrytz** [lampepfl/dotty#1223]
```scala
import annotation.static
class T
object T { @static val ff = 10 }
```

produces an invalid forwarder method in `T.class`:
```
public class T {
  public static ff()I
    GETSTATIC T$.MODULE$ : LT$;
    INVOKEVIRTUAL T$.ff ()I
    IRETURN
}
```

In `T$.class` we have
```
public final class T$ {
  private final static I ff$$local

  public static ff()I
    GETSTATIC T$.ff$$local : I
    IRETURN
}
```

Accordingly, the following Java file compiles:
```java
public class A {
  public static void main(String[] args) {
    System.out.println(T.ff());
  }
}
```
but fails at runtime: with `Exception in thread "main" java.lang.IncompatibleClassChangeError: Expecting non-static method T$.ff()I`

invoking `T$.ff()` from Java works, but is not as expected.

Also note that the field is private, name-mangled and in the module class. IUC, the SIP says that a public static should be generated in the companion class (not the module class), and it should not be name-mangled to support java interop.

**Comment by DarkDimius** [comment]
Fixed in #1226
