### ISSUE TITLE
Ident factory in Quotes

### ISSUE THREAD

**Issue by cchantep** [lampepfl/dotty#12237]
The `Ident` type is exposed in `Quotes.reflectModule` API, but I don't see a function in `IdentModule` (or elsewhere) provided to create such a value for a term name (is there anything I missed?).

Some simple factory like `Ident("foo", ...)` would be nice (and seems possible: https://github.com/cchantep/dotty/commit/a4c3dcfe8f0fa7a685a46da67aa322443206e61b#diff-42ea4b504ef08605734e689ebe8e3aed413718879873e2eff4951dbed4dc8da0R430 ).

**Comment by nicolasstucki** [comment]
An alternative is to use `Ref.apply`.

Before creating an ident it is necessary to resolve to what `Symbol` or `TypeRef` it point. That part if the logic belongs to `Symbol` or `TypeRef` and not to `Ident`.

Creating a new symbol an returning an ident will not work and this ident points to a symbol/definition that does not exist in the program (i.e. there is not `Definition` with that symbol).

**Comment by cchantep** [comment]
Thanks for your feedback.
I don't see the point about `Ref`, except if `Ref` is an `Ident` under the hood.
For now for example, I don't see about to create a `case foo: MyType` using `CaseDefModule` as not being able to create the `Ident` for the pattern matching.

**Comment by nicolasstucki** [comment]
`Ref` will return an `Ident` or a `Select`, whichever is the one that is needed.

> For now for example, I don't see about to create a case foo: MyType using CaseDefModule as not being able to create the Ident for the pattern matching.

Which `Ident`?

**Comment by nicolasstucki** [comment]
To create `case foo: MyType => foo` you will need something like
```scala
      val owner = Symbol.spliceOwner
      val tpe = TypeRepr.of[MyType]
      val bind = Symbol.newBind(owner, "foo", Flags.Case, tpe)
      CaseDef(Bind(bind, Typed(Ref(bind), Inferred(tpe))), None, Ref(bind)))
```

**Comment by cchantep** [comment]
Thanks for your feedback. As far as I see, the `Bind(..)` is not required.
That's such a case that makes me miss quasiquotes ...

**Comment by cchantep** [comment]
BTW it seems weird that to emit a `case x: String => ()` it's not possible to use:

```scala
val tpr = TypeRepr.of[String]
val bind =
  Symbol.newBind(
    Symbol.spliceOwner,
    tpr.typeSymbol.name.toLowerCase,
    Flags.Case,
    tpr
  )

val br = Ref(bind)

CaseDef(Typed(br, Inferred(tpr)), guard = None, rhs = UnitConstant())

/* Compilation error:

While expanding a macro, a reference to value string was used outside the scope where it was defined
*/
```

Indeed it seems required to write the `CaseDef` as below.

```scala
CaseDef(
  Bind(bind, Typed(Wildcard(), Inferred(tpr))),
  guard = None,
  rhs = Block(Nil, Literal(UnitConstant()))
)
```
