### ISSUE TITLE
`js.UndefOr` is no longer considered a subtype of `js.Any`

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#12234]
## Compiler version

* 2.13.5 - pass
* 3.0.0-RC1 - pass
* 3.0.0-RC2 - fail
* 3.0.0-RC3 - fail

## Minimized code

```Scala
import scala.scalajs.js

object Test {
  def x: js.UndefOr[Int] = 1
  x: js.Any
}
```

## Output

```
[error] 5 |  x: js.Any
[error]   |  ^
[error]   |  Found:    scala.scalajs.js.UndefOr[Int]
[error]   |  Required: scalajs.js.Any
[error] one error found
```

## Expectation

Success.

**Comment by sjrd** [comment]
This is something we had to intentionally trade away, in exchange for getting Scala.js' `|` type to really *be* the Scala 3 built-in union type. So I am afraid the regression here is as-designed.

It's probably possible to locally reclaim it using something like
```scala
given undefOrAsJSAny[A](using Conversion[A, js.Any]): Conversion[js.UndefOr[A], js.Any] with
  def apply(x: js.UndefOr[A]): js.Any = x.map(y => y: js.Any)
```

**Comment by japgolly** [comment]
@sjrd What do you think about redefining js.Any in Scala 3 to be:

```scala
type Any = Unit | Boolean | Byte | Int | ... | String | js.Object
```

**Comment by sjrd** [comment]
That would simply not be correct (there are plenty of types that are `js.Any`s but none of those), and would go against all the core design principles behind the Scala.js dialect.

Usually the correct solution is not to use `js.Any` as an expected type in the first place, just like you would not use `AnyVal`. If for your use case, that union type is the correct answer, then use that union type, not `js.Any`.

**Comment by japgolly** [comment]
> Usually the correct solution is not to use js.Any as an expected type in the first place

It's not me setting the type, it's Scala.js. My use-case is that I have an instance of `js.Dynamic` and assigning a new field only works if the rhs is a subtype of `js.Any`.

If this behaviour is intentionally traded away, then shouldn't an implicit conversion be added to Scala.js to regain it?

**Comment by sjrd** [comment]
> It's not me setting the type, it's Scala.js. My use-case is that I have an instance of `js.Dynamic` and assigning a new field only works if the rhs is a subtype of `js.Any`.

Ah yes, `js.Dynamic` is suboptimal. It works when it works, but it has its limitations.

> If this behaviour is intentionally traded away, then shouldn't an implicit conversion be added to Scala.js to regain it?

That could perhaps actually be done, indeed. It would require careful analysis and testing to make sure that we don't break anything in Scala 2, though, but it's worth investigating.

**Comment by japgolly** [comment]
> It would require careful analysis and testing to make sure that we don't break anything in Scala 2, though, but it's worth investigating.

Oh I didn't mean it that way. I don't think any of the Scala 2.x stuff should be changed. I was imagining adding a new file under `src/main/scala-3` and only adding a conversion to the Scala 3.x sources and then using the shared tests to pass both. After all, parity with 2.x is the goal.

**Comment by sjrd** [comment]
If it's a new file, and you don't import what's in it, the implicit conversion won't be visible and hence never used. If it were that simple, we would already have done it.

**Comment by smarter** [comment]
if we just wanted to support conversions from js.UndefOr and not all unions of primitives, we could add an implicit def to https://github.com/lampepfl/dotty/blob/master/library-js/src/scala/scalajs/js/internal/UnitOps.scala in 3.1.

**Comment by japgolly** [comment]
> If it were that simple, we would already have done it.

It really is that simple. I'm doing the same thing pretty regularly now that I'm upgrading all of my libraries to Scala 3. You can do it two ways:

### 1

`src/main/scala-2/scala/scalajs/internal/ScalaSpecific.scala`:
```scala
package scala.scalajs.internal

trait ScalaSpecificJsPackage
```

`src/main/scala-3/scala/scalajs/internal/ScalaSpecific.scala`:
```scala
package scala.scalajs.internal

trait ScalaSpecificJsPackage {
  // conversion goes here
}
```

`src/main/scala/scala/scalajs/js/package.scala`:
```scala
package scala.scalajs

package object js extends internal.ScalaSpecificJsPackage {
  // existing shared stuff
}
```

### 2

`src/main/scala/scala/scalajs/internal/JsPackageShared.scala`:
```scala
package scala.scalajs.internal

trait JsPackageShared {
  // existing shared stuff
}
```

`src/main/scala-2/scala/scalajs/js/package.scala`:
```scala
package scala.scalajs

package object js extends internal.ScalaSpecificJsPackage
```

`src/main/scala-3/scala/scalajs/js/package.scala`:
```scala
package scala.scalajs

package object js extends internal.ScalaSpecificJsPackage {
  // conversion goes here
}
```

**Comment by japgolly** [comment]
Oh silly me, 99% of the time we `import scala.scalajs.js`, not `import scala.scalajs.js._` which is different to expected usage with most of my own libraries. Ok yep my bad, you're right.
