### ISSUE TITLE
summonFrom and using clause should act the same

### ISSUE THREAD

**Issue by liewhite** [lampepfl/dotty#12252]
## 3.0.0-RC3
If a report.error in a given macro and use NotGiven to deal with it,  It works with a summonFrom but compile error in a using clause.

## Minimized code
MkGiven.scala:
```scala
import scala.compiletime.*
import scala.quoted.*

object MkGiven:
  inline def mkInt:Int = ${ mkIntMacro }

  inline given Int = mkInt

  def mkIntMacro(using q: Quotes): Expr[Int] = 
    import q.reflect._
    report.error("no int found") // this break using but  summonFrom works well
    Expr(1)
```

Main.scala:
```Scala
import scala.compiletime.{summonFrom}
import scala.util.NotGiven
import MkGiven.given

trait OptionGiven[T]:
  def give: Option[T]

object OptionGiven:
  given exist[T](using NotGiven[T]): OptionGiven[T] with
    def give = None

  given notExist[T](using t: T): OptionGiven[T] with
    def give = Some(t)

inline def mySummon[T] = summonFrom {
  case t: T => t
}

def usingFailed(using i:Int) = i

@main def hello: Unit = {
  val ok = mySummon[OptionGiven[Int]].give
  val error = usingFailed
}
```

## Output

```scala
no int found
```

## Expectation
I think the using clause and summonFrom should act the same.

**Comment by odersky** [comment]
The purpose of `summonFrom` is that it is _not_ equivalent to `using` since it gets elaborated at the call site not the definition site.  So the argument "they should act the same" does not hold per se. Can we have a self-contained example? Without that it's hard to make progress here.

**Comment by liewhite** [comment]
@odersky  update the code to reproduce the problem.

**Comment by som-snytt** [comment]
If `MkGiven` uses `transparent inline`, then implicit search continues as described at https://dotty.epfl.ch/docs/reference/metaprogramming/inline.html#transparent-inline-methods

The no implicit argument error message adds:
```
But given instance given_Int in object MkGiven does not match type Int.
```
which is potentially confusing.

There is a similar question of how Scala 2 macro error reporting ought to interact with implicit search at https://github.com/scala/bug/issues/12388

**Comment by nicolasstucki** [comment]
The code seems to work as intended. What did you mean by `this break using but  summonFrom works well`?

**Comment by liewhite** [comment]
@nicolasstucki Oh, I forgot to close this.  `using` and `summonFrom` should act differently as design.
