### ISSUE TITLE
Type inference does not always work for higher-order types

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#12256]
## Compiler version

Scala2, Scala 3.0.0-RC3

## Minimized code

```Scala
trait Foo[F[_]]

def apply1[F[_]](f: Foo[F] => Foo[F] = identity): Unit = ??? // does not compile
def apply2[F[_]](f: Foo[F] => Foo[F] = identity[Foo[F]]): Unit = ??? // compiles
```

## Output

```scala
Found:    Foo[Nothing]
Required: Foo[(param)1]

where:    (param)1 is a type variable with constraint <: [_$2] =>> Any
```

## Expectation
Successful compilation.

This didn't work in Scala 2 as well so I don't know whether this is a bug or not. However, it is very inconvenient.

**Comment by smarter** [comment]
This is specific to default parameters which are very peculiar: we can't type them with the parameter type as expected type because they're allowed to have a completely different type (for example `def foo[A](x: A = 1) = {}` is allowed), so I don't think there's much we can do here.
