### ISSUE TITLE
Emit warning on `val x = x`

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#12263]
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
val x: Int = x
```

## Output

With Scala 2.13:
```
warning: value x does nothing other than call itself recursively
```

With Scala 3: No warning

## Expectation

Scala 3 should warn as well.

**Comment by som-snytt** [comment]
They need a 3rd repo for 3rd party lint requests. The lesson from Scala 2 is not only that someone has to code these warnings, but that someone has to review the PRs etc. I don't know if the 3rd party issue should be resolved by `foo-linter`, or if it is resolved by a test kit. Then `foo-linter` may conform to the test kit.

**Comment by liufengyun** [comment]
- If `x` is a field, enabling `-Ysafe-init` will issue a warning here.
- If `x` is a local variable, a forward reference error will be reported

**Comment by nicolasstucki** [comment]
We should already have a warning for `def f = f`, we could generalize it to `val`s.

**Comment by odersky** [comment]
The Scala 2.13 warning message is bogus. `x` does not call itself recursively. Instead, it's an initialization problem which will be caught. We do emit the warning for defs.
```scala
-- Warning: ../new/test.scala:4:6 ----------------------------------------------
4 |  def x: Int = x
  |  ^^^^^^^^^^^^^^
  |  Infinite recursive call
1 warning found
```

**Comment by som-snytt** [comment]
I don't remember how much tongue was in my cheek, but previously I suggested:

`var x: X = x` is the new `var x: X = _`.

https://github.com/scala/scala/pull/5391

Needless to add, that was rejected.
