### ISSUE TITLE
@uncheckedVariance stripped from case class's copy default getter(s)

### ISSUE THREAD

**Issue by dwijnand** [lampepfl/dotty#12273]
## Compiler version

3.0.0-RC3

## Minimized code

```scala
import scala.annotation.unchecked.uncheckedVariance

final case class Outlet[T](out: T)
final case class SourceShape[+T](val out: Outlet[T @uncheckedVariance])
```

## Output

```scala
-- Error: test.scala:4:29 ------------------------------------------------------
4 |final case class SourceShape[+T](val out: Outlet[T @uncheckedVariance])
  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |covariant type T occurs in invariant position in type [T] => Outlet[T] of method copy$default$1
1 error found
```

## Expectation

I expect it to compile like it does for Scala 2 (2.13.5).

## Notes

I believe this doesn't happen in Scala 2 with https://github.com/scala/scala/commit/fb38e47af1dec087a11585c6878c70ccdc930312, which was addressing https://github.com/scala/bug/issues/2382.  Did that get removed with #9909?  More recently #11704 also touched this, but that shipped in 3.0.0-RC2 and I originally saw this in 3.0.0-RC1.  Either way, it looks like this is accidentally breaking compilation.

Btw, this comes from cross-compiling Akka Streams to Scala 3.  Potentially this can be worked around by making un-casing the case classes, hand-writing all the boilerplate.  For non-copy methods you can try overloading, though that becomes difficult when you have other default arguments (which is the case in Akka Streams)...

**Comment by smarter** [comment]
> I believe this doesn't happen in Scala 2 with scala/scala@fb38e47, which was addressing scala/bug#2382.

That change in Scala 2 is unsound in general, cf https://github.com/lampepfl/dotty/pull/11704/commits/5b46ac2f8ab6618055e895adc39e4d82af48f87d

> Did that get removed with #9909?

Looks like that's what you're hitting here yeah, we strip `@uncheckedVariance` from the inferred types but it turns out we need it for the default getter inferred type.
