### ISSUE TITLE
Navigation bar items overflow on the dotty page

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#12290]
Navigation bar items overflow on the dotty page.

<img width="285" alt="Screenshot 2021-04-30 at 10 32 12" src="https://user-images.githubusercontent.com/3648029/116669902-6b4c7880-a99f-11eb-8946-4b03d50732e5.png">

Element size seen with the Chrome console layout tools.
<img width="327" alt="Screenshot 2021-04-30 at 10 34 33" src="https://user-images.githubusercontent.com/3648029/116670165-afd81400-a99f-11eb-9e7a-067f3f01f7ab.png">

**Comment by nicolasstucki** [comment]
The text is a bit too dense. Maybe a bit of padding on the top and bottom would be good as well. Lowering the font weight might also help.

**Comment by pikinier20** [comment]
Duplicated issue: #12098 

I close this one and leave the older one.
