### ISSUE TITLE
Investigate the differences in typechecking

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1230]
https://github.com/alexander-myltsev/scala-parser-combinators/commit/990f54be8a66b23fa6d971a14acc00edffd4fe95

Most of changes are in patterns.
We should see if we can get dotty to infer more precise types, or report a more user-friendly error than:

``` scala
./src/main/scala/scala/util/parsing/combinator/lexical/Scanners.scala:47: error: type mismatch:
 found   : Any(in1)
 required: Scanners.this.Input
        token(in1) match {
              ^
```

**Comment by liufengyun** [comment]
Close now, the issue is not actionable, as the issues are not minimized. Note that scala-parser-combinator is in the todo list of community buid.
