### ISSUE TITLE
new Ycheck: check that This(cls) can only refer to outer classes.

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1232]
Had a hard-to-spot bug in specialization that would have been revealed by such check.

**Comment by liufengyun** [comment]
I'm taking this one.

**Comment by liufengyun** [comment]
@DarkDimius I tried to create a tree to reproduce the problem, and found that we already have this check:

https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/transform/TreeChecker.scala#L336

**Comment by DarkDimius** [comment]
Yes, and I was the one who implemented it back then...
Thanks for having a look.
