### ISSUE TITLE
`transparent inline def` does not enforce type parameter bounds

### ISSUE THREAD

**Issue by bplommer** [lampepfl/dotty#12325]
## Compiler version
3.0.0-RC3

## Minimized code

```Scala
transparent inline def foo[A <: Int]: Int = valueOf[A]
@main def run = println(foo["hi"])
```

## Output
```scala
hi
```

## Expectation
This should fail to compile with a type error, as it does when `foo` in not `transparent`

**Comment by nicolasstucki** [comment]
This is a duplicate of #10552
