### ISSUE TITLE
Incremental compilation fails to update docstring of classes in the same file as the macro reading it

### ISSUE THREAD

**Issue by MaximeKjaer** [lampepfl/dotty#12351]
## Compiler version

3.0.0-RC3

## Minimized code

`Test.scala`

```Scala
@main def main(): Unit = {
    println("Test: " + getDocString[Test])
}
```

`GetDocString.scala`

```scala
import scala.quoted.*

/** HELLO */
case class Test(test: Boolean)

inline def getDocString[T]: Option[String] = ${ getDocStringImpl[T] }

private def getDocStringImpl[T : Type](using Quotes): Expr[Option[String]] = {
    import quotes.reflect.*
    Expr(TypeRepr.of[T].typeSymbol.docstring)
}
```

## Output

First run, with the above code:

```scala
Test: Some(/** HELLO */)
```

Second run: I now remove the comment from `Test`:

```scala
Test: None
```

Third run: I now place the comment back:

```scala
Test: None
```

## Expectation

In the third run, the `Test` class has a docstring, so I would expect `Some(/** HELLO */)` instead of `None`. 

## Other information

Running `sbt clean` and `sbt run` fixes the problem, so this tells me that the problem probably lies somewhere with incremental compilation.

If I place the `Test` case class in `Main.scala` instead of in `GetDocString.scala`, the bug doesn't happen.

**Comment by liufengyun** [comment]
I suspect this has the same cause as #12352.
