### ISSUE TITLE
TASTy reflect docstring of Scala library types is `None`

### ISSUE THREAD

**Issue by MaximeKjaer** [lampepfl/dotty#12352]
## Compiler version

3.0.0-RC3 and 3.0.1-RC1-bin-SNAPSHOT-nonbootstrapped-git-8957e51 (the version on `master` as of this writing)

## Minimized code

`Test.scala`

```Scala
@main def main(): Unit = {
    println("Quotes: " + getDocString[scala.quoted.Quotes])
}
```

`GetDocString.scala`

```scala
import scala.quoted.*

inline def getDocString[T]: Option[String] = ${ getDocStringImpl[T] }

private def getDocStringImpl[T : Type](using Quotes): Expr[Option[String]] = {
    import quotes.reflect.*
    Expr(TypeRepr.of[T].typeSymbol.docstring)
}
```

`build.sbt`

```scala
val dottyVersion = "3.0.0-RC3"

lazy val root = project
  .in(file("."))
  .settings(
    name := "docstring-none",
    version := "0.1.0",
    scalaVersion := dottyVersion,
    scalacOptions ++= Seq(
      "-Yretain-trees",
      "-Ycook-comments"
    )
  )
```

## Output

```scala
Quotes: None
```

## Expectation

It should print a `Some` containing the documentation of `Quotes`:

https://github.com/lampepfl/dotty/blob/8957e51230b843a7b3cff6f8e0698aad6f1d778e/library/src/scala/quoted/Quotes.scala#L18-L24

## Other info

I picked `Quotes` as an example in the above, but it seems that all Scala library types are returning `None` for their `docstring`. 

It seems that the condition of the `if` statement below is `false`, so the then branch isn't being executed.

https://github.com/lampepfl/dotty/blob/8957e51230b843a7b3cff6f8e0698aad6f1d778e/compiler/src/dotty/tools/dotc/core/tasty/TreeUnpickler.scala#L888-L895

**Comment by liufengyun** [comment]
If the purpose is to inspect tasty, maybe TastyInspector should be used, which sets `Mode.ReadComments`:

https://github.com/lampepfl/dotty/blob/8957e51230b843a7b3cff6f8e0698aad6f1d778e/tasty-inspector/src/scala/tasty/inspector/TastyInspector.scala#L87-L90

**Comment by liufengyun** [comment]
@nicolasstucki : Is `docstring` supposed to be usable in macros, or it's restricted to `TastyInspector`? If it's the latter, maybe we should update the documentation of `docstring`.

**Comment by nicolasstucki** [comment]
We always assumed that `docstring` would only be usable from a macro. To support it would require starting the compiler with that mode. This would probably require a compiler flag.
