### ISSUE TITLE
Clarify/spec whether traits can have secondary constructors

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1236]
Sip 25 does not address if this is supported. 
http://docs.scala-lang.org/sips/pending/trait-parameters.html
```scala

trait A(val s: Int){ def this(s: Double) = this(s.toInt)}
```
```
A.scala:1: error: wrong number of parameters for (()E)(E.this.<init>); expected: 0
trait E(val s: Int){ def this(s: Double) = this(s.toInt)}
                                               ^
```

**Comment by DarkDimius** [comment]
Agreed on a meeting that we don't want to allow secondary constructors in traits.

**Comment by felixmulder** [comment]
Has been amended to the SIP: https://github.com/scala/scala.github.com/pull/571
