### ISSUE TITLE
Eliminate self-symbols from trees & types

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1239]
Following discussion with Martin, it seems that self-symbols are not needed after typer.
If this is true, it makes sense to create a Mini-Phase&InfoTransformer that would eliminate self symbols both from trees and from types.
It it's false, it would be great to know how are they used.

**Comment by liufengyun** [comment]
I've tested a simple transform locally as follows:

```
class ElimSelf extends MiniPhaseTransform with InfoTransformer { thisTransformer =>
  override def transformInfo(tp: Type, sym: Symbol)(implicit ctx: Context) = tp match {
    case tp: ClassInfo =>
      tp.derivedClassInfo(selfInfo = NoType)
    case _ =>
      tp
  }

  override protected def mayChange(sym: Symbol)(implicit ctx: Context): Boolean = !(sym is Module)

  override def transformTemplate(impl: Template)(implicit ctx: Context, info: TransformerInfo): Tree = {
    cpy.Template(impl)(self = EmptyValDef)
  }
}
```

Elimination of `self` in tree works well, but elimination of `selfInfo` in `ClassInfo` have some caveats:

- Can't eliminate self type of package class, it's assumed [here](https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/core/Denotations.scala#L654).
- Can't eliminate self type of module class, it results in errors in backend -- backend uses self type to access the `sourceModule` ([log](https://gist.github.com/liufengyun/dd41d3b69a066e6b2d53c2f587712cb8)).
- TreeChecker requires `self` type in order to correctly retype the program.

The first two constrains us to only eliminate `self` of non-modules classes, however the last one makes elimination of `self` in `ClassInfo` impossible.

**Comment by DarkDimius** [comment]
@liufengyun, nice!

>Can't eliminate self type of package class, it's assumed here.

I didn't mean to eliminate self-types, only self-symbols. Self-types are needed for the reasons you've indicated.

**Comment by odersky** [comment]
Classinfos definitely need a selfinfo. The hypothesis is that, after, typer,

 - it can be a type, no symbol is needed.
 - we don't need a self definition in the trees

Cheers

 - Martin

On Sun, May 1, 2016 at 8:17 PM, liu fengyun <notifications@github.com>
wrote:

> I've tested a simple transform locally as follows:
>
> class ElimSelf extends MiniPhaseTransform with InfoTransformer { thisTransformer =>
>   override def transformInfo(tp: Type, sym: Symbol)(implicit ctx: Context) = tp match {
>     case tp: ClassInfo =>
>       tp.derivedClassInfo(selfInfo = NoType)
>     case _ =>
>       tp
>   }
>
>   override protected def mayChange(sym: Symbol)(implicit ctx: Context): Boolean = !(sym is Module)
>
>   override def transformTemplate(impl: Template)(implicit ctx: Context, info: TransformerInfo): Tree = {
>     cpy.Template(impl)(self = EmptyValDef)
>   }
> }
>
> Elimination of self in tree works well, but elimination of selfInfo in
> ClassInfo have some caveats:
>
>    - Can't eliminate self type of package class, it's assumed here
>    <https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/core/Denotations.scala#L654>
>    .
>    - Can't eliminate self type of module class, it results in errors in
>    backend -- backend uses self type to access the sourceModule (log
>    <https://gist.github.com/liufengyun/dd41d3b69a066e6b2d53c2f587712cb8>).
>    - TreeChecker requires self type in order to correctly retype the
>    program.
>
> The first two constrains us to only eliminate self of non-modules
> classes, however the last one makes elimination of self in ClassInfo
> impossible.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/1239#issuecomment-216061865>
>



-- 

Martin Odersky
EPFL and Lightbend
