### ISSUE TITLE
"Compiler bug" when using constValue inside an inline method

### ISSUE THREAD

**Issue by adamw** [lampepfl/dotty#12417]
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
import scala.deriving.Mirror
import scala.compiletime.{constValue, error}
import scala.quoted.*

object TestMacro {
  inline def test1[CASE_CLASS <: Product](using m: Mirror.ProductOf[CASE_CLASS]): Unit = {
    error(s"Error: ${constValue[m.MirroredElemLabels]}.")
  }
}

object Test extends App {
  case class A(x: String, y: Int)
  TestMacro.test1[A]
}
```

This comes from an attempt to provide user-friendly error messages for inline derivations which use mirrors.

## Output

```scala
[error] -- Error: Test.scala:14:2 
[error] 14 |  TestMacro.test1[A]
[error]    |  ^^^^^^^^^^^^^^^^^^
[error]    |  Compiler bug: `constValue` was not evaluated by the compiler
[error] -- Error: Test.scala:14:2 
[error] 14 |  TestMacro.test1[A]
[error]    |  ^^^^^^^^^^^^^^^^^^
[error]    |not a constant type: m$proxy1.MirroredElemLabels; cannot take constValue
```

**Comment by adamw** [comment]
Ready :)

**Comment by nicolasstucki** [comment]
`m.MirroredElemLabels` is a `Tuple`. `constValue` expects values of type `Int`, `Boolean`, ..., `String`.

This use case is too advances for `compiletime.error`. In this case a macro should be used. Something like:

```scala
object TestMacro {
  inline def test1[CASE_CLASS <: Product](using m: Mirror.ProductOf[CASE_CLASS]): Unit =
    ${ code('m) }

  def code[CASE_CLASS <: Product: Type](m: Expr[Mirror.ProductOf[CASE_CLASS]])(using Quotes): Expr[Unit] =
    m match
      case '{ $_ : Mirror { type MirroredElemLabels = t } } =>
        quotes.reflect.report.error(s"Error: ${ Type.show[t] }", m)
    '{}
}
```

We have [`Type.valueOfConstant`](https://github.com/lampepfl/dotty/blob/master/library/src/scala/quoted/Type.scala#L37) that is similar to [`compiletime.constValue`](https://github.com/lampepfl/dotty/blob/master/library/src/scala/compiletime/package.scala#L100). But we are missing a `Type.valueOfTuple` which would be similar to [`compiletime.constValueTuple`](https://github.com/lampepfl/dotty/blob/master/library/src/scala/compiletime/package.scala#L107)

**Comment by nicolasstucki** [comment]
That is #10315

**Comment by adamw** [comment]
Ah :) Indeed - so I suppose construction of an error message which is anything above a constant string means going to a macro. Though ... maybe I can call the macro from the inline branch? 🤔 I'll have to try that.

Would you like me to close this issue as a duplicate, or keep it open to improve the error message?

**Comment by adamw** [comment]
Although, maybe this is already covered by the second error, `not a constant type: m$proxy1.MirroredElemLabels; cannot take constValue`. I guess I got focused on the "Compiler bug" part and didn't look much further ;) That's the misleading part - it's not a compiler bug, it's my incorrect usage of inlines.

**Comment by nicolasstucki** [comment]
Oh, I missed that part. We should not emit the first error.

**Comment by nicolasstucki** [comment]
Ah, I missed it because it is already fixed. I remember that issue.

Now it fails with 
```scala
13 |  TestMacro.test1[A]
   |  ^^^^^^^^^^^^^^^^^^
   |not a constant type: m$proxy1.MirroredElemLabels; cannot take constValue
   | This location contains code that was inlined from Foo.scala:7
```

**Comment by adamw** [comment]
Awesome, thank you! :)
