### ISSUE TITLE
Wrong behavior of unapply on case classes ?

### ISSUE THREAD

**Issue by ThomasAlexandre** [lampepfl/dotty#12413]
## Compiler version

3.0.0-RC3

## Minimized code

```Scala
case class Person(firstName:String, lastName:String)

val person = Person("Joe","Bloggs")

val result: Option[(String, String)] = Person.unapply(person)
```

## Output

```scala
1 |val result: Option[(String, String)] = Person.unapply(person)
  |                                       ^^^^^^^^^^^^^^^^^^^^^^
  |                                       Found:    Person
  |                                       Required: Option[(String, String)]
```

## Expectation
val result: Option[(String, String)] = Person.unapply(person) should compile and give Some((Joe,Bloggs)) ( as in Scala2)

**Comment by nicolasstucki** [comment]
Now we use [name based pattern matching](http://dotty.epfl.ch/docs/reference/changed-features/pattern-matching.html#name-based-match) for case classes to avoid boxing the result.

Maybe we could have a better error message or some implicit conversion from `Person` (case classes) to `Option[(String, String)]` (mirrored option) for compat.
