### ISSUE TITLE
`-no-indent` flag doesn't disable new syntax in for-comprehensions

### ISSUE THREAD

**Issue by unkarjedy** [lampepfl/dotty#12427]
## Compiler version
`3.0.0-RC3`

add `scalacOptions ++= Seq("-no-indent")` to you `build.sbt`

## Minimized code

```Scala
@main
def test1(): Unit = {
  //42 match
  //   case 42 => println("ok")
  //   case _ => println("not ok")

  for
    x <- 1 to 2
    y <- 1 to 2
    z <- 1 to 2
  do
    println(s"x: $x, y: $y, z: $z")
}

```

## Output

This code compiles without any error, though `-no-indent` flag was provided.

## Expectation
Compilation error for indentation-based syntax in `for`.
Notice, that if I uncomment `match` the compilation error is shown:
![image](https://user-images.githubusercontent.com/3989292/117861096-ba48b680-b299-11eb-8e43-e076d1d65fff.png)

http://dotty.epfl.ch/docs/reference/other-new-features/indentation.html

**Comment by som-snytt** [comment]
The feature is actually http://dotty.epfl.ch/docs/reference/other-new-features/control-syntax.html

**Comment by odersky** [comment]
As @som-snytt explains, this is actually controlled by `old-syntax`

**Comment by unkarjedy** [comment]
@som-snytt 
Here http://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#optional-braces
it's stated that `An indentation region can start ... after one of the following tokens: ... for`

While in the beginning it's said that `These changes can be turned off with the compiler flag -no-indent.`
Maybe it's worth leaving a comment for `for` that the behavior for enumerators is controlled by `old-syntax` flag.

**Comment by som-snytt** [comment]
@unkarjedy indentation tracking and quiet syntax are orthogonal, except that `-old-syntax` also disables warnings about alignment (as [mentioned](http://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#settings-and-rewrites) in the doc).

I just spent a midnight hour learning about it, and I agree it is confusing. I think the use cases are out-of-the-box, `-no-indent` because of noisy warnings or you prefer braces, and `-old-syntax` for traditionalists.

Similar example of two flavors of braceless syntax, with indent errors for illustration:
```
  for
    x <- List(42)
   y <- List(1)
 yield
    val z = x + y
    z
```

**Comment by unkarjedy** [comment]
@som-snytt I see, thanks

BTW:
> -old-syntax also disables warnings about alignment (as mentioned in the doc).

Actually, it says the opposite:
> It can be turned off by giving any of the options -no-indent, old-syntax and language:Scala2
> If indentation is turned off, it is nevertheless checked that indentation conforms to the logical program structure as defined by braces. If that is not the case, the compiler issues a warning.

here is example of poor-indented code with `-old-indent`
![image](https://user-images.githubusercontent.com/3989292/117971422-8ff70780-b332-11eb-8b3b-e28b1f39383f.png)

**Comment by som-snytt** [comment]
For example, this does not warn under `-old-syntax`
```
def f() =
  for {
    x <- List(42)
 y <- List(1)
  }
  println(x + y)
```

**Comment by unkarjedy** [comment]
Ah, so it doesn't warn for the code with braces (old style), but still warns if some code "looks like" new syntax but is actually just poorly-formatted
