### ISSUE TITLE
Don't publish documentation from release branches

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#12454]
Right now https://dotty.epfl.ch/docs/ corresponds to 3.0.0 and is missing all changes that were committed to master since 3.0.0-RC2, we should make sure we never publish documentation from a release branch and only from nightlies to avoid this.

**Comment by griggt** [comment]
Are there any plans to make the reference and API documentation for released versions available online, in addition to the documentation for nightlies?

There are snapshots from older release candidates available, e.g. https://dotty.epfl.ch/0.27.0-RC1/docs/ for 0.27.0-RC1, but that is the last RC for which this seems to have occurred.

**Comment by smarter** [comment]
We should do that eventually yes, I don't know if we have an issue for keeping track of that, also I realized this issue is a duplicate of https://github.com/lampepfl/dotty/issues/8831
