### ISSUE TITLE
Match type reduction is aborted when combining literal and non-literal types

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#12458]
It looks like match type reduction is aborted when combining literal and non-literal comparisons.
I'm not sure exactly this is the consistent rule of the bug, but that's what I notice from the examples below.

## Compiler version
3.0.1 master branch

## Minimized code

```Scala
type Is1Or2[T] = T match
  case 1 => true
  case 2 => true
  case _ => false

val x1 : Is1Or2[1] = true //works
val x2 : Is1Or2[2] = true //works
val x3 : Is1Or2[3] = false //works
val xInt : Is1Or2[Int] = false //only error here

type IsIntOrString[T] = T match
  case Int => true
  case String => true
  case _ => false

val xInt2 : IsIntOrString[Int] = true //works
```

## Output

```scala
xInt : Is1Or2[Int] = false

Found:    (false : Boolean)
Required: Is1Or2[Int]
```

## Expectation
Should compile

**Comment by LPTK** [comment]
Match types are covariant, because they're supposed to precisely type corresponding term-level pattern matches. If you want to match a type invariantly, you can use this tricks (that compilers developers don't want you to see):

```scala
type Is1Or2[T] = Set[T] match
  case Set[1] => true
  case Set[2] => true
  case _ => false
```

**Comment by OlivierBlanvillain** [comment]
I don't think this should compile:

```scala
type Is1Or2[T] = T match
  case 1 => true
  case 2 => true
  case _ => false

def is1Or2[T](t: T): Is1Or2[T] = t match
  case 1 => true
  case 2 => true
  case _ => false
```

Here `is1Or2[Int](1)` would have type `false` but evaluates to `true`, which would clearly be unsound when using something other than two booleans...
