### ISSUE TITLE
Compiler freezes if type parameter is omitted

### ISSUE THREAD

**Issue by ansvonwa** [lampepfl/dotty#12466]
## Compiler version
`3.0.0`

## Minimized code

```Scala
scala> ???.asInstanceOf[scala.collection.Seq] += 1

```
Note:
* The type parameter of `s.c.Seq` is omitted (Compiler does not freeze if it is given)
* `+=` is not a member of collection.Seq
* May be related to #12465

## Output (click arrow to expand)
<details>

Absolutely nothing: No output, no error, no new prompt.
Same with `-Xprint:typer`:

```scala
$ time scala -Xprint:typer
scala> ???.asInstanceOf[scala.collection.Seq] += 1                                              
^C
real	1m5,798s
user	0m8,007s
sys	0m0,721s
```
</details>

**Comment by griggt** [comment]
Already fixed on master by #12223 

Now:

```scala
scala> ???.asInstanceOf[scala.collection.Seq] += 1
1 |???.asInstanceOf[scala.collection.Seq] += 1
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |collection.Seq takes type parameters
```
