### ISSUE TITLE
Using `$new` breaks exhaustivity checking

### ISSUE THREAD

**Issue by kubukoz** [lampepfl/dotty#12469]
## Compiler version

3.0.0

## Minimized code

```scala
enum Example {
  case Good(s: String)
  case Bad
}

object Example {
  val anon = $new(10, "anon")
}

@main def demo = Example.anon match {
  case Example.Good(s) => println(s)
  case Example.Bad     => println("ok")
}
```

## Output

```scala
[E] Exception in thread "main" scala.MatchError: anon (of class Example$$anon$1)
[E]     at Main$package$.demo(Main.scala:22)
[E]     at demo.main(Main.scala:20)
```

## Expectation

One of the following:

- Warning: "Match may not be exhaustive"
- Compilation error (`$new` isn't accessible by user code)

Note: if I add a wildcard (`case anything => `) to the pattern match, I get the wrong warning:

`Only null is matched. Consider using case null => instead.`

**Comment by odersky** [comment]
I don't think this needs fixing. We have already stated that all identifiers with `$`'s in them are reserved. You use them at your own risk. Java has the same policy.

**Comment by som-snytt** [comment]
Gitter joke was `import language.experimental.$`, but that is to say that it is the job of a linter to enforce policies that are more strict.

**Comment by neko-kai** [comment]
@som-snytt Why a joke though? For prior art, Haskell had -XMagicHash which is the same thing in effect. In the name of further user-friendly restrictions we could disable references to all names with `$` without language import, after all something Haskell does can't be bad!

**Comment by som-snytt** [comment]
@neko-kai It is a judgment call, but I am coming around to the side of minimal warnings and behavioral options. Let a thousand plugins bloom. `scalac` need only enforce correctness, and expose API for 3rd party tooling, which is plentiful in today's ecosystem. With a friendly plugin, you could get warnings about deprecations, `dangerou$` identifiers, etc.

**Comment by kubukoz** [comment]
Just curious, why would anyone ever intentionally call `$new` if they're not the compiler?
