### ISSUE TITLE
Members of a package are not sorted alphabetically in API docs

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#12496]
## Compiler version

3.0.0

See the API documentation of the trait `Quotes#reflectModule`: https://dotty.epfl.ch/api/scala/quoted/Quotes$reflectModule.html

## Output

![Screenshot from 2021-05-17 10-13-10](https://user-images.githubusercontent.com/332812/118454627-df558300-b6f8-11eb-9b3f-8c714641f850.png)

The members are not sorted alphabetically. Since there are a lot of members, that makes it hard to jump from one to the other.

## Expectation

Sorting the members alphabetically would make it easier to navigate through the docs.

**Comment by nicolasstucki** [comment]
It looks like they use the definition order.

**Comment by pikinier20** [comment]
Currently, members are sorted alphabetically. It was done in #12789
