### ISSUE TITLE
Allow "Yskip" "YstopAfter" "YstopBefore" to specify TreeTransforms

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#125]
As for now, TreeTransforms are stacked into phases with dynamically generated names, which renders disabling single TreeTransform impossible in case when squashing of transforms is enabled(which is default).

**Comment by DarkDimius** [comment]
Implemented in #377

**Comment by nicolasstucki** [comment]
@DarkDimius can we close this one?
