### ISSUE TITLE
-rewrite -indent breaks for-expressions with blocks for further processing via -rewrite -new-syntax

### ISSUE THREAD

**Issue by nemoo** [lampepfl/dotty#12503]
## Compiler version

3.0.0

## Minimized code before the rewrite
```
object RewriteTest {
  def main(args: Array[String]): Unit = {
    for { i <-  List(1,2,3)}
      {
        val a = 2
        println(s"$a")
      }
  }
}
```

## Output after compiling with options -rewrite -**indent**
```
object RewriteTest:
  def main(args: Array[String]): Unit =
    for { i <-  List(1,2,3)}
        val a = 2
        println(s"$a")
```

When I try to rewrite further by using compile -rewrite -**new-syntax** , the compiler produces this error: 

```
[error] -- [E018] Syntax Error: C:\gitrepo\scala3\src\main\scala\RewriteTest.scala:6:28 
[error] 6 |    for { i <-  List(1,2,3)}
[error]   |                            ^
[error]   |                            expression expected but val found
[error] -- [E006] Not Found Error: C:\gitrepo\scala3\src\main\scala\RewriteTest.scala:8:19 
[error] 8 |        println(s"$a")
[error]   |                   ^
[error]   |                   Not found: a

```

I am able to successfully call compile -rewrite -new-syntax when I first **manually** add the 'do'  keyword:
```
  for { i <-  List(1,2,3)} do
        val a = 2
        println(s"$a")
```
The final compilation produces the expected transformed code:
```
    for  i <-  List(1,2,3) do
        val a = 2
        println(s"$a")
```

## Expectation
The expectation is that the -rewrite -indent option honors code blocks correctly in conjunction with -rewrite -new-syntax.

**Comment by smarter** [comment]
From https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html:
> The -indent option only works on new-style syntax. So to go from old-style syntax to new-style indented code one has to invoke the compiler twice, first with options -rewrite -new-syntax, then again with options -rewrite -indent

So you need to do it in the opposite order.

**Comment by nemoo** [comment]
ok, then it is a documentation bug. I followed the instructions of the migration guide:

**Comment by smarter** [comment]
Indeed, please open an issue in https://github.com/scalacenter/scala-3-migration-guide/issues
