### ISSUE TITLE
import * means wildcard with 3.0-migration

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#12512]
## Compiler version

3.0.0 (only tested in REPL)

## Minimized code

```Scala
// REPL with -source:3.0-migration
class Operations {
  def *(i: Int, j: Int) = i * j
  def println(any: Any): Unit = ???
}

object Main extends App {
  val ops = new Operations()
  import ops.*
  println(*(2, 3))
}

val _ = Main
```

## Output

```scala
scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(Predef.scala:345)
  at rs$line$1$Operations.println(rs$line$1:3)
  at rs$line$1$Main$.<clinit>(rs$line$1:9)
```

## Expectation

print 6

**Comment by som-snytt** [comment]
What is the corrective syntax?
```
import ops.`*`
```
?

**Comment by tgodzik** [comment]
Also fails when running from sbt on `3.0.1-RC1`.

**Comment by nicolasstucki** [comment]
It seems that we should be able to add the following rewrite rule

```diff
-  import p.*
+  import p.`*`
```

**Comment by nicolasstucki** [comment]
We should also be able to detect if a `import p.*` imports a `*` and emit a waring.

**Comment by odersky** [comment]
I honestly think it's not important enough for a specialized rewrite rule. There's not a single instance where this happens in the community build.

**Comment by bishabosha** [comment]
my point here is that under `3.0-migration` no "new syntax" should be allowed, so shouldn't this behave as `import foo.*` would in scala 2?
