### ISSUE TITLE
REPL tab completion includes spurious Any members

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#12514]
## Compiler version

```
➜  dotty git:(master) ./bin/scala -version
Scala compiler version 3.0.1-RC1-bin-SNAPSHOT-git-62f202b -- Copyright 2002-2021, LAMP/EPFL
```

## Minimized code

```Scala
scala> import scala.util.chaining.`s
scalaUtilChainingOps   synchronized
```
and then
```
scala> import scala.util.chaining.`sc
asInstanceOf           scalaUtilChainingOps
isInstanceOf           synchronized
```
and completion after `sca`
```
scala> import scala.util.chaining.`scasInstanceOf
```

I guess it's because package object?
```
scala> scala.util.chaining.asInstanceOf[Any]
val res1: Any = scala.util.package$chaining$@563843f1
```

## Output

```scala
// as shown
```

## Expectation

Tab completion shows actual members of thing being completed.

**Comment by griggt** [comment]
I'm unable to reproduce this:

```
$ ./bin/scala -version
Scala compiler version 3.0.1-RC1-bin-SNAPSHOT-git-62f202b -- Copyright 2002-2021, LAMP/EPFL

$ ./bin/scala
scala> import scala.util.chaining.`sc
scalaUtilChainingOps
```

(I presume the backtick is an indication of where the tab key was pressed)

**Comment by som-snytt** [comment]
Hmm. It's the same with 3.0.0 release or local project.
```
➜  ~ ~/projects/dotty/bin/scala
scala> 42
val res0: Int = 42

scala> import scala.util.chaining.s
scalaUtilChainingOps   synchronized
```

The backtick may have been because I expected a backticked identifier for the implicit.

**Comment by griggt** [comment]
Aha, so the backtick was part of the input!  I tried that originally but there were no completions...or as it turns out, I am too impatient, as the completions when the backtick is included turn out to be very slow to appear here.

I can reproduce now, when including the backtick as typed input.
