### ISSUE TITLE
StackOverFlowError while compiling Eff

### ISSUE THREAD

**Issue by exoego** [lampepfl/dotty#12531]
cc: @xuwei-k 

## Compiler version

`3.0.0`

## Minimized code

Sorry, I could not prepare a true minimized code, but prepare a very small repro.

### How to repro
```
git clone -b mvp https://github.com/exoego/eff.git 
cd eff
sbt compile
```

### code
```scala
package org.atnos.eff

import cats._
import cats.syntax.all._

case class Last[R](value: Option[Eval[Eff[R, Unit]]]) {
  def *>(other: Last[R]): Last[R] = ???
}
object Last {
  def none[R]: Last[R] = ???
}

sealed trait Effect[R, A]
sealed trait Union[R, A] extends Effect[R, A]
case class Unions[R, A](first: Union[R, A], rest: Vector[Union[R, Any]])

case class Continuation[R, A, B](functions: Vector[Any => Eff[R, Any]], onNone: Last[R] = Last.none[R]) {
  def map[C](f: B => C): Continuation[R, A, C] = ???
  def dimapEff[C, D](f: C => A)(g: Eff[R, B] => Eff[R, D]): Continuation[R, C, D] = ???
}

sealed trait Eff[R, A]
case class Pure[R, A](value: A, last: Last[R] = Last.none[R]) extends Eff[R, A]
case class Impure[R, X, A](union: Effect[R, X], continuation: Continuation[R, X, A], last: Last[R] = Last.none[R]) extends Eff[R, A]
case class ImpureAp[R, X, A](unions: Unions[R, X], continuation: Continuation[R, Vector[Any], A], last: Last[R] = Last.none[R]) extends Eff[R, A]

trait EffImplicits {
  final def EffApplicative[R]: Applicative[Eff[R, *]] = effApplicativeUnsafeImpl.asInstanceOf[Applicative[Eff[R, *]]]

  private[this] final val effApplicativeUnsafeImpl: Applicative[Eff[AnyRef, *]] = new Applicative[Eff[AnyRef, *]] {
    def pure[A](a: A): Eff[AnyRef, A] = ???
    override def product[A, B](fa: Eff[AnyRef, A], fb: Eff[AnyRef, B]): Eff[AnyRef, (A, B)] = ???

    def ap[A, B](ff: Eff[AnyRef, A => B])(fa: Eff[AnyRef, A]): Eff[AnyRef, B] =
      fa match {
        case Pure(a, last) =>
          ff match {
            case Pure(f, last1)                   => Pure(f(a), last1 *> last)
            case Impure(u: Union[_, _], c, last1) =>
              // NOTE) StackOverFlowError is gone if the below line is replaced with ???
              ImpureAp(Unions(u, Vector.empty), c.dimapEff((_:Vector[Any]).head)(_.map(_(a))), last1 *> last)
            case ImpureAp(u, c, last1)            => ImpureAp(u, c.map(_(a)), last1 *> last)
          }
        case Impure(u: Union[_, _], c, last) => ???
        case ImpureAp(unions, c, last) => ???
      }
  }
}
```

## Output (click arrow to expand)
<details>
[info] welcome to sbt 1.5.2 (AdoptOpenJDK Java 1.8.0_282)
[info] loading project definition from /Users/uu197812/IdeaProjects/tmp/eff/project
[info] loading settings for project eff from build.sbt ...
[info] set current project to eff (in build file:/Users/uu197812/IdeaProjects/tmp/eff/)
[info] Executing in batch mode. For better performance use sbt's shell
[info] compiling 1 Scala source to /Users/uu197812/IdeaProjects/tmp/eff/target/scala-3.0.0/classes ...
java.lang.StackOverflowError while compiling /Users/uu197812/IdeaProjects/tmp/eff/src/main/scala/org/atnos/eff/Eff.scala
[error] ## Exception when compiling 1 sources to /Users/uu197812/IdeaProjects/tmp/eff/target/scala-3.0.0/classes
[error] java.lang.StackOverflowError
[error] dotty.tools.dotc.core.Substituters$.substParam(Substituters.scala:145)
[error] dotty.tools.dotc.core.Substituters$SubstParamMap.apply(Substituters.scala:193)
[error] dotty.tools.dotc.core.Types$TypeMap.mapOver(Types.scala:5234)
[error] dotty.tools.dotc.core.Substituters$.substParam(Substituters.scala:145)
...(snip(
</details>

**Comment by smarter** [comment]
This appears to be fixed with recent nightlies (tested with `scalaVersion := "3.0.1-RC1-bin-20210518-4bf2f04-NIGHTLY"`)
