### ISSUE TITLE
Implement something like scalac -Ybrowse to visually inspect trees and types

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1253]
`scalac` has this neat feature where you can inspect the AST by clicking around in a GUI:

``` scala
scalac -Ybrowse:typer examples/hello.scala
```

![Ybrowse example](https://i.imgur.com/vIwdHIY.png)

It would be interesting to try to do something similar in dotty, probably using HTML for the GUI instead of Swing (because Swing is Satan).
The implementation in `scalac` is contained in https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/ast/TreeBrowsers.scala

**Comment by smarter** [comment]
For reference, if you're looking for inspiration for tools with visual debugging capabilities, [Pharo](http://pharo.org/) (a smalltalk-like environment and language) does some really awesome stuff: https://vimeo.com/97315968

**Comment by OlivierBlanvillain** [comment]
Sounds like this could be a cool semester / GSOC project, but should we keep it as an open issue?

**Comment by smarter** [comment]
I'm OK with closing it if you want to keep the issue list lean.
