### ISSUE TITLE
Inaccurate warning with -Ysafe-init with enum and nested object in companion

### ISSUE THREAD

**Issue by TVerse** [lampepfl/dotty#12544]
## Compiler version

Scala 3.0.0 with compiler flag `-Ysafe-init`.

## Minimized code

```Scala
enum Enum:
  case Case

object Enum:
  object nested:
    val a: Enum = Case

  val b: Enum = f(nested.a)

  def f(e: Enum): Enum = e

@main def main(): Unit = println(Enum.b)
```

## Output

```
> sbt run
<SNIP>
[warn] -- Warning: <PATH>
[warn] 8 |  val b: Enum = f(nested.a)
[warn]   |                  ^^^^^^^^
[warn]   |Promoting the value under initialization to fully-initialized. Calling trace:
[warn]   | -> val b: Enum = f(nested.a) [ Enum.scala:8 ]
[warn] one warning found
[warn] one warning found
[info] running main
Case
```

## Expectation
No warning. Given that it prints correctly, the value was correctly initialized. I believe there's no real initialization order issue here: when `b` initializes, `nested` gets initialized and `nested.a` with it.

Things that do not cause a warning:
* Using a case class, `Int`, or `String` instead of the enum
* Renaming the outer object so it's not a companion anymore
* `val a: Enum = ???` (this breaks when printing of course)

**Comment by liufengyun** [comment]
Thanks for your report @TVerse . It's fixed in the master, and will be part of 3.0.1.

**Comment by liufengyun** [comment]
If the promotion warning is happens when we pass an instance of inner class as method arguments.

For example, given the following program:

```Scala
def g(b: O.B): Int = b.foo()

object O:
  class B() { def foo() = n + 1 }
  g(new B())
  val n: Int = 10
```

The checker reports the following warning:

```Scala
-- Warning: tests/init/neg/i12544.scala:5:4 ------------------------------------
5 |  g(new B())
  |    ^^^^^^^
  |    Promoting the value to fully-initialized is unsafe.
  |     Calling trace:
  |     -> g(new B())	[ i12544.scala:5 ]
  |
  |    The unsafe promotion may cause the following problem(s):
  |
  |    1. Access non-initialized value n. Calling trace:
  |     -> g(new B())	[ i12544.scala:5 ]
  |       -> class B() { def foo() = n + 1 }	[ i12544.scala:4 ]
```

**Comment by TVerse** [comment]
Thank you!
