### ISSUE TITLE
flame graphs for compilation performance analysis

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1254]
As performance is an important concern of dotty, I think the feature of generating flame graphs is going to be helpful at some point. It's possible to do both on-cpu and off-cpu flame graphs.

Here is a sample flame graph:

![](http://www.brendangregg.com/FlameGraphs/cpu-mixedmode-flamegraph-java.svg)

Reference:

- [Java in Flames](http://techblog.netflix.com/2015/07/java-in-flames.html)
- [Off-CPU analysis](http://www.brendangregg.com/offcpuanalysis.html)

**Comment by smarter** [comment]
Besides the coolness of the visualisation, the interesting thing about using low-level profiles like this is that you avoid the imprecision of sampling profiles on the JVM: http://psy-lob-saw.blogspot.fr/2016/02/why-most-sampling-java-profilers-are.html

**Comment by liufengyun** [comment]
BTW, the interactive flame graph I linked above doesn't work well, following link to the original SVG works well:

http://www.brendangregg.com/FlameGraphs/cpu-mixedmode-flamegraph-java.svg

**Comment by liufengyun** [comment]
I have been playing with flamegraph during the holiday. It doesn't look good. As Dmitry commented, flamegraphs don't work well with recursive functions. I close this issue for now.

https://dl.dropboxusercontent.com/u/54580502/flamegraph.svg

**Comment by DarkDimius** [comment]
@liufengyun it seems that the flame grave you have build is for jvm that used frame pointer for different purposes. Try building it with `-XX:+PreserveFramePointer` passed to java, it should look better.
