### ISSUE TITLE
Indented function params rules

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#12554]
## Compiler version

3.0.0

## Minimized code

This one compiles:
```Scala
def f(s: String)(t: String) = s"$t: $s"

def g =
  f("Foo")
    ("Bar")
```

but:

```scala
def f(s: String)(t: String) = s"$t: $s"

def g =
  f("Foo")
  ("Bar")
```

does not.

This looks like a feature/bug connected to optional braces and I am not sure if the exact rule is mentioned anywhere. It's not mentioned here https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html as far as I can tell.

**Comment by odersky** [comment]
Yes, that's a separate tweak for newline insertion. A newline is inserted between `)` and `(` on the next line only if the next line is not indented relative to the previous line.

**Comment by tgodzik** [comment]
Just a follow up. It seems it's exactly the same situation with `}`, which changes the Scala 2 behaviour.

To quote example from @dos65 : 
```scala
def fun(a: Int, b: Int, c: Int)(d: Int): String = ???
def method: String = 
  fun(1, 2, 3) 
    {4} // <- this  Term.Apply(Term.Apply("fun", ...), "d")
def method2: String = 
  fun(1, 2, 3)
  {4} // <- doesn't compile - `{4}` is not part of apply
      // but scalameta parses it the same way as above -  Term.Apply(Term.Apply("fun", ...), "d")
```
