### ISSUE TITLE
Windows & Scala 3 UX - consistency

### ISSUE THREAD

**Issue by ScalaWilliam** [lampepfl/dotty#12550]
Hi all!

Just noticed Scala 3 is now officially on the scala-lang.org website - that's absolutely fantastic! I would like to share some of my findings from a Windows user's point of view, that could be smoother.

**My suggestion**

For Windows users, at the Download page, give only 1 choice, which is the "Scala Installer" (don't confuse them with SBT, and Coursier -- they probably heard of Scala only 5 minutes ago!). If anything, they could also be offered an offline installer with a small link below (which includes all the dependencies). Once the "Scala Installer" (Coursier) installs everything, it opens an HTML page with instructions how to use Scala.

![image](https://user-images.githubusercontent.com/2464813/119060539-48bfe500-b9ca-11eb-8974-167feb7a0d9f.png)

HTML (edited rapidly, so 🦅 )

```html
<div class="install-steps">


<div class="download-options">
  <div class="download-left">
    
    <a href="https://git.io/coursier-cli-windows-exe" class="btn-download">
      <i class="fa fa-download"></i>
      <span>Download the Scala installer (.exe, 64-bit)</span>
    </a>
    <div class="text-variant" style="text-align:center">
      <p style="font-style:italic">Do you need an offline installer? <a>Download here (59MB)</a>.</p>
<p>The Scala Installer will install Scala as well as various utilities like SBT, Coursier, scalafmt, the Ammonite REPL, all of which you can use from PowerShell or cmd. <u>Batteries included</u>.</p>
      
    </div>
  </div>
  
</div>
</div>
```

**Current UX & Explanation**

First, the download instructions on the homepage point to the Coursier & SBT websites.
![image](https://user-images.githubusercontent.com/2464813/119059298-ef56b680-b9c7-11eb-9ff0-7dcd65eb9370.png)

You may then choose to do a quick set-up with Coursier, however for Windows users to enter commands like 'bitsadmin', is very unusual; people rarely ever do this on Windows.
![image](https://user-images.githubusercontent.com/2464813/119057408-5a9e8980-b9c4-11eb-9e0b-e94492e87783.png)
(also the Windows instruction here is below the fold so you take a bit of time to find it; I include some examples of how Python and Nodejs do it below).

There is another page, getting started, which instead has a link to the Coursier binary. Windows shows it may be unsafe - is there any way to fix this? ![image](https://user-images.githubusercontent.com/2464813/119057107-c6342700-b9c3-11eb-91d2-cbf6633034b8.png)

This could be 'the' installer, and after installing you should get greeted with a message how to proceed. In fact, after running it myself, I was very pleased that everything I needed was installed, which is absolutely fantastic.

Let's look at Python:
When you go to the Python website, and try to download, it gives you a .exe, which you then open,
![image](https://user-images.githubusercontent.com/2464813/119058197-cf25f800-b9c5-11eb-80ab-fd60f0b0a88d.png)

And then it gives you an installer (I already have it installed).
![image](https://user-images.githubusercontent.com/2464813/119058358-27f59080-b9c6-11eb-9e0a-81fc1e2631c8.png)

Node.js:
![image](https://user-images.githubusercontent.com/2464813/119058558-8458b000-b9c6-11eb-836d-dc6cf00635b5.png)

(this one I also have installed 😁 )
![image](https://user-images.githubusercontent.com/2464813/119058581-90dd0880-b9c6-11eb-9ca8-bc2fdd9cd22a.png)

There could be a segment of the market who might jump off at this point because this is their first point of touch with Scala, especially if coming for example from .NET which has all-inclusive GUI installers and similar.

While many people in the Scala community use Mac we could definitely do better with smoother support for Windows, especially considering inclusivity; many potential members of the Scala community might come from countries where a Mac costs several months of salary, and normally use the OS that came with their PC, Windows; however they might drop off early despite all the amazing efforts done by the Scala community. Python's start-up UX is great and I believe is a huge contributor to its popularity.

**Comment by OlivierBlanvillain** [comment]
I'm not sure this issue belong to this repository, maybe it should be moved to https://github.com/scala/scala-lang ?

**Comment by fenginsc** [comment]
In fact, you just want an MSI installation package for scala3.
Because scala2 already provides MSI installation package, it is appropriate to put this proposal here.

**Comment by ScalaWilliam** [comment]
Hi @odersky just noticed this was closed, but also saw that the suggestion was taken (although partly). The download is a ZIP file with an .exe file (think it should be just .exe), after opening which, you see this, which I believe does not happen with competing languages:
![image](https://user-images.githubusercontent.com/2464813/162294637-322a9fbf-e0db-4771-a456-71ddaf1585d8.png)

Is it worth having another ticket or should this go straight to coursier about this?

**Comment by som-snytt** [comment]
The related forum thread is picking up steam https://contributors.scala-lang.org/t/pre-sip-scala-cli-as-new-scala-command/5628

I sense that no one knows whose lap this should land in.

The comment above from last year suggests the other repo.

But I'm sure whoever takes it on will appreciate all inputs.

**Comment by michelou** [comment]
@ScalaWilliam I suggest you to visit the following pages from my GitHub project [`michelou/wix-examples`](https://github.com/michelou/wix-examples/) : 
1. [WiX examples with Scala 3 distribution](https://github.com/michelou/wix-examples/blob/main/scala3-examples/README.md)
2. [MSI Files](https://github.com/michelou/wix-examples/blob/main/MSI.md)
3. [Security of MSI files](https://github.com/michelou/wix-examples/blob/main/SECURITY.md)
4. [Releases](https://github.com/michelou/wix-examples/releases) (MSI 3.1.2 will be available very soon)

**Comment by ScalaWilliam** [comment]
@michelou nice! could these be considered for adoption? :-)

**Comment by odersky** [comment]
The whole discussion should be taken to scala-lang. /cc @julienrf @bishabosha

**Comment by julienrf** [comment]
Thank you @odersky for bringing this to my attention. I am re-opening the issue, and it will be moved to the repository scala/docs.scala-lang.
