### ISSUE TITLE
Compiletime ops within match types are evaluated too eagerly 

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#12587]
It turns out that `compiletime.ops.*` operations that are applied in a match type occur eagerly and unconditionally. Meaning that if we have a match type like the following:
```
type Foo[T] = T match 
  case X => Op[X]
  case Y => Op[Y]
```
And if `Op` is a compiletime.ops operation then all the case branches are evaluated anyway and at the definition site of `Foo` and not where it is applied.

## Compiler version

v3.0.1-RC1 master branch

## Minimized code

```Scala
import compiletime.ops.int.+
type TwiceOrElse[T, E <: Int] <: Int = T match 
  case Some[x] => x + x
  case None.type => E

val x : TwiceOrElse[5, 3] = 10
```

## Output

```scala
   |val x : TwiceOrElse[5, 3] = 10
   |                            ^^
   |                            Found:    (10 : Int)
   |                            Required: TwiceOrElse[(5 : Int), (3 : Int)]
   |
   |                            Note: a match type could not be fully reduced:
   |
   |                              trying to reduce  TwiceOrElse[(5 : Int), (3 : Int)]
   |                              failed since selector  (5 : Int)
   |                              matches none of the cases
   |
   |                                case Some[x] => x + x
   |                                case None.type => (3 : Int)
```

## Expectation
`compiletime.ops` operations should be inferred lazily, so that the above will compile.

**Comment by smarter** [comment]
The error message looks correct here: you're matching T against Some[x] and None.type, but T=5 so it doesn't match.

**Comment by soronpo** [comment]
Oh, yeah. So much experimentation, I missed that. This indeed works:
```
val x : TwiceOrElse[Some[5], 3] = 10
```
