### ISSUE TITLE
“No singleton value available for A” where A is clearly a singleton

### ISSUE THREAD

**Issue by epifab** [lampepfl/dotty#12583]
## Compiler version

3.0.0

## Minimized code

```Scala
case class Wrapper[A <: Singleton](a: A)(using ValueOf[A])

def test[A <: Singleton](blabla: Wrapper[A]): Unit = ()

test(Wrapper("yo"))
```

## Output

> No singleton value available for A
> where: A is a type variable with constraint >: ("yo" : String) and <: Singleton

## Expectation

It looks like the compiler could infer the right type for `A` (`"yo": String`) but then it can't find a `ValueOf` instance for it

**Comment by epifab** [comment]
both the following workaround fix the issue:
```scala
test["yo"](Wrapper("yo"))
```
and
```scala
val yo = Wrapper("yo")
test(yo)
```

**Comment by prolativ** [comment]
Another workaround:
```
case class Wrapper[A <: Singleton](a: A)(using ValueOf[a.type])

def test[A <: Singleton](blabla: Wrapper[A]): Unit = ()

test(Wrapper("yo"))
```
The question here is whether the compiler, knowing that `A <: Singleton`, should be able to tell that `A =:= a.type`

**Comment by epifab** [comment]
also, this seems to be a regression from Scala 2
