### ISSUE TITLE
Given instance not imported when importing entire package/object

### ISSUE THREAD

**Issue by Iltotore** [lampepfl/dotty#12609]
## Compiler version
3.0.0

## Minimized code

`numeric.scala`
```Scala
trait Test {
  def testMethod: String
}

object test {

  given Test with {
    override def testMethod: String = "Hello"
  }
}
```

```scala
import test._

@main def test = {
  implicitly[Test]
}
```

## Output

```scala
no implicit argument of type Test was found for parameter e of method implicitly in object Predef

The following import might fix the problem:

  import test.given_Test
```

Actually works when importing `test.given_Test`

## Expectation
The minimized code should compile because `test.given_Test` is imported through `import test._`

**Comment by som-snytt** [comment]
https://dotty.epfl.ch/docs/reference/contextual/given-imports.html for explanation.

**Comment by soronpo** [comment]
As @som-snytt mentioned, this is the expected behavior, since in Scala 3 the givens import must be explicit: `import test.{*, given}`

**Comment by Iltotore** [comment]
Hello, shouldn't be this mentioned in the [Given Instances](https://dotty.epfl.ch/docs/reference/contextual/givens.html) page ?

**Comment by som-snytt** [comment]
Reference pages or a spec will suffer from that problem, that you have to know a, b, and c about a feature to use it, but those items are defined in disparate sections of the text. A tutorial might introduce a, b, and c together, albeit in a reduced form, to arrive at a working example quickly.

I also have this problem looking up some syntax, even if I'm looking it up a second or third time. An automated index or cross-reference might help in this regard. Maybe I'll lodge a feature request.
