### ISSUE TITLE
Please merge in latest ProtoQuill into community build

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#12625]
Hi, I made a PR to merge in latest ProtoQuill into the community build here:
https://github.com/dotty-staging/protoquill/pull/1

Could someone please merge this?
Sorry if this is the wrong place for requests like this. How should I do it in the future?

**Comment by smarter** [comment]
I've given you push access to that repo, so you can just push there then open a PR here to update the submodule commit. Just make sure to never push-force and overwrite existing commits since that would prevent existing commits from passing the CI.

**Comment by deusaquilus** [comment]
Okay. Thanks!
Should I open up the submodule commit against dotty or dotty-staging?

**Comment by smarter** [comment]
against this repo, lampepfl/dotty

**Comment by deusaquilus** [comment]
Okay, just opened. https://github.com/lampepfl/dotty/pull/12630
Thanks!

**Comment by deusaquilus** [comment]
@smarter Any chance you can approve my workflow in https://github.com/lampepfl/dotty/pull/12630 ?

**Comment by deusaquilus** [comment]
Working now. Thanks!

**Comment by deusaquilus** [comment]
@smarter I restarted the builds. Looks like I need approval again. Sorry
