### ISSUE TITLE
val and single given pattern combination

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#12629]
## Compiler version

3.0.0

## Minimized code

```Scala
case class A(i: Int)
case class B(b: Boolean)

def test =
  val (given A) = A(23)
  val given B = B(false)
```

## Output

compiles ok

## Expectation

`val given B` is treated as a pattern val def, but this is too close to `given B = B(false)` so I would expect a syntax error in favour of the alias given,

alternatively, with #11897 fixed, it could be a way to define a (non-lazy) given?

**Comment by bishabosha** [comment]
it seems that this pattern was known about and explicitly allowed in https://github.com/lampepfl/dotty/blob/d09981141ea16a98c654b98ca582b9626bf0ff0b/tests/neg/given-pattern.scala#L7

**Comment by odersky** [comment]
How do you propose to change the syntax to support the distinction?

**Comment by bishabosha** [comment]
in the dotty meeting we decided to make this an error
