### ISSUE TITLE
version issue

### ISSUE THREAD

**Issue by chen-bob** [lampepfl/dotty#12628]
Hi there, I got this on ubuntu 18.04 with scala 3 from https://github.com/lampepfl/dotty/releases/download/3.0.0/scala3-3.0.0.tar.gz :

[me@ubuntu:~/scala_project]$ /usr/share/scala3-3.0.0/bin/scala
scala> scala.util.Properties.versionString
val res0: String = version 2.13.5

Why the version is not 3? Thanks!

**Comment by smarter** [comment]
Because it's the version of the standard library, there is no mechanism for getting the compiler version currently.
