### ISSUE TITLE
Given within for-comprehension not found

### ISSUE THREAD

**Issue by qwbarch** [lampepfl/dotty#12646]
## Compiler version

3.0.0

## Minimized code

Declaring a result as ``given`` works as expected if I'm flat-mapping to another monadic value. For example:
```scala
for
   given Int <- List(0)
   x <- List(summon[Int])
yield x
```
Scastie: https://scastie.scala-lang.org/9nPXzZH0QEaVzz3zI4ER8g

However, if the next step in the for-comprehension is a variable, the given is not found. For example:
```scala
for
   given Int <- List(0)
   x = summon[Int]
yield x
```
Scastie: https://scastie.scala-lang.org/1cuJc8bcS4q59Y5ZoSQ4bw

## Output

```scala
no implicit argument of type Int was found for parameter x of method summon in object Predef
```

## Expectation

It should compile just like the first example.

**Comment by smarter** [comment]
@bishabosha is this perhaps related to https://github.com/lampepfl/dotty/pull/12631 ?

**Comment by bishabosha** [comment]
> @bishabosha is this perhaps related to #12631 ?

I don't think so - it seems that the code path that recognises given pattern as irrefutable is only checked for generator enumerators not alias enumerators

https://github.com/lampepfl/dotty/blob/d9799a8e3374cd3bee8becb39c950022fb525f41/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L1590

**Comment by dwijnand** [comment]
Looks like the translation happens during typer.  (Couldn't tell just from comparing -Xprint outputs why things go how they go.)

**Comment by kubukoz** [comment]
A nasty workaround that's less unpleasant than no givens at all... adding a dummy value to flatMap on before you use the newly created given.

```scala
trait demo {
  trait A
  trait B
  def mkA: Option[A]
  def mkB(using A): B

  val dummy: Option[Any] = Some(42)

  def example = for {
    given A <- mkA
    _ <- dummy
    given B = mkB
  } yield ()
}
```

but yeah, it would be great if it just worked. FWIW it seems `withFilter` is involved, ignoring the `<- dummy` line with a type that doesn't have it issues:

```
value withFilter is not a member of demo.this.Op[demo.this.A]
```

<details>
<summary>code that produced this</summary>

```scala
trait demo {
  trait Op[X] {
    def flatMap[B](f: X => Op[B]): Op[B]
    def map[B](f: X => B): Op[B]
  }
  trait A
  trait B
  def mkA: Op[A]
  def mkB(using A): B

  val dummy: Op[Any]

  def example = for {
    given A <- mkA
    // _ <- dummy
    given B = mkB
  } yield ()
}
```

</details>

all tested on 3.0.2.

**Comment by bishabosha** [comment]
another example from #14836
```scala
trait C
object C:
  def provide: Option[C] = Some(new C {})

def consume(arg: Int)(using C): Unit = ()

val result1 = for {
  given C <- C.provide
  a = consume(42) // Error: no implicit of type C
} yield a


val result2 = for {
  c <- C.provide
  a = {
    given C = c
    consume(42) // this works fine
  }
} yield a
```
