### ISSUE TITLE
Tuple.Map and upper bounds

### ISSUE THREAD

**Issue by Adam-Vandervorst** [lampepfl/dotty#12645]
## Compiler version

3.0.0-RC3
## Minimized code

```Scala
case class TBox[A <: Tuple](v: A)

@main def m =
    val t: TBox[EmptyTuple] = TBox(EmptyTuple) // works
    val tt: Tuple.Map[(EmptyTuple, EmptyTuple), TBox] = (TBox(EmptyTuple), TBox(EmptyTuple))
```

## Output

```
Type argument TBox does not conform to upper bound [_$4] =>> Any
    val tt: Tuple.Map[(EmptyTuple, EmptyTuple), TBox] = (TBox(EmptyTuple), TBox(EmptyTuple))
```

## Expectation
Since the first line of the main function and the snippet below work, I expected the above to work too.
```scala
case class ABox[A](v: A)

@main def main_f = {
    val a: ABox[Int] = ABox(1)
    val ta: Tuple.Map[(Int, Int), ABox] = (ABox(1), ABox(2))
```

**Comment by smarter** [comment]
The second parameter of Tuple.Map is `F[_]`, meaning that one has to pass a type lambda that can be applied to any type parameter, this isn't the case of `TBox` which requires its type parameter to be a subtype of `Tuple`, hence the error message. It looks like this is fixable by changing that second parameter type to be upper-bounded by `Union[Tup]` instead:
```scala
object Test {
  type Map[Tup <: Tuple, F[_ <: Tuple.Union[Tup]]] <: Tuple = Tup match {
    case EmptyTuple => EmptyTuple
    case h *: t => F[h] *: Map[t, F]
  }
  case class TBox[A <: Tuple](v: A)
  val tt: Map[(EmptyTuple, EmptyTuple), TBox] = (TBox(EmptyTuple), TBox(EmptyTuple)) // now OK
}
```
The same change might be applicable to other match types in Tuple too /cc @nicolasstucki

**Comment by smarter** [comment]
To clarify, the fix also works when the second parameter upper-bound is not Tuple:
```scala
  case class IBox[A <: Int](v: A)
  val tt: Map[(1, 2), IBox] = (IBox(1), IBox(2)) // now OK
```
