### ISSUE TITLE
Wrapped typeCheckErrors is emitting compilation errors

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#12656]
The `typeCheckErrors` when used inside another definition does not trap the error messages. 
Affects munit.

## Compiler version

v3.0.0 (also tested on nightly)

## Minimized code

```Scala
  transparent inline def expectCompileError(
      inline code: String,
      expectedMsg: String
  ) =
    val errors = compiletime.testing.typeCheckErrors(code)
    assert(errors.head.message == expectedMsg)

  expectCompileError("""compiletime.error("some error")""", "some error")
```

## Output

```scala
error: some error
```

## Expectation
No compilation error (the error should be trapped)

**Comment by soronpo** [comment]
@nicolasstucki I want to try and tackle this, since there is no easy workaround and I'm currently avoiding creating tests because of this. Any suggestion where to begin?

**Comment by nicolasstucki** [comment]
This test should catch what we need `tests/run/i12656.scala`

```scala
transparent inline def expectCompileError(
    inline code: String,
    expectedMsg: String
) =
  val errors = compiletime.testing.typeCheckErrors(code)
  assert(errors.head.message == expectedMsg, (errors.head.message, expectedMsg))

@main def Test = expectCompileError("""compiletime.error("some error")""", "some error")
```

We process `compiletime.error` here https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/typer/Inliner.scala#L335-L349.
We should probably set a new reporter that does not propagate the errors to the outer context reporter. The reporter can be set on the `TyperState`, maybe when we do `ctx.fresh.setNewTyperState()`.
