### ISSUE TITLE
Type class derivation does not work with type aliases

### ISSUE THREAD

**Issue by joroKr21** [lampepfl/dotty#12666]
## Compiler version

3.0.1-RC1-bin-SNAPSHOT

## Minimized code

```Scala
trait Foo[A, B]
object Foo:
  type Id[A] = Foo[A, A]
  given derived[A]: Id[A] with {}

case class Bar(x: Int) derives Foo.Id
```

## Output

```scala
6 |case class Bar(x: Int) derives Foo.Id
  |                               ^^^^^^
  |                       Bar cannot be unified with the type argument of Foo
```

## Expectation

should compile

**Comment by odersky** [comment]
No, it will always go to the underlying class. That's how it is supposed to work. Changing this would be very complex and very risky. Maybe someone wants to do an experiment along these lines?
