### ISSUE TITLE
Remove branches that should not be in this repo

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#12678]
These branches should have been created in forks of this project.
These were last updated by the mentioned user.

* https://github.com/lampepfl/dotty/tree/scaladoc/site-css-fix @pikinier20
* https://github.com/lampepfl/dotty/tree/scaladoc/searchbar-improvement @pikinier20
* https://github.com/lampepfl/dotty/tree/scaladoc/mdoc @pikinier20
* https://github.com/lampepfl/dotty/tree/test-master-2 @anatoliykmetyuk
* https://github.com/lampepfl/dotty/tree/test-master-playground @anatoliykmetyuk
* https://github.com/lampepfl/dotty/tree/oslib-debug @anatoliykmetyuk
* https://github.com/lampepfl/dotty/tree/community-build-sync @dotty-bot

**Comment by anatoliykmetyuk** [comment]
Removed my branches. The community-build-sync one appears to be one of @tdudzik.

**Comment by anatoliykmetyuk** [comment]
All branches removed
