### ISSUE TITLE
The type hierarchy chart in the "Explicit Nulls" document doesn't include the `Matchable` type

### ISSUE THREAD

**Issue by ShapelessCat** [lampepfl/dotty#12689]
The type hierarchy chart in this [Explicit Nulls](https://dotty.epfl.ch/docs/reference/other-new-features/explicit-nulls.html) page  doesn't include the `Matchable` type.
The description is also a little bit out of date, and it doesn't mention the relation between `Null` and `Matchable` after applying the `-Yexplicit-nulls` compiler flag.

**Comment by noti0na1** [comment]
I don't think `-Yexplicit-nulls` will affect `Null` and `Matchable` significantly.

`Null` will just become the direct subtype of `Any` and `Matchable`.

I need to update the diagram and description.

**Comment by bishabosha** [comment]
> I don't think `-Yexplicit-nulls` will affect `Null` and `Matchable` significantly.
> 
> `Null` will just become the direct subtype of `Any` and `Matchable`.

Are the following examples bugs?
```scala
$ scala -Yexplicit-nulls
scala> def foo[T <: Matchable](t: T) = t match { case t: Null => () }
1 |def foo[T <: Matchable](t: T) = t match { case t: Null => () }
  |                                               ^
  |        this case is unreachable since type T and class Null are unrelated

scala> def foo[T <: Matchable](t: T) = t match { case null => () }                                               
1 |def foo[T <: Matchable](t: T) = t match { case null => () }
  |                                               ^^^^
  |Values of types Null and T
  |
  |where:    T is a type in method foo with bounds >: (?1 : Null) and <: Matchable
  | cannot be compared with == or !=

scala> def foo[T <: Matchable](t: T) = t match { case t => println(s"got $t") }                                     
def foo[T <: Matchable](t: T): Unit

scala> foo(null)
got null
```

**Comment by noti0na1** [comment]
@bishabosha I think they are bugs.

**Comment by olhotak** [comment]
The diagram is an image generated using graphviz. Could the graphviz source of the diagram be stored in git somewhere? What would be the best place? Does the markdown processor used to generate the docs support graphviz?
