### ISSUE TITLE
Ambiguous reference error message does not know about rule change in #8622

### ISSUE THREAD

**Issue by lrytz** [lampepfl/dotty#12682]
```scala
object C {
  def m(x: Int) = 1
  object T extends K {
    val x = m(1)
  }
}
class K {
  def m(i: Int) = 2
}
```

gives

```
-- [E049] Reference Error: Test.scala:4:12 -------------------------------------
4 |    val x = m(1)
  |            ^
  |            Reference to m is ambiguous,
  |            it is both defined in object C
  |            and inherited subsequently in object T

Explanation
===========
The compiler can't decide which of the possible choices you
are referencing with m: A definition of lower precedence
in an inner scope, or a definition with higher precedence in
an outer scope.
Note:
 - Definitions in an enclosing scope take precedence over inherited definitions
 - Definitions take precedence over imports
 - Named imports take precedence over wildcard imports
 - You may replace a name when imported using
   import scala.{ m => mTick }
```

The `-explain` message even says "Definitions in an enclosing scope take precedence over inherited definitions".

**Comment by smarter** [comment]
This was intentionally changed in https://github.com/lampepfl/dotty/pull/8622, looks like the error message needs to be updated.

**Comment by lrytz** [comment]
👍

Ftr, Scala 2 actually resolves `m` to `K.m`, need to check if that's according to the spec.

**Comment by som-snytt** [comment]
I intended to follow up Scala 2 at https://github.com/scala/scala/pull/8839

**Comment by odersky** [comment]
The error message could be clearer, but is correct. There  is "A definition of lower precedence (i.e. inheritance)
in an inner scope, and a definition with higher precedence (i.e. definition) in an outer scope.".

**Comment by odersky** [comment]
I close since no better diagnostics was forthcoming.
