### ISSUE TITLE
summonFrom and by-name using don't work together

### ISSUE THREAD

**Issue by joroKr21** [lampepfl/dotty#12696]
## Compiler version

3.1.3-RC1

## Minimized code

```scala
import compiletime.{summonFrom, summonInline}

trait Tc[A]
def delegated[A](using tc: => Tc[A]): Tc[A] = new Tc[A] {}

inline given [A]: Tc[A] = summonFrom {
  case given Tc[A] => delegated[A]
}

summonInline[Tc[Int]]
```

I don't have minimized code because I'm using shapeless 3 and cats, but I have a branch with a reproduction: typelevel/kittens#360

It looks like `summonFrom` doesn't work with by-name givens (although shapeless 3 itself is mixing `summonFrom` with by-name givens).

## Output
https://github.com/typelevel/kittens/pull/360/checks?check_run_id=2734916700
```scala
[error] -- [E039] Reference Error: /home/runner/work/kittens/kittens/core/src/test/scala-3/cats/derived/ReducibleTests.scala:30:14 
[error] 30 |  summonInline[DerivedFunctor[MyList]]
[error]    |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |  t is a forward reference extending over the definition of t
[error]    | This location contains code that was inlined from package.scala:33
[error] one error found
```

## Expectation

should compile

**Comment by joroKr21** [comment]
Perhaps this can serve as a (trivial) minization:
```scala
trait Tc[A]
def delegated[A](using tc: => Tc[A]): Tc[A] = new Tc[A] {}

inline given [A]: Tc[A] = summonFrom {
  case given Tc[A] => delegated[A]
}

summonInline[Tc[Int]]
```

**Comment by bishabosha** [comment]
> Perhaps this can serve as a (trivial) minization:
> 
> ```scala
> import compiletime.{summonFrom, summonInline}
> 
> trait Tc[A]
> def delegated[A](using tc: => Tc[A]): Tc[A] = new Tc[A] {}
> 
> inline given [A]: Tc[A] = summonFrom {
>   case given Tc[A] => delegated[A]
> }
> 
> summonInline[Tc[Int]]
> ```

This has a new error in 3.0.1-RC1:
```scala
10 |summonInline[Tc[Int]]
   |             ^
   |             cannot reduce summonFrom with
   |              patterns :  case given given_Tc_A @ _:Tc[Int]
   | This location contains code that was inlined from rs$line$1:6
```

**Comment by joroKr21** [comment]
We have found a way around it: typelevel/kittens#359 I am not 100% if this is indeed a bug or just a weird interaction between `summonFrom` and by-name givens.

**Comment by joroKr21** [comment]
It doesn't crash and I think it's fine that this example can't be reduced.
