### ISSUE TITLE
default parameter values not passed to scala 2 tasty-reader

### ISSUE THREAD

**Issue by johnduffell** [lampepfl/dotty#12704]
## Compiler version

3.0.0 and 2.13.6 in a multi project build

## Minimized code

```Scala
// in a scala 3 module
case class Scala3CaseClass(value: Int = 1)

// and in a scala 2 module which has -Ytasty-reader
  val importedCaseClass = Scala3CaseClass() // fails with "not enough arguments for method apply"
```

I have pushed a full example SBT project here: https://github.com/johnduffell/tasty-default-param-bug

## Output

```scala
[error] /Users/john_duffell/code/tasty-default-param-bug/scala2/src/main/scala/scala2/Main.scala:8:42: not enough arguments for method apply: (value: Int): scala3.Scala3CaseClass in object Scala3CaseClass
[error]   val importedCaseClass = Scala3CaseClass() // fails with "not enough arguments for method apply"

```

## Expectation
It should compile the same as the scala 2 version

## Workaround
Remove the default parameter, and add an explicit/overloaded apply method in a companion object.

## Other info
I have shared the problem on scala/scala gitter channel and another user has hit the same issue.  I couldn't find an existing report.  Let me know if you need more info.

**Comment by bishabosha** [comment]
Hi, thank you for reporting this issue, would you be able to report it at https://github.com/scala/bug/issues and close this one?

**Comment by johnduffell** [comment]
as requested, closed in favour of https://github.com/scala/bug/issues/12409
