### ISSUE TITLE
Should match type cases be checked for disjointness?

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#12705]
## Compiler version

3.0.1-RC1

## Minimized example

```Scala
trait A
trait B
type M[X] = X match
  case A => Int
  case B => String
val x: String = ??? : M[B] // error
```

## Output

```scala
6 | val x: String = ??? : M[B] // error
  |                 ^^^^^^^^^^
  |               Found:    M[B]
  |               Required: String
  |
  |               Note: a match type could not be fully reduced:
  |
  |                 trying to reduce  M[B]
  |                 failed since selector  B
  |                 does not match  case A => Int
  |                 and cannot be shown to be disjoint from it either.
  |                 Therefore, reduction cannot advance to the remaining case
  |
  |                   case B => String
```

## Expectation

This error message suggests that it is impossible to match on the `B` case, so should we reject `case B => String` in the match type definition as being unreachable?

**Comment by odersky** [comment]
I think we already do a good job with the error messages. As soon as you write the first test you will see the error in your logic. Restricting the definition seems dicey.

**Comment by bishabosha** [comment]
perhaps we can give some general advice in the error, or point to a Q&A about matching with open class hierarchies
