### ISSUE TITLE
Parametrized enum case type is not widened when selecting a generic extension method

### ISSUE THREAD

**Issue by gabro** [lampepfl/dotty#12701]
## Compiler version

3.0.0, also tested on 3.0.1-RC1

## Minimized code

```Scala
enum Color:
  case Red(s: Int)

trait Id[A]:
  def id(a: A): A

given Id[Color] with
  def id(a: Color) = a

extension [A](a: A)
  def id(using ev: Id[A]): A = ev.id(a)

@main def main =
  Color.Red(1).id // A

  val x = Color.Red(1)
  x.id // B
```

Scastie: https://scastie.scala-lang.org/wan36bSGQmawIKWpiXULwA

## Output

This is the error we get at the point marked as `A`. `B` (same method, but invoked after assigning a val) compiles fine.

```scala
value id is not a member of Color.Red.
An extension method was tried, but could not be fully constructed:

    id[Color.Red](Color.Red.apply(1))(/* missing */summon[Id[Color.Red]])    failed with

        no implicit argument of type Id[Color.Red] was found for parameter ev of method id
```

## Expectation
The compiler finds a given for `Id[Color]` and the code above compiles.

**Comment by odersky** [comment]
We discussed this at length before. `Color.Red(1)` is of type `Color.Red`. Since `Id` is invariant, no given is found.
By contrast `x` has the widened type `Color`, that's why it work. After epic and extensive discussions we settled on this scheme. I don't think we will change this now.

**Comment by gabro** [comment]
Thanks for the reply @odersky. Could you elaborate on why the widening happens when assigning and it does happen when using the same expression inline
