### ISSUE TITLE
Odd output from Scaladoc

### ISSUE THREAD

**Issue by jphmrst** [lampepfl/dotty#12714]
## Compiler version

3.0.0

## Minimized code

```Scala
package blah // Remove the package decl, message goes away
trait AA[E]
object AA {
  given givenSeqToItem[E]: Conversion[E, AA[E]] with
    def apply(s: E): AA[E] = ???
}
```

## Output

```scala
Variable implicitConversion undefined in comment for class Conversion in class Conversion
```

Note that this message is not prefixed by `[warn]`, `[info]`, etc., and is not included in the warning count.

Possibly this is debugging output leaking out?

## Expectation

Either this line should not appear, or should be a more actionable message with file/line number and counted as a warning.  And it seems like the `package` shouldn't matter.

**Comment by som-snytt** [comment]
Silenced by https://github.com/lampepfl/dotty/pull/12230 on 3.0.1-RC1

**Comment by abgruszecki** [comment]
Yep, this is already fixed. Thanks for raising the issue, @jphmrst!
