### ISSUE TITLE
Extension method not fully constructed error where type mismatch should be

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#12725]
If an extension method is successful, but the result does not matched the required type we get "value XXXX is not a member" and "extension method not fully constructed" instead of a type-mismatch error.

## Compiler version

v3.0.1-RC1

## Minimized code

```Scala
  class Foo:
    type Out = 5
  class Baz[T]

  extension (foo: Foo) def getBaz: Baz[foo.Out] = ???

  val foo = Foo
  val err: Baz[4] = foo.getBaz
```

## Output

```scala
value getBaz is not a member of object Foo.
An extension method was tried, but could not be fully constructed:

    getBaz(foo)    failed with

        Found:    Baz[(5 : Int)]
        Required: Baz[(4 : Int)]
```

## Expectation
IMO, the current error is confusing. Indeed, we get all the information that is required to understand what is going on, but the error should be a type-mismatch, since the extension method itself has no real issue of being invoked.

**Comment by som-snytt** [comment]
It's a type mismatch after adding
```
object Foo:
  extension (foo: Foo) def getBaz: Baz[foo.Out] = ???
```
so it's also confusing to see a different message from implicit scope, and maybe that there is one message and not two.

**Comment by odersky** [comment]
> value getBaz is not a member of object Foo.

Correct.

> An extension method was tried, but could not be fully constructed:

    getBaz(foo)    failed with

        Found:    Baz[(5 : Int)]
        Required: Baz[(4 : Int)]

Also correct. What else do you want? It can insert an extension method only if the result type matches, but in this case it did not.

**Comment by soronpo** [comment]
> > value getBaz is not a member of object Foo.
> 
> Correct.

@odersky 

I would expect the same error message if the we had separated the expression:
```scala
  val foo = new Foo
  val baz = foo.getBaz
  val err: Baz[4] = baz
```

```scala
Found:    (baz : Baz[(5 : Int)])
Required: Baz[(4 : Int)]
```

Why should the extension method not work?

**Comment by som-snytt** [comment]
@soronpo It hasn't tried implicit scope yet, so the extension in lexical scope has to fail, for example:
```
class Foo:
  type Out = 5
object Foo:
  extension (foo: Foo) def getBaz: Baz[4] = ???

class Baz[A]

extension (foo: Foo) def getBaz: Baz[foo.Out] = ???

val foo = Foo()
val err: Baz[4] = foo.getBaz
```
It shows the error you expect if `Foo.getBaz` doesn't work out:
```
class Foo:
  type Out = 5
object Foo:
  extension (foo: Foo) def getBaz: Baz[foo.Out] = ???

class Baz[T]

val foo = Foo()
val err: Baz[4] = foo.getBaz
```
In my previous comment, I meant that it would be nice to have `-Ylog-implicits` or similar to log the extension which failed, even if a successful extension is found. It seems to me that folks might still find it confusing to know "where do I put my extension" and "how do I bring it into scope" and "why didn't it pick up my extension"? The usual questions about implicits.

TIL with targetName to distinguish them, there could be various competing extensions.
```
extension (foo: Foo)
  def getBaz: Baz[foo.Out] = ???
  @annotation.targetName("goodie") def getBaz: Baz[4] = ???
```
