### ISSUE TITLE
Spurious "illegal trait inheritance"

### ISSUE THREAD

**Issue by oyvindberg** [lampepfl/dotty#12722]
## Compiler version
3.0.0

## Minimized code

The two first types are a minimization of scalajs-library, making this code independent of scalajs.
The last five form a somewhat interesting inheritance chain.

```Scala
trait JsAny extends AnyRef
class JsObject extends JsAny

trait HTMLAttributes[T] extends JsObject
trait Component[P] extends JsObject
trait IPersonaSharedProps extends HTMLAttributes[PersonaCoinBase]
trait PersonaCoinBase extends Component[IPersonaCoinProps]
trait IPersonaCoinProps extends IPersonaSharedProps
```

## Output

```

-- Error: tester.scala:8:32 
8 |trait IPersonaCoinProps extends IPersonaSharedProps
  |                                ^^^^^^^^^^^^^^^^^^^
  |illegal trait inheritance: superclass Object does not derive from trait IPersonaSharedProps's superclass JsObject
1 error found

```

## Expectation
Compiles, it did in Scala 2.

Most changes to the code above removes the compile error.

**Comment by oyvindberg** [comment]
> Most changes to the code above removes the compile error.

I should add that I added this phrase to highlight that it takes a fairly specific circumstance to trigger this, not that it's insignificant. It was a huge pain to discover, try to understand and minimize. I've also yet to discover a workaround for it.

With this bug showing up for this concrete case, I suppose it's likely that other trait composition constellations are affected as well

**Comment by som-snytt** [comment]
With shorter names for visual clarity
```
//trait JsAny extends AnyRef
class JsObject //extends JsAny

trait HTMLAttributes[A] extends JsObject
trait Component[B] extends JsObject

trait T extends HTMLAttributes[U]
trait U extends Component[V]
trait V extends T
```

**Comment by smarter** [comment]
As a workaround you can make the class parent JsObject of the trait explicit
```scala
trait IPersonaCoinProps extends JsObject with IPersonaSharedProps
```

**Comment by oyvindberg** [comment]
thanks a lot @smarter I'll try it

**Comment by odersky** [comment]
The method to investigate further here is `typedParentTypes` and in particular `normalizeFirstParent`.

**Comment by odersky** [comment]
It's a compilation order problem.The parents of a class were not evaluated yet at the point where we need the info. This will be quite hard to fix without some additional lazy datastructures
