### ISSUE TITLE
The JVM doesn't know the CA of the ScalaMeter server.

### ISSUE THREAD

**Issue by ThibaultUrien** [lampepfl/dotty#1272]
Wile working on a semester project related with the ScalaMeter, I had the problem that it where impossible to connect to the ScalaMeter server in java. On my Windows 10 the JVM seem not able to find a path to the CA that certify the ScalaMeter server, and thus always abort the connection.
Manually adding to the JVM the cert file of the CA StartCom Class 1 Primary Intermediate Server CA have solved the problem for me. 
I don't have investigated this problem any further.
Sébastien Doeraene recommended me to create an issue here about this.

How to reproduce
`
scala.io.Source.fromURL("https://d-d.me/tnc/dotty/report/js/ScalaMeter/data.js").mkString
`

**Comment by DarkDimius** [comment]
Oracle does not want to add the CA to their cert-store. 
More details can be found here: http://iam-jla.blogspot.ch/2015/04/startssl-in-java.html

For now, I've disabled enforcing ssl on http://d-d.me/tnc/dotty/. 
Note that browsers will still discover and use ssl-powered website as response header conation both [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security) and [HPKP](https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning).

**Comment by ThibaultUrien** [comment]
@DarkDimius I'm not sure if anything have changed since you made the fix, but the SSLHandshakeException have restarted to occur when attempting to connect to  http://d-d.me/tnc/dotty/ from java. And this, whicher I try with http://, https:// or nothing at the start.

**Comment by DarkDimius** [comment]
@ThibaultUrien that is very strange. If you connect to http version, SSL should not participate at all:
```
$ curl -v http://d-d.me/tnc/dotty/report/
*   Trying 46.101.68.178...
* Connected to d-d.me (46.101.68.178) port 80 (#0)
> GET /tnc/dotty/report/ HTTP/1.1
> Host: d-d.me
> User-Agent: curl/7.49.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 07 Jun 2016 18:45:33 GMT
< Content-Type: text/html
< Content-Length: 3590
< Connection: keep-alive
< Last-Modified: Sat, 04 Jun 2016 01:32:38 GMT
< Accept-Ranges: bytes
<
<!DOCTYPE html>
...
```

**Comment by ThibaultUrien** [comment]
My bad, I released that when failing to connect in https, instead of switching to http, my code was trying again with exactly the same url.
 So indeed you can reach http://d-d.me/tnc/dotty/report/ from java.

**Comment by DarkDimius** [comment]
Fixed.
