### ISSUE TITLE
Parsing difference between Scala 2 & 3

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#12738]
## Compiler version

3.0.0

## Minimized code

```Scala
var x = null: Int => Int
```

## Output

```
1 |var x = null: Int => Int
  |                  ^
  |                  parentheses are required around the parameter of a lambda
  |                  This construct can be rewritten automatically under -rewrite -source 3.0-migration.
1 |var x = null: Int => Int
  |        ^^^^^^^^^
  |        not a legal formal parameter
```

## Expectation

Compiles fine with Scala 2.13.
Scala 3 needs parens: `var x = null: (Int => Int)`

**Comment by odersky** [comment]
I think it's cleaner to leave it as it is. `a: A => B` means `(a: (A => B))` only when it appears in parentheses. There are simply too many situations where a following `=>` is legal and we want to group as `(a: A) => B` instead: closures, case definitions, self types.

**Comment by som-snytt** [comment]
Related confusion at https://github.com/lampepfl/dotty/issues/12522#issuecomment-844129295

Obviously, the naive eye asks how are they different, `A X B`.

Worth documenting that the first advice is misleading: you might try `-rewrite` or `(Int) => String` to no avail.

You have to look at the second error to understand. Under `-source 3.0-migration`, it's a warning followed by an error.

```
scala> Map.empty[Int, String]: Int Map String
val res0: Map[Int, String] = Map()

scala> Map.empty[Int, String]: Int => String
1 |Map.empty[Int, String]: Int => String
  |                            ^
  |                            parentheses are required around the parameter of a lambda
  |                            This construct can be rewritten automatically under -rewrite -source 3.0-migration.
1 |Map.empty[Int, String]: Int => String
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |not a legal formal parameter
```
