### ISSUE TITLE
"Edit on GitHub" button in the docs is broken

### ISSUE THREAD

**Issue by martijnhoekstra** [lampepfl/dotty#12741]
## Compiler version

3.0.0

## Minimized code

None

## Output

None

## Expectation

When you press the "edit this page on github" button on the documentation, e.g. on https://dotty.epfl.ch/docs/reference/changed-features/main-functions.html, you can edit the page. It seems to try to edit the tagged version, which is impossible.

**Comment by bishabosha** [comment]
I am closing this due to migrating the docs away to https://github.com/scala/docs.scala-lang
