### ISSUE TITLE
Overridden trait method cannot be called from java

### ISSUE THREAD

**Issue by felixbr** [lampepfl/dotty#12753]
## Compiler version

3.0.0 (it compiles fine with 2.13.6 and earlier)

## Minimized code

The following is minimized code from my Scala3 migration attempt of [`twitter/util`](https://github.com/twitter/util/pull/290).

```Scala
trait TimeLike[This <: TimeLike[This]]

trait TimeLikeOps[This <: TimeLike[This]] {
  def fromMilliseconds(milliseconds: Long): This

  def fromSeconds(seconds: Long): This = fromMilliseconds(seconds * 1000L)
}

sealed class Duration(val milliseconds: Long) extends TimeLike[Duration]
object Duration extends TimeLikeOps[Duration] {
  def fromMilliseconds(milliseconds: Long): Duration = new Duration(milliseconds)
  
  // note that this override was already a workaround for calling Scala2 from Java. For pure Scala it's not needed.
  override def fromSeconds(seconds: Long): Duration = super.fromSeconds(seconds)
}
```
Then trying to call the overridden method **from Java** causes a compile-error:
```java
Duration.fromSeconds(1);
```

If you want to run the code, here's a runnable branch/commit: https://github.com/felixbr/scala3-example-project/commit/e23ffcf5a618b69f5513e62bd4aa1774dccdea3c

## Output

```scala
reference to fromSeconds is ambiguous 
both method fromSeconds(long) in twitter.Duration and method fromSeconds(long) in twitter.Duration match
Duration.fromSeconds
```

## Expectation

It should compile as it did in 2.13.6 and earlier.

Cheers
~ Felix

**Comment by lrytz** [comment]
Scala 3 generates two static forwarders.
```
  public static fromSeconds(J)LDuration;

  public static fromSeconds(J)LTimeLike;
```

Scala 2 only the first.

The override is necessary because of https://github.com/scala/bug/issues/11305, I assume.

https://github.com/lampepfl/dotty/blob/fdbb94f29b05fb712c04b981f462ae65b447fc39/compiler/src/dotty/tools/backend/jvm/BCodeHelpers.scala#L925-L926

**Comment by lrytz** [comment]
I'll take a look (can't assign myself, don't have permission in this repo)
