### ISSUE TITLE
Patternmatcher fails to bind `_: _*` correctly

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1276]
When transforming:

```scala
val List(_: _*) = List(1)
```

`_` is evaluated to be an `Int` instead of a `Seq[Int]`.

**Comment by DarkDimius** [comment]
`val List(x: _*) = List(1)`
is handled correctly, but 
`val List(_: _*) = List(1)`
isn't

**Comment by DarkDimius** [comment]
As far as I see, the issue stems from the fact that desugaring performed by typer is ambiguous:

```scala
object Test {
  def main(args: Array[String]): Unit = {
   val List(_: _*) = (List(1) : Any)
   /*  case List.unapplySeq[Any'](_: scala.collection.Seq[Any]):
            scala.collection.immutable.List[Any']          => () */

   val List(_: Seq[Int]) = (List(List()) : Any)
   /* case List.unapplySeq[Any'](_: Seq[Int]):
            scala.collection.immutable.List[Any']  => () */
  }
}
```

both matches here are desugared into the very same tree.

@odersky has found the very same issue from a different side: `TreeInfo.isWildcardStarArg` assumes that the `_: _*` case should be matching: 
```scala 
case Typed(_, tpt: TypeTree) => tpt.hasType && tpt.tpe.isRepeatedParam
```

but it does not, as tpt will not be `Int*` but will be `Seq[Int]` instead.
