### ISSUE TITLE
`val`s in `final` classes don't get the same optimisation that `final val`s get

### ISSUE THREAD

**Issue by dwijnand** [lampepfl/dotty#12776]
## Compiler version

3.0.0

## Minimized code

```scala
class Creature {
  val range: Int = 10
  println(range)
}

class Ant1 extends Creature {
  override final val range: Int = 2
}

final class Ant2 extends Creature {
  override val range: Int = 2
}

object Test extends App {
  new Ant1
  new Ant2
}
```

## Output

```
2
0
```

## Expectation

```
2
2
```

(Mentioned on the side in #12570.)

**Comment by dwijnand** [comment]
Why not?  Is there a downside to the optimisation?

**Comment by odersky** [comment]
@dwijnand It changes semantics (even though only in weird cases), so it's technically not an optimization.

**Comment by dwijnand** [comment]
Sure, but if we're fine with that for final vals why not for the vals of final classes?  It's consistent that way.

**Comment by dwijnand** [comment]
Hmm consistency vs change weird case semantics...

**Comment by nicolasstucki** [comment]
Does the behavior of the uninitialized field access have strict semantics, or is it an undefined behavior? 

Is the behavior of uninitialized fields sound? Consider `val x: 2 = 2`, if accessed before initialization it could yield `0` which is unsound because `0 <:< 2` does not hold. Otherwise, 0 would need to be a bottom type of all numerical constants which would break all type-level numeric computations.

**Comment by sjrd** [comment]
It is undefined behavior. It has always been. The `-Xcheck-init` was a way to force these issues to surface as immediate exceptions, much like Scala.js' fastOpt mode can surface other kind of undefined behavior as exceptions, to aid debugging.

**Comment by nicolasstucki** [comment]
Good. Then it is ok to optimize them and therefore have fewer cases with uninitialized accesses that return unexpected values

**Comment by odersky** [comment]
It is undefined behavior, but has been the same since the start of Scala. We should not mess with it now.
