### ISSUE TITLE
No "Run this Worksheet" in worksheet mode of VSCode

### ISSUE THREAD

**Issue by fixablecar** [lampepfl/dotty#12779]
## Environment

```
$ java --version
openjdk 11.0.11 2021-04-20

sbt:playground> print scalaVersion
3.0.0
```

VSCode Extensions:
```
Dotty Language Server: 0.1.16
Scala(Metals): 1.10.6
Scala Syntax (official): 0.5.3
```

## Observation

1. There is no `Run this worksheet` at the top of worksheet, but `Copy Worksheet Output`.
<img width="532" alt="ps 2021-06-10 11 47 12" src="https://user-images.githubusercontent.com/5638823/121465272-12352300-c9e8-11eb-87f0-876d53e44400.png">

2. The `Run Worksheet On Save` option works fine, Type hint on hovering works fine as well.

3. When I choose `Scala: Run Worksheet` in the command, `Command 'Scala: Run worksheet' resulted in an error (command 'dotty.worksheet.run' not found)` is reported.

## Expectation
[Worksheet mode with Dotty IDE](https://dotty.epfl.ch/docs/usage/worksheet-mode.html)

**Comment by bishabosha** [comment]
This output is the expected output of Metals which activates because the file has the suffix `.worksheet.sc`

**Comment by fixablecar** [comment]
> This output is the expected output of Metals which activates because the file has the suffix `.worksheet.sc`, Metals worksheets run on each save

So the only way to evaluate the worksheet is to save it?

**Comment by bishabosha** [comment]
> So the only way to evaluate the worksheet is to save it?

Yes I believe so, you may ask about it in https://gitter.im/scalameta/metals and if there is no other way then you can open a feature request at https://github.com/scalameta/metals-feature-requests

**Comment by fixablecar** [comment]
> > So the only way to evaluate the worksheet is to save it?
> 
> Yes I believe so, you can ask about it in https://gitter.im/scalameta/metals and if there is no other way then you can open a feature request at https://github.com/scalameta/metals-feature-requests

Thanks for the response. I am closing this.
