### ISSUE TITLE
Automatic expansion of Tuple1

### ISSUE THREAD

**Issue by Adam-Vandervorst** [lampepfl/dotty#12797]
## Compiler version
3.0.0
## Minimized code

```Scala
def g(a: Tuple1[Int]) = a._1*2

@main def main_f = 
    println(g(1))
```

## Output

```scala
Found:    (1 : Int)
Required: Tuple1[Int]
    println(g(1))
```

## Expectation
Work the same as 
```scala
def f(a: Tuple2[Int, Int]) = a._1 + a._2

@main def main_f = 
    println(f(1, 2))
```
or work with `g((1))`, `g((1,))`, or `g(1,)`.

**Comment by smarter** [comment]
Scala 2 has the same behavior so this isn't a regression but more like a feature request. And the direction we're trying to go in involves less auto-tupling, not more of it, cf https://github.com/lampepfl/dotty/pull/4311 which is closed but the discussion isn't settled yet.

**Comment by Adam-Vandervorst** [comment]
In my opinion, this inconsistent with
```scala
def op[T <: NonEmptyTuple](name: String)(ps: Map[T, AOp]) = AOp[T](name, ps)
```
where you can define your ops and do `biop(x, y)` but not `uop(x)`.
