### ISSUE TITLE
Comparison can't be inlined when using inline values but can with litteral

### ISSUE THREAD

**Issue by Iltotore** [lampepfl/dotty#12794]
## Compiler version
3.0.0

## Minimized code

First sample:
```scala
@main def test = {
  compiletime.preAssert(2 > 1)
}
```

Second sample:
```scala
inline def foo: Int = 2

@main def test = {
  compiletime.preAssert(foo > 1)
}
```

compiletime.scala
```scala
import scala.quoted._

object compileTime {

  inline def preAssert(inline value: Boolean): Boolean = ${preAssertImpl('value)}

  private def preAssertImpl(expr: Expr[Boolean])(using quotes: Quotes): Expr[Boolean] = {

    expr.value match {

      case Some(false) => quotes.reflect.report.error(s"Compile-time assertion failed", expr)

      case None => quotes.reflect.report.warning(s"Unable to evaluate assertion at compile time", expr)

      case _ =>
    }

    expr
  }
}
```

## Output

First sample: The code compiles and is inlined to `true`

Second sample: The code is __partially_ inlined (`2 > 1` in the bytecode) and the macro can't retrieve the value at compiletime
```
Unable to evaluate assertion at compile time
```

## Expectation
I expect the compiler to fully inline the second example in order to get the same result as the first one:
```scala
foo > 1
//to
2 > 1
//to
true
```

**Comment by odersky** [comment]
It would probably have to be 
```scala
transparent inline def foo: Int = 2
```
Can you try with that variant?

**Comment by Iltotore** [comment]
It works. Thank you.

I don't see any mention of this behaviour in the [Transparent Inline method paragraph](http://dotty.epfl.ch/docs/reference/metaprogramming/inline.html#transparent-inline-methods). If it's not mentionned, maybe this should be added ?

**Comment by som-snytt** [comment]
Maybe this comment should be a faq: https://github.com/lampepfl/dotty/issues/12700#issuecomment-854271776
