### ISSUE TITLE
TermMethods has `etaExpand` instead of `betaExpand`

### ISSUE THREAD

**Issue by Snowflake8** [lampepfl/dotty#12798]
## Compiler version
Scala 3.0.0

## Problem
I found this typo going through the documentation. This is inconsistent with the  `betaReduce` function

Found this at 
http://dotty.epfl.ch/api/scala/quoted/Quotes$reflectModule$TermMethods.html#etaExpand-fffffab9
and tracked it back to 
https://github.com/lampepfl/dotty/blob/3.0.0/library/src/scala/quoted/Quotes.scala#L663

## Expectation
I would expect this to be a quick refactor/fix, but I'm not sure how deep the oversight goes.

**Comment by odersky** [comment]
It's actually called etaExpand.  No relationship to betaReduce.

**Comment by Snowflake8** [comment]
My bad
