### ISSUE TITLE
Incorrect union type exhaustivity warning (Nested pattern)

### ISSUE THREAD

**Issue by Swoorup** [lampepfl/dotty#12808]
## Compiler version

`3.0.1-RC1`

## Minimized code

```Scala
import scala.reflect.Typeable

case class Err1()
case class Err2()

def handleError[A: Typeable, B: Typeable](x: Either[A | B, Nothing]): Unit =
  x match // false alarm warning: It would fail on pattern case: Left(_)
    case Left(e: A)  => println("A")
    case Left(_: B) => println("B")
    case Right(_)    => println("Nothing")

handleError[Err1, Err2](Left(Err1())) // prints A
handleError[Err1, Err2](Left(Err2())) // prints B
```

## Output

```shell
match may not be exhaustive.

It would fail on pattern case: Left(_)
```

## Expectation

As all cases are handled no warnings need to be generated. 

Unrelated question, but shouldn't removing `Right` be also fine? since it is of `Nothing` type? If you remove the last, the compiler gives out warning for `Right` pattern as well. (Looks like scala 2 has the same issue for this)

**Comment by Swoorup** [comment]
@liufengyun this seems another case related to https://github.com/lampepfl/dotty/issues/12279 ?

**Comment by liufengyun** [comment]
> @liufengyun this seems another case related to #12279 ?

@Swoorup Thanks for reporting. This seems to be fixed in master

**Comment by liufengyun** [comment]
> Unrelated question, but shouldn't removing `Right` be also fine? since it is of `Nothing` type? If you remove the last, the compiler gives out warning for `Right` pattern as well. (Looks like scala 2 has the same issue for this)

Yes, conceptually it's possible to remove a pattern if it only matches `Nothing`. Currently, we didn't optimize for that, as it seems there is no need for it in practice.

**Comment by Swoorup** [comment]
> > Unrelated question, but shouldn't removing `Right` be also fine? since it is of `Nothing` type? If you remove the last, the compiler gives out warning for `Right` pattern as well. (Looks like scala 2 has the same issue for this)
> 
> Yes, conceptually it's possible to remove a pattern if it only matches `Nothing`. Currently, we didn't optimize for that, as it seems there is no need for it in practice.

Yep would be nice just for the sake of completeness and demo'ing scala 😛

**Comment by liufengyun** [comment]
> > > Unrelated question, but shouldn't removing `Right` be also fine? since it is of `Nothing` type? If you remove the last, the compiler gives out warning for `Right` pattern as well. (Looks like scala 2 has the same issue for this)
> > 
> > 
> > Yes, conceptually it's possible to remove a pattern if it only matches `Nothing`. Currently, we didn't optimize for that, as it seems there is no need for it in practice.
> 
> Yep would be nice just for the sake of completeness and demo'ing scala

A PR is welcome:  you can tweak the following two methods following the example for `Unit` and `Boolean`:

https://github.com/lampepfl/dotty/blob/229ec59c3b803c7004c988905a06c07b4f5e67d1/compiler/src/dotty/tools/dotc/transform/patmat/Space.scala#L594-L670
