### ISSUE TITLE
Unions of Singletons unreachable literals not being checked in pattern match.

### ISSUE THREAD

**Issue by Swoorup** [lampepfl/dotty#12805]
The pattern match on the lhs side doesn't exhaustively check if the pattern is of valid type for singletons of union. 

In this example both `240` and `4H` are not a valid subtype of both `TimeframeN` and `Timeframe` respectively, but compiler appears to compile without reporting type mismatch errors. It appears as if union type is widen'ed prematurely.

## Compiler version

`3.0.1-RC1`

## Minimized code

```Scala
import scala.language.implicitConversions

type Timeframe = "1m" | "2m" | "1H"
type TimeframeN = 1 | 2 | 60

def manualConvertToN(tf: Timeframe): TimeframeN = tf match
  case "1m" => 1
  case "2m" => 2
  case "1H" => 60
  case "4H" => ??? // incorrect but compiles

given Conversion[Timeframe, TimeframeN] = 
  case "1m" => 1
  case "2m" => 2
  case "1H" => 60
  case "4H" => ??? // incorrect but compiles

given Conversion[TimeframeN, Timeframe] = 
  case 1 => "1m"
  case 2 => "2m"
  case 60 => "1H"
  case 240 => ??? // incorrect but compiles
```

## Output

No errors on compilation

## Expectation

Type mismatch errors. Hypothetical sample:

```shell
[error] -- [E007] Type Mismatch Error: /Users/swoorup.joshi/playground/test/src/main/scala/Main.scala:18:15
[error] 18 |  case "4H" => ???
[error]    |        ^^^
[error]    |        Found:    ("4H" : String)
[error]    |        Required: Timeframe

[error] -- [E007] Type Mismatch Error: /Users/swoorup.joshi/playground/test/src/main/scala/Main.scala:24:15
[error] 24 |  case "4H" => ???
[error]    |        ^^^
[error]    |        Found:    ("4H" : String)
[error]    |        Required: Timeframe

[error] -- [E007] Type Mismatch Error: /Users/swoorup.joshi/playground/test/src/main/scala/Main.scala:30:15
[error] 30 |  case 240 => ???
[error]    |       ^^^
[error]    |       Found:    (240 : Int)
[error]    |       Required: TimeframeN
```

Note that this doesn't happen if the returning subtype is invalid. In such cases, compiler reports a type mismatch error correctly.

**Comment by sinanspd** [comment]
Maybe I have missed this feature and this is actually expected to work but can the compiler expected to interpret values as types here? Correct me if I am wrong but this seems like a use case for `Enum` as you aren't actually restricting the subtypes but the set of values an instance of a type can have. 

The following for example works 

```
case class OneM()
case class TwoM()
case class FourM()
type Timeframe = OneM | TwoM

def manual(tf: Timeframe): Int = tf match                                                                                                              
     case _ @ OneM() => 1
     case _ @ TwoM() => 2
     case _ @ FourM() => 4
```

```
4 |case _ @ FourM() => 4
  |         ^
  |this case is unreachable since type Timeframe and class FourM are unrelated
```

but it seems like you are expecting the compiler to generate a type from the concrete values and union them. 


In my opinion if there is a line that shouldn't compile here, it's

```
type Timeframe = "1m" | "2m" | "1H"
type TimeframeN = 1 | 2 | 60
```

**Comment by romanowski** [comment]
It seems that exchusivity checks does not pick up a case where additional signletons are provided.

```
scala> def foo(a: 1 | 2) = a match       // Compiles fine                                                                                                               
     |   case 1 => true
     |   case 2 => false
     |   case 4 => ???                          
     | 
def foo(a: 1 | 2): Boolean

scala> def bar(a: 1 | 2) = a match                                                                                                                       
     |   case 1 => true
     |   case 2 => false
     |   case _ => ???
     | 
4 |  case _ => ???
  |       ^
  |       Unreachable case

scala> def baz(a: 1 | 2) = a match                                                                                                                       
     |   case 1 => true
     |   case 2 => false
     |   case a if a < 0 => ???
     | 
4 |  case a if a < 0 => ???
  |       ^
  |       Unreachable case

**Comment by SethTisue** [comment]
you don't even need to bring a union into it:

```
scala> def foo(a: 1) = a match { case 1 => 1; case 2 => 2 }
def foo(a: 1): Int
                                                                                                                        
scala> def foo(a: 1) = a match { case 1 => 1; case _ => 2 }
def foo(a: 1): Int
```

here _neither_ warns, but _both_ should warn

**Comment by SethTisue** [comment]
in `Space.scala`, 

```scala
        // `covered == Empty` may happen for primitive types with auto-conversion
        // see tests/patmat/reader.scala  tests/patmat/byte.scala
        if (covered == Empty && !isNullLit(pat)) covered = curr
```

commenting this line out causes at least one of the tests to progress, so this may be the key piece of code. it was added by Fengyun in #4253

**Comment by dwijnand** [comment]
Dead code, such as unreachable cases or even just unused imports, can be misleading and so are worth linting.  But by themselves they aren't hazardous, and stopping compilation might prove very annoying.

**Comment by Swoorup** [comment]
I think warnings dead code and unused imports are fine and think it forms validation compilation, but for unreachable cases, invalid patterns it seems odd to have it as a warning, at least by default. 

Same with match types. 

```scala
type M[X <: String] = X match 
  case "SA" => Int
  case 12 => String
```

If some invalid construct compiles, most likely someone will use it in their codebase.

**Comment by dwijnand** [comment]
When configurable warnings gets merged (soon hopefully) then you should be able to promote a reachability warning into a reachability error.

Match types are different though, and I'm not too sure yet how much more worrisome unreachable cases are there.  Same with in-exhaustive match types... 🤔

**Comment by SethTisue** [comment]
> But in Scala 3, we don't have weak conformance anymore. So there needs to be some other justification for considering such a match to be reachable. The justification is provided by docs.scala-lang.org/scala3/reference/dropped-features/weak-conformance-spec.html 

Note that that documentation doesn't actually directly cover this. It applies to numeric expression, not numeric patterns. We're extending it to numeric patterns _in the context of reachability-and-exhaustiveness analysis only_. Ultimately the justification for this isn't the doc I cited, the justification is that numeric types are spec'ed as comparing equal at runtime.

**Comment by SethTisue** [comment]
Dale and I attempted a fix on the draft PR https://github.com/lampepfl/dotty/pull/13290, but our efforts may have stalled; see our recent remarks there.
