### ISSUE TITLE
ScalaDoc : type parameter in extension method is wrong

### ISSUE THREAD

**Issue by PaulCoral** [lampepfl/dotty#12813]
## Compiler version

sbt 1.5.3 / scalaVersion 3.0.0 and 3.0.1-RC1

## Minimized example

Start a new project `sbt new scala/scala3.g8`

```Scala
/* src/main/scala/Main.scala */
@main def hello: Unit = 
  println(foo)

val foo: (Int,String) = 1.toTuple2("string")

extension [A](thiz:A)
  def toTuple2[B](that:B):(A,B) = thiz -> that /* <- HERE */

```
then run `sbt doc`, when finished open `target/scala-3*/api/index.html` in a browser and look for package `<empty>`.

## Output

![image](https://user-images.githubusercontent.com/39838649/121810560-b2e24780-cc61-11eb-8c49-02bd9475413f.png)

## Expectation

Type parameter `B` is not present. Expecting the type paremeter of the method `toTuple2` function to be `[B]`

**Comment by nicolasstucki** [comment]
In tasty, the extension
```scala
extension [A](thiz:A)
  def toTuple2[B](that:B):(A,B) = thiz -> that /* <- HERE */
```
Is represented as

```scala
def toTuple2[A](thiz:A)[B](that:B):(A,B) = thiz -> that /* <- HERE */
```
To get the type parameters we need to drop the parameters until the thiz parameter and then possibly drop contextual/implicit parameters, then it might be followed by the desired type parameters.

**Comment by julienrf** [comment]
Is anyone from the doctool team interested in taking this one?

**Comment by romanowski** [comment]
Yes. me :)
