### ISSUE TITLE
Coursier `scala3-repl` launcher cannot be used as a runner

### ISSUE THREAD

**Issue by ShapelessCat** [lampepfl/dotty#12811]
## Compiler version
**3.0.0**

## Minimized example
Follow the _official document_ **Scala 3 Book**, run the simple "Hello, world" example through scala3-repl.
1. In the file _Hello.scala_, write
    ```scala
    @main def hello = println("Hello, world!")
    ```
2. `scala3-compiler Hello.scala`
3. `scala3-repl hello`

The scala3-repl was installed through Coursier, as suggested by the official webpage [Download Scala 3](https://www.scala-lang.org/download/scala3.html)

## Output
NO output.
I see the scala3-repl get into the interactive mode directly without any output.

## Expectation
I expect to see the `"Hello, wrold!"` output, the same as in Scala 2.

**Comment by romanowski** [comment]
The core of the problem is that coursier installs repl and compiler as java applications and do not include bash scripts that contains logic that switch repl to execute compiled scala code rather then start repl.

**Comment by bjornregnell** [comment]
See also https://github.com/lampepfl/dotty/issues/12502  and    https://github.com/scala/scala-lang/issues/1248 

This is a showstopper for me to use cs in my teaching. And there is no .msi for Scala 3 so I'm more or less stuck (manually unpackaging a zip and going into environment variables to fiddle with path etc in Windows is not very attractive beginner programmer user experience...)

**Comment by smarter** [comment]
Please open coursier issues at github.com/coursier/coursier, there's nothing we can do about it in this repository.

**Comment by bjornregnell** [comment]
Thanks @smarter Fixed now here https://github.com/coursier/coursier/issues/2058

I still think the official home page is a problem. Where to file bugs on the scala-lang.org page?

**Comment by smarter** [comment]
That's https://github.com/scala/scala-lang/

**Comment by bjornregnell** [comment]
Aha. Then its already there: https://github.com/scala/scala-lang/issues/1248
