### ISSUE TITLE
Broken Link in dotty blog

### ISSUE THREAD

**Issue by antognini** [lampepfl/dotty#12817]
Could you please fix the latest blog entry (3.0.1-RC1), which is broken in http://dotty.epfl.ch/blog/index.html?
It points to
http://dotty.epfl.ch/blog/_posts/2021-06-07-scala3.0.1-rc1-release.md
instead of
http://dotty.epfl.ch/blog/2021/06/07/scala3.0.1-rc1-release.html

**Comment by griggt** [comment]
Related: https://github.com/lampepfl/dotty/issues/12762

**Comment by antognini** [comment]
Thanks, this is a duplicate. Closing the issue.
