### ISSUE TITLE
Overload that differs only in parameter type is mistaken as override, crashes with a ClassCastException at runtime

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#12828]
## Compiler version

3.0.1-RC1

## Minimized code

```Scala
trait Foo[A]:
  def foo(x: A): Unit

trait Bar[A] extends Foo[A]:
  def foo(x: A & String): Unit = println(x.toUpperCase)

object Baz extends Bar[Int]

@main def run() = Baz.foo(42)
```

## Output

The code compiles, but fails at run-time:

> java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
>	at Baz$.foo(main.scala:7)

## Expectation

The code should not compile. It should produce the following error:

> object creation impossible, since def foo(x: A): Unit in trait Foo is not defined 
> (Note that
>  parameter A in def foo(x: A): Unit in trait Foo does not match
>  parameter A & String in def foo(x: A & String): Unit in trait Bar
>  type A & String is a subtype of trait A, but method parameter types must match exactly.)

Note: adding the `override` keyword raises a compile-time error:

~~~ scala
trait Foo[A]:
  def foo(x: A): Unit

trait Bar[A] extends Foo[A]:
  override def foo(x: A & String): Unit = println(x.toUpperCase)
//                    ^^^^^^^^^^
// method foo has a different signature than the overridden declaration
~~~

**Comment by smarter** [comment]
The override check is supposed to happen in https://github.com/lampepfl/dotty/blob/4ad0c8f2a73f12e58750bcd4570616cbf50a3011/compiler/src/dotty/tools/dotc/typer/RefChecks.scala#L499-L521
But even though the `opc.matches` method returns true on the symbols we'd like to compare, `ops.hasNext` returns false, so this seems to be an issue in how OverridingPairs.Cursor works and I have to admit that I don't fully understand that class (but I know we're missing some fixes from scala 2 there: https://github.com/lampepfl/dotty/issues/7551), do you think you could have a look @odersky ?
