### ISSUE TITLE
non determinism for `Ysafe-init` external method trace

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#12824]
there seems to be some non determinism in running the `Ysafe-init` tests in https://github.com/lampepfl/dotty/pull/12685. either method `name` or `ordinal` appears in the error message for the enum example, so the check file diff fails in test_windows_full https://github.com/lampepfl/dotty/actions/runs/937890644

_Originally posted by @bishabosha in https://github.com/lampepfl/dotty/issues/12823#issuecomment-861291086_

Here is the line in the error:

https://github.com/lampepfl/dotty/blob/076ab0a974fdc1039ca877736e8436bcecea0fd0/tests/init/neg/enum-desugared.check#L8

**Comment by odersky** [comment]
I believe it is this failure that causes the nightlies to fail

**Comment by liufengyun** [comment]
We can simply remove the test as a temporary fix. /cc @EnzeXing

**Comment by smarter** [comment]
Re-opening since the underlying issue isn't fixed.

**Comment by EnzeXing** [comment]
I see that the check-files are removed. Shall I remove the tests as well?

**Comment by smarter** [comment]
The test by itself will check that there actually is an error at the line ending with `// error`, so if that works consistently it's fine to leave it.

**Comment by EnzeXing** [comment]
Is the underlying issue still not resolved?

**Comment by bishabosha** [comment]
> Is the underlying issue still not resolved?

The underlying issue is that the error message changes if we are on windows or on linux, perhaps this is not solvable, but investigation is needed

**Comment by liufengyun** [comment]
> > Is the underlying issue still not resolved?
> 
> The underlying issue is that the error message changes if we are on windows or on linux, perhaps this is not solvable, but investigation is needed

It should be able to be fixed, let's discuss it today /cc: @EnzeXing  @olhotak today.

**Comment by liufengyun** [comment]
Fixed in #12989
