### ISSUE TITLE
Singleton types should not be inferred for final vars

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1285]
```scala
class Test {
  final var x = false
  x = true
}
```
```scala
error: type mismatch:
 found   : Boolean(true)
 required: Boolean(false)
  x = true
      ^
```

**Comment by sjrd** [comment]
So there is such a thing as a `final var` ... :anguished:

**Comment by DarkDimius** [comment]
what does `final var` mean in the first place?

**Comment by smarter** [comment]
Good question, I just found it in the wild in https://github.com/molecule-labs/molecule/search?utf8=%E2%9C%93&q=%22final+var%22 but didn't stop to think if it made any sense :). http://stackoverflow.com/questions/18222233/what-is-the-usage-of-a-final-var-in-scala says it's to prevent overriding.

**Comment by DarkDimius** [comment]
> says it's to prevent overriding.

Mutable variables can't be overridden even if they are not final.

```scala
scala> class A{var s = 3}; class B extends A{override var s = 4}
<console>:10: error: overriding variable s in class A of type Int;
 variable s cannot override a mutable variable
       class A{var s = 3}; class B extends A{ override var s = 4}
```

**Comment by smarter** [comment]
@adriaanm: any idea if the semantics of `final var` are different from the semantics of `var` ?

**Comment by adriaanm** [comment]
As @DarkDimius said, currently, final is implied for a var currently. I can't think of any difference implied by the presence of the modifier. I guess you could defend a design where you can override a var so you can introduce validation logic in the setter, but you couldn't change the type and the storage would still have to be in the super class, so, not sure...

**Comment by adriaanm** [comment]
The logic around widening inferred types is here: https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/typechecker/Namers.scala#L839
