### ISSUE TITLE
Unchecked type arg warning induces inexhaustive warning

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#12853]
## Compiler version

3

## Minimized code

```Scala
scala> def f[A](xs: List[A]) = xs match { case _: List[Int] => }
1 |def f[A](xs: List[A]) = xs match { case _: List[Int] => }
  |                        ^^
  |                        match may not be exhaustive.
  |
  |                        It would fail on pattern case: List(_, _*)
1 |def f[A](xs: List[A]) = xs match { case _: List[Int] => }
  |                                        ^^^^^^^^^^^^
  |                                        the type test for List[Int] cannot be checked at runtime
def f[A](xs: List[A]): Unit
```

## Output

The second warning is correct but induces the first warning.

From the suggested missing case, maybe it takes the pattern as `List[Nothing]` or `Nil`.

## Expectation

Only the second warning. The order of the messages increases likelihood of confusion.

**Comment by liufengyun** [comment]
> From the suggested missing case, maybe it takes the pattern as `List[Nothing]` or `Nil`.

This is correct, as `Nil <: List[Nothing] <: List[Int]`, therefore `_: List[Int]` matches `Nil` irregardless of type erasure.
