### ISSUE TITLE
Scaladoc wrongly interprets markdown inside code blocks

### ISSUE THREAD

**Issue by ShapelessCat** [lampepfl/dotty#12868]
The section "Types supporting derives clauses" of the document [Type Class Derivation](https://github.com/lampepfl/dotty/blob/master/docs/docs/reference/contextual/derivation.md) includes a code example
````
```scala
sealed trait Mirror:

  /** the type being mirrored */
  type MirroredType

  /** the type of the elements of the mirrored type */
  type MirroredElemTypes

  /** The mirrored *-type */
  type MirroredMonoType

  /** The name of the type */
  type MirroredLabel <: String

  /** The names of the elements of the type */
  type MirroredElemLabels <: Tuple
```
````

Currently its view in HTML is wrong: several lines are merged into one line.
I guess the reason is the `*-type`, the comment line that above the code `type MirroredMonoType`, which affects the HTML rendering.

Please check http://dotty.epfl.ch/docs/reference/contextual/derivation.html
I already checked its view in both Chrome and Firefox.

**Comment by ShapelessCat** [comment]
@pikinier20 
I think your #12887 fixed the bug I mentioned, but it also introduced a new bug.
You can check the same code example:

```scala
object Mirror:

  /** The Mirror for a product type */
  trait Product extends Mirror:

    /** Create a new instance of type `T` with elements * taken from product `p`. */ 
    def fromProduct(p: scala.Product): MirroredMonoType

  trait Sum extends Mirror:

    /** The ordinal number of the case class of `x`. * For enums, `ordinal(x) == x.ordinal` */ 
    def ordinal(x: MirroredMonoType): Int

end Mirror
```

The last two comments should be multiple line comments. You can see those `*`s, which should be at the beginning of new lines, now in the middle of those single line comments.

**Comment by pikinier20** [comment]
It seems like it's another unrelated bug inside our hljs rules. It will be hard to decide whether * is start of emphasis or newline (eg. if there would be two *'s). Hljs may be not sophisticated enough to be able to fix this, but I'm gonna think about this.

**Comment by TheElectronWill** [comment]
Is it really because of this rule? I don't get the multiline problem if I use [my test](https://github.com/TheElectronWill/dotty-hljs).
