### ISSUE TITLE
sealed class with companion object yields match exhaustivity warning

### ISSUE THREAD

**Issue by ansvonwa** [lampepfl/dotty#12877]
## Compiler version
`3.0.0`, `3.0.1-RC1`

## Minimized code
[Scastie](https://scastie.scala-lang.org/gDdeC8qrRY2rQ4igN2oNGg)

```Scala
sealed class A
object A extends A
```

## Output

```scala
match may not be exhaustive.

It would fail on pattern case: _: Main.A
```

## Expectation
No warning as in Scala 2 or with `sealed trait`, `trait` or `class` instead of `sealed class`.
(Or a better explanation of the problem, if there is one?)

**Comment by smarter** [comment]
This appear to be fixed in nightly builds (try `scalaVersion := "3.0.2-RC1-bin-20210617-af3703b-NIGHTLY"`)
