### ISSUE TITLE
stdlib-sourcelinks-test is failing some of the time on PRs opened against release-3.0.1 branch

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#12882]
See https://github.com/lampepfl/dotty/pull/12873 and https://github.com/lampepfl/dotty/pull/12845 which both failed with:
> Error:  Test dotty.tools.scaladoc.sourcelinks.RemoteLinksTest.runTest failed: Expected to find Predef at scala/scala@v2.13.6/src/library/scala/Predef.scala at line 96, took 3.607 sec

**Comment by BarkingBad** [comment]
I'll fix it tomorrow ASAP. 

However, problem with positions of/in Predef exists for a long time and we should investigate it deeper to find the root cause.

**Comment by odersky** [comment]
It's probably because Predef is not a regular file but is patched.

**Comment by BarkingBad** [comment]
Could you elaborate on how is it patched? I would like to resolve this issue since it came over too many times

**Comment by BarkingBad** [comment]
@smarter I think the PRs weren't rebased, there is [PR](https://github.com/lampepfl/dotty/pull/12819) merged by Krzysztof that disables `Predef` from testing, and I see that CI on master succeedes.

**Comment by smarter** [comment]
This issue is about the release-3.0.1 branch, the PR you linked to needs to be backported to that branch.

**Comment by anatoliykmetyuk** [comment]
Backported, closing this one.
