### ISSUE TITLE
Type inference bug for type member based on a dependent type

### ISSUE THREAD

**Issue by epifab** [lampepfl/dotty#12886]
## Compiler version

3.0.0

## Minimized code

```Scala
trait X:
  type Out
  def value: Out

class XWrapper[XX <: X](val x: XX):
  type Out = x.Out

object XWrapper:
  type Aux[T, U] = XWrapper[T] { type Out = U }

def getValue[XX <: X, U](y: XWrapper.Aux[XX, U]): U =
  y.x.value
```

## Output

Compilation error:
```
Found:    y.x.Out
Required: U
    y.x.value
```

## Expectation

The compiler should know that y.x.Out and U are the same type

**Comment by smarter** [comment]
Both `X` and `XWrapper` have a member called `Out`, but they're not the same member. Let's give them their own name to make things clearer:
```scala
trait X:
  type A
  def value: A

class XWrapper[XX <: X](val x: XX):
  type B = x.A

object XWrapper:
  type Aux[T <: X, U] = XWrapper[T] { type B = U }

  def getValue[XX <: X, U](y: XWrapper.Aux[XX, U]): U =
    y.x.value
```
```scala
-- [E007] Type Mismatch Error: try/i12886.scala:12:8 ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
12 |    y.x.value
   |    ^^^^^^^^^
   |    Found:    y.x.A
   |    Required: U
```

Here I think it's clear that the issue is that `A` does not match `U`, the value of `B` doesn't matter since `y.x` has type `y.x.A`.

**Comment by epifab** [comment]
@smarter well, as far as I can tell, U = y.B = y.x.A. can't the compiler figure this out?

**Comment by smarter** [comment]
No, subtype checking isn't transitive: when checking `y.B <: y.x.A` the compiler won't look for some other type T such that `y.B <: T` and `T <: y.x.A`, that would mean checking a potentially infinite number of types.

**Comment by epifab** [comment]
@smarter I am not sure I follow. in the example we have: `U = B` and `B = x.A`. why would the compiler need to look for another type `T` in between?

**Comment by smarter** [comment]
When the compiler checks `y.x.A <: U`, `U` isn't constrained (it's declared as just `U` without bounds in `def getValue[XX <: X, U]`), the fact that `U` has to be equal to `y.x.A` is something that can be derived from the fact that it appears as the rhs of `B` and that `B` is already defined to be equal to `x.A`, but that's a very indirect complex reasoning the compiler isn't going to perform.
