### ISSUE TITLE
Unit-Insertion works differently in Scala 2 & Scala 3

### ISSUE THREAD

**Issue by Arthurm1** [lampepfl/dotty#12890]
Scala 3 handles unit-insertion differently to Scala 2

## Compiler version
3.0.0 vs 2.13.6 - both using Scastie

## Minimized code

```Scala
val f: Boolean => Any = g => {
  if (g)
    1
}
println(f(true))
println(f(false))
```

## Output - using Scala 3...
```scala
()
()
```
plus warning...
`A pure expression does nothing in statement position; you may be omitting necessary parentheses`

## Expectation - as in Scala 2...
```scala
1
()
```
plus no warning

## Comments
Scala 3 does give the above warning about a pure expression and changing the code to the following works...

```Scala
val f: Boolean => Any = g => {
  if (g)
    1
  else
    ()
  }
}
println(f(true))
println(f(false))
```

From @smarter ...
_"it looks like unit-insertion is working differently in scala 2 and 3 (in scala 2 it only inserts Unit in the missing branch, in Scala 3 it inserts it in both branches)"_

**Comment by abgruszecki** [comment]
IIRC, I think this was intentional - an `if` with only one branch is essentially treated as a side-effectful statement. @odersky can you comment?

**Comment by odersky** [comment]
Yes, that's intentional. I am not sure whether Scala 2's behavior was an accident, or whether there was some specific motivation behind it.

**Comment by som-snytt** [comment]
The behavior is [specified](https://scala-lang.org/files/archive/spec/2.13/06-expressions.html#conditional-expressions):

> A short form of the conditional expression eliminates the else-part. The conditional expression if (e1e_1e1​) e2e_2e2​ is evaluated as if it was if (e1e_1e1​) e2e_2e2​ else ().

Also the feature is not called "Unit insertion" (which sounds helpful) but "Value discard" (which sounds possibly dangerous).

**Comment by cayhorstmann** [comment]
Is the Scala3 behavior documented anywhere? In http://dotty.epfl.ch/docs/reference/syntax.html, `Expr1 ::= ...  [‘inline’] ‘if’  Expr ‘then’ Expr [[semi] ‘else’ Expr] ...`, so an `if` without `else` is an expression, not a statement. It's not immediately intuitive that it should be an expression with value `()`

**Comment by som-snytt** [comment]
I saw a tailrec method of the form `def f: Unit = if (b) f` and wondered does that even compile. It compiles for `Unit` result but not for `Any`. The Scala 2 rule, that `if (b) expr` means `if (b) expr else ()`, is much easier to reason about, in that there is nothing to reason about.

```
import annotation._

class C() {
  //type R = Unit
  type R = Any
  @tailrec
  final def f(i: Int): R =
    if (i > 0) {
      println(s"$i ...")
      f(i-1)
    }
}

object Test extends App {
  val c = new C()
  println(c.f(5))
}
```
