### ISSUE TITLE
SBT: report a warning if ./scala-scala is absent

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1290]
Dotty test suite would fail if one didn't clone compatible version of stdlib.

It would be nice to give a warning for people running either `test` or `partests` suggesting the to do:

```
git clone -b dotty-library https://github.com/DarkDimius/scala.git ./scala-scala
```

**Comment by sjrd** [comment]
Even better, we can have `sbt` clone it for you.

**Comment by liufengyun** [comment]
What about add `scala` as a submodule?

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by smarter** [comment]
We now have warnings when submodules are not present.
