### ISSUE TITLE
Wrong error about recursive method needing return type

### ISSUE THREAD

**Issue by Duhemm** [lampepfl/dotty#12916]
## Compiler version
3.0.0
I can also reproduce in master @ 2ccf681537f48577a834780b8da1193d92b69f5f (with the repl)

## Minimized code

```Scala
def foo(x: Int, d: => Int = foo(0)): Int = if (x < 10) x else d
```

## Output
```
1 |def foo(x: Int, d: => Int = foo(0)): Int = if (x < 10) x else d
  |                               ^
  |            Overloaded or recursive method foo$default$2 needs return type
```

## Expectation
The function is defined.

## Notes
Compiles fine with Scala 2.12, 2.13

Workaround:
```scala
def foo(x: Int, d: => Int = foo(0, ???)): Int = if (x < 10) x else d
```

**Comment by odersky** [comment]
I think that will sort itself out anyway once we change default parameters to inline expressions. I don't see much we can do now.
