### ISSUE TITLE
tests/generic-java-signatures/derivedNames.scala fails on macOS

### ISSUE THREAD

**Issue by changvvb** [lampepfl/dotty#12917]
## Compiler version

3.0.0

## Minimized example

```sh
sbt testCompilation derivedNames
```

## Output
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at dotty.tools.vulpix.ChildJVMMain.runMain(ChildJVMMain.java:40)
        at dotty.tools.vulpix.ChildJVMMain.main(ChildJVMMain.java:47)
Caused by: java.lang.AssertionError: assertion failed: Test$Foo$A<Test$Foo<T1>$B$> != Test$Foo.Test$Foo$A<Test.Test$Foo<T1>.B$>
        at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
        at Test$.main(derivedNames.scala:12)
        at Test.main(derivedNames.scala)
        ... 6 more
```

## Expectation
No test failed.

**Comment by odersky** [comment]
I actually get the same error when testing locally on an Intel MacBook Pro. Is it a Mac vs Linux problem? Or a compilation order dependency?

**Comment by bishabosha** [comment]
also fails for me on intel mac

**Comment by smarter** [comment]
The test as-is already does different things on different platforms but that seems very weird to me, I would expect the difference to come from different JDK versions: https://github.com/lampepfl/dotty/blob/master/tests/generic-java-signatures/derivedNames.scala, can everyone list what the output of `java -version` is like for them?

**Comment by changvvb** [comment]
> can everyone list what the output of `java -version` is like for them?

openjdk version "1.8.0_282"
OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-macos-aarch64) (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (Zulu 8.52.0.23-CA-macos-aarch64) (build 25.282-b08, mixed mode)

**Comment by bishabosha** [comment]
also tested failing with
```
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)
```

**Comment by odersky** [comment]
I have:
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

**Comment by smarter** [comment]
@Kordyjan You changed the output of this test on Mac in https://github.com/lampepfl/dotty/commit/fea5ccf6897fabe8e5e9b7ec1560c020a93564fc#diff-c6eb8702fbdb4a1cb10e2f1f45e8f055907168d494763a923ad91bc842a1b105, which java version are you using where this is needed?

**Comment by Kordyjan** [comment]
> which java version are you using where this is needed?
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```
That is my current version and the test is passing.
Although, I may have been using OpenJDK 11, when I made this change.

**Comment by smarter** [comment]
1.8.0 161 is pretty old (https://www.oracle.com/java/technologies/javase/8u161-relnotes.html says January 2018), it sounds like a bug was fixed meanwhile, so it's probably a good idea to upgrade and either revert the change or allow both forms to compile on Mac with the test too.

**Comment by Kordyjan** [comment]
I've updated the jdk to `1.8.0_291` and the output is the same as on Linux. I'll revert this change as it seems to only affect really outdated builds of `1.8`.
