### ISSUE TITLE
make refined type printing more source compatible

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#12939]
## Compiler version

3.0.1-RC1

## Minimized example

```Scala
class Bag extends reflect.Selectable

val m = new Bag { val f = 23; def g = 47; def h(i: Int): Int = i }
```

## Output

in the repl the type printed has a type that is not source compatible
```scala
scala> val m = new Bag { val f = 23; def g = 47; def h(i: Int): Int = i; var i = 101; type N = Int }
val m: Bag{f: Int; g: => Int; h(i: Int): Int; i: Int; i_=(x$1: Int): Unit; N = Int} = anon$1@403364e9
```

## Expectation

we annotate each refinement with if it is a `type`, `def` or `val`

```scala
scala> val m = new Bag { val f = 23; def g = 47; def h(i: Int): Int = i; var i = 101; type N = Int }
val m: Bag{val f: Int; def g: Int; def h(i: Int): Int; def i: Int; def i_=(x$1: Int): Unit; type N = Int} = anon$1@403364e9
```

**Comment by yasuomaidana** [comment]
Hi, let me try it.

**Comment by yasuomaidana** [comment]
I have a question, how do you make this test?.
It is my first time trying to use and contribute with this project. I already downloaded the repo and if I'm doing well, I'm running scala3 with this repo.
I run tests/pos/HelloWorld.scala, but I'm not sure how to run this example 
😞

**Comment by bishabosha** [comment]
you should be able to add a case to `compiler/test/dotty/tools/repl/TypeTests.scala`

**Comment by anatoliykmetyuk** [comment]
This issue was picked for the Issue Spree No. 23 of 08 November 2022 which takes place in a week from now. @SethTisue, @jan-pieter will be working on it. If you have any insight into the issue or guidance on how to fix it, please leave it here.

**Comment by SethTisue** [comment]
note that there is an abandoned WIP PR at https://github.com/lampepfl/dotty/pull/13698 that already got some review feedback, so presumably we just need to pick that back up again and get it across the finish line

**Comment by SethTisue** [comment]
`var` isn't allowed in refined types, so it's expected that the `var` shows up as a getter/setter pair
