### ISSUE TITLE
Allow pattern matching case classes/enums when using Match Types

### ISSUE THREAD

**Issue by Swoorup** [lampepfl/dotty#12932]
## Compiler version

`3.0.1-RC2`

## Minimized code

```Scala
case class P1(x: String)
case class P2(x: Int)

type Elem[X] = X match
    case P1  => String
    case P2 => Int

def bla[X](v: X): Elem[X] = v match
    case P1(x) => x + "oo"
    case P2(x) => x * 100

@main def main = 
  bla(P1("Blaa"))
```

## Output

```scala
Found:    String
Required: Elem[X]

where:    X is a type in method bla with bounds >: (?1 : P1)
10
    case P2(x) => x * 100
Found:    Int
Required: Elem[X]

where:    X is a type in method bla with bounds >: (?2 : P2)
```

## Expectation

Compiles and runs fine.

This works if you use the type test method instead like replace `bla` with:
```scala

def bla[X](v: X): Elem[X] = v match
    case x: P1 => x.x + "oo"
    case x: P2 => x.x * 100
```

This also applies to enum pattern matches.

**Comment by prolativ** [comment]
This might be a feature request (I would assume this has already been reported) but it's not a bug. This is as specified here https://dotty.epfl.ch/docs/reference/new-types/match-types.html#dependent-typing:
```
The match expression patterns are all Typed Patterns, and these types are =:= to their corresponding type patterns in the match type
```
So the workaround you suggested is actually the official solution to this limitation

**Comment by Swoorup** [comment]
Is there a feature request somewhere, so i can upvote it?

**Comment by prolativ** [comment]
Not sure. @OlivierBlanvillain are there any plans to make this work in the nearest future?
