### ISSUE TITLE
[Semanticdb] Incorrect handling of patched definitions

### ISSUE THREAD

**Issue by dos65** [lampepfl/dotty#12942]
## 3.0.1-RC2

There are difference in members ordering between classes that was pickled from Scala2 and Scala3.
Overloaded id in semanticdb is correct for Scala3 symbol occurences but not for Scala2.

## Minimized code

```Scala
package example

class A {
  assert(true)             // written as scala/Predef.assert(+1) - should be `scala/Predef.assert()`
  assert(true, "error")//  written as scala/Predef.assert() - should be `scala/Predef.assert(+1)`
}
```

## Output

<details>
  <summary>3.0.1-RC2 metap</summary>
  src/main/scala/example/Foo.scala
  --------------------------------

  Summary:
  Schema => SemanticDB v4
  Uri => src/main/scala/example/Foo.scala
  Text => empty
  Language => Scala
  Symbols => 2 entries
  Occurrences => 5 entries

  Symbols:
  example/A# => class A
  example/A#`<init>`(). => primary ctor <init>

  Occurrences:
  [0:8..0:15) <= example/
  [2:6..2:7) <= example/A#
  [3:2..3:2) <= example/A#`<init>`().
  [3:2..3:8) => scala/Predef.assert(+1).
  [4:2..4:8) => scala/Predef.assert().
</details>

<details>
<summary>2.13.6 metap</summary>
src/main/scala/example/Foo.scala
--------------------------------

Summary:
Schema => SemanticDB v4
Uri => src/main/scala/example/Foo.scala
Text => empty
Language => Scala
Symbols => 2 entries
Occurrences => 5 entries

Symbols:
example/A# => class A extends AnyRef { +1 decls }
example/A#`<init>`(). => primary ctor <init>()

Occurrences:
[0:8..0:15) <= example/
[2:6..2:7) <= example/A#
[2:8..2:8) <= example/A#`<init>`().
[3:2..3:8) => scala/Predef.assert().
[4:2..4:8) => scala/Predef.assert(+1).
</details>

## Expectation

```Scala
package example

class A {
  assert(true)             // should be `scala/Predef.assert()`
  assert(true, "error")//  should be `scala/Predef.assert(+1)`
}
```

**Comment by smarter** [comment]
Predef is special: we patch it to add/replace some methods like assert: https://github.com/lampepfl/dotty/blob/master/library/src/scala/runtime/stdLibPatches/Predef.scala, is this issue specific to Predef or can you reproduce it with some other Scala class?

**Comment by dos65** [comment]
@smarter Oh. That explains. Tried on `math.signum` - and it works well.

I don't think that it's a critical issue as there aren't a lot of patches but it would be great if there would be a way to obtain an original symbol name.

**Comment by smarter** [comment]
If you run go-to-definition on `assert(true)` in a Scala 3 file, it should jump to https://github.com/lampepfl/dotty/blob/master/library/src/scala/runtime/stdLibPatches/Predef.scala#L9, not to either definition of assert in Predef.scala in the Scala 2 standard library, on the other hand users should still see the type as scala.Predef.assert, so I don't know if that can be handled in the semanticdb we output or if it should be left to be special-cased in metals or something, wdyt @bishabosha ?

**Comment by dos65** [comment]
Hm. I realized that we can handle this on the Metals side.
For scala 3 we are able to check if there is a patched version for `scala.Predef.$sym`/`scala.language.$sym` symbols in `scala.runtime.stdLibPatches` and provide the correct source file.

Thx for your help. I close this one.
