### ISSUE TITLE
Show per commit benchmarks & PR benchmarks

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1295]
Currently the benchmarks are nightly, which is difficult to spot which commit caused slow down or speed up.

We can build a completely new UI as follows for each graph -- which will be horizontal bar charts instead of line chart:

```
[commit link]  -----------------------------------------------------------------------------
[commit link]  --------------------------------------------------------------
[commit link]  -----------------------------------------------------------
[commit link]  ------------------------------------------------------------
[commit link]  ---------------------------------------------
```

When hovering on each line, we'll be able to see the commit author, summary, message, time, and link back to github.

By default, we only show the latest 10 commits. It's possible to load more to show data for previous commits.

When we have more project-level benchmarks and feature-level benchmarks, it'll be easy to see how performance evolves.

**Comment by sjrd** [comment]
One of my students has been building such a UI this semester (and better, with commit graph). The only thing that would be needed is for the benchmarks to actually *run* the benchmarks on each commit. If the data are available on the server, the UI can already pick them up.

https://github.com/ThibaultUrien/SemesterProject

**Comment by liufengyun** [comment]
@sjrd that's a good news to know.

> The only thing that would be needed is for the benchmarks to actually run the benchmarks on each commit.

That's easy if we have the project-level tests and feature-level tests, we can always regenerate the data from history commits.

If there's any documentation or report, I'm very interested in how to use it. Thanks.

**Comment by sjrd** [comment]
> If there's any documentation or report, I'm very interested in how to use it. Thanks.

Not yet, but it's coming. The deadline for the report is June 10-ish. There will be a presentation, together with the other semester projects, on June 21st.

**Comment by liufengyun** [comment]
Thanks, I'll definitely go to the presentation and learn more.

**Comment by sjrd** [comment]
One thing that would really be needed is for the files containing the results of the benchmarks to identify things by their commit hash, rather than a date. A date is not enough to correctly identify a commit, especially in the presence of reordering rebases.

@liufengyun or @DarkDimius Could one of you adapt whatever is needed so that the commit hash information is stored in the benchmark result files?

**Comment by liufengyun** [comment]
@sjrd I've played with ScalaMeter for a while, I think it's really not a good idea to do regression benchmarks within ScalaMeter.

Rather, I think it's better to define a neutral regressional benchmark format with commit history in mind. This way, the web app is not tied to any specific test framework, and it's easy to adapt the result of any test framework to the standard format.

It would be easy for me to generate the format you defined, than to generate a ScalaMeter-compatible format and clumsily embed the information needed by the web app.

**Comment by sjrd** [comment]
> It would be easy for me to generate the format you defined, than to generate a ScalaMeter-compatible format and clumsily embed the information needed by the web app.

Sure. Any kind of format that contains the relevant information would be fine. It doesn't need to be ScalaMeter-compatible.

**Comment by sjrd** [comment]
@ThibaultUrien What information do you need exactly?

**Comment by japgolly** [comment]
Is this something https://github.com/japgolly/scalajs-benchmark can help with? It doesn't have regression BMs but I'd like to add it.

**Comment by ThibaultUrien** [comment]
@sjrd @liufengyun I think if each test could also contain a field with the hash of the tested commit it would be perfect. Currently, my project use the ScalaMeter sever to get data about dotty performance, but it can be changed whenever needed.

**Comment by liufengyun** [comment]
@japgolly the project looks interesting, it only works for scalajs, right? We'll probably stick with ScalaMeter, and integrate with a regression benchmark web app that has github in mind.

**Comment by liufengyun** [comment]
@ThibaultUrien can we just define a CSV format like follows?

```
commit, test name, result (ms)
```

For example:

```
b853827, stdlib, 15000
```

Is it possible to get all other meta data about a commit through JSON request?

**Comment by DarkDimius** [comment]
@liufengyun, I'd also include confidence intervals in format to discover noisy tests.

**Comment by liufengyun** [comment]
@DarkDimius thanks for the reminder, I updated the proposal.

**Comment by ThibaultUrien** [comment]
This project could work with anything that have a regression test sever and a git repository. The format for the tests result are flexible: there is a .js file used for configuration, by changing one or two regexp inside this file this application could read different file format.

The current format for the test result is : 
test-date	test-name average-time is-success confidence-interval-low	confidence-interval-high	time-unit	"test-iteration1-result test-iteration2-result … "
real exempl of a test oddly named **()** : 
2016-05-31T01:33:12Z	()	13812.2171356	true	12721.746	14902.688	ms	"13676.79428 13704.964335 13731.057285 13750.391144 13765.589825 13850.616772 13859.055074 13873.384517 13899.10174 14011.216384"

**Comment by liufengyun** [comment]
Superseded by #2878
