### ISSUE TITLE
Missing import term 

### ISSUE THREAD

**Issue by mbore** [lampepfl/dotty#12965]
## Compiler version
3.0.1-RC2

## Minimized code
Main.scala
```Scala
object Instances {
  val s: String = "STRING"
}

object Test {
  import Instances.*

  val sMacro = Macros.f()
}
```
Macros.scala
```Scala
import scala.quoted.*

object Macros {
  inline def f(): String = ${ fImpl }

  def fImpl(using q: Quotes): Expr[String] = {
    import q.reflect.*

    val classSymbol = Symbol.spliceOwner.owner.owner
    println(classSymbol.tree.show)

    ???
  }
}

```
## Output

```scala
@scala.annotation.internal.SourceFile("src/main/scala/Main.scala") object Test extends java.lang.Object { this: Test.type =>
        val sMacro: scala.Predef.String
      }
```

## Expectation
`classSymbol.tree` does not contain any `Import` term, but as far as I understand it should. 
Based on output of 
```Scala
object Macros {
  inline def f(): String = ${ fImpl }

  def fImpl(using q: Quotes): Expr[String] = {
    import q.reflect.*

    val expr = '{
      import Instances.*

      val sMacro = Macros.f()
    }
      
    println(expr.asTerm.show)

    ???
  }
}
```
which is 
```Scala
{
  import Instances.{_}
  val sMacro: scala.Predef.String = Macros.f()
  ()
}
```
I would expect output:

```Scala
@scala.annotation.internal.SourceFile("src/main/scala/Main.scala") object Test extends java.lang.Object { this: Test.type =>
        import Instances.{_}
        val sMacro: scala.Predef.String
      }
```

**Comment by nicolasstucki** [comment]
That tree for the class seems to be synthesized. This should be run with `-Yretain-trees` to load the tree from the tasty file. That one should contain the import.

**Comment by mbore** [comment]
Yes, you're right, it works this way, thank you.
But in my use case, I would like to access the Import term in a macro used in a library (expanded in the user code).
Does it mean that every user of the library needs to add the `-Yretain-trees` flag to make it work?

**Comment by nicolasstucki** [comment]
Yes, for now you will have to use `-Yretain-trees`. In the future, we should be able to enable `-Yretain-trees` by default. We do not currently do it because it currently we retain too much and we cannot GC those trees. An issue that is solvable but requires some work.

**Comment by mbore** [comment]
Ok I see, hope it will be fixed soon. thanks for the answer!
