### ISSUE TITLE
scala 3 repl does not work with -cp argument, needs -repl as workaround

### ISSUE THREAD

**Issue by bjornregnell** [lampepfl/dotty#12973]
## Compiler version

3.0.0 and 3.0.1-RC2

## Minimized code and output
The repl cannot be started with a `-cp` argument.

In 3.0.0 using the .zip from the release on Ubuntu:
```
$ scala -cp "some.jar" 
warning: command option is not correct.
```
In 3.0.1-RC2 instead of a warning, the `-help` output is printed.

## Expectation
* Should start the repl with "some.jar" on claspath.
* Should work as in Scala 2.
 
## Undocumented workaround:
```
$ scala -cp "some.jar" -repl
```

**Comment by griggt** [comment]
This seems to have been recently fixed, perhaps by #13081?

**Comment by bjornregnell** [comment]
Fantastic if this is fixed!!!  Will the old -repl option hurt after the fix or will that still work? 
(I have updated my teaching material in several places to add -repl  when -cp and it goes to print hopefully on Monday, students come Aug 30...)

**Comment by griggt** [comment]
> Will the old -repl option hurt after the fix or will that still work?

I just tried it, and it now displays a message on startup: `bad option '-repl' was ignored`, but otherwise works.

So the situation is:

Scala 3.0.0 through 3.0.2 (forthcoming, RC1 is out): needs the `-repl` workaround
Scala 3.1.0 (not yet in RC): has the fix, complains that `-repl` is a bad option, but works regardless

**Comment by bjornregnell** [comment]
Thanks @griggt for clarification on versions. (Then I need to decide if I should print as is and make errata or add some kind of footnote with version info or something.) 
When might stable 3.1.0 earliest be out on github releases?

**Comment by bishabosha** [comment]
> When might stable 3.1.0 earliest be out on github releases?

If no issues are found with the 3.1.0-RC1 releasing September 1 then the 3.1.0 final should be about October 13th

**Comment by bjornregnell** [comment]
@griggt Is "bad option" the right message after fix? I mean: is there any use still for that -repl option or it is eradicated for good from 3.1?

**Comment by BarkingBad** [comment]
I removed it. Related disscussion is here https://github.com/lampepfl/dotty/pull/13081#discussion_r671285716

**Comment by bjornregnell** [comment]
Great! (I have just added a note in my teaching material that `-repl` in conjunction with `-cp` is not needed from Scala 3.1.0. It will be sent to print on sunday...)
