### ISSUE TITLE
scala 3 repl does not show if a message is an error or a warning (regression from scala 2)

### ISSUE THREAD

**Issue by bjornregnell** [lampepfl/dotty#12981]
## Compiler version

3.0.0

## Minimized code and output

```Scala
scala> val x = if true then 42
1 |val x = if true then 42
  |                     ^^
  |A pure expression does nothing in statement position; you may be omitting necessary parentheses

scala> val x = val
1 |val x = val
  |        ^^^
  |        expression expected but val found
```

## Expectation
The first message above should include `warning` and the the second should include `error`. It is conceptually important to understand if the code has run or not, esp. for learners but also for professionals - I don't know all messages by hart if they are warnings or errors. Now it all looks the same in the Scala 3 REPL.

This is a regression from the Scala 2 REPL, in which you can always tell if a message is an error or a warning.

**Comment by som-snytt** [comment]
Warning text could be in yellow, error text in red and blinking!

But maybe manage that annoying behavior with `-color:no-blink`?

**Comment by bjornregnell** [comment]
I'm copy-pasting things around in various teaching material and also some people are color blind so I think `warning:` and `error:` is still necessary. Although a colorful life is always nice :rainbow:

**Comment by bjornregnell** [comment]
@som-snytt  Is this too hard to fix for a REPL-hacker-noob like me, do you think? I mean, I managed to find where to prohibit mal-truncation last time with your help :rescue_worker_helmet:

**Comment by SethTisue** [comment]
for reference/comparison, Scala 2:

<img width="400" alt="Screen Shot 2021-06-29 at 8 32 22 AM" src="https://user-images.githubusercontent.com/161079/123826369-90346d80-d8b4-11eb-99fc-1061e57d2f07.png">

**Comment by dwijnand** [comment]
I don't know for sure but I would hazard a guess that this is very noob-friendly :)

**Comment by bjornregnell** [comment]
Thanks @dwijnand for encouragement. I'll hopefully find a coffee-break slot for looking into this soon.

**Comment by bjornregnell** [comment]
I have started to browse the code and the REPL has [ParseResult](https://github.com/lampepfl/dotty/blob/b7d2a122555a6aa44cc7590852a80f12512c535e/compiler/src/dotty/tools/repl/ParseResult.scala) and the compiler dotc itself has [StoreReporter](https://github.com/lampepfl/dotty/blob/5ac62a1618f3d311d4c249c4adeeee571b5f2840/compiler/src/dotty/tools/dotc/reporting/StoreReporter.scala) but I'm uncertain if this should just be a tweak to the printout at the outer rim of the REPL or it should go deep down into the rendering of error messages inside the compiler?

**Comment by dwijnand** [comment]
I think it's a REPL thing, as the batch compiler already displays it its own way:

```
$ scalac3 test/files/neg/t8597.1.scala
-- Warning: test/files/neg/t8597.1.scala:5:43 ----------------------------------
5 |  def warn1[T]  = (null: Any) match { case _: T            => } // warn
  |                                           ^^^^
  |                          the type test for T cannot be checked at runtime
1 warning found
```

**Comment by bishabosha** [comment]
you can look in `compiler/src/dotty/tools/dotc/reporting/MessageRendering.scala` for the way it is printed in the standard compiler

**Comment by bjornregnell** [comment]
Thanks for pointers! Will try to grok it. It seems to me that the REPL should reuse all the reporting stuff from dotc sans the file marker, but apparently the REPL just utilizes the vertical bar stuff.

**Comment by bjornregnell** [comment]
My plan is to try to fix this before or during rendering.formatError which is called from [displayErrors](https://github.com/lampepfl/dotty/blob/00218e8cef94051569b5b184ba8e1f624348e4ab/compiler/src/dotty/tools/repl/ReplDriver.scala#L421) and I starting to investigate it with some good old println instrumentation but it seems as the error level does not differentiate between warnings and errors; check the level output here:
```
sbt:scala3> repl
[info] compiling 1 Scala source to /home/bjornr/git/hub/bjornregnell/dotty/compiler/target/scala-3.0.0/classes ...
[info] compiling 1 Scala source to /home/bjornr/git/hub/bjornregnell/dotty/out/bootstrap/scala3-compiler-bootstrapped/scala-3.0.2-RC1-bin-SNAPSHOT-nonbootstrapped/classes ...

scala> val x = if true then 42  // should be a warning but level == 2 not 1
*** DEBUG: start of displayErrors(List(class dotty.tools.dotc.reporting.Diagnostic$Error at rs$line$1:[21..23]: A pure expression does nothing in statement position; you may be omitting necessary parentheses))
*** DEBUG: errs.size = 1
*** DEBUG: errs.head.level = 2
*** DEBUG: rendering.formatError(errs.head) = class dotty.tools.dotc.reporting.Diagnostic at rs$line$1:[21..23]: 1 |val x = if true then 42
  |                     ^^
  |A pure expression does nothing in statement position; you may be omitting necessary parentheses
1 |val x = if true then 42
  |                     ^^
  |A pure expression does nothing in statement position; you may be omitting necessary parentheses

scala> val x: String = 42
*** DEBUG: start of displayErrors(List(class dotty.tools.dotc.reporting.Diagnostic$Error at rs$line$1:[16..18]: Found:    (42 : Int)
Required: String))
*** DEBUG: errs.size = 1
*** DEBUG: errs.head.level = 2
*** DEBUG: rendering.formatError(errs.head) = class dotty.tools.dotc.reporting.Diagnostic at rs$line$1:[16..18]: 1 |val x: String = 42
  |                ^^
  |                Found:    (42 : Int)
  |                Required: String
1 |val x: String = 42
  |                ^^
  |                Found:    (42 : Int)
  |                Required: String

scala> def warn[T] = (null: Any) match { case _: T => }
*** DEBUG: start of displayErrors(List(class dotty.tools.dotc.reporting.Diagnostic$Error at rs$line$1:<39..39>: the type test for T cannot be checked at runtime))
*** DEBUG: errs.size = 1
*** DEBUG: errs.head.level = 2
*** DEBUG: rendering.formatError(errs.head) = class dotty.tools.dotc.reporting.Diagnostic at rs$line$1:<39..39>: 1 |def warn[T] = (null: Any) match { case _: T => }
  |                                       ^
  |                          the type test for T cannot be checked at runtime
1 |def warn[T] = (null: Any) match { case _: T => }
  |                                       ^
  |                          the type test for T cannot be checked at runtime

scala>                                                                                                                                                                                   
```
Above is the output of this tweaked displayErrors during the above `sbt repl` session:
```
  private def displayErrors(errs: Seq[Diagnostic])(implicit state: State): State = {
    println(s"*** DEBUG: start of displayErrors($errs)")
    println(s"*** DEBUG: errs.size = ${errs.size}")
    println(s"*** DEBUG: errs.head.level = ${errs.head.level}")
    println(s"*** DEBUG: rendering.formatError(errs.head) = ${rendering.formatError(errs.head)}")
    errs.map(rendering.formatError).map(_.msg).foreach(out.println)
    //println(s"*** DEBUG: end of displayErrors: State = $state")
    state
  }
```
Is it a bug that the level is not 1 instead of 2 for the warnings above or have I misunderstood the usage of the [level attribute](https://github.com/lampepfl/dotty/blob/master/interfaces/src/dotty/tools/dotc/interfaces/Diagnostic.java)?

**Comment by bjornregnell** [comment]
Perhaps the Build's fatal warnings propagate? I'm checking currently with all fatal warnings turned off in Build.sbt.

**Comment by bjornregnell** [comment]
Yes! Turning off fatal warnings helped! Now trying to find ways to tweak the rendering... Hang on.

**Comment by bjornregnell** [comment]
SUCCESS: :smile: 
```
scala> val x = if true then 42                                                                                                                                                           
-- Warning:
1 |val x = if true then 42
  |                     ^^
  |A pure expression does nothing in statement position; you may be omitting necessary parentheses

scala> val x: String = 42                                                                                                                                                 
-- Error:
1 |val x: String = 42
  |                ^^
  |                Found:    (42 : Int)
  |                Required: String
```
I have found a minimal tweak of the REPL's [messageRenderer](https://github.com/bjornregnell/dotty/commit/b3643e05fbeba8f17f9050f13ff4b36508a9298f).
I have no idea how to add tests for this; esp since all fatal warnings needs to be cleansed from Build.sbt for this to happen... But I guess I should not commit that as dotty devs want fatal warnings?

**Comment by bjornregnell** [comment]
@dwijnand  Should I make a PR now?

**Comment by bishabosha** [comment]
you will probably have to change the sources in `compiler/test-resources/repl`, which are used to "replay" repl sessions and check the output (these are ran by `compiler/test/dotty/tools/repl/ScriptedTests.scala`)

**Comment by bjornregnell** [comment]
@bishabosha thanks; will `testOnly dotty.tools.repl.ScriptedTests` not have fatal warnings on?

**Comment by bjornregnell** [comment]
Aha I get it. Sorry. Checking errors now and fixing output.

**Comment by bjornregnell** [comment]
... a lot of manual work. Have just managed to do a tiny percentage of the tests so far. I'm considering writing a script or something.

**Comment by bjornregnell** [comment]
I've made a scritpt to insert "Error:" and then tweaked the few "Warning:" cases manually.

**Comment by bjornregnell** [comment]
Now here: https://github.com/lampepfl/dotty/pull/13000  A nice and even PR number :smile: 
Happy for review input @bishabosha @dwijnand

**Comment by bjornregnell** [comment]
@bishabosha The builds seem to fail - are there more sbt tasks than `dotty.tools.repl.ScriptedTests` that I should run? (I guess my little util needs to dig deeper into the guts of the repl test dir...)

**Comment by bjornregnell** [comment]
The CI build fails here: Test dotty.tools.repl.ShadowingTests.i7635 failed: java.lang.AssertionError: Error in script <i7635>,
But I can't find it even if I search for it. Any clue where it is?

**Comment by bjornregnell** [comment]
@bishabosha  Found it: compiler/test/dotty/tools/repl/ShadowingTests.scala

**Comment by bjornregnell** [comment]
I'm running `testOnly dotty.tools.repl.*` now to be sure.

**Comment by bjornregnell** [comment]
All tests pass in CI build. :partying_face:

**Comment by bjornregnell** [comment]
@som-snytt Your colorful suggestion has gotten red alert attention with hope of a green light soon.
