### ISSUE TITLE
LUB of `Int | Short`

### ISSUE THREAD

**Issue by cquiroz** [lampepfl/dotty#12985]
## Compiler version

3.0.0

## Minimized code

```Scala
      val s: Short = 1
      (if (true) s else -s).toShort
```

## Output

```scala
[error] 36 |      (if (true) s else -s).toShort
[error]    |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |      value toShort is not a member of (s : Short) | Int
```

## Expectation

On Scala 2 the `if` expression was of type `Int` and you could call any valid methods in `Int` but in Scala 3. the expression is of type `Short | Int` thus methods like `toShort` cannot be calle
Note this is valid though

` val p: Int = (if (true) s else -s)`

**Comment by som-snytt** [comment]
`-s` is `Int` also in Scala 2, but spec says result of negation is `T` itself.
```
Parameterless arithmetic methods identity (+) and negation (-), with result type T. The first of these returns the receiver unchanged, whereas the second returns its negation.
```

**Comment by cquiroz** [comment]
Right -s produces an Int in both scala 2 and scala 3

**Comment by odersky** [comment]
That's weak conformance in Scala 2 kicking in. I personally found it OK but a lot of people hated it so it got removed.
