### ISSUE TITLE
summonInline can't find local givens.

### ISSUE THREAD

**Issue by roald-di** [lampepfl/dotty#12997]
## Compiler version

v3.0.0 , v3.0.1-RC1 and v3.0.1-RC2

## Minimized code

```scala
import scala.compiletime._

// works
val a = {
    given Int = 0
    summon[Int]
}
  
// doesn't
inline def summonInt = {
    given Int = 0
    summonInline[Int]
}
  
val b = summonInt
```

## Output
v3.0.0:
```
cannot reduce summonFrom with
 patterns :  case given t @ _:Int
```

v3.0.1-RC1 and v3.0.1-RC2:
```
no implicit argument of type Int was found
```

## Expectation
The locally introduced given is found

### Update
As per #12359 this can currently be achieved with

```scala
inline def delayedSummonInline[T] = summonInline[T]

transparent inline def summonInt = {
    given Int = 0
    delayedSummonInline[Int]
}
  
val b = summonInt
```

**Comment by odersky** [comment]
Maybe local givens are not properly entered in TreeMapWithImplicits?

**Comment by nicolasstucki** [comment]
It seems that in this case we should be adding the implicit in the `InlineTyper` while inlining `summonInt`.

**Comment by nicolasstucki** [comment]
It looks like the `ReTyper` does not add the implicit. But the `ReTyper.typedBlock` used the `Typer.typedBlock` which does add the implicit in scope when typing. 

@odersky is there something that disables the tracking of implicit in the `ReTyper`?

**Comment by odersky** [comment]
@nicolasstucki I believe it's the fact that `index` is overridden to do nothing. `ReTyper` does not have a local scope, so it cannot compute local implicits.
