### ISSUE TITLE
Classes that are not open can be extended even though different files and adhocExtensions not used

### ISSUE THREAD

**Issue by hseeberger** [lampepfl/dotty#12996]
## Compiler version

3.0.1-RC2

## Minimized code

(file Foo.scala)
```Scala
class Foo
```

(file Bar.scala)
```Scala
class Bar extends Foo
```

## Output

The above compiles, but that is not expected.

## Expectation

According to the docs about open classes (http://dotty.epfl.ch/docs/reference/other-new-features/open-classes.html), "Classes that are not open can still be extended, but only if ...". None of the required preconditions are met here, because we are using different files and have not used the language feature `adhocExtensions`.

**Comment by bishabosha** [comment]
Perhaps the documentation isnt so clear, it states at the bottom of the page that the warning is only produced when `future` language/source mode is used

```
import scala.language.future
```
or
```
scalac -source:future
```
