### ISSUE TITLE
Provide windows version binary package.

### ISSUE THREAD

**Issue by fenginsc** [lampepfl/dotty#13002]
Download the Scala binaries for 3.0.0 at github.
I downloaded the binary installation package, but there is no windows version of the startup file. I hope to provide the windows version of the bat startup file. The current version is the *nix version of the bash startup file.

**Comment by michelou** [comment]
Duplicate of [issue #12551](https://github.com/lampepfl/dotty/issues/12551).

Related to (closed) [issue #10300](https://github.com/lampepfl/dotty/issues/10300).

**PS.** PR is pending (subset of [PR #5444](https://github.com/lampepfl/dotty/pull/5444)).
