### ISSUE TITLE
Have a consistent classpath order between partest joined compilation, partest separate compilation, partest run tests, dotc and dotr

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1301]
Currently, all of these things work differently, this bites us in https://github.com/lampepfl/dotty/pull/1289 because the same class `strawman.collection.CollectionStrawMan5` is defined in two files:
- src/strawman/collections/CollectionStrawMan5.scala
- tests/run/colltest5/CollectionStrawMan5_1.scala

Which one gets picked varies:
1. Under joined compilation of
   `tests/run/colltest5/CollectionStrawMan5_1.scala` and
   `tests/run/colltest5/CollectionTests_2.scala`, the source file that comes from `tests` is
   prioritized over the classfile that comes from `src`
2. Under separate compilation, we  pick the classfile that comes from `src` because it is on the java bootclasspath and the partest output directory is only on the scala classpath ([`-classpath` option passed to dotty, not to the JVM](https://github.com/lampepfl/dotty/pull/1289/commits/c31418b503dc1a438113c15bcb4268ba4ccbd822#diff-973097a36413c0bcee9d696571e85699))
3. When running the run test we pick the classfile that comes from `test` and here understanding how the classpath is set becomes near impossible because of #1300 

For now I've worked around this by [changing the name of the class in the tests](https://github.com/lampepfl/dotty/pull/1289/commits/69f973a71945d541c77962eddb926822bb92abbf), but this still seriously needs to be more consistent, especially if we want to test separate compilation of parts of dotty.

**Comment by sjrd** [comment]
That is also on my roadmap about cleaning up the build.

**Comment by smarter** [comment]
Also the current source directory should not be part of the classpath when compiling and running tests, otherwise you might get test failures because of classpath pollution

**Comment by nicolasstucki** [comment]
Partest is no more. This is not an issue anymore.
