### ISSUE TITLE
Inlined "pure expression" is not recognized as such

### ISSUE THREAD

**Issue by edolgy** [lampepfl/dotty#13024]
## Compiler version

3.0.1-RC2

## Minimized code

```Scala
object Test:

  object FooDef:
    class Bar

  inline def Foo = FooDef

  import Foo.Bar  // Fails to compile: "import prefix is not a pure expression"
```

## Expectation
"inline def Foo" is not a pure expression, but it does inline the pure one.  

I understand that a "val" can be used, but to eliminate circular calls it must be a "lazy val", which results in very heavy java byte code. When used in hundreds of cases, the overhead becomes really significant.

On the other hand, if inlining pure expression is allowed, the java byte code is just perfect, calling FooDef.Bar directly.

Please, consider making the change, as this could be a huge design pattern in larger systems.

Even in scala.Predef, stuff like:
``` 
val Map = immutable.Map
val Set = immutable.Set
```
eventually could be more natural when reading stack traces as "inline def"

**Comment by smarter** [comment]
It works with `transparent inline def Foo = FooDef`, it can't work with a regular inline def because that only gets inlined after typechecking

**Comment by edolgy** [comment]
Perfect

Thanks a lot

**Comment by som-snytt** [comment]
The Scala 3 "one-question FAQ" is surely "add transparent".
