### ISSUE TITLE
ambiguous static forwarders for overridden methods

### ISSUE THREAD

**Issue by raboof** [lampepfl/dotty#13039]
## Compiler version

3.0.1-RC1

## Minimized code

```Scala
trait Super[T <: Number]:
  def get: T

class Sub extends Super[Integer]:
  override def get: Integer = ???
```

## Output (OK?)

```scala
$ javap Sub.scala
public class Sub implements Super<java.lang.Integer> {
  public Sub();
  public java.lang.Integer get();
  public java.lang.Number get();
}
```

## Expectation

That duplicate 'get' method seems suspicious to me, I had expected:

```scala
$ javap Sub.scala
public class Sub implements Super<java.lang.Integer> {
  public Sub();
  public java.lang.Integer get();
}
```

... however in fact both Scala and Java appear to select the correct method just fine.

## Minimized code

Adding static object forwarders to the mix, however:

```
trait Super[T <: Number]:
  def get: T = ???

object Sub extends Super[Integer]:
  override def get: Integer = 37
```

## Output

```
$ javap Sub.class
public final class Sub {
  public static java.lang.Integer get();
  public static java.lang.Number get();
}
```

## Expectation

Here I expected:

```
$ javap Sub.class
public final class Sub {
  public static java.lang.Integer get();
}
```

And in this case it actually leads to a problem: while Scala code will not use these forwarders anyway, when using them from Java:

```
public class Use {
	public static void main(String... args) {
		System.out.println(Sub.get());
	}
}
```

I get a "reference to get is ambiguous" error from javac (tested with AdoptOpenJDK-11.0.11+9 - interestingly OpenJDK 1.8.0_272-b10 appears to select the right method just fine).

(of course this is a minimized example, but we see this problem when building Akka with Scala 3 and referring to Akka extensions from Java code)

**Comment by smarter** [comment]
Can you try with a nightly? (`scalaVersion := "3.0.2-RC1-bin-20210708-7627583-NIGHTLY"`), https://github.com/lampepfl/dotty/pull/12860 should have fixed this.

**Comment by raboof** [comment]
> Can you try with a nightly? (scalaVersion := "3.0.2-RC1-bin-20210708-7627583-NIGHTLY"), #12860 should have fixed this.

Confirmed, both on the reproducer and on the Akka build!
