### ISSUE TITLE
NaN quoted pattern

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#13033]
## Compiler version

3.0.0

## Minimized example
Does this quoted pattern work?

```Scala
'{ Double.NaN } match 
  case '{ Double.NaN } =>
```

## Expectation

It should match.

**Comment by sjrd** [comment]
If you have that problem, you probably have the reverse problem for +0.0 v -0.0:
```scala
'{ 0.0 }  match
  case '{ -0.0 } =>
```
should not match, nor should
```scala
'{ -0.0 }  match
  case '{ 0.0 } =>
```
