### ISSUE TITLE
Scala3 should support Unicode supplementary characters

### ISSUE THREAD

**Issue by magnolia-k** [lampepfl/dotty#13045]
https://github.com/scala/bug/issues/1406

https://github.com/scala/scala/pull/9687

**Comment by som-snytt** [comment]
I will forward port as soon as dust settles. Sorry for breaking previous rule to contribute here and then backport. My excuse is Lukas gives quick feedback and fixes your mistakes, he is Copilot for Scala corpus.

**Comment by odersky** [comment]
@som-snytt Thanks!
