### ISSUE TITLE
Signum deprecation warning

### ISSUE THREAD

**Issue by NataliaMGonzalez** [lampepfl/dotty#13055]
## Compiler version
3.0.0

## Minimized example
``` scala
object TryThis {
  val n:Long = 1L
  
  println(n.signum)
  println(n.sign)
}
```

https://github.com/twitter/util/blob/31849459c9987fd3c457691b385eed295a7e2d48/util-core/src/main/scala/com/twitter/util/StorageUnit.scala#L142 

## Output
method signum in trait ScalaNumberProxy is deprecated since 2.13.0: use `sign` method instead

## Expectation
We tried looking up 'sign' in the scala3 documentation, but only found 'signum'. We expect both methods to work exactly the same, but we just need to make sure.
https://dotty.epfl.ch/api/scala/math.html

**Comment by smarter** [comment]
It's a bit hidden but there's an implicit conversion from Long to RichLong and sign is a member of RichLong: https://dotty.epfl.ch/api/scala/runtime/RichLong.html#sign-0

**Comment by smarter** [comment]
By the way, for asking questions it's better to use https://gitter.im/scala/scala or https://users.scala-lang.org/ rather than the issue tracker.

**Comment by som-snytt** [comment]
Or chatty discord channel since everyone except smarter is transitioning.

**Comment by som-snytt** [comment]
Interestingly, `sign` has doc in `runtime.ScalaNumberProxy` but is not shown in inherited members, either Scaladoc 2 or 3. The class comment is "this is not supported API", so there ought to be a way to make such a member documentable. (I'm guessing runtime is excluded.) I see in Scaladoc 3 the search box works but doesn't show it as member of Long, as in Scaladoc 2.

**Comment by NataliaMGonzalez** [comment]
awesome, thanks
