### ISSUE TITLE
Stub code suggestion in missing method error message should use type parameters of present class, not parent trait

### ISSUE THREAD

**Issue by jphmrst** [lampepfl/dotty#13076]
## Compiler version

3.0.1 (and I've noticed this is earlier versions as well)

## Minimized code

```Scala
trait T[A, B] {
  def f(a: A): B
  def g(a: A, b: B): Unit
}

class C[X, Y] extends T[X, Y] {
}
```

## Output

```scala
[info] compiling 1 Scala source to /home/jm/tmp/test/target/scala-3.0.1/classes ...
[error] -- Error: /home/jm/tmp/test/src/main/scala/Main.scala:7:6 ---------------------
[error] 7 |class C[X, Y] extends T[X, Y] {
[error]   |      ^
[error]   |      class C needs to be abstract, since:
[error]   |      it has 2 unimplemented members.
[error]   |      /** As seen from class C, the missing signatures are as follows.
[error]   |       *  For convenience, these are usable as stub implementations.
[error]   |       */
[error]   |        def f(a: A): B = ???
[error]   |        def g(a: A, b: B): Unit = ???
[error] one error found
```

## Expectation

The error is obviously valid, but the suggested code is incorrect: `C`'s type variables are `X` and `Y`, not `A` and `B`.

Bonus whine: the issue "goes away" if the trait only contains one of the two methods, because when it's just one missing method, there is no suggested stub code.  It would be nice to get the stub code in those cases anyway!

**Comment by SethTisue** [comment]
Scala 2 gets it right:

```
On line 6: error: class C needs to be abstract.
       Missing implementations for 2 members. Stub implementations follow:
         def f(a: X): Y = ???
         def g(a: X, b: Y): Unit = ???
```

**Comment by SethTisue** [comment]
> Bonus whine: the issue "goes away" if the trait only contains one of the two methods, because when it's just one missing method, there is no suggested stub code. It would be nice to get the stub code in those cases anyway!

Mind opening a separate ticket on that? Our PR didn't address this.
