### ISSUE TITLE
Extension method name collision across different source files

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#13089]
Different extension methods in the same package, with the same name, but in different files collide. 
If defined in the same source file no error.

## Compiler version

v3.0.1

## Minimized code
Minimized project at: https://github.com/soronpo/dottybug/tree/extension_collision

**Test/Foo.scala**
```Scala
package Test

trait Foo
extension (foo : Foo)
  def fails : Unit = {}
  def works : Unit = {}

extension (bar : Bar)
  def works : Unit = {}
```

**Test/Bar.scala**
```Scala
package Test

trait Bar
extension (bar : Bar)
  def fails : Unit = {}
```
## Output

```scala
[error] -- [E161] Naming Error: C:\IdeaProjects\dottybug\src\main\scala\Test\Foo.scala:5:6 ----------------------------------
[error] 5 |  def fails : Unit = {}
[error]   |  ^^^^^^^^^^^^^^^^^^^^^
[error]   |  fails is already defined as method fails in C:\IdeaProjects\dottybug\src\main\scala\Test\Bar.scala
```

## Expectation
No error.

**Comment by odersky** [comment]
It is an error. See clause 4 in https://dotty.epfl.ch/docs/reference/dropped-features/package-objects.html

> If several top-level definitions are overloaded variants with the same name, they must all come from the same source file.

I have changed the error message to add that as an additional note.

**Comment by soronpo** [comment]
What is the reason for this limitation?

**Comment by odersky** [comment]
Name resolution needs a single prefix to represent an overloaded reference. That prefix is the reference to the package object in which all alternatives are defined.

**Comment by som-snytt** [comment]
and with open class path, you can't have arbitrary locations contributing to top-level definitions aka package object.

Maybe there should be a mechanism for a location to say "I am the canonical package object".
