### ISSUE TITLE
Introduction of `CastClassException` in some lambda with bad type inference

### ISSUE THREAD

**Issue by sherpal** [lampepfl/dotty#13086]
# ClassCastException in lambda with bad type inference

I stumbled on a bug where using a lambda with wildcard to ignore the argument.

## Minimized code

The following [repository](https://github.com/sherpal/class-cast-exception-bug) allows to reproduce the bug.

In `main/Main.scala`

```Scala
package main

import example._

object Main {
  def main(args: Array[String]): Unit = {
    val theFirstWorkingInstance = Foo.UnitFoo.bar("hello").map((_: Any) => 2)
    val theSecondWorkingInstance = Foo.UnitFoo.bar("hello").map((_: Bar) => 2)
    val theCrashingInstance = Foo.UnitFoo.bar("hello").map(_ => 2)

    println("This will work:")
    println(theFirstWorkingInstance.run())
    println(theSecondWorkingInstance.run())

    println("This will crash:")
    println(theCrashingInstance.run())
  }
}

```

In `example/Bar.scala`

```scala
package example

trait Bar

object Bar:
  def bar[A <: Bar]: A = (new Bar {}).asInstanceOf[A]
end Bar
```

and in `example/Foo.scala`

```scala
package example

import example.Foo.MakeBar

trait Foo[+A]:
  def run(): A

  def bar[B <: Bar](stuff: String): Foo[B] = 
    Foo.MakeBar[B](stuff)

  def map[B](f: A => B): Foo[B] =
    Foo.Map(this, f)
end Foo

object Foo:
  case class MakeBar[A <: Bar](stuff: String) extends Foo[A]:
    def run(): A = Bar.bar

  case class Map[A, B](foo: Foo[A], f: A => B) extends Foo[B]:
    def run(): B = f(foo.run())

  object UnitFoo extends Foo[Unit]:
    def run(): Unit = ()
end Foo
```

## Output

```
[info] running main.Main 
This will work:
2
2
This will crash:
[error] (run-main-0) java.lang.ClassCastException: class example.Bar$$anon$1 cannot be cast to class scala.runtime.Nothing$ (example.Bar$$anon$1 is in unnamed module of loader sbt.internal.LayeredClassLoader @27224ada; scala.runtime.Nothing$ is in unnamed module of loader sbt.internal.ScalaLibraryClassLoader @40995e8a)
[error] java.lang.ClassCastException: class example.Bar$$anon$1 cannot be cast to class scala.runtime.Nothing$ (example.Bar$$anon$1 is in unnamed module of loader sbt.internal.LayeredClassLoader @27224ada; scala.runtime.Nothing$ is in unnamed module of loader sbt.internal.ScalaLibraryClassLoader @40995e8a)
[error]         at example.Foo$Map.run(Foo.scala:20)
[error]         at main.Main$.main(Main.scala:16)
[error]         at main.Main.main(Main.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
[error] Total time: 1 s, completed 15 Jul 2021, 21:01:19
```

## Expectation

Calling the `run` method in `theCrashingInstance` should not cast an exception.

**Comment by som-snytt** [comment]
I don't understand why this is unexpected. `Bar.bar` lies when it claims to return `A`. It returns `Bar`s, so only functions taking a `Bar` (or less specific) will work. `Nothing` is a fine thing to infer.

**Comment by sherpal** [comment]
The implementation of the `run` method for `MakeBar` does not matter in this instance. I tried to make a minimal reproducible code. In the actual scenario that I encountered, the method `bar` is well implemented.

When `UnitFoo` calls `bar("hello")`, I would expect the compiler to infer the least upper bound, which, given the definition of `bar`, is `Bar`. And then the `map` method should understand that `_` is a `Bar` (in which case the implementation of `run` is not even lying). But here, the compiler seems to infer `Nothing`.

**Comment by smarter** [comment]
> When UnitFoo calls bar("hello"), I would expect the compiler to infer the least upper bound, which, given the definition of bar, is Bar [...] But here, the compiler seems to infer Nothing.

The compiler, like the user, is free to choose any type argument that satisfies its bounds and that makes the program typecheck, so inferring Nothing is not a bug (see https://www.youtube.com/watch?v=lMvOykNQ4zs for more on how inference works), the bug is in the use of `asInstanceOf` in the program in a situation where the cast might be unsound.
