### ISSUE TITLE
NoSuchMethodError when pattern matching on inner class (no outer accessor)

### ISSUE THREAD

**Issue by SethTisue** [lampepfl/dotty#13096]
tested on both 3.0.0 and 3.0.1-RC2

originally reported by Scala book author @cayhorstmann at https://github.com/scala/scala-xml/issues/541

## Minimized code

```Scala
class C1 {
  private class C2
  new C2 match {
    case c: C2 =>
  }
}

object Test extends App {
  new C1
}
```

## Output

```scala
java.lang.NoSuchMethodError: C1$C2.C1$C2$$$outer()LC1;
 	at C1.<init>(S.scala:6)
```

which occurs because `C2` simply doesn't have an outer accessor method. `C2`s constructor accepts an outer reference, but doesn't do anything with it:

```
  public C1$C2(C1);
    descriptor: (LC1;)V
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=2, args_size=2
         0: aload_0
         1: invokespecial #14                 // Method java/lang/Object."<init>":()V
         4: return
```

## Expectation

The runtime error occurs regardless of whether `C2` is declared `private[this]` or merely `private`. It stops occurring if you declare `C2` to be `private[C1]`. (Perhaps the `private` version fails because of the Scala 3 behavior where plain `private` sometimes means `private[this]` and sometimes means `private[C1]`?)

Ironically, Scala 2 does the reverse: for `private[this]` it gives `C2` an outer accessor, but then the pattern match in `C1`'s constructor does not call it...!

So, what would the correct behavior — keep the check and make it work, or omit it? I don't know offhand, especially once you start considering the nuances of the different access levels the inner class might have. But I see there is a lot of previous lore in this area: https://github.com/lampepfl/dotty/issues/2156, https://github.com/scala/bug/issues/4440, https://github.com/scala/bug/issues/1419, maybe others...?

**Comment by dwijnand** [comment]
> So, what would the correct behavior — keep the check and make it work, or omit it?

Make it work, IMO.  Looks like it's in one of posttyper's phases (oh, probably `explicitOuter`) that isn't capturing an outer reference in `private class C2`.

**Comment by SethTisue** [comment]
compilation of the test code fails under `-Ycheck:all` with

```
*** error while checking tests/run/i13096.scala after phase stringInterpolatorOpt ***
exception occurred while compiling tests/run/i13096.scala
java.lang.AssertionError: assertion failed:  class C2 tree does not define members: method C1$C2$$$outer, value $outer
expected: constructor C2, method C1$C2$$$outer, value $outer
defined:  while compiling tests/run/i13096.scala
Exception in thread "main" java.lang.AssertionError: assertion failed:  class C2 tree does not define members: method C1$C2$$$outer, value $outer
expected: constructor C2, method C1$C2$$$outer, value $outer
defined: 
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.transform.TreeChecker$Checker.typedClassDef(TreeChecker.scala:482)
	at dotty.tools.dotc.typer.Typer.typedTypeOrClassDef$2(Typer.scala:2681)
	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:2685)
```

**Comment by SethTisue** [comment]
PR: #13124
