### ISSUE TITLE
f interpolator rejects vertical bar followed by newline following interpolation  %s|%n

### ISSUE THREAD

**Issue by cayhorstmann** [lampepfl/dotty#13098]
## Compiler version

3.0.0

## Minimized code

```Scala
val s = "Fred"
f"$s|%n"
```

## Output

```scala
conversions must follow a splice; use %% for literal %, %n for newline. 
```

## Expectation

"Fred|" followed by a newline

**Comment by som-snytt** [comment]
Thanks for the report. That is https://github.com/lampepfl/dotty/issues/9939#issuecomment-702991722 where `%n` consumes the preceding interpolation.

The VBAR is not special here. Without it, `%n` would swallow `Fred`.

I did some work on that PR, and will return to it shortly.

**Comment by smarter** [comment]
Closing as duplicate of  #9939 then
