### ISSUE TITLE
Private Super-Trait Inconsistency with 2.13

### ISSUE THREAD

**Issue by djspiewak** [lampepfl/dotty#13099]
## Compiler version

3.0.1

## Minimized code

```Scala
package foo

private[foo] trait Super {
  private[this] val dummy = "42"
}

trait Sub extends Super {
  def foo: Unit
}

// meanwhile, in another part of town

package bar

object Baz extends Sub {
  def foo = ()
}
```

## Output

Scala 2.13 compiles the above just fine. In 3.0.1, this will result in an error saying that class `Super` cannot be accessed in module `Baz`.

## Expectation

Consistency with 2.13.

**Comment by smarter** [comment]
Hmm, I just tried it (putitng packages foo and bar in separate files, and adding an `import foo._` in the second file) and I can't reproduce the issue: both joint and separate compilation of the two files succeeds. Can you give the exact steps needed to reproduce the issue?

**Comment by djspiewak** [comment]
This is what I get for being lazy with my minimization. I'll give you something more rigorous in a bit. Here's the unminimized reproduction: https://github.com/typelevel/cats-effect/runs/3095941607

**Comment by smarter** [comment]
based on the code in the corresponding PR, did you mean for `Super` to be an abstract class here?

**Comment by djspiewak** [comment]
Ah yes, it *is* a class and not a trait. Also can confirm that's the critical distinction here: swapping it to a trait seems to make 3.0.1 happy, whereas 2.13 is happy with both a trait and an abstract class.

**Comment by smarter** [comment]
Quoting from the spec (https://www.scala-lang.org/files/archive/spec/2.13/05-classes-and-objects.html#templates):
> It is possible to write a list of parents that starts with a trait reference, e.g. mt_1​ with ... with mt_n​. In that case the list of parents is implicitly extended to include the supertype of mt_1​ as the first parent type

In other words, when we write:
```scala
object Baz extends foo.Sub
```
because Sub is a trait whose parent class is Super, it gets expanded to:
```scala
object Baz extends foo.Super with Sub
```
which does not typecheck because foo.Super is inaccessible. So I think that the error is legitimate, and Scala 2 just happens to not check for accessibility here, so I'd say this is a bug in Scala 2 rather than Scala 3 (but this is also the option that requires the least amount of work for me, so I'm biased :)).

**Comment by djspiewak** [comment]
> which does not typecheck because foo.Super is inaccessible. So I think that the error is legitimate, and Scala 2 just happens to not check for accessibility here, so I'd say this is a bug in Scala 2 rather than Scala 3 (but this is also the option that requires the least amount of work for me, so I'm biased :)).

Sounds good to me!
