### ISSUE TITLE
"Reference to X is ambiguous" compiling Java code

### ISSUE THREAD

**Issue by ignasi35** [lampepfl/dotty#13106]
The Akka codebase includes some Java code resulting from code generation using `protoc` from `.protobuf` files. This Java code is kept under SCM (git) so it is not regenerated over and over.

A [particular protobuf file](https://github.com/akka/akka/blob/31f654768f86db68f4c22daa2cbd0bae28fc1fad/akka-persistence/src/main/protobuf/MessageFormats.proto) uses protobuf inner messages that result into generating inner classes when producing Java classes for the protobuf messages. Each of the generated classes includes a `Builder` inner class.

Compiling code that uses those `Builder` classes produces the following compiler error:

```
[error] -- [E049] Reference Error: /Users/ignasi/git/github/akka/akka/akka-persistence-scala3/akka-persistence/src/main/java/akka/persistence/serialization/MessageFormats.java:4113:16 
[error] 4113 |      protected Builder newBuilderForType(
[error]      |                ^^^^^^^
[error]      |            Reference to Builder is ambiguous,
[error]      |            it is both defined in object AtLeastOnceDeliverySnapshot
[error]      |            and inherited subsequently in class UnconfirmedDelivery
```

when compiling [this code](https://github.com/akka/akka/blob/31f654768f86db68f4c22daa2cbd0bae28fc1fad/akka-persistence/src/main/protobuf/MessageFormats.proto#L36-L46).
*NOTE*: this error is a sample, there are a few more identical to that one.

I already tried [compiling java sources first](https://www.scala-sbt.org/1.x/docs/Java-Sources.html) as suggested offline by some colleagues (@lrytz) but that workaround is not feasible in this particular codebase, unfortunately, since there are other parts of the build that require compiling Scala first. Using `Mixed` compile ordering doesn't work around the issue.

## Compiler version

3.0.1-RC1

## Minimized code

```Java
public final class MessageFormats {
    public  static final class AtLeastOnceDeliverySnapshot extends ... {
         public static final class Builder extends ... {
         }
         public  static final class UnconfirmedDelivery extends ... {
             public static final class Builder extends ... {
             }
             // code referring to `Builder` in this block will no longer 
             // compile in scala3
             @java.lang.Override
             protected Builder newBuilderForType(...) {
                  Builder builder = new Builder(parent);
                  return builder;
             }
             ...
         }
    }
}
```

Or probably smaller:

```java
public final class A {
  public static final class C { }
  public static final class D {
    public static final class C { }
    public C foo() { return new C(); }
  }
}
```

## Expectation

The compile can compile the Java code as it did in 2.13 and previous versions.

**Comment by odersky** [comment]
I can take a look at this

**Comment by lrytz** [comment]
See https://github.com/scala/scala/pull/5332 and https://github.com/scala/scala/pull/7671 for fixes in this area in scala/scala. At some point in the past, I think the strategy was to represent a Java class

```
class C {
  static class D
  D foo()
}
```

using an import

```
object C:
  class D
class C:
  import C._
  def foo(): D
```

but we changed this and now there is a java-specific lookup method `javaFindMember`. It seems dotty is using the "old" strategy.

**Comment by smarter** [comment]
> It seems dotty is using the "old" strategy.

No we actually ported that change: https://github.com/lampepfl/dotty/pull/12884

**Comment by lrytz** [comment]
Ah, OK. The imports seem to be there after parsing though:

```java
public final class A {
  public static final class C { }
  public static final class D {
    public static final class C { }
    public C foo() { return new C(); }
  }
}
```

```scala
object Test {
  def foo: A.D.C = (new A.D).foo()
}

```
$> sc3 A.java Test.scala -Xprint:parser
parsed:
package <empty> {
  object A() {
    <static> object C() {}
    final <static> class C private[this](x$1: _root_.scala.Unit) extends _root_.java.lang.Object {
      def <init>()
    }
    <static> object D() {
      <static> object C() {}
      final <static> class C private[this](x$1: _root_.scala.Unit) extends _root_.java.lang.Object {
        def <init>()
      }
    }
    final <static> class D private[this](x$1: _root_.scala.Unit) extends _root_.java.lang.Object {
      import D.*
      def <init>()
      def foo(): C = _root_.scala.Predef.???
    }
  }
  final class A private[this](x$1: _root_.scala.Unit) extends _root_.java.lang.Object {
    import A.*
    def <init>()
  }
}
```

**Comment by smarter** [comment]
I don't see them on master, so I assume you're using an older compiler.

**Comment by lrytz** [comment]
Allright, I tried 3.0.1

**Comment by smarter** [comment]
3.0.1 was branched more than six weeks ago so it's old news already ;)

**Comment by som-snytt** [comment]
sdkman is out of the loop.
```
➜  ~ sdk list scala
================================================================================
Available Scala Versions
================================================================================
 > * 3.0.0             * 2.12.10             2.11.6
   + 3.0.0-RC1           2.12.9              2.11.5
   + 3.0.0-M3          * 2.12.8              2.11.4
   + 3.0.0-M2          * 2.12.7              2.11.3
   + 3.0.0-M1          * 2.12.6            * 2.11.2
```
