### ISSUE TITLE
`other-new-features/transparent-traits.md` omits a line of code I think, and it's slightly confusing

### ISSUE THREAD

**Issue by GavinRay97** [lampepfl/dotty#13109]
https://github.com/lampepfl/dotty/blob/master/docs/docs/reference/other-new-features/transparent-traits.md

```scala
trait Kind
case object Var extends Kind
case object Val extends Kind
val x = Set(if condition then Val else Var)
```

> Here, the inferred type of x is `Set[Kind & Product & Serializable]` whereas one would have hoped it to be `Set[Kind]`. The reasoning for this particular type to be inferred is as follows:

...

> Here's an example that follows the lines of the code above, but now with a new transparent trait `S` instead of `Product`:

I think this was maybe meant to be:
```scala
trait Kind
trait Product
case object Var extends Kind, Product
case object Val extends Kind, Product
val x = Set(if condition then Val else Var)
```
But I'm not sure (otherwise would have just submitted a PR)

**Comment by aumann** [comment]
The example is probably as intended, as the compiler adds these traits automatically for case classes. It's probably easy to miss if one is not already familiar with this particular annoyance in scala 2, however, it is mentioned at the very top of the page:

> Some traits are used primarily in the first role, and we usually do not want to see them in inferred types. An example is the Product trait that the compiler adds as a mixin trait to every case class or case object.

**Comment by GavinRay97** [comment]
Ahh whoops, how embarassing. It sounded like a domain model so I thought it might have been erroneously lost in copy-pasting somehow.

My apologies, closing the issue and I learned something too!
