### ISSUE TITLE
No generic signature generated for type aliases

### ISSUE THREAD

**Issue by hamdiallam** [lampepfl/dotty#13103]
## Problem
Given

Scala 
```Scala
object Foo {
  type IntGetter = () => Int
  def getFunc(): IntGetter = () => 1
  def getFunc2(): () => Int = () => 1
}

```
The generic signatures generated (as seen using javap) are:
```Java
public static scala.Function0 getFunc();
public static scala.Function0<java.lang.Object> getFunc2();
```

Whereas in Scala 2 we get:
```java
public static scala.Function0<java.lang.Object> getFunc();
public static scala.Function0<java.lang.Object> getFunc2();
```

**Comment by Kordyjan** [comment]
I've tried to replicate your bug on the current master branch and failed. For me both methods look identical in the bytecode and have the same jvm signature (`<A:Ljava/lang/Object;>()LBoxed<TA;>;`). There are also no warnings when they are called from java. Can you provide the full java file that you see this problem in?

**Comment by smarter** [comment]
If `get` is defined as a val or var in a trait, this would be https://github.com/lampepfl/dotty/issues/6350

**Comment by hamdiallam** [comment]
will work on another repro case

**Comment by dwijnand** [comment]
> and Integer cannot be used here either for other reasons

Why can't Integer be used?  I've mentally built the model "scala.Int erases to int when it can, to Integer when it can't" (ignoring specialisation) - much like value classes.

**Comment by smarter** [comment]
> Why can't Integer be used?

It looks like it would require extra bridges: https://github.com/scala/scala/commit/e42733e9fe1f3af591976fbb48b66035253d85b9 (when generic signatures are available, javac uses them to derive the bytecode signatures it will emit in invoke\* instructions instead of just reading the actual bytecode signature written in the classfile, this complicates our job a lot).

**Comment by SethTisue** [comment]
@dwijnand ticket of record on this is https://github.com/scala/bug/issues/4214
