### ISSUE TITLE
FunctionalInterfaces should also transform non-SAMs for concistency.

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1310]
If we have a SAM that implements a `Function1[Int, Int]`, we currently rewrite it to have a specialized superclass(`JFunction1$mcII$sp` in particular).
This does not happen if the function is not a SAM.

From discussion with @VladimirNik.

**Comment by CucumisSativus** [comment]
Hey @DarkDimius I would be grateful if you cold elaborate in more detail, what should be done in scope of this issue (ofc if it's still valid)
