### ISSUE TITLE
No Manifest Available for String

### ISSUE THREAD

**Issue by romainreuillon** [lampepfl/dotty#13102]
## Compiler version

[reuillon:~/Projects/gridscale] master(+63/-57,1) ± scala3-repl --version       Scala code runner version 3.0.1 -- Copyright 2002-2021, LAMP/EPFL

## Minimized code

```Scala
manifest[String]
```

## Output

```
1 |manifest[String]
  |                ^
  |                No Manifest available for String.

```

## Expectation

A manifest for the type String

**Comment by Kordyjan** [comment]
For now, there is no support for summoning `Manifest` instances in scala 3. As a workaround for most use cases, you can use [ClassTag](https://dotty.epfl.ch/api/scala/reflect/ClassTag.html).

**Comment by Kordyjan** [comment]
Also, there was a discussion under https://github.com/lampepfl/dotty/issues/9482, which is sort of relevant.

**Comment by bishabosha** [comment]
We could keep this open as #9482 is about summoning `OptManifest`, this is for summoning `Manifest`, or we keep one?

**Comment by smarter** [comment]
let's close in favor of #9482, if we can do one we can do the other.

>  As a workaround for most use cases, you can use ClassTag.

In fact it's more than a workaround, please treat Manifest as deprecated and use ClassTag instead.
