### ISSUE TITLE
on GitHub, please distinguish full releases from prereleases

### ISSUE THREAD

**Issue by SethTisue** [lampepfl/dotty#13119]
GitHub Releases allows you to mark certain releases as being pre-releases:

<img width="666" alt="Screen Shot 2021-07-20 at 11 44 33 AM" src="https://user-images.githubusercontent.com/161079/126378539-68151483-dea1-4055-9c5e-733b09b94207.png">

currently in this repo this isn't being taken advantage of, so e.g. https://github.com/lampepfl/dotty/releases/tag/3.0.2-RC1 doesn't have this checkbox checked

@anatoliykmetyuk could checking this checkbox when appropriate be made part of the release process? it would help tooling such as https://github.com/dwijnand/scala-runners — @dwijnand and I hit this today as we were adding Scala 3 support there

**Comment by prolativ** [comment]
Actually this is something I discussed with @anatoliykmetyuk and I thought I had done this for 3.0.2-RC1 but maybe the change was not saved then. Thanks for pointing this out. I also marked the other RCs following 3.0.0 as pre-releases.

**Comment by SethTisue** [comment]
cool, thanks!
