### ISSUE TITLE
opaque type with wildcard unreducible application of higher-kinded type errror

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#13111]
Not completely sure this is an issue, since maybe there is an opaque type limitation I don't understand.

## Compiler version

3.0.3-RC1-bin-20210716-cc47c56-NIGHTLY

## Minimized code

```Scala
opaque type Foo[T] = Int
type F = Foo[?]
```

## Output

```scala
unreducible application of higher-kinded type Foo to wildcard arguments
```

## Expectation
No error.

**Comment by LPTK** [comment]
I don't think this is a bug. It's just the way wildcards don't work with abstract types (opaque types are kind of like abstract types). You get the same error with:

```scala
object Test:
  type Foo[T]
  type F = Foo[?]
```

Not sure anything can be done about this since Dotty does not support existentials.

**Comment by odersky** [comment]
@LPTK's diagnosis is correct.

**Comment by soronpo** [comment]
They may be like abstract types but they are not exactly like them, so the following codes are problematic:

* Seems redundant to define a type argument just to workaround this limitation
```scala
def fails(arg : Foo[?]) : Unit = {}
def works[Ignored](arg : Foo[Ignored]) : Unit = {}
```

* It's not possible to do in a macro `Type.of[Foo[?]]`, which makes constructing opaque types in macro a bit awkward.
