### ISSUE TITLE
Compiler error with covariant types

### ISSUE THREAD

**Issue by hamdiallam** [lampepfl/dotty#13126]
## Compiler version: 3.0.1

Apologies ahead of time if this title isn't the most descriptive. Not sure how else to describe this problem. This works fine in Scala 2

With the repro below, the compiler differentiates between the parameterized type of `Foo` and the parametrized type of `Bar` even though the `state` variable has been typed to the class's generic. 

## Problem

```Scala
trait State[+A]

case object Idle extends State[Nothing]
case class Bar[A](boxed: Boxed[A]) extends State[A]


class Boxed[+A](var a: A)

class Foo[A] {
  var state: State[A] = Idle
  
  def set(a: A): Unit = state match {
    case Idle =>
    case Bar(boxed) => boxed.a = a
  }
}
```

Emmitted error
```
Found:    (a : A)
Required: A$1

where:    A   is a type in class Foo with bounds >: A$1
          A$1 is a type in method set with bounds <: A
```

**Comment by smarter** [comment]
This is intentional: `A` is invariant in `Bar` but covariant in `State`, so all we know about `boxed.a = ...` is that its parameter type is some unknown type `A$1` which is a subtype of `A`. Scala 2 wrongly lets this compile which leads to crashes at runtime with code that typechecks:
```scala
trait State[+A]

case object Idle extends State[Nothing]
case class Bar[A](boxed: Boxed[A]) extends State[A]


class Boxed[A](var a: A)

class Foo[A] {
  var state: State[A] = Idle
  
  def set(a: A): Unit = state match {
    case Idle =>
    case Bar(boxed) =>
      boxed.a = a
  }
}

class Base
class Sub extends Base

object Test {
  def main(args: Array[String]): Unit = {
    val fy: Foo[Base] = new Foo[Base]
    val bz = new Boxed[Sub](new Sub)
    fy.state = new Bar(bz)
    fy.set(new Base)
    val sub: Sub = bz.a // ClassCastException: Base cannot be cast to Sub
  }
}
```
