### ISSUE TITLE
Leading infix operator doesn't respect outdent

### ISSUE THREAD

**Issue by SrTobi** [lampepfl/dotty#13138]
## Minimized code

Very unusual, synthetic example, but I still think it is handled wrongly:
```Scala
@main
def test() = println(x)

def x =
  def y =
    4
  + 3
```

## Output
Should print `3` but prints `()`

**Comment by odersky** [comment]
The `+` is intentionally treated like a leading infix operator here. I don't think we want to change this.

**Comment by som-snytt** [comment]
The space after the `+` is significantly significant. I like that it means leading infix is intended.

Intuitively, perhaps the indentation of the leading infix line should be the indentation of the token after the operator (if any).

Currently, leading infix is a kind of line continuation.

You expect the operands to "line up":
```
  def y =
    4
+ 3
  + 2
```
Under such a rule, the `+` could be in column 1, which looks like a weird DSL for `diff`.
```
  def y =
    "a"
+   "b"
-   "c"
```
That would also harmonize with
```
  def y =
    4
+
    3
```
where it is obvious that only the operator line gets a pass on indentation.

Note that "Odersky interpolation" syntax doesn't work as leading infix:
```
def y = "a "+ b +" c"
def y =
  "a "
+  b
+" c"
```
It would be an amazing accommodation of style to take the last concatenation as infix.

The spec is not currently consistent on outdent:
>if the first token on the next line is a leading infix operator. then its indentation width is less then the current indentation width, and it either matches a previous indentation width or is also less than the enclosing indentation width.

But the styling of the new `scala3/reference` pages is very nice, though I haven't found the dark mode button yet.
