### ISSUE TITLE
Bug with `-Ykind-projector` and `*` term

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#13141]
## Compiler version

* 3.0.1
* 3.0.2-RC1

## Minimized code

```scala
object A {

  class X { type Blah = Int }

  val * = new X

  val a: *.Blah = 2
}
```

## Output

```
[error] 7 |  val a: *.Blah = 2
[error]   |          ^
[error]   |          end of statement expected but '.' found
[error] one error found
```

## Expectation

Should compile. It does in Scala 3 without the `-Ykind-projector` flag.

**Comment by bishabosha** [comment]
@neko-kai would you like to do this?

**Comment by neko-kai** [comment]
@bishabosha I'll try to have a look this evening, but if I don't push a fix today, feel free to reassign because I won't have the time to look into this later.

**Comment by neko-kai** [comment]
@bishabosha Done in https://github.com/lampepfl/dotty/pull/13237 👍
