### ISSUE TITLE
ClassCastException at MethodType.resType

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#13151]
## Compiler version

3.0.1

## Minimized code

I hope root of this error is obvious. If not, ask and I will try to extract minimized example.
```Scala
${Expr.ofList(t.classSymbol.get.declaredMethods.map { methodSymbol =>
  val methodType = t.memberType(methodSymbol).asInstanceOf[MethodType]
  methodType.resType
}}
```

## Output

```scala
Exception occurred while executing macro expansion.
java.lang.ClassCastException: dotty.tools.dotc.core.Types$CachedExprType cannot be cast to dotty.tools.dotc.core.Types$LambdaType
	at scala.quoted.runtime.impl.QuotesImpl$reflect$LambdaTypeMethods$.resType(QuotesImpl.scala:2035)
```

**Comment by smarter** [comment]
If you use `asInstanceOf` instead of pattern matching in your code, you shouldn't be surprised that you get ClassCastExceptions, in particular here you're getting a crash because a method defined without any parameter list is a ByNameType, not a MethodType.
