### ISSUE TITLE
Remove JLine

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1316]
Should it be done? We're not really depending on it anymore thanks to Ammonite.

**Comment by kzys** [comment]
Like that? I'm gonna send a PR if the direction is fine.
https://github.com/kzys/dotty/commit/24c7ef7dfc44625de6f76f51f8ee838ec2956296

**Comment by kzys** [comment]
On -Xnojline, doesn't it make sense to just use `System.console()` instead of having the flag?
http://docs.oracle.com/javase/7/docs/api/java/lang/System.html#console%28%29

**Comment by felixmulder** [comment]
Hi @kzys - yes like that :) Would you mind making PR out of it?
