### ISSUE TITLE
Backtick identifiers don't work in destructuring assignments

### ISSUE THREAD

**Issue by GavinRay97** [lampepfl/dotty#13160]
## Compiler version

`3.0.3-RC1-bin-20210721-ec15557-NIGHTLY`

## Minimized code

```Scala
def example(string: String) =
  val len       							  = string.length
  val `middle letter index`                   = ((len - 1) / 2) + 1
  val (`left including middle letter`, right) = string.splitAt(`middle letter index`)
```

https://scastie.scala-lang.org/UpMEJHUNQE2EfAUrN0W59Q

![image](https://user-images.githubusercontent.com/26604994/127058105-ce6515d8-5a73-4448-9a7c-0c6ea88d264a.png)

## Output

`Not found: <backtick identifier>`

## Expectation

It works, or the compiler says `Backtick identifiers are not allowed in destructuring assignments` or similar

**Comment by Kordyjan** [comment]
Backticks identifiers have a special meaning in destructuring assignments, same way they have special meaning in pattern matching. They are not creating new values, but allow to reference other values from the scope.
Consider:
```scala
val left = 6
(5, 7) match
  case (`left`, right)     => ??? 
  case (newLeft, right) => ???
```
We will not enter the first match branch as `left` there is not new value but a reference to `val left = 6`, so the pattern match will fail as `5 != 6`.
Destructuring assignments has the same behaviour:
```scala
val left = 6
val (`left`, right) = (6, 7)
```
will be equivalent to just
```scala
val right = 7
```
while
```scala
val left = 6
val (`left`, right) = (5, 7)
```
will fail with `MatchError`.

**Comment by GavinRay97** [comment]
@Kordyjan Ah okay, I see what you mean
Do you think it's worth improving the error message, to prevent any future confusion about what's happening here?
