### ISSUE TITLE
Specification for synthesized unapply changed in dotty?

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1317]
With following code:
```Scala
case class A(i: Int)
```
The synthesized `unapply` is as follows:
``` Scala
def unapply(x$1: A): A = x$1
```
According to the scala specification, the return type should be `Option[Int]`, and scalac does that:
```Scala
case <synthetic> def unapply(x$0: A): Option[Int] = if (x$0.==(null))
      scala.this.None
    else
      Some.apply[Int](x$0.i);
```

**Comment by DarkDimius** [comment]
That's intended.

First of all, in `scalac` does not use synthesized unapply for pattern-matching over case classes. Case-classes are special-cased by pattern-matcher in `scalac` and it generates code that does not call them.

Second, in `dotty`, we implement scheme similar to https://github.com/scala/scala/pull/2848. It has several advantages: 
 - does not allocate options;
 - patmat does not need to special-case case classes to generate efficient code;

**Comment by DarkDimius** [comment]
The biggest difference is that instead of using `isEmpty` dotty uses `isDefined`. I'm not aware why.

**Comment by liufengyun** [comment]
Thanks a lot for explanation, it makes perfect sense.

**Comment by DarkDimius** [comment]
One more small note. If you'll be playing with how patmat works in `scalac`, do not test it on classes defined in `scala` package. It applies ad-hoc optimizations that are generally unsound.
