### ISSUE TITLE
REPL should report git-hash used to package the disrtibution

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1319]
Something similar to https://github.com/hmrc/sbt-git-stamp simplify implementing this.

**Comment by Jentsch** [comment]
Do you mean something like below?
```
Welcome to Scala.next (pre-alpha)  (OpenJDK 64-Bit Server VM, Java 1.8.0_112).
Build d60f89dc005b32c18f9daf22c923c6de3dd00155
Type in expressions to have them evaluated.
Type :help for more information.
```

**Comment by felixmulder** [comment]
@Jentsch - yes, please note that @krasinski was previously working on this and has a PR open with some more information.

I'm not sure if he's still working on this so maybe sync up a bit?

**Comment by krasinski** [comment]
I will submit the new solution tommorow
