### ISSUE TITLE
Dotty is slower than stripped down linker.

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1320]
This is more of a note to myself to continue investigation.

If I disable linker-specific phases in my fork, I get a version of dotc that is 1.6x faster to compile the following file than current dotty upsteam. 

``` scala
case class CC(a: Int, b: Object)
object Lists{
  def foo(x: Any): Int = {
    val (a, b) = x match {
      case CC(s @ 1, _) =>
        (s , 2)
      case _ => (42, 43)
    }
    a + b
  }
  def lists(x: Any): Int = {
    x match {
      case List(s @ 1) =>
        s
      case _ => 42
    }
  }
  def booleans(a: Object) = {
    val (b1, b2) = (a.isInstanceOf[CC], a.isInstanceOf[List[Int]])
    (b1, b2) match {
      case (true, true) => true
      case (false, false) => true
      case _ => false
    }
  }
 }
```

My fork it is also 20% faster to compile itself, than Dotty.

Linker is based on 9e95a6454a1ebbb2fc571b2a9bf72bf8f6281890(dated January) with changes to many phases. I assume that over last 6 month either I've introduced a substantial speedup in linker or dotty has received a substantial slowdown.

**Comment by odersky** [comment]
Probably the latter. Can the benchmarks help to investigate this?

On Tue, Jun 14, 2016 at 1:52 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> This is more of a note to myself to continue investigation.
>
> If I disable linker-specific phases in my fork, I get a version of dotc
> that is 1.6x faster to compile the following file than current dotty
> upsteam.
>
> case class CC(a: Int, b: Object)object Lists{
>   def foo(x: Any): Int = {
>     val (a, b) = x match {
>       case CC(s @ 1, _) =>
>         (s , 2)
>       case _ => (42, 43)
>     }
>     a + b
>   }
>   def lists(x: Any): Int = {
>     x match {
>       case List(s @ 1) =>
>         s
>       case _ => 42
>     }
>   }
>   def booleans(a: Object) = {
>     val (b1, b2) = (a.isInstanceOf[CC], a.isInstanceOf[List[Int]])
>     (b1, b2) match {
>       case (true, true) => true
>       case (false, false) => true
>       case _ => false
>     }
>   }
>  }
>
> My fork it is also 20% faster to compile itself, than Dotty.
>
> Linker is based on 9e95a64
> <https://github.com/lampepfl/dotty/commit/9e95a6454a1ebbb2fc571b2a9bf72bf8f6281890>(dated
> January) with changes to many phases. I assume that over last 6 month
> either I've introduced a substantial speedup in linker or dotty has
> received a substantial slowdown.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lampepfl/dotty/issues/1320>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAwlVmaJZ8pNtcdoZAJ_IQ_L9rpE33cpks5qLpXrgaJpZM4I1POd>
> .
>



-- 
Prof. Martin Odersky
LAMP/IC, EPFL

**Comment by DarkDimius** [comment]
the way it is tested. I've restarted the machine to clean all the caches and then:

1. read hotspot form HD
```
dark@reco ~/taps/patterns $ time javac
Usage: javac <options> <source files>
...
real	0m0.229s
user	0m0.188s
sys	0m0.039s
 ```
2. cold start of dotty linker:
```
dark@reco ~/taps/patterns $ time dotc CaseClasses.scala

real	0m1.633s
user	0m5.068s
sys	0m0.282s
```
3. cold start of dotty upstream:
```
dark@reco ~/taps/patterns $ time dotc2 CaseClasses.scala

real	0m2.264s
user	0m6.113s
sys	0m0.438s
```
4. cold start of scalac for comparison:
```
dark@reco ~/taps/patterns $ time scalac CaseClasses.scala // this is 2.11.8
CaseClasses.scala:19: warning: non-variable type argument Int in type List[Int] (the underlying of List[Int]) is unchecked since it is eliminated by erasure
    val (b1, b2) = (a.isInstanceOf[CC], a.isInstanceOf[List[Int]])
                                                      ^
one warning found

real	0m2.585s
user	0m7.739s
sys	0m0.395s

dark@reco ~/taps/patterns $ time scalac-2.12.0-M4 CaseClasses.scala
CaseClasses.scala:19: warning: non-variable type argument Int in type List[Int] (the underlying of List[Int]) is unchecked since it is eliminated by erasure
    val (b1, b2) = (a.isInstanceOf[CC], a.isInstanceOf[List[Int]])
                                                      ^
one warning found

real	0m3.483s
user	0m9.650s
sys	0m0.428s

dark@reco ~/taps/patterns $ time scalac-2.12.0-M4 -optimize CaseClasses.scala
CaseClasses.scala:19: warning: non-variable type argument Int in type List[Int] (the underlying of List[Int]) is unchecked since it is eliminated by erasure
    val (b1, b2) = (a.isInstanceOf[CC], a.isInstanceOf[List[Int]])
                                                      ^
warning: there was one deprecation warning; re-run with -deprecation for details
two warnings found

real	0m3.636s
user	0m12.803s
sys	0m0.575s
```

**Comment by smarter** [comment]
Something that can make benchmarking a bit more reliable is to always disable the intel turbo boost that which may or may not be enabled depending on the temperature of the processor, number of cores in use, etc. Under linux with a recent enough kernel:
```shell
echo 1 | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo
```

**Comment by lrytz** [comment]
good hint, googling for mac shows https://github.com/rugarciap/Turbo-Boost-Switcher
