### ISSUE TITLE
NoSuchMethod error when matching on a private inner class

### ISSUE THREAD

**Issue by hamdiallam** [lampepfl/dotty#13256]
## Minimized code
Scastie Link: https://scastie.scala-lang.org/AL4lT7w7RIuGUBPnhoCoTA

```Scala
object Monitor {
  def handle(exc: Exception, pf: PartialFunction[Throwable, Unit]): Unit = {
    pf.applyOrElse(exc, { (exc: Exception) =>
      ()
    })
  }
}

class Outer {
  private class MyExc extends Exception
  Monitor.handle(new MyExc, {
      case _: MyExc => println("here")
  })
}

object Main {
  def main(args: Array[String]): Unit = {
    new Test
  }
}
```

## Output (Runtime, not compile time)
```scala
java.lang.NoSuchMethodError: Test$MyExc.Test$MyExc$$$outer()LTest;
```

## Expectation
When the inner class is marked private, Dotty will not generate an `outer` method. Verified this in the byte code. Making `MyExc` public will have the outer method generated. However, even when private, the bytecode generated in the for the PartialFunctions `applyOrElse` needs access to the outer instance to when checking to `MyExc`

Works fine in Scala 2

**Comment by smarter** [comment]
Fixed in recent nightlies by https://github.com/lampepfl/dotty/pull/13124

**Comment by smarter** [comment]
(you can test the latest nightly by setting `scalaVersion := "3.0.3-RC1-bin-20210803-010f8de-NIGHTLY"`)

**Comment by hamdiallam** [comment]
Ah thanks, i'll double check the nightlies and issues before creating
