### ISSUE TITLE
[SemanticDB] Missing symbol occurrence for type annotation

### ISSUE THREAD

**Issue by tanishiking** [lampepfl/dotty#13270]
Missing symbol occurrence for an upper bound of the type parameter of class/trait/object definition.

## Compiler version
`v3.0.1`

## Minimized example

```Scala
class Foo[T <: Int]
```

## Output

```scala
class Foo/*<-example::Foo#*/[T/*<-example::Foo#[T]*/ <: Int]
```

For example, see: https://github.com/lampepfl/dotty/blob/49250915e0d28f3450f03d16a24c14577bc17562/tests/semanticdb/expect/i9782.expect.scala#L8

## Expectation

```scala
class Foo/*<-example::Foo#*/[T/*<-example::Foo#[T]*/ <: Int/*->scala::Int#*/]
```

## Possible solution
See:
- https://github.com/lampepfl/dotty/pull/12885#discussion_r673987228
- https://github.com/lampepfl/dotty/pull/12885#discussion_r684571086

**Comment by bishabosha** [comment]
I think this can be extracted by finding the matching type tree in the primary constructor
