### ISSUE TITLE
Rendering documentation with scaladoc should work offline

### ISSUE THREAD

**Issue by hamdiallam** [lampepfl/dotty#13272]
## Compiler version 3.0.2-RC1

The scaladoc generator requires network access. This is not good for CI machines that run jobs with commands like `publishLocal` without network access. The exception originates from `renderResources` [here](https://github.com/lampepfl/dotty/blob/master/scaladoc/src/dotty/tools/scaladoc/renderers/Resources.scala#L188).

## Expectation
Ability to generate docs without network access

**Comment by smarter** [comment]
Looks like scaladoc tries to fetch a few js files: https://github.com/lampepfl/dotty/blob/38b983c1b4a61d4c45f314ae895b95317c322c62/scaladoc/src/dotty/tools/scaladoc/renderers/Resources.scala#L95-L99. Could we instead store these files in the scaladoc jar? We'd have to check their licenses to make sure the result can be redistributed under Apache v2 first. /cc @romanowski

**Comment by pikinier20** [comment]
3rd party libraries are not fetched during generation. They are included to HTMLs using URL to remote location. The real reason of this exception is fetching Inkuire from Github because Inkuire.js file needs to be locally in generated documentation. The solution is to have inkuire.js packed in scaladoc jar.

**Comment by BarkingBad** [comment]
We should not require inkuire.js when there is no `-Ygenerate-inkuire` flag provided, so I think we should fix it there, not by providing inkuire.js to the jar

**Comment by smarter** [comment]
I think including inkuire.js in the jar would also be fine, although indeed that's less important as long as inkuire is not enabled by default.
