### ISSUE TITLE
Opaque alias for case class is accessible outside of defining class 

### ISSUE THREAD

**Issue by mheiber** [lampepfl/dotty#13281]
## Compiler version

3.0.0

## Minimized code

```Scala
object Example:
   case class Thing(val s: String)

   object Foo:
      opaque type Opaque = Thing
      opaque type Log = Double

   class Test:
      def unThing(t: Foo.Opaque): String = t match {
         case Thing(s) => s // OK, but expected error
      }

      def unLog(log: Foo.Log): Unit = log match {
         case 2.0 => () // Correct error: Values of type Double and Foo.Log cannot be compared with == or !=
      }

```

## Output

The pattern match in `unThing` does not error

## Expectation

The pattern match in `unThing` errors, like the pattern match in `unLog`

**Comment by som-snytt** [comment]
You can pattern match against values you don't have much type info about, such as `Any`. The second example errors because it is an equality check `2.0.equals`.

**Comment by mheiber** [comment]
@som-snytt thanks for explaining, closing the issue
