### ISSUE TITLE
Compiler does not allow to define top-level method and class with the same name

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#13283]
Hey, here's the next blocker for compilation Scala Native in Scala 3 without changing API. In Scala 2 these two definitions were placed in different files but inside the same package. For Scala 3 I've moved them to the same file as the compiler suggests. 

## Minimized code

```Scala
//file `extern.scala`
package scalanative.unsafe
def extern: Nothing = ??? // Intrinsic method replaced inside compiler plugin
final class extern(v: String = "") extends  scala.annotation.StaticAnnotation

// file foo.scala
import scalanative.unsafe._
@extern
object Ext{
  def foo: Boolean = extern
}
```

## Output

```scala
[error] -- [E161] Naming Error: .../scalanative/unsafe/extern.scala:8:4 
[error] 8 |def extern: Nothing = ???
[error]   |^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |extern clashes with class extern in .../scalanative/unsafe/extern.scala; the two must be defined together
[error] -- [E007] Type Mismatch Error: .../foo.scala
[error] 16 |    extern
[error]    |    ^^^^^^
[error]    |    Found:    scalanative.unsafe.extern.type
[error]    |    Required: Boolean
```

## Expectation

The compiler should allow defining class and top-level method in the same package, both top-level method and class can have empty arguments list or be parameter-less definitions.

**Comment by odersky** [comment]
I tried to avoid the conflict, but when I compile `foo.scala` separately I then get:
```
@extern
  |^
  |Toplevel definition extern is defined in
  |  /Users/odersky/classes/scalanative/unsafe/extern$package.class
  |and also in
  |  /Users/odersky/classes/scalanative/unsafe/extern.class
  |One of these files should be removed from the classpath.
```
And the compiler is right here. It is a true ambiguity. Package objects are invisible and their contents are looked up together with the contents of the enclosing package. So it's like you define
```
   object extern
   def extern = ???
```
That will also be a double definition.

So I don't think there's anything to be done here.

**Comment by dwijnand** [comment]
But isn't the fact that `@` is only for classes relevant here?  You're looking for the type `extern`, not any term `extern`, whether that term is an object or a def, no?

```scala
scala> object externObj
// defined object externObj

scala> @externObj object Ext
1 |@externObj object Ext
  | ^^^^^^^^^
  | Not found: type externObj
```

**Comment by odersky** [comment]
> But isn't the fact that @ is only for classes relevant here? You're looking for the type extern, not any term extern, whether that term is an object or a def, no?

It might be too eager in issuing the error, but it will get you for sure on the line reading
```scala
 ... = extern
```
Here there's no escape. `extern` has a companion object (because it has a default argument) and that will clash with the `extern` method.

**Comment by dwijnand** [comment]
> `extern` has a companion object (because it has a default argument)

Ah, that's why it wants the def in the same file as that class.  So the issue is "Compiler does not allow to define top-level method and class with the same name and default arguments".

Should a top-level method suppress the synthetic object?  That way the user in this situation gets a chance to define `def extern` as of type Nothing rather than it be of type extern.type.

**Comment by WojciechMazur** [comment]
Originally extern annotation had no arguments. I wanted to work around problems and passed the wrong example instead. 
Here're links to original Scala 2 sources that were working fine: 
* [exern annotation](https://github.com/scala-native/scala-native/blob/master/nativelib/src/main/scala/scala/scalanative/unsafe/extern.scala)
* [extern method](https://github.com/scala-native/scala-native/blob/28345bb1f6161690dc23ce6d26feba529781ff67/nativelib/src/main/scala/scala/scalanative/unsafe/package.scala#L153)

In Scala 2 these 2 definitions were in the separate files, compiler suggested that they `must be defined together`, so I did, but they still were failing.
