### ISSUE TITLE
Split method doesn't work with string interpolation and special symbols

### ISSUE THREAD

**Issue by micosu** [lampepfl/dotty#13293]
## Minimized code

```Scala
scala> val str = f"random\n"
val res0: String = random\n
scala> val str.split("\n")
val res1: Array[String] = Array(random\n)
```

## Expectation
The split method should remove the `\n` at the end of the string, but with Scala's string interpolation in Scala 3 the split method does not properly remove some special symbols

**Comment by som-snytt** [comment]
Duplicates https://github.com/lampepfl/dotty/issues/11750 where f-interpolator doesn't attempt to process escapes.

I have a PR to submit for the f-interpolator issues, forthcoming shortly. Thanks for the ticket, sorry for delayed fix.
