### ISSUE TITLE
I can not get Scala 3 working on a Raspberry Pi

### ISSUE THREAD

**Issue by FLRF** [lampepfl/dotty#13318]
## Compiler version
Scala 3 (any)
metals (in VS Code), sbt, apt-get, Coursier
JDK11
Raspberry Pi 4, Raspberry PI OS (aka Raspbian) - a 32bit ARM linux OS

JDK11, VS Code,  install successfully 
 Metals (for VS Code) installs but does not function (can highlight scala, but not compile)
 Coursier does not successfully install scala - but gives not error.
 apt-get has only Scala 2.11 available
 sbt does not install successfully.
 
 Reason:
 There does not appear to be any Scala 3 for ARM binaries.
 The scripts (apt-get, coursier, sbt, wget etc have not been configured for Raspberry Pi (or any ARM machine)
 At the very least they should provide an error:
 "You can not run Scala 3 on an ARM processor yet. no binaries are available"
 
 Solution:
1)  Compiling Scala 3 for ARM
2) including it in the common repos and providing the scripts (coursier, sbt, wget, apt-get) as well as Metals
so that Scala 3 can be installed on a variety of ARM systems (Raspberry Pi, Android, Mac, iOS etc)

**Comment by SethTisue** [comment]
there aren't "Scala 3 binaries", per se — both Scala 2 and 3 are distributed as platform-independent JAR files

your goals are definitely valid, but the situation probably isn't actionable here in this repo — you'll probably need to open tickets in the particular repos where support is missing

at least one such ticket already exists, namely https://github.com/sbt/sbt/issues/6614

**Comment by dwijnand** [comment]
You can try installing https://github.com/dwijnand/sbt-extras, which will work on JDK 11.
