### ISSUE TITLE
Testing with checkfiles is not working for tests in subdirectory

### ISSUE THREAD

**Issue by noti0na1** [lampepfl/dotty#13325]
The "run“ tests with checkfiles are not working when the test files are placed in subdirectories.

Test `tests/run/trailingCommas/trailingCommas.check` is affected, becasue it always successes.

## Compiler version

3.1.0-RC1-bin-SNAPSHOT-nonbootstrapped-git-567787f

## Minimized code

Create a folder `test-checkfiles` in `test/run`,

`test/run/test-checkfiles/testCheck.scala`
```Scala
@main def Test = println(1)
```

`test/run/test-checkfiles/testCheck.check`
```Scala
2

```

## Run

```
$ testCompilation test-checkfiles
```

## Expectation

The test run is expected to fail, but successed.

**Comment by dwijnand** [comment]
> ## Expectation
> The test run is expected to fail, but successed.

Where does that expectation come from?  A `test/run/test-checkfiles/testCheck.scala` file is picked up by:

https://github.com/lampepfl/dotty/blob/26a27cbae68108cf673a309d84d4d0a0cd6608dc/compiler/test/dotty/tools/dotc/CompilationTests.scala#L202

and `compileFilesInDir` documents the path of the optional, associated checkfile is:

https://github.com/lampepfl/dotty/blob/110e5cbab5f808532fc92093521e71d3c93574a9/compiler/test/dotty/tools/vulpix/ParallelTesting.scala#L1219-L1222

**Comment by noti0na1** [comment]
@dwijnand 
If I rename the checkfile to `test-check.check`,  the test still successed.

**Comment by dwijnand** [comment]
> If I rename the checkfile to `test-check.check`, the test still successed.

That's because it needs to be called `test/run/test-checkfiles.check`, instead.

> I am able to change the checkfile of `trailingCommas` to random content, the test still successes.

Similarly, that file is wrong (and committed! 😞 ).  It should be `tests/run/trailingCommas.check`.

**Comment by noti0na1** [comment]
Thanks, I can make a pr to rename the test file.
