### ISSUE TITLE
Symbol.fullName is inconsistent with JVM class name for nested objects

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#13321]
## Compiler version

3.0.1

## Minimized code

```Scala
import scala.quoted._
object Macro:
  inline def apply[A]: Unit = ${impl[A]}

  private def impl[A: Type](using Quotes): Expr[String] =
    import quotes.reflect._
    val t = TypeRepr.of[A]
    println(t.classSymbol.get.fullName)
    Expr("")
```
```Scala
object Foo:
  object Boo

object Main:
  def main(args: Array[String]) =
    Macro[Foo.Boo.type]

```

## Output

```scala
Foo$.Boo$
```

## Expectation
Correct runtime name for Foo.Boo:
```
Foo$Boo$
```

**Comment by dwijnand** [comment]
I don't see how the expectation is justified.  Here's the docs for `fullName`:

https://github.com/lampepfl/dotty/blob/3be078dfd06d0438cfaea44632947b7ec3b676ac/library/src/scala/quoted/Quotes.scala#L3485-L3486

Which gives no guarantees in regards to the runtime names.
