### ISSUE TITLE
Summoning Mirror for ADT defined in trait

### ISSUE THREAD

**Issue by TimWSpence** [lampepfl/dotty#13332]
## Compiler version

scala-3.1.0-RC1-bin-20210817-f27c250-NIGHTLY (I tried  to use the most recent I could find as I thought there's a chance that https://github.com/lampepfl/dotty/pull/11686 might have fixed this as it's in a similar area. Not entirely sure if that made it into this nightly or not)

## Minimized code

```Scala
import scala.deriving.Mirror

class Scope extends IListDefn {

  type Of = Mirror { type MirroredType[X] = IList[X]; type MirroredMonoType = IList[Any] ; type MirroredElemTypes[_] <: Tuple }

  val M = summon[Of]
}


trait IListDefn {
  sealed trait IList[A]
  case class INil[A]() extends IList[A]
  case class ICons[A](h: A, t: IList[A]) extends IList[A]
}
```

## Output

```scala
[error] -- Error: /private/tmp/scala/Minimization.scala:7:20 ---------------------------
[error] 7 |  val M = summon[Of]
[error]   |                    ^
[error]   |no implicit argument of type Scope.this.Of was found for parameter x of method summon in object Predef
[error] one error found
```

## Expectation
Compilation should succeed (and does if you move the `IList` definition out of the trait and up to top-level)

**Comment by bishabosha** [comment]
workaround is to give a companion object to `IList`. Otherwise e.g. the child `INil` fails the accessibility test for generating a `Mirror` type, perhaps that test is too restrictive in some cases

**Comment by TimWSpence** [comment]
Thanks @bishabosha! Unfortunately this is ultimately for https://github.com/typelevel/kittens where we summon `Mirror` instances via shapeless 3 for typeclass derivation so we have no control over how users define their ADTs.

**Comment by milessabin** [comment]
@bishabosha is there any chance we could tweak the accessibility test before 3.1?

**Comment by odersky** [comment]
Yes, for the moment this is simply out of spec. We generate mirrors only for statically accessible classes. I would advise to go slowly here and make absolutely sure that each generalization step can be made without negative consequences.

**Comment by joroKr21** [comment]
Not sure how that's related to accessibility - it sounds like incorrect handling of prefixes when generating a mirror. In general I think Scala users expect nesting to just work in most cases. Restricting certain features to only statically accessible symbols sounds very hard to explain.

**Comment by joroKr21** [comment]
I think if we look for a mirror of `foo.bar.baz.Qux` from `foo.bar.x.y.` then the path should be `bar.baz.Qux` - i.e. go up the owner chain until you reach a common owner - if it's static of course you can shortcut to the fully qualified name.

**Comment by bishabosha** [comment]
> I think if we look for a mirror of `foo.bar.baz.Qux` from `foo.bar.x.y` then the path should be `baz.Qux` - i.e. go up the owner chain until you reach a common owner - if it's static of course you can shortcut to the fully qualified path.

I am trying this is #13502, I still need to test in more cases

**Comment by joroKr21** [comment]
We can dig out some test cases from Shapeless 2 or Magnolia for Scala 2
