### ISSUE TITLE
Remove "Edit this page on GitHub" from outdated doc pages

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#13355]
from this comment: https://github.com/lampepfl/dotty/pull/13327#issuecomment-903543077

leaving the "Edit this page on GitHub" link on the docs, e.g. at https://dotty.epfl.ch/docs/reference/other-new-features/export.html will lead to more PR's being generated here

**Comment by BarkingBad** [comment]
I don't know if this will be valid after merging #13350 because we will not generate static docs anymore, just preprocess the subset for docs.scala-lang website

**Comment by julienrf** [comment]
We need this before we can merge #13350
