### ISSUE TITLE
Patmat: dotty does not generate null checks for extractors

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1335]
```scala
object Test {
 case class MyTuple(a: Int, b: Int)
 def foo = MyTuple(1,2)
 def main(args: Array[String]): Unit = {
   val MyTuple(a,b) = null // should throw MatchError. Throws NPE instead.
   println(a + b)
 }
}
```
Scala2 style option-based pattern matching is handled correctly. This bug only happens with option-less pattern matching.

**Comment by DarkDimius** [comment]
This is a low-hanging fruit that may be a good introduction into PatternMatcher.

**Comment by jvican** [comment]
This code snippet doesn't compile in Scala:
```
<console>:15: error: constructor cannot be instantiated to expected type;
 found   : Test.MyTuple
 required: Null
          val MyTuple(a,b) = null
```
  
In my opinion, this shouldn't typecheck, while the following should both typecheck and throw a `MatchError` as @DarkDimius said:
```scala
object Test {
 case class MyTuple(a: Int, b: Int)
 def foo = MyTuple(1,2)
 def main(args: Array[String]): Unit = {
   def bla: MyTuple = null // this is probably gonna be defined in another scope
   val MyTuple(a,b) = bla // should throw MatchError. Throws NPE instead.
   println(a + b)
 }
}
```
  
Is there any way we can make the proposed code snippet fail to typecheck? I'm planning to make Dotty throw a MatchError in my code snippet.
