### ISSUE TITLE
Basic option processing is still broken for REPL

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#13443]
## Compiler version

3.1.0-RC1-bin-SNAPSHOT

## Minimized code

```Scala
✗ ./bin/scala -source 3.0-migration
Exception in thread "main" java.nio.file.NoSuchFileException: -source
```

## Output

```scala
// As shown.
```

## Expectation

Processing command line options for the compiler, with additional REPL-specific options.

**Comment by BarkingBad** [comment]
Did it work well for Scala2 or before changing the scala runner from shell script to scala script (https://github.com/lampepfl/dotty/pull/13081)? I know why it fails and an idea of how to fix it

**Comment by bjornregnell** [comment]
A workaround: add `-repl` as a last arg works i some situations.

**Comment by bjornregnell** [comment]
:tada:
