### ISSUE TITLE
Browsing to source files of 'bootstrapped' lib types in scaladoc fails with 404

### ISSUE THREAD

**Issue by DieBauer** [lampepfl/dotty#13488]
When clicking the source link in a scaladoc page of the collections
For example https://scala-lang.org/api/3.0.2/scala/collection/immutable/LazyList.html 
Or some other type that is 'bootstrapped' like https://scala-lang.org/api/3.0.2/scala/beans/BooleanBeanProperty.html fails to resolve. 

The link goes to https://github.com/lampepfl/dotty/blob/3.0.2/out/bootstrap/stdlib-bootstrapped/scala-3.0.3-RC1-bin-SNAPSHOT-nonbootstrapped/src_managed/main/scala-library-src/scala/collection/immutable/LazyList.scala#L240 
which gives a 404.

**Comment by BarkingBad** [comment]
https://scala-lang.org/api/3.0.2/scala/collection/immutable/LazyList.html (and all other 2.13.16 sources) should work now. Please check. If not, please hard refresh your browser in case it cached some results.
