### ISSUE TITLE
REFINEDtype rhs in TASTy format does not correspond to reality

### ISSUE THREAD

**Issue by cache-nez** [lampepfl/dotty#13506]
TASTy format specifies

> `REFINEDtype    Length underlying_Type refinement_NameRef info_Type`

however, the TreePickler first pickles the name, switching the order of `underlying_Type` and `refinement_NameRef`.

**Comment by smarter** [comment]
Thanks for the report, would you mind making a PR fixing the documentation?

**Comment by cache-nez** [comment]
@smarter I could fix the grammar, but I think the grammar has a more reasonable order: parent, refinement name, refinement type (compare: refinement name, parent, refinement type). 
On the other hand, fixing the pickler + unpickler changes the TASTy format, which might also touch other areas I'm not aware of. That fix I am not sure how to proceed with.

**Comment by smarter** [comment]
Changing the pickler/unpickler would be a breaking change requiring us to bump our version to 3.2 and to keep a special case in the unpickler to handle existing tasty files produced by older versions of the compiler, so it's much simple to just change the grammar even if it looks a bit weird :).
