### ISSUE TITLE
Java style enum does not define values method with parentheses

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#13500]
## Compiler version

3.0.2

## Minimized code

```Scala
enum Foo extends Enum[Foo] {
  case A, B, C
}
assert(Foo.values()(2) == Foo.C)
```

## Output

```scala
-- Error:
4 |assert(Foo.values()(2) == Foo.C)
  |       ^^^^^^^^^^^^
  |missing argument for parameter i of method apply in class Array: (i: Int): Foo
```

## Expectation

If we follow the idea that Java style enums should have the exact same API as if they were compiled by Java, then this should also compile (as all Java methods must be defined with parentheses).

**Comment by smarter** [comment]
I don't think we can change this anymore in Scala 3 since it would tasty compatibility.

**Comment by bishabosha** [comment]
> I don't think we can change this anymore in Scala 3 since it would break tasty compatibility.

indeed, it crashes in the TreeUnpickler: https://github.com/lampepfl/dotty/issues/13501
