### ISSUE TITLE
Math.signum returns float, not int

### ISSUE THREAD

**Issue by Prosfilaes** [lampepfl/dotty#13508]
## Compiler version

3.01

## Minimized code

scala> Math.signum (1)                                                                                                                                                                        
val res0: Float = 1.0

scala> java.lang.Integer.signum (1)
val res1: Int = 1

## Expectation
https://www.scala-lang.org/files/archive/api/3.0.1/scala/math.html says "def signum(x: Int): Int Forwards to java.lang.Integer", but Math.signum (1) is actually returning a float.

**Comment by griggt** [comment]
`Math` (upper case 'M') is `java.lang.Math`, which has only `public static double signum(double d)` and `public static float signum(float f)`

`math` (lower case 'm') is `scala.math`, which has `def signum(x: Int)` among other overloads

```
Welcome to Scala 3.1.0-RC1 (1.8.0_292, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> Math.signum(1)
val res0: Float = 1.0

scala> math.signum(1)
val res1: Int = 1
```
