### ISSUE TITLE
Decide when we should do exhaustivity checks

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1351]
scalac only checks sealed classes. We should consider if we indeed want to change this.
https://github.com/lampepfl/dotty/pull/1261/files#diff-3fbc86b62f6455f297c02b6711bc66b1R470

In case we indeed decide to change it, I propose to maintain scalac compatible behavior in -language:Scala2 mode.

**Comment by liufengyun** [comment]
Follow the same approach as in scalac for now.

**Comment by liufengyun** [comment]
This is done in the #1364
