### ISSUE TITLE
Typer: Incorrent assumtions when typing pattern matches

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1352]
Typer assumes that pattern matching in only doing dowcasts and rejects this valid code. This code is accepted by scalac:

```scala
trait A
trait B

abstract sealed class Parent
class Foo extends Parent with A
class Bar extends Parent with B

(null: Parent) match {
  case (_: A) | (_: B) => // dotty complains here that neither A or B are subtypes of Parent
}
```

**Comment by DarkDimius** [comment]
Decided that: 
1. we do not want to substantially change the current behaviour
2. we would like to have a simplistic mode for -languge:Scala2 that typechecks the subpattern with either lub or some parent type as expected type.

**Comment by odersky** [comment]
I just looked at it. Typer accepts this code. The error gets raised by IsInstanceOfEvaluator. Reassigning to Felix.
