### ISSUE TITLE
TastyFormat: the only toplevel stat should be package

### ISSUE THREAD

**Issue by cache-nez** [lampepfl/dotty#13522]
Right now, TastyFormat allows any stat (import, export, typedef, valdef, defdef and any term) to be toplevel in a file. However, in practice stats are always contained in a package. Unless this is supposed to change, we should make the grammar more precise and specify package as the only toplevel stat.

Let me know if there are cases I missed.

**Comment by bishabosha** [comment]
the current implementation in the compiler treats the TASTy that is produced for spliced quotes as a top level statement, and those are trees of expressions

**Comment by nicolasstucki** [comment]
In that situation, we can have the tree of an arbitrary expression or the tree of an arbitrary type.

**Comment by nicolasstucki** [comment]
It is also possible that at some point we might generate TASTy with a pattern or a definition inside. So I would level it is.
