### ISSUE TITLE
PatMat & exhastivity spec OrTypes

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1354]
How should this compile? Is the pattern exhaustive? Does it have unreachable cases?

```scala
object A {
  def foo(a: Int | Double) = a match {case a: (Float | Boolean) => 1}
  def fooUnsafe(a: Int | Double) = a.isInstanceOf[ Float | Boolean] // is it true or false?
}
```

**Comment by DarkDimius** [comment]
had a discussion, decided that:
1. the pattern is not exhastive in the single case is dead code
2. method should return false

**Comment by liufengyun** [comment]
If I were right, the key to solve this problem here is to translate `x.isInstanceOf[T1 | T2]` to `x.isInstanceOf[T1] | x.insInstanceOf[T2]` before type erasure?
