### ISSUE TITLE
Matching on java enum in dotty.tools.dotc.Run breaks run/dotc test.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#1355]
Discovered on this issue [pattern match](https://github.com/lampepfl/dotty/pull/1345/files#diff-54ef0a9755f17d82ce13623136430519R142). `run/dotc` fails if the `toString` is removed and the references to the enums are added in the cases. The same happens if the enums are compared directly with reference equality.

**Comment by nicolasstucki** [comment]
This might be a bug with pickling.

**Comment by odersky** [comment]
Can you provide a minimized test case?

**Comment by nicolasstucki** [comment]
I could not reduce it much, but I have here is a [branch](https://github.com/dotty-staging/dotty/commit/4f8c29b70e63d3cc164a7a077e484812f9b342b6) where it can be reproduced easely. 
Need to execute `sbt test` and test `dotc.tests.tasty_dotc_util` will fail. `before-pickling.txt` and `after-pickling.txt` will be generated.

**Comment by smarter** [comment]
Can you put both files and the diff in a gist for convenience?

**Comment by nicolasstucki** [comment]
Here is the gist with the output files.
https://gist.github.com/nicolasstucki/d76d2bfb5434f9441df4c47db5e51799

**Comment by odersky** [comment]
Closing since there's no minimized test case
