### ISSUE TITLE
Possible bug: intransitive type equality

### ISSUE THREAD

**Issue by kubukoz** [lampepfl/dotty#13555]
## Compiler version

3.0.2, 3.1.0-RC2

## Minimized code

```Scala
import scala.util.NotGiven

case object Obj

def handle[x](req: x): Any = req match {
  case a: Obj.type =>
    summon[a.type =:= Obj.type]
    summon[a.type <:< (x & Obj.type)]

    //but...
    //Obj isn't even an `x`
    summon[NotGiven[Obj.type <:< x]]

  case other => ()
}

```

## Output

Code compiles

## Expectation

`Obj.type <:< x` is a given - `a.type` is equivalent to `Obj.type`, so its subtyping relationship with `x` should be preserved

Update: I think this is related to https://github.com/lampepfl/dotty/issues/9510.

**Comment by kubukoz** [comment]
Similar case, although with a different way to pattern match:

```scala
import scala.util.NotGiven

case object Obj

def handle[x](req: x): Any = req match {
  case a @ Obj =>
    summon[NotGiven[Obj.type <:< a.type]]
    summon[NotGiven[a.type <:< Obj.type]]

    summon[a.type <:< x]
    summon[NotGiven[Obj.type <:< x]]

  case other => ()
}
```

This also compiles - looks like `Obj.type` and `a.type` are completely unrelated.

**Comment by smarter** [comment]
`summon[NotGiven[A <:< B]]` succeeding doesn't mean "`A` isn't a subtype of `B`" it means "I can't prove that `A` is a subtype of `B`", and yeah in general the subtyping check can fail when the subtyping relationship between A and B rely on transitivity since it's impossible for the compiler to go check if there exists an X among all possible types such that `A <:< X` and `X <:< B`.

**Comment by smarter** [comment]
Concerning `case a @ Obj`, it desugars into `if Obj.equals(x) then { val a = x; ... }`, so it isn't in fact guaranteed to be the same singleton type.

**Comment by smarter** [comment]
(because equals can be overridden)

**Comment by kubukoz** [comment]
This is why we can't have nice things 😅 thanks for the explanation.
