### ISSUE TITLE
Proper infrastructure for testing reported errors\warnings

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1356]
https://github.com/lampepfl/dotty/pull/1261/files#diff-0dffcbbb85984df42a7e959859af6e5aR39
introduces the infrastructure specifically for exhaustivity checks in pattern matching.

It would be nice to have a common infrastructure for whole compiler.

The version that I propose to implement is:
- define a `Diagnostic.raw` method that is used to print the part of diagnostic that should participate in unit tests. Egg: `CallInNonTailrecPosition([324..346])`  where numbers are positions
- make a reporter that collects instead of printing a nice message prints the `raw` message. 
- use it during unit tests.

This should make the error reporting be robust against typos in error messages and make error messages translatable to other languages.

@adriaanm @lrytz @retronym, would you mind giving advice and sharing your experience on the topic?

**Comment by liufengyun** [comment]
Now we already have `TestReporter.simplifiedReporter` and `-Xfatal-warnings`.

Note that for exhaustivity check it cannot depend on `-Xfatal-warnings`, as it need to check that the counter-examples generated by the algorithm match the expected result.
