### ISSUE TITLE
Extension method included in the namespace of the enclosing object

### ISSUE THREAD

**Issue by cquiroz** [lampepfl/dotty#13602]
## Compiler version

3.0.1

## Minimized example

```Scala
object U:
  extension(i: Int)
    def b = 3

object M:
  def t(b: String): String =
    import U._
    b
```

## Output

```scala
[error] -- [E049] Reference Error: /Users/cquiroz/code/spire/core/src/main/scala-3/spire/syntax/Syntax.scala:823:4
[error] 823 |    b
[error]     |    ^
[error]     |    Reference to b is ambiguous,
[error]     |    it is both defined in method t
[error]     |    and imported subsequently by import spire.syntax.U._

```

## Expectation
I didn't expect the `b` extension method to become parte of the object namespace. I'm not sure if this is according to spec but it seems odd to me

**Comment by bishabosha** [comment]
extension methods can be called as ordinary methods, such as `U.b(someInt)`, but maybe they can have lower priority in case of ambiguity?

**Comment by odersky** [comment]
> extension methods can be called as ordinary methods, such as U.b(someInt), but maybe they can have lower priority in case of ambiguity?, or only be called in prefix form if they are selected from their owner

No, there are no such rules. The error is legitimate.
