### ISSUE TITLE
Code completion not working for annotations

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#13624]
## Compiler version

3.1.0-RC2

## Minimized code

In a REPL session:

```Scala
@annotation.implicitNot
```

and press TAB (or invoke code completion in IDE)

## Output

No completions are suggested

## Expectation

Code completion should work for annotations (both in their prefix form, e.g. `@foo class Bar`, and in the suffix form, e.g. `1: @foo`).
In the particular case above the code should expand to `@annotation.implicitNotFound`

**Comment by tgodzik** [comment]
This should now be fixed based on #13834 and #13834
