### ISSUE TITLE
Include heartbeat\stats using linker in CI

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1363]
Together with @odersky we just hunted a 20x slowdown in subtyping by using `-Yheartbeat`.
The slowdown was showcased by Linker as it performs huge number of subtyping tests on complex types. Using `-Yheartbeat` we were able to find increase of number of '&' from 60K to 67'596K. Ie more than 1000 times increase.

@odersky was able to fix it using a single line. Thanks a lot! 🙇 
It would be nice to track this in future, as this may have been the reason of #1320. It allowed to reduce time needed to typecheck stdlib from 15 to 11 seconds. Based on this I propose to include Linker-defined metrics in regression suite.

**Comment by DarkDimius** [comment]
The commit I'm referring to is c676d7d7908f1b021d9333f7394963c4c62a1009..82c002688537274f35aa49ac5efc8e13c8583498.

**Comment by DarkDimius** [comment]
Agreed to implement this.

**Comment by liufengyun** [comment]
I agree it's good to add more minuscule benchmarks that can provide insights about what might be wrong.

To make that benchmarks useful, what we are missing is a regression benchmark platform that seamlessly integrated with PR & commits. I've done a little search, there's no similar services like travis-ci for regressional benchmarks. If this is something we need, I'm motivated to build one such platform.

#1295

**Comment by DarkDimius** [comment]
Just had a discussion with @liufengyun. For start, it may be simpler to build a regression testing infrastructure that does not involve graphs, by checking that metrics do not deviate too much in the CI.

**Comment by liufengyun** [comment]
This is no longer relevant -- current benchmark infrastructure are sensitive enough to track 20x slowdown.
