### ISSUE TITLE
Catch without case not recognized as CanThrow scope

### ISSUE THREAD

**Issue by romanowski** [lampepfl/dotty#13692]
## Compiler version

`Scala 3.1.1-RC1-bin-SNAPSHOT-git-3a6a949 (16.0.1, Java OpenJDK 64-Bit Server VM)`

## Minimized code

The following code compiles:
```scala
import language.experimental.saferExceptions
def safe(): Unit = try
  throw Exception()
  catch case e: Exception => ()
```

But this does not:
```scala
import language.experimental.saferExceptions
def safe(): Unit = try
  throw Exception()
  catch Exception => ()
```

The compiler does not recognize that the "simple" `catch` expression implies a `CanThrow[Exception]` in scope.

## Output

The compiler reports in the second example: `The capability to throw exception Exception is missing.`

## Expectation

No compile error in both cases.

**Comment by odersky** [comment]
That's because the simple catch expression is not what you think it is. In fact it the same as:
```scala
import language.experimental.saferExceptions
def safe(): Unit = try
  throw Exception()
  catch _ => ()
```
We do not generate `CanThrow` capabilities for wildcard catches. In fact, such catches should be discouraged anyway.
