### ISSUE TITLE
repl leaks inner object names

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1370]
taken from http://scalapuzzlers.com/#pzzlr-015

``` scala

scala> object Lives {
         class Private {
           def foo1: Any = new Private.C1
           def foo2: Any = new Private.C2
         }

         object Private {
           class C1 private {}
           private class C2 {}
         }
       }
                        ^
    def foo1: Any = new Private.C1
<console>:9: error: constructor C1 cannot be accessed as a member of line14$object.$iw.$iw.Lives.Private.C1 from class Private.
```

`line14$object.$iw.$iw.` shoundn't be shown to user.

**Comment by kzys** [comment]
bb60d3c43bd42d24b54d5cad0dcfdb50cbdd5782 disabled that calling stripWrapperGunk from ConsoleReporter.

Apparently stripWrapperGunk removes a specific pattern which includes ```line```, ```object``` and ```iw```. So enabling the function seems safe for me.
