### ISSUE TITLE
Scala 2's implicit lambda arguments have no real replacement in Scala 3

### ISSUE THREAD

**Issue by megri** [lampepfl/dotty#13713]
## Compiler version
3.0.2

## Minimized example

```Scala
// with the following declarations ...
def test(x: Int)(f: Int => Int) = f(x)
def doStuff()(using x: Int) = ???

// .. legacy implicits works
test(0) { implicit x => 
  doStuff()
}

// neither of these works
test(1) { using x => 
  doStuff()
}

test(2) { given x =>
  doStuff()
}

// this works but looks weird and feels clunky, especially in contexts where the type should be contextual (like with ExecutionContext)
test(3) { x => 
  given Int = x
  doStuff()
}
```

## Expectation

While situational, it is nice to be able to promote a lambda argument to an implicit. With the push for given/using, no real solution is given. It seems like this use-case was simply forgotten.

Another issue is that neither `given` nor `using` feels like a semantically correct replacement for implicit in the example above. `using` makes sense if the lambda body is compared to a def declaration but `given` is what actually works in the "clunky workaround". Both of them are unsuitable in the sense that they normally require the type declared, and they are easily mixed up (I always forget which one goes where but that's not really a point of the issue).

edit: `using` also makes sense when considering `doStuff()(using 4)`

**Comment by odersky** [comment]
The following works and is the recommended replacement:
```scala
def test(x: Int)(f: Int ?=> Int) = f(using x)
def doStuff()(using x: Int) = ???

test(1) { x ?=>
  doStuff()
}
```

**Comment by bishabosha** [comment]
as I noted in [this discussion](https://github.com/lampepfl/dotty/discussions/12007#discussioncomment-588630)
you can make a wrapper method for implicit functions:
```scala
inline def implicitfn[T, U](inline f: T ?=> U): T => U = f(using _)

test(1)(implicitfn {
  doStuff()
})
```
