### ISSUE TITLE
[Docs] The link to source code does not work

### ISSUE THREAD

**Issue by ShuiRuTian** [lampepfl/dotty#13716]
## Minimized example

visit https://scala-lang.org/api/3.x/scala/collection/immutable/HashMap.html

click "source" property: "HashMap.scala"

## Output

An error page

https://github.com/lampepfl/dotty/blob/3.0.2/out/bootstrap/stdlib-bootstrapped/scala-3.0.3-RC1-bin-SNAPSHOT-nonbootstrapped/src_managed/main/scala-library-src/scala/collection/immutable/HashMap.scala#L39

## Expectation

The opened source file.

**Comment by KacperFKorban** [comment]
Hi, thanks for reporting the issue.
This problem was already reported here #13488
We'll try to update the docs as soon as possible. In the meantime you can use the nightly version of docs for stdlib [here](https://dotty.epfl.ch/api/index.html)
