### ISSUE TITLE
Regression in Scala 3.0.{1 ⇒ 2}

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#13730]
## Compiler version

scalajs-react compiles with 3.0.1 but doesn't with 3.0.2.

## Reproduction

1. `git clone https://github.com/japgolly/scalajs-react.git`
2. `cd scalajs-react`
3. `git checkout topic/scala302`
4. `sbt Test/compile`

## Output

```
[error] -- [E007] Type Mismatch Error: .../scalajs-react/tests/src/test/scala/japgolly/scalajs/react/extra/router/Router2Test.scala:36:25 
[error] 36 |        | dynamicRouteCT("two" / int.caseClass[Module2]) ~> dynRender(m => <.h3(s"Module #2 @ ${m.i}"))
[error]    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Found:    japgolly.scalajs.react.extra.router.StaticDsl.RouteB[?1.C]
[error]    |Required: japgolly.scalajs.react.extra.router.StaticDsl.Route[
[error]    |  japgolly.scalajs.react.extra.router.Router2Test.Module
[error]    |]
[error]    |
[error]    |where:    ?1 is an unknown value of type japgolly.scalajs.react.extra.router.StaticDsl.RouteB.Composition.Aux[Unit, 
[error]    |  japgolly.scalajs.react.extra.router.Router2Test.Module2
[error]    |, japgolly.scalajs.react.extra.router.Router2Test.Module2]
```

**Comment by smarter** [comment]
> Found:    japgolly.scalajs.react.extra.router.StaticDsl.RouteB[?1.C]
> Required: japgolly.scalajs.react.extra.router.StaticDsl.Route[japgolly.scalajs.react.extra.router.Router2Test.Module]

RouteB is invariant, so the error is correct, it likely only worked by chance before I fixed a bug with skolems in https://github.com/lampepfl/dotty/commit/a0236000d3f9500dff58f9c6ef89b1c00073c7b3. Without a minimization to demonstrate an actual issue, to me this is working as intended.

**Comment by japgolly** [comment]
Sorry I haven't had a chance to verify this but @smarter know's what he's on about. I'll just close this. Thanks!
