### ISSUE TITLE
Spurios "duplicate pattern variable" when using lower-case type names

### ISSUE THREAD

**Issue by larsrh** [lampepfl/dotty#13740]
## Compiler version

3.0.2 and 3.1.0-RC3

## Minimized code

```Scala
scala> type int = Int
// defined alias type int = Int

scala> val (x, y): (int, int) = (1, 2)
-- Error:
1 |val (x, y): (int, int) = (1, 2)
  |                  ^^^
  |                  duplicate pattern variable: int
```

## Expectation

No error, since this example is not a violation of linearity.

It works if the type is used in uppercase, or if ascribing each variable with `: int` individually.

**Comment by KacperFKorban** [comment]
@larsrh I think that this is a correct behavior as well. Acording to the [syntax](https://github.com/lampepfl/dotty/blob/master/docs/docs/internals/syntax.md) reference, they are interpreted as different definitions.

@odersky Maybe it would be a good idea to reopen this as a documentation improvement issue?
