### ISSUE TITLE
inline match breaks simple example, documentation?

### ISSUE THREAD

**Issue by Adam-Vandervorst** [lampepfl/dotty#13774]
## Compiler version

3.0.2

## Minimized code

```Scala
(transparent) inline def f(x: Int) = inline x match
  case 1 => 1
  case _ => 0

@main def m =
  val v = 1
  println(f(v))
```

## Output

```scala
0
```

## Expectation

Give the same output as (namely 1)
```scala
inline def f(x: Int) = x match
  case 1 => 1
  case _ => 0
```
and if not, be documented in the "Inline Matches" section of https://docs.scala-lang.org/scala3/reference/metaprogramming/inline.html.

(Note that this does work when `v` has singleton type `1`)

**Comment by SethTisue** [comment]
This came up last year at #10919, where @odersky said the behavior is not just intended, but "specified".

But I really don't see any wording at https://docs.scala-lang.org/scala3/reference/metaprogramming/inline.html that specifies it.

In fact, as Nicolas observes, "If there is enough static information to unambiguously take a branch" (wording from that page) can be read as requiring that compilation fail, since the cases overlap.

**Comment by som-snytt** [comment]
Speaking as a non-expert, which makes me an audience for the simple example, I think the doc is quite clear.

However, I would remove the weaselly adverb, "unambiguously". I would also prefer "select" or "pick" to "take". I'd also prefer not to split an infinitive. (I also double-checked, the character's name is Ron Weasley.)

> If there is enough static information to select a branch, the expression is reduced...

It already says "static type":

> The example below ... picks a case based on its static type

But I sympathize with the OP, where there was not enough inlining to have the salutary effect. 🖖 

Maybe a lint could warn about non-unambiguously specified inline matches. In the example, if a branch matches on a narrow type (`1`) but the (inlined) scrutinee is a wider type (`Int`), then annoy me by pointing that out. Maybe the lint is only triggered by singleton types (which might suggest "I was expecting runtime-like semantics").

Also, on the semantics of "semantics", to speak of "preserving" them, one must distinguish "compiletime" and "runtime", a difference encapsulated by the word "static". Unfortunately, that word is overloaded: connotations accrue to it as by "static cling".

> If there is enough type information at compile time to select a branch, the expression is reduced...

That may be usefully redundant.

**Comment by som-snytt** [comment]
Surprisingly warning-free
```
transparent inline def f(x: Any): Any =
  inline x match
    case x: Any => (x, x)
    case x: Any => x
```

**Comment by som-snytt** [comment]
I "committed" my formulation in the proposed PR, but I'm open to suggestions and amendments or emendations that are not mendacious.
