### ISSUE TITLE
ClassCastException when summoning Mirror for hierarchical sum compiled by 3.0.x

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#13777]
## Compiler version

3.1.0

## Minimized code

compile with Scala 3.0.2 to `out` dir
```scala
sealed trait Top
object Top // companion is necessary

case class Middle() extends Top with Bottom
sealed trait Bottom extends Top
```

compile with Scala 3.1.0 and with `out` on classpath
```scala
val m = summon[deriving.Mirror.SumOf[Top]]
```

## Output

runtime error:
```scala
java.lang.ClassCastException: Top$ cannot be cast to scala.deriving.Mirror$Sum
  ... 28 elided
```
This happens because `Top` is an eligible sum, and it has a companion object (which if compiled by Scala 3.1.0 would extend `deriving.Mirror.Sum`), so the companion object is used as the mirror and is cast to `Sum`.

## Expectation
prevent summoning mirrors for hierarchical sums with companion objects compiled before 3.1.0

**Comment by bishabosha** [comment]
> I'd say don't use the companion object as the mirror if it doesn't extend Mirror.Sum, but rather summon a local mirror. Any reason that can't be made to work?

This sounds very reasonable to me, quoting your other comment:
> I feel like there's a way to tell if a symbol is for a classfile or from a source file, so the check could be companionObject.isSource || companionObject <:< Mirror.Sum.

hopefully this works!

**Comment by dwijnand** [comment]
I haven't forgotten it but I'm happy to hand it off if someone wants it.

**Comment by bishabosha** [comment]
@dwijnand I have added a test case on the branch https://github.com/dotty-staging/dotty/tree/fix-13777
