### ISSUE TITLE
private variables are scoped to constructor not the class

### ISSUE THREAD

**Issue by Arthurm1** [lampepfl/dotty#13770]
In Scala 2, private variables in a class would be defined in the class.  In Scala 3 they seem to be defined in the constructor.

I ran into this because I had weak references to the variables and then the variables got garbage collected - which was not what I wanted.

## Compiler version
3.1.0-RC3

## Minimized code
```Scala
class Foo(i: Int) {
  private val bar: Int = 0
}
```

seems to give the equivalent in Java of...

```java
public class Foo
{
    Foo(int i) {
        int bar = 0;
    }
}
```

when in Scala 2 it gave...

```java
public class Foo
{
    private int bar = 0;

    Foo(int i) {
    }
}
```

I think Scala 2 also defined `private[this] val` in the class, not the constructor.

**Comment by Arthurm1** [comment]
So having a `private def` refer to `bar` is the only way to force it to be a class field without Scala automatically creating a public getter?  There's no special keyword to force it to be a class field, e.g. `private[class] val bar:int = 0`?

My issue is that I have something like this...
```
class Foo(i: Int) {
  private val privateBar: Int = 0
  val publicRef = new java.lang.ref.WeakReference(privateBar)
}
```
which was fine in Scala 2 but now `publicRef.get` returns null after a GC.

**Comment by smarter** [comment]
For anyone wanting to work on this, the logic which decides which private val should not be moved to the constructor is here: https://github.com/lampepfl/dotty/blob/7cb30029a5eadea5d4848519f3ae96aca319d914/compiler/src/dotty/tools/dotc/transform/Constructors.scala#L49-L80

**Comment by alexknvl** [comment]
I can imagine there are situations where you don't want a `private val` to become an actual field and you still have a public `WeakReference` to it. Say something like

```scala
class BarAllocator(barManager: BarManager) {
  private val privateBar = new Bar
  val publicRef = new java.lang.ref.WeakReference(privateBar)
  barManager.add(privateBar) // may or may not delete it later
}
```

It seems to me that adding special cases for special cases is a bad idea and a consistent set of rules is more preferable. I.e. adding a `private def` seems like a reasonable workaround assuming that compiler behavior is documented somewhere and stays consistent so that the code doesn't suddenly break.
