### ISSUE TITLE
Match types fail to identify disjoint of opaque types when defined in a separate file

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#13804]
After I was corrected on the false bug report in #13802, now the bug is minimized properly after introduction of a separate file for an opaque type. As can be seen, when the opaque type is defined in the same file, the match does not produce an error, but when the opaque is defined at a different file, the match fails to identify disjointness.

## Compiler version

v3.1.0

## Minimized code
Minimized project available at: https://github.com/soronpo/dottybug/tree/opaque_match_type_disjoint

**MyMatch.scala**
```Scala
opaque type DFType = Int
sealed trait DFEncoding
class DFString extends DFEncoding

type MyMatch[T <: DFType | DFEncoding] = T match
  case DFType     => Int
  case DFEncoding => String

type MyMatch2[T <: DFType2 | DFEncoding] = T match
  case DFType2     => Int
  case DFEncoding => String

val works = summon[MyMatch[DFString] =:= String]
val fails = summon[MyMatch2[DFString] =:= String]
```
**DFType2.scala**
```scala
opaque type DFType2 = Int
```

## Output

```scala
[error] 14 |val fails = summon[MyMatch2[DFString] =:= String]
[error]    |                                                 ^
[error]    |             Cannot prove that MyMatch2[DFString] =:= String.
[error]    |
[error]    |             Note: a match type could not be fully reduced:
[error]    |
[error]    |               trying to reduce  MyMatch2[DFString]
[error]    |               failed since selector  DFString
[error]    |               does not match  case DFType2 => Int
[error]    |               and cannot be shown to be disjoint from it either.
[error]    |               Therefore, reduction cannot advance to the remaining case
[error]    |
[error]    |                 case DFEncoding => String
```

## Expectation
No error.

**Comment by TheElectronWill** [comment]
Just got hit by this :(
It's a pity that we must return to value classes to use match types.
I'm curious to know why opaque types are considered to be abstract by the compiler, instead of new "concrete" types :thinking: (in the context of match types of course - for pattern matching it makes sense to at least emit a warning)

**Comment by smarter** [comment]
> I'm curious to know why opaque types are considered to be abstract by the compiler

Opaque types are an encapsulation mechanism, like making a method `private`. When you define an opaque type, you should be able to change the type in its right-hand side without breaking your API (though the right-hand side type does leak into bytecode signatures, so changing it can break the ABI).

**Comment by TheElectronWill** [comment]
I think what's a bit confusing is that, for functions and variables, it's "as is" opaque types were totally new types, different from the others. For instance an `opaque type Distance = Int` is considered to be different from `Int`. Of course, it's important allow the rhs of the opaque type to change without breaking everything. But I fail to see how it would break if the following match type reduction worked:
```scala
A match
  case Int => Something
  case Distance => SomethingElse // the rhs of the opaque type doesn't matter, it's not an Int at compile-time
  case _ => Other
```
Doesn't the compiler has all the information about `A` (for each use site)?
