### ISSUE TITLE
Lost type member bounds for refined pattern types

### ISSUE THREAD

**Issue by Linyxus** [lampepfl/dotty#13820]
## Compiler version

3.1.0

## Minimized code

```Scala
trait Expr { type T }

def foo[A](e: Expr { type T = A }) = e match
  case e1: Expr { type T <: Int } =>
    val i: Int = ??? : e1.T
```

## Output

```scala
Found:    e1.T
Required: Int
```

## Expectation

The code should be accepted, since `e1.T` is defined to be the subtype of `Int`. However, by inspecting the typer, we found that the pattern will be typed as `_: Expr{type T = _}` where `_` is the wildcard type, and the information about the bounds `<: Int` gets lost.

**Comment by abgruszecki** [comment]
Unassigning myself since if there's anything in the compiler I will be taking a look at anytime soon, it will be issues directly related to GADTs.
