### ISSUE TITLE
parameter can have path dependent type on itself, causing cycle

### ISSUE THREAD

**Issue by dwijnand** [lampepfl/dotty#13840]
## Compiler version

3.1.0

## Minimized code

```scala
package foo

class Foo:
  def bar(foo: foo.Foo) = 1
```

## Output

```scala
-- [E046] Cyclic Error: a.scala:4:15 -------------------------------------------
4 |  def bar(foo: foo.Foo) = 1
  |               ^
  |               Cyclic reference involving val foo
```

## Expectation

I don't expected the parameter name to shadow the package name when naming the parameter's type.

There are proposals to allow parameter values to be used in type position within new parameter groups.  Maybe that could even work within the same parameter group.  But there's no chance of that working within the same parameter!

For context, this occurred in some generated Akka Serverless code (the problem is also present in Scala 2).

**Comment by bishabosha** [comment]
we do allow path dependent types between parameters, but does it make sense to have it on itself?
```scala
package foo

class Foo:
  type F
  def bar(foo: Foo, f: foo.F) = 1
```

**Comment by bishabosha** [comment]
same error if you declare a val:
```scala
package foo

val foo: foo.Foo = ???

class Foo
```
```scala
-- [E046] Cyclic Error: foo.scala:3:9 ------------------------------------------
3 |val foo: foo.Foo = ???
  |         ^
  |         Cyclic reference involving val foo
```

**Comment by odersky** [comment]
Since we _do_ allow parameters from the same group, but require that they must come before the reference. For comparison, if we refer to a _following_ parameter
```scala
package foo

class Bar:
  val self = Bar()
  class Foo:
    def bar(x: foo.Foo, foo: Bar) = 1
```
 we get:
```
-- Error: test.scala:6:15 ------------------------------------------------------
6 |    def bar(x: foo.Foo, foo: Bar) = 1
  |               ^^^
  |               illegal forward reference to method parameter
1 error found
```
So I think this is as it should be. One can quibble about the error message, but I think Cyclic Reference is actually OK in this case.

**Comment by odersky** [comment]
And this goes to show that, if the compiler let's them, people will use every crazy loophole the language allows. 
```scala
class Foo {
  def bar(foo: foo.Foo) = 1
}
```
looks really dubious. What's the point of this name choice?

**Comment by dwijnand** [comment]
It came out of generated code, where the names were:

```scala
def create(customer: customer.api.Customer): DeferredCall[customer.api.Customer, com.google.protobuf.empty.Empty]
```

So I thought seeing as it's impossible to self-reference in the type, we could unshadow.  But that doesn't solve the problem in the final result type, and it adds more rules, so happy to have this as it is.  It's only not an issue in Java because Java just doesn't have any path dependency.
