### ISSUE TITLE
Lambdas with parametrized captured parameters may end with more than 22 parameters.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#1385]
```scala
 def foo22[T](c1:T, c2:T, c3:T, c4:T, c5:T, c6:T, c7:T, c8:T, c9:T, c10:T, c11:T, c12:T, c13:T, c14:T, c15:T, c16:T, c17:T, c18:T, c19:T, c20:T, c21:T, c22:T): Int => T = {
    (a: Int) => { // This labda ends with 23 parameters (c1 to c22 and a)
      c22; c21; c20; c19; c18; c17; c16; c15; c14; c13; c12; c11; c10; c9; c8; c7; c6; c5; c4; c3; c2; c1
    }
  }
```

This case will fail because the inner lambda will have 23 parameter, which fails due to #1384.

**Comment by odersky** [comment]
The illegal closure gets created temporarily in phase lambda lift bt the transform framework. Lambdalift takes the closure and subtracts the environment from it, thereby turning a closure with 23 parameters into a closure with 1 parameter. The most elegant fix is probably to simply accept functions with more than 22 parameters.
