### ISSUE TITLE
disable caching hierarchical sum mirror in companion when < 3.1

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#13863]
## Compiler version

3.1.0

## Minimized example

`using -source:3.0`
```Scala
sealed trait Top
object Top // companion is necessary

case class Middle() extends Top with Bottom
sealed trait Bottom extends Top

@main def test =
  println(classOf[deriving.Mirror.Sum].isAssignableFrom(classOf[Top.type]))
```

## Output

```scala
true
```

## Expectation

`false` when the source version / target version is less than 3.1

**Comment by smarter** [comment]
> false when the source version / target version is less than 3.1

I don't see why, -source purpose so far has been to tweak type inference and enable/disable warnings and errors, but it never tried to mimic a specific compiler version exactly. Especially in that case I don't see how that could be useful?

**Comment by bishabosha** [comment]
maybe not do anything for `-source:3.0` then, but do you agree that if we target 3.0 then we should not add the `Mirror.Sum` parent? (which will add a method called `ordinal` to the companion)

**Comment by smarter** [comment]
> do you agree that in a hypothetical -target:3.0 then we should not add the Mirror.Sum parent?

Would that be needed to be able to safely consume the artefact from Scala 3.0? If it's not needed then no, I think it's fine to keep the additional parent.

**Comment by bishabosha** [comment]
if someone recompiles their library with `3.1.0` and suddenly there is a synthetic `ordinal` method (added by Mirror framework) on one of the companion objects then that breaks the forward binary compat

**Comment by smarter** [comment]
I think that's fine, people who care about forward binary compat will have mima setup to warn about it and can bump their minor versions when that happens.

**Comment by bishabosha** [comment]
closing due to not taking action
