### ISSUE TITLE
Not possible to construct an aliased class without `new` keyword 

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#13876]
Not sure if this is a bug, but generally I do not expect a difference between a class and an aliased class.

## Compiler version

v3.1.0

## Minimized code

```Scala
class Foo()
type Bar = Foo
val foo = Foo()
val bar = Bar()
```

## Output

```scala
Not found: Bar
```

## Expectation
No error.

**Comment by bishabosha** [comment]
this seems strange when you consider that exported classes do get constructor proxies, i.e. the following compiles:
```scala
class Foo()
export `<empty>`.Foo as Bar
val foo = Foo()
val bar = Bar()
```

**Comment by bishabosha** [comment]
you can get around this by defining a value alias to the companion of `Foo`:
```scala
class Foo()
val Bar = Foo
type Bar = Foo
val foo = Foo()
val bar = Bar()
```

**Comment by bishabosha** [comment]
this is strange when you consider that exporting a class does make a constructor proxy:
```scala
class Foo()
export `<empty>`.Foo as Bar
val foo = Foo()
val bar = Bar()
```

**Comment by odersky** [comment]
This is as specced currently, and would be very hard to change. Maybe make it a feature request? But I can't really promise anything. There are a lot of tradeoffs.
