### ISSUE TITLE
Scaladoc does not give source reference for missing DRI in file specified by -doc-root-content

### ISSUE THREAD

**Issue by jphmrst** [lampepfl/dotty#13874]
## Compiler version

3.1.0

## Minimized code

In `build.sbt`
```Scala
Compile / doc / scalacOptions ++= Seq(
  "-doc-root-content", "rootdoc.txt"
)
```

In `rootdoc.txt`
```
I'm a little [[org.teapot]]
```

## Output

From SBT
```scala
[info] Main Scala API documentation to /home/jm/tmp/tmp/target/scala-3.1.0/api...
[warn] No DRI found for query: org.teapot
[warn] one warning found
[info] Main Scala API documentation successful.
[success] Total time: 0 s, completed Nov 3, 2021, 10:35:14 PM
```

## Expectation

It should mention that the problem is in the `rootdoc.txt` file.

**Comment by raquo** [comment]
Relatedly, how do I silence this "No DRI found for query" warning? I think previous versions had "-no-link-warnings", but it doesn't seem to silence this warning anymore.

**Comment by pikinier20** [comment]
> Relatedly, how do I silence this "No DRI found for query" warning? I think previous versions had "-no-link-warnings" option, but it doesn't seem to silence this warning anymore.

Hey, I tried to reproduce your problem on newest master snapshot as well as on 3.1.0 and it seems that flag `-no-link-warnings` works well on both versions.
