### ISSUE TITLE
Quoted Expr contains unexpected TypeVar

### ISSUE THREAD

**Issue by cchantep** [lampepfl/dotty#13895]
## Compiler version

3.1.2-RC1-bin-20211022-f7abd32-NIGHTLY

## Minimized code

TODO

Quite hard to draft a reproducer as would depend on internal types not exposed in the API (`TypeVar`, `TypeParamRef`, ...) : https://github.com/cchantep/ReactiveMongo-BSON/blob/task/dotty/api/src/main/scala-3/MacroImpl.scala#L338

## Output

```
[error]    |scala.MatchError: TypeVar(TypeParamRef(Opts)) (of class dotty.tools.dotc.core.Types$TypeVar)
[error]    |	at scala.quoted.runtime.impl.printers.Extractors$ExtractorsPrinter.visitType(Extractors.scala:242)
[error]    |	at scala.quoted.runtime.impl.printers.Extractors$.showType(Extractors.scala:12)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$$anon$17.show(QuotesImpl.scala:2960)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$$anon$17.show(QuotesImpl.scala:2959)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TypeReprMethods$.show(QuotesImpl.scala:1708)
[error]    |	at scala.quoted.runtime.impl.QuotesImpl$reflect$TypeReprMethods$.show(QuotesImpl.scala:1708)
```

## Expectation

Print successfully the `Expr`

**Comment by nicolasstucki** [comment]
This `TypeVar` should not have been present. The fix is most likely 
a missing `stripTypeVar` in `QuotesImpl`. We need a minimized self-contained example to make progress on this issue.

**Comment by nicolasstucki** [comment]
Minimizing the code in the link to a small failing case where we have the unwanted `TypeVar` would be a good issue for the spree.

**Comment by nicolasstucki** [comment]
The original link yields a 404. There is no way to figure out what happened.

**Comment by cchantep** [comment]
Maybe that's a bit late ...
