### ISSUE TITLE
Implicit search not performed on type of transparent inline given expansion

### ISSUE THREAD

**Issue by zawodskoj** [lampepfl/dotty#13890]
## Compiler version

3.1.0

## Minimized code

```Scala
trait Trait[X]
trait RefinedTrait[X, Y] extends Trait[X]

case class Foo(bar: Int)
object Foo:
  transparent inline given derived: Trait[Foo] = null.asInstanceOf[RefinedTrait[Foo, Int]]

@main
def main: Unit =
  println(implicitly[Trait[Foo]]) // ok
  println(implicitly[RefinedTrait[Foo, Int]]) // no implicit argument of type RefinedTrait[Foo, Int] was found ...
  println(implicitly[RefinedTrait[Foo, Int]](using Foo.derived)) // ok
```

## Expectation

I would expect givens to not to lose their real type when they are transparent

## Possible fix

Not sure if this is a dirty hack or not, but at least it works on sample and does not break tests

https://github.com/zawodskoj/dotty/commit/f4da86033fb02d85a7a7b236a6e172d01e9a708c

This issue is probably related to #10031

**Comment by nicolasstucki** [comment]
This is the intended behavior. Implicit lookup is performed based on the signature of the methods. Inline expansion is only performed for `given`s that were found by the implicit search.

Doing it the way proposed by this issue would imply that we would need to expand every single transparent inline given with all possible given parameter combinations to perform implicit search.  This also would make it impossible to use caches in implicit searches.
