### ISSUE TITLE
Custom StaticAnnotation not represented on field Symbol

### ISSUE THREAD

**Issue by cchantep** [lampepfl/dotty#13921]
## Compiler version

3.1.2-RC1-bin-20211022-f7abd32-NIGHTLY

## Minimized code

```Scala
import scala.quoted.*

final class Ann extends scala.annotation.StaticAnnotation

case class Foo(
    @Ann @transient bar: String,
    lorem: Int)

  inline def foo[T]: Unit = ${ fooImpl[T] }

  private def fooImpl[T: Type](using q: Quotes): Expr[Unit] = {
    import q.reflect.*

    val tpe = TypeRepr.of[T]
    val annots =
      tpe.typeSymbol.declaredFields.flatMap(_.annotations).mkString(", ")

    '{ println("annotations = " + ${ Expr(annots) }) }
  }
```

## Output

```
annotations = Apply(Select(New(Ident(transient)),<init>),List())
```

## Expectation

Custom `StaticAnnotation` `Ann` should be resolved (and so printed there)

**Comment by KacperFKorban** [comment]
The annotation is on the primary constructor parameter. It can be accessed like this:
```scala
import scala.quoted.*

final class Ann extends scala.annotation.StaticAnnotation

case class Foo(
  @Ann @transient bar: String,
  lorem: Int
)

inline def foo[T]: Unit = ${ fooImpl[T] }

private def fooImpl[T: Type](using q: Quotes): Expr[Unit] = {
  import q.reflect.*

  val tpe = TypeRepr.of[T]
  val annots =
    tpe.typeSymbol.primaryConstructor.paramSymss.flatten.flatMap(_.annotations).mkString(", ")

  '{ println("annotations = " + ${ Expr(annots) }) }
}
```

**Comment by cchantep** [comment]
Why the `@transient` annotation is represented on the field and not the custom one? Doesn't seem consistent to me anyway.

**Comment by KacperFKorban** [comment]
It's because of the `@field` annotation on transient https://dotty.epfl.ch/api/scala/transient.html
If you add it to `Ann` it will also be on the field.

**Comment by cchantep** [comment]
Thx, it could be documented.

**Comment by KacperFKorban** [comment]
The documentation of annotations behavior is here: https://dotty.epfl.ch/api/scala/annotation/meta.html

**Comment by cchantep** [comment]
I mean at least adding a `@see` in `StaticAnnotation` and/or `Annotation` to `meta` indicating that it could be helpful to define the required retention. Otherwise you need to already know of `@meta`.
