### ISSUE TITLE
source links in api docs are broken in 3.1.0

### ISSUE THREAD

**Issue by bjornregnell** [lampepfl/dotty#13920]
## Compiler version

3.1.0 

## Minimized code

On the api-doc every source link seems broken, for instance on https://scala-lang.org/api/3.x/scala/Option.html
this link https://github.com/lampepfl/dotty/blob/3.1.0/out/bootstrap/stdlib-bootstrapped/scala-3.1.0-bin-SNAPSHOT-nonbootstrapped/src_managed/main/scala-library-src/scala/Option.scala#L144
is broken

![image](https://user-images.githubusercontent.com/3601817/141114709-2de44408-1fb9-4bd5-a06b-c02865ac9915.png)

## Expectation

The link should go to the relevant source file.

**Comment by BarkingBad** [comment]
Sorry for the inconvenience. Hopefully, tomorrow server will reindex updated files and it should work then

**Comment by julienrf** [comment]
It works now!
