### ISSUE TITLE
`Cannot rewrite recursive call: it is not in tail position` error

### ISSUE THREAD

**Issue by xuwei-k** [lampepfl/dotty#13941]
## Compiler version

- `3.1.2-RC1-bin-20211102-82172ed-NIGHTLY`
- `3.1.1-RC1`
- `3.1.0`
- `3.0.2`

## Minimized code

```Scala
import scala.annotation.tailrec

class A {
  def b = Option("a").map { x =>
    @tailrec def loop(): Int = {
      try {
        2
      } catch { 
        case _: Throwable =>
          loop()
      }
    }
    x
  }
}
```

## Output

```scala
[error] 10 |          loop()
[error]    |          ^^^^^^
[error]    |          Cannot rewrite recursive call: it is not in tail position
```

**Comment by nicolasstucki** [comment]
Even worse, with the following variant the check passes and the tailrec transformation is ignored

```scala
import scala.annotation.tailrec

class A {
  def b = Option("a").map { x =>
    def loop(): Int = {
      try {
        loop()
      } catch {
        case _: Throwable =>
          2
      }
    }
    x
  }
}
```

**Comment by bishabosha** [comment]
> Even worse, with the following variant the check passes and the tailrec transformation is ignored

I think there may be a typo - it fails for me when I annotated `loop`

**Comment by nicolasstucki** [comment]
Indeed. My mistake.

**Comment by KacperFKorban** [comment]
The problem here is that `LiftTry` is applied for the try-catch statement and this makes it no longer directly tailrec. I drafted a PR, but after some consideration, I'm not sure if it is correct.
