### ISSUE TITLE
No way to list the type parameters from a quotes Symbol or TypeRepr

### ISSUE THREAD

**Issue by cchantep** [lampepfl/dotty#13947]
It's not possible in quotes to do something like:

```scala
def foo(s: Symbol): List[Symbol] = s.typeParams
```

In dotc it's possible to:

```scala
def foo(s: Symbol)(using Context): List[TypeSymbol] = s.denot.typeParams
```

**Comment by nicolasstucki** [comment]
This is a bit trickier than it would seem. The assumption above is that there is a single type argument list. This is not necessarily true as some definitions can have multiple type parameter lists. For example
```scala
extension [A](a: A) def f[B](b: B): C = ???
// becomes internally
def f[A](a: A)[B](b: B): C
```

**Comment by nicolasstucki** [comment]
Currently, the idea is to get the `DefDef` from the `Symbol` and then use one of the `paramss`, `leadingTypeParams`, `trailingParamss`,  `termParamss`.

**Comment by cchantep** [comment]
For me, the type arguments/parameters on the functions through extension don't correspond to the definition of resolving the type arguments/parameters.
