### ISSUE TITLE
Warning about open classes doesn't work in Scala 3.1.0

### ISSUE THREAD

**Issue by trackiss** [lampepfl/dotty#13946]
## Compiler version

3.1.0

## Minimized code

```Scala
// in Printer.scala
class Printer:
  def print(s: String): Unit = println(s)
```

```scala
// in BadPrinter.scala
class BadPrinter extends Printer:
  override def print(s: String): Unit = println("Bad!!!")
```

and enabled `-source future` flag.
Of course, `-language.adHocExtensions` flag has been disabled, and it hasn't imported `scala.language.adHocExtensions` in these source files.

## Output

It compiles successfully and no warning is output.

## Expectation

The warning should be output because the `open` modifier hasn't been added.
On the other hand, the warning is output successfully in Scala 3.0.2.

**Comment by odersky** [comment]
I could not reproduce that on master. Maybe the -source future did not apply correctly? I made a regression test to make sure we do not regress in the future.

**Comment by som-snytt** [comment]
without consulting the master,

```
Using scala version 3.1.0 in this shell.
➜  i13946 scalac -source future *la
there were 1 feature warning(s); re-run with -feature for details
➜  i13946 scalac -feature -source future *la
-- Feature Warning: badprinter.scala:2:25 -------------------------------------------------------------------------------------------------------
2 |class BadPrinter extends Printer:
  |                         ^^^^^^^
  |                         Unless class Printer is declared 'open', its extension in a separate file should be enabled
  |                         by adding the import clause 'import scala.language.adhocExtensions'
  |                         or by setting the compiler option -language:adhocExtensions.
  |                         See the Scala docs for value scala.language.adhocExtensions for a discussion
  |                         why the feature should be explicitly enabled.
1 warning found
```
Per the previous comment, the real bug is how did the OP see their unexpected output? For example, `-Wconf`? under the aegis of "things should just work".

"Use the flag, Luke."
