### ISSUE TITLE
Illegal quote/splice syntax passing through parser

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#13951]
## Compiler version

3.1.1

## Minimized code

```Scala
import scala.quoted.*

def q1(using Quotes): Expr[Int] = '{ 1 }
def q2(using Quotes): Expr[Int] = ' { 1 } // compiles but should not
def q3(using Quotes): Expr[Int] = '{ ${ foo } }
def q4(using Quotes): Expr[Int] = '{ $ { foo } } // compiles but should not
```

## Expectation

They should have the same syntactic rules as string interpolators. `'` or `$` must be immediately followed by a `{`.

For examples the equivalent string interpolators 
```scala
def s1 = s"abc"
```
```scala
def s2 = s "abc" // does not compile
```
```scala
def s3 = s"<${"abc"}>"
```
```scala
def s4 = s"<$ {"abc"}>" // does not compile
```

Also see
* https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L2247-L2248
* https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L2232
* https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L1569-L1570

**Comment by tgodzik** [comment]
If this gets removed we should also revert https://github.com/scalameta/scalameta/pull/2487/files

**Comment by nicolasstucki** [comment]
Even stranger
```scala
import scala.quoted.*

def q2(using Quotes): Expr[Int] = ' /*aa*/ {
  println("hello")
  $/*a*/{ println(2); ' /*a*/ {3} }

}
```

**Comment by odersky** [comment]
That's not what the rules say. string interpolators are different since we are in a string where whitespace counts. For quotes and splices, they are technically a two token sequences.
