### ISSUE TITLE
`unapply` cannot return generic tuples

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#13969]
## Compiler version

3.1.0

## Minimized example

```Scala
object Bar:
  def unapply(x: Any): Int *: Int *: EmptyTuple = ??? // Works it returns a `Tuple2[Int, Int]`

def test =
  "" match
    case Bar(a, b) =>
```

## Output

```scala
10 |    case Bar(a, b) =>
   |         ^^^^^^^^^
   |         Wrong number of argument patterns for Bar; expected: ()
```

## Expectation

Should be supported.

**Comment by dwijnand** [comment]
This doesn't work because Tuple's product arity is 0 ("expected: ()").  I guess we need to teach `productArity` to walk the type to count the arity.

**Comment by nicolasstucki** [comment]
It seems that in the example of #13968 we do calculate the arity correctly. We should see how it is handled there and why it was not done here.

**Comment by dwijnand** [comment]
Duplicate of #11008
