### ISSUE TITLE
The feature of :-ending operator doesn't work correctly as extension operator

### ISSUE THREAD

**Issue by HoshinoTented** [lampepfl/dotty#13988]
## Compiler version

```plain
sbt:scala3> print scalaVersion
3.1.0
```

## Minimized code

```Scala
case class Foo(val value: String) {
  def +: (that: Foo) = Foo(that.value + value)
}

case class Bar(val value: String)

extension (bar: Bar) def +: (that: Bar) = Bar(that.value + bar.value)

println(Foo("1") +: Foo("2"))    // expected Foo("12")
println(Bar("1") +: Bar("2"))     // expected Bar("12")
```

## Output

```scala
Foo(12)
Bar(21)
```

## Expectation

:-ending operator doesn't reverse the argument and `this` correctly when as an extension method.

**Comment by prolativ** [comment]
This is as specified even though this might not be obvious when one reads the documentation https://docs.scala-lang.org/scala3/reference/contextual/right-associative-extension-methods.html.
In general the idea is that with extension methods you are now able to write operators ending in `:` without having to think whether the arguments would be swapped or not - their order at definition and  use site would be always the same. With this in mind one should now prefer extension methods to old style right associative methods defined in classes.

**Comment by som-snytt** [comment]
I have read the text at https://docs.scala-lang.org/scala3/reference/contextual/extension-methods.html "the two swaps cancel each other out" and also the details link. I am still confused, but I understand that there was a discussion in which the outcome was that it would be neat if the extension definition did not require mentally swapping the order of operands. (Per the detail page, the future simplification involves "no swapping". In Dora the Explorer, the phrase is, "Swiper, no swiping!" so this would be similar.)

Maybe I've spent time in Stockholm, so I'm used to the Syndrome there, but I read `a op_: b` as `b.op_:(a)` so I would also expect to write the extension that way, as an extension on `b`, `extension (b: B)` etc. Probably after spending some time with it, I will accept the current behavior as obvious.

**Comment by prolativ** [comment]
As I understand it the reason why scala has a special rule for desugaring operators ending in `:` was to enable writing operations like `1  +: MySeq(2, 3)` when you can't add the method `+:` to an existing type like Int. I'm not that long into scala to tell whether this feature was added before or after implicit conversions and implicit classes.
But as this rule is something newcomers to the language have to learn and even some developers with more experience might get surprised by this as even though they happen to use such operators in most cases they don't have to think about how they're defined so they might even define an operator which just happens to end in `:` expecting it to work just as any other operator.
With extension methods we could get rid of this rule thus making the language simpler. It would be enough to start reporting deprecation warnings on definitions of non-extension methods ending in `:` telling authors of libraries to use extensions instead and then in the future (not sure if only in scala 4 or earlier) we could stop handling such methods specially.

**Comment by som-snytt** [comment]
Thanks, I had never thought of the colon rule as anything but a generalization of `42 :: Nil`, which looks like a list thing, not `42.prependedTo(Nil)`. But I see that is just an artifact of having read "Programming in Scala".

I will learn to read terminal colon as `edTo`.
