### ISSUE TITLE
Incorrect position of error reported from macro in inline methods chain

### ISSUE THREAD

**Issue by dos65** [lampepfl/dotty#13991]
This issue is based on scalameta/metals#3214

The position of error that was produced in inline context is unwrapped to the outermost one.
In case if it's a chain of inline calls, it's unclear where the actual error happens.

Example:
```scala
// InlineMac.scala
object InlineMac:
  
  inline def sample(inline expr: String): Int =
    ${ sampleImpl('expr) }
  
  def sampleImpl(expr: Expr[String])(using Quotes): Expr[Int] =
      import quotes.reflect.*
      report.errorAndAbort("Error", expr)
      
// Main.scala
object Main:
  def main(args: Array: String): Unit =
     inline def v2 = InlineMac.sample("foo")  // <- the actual error position was here
     inline def v1 = v2
     
     v2  // [error] Error <- reported error position is here - wrong
```

There is a difference between in error message between direct compiler usage and using bsp-client.
The default compiler reportee additionally adds lines like: `This location contains code that was inlined from Main.scala:27` but I don't think that it helps a lot in this case.

**Comment by dos65** [comment]
After looking a bit more at inline errors, I noticed that it's a broader topic than just a reported case in this issue.

Even if the described case would have a more accurate position, it might be hard to understand the source of the error as it might depend on a parameter.

For example - a chain of inline defs with a `summonInline` with some specific type at the end:
```scala
inline def second[A]: Int = 
   summonInline[Foo[A]].foo

inline def first[A]: Int
  second[A] + 42
  
def foo =       // It's hard to say what is wrong by this error even having a correct position
  first[String] // [error] no implicit argument of  type Foo[A] was found
```

I've also noticed that [`InlinedCalls`](https://github.com/lampepfl/dotty/blob/1f48de1488b5deafce56e5d1365241cbc475c788/compiler/src/dotty/tools/dotc/ast/tpd.scala#L1290-L1313) property has a similarity with stacktraces which fits this case. Also, as the nature of inlining is a kind of interpretation so probably having errors with traces wouldn't be a completely insane idea.

From Metals viewpoint, if there were stacktraces from inlineContext we could show them to the user at the place of error + provide additional navigation.
I did a quick test and attached a fake trace to hover to check if it's possible.
![Screenshot from 2021-11-24 23-03-48](https://user-images.githubusercontent.com/5816952/143308684-57384eeb-d26b-4b1b-9005-df31711e495e.png)

So, I'm wondering if it's possible to extend `Diagnostic` interface to add an option to carry such stacktraces from inlining. 
I think that would make these error more clear.

Could anyone dive into this thing? I don't know who should I ping to start a discussion.

**Comment by nicolasstucki** [comment]
This example
```scala
trait Foo[X]:
  def foo: Int

inline def second[A]: Int = compiletime.summonInline[Foo[A]].foo

inline def first[A]: Int = second[A] + 42

def foo = first[String]
```
fails with 
```
8 |def foo = first[String]
  |          ^^^^^^^^^^^^^
  |          no implicit argument of type Foo[String] was found
  | This location contains code that was inlined from Foo.scala:4
  | This location contains code that was inlined from Foo.scala:6
```
which seems to be correct. The `summonInline` was executed at inline site which is at the call of `first[String]`. Then we output the inline stack which points to the call of `second[A]` and `summonInline[Foo[A]]`.

**Comment by nicolasstucki** [comment]
For the first case 
```scala
// Main.scala
object Main:
  def main(args: Array[String]): Unit =
     inline def v2 =
       InlineMac.sample(
        "foo" // <- the actual error position was here
       )
     inline def v1 = v2

     v2  // [error] Error <- reported error position is here
```
the error is
```
0 |     v2  // [error] Error <- reported error position is here - wrong
   |     ^^
   |     Error
   | This location contains code that was inlined from Foo2.scala:6
   | This location contains code that was inlined from Foo2.scala:5
```
which points to the macro expansion site. This is the place where the error happened. It also points out the was reported on the `"foo"` string which was in code inlined by `InlineMac.sample(...)`. It seems to have all the correct positions.

**Comment by nicolasstucki** [comment]
What we can improve is how the inline stack is reported. We could show the code and not only the line number.

**Comment by deusaquilus** [comment]
@dos65 @nicolasstucki Is #14002 supposed to be the solution to this issue? Or is there something else needed?

**Comment by nicolasstucki** [comment]
From the dotty perspective #14002 is the solution. But metals also needs to do a similar improvement.

**Comment by dos65** [comment]
@tgodzik The plan was to expand the diagnostic framework to carry this additional info for inline error, but I haven't had time to prototype this thing yet.

**Comment by nicolasstucki** [comment]
#14002 does not change anything for metals. The positions already contain the necessary information, it is a matter of displaying it correctly. The code in #14002 can be used as a reference to implement the metals version of this.

**Comment by deusaquilus** [comment]
Thanks @nicolasstucki, @dos65 and @tgodzik! Being able to display error underlines on specific terms is super exciting for me!
