### ISSUE TITLE
Constant fold `toInt`, `toLong`, `toDouble`, `toFloat`, `toByte` and `toShort`

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#13990]
## Compiler version

3.1.0

## Minimized code

```Scala
inline val myIntMask = 1 << 4
inline val myLongMask = myIntMask.toLong
```

## Output

```
2 |inline val myLongMask = myIntMask.toLong
  |                        ^^^^^^^^^^^^^^^^
  |                        inline value must have a literal constant type
```

## Expectation

We should be able to constant fold `toInt`, `toLong`, `toDouble`, `toFloat`, `toByte` and `toShort`.

This would also alow us to write `inline val`s with `Short` and `Byte` types as shown bellow
```Scala
inline val myByteMask = 2.toByte
```
This is currently impossible as we do not possess a byte or short numerical postfix in the syntax.

**Comment by mbovel** [comment]
Seems like this should relatively straightforward to extends `foldUnop` to support constant-folding these methods:

https://github.com/lampepfl/dotty/blob/d02ecd02b7acde957600649ad41a1a1b33572f4d/compiler/src/dotty/tools/dotc/typer/ConstFold.scala#L76C15-L90

Maybe good for a spree?

**Comment by mbovel** [comment]
Please ignore the 2 previous message from the Scala Center bot. Teams for the next spree can be found here: https://airtable.com/shrSni1OItSuErosU/tblLEWc2ISeGHPbsc. Sorry for the spam!
