### ISSUE TITLE
An opaque type should not be covariant when the underlying type is invariant

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#13997]
## Compiler version

3.1.0
## Minimized code

```Scala
opaque type CovariantArray[+A] = Array[A]

object CovariantArray:
  def crash() =
    val stringArray: CovariantArray[String] = Array("foo", "bar")
    val anyArray: CovariantArray[Any] = stringArray
    anyArray(0) = 42
    stringArray(0).length

CovariantArray.crash()
```

## Output

```scala
java.lang.ArrayStoreException: java.lang.Integer
	at Playground$CovariantArray$.crash(main.scala:9)
	at Playground$.<clinit>(main.scala:12)
	... 13 more
```

## Expectation
Should not compile

**Comment by KacperFKorban** [comment]
Looks like a soundness issue. For non-primitives, it throws `ClassCastException` at runtime, with no compilation errors.
```scala
case class Invariant[A](var a: A)

opaque type CovariantArray[+A] = Invariant[A]

object CovariantArray:
  def crash() =
    val stringArray: CovariantArray[String] = Invariant("foo")
    val anyArray: CovariantArray[Any] = stringArray
    anyArray.a = 42
    stringArray.a.length

@main
def main =
  CovariantArray.crash()
```

Stacktrace:

```
Exception in thread main: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
    at method crash in main$package$CovariantArray$:10 
    at method main in main.scala:14
```

**Comment by smarter** [comment]
The variance checker on top-level types should be called from https://github.com/lampepfl/dotty/blob/51828cc215ac2b181b6a978144e33e971ba01589/compiler/src/dotty/tools/dotc/transform/PostTyper.scala#L380, I don't know if it's not called at all here or if the check is incomplete.

**Comment by smarter** [comment]
>   opaque type CovariantArray[+A] = Array[A]

We can already achieve something like this using wildcards: https://github.com/lampepfl/dotty/blob/51828cc215ac2b181b6a978144e33e971ba01589/library/src/scala/IArray.scala#L8, more complicated checks don't seem worth it (and would be very hard to implement correctly I think).

**Comment by prolativ** [comment]
The trick with a wildcard will indeed prevent you from inserting an `Int` to an array of `String`s but then you can't even insert a `String`, which should work:
```scala
opaque type CovariantArray[+A] = Array[_ <: A]

object CovariantArray:
  def test() =
    val stringArray: CovariantArray[String] = Array("foo", "bar")
    stringArray(0) = "baz"

@main def run() =
  CovariantArray.test()
```

```scala
[error] Found:    ("baz" : String)
[error] Required: stringArray.T
```

**Comment by smarter** [comment]
In any case you can always use `@uncheckedVariance` if you believe you know better than the compiler.

**Comment by prolativ** [comment]
@smarter where should I put the annotation? I tried to put it in different places to make my example work but the code still doesn't compile.

**Comment by smarter** [comment]
```scala
type CovariantArray[+A] = Array[A @scala.annotation.unchecked.uncheckedVariance]
```

**Comment by prolativ** [comment]
OK I thought one would need to put the annotation on the wildcard (which doesn't seem to be possible BTW - is this a bug?)

**Comment by smarter** [comment]
I don't understand what you mean, which wildcard would you put an annotation on? But this discussion is now completely unrelated to the original bug.
