### ISSUE TITLE
Wildcard capture not working for an abstract type

### ISSUE THREAD

**Issue by TomasMikula** [lampepfl/dotty#14008]
## Compiler version

3.1.0

## Minimized code

```Scala
trait Collection[F[_]] {
  def isEmpty[A](fa: F[A]): Boolean
  
  def isEmpty_(f: F[?]): Boolean =
    isEmpty(f) // type mismatch
}
```

## Output

```scala
Found:    (f : F[?])
Required: F[A]

where:    A is a type variable
          F is a type in trait Collection with bounds <: [_] =>> Any
```

## Expectation

It should typecheck.

## Notes

It seems essential for reproducing the problem that the `F` in `F[?]` is an abstract type.

**Comment by Atry** [comment]
Similar to #7864

**Comment by TomasMikula** [comment]
Yes, thanks for the link @Atry.

I still wonder, what is it about concrete types that justifies wildcard capture, that is absent from abstract types?

**Comment by Atry** [comment]
``` scala
trait Collection[F[_]] {
  type E = F[_]
}

object MyCollection extends Collection[[X] =>> Either[X, X]]
```
Now `MyCollection.E` is `Either[X, X] forSome { type X }`, which is supposed to be forbidden in Scala 3.

**Comment by TomasMikula** [comment]
Right, but being forbidden for the sake of being forbidden is a weird argument.

It is an irregularity of the language that concrete types get special treatment.
I would like to know what justifies this, namely, what trouble would `F[?]` get us into, or, to phrase things positively, what is the property of concrete types that allows application to wildcard type, that does not hold about types in general.

**Comment by odersky** [comment]
A wildcard type of a class can be regarded as a class with an unspecified type member. I.e.
```scala
class C[T]   ===>    class C { type T }
          C[?]   ===>    C
```
The same trick is not available for abstract types. Scala 2 maps them to existential types, but existential types were never working fully correctly and in the interest of simplicity we got rid of them in Scala 3.

**Comment by TomasMikula** [comment]
Thanks for the explanation. Then a possible solution suggests itself: require implicit evidence, say `ClassType[C]`, to be in scope for wildcard applications of `C[_]`. (NB, the `ClassType` itself would have to be kind-polymorphic.)

`ClassType` could be useful elsewhere, too: as evidence of injectivity of abstract types, for the purposes of pattern matching.
