### ISSUE TITLE
Scala 2 regression: Private implicit conversion in companion object scope is not found inside companion class

### ISSUE THREAD

**Issue by neko-kai** [lampepfl/dotty#14013]
## Compiler version

3.1.0 and 3.1.1-RC1

## Minimized code

```Scala
import LightTypeTagInheritance._
// import LightTypeTagInheritance.Ctx // this doesn't work either

trait LightTypeTagRef

object LightTypeTagInheritance {
  private final case class Ctx(self: LightTypeTagInheritance) {
    def next(): Ctx = Ctx(self)
  }
  private implicit final class CtxExt(private val ctx: Ctx) extends AnyVal {
    def isChild(selfT0: LightTypeTagRef, thatT0: LightTypeTagRef): Boolean = ctx.self.isChild(ctx.next())(selfT0, thatT0)
  }
}

class LightTypeTagInheritance {
  
  def isChild(s: LightTypeTagRef, t: LightTypeTagRef): Boolean = {
    isChild(new Ctx(this))(s, t)
  }
  
  private def isChild(ctx: Ctx)(s: LightTypeTagRef, t: LightTypeTagRef): Boolean = {
    ctx.isChild(s, t)
  }
  
}

object App extends App {
  println(LightTypeTagInheritance)
}
```

Scastie: https://scastie.scala-lang.org/BfgPFl4wR9KewXSVPFCXFg

## Output

```scala
value isChild is not a member of LightTypeTagInheritance.Ctx, but could be made available as an extension method.

The following import might fix the problem:

  import LightTypeTagInheritance.CtxExt
```

## Expectation

Expected to compile, as in Scala 2 (https://scastie.scala-lang.org/urqciNvJRPWdhYPH8SGrjQ)

Workaround: changing `CtxExt` from `private` to `private[LightTypeTagInheritance]` fixes the issue

**Comment by prolativ** [comment]
Interestingly this works if you move `import LightTypeTagInheritance._` from the top level to the inside of `class LightTypeTagInheritance`. Honestly speaking I'm not sure if this is a bug or a feature.

**Comment by neko-kai** [comment]
@prolativ 
This is a bug, because this implicit is not dependent on the import one way or another - it's in `Ctx`'s implicit scope, so it should be available without imports - and in Scala 2 it is, with no imports in the source code (https://scastie.scala-lang.org/mZEPz1g9TXqiTmWizi5JHw)

```scala

trait LightTypeTagRef

object LightTypeTagInheritance {
  private final case class Ctx(self: LightTypeTagInheritance) {
    def next(): Ctx = Ctx(self)
  }
  private implicit final class CtxExt(private val ctx: Ctx) extends AnyVal {
    def isChild(selfT0: LightTypeTagRef, thatT0: LightTypeTagRef): Boolean = ctx.self.isChild(ctx.next())(selfT0, thatT0)
  }
}

class LightTypeTagInheritance {
  
  def isChild(s: LightTypeTagRef, t: LightTypeTagRef): Boolean = {
    isChild(new LightTypeTagInheritance.Ctx(this))(s, t)
  }
  
  private def isChild(ctx: LightTypeTagInheritance.Ctx)(s: LightTypeTagRef, t: LightTypeTagRef): Boolean = {
    ctx.isChild(s, t)
  }
  
}

object App extends App {
  println(LightTypeTagInheritance)
}
```

**Comment by neko-kai** [comment]
Forgot one detail: changing `CtxExt` from `private` to `private[LightTypeTagInheritance]` fixes the issue too

**Comment by prolativ** [comment]
Sorry, for some reason I thought you expected this to work by having the implicit conversion brought into scope by the wildcard import.
You seem to be right that the conversion should be available in the implicit scope of `Ctx`.
First I thought this might be a bug related to this change in the language spec https://docs.scala-lang.org/scala3/reference/dropped-features/this-qualifier.html where for some reason the access qualifier was inferred as `private[this]` instead of just `private`.
But now I'm quite confused because when I was trying to minimize this further I wrote this piece of code
```
import scala.language.implicitConversions

case class Bar(i: Int)

object Foo {
  private implicit def iToBar(i: Int): Bar = Bar(i)
}

import Foo._

class Foo {
  def i: Bar = 1
}

object App extends App {
  println((new Foo).i)
}
```
Which I expected to compile but it works neither in scala 3 nor 2. But in both cases this starts to compile when I make the implicit conversion public (`private[Foo]` doesn't help)

**Comment by prolativ** [comment]
Sorry, my bad. In my example both `private` and `private[Foo]` work for both scala 2 and 3 if `import Foo._` is moved into `class Foo` so this still doesn't minimize the problem with inferred `this`.

**Comment by prolativ** [comment]
Minimized example:
```scala
object Foo {
  case class Bar(i: Int)

  private implicit class BarOps(bar: Bar) {
    def twice = Bar(bar.i * 2)
  }
}

class Foo {
  def bar = Foo.Bar(1).twice
}

object App extends App {
  println((new Foo).bar)
}
```
