### ISSUE TITLE
Compile error with case class companion object extending trait defining `unapply` 

### ISSUE THREAD

**Issue by lolgab** [lampepfl/dotty#14017]
## Compiler version

`3.1.0`

## Minimized code

```scala
trait Unapply[T] {
  def unapply(s: T): Option[String]
}
case class Foo(s: String)
object Foo extends Unapply[Foo]
```

## Output

```scala
[error] -- [E007] Type Mismatch Error: /Users/lorenzo/scala/repro-scala3-bug/repro.scala:4:0 
[error] 4 |case class Foo(s: String)
[error]   |^
[error]   |Found:    (x$1 : Foo)
[error]   |Required: Option[String]
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## Expectation

in Scala 2.13.7 this code compiles just fine.
My best guess is that this is related to [Option-less pattern matching](https://docs.scala-lang.org/scala3/reference/changed-features/pattern-matching.html) in Scala 3. But should't it be compatible with Scala 2 pattern matching?
This is currently used in [scalatags](https://github.com/com-lihaoyi/scalatags) and was discovered while trying to migrate it to Scala 3.

**Comment by odersky** [comment]
There's no expectation that `unapply`s should have the same type in Scala 2 and Scala 3.
