### ISSUE TITLE
Adding mutable.BufferLike to whitelist breaks partest

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#1401]
Uncommenting this line

    #./scala-scala/src/library/scala/collection/mutable/BufferLike.scala

in scala-collections-whitelist breaks partest, when run with all the other test but succeeds when `compileStdLib` is run as the only test. Unfortunately, the only debug info I can see is this:

    !! 306 - pos/compileStdLib                         [compilation failed]

    # Failed test paths (this command will update checkfiles)
    test/partest --update-check \
      /Users/odersky/workspace/dotty/tests/partest-generated/pos/compileStdLib
commit 9ccb47ae2e9ae34a0ebd6bafbf6f327b39fc8d4a

Any help in debugging this further would be appreciated.

**Comment by liufengyun** [comment]
Let me take care of this.

**Comment by smarter** [comment]
Unfortunately jenkins is not configured to save all of this currently but you could run it locally and see if some logs are saved in `tests/partest-generated/pos/compileStdLib*`

**Comment by liufengyun** [comment]
Thanks for the tip @smarter , will try as you suggested and find the root cause.

**Comment by DarkDimius** [comment]
@odersky if you go to the link of failed PR
https://scala-ci.typesafe.com/job/dotty-master-validate-partest/1791/console
you can get some of the log file.

The reported error message:
```scala
             ^
/home/jenkins/workspace/dotty-master-validate-partest@2/tests/partest-generated/pos/compileStdLib/BufferLike.scala:62: error: illegal inheritance: self type This & scala.collection.mutable.BufferLike[A, This] of trait BufferLike does not conform to self type scala.collection.generic.Subtractable[A, This & scala.collection.mutable.Buffer[A]] of parent trait Subtractable
trait BufferLike[A, +This <: BufferLike[A, This] with Buffer[A]]
      ^
/home/jenkins/workspace/dotty-master-validate-partest@2/tests/partest-generated/pos/compileStdLib/BufferLike.scala:236: error: overriding method - in trait Subtractable of type (elem: A)This & scala.collection.mutable.Buffer[A];
 method - of type (elem: A)This has incompatible type
  override def -(elem: A): This = clone() -= elem
               ^
/home/jenkins/workspace/dotty-master-validate-partest@2/tests/partest-generated/pos/compileStdLib/BufferLike.scala:248: error: overriding method - in trait Subtractable of type (elem1: A, elem2: A, elems: A*)This & scala.collection.mutable.Buffer[A];
 method - of type (elem1: A, elem2: A, elems: A*)This has incompatible type
  override def -(elem1: A, elem2: A, elems: A*): This = clone() -= elem1 -= elem2 --= elems
               ^
/home/jenkins/workspace/dotty-master-validate-partest@2/tests/partest-generated/pos/compileStdLib/BufferLike.scala:258: error: overriding method -- in trait Subtractable of type (xs: scala.collection.GenTraversableOnce[A])This & scala.collection.mutable.Buffer[A];
 method -- of type (xs: scala.collection.GenTraversableOnce[A])This has incompatible type
  override def --(xs: GenTraversableOnce[A]): This = clone() --= xs.seq
               ^
/home/jenkins/workspace/dotty-master-validate-partest@2/tests/partest-generated/pos/compileStdLib/BufferLike.scala:264: error: overriding method clone in trait Cloneable of type ()scala.collection.mutable.Buffer[A] & This;
 method clone of type ()This has incompatible type
  override def clone(): This = {
               ^
```

**Comment by liufengyun** [comment]
The problem is related to the order of source files for compilation. In JUnit tests, the source files are ordered as they are specified in the whitelist. But in partest, all sources files are in the same folder, they are ordered by file name.

We can reproduce the compilation error by moving `BufferLike.scala` to the top of the white list and then run `sbt "test-only -- --tests=compileStdLib"`.

```
--- a/test/dotc/scala-collections.whitelist
+++ b/test/dotc/scala-collections.whitelist
@@ -14,6 +14,8 @@
 # AnyVal is a synthesized class in Dotty, cannot be compiled from source.
 #./scala-scala/src/library/scala/AnyVal.scala

+./scala-scala/src/library/scala/collection/mutable/BufferLike.scala
+
 ./scala-scala/src/library/scala/Boolean.scala
 ./scala-scala/src/library/scala/Byte.scala
 ./scala-scala/src/library/scala/Char.scala
@@ -83,7 +85,6 @@
 ./scala-scala/src/library/scala/collection/immutable/Seq.scala
 ./scala-scala/src/library/scala/collection/mutable/IndexedSeq.scala
 ./scala-scala/src/library/scala/collection/mutable/ListBuffer.scala
-#./scala-scala/src/library/scala/collection/mutable/BufferLike.scala // works under junit, fails under partest, but can't see more info on the cause

 ./scala-scala/src/library/scala/collection/mutable/ArrayBuilder.scala
```

**Comment by odersky** [comment]
@liufengyun That's an important observation! I condensed it further to find out that compiling

    Buffer.scala BufferLike.scala

works, but reversing the order has the error. I tracked it down to differences in the way type parameters are bound in subclasses. In the OK scenario, Buffer contains several bindings for superclass parameters that it lacks in the error scenario. Will dig further.
