### ISSUE TITLE
Scaladoc for Symbol describes deprecated quote mechanism

### ISSUE THREAD

**Issue by jphmrst** [lampepfl/dotty#14028]
## Compiler version

On the web page https://dotty.epfl.ch/api/scala/Symbol.html , referencing 3.1.2-RC1-bin-20211130-f6b6e50-NIGHTLY

## Minimized example

The scaladoc output reads: 

- For instance, the Scala term `'mysym` will invoke the constructor of the Symbol class in the following way: `Symbol("mysym")`.

But this symbol literal mechanism is no longer supported,

```
[error]     |symbol literal 'user is no longer supported,
[error]     |use a string literal "user" or an application Symbol("user") instead,
[error]     |or enclose in braces '{user} if you want a quoted expression.
[error]     |For now, you can also `import language.deprecated.symbolLiterals` to accept
[error]     |the idiom, but this possibility might no longer be available in the future.
```

## Expectation

The Scaladoc should either drop the reference to the symbol literal mechanism, or include the new syntax, or else include reference to the `import` option.

**Comment by smarter** [comment]
Symbol.scala is part of the scala 2 standard library in https://github.com/scala/scala/blob/2.13.x/src/library/scala/Symbol.scala so please open an issue in the scala 2 bug tracker at https://github.com/scala/bug/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by som-snytt** [comment]
Of either of the three options, I'll PR the first, to just remove the language. The Scala 2 spec was also lacking or lagging.
