### ISSUE TITLE
Union type should be inferred

### ISSUE THREAD

**Issue by epifab** [lampepfl/dotty#14031]
## Compiler version

Scala 3.1.0

## Minimized code

```Scala
extension (xs: List[Int | String])
  def double: List[Int | String] = xs.map {
    case i: Int => i * 2
    case s: String => s + "x2"
  }

List(100, "100").double
```

## Output

```
value double is not a member of List[Matchable].
```

Workaround:
```scala
List[Int | String](100, "100").double 
```

## Expectation

Should the compiler infer List(100, "100") as a List[Int | String] ?

**Comment by bishabosha** [comment]
Thank you for opening this issue, this has come up a few times, and usually it is concluded that union types should only be preserved if the user wrote them (this is marked in the compiler by if a union type is `hard` or `soft`)

**Comment by epifab** [comment]
hi @bishabosha thanks for the quick response!
what do you mean by "if a user wrote them"? do you mean if the user explicitly declares declares the type?
I feel like union types should be treated as first class citizens

**Comment by bishabosha** [comment]
that's right, only if the result type is explicitly declared for whichever definition the expression is bound to. I believe there are some follow up inference issues if we keep unions everywhere, @smarter knows more.

**Comment by odersky** [comment]
Yes, union types are not inferred by design.
