### ISSUE TITLE
Usages of experimentals are not always checked in types

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#14034]
## Compiler version

3.1.1-RC1

## Minimized code

```scala
import annotation.experimental

@experimental trait Exp
@experimental val exp = 1

type Foo = Option[Exp]
type Bar = Option[exp.type]
type Baz = Exp | Int
type Quux = [X] = X match
  case Exp => Int
type Quuz[A <: Exp] = Int
```

## Output

Compiles successfully

## Expectation

The compilation should fail and all the usages of the experimentals should be reported as errors

**Comment by odersky** [comment]
What happens with @deprecated? The two should work exactly the same.

**Comment by nicolasstucki** [comment]
We also miss all these cases with `@deprecated`.

Only one error is emitted for the following example. Scala 2 emits all of them except the `exp.type`.
```scala

@deprecated trait Exp
@deprecated val exp = 1

def test1 = exp // error
def test2(a: Exp) = ()

type Foo0 = Exp
type Foo = Option[Exp]
type Bar = Option[exp.type]
type Baz = Exp | Int // error
type Quux = [X] =>> X match
  case Exp => Int
type Quuz[A <: Exp] = Int
```
See https://scastie.scala-lang.org/U0JDQtjQTBK64CRf7PqPTA for Scala 2 example

**Comment by odersky** [comment]
I think the right fix is to check deprecation and experimental before RefChecks, when we still have the full types.
