### ISSUE TITLE
Experimental given instances partially leaking to nonexperimental code

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#14052]
## Compiler version

3.1.1-RC1

## Minimized code

Case 1:

```scala
import annotation.experimental

trait Foo

@experimental
given experimentalFoo: Foo with {}

val foo = summon[Foo]
```

Case 2:

```scala
import annotation.experimental

trait Foo

@experimental
given experimentalFoo: Foo with {}

given stableFoo: Foo with {}

val foo = summon[Foo]
```

## Output

Case 1:

```scala
[error] object experimentalFoo is marked @experimental and therefore may only be used in an experimental scope.
[error] val foo = summon[Foo]
[error]                      ^
```

Case 2:

```scala
[error] ambiguous implicit arguments: both object experimentalFoo and object stableFoo match type Foo of parameter x of method summon in object Predef
[error] val foo = summon[Foo]
[error]                      ^                   ^
```

## Expectation

Case 1 should fail with `implicitNotFound`, case 2 should compile successfully.

It turns out the current design/implementation of handling experimental definitions might break someone's code (e.g. imagine some given instance gets added as experimental in scala 3.1.2 - then bumping from 3.1.1 to 3.1.2 might break compilation, which should not happen while bumping a patch version).

**Comment by prolativ** [comment]
Interestingly an error might get reported twice with different positions if the given instance is defined inside an experimental companion object

```scala
import annotation.experimental

trait Foo

@experimental
object Foo:
  given experimentalFoo: Foo with {}

val foo = summon[Foo]
```

```scala
[error] object Foo is marked @experimental and therefore may only be used in an experimental scope.
[error] val foo = summon[Foo]
[error]        ^
[error] object Foo is marked @experimental and therefore may only be used in an experimental scope.
[error] val foo = summon[Foo]
[error]                      ^
```

BTW should it be possible to add an experimental companion object to an existing trait/class and vice versa?

**Comment by odersky** [comment]
As discussed verbally, we have decided that the compiler's name resolution and typing should not take into account whether something is experimental or not. So, the current behavior is what we should expect.
