### ISSUE TITLE
Methods from experimental companion objects shadow the generated ones

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#14053]
## Compiler version

3.1.1-CR1

## Minimized code

```scala
import annotation.experimental

case class Foo(i: Int)

@experimental
object Foo:
  def apply(i: Int): Int = i

val foo: Foo = Foo(1)
```

## Output

```scala
[error] Found:    Int
[error] Required: Foo
[error] val foo: Foo = Foo(1)
[error]                ^^^^^^
```

## Expectation

This should compile with a stable compiler. The question is however whether this should compile when experimentals are enabled. Should we disallow adding experimental companion objects to existing traits/classes (and vice versa?) instead?

**Comment by odersky** [comment]
As discussed verbally, we have decided that the compiler's name resolution and typing should not take into account whether something is experimental or not. So, the current behavior is what we should expect.
