### ISSUE TITLE
Union type constraint inferred when type is not explicitly a union

### ISSUE THREAD

**Issue by Lumintorious** [lampepfl/dotty#14060]
## Compiler version

3.1.0

## Minimized code

```Scala
case class Foo(foo: Int)
case class Bar(bar: String)

def showUnion[A, B](obj: A | B) = println(obj.toString)

@main def run() =
  val foo: Foo = Foo(1)
  val fooOrBar: Foo | Bar = Foo(1)

  showUnion(foo) // works, but shouldn't
  showUnion(fooOrBar) // works
```

## Output

```scala
Foo(1)
Foo(1)
```

## Expectation
Expected a type such as `Foo` to not be passable to `showUnion` since it is not an explicit union.
Normally I would say it's fair since `Foo = Foo | Foo`, but in [this issue](https://github.com/lampepfl/dotty/issues/14031) it is mentioned that union types should not be inferred by design unless they are set explicitly.

I don't know if this behaviour is intended or not, however having some sort of way to detect if a type is an **explicit** union or intersection and have other constraints on the `left` and `right` types would make working with inlines/macros/implicits easier in some cases.

**Comment by odersky** [comment]
The _expected_ type A | B is an explicit union, that's what guides type inference.
