### ISSUE TITLE
Missing requirement with transitive self-type annotation

### ISSUE THREAD

**Issue by cornerman** [lampepfl/dotty#14095]
## Compiler version

3.1.0

## Minimized code

```Scala
trait TheThing
trait Dependency { self: TheThing => }
trait Extra { self: Dependency => }
```

## Output

```
-- Error:
1 |trait Extra { self: Dependency => }
  |      ^
  |missing requirement: self type Dependency & Extra of trait Extra does not conform to self type TheThing
  |of required trait Dependency
```

## Expectation

This should compile, like in scala 2.13 and 2.12.

## Workaround

To workaround the issue, you somehow need to explicitly mention the "transitive" self-type, like this:

```scala
trait Extra { self: Dependency with TheThing => }
```

**Comment by smarter** [comment]
This was an intentional change (https://github.com/lampepfl/dotty/pull/474/commits/04eea24326c3a42ad908fe45e204af41b880f2cd), you have to be explicit about the complete self-type now.

**Comment by cornerman** [comment]
@smarter Thank you! Is there a specific reason, why it should be explicit?

**Comment by smarter** [comment]
I think it's just that it makes it easier for both the compiler and the reader to figure out how to interpret the body of the class.

**Comment by cornerman** [comment]
I just had to do some changes in a code-base to cross compile it for scala 2 and scala 3. It felt unintuitive that I had to write down these self-types explicitly. I have to look into the definition of my self-type `Dependency` to find its self-type `TheThing` and write it down as well.

If a type like `Dependency` is defined in a library, I will have to look into that library and copy the self-types from there. If that ever changes, I will have to extend it or clean up manually.

For me, this is equivalent to inheritance: I just implicitly inherit all base-classes and do not have to write down all the transitive base-classes explicitly.

**Comment by cornerman** [comment]
@smarter Any chance that this issue will be revisited or will it clearly stay like it is?

**Comment by smarter** [comment]
You could try raising this in https://contributors.scala-lang.org/ to see what people think but given that we're not really encouraging the use of self-types anymore I wouldn't expect this to change.

**Comment by cornerman** [comment]
Fair enough. Thank you. I did not know that self-types are discouraged nowadays. Though it makes sense, because it often leads to inheritance chains that are difficult to understand.
Nevertheless, when porting projects to scala-3, this can introduce some friction. At least, I had difficulties to understand the error message and it took me some time to fix it.

**Comment by fdietze** [comment]
In this case, a better error message might help to ease the migration path from Scala 2. The error message could contain the rewritten code.
