### ISSUE TITLE
Complete packages if they contain toplevel definitions

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#14101]
## Compiler version

3.1.0-RC2

## Minimized code

In a REPL session:

```Scala
package example:
    def foo = ""

def main =
  exam@@
```

and press TAB (or invoke code completion in IDE)

## Output

No completions are suggested

## Expectation

We should get a suggestion of `example`

In Scala 2 this approach worked with package objects such as widely used `pprint` library and made it much easier to discover the utility methods contained there. This should probably also work for package object in Scala 3.

**Comment by prolativ** [comment]
I believe you meant `We should get a suggestion of example`, right?

**Comment by tgodzik** [comment]
> I believe you meant `We should get a suggestion of example`, right?

You're right! Updated.
