### ISSUE TITLE
Java's String::split() return is inferred as a union with Null

### ISSUE THREAD

**Issue by zanella** [lampepfl/dotty#14111]
## Compiler version
> print scalaVersion
3.1.0

build.sbt:

> scalacOptions ++= Seq("-Yexplicit-nulls")

## Minimized code

```
 "1 2 3".split(" ").map(_.toInt) // Doesn't compile
 "1 2 3".split(" ").nn.map(_.nn.toInt) // Compiles
 "1 2 3".split(' ').map(_.toInt) // Compiles
```

## Output

```scala
[error] 10 |  "1 2 3".split(" ").map(_.toInt) // Doesn't compile
[error]    |  ^^^^^^^^^^^^^^^^^^^^^^
[error]    |  value map is not a member of Array[String | Null] | Null.
[error]    |  An extension method was tried, but could not be fully constructed:
[error]    |
[error]    |      genericArrayOps[T]("1 2 3".split(" "))
```

## Expectation

Override `split(String)` in StringOps ?

**Comment by zanella** [comment]
@bishabosha yes! Forgot to mention that, sorry.

build.sbt: 
> scalacOptions ++= Seq(
>   "-Yexplicit-nulls" // https://docs.scala-lang.org/scala3/reference/other-new-features/explicit-nulls.html
> )

Using `.nn` is a bit cumbersome (`"1 2 3".split(" ").nn.map(_.nn.toInt) // Compiles`), and since `split(separator: Char)` uses the java.String::split() under the hood.

(I've been away from Scala for quite a while now, sorry for any stupid mistake in advance)

**Comment by olhotak** [comment]
It's not possible to use extension methods to replace an existing method, is it? `java.lang.String` already has a `split(String)` method but not a `split(Char)` method. This is why `StringOps` can add a Scala `split(Char)` method, but it cannot change the existing Java `split(String)` method.
