### ISSUE TITLE
TypeDef or ClassDef not matched in class definition tree

### ISSUE THREAD

**Issue by cchantep** [lampepfl/dotty#14149]
## Compiler version

3.1.2-RC1-bin-20211205-94f4118-NIGHTLY

## Minimized code

```Scala
  inline def foo[A]: Unit = ${ fooImpl[A] }

  private def fooImpl[A: Type](using q: Quotes): Expr[Unit] = {
    import q.reflect.*

    val aTpeRepr = TypeRepr.of[A]

    aTpeRepr.classSymbol.foreach { cls =>
      cls.children.foreach {
        _.tree match {
          case tpd: Typed =>
            println(s"tpd = ${tpd.tpt.tpe}")

          case vd: ValDef =>
            println(s"vd = ${vd.tpt.tpe}")

          case td: TypeDef =>
            println(s"td = $td")

          case x =>
            println(s"other = $x / ${x.getClass}")
        }
      }
    }

    '{ () }
  }
```

Tested as below:

```scala
object Union {
  sealed trait UT

  case class UA(n: Int) extends UT

  class UB(val s: String) extends UT
}

foo[Union.UT]
```

## Output

Case `td` is never applied.

If using `ClassDef` it works.

**Comment by smarter** [comment]
> If using ClassDef it works.

Which is what the documentation implies:
```scala
    /** Tree representing a type (parameter or member) definition in the source code */
    type TypeDef <: Definition
...
    /** Tree representing a class definition. This includes anonymous class definitions and the class of a module object */
    type ClassDef <: Definition
```
ClassDef is not a subtype of TypeDef, so something matching as a ClassDef won't match as a TypeDef.

**Comment by cchantep** [comment]
The issue is in quotes, where:

```
type TypeDef = tpd.TypeDef
type ClassDef = tpd.TypeDef
```

**Comment by smarter** [comment]
> type ClassDef = tpd.TypeDef

This is an implementation detail intentionally not exposed to the user (notice it's in compiler/ and not in library/), when you do `case td: TypeDef` because TypeDef is an abstract type in Quotes.scala the compiler goes looking for an instance of `TypeTest[Tree, TypeDef]` and will end up using this implementation which excludes ClassDef: https://github.com/lampepfl/dotty/blob/0b55c7d439f57a880b9608bb3087dcd5800c8825/compiler/src/scala/quoted/runtime/impl/QuotesImpl.scala#L319-L323

**Comment by smarter** [comment]
For more information on TypeTest, see https://dotty.epfl.ch/docs/reference/other-new-features/type-test.html

**Comment by cchantep** [comment]
I know the `TypeDefTypeTest`, but this implementation is quite surprising to me from the API design pov
