### ISSUE TITLE
Match type on parameterized trait doesn't preserve input parameter in type variable

### ISSUE THREAD

**Issue by s5bug** [lampepfl/dotty#14151]
## Compiler version

3.1.0, 3.1.1-RC1, 3.1.1-RC2

## Minimized code

```scala
sealed trait BoundedPair[A, B <: A]

type Second[A, T <: BoundedPair[A, _ <: A]] <: A = T match {
  case BoundedPair[A, b] => b
}
```

## Output

```scala
Found:    b
Required: A

where:    b is a type in type Second with bounds <: Playground.BoundedPair[?, ?]#A
```

## Expectation

`Second[Animal, BoundedPair[Animal, Cat]]` ⇒ `Cat`

**Comment by s5bug** [comment]
Note that this is also true with just

```scala
sealed trait Bounded[B]

type Second[A, T <: Bounded[_ <: A]] <: A = T match {
  case Bounded[b] => b
}
```

but I was not sure whether that is the same issue or not.

**Comment by OlivierBlanvillain** [comment]
Probably related to #11205

**Comment by SethTisue** [comment]
> not sure whether that is the same issue or not

looks like it to me and Dale, this looks like the one to investigate since it's simpler. we're digging into it, but we're still exploring/flailing and don't have a theory yet

**Comment by SethTisue** [comment]
This can be simplified one step further:

```scala
sealed trait Single[B]
type Retrieve[A, T <: Single[A]] <: A = T match
  case Single[b] => b

-- [E007] Type Mismatch Error: -------------------------------------------------
3 |  case Single[b] => b
  |                    ^
  |                    Found:    b
  |                    Required: A
```
