### ISSUE TITLE
parameter of anonymous function cannot be `given` ?

### ISSUE THREAD

**Issue by armanbilge** [lampepfl/dotty#14167]
## Compiler version

3.1.1-RC1

## Minimized code

Given:
```scala
class Foo:
  def bar = ()
```

This compiles:

```scala
Option(new Foo).map { implicit foo: Foo =>
  summon[Foo].bar
}
```

So does this:
```scala
for {
  given Foo <- Option(new Foo)
} yield summon[Foo].bar
```

But, none of these do. Am I writing it wrong, or is it just not possible?

```scala
Option(new Foo).map { given Foo =>
  // abstract givens cannot be annonymous
  summon[Foo].bar
}
```

```scala
Option(new Foo).map { (given Foo) =>
  // illegal start of simple expression
  summon[Foo].bar
}
```

```scala
Option(new Foo).map { (given foo: Foo) =>
  // illegal start of simple expression
  summon[Foo].bar
}
```

```scala
Option(new Foo).map { given foo: Foo =>
  // ; expected but => found
  summon[Foo].bar
}
```

**Comment by som-snytt** [comment]
`Option(C()).map { ((x: C) ?=> summon[C])(using _) }`

**Comment by som-snytt** [comment]
`Option(C()).map { case given C => summon[C] }`

As mentioned under "pattern-bound givens", same as `for given`.

https://docs.scala-lang.org/scala3/reference/contextual/givens.html

**Comment by armanbilge** [comment]
Aha! That's a reasonable syntax, thanks :)

I'd still love to see something similar to Scala 2, if possible, so we can skip the `case` keyword.
