### ISSUE TITLE
Constructor proxies of classes with type parameters are not exported

### ISSUE THREAD

**Issue by dcascaval** [lampepfl/dotty#14160]
## Compiler version

3.1.0

## Minimized code

```Scala
object api:
  export impl.*

object impl:
  class Bar[T](foo: T)

object Test1:
  import api.*
  val value = Bar(0) // Not Found: Bar

object Test2:
  import impl.*
  val value = Bar(0) // Works

object Test3:
  import api.*
  val value = new Bar[Int](0) // Works
```

## Output

```scala
[error] 10 |  val value = Bar(0) // Not Found: Bar
[error]    |              ^^^
[error]    |              Not found: Bar
```

## Expectation

When exporting a class that has a type parameter via a facade object, should be able to construct that class without error, having `T` be inferred rather than explicitly specified, as is the case when the class is imported directly from the implementation object.

**Comment by smarter** [comment]
It works if you do `new Bar(0)`, it looks like https://github.com/lampepfl/dotty/pull/12311 needs to be extended to handle exporting constructor proxies of classes with type parameters too.
