### ISSUE TITLE
How can I get the dotc command from release code?

### ISSUE THREAD

**Issue by nirvana198801** [lampepfl/dotty#14172]
Hi ,
   I want to use the dotc command to decompile some classes file, but i can't find the  dotc command from release code.
it only have scalac / common / scaladoc..
   How can I get the dotc command from release code? my os is ubunut.
   Thanks!

**Comment by som-snytt** [comment]
Probably they will ask you not to use the issue tracker for user questions, but use discord instead.

The command is scalac in releases:
```
➜  ~ scalac -version
Scala compiler version 3.1.0 -- Copyright 2002-2021, LAMP/EPFL
```

**Comment by SethTisue** [comment]
https://users.scala-lang.org for questions, please
