### ISSUE TITLE
-from-tasty compilation fails on correct scala.js code

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/dotty#14178]
## Compiler version

Newest master - c94b333
The bug occurs also on 3.1.0

## Minimized code

```Scala
import scala.scalajs.js

trait Foo[A] {
    def p: js.Promise[A] = ???
    def onFulfilled: js.Function1[A, Unit | js.Thenable[Unit]] = ???
    def onRejected: js.Function1[Any, Unit | scala.scalajs.js.Thenable[Unit]] = ???

    p.`then`[Unit](
    onFulfilled,
    js.defined(onRejected)
    )
}
```

## Output
For command:
`~/dotty/dist/target/pack/bin/scalac -scalajs -from-tasty target/scala-3.1.2-RC1-bin-SNAPSHOT/classes/Foo.tasty`

```scala
-- Error: src/main/scala/test2.scala:8:4 ---------------------------------------
8 |    p.`then`[Unit](
  |    ^^^^^^^^^^^^^
  |undefined: this.p.then # -1: TermRef(AppliedType(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class scalajs)),object js),Promise),List(TypeRef(ThisType(TypeRef(ThisType(TypeRef(ThisType(TypeRef(NoPrefix,module class <root>)),module class <empty>)),trait Foo)),type A))),then) at readTasty
-- Error: src/main/scala/test2.scala:10:4 --------------------------------------
10 |    js.defined(onRejected)
   |    ^^^^^^^^^^
   |undefined: scala.scalajs.js.defined.apply # -1: TermRef(TermRef(TermRef(ThisType(TypeRef(NoPrefix,module class scalajs)),object js),defined),apply) at readTasty
2 errors found
```

## Expectation
The same as for standard compilation which passes.

**Comment by smarter** [comment]
Does this also happen if you add scalajs-library_2.13 to the classpath?

**Comment by pikinier20** [comment]
No, it doesn't. So probably somehow the library is missing in classpath argument passed to Scaladoc

**Comment by pikinier20** [comment]
Okey, there's no bug. I realized that it might be related to sbt version since we've made some changes in scalacOptions resolution for doc task. The problem is gone on sbt 1.5.3+ since from this version the `-scalajs` flag is passed to Scaladoc.
