### ISSUE TITLE
Documentation for Array.equals incorrect

### ISSUE THREAD

**Issue by p2titus** [lampepfl/dotty#14179]
## Compiler version
3.1.0

## Minimized code

```Scala
object Test {
  val xs = Array(1,2,3)
  val ys = Array(2,3,1)

  def main(args: Array[String]): Unit = {
    println(xs == ys)
    println(xs.sorted == ys.sorted)
    println(xs.sorted.equals(ys.sorted))
    println(xs.sorted.sameElements(ys.sorted))
  }
}
```

## Output
```
false
false
false
true
```

## Expectation
```
false
false
true
true
```

The documentation for [`Array.equals`](https://scala-lang.org/api/3.x/scala/Array$.html#equals-fffff676) would suggest we would expect the last two tests to match always. However, this is not the case. 

This [Scala 2.8](https://docs.scala-lang.org/overviews/collections/equality.html) page would suggest that the equals implementation is elementwise. However, Java implements equality on objects by reference, and I suspect that's what `equals` is actually implementing.

**Comment by som-snytt** [comment]
`Array.equals`, a method on the companion to compare two arrays, is different from `anArray.equals`.

**Comment by p2titus** [comment]
Cheers, I feel a bit stupid now

**Comment by som-snytt** [comment]
It's a hazard of how the docs for companions are accessed, and also how bad the signature for `equals` is. Even counting args is susceptible to `Array(42).equals(1,2)`, which looks like equals with two args.
