### ISSUE TITLE
Implicit conversion implemented as `val` is not resolved

### ISSUE THREAD

**Issue by cchantep** [lampepfl/dotty#14181]
## Compiler version

3.1.2-RC1-bin-20211222-c94b333-NIGHTLY-git-c94b333

## Minimized code

```scala
object Foo
object Bar

implicit val bar2foo: Bar.type => Foo.type = _ => Foo

implicitly[Foo.type](Bar)
```

## Output

```
-- [E007] Type Mismatch Error: -------------------------------------------------
1 |implicitly[Foo.type](Bar)
 */
```

## Expectation

`Foo` should be successfully returned, as below.

```scala
implicit def foo2bar(_foo: Foo.type): Bar.type = Bar

implicitly[Bar.type](Foo)
// OK => val res0: Bar.type = Bar$@394ba91a
```

**Comment by smarter** [comment]
Implicit instances of functions are no longer considered as implicit conversions in scala 3 (it was problematic since List extends Function1 for example, and in general we're trying to reduce the amount of implicit conversions in common use)

**Comment by som-snytt** [comment]
That's a weird idiom for `implicitly`, so thanks! Normally I would `Bar: Foo.type`.

This change was a real puzzler-killer, or maybe we should say "puzz kill" as in "buzz kill".

**Comment by cchantep** [comment]
> Implicit instances of functions are no longer considered as implicit conversions in scala 3 (it was problematic since List extends Function1 for example, and in general we're trying to reduce the amount of implicit conversions in common use)

Where is that documented?

**Comment by som-snytt** [comment]
It says it must be an `implicit def` but doesn't highlight the diff. I thought it was mentioned somewhere, but perhaps only in the forums.

https://docs.scala-lang.org/scala3/reference/changed-features/implicit-conversions.html
