### ISSUE TITLE
Allow overriding inline members of anonymous instance defined inside inline method

### ISSUE THREAD

**Issue by Iltotore** [lampepfl/dotty#14226]
## Compiler version

3.1.0

## Minimized code

```scala
trait Test {

  inline def msg: String
}

//Does not compile
inline def foo: Test = new Test {

  override inline def msg: String = "hello" 
}


//Compiles
class HelloTest extends Test {

  override inline def msg: String = "hello"
}

inline def foo: Test = new HelloTest
```
## Output

The first example does not compile and gives an
```scala
Implementation restriction: nested inline methods are not supported
```

## Expectation

I would expect the first sample to compile and behave like the second one. The "nested inline" error seems to be a false-positive.

**Comment by nicolasstucki** [comment]
The first pattern is not supported as it has an inline method within an inline method. The error message clearly states this.

Furthermore, both of these patterns will not work as it will not be possible to call `foo.msg`.

**Comment by Iltotore** [comment]
> Furthermore, both of these patterns will not work as it will not be possible to call foo.msg.

Actually, the second example compiles and run as expected. I use it in one of my metaprogramming-related project for refined types and it behave consistently and as expected at both compile time and runtime.
