### ISSUE TITLE
Failure to parse array annotation argument from Scala 2 dependency

### ISSUE THREAD

**Issue by 14sxlin** [lampepfl/dotty#14223]
I am using a scala 2.13 library Kantan ("com.nrinaudo" % "kantan.csv-commons" % "0.6.2" cross CrossVersion.for3Use2_13) in scala 3.1.0 of cross version.

When I try to provide a implicit instance the compiler crashes. (Using given has the same result.)

Did I do something wrong ? Or Any Idea?  I think the library may have used some scala 2 macro so it won't compile in scala 3. If that is true , it will be better if we has more specific compile error output.

I found this may help : https://github.com/scalacenter/bloop/issues/1272

## Compiler version

scalaVersion: 3.1.0
sbt: 1.6.1

## Minimized code
full demo: https://github.com/14sxlin/compileerror

In build.sbt
```Scala
val scala3Version = "3.1.0"

lazy val root = project
  .in(file("."))
  .settings(
    name := "compileerrordemo",
    version := "0.1.0-SNAPSHOT",
    scalaVersion := scala3Version,
    libraryDependencies += "com.nrinaudo" % "kantan.csv-commons" % "0.6.2" cross CrossVersion.for3Use2_13
  )
```
In Main.scala
```Scala
import kantan.csv.CellEncoder

@main def encode: Unit =

  implicit val cellEncoder = new CellEncoder[String] {
    override def encode(str: String): String =
      str
  }
```

## Output

```scala
[error] Found:    Seq[scala.annotation.Annotation]
[error] Required: Array[String]
[error] one error found
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

There is no useful info in compile output.

**Comment by smarter** [comment]
The compiler trips up while unpickling the following annotation: https://github.com/nrinaudo/kantan.codecs/blob/08ccfc69c9982d3b59800b7c575c4adf00c12831/core/shared/src/main/scala/kantan/codecs/Encoder.scala#L41
The code that unpickles an annotation argument array is at https://github.com/lampepfl/dotty/blob/b4d03347e46d82cbefc9b9b88fe410a1ceac9551/compiler/src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala#L971-L980 and looks weird indeed: array elements don't need to be annotations themselves,  so we shouldn't create a SeqLiteral with element type Annotation.

**Comment by michelou** [comment]
@smarter 🏆
