### ISSUE TITLE
Weird inference between Int and Double

### ISSUE THREAD

**Issue by cchantep** [lampepfl/dotty#14229]
## Compiler version

`3.1.2-RC1-bin-20211222-c94b333-NIGHTLY-git-c94b333`

## Minimized code

```scala
List(0.123D, 1).toArray
```

## Output

    Array[Double] = Array(0.123, 1.0)

Integer `1` is converted to `Double` value.

## Expectation

    Array[Any] = Array(0.123, 1)

As bellow with boxing workaround:

```
List[Any](0.123D, 1).toArray
// => Array[Any] = Array(0.123, 1)
```

**Comment by cchantep** [comment]
Rather inference related

**Comment by som-snytt** [comment]
They called it "harmonization", but now I prefer "weird inference."

**Comment by smarter** [comment]
> Integer 1 is converted to Double value.

This is as specified: https://docs.scala-lang.org/scala3/reference/dropped-features/weak-conformance.html / https://docs.scala-lang.org/scala3/reference/dropped-features/weak-conformance-spec.html

A value of type Int may also be converted to a value of type Double because of the implicit conversion present in the standard library: https://github.com/scala/scala/blob/4b2151cbe4c857d49556b70c3fa0f5e236fd7754/src/library/scala/Int.scala#L484

**Comment by cchantep** [comment]
> They called it "harmonization", but now I prefer "weird inference."

Quite weird

**Comment by dwijnand** [comment]
The motivation (or at least one of the big ones) is to avoid the imposition of having to write ".0".

**Comment by cchantep** [comment]
Don't understand. Anyway it convert an integer to a double, which is not the wanted behaviour for me.

**Comment by dwijnand** [comment]
It will only convert if the conversion is not lossy.  What I meant to say is that it allows you to write `List(1.2, 2, 3.4, 4, 4.6, 5)` instead of `List(1.2, 2.0, 3.4, 4.0, 4.6, 5.0)`.

**Comment by cchantep** [comment]
Anyway, it changes the type. I can hardly see the rationale of having such behaviour as the default one.
It has value if it can be explicitly required, but not by default.

**Comment by som-snytt** [comment]
@cchantep or contribute a compiler option or more likely a scalafix lint that allows you to fail your compilation.

**Comment by cchantep** [comment]
Yes options like that to make it explicit.
