### ISSUE TITLE
Scaladoc: Write basic documentation for static site

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/dotty#14237]
What features work and what features don't work, what can be expected to work.

How to add CSS files to style project documentation (if necessary).

**Comment by pikinier20** [comment]
The documentation is present here: https://dotty.epfl.ch/docs/usage/scaladoc/static-site.html

**Comment by SethTisue** [comment]
can it be moved to https://docs.scala-lang.org ?

**Comment by pikinier20** [comment]
For sure it should be in more visible place.

**Comment by deusaquilus** [comment]
Hey Guys, where is this now? Is it working? I really want to try using Dotty's Scaladoc to build a static site for protoquill.
