### ISSUE TITLE
New unreachable warning on Int literals since 3.1.0

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#14239]
## Compiler version

3.1.1-RC2

## Minimized code

```Scala
object Test extends App {
  0 match {
    case 0 => println("zero")
    case -1 => throw new IllegalArgumentException("-1")
  }
}
```

## Output

```scala
[warn] ./Test.scala:4:10: Unreachable case
[warn]     case -1 => throw new IllegalArgumentException("-1")
[warn]          ^^
```

## Expectation

in Scala 3.1.0 this did not make a warning. I'm not sure what happened since, but I believe that mismatching singleton types were not enough to dismiss a case in general due to overriding of `equals`, perhaps there is a special case for ints?

**Comment by dwijnand** [comment]
No, I think it's because we no longer widen singletons.  Does this happen for non primitives?

**Comment by bishabosha** [comment]
with plain vals there is no error, with objects there is (both are consistent with 3.1.0 behaviour):
```scala
object Test extends App {

  class Foo
  val Bar: Foo = new Foo {}
  val Baz: Foo = new Foo {}

  (Bar: Bar.type) match {
    case _: Bar.type => println(Bar)
    case _: Baz.type => throw new IllegalArgumentException(Baz.toString)
  }
}
```
```scala
object Test extends App {

  trait Foo
  object Bar extends Foo
  object Baz extends Foo

  Bar match {
    case Bar => println(Bar)
    case Baz => throw new IllegalArgumentException(Baz.toString)
  }
}
```

**Comment by dwijnand** [comment]
So I think we're all good then.  It's not special-casing int's, per say, it's just that they're not just singleton types but constant types, and constants can't have custom, funky equals.

**Comment by bishabosha** [comment]
ok seems if you keep a singleton bound on the scrutinee for reference types it behaved like this in 3.1.0 too:
```scala
object Test extends App {

  class Foo
  val Bar: Foo = new Foo {}
  val Baz: Foo = new Foo {}

  (Bar: Bar.type & Singleton) match {
    case Bar => println(Bar)
    case Baz => throw new IllegalArgumentException(Baz.toString)
  }
}
```
^ will make in 3.1.0
```scala
[warn] ./Test.scala:9:10: Unreachable case
[warn]     case Baz => throw new IllegalArgumentException(Baz.toString)
[warn]          ^^^
```
