### ISSUE TITLE
inline match over Option[String] not accept  None as scrutinee 

### ISSUE THREAD

**Issue by rssh** [lampepfl/dotty#14245]
## Compiler version

Master on state of Tue Jan 11 00:12:54 EET 2022

## Minimized code

```Scala

object Test {

  inline def get: Option[String] = None

  private transparent inline def fun: Unit =
    inline get match
      case Some(x) => println("value = $x")
      case None    => println("value not set")

  fun

}
```

## Output

```scala
[info] compiling 1 Scala source to /Users/rssh/tests/dotty/compileTimeNoCast/target/scala-3.1.2-RC1-bin-SNAPSHOT/classes ...
[error] -- [E007] Type Mismatch Error: /Users/rssh/tests/dotty/compileTimeNoCast/src/main/scala/x/Test.scala:12:2 
[error] 12 |  fun
[error]    |  ^^^
[error]    |  Found:    Option[String]
[error]    |  Required: None.type
[error]    | This location contains code that was inlined from Test.scala:5
[error]    | This location contains code that was inlined from Test.scala:8
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 3 s, completed 11 Jan 2022, 00:14:05
```

## Expectation

should be compiled.

**Comment by rssh** [comment]
// discovered during porting example from #12039. into #14234

**Comment by som-snytt** [comment]
Where we used to say, "full disclosure", we now say "transparent inline." Without much experience, this seems expected to me.

Also, the elimination of closures ought to be called "disclosure".

**Comment by rssh** [comment]
slightly minimized:
```
object Test {

  inline def get: Option[String] = None

  inline def fun: Unit =
    inline get match
      case Some(x) => println("value = $x")
      case None    => println("value not set")

  fun

}
```

**Comment by rssh** [comment]
It has supposed to work in April 2021.  But yes, expectations can change over time.

**Comment by dwijnand** [comment]
> Without much experience, this seems expected to me.

I likely have the same or less experience with inline semantics, but this doesn't seem expected to me, given the explicit type annotation on `get`.  Now, had `get` been `transparent` or declared `: None.type` or inferred type, then sure, but as it stands I expect it to inline presenting itself as an `Option[String]`.

Is that not how inlining works in general?  I.e. is this a match-specific bug?

**Comment by bishabosha** [comment]
Inline match can only work on the static type of an expression, not its actual "code", so an `Option[String]` can not be matched

**Comment by SethTisue** [comment]
> We have discussed several times about looking at the expression instead

I'm interested what that would even mean and what the design implications are.

**Comment by rssh** [comment]
One question left -- why did the original proof request (#12039) passes all tests.  So, the inline match was able to statically reduce an Option a few months ago?

**Comment by dwijnand** [comment]
Perhaps because there envGet is transparent, so using the RHS static type rather than the get static type is expected.

**Comment by rssh** [comment]
yes, that was it...   (Hmm, but port without macros still not possible, because compiletime.error now want constant literal).
