### ISSUE TITLE
update scala-asm library dependency

### ISSUE THREAD

**Issue by michelou** [lampepfl/dotty#14251]
## Observation

- Scala 2 [2.12.5](https://scala-lang.org/files/archive/) (Sep 2021) depends on `scala-asm`[9.2.0](https://mvnrepository.com/artifact/org.scala-lang.modules/scala-asm) (July 2021)
- Scala 2 [2.13.7](https://scala-lang.org/files/archive/) (Nov 2021) *and* [2.13.8](https://scala-lang.org/files/archive/) (Jan 2022) depend on `scala-asm`[9.2.0](https://mvnrepository.com/artifact/org.scala-lang.modules/scala-asm) (July 2021)
- Scala 3 [3.1.0](https://github.com/lampepfl/dotty/releases) (Oct 2021) *and newer* depend on `scala-asm`[9.1.0](https://mvnrepository.com/artifact/org.scala-lang.modules/scala-asm) (February 2021)

## Expectation
Is there any reason for the upcoming `3.1.1 final` release (latest pre-release is [`3.1.1-RC2`](https://github.com/lampepfl/dotty/releases/tag/3.1.1-RC2)) not to be aligned with 2.12 and 2.13 releases.

**PS.** Issue is related to [discussion 17799](https://github.com/lampepfl/dotty/discussions/13799).

**Comment by SethTisue** [comment]
I think this would make a good addition to the Scala 3 release steps. Checking for alignment on JLine would also be desirable.

**Comment by michelou** [comment]
Version [3.1.1](https://github.com/lampepfl/dotty/releases/tag/3.1.1) final is now released and is still using `scala-asm` [9.1.0](https://mvnrepository.com/artifact/org.scala-lang.modules/scala-asm/9.1.0-scala-1) (version [9.2.0](https://mvnrepository.com/artifact/org.scala-lang.modules/scala-asm/9.2.0-scala-1) adds support for Java 18).
