### ISSUE TITLE
Scala.js facade fails to compile unless you explicitly call js.native

### ISSUE THREAD

**Issue by AlexITC** [lampepfl/dotty#14289]
There is a weird behavior when calling `native` when importing `scala.scalajs.js.native`.

See this [example](https://github.com/AlexITC/scala-js-chrome/commit/7f0a35568a932d1680792e827137c09f5dbe3e18) to reproduce the problem.

## Compiler version
3.1.0 (Scala.js)

## Minimized code

```Scala
import scala.scalajs.js.native

@js.native
trait OnTabReplacedDetails extends js.Object {
  val replacedTabId: Int = native
}
```

## Output

```scala
[error] -- Error: /scala-js-chrome/bindings/src/main/scala/chrome/webNavigation/bindings/OnTabReplacedDetails.scala:11:27 
[error] 11 |  val replacedTabId: Int = native
[error]    |                           ^^^^^^
[error]    |            Concrete members of JS native types may only call js.native.
[error] one error found
```

## Expectation

The code should behave just like calling `js.native`.

**Comment by sjrd** [comment]
Thanks for the report. I'll have a look when I get the chance.
