### ISSUE TITLE
Facilitate compile-time typeclass creation

### ISSUE THREAD

**Issue by Iltotore** [lampepfl/dotty#14282]
There was a quiproquo in the original issue #14226 and it got closed before clarifying it. I will try to reformulate and be as accurate as possible.

## Compiler version

3.1.0

## Introdution

In Scala 3, you can create traits with inline methods:
```scala
trait Test {

  inline def msg: String
}
```

`msg` is compiles **and runs as expected** if the implementation's exact type is known at compile-time:

```scala
inline given Test = new TestImpl
summon[Test].msg //Deferred inline

inline given TestImpl = new TestImpl
summon[TestImpl].msg //Compiles and runs

transparent inline given Test = new TestImpl
summon[TestImpl].msg //Compiles and runs
```

This behaviour is useful when creating typeclasses that have to (or can) be evaluated at compile-time. A minimized example from on of my projects:
```scala
trait Constraint[A, -B] {

  inline def assert(value: A): Boolean

  inline def getMessage(value: A): String
}

implicit inline def refineValue[A, B, C <: Constraint[A, B]](value: A)(using inline constraint: C): A / B = {
  Constrained(compileTime.preAssert[A, B, C](value, constraint.getMessage(value), constraint.assert(value)))
}
```
This code will pass the compile time-evaluated `String` `constraint.getMessage(value)` and `Boolean` `constraint.assert(value)`

Note: the `C` redudant type parameter forces the compiler to get the exact type of the `Constraint` implementation.

## The Issue

Currently, for Constraints with type parameters, we have to create a brand new class for each implementation:

```scala
trait Less[V] extends AlgebraEntryPoint[MathAlgebra] with Transitive[V] with Asymmetric[V, Greater]

class LessConstraint[A <: Number, V <: A] extends Constraint[A, Less[V]] {
  override inline def assert(value: A): Boolean = NumberOrdering.lt(value, constValue[V])

  override inline def getMessage(value: A): String = "value should be less than the specified one"
}

transparent inline given[A <: Number, V <: A]: Constraint[A, Less[V]] = new LessConstraint
```

Which works but we actually can't use anonymous `given` instances for this:
```scala
given [A <: Number, V <: A]: Constraint[A, Less[V]] with {

  override inline def assert(value: A): Boolean = NumberOrdering.lt(value, constValue[V])

  override inline def getMessage(value: A): String = "value should be less than the specified one"
}
```

The `assert` and `getMessage` methods are not fully inline even when called with an inline `value` input.

## Expectation

I would expect this last example to behave the same as the preceding one above: method calls fully inline.

I hope my issue is now clearer. My goal is not to spam my issue.

**Comment by nicolasstucki** [comment]
I see where you got stuck now. Fortunately, this already works with a slightly different pattern. The pattern you are looking for is
```scala
given [A <: Number, V <: A]: Constraint[A, Less[V]] with {

  override inline def assert(value: A): Boolean = NumberOrdering.lt(value, constValue[V])

  override inline def getMessage(value: A): String = "value should be less than the specified one"
}
```

Note that the inline for the given is useless and will be disallowed https://github.com/lampepfl/dotty/pull/14207#issuecomment-1005494510.

**Comment by Iltotore** [comment]
> I see where you got stuck now. Fortunately, this already works with a slightly different pattern. The pattern you are looking for is
> ```scala
> given [A <: Number, V <: A]: Constraint[A, Less[V]] with {
> 
>   override inline def assert(value: A): Boolean = NumberOrdering.lt(value, constValue[V])
> 
>   override inline def getMessage(value: A): String = "value should be less than the specified one"
> }
> ```
> 
> Note that the inline for the given is useless and will be disallowed https://github.com/lampepfl/dotty/pull/14207#issuecomment-1005494510.
> 
> @Iltotore could you confirm that this works in your use case?

Excuse me for my typo. This is the pattern I wanted to report. I'll edit my post above.

This pattern compiles but is only fully inlined if there's no type parameter/value parameter. It isn't inlined for the example above.

**Comment by nicolasstucki** [comment]
Ok so i guess the issue is with the prefix of the inline method that does not get optimized away.
```scala
trait Foo[A] {
  inline def foo(): Unit
}

given FooA[A]: Foo[A] with {
  inline def foo(): Unit = println(1)
}

given FooInt: Foo[Int] with {
  inline def foo(): Unit = println(2)
}

def test1 = FooA.foo() // {
//        val FooA_this: FooA[Any] = FooA[Any]
//        println(1):Unit
//      }

def test2 = FooInt.foo() // println(2)

```

**Comment by Iltotore** [comment]
From what I tested, this seems to be the origin of this issue. By not completely inlining the call, the compiler prevents compile-time evaluation of this value via `FromExprs`/`Expr#value` in a macro for example.
