### ISSUE TITLE
Change collections strawman to support capture checking

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#14285]
We are getting close with capture checking to support large programs. As a useful next step, we should try to port some standard collections to support capture checking. This can be used as a test-bed to find problems in the capture checker and as a basis for larger capture-checked programs that use collections.

Work should be based on the cc-experiment branch.

For a motivation and intro to capture checking, see https://infoscience.epfl.ch/record/290885?ln=en.

There's a similar short research project at the University of Waterloo supervised by @olhotak. Maybe we can get the two projects to work together.

The most up-to-date version of the collections strawman is `CollectionStrawman6` in `tests/pos-special/strawman-collections`.

**Comment by anatoliykmetyuk** [comment]
Simon Hayoz is going to do this project.

**Comment by olhotak** [comment]
Here's an inheritance diagram of the original collections strawman to guide our discussion (made by Rakeeb).
![xout](https://user-images.githubusercontent.com/5207003/155894479-46590875-77c9-414b-ac24-f208004b774f.svg)
