### ISSUE TITLE
Scala 3.1.0 compiler happily compiles incorrect code

### ISSUE THREAD

**Issue by eloots** [lampepfl/dotty#14312]
## Compiler version

3.1.0 (but same problem on 3.0.0, 3.0.1, 3.0.2)

## Minimized code

```
// This minimal code sample exposes the problem when compiled with Scala 3.1,
// i.e., it doesn't generate a compilation error on line xxx
// When compiled as-is with Scala 2.13.8, that line (correctly) doesn't compile

object M {
  // In Scala 3.1, the following extension produces incorrect results:
  // extension [A](a: A)
  //   def ===(a1: A): Boolean = a == a1

  // This is the same extension method defined using Scala 2 syntax
  // and when compiled with Scala 3, it exhibits the same problem
  implicit class EqualExtension[A](val a: A) extends AnyVal {
    def ===(a1: A): Boolean = a == a1
  }
}

object Main {
  import M._

  val eqs: Seq[Boolean] = Seq(
    1 === 1,
    "1" === "1",
    "1" === 1   // This line shouldn't compile, but does with the Scala 3.1.0 compiler
  )
}
```
## Output

When compiled with Scala 2.13.8, the following (correct) compiler error message is produced:

```scala
sbt:sc3> compile
[info] compiling 1 Scala source to /Users/ericloots/tmp/sc3/target/scala-2.13/classes ...
[error] /Users/ericloots/tmp/sc3/src/main/scala/ExtensionMethods.scala:25:13: type mismatch;
[error]  found   : Int(1)
[error]  required: String
[error]     "1" === 1   // This line shouldn't compile, but does with the Scala 3.1.0 compiler
[error]             ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 2 s, completed 20 Jan 2022, 18:38:07
```

## Expectation

Compiling the minimised code with Scala 3.1.0 should produce the same compilation error.

Note: I first thought this was an issue with Scala 3 extension methods, so then I tried using the Scala 2 way to define the extension method, with the same result.

**Comment by odersky** [comment]
Why should it not compile? The Scala3 compiler expands the last line to
```scala
new M.EqualExtension[Matchable]("1").===(1)
```
That seems correct to me. (`Any` instead of `Matchable` would work as well).

**Comment by eloots** [comment]
> Why should it not compile? 

Maybe I'm missing the obvious, but, when looking at the extension method:

```
  extension [A](a: A)
    def ===(a1: A): Boolean = a == a1
```

implies that `a` and `a1` have to be the same type, doesn't it?

**Comment by som-snytt** [comment]
The "same type" here is `Any` or `Matchable`, it depends on what is inferred.

Scala 2 is unable to infer the obvious thing, as it were.

I notice that `def ===[B <: A]` doesn't "help", as the `A` is not "fixed" by supplying a string.

**Comment by eloots** [comment]
Interesting. And I realize that the ‘canonical’ solution to this is Multiversal Equality. 

That said; it surprised me that the behavior observed when compiling with Scala 2(.13.8) is, as it were, as side effect of the inability of that compiler to infer the correct type(s).

**Comment by dwijnand** [comment]
Many moons ago a @smarter man than I said "please use type equality instead" (https://youtu.be/YIQjfCKDR5A?list=PL_5uJkfWNxdkZYT7fXqpZYzByfMLSSL7N&t=622):

```scala
$ scala -language:experimental.erasedDefinitions -3.head
Welcome to Scala 3.1.2-RC1-bin-20220119-2849aed-NIGHTLY-git-2849aed (11.0.12, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> extension [A](a: A) def ===[B](b: B)(using erased ev: A =:= B) = a == b
def ===[A](a: A): [B](b: B)(using erased ev: A =:= B): Boolean

scala> "1" === 1
-- Error: ----------------------------------------------------------------------
1 |"1" === 1
  |         ^
  |         Cannot prove that String =:= Int.
1 error found
```

**Comment by smarter** [comment]
Yup, this was foreseen :) Another instance of https://www.hyrumslaw.com/

**Comment by som-snytt** [comment]
> While I may have made the observation, credit goes to Titus Winters for actually naming it as "Hyrum's Law" and popularizing the concept more broadly.

May I say that everyone needs their Titus Winters.
