### ISSUE TITLE
make language imports available after Typer

### ISSUE THREAD

**Issue by olhotak** [lampepfl/dotty#14346]
In #14319 and #13976, we need a way to know whether we are in unsafe nulls mode in later phases after Typer. I discussed with @odersky and we came up with a general approach to make language imports available in later phases.

1. Modify `FirstTransform` to keep language imports.
2. In `MegaPhase`, clone and modify `mapInline` (called from `transformStats`) so that it can pass a context to the `op`. When this new `mapInline` sees an import, it should create `importContext` to pass to later `stats`. `mapInline` is performance sensitive so this has to be done carefully.

If we do the above in general, for the specific case of unsafe nulls, the existing handling in `setImportInfo` will automatically set the `Mode.SafeNulls` flag accordingly.

**Comment by odersky** [comment]
I can take care of this.
