### ISSUE TITLE
Scaladoc signature for `Foo.this.type` displays as `Foo`

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#14355]
In Scaladoc, the return type for `patchInPlace` on `scala.collection.mutable.Buffer` appears to show `Buffer[A]` when it should show `Buffer.this.type`: http://dotty.epfl.ch/api/scala/collection/mutable/Buffer.html#patchInPlace-fdd,

to compare, here it is in the scala 2 docs: https://www.scala-lang.org/api/2.13.8/scala/collection/mutable/Buffer.html#patchInPlace(from:Int,patch:scala.collection.IterableOnce[A],replaced:Int):Buffer.this.type

## Compiler version

`3.1.2-RC1-bin-20220125-a83a0a7-NIGHTLY`

## Impact

At a glance, user may think that `patchInPlace` returns a new `Buffer`, rather than the same instance

**Comment by Dedelweiss** [comment]
This issue seems to be corrected

**Comment by ckipp01** [comment]
> This issue seems to be corrected @ckipp01

Indeed, thanks for checking @Dedelweiss!
