### ISSUE TITLE
REPL/compiler leak `@unchecked` annotations in aliased assignments

### ISSUE THREAD

**Issue by cswinter** [lampepfl/dotty#1435]
```
scala> {val x@y = 1; x} 
res0: Int @unchecked = 1
```

**Comment by allanrenucci** [comment]
Fixed in #3723. We already have a test for this in our test suite: https://github.com/lampepfl/dotty/blob/dd02cbc6b9114e6d5360e3f533d5b76f99eca7e5/compiler/test-resources/repl/patdef#L7
