### ISSUE TITLE
`implicit` lambda parameters should be under `-source:3.0-migration`

### ISSUE THREAD

**Issue by KacperFKorban** [lampepfl/dotty#14365]
## Compiler version

`3.1.0`, `3.1.1`, `3.1.2-RC1-bin-20220121-7ce60e1-NIGHTLY`

## Minimized code

```Scala
List(1,2,3).map { implicit i: Int =>
  i
}
```

## Output

Nothing (compiles successfully)

## Expectation

This syntax should only be available under `-source:3.0-migration`, since the following code:

```scala
List(1,2,3).map { i: Int =>
  i
}
```

Results in error:
```
parentheses are required around the parameter of a lambda
This construct can be rewritten automatically under -rewrite -source 3.0-migration.
```

**Comment by smarter** [comment]
Hmm we could suggest a rewrite to `implicit (i: Int) =>` but I just tried it and that syntax works in Scala 3 but not Scala 2, so this would significantly complicate cross-compilation given that there is no straight-forward replacement that would work in both compilers (see also  https://github.com/lampepfl/dotty/discussions/12007 and https://github.com/lampepfl/dotty/discussions/12676).

So I don't see what else we can do here (we already disallow this syntax under `-source future`).

**Comment by KacperFKorban** [comment]
If that's the only way of expressing implicit parameters that is common between Scala 2 and 3, then you're probably right.

**Comment by som-snytt** [comment]
Compare https://github.com/lampepfl/dotty/issues/14167 except conversely.

Maybe backport `{ case given T => }`, since Scala 2 already has `for (case _: T <- xs)`. `case given` is like `case class` as a token.
