### ISSUE TITLE
Match Types do not handle Opaque Types correctly compile time

### ISSUE THREAD

**Issue by ThijsBroersen** [lampepfl/dotty#14370]
## Compiler version

3.1.0

## Minimized code

```Scala
object A:
  opaque type A[t] = t
object B:
  opaque type B[t] = t

//only A
type OnlyA[x] = x match
  case A.A[t] => t

(1: OnlyA[A.A[1]]) //OK
(1: OnlyA[B.B[1]]) //does not compile as expected

//only B
type OnlyB[x] = x match
  case B.B[t] => t

(1: OnlyB[A.A[1]]) //does not compile as expected
(1: OnlyB[B.B[1]]) //OK

//A or B
type AorB[x] = x match
  case A.A[t] => t
  case B.B[t] => t

(1: AorB[A.A[1]]) //OK
(1: AorB[B.B[1]]) //should compile but does not
```

## Output

```scala
[E]      Found:    (1 : Int)
[E]      Required: AorB[B.B[(1 : Int)]]
[E]      Found:    (1 : Int)
[E]      Required: OnlyB[A.A[(1 : Int)]]
[E]      Found:    (1 : Int)
[E]      Required: AorB[B.B[(1 : Int)]]
```

## Expectation
I would expect AorB to properly match type B on compile time. I know opaque types are erased at runtime, so this example is only meant for creating compile-time logic.

**Comment by smarter** [comment]
Match types are defined to behave like runtime matches, from http://dotty.epfl.ch/docs/reference/new-types/match-types.html :
> Match type reduction follows the semantics of match expressions, that is, a match type of the form S match { P1 => T1 ... Pn => Tn } reduces to Ti if and only if s: S match { _: P1 => T1 ... _: Pn => Tn } evaluates to a value of type Ti for all s: S.

So `AorB[B.B[1]]` cannot be reduced.

**Comment by ThijsBroersen** [comment]
It looks like they allow for interesting refined typing. Opaque types are used correctly in they simple match types. Why shouldn't it work? I read the documentation you referenced but if feels Match Types could be multi-purpose. 

The compiler is also able to prove `A.A[1] =:= A.A[1]` and rejects `A.A[1] =:= B.B[1]`. 
With implicits we can also resolve properly using Opaque Types. They offer a nice way to write compile time logic...

**Comment by smarter** [comment]
> Why shouldn't it work?

The current rules let us type a match expression using a match type (see section "Dependent Typing" of the documentation page). If you feel like these rules could be changed in a backwards-compatible way feel free to propose an improved specification, but this should be discussed on https://contributors.scala-lang.org/, not here.
