### ISSUE TITLE
Vulpix leaks file handles

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#14376]
## Compiler version

3.1.3-RC1

## Minimized example

Since the latest upgrade I get this on MacOS:

**sbt:scala3> scala3-bootstrapped/testOnly dotty.tools.dotc.CompilationTests
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-interfaces / Test / testOnly
[info] compiling 7 Scala sources to /Users/odersky/workspace/dotty/compiler/target/scala-3.1.2-RC1/classes ...
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-sbt-bridge / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-library-bootstrapped / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for tasty-core-bootstrapped / Test / testOnly
[info] compiling 4 Scala sources to /Users/odersky/workspace/dotty/compiler/../out/bootstrap/scala3-compiler-bootstrapped/scala-3.1.3-RC1-bin-SNAPSHOT-nonbootstrapped/classes ...
[info] compiling 15 Scala sources to /Users/odersky/workspace/dotty/compiler/../out/bootstrap/scala3-compiler-bootstrapped/scala-3.1.3-RC1-bin-SNAPSHOT-nonbootstrapped/classes ...
[info] compiling 1 Scala source to /Users/odersky/workspace/dotty/compiler/../out/bootstrap/scala3-compiler-bootstrapped/scala-3.1.3-RC1-bin-SNAPSHOT-nonbootstrapped/test-classes ...
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-bootstrapped / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scaladoc / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-staging / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-language-server / Test / testOnly
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for scala3-tasty-inspector / Test / testOnly
[info] Test run started
[info] Test dotty.tools.dotc.CompilationTests.negAll started
[=======================================] completed (1366/1366, 0 failed, 54s)
[info] Test dotty.tools.dotc.CompilationTests.runAll started
[=======================================] completed (1418/1418, 0 failed, 69s)
[info] Test dotty.tools.dotc.CompilationTests.pickling started
[=======================================] completed (3636/3636, 0 failed, 57s)
[info] Test dotty.tools.dotc.CompilationTests.rewrites started
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (6/6, 0 failed, 0s)
[info] Test dotty.tools.dotc.CompilationTests.pos started
[=======================================] completed (2655/2655, 0 failed, 64s)
[info] Test dotty.tools.dotc.CompilationTests.checkInit started
[=======================================] completed (139/139, 0 failed, 0s)
[=======================================] completed (38/38, 0 failed, 0s)
[=======================================] completed (23/23, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[=======================================] completed (1/1, 0 failed, 0s)
[info] Test dotty.tools.dotc.CompilationTests.posTwice started
[=======================================] completed (133/133, 0 failed, 10s)
[info] Test dotty.tools.dotc.CompilationTests.explicitNullsPos started
java.nio.file.FileSystemException: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/ext: Too many open files while compiling tests/explicit-nulls/pos/flow-while-loop.scala
java.nio.file.FileSystemException: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/ext: Too many open files while compiling tests/explicit-nulls/pos/i13608.scala
java.nio.file.FileSystemException: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/ext: Too many open files while compiling tests/explicit-nulls/pos/flow-match.scala
java.nio.file.FileSystemException: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/ext: Too many open files while compiling tests/explicit-nulls/pos/opaque-nullable.scala
Fatal compiler crash when compiling: tests/explicit-nulls/pos/flow-while-loop.scala:
/Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre/lib/ext: Too many open files
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.Files.list(Files.java:3451)
	at dotty.tools.io.Directory.list(Directory.scala:51)
	at dotty.tools.io.PlainFile.iterator(PlainFile.scala:92)
	at scala.collection.View$Filter.iterator(View.scala:144)
```

**Comment by odersky** [comment]
I disabled explicitNullsNeg and then explicitiNullsPos. In any case it always crashes immediately after posTwice, no matter what comes next. So the filehandles must have been leaked by the tests that came before.

**Comment by odersky** [comment]
@nicolasstucki experienced the same issue

**Comment by nicolasstucki** [comment]
This issue started in with 643314d689f506efb3bd01d44cda49db22072960.

**Comment by nicolasstucki** [comment]
This line could be the cause https://github.com/lampepfl/dotty/commit/643314d689f506efb3bd01d44cda49db22072960#diff-ca2b46a626d438f1fb62d071a802694205a52435cfafb6a0595afe423c305d1eR451

**Comment by nicolasstucki** [comment]
We might be missing a call to `close` on the `Files.lines(path, charset)` stream at line
https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/tools/utils.scala#L50.
