### ISSUE TITLE
REPL eagerly evaluates lazy vals

### ISSUE THREAD

**Issue by cswinter** [lampepfl/dotty#1440]
```
scala> lazy val a = { println("side effect"); 0 } 
side effect
a: Int = 0
```

What scalac/ammonite do:

```
scala> lazy val a = { println("side effect"); 0 }
a: Int = <lazy>
```

**Comment by kcsongor** [comment]
I think this is an improvement, rather than a regression

**Comment by Jasper-M** [comment]
If the REPL immediately forces lazy vals, then there is absolutely no use for lazy vals in the REPL.

**Comment by felixmulder** [comment]
New REPL doesn't do this :)
