### ISSUE TITLE
`.isInstanceOf` type inferrence discrepancy between Scala 2 and Scala 3

### ISSUE THREAD

**Issue by vasilmkd-jetbrains** [lampepfl/dotty#14419]
## Compiler version
2.13.8 and 3.1.1

## Minimized code

```Scala
"123".isInstanceOf // Notice no explicit type
```

## Output

Scala 2
```scala
false
```

Scala 3
```scala
true
```

Examining the bytecode produced by Scala 2:
```
12: instanceof    #20                 // class scala/runtime/Nothing$
```

while Scala 3 gives the following warning:
```
The highlighted type test will always succeed since the scrutinee type ("123" : String) is a subtype of Object
```

which suggests that different types are inferred (`Nothing` in Scala 2 and `Any` in Scala 3).

**Comment by som-snytt** [comment]
This is not peculiar to `isInstanceOf`.

`def f[A]: Boolean = true`

**Comment by smarter** [comment]
There is no guaranteed behavior here, the compiler is free to fill in the type argument with any type that fits the constraints inferred from the type parameter bounds and the expected type at the point the method call takes place, so this isn't a bug (and I highly recommend being explicit about the type argument passed to isInstanceOf/asInstanceOf, maybe we should just always warn when it's not passed explicitly).
