### ISSUE TITLE
Unbound wildcards cause assertion error/oom

### ISSUE THREAD

**Issue by cswinter** [lampepfl/dotty#1443]
E.g. `val a: _ = ???` causes compiler hang/OOM and `val a: List[_ <: _] = List(0)` crashes with a failed assertion in typer. Some more details on why this happens can be found in [this comment](https://github.com/lampepfl/dotty/issues/1396#issuecomment-234186015). This can only be replicated with dotc; REPL aborts compilation as soon as the frontend emits an "unbound wildcard type" error.

Further examples can be found in `tests/pending/neg/unboundWildcard.scala`, which should be moved to `tests/neg` once this issues has been resolved.

**Comment by odersky** [comment]
I think this has an easy fix: When the parser reports an unbound wildcard error for a type, it should return `Any` as the tree instead of the TypeBounds tree that it saw originally. No need to worry about follow-on errors: the reporter will suppress subsequent errors on the same position anyway.
