### ISSUE TITLE
Weird capture checker failure in predef

### ISSUE THREAD

**Issue by mhammons-ledger** [lampepfl/dotty#14459]
## Compiler version
CC-experiment e82d110fd8a30f7c3580da8dd77c3a6fc9466323
## Minimized code

https://gitlab.com/mhammons/slinc-foreign-function-interface/-/tree/CC

## Output

```scala
[error] -- [E007] Type Mismatch Error: library/src/scala/runtime/stdLibPatches/Predef.scala:49:35 
[error] Found:    (x$proxy34 : {s} jdk.incubator.foreign.MemoryAddress)
[error] Required: jdk.incubator.foreign.MemoryAddress | Null
[error] one error found
```

## Expectation

Not this. Not sure what's even happening here, or where it's happening

**Comment by odersky** [comment]
The error looks legit:
```scala
{s} jdk.incubator.foreign.MemoryAddress)
```
is not a subtype of 
```scala
jdk.incubator.foreign.MemoryAddress | Null
```
But none of stdlib or Predef has been ported yet, so getting errors is not surprising.

**Comment by odersky** [comment]
Closing to revisit once Predef has been ported.
