### ISSUE TITLE
For an object X, `X$` should be =:= to `X.type`

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1447]
This works in scalac but not in dotty:
```scala
case object X

object Test {
  val Alias = X

  val x: X.type = Alias
}
```
```scala
error: type mismatch:
 found   : X(Test.Alias)
 required: X.type
  val x: X.type = Alias
                  ^
```
Logging shows the issue:
```scala
[log frontend] ==> isSubType X$(Test.Alias) <:< X.type class dotty.tools.dotc.core.Types$TermRefWithSignature, class dotty.tools.dotc.core.Types$TermRefWithSignature?
[log frontend]   ==> isSubType X$ <:< X.type class dotty.tools.dotc.core.Types$CachedTypeRef, class dotty.tools.dotc.core.Types$TermRefWithSignature?
[log frontend]   <== isSubType X$ <:< X.type class dotty.tools.dotc.core.Types$CachedTypeRef, class dotty.tools.dotc.core.Types$TermRefWithSignature = false
[log frontend] <== isSubType X$(Test.Alias) <:< X.type class dotty.tools.dotc.core.Types$TermRefWithSignature, class dotty.tools.dotc.core.Types$TermRefWithSignature = false
```

**Comment by sjrd** [comment]
Hum ... I don't think this is the proper fix. `X$` accepts `null`, whereas `X.type` does not. These types should not be equal.

The proper fix, IMO, is for `Alias` to be inferred to have type `X.type`, instead of `X$`.

**Comment by retronym** [comment]
Not sure if this is the relevant or not, but I fixed a problem in scalac related to transitity of `<:<` and `=:=` being broken for:

```
    val tp1 = TypeRef(ThisType(EmptyPackageClass), moduleClass, Nil)
    val tp2 = SingleType(ThisType(EmptyPackageClass), module)
    val tp3 = ThisType(moduleClass)
```

Here's the test:

https://github.com/scala/scala/blob/b8e4d1f692c5712990b45f50625627015112df32/test/junit/scala/reflect/internal/TypesTest.scala#L38

**Comment by smarter** [comment]
@sjrd What you're suggesting might be better in principle but note that module classes are not nullable in dotty, so the difference might not be observable: https://github.com/lampepfl/dotty/blob/5a5f9d7ed37ca6449ef61ee5e0f6fbf9731df795/src/dotty/tools/dotc/core/SymDenotations.scala#L616-L618
