### ISSUE TITLE
AnyVal inference for numeric types and/or literals blocks type class resolution under covariance

### ISSUE THREAD

**Issue by Sciss** [lampepfl/dotty#14482]
## Compiler version

3.1.1

## Minimized code

```Scala
import scala.language.implicitConversions

object GE {
  implicit def intConst     (x: Int     ): GE.I = ???
  implicit def doubleConst  (x: Double  ): GE.D = ???

  type D = GE[Double]
  type I = GE[Int]
  type B = GE[Boolean]
}
trait GE[+A] // covariance introduces the problem in Scala 3!

object Ord {
  implicit def intOrd   : Ord[Int   ] = ???
  implicit def doubleOrd: Ord[Double] = ???
}
trait Ord[A]

object Ops {
  implicit class GEOps[A](private val in: GE[A]) extends AnyVal {
    def >= (that: GE[A])(implicit ord: Ord[A]): GE.B = ???
  }
}

trait Test {
  import Ops._
  def tk: GE.D
  val p: GE.B = tk >= 0   // error here
}
```

## Output

```scala
no implicit argument of type Playground.Ord[AnyVal] was found for parameter ord of method >= in class GEOps
```

https://scastie.scala-lang.org/Dc6XtOSYS0SgWX62hpsBYQ

## Expectation

Works as expected in Scala 2:

https://scastie.scala-lang.org/fzjDjG5eTJWHoP47VV1S0g

**Comment by romanowski** [comment]
Hi @Sciss

I was playing with the code and I am not sure if the behaviour in Scala 2 is correct. The place where I am not so sure about is `val p: GE.B = tk >= 0`. `kt` here is of the type `GE.D` and there is no direct way to turn Int into `GE.D` (only `GE.I`). 

It seems that Scala 3 is more reluctant to apply conversion from Int (`0`) to double to later convert it into `GE.D` since chaining it to `0.0` or commenting out `intConst` fixes the problem.

**Comment by odersky** [comment]
Yes, that looks like an intentional restriction in Scala 2: https://dotty.epfl.ch/0.23.0-RC1/docs/reference/dropped-features/weak-conformance.html

**Comment by sjrd** [comment]
My assessment is that it is not related to weak conformance/harmonization. Instead, it is one of those cases where is a bad consequence of the (overall) improved type inference of Scala 3.

Scala 2 eagerly infers `A = Double` when invoking the implicit class on the `GE.D`. Then it must adapt the `Int` to `Double`, and still resolves `Ord[Double]`. Scala 3, on the contrary, delays the instantiation of `A` to later. In particular, it waits until it sees the argument `0` of type `Int`. At that point, it sees the `intConst` conversion which can be applied to an `Int` to get a `GE[Int]`, which matches the shape `GE[A]`. Only *then* does it try to instantiate `A`, which must now be a super type of `Double` and `Int`, hence `AnyVal`. Then of course it fails to resolve an `Ord[AnyVal]`, so, bummer.

A fix is to move the `implicit Ord[A]` further up, to force the inference to take into account the fact that it needs an `Ord[A]` *before* taking other considerations into account:
```scala
  implicit class GEOps[A](private val in: GE[A])(implicit ord: Ord[A]) {
    def >= (that: GE[A]): GE.B = ???
  }
```
Scastie: https://scastie.scala-lang.org/rR4Mgu3hSmSt7C4ZTg07lA

Another "proof" that implicit resolution per se is not to blame, is that the code compiles if we explicitly set `A = Double`, as follows:
```scala
val p: GE.B = GEOps[Double](tk) >= 0
```

So, unfortunately, I think this is as-designed, and cannot be fixed.

**Comment by nicolasstucki** [comment]
@sjrd should we investigate further to make sure that this is happening as you described? Or can we close the issue?

**Comment by sjrd** [comment]
IMO we can close the issue.
