### ISSUE TITLE
Unknown name for enum field with Scala.js

### ISSUE THREAD

**Issue by plokhotnyuk** [lampepfl/dotty#14488]
## Compiler version(s)

scalac 3.1.1 + scala.js 1.9.0

## Minimized code

```Scala
object LocationType extends Enumeration {
  type LocationType = Value

  val IP, GPS: LocationType = Value
}

LocationType.GPS.toString
```

## Output

```scala
"<Unknown name for enum field #1 of class class scala.Enumeration$Val>"
```

## Expectation

```scala
"GPS"
```

**Comment by sjrd** [comment]
Ah, yes, `Enumeration`. We never ported the compiler support for `scala.Enumeration` to Scala 3. I guess I was hoping that they would have disappeared in favor of `enum`s.

Work around: give explicit names to the fields:
```scala
object LocationType extends Enumeration {
  type LocationType = Value

  val IP: LocationType = Value("IP")
  val GPS: LocationType = Value("GPS")
}
```

**Comment by sjrd** [comment]
What would people think about releasing the support for `Enumeration` in a separate compiler for Scala 3? The use cases are rare, now that `enum` is there, and I hope we can eventually sunset it. Publishing it as a compiler plugin would reduce the maintenance burden, *and* compile-time performance for everyone that doesn't use `Enumeration`.
