### ISSUE TITLE
Broken link for #:: on the Scaladoc website search results

### ISSUE THREAD

**Issue by Nicolapps** [lampepfl/dotty#14505]
When searching for the `#::` object on the [API documentation website](https://scala-lang.org/api/3.x/), the link doesn’t lead to the correct URL (I get a 404 page when clicking on it).

The URL that I currently get is:
```
https://scala-lang.org/api/3.x/scala/#::$.html
```

In order for the link to work, it should rather lead to:
```
https://scala-lang.org/api/3.x/scala/%23::$.html
```

<img width="845" alt="image" src="https://user-images.githubusercontent.com/7029582/154368267-83d3a58d-5980-43ed-a2f0-cecba9d7946f.png">

**Comment by romanowski** [comment]
Thank you @Nicolapps for reporting, it seems we are missing escaping in the links we generate. cc @jchyb
