### ISSUE TITLE
Enum values are not properly reused due to underlyingArgument in macros

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#14510]
## Compiler version

3.1.1

## Minimized code

```Scala
import scala.quoted.*

given staging.Compiler = staging.Compiler.make(getClass.getClassLoader)

def underlyingArgumentImpl[A](expr: Expr[A])(using Quotes, Type[A]) =
  import scala.quoted.quotes.reflect.*
  expr.asTerm.underlyingArgument.asExprOf[A]

inline def underlyingArgument[A](inline a: A): A = ${
  underlyingArgumentImpl('a)
}

val b: Boolean = staging.run[Boolean] {
  '{
    def f() = {
      enum E:
        case V
      underlyingArgument(E.V == E.V)
    }
    f()
  }
}

println(b)
```

https://scastie.scala-lang.org/82665kkpQ3KIBESu0jMnTg

## Output

`false`

## Expectation

`true`

**Comment by Atry** [comment]
If I replace `expr.asTerm.underlyingArgument.asExprOf[A]` with `expr.asTerm.asExprOf[A]`, then the output would be `true`, as expected. 

https://scastie.scala-lang.org/XuLYeLJ4TPmf8saom43maA

**Comment by Atry** [comment]
Note that the staging compiler is used to bypass the error "Cannot call macro method underlyingArgumentImpl defined in the same source file". This bug can be reproduced without the staging compiler.

**Comment by nicolasstucki** [comment]
It is unsafe to use the result of `underlyingArgument` in the generated code. The tree returned by this method is only meant to be analyzed. 

The documentation should state this clearly.
