### ISSUE TITLE
Scaladoc: reported type of `Map#map`

### ISSUE THREAD

**Issue by jmgimeno** [lampepfl/dotty#14511]
The type reported for `Map#map` in the docs accessible from https://scala-lang.org/api/3.x/scala/collection/immutable/Map.html#map-fffffcb7 is

```scala
def map[K2, V2](f: (K, V) => (K2, V2)): Map[K2, V2]
```

but, if we go to its definition in the linked source file https://github.com/scala/scala/blob/v2.13.6/src/library/scala/collection/Map.scala#L299 we find that the real type is

```scala
def map[K2, V2](f: ((K, V)) => (K2, V2)): CC[K2, V2]
```
which, at least, I find it *very confusing*.

If I understand *untupling* correctly, the *magic* that allows calling a function which receives a tuple with a function with various parameters occurs at the call-site, so the documented type of the method should not change (or maybe this issue in the documentation has nothing to do with it).

**Comment by pikinier20** [comment]
The `map` method is defined in `trait MapOps` which takes a type parameter named `CC`. The docs that you provided lead to `scala.collection.immutable.Map` which mixins `MapOps` and applies type `Map[K, V]` in place of `CC`. Therefore, I think the shown type is ok. 

Scaladoc 2 does the same: [Map.map](https://www.scala-lang.org/api/2.13.3/scala/collection/immutable/Map.html#map[K2,V2](f:((K,V))=%3E(K2,V2)):CC[K2,V2])

**Comment by jmgimeno** [comment]
I know there is another version of `map` but the problem I report is that the shown type in the documentation does not match the type in the implementation. The type of the parameter changes.
