### ISSUE TITLE
Forward Ref allowed in enum cases, leading to null reference

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#14548]
## Compiler version

3.1.1

## Minimized code

```Scala
enum E(val ref: AnyRef):
  case Foo extends E(Bar)
  case Bar extends E("")

@main def Test =
  assert(E.Foo.ref ne null)
```

## Output

runtime error:
```scala
java.lang.AssertionError: assertion failed
  at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
  ... 36 elided
```

## Expectation

forbid this maybe? at least `-Ysafe-init` detects this

**Comment by bishabosha** [comment]
probably should have noticed this when https://github.com/lampepfl/dotty/issues/9177 was reported

**Comment by som-snytt** [comment]
Only just encountered this as an unlikely epigraph to the Tina Turner biopic "What's Love Got to Do with It":

> "The Lotus flower blooms most beautifully from the deepest and thickest mud" - Buddhist proverb "The Lotus grows out of the mud. Without the mud, there is no Lotus. Suffering is a kind of mud, that we must use in order to grow the flower of Understanding and Love" - Thich Nat Hanh

It would be nice to have a mode in which the compiler is applying all available lints (whatever that means). Maybe `--zen`.
