### ISSUE TITLE
Match type not simplified in return position

### ISSUE THREAD

**Issue by s5bug** [lampepfl/dotty#14549]
## Compiler version

3.1.1, 3.1.2-RC1

## Minimized code

```Scala
import scala.compiletime.ops.int.*

type Fill[N <: Int, A] <: Tuple = N match {
  case 0 => EmptyTuple
  case S[n] => A *: Fill[n, A]
}

sealed trait SeqToTuple[N <: Int] {
  def apply[A](s: Seq[A]): Fill[N, A]
}
implicit val emptyToZero: SeqToTuple[0] = new SeqToTuple[0] {
  override def apply[A](s: Seq[A]): EmptyTuple = EmptyTuple
}
implicit def successorToSuccessor[N <: Int](implicit pred: SeqToTuple[N]): SeqToTuple[S[N]] = new SeqToTuple[S[N]] {
  override def apply[A](s: Seq[A]): Fill[S[N], A] =
    s.head *: pred(s.tail) // Scala doesn't know that `A *: Fill[N, A]` = `Fill[S[N], A]` for some reason
}
```

## Output

```scala
Found:    A *: Fill[N, A]
Required: Fill[compiletime.ops.int.S[N], A]

where:    N is a type in method successorToSuccessor with bounds <: Int
```

## Expectation

Scala recognizes that `Fill[S[N], A]` = `A *: Fill[N, A]` (as it is a case of the match type) and lets the program compile.

**Comment by bishabosha** [comment]
this can not work because in the body of `successorToSuccessor`, `N` is totally abstract, so when passed to `Fill` it is impossible to prove that `N` is either `0` or `S[n]`, so the match type does not reduce to a rhs, this causes an error because match types must reduce to one of their rhs.

In this case I believe your only option is to cast, and the behaviour will be correct for users:
```scala
implicit def successorToSuccessor[N <: Int: ValueOf](implicit pred: SeqToTuple[N]): SeqToTuple[S[N]] = new SeqToTuple[S[N]] {
  override def apply[A](s: Seq[A]): Fill[S[N], A] =
    Tuple.fromIArray(IArray.from(s.asInstanceOf[Seq[AnyRef]].take(valueOf[N] + 1))).asInstanceOf[Fill[S[N], A]]
}
```

used like:

```scala
scala> summon[SeqToTuple[3]](List(1,2,3,4,5))
val res2: Int *: Int *: Int *: EmptyTuple = (1,2,3)
```

**Comment by s5bug** [comment]
surely `Fill[S[N], A]` should reduce to `A *: Fill[N, A]`, no? I'm meaning the `apply` of `successorToSuccessor`'s return type.

**Comment by smarter** [comment]
> this causes an error because match types must reduce to one of their rhs.

Not necessarily, a match type that doesn't reduce just stays as an abstract type, it only causes an error if the compiler can prove that this match type could never reduce even if it knew more about the type arguments.

**Comment by dwijnand** [comment]
Yeah, 0 and `S[n]` are provably disjoint, so the match doesn't get stuck.

**Comment by s5bug** [comment]
Interesting, so it tries to reduce _too far_, not checking that the first reduction it does is equal to the target?

**Comment by bishabosha** [comment]
if I tweak a bit then the result type does not reduce one step either:
```scala
override def apply[A](s: Seq[A]): Fill[S[N], A] =
  val res: A *: Fill[N, A] = s.head *: pred(s.tail)
  res
```

```scala
   | Note: a match type could not be fully reduced:
   |
   |   trying to reduce  Fill[compiletime.ops.int.S[N], A]
   |   failed since selector  compiletime.ops.int.S[N]
   |   does not match  case (0 : Int) => EmptyTuple
   |   and cannot be shown to be disjoint from it either.
   |   Therefore, reduction cannot advance to the remaining case
   |
   |     case compiletime.ops.int.S[n] => A *: Fill[n, A]
```

**Comment by smarter** [comment]
@OlivierBlanvillain Do match types support partial reduction, or do we always return the unreduced match type if we were not able to fully reduce it?

**Comment by odersky** [comment]
As far as I know, we always return the unreduced match type. 

But all of this is a red herring. An unreduced match type should allow the same subtyping judgments as a partially reduced subtype. But in the case here it seems, that we simply do not have a subtyping judgement at the point where we check it since `N` is abstract. 

So, please don't get hung up by the notion of "reducing matchtypes". That's not how it works. Instead, we build matchtype checking into the subtyping test.

**Comment by OlivierBlanvillain** [comment]
@smarter If by partial reduction you mean getting rid of the first N non-matching cases of match, no we don't, but we can reduce a type N steps and be stuck on an unreduced match at the end, which we then return:

```scala
scala> type Foo[X] = X match { case Int => X match { case 1 => true }}

scala> val x: Foo[Int] = ""
-- [E007] Type Mismatch Error: ---------------------------------------
1 |val x: Foo[Int] = ""
  |                  ^^
  |                  Found:    ("" : String)
  |                  Required: Int match {
  |                    case (1 : Int) => (true : Boolean)
  |                  }

longer explanation available when compiling with `-explain`
1 error found
```

**Comment by OlivierBlanvillain** [comment]
@smarter If by partial reduction you mean getting rid of the first N non-matching cases of match, no we don't, but we can reduce a type N steps and be stuck on an unreduced match at the end, which we then return:

```scala
scala> type Foo[X] = X match { case Int => X match { case 1 => true }}

scala> val x: Foo[Int] = ""
-- [E007] Type Mismatch Error: ---------------------------------------
1 |val x: Foo[Int] = ""
  |                  ^^
  |                  Found:    ("" : String)
  |                  Required: Int match {
  |                    case (1 : Int) => (true : Boolean)
  |                  }

longer explanation available when compiling with `-explain`
1 error found
```

**Comment by OlivierBlanvillain** [comment]
@smarter If by partial reduction you mean getting rid of the first N non-matching cases of match, no we don't, but we can reduce a type N steps and be stuck on an unreduced match at the end, which we then return:

```scala
scala> type Foo[X] = X match { case Int => X match { case 1 => true }}

scala> val x: Foo[Int] = ""
-- [E007] Type Mismatch Error: ---------------------------------------
1 |val x: Foo[Int] = ""
  |                  ^^
  |                  Found:    ("" : String)
  |                  Required: Int match {
  |                    case (1 : Int) => (true : Boolean)
  |                  }
```

**Comment by dwijnand** [comment]
Yeah, Jamie was right all along: `Fill[S[N], A]` isn't necessarily `= A *: Fill[N, A] ` because `N` could be -1, and therefore would reduce to EmptyTuple, which `s.head *: pred(s.tail)` isn't.  So it's right not to reduce and right not to subtype check.

Though I'm not proficient enough to know how to change the intent of the code into something that would work 😕

**Comment by bishabosha** [comment]
I think really the issue is that `0` and `S[n]` are not treated like independent class types, for example, if we substitute `Int` for some `Nat` enum then the example works unchanged:

```scala
enum Nat {
  case Zero
  case Succ[N <: Nat](pred: N)
}

object Nat {

  transparent inline given inferNat[I <: Nat]: I = inline compiletime.erasedValue[I] match {
    case _: Nat.Zero.type  => Nat.Zero.asInstanceOf[I]
    case _: Nat.Succ[pred] => Nat.Succ(inferNat[pred]).asInstanceOf[I]
  }

  type FromInt[I <: Int] <: Nat = I match {
    case 0 => Nat.Zero.type
    case compiletime.ops.int.S[n] => Nat.Succ[FromInt[n]] 
  }

}

/// begin of example

import scala.compiletime.ops.int.*

type Fill[N <: Nat, A] <: Tuple = N match {
  case Nat.Zero.type => EmptyTuple
  case Nat.Succ[n] => A *: Fill[n, A]
}

sealed trait SeqToTuple[N <: Nat] {
  def apply[A](s: Seq[A]): Fill[N, A]
}
implicit val emptyToZero: SeqToTuple[Nat.Zero.type] = new SeqToTuple[Nat.Zero.type] {
  override def apply[A](s: Seq[A]): EmptyTuple = EmptyTuple
}
implicit def successorToSuccessor[N <: Nat](implicit pred: SeqToTuple[N]): SeqToTuple[Nat.Succ[N]] = new SeqToTuple[Nat.Succ[N]] {
  override def apply[A](s: Seq[A]): Fill[Nat.Succ[N], A] =
    s.head *: pred(s.tail) // Scala doesn't know that `A *: Fill[N, A]` = `Fill[S[N], A]` for some reason
}
```

**Comment by s5bug** [comment]
Awesome! Thanks for the insights.
