### ISSUE TITLE
Problem running `@main` methods with command line arguments

### ISSUE THREAD

**Issue by spamegg1** [lampepfl/dotty#14541]
## Compiler version
3.1.1

## Minimized code

```Scala
// In file echoargs.scala
@main def echo(args: String*) =
  println(args.mkString(" "))
```

## Output
First compile
```
$ scalac echoargs.scala
```
Then run the main method:
```
$ scala echo hello world
echo hello world hello world
```

## Expectation
```
$ scala echo hello world
hello world
```
Edit: this was the output using the `scala` command of 3.0.2

**Comment by spamegg1** [comment]
Similarly, for this file
```Scala
// In file repeatword.scala
@main def repeat(word: String, count: Int) =
  println(List.fill(count)(word).mkString(" "))
```

## Output
First compile
```
$ scalac repeatword.scala
```
Then run the main method:
```
$ scala repeat hello 3
Illegal command line after first argument: java.lang.NumberFormatException: For input string: "hello"
```
However:
```
$ scala repeat 3
repeat repeat repeat
```

## Expectation
```
$ scala repeat hello 3
hello hello hello
```

**Comment by som-snytt** [comment]
PR is quick tweak. Key phrase from last summer: "MainGenericRunner should work almost ".

If we can go 6 months without using command line args, then maybe we don't need command line args.

**Comment by som-snytt** [comment]
```
$ scala echo hello world
echo hello world hello world
```
Crossword just had clue "hello hello hello, e.g." for "echo".

**Comment by spamegg1** [comment]
> If we can go 6 months without using command line args, then maybe we don't need command line args.

The book told me to do it! (Prog in Scala 5th ed) It's used to show the power of type classes:
> How does Scala know how to turn the command line string "3" into
an Int 3 ? It uses a typeclass named FromString ,

**Comment by bishabosha** [comment]
we changed the `scala` script from bash to Scala in 3.1.0 - this did work as expected with the scala script of 3.0.2
