### ISSUE TITLE
Class names and case sesitivity

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1454]
`scala.collection.immutable.Stream` defines inner `class Cons` and an inner `object cons`.
The second one triggers creation of a `class cons` with static forwarders, that are used in separate compilation and that bears TASTY. 
OS X has case-insensitive filesystem and `Cons.class` and `cons.class` overwrite each-other. 

Manifests itself with a funny exception: 

```
Exception in thread "main" java.lang.NoClassDefFoundError:
scala/collection/immutable/Stream$Cons (wrong name: scala/collection/immutable/Stream$cons)
```

**Comment by smarter** [comment]
How come this issue does not manifest itself with scalac?

**Comment by smarter** [comment]
Also, is there any way to fix this other than completely disallowing classes to have the same case-insensitive name?

**Comment by Jasper-M** [comment]
Scalac doesn't generate a class with static forwarders for inner objects. For toplevel objects and classes it has the same issue on OS X.

**Comment by odersky** [comment]
Seen that this is not fixed by scalac either, I change to enhancement

**Comment by smarter** [comment]
> Scalac doesn't generate a class with static forwarders for inner objects

Dotty doesn't either since https://github.com/lampepfl/dotty/pull/2703 so closing. The case-sensitivity issue is discussed in https://github.com/lampepfl/dotty/issues/1077
