### ISSUE TITLE
Mirror.Sum for enums are not cached in companion in REPL

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#14540]
## Compiler version

3.1.1

## Minimized code

Edit: since https://github.com/lampepfl/dotty/issues/14540#issuecomment-1049844123 I have adjusted to a repl example

```Scala
scala> import scala.deriving.Mirror
scala> enum Foo { case A }
scala> assert(summon[Mirror.SumOf[Foo]] eq Foo)
```

## Output

fail at runtime:
```scala
scala> assert(summon[Mirror.SumOf[Foo]] eq Foo)
java.lang.AssertionError: assertion failed
  at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
  ... 36 elided
```

## Expectation

work, as in Scala 3.1.0

**Comment by bishabosha** [comment]
investigate if https://github.com/lampepfl/dotty/pull/14100 is the cause

**Comment by nicolasstucki** [comment]
@bishabosha I could not reproduce this issue.

**Comment by bishabosha** [comment]
this seems to only affect summoning a mirror for a class defined in a previous command in the repl
