### ISSUE TITLE
3 incompatibilities with scalac

### ISSUE THREAD

**Issue by olafurpg** [lampepfl/dotty#1457]
See: https://github.com/olafurpg/dotty/pull/2/files

All three examples compile fine with scalac while dotc emits a compiler error. I don't know if these incompatibilities are intentional or known bugs.

**Comment by odersky** [comment]
Hi Olaf, can you make a PR against dotty master and put the tests in pos/pending please?

**Comment by olafurpg** [comment]
Done, see #1464.
