### ISSUE TITLE
Accessing superclass fields defined by primary ctor is inefficient

### ISSUE THREAD

**Issue by informarte** [lampepfl/dotty#14600]
## Compiler version

3.1.1

## Minimized example

```Scala
class A(val id: Int)

class B(id: Int) extends A(id) {
    override def toString = String.format("%d", id)
}
```

## Output

Above code compiles to:

```
public class scala.A {
  private final int id;

  public scala.A(int);
    Code:
       0: aload_0
       1: iload_1
       2: putfield      #11                 // Field id:I
       5: aload_0
       6: invokespecial #14                 // Method java/lang/Object."<init>":()V
       9: return
    LineNumberTable:
      line 3: 0
      line 4: 9
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          0      10     0  this   Lscala/A;
          0      10     1    id   I

  public int id();
    Code:
       0: aload_0
       1: getfield      #11                 // Field id:I
       4: ireturn
    LineNumberTable:
      line 3: 0
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          0       5     0  this   Lscala/A;
}

public class scala.B extends scala.A {
  public scala.B(int);
    Code:
       0: aload_0
       1: iload_1
       2: invokespecial #10                 // Method scala/A."<init>":(I)V
       5: return
    LineNumberTable:
      line 7: 0
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          0       6     0  this   Lscala/B;
          0       6     1    id   I

  private int id$accessor();
    Code:
       0: aload_0
       1: invokespecial #17                 // Method scala/A.id:()I
       4: ireturn
    LineNumberTable:
      line 7: 0
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          0       5     0  this   Lscala/B;

  public java.lang.String toString();
    Code:
       0: ldc           #21                 // String %d
       2: iconst_1
       3: anewarray     #23                 // class java/lang/Object
       6: dup
       7: iconst_0
       8: aload_0
       9: invokespecial #25                 // Method id$accessor:()I
      12: invokestatic  #31                 // Method scala/runtime/BoxesRunTime.boxToInteger:(I)Ljava/lang/Integer;
      15: aastore
      16: invokestatic  #37                 // Method java/lang/String.format:(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
      19: areturn
    LineNumberTable:
      line 8: 0
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          0      20     0  this   Lscala/B;
}
```
Things to notice:

- The Scala compiler extended A with the getter A.id.
- The Scala compiler extended A with B.id$accessor which calls A.id.
- B.toString calls id$accessor.

Concluding, B.toString needs two method calls to retrieve the id where a getfield would be enough.

This problem can be avoided by making A.id private at the cost of storing id in both A and B. 

## Expectation

I expect the Scala compiler to produce byte code as efficient as Java.

```Java
public class A {

    public final int id;

    public A(int id) {
        this.id = id;
    }

}

public class B extends A {

    public B(int id) {
        super(id);
    }

    public String toString() {
        return String.format("%d", id);
    }

}
```

gets compiled to:

```
public class java.A {
  public int id;

  public java.A(int);
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: aload_0
       5: iload_1
       6: putfield      #2                  // Field id:I
       9: return
    LineNumberTable:
      line 7: 0
      line 8: 4
      line 9: 9
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          0      10     0  this   Ljava/A;
          0      10     1    id   I
}

public class java.B extends java.A {
  public java.B(int);
    Code:
       0: aload_0
       1: iload_1
       2: invokespecial #1                  // Method java/A."<init>":(I)V
       5: return
    LineNumberTable:
      line 6: 0
      line 7: 5
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          0       6     0  this   Ljava/B;
          0       6     1    id   I


public java.lang.String toString();
    Code:
       0: ldc           #2                  // String %d
       2: iconst_1
       3: anewarray     #3                  // class java/lang/Object
       6: dup
       7: iconst_0
       8: aload_0
       9: getfield      #4                  // Field id:I
      12: invokestatic  #5                  // Method java/lang/Integer.valueOf:(I)Ljava/lang/Integer;
      15: aastore
      16: invokestatic  #6                  // Method java/lang/String.format:(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;
      19: areturn
    LineNumberTable:
      line 10: 0
    LocalVariableTable:
      Start  Length  Slot  Name   Signature
          0      20     0  this   Ljava/B;
}
```

Here id is stored only once and B.toString retrieves id via getfield.

**Comment by odersky** [comment]
> This problem can be avoided by making A.id private at the cost of storing id in both A and B.

This would be strictly worse than what we have now. Accessor methods like this get inlined immediately by the JVM, so unless someone proves otherwise I don't see there is a performance problem. A proof would consist of a benchmark of a realistic application that shows that this can deteriorate performance. 

Note that adding a separate field does constitute a performance problem in some cases -- just create a lot of objects.

Also this is not a backend problem. The optimization to replace an extra field by a forwarder is performed in `forwardParamAccessors` in `PostTyper`.

**Comment by SethTisue** [comment]
Note that Scala 2.13.8 produces leaner bytecode here. No `id$accessor` is generated in B, instead `id` is accessed via `A.id:()I`.

**Comment by informarte** [comment]
@odersky, after I noticed the issue with duplicate members in my code, I changed the code, and then observed a performance drop of ~4% that I can only attribute to this change. To be on the safe side, I ran my benchmark several times for both versions of the code, and each time the drop was there. The benchmark is in the area of combinatorial optimization and it runs for four and half hours on four cores. The following figure depicts the speedup stats:

![avoid-duplicate-members](https://user-images.githubusercontent.com/13946903/158070626-1e9e5405-6a53-4323-a353-0aa603d8d1dd.svg)

This the project: https://github.com/informarte/yuck
The above figure compares the branch `spikes/avoid-duplicate-members` to the branch `dev`.
This is the change: https://github.com/informarte/yuck/commit/acf1230423011214267470050fce6920d7d05d84

**Comment by smarter** [comment]
Did you use jmh to run your benchmarks? Otherwise the effect you see might be limited to a cold JVM before the JIT has had a chance to inline the accessors.

**Comment by informarte** [comment]
Well, my benchmark is not exactly micro: It is implemented as a single JUnit test suite, so the JVM is invoked only once and then runs for four hours thirty.

**Comment by odersky** [comment]
The conventional wisdom is that both accessors get inlined. To be sure that's not the case (and we have a problem) we'd have to see the jitted assembly code.

**Comment by smarter** [comment]
There's a lot of thing that can affect how much inlining is done, a common trick is to use `-XX:MaxInlineLevel=35` (or use a recent version of OpenJDK where the default limit was increased, or use graalvm which is much more aggressive at inlining).

**Comment by informarte** [comment]
@smarter, thanks for your tips regarding inlining. I will give it a try and come back with the results ASAP.

**Comment by informarte** [comment]
@odersky, I tried to produce jitted assembly code. I am on Ubuntu 20.04, so I installed `libhsdis0-fcml`, but to no avail: The JVM output contains only hex codes. So it seems that the OpenJDK 16 JVM does not pick up the library or maybe there is some incompatibility. Could you (or someone else) please share some best practices on how to produce jitted assembly code on a Debian-based system?

**Comment by informarte** [comment]
hsdis-amd64.so worked for me and I can confirm that Hotspot inlines the accessor methods.

**Comment by odersky** [comment]
Thanks, that's good to know!
