### ISSUE TITLE
scala.reflect.Selectable do not expose fields of inner classes

### ISSUE THREAD

**Issue by Dolu1990** [lampepfl/dotty#14616]
Hi,

## Compiler version

3.1.1

## Minimized code

```Scala
import scala.reflect.Selectable
val x = new Selectable {
  class Data {
    val thing = 42
  }
  val data = Data()
  println(data.thing) //OK
}
println(x.data.thing) //KO value thing is not a member of spinal.core.Bundle
```

## Output

```scala
value thing is not a member of spinal.core.Bundle
    println(x.data.thing)
```

## Expectation

Should not throw an error.

Note that actualy if i move that Data class above the "val x" it compile fine.

## Context

Porting SpinalHDL internal DSL from scala 2 to scala 3. It extensively use anonymous class to provide structures and namespace.

Here is some example (to help understanding the context) :

Bundle to define hardware data structures :
https://github.com/SpinalHDL/SpinalHDL/blob/dev/lib/src/main/scala/spinal/lib/com/usb/ohci/UsbOhci.scala#L127

Area to define hardware namespaces :
https://github.com/SpinalHDL/SpinalHDL/blob/dev/lib/src/main/scala/spinal/lib/com/usb/ohci/UsbOhci.scala#L170

More generaly, i do not understand why the type of anonymous classes isn't refined and that we have to fallback on Selectable.

Here is a instance : 

```scala
val server = new Thread  {
  val socket = new ServerSocket(7894)
  override def run() : Unit = {
    // manage connection here
  }
}
//...
server.socket.close() //Can't do this that way anymore in scala 3, unless you use selectable
``` 

Why the type of the "server" field is "Thread" and not the type of the anonymous class which is defined ? This seems to cut away quite many cool usages, especialy for internal DSL.
Thanks ^^

**Comment by bishabosha** [comment]
solution:
```scala
import scala.reflect.Selectable
val x = new Selectable {
  class Data extends Selectable {
    val thing = 42
  }
  val data = Data()
  println(data.thing) //OK
}
println(x.data.thing) //KO value thing is not a member of spinal.core.Bundle
```
