### ISSUE TITLE
Add @since("3.1") to language imports

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#14634]
There is no since annotation on the language imports, so the -scala-release checker will not see. Perhaps someone could generate a reference to these in a macro that gets inlined

https://github.com/lampepfl/dotty/blob/6dc591acec1df0defb05452449fbfb60bb29bf9e/library/src/scala/runtime/stdLibPatches/language.scala#L154-L156

**Comment by prolativ** [comment]
In general references to language imports shouldn't be a problem when using `-scalaOutputVersion` set to an older version as long as they don't leave any traces in the outputs of a compilation.
Actually that's one of the reasons we struggle to support forward compatibility on TASTy level - one might be forced to produce TASTy files consumable for older compilers but want to use newer syntax.

**Comment by bishabosha** [comment]
we removed this feature
