### ISSUE TITLE
Bad code for pattern matches with values.

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#1463]
Consider the following test case adapted from pending/run/t3150:

```
object Test {
  case object Bob { override def equals(other: Any) = true }

  class Bob2 {
    override def equals(other: Any) = true
  }
  val Bob2 = new Bob2

  def f0(x: Any) = x match { case Bob2 => Bob2 } // class cast exception at runtime, dotc only
  def f1(x: Any) = x match { case Bob => Bob } // class cast exception at runtime, dotc only
  def f2(x: Any): Bob.type = x match { case x @ Bob => x } // class cast exception at runtime, dotc and javac.

  def main(args: Array[String]): Unit = {
    assert(f0(Bob2) eq Bob2)
    assert(f0(0) eq Bob2)  // only dotty fails here
    assert(f0(Nil) eq Bob2)

    assert(f1(Bob) eq Bob)
    assert(f1(0) eq Bob)  // only dotty fails here
    assert(f1(Nil) eq Bob)

    assert(f2(Bob) eq Bob)
    assert(f2(0) eq Bob) // both dotty and scalac fail here
    assert(f2(Nil) eq Bob)
  }
}
```

Dotty causes a class cast exception in three scenarios, scalac only in the last. Each class cast exception is a bug. We should decide what the precise typing and comparison rules for pattern matches involving equals tests are.

**Comment by smarter** [comment]
See the discussion in https://issues.scala-lang.org/browse/SI-1503 for more context, note that this is one of these cases where you can't trust the spec: it was updated following some discussions in this bug report and the proposed solution was later found out to be incorrect and reverted, but the spec wasn't updated. Anyway the only sane and correct thing to do here is that in:
```scala
(Vector(): Any) match { case n @ Nil => n }
```
`n` should not be cast to anything, the only thing we know about `n` is that it has type `Any` and it's `==` to `Nil`, no safe casting is possible here.

**Comment by smarter** [comment]
This should also be the behaviour of Scala 2.12 and Scala 2.11 with `-Xfuture`
