### ISSUE TITLE
Private field with non-alphanumeric identifier exhibits incorrect behavior at runtime

### ISSUE THREAD

**Issue by FlorianCassayre** [lampepfl/dotty#14667]
## Compiler version

Affects `3.0.0` to `3.1.2-RC1`.

Does not affect `2.13.8`.

## Minimized code

```Scala
trait A {
  private val ? = ""
  def a = ?
}

@main def run(): Unit = println(new A {}.a)
```

[Link to 3.1.1 Scastie](https://scastie.scala-lang.org/guffMVjITtG35SjoriJ2wQ)

## Output

```
null
```

## Expectation

This program should print an empty line, not `null`.

Observations: the problem does not occur when
* `?` is renamed to an alphanumeric identifier (**!**)
* `?` is a definition instead of a value
* `A` is a class instead of a trait
* `?` is protected or public

The `?` can be replaced with any other symbol e.g. `*`, `|||`, ... (all of those will trigger the same problem)

When replacing `""` by e.g. `1`, the program prints `0` which confirms that it is a problem related to initialization.

**Comment by odersky** [comment]
here's what we see after the Memoize phase:
```scala
final class $anon() extends Object, A {
            super()
            private val A$$?: String
            def A$$?(): String = this.A$$?
            super[A].$init()
            def A$_setter_$A$$$qmark_$eq(x$0: String): Unit = ()
            def a(): String = super[A].a()
          }
```
The problem is that the trait setter `A$_setter_$A$$$qmark_$eq` has a mangled name but the field `A$$?` is unmangled. As a consequence, the memoization code in line 171 falls into this case.
```
        val field = sym.field
        if !field.exists then
          // When transforming the getter, we determined that no field was needed.
          // In that case we can keep the setter as is, with a () rhs.
          tree
```
We should preferably use an unmangled name for the trait setter. If that does not work we have to take mangling into account when computing `field`.
