### ISSUE TITLE
SignatureHelp gives apply of the current symbol instead of enclosing apply

### ISSUE THREAD

**Issue by ckipp01** [lampepfl/dotty#14661]
## Compiler version

3.1.1

## Explanation

I hit on this with Metals but then testing in Dotty with the SignatureHelp tests it suffers from the same issue, so the fix should probably be here.

Given the following code with the `@@` signifying a trigger of the user to get signature help.

```Scala
Li@@st(1, 2,  3)
```

The user will actually get the signature help of the apply on the List. That may not seem that problematic, but when you have something like this:

```scala
def doThing(myList: List[Int]) = ???

doThing(L@@ist(1, 2, 3))
```

The user is expecting to see the signature help for `doThing`, not the apply on List.

## Example test

Here is what I used to test this:

```scala
  @Test def applyWhenYouDontWantIt: Unit = {
    val signature =
      S("apply[A]", Nil, List(List(P("elems", "A*"))), Some("CC[A]"))
    code"""|object O:
           |  def doThing(myList: List[Int]) = ???
           |  doThing(Li${m1}st(1, 2, 3)""".withSource
      .signatureHelp(m1, List(signature), Some(0), 0)
  }
```
## Expectation

The test above will pass, when you really want it to fail and to be showing you the info for doThing meaning I care about the `myList` here.

**Comment by bishabosha** [comment]
I was a bit confused reading this, do you mean you still want to see the `List.apply` method, but with `A` substituted for `Int`, so rendering in metals like `def apply(elems: Int*): List[Int]`?

**Comment by ckipp01** [comment]
> I was a bit confused reading this, do you mean you still want to see the `List.apply` method, but with `A` substituted for `Int`, so rendering in metals like `def apply(elems: Int*): List[Int]`?

No, I mean in the situation for `doThing(Li${m1}st(1,2,3))` I would hope that the signature help would show me `doThing(myList: List[Int])` with `myList` being highlight. That should be the correct behavior here imo since that's the actual enclosing apply that we care about when triggering a signature help here. This is currently how it works for Scala 2 in Metals.

<img width="416" alt="Screenshot 2022-03-11 at 10 34 12" src="https://user-images.githubusercontent.com/13974112/157841039-d319a352-7da4-4782-a7a1-b0aa82534497.png">

Whereas with Scala 3 triggering a signature help in the same position instead gives me the signature for the `List.apply`.

**Comment by prolativ** [comment]
Yeah, I didn't get it like this at the first moment. So even in a case like
```scala
val x = foo1(foo2(foo3(foo4(foo5(0)))))
```
when you hover on `foo5` you would expect to get the signature help for `foo1`?

**Comment by ckipp01** [comment]
In Scala 2 the way that it's set up in Metals is that it will also go to the closest enclosing apply. So in the situation you have @prolativ if you triggered a signature help like so:

```scala
val x = foo1(foo2(foo3(foo4(fo${m1}o5(0)))))
```
This apply you actually care about would be the closest enclosing one meaning `foo4`.

<img width="442" alt="Screenshot 2022-03-11 at 10 52 51" src="https://user-images.githubusercontent.com/13974112/157844005-58333a10-4f77-4472-ba4f-699a45ef5db5.png">

Whereas currently in Scala 3 this shows:

<img width="442" alt="Screenshot 2022-03-11 at 10 53 37" src="https://user-images.githubusercontent.com/13974112/157844124-435fe8d9-a3e5-451c-8dd8-c4df6700aa9d.png">

However this isn't what is desired. The only time the signature for `foo5` here should be shown is if you triggered it in:

```scala
val x = foo1(foo2(foo3(foo4(foo5(${m1})))))
```
Does this make sense?

**Comment by prolativ** [comment]
Ok, I think I get it now

**Comment by rochala** [comment]
> Furthermore, this behavior also leads to other issues. For example
> 
> ```scala
> def doThing(myList: List[Int], second: Int) = ???
> 
> do${m1}Thing(List(1,2,3), 2)
> ```
> 
> Will result in:
> 
> <img alt="Screenshot 2022-03-11 at 10 59 44" width="445" src="https://user-images.githubusercontent.com/13974112/157845296-d9a6a94c-bf63-4c1f-a32a-5ac7983aad00.png">
> 
> Notice how it shows the second parameter is the current one? Signature help in this scenario shouldn't return anything since you're not in an apply. You see the same thing whenever you try to trigger it on `List` for example since the apply span covers the entire `<<List(1, 2, 3)>>` not just `List(<<1, 2, 3>>`. However you really only want signature help triggerable in the latter region.

@ckipp01 Should we remove signatureHelp when its triggered by position on toplevel function name such as doThi{m1}g(Nil, "") or rather make activeParameter an Option ( it will require changes in existing tools ).

**Comment by ckipp01** [comment]
> @ckipp01 Should we remove signatureHelp when its triggered by position on toplevel function name such as `doThi{m1}g(Nil, "")` or rather make activeParameter an `Option` ( it will require changes in existing tools ).
> In my opinion we should leave signatureHelp as is and just fix activeParameter selection but what's your opinion on that. I know that metals doesn't support such calls `doThi{m1}g(Nil, "")`

So I'm most familiar with Metals and not sure how this works with other tooling, but in the scenario where the user triggers a signature help on `doThi{m1}g(Nil, "")` in Scala 2 with Metals, nothing is returned as you'd need to trigger it inside like `doThig(Nil, {m1}"")`. I'm used to this behavior so my first reaction was that in your example, the entire signature help shouldn't provide anything, but then again, I see how it'd be useful. The idea of an `activeParameter` sort of implies that it's always being triggered when you have some sort of position in the argument list, where in your example, you don't since you're not inside. @tgodzik do you by chance have any thoughts on this?
