### ISSUE TITLE
Where to download the scala-3.1.1-sdk

### ISSUE THREAD

**Issue by LiGuoshen** [lampepfl/dotty#14673]
## Compiler version

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

```Scala
println("hello, world")
```

## Output (click arrow to expand)
<details>

```scala
// TODO add output here
```
</details>

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions
