### ISSUE TITLE
Type Parameters in completions from implicit conversions not reducing properly

### ISSUE THREAD

**Issue by rochala** [lampepfl/dotty#14687]
## Compiler version
3.1.1 

## Minimized code

Completion `SingleDenotation` for snippet below is not reduced properly. It happens when we try to fire completion on implicitly converted type to other, higher kinded type.
Unluckily I don't know if you can check signatures in repl, so we must create snippet.

```Scala
import scala.language.implicitConversions
implicit def intToOption(f: Int): Option[Int] = Some(f)

1.ma
```
and now hit completion on `1.ma`.
## Output
Map method has signature of ```[A](f: A => B): Option[B]```

## Expectation
It should be properly reduced to `[B](f: Int => B): Option[B]`

**Comment by prolativ** [comment]
When https://github.com/lampepfl/dotty/issues/14689 gets fixed we should make sure the intersection of these two issues also gets handled properly

**Comment by odersky** [comment]
To whom should we assign ide-related issues like these?

**Comment by prolativ** [comment]
I guess currently I'm the one with most experience in this area

**Comment by odersky** [comment]
OK, you got them. Thanks!
