### ISSUE TITLE
Implicit conversion using given Conversion clause has no completions

### ISSUE THREAD

**Issue by rochala** [lampepfl/dotty#14689]
## Compiler version

3.1.1

## Minimized code

Completions for objects converted with given Conversion[_, _] clause are not present.

Paste following snippet into repl:
```Scala
import scala.language.implicitConversions
given Conversion[Int, Option[Int]] = Some(_)
```
Now try to complete `1.m`{hit completion}
## Output
max, min completion options

## Expectation
Option[Int] completions should also be present for `1.m`

**Comment by odersky** [comment]
There's a fairly high likelihood that new style conversions like this will be disallowed unless the language option is given. They certainly are discouraged now. So this might not be very important to fix.

**Comment by rochala** [comment]
Fixed by accident with https://github.com/lampepfl/dotty/pull/15283
