### ISSUE TITLE
Semantic bug when override `var` with `val` and no way to extends from a trait that has a `var` for a `case class`

### ISSUE THREAD

**Issue by pootow** [lampepfl/dotty#14722]
## Compiler version

3.1.1

## Minimized code

```Scala
trait HasId(var id: String)

case class Entity(override val id: String) extends HasId(id)

val entity = Entity("0001")
entity.id = "0002"
println(entity.id)
```

## Output

```scala
0001
```

## Expectation

Either does not compile or output `0002`.

My intention is that I do not want to introduce a redundant variable just for assigning to trait parameter.
```Scala
trait HasId(var id: String)

case class Entity(var idJustForAssignment: String) extends HasId(idJustForAssignment)

val entity = Entity("id")
entity.id
entity.idJustForAssignment // this is a duplication

```

and this does not work:
```Scala
trait HasId(var id: String)

case class Entity(id: String) extends HasId(id) // and this works when it's a normal class not a case class
```

and this does not work either:
```Scala
trait HasId(var id: String)

case class Entity(override var id: String) extends HasId(id)
```

So there's no way to extends from a trait that has a `var` for a case class.

**Comment by odersky** [comment]
The erroneous behavior was introduced in #13019. Before it was a compile error.

We need to make it a compile error again unless we can fix the underlying issues. This means jumping into trait_setter logic, which is not fun.

Meanwhile, the following will work:
```scala
trait HasId:
  def id: String
  def id_=(s: String): Unit

case class Entity(var id: String) extends HasId
```
