### ISSUE TITLE
[Links] Known incompatibilities with scalac

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1473]
This issue is a list of issues where dotty by-design or by-intention does not support some of the code-patterns that were previously (partially) supported by scalac. Some of those features may be partially supported under `-language:Scala2`.

Dependent method types: 
- ~disallowed dependent implicit methods https://github.com/lampepfl/dotty/pull/1467~

Overloading:
- disallowed overloading of parameter-less methods https://github.com/lampepfl/dotty/pull/1465

Widening and constraint solving:
- vals infer less precise types than equivalent `object`s
- implicit search on with type parameters in contravariant positions works differently

Supercalls:
- restriction on super-calls inside traits: https://github.com/lampepfl/dotty/issues/1392#issuecomment-235879678

Early initialisers and DelayedInit: 
- not supported https://github.com/lampepfl/dotty/issues/559

Definitions:
- unnamed type parameters not supported: https://github.com/lampepfl/dotty/issues/235

Structural types:
- we haven't yet decided if we support them and how much would be supported https://github.com/lampepfl/dotty/issues/1175. This issue is linked with HList & record types.

Weak subtyping:
- not supported. Though constant widening is supported.

**Comment by smarter** [comment]
I think it would make more sense to collect these in a wiki page.

**Comment by DarkDimius** [comment]
I would have agreed if people were reading wikis. My sample suggest that only a very small percentage of people does.

**Comment by smarter** [comment]
That suggests that we should advertise it better :). But I think a wiki page among 20 wiki pages is going to be read more than one issue among 160 issues.

**Comment by smarter** [comment]
Also, just as a sample point, the github statistics indicate that the "Getting Started" page of the wiki is read by slightly more unique visitors (100 vs 93) than the main "Issues" page: https://github.com/lampepfl/dotty/graphs/traffic

**Comment by DarkDimius** [comment]
https://github.com/lampepfl/dotty/pull/1787

**Comment by liufengyun** [comment]
Major changes are now documented in http://dotty.epfl.ch/docs/index.html `REFERENCE > OTHER CHANGED FEATURES & DROPPED FEATURES`.

Minor changes/incompatibilities now temporarily locate in wiki: https://github.com/lampepfl/dotty/wiki/Known-incompatibilities-with-scalac
