### ISSUE TITLE
IndexOutOfBounds in SourceFile.scala `contents()`

### ISSUE THREAD

**Issue by Xavientois** [lampepfl/dotty#14795]
Given a `SourcePosition` `pos` where `pos.exists` and `pos.source.exists`, I would expect that it is safe to call `startColumnPadding` on `pos`. This is not always the case, as can be seen when building the community lib `Lucre` [here](https://github.com/lampepfl/dotty/runs/5710367932?check_suite_focus=true#step:8:5930).

This exception issue occurs at `startColumnPadding` in `SourceFile.scala`, when `content()` is empty, but `length` is non-zero.

It seems content().length != length happens when length is computed from Tasty using setLineIndicesFromLineSizes instead of using calculateLineIndicesFromContents.

_Originally posted by @olhotak in https://github.com/lampepfl/dotty/pull/14683#discussion_r833193163_

**Comment by olhotak** [comment]
#14683 fixed `startColumnPadding` by replacing `length` with `content().length`, so we can probably close this.

Before #10363, `length` and `content().length` were synonyms and various functions in `SourceFile` called `length` to get `content().length`. #10363 made them different. Over time, various functions that called `length` were changed to call `content().length` instead. Now only one reference to `length` remains, in `offsetToLine`.

For future users, it would be good to document the intended meaning of `length` and how it now differs from `content().length`, to give a hint as to when to use which one. I would add such a comment myself but I don't fully understand the subtleties of the intended meaning of the new `length`.
