### ISSUE TITLE
Tests failing on Windows

### ISSUE THREAD

**Issue by martijnhoekstra** [lampepfl/dotty#1480]
Tests on Windows are failing for multiple reasons
- Path separators are assumed and checked to be "/"
- partest fails to copy ValueClasses.flags
- newline differences
- default encoding problems in slurp and writeAll

Some fixes in:  
- https://github.com/martijnhoekstra/dotty/commit/e4adf409c9093e0e5c34be3b9473d82f8d33392a (file paths and a missing string interpolator)
- https://github.com/martijnhoekstra/dotty/commit/87e24e75a99687388e1eea5d51abf9456ba02442 (line endings for repl session)
- https://github.com/martijnhoekstra/dotty/commit/76f5ff30faea01f4e3a42774c98c2b0c54dbb19d (that can probably be done a lot better)

**Comment by smarter** [comment]
Thanks for looking into this! Would you mind opening a pull request with your fixes? For https://github.com/martijnhoekstra/dotty/commit/76f5ff30faea01f4e3a42774c98c2b0c54dbb19d you might be able to set UTF8 as the default codec for everything in tests instead. I'm not sure what the best way to do this is, maybe pass `-Dfile.encoding` to the test jvm? /cc @sjrd

**Comment by martijnhoekstra** [comment]
@smarter now that I'm properly including scala-scala, I have a bunch more encoding problems, I'll try to find a better solution. would you like a PR for the first two commits first?

**Comment by smarter** [comment]
Sure.

**Comment by martijnhoekstra** [comment]
done in https://github.com/lampepfl/dotty/pull/1493

**Comment by smarter** [comment]
https://github.com/lampepfl/dotty/pull/1494 was merged so I think we can close this one.
