### ISSUE TITLE
Scaladoc incorrectly creates method signatures from extensions

### ISSUE THREAD

**Issue by rochala** [lampepfl/dotty#14811]
## Compiler version

3.1.2-RC2

## Minimized example
Generated documentation for methods from extensions have signatures without parameters.

 ```
class A

extension (a: A) def fun(x: Int) = x + 1
```

## Output

![image](https://user-images.githubusercontent.com/48657087/160792537-fab18cd7-54cf-429c-b800-8dadec2fa6a9.png)

## Expectation
Output should show proper signature for method fun. In this example it should be: `def fun(x: Int): Int`

**Comment by prolativ** [comment]
This seems to be working correctly with the newest docs, e.g. https://dotty.epfl.ch/api/scala/IArray$.html#partition-ffffffff

**Comment by rochala** [comment]
https://dotty.epfl.ch/api/scala/IArray$.html#partition-ffffffff this is not method which is accessible via extension, but this is declaration of extension. I can't find such usage in existing documentation, but still it doesn't work properly as it does for implicitly added methods https://dotty.epfl.ch/api/scala/Int.html#+-ffffffb7
