### ISSUE TITLE
Scaladoc snippet expanding and copying regression 

### ISSUE THREAD

**Issue by rochala** [lampepfl/dotty#14824]
## Compiler version
3.1.3 - RC1

## Minimized example
Scaladoc snippet copy ignores newlines when it's done via "copy" icon.
Scaladoc snippets has option to show collapsed lines with toggle button. It doesn't work right now as you can see at: https://dotty.epfl.ch/api/scala/quoted/Quotes$reflectModule$ClassDefMethods.html#body-5f

## Output

![image](https://user-images.githubusercontent.com/48657087/161299988-7dafb2c3-8564-42d4-a0a9-77c4c6e4409e.png)

## Expectation

Snippets copying should properly include newlines.
Snippets should be expanded properly as they did in earlier versions ( this is scala 3.1.1 ) 
https://scala-lang.org/api/3.1.1/scala/quoted/Quotes$reflectModule$ClassDefMethods.html
![image](https://user-images.githubusercontent.com/48657087/161300373-0240c2e3-4f8e-4bf2-8c76-05c3e3e8fb2d.png)

**Comment by pikinier20** [comment]
Recently bumped highlight.js is removing `.hideable` class in highlighted snippets...

**Comment by pikinier20** [comment]
I did some workaround to make the current version work properly. After few checks I'm gonna make a PR
