### ISSUE TITLE
Support parsing record classes in Java source files

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#14846]
We need to forward-port @harpocrates's https://github.com/scala/scala/pull/9551. Note that our equivalent of Scala 2's JavaParsers is in https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/parsing/JavaParsers.scala.

**Comment by som-snytt** [comment]
I got my feet wet on text blocks. The harpocratic oath requires I do no harm, or harp. I'll (try to) follow this up. No better way to learn about new java features.

**Comment by harpocrates** [comment]
Thanks and I'm sorry I didn't do the right thing of porting this over to Dotty. I must've just forgotten... 😬

**Comment by charpov** [comment]
Any progress on this, or an estimate as to when records will be supported? I'm dealing with Java applications with Scala tests, and it's frustrating not to be able to use records, especially since Scala 2 was fixed. Could this issue's priority be bumped up? Thanks.

**Comment by som-snytt** [comment]
I'll make time some time for this, as a break from another PR with annoying test failures.

**Comment by charpov** [comment]
> I'll make time some time for this, as a break from another PR with annoying test failures.

Thank you.  Just checking you didn't find something more interesting to do in the meantime ;-).
I know it's a small thing (who uses Java records in mixed Scala/Java projects?), but I happen to have two projects with them, and it complicates my life tremendously.

**Comment by som-snytt** [comment]
I suspect I figured out the annoying test failures, but I don't have great success moving PRs thru the pipeline.

**Comment by TheElectronWill** [comment]
We've started to work on it during the Spree with @odd

**Comment by mbovel** [comment]
Removing the Spree label as there is a finished open PR (#16762).

**Comment by SethTisue** [comment]
If you are a user who is running into the lack of this, consider changing your project to set `compileOrder` to use `CompileOrder.JavaThenScala` (or, if appropriate for your code, `CompileOrder.ScalaThenJava`) instead of the default `CompileOrder.Mixed`. This will tell the Scala compiler not to attempt to process the Java sources.

see https://www.scala-sbt.org/1.x/docs/Java-Sources.html
