### ISSUE TITLE
[debug] code gen for WHILE loop unfriendly for debugging

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1484]
Given the code:

```
    var a = 1 + 2

    while (a * 8 < 100) { // first jump to end
      a += 1
    }
```

The compilation generates following code, which has an unnecessary jump at the beginning:

```
       9: goto          37                                         <---- unnecessary jump
      12: iload_2
      13: bipush        8
      15: imul
      16: bipush        100
      18: if_icmplt     24
      21: goto          34
      24: iload_2
      25: iconst_1
      26: iadd
      27: istore_2
      28: goto          12
      31: nop
      32: nop
      33: athrow
      34: goto          40
      37: goto          12
```

**Comment by DarkDimius** [comment]
My guess is that Closure tree has wrong position.

**Comment by liufengyun** [comment]
It seems to me it's related to how `while` is compiled. The code snippet above compiles to something like follows:

``` Scala
      {
        def while$(): Unit =
          if a.*(8).<(100) then {
            a = a.+(1)
            while$()
          } else ()
        while$()
      }
```

With such a translation, it seems natural for the backend to generate the byte code above.

**Comment by DarkDimius** [comment]
@liufengyun, is the problem that you can see this forward jump in the debugger? if yes, this may be because `while$()` tree has wrong position. AFAIK this can be fixed without changing the compilation scheme of labels.

**Comment by liufengyun** [comment]
@DarkDimius Yes, when I step through the code, it first goes to the end of `WHILE` and then goes back to the beginning. I'll investigate as you hinted, thanks a lot.
