### ISSUE TITLE
Update to asm 9.3 for Java 19 

### ISSUE THREAD

**Issue by hepin1989** [lampepfl/dotty#14869]
## Compiler version

Scala 3.1.x

https://asm.ow2.io/versions.html

>new Opcodes.V19 constant for Java 19

## Expectation
Java 19 is supported.
refs: https://github.com/scala/bug/issues/12570

**Comment by smarter** [comment]
> Expectation: Java 19 is supported.

Note that this upgrade isn't needed to support Java 19 which should work out of the box (unless they break something), it's only needed to be able to pass `19` to the `-release` flag.
