### ISSUE TITLE
[debug] incorrect jumping between cases in patmat

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1486]
When step through the method `f`, it jumps randomly back and forth in cases.

``` Scala
object Test {
  sealed abstract class CL3Literal
  case class IntLit(i: Int) extends CL3Literal
  case class CharLit(c: Char) extends CL3Literal
  case class BooleanLit(b: Boolean) extends CL3Literal

  // incorrect jumping among cases
  def f(tree: CL3Literal) : Unit = tree match {
    case IntLit(x) =>
      println(x)
    case CharLit(x) => println(x)
    case BooleanLit(x) =>
      println(x)
  }

   def main(args: Array[String]): Unit = {
     val a = 1 + 2
     val b = a * 9
     f(IntLit(3)) 
     f(CharLit('A'))
     f(BooleanLit(false))
  }
}
```

**Comment by DarkDimius** [comment]
I have an idea to try to fix all those issues with pattern-matching\closures\whiles.
What if we don't emit line numbers for:
 -  `Apply` nodes if the target has flag `Label`;
 - `Closure` nodes if the target has flag `Synthetic`;
 - `DefDef` that has flag `Label`.

@liufengyun, you can try this out be redefining `DottyBackendInterface.treeHelper.pos` to return NoPosition for those cases.

**Comment by liufengyun** [comment]
@DarkDimius thanks a lot, I'm trying.

**Comment by retronym** [comment]
related scalac ticket: https://github.com/scala/scala-dev/issues/187

**Comment by liufengyun** [comment]
@DarkDimius I tried with following changes, the problem still persists.

```Scala
    def pos: Position = a match {
      case t: Apply if t.symbol.is(Flags.Label) => NoPosition
      case t: Closure if t.symbol.is(Flags.Synthetic) => NoPosition
      case t: DefDef if t.symbol.is(Flags.Label) => NoPosition
      case _ => a.pos
    }
```

Thanks for the pointer @retronym , It's interesting to know IntelliJ behaves different from jdb.
