### ISSUE TITLE
[debug] tail IF expression in a method

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1487]
When stepping through following code with `x == 0`, it will go through line 2 and **5**, while the correct path should be 2, **3**.

``` Scala
1  def fact(x: Int): Int = {
2    if (x == 0)
3      1
4    else
5      x * fact(x - 1) // Error: incorrectly reach this line when x = 0
6  }
```

**Comment by liufengyun** [comment]
The commit 3beddb3 partially fixed the pos of literals. To completely fix this problem, it seems we need to change the codegen:

```
When IF is the last expression in a method, generate a RETURN instead of GOTO.
```

Following generated code illustrates this change:

```
  public int fact(int);
    Code:
       0: iload_1
       1: iconst_0
       2: if_icmpeq     8
       5: goto          12
       8: iconst_1
       9: goto          21        <===    "ireturn" instead of "goto 21" here!!!
      12: iload_1
      13: aload_0
      14: iload_1
      15: iconst_1
      16: isub
      17: invokevirtual #20                 // Method fact:(I)I
      20: imul
      21: ireturn
    LineNumberTable:
      line 2: 0
      line 3: 0
      line 4: 8
      line 6: 12
```

**Comment by DarkDimius** [comment]
@liufengyun, I don't thing that's a change that we can easily make.
goto isn't aware that it jumps to a return: it just jumps to the end of the if.

What we can to do though, is make the return have line __6__ in your example, which will be more logical.

**Comment by liufengyun** [comment]
@DarkDimius that's what I tried initially. It has following problems:

1. It will trigger an additional stop at the end of the method (not a big issue).
2. If the `{ }` is omitted, `ireturn` will have the same line number of the `else` branch, thus have the same issues.
3. The `LabelDefs` removes the enclosing `{ }` in the code example above, thus have the same problem as in 2.

**Comment by DarkDimius** [comment]
> The LabelDefs removes the enclosing { } in the code example above, thus have the same problem as in 2.

I'm working on a rewrite of LabelDefs. Unfortunatelly it introduces 2x slowdown so far....

@liufengyun, another option is give the return position of method start(line 1 in your example).

**Comment by liufengyun** [comment]
> another option is give the return position of method start(line 1 in your example)

That can be a simpler workaround. I  agree making `genLoadIf` context-aware will complicate the code unnecessarily.
