### ISSUE TITLE
[debug] unfriendly jumping in evaluating lazy val block

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1488]
When stepping through the evaluation of the lazy block, it will jump back and forth between line 1 and `LazyHolders.scala` several times, that's acceptable, given how lazy vals are implemented.

However, it also jumps to the end of the block **before** evaluation of the body, which is not friendly.

``` Scala
0  def test() = {
1     lazy val a = {
2       val b = 8 * 9
3       val c = b + 5
4       c + b
5     }
6     println(a)
7  }
```

**Comment by DarkDimius** [comment]
@liufengyun, lazy vals are implemented differently depending on if they are:

 - a field or a local variable;
 - `@volatile` or not;
 - nullable or not.

which particular case in this choice-space was examined?

**Comment by liufengyun** [comment]
Thanks for the tip. It's local variable for this issue, without additional annotation. I'll test other kinds of lazy vals as you indicated.

I've updated the code to provide more context.

**Comment by liufengyun** [comment]
@DarkDimius FYI, lazy val fields debug well.
