### ISSUE TITLE
Can't get inherited types from Quotes

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/dotty#14902]
## Compiler version

2ec9c52

## Minimized code

Having a symbol of a class, we can retrieve from compiler API the information about:
- declared methods
- declared + inherited methods
- declared fields
- declared + inherited fields
- declared types

However, we can't retrieve information about **inherited types**.

## Expectation

Looking at the API, I'm not sure if it's not a oversight since there's a naming convention:
 - `declaredMethods` - methods declared in a class
 - `methodMembers` - methods declared in a class and inherited
 - `declaredFields` - fields declared in a class
 - `fieldMembers` - fields declared in a class and inherited

And the method: `typeMembers` breaks the convention since it returns only declared types.

Aren't we missing this method?

**Comment by nicolasstucki** [comment]
Indeed, `typeMembers` is supposed to return all type members. it seems that right now it does the same as `declaredTypes`. This is a bug.
