### ISSUE TITLE
Port missing changes from the Scala 2 backend (bug fixes for inner class generation, refactorings, optimizations ...)

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#14912]
The Scala 2 and 3 backend diverged many years ago and we're missing a lot of changes that went into the Scala 2 backend. We haven't altered the structure of our backend too much, so in theory it should be possible to port changes from Scala 2 piece-by-piece. We've done that so far to port various bugfixes, but we should do the same for the bigger structural changes, if only because it would allow us to more easily diff the two backends and see what else we might be missing. I had a quick look through the history and I think the big missing pieces we should port in order are:
- [ ] https://github.com/scala/scala/pull/3826
- [ ] https://github.com/scala/scala/pull/3931
- [x] https://github.com/scala/scala/pull/4807
- [x] https://github.com/scala/scala/pull/6012
- [x] https://github.com/scala/scala/pull/6057
- [x] https://github.com/scala/scala/pull/6124

Note that we don't have a backend optimizer, so anything related to it can be ignored, we can consider adding back the optimizer afterwards.
@lrytz: did I miss anything?

**Comment by smarter** [comment]
Tentatively assigning @Kordyjan since he's listed as primary maintainer in https://github.com/lampepfl/dotty/blob/main/MAINTENANCE.md, it's possible this could be done piecewise during sprees too with the help of a backend maintainer.

**Comment by som-snytt** [comment]
I have an interest in helping out in this area. I was just poking around back there for some reason.

I noticed I added `-Ygenasmp` but it's on a branch that Odersky beat me to closing the ticket.

If you enable syntax, half the people will be overjoyed and half will despise you. But in the backend, everyone ignores you, up until you break something and then everyone hates you. So, it's win-win.

**Comment by He-Pin** [comment]
Should this be included in release 3.3.0? @Kordyjan

**Comment by SethTisue** [comment]
@WojciechMazur time to check another box here...?

**Comment by WojciechMazur** [comment]
AFAIR the first two tasks were already incorporated into the Dotty, so probably the last remaining one is parallelisation (rebase in progress)

**Comment by He-Pin** [comment]
@WojciechMazur does all thest been ported, in case missed.
