### ISSUE TITLE
regression: Integer overflow in nesting level of a Macro expansion (PolyType/TypeBounds) between 3.1.1 and 3.1.2

### ISSUE THREAD

**Issue by arixmkii** [lampepfl/dotty#14921]
## Compiler version

3.1.2

## Minimized code

It requires some macro magic to reproduce and I didn't manage to extract the minimal reproducible code. But it manifests with one specific open source project https://github.com/davenverse/epimetheus

If you perform git clone and then run sbt (in my case JDK 17 was used) with these commands it will encounter compilation errors. 

```
++ 3.1.2; Test / compile
```

## Output

sbt log

```
[error] -- Error: ~/epimetheus/core/src/test/scala/io/chrisdavenport/epimetheus/CounterSpec.scala:30:68 
[error] 30 |        counter <- Counter.labelled(cr, Name("boo"), "Boo Counter", Sized(Label("foo")), {(s: String) => Sized(s)})
[error]    |                                                                    ^
[error]    |Could not decrease the nesting level of a from 2147483647 to 6 in
```
And a lot more of `PolyType` and `TypeBounds` output.

## Expectation

Compile w/o errors like it was with 3.1.1
```
++ 3.1.1; Test / compile
```

**Comment by arixmkii** [comment]
Edited previous reply to minimize it more.

**Comment by arixmkii** [comment]
Updated once again. This is now the most minimal what I can provide.

**Comment by bishabosha** [comment]
the example still fails for me without the macro, so I removed it
