### ISSUE TITLE
Improving safe-init errors for promotion failure

### ISSUE THREAD

**Issue by Xavientois** [lampepfl/dotty#14928]
We should improve the error message for promotion failure. (Here, `this` is warm because its outer is not initialized (Rule 1) but the QualifiedName class does access some fields (namely the cache at the top) of its outer (Rule 2). But the error message doesn't say anything about that.)

_Originally posted by @olhotak in https://github.com/lampepfl/dotty/issues/14918#issuecomment-1098081637_

**Comment by olhotak** [comment]
This was fixed by #15659. Closing.
