### ISSUE TITLE
Incorrect inexhaustivity warning when leafs are defined in an unrelated sealed trait

### ISSUE THREAD

**Issue by kitlangton** [lampepfl/dotty#15029]
## Compiler version

3.1.1

## Minimized code

Here is a [Scastie](https://scastie.scala-lang.org/WwDjucNPS4ekVwn2977OKA).

The exhaustivity check fails when instances of Schema are defined in a trait.

```Scala
sealed trait Schema[A]

object Schema extends RecordInstances

sealed trait RecordInstances:
  case class Field[A]() extends Schema[A]
  case object Thing extends Schema[Int]

import Schema._

// Match not exhaustive error! (with fatal warnings :P)
def handle[A](schema: Schema[A]) =
  schema match
    case Field() => println("field")
    case Thing   => println("thing")
```

## Expectation

While it is a bit odd to define these instances in a trait, I would still expect this to correctly check exhaustivity. Scala 2 works as expected here.

**Comment by kitlangton** [comment]
On second thought. Maybe this is more sound. I don't know why the code I'm working on was originally organized like this—I think I can merely remove these intermediate traits. Feel free to close this if you agree!

**Comment by som-snytt** [comment]
For example,
```
@main def test() = println {
  val r = new RecordInstances {}
  val s = r.Thing
  handle(s)
}
```

**Comment by smarter** [comment]
There is an exhaustiveness issue here since RecordInstances isn't sealed (but the error message wording is a bit confusing: it says `RecordInstances.Field()` when it should say something like `_: RecordInstances#Field`). However, if RecordInstances is sealed the error doesn't go away when it should (but it's a pretty weird thing to do indeed).

**Comment by kitlangton** [comment]
@smarter @som-snytt Apologies. It actually still fails: https://scastie.scala-lang.org/WwDjucNPS4ekVwn2977OKA
Forgot to seal both in my example (updating my issue link now)

**Comment by som-snytt** [comment]
Also Scala 2 warns. `It would fail on the following inputs: Field(), Thing, _`

**Comment by smarter** [comment]
> It causes another similar compiler error here ([scastie.scala-lang.org/2ME3I1HIQuyUAe67T2jziw](https://scastie.scala-lang.org/2ME3I1HIQuyUAe67T2jziw))

That looks like an unrelated bug (missing substitution of RecordInstances.this into Schema), could you open a separate issue for it?

**Comment by kitlangton** [comment]
> Also Scala 2 warns. `It would fail on the following inputs: Field(), Thing, _`

Oh yeah... Don't know why that didn't trigger fatal warnings for me in Scala 2. The solution for me was to replace these traits with `// RECORD INSTANCES` comment headers instead 😛. I think someone just wanted the organizational niceties of traits to organize a very large sealed  trait file.

**Comment by som-snytt** [comment]
It also still warns when the case class is final.
