### ISSUE TITLE
Multiline generators with braceless syntax not recognized

### ISSUE THREAD

**Issue by markuswt** [lampepfl/dotty#15039]
## Compiler version

3.1.2

## Minimized code

```Scala
for {x <-
  val k = 3
  1 to k
} println(x)
```

## Output

```
-- [E018] Syntax Error: --------------------------------------------------------
1 |for {x <-
  |         ^
  |         expression expected but val found

longer explanation available when compiling with `-explain`
-- [E040] Syntax Error: --------------------------------------------------------
4 |} println(x)
  |^
  |'<-' expected, but '}' found
```

## Expectation

The given code should be valid, as `<-` [can be followed](https://docs.scala-lang.org/scala3/reference/syntax.html) by an indented block. This is also mentioned in the [optional braces reference](https://docs.scala-lang.org/scala3/reference/other-new-features/indentation.html).

Interestingly, these two examples work:

```Scala
for (x <-
  val k = 3
  1 to k
) println(x)
```

```Scala
for {x <- {
  val k = 3
  1 to k
  }
} println(x)
```

**Comment by som-snytt** [comment]
My guess is that it's necessary to incur an initial indent:
```
  for {
    x <-
      val k = 3
      1 to k
  } println(x)
```
Otherwise, the example is indistinguishable from "ordinary for with braces".

Something similar came up recently, I'll link if I can find it; or I'll delete this comment if it is way off base.

**Comment by markuswt** [comment]
Thanks, I think you're right. Closing this issue because #11444 resulted in no changes.
