### ISSUE TITLE
names of anonymous functions generated as annotation arguments are not unique

### ISSUE THREAD

**Issue by robmwalsh** [lampepfl/dotty#15054]
## Compiler version
3.1.1

## Minimized code
https://scastie.scala-lang.org/JyCTJBMCRIKW73xNmAuaLA
```scala
import scala.annotation.Annotation

class AnAnnotation(function: Int => String) extends Annotation

@AnAnnotation(_.toString)
val a = 1
@AnAnnotation(_.toString.length.toString)
val b = 2
```

## Output

```scala
Double definition:
def $anonfun(_$2: Int): String in object Playground at line 9 and
def $anonfun(_$1: Int): String in object Playground at line 7
```

## Expectation
generated anonymous functions should have unique names

**Comment by robmwalsh** [comment]
similar issue for annotations on function arguments
https://scastie.scala-lang.org/9pEHR8DqSr6MbGci5ONv0w
and
https://scastie.scala-lang.org/gFlKy6QATEqpQcNyvs7R4w

**Comment by odersky** [comment]
Thanks for the report, and sorry it took so long to fix.

**Comment by robmwalsh** [comment]
Thanks for the fix :)
