### ISSUE TITLE
`@targetName` on toplevel class/trait/object fails separate compilation

### ISSUE THREAD

**Issue by griggt** [lampepfl/dotty#15066]
## Compiler version

3.2.0-RC1-bin-20220427-b1f00a7-NIGHTLY and earlier

## Minimized code

**Foo.scala**

```scala
@annotation.targetName("Bar") class Foo:
  def it: Int = 42
```

**Test.scala**

```scala
@main def Test = println(Foo().it)
```

## Output

```
$ scalac Foo.scala
$ scalac Test.scala
-- [E006] Not Found Error: Test.scala:1:25 -------------------------------------
1 |@main def Test = println(Foo().it)
  |                         ^^^
  |                         Not found: Foo
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

## Expectation

I understand that supporting `@targetName` on class/trait/object is intentional (see https://github.com/lampepfl/dotty/issues/11969#issuecomment-812090356), thus I would expect such usage to work with separate compilation.

## Remarks

No issue with joint compilation.
No issue if `Foo` is an inner class.

**Comment by griggt** [comment]
I don't see an efficient was to support this, since the symbol loader determines the entered symbol name from the classfile name

https://github.com/lampepfl/dotty/blob/f29eea79bb1bae6849dd9842c131b2eb1c1d1cb8/compiler/src/dotty/tools/dotc/core/SymbolLoaders.scala#L204-L205

and to do otherwise would likely require eagerly reading the classfile?

Can we just disallow `@targetName` on toplevel class/trait/object?

**Comment by smarter** [comment]
Hmm, this also breaks the convention that there's a Foo.tasty matching Foo.class, so I now agree that we should just disallow this.
