### ISSUE TITLE
Code coverage crashes at runtime

### ISSUE THREAD

**Issue by MasseGuillaume** [lampepfl/dotty#15078]
I was testing the new coverage support for scala3 with:

The latest version of `sbt-scoverage`
https://github.com/scoverage/sbt-scoverage/tree/V2

with https://github.com/scoverage/sbt-scoverage/blob/V2/src/main/scala/scoverage/ScoverageSbtPlugin.scala#L162 set to 3.2.0-RC1-bin-SNAPSHOT

This call crashes with the instrumented code:

https://github.com/MasseGuillaume/porc-epic/blob/main/src/test/scala/porcEpic/unit/VisualizationTest.scala#L53

https://github.com/MasseGuillaume/porc-epic/blob/07157829817afd03d286f056f3c0dda3fd5e6eca/src/main/scala/porcEpic/Visualization.scala#L59-L80

## Compiler version

latest (main branch)

## Minimized code

```scala
import java.nio.file._
import java.io.File

extension (v: Int) {
  def save(): File = {
    Files.createTempDirectory("porc-epic").toFile
  }
}

1.save()

```

## Output (click arrow to expand)
<details>
java.lang.ClassCastException: class scala.collection.immutable.ArraySeq$ofRef cannot be cast to class [Ljava.nio.file.attribute.FileAttribute; (scala.collection.immutable.ArraySeq$ofRef is in unnamed module of loader sbt.internal.ScalaLibraryClassLoader @53bcaacb; [Ljava.nio.file.attribute.FileAttribute; is in module java.base of loader 'bootstrap')
    at porcEpic.Visualization$package$.save(Visualization.scala:61)
    at porcEpic.unit.VisualizationTest.$init$$$anonfun$2(VisualizationTest.scala:91)
</details>

**Comment by smarter** [comment]
Can you take a look @TheElectronWill

**Comment by TheElectronWill** [comment]
I'll take a look. Thanks for reporting!

**Comment by smarter** [comment]
This issue has a really high concentration of Guillaumes :sweat_smile:

**Comment by som-snytt** [comment]
Will power!

**Comment by MasseGuillaume** [comment]
> This issue has a really high concentration of Guillaumes sweat_smile

Guillaume³ taking over the world.

**Comment by TheElectronWill** [comment]
It seems that the types generated by the lifter are wrong for varargs with type arguments.
Produced code, with coverage enabled:
```scala
extension (v: Int) def save(): java.io.File = 
      {
        scala.runtime.coverage.Invoker.invoked(2, "target/o")
        {
          {
            scala.runtime.coverage.Invoker.invoked(1, "target/o")
            {
              val $1$: String = "porc-epic"
              val $2$: java.nio.file.attribute.FileAttribute[?]* = 
                ([ : java.nio.file.attribute.FileAttribute[?]]*)
              {
                scala.runtime.coverage.Invoker.invoked(0, "target/o")
                java.nio.file.Files.createTempDirectory($1$, $2$)
              }
            }.toFile()
          }
        }
      }
```
`-Ycheck:all` catches the problem at `refchecks`:
```scala
*** error while checking target/bug.scala after phase refchecks ***
exception occurred while compiling target/bug.scala
java.lang.AssertionError: assertion failed: Found:    ($2$ : java.nio.file.attribute.FileAttribute[?]*)
Required: Array[? <: java.nio.file.attribute.FileAttribute[?]]
found: ??
expected: ??
```
