### ISSUE TITLE
Failing .type on class parameter

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#1507]
```scala
class Example[K](k: K) {
  def example: Option[k.type] = None
}
```

fails with

```
error: non-private method example refers to private value k
 in its type signature => Option[K(Example.this.k)]
      def example: Option[k.type] = None
          ^
```

(Simple workaround: change `k: K` to `val k: K`)

**Comment by julienrf** [comment]
What result would you expect? (I think that’s scalac behaves the same)

**Comment by sjrd** [comment]
IMO this is *exactly* what we want. The public `def example` must not have a type that depends on the private `k`.

**Comment by OlivierBlanvillain** [comment]
Makes sense, thanks @sjrd
