### ISSUE TITLE
CC Tracking information is lost when calling a lambda defined in a class

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#15112]
## Compiler version

`cc-experiment` head, `08597054504d8deeee543301b771c509074b8993` commit.

## Minimized code

```Scala
@main def Test =
  class Foo(val m: {*} String):
    val set: {m} String -> Unit = v => println(v)
  val f = Foo("Mutation")
  val use: String -> Unit = v => f.set(v)
```

## Output

Compiles

## Expectation

Fails. The following fails as expected:

```scala
@main def Test =
  val m: {*} String = "Mutation"
  val set: {m} String -> Unit = v => println(v)
  val use: String -> Unit = v => set(v)
```

**Comment by odersky** [comment]
This is actually as intended. The class parameter has type {*} String, but the actual class arguments are pure, so the capture set is not kept. That's the whole idea of dependent class parameters.
