### ISSUE TITLE
The purpose of https://dotty.epfl.ch should be clarified and the content should be updated accordingly

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#15111]
The dotty website https://dotty.epfl.ch currently contains several pages that were relevant when Dotty was not yet Scala 3.0.0, especially the section [Usage](https://dotty.epfl.ch/docs/usage), which is now largely covered by the [Getting Started page](https://docs.scala-lang.org/getting-started) of the Scala documentation website. Same for the section [Contributing](https://dotty.epfl.ch/docs/contributing), which is redundant with the [Scala 3 Contributing Guide](https://docs.scala-lang.org/scala3/guides/contribution/contribution-intro.html).

When we created the documentation content in the Scala documentation website, we did not immediately remove the corresponding content from the Dotty website, to allow for a smooth transition, but I think it is now time to remove the content that should be hosted on the Scala documentation website instead.

What needs to be done:
- [x] Remove the “Usage” section (if its content is not already covered by the Scala documentation, it should be added there)
- [x] Explain clearly the purpose of the https://dotty.epfl.ch on its frontpage (it targets developers or contributors, it shows the API documentation of the nightlies, and some internal documentation), and put a link to the actual Scala documentation website for users.
- [x] Update the “Contributing” section (the content that is covered by the [Scala 3 contributing guide](https://docs.scala-lang.org/scala3/guides/contribution/contribution-intro.html) should be moved here)

**Comment by Dedelweiss** [comment]
Hello, a discussion was held in PR #17253 between @dwijnand and @bishabosha (whose feedback I would like to thank). I just wanted to make a summary here in order to be sure of what should be done. From what I understood, it would be more interesting to move the [contribution part in Scala-lang](https://docs.scala-lang.org/scala3/guides/contribution/contribution-intro.html) to the [Dotty documentation](https://dotty.epfl.ch/docs/contributing/index.html) (where the contribution takes place and which thus makes more sense.) Thus one would remove the contribution part in Scala-lang, taking into account however that the sources are more up to date and that it will be necessary to copy them at the time of the move. I hope I have understood correctly and I am willing to do it if it is not a problem.

**Comment by julienrf** [comment]
I personally think the website dotty.epfl.ch is a source of confusion because it overlaps and repeats with content that is already on the _main_ Scala website. It gives the feeling that Dotty and Scala are two different things. As a user of Scala, I would expect to find all the documentation in one place, the scala-lang.org website.

I keep thinking that all the content related to external contributions should be in https://docs.scala-lang.org/contribute/, which currently documents how to contribute to the Scala 2 compiler (the scala/scala repo), and the Scala documentation (scala/docs.scala-lang). So, that place already covers things that live in separate repositories. I don’t think this is a big deal. It should also cover contributions to the Scala 3 compiler.

**Comment by dwijnand** [comment]
> I personally think the website dotty.epfl.ch is a source of confusion because it overlaps and repeats with content that is already on the _main_ Scala website. It gives the feeling that Dotty and Scala are two different things.

Fair, and I would be in favour of doing something that assists remove that confusing, except removing the content from this repo.  For instance I wouldn't mind if the content here (both the contributor docs and the experimental docs) here somehow hosted under scala-lang.org, or if it just wasn't hosted and the content were just viewed as rendered markdown - though that would be quite the visual regression.

> As a user of Scala, I would expect to find all the documentation in one place, the scala-lang.org website.

As I said, I wouldn't mind if the contents here were somehow viewed through scala-lang.org.

> I keep thinking that all the content related to external contributions should be in [docs.scala-lang.org/contribute](https://docs.scala-lang.org/contribute/), which currently documents how to contribute to the Scala 2 compiler (the scala/scala repo), and the Scala documentation (scala/docs.scala-lang). So, that place already covers things that live in separate repositories. I don’t think this is a big deal. It should also cover contributions to the Scala 3 compiler.

OK, so it covers itself and the scala/scala repo.  Then if we need consistency I'd in favour of moving the scala 2 contribution docs to the scala/scala repo.

**Comment by julienrf** [comment]
> I wouldn't mind if the content here (both the contributor docs and the experimental docs) here somehow hosted under scala-lang.org

We do that with the [Scala 3 Reference](https://docs.scala-lang.org/scala3/reference/), and IMHO that brings a lot of complications (see e.g. #16867).

I really think the simplest solution to maintain is to move the source files to the docs.scala-lang repo.

**Comment by julienrf** [comment]
Or, if the sources stay here, they should not be rendered to the dotty.epfl.ch website, but they should just be Markdown files sitting in a directory and linked from the `CONTRIBUTING.md`.

**Comment by julienrf** [comment]
After an internal discussion, I think it is fine to move the .md files here. The most important thing being to not have duplicate/redundant docs, so merging the contributing docs with what we currently have on docs.scala-lang and putting it either here or there is already a good step forward.

Then, if we store the .md files here, it is also fine to render them in the website dotty.epfl.ch but we need to be clear about the purpose of that website in the frontpage. Currently, it still says “Scala has pioneered the fusion of object-oriented and functional programming in a typed setting. Scala 3 will be a big step towards realizing the full potential of these ideas.” which is weird because Scala 3 was released two years ago. I will update the first post of this issue with a proposal of action plan.
