### ISSUE TITLE
add addendum to implicit search failure for failed Mirror synthesis

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#15128]
I think it would be desirable to indicate why implicit search for a mirror fails.

tasks:
- in [Synthesizer](https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/typer/Synthesizer.scala) collect reasons for why synthesis fails (indicated by when a branch returns `EmptyTree`) - (whyNotGenericSum/whyNotGenericProduct) are good starts because they already generate error message strings that are later ignored.
- add the collected errors to the implicit search failure message that is emitted in [Implicits](https://github.com/lampepfl/dotty/blob/981732366432cd2045bf1c5baa26e3443b829fb1/compiler/src/dotty/tools/dotc/typer/Implicits.scala#L863)

ideas for implementation:
- `synthesizer.tryAll` returns a tuple of `(Tree, List[String])`, where non-empty list indicates errors, then any errors are attached to the `SearchFailureType` of the tree returned from `inferImplicitArg`

**Comment by szymon-rd** [comment]
I'm taking on this issue.
