### ISSUE TITLE
Type matched class cannot be referenced using `classOf`

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#15155]
## Compiler version
3.2.0-RC1-bin-20220429-400427d-NIGHTLY

Works with 3.1.2

The first bad commit is 54dc0c19e76841384bb13595cf74929a55122339 from #14761

## Minimized code

```scala
//> using scala "3.2.0-RC1-bin-20220429-400427d-NIGHTLY"

// Last working version
// //> using scala "3.1.2"

import scala.reflect.ClassTag
// https://github.com/json4s/json4s/blob/355d8751391773e0d79d04402a4f9fb7bfc684ec/ext/src/main/scala-3/org/json4s/ext/package.scala#L4-L8
type Aux[A] = { type Value = A }
type EnumValue[A <: Enumeration] = A match {
  case Aux[a] => a
}

// https://github.com/json4s/json4s/blob/355d8751391773e0d79d04402a4f9fb7bfc684ec/ext/src/main/scala/org/json4s/ext/EnumSerializer.scala#L25-L26
class EnumSerializer[E <: Enumeration: ClassTag](enumeration: E) {
  val EnumerationClass = classOf[EnumValue[E]]
}
```
## Output

```scala
[error] ./test.scala:15:34: EnumValue[E] is not a class type
[error]   val EnumerationClass = classOf[EnumValue[E]]
[error]                                  ^^^^^^^^^^^^```
```

## Expectation
Should correctly allow getting an instance of Class for Enum.Value

**Comment by nicolasstucki** [comment]
The first bad commit is 54dc0c19e76841384bb13595cf74929a55122339

**Comment by odersky** [comment]
It looks indeed plausible that #13780 is the PR that makes it fail.

I added a `summon[EnumValue[A]]` and got:
```
Note: a match type could not be fully reduced:
   |
   |  trying to reduce  EnumValue[E]
   |  failed since selector  E
   |  does not match  case Aux[a] => a
   |  and cannot be shown to be disjoint from it either.
```

**Comment by odersky** [comment]
I am not sure the match type is supposed to reduce. Maybe use a TypeTest? But I don't know enough about the details here.

**Comment by odersky** [comment]
@OlivierBlanvillain, do you have an opinion about this issue?

**Comment by OlivierBlanvillain** [comment]
> I am not sure the match type is supposed to reduce.

I'm also not sure. This code is asking the compiler to show that `E <: Aux[a]`, knowing that `E <: Enumeration` and `type Aux[A] = { type Value = A }`. Looking at the definitions, `Value` is an abstract inner class of [Enumeration](https://github.com/scala/scala/blob/4b2151cbe4c857d49556b70c3fa0f5e236fd7754/src/library/scala/Enumeration.scala#L224), so it feels like `E` *could* be a subtype of the `{ type Value = A }` refinement, but I don't know how those two features interact (inner classes vs refinement types)...
