### ISSUE TITLE
Pattern matching on GATD generating `.asInstanceOf[Nothing]`

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#1515]
The following example:

```scala
sealed trait Trait[T]

final case class Case[T](e: T) extends Trait[T]

object Demo {
  def main(args: Array[String]): Unit = {

    def f[H](t: Trait[H]): Unit =
      t match {
        case Case(e) => println(Some(e))
      }

    f(Case(1))

  }
}
```

Fails at run time with `java.lang.ClassCastException: java.lang.Integer cannot be cast to scala.runtime.Nothing$`.

**Comment by smarter** [comment]
I have some work-in-progress GADT fixes that I think are related to this, I'll take a look in the next few days

**Comment by OlivierBlanvillain** [comment]
Ping @smarter (I think this issue is affecting large portions of Scalatest source code)

**Comment by smarter** [comment]
Alright, let me get this on top of my todo list
