### ISSUE TITLE
`movedTo` link in documentation is a 404

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#15167]
https://dotty.epfl.ch/docs/reference/language-versions/source-compatibility.html points to https://docs.scala-lang.org/scala3/reference/language-versions.html which doesn't exist. I haven't checked if other pages have the same issue.

**Comment by bishabosha** [comment]
I think the correct link is https://docs.scala-lang.org/scala3/reference/language-versions

**Comment by pikinier20** [comment]
This is going to be resolved by: https://github.com/lampepfl/dotty/pull/15146

**Comment by ckipp01** [comment]
> This is going to be resolved by: https://github.com/lampepfl/dotty/pull/15146

Since this has been merged and the original issue seems to be fixed, I'll go ahead and close this. Please do report back if there is still something missing here.
