### ISSUE TITLE
Match exhaustivity is broken when case class contains java enum field 

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#15179]
## Compiler version
3.1.3-RC3
When testing in the source project (link below) if fails with 3.1.2 also, works correctly with 3.1.1

## Minimized code
Based on https://github.com/kirill5k/mongo4cats/blob/ed6a5c112c16e71af2557efa9f4e5f45f9a63551/core/src/main/scala/mongo4cats/collection/queries/WatchQueryBuilder.scala#L125-L137

FullDocument.java
```Java 
package changestream;

public enum FullDocument {
    DEFAULT("default"),
    UPDATE_LOOKUP("updateLookup"),
    WHEN_AVAILABLE("whenAvailable"),
    REQUIRED("required");

    private final String value;
    FullDocument(final String caseFirst) {
        this.value = caseFirst;
    }
}

```

QueryCommand.scala
```Scala
package queries

sealed private[queries] trait QueryCommand

private[queries] object QueryCommand {
  final private[queries] case class FullDocument(fullDocument: changestream.FullDocument)       extends QueryCommand
  final private[queries] case class AllowDiskUse(allowDiskUse: Boolean)                         extends QueryCommand
  final private[queries] case class BypassDocumentValidation(bypassDocumentValidation: Boolean) extends QueryCommand
}
```

test.scala
``` Scala 
//> using scala "3.1.3-RC3"

package queries

def test() =
  val command: queries.QueryCommand = ???
  command match {
    case QueryCommand.FullDocument(doc) => ???
    case QueryCommand.AllowDiskUse(v)   => ???
    case _ => ???
  }
```

```Bash
javac -d . FullDocument.java  
./bin/scalac QueryCommand.scala test.scala
```
Reproducing with scala-cli for different Scala version is not determistic - might or might not give a warning

## Output

```scala
-- [E030] Match case Unreachable Warning: test.scala:9:9 ----------------------------------------------------------------------------------------
9 |    case QueryCommand.FullDocument(doc) => ???
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |         Unreachable case
1 warning found
```

## Expectation
Compiler should know give an incorrect exhaustivity warning

**Comment by bishabosha** [comment]
I think this should have been fixed by https://github.com/lampepfl/dotty/pull/15109, could you try with a nightly?

**Comment by WojciechMazur** [comment]
I've also had a similar issue when compiling another project with 3.2.0-RC1 nightly, but it was not using java classes and I was not able to minimize it outside the project. 
https://github.com/gemini-hlsw/gsp-graphql/blob/3c14c0ed2827c334e7d1c875afbc081bf0d1ebe1/modules/sql/src/main/scala/SqlMapping.scala#L1799-L1804

Simplified snippet given a warning, but only in that project.
```Scala
  def x: SqlDiscriminatedType = ???
  val ctpe = Some(x) match {
     case Some(discriminator) => ???
     case _ => ???
  }

Output:
[info] compiling 9 Scala sources to /home/wmazur/projects/virtuslab/dotty-community/gsp-graphql/modules/sql/target/scala-3.1.2/classes ...
[error] -- [E030] Match case Unreachable Error: /home/wmazur/projects/virtuslab/dotty-community/gsp-graphql/modules/sql/src/main/scala/SqlMapping.scala:1803:19 
[error] 1803 |          case Some(discriminator) => ???
[error]      |               ^^^^^^^^^^^^^^^^^^^
[error]      |               Unreachable case
[error] one error found
```

**Comment by WojciechMazur** [comment]
@bishabosha I've run it now with 3.2.0-RC1-bin-SNAPSHOT-git-9dbe2d3 and it seems to work. 
@Kordyjan should we make an 3.1.3-RC4 with regression fixes chery-picked from current main?

**Comment by Kordyjan** [comment]
Am I reading it correctly?
```
3.1.1         -> OK
3.1.2         -> broken
3.1.3-RC3     -> broken
3.2.0-nighlty -> OK
```

**Comment by WojciechMazur** [comment]
@Kordyjan yes, this is correct, it seems to be broken in 3.1.2 and 3.1.3-RC3

**Comment by dwijnand** [comment]
Just for context, the "breakage" in [3.1.2,3.2.0) comes from my fix to the warning emission (which wasn't stable before: unrelated changes would cause untouched warnings from be emitted).
