### ISSUE TITLE
Decide upon approach to structural types

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1517]

**Comment by olafurpg** [comment]
Related discussion #1175.

**Comment by sirinath** [comment]
Perhaps it might be worthwhile to look into other languages like OCaml which uses structural types and also make this an opportunity to improve on structural types.

**Comment by olafurpg** [comment]
Here is a summary of structural types containing defs in the wild: https://github.com/olafurpg/syntax-experiments/issues/2

The sample is taken from these projects: https://github.com/olafurpg/scala-repos/tree/master/repos

Seems like many of them are in scala/scala jetbrains/intellij-scala

**Comment by edmundnoble** [comment]
Have we considered removing structural types? From your analysis @olafurpg it looks like structural types with defs are used more in Scala's compiler tests than anywhere else, and if we came up with a story for first-class type projections I don't think they'd have any uses at all.

**Comment by smarter** [comment]
The latest status of structural types is the new implementation (which is not tied to Java reflection, although it can support it to) at: https://github.com/lampepfl/dotty/pull/1881

**Comment by odersky** [comment]
Superseded by #1886 and #1881.
