### ISSUE TITLE
Docs should not show annotations by default

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#15196]
## Compiler version

3.2

## Minimized example

What I see at https://dotty.epfl.ch/api/scala/collection/immutable/List$.html:

```
[@SerialVersionUID](https://dotty.epfl.ch/api/scala/SerialVersionUID.html)(3L)
object List extends StrictOptimizedSeqFactory]
```

## Expectation

The annotation should not be printed. The same should go by default for most other annotations. Maybe we want to show some of the annotations (but which ones?). But then they should be shown in a separate section.

**Comment by odersky** [comment]
@pikinier20 I believe this is now fixed? If yes, please close the issue.

**Comment by SethTisue** [comment]
PR: #15361
