### ISSUE TITLE
Windows scripts do not delegate to MainGenericRunner

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#15220]
if we want a unified experience across  platforms then the windows batch scripts should replicate the bash scripts for other platforms, i.e. delegate to the `MainGenericRunner`

i.e. see how https://github.com/lampepfl/dotty/blob/main/dist/bin/scala does minimal preprocessing of the arguments before delegating to the class `dotty.tools.MainGenericRunner`

@michelou I have assigned you since you made the original scripts, but feel free let us know if you do not want to.

**Comment by michelou** [comment]
@bishabosha With [PR 15275](https://github.com/lampepfl/dotty/pull/15275) (backport to the 3.1.3 branch) this issue now affects both upcoming 3.1 and 3.2 releases.

**Comment by michelou** [comment]
@bishabosha Work is in progress.
I have changes in the 4 batch files (`common.bat`, `scala.bat`, `scalac.bat` and `scaladoc.bat`).

Two remarks regarding the changes : 
- batch files are now shorter (positive effect).
- changes are quite large, so more testing is needed.

Do you know what are the release deadlines for 3.1.3 and 3.2.0-RC1 ?

**Comment by griggt** [comment]
> Do you know what are the release deadlines for 3.1.3

3.1.3-RC4 was released to Maven Central earlier today: https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.1.3-RC4/

see https://github.com/lampepfl/dotty/issues/15282

**Comment by Kordyjan** [comment]
> Do you know what are the release deadlines for 3.1.3 and 3.2.0-RC1 ?

As of now, the date is June 1st.

**Comment by prolativ** [comment]
Fixed via https://github.com/lampepfl/dotty/pull/15325
