### ISSUE TITLE
sum mirror is available when mirror for child can't be summoned

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#15222]
The fix for https://github.com/lampepfl/dotty/pull/14986 does not consider when a sum type has a child for which the mirror can not be summoned.

## Compiler version

3.2.0-RC1-bin-20220517-e5abec0-NIGHTLY

First bad commit d6e17a23e65e8efa0dea608eb5dbfc490a977bd1 in #15008

## Minimized code

```Scala
import scala.deriving.Mirror

package lib {
  sealed trait Foo
  object Foo // Mirror.Of[Foo] cached in companion
  case class Bar private[lib] () extends Foo
  case object Bar // force mirror for Bar to be anonymous.
}

package app {
  val mFoo = summon[Mirror.SumOf[lib.Foo]]
  val mBar = summon[Mirror.ProductOf[lib.Bar]] // error
}
```

## Output

```scala
-- Error: test.scala:11:49 -------------------------------------------------------------
11 |  val mBar = summon[Mirror.ProductOf[lib.Bar]] // error
   |                                                 ^
   |No given instance of type deriving.Mirror.ProductOf[lib.Bar] was found for parameter x of method summon in object Predef. Failed to synthesize an instance of type deriving.Mirror.ProductOf[lib.Bar]: class Bar is not a generic product because the constructor of class Bar is innaccessible from the calling scope.
```

## Expectation

`summon[Mirror.SumOf[lib.Foo]]` should also fail because in the calling scope, the child of Foo, i.e. `Bar` can not have a mirror - this affects signatures of Foo, because object Foo should not cache the mirror.

**Comment by bishabosha** [comment]
this example is quite problematic - from within `lib`, `Bar` is accessible, so from `Foo`'s perspective Bar should have a mirror, however the moment we move outside of `lib`, there is no longer a mirror for `Bar`.

So what to do?
- 1) mirror for `Foo` is anonymous, therefore it will exist in `lib`, but not outside. This will remove `Mirror.Sum` subclass and `ordinal` method from the companion compared to if it were compiled by `3.1`. - so a bincompat issue
- 2) no mirror for `Foo` ever. - more consistent, but same issue with bincompat.
- 3) cache Mirror for `Foo` in its companion, but make it inaccessible outside of `lib`. (i.e. do not synthesize a mirror in `app`) This is completely compatible

**Comment by nicolasstucki** [comment]
The first bad commit is d6e17a23e65e8efa0dea608eb5dbfc490a977bd1

**Comment by joroKr21** [comment]
Why does the child also need to have a mirror?

**Comment by bishabosha** [comment]
> Why does the child also need to have a mirror?

A type is only a "generic sum" if all of its children are also either "generic sum" or "generic product".

That has been the rule forever, so we should be quite careful to consider this recursive case whenever we change the rules for mirror generation

**Comment by bishabosha** [comment]
mirrors are meant to represent an algebraic data type, and that all parts mentioned by the mirror should be reachable.
The mirror for `Foo` will mention `Bar` in its `MirroredElemTypes`. the user should then be able to iterate through `MirroredElemTypes` to summon the mirror for `Bar` programatically. This operation is meant to be total
