### ISSUE TITLE
docs: theme slider does not work when window is narrow

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#15239]
Edit: when window is narrow, such that the right-table-of contents overlaps with the theme slider, it is no longer interactive

**Comment by pikinier20** [comment]
I use the same version of Chrome on Mac and everything works fine.
Could you check if there are no errors in console?

**Comment by bishabosha** [comment]
here are the log messages in chrome:
```scala
DevTools failed to load source map: Could not load content for http://dotty.epfl.ch/js/scaladoc-js-contributors-opt.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://dotty.epfl.ch/js/bootstrap.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://dotty.epfl.ch/scripts/scaladoc-js-main-opt.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://dotty.epfl.ch/scripts/engine-js-opt.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Comment by pikinier20** [comment]
Everything looks fine. Have you tried loading the page with disabled cache? This is really strange because I've got literally the same environment and there's no problem on my side

**Comment by griggt** [comment]
I have the same problem but it goes away if I make the browser window wider or maximized.  Perhaps something to do with the table of contents on the right?

**Comment by bishabosha** [comment]
> I have the same problem but it goes away if I make the browser window wider or maximized. Perhaps something to do with the table of contents on the right?

oh you are right, if I widen the window it works
