### ISSUE TITLE
two different ways to unapply type from one object

### ISSUE THREAD

**Issue by rochala** [lampepfl/dotty#15230]
## Compiler version

3.1.3-RC2

## Minimized code

We can unapply same type in 2 different ways. Example in repl.

```scala
object ProdEmpty:
  def _1: Int = 1
  def _2: String = "abc"
  def isEmpty = false
  def unapply(s: String): this.type = this
  def get = this
```

```scala
"" match
  case ProdEmpty(x) => x

"" match 
  case ProdEmpty(x, y) => s"$x, $y"
```

Outputs:
```scala
val res0: ProdEmpty.type = ProdEmpty$@4a922149
val res1: String = 1, abc
```

When there is only 1 extractor method:
```scala
object ProdEmpty:
  def _1: Int = 1
  def isEmpty = false
  def unapply(s: String): this.type = this
  def get = this
```

```scala
"" match
  case ProdEmpty(x) => x
```
Outputs:
```scala
val res2: ProdEmpty.type = ProdEmpty$@26fdec81
```

## Expectation

I would expect it not to compile at all.

I'm not sure if it's a bug, but as far as I am concerned there should be only one way to unapply type from single object.
@dwijnand what do you think?

**Comment by dwijnand** [comment]
> I would expect it not to compile at all.
> 
> I'm not sure if it's a bug, but as far as I am concerned there should be only one way to unapply type from single object. @dwijnand what do you think?

I also thought something was funky about this back in 2016, but I was arguing it was returning the wrong type: https://github.com/scala/bug/issues/9836

Which code are you saying shouldn't compile?  I can't see why you would say the last version with one `_1` selector and one `x` pattern shouldn't compile.  So I assume you mean that it shouldn't be possible to have both `case ProdEmpty(x)` and `case ProdEmpty(x, y)`.

I would back you up that argument, on personal preference.  But the documentation (https://dotty.epfl.ch/docs/reference/changed-features/pattern-matching.html) talks about "precedence", which I take to mean: which rule to honour if 2 or more rules match.  But is it true to say that if the extractor qualifies as a product match of 2 elements, it shouldn't also qualify for use as a name-based match?

Looks like @liufengyun added that passage to the docs, so perhaps he can weigh in his perception and opinion?  I think it's  a reasonable argument, and I wouldn't mind seeing someone run an experiment of what (if any) tests or community projects fail if we apply this change.

**Comment by liufengyun** [comment]
> Looks like @liufengyun added that passage to the docs, so perhaps he can weigh in his perception and opinion? I think it's a reasonable argument, and I wouldn't mind seeing someone run an experiment of what (if any) tests or community projects fail if we apply this change - but I don't have that time for that at the moment.

Thanks for pinging, Dale. I agree the example above can be surprising to end users. However, the extractor in the example above conforms to the protocol for product match, single match, and named-based match --- it is rather atypical.

From the specification point of view, we want rules that are simple and precise. If we want to avoid such surprise, i.e., make the meaning of extractors independent of their usage, we would need to define rules to specify what is a valid extractor, and ideally, the compiler needs to enforce such rules _at the definition site_. I don't see an elegant way to specify and implement such checks. But if there is a way to achieve that, there seems to be no reason to not do it.

**Comment by dwijnand** [comment]
I think what's necessary is separating the classification of an extractor from its correct or incorrect usage.  `ProdEmpty` should only be considered as a product match of 2 elements, and never as a name-based extractor.  Getting the compiler to warning because of the additional presence of isEmpty/get might be fine or maybe it's better as an opt-in lint warning.

**Comment by dwijnand** [comment]
Turns out I wasn't reading this right at all.  Let's start at the top, but I'm going to tweak the example:

```scala
object ProdEmpty1:
  def isEmpty                       = false
  def unapply(s: String): this.type = this
  def get                           = new Tuple1(1)

object ProdEmpty2:
  def isEmpty                       = false
  def unapply(s: String): this.type = this
  def get                           = (1, "abc")

class Test:
  def test1    = "" match { case ProdEmpty1(x)      => x: Tuple1[Int]      }

  def test2_1  = "" match { case ProdEmpty2(x)      => x: (Int, String)    }
  def test2_2a = "" match { case ProdEmpty2((x, y)) => (x: Int, y: String) }
  def test2_2b = "" match { case ProdEmpty2(x, y)   => (x: Int, y: String) }

  def opt1  (x: Option[(String, String)]) = x match { case Some(_)      => case _ => }
  def opt1_2(x: Option[(String, String)]) = x match { case Some((_, _)) => case _ => }
  def opt2  (x: Option[(String, String)]) = x match { case Some(_, _)   => case _ => }
```

Turns out there isn't a problem in precedence between name-based matching and product matching.  This is wholly within the specification of name-based matching.  When there's only one sub pattern, then you're binding the result of `get`, when there's more than one then you're not binding that and binding the components of that result.  *Not* doing that, aka making `test1` fail to compile, would also mean that `test2_1`, `test2_2a`, `opt1`, and `opt1_2` wouldn't compile!  Which we just can't do.
