### ISSUE TITLE
Wrong signature help in two edge cases

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#15244]
## Compiler version

`3.2.0-RC1-bin-20220519-ee9cc8f-NIGHTLY`

## Minimized code

For signature help with cursor located at `@@`:
1.
```scala
object a {
  List(1, 2@@
}
```
2.
```scala
object a {
  def curry(a: Int, b: Int)(c: Int) = a
  curry(1)(3@@)
}
```

## Output

Empty output.

## Expectation

1.
```scala
apply[A](xs: A*): List[A]
         ^^^^^^
```

2.
```scala
curry(a: Int, b: Int)(c: Int): Int
                      ^^^^^^
```

**Comment by tgodzik** [comment]
Actually, scratch that. It seems only the second case  is failing.

**Comment by tgodzik** [comment]
I added another case for a broken code that should still suggest signature help.

**Comment by tgodzik** [comment]
Another potential thing to fix:
```
object a {
  Option(1, 2, @@2)
}
```

we should still show signature help for Option even if user wrote too much.

**Comment by rochala** [comment]
Do we ever want to show tuple signature ? In my opinion no, what do you say ?

**Comment by tgodzik** [comment]
> Do we ever want to show tuple signature ? In my opinion no, what do you say ?

I would say that we don't want to show it ever.
