### ISSUE TITLE
Type inferring with enum case and val is not transparent

### ISSUE THREAD

**Issue by qiujiangkun** [lampepfl/dotty#15256]
## Compiler version
Scala compiler version 3.1.0 -- Copyright 2002-2021, LAMP/EPFL

## Minimized code

```Scala
enum Foo:
  case Bar()
  case Baz()
object Main {
  def iWantBar(bar: Foo.Bar) = ()
  def main(args: Array[String]): Unit = {
    val bar = Foo.Bar()
    iWantBar(bar)
  }

}

```

## Output

```text
Could not compile
Found:    (bar : Foo)
Required: Foo.Bar
    iWantBar(bar)

```

## Expectation
It compiles, like the following two examples
```scala
 iWantBar(Foo.Bar())

```
```scala
    val bar: Foo.Bar = Foo.Bar()
    iWantBar(bar)
```

**Comment by bishabosha** [comment]
This is a documented design choice that Enum types are widened unless the narrow type is requested

**Comment by bishabosha** [comment]
In https://docs.scala-lang.org/scala3/reference/enums/adts.html there is the quote

Generally, the type of a enum case constructor application will be widened to the underlying enum type, unless a more specific type is expected. This is a subtle difference with respect to normal case classes. The classes making up the cases do exist, and can be unveiled, either by constructing them directly with a new, or by explicitly providing an expected type.
