### ISSUE TITLE
Generated `given` instances' names are the same for different types

### ISSUE THREAD

**Issue by nikololiahim** [lampepfl/dotty#15316]
## Compiler version
3.1.2

## Minimized code

```Scala
//> using scala "3.1.2"

trait Thing[A]
trait Box[A]

given Thing[Box[Int]] = new Thing[Box[Int]] {}
given Thing[Box[String]] = new Thing[Box[String]] {}

```

## Output

```scala
Double definition:
final lazy given val given_Thing_Box: Thing[Box[Int]] in package object bug$package at line 6 and
final lazy given val given_Thing_Box: Thing[Box[String]] in package object bug$package at line 7
bloop
```

## Expectation
The code should compile and the instances of `Thing` for both `Box[String]` and `Box[Int]` should be available.

**Comment by som-snytt** [comment]
It specifies "top-level argument type constructors" at https://dotty.epfl.ch/docs/reference/contextual/relationship-implicits.html#anonymous-given-instances

which is linked from https://dotty.epfl.ch/docs/reference/contextual/givens.html#anonymous-givens

where it says the generated names are not conflict-free.

The only problem in computer science harder than naming is automatic name generation.

**Comment by bishabosha** [comment]
as mentioned above, this problem is documented and as specified, so I will close.

I'm not sure of your original code but something like the following work?
```scala
given [T](using Box[T]): Thing[Box[T]] = ...
```

you can also use a type alias:
```scala
type BoxInt = Box[Int]
type BoxString = Box[String]
given Thing[BoxInt] = new Thing[BoxInt] {}
given Thing[BoxString] = new Thing[BoxString] {}
```

**Comment by nikololiahim** [comment]
@bishabosha @som-snytt The workarounds do work. Thank you for the pointers to docs!
