### ISSUE TITLE
Improve error messaging in sidebar YAML parser

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/dotty#15326]
https://github.com/lampepfl/dotty/blob/main/scaladoc/src/dotty/tools/scaladoc/site/SidebarParser.scala
contains only general info about the file format and returns a general error for all problems. The idea is to improve the error handling so that user can see an erroneous line or which information is missing.

**Comment by gringrape** [comment]
Could I work on this?

**Comment by julienrf** [comment]
Thank you for your interest, sure, feel free to do so! Do you already have a specific plan in mind?

**Comment by gringrape** [comment]
> Thank you for your interest, sure, feel free to do so! Do you already have a specific plan in mind?

Thank you. Actually, I don't have plan not right now. But, I am interested in this and want to check detail.
Or could you share your idea?

**Comment by julienrf** [comment]
I don’t have anything in particular off the top of my head: I would try to write incorrect sidebar files, look at the output of scaladoc, and see how to improve it…

**Comment by gringrape** [comment]
> I don’t have anything in particular off the top of my head: I would try to write incorrect sidebar files, look at the output of scaladoc, and see how to improve it…

Thank you! I'll try and tell the any progress or question here.

**Comment by Dedelweiss** [comment]
Hello @gringrape, I was going to start correcting this issue but I see that you have started working on it. Is this still the case? Have you started anything?

**Comment by Dedelweiss** [comment]
I have started a first PR with some questions, if you are interested to see it.
