### ISSUE TITLE
Case class named apply has surprising behavior/error message

### ISSUE THREAD

**Issue by adampauls** [lampepfl/dotty#15332]
## Compiler version

3.1.2-RC2.

## Minimized code

```scala
sealed abstract class Enum

object Enum {
  final case class apply(x: Int)
}

Enum(1) // error: object apply in object Enum does not take parameters
Enum.apply(1) // fine
```
## Output

Error mentioned above.

## Expectation

I hesitate to call this a bug, but it is a slightly surprising behavior. One might expect the auto-insertion of `apply` to "see through" the auto-generated `object apply` to its inner `apply`. Alternatively, one might expect `object`s not to be eligible for `apply` auto-insertion. I think that's effectively true now, but the error message could be a little more clear: `method apply is not a member of object Enum` or something like that.

I'm a little surprised that
```scala
object Enum
Enum(1)
```

also gives `object Enum does not take parameters`. I think it could similarly benefit from the same error message that makes explicit that `apply` is missing, since `object`s never "take parameters", except via the `apply` method (AFAIK). 

For context, I got here by trying

```scala
enum Enum {
  case apply(x: Int)
}
```

It's a strange thing to do, but I thought it might work.

**Comment by som-snytt** [comment]
scala 2
```
i15332.scala:9: error: Enum.type does not take parameters
  def f(): Unit = Enum(1) // error: object apply in object Enum does not take parameters
                      ^
```
