### ISSUE TITLE
Exponential type checking time of nested Tuples

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#1535]
This example complies in ~16 seconds on my machine, and goes to ~32 seconds with one additional level of nesting.

``` scala
object Example {
  case class C[H, T](h: H, t: T)

  type I = Int

  val p
    : C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,C[I,I]]]]]]]]]]]]]]]]]]]]]]]
    = C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,C(1,1)))))))))))))))))))))))
}
```

This explosion only happens when _both_ the type and the value are provided, commenting the `:` line or replacing the `=` line with `= ???` leads to normal compilation times. For some reason things work fine when replacing `C` with `Tuple2`.

**Comment by odersky** [comment]
Comparing with `scalac` I get:

    /Users/odersky/workspace/dotty/tests/pos> time java -Xms1g -Xmx3g dotty.tools.dotc.Main i1535.scala
    17.688u 0.705s 0:13.11 140.1%	0+0k 0+6io 0pf+0w
    /Users/odersky/workspace/dotty/tests/pos> time scalac i1535.scala
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
    25.356u 0.386s 0:20.38 126.2%	0+0k 0+3io 0pf+0w

So `dotc` is no worse than `scalac` here, even slightly better.

**Comment by odersky** [comment]
It would be good to run a profiler over this example to see whether the time is spent.

**Comment by odersky** [comment]
@OlivierBlanvillain do you want to dig deeper here?

**Comment by retronym** [comment]
For both scalac and dotc, the type alias seems crucial to provoking the problem.

```
dotc -J-Xprof sandbox/test.scala

Flat profile of 13.32 secs (1039 total ticks): main

 ...

     Compiled + native   Method
 24.7%   257  +     0    dotty.tools.dotc.core.TypeComparer.compareNamed$1
 22.4%   232  +     1    dotty.tools.dotc.core.TypeComparer.thirdTry
 10.1%   104  +     1    dotty.tools.dotc.core.TypeComparer.compareRefined$1
  5.2%    54  +     0    dotty.tools.dotc.core.SymDenotations$ClassDenotation$$anonfun$baseTypeRefOf$2.apply
```

```
% qscalac -J-Xprof sandbox/test.scala

Flat profile of 18.80 secs (1445 total ticks): main
     Compiled + native   Method
 33.1%   478  +     0    scala.reflect.internal.Symbols$Symbol.typeParams
 26.7%   376  +     9    scala.reflect.internal.tpe.TypeComparers.firstTry$1
 20.0%   289  +     0    scala.reflect.internal.SymbolTable.isSubType
  3.1%    44  +     1    scala.reflect.internal.Symbols$Symbol.info
  2.6%    37  +     0    scala.collection.AbstractTraversable.nonEmpty
```

In scalac, it looks like we end up with the aliased and dealised type as the lower bounds of the type variable:

![image](https://cloud.githubusercontent.com/assets/65551/19382260/19870760-924b-11e6-936f-0c453158d0b5.png)

which might be a contributing factor.

**Comment by odersky** [comment]
@retronym Very interesting analysis. That looks like a good candidate to dig deeper!

**Comment by retronym** [comment]
See also https://bugs.openjdk.java.net/browse/JDK-8055984 / https://bugs.openjdk.java.net/browse/JDK-8046685 / http://hg.openjdk.java.net/jdk9/dev/langtools/rev/3793a6706e58 for some similar problems+solutions form javac.

**Comment by smarter** [comment]
This example now compiles in 3 seconds for me, and the compilation time does not seem to significantly increase when adding more nesting. Closing.
