### ISSUE TITLE
Implicit search does not work for `x.type`

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#15366]
## Compiler version
3.1.2

## Minimized code
```Scala
import scala.compiletime.constValue

opaque type T1[N <: Int] = Unit
opaque type T2[C, N <: Int] = C

trait Holder[A] {
  type V <: Int
}

inline transparent given [A <: Int]: Holder[T1[A]] = new Holder {
  override type V = A
}

inline transparent given [C, A <: Int]: Holder[T2[C, A]] = new Holder {
  override type V = A
}

inline def value[A](using h: Holder[A]): Int = constValue[h.V]

value[T1[42]] // ok for explicit type with one parameter
value[T2[String, 42]] // ok for explicit type with two parameters

val x1: T1[42] = ()
val x2: T2[String, 42] = ""

value[x1.type] // ok for field type with one parameter
value[x2.type] // error for field type with two parameters
```

## Output
https://scastie.scala-lang.org/TZPeFw3tTpSv0PTKMdeyPg

```scala
no implicit argument of type Playground.Holder[(Playground.x2 : Playground.T2[String, (42 : Int)])] was found for parameter h of method value in object Playground.
I found:

    Playground.given_Holder_T2[Any, Int]

But given instance given_Holder_T2 in object Playground does not match type Playground.Holder[(Playground.x2 : Playground.T2[String, (42 : Int)])].
```

## Expectation
Successful compilation.

**Comment by odersky** [comment]
This needs a better minimization and explanation.

 - `transparent` is not necessary to trigger the error
 - `inline` is not necessary to trigger the error
 - what should be the inferred implicit argument for `value[x2.type]`? Have you tried supplying it manually?

**Comment by scf37** [comment]
I assumed `value[x2.type]` should be identical to `value[T2[String, 42]]` because `val x2: T2[String, 42]`.
However, second one compiles while first one does not.

I'm not even sure this is a bug, it is just weird `summon[T]` works while `val x: T = ... ;  summon[x.type]` doesn't.

**Comment by odersky** [comment]
> I assumed value[x2.type] should be identical to value[T2[String, 42]] because val x2: T2[String, 42].

No, the two types are different. It's like if `x: Int` then `x.type` is still not the same as `Int`. So I think we can close this.
