### ISSUE TITLE
Update documentation for Eclipse setup

### ISSUE THREAD

**Issue by sschaef** [lampepfl/dotty#1537]
The docs on [how to build dotty in Eclipse](https://github.com/lampepfl/dotty/wiki/Building-Dotty-on-Eclipse) are outdated, they are not enough to build dotty successfully in Eclipse because some dependencies are not found. For example there are compilation errors in `dotty/src/dotty/tools/backend/jvm/DottyBackendInterface.scala` because types such as `ApplyDynamicDeconstructor` are not found. Where can one find the sources or binaries for `ApplyDynamicDeconstructor`?

**Comment by felixmulder** [comment]
Hi @sschaef - thanks for reporting on this. Since @odersky is the only person currently running Eclipse - he's best poised to answer this question.

Thanks again for reporting on this,
Felix

**Comment by smarter** [comment]
This stuff comes from the scalac fork where the dotty backend resides, did you follow the second step precisely? It says to add the latest jar you'll find in l`.ivy2/cache/me.d-d/scala-compiler/jars/`

**Comment by sschaef** [comment]
I see, I thought a more recent compiler version was needed than the one that was available the time when the docs were written. Therefore I ignored this step. The compilation errors indeed go away after including this predefined scala-compiler JAR.

Are these types hardcoded in the compiler? Because Eclipse still can't find the definitions of these types.

There is only one compilation error left: [`ENUM`](https://github.com/lampepfl/dotty/blob/db354748e387f664db4eae2aa61e1a17037548e8/src/dotty/tools/dotc/core/unpickleScala2/PickleBuffer.scala#L254) can't be found.

**Comment by smarter** [comment]
> Are these types hardcoded in the compiler? 

No: https://github.com/DarkDimius/scala/blob/sharing-backend/src/compiler/scala/tools/nsc/backend/jvm/BackendInterface.scala#L360

**Comment by sschaef** [comment]
The last compilation error with `ENUM` can be solved by using scala-reflect 2.11.5 in favor of a newer version.

**Comment by felixmulder** [comment]
Thank you @sschaef - the wiki has been updated to include this information.

**Comment by Blaisorblade** [comment]
Just tried the new instructions: adding scala-reflect 2.11.5 wasn't quite enough, seemingly because 2.11.8 was still on the classpath.
To fix that, I removed the Scala library container and add a standard library as an external JAR from project `dotty`.

Since ScalaIDE defaults to the latest Scala, would it be an option to switch to that too?

**Comment by smarter** [comment]
> Since ScalaIDE defaults to the latest Scala, would it be an option to switch to that too?

We'd love that, the issue is that the dotty backend is a fork of the scalac 2.11.5 backend and needs to be brought up to date
