### ISSUE TITLE
Redo two recent reversals

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#15373]
We had to revert #13780 and #14026. These two PRs both fixed soundness bugs but the fixes broke too much code. 

We need to address the original bugs re-introducing these PRs after applying some fixes or complements to them.

**Comment by odersky** [comment]
See #15432 as a replacement for #13780

**Comment by dwijnand** [comment]
> #15423 is now merged. Should this ticket still be open?

And #15746 addressed #14026, as I see it.  So yes, IMO.
