### ISSUE TITLE
scala.concurrent.ExecutionContext.Implicits.global hangs forever

### ISSUE THREAD

**Issue by gfZeng** [lampepfl/dotty#15380]
## Compiler version

3.1.2

```sh
java version "17.0.3" 2022-04-19 LTS
Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)
```

## Minimized code

`jstack` shows nothing about my code, even nothing about scala code.

Just 1 thread, 1c1g AWS ec2

```
"scala-execution-context-global-46" #46 daemon prio=5 os_prio=0 cpu=20.53ms elapsed=1207.73s tid=0x00007f5bdc0309d0 nid=0x32a3 waiting on condition  [0x00007f5bbeefc000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@17.0.3/Native Method)
        - parking to wait for  <0x00000000f6987950> (a scala.concurrent.impl.ExecutionContextImpl$$anon$3)
        at java.util.concurrent.locks.LockSupport.parkUntil(java.base@17.0.3/LockSupport.java:410)
        at java.util.concurrent.ForkJoinPool.awaitWork(java.base@17.0.3/ForkJoinPool.java:1726)
        at java.util.concurrent.ForkJoinPool.runWorker(java.base@17.0.3/ForkJoinPool.java:1623)
        at java.util.concurrent.ForkJoinWorkerThread.run(java.base@17.0.3/ForkJoinWorkerThread.java:165)
```

## Output
no output

## Expectation
no exception

**Comment by dwijnand** [comment]
Please use https://users.scala-lang.org/ for general questions.

**Comment by SethTisue** [comment]
You haven't made the nature of the bug clear (not to me or to Dale anyway), and you haven't provided instructions for reproducing the problem. Therefore this doesn't qualify as a bug report.... yet?

**Comment by som-snytt** [comment]
Worth adding that the pool thread is presumed innocent: there is no hanging here.

Whether there is something about AWS that could demonstrate a JVM in such a state? It seems unlikely, but maybe it's a good interview question.
