### ISSUE TITLE
Missing arity check in fromProduct for Tuples

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#15399]
## Compiler version

438dfb024faa91f4239f346fa4f496a20c5e3d15

## Minimized code

```Scala
@main def Test =
  val tup2Mirror = summon[scala.deriving.Mirror.Of[(Int, Int)]]
  val tup2a: (Int, Int) = tup2Mirror.fromProduct((1, 2, 3)) // fails silently and creates (1, 2)
  println(tup2a)
  val tup2b: (Int, Int) = tup2Mirror.fromProduct(Tuple(1)) // crashes with index out of bounds
  println(tup2b)
```

## Output

```scala
Exception in thread "main" java.lang.IndexOutOfBoundsException: 1 is out of bounds (min 0, max 0)
        at scala.Product1.productElement(Product1.scala:42)
        at scala.Product1.productElement$(Product1.scala:40)
        at scala.Tuple1.productElement(Tuple1.scala:23)
        at Test$package$$anon$1.fromProduct(Test.scala:4)
        at Test$package$$anon$1.fromProduct(Test.scala:4)
        at Test$package$.Test(Test.scala:6)
        at Test.main(Test.scala:3)
```

## Expectation

`fromProduct` should assert that the arity of the given tuple is correct. It should fail with a meaningful error message.

**Comment by bishabosha** [comment]
we can patch this for newly compiled code but its still not going to work for libraries compiled by 3.1.x - but fromProduct is supposed to be unsafe anyway - what if the arity is correct but the element types are wrong?

**Comment by nicolasstucki** [comment]
This also made me notice that the tuple mirrors are extremely inefficient as each inferred instance creates a new class with a duplication of the same code. This would be solved by the `runtime.TupleMirror` with or without an arity.

**Comment by nicolasstucki** [comment]
Furthermore, the `runtime.TupleMirror` would also work for large tuples (see #15398).

**Comment by bishabosha** [comment]
this sounds good to me - I didn't quite get before that this change was just for tuples. - and the `runtime.TupleMirror` should not leak into public apis. would that need to be experimental still?

**Comment by nicolasstucki** [comment]
We could add the `runtime.TupleMirror` as experimental in a patch release but we will not be able to use it until the next minor release. Maybe it is cleaner to add the class and change the mirror inference at the same time on the minor release.
