### ISSUE TITLE
Context bounds doesn't work sometime

### ISSUE THREAD

**Issue by iron9light** [lampepfl/dotty#15410]
## Compiler version

3.1.2

## Minimized code

```Scala
trait Sorting:
  def sort1[A: ClassTag, B >: A: Ordering, CC](
      xs: CC
  )(using view: CC => IterableOnce[A], factory: Factory[A, CC]): CC

  def sort2[A, B >: A: Ordering, CC](
      xs: CC
  )(using view: CC => IterableOnce[A], factory: Factory[A, CC])(using ClassTag[A]): CC
```

## Output

```scala
val sorting: Sorting = ...
sorting.sort1(Seq(3, 2, 1))
```

Will got this compile error:

```console
[error] 48 |    val actual = sorting.sort(input)
[error]    |                                    ^
[error]    |                         No ClassTag available for A
[error]    |
[error]    |                         where:    A is a type variable with constraint
```

But `sort2` works with no problem:

```scala
val sorting: Sorting = ...
sorting.sort2(Seq(3, 2, 1))
```

## Expectation

Based on this [article](<https://docs.scala-lang.org/scala3/book/ca-context-bounds.html>), I think `sort1` is just the `sort2` with syntactic sugar.

Is it a bug or just a misused case?

**Comment by KacperFKorban** [comment]
Minimized:
```scala
import scala.reflect.ClassTag

def sort1[A: ClassTag, CC](
    xs: CC
)(using CC => IterableOnce[A]): CC = ???

def sort2[A, CC](
    xs: CC
)(using CC => IterableOnce[A])(using ClassTag[A]): CC = ???

sort1(Seq(3, 2, 1)) // error `No ClassTag available for A`
sort2(Seq(3, 2, 1))
```

It seems that the difference is that `sort1` is desugared to
```scala
def sort1[A, CC](
    xs: CC
)(using ClassTag[A], CC => IterableOnce[A]): CC = ???
```

**Comment by iron9light** [comment]
What's different between

```scala
def sort2[A, CC](
    xs: CC
)(using CC => IterableOnce[A])(using ClassTag[A]): CC = ???
```

and

```scala
def sort1[A, CC](
    xs: CC
)(using ClassTag[A], CC => IterableOnce[A]): CC = ???
```

Looks like the same thing.

**Comment by prolativ** [comment]
It looks like in the first snippet the actual value of `A` is inferred first and then the compiler tries to find a given instance of `ClassTag` for it.
In the second case the order of the operations the compiler needs to perform is reversed and the compiler cannot find the given instance for `A` because it's still an unbound type variable at the point of the search.

**Comment by anatoliykmetyuk** [comment]
Does that mean we should change the desugaring of context bounds so that the corresponding implicit goes last? The reasoning for this would be that we want to collect as much info about the type variable as possible before performing context-bound resolution on it.

**Comment by KacperFKorban** [comment]
> Does that mean we should change the desugaring of context bounds so that the corresponding implicit goes last?

I'm not sure that we do. IMHO it's just a design decision: we have to choose one or the other. And either way, there will be a case where the implicit search will be performed before the more specific type inference.

If we change it then someone can write the following code:
```scala
def sort1[A, CC: [X] =>> X => IterableOnce[A]](
    xs: CC
)(using ClassTag[A]): CC = ???
```
which works now, but won't work if we change the order.

I think that the current way it is desugared is better. The bounds are typed from left to right, which is consistent with the code.

**Comment by odersky** [comment]
And we can't change it, since we need to stay compatible with the way Scala-2 does it.

**Comment by odersky** [comment]
Note that the current reference doc already describes the actual expansion. It's just that docs-scala-lang is not updated yet. 

 https://dotty.epfl.ch/docs/reference/contextual/context-bounds.html

**Comment by lrytz** [comment]
Another example, I think:

```scala
object O {
  trait M[K, +V] {
    def getOrElse[V1 >: V](k: K, d: V1): V1 = ???
  }
  class Arr[M]
  object Arr {
    // def apply[N](): Arr[N] = new Arr[N]
    def apply[N: reflect.ClassTag](): Arr[N] = new Arr[N]
  }
  // OK in Scala 2
  // Error in Scala 3: No ClassTag available for N
  // OK in Scala 3 if there is no `ClassTag` constraint. Then the compiler infers `Arr.apply[String]()`
  def f(m: M[Int, Arr[String]]) = m.getOrElse(1, Arr())
}
```
