### ISSUE TITLE
Extension method on a function lacks parity with ordinary method

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#15427]
## Compiler version

3.1.1

## Minimized code

```Scala
scala> def log(prefix: String, x: Int) = println(s"$prefix : $x")
def log(prefix: String, x: Int): Unit

scala> extension (logfun: String => Unit) def info = logfun("info")
def info(logfun: String => Unit): Unit

scala> log(_, 10).info
-- [E081] Type Error: ----------------------------------------------------------
1 |log(_, 10).info
  |    ^
  |    Missing parameter type
  |
  |    I could not infer the type of the parameter _$1 of expanded function:
  |    _$1 => log(_$1, 10).info.
1 error found

scala> log(_: String, 10).info
-- [E008] Not Found Error: -----------------------------------------------------
1 |log(_: String, 10).info
  |^^^^^^^^^^^^^^^^^^^^^^^
  |value info is not a member of Unit.
  |An extension method was tried, but could not be fully constructed:
  |
  |    info(log(_$1:String, 10))    failed with
  |
  |        Found:    Unit
  |        Required: String => Unit
1 error found

scala> info(log(_, 10))
info : 10
```
## Expectation
if `info(log(_, 10))` works, `log(_, 10).info` should also work.

**Comment by odersky** [comment]
That would be nice, but it does not work that way. To find out what `info` would be applicable as an extension method, we need to type `log(_, 10)` first.

**Comment by dwijnand** [comment]
Why is this failing, though?

> ```scala
> scala> log(_: String, 10).info
> -- [E008] Not Found Error: -----------------------------------------------------
> 1 |log(_: String, 10).info
>   |^^^^^^^^^^^^^^^^^^^^^^^
>   |value info is not a member of Unit.
>   |An extension method was tried, but could not be fully constructed:
>   |
>   |    info(log(_$1:String, 10))    failed with
>   |
>   |        Found:    Unit
>   |        Required: String => Unit
> ```

I don't understand what was typed as Unit here.  `info` takes `String => Unit`, so was `log(_$1:String, 10)` typed as `Unit` instead of `String => Unit`?

**Comment by griggt** [comment]
```scala
scala> log(_, 10).info
-- [E081] Type Error: ----------------------------------------------------------
1 |log(_, 10).info
  |    ^
  |    Missing parameter type
  |
  |    I could not infer the type of the parameter _$1 of expanded function:
  |    _$1 => log(_$1, 10).info.
1 error found

scala> (log(_, 10)).info
info : 10
```

**Comment by dwijnand** [comment]
Oh, _there's_ the forest!...
