### ISSUE TITLE
Local imports occasionally don't work

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#15468]
## Compiler version

3.1.2

## Minimized code

```Scala
object Test {
  val s = ""
  import s.{length => x, size => y}
  locally(x) // ok
  locally(y) // Not found: y
}
```

## Output

```
[error] 5 |  locally(y) // Not found: y
[error]   |          ^
[error]   |          Not found: y
[error] one error found
```

## Expectation

It should compile.

**Comment by som-snytt** [comment]
> You don't get implicit augmentation in import clauses.

But maybe you should! So many values get stabilized, why not import qualifier? Import clauses are selections, too.
