### ISSUE TITLE
`-coverage-out` fails to compile formatted string interpolation

### ISSUE THREAD

**Issue by arixmkii** [lampepfl/dotty#15487]
## Compiler version

3.2.0-RC1 with "-coverage-out:."

## Minimized code

```Scala
@main def main: Unit =
  println(hexMe(127))

def hexMe(i: Int): String =
  f"0x$i%016x"

```

## Output

```
[error] 5 |  f"0x$i%016x"
[error]   |  ^^^^^^^^^^^^
[error]   |  Expected statically known StringContext
[error] one error found
```

## Expectation
Code compiles

**Comment by nicolasstucki** [comment]
When instrumenting, we should not lift `StringContext.f` as this code is an intrinsic macro that will be replaced in `StringInterpolatorOpt`.
