### ISSUE TITLE
Import selector check is too strict on aliasing

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#15480]
## Compiler version

3.1.2

## Minimized code

```Scala
object X {
  val x = 42
  val y = 17
}
object Y {
  import X.{x => a, x => b}
  //import X.{x => a}, X.{x => b}
  //import X.{x => b}, X.{x => a, y => a}
  def main(args: Array[String]) = println {
    (a, b)
  }
}
```

## Output

```scala
8 |  import X.{x => a, x => b}
  |                    ^
  |                    x is renamed twice on the same import line.
1 error found
```

## Expectation

My quirky alias isn't hurting anybody. The same alias works as a separate clause; arguably, the greater the distance between the aliases, the greater the chance that it will be overlooked or edited by mistake.

Incongruously, `X.{x => a, y => a}` errors in Scala 2 (`error: a appears twice as a target of a renaming`) but not Scala 3, where it results in an ambiguous reference if `a` is "used". The counter-argument might be that it is an idiom that ensures `a` is not referenced without further shadowing.

Nothing in the spec prohibits these "off-label" usages (as they call certain prescriptions made by adventurous doctors).

Possibly, all second-guessing of my `x as a` should be relegated to lint warnings. (That is, it should be a `-W` flag, and `-Xlint` should enable it.)

**Comment by odersky** [comment]
I think we want to keep the checks we have and not go further. I agree it's a murky area, but I don't feel like entering this swamp.
