### ISSUE TITLE
Dotc script creaing wrong state

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#1549]
I can't reproduce it, but I've already seen multiple cases when `dotc` script creates wrong `.packages` file:

```
/home/test/dotty/bin/../interfaces/target/
/home/test/dotty/bin/../target/scala-2.11/
/home/test/dotty/bin/../target/scala-2.11/
```

ping @felixmulder

**Comment by smarter** [comment]
dotc script got rewritten.
