### ISSUE TITLE
Overriding a non-abstract var is compiled in Scala 3 / fails in Scala 2

### ISSUE THREAD

**Issue by makingthematrix** [lampepfl/dotty#15491]
## Compiler version

3.1.1

## Minimized code
```
  trait Animal {
    var cat: String = ""
  }

  class Cat extends Animal {
    override val cat: String = "cat"
  }
```
## Output

Compilation works.

## Expectation

In Scala 2.13.8 compilation of this code fails with:
```
mutable variable cannot be overridden:
[error] def cat: String (defined in trait Animal)
[error]     override val cat: String = "cat"
[error]   
```

[Here’s a Scastie for it.](https://scastie.scala-lang.org/makingthematrix/tRd2gIbFQLaHZ9IWvUo11A/1)

I have already seen [this ticket](https://github.com/lampepfl/dotty/issues/13019) and I can confirm it is fixed now, but the code above is a bit different - the var in the superclass is **not** abstract. You can modify the Scastie linked above to see how that changes how Scala 3 reacts. As far as I can tell, the only case where Scala 3 shows an error is when the field in the subclass is also a `var`: `override var cat = "cat".` 
```
error overriding variable cat in trait Animal of type String; [error] 
| variable cat of type String cannot override a mutable variable
```

I asked about it on the contributors forum and was advised to open a ticket: https://contributors.scala-lang.org/t/a-possible-issue-with-overriding-vars-in-scala-3/5768
It feels to me as if it was an overlooked detail and Scala 3 should behave exactly as Scala 2.

**Comment by som-snytt** [comment]
Current HEAD says
```
-- [E164] Declaration Error: i15491.scala:7:15 -------------------------------------------------------------------------
7 |  override val cat: String = "cat"
  |               ^
  |               error overriding variable cat in trait Animal of type String;
  |                 value cat of type String cannot override a mutable variable
1 error found
```

**Comment by Kordyjan** [comment]
It is correctly giving a compilation error on both 3.1.3 and 3.2.0-RC1.

**Comment by Kordyjan** [comment]
We already have a test for this exact case.
https://github.com/dotty-staging/dotty/blob/main/tests/neg/i14722.scala#L3
