### ISSUE TITLE
Implement linter options

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#15503]
Scala 3 is currently missing several of Scala 2's linter options, including:

 - unused variables
 - unused imports

It would be great to add these.

We could also look out for other valuable options to add.

**Comment by griggt** [comment]
I can probably make some time to help with that one if needed.

**Comment by odersky** [comment]
Project reserved for Paul Cole.

**Comment by odersky** [comment]
See #15885 for another possible linter task.

**Comment by ckipp01** [comment]
As of https://github.com/lampepfl/dotty/pull/16157 this is now implemented, so I'll go ahead and close!
