### ISSUE TITLE
String interpolation followed by a dot is missing string literals

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#15514]
## Compiler version

`3.2.0-RC1`

## Minimized code

```Scala
object Main {
 s"Hello $Main.toStr!"
}
```

## Output

This is the tree representing the string interpolation:
```scala
 Select(
    qualifier = Apply(
      fun = Select(
        qualifier = Apply(
          fun = Select(
            qualifier = Select(
              qualifier = Select(qualifier = Ident(name = _root_), name = scala),
              name = StringContext
            ),
            name = apply
          ),
          args = List(
            Typed(
              expr = SeqLiteral(
                elems = List(Literal(const = ( = "Hello "))),
                elemtpt = ...
              ),
              tpt = ...
            )
          )
        ),
        name = s
      ),
      args = List(
        ...
      )
    ),
    name = <error>
  ),
```

Notice it only contains `"Hello "` literal.

## Expectation

```scala
 Select(
    qualifier = Apply(
      fun = Select(
        qualifier = Apply(
          fun = Select(
            qualifier = Select(
              qualifier = Select(qualifier = Ident(name = _root_), name = scala),
              name = StringContext
            ),
            name = apply
          ),
          args = List(
            Typed(
              expr = SeqLiteral(
                 elems = List(Literal(const = ( = "Hello ")), Literal(const = ( = ".toStr!")))
                elemtpt = ...
              ),
              tpt = ...
            )
          )
        ),
        name = s
      ),
      args = List(
        ...
      )
    ),
    name = <error>
  ),
```

The main part is ` elems = List(Literal(const = ( = "Hello ")), Literal(const = ( = ".toStr!")))`

**Comment by som-snytt** [comment]
Remarkably,
```
scala> object Main { def m = s"Hello $Main.toStr!" }
// defined object Main

scala> Main.m
val res0: String = Hello rs$line$2$Main$@44ddb518.toStr!
```

**Comment by odersky** [comment]
I also don't see yet what is wrong here. There is no error reported and it generates the correct code.

**Comment by som-snytt** [comment]
I took a look and will follow up. The dot is tokenized FSR after self type looks ahead, maybe something to do with string interpolation as two tokens, the part and the embedded ident.

**Comment by som-snytt** [comment]
Probably this edge case results from a tweak to lookahead https://github.com/lampepfl/dotty/pull/14562

My proposed fix is defensive. I'll consider whether it's possible to tweak scanning the interpolation instead.

**Comment by odersky** [comment]
I still don't understand what is wrong.

**Comment by som-snytt** [comment]
Calling lookahead at INTERPOLATIONID populates current token at STRINGPART and next at IDENT, but reset makes current INTERPOLATIONID and next at STRINGPART, so IDENT is dropped.

It works either to avoid lookahead in that case, or resort to LookaheadScanner.

I'll look at whether producing STRINGPART can be less eager in producing the next IDENT. One idea is that if it's done in postProcess, then lookahead won't do it, much like fusion of case class.

**Comment by som-snytt** [comment]
It looks like I edited my previous comment. I'll show the spurious syntax error in a minute after a recompile. Maybe a couple of minutes.
