### ISSUE TITLE
Load file in repl -  eof expected but '}' found

### ISSUE THREAD

**Issue by dos65** [lampepfl/dotty#1552]
The example below failed with `<console>:8: error: eof expected but '}' found;}^`
```scala
def foo(): String = { 
  "foo" 
}

class B {

}
```
But when i place braces in one line - it's work
```scala
def foo(): String = { "foo" }

class B {}
```

**Comment by felixmulder** [comment]
Hi @dos65 - thanks for reporting this. It is indeed a bug in the REPL.

What happens is the following:
 
1. REPL sees that you're trying to load a file
2. Loads the file
3. Gives the contents of the file to `CompilingInterpreter` line by line
4. Tries to compile each line separately thus failing compilation.

A simple fix for this would be to join the lines or tell the `CompilingInterpreter` that it's receiving multiple lines and hold off on the compilation until these have been delivered.
