### ISSUE TITLE
Can't recognize that parameter is Singleton and has ValueOf

### ISSUE THREAD

**Issue by RazvanSmeu** [lampepfl/dotty#15537]
## Compiler version

3.1.2

## Minimized code
```Scala
def someSingletonLogic[L <: List[Int] & Singleton : ValueOf](listParam: L) = 0

@main def test() =
  val listVal = List(1, 2, 3)

  someSingletonLogic(listVal) // Works fine
  someSingletonLogic(List(1, 2, 3)) // Compiler error
```

## Output
It fails with any compilation of `ValueOf` and `Singleton`
```scala
Found:    List[Int]
Required: List[Int] & Singleton
No singleton value available for (List[Int] & Singleton).
```

## Expectation
Expected it to compile, and the body of the `someSingletonLogic` function to be able to use the `valueOf[L]` because the passed param is a singleton and it does have a value

**Comment by soronpo** [comment]
`List(...)` is not a singleton. It's an apply method with multiple arguments. What is it that you are trying to achieve?

**Comment by prolativ** [comment]
As mentioned above, this works as expected. To learn why, try to add the type parameter explicitly - in the first case it's
```scala
someSingletonLogic[listVal.type](listVal)
```
but in the second case that would be just
```scala
someSingletonLogic[List[Int]](List(1, 2, 3))
```
Something like
```scala
someSingletonLogic[List(1, 2, 3).type](List(1, 2, 3))
```
is not possible

**Comment by RazvanSmeu** [comment]
But the value returned by `List(...)` or any value for that matter is a singleton. Can't it be that when a singleton is expected and a val reference is not passed, the val def is generated above at compile time? It would still be correct.

This is useful for typeclass instances using macros, having the singleton passable and generated as a type would allow for example refinements that issue compile time errors when `List(1, 2, 3)` is not `SizeOf[4]` for example

**Comment by soronpo** [comment]
You can use a tuple instead of a list

**Comment by prolativ** [comment]
> But the value returned by List(...) or any value for that matter is a singleton
It is not. It's just a `List[A]`, nothing more. Look at the signature of `List.apply`. `listVal` has a more specific singleton type because it's a `val` and this makes it a stable identifier. Note that even your first example wouldn't compile if `listVal` was a `var` or `def` instead.
