### ISSUE TITLE
Make bridge test a part of CI

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1554]
Currently, the tests that are a part of the bridge do not get run by CI. Ergo, any error in them will go unnoticed and we risk breaking master.

cc: @smarter

**Comment by smarter** [comment]
My plan was to wait until we switch to sbt/zinc 1.0 where the scripted tests should be much faster to run (because they don' t require starting a full instance of sbt for every single test), I think they currently they take about 25 minutes so we could enable them anyway

**Comment by felixmulder** [comment]
I think at least we should be compiling the bridge on CI :)

**Comment by allanrenucci** [comment]
sbt scripted tests currently run on every merged PR and nightly build
