### ISSUE TITLE
Arrays of value classes

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1558]
The initial work on Arrays of value classes was completed by @VladimirNik. The current state of Arrays of value classes is described within this PR: https://github.com/lampepfl/dotty/pull/1228

If anyone wants to pick this up - you're more than welcome to pick up from this PR.

**Comment by DarkDimius** [comment]
In case @VladimirNik is not reachable, feel free to also ask me, as I've proposed the original idea.

**Comment by smarter** [comment]
Closing with stat:revisit (see https://github.com/lampepfl/dotty/issues/3706 to know what this means) since this is unlikely to be worked on in the near future.
