### ISSUE TITLE
Test framework should emit warnings about tests that aren't checked

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#15594]
## Compiler version

HEAD, of course.

## Minimized code

```Scala
➜  dotty git:(issue/15381-dollar) ✗ find tests/pos -name "*.check"
tests/pos/t11593.check
tests/pos/i15381.check
tests/pos/opaque-inline2.check
```

## Output

```scala
// the same
```

## Expectation

I thought that since there were existing check files under pos, vulpix must check them.

Scala 2 `partest` warns about extraneous check files, after years of development.

**Comment by dwijnand** [comment]
I'd sweat the test files that exist under `tests/` that vulpix doesn't check...  E.g. `tests/run-custom-args/typeclass-derivation2.scala`.
