### ISSUE TITLE
Reference documentation is not up to date

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#15598]
Currently, the [Scala 3 reference documentation](https://docs.scala-lang.org/scala3/reference/) shows version 3.1.2 instead of the latest 3.1.3.

I think there is a missing step in the release process. The documentation should have been updated with the content of the `main` branch.

**Comment by Kordyjan** [comment]
The documentation is updating as it should. Only the version string is incorrect. I fixed it for now. After my vacation, I will think about a more robust solution. Maybe we can use `previousDottyVersion` here.

**Comment by Kordyjan** [comment]
It is now part of the release steps. I'll probably automate it further in the future.
