### ISSUE TITLE
Match types unable to match on `Nothing`

### ISSUE THREAD

**Issue by Swoorup** [lampepfl/dotty#15607]
Apologies if this is expected behavior. I am trying to constrain the return type of Behavior Response to be `Unit` instead of `Nothing` for `CounterMsg.Inc extends CounterMsg[Nothing]` but it appears I can't type match on `Nothing`? 

The code works if I instead use the line
`// type ResponseOf[O] = O | Unit` and comment the one with the match type. But it allows `Unit` type despite `O` isn't necessarily `Nothing`

## Compiler version

3.1.3

## Minimized code

```Scala
type ResponseOf[O] = O match
  case Nothing => Unit
  case _       => O

// type ResponseOf[O] = O | Unit

type Behavior[S, -I[_]] = [O] => ((S, I[O]) => (S, ResponseOf[O]))

enum CounterMsg[+Response]:
  case Inc
  case Get extends CounterMsg[Int]

val counterFsm: Behavior[Int, CounterMsg] =
  [O] =>
    (state: Int, msg: CounterMsg[O]) =>
      (msg match
        case CounterMsg.Inc => state + 1 -> ()
        case CounterMsg.Get => state -> state
      ): (Int, ResponseOf[O])
```
Scastie: https://scastie.scala-lang.org/KG1Q2sbVSUawd18xXk5kXQ

## Output

```scala
Found:    (state : Int)
Required: Playground.ResponseOf[O]

where:    O is a type in method apply with bounds >: Int
```

## Expectation

Compiles successfully

**Comment by Swoorup** [comment]
I tried inverted the match cases such as 
```scala
type ResponseOf[O] = O match
  case Any => O
  case _   => Unit
```

The `CounterMsg.Get` scrutinee seems to compile, but the other cases still complains of the same issue.
```shell
Found:    Unit
Required: ResponseOf[O]
```

**Comment by prolativ** [comment]
Trying to play a bit with your code I accidentally found out that your original snippet will compile if you define `CounterMsg` as invariant and add an explicit extends clause for `Inc`:
```scala
type ResponseOf[O] = O match
  case Nothing => Unit
  case _       => O

type Behavior[S, -I[_]] = [O] => ((S, I[O]) => (S, ResponseOf[O]))

enum CounterMsg[Response]:
  case Inc extends CounterMsg[Nothing]
  case Get extends CounterMsg[Int]

val counterFsm: Behavior[Int, CounterMsg] =
  [O] =>
    (state: Int, msg: CounterMsg[O]) =>
      (msg match
        case CounterMsg.Inc => state + 1 -> ()
        case CounterMsg.Get => state -> state
      ): (Int, ResponseOf[O])
```
Would that be enough for your use case? I'm not really sure at the moment what the behaviour should be for a covariant `CounterMsg`.

**Comment by Swoorup** [comment]
Interesting was just toying around to see what's possible, should I leave this open in that case?

**Comment by prolativ** [comment]
I think the compiler might be right to reject this code (although I'm not sure if the error messages could be more informative in such situations in general).
If you define `CounterMsg` as covariant then `Inc` would be a subtype of both `CounterMsg[Nothing]` and `CounterMsg[Int]` so code like
```scala
counterFsm(1, CounterMsg.Inc: CounterMsg[Int])
``` should compile. But then in
```scala
[O] =>
    (state: Int, msg: CounterMsg[O]) =>
      (msg match
        case CounterMsg.Inc => state + 1 -> ()
        case CounterMsg.Get => state -> state
      ): (Int, ResponseOf[O])
```
`O` would get substituted with `Int` and while `case CounterMsg.Inc` pattern gets matched, the type of `state + 1 -> ()` should be `(Int, ResponseOf[O])`, which should further expand to `(Int, Int)` but it's actually `(Int, Unit)`
