### ISSUE TITLE
5 did not conform to type: scala.Int - updating a macro value in the macro context in staging

### ISSUE THREAD

**Issue by Adam-Vandervorst** [lampepfl/dotty#15641]
## Compiler version

3.1.3

## Minimized code

```Scala
// macros.scala
import scala.quoted.{Expr, Type, Quotes, staging}

given staging.Compiler = staging.Compiler.make(getClass.getClassLoader)

def fImpl(x: Expr[Int])(using q: Quotes): Expr[Int] =
  import q.reflect.asTerm
  val y = '{ $x + 1 }.asTerm
  val qe = (p: Quotes) ?=> {
    val eq = y.asExprOf[Int]
    '{ val a = $eq; a*a }
  }
  Expr(staging.run(qe))

// main.scala
inline def f(inline x: Int) = ${ fImpl('x) }

@main def m = println(f(2 * 2))
```

## Output

```scala
@main def m = println(f(2 * 2))
                      ^^^^^^^^
Exception occurred while executing macro expansion.
java.lang.Exception: Expr cast exception: 4.+(1)
of type: 5
did not conform to type: scala.Int
```

**Comment by nicolasstucki** [comment]
An `Expr` generated outside should never be passed into `run`. We have runtime checks on `Expr` to catch these situations (`ExprImpl.scope`). It seems that this code hacked its way around the reflection API to make an ill-formed expression.

**Comment by nicolasstucki** [comment]
We could try to catch this mistake when calling the `asExprOf` or splicing the `eq`.

**Comment by Adam-Vandervorst** [comment]
> seems that this code hacked its way around the reflection API

Is funny because it's literally the first thing I tried to do outside of the documentation.
That is, using the staging compiler in macros to do constant folding.

**Comment by nicolasstucki** [comment]
Unfortunately, that is not safe because you might always have variables defined outside the quote. Furthermore, `staging` uses a different instance of the compiler, which is why you get error messages that do not make sense.
