### ISSUE TITLE
java.lang.ClassCastException on a trivial match

### ISSUE THREAD

**Issue by strelec** [lampepfl/dotty#15662]
## Compiler version

3.2.0-RC1
On 3.1.3 it is a compiler error instead (it should not be)

## Minimized code

```Scala
case class Composite[T](v: T)

def m(composite: Composite[_]): Unit =
  composite match {
    case Composite[Int](v) => println(v)
    case _ => println("OTHER")
  }

m(Composite("This is String"))
```

## Output

`java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer`

## Expectation

Print "OTHER"

**Comment by som-snytt** [comment]
https://github.com/lampepfl/dotty/pull/15356 explains the revised translation. 

When written as an extractor, it correctly warns, so "constructor" pattern style should also warn:
```
-- Unchecked Warning: -------------------------------------------------------------------------------------------------------
3 |    case X[Int](v) => println(v)
  |         ^
  |         the type test for C[Int] cannot be checked at runtime
```
