### ISSUE TITLE
Implicit value can no longer be accessed via implicit conversion

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#15670]
Community build regression for https://github.com/giiita/refuel (maintainer @giiita)
Based on [Open Community Build #1884](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/1884/)
Part of https://github.com/lampepfl/dotty/issues/15647 regressions tracker

## Compiler version

Works in 3.1.1
Fails in 3.1.2 and 3.1.3
Fails in 3.2.0-RC* and 3.2.1-RC1-bin-20220711-6efd92d-NIGHTLY

## Minimized code

```Scala
trait JsonRowEntry {
  def readAs[E](implicit c: Read[E]): Option[E] = ???
}
trait Read[T]
trait Codec[T] extends Read[T]
trait CodecTypeProjection[C[_]]
object JsonTransform  {
  given SetCodec[T, C[_]: CodecTypeProjection]: scala.Conversion[C[T], C[Set[T]]] = ???
  given SetCodecExp[T, C[_]: CodecTypeProjection](using codec: C[T]): C[Set[T]] = codec
  given Codec[String] = ???
  given CodecTypeProjection[Read] = ???
}

@main def Test() = {
  import JsonTransform.given
  val tree = new JsonRowEntry {}
  tree.readAs[Set[String]]
}
```

## Output

```scala
rror] ./test.scala:17:27: No given instance of type Read[Set[String]] was found for parameter c of method readAs in trait JsonRowEntry.
[error] I found:
[error] 
[error]     JsonTransform.SetCodecExp[String, C](
[error]       JsonTransform.given_CodecTypeProjection_Read
[error]     , /* missing */summon[C[String]])
[error] 
[error] But no implicit values were found that match type C[String].
[error]   tree.readAs[Set[String]]
[error]              
```

## Expectation
Should be able to find correct implicit value by usage of implicit conversion

**Comment by griggt** [comment]
First bad commit is db5956b36a7e62b77f4b3a9335ab1587e0e47e2c from #13886

**Comment by odersky** [comment]
That one is as expected. We now refuse to search implicits for type variables that are unknown, and we know that this will refuse to compile some code that compiled before. The reason for the restriction is that there is a latent danger of unboundedly long implicit searches, in particular as programs grow. That's more important than a small expressiveness win.

**Comment by smarter** [comment]
Related: https://github.com/lampepfl/dotty/issues/15160

**Comment by KacperFKorban** [comment]
I found a similar issue in `earogov/ordset`

Compiled for `3.0.0`, ..., `3.1.1`
Gives an error for `3.1.2`, .., `3.2.0-RC1`, `3.2.1-RC1-bin-20220715-d247c37-NIGHTLY`

```scala
trait Box[E]

trait Domain

def fun[E, D[_] <: Domain](box: Box[E])(implicit domain: D[E]): Unit = {

  val newBox: Box[E] =  ???

  fun(newBox)
}
```

Is this behavior also expected? @odersky

**Comment by odersky** [comment]
> Is this behavior also expected? @odersky

Probably. It looks similar. We know for sure if it is the same commit that broke it.

**Comment by KacperFKorban** [comment]
The commit that broke it is the same (db5956b36a7e62b77f4b3a9335ab1587e0e47e2c), so it probably is also expected.
