### ISSUE TITLE
Imported extension method is ignored

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#15691]
The overloading of extension methods ignored the imported methods because of the locally defined one, even though the extension methods do not collide before erasure. Note that if we were to use implicit classes instead of extension methods there is no error.

## Compiler version

v3.2.0-RC2

## Minimized code
https://scastie.scala-lang.org/ifsZBnX7SeeGhTs0buF9XQ
```Scala
import scala.annotation.targetName
trait Foo[+T]

object Ops:
  extension (foo : Foo[Int])
    @targetName("bazInt")
    def baz : Unit = {}

import Ops.*

extension (foo : Foo[Double])
  @targetName("bazDouble")
  def baz : Unit = {}

val f = new Foo[Int] {}
f.baz
```

## Output

```scala
value baz is not a member of Playground.Foo[Int].
An extension method was tried, but could not be fully constructed:

    Playground.baz(f)    failed with

        Found:    (Playground.f : Playground.Foo[Int])
        Required: Playground.Foo[Double]
```

## Expectation
No error.

**Comment by som-snytt** [comment]
That is ordinary name binding precedence, where the definition shadows the import.

**Comment by soronpo** [comment]
> That is ordinary name binding precedence, where the definition shadows the import.

OK, I see what you mean:
```scala
import scala.annotation.targetName
object Test:
  trait Foo[+T]

  object Ops:
    @targetName("bazInt")
    def baz(foo : Foo[Int]) : Unit = {}

  import Ops.*
  @targetName("bazDouble")
  def baz(foo : Foo[Double]) : Unit = {}

  val f = new Foo[Int] {}
  baz(f) //error
```
I really wanted for extension methods to replace implicit classes and this is the biggest obstacle for me.
A very bad workaround is to use `export` instead of import.

**Comment by som-snytt** [comment]
The other idiom is to use traits and make the extension available as a `given`.
```
trait Ops1:
  extension (foo: Foo[Int])
    @targetName("bazInt")
    def baz : Unit = {}

trait Ops2:
  extension (foo : Foo[Double])
    @targetName("bazDouble")
    def baz : Unit = {}

class Ops extends Ops1, Ops2

given Ops = Ops()
```
