### ISSUE TITLE
Compiler Infer The Wrong Type

### ISSUE THREAD

**Issue by Serendipithub** [lampepfl/dotty#15711]
## Compiler version
Scala compiler version 3.1.3 -- Copyright 2002-2022, LAMP/EPFL

## Minimized code

```Scala
extension [Input, Return](value: Input => Return) {
  @targetName("apply")
  def <=(input: Input) = value(input)

  @targetName("compose")
  def $[AnotherInput](otherFun: (AnotherInput) => Input) =
    (x: AnotherInput) => value(otherFun(x))
  end $

  @targetName("compose")
  def $[AnotherInput1, AnotherInput2](
      otherFun: (AnotherInput1, AnotherInput2) => Input
  ) =
    (x: AnotherInput1, y: AnotherInput2) => value(otherFun(x, y))
  end $
}
extension [Input1, Input2, Return](value: (Input1, Input2) => Return) {
  @targetName("apply")
  def <=(input: (Input1, Input2)) = value(input._1, input._2)
}

def curried[Input1, Input2, Output](a: (Input1, Input2) => Output) =
  (x: Input1) => (y: Input2) => a(x, y)

def add(x: Int)(y: Int) = x + y
val f = Function.uncurried(add)

//this line won't be compiled
//but it should be
val b = curried <= f //Found: (f : (Int, Int) => Int) Required: (Any, Any) => Any

```

## Output

```scala
// compiling fail
```

## Expectation
Found: (f : (Int, Int) => Int) Required: (Any, Any) => Any

**Comment by szymon-rd** [comment]
Thank you for reporting!

The last line uses the `<=` method from the first extension body, and that method is effectively a syntactic sugar for:
```scala
def <=[Input, Return](value: Input => Return)(input: Input): Return = value(input)
```

So we could think about the whole minimised code with extension expanded like this:
```scala
def <=[Input, Return](value: Input => Return)(input: Input): Return = value(input)

def curried[Input1, Input2, Output](a: (Input1, Input2) => Output): Input1 => Input2 => Output =
  (x: Input1) => (y: Input2) => a(x, y)

def add(x: Int)(y: Int) = x + y
val f: (Int, Int) => Int = Function.uncurried(add)

val b = <=(curried)(f)//Found: (f : (Int, Int) => Int) Required: (Any, Any) => Any
```
In Scala, generic types in curried function are inferred by reading the parameters from left to right. In this case, the first parameter it encounters is the `curried` function, that is generic with type params `Input1, Input2, Output`. It takes the most general types matching the definition - that is `Any, Any, Any` and uses them to infer the generic parameters of `<=` function. And we end up with `Any` being expected as the types for the parameter in second curried group. 

I hope my comment helped you, for now I am closing this issue but if you feel that I haven't covered it and there is something missing, please let me know! :)
