### ISSUE TITLE
Path dependent types in doc not rendered properly

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#15716]
## Compiler version

3.2.1-RC1-bin-20220720-6c7acf9-NIGHTLY

## Problem description

Path dependent types in scaladoc are not rendered properly - they're replaced with `<none>`, e.g. for object `scala.deriving.Mirror`:

```scala
  extension [T](p: ProductOf[T])
    def fromTuple(t: p.MirroredElemTypes): T
```
is displayed as
```scala
extension [T](p: [ProductOf][T])
  def fromTuple(t: <none>): T
```

![Screenshot 2022-07-21 at 11 22 59](https://user-images.githubusercontent.com/9847846/180179228-1606a76b-4f06-4363-8aa9-65e075fb0327.png)

**Comment by Dedelweiss** [comment]
This problem seems to be fixed thanks to @Florian3k in PR #17213. (Tested locally)
