### ISSUE TITLE
Coverage generated for inlined Predef function

### ISSUE THREAD

**Issue by Martomate** [lampepfl/dotty#15791]
## Compiler version

3.2.0-RC3

## Minimized code

```Scala
@main def a(b: Int): Unit = {
  assert(b == 1)
}
```

The `assert` function is part of the Scala 3 library at `scala.runtime.stdLibPatches.Predef` and has this definition:

```Scala  
transparent inline def assert(inline assertion: Boolean): Unit =
  if !assertion then scala.runtime.Scala3RunTime.assertFailed()
```

## Output

`scoverage.coverage` contains entries for `library/src/scala/runtime/stdLibPatches/Predef.scala`.

As a result `sbt coverageReport` fails with the following error:
```
No source root found for '/Users/martin/git/myproject/library/src/scala/runtime/stdLibPatches/Predef.scala' (source roots: '/Users/martin/git/myproject/src/main/scala/')
```

## Expectation

No coverage entries should be generated for the Predef file, just like all other files in the Scala library.

This issue seems to be related to #15490.

**Comment by arixmkii** [comment]
Most probably not on sbt plugin side, but in the core module. But previously they stated that will not fix it at least for Macro libraries https://github.com/scoverage/scalac-scoverage-plugin/issues/474

This case is not purely macro, but an inline. Though it is could be questioned if inlined parts should be reported with external source reference if this is an actual code "placed" elsewhere. Similarly with macro code.

An option to hide this behind some configuration key would be appreciated I believe as in some cases people might don't want the coverage info from sources they don't own.
