### ISSUE TITLE
Adapt the sbt bridge for the new error messages

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1579]
The sbt bridge currently does not use the new scheme for error messages.

It simply delegates the error message (not the complete error) to the sbt reporter. To fix this we should be able to simply do the following:
- Adapt `src/dotty/.../ConsoleReporter.scala` to produce a complete string of the whole error message before printing
- Hand the above string to the delegate in `bridge/.../DelegatingReporter.scala`
- Check that the pretty error messages are now available without hickups in an sbt example project

**Comment by slothspot** [comment]
@felixmulder if nobody works on this, I'm going to start.

> Check that the pretty error messages are now available without hickups in an sbt example project
Does it mean that I need to contribute to smarter/dotty-example-project code with errors?

**Comment by felixmulder** [comment]
Hi @slothspot - you're more than welcome to work on this :)

You will probably not need to do modify anything in the example project. But you'll need to tweak the bridge and you'll need to do `publishLocal` to check the results. Let us know on gitter if you need any help!
