### ISSUE TITLE
Please right bias Either

### ISSUE THREAD

**Issue by godenji** [lampepfl/dotty#158]
Not sure what benefit there is in leaving Either unbiased (beyond, of course, not breaking existing Scala code).

Any chance this request can make it in to Dotty? I know a production ready compiler is a long way off, just putting this out there on the nice-to-have list.

Thanks

**Comment by rogue-one** [comment]
Since Dotty supports union types is there any reason to use Either at all?

**Comment by ritschwumm** [comment]
@rogue-one `Either[String,Either[String,Int]]`
