### ISSUE TITLE
object 

### ISSUE THREAD

**Issue by OlegYch** [lampepfl/dotty#15800]
## Compiler version

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

```Scala
println("hello, world")
```

## Output

```scala
// TODO add output here
```

**Comment by SethTisue** [comment]
note that there's an FAQ entry on this subject that is still evolving, e.g. https://github.com/scala/docs.scala-lang/pull/2485
