### ISSUE TITLE
Write a HOWTO on compiling cbt projects with Dotty

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1580]
We need to create some simple documentation on how create a project with dotty using cbt. It should appear on our documentation website: http://lampepfl.github.io/dotty/docs/

* A markdown file should be placed in: https://github.com/lampepfl/dotty/tree/master/docs/docs/usage
* A table of contents entry should be added to: https://github.com/lampepfl/dotty/blob/master/docs/_includes/toc.html#L13

ping: @cvogt

**Comment by cvogt** [comment]
Happy to add that.

**Comment by cvogt** [comment]
usage: https://github.com/lampepfl/dotty/pull/1581

**Comment by cvogt** [comment]
TOC entry: https://github.com/lampepfl/dotty/pull/1582
