### ISSUE TITLE
No "Reference to uninitialized value" warning

### ISSUE THREAD

**Issue by Bersier** [lampepfl/dotty#15883]
## Compiler version

3.1.3

## Minimized code

```Scala
val a = b
val b = 1

@main def main(): Unit =
  println(a)
```

## Output

```scala
0
```

## Expectation
Expected output: `1`. The natural expected behavior is that initialization would follow the dependency graph, and it would be a compiler error if it contains a cycle.

At the very least, the compiler should issue an uninitialized value warning, as in Scala 2, a fortiori when `-Ysafe-init` is enabled.

As it stands, referential transparency and `val` immutability are violated without so much as a warning.

**Comment by SethTisue** [comment]
https://docs.scala-lang.org/scala3/reference/other-new-features/safe-initialization.html exists, but requires a `-Y` flag

there's some older history on this at https://docs.scala-lang.org/tutorials/FAQ/initialization-order.html

**Comment by keynmol** [comment]
`-Ysafe-init` doesn't catch it in the presented by the author, but in a modified scenario it does:

```scala
object test:
  val a = b
  val b = 1

@main def hello =
  println(test.a)
```
```
-- Warning: test.scala:3:6 -----------------------------------------------------
3 |  val b = 1
  |      ^
  |      Access non-initialized value b. Calling trace:
  |      -> val a = b	[ test.scala:2 ]
  |                 ^
1 warning found
```

**Comment by odersky** [comment]
Maybe -Ysafe-init can be changed so that it also works for toplevel objects?

**Comment by liufengyun** [comment]
> Maybe -Ysafe-init can be changed so that it also works for toplevel code?

I'll have a look, it should behave the same as top-level objects.
