### ISSUE TITLE
Result of a method call is not accepted when by-name Unit value is expected once default values are used

### ISSUE THREAD

**Issue by OndrejSpanel** [lampepfl/dotty#15898]
## Compiler version

3.2.0-RC1

## Minimized code

```Scala
object O {
  class AC(code: => Unit) {
    def apply() = code

    def this(code: => Unit, key: Int, modifiers: Int = 0) = {
      this(code)
    }
  }

  class Doc {
    def method: Boolean = true
  }

  val doc = new Doc

  val ac = new AC(doc.method)
}
```

## Output

```text
None of the overloaded alternatives of constructor AC in class AC with types
 (code: => Unit, key: Int, modifiers: Int): Playground.O.AC
 (code: => Unit): Playground.O.AC
match arguments ((Playground.O.doc.method : => Boolean))
```

See also https://scastie.scala-lang.org/1LhQNKxeQi2WPLlt8o2Cng

## Expectation

The code should compile. It compiles when I remove the secondary constructor or when I remove the default value for parameter `modifiers`.

Note: the same code compiles fine with Scala 2.12 and 2.13

**Comment by som-snytt** [comment]
Same result if the ctors are switched (in case it was due to nesting level).

Works with `val ac = new AC({doc.method; ()})`, so it's an adaptation problem, not just an overloading problem.

**Comment by OndrejSpanel** [comment]
Note: replacing a default parameter value with an overload also compiles fine:

```scala
object O {
  class AC(code: => Unit) {
    def apply() = code

    def this(code: => Unit, key: Int) = this(code)
    def this(code: => Unit, key: Int, modifiers: Int) = this(code)
}

  class Doc {
    def method: Boolean = true
  }

  val doc = new Doc

  val ac = new AC(doc.method)
}
```

**Comment by Kordyjan** [comment]
The bug is still present on the current nightly (`3.2.1-RC1-bin-20220823-3ad97df-NIGHTLY`).
