### ISSUE TITLE
New docs UI: double digit line counts increase indentation

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#15902]
e.g. at https://dotty.epfl.ch/docs/reference/enums/enums.html#user-defined-members-of-enums

<img width="839" alt="Screenshot 2022-08-24 at 15 51 33" src="https://user-images.githubusercontent.com/13436592/186435942-9603e0b6-f6c9-4c48-98fc-f0d1a22b5c5b.png">

**Comment by Dedelweiss** [comment]
Hello @bishabosha, On reviewing the documentation, I notice that the issue seems to be corrected. I'll tag @ckipp01  to close it if you don't see a problem.

**Comment by bishabosha** [comment]
yeah this seems fixed to me
