### ISSUE TITLE
Overload resolution vs. a vararg method breaks when a type argument is set explicitly

### ISSUE THREAD

**Issue by neko-kai** [lampepfl/dotty#15913]
## Compiler version

3.1.3 and 3.2.0-RC1

## Minimized code

runnable: https://scastie.scala-lang.org/zgzJSXSgQ4uLcczMlsoFOw

```Scala
class injector[F]

object injectorFactory {
  def apply[F](overrides: String*): injector[F] = new injector[F]

  def apply[F](
    bootstrapActivation: Int = ???,
    overrides: Seq[String] = Seq.empty,
  ): injector[F] = new injector[F]
}

object main extends App {
  println(
    injectorFactory[String](
      bootstrapActivation = 0
    )
  )
}
```

## Output

```scala
None of the overloaded alternatives of method apply in object injectorFactory with types
 [F](bootstrapActivation: Int, overrides: Seq[String]): injector[F]
 [F](overrides: String*): injector[F]
match type arguments [String] and arguments ((0 : Int))
```

## Expectation

Expected to compile successfully, as in Scala 2: https://scastie.scala-lang.org/nvb0KV3cTHeJloTyW1SY8g

Workaround: removing the explicit type argument fixes the error:

```scala
injectorFactory(
  bootstrapActivation = 0
)
```

**Comment by Kordyjan** [comment]
Still reproducible on the current `main`.

**Comment by som-snytt** [comment]
It also works to remove the default args. There are a few tickets about unhappy interaction with defaults and overloads.

https://github.com/lampepfl/dotty/issues/12679

Despair at https://github.com/lampepfl/dotty/issues/12679#issuecomment-933350375
