### ISSUE TITLE
right-associatve extension methods don't work

### ISSUE THREAD

**Issue by armanbilge** [lampepfl/dotty#15954]
## Compiler version

`3.2.1-RC1-bin-20220901-bf03086-NIGHTLY`

## Minimized code

```Scala
//> using scala "3.2.1-RC1-bin-20220901-bf03086-NIGHTLY"

class Foo
class Bar
  // this works
  // def +:(foo: Foo): Bar = ???

object Bar:
  // this doesn't
  extension (bar: Bar)
    def +:(foo: Foo): Bar = ???

@main def main =
  val foo = Foo()
  val bar = Bar()

  foo +: bar
```

## Output

```
Compiling project (Scala 3.2.1-RC1-bin-20220901-bf03086-NIGHTLY, JVM)
[error] ./bug.scala:17:7: value +: is not a member of Bar
[error]   foo +: bar
[error]       ^^^^^^
Error compiling project (Scala 3.2.1-RC1-bin-20220901-bf03086-NIGHTLY, JVM)
Compilation failed
```

## Expectation

It should compile as if the method was defined directly on the class.

**Comment by bishabosha** [comment]
There is no need to swap the arguments in the definition of a right associative extension method

**Comment by armanbilge** [comment]
@bishabosha thanks, is this documented anywhere? I spent quite a bit of time searching for information on this.

**Comment by bishabosha** [comment]
There's an example here https://docs.scala-lang.org/scala3/reference/contextual/extension-methods.html#operators

**Comment by som-snytt** [comment]
I was about to say https://dotty.epfl.ch/docs/reference/contextual/right-associative-extension-methods.html

**Comment by armanbilge** [comment]
Thanks both! I was hunting on the "rules for operators" and related pages.

https://docs.scala-lang.org/scala3/reference/changed-features/operators.html

Sorry, one more dumb question: even if I define the extension method in reverse inside of the companion for my custom object, will it automatically be in scope for the tuple?
