### ISSUE TITLE
A with B causes ClassCastException after asInstanceOf

### ISSUE THREAD

**Issue by OndrejSpanel** [lampepfl/dotty#15952]
## Compiler version

3.2.0-RC1

## Minimized code

```Scala
sealed trait T
case class A(a: Int) extends T
trait B {
  def a: Int
}

val ab: T with B = new A(0) with B

val res: T with B = // if we change the ascription to `A & B` it works
  if(ab.isInstanceOf[A]) {
    ab.asInstanceOf[A].copy().asInstanceOf[A with B]
  } else {
    ???
  }
```

https://scastie.scala-lang.org/0vAFV0B8SDmZrjvbRj3jsA

## Output

```text
java.lang.ClassCastException: class Playground$A cannot be cast to class Playground$B
```

## Expectation

The code should compile and run.

The same code works with Scala 2.13, the value `ab` looks like it should be both `A` and `B`.

Note: code taken from https://github.com/softwaremill/quicklens/pull/99#discussion_r961735710

**Comment by SethTisue** [comment]
also reproduces on 3.2.0

**Comment by odersky** [comment]
I think this is as expected. `T with B` happens to erase to `B` whereas `A with B` erases to `A`. When you copy `ab` you get an `A` not an `A with B`. The `asInstanceOf` only casts to `A`. So in the version shown the result of the cast will be cast to `B` which causes the exception. Here is the generated code, which I believe is correct:
```scala
       val ab: B = 
          {
            final class $anon() extends A(0), B {}
            (new A with B {...}():A).asInstanceOf[B]
          }
        val res: B = 
          if ab.isInstanceOf[A] then 
            {
              (
                {
                  val $1$: A = ab.asInstanceOf[A]
                  $1$.copy($1$.copy$default$1())
                }
              :A).asInstanceOf[B]
            }
           else 
            {
              ???()
            }
        ()
```

**Comment by odersky** [comment]
@smarter Do you agree?

**Comment by dwijnand** [comment]
A few things worth investigating (IMO): what's the scala 2 generated code? Is it wrong?

TIL TypeTestsCasts emits unchecked warnings for type tests, but not for dubious type casts.  Should it?  🤔

**Comment by odersky** [comment]
No it should not. All bets are off when you use asInstanceOf.

**Comment by odersky** [comment]
Note that it's the choice how to erase intersections that cause an error or not. `T & B` might erase to `T` or `B`. In the first case it would work. Furthermore the choices are different between Scala 3 and 3. @smarter can tell more, he went down into this very deep rabbit hole.

**Comment by sjrd** [comment]
I agree with @odersky. The original code is wrong, as it performs a nonsensical cast to `A with B` of something that's definitely *not* a `B`, and a fortiori not an `A with B`.

That the Scala 2 version works is sheer luck.

**Comment by OndrejSpanel** [comment]
You are right, I did not think about implication of using `copy`.

**Comment by dwijnand** [comment]
Makes sense, I agree.
