### ISSUE TITLE
open is not treated as a normal identifier inside match

### ISSUE THREAD

**Issue by andrelfpinto** [lampepfl/dotty#15960]
## Compiler version

3.1.3

## Minimized code

```Scala
class Foo(open: String) {
  def bar(n: Int) = n match {
    case 0 => open
    case _ => throw new IndexOutOfBoundsException()
  }
  def baz() = open
}
```

## Output

```scala
-- [E088] Syntax Error: Open.scala:4:4 ----------------------------------------------------
4 |    case _ => throw new IndexOutOfBoundsException()
  |    ^^^^
  |    Expected start of definition

Explanation
===========
You have to provide either class, trait, object, or enum definitions after qualifiers

1 error found
```

## Expectation
 `bar` should compile as `baz` does.

According to [this](https://docs.scala-lang.org/scala3/reference/other-new-features/open-classes.html):

> `open` is a soft modifier. It is treated as a normal identifier unless it is in modifier position.

It seems like `open` is not being treated as a normal identifier inside `match`.

**Comment by som-snytt** [comment]
It needs to work a bit harder to disambiguate `case`.
```
class Foo(open: String):
  def bar(n: Int) = n match
    case 0 => open case class C(); ???
    case 1 => case class K(); ???
    case _ => throw new IndexOutOfBoundsException()
  def baz() = { open class D; () }
```
It says

> Modifier open is redundant for this definition

but not illegal.
