### ISSUE TITLE
Inheritence diagram is cut on new Scaladoc/Reference page

### ISSUE THREAD

**Issue by Sporarum** [lampepfl/dotty#15982]
The rendering of the picture is wrong:
https://dotty.epfl.ch/docs/reference/experimental/explicit-nulls.html
Cuts the image:
![image](https://user-images.githubusercontent.com/28290641/188683802-4724729a-4333-4723-8ce4-bf559e8c293e.png)

**Comment by Dedelweiss** [comment]
Hello, this problem is related to PR #17016
