### ISSUE TITLE
Type aliases of path-dependent context functions aren't interchangeable with their definition

### ISSUE THREAD

**Issue by ruippeixotog** [lampepfl/dotty#15995]
## Compiler version

3.2.0

## Minimized code

```Scala
trait Env {
  type Res
}

type EnvFunc = (env: Env) ?=> env.Res

val func1: (env: Env) ?=> env.Res = ???
val func2: EnvFunc = ???

def consume(f: EnvFunc): Unit = ???

object Main {
  consume(func1) // ok
  consume(func2) // error
}
```

## Output

```
[error] 33 |  consume(func2) // error
[error]    |          ^^^^^
[error]    |          Found:    examples.Env#Res
[error]    |          Required: evidence$2.Res
```

## Expectation

Both functions should type check, as I expect type alias usages to be always interchangeable with their definition.

**Comment by odersky** [comment]
I verified that this works now on latest main.

**Comment by ruippeixotog** [comment]
Thanks for confirming, @odersky! Do you know which PR fixed it? I'm curious to see details about this.

**Comment by odersky** [comment]
I think it was #15742, but did not check.
