### ISSUE TITLE
"Type Class Derivation" article uses an outdated version of `Mirror`

### ISSUE THREAD

**Issue by Sporarum** [lampepfl/dotty#16000]
https://dotty.epfl.ch/docs/reference/contextual/derivation.html

The signature in the article, [here](https://dotty.epfl.ch/docs/reference/contextual/derivation.html#types-supporting-derives-clauses), differs significantly from the one in the library, [here](https://dotty.epfl.ch/api/scala/deriving/Mirror.html).

Since the rest of the article is impacted by this, significant changes are needed.

**Comment by DmytroMitin** [comment]
@Sporarum Do you mean the absence of `MirroredType` and `MirroredElemTypes` at https://dotty.epfl.ch/api/scala/deriving/Mirror.html ?
But they are still present. You can check that
```scala
import scala.deriving.Mirror

case class A(i: Int, s: String)
val m = summon[Mirror.Of[A]]
summon[m.MirroredType =:= A]
summon[m.MirroredElemTypes =:= (Int, String)]
```
compiles independently of what is written in the API
https://scastie.scala-lang.org/DmytroMitin/fptUkuMwRnadns91SCKIdw

**Comment by Sporarum** [comment]
Ah I see, thank you, I'll close this issue
