### ISSUE TITLE
Cannot export extension methods from a generic type

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#16002]
## Compiler version

3.2.0

## Minimized code

I'm not sure if this is a bug, a feature, or something else but it is impossible to export methods from a generic type. The important of this kind of feature is that if it existed, it would be (probably) be possible to replace Quill's implicit conversion `Quoted[T] => T` with implicit exports (so long as the exported method themselves are inline).

```Scala
  class Wrapped[T](t: T) {
    def unwrap:T = ???
  }

  extension [T](t: Wrapped[T])
    def unwrapped: T = t.unwrap
    export unwrapped.*

Wrapped("blah").toUpperCase()
```

## Output

```
[error] 27 |      PrintMac(Wrapped("blah").toUpperCase())
[error]    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |value toUpperCase is not a member of org.deusaquilus.ImplicitConf.Wrapped[String], but could be made available as an extension method.
```

## Expectation
It should recognize that `.toUpperCase()` exists on `Wrapped[String]` because it exists on `String`.

The functionality should be equivalent to this (which works):
```scala
  extension (t: Wrapped[String])
    def unwrapped: String = t.unwrap
    export unwrapped.*

  Wrapped("blah").toUpperCase()
```

Of if `inline` is used, 
```scala
  extension (inline t: Wrapped[String])
    inline def unwrapped: String = t.unwrap
    export unwrapped.*

Wrapped("blah").toUpperCase()
// Which in the AST should be encoded as:
Wrapped("blah").unwrap.toUpperCase()
```
it should be equivalent to this:
```scala
extension (inline t: Wrapped[String])
    inline def unwrapped: String = t.unwrap
    inline def toUpperCase(): String = unwrapped.toUpperCase()

Wrapped("blah").toUpperCase()
```
Quill's unquotation `Quoted[T] => T` function specifically relies on this kind of pattern (i.e. the input `t` has to be directly spliced).

**Comment by odersky** [comment]
That will indeed not work. The exported members are chosen where the extension is defined. I don't see another possibility.

**Comment by deusaquilus** [comment]
@odersky I’m totally stuck then. Is there any other way I could potentially do automatic conversion of `Quoted[T] => T` without implicit conversion or in some way that is planned for long term support? Everything that is currently proposed wouldn’t work.

My original thoughts were here.
https://contributors.scala-lang.org/t/proposed-changes-and-restrictions-for-implicit-conversions/4923/167?u=deusaquilus
