### ISSUE TITLE
Inconsistency in fewerBraces applied to a literal

### ISSUE THREAD

**Issue by marcinzh** [lampepfl/dotty#16026]
## Compiler version

3.2.2-RC1-bin-20220910-ac6cd1c-NIGHTLY

## Minimized code

This one fails, because it is interpreted as a type-ascription expression:
```Scala
    val b = "abc":
      1
```

Those 2 succeed though:
```Scala
    val b = ("abc"):
      1
```
```Scala
    val abc = "abc"
    val b = abc:
      1
```

## Output

```scala
val b = "abc":
        ^^^^^
        Found:    ("abc" : String)
        Required: (1 : Int)
```

## Expectation
All 3 cases interpreted as fewerBraces application.

**Comment by som-snytt** [comment]
All hail early adopters of fewer braces!

**Comment by odersky** [comment]
This is as [specced](https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html):

> To this purpose we introduce a new <colon> token that reads as the standard colon ":" but is generated instead of it where <colon> is legal according to the context free syntax, but only if the previous token is an alphanumeric identifier, a backticked identifier, or one of the tokens this, super, ")", and "]".

So, `:` after a string is not interpreted as starting an indentation block. This was done so we err on the side of being restrictive. We can always generalize later. Also, it's a bit dubious why you would want `"...":`. It's a very obscure way to index a string! Or maybe you want to create a DSL where you insert a conversion or have an extension `apply` method. That would be interesting, maybe, but syntactic generality for the purpose of writing interesting DSL's has very much gone out of favor.

**Comment by marcinzh** [comment]
> It's a very obscure way to index a string!

I can't disagree :) I was toying with my DSL and ran into this limitation. I chose indexing for minimization.

> or have an extension apply method. 

This is the case. [Example](https://github.com/marcinzh/yamlike/blob/master/modules/yamlist-examples/src/main/scala/examples/TreeOfStrings.scala)
