### ISSUE TITLE
Incorrect "Missing type parameters for $type in subpart" for type variables in match clauses

### ISSUE THREAD

**Issue by pshirshov** [lampepfl/dotty#16039]
Compiler 3.2.0 / 3.1.*

```scala
trait K[-T]

import scala.quoted.{Expr, Quotes, Type}

def message( expr: Expr[Any])(using qctx: Quotes): Expr[String] = {
    import qctx.reflect.*

    val a = expr.asTerm.tpe.asType match {
        case given Type[a] =>
          Expr.summon[K[a]]
    }
    
    ???
}
```

This should compile but fails with incorrect message `Missing type parameters for a in subpart K[a] of inferred type K[a]` (type `a` accepts no type parameters)

Same code works as expected in a bit different environment: https://github.com/zio/izumi-reflect/blob/726ba818cd22091c74e51b729a05d7840eddeeaf/izumi-reflect/izumi-reflect/src/main/scala-3/izumi/reflect/TagMacro.scala#L113

https://scastie.scala-lang.org/C87fZpYVQcaXZ6muSTofKw

**Comment by WojciechMazur** [comment]
The bit different environment assumed the usage of [kind polymorphism](https://docs.scala-lang.org/scala3/reference/other-new-features/kind-polymorphism.html). I belive you missed a type bound, after applying which your code snippet would compile.
```
trait K[-T <: AnyKind]
```
