### ISSUE TITLE
Infinite recursion in TailRec

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#1603]
The `TailRec` phase goes into an infinit loop when processing a `tree: Apply` such that `tree.symbol != tree.fun`. This is the loop I observed with `jstack`:
- [src/dotty/tools/dotc/transform/TailRec.scala#309](https://github.com/lampepfl/dotty/blob/75f4400/src/dotty/tools/dotc/transform/TailRec.scala#L309)
- [src/dotty/tools/dotc/transform/TailRec.scala#210](https://github.com/lampepfl/dotty/blob/75f4400/src/dotty/tools/dotc/transform/TailRec.scala#L210)
- [src/dotty/tools/dotc/transform/TailRec.scala#190](https://github.com/lampepfl/dotty/blob/75f4400/src/dotty/tools/dotc/transform/TailRec.scala#L190)
- [src/dotty/tools/dotc/transform/TailRec.scala#177](https://github.com/lampepfl/dotty/blob/75f4400/src/dotty/tools/dotc/transform/TailRec.scala#L177)

Unfortunately I don't see how I could derive a minimized test case from the very large scalatest code base, if someone has an idea on how to pinpoint the issue in source please let me know!

**Comment by DarkDimius** [comment]
I don't think that making tailrec have less guards would be a proper way to resolve this. 
There are several locations in Dotty & Liker where extraction similar to https://github.com/lampepfl/dotty/blob/75f4400/src/dotty/tools/dotc/transform/TailRec.scala#L198-L206 is happening, where the way to detect when one curried application finished is to check for the symbol.

It would be better to find how this irregular Apply node was created in first place. Did you try running with `Ycheck` enabled?

**Comment by OlivierBlanvillain** [comment]
> Did you try running with `Ycheck` enabled?

No, so far I could only reproduce this by compiling the entirety of scalatest, and I don't really have an idea on how to reduce the search space...

**Comment by DarkDimius** [comment]
@OlivierBlanvillain, you should still be able to run under "-Ycheck:firstTransform" and see if `Ycheck` complains, even before minimization.

**Comment by OlivierBlanvillain** [comment]
I minimized this issue in #1687. Turns out it was not an infinite recursion but just a very large code explosion which looked infinite thought `jstack` :)
