### ISSUE TITLE
Lack of match type bound reduction

### ISSUE THREAD

**Issue by Bersier** [lampepfl/dotty#16058]
## Compiler version

3.2.0

## Minimized code

```Scala
sealed trait Nat
case class Zero() extends Nat
case class Succ[N <: Nat](n: N) extends Nat

type PredOrZero[N <: Nat] = N match
  case Zero => Zero
  case Succ[predN] => predN

type PredOrZeroOption[N <: Nat] <: Option[PredOrZero[N]] = N match
  case Zero => None.type
  case Succ[predN] => Some[predN]
```

## Output

```scala
Found:    Some[predN]
Required: Option[Playground.PredOrZero[N]]
```

## Expectation
It is expected that any match type within the type bound be reduced with all available information. For the branch `case Succ[predN]`, `N` is `Succ[predN]`. In other words, the code is expected to compile.

Note that this is distinct from refining the type bound directly with the available information within a branch, which would be unsound, as in the following example.

```Scala
type Foo[N <: Nat] <: (N => Unit) = N match
  case Zero => (Zero => Unit)
  case Succ[predN] => (Succ[predN] => Unit)
```

**Comment by sjrd** [comment]
> It is expected that any match type within the type bound be reduced with all available information. For the branch `case Succ[predN]`, `N` is `Succ[predN]`. In other words, the code is expected to compile.

While one could make a case for that, this amounts to adding GADT-style reasoning at the (meta-)type level when checking the branches of a match types against its bounds. The current spec for match types makes no such provision, so the current behavior is as specified.

Making this work would therefore require a spec change, which requires a SIP.

**Comment by bishabosha** [comment]
is this workaround satisfactory?
```scala
type PredOrZeroOption[N <: Nat] <: Option[PredOrZero[N]] = N match
  case Zero => None.type
  case Succ[predN] => Some[PredOrZero[N]]
```
