### ISSUE TITLE
Unsoundness from overriding vals

### ISSUE THREAD

**Issue by howtonotwin** [lampepfl/dotty#16092]
Tested on Dotty 3.2.0 and 3.2.1-RC2 (both via Scastie). What it says on the tin: overriding a `val` basically makes paths containing that `val` unstable. I searched the Dotty issue tracker for this issue and didn't find it, but I was expecting that a (serious?) soundness failure would be there. So this might be a duplicate.

## Code

```Scala
trait X {
  type T
  def process(t: T): Unit
}

class Z(val x: X, val t: x.T) {
  def process(): Unit = x.process(t)
}
class Evil(x1: X, x2: X, t: x1.T) extends Z(x1, t) {
  override val x: X = x2 // breaks connection between x and t
}
// alarm bells should be ringing by now

// taking it to its conclusion...
object x1 extends X {
  override type T = Int
  override def process(t: T): Unit = println("Int: " + t)
}
object x2 extends X {
  override type T = String
  override def process(t: T): Unit = println("String: " + t)
}
new Evil(x1, x2, 42).process() // BOOM: basically did x2.process(42)
```

## Output
No compiler error, and a `ClassCastException` when run.

## Expectation
Compiler error of some kind.

**Comment by odersky** [comment]
Good point. `val` overriding has been eyed with unease for a long time, but the objections were mostly about the weird initialization behavior. This might be the final straw to disallow it altogether.

**Comment by odersky** [comment]
I tried to construct a similar unsoundness example using just member val overriding (no val parameters) but failed. It would be good to find out whether that's just my lack of imagination or indeed it's necessary to have an overridden val parameter to exhibit the unsoundness.

**Comment by som-snytt** [comment]
FWIW, I would expect RefChecks to flag the `Evil` subclass. Although ctors are not overrides, the restriction would be that the two params must be redefined together. I was also surprised by how quickly the screws were tightened on val params. I expected clever syntax instead of the opinionated solution, but of course this is Scala 3.
