### ISSUE TITLE
Usage of this inside a lambda inside the constructor should be valid

### ISSUE THREAD

**Issue by evbo** [lampepfl/dotty#16103]
## Compiler version

3.2.0

## Minimized code
https://scastie.scala-lang.org/t7favpaqQNKAy9Nlt651uA
```scala
object Functions {
  def doSomething(e: TheEnum): Unit = {
    println(e.toString)
  }
}

sealed abstract class TheEnum(val status: () => Unit)
case object syntax extends TheEnum(status = () => Functions.doSomething(syntax))

object Main {
  def main(args: Array[String]): Unit = {
    println("It compiles")
    syntax.status()
  }
}
```

## Expectation

See discussion here:
https://discord.com/channels/632150470000902164/632150470000902166/1024034536432083016

<details>
<summary>discord</summary>

> It seems the problem has nothing to do with enum
> this is simply not valid inside a lambda inside the constructor: https://scastie.scala-lang.org/t7favpaqQNKAy9Nlt651uA
> Add this to the list of things of why constructors are weird
> Maybe worth reporting as a bug?
> Aly — Yesterday at 3:09 PM
> Well
> enum MyEnum(val f: () => Unit) {
>   case object Foo extends MyEnum(() => println(Foo))
> }
> 
> seems to cause a compiler crash 
> BalmungSan — Yesterday at 3:09 PM
> https://scastie.scala-lang.org/ZuvmjZtiT1SGLYQnuvyqPQ
> super constructor cannot be passed a self reference unless parameter is declared by-name
> Yeah, it seems all this is wrong.
> Aly — Yesterday at 3:10 PM
> Only on 3.1.3: In 3.2.0, it's handled correctly
> BalmungSan — Yesterday at 3:11 PM
> https://scastie.scala-lang.org/PD1U1g0tSeGtkKuFZxnZZw
> 
> You are goddamn right.
> So, I guess it is indeed worth reporting a bug.
> ebo — Yesterday at 3:12 PM
> im using scalaVersion := "3.2.0",
> BalmungSan — Yesterday at 3:12 PM
> It works if you use the enum name rather than this
> Which just means this should also work
> So you may workaround for now doing that, but still I would write a bug report.
> ebo — Yesterday at 3:14 PM
> I can't get it to work with enum... I see what you posted but that's using abstract classes
> BalmungSan — Yesterday at 3:14 PM
> Right: https://scastie.scala-lang.org/BalmungSan/zRbDbArKQYyVGpHBCnBbtA/3
> So, I think this deserves two bug reports.
> 1. Usage of this inside a lambda inside the constructor should be valid.
> 2. The expansion of enum cases should include an explicit type signature to allow recursive usage.
> 

</details>

**Comment by abgruszecki** [comment]
@evbo would you mind copying the discussion over from Discord, or at least including a screenshot?

**Comment by odersky** [comment]
This compiles and runs as expected with latest main.
