### ISSUE TITLE
Inline extension method leaks out proxy variable to macros

### ISSUE THREAD

**Issue by eed3si9n** [lampepfl/dotty#16106]
## Compiler version

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

I don't have minimized repro yet.  In sbt `.value` method for a setting is implemented as follows:

```Scala
  extension [A1](in: Initialize[A1])
    inline def value: A1 = InputWrapper.wrapInit[A1](in)
```

For example,

```scala
name := "abc" + version.value
```

first becomes

```scala
name := "abc" + InputWrapper.wrapInput(version)
```

Later on `:=(...)` macro expands the above to

```scala
name.set(version.mapN { p0 => "abc" + p0 })
```

## Output

```
While expanding a macro, a reference to value in$proxy1 was used outside the scope where it was defined
```

This happens I think because `.value` expands to

```scala
name := "abc" + {
  val in$proxy1 = version
  InputWrapper.wrapInput(in$proxy1)
}
```

## Expectation

Inline extension method is inlined.

As a workaround, I've started inlining these myself - https://gist.github.com/eed3si9n/6fc1e89f9a730f0e827327af0c268cb1

**Comment by nicolasstucki** [comment]
To avoid the proxy for the prefix you can inline it.

```diff
-  extension [A1](in: Initialize[A1])
+  extension [A1](inline in: Initialize[A1])
    inline def value: A1 = InputWrapper.wrapInit[A1](in)
```

**Comment by nicolasstucki** [comment]
@eed3si9n did that solve your issue?

**Comment by eed3si9n** [comment]
Yes, that fixed the issue. Thanks!
