### ISSUE TITLE
The expansion of enum cases should include an explicit type signature to allow recursive usage

### ISSUE THREAD

**Issue by evbo** [lampepfl/dotty#16102]
## Compiler version

3.2.0

## Minimized code

https://scastie.scala-lang.org/jlLGwMYtSzG7dYrEYNXGNQ

```scala
def doSomething(e: TheEnum) = println(e.toString)

enum TheEnum(val status: () => Unit) {
  case syntax extends TheEnum(
    status = () => doSomething(this)
    
  )
}

val a = TheEnum.syntax
a.status()
```

## Expectation

This does not compile but should. It is useful being able to reference `this` because otherwise trying to reference the enum from inside its own constructive triggers unwanted recursion. 

See for more details:
https://discord.com/channels/632150470000902164/632150470000902166/1024019578948431952

**Comment by bishabosha** [comment]
I'd like to see this work, but due to how enums desugar `this` doesnt make sense. e.g.
```scala
sealed abstract class TheEnum(val status: () => Unit) extends scala.reflect.Enum
object TheEnum:
  val syntax = new TheEnum(
    status = () => doSomething(this) // `this.type =:= TheEnum.type`
  )
```
In the example above, we can't replace `this` with `syntax`, because it's a val.

**Comment by bishabosha** [comment]
syntactically though it looks like this should be possible, so perhaps we can tweak the error message.

**Comment by bishabosha** [comment]
There's another problem which is that any reference to 'this' from the `extends` clause is always the outer scope - so this would be very unusual to suddenly refer to the enum case itself.

as to the unsafe recursion, this can be detected with `-Ysafe-init` which is why I mentioned it.

**Comment by evbo** [comment]
@bishabosha ok so then how do I pass `syntax` instead of `this`? It seems to want a type defined but I can't tell what it means based on the compiler error message. I'm sure it's simple, but I'm just a little confused where exactly it needs the type:
> Recursive value syntax needs type

**Comment by bishabosha** [comment]
> It seems to want a type defined but I can't tell what it means based on the compiler error message. I'm sure it's simple, but I'm just a little confused where exactly it needs the type:
> 
> > Recursive value syntax needs type

yeah so that error is because the desugaring is a val with an inferred type, not an explicit type, so it's not possible without changing desugaring. However I am not sure how possible this is to fix.

**Comment by evbo** [comment]
Thanks @bishabosha, so instead of calling `status` like so:

`theEnum.status()`

I can relent and just call it a bit more verbosely like:

`theEnum.status(theEnum)`

And then there's no need for `this`. All the same, this has been a fun deep dive and I appreciate the quick response. Good luck deciding what to do with this one.
