### ISSUE TITLE
Spurious unreachable case warning

### ISSUE THREAD

**Issue by Bersier** [lampepfl/dotty#16123]
## Compiler version

3.2.0

## Minimized code

```Scala
sealed trait Nat
case class Zero() extends Nat
case class Succ[N <: Nat](n: N) extends Nat

def foo(n: Nat): Int = n match
  case Zero() => 0
  case Succ(Zero()) => 1
  case _ => 2 // warning for this line

foo(Succ(Succ(Zero()))) // evaluates to 2
```

## Compiler warning

```scala
Unreachable case except for null (if this is intentional, consider writing case null => instead).
```

## Expectation
No warning

**Comment by strelec** [comment]
I has a similar issue in https://github.com/lampepfl/dotty/issues/15661

**Comment by tusharmath** [comment]
Facing similar issue here - https://github.com/zio/zio-schema/actions/runs/3226341119/jobs/5279743723

**Comment by KacperFKorban** [comment]
The fix will be released in `3.2.2`. It is currently included in `3.2.2-RC1` pre-release.

**Comment by tusharmath** [comment]
I tried again on `3.2.2-RC1` and am observing the same error.

**Comment by KacperFKorban** [comment]
@tusharmath Which snippet are you running? The one from the issue description works correctly in `3.2.2-RC1` for me.

**Comment by tusharmath** [comment]
I think in my case it's a valid warning :D

**Comment by tusharmath** [comment]
Actually this is still failing with `3.2.2-RC1` 
https://github.com/zio/zio-schema/actions/runs/3497863080/jobs/5857488661#step:5:126

**Comment by KacperFKorban** [comment]
@tusharmath If you think that the warning in `zio-schema` is wrong, then could you create a new issue for it? (this would mean that it is caused by a different bug)

**Comment by tusharmath** [comment]
Created a small repro — https://github.com/lampepfl/dotty/issues/16379
