### ISSUE TITLE
Extension method with same name but different type fails to compile when imported from another namespace

### ISSUE THREAD

**Issue by rpiaggio** [lampepfl/dotty#16139]
## Compiler version

3.2.0 and 3.2.1-RC2

## Minimized code

```Scala
object conversions1:
  extension (a: Int)
    def toInput: String = a.toString

object conversions2:
  import conversions1.*

  extension (b: Option[Int])
    def toInput: Option[String] = b.map(_.toInput)

import conversions2.*

println(Some(1).toInput)
```

(Can be found at https://scastie.scala-lang.org/2lP4Ei3gQlywZysAqUFcvQ)

## Output

Code doesn't compile. On the 2nd `toInput` definition (in `conversions2`) it emits the error:

```
value toInput is not a member of Int.
An extension method was tried, but could not be fully constructed:

    Playground.conversions2.toInput(_$1)    failed with

        Found:    Option[String]
        Required: String
```

## Expectation

The expectaction is for the code to compile. Both these versions work fine:

* Define both extension methods in same namespace:

```Scala
object conversions1:
  extension (a: Int)
    def toInput: String = a.toString

  extension (b: Option[Int])
    def toInput: Option[String] = b.map(_.toInput)

import conversions1.*

println(Some(1).toInput)
```

* or, change name of one of the extension methods:

```Scala
object conversions1:
  extension (a: Int)
    def toInput: String = a.toString

object conversions2:
  import conversions1.*

  extension (b: Option[Int])
    def toInput2: Option[String] = b.map(_.toInput)

import conversions2.*

println(Some(1).toInput2)
```

**Comment by som-snytt** [comment]
That is just how imports work. People ask for imports to introduce an overload, and there may be a "feature request".

It would be nice to have a FAQ for "how do I compose extensions".

**Comment by rpiaggio** [comment]
How is this an overload if both `toInput` methods are defined for different types? I mean, in `b.map(_.toInput)`, `_`'s type is `Int` and I would expect the compiler to match `conversion1`'s extension method, since it's defined unambiguously for `Int` in this scope.

This is code we are porting from Scala 2, where it worked with `implicit class (...) extends AnyVal`. We would like to keep downstream code unchanged. Is there some hint we can give to the compiler, or reorganize how we define the extensions, to achieve this? 

(We cannot define them all in the same file since our real `conversions2` refers to classes that are not available in other clients of `conversions1`.)

**Comment by som-snytt** [comment]
IIUC, you have the same complaint as others about extension methods, that they are "just a method". The method is `toInput` and takes `Int` or `Option[Int]` respectively.

This is a possible duplicate issue: https://github.com/lampepfl/dotty/issues/15691

I think the use case is the same: porting implicit classes to extension methods where the mechanisms are different.

**Comment by rpiaggio** [comment]
Thank you for the explanation.

Yes, this is definitely a duplicate of https://github.com/lampepfl/dotty/issues/15691, so I'm closing this one.

I see you also propose an alternate way of composing extensions on that issue, which we are adopting. Thanks again.
