### ISSUE TITLE
Methods on original type bleed into scope of extension method when they have the same name

### ISSUE THREAD

**Issue by felher** [lampepfl/dotty#16163]
## Compiler version
3.1.3, 3.2.0, 3.2.1-RC2 (maybe more, I've only tested those)

## Minimized code

```Scala
final case class Test():
  def run(x: Int): Unit = println("base")

object Scope:
  opaque type OTest = Test
  val otest: OTest = Test()

  object OTest:
    extension (t: OTest)
      def test(): Unit = run(3)
      def run(): Unit = println("extension")


import Scope.*

otest.test()
```
scastie: https://scastie.scala-lang.org/rtZZu12fT7edXKcbQRw60A

## Output

```scala
base
```

## Expectation

Should fail to compile because `def run(Int)` should not be in scope inside the extension method. Indeed, if the `def run(): Unit = println("extension")` line is removed, `def run(Int)` from `Test` is no longer in scope.

Not really sure if this is a bug, but it is not clear to me why defining a method with the same name but different signature pulls the original method into scope.

**Comment by odersky** [comment]
This is actually as specified. Quoted from https://dotty.epfl.ch/docs/reference/contextual/extension-methods.html:

> An extension method can also be referenced using a simple identifier without a preceding expression. If an identifier g appears in the body of an extension method f and refers to an extension method g that is defined in the same collective extension

    extension (x: T)
       def f ... = ... g ...
       def g ...

> the identifier is rewritten to x.g

In the example, `run(3)` is rewritten to `t.run(3)`.

**Comment by felher** [comment]
Does "If an identifier g appears in the body of an extension method f and **refers to an extension method g**..." mean "have the same name as"?
If so, that explains it, thank you! I would not have been surprised if I could call other extension methods this way. I was surprised that I could call non-extension-methods this way.

**Comment by odersky** [comment]
Yes, in this case it means "has the same name as". I tried to tighten the condition but it's actually quite hard since after typing all sorts of adaptations can happen so it's hard to see which method was actually called. I agree it's surprising, though.
