### ISSUE TITLE
given T = summon[T] sometimes loops forever

### ISSUE THREAD

**Issue by Bersier** [lampepfl/dotty#16162]
## Compiler version

3.2.0

## Minimized code

```Scala
package Scope:
  class BaseClass:
    opaque type Opaque = Foo
    given TypeClass[Opaque] = summon[TypeClass[Opaque]]
    def getFoo: Foo = Foo()

  class SubClass extends BaseClass:
    override def getFoo: Opaque & Foo = new Foo().asInstanceOf[Opaque & Foo]

  class Foo

  trait TypeClass[T]:
    extension (b: T)
      def other: T

  given TypeClass[Foo] with
    extension (b: Foo)
      final def other: Foo = ???

@main def main(): Unit =
  val instance = Scope.SubClass()
  val concrete = instance.getFoo
  println("About to hang")
  val other = concrete.other
  println("Never reached")
```

## Output

```
About to hang
```

## Expectation
Termination (with a runtime error)

**Comment by TheElectronWill** [comment]
The following works as expected, so the problem seems to come from the package declaration `package Scope:`.
```scala
package Scope // this line has changed

// the rest has one less indentation level
class BaseClass:
  opaque type Opaque = Foo
  given TypeClass[Opaque] = summon[TypeClass[Opaque]]
  def getFoo: Foo = Foo()

class SubClass extends BaseClass:
  override def getFoo: Opaque & Foo = new Foo().asInstanceOf[Opaque & Foo]

class Foo

trait TypeClass[T]:
  extension (b: T)
    def other: T

given TypeClass[Foo] with
  extension (b: Foo)
    final def other: Foo = ???

@main def main(): Unit =
  val instance = Scope.SubClass()
  val concrete = instance.getFoo
  println("About to hang")
  val other = concrete.other
  println("Never reached")
```
> About to hang
> Exception in thread "main" scala.NotImplementedError: an implementation is missing
>	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:344)
>        ...

**Comment by Bersier** [comment]
@TheElectronWill I spent a couple of hours minimizing the code. Adding the block package declaration allowed me to preserve the issue while putting everything in one file. Originally, the code spanned multiple files across several packages. So it doesn't have to be a **block** package necessarily, though a separate package might be essential.

**Comment by TheElectronWill** [comment]
Yes it seems that the important point is to have a separate package :)

**Comment by Bersier** [comment]
@anatoliykmetyuk did you assign this issue to me by mistake? I do not work on the Scala compiler.

**Comment by anatoliykmetyuk** [comment]
@Bersier could you please minimize the issue and pinpoint what exactly loops. So that we can fix it once we know what is broken.

**Comment by Bersier** [comment]
@anatoliykmetyuk I spent hours minimizing it. I couldn't find any simple change to minimize it further (I tried removing each part individually, I think). But perhaps it's due to exhaustion, and a fresh eye can minimize it further. `summon[TypeClass[Opaque]]` seems to be what loops.

**Comment by odersky** [comment]
> summon[TypeClass[Opaque]] seems to be what loops.

Why do you think it should not loop?

**Comment by odersky** [comment]
You can find out what code gets generated if you compile with -Xprint:typer.

**Comment by Bersier** [comment]
I know about the flag; I'm not personally interested in learning to study intermediate Scala representation to understand the compiler's obscure behavior.

However, I'm sure it will be helpful to whoever eventually investigates this.

**Comment by odersky** [comment]
I don't think we have the capacity to look further intro this then.

**Comment by Bersier** [comment]
How does lack of capacity make an issue "completed"? Many of the existing issues have been open for years, and many will remain open for years.

Or do you think it's not a real issue?

If so, it seems important for the language to have a high-level explanation for its behavior (ideally, answers to the questions I asked), rather than having the intermediate output generated by the compiler be the reference.

**Comment by Kordyjan** [comment]
As far as I remember our policy for dealing with issues that the core team has no capability to work on in the foreseeable future is to keep them open but tag them with a `backlog` label. There is always a chance that an outside contributor has some idea of what is going on and it may result in some improvements in the compiler.

On the other hand, this code is not working because the `given TypeClass[Opaque] = summon[TypeClass[Opaque]]` line is nonsensical and I cannot imagine any correct code in which it could arise. 

However, the fact that it changes the behavior depending on the scope in which it is defined points to something fishy going on. This is another reason to keep it open. The, yet untraced, bug that is causing the change in the behavior may manifest somewhere else. When we encounter it there this issue may give us some insight into fixing the bug.

There is also the fact that if we change the `summon` to `implicitly` we get a nice warning explaining why the code will result in an endless loop. We should probably try to apply this to `summon`s.
Is it possible, @odersky ?

**Comment by Bersier** [comment]
@Kordyjan's analysis seems most reasonable to me.

Sidenote: I have used this pattern successfully in my code, where for some reason, the `summon` picks the other given, rather than going into an infinite loop. So `given TypeClass[Opaque] = summon[TypeClass[Opaque]]` can technically be sensical in Scala 3.2.0. But I don't advocate keeping this quirk usable, particularly if it's not reliable.

**Comment by kyri-petrou** [comment]
I believe this might be similar to something I recently came across as well. Best I could do with minimizing it:

```scala
trait IntNewtype:
  opaque type Type = Int
  def apply(value: Int): Type = value
  given Ordering[Type] = summon[Ordering[Int]]

object Bar extends IntNewtype

@main def main: Unit =
  val barList = List(Bar(2), Bar(1))
  println("sorting list") 
  val _ = barList.sorted  // Hangs here
  println("finished sorting list")
```
As @Kordyjan mentioned, substituting `summon[...]` with `implicitely[...]` indeed raises a compiler warning. Interestingly, if we substitute `given Ordering[Type] = implicitly[Ordering[Int]]` with the snippet below, no warning is raised and the code hangs

```scala
  private def ord = implicitly[Ordering[Int]]
  given Ordering[Type] = ord
```

**Comment by dwijnand** [comment]
Oh, yeah.  I hit that back in 3.1.1, which I can minimise to:

```scala
object Test:
  opaque type Val = Int
  given Integral[Val] = summon[Integral[Int]]
  def main(args: Array[String]): Unit = summon[Integral[Val]]
```

In the original, I'm defining the given inside Val's companion object, so it's in implicit scope.  It seemed obvious to me that you can look things up in implicit scope while defining an opaque type, without the definition recursing back on itself.

I've also hit this in a large corporate codebase, using Scala 2, while migrating the code to give implicits explicit types: that affects implicit lookup leading to loop where previously it worked.  So I think it might help the opaque type use case in particular (my minimised, simple one, perhaps the original one too) but maybe even given definitions in general if the LHS declaration weren't available in scope in its definition.  Perhaps there are use cases where that looping is required, so it might be necessary to opt-in or opt-out to this change.

**Comment by odersky** [comment]
> In the original, I'm defining the given inside Val's companion object, so it's in implicit scope. It seemed obvious to me that you can look things up in implicit scope while defining an opaque type, without the definition recursing back on itself.

Lookup in the current scope is done before lookup in the implicit scope, and it finds the recursive given. So, no, you can't do that. You need a construction where the `summon` happens outside the scope where `Val` is defined.

**Comment by odersky** [comment]
I see warnings for all three summons that were shown in the examples above:
```
-- Warning: i16162.scala:3:24 --------------------------------------------------
3 |  given Integral[Val] = summon[Integral[Int]]  // error
  |                        ^^^^^^^^^^^^^^^^^^^^^
  |                        Infinite loop in function body
  |                        Test.given_Integral_Val
-- Warning: i16162.scala:9:25 --------------------------------------------------
9 |  given Ordering[Type] = summon[Ordering[Int]] // error
  |                         ^^^^^^^^^^^^^^^^^^^^^
  |                         Infinite loop in function body
  |                         this.given_Ordering_Type
-- Warning: i16162.scala:24:30 -------------------------------------------------
24 |    given TypeClass[Opaque] = summon[TypeClass[Opaque]]
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^
   |                              Infinite loop in function body
   |                              this.given_TypeClass_Opaque
```
Not sure what else one should do here. It all looks completely as expected and the compiler does give the helpful warnings.

**Comment by kyri-petrou** [comment]
> I see warnings for all three summons that were shown in the examples above

Okay I see, I was using Scala `3.2.0` which doesn't produce any warnings, but `3.2.1-RC1` and `3.2.1-RC2` do. Apologies for not checking that beforehand

**Comment by odersky** [comment]
I did not realize 3.2.0 did not have the fix. It feels a long time since this was fixed; I thought it would be in stable release now.

**Comment by odersky** [comment]
So I can think we can safely close this now.
