### ISSUE TITLE
Alias givens don't forward the reference for simple expressions

### ISSUE THREAD

**Issue by kyri-petrou** [lampepfl/dotty#16191]
## Compiler version

3.1.3 / 3.2.0 / 3.2.1-RC2

## Minimized code

```Scala
class Context

val ctx: Context = new Context
given Context = ctx
```

## Output

Compiler output using `-Xprint:typer`:

```scala
package <empty> {
  class Context() extends Object() {}
  final lazy module val Main$package: Main$package = new Main$package()
  final module class Main$package() extends Object() { 
    this: Main$package.type =>
    val ctx: Context = new Context()
    final lazy given val given_Context: Context = ctx
  }
}
```

## Expectation

According to the [documentation](https://docs.scala-lang.org/scala3/reference/contextual/relationship-implicits.html#given-instances), the given in the example above should forward the reference instead of caching it. i.e.,

```scala
final lazy given val given_Context: Context = ctx
```

should map to 

```scala
final given def given_Context: Context = ctx
```

Is this an issue with the documentation, the compiler or am I misinterpreting the documentation?

**Comment by odersky** [comment]
It was a bug in the compiler. To find out it's OK now, one actually has to look after typer, for instance using `-Xprint:erasure`, since the val is converted to a def only in miniphase UncacheGivenAliases. I also included a test.

**Comment by kyri-petrou** [comment]
Ah, I wasn't sure if I was printing the output at the right place, although it seems the bug was there nonetheless. Thanks!
