### ISSUE TITLE
Scala 3 reference docs for 3.2.0 do not have updated sources

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#16201]
as of 18 October 2022 https://docs.scala-lang.org/scala3/reference/language-versions/source-compatibility.html looks like:
<img width="1283" alt="Screenshot 2022-10-18 at 09 59 56" src="https://user-images.githubusercontent.com/13436592/196371603-c0b00194-7846-4ca3-b9ec-e59cd2f6ce04.png">

it should show content as listed in https://github.com/lampepfl/dotty/blob/release-3.2.0/docs/_docs/reference/language-versions/source-compatibility.md

**Comment by bishabosha** [comment]
according to @julienrf `release-3.2.0` should be merged into `language-reference-stable`

**Comment by julienrf** [comment]
I think there is a general lack of clarity about how the various docs are generated.

As far as I understand, we have:
- https://scala-lang.org/api/3.x (which is generated by VirtusLab publishing some files on an EPFL-owned server)
- https://docs.scala-lang.org/scala3/reference (which is generated by EPFL, by pulling the content of https://github.com/lampepfl/scala3-reference-docs, which is itself generated automatically from the content on this repository on branch `language-reference-stable`)
- https://dotty.epfl.ch (nightly documentation)

Correct me if I am wrong, and please document those things here (in `CONTRIBUTING.md`?), and explain the policies regarding what goes into what branch (if I want to fix something in the documentation, should I target `main` or `language-reference-stable`?).

Last, make sure the release procedure takes all those forms of documentation into account (currently, it seems only the API documentation is updated during the release process, but you should also merge the content of the main branch to `language-reference-stable` before the release)

**Comment by bishabosha** [comment]
> Last, make sure the release procedure takes all those forms of documentation into account ... but you should also merge the content of the main branch to `language-reference-stable` before the release)

I think you mean the current release branch? - main branch might have documentation for unreleased new features

**Comment by julienrf** [comment]
> I think you mean the current release branch? - main branch might have documentation for unreleased new features

Yes.

**Comment by bishabosha** [comment]
Changes are now visible on the website
