### ISSUE TITLE
No documentation for `-scastie-configuration`

### ISSUE THREAD

**Issue by ckipp01** [lampepfl/dotty#16220]
## Compiler version

All of them

## Example

As outlined in [here](https://github.com/lampepfl/dotty/discussions/15966) most users of Scaladoc are going to want to use examples of their code. However, by default the integration with scastie won't work for this since it won't recognize any of the needed dependencies, including your own code. From the response there and in the pr that added this [here](https://github.com/lampepfl/dotty/pull/13258) you see the following:

> You can there specify libraryDependencies setting. It will probably be done better in future (automatically get this configuration from sbt) but for now it works like that.

However there is no further explanation on how to actually use `-scastie-configuration` and even looking in the code you just see it's a `String` setting with a description and no examples of how to actually use it.

## Expectation

I'd expect for a core feature like this to be documented so that library authors can use Scaladoc with the scastie integration for their projects. Right now it's pretty unusable for snippets.

**Comment by SethTisue** [comment]
> Right now it's pretty unusable for snippets

And what I'm sometimes seeing in the wild is people publishing Scaladoc that has snippets, but they don't actually run. I'm not sure the library maintainers are even noticing the play buttons.

I doubt it's a good idea for the Scastie links to be emitted to be default. As Chris wrote in the discussion,

> I also then don't see a way to turn the play button off

**Comment by szymon-rd** [comment]
Thanks for reporting! We will look into it after the current polishing of scaladoc.
