### ISSUE TITLE
Update flexmark to a modern version and try to avoid CVEs.

### ISSUE THREAD

**Issue by ckipp01** [lampepfl/dotty#16223]
## Compiler version

All of them that contain the new Scaladoc.

## Description

From what I can see since the new Scaladoc was introduced it's using a very [old version of Flexmark](https://github.com/lampepfl/dotty/blob/7919cb375a3d1c931ed3841617774bdd8c49c62c/project/Dependencies.scala#L13), 0.42.12. This version was released early in 2019 and has a handful of CVEs attached to it as you can see under [Vulnerabilities](https://mvnrepository.com/artifact/com.vladsch.flexmark/flexmark/0.42.12). Any type of CVE scanning that _many_ places will do will pick this up. There is also a ton of extensions that are being use that are old and also have CVEs attached to them. It looks like even the newest version 0.64.0 still [has some](https://mvnrepository.com/artifact/com.vladsch.flexmark/flexmark/0.64.0), but I feel like it's not a good idea to use something as old as this without ever updating especially seeing that there are CVEs attached to it.

## Expectation

I'd expect the dependencies the compiler uses are up to date and that the team does its best to avoid dependencies with published CVEs.

**Comment by michelou** [comment]
@ckipp01 Agreed. Related to the discussion [**13799**](https://github.com/lampepfl/dotty/discussions/13799) I initiated on October 2021 (and with only 1 feedback, sadly IMO).

**Comment by Dedelweiss** [comment]
Hello, I would like to help with this issue. I notice that a PR is started but blocked by an error. At least if someone has started a correction or has some suggestions, I am quite interested !
