### ISSUE TITLE
Regression in warning style in new Scaladoc UI

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#16233]
The current dotty website contains a section with `class="warning"` that renders as follows:

![image](https://user-images.githubusercontent.com/332812/197326549-4fb6f359-91d4-475c-a9e8-8dd8e94893bb.png)

This section should more visible. Fore reference, it used to be as follows before the migration to the new Scaladoc UI:

![image](https://user-images.githubusercontent.com/332812/197326666-8bff80ce-744c-45b0-bf99-48c43f6d9541.png)

**Comment by Dedelweiss** [comment]
This issue seems to be corrected. @ckipp01

**Comment by ckipp01** [comment]
> This issue seems to be corrected. @ckipp01

Do you have a link on the current scaladoc where this is being used and is showing correctly @Dedelweiss ?

**Comment by Dedelweiss** [comment]
Of course, here is an example on this [page](https://dotty.epfl.ch/docs/reference/dropped-features/type-projection.html). As you can see below, the section with the warning class is much more visible. 
<img width="500" alt="Screenshot 2023-04-12 at 14 03 41" src="https://user-images.githubusercontent.com/44496264/231451947-638fe7af-2353-45b6-9bec-3e0fa1ae7d02.png">

**Comment by julienrf** [comment]
Thank you for checking this, @Dedelweiss!
