### ISSUE TITLE
Probably a false positive warning for type tests 

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#16259]
Type test for locally defined classes (eg. within method) ends up with a warning. Not sure if it's a false ~negative~ positive introduced via regression or an improvement.

## Compiler version
3.2.1

## Minimized code

```Scala
@main def Test = {
  class A(private val x: Int) {
    override def equals(that: Any): Boolean = that match {
      case that: A => this.x == that.x
      case _       => false
    }
  }
}
```

## Output

```scala
Compiling project (Scala 3.2.1, JVM)
[warn] ./sandbox/src/main/scala/Test.scala:5:12: the type test for A cannot be checked at runtime
[warn]       case that: A => this.x == that.x
```

**Comment by SethTisue** [comment]
Seems like a regression to me. I see no reason the type test couldn't be performed.

Nitpick: we would refer to this as a "false positive", not a "false negative" — as per https://en.wikipedia.org/wiki/False_positives_and_false_negatives, it isn't about whether something good or something bad is being signaled; it's about whether a signal is present or absent. Here something (a warning) is present when it shouldn't be, hence "false positive" — despite the warnings being about something bad.

**Comment by dwijnand** [comment]
It's not a regression, it's right.  See https://github.com/lampepfl/dotty/issues/4812 and https://github.com/lampepfl/dotty/pull/15134.

**Comment by SethTisue** [comment]
TIL!
