### ISSUE TITLE
Improve support for Unicode supplementary characters in identifiers and string interpolation (as in Scala 2)

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#16271]
## Minimized code

```Scala
Welcome to Scala 3.2.0 (19, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> val Trying to highlight erroneous position <7..7>. Input size: 6
😈 = 42
-- Error: --------------------------------------------------------------------------------------------------------------
1 |val 😈 = 42
  |    ^
  |    illegal character '\ud83d\ude08'

scala>
```

## Shotput

Gave it a shot.

## Expectation

https://twitter.com/SethTisue/status/1587184657141039110

**Comment by SethTisue** [comment]
sounds like Satan wanted a list made of who’d been naughty but his minion just cashed the check and never delivered

**Comment by som-snytt** [comment]
Little-known fact, Santa does outsource it, and this is the only reason we ever get any presents.

**Comment by som-snytt** [comment]
This is just the ~backport~ forward [!] port of the PR mentioned by Seth, https://github.com/scala/scala/pull/9805

Took me a while to remember the subtle difference: the horned face is an operator.

I also see that on the linked PR, I suggested that I would try to refresh my memory and forward port it.
