### ISSUE TITLE
XML conflict with LazyVals

### ISSUE THREAD

**Issue by lrrebenitsch** [lampepfl/dotty#16281]
The compiler crashes with this note: **scalac: value getOffsetStatic is not a member of object scala.runtime.LazyVals**

To reproduce:
IDE: IntelliJ 2022
Project type: .idea
OS: Windows 10
Scala version: 3.2.1
XML library installed: 3-2.1.0
Lines of code that reproduce the error:
   var y: Int = 0
   lazy val temp = y + 1

When checking what version of LazyVal was being used, both scala.runtime.LazyVals and one from the xml library.

**Comment by smarter** [comment]
> When checking what version of LazyVal was being used, both scala.runtime.LazyVals and one from the xml library.

There's no scala.runtime.LazyVals in scala-xml so I'm not sure what you mean, I suspect there is something wrong in your classpath (an old version of scala3-library ?), but we'd need to see the full classpath to know.

**Comment by lrrebenitsch** [comment]
I definitely have a double LazyVals somehow. I'll pull up the library list. Oh for...

IntelliJ triple imported a sdk. I had both 3.1.3 and 3.2.1 importing into the same project, but only one had the xml, which gave me the false lead. Now I do not know how is compiled in the first place. Here is what I have now (I have 3.2.1 to take the xml as  global library, since I use xml a lot):
[cid:dddf7f55-609f-421a-9a7a-5181def58709]
What I had before managed to give me sdk 3.1.3 in that list, twice. I only had xml in the 3.1.3 sdk, but not the 3.2.1. Now, the better question, is how on Earth did it compile before when it was looking at 3 sdks?!

Well...this sound like a bug report to IntelliJ, not Scala...Sorry!

Lisa

________________________________
From: Guillaume Martres ***@***.***>
Sent: Thursday, November 3, 2022 10:42 AM
To: lampepfl/dotty ***@***.***>
Cc: Rebenitsch, Lisa R. ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [lampepfl/dotty] XML conflict with LazyVals (Issue #16281)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

    *** This email is from an EXTERNAL sender. Use CAUTION before opening attachments or clicking links.***

When checking what version of LazyVal was being used, both scala.runtime.LazyVals and one from the xml library.

There's no scala.runtime.LazyVals in scala-xml so I'm not sure what you mean, I suspect there is something wrong in your classpath (an old version of scala3-library ?), but we'd need to see the full classpath to know.
