### ISSUE TITLE
Decide what `future` behavior should be enabled in 3.4

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#16334]
for `-source:3.4` we need to turn on current `future` semantics for refutable pattern bindings

**Comment by smarter** [comment]
> Can we write for case p <- xs in 2.13?

Yes, this is possible in both 2.12 and 2.13 now, case is just a no-op by default: https://github.com/scala/scala/pull/9721

**Comment by carlosedp** [comment]
I was looking for a way to directly unpack tuples on for comprehensions and found `better-monadic-for` then saw that enabling the `-source:future` flag makes the behavior available in Scala 3. One use case is similar to https://github.com/zio/zio/issues/2761.

I wonder if this feature included in the "refutable patterns" listed above and if there plans to make it available as default in Scala 3.3?

Thanks!

**Comment by gabro** [comment]
Hi, just FYI the documentation still states that the new pattern bindings behavior "will be enabled by default in version 3.2 of the language", which turns out not to be true.

I can send a PR updating the docs, but I was wondering if there's a scheduled timeline for this?

**Comment by odersky** [comment]
There's no scheduled timeline. It would be great if someone would work out a proposition.

**Comment by carlosedp** [comment]
I understand the implementation already exists in dotty and it would be a matter of making it into 3.4 instead of source:future, correct?

If so, I could take a look into trying to submit a PR changing this.

**Comment by bishabosha** [comment]
I've now updated the title to be what to enable in 3.4

**Comment by SethTisue** [comment]
I have taken the liberty of adding this to the 3.4.0 milestone.

**Comment by rssh** [comment]
Also, please look at making -XmacroSettings non-experimental.
(related ticked - https://github.com/lampepfl/dotty/issues/15637 )

**Comment by nicolasstucki** [comment]
-XmacroSettings is not ready to be made non experimental. We do not have a proper specification for it and we know that the current implementation is fundamentally broken.

**Comment by carlosedp** [comment]
I've submitted #18606 to address the direct tuple assignment in for comprehensions.

**Comment by nicolasstucki** [comment]
We decided to include in 3.4 all that is already on maser plus what is listed in the [3.4 milestone](https://github.com/lampepfl/dotty/milestone/49). The list of syntactic deprecation warnings that will be enabled in 3.4 can be found [here](https://github.com/orgs/lampepfl/projects/2/views/11).

**Comment by joan38** [comment]
This does not seem enabled in Scala 3.4.x
See Stackoverflow question https://stackoverflow.com/questions/78580466/why-doesnt-my-scalac-prints-any-warning-for-missing-open-keyword
Any information on if it is and we are missing something or if it's planned for 3.5.x?

**Comment by odersky** [comment]
3.5 is already defined, but it should arrive in 3.6, later this year. It is already enabled under `-source future`.

**Comment by Gedochao** [comment]
So just to keep everyone up-to-date, it was decided on this week's Scala Core that we'd enable it under 3.10.
