### ISSUE TITLE
Ambiguous given instances despite inferrable type variable.

### ISSUE THREAD

**Issue by adampauls** [lampepfl/dotty#16356]
## Compiler version

3.2.0-RC2 (from Scastie)

## Minimized code

```Scala
import math.Ordering.Implicits.infixOrderingOps
extension [T: Ordering] (t: T) {
  def lessThan(o: T): Boolean = t < o
}

trait MyConversion[T, U] {
  def apply(t: T): U
}
object MyConversion {
  def convert[T, U](t: T)(using conv: MyConversion[T, U]): U = conv(t)
}

given MyConversion[Date => Boolean, Date] with {
  def apply(t: Date => Boolean): Date = new Date
}
given [T]: MyConversion[T, T] with {
  def apply(t: T): T = t
}
class Date
given Ordering[Date] with {
  def compare(a: Date, b: Date): Int = 0
}

def before(x: Date => Boolean): Date => Boolean = { d =>
    d.lessThan(MyConversion.convert(x)) // error
}
```

## Output

```
Ambiguous given instances: both object given_MyConversion_Function_Date in object Playground and given instance given_MyConversion_T_T in object Playground match type Playground.MyConversion[(Playground.Date => Boolean), U] of parameter conv of method convert in object MyConversion
```

## Expectation

Should compile because the first given instance is more specific. Note that `d.lessThan(MyConversion.convert(x): Date)` compiles just fine, but does not add new information since `d` is known to be `Date` and `lessThan` should therefore constrain its right argument to be `Date`.

**Comment by adampauls** [comment]
I did a little more digging. This is not related to `extension` methods, but rather some funny currying behavior. If I replace `d.lessThan(MyConversion.convert(x))`  with 
```scala
val tmp = lessThan(d)
 tmp(MyConversion.convert(x))
```

then everything works. Although I understand that type inference is expected to behave differently with multi-param applies, I thought it was supposed to be tighter, but here it is looser.

**Comment by adampauls** [comment]
I see, I did realize that typer was happy to find the lub of the arguments in a multi-param list function since "type inference proceeds one parameter list at a time", but TIL.

**Comment by adampauls** [comment]
Okay, I think I understand this now. I made two incorrect assumptions: (1) I think "type inference proceeds one parameter list at a time", from [this page](https://docs.scala-lang.org/tour/multiple-parameter-lists.html) is a little misleading: the compiler is happy to compute the least upper bound of `a` and `b` in `def foo[T](a: T)(b: T)` when it is invoked with both param lists and (2) `given MyConversion[Date => Boolean, Date]` is always "more specific" than `given [T]: MyConversion[T, T]`. 

What happens here is that the compiler only bounds `T` in `lessThan` to be `>: d.type`, because it is the first argument and then waits to see what the second argument to `lessThan` is. Since the second argument to can be anything `>: d.type` and there exists a conversion from from `T=> T` for all `T`, it is possible to convert `Date => Boolean` to `Date => Boolean` and then invoke `lessThan` with the least upper bound of `Date` and `Date => Boolean` (probably `Any`). Of course, there is no `Ordering` instance for `Any`, but the compiler doesn't know that when trying to find the right `MyConversion` instance. I'm still a little surprised that the compiler doesn't consider `given MyConversion[Date => Boolean, Date]` to be more specific of the two; is that a bug? I've never totally understood the implicit resolution rules here, but I do know that for the typical cases, alternatives with fewer type parameters are more specific.

**Comment by adampauls** [comment]
This was my mistake. The problem is that `MyConversion` needs to be `[-T, +U]`.

**Comment by smarter** [comment]
> I think "type inference proceeds one parameter list at a time", from [this page](https://docs.scala-lang.org/tour/multiple-parameter-lists.html) is a little misleading

Yes that information is completely obsolete, it applies to how Scala 2 works but now how Scala 3 works where multiple parameter lists don't influence inference. I've opened https://github.com/scala/docs.scala-lang/issues/2648 to take this into account, I'm afraid my talk on inference (linked in the issue) is the only source of mostly accurate information on inference on Scala 3 right now.
