### ISSUE TITLE
Problem with Traits not being Matchable

### ISSUE THREAD

**Issue by bblfish** [lampepfl/dotty#16408]
A fully minimized version of code to duplicate the problem can be found [in the comment below by Symon R.]( https://github.com/lampepfl/dotty/issues/16408#issuecomment-1359668426).

## Compiler version

scala 3.2.1 (older too) and nightly 3.3....

## Minimized code

The code that does not compile is on this [onepage](https://github.com/bblfish/DottyIssue16247/tree/onepage) branch of a repo specially for this Dotty issue. There is now only  one file to look at: [RDF.scala](https://github.com/bblfish/DottyIssue16247/blob/onepage/scala/RDF.scala).

The code is duplicated in full here:

```scala
import scala.util.Try

trait RDF:
  rdf =>

  type R = rdf.type
  type Node <: Matchable
  type URI <: Node 

  given rops: ROps[R]
end RDF

object RDF:
  type Node[R <: RDF] = R match
    case GetNode[n] => Matchable //n & rNode[R]

  type URI[R <: RDF] <: Node[R] = R match
    case GetURI[u] => u & Node[R] 

  private type GetNode[N] = RDF { type Node = N }
  private type GetURI[U] = RDF { type URI = U }
end RDF

trait ROps[R <: RDF]:
  def mkUri(str: String): Try[RDF.URI[R]]
  def auth(uri: RDF.URI[R]): Try[String]

object TraitTypes:
  trait Node:
    def value: String

  trait Uri extends Node

  def mkUri(u: String): Uri =
    new Uri { def value = u }

object TraitRDF extends RDF:
  import TraitTypes as tz

  override opaque type Node <: Matchable = tz.Node
  override opaque type URI <: Node = tz.Uri

  given rops: ROps[R] with
    override def mkUri(str: String): Try[RDF.URI[R]] = Try(tz.mkUri(str))
    override def auth(uri: RDF.URI[R]): Try[String] =
      Try(java.net.URI.create(uri.value).getAuthority())

end TraitRDF

class Test[R <: RDF](using rops: ROps[R]):
  import rops.given
  lazy val uriT: Try[RDF.URI[R]] = rops.mkUri("https://bblfish.net/#i")
  lazy val x: String = "uri authority=" + uriT.map(u => rops.auth(u))

@main def run =
  val test = Test[TraitRDF.type]
  println(test.x)
```

## Output

The compilation error can be seen in the github actions [failing check here](https://github.com/bblfish/DottyIssue16247/actions/runs/3734423056/jobs/6336456332).
But I could not get the `-explain` flag to work with `scala-cli`.

Running it on the command line one gets the full error explantion. (After setting the env variables
below
```zsh
export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home
export SCALA_HOME=/usr/local/scala/scala3-3.2.1
```
The following command
```zsh
sh bin/clean
sh bin/compileScala
-- Error: scala/RDF.scala:44:8 -------------------------------------------------
44 |  given rops: ROps[R] with
   |        ^
   |object creation impossible, since def auth(uri: RDF.URI[R]): util.Try[String] in trait ROps is not defined
   |(Note that
   | parameter RDF.URI[R] in def auth(uri: RDF.URI[R]): util.Try[String] in trait ROps does not match
   | parameter TraitTypes.Uri & Matchable in override def auth(uri: TraitTypes.Uri & Matchable): util.Try[String] in object rops in object TraitRDF
   | )
-- [E038] Declaration Error: scala/RDF.scala:46:17 -----------------------------
46 |    override def auth(uri: RDF.URI[R]): Try[String] =
   |                 ^
   |   method auth has a different signature than the overridden declaration
   |----------------------------------------------------------------------------
   | Explanation (enabled by `-explain`)
   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   | There must be a non-final field or method with the name auth and the
   | same parameter list in a super class of object rops to override it.
   |
   |   override def auth(uri: TraitTypes.Uri & Matchable): util.Try[String]
   |
   | The super classes of object rops contain the following members
   | named auth:
   |   def auth(uri: RDF.URI[TraitRDF.R]): util.Try[String]
    ----------------------------------------------------------------------------
```

But the compiler only has a problem when the URI is implemented in terms of a trait, not when it is implemented in terms of a class. 

## Expectation

The expectation is that it should work with traits as well as with classes. 

A fix is to change the `trait Uri` to a `class Uri` as in the commit that lead to the [onepage-works branch commit](https://github.com/bblfish/DottyIssue16247/commit/9a84a06c28013add0914b6741420c77c595a51bd) as shown in this minimal diff:

<img width="1332" alt="Screenshot 2022-12-19 at 21 04 36" src="https://user-images.githubusercontent.com/124506/208510588-d3960f5a-5c95-44c9-8f5b-5b3d5b64decf.png">

The problem is that it is not always possible use classes only and not traits. A major RDF library [RDF4J](https://rdf4j.org) uses traits for its RDF model, such as [IRI](https://github.com/eclipse/rdf4j/blob/main/core/model-api/src/main/java/org/eclipse/rdf4j/model/IRI.java).

**Comment by bblfish** [comment]
The code I posted currently stems from the use case I described in [lib unification and match types](https://users.scala-lang.org/t/lib-unification-with-match-types-a-problem-with-inheritance/8880/7) so it has the advantage of describing a realistic situation.

But I agree. I'll try to remove stuff slowly and see how small I can get. 
Doing that will take a bit of time though...

**Comment by szymon-rd** [comment]
To be fair, it is not that valuable to represent a realistic situation. It's best to require as little context as possible, and representing a realistic situation often requires adding additional, unnecessary information. This is a bug report to the compiler, and it's best to stay on the same level of abstraction that the compiler is operating on - the syntactic and semantic structures. You can, of course, provide a rationale on why it is a bug that relates to the real-world problem - for example, argument that the compiler behaves confusingly in a common real-world case. But the problem itself should be kept as simple as possible, and having as narrow context as possible.

**Comment by bblfish** [comment]
Ok, @szymon-rd I created a new branch [minimization](https://github.com/bblfish/DottyIssue16247/tree/minimization) and was able to remove quite a lot of code, as shown by the [history](https://github.com/bblfish/DottyIssue16247/commits/minimization). commit https://github.com/bblfish/DottyIssue16247/commit/4159ccdb2e02c225561b43cb22099cb70e21499c removed too much, and  commit https://github.com/bblfish/DottyIssue16247/commit/eaf445a867bf27d01d4d3f8d954dc807320a176d put back the minmum for the problem to reappear, as one can see in the [github actions](https://github.com/bblfish/DottyIssue16247/actions/runs/3542020622/jobs/5947007274#step:9:31). 

The problem appears when I move from the

```scala
trait RDF:
  rdf =>

  type R = rdf.type
  
  type Node <: Matchable
  type URI <: Node

  given rops: ROps[R]
end RDF
```

```scala
trait RDF:
  rdf =>

  type R = rdf.type
  type rNode <: Matchable
  type rURI <: rNode
  type Node <: rNode
  type URI <: Node & rURI

  given rops: ROps[R]
end RDF
```

I should have saved the intermediate point which also compiled which I think was 
```
```scala
trait RDF:
  rdf =>

  type R = rdf.type
  type rURI <: Matchable
  type Node <: rNode
  type URI <: Node & rURI

  given rops: ROps[R]
end RDF
```

**Comment by szymon-rd** [comment]
Thank you for the additional information! This code is still really complex, and further minimization would be welcome. Making the code simpler and shorter will allow us to address this issue faster.

**Comment by bblfish** [comment]
I have simplified the code again now here in the `min2` branch. I removed the no-longer needed java interfaces, and I merged two files so as to reduce them down to 3.  

https://github.com/bblfish/DottyIssue16247/blob/min2

The difference between the two classes `RDF_Class` and `RDF_Trait` is very small as can be seen by this opendiff snapshot.

<img width="1512" alt="Screenshot 2022-12-01 at 16 28 18" src="https://user-images.githubusercontent.com/124506/205093181-a3094b0b-165f-4c35-898c-40cd03c39fc8.png">

The code is run https://github.com/bblfish/DottyIssue16247/actions/runs/3594012563

**Comment by bblfish** [comment]
I have no created a new branch [min2-fix](https://github.com/bblfish/DottyIssue16247/tree/min2-fix) which sets out to fix the trait code in two steps. The second commit to that branch involves just changing `trait` to `abstract class` which moves the build from broken to fixed. See the one line diff:

https://github.com/bblfish/DottyIssue16247/commit/2b2e93546a388bf850c8ced46ea558c60fa61643

**Comment by bblfish** [comment]
Actually it's interesting. The first commit creates fixes the problem on scala 3.2.1 but leaves it open in Scala nightly. 

https://github.com/bblfish/DottyIssue16247/actions/runs/3602975365/jobs/6070596212

The second change removing `trait`s entirely fixes it on nightly too.

**Comment by szymon-rd** [comment]
There is a lot of information in this post right now. Could you put a self-contained summary with the current status of minimisation with the links and all the required information to look into the problem in the issue itself? By that I mean editing it so it only contains the information that is up-to date and required to debug the issue, removing all the outdated information and other background info like history of the problem. It would be very helpful for us, and again thanks for your work minimizing and simplifying the snippets!

**Comment by bblfish** [comment]
Ok, I rewrote the original issue. I hope that is clear enough.

**Comment by szymon-rd** [comment]
Ok, so we minimized the code to this snippet:
```scala
object Helpers:

  type NodeFun[R] = Matchable

  type URIFun[R] = R match
    case GetURI[u] => u & NodeFun[R] 
  private type GetURI[U] = RDF { type URI = U }
  
end Helpers

trait RDF:
  type URI 
end RDF

trait ROps[R <: RDF]:
  def auth(uri: Helpers.URIFun[R]): String
  

object TraitRDF extends RDF:
  override type URI = TraitTypes.UriImpl

  val z = new ROps[TraitRDF.type] {
    override def auth(uri: Helpers.URIFun[TraitRDF.type]): String = ???
  }
end TraitRDF

object TraitTypes:
  trait UriImpl // doesn't compile
  // class UriImpl // compiles
```

**Comment by bblfish** [comment]
Impressive to see that further reduction :-)

**Comment by bblfish** [comment]
should one remove the tag "stat:needs minimization"?

**Comment by bblfish** [comment]
Do you have any idea yet how complicated or deep a problem this bug has uncovered? Having this added to the "Future versions" milestone sounds very open-ended :-/

**Comment by sjrd** [comment]
Minimized just a *bit* more, without requiring the `GetURI` extractor:
```scala
object Helpers:
  type NodeFun[R] = Matchable // compiles without [R] parameter

  type URIFun[R] = R match
    case RDF[u] => u & NodeFun[R]
end Helpers

trait RDF[URIParam]

trait ROps[R <: RDF[?]]:
  def auth(uri: Helpers.URIFun[R]): String

object TraitRDF extends RDF[TraitTypes.UriImpl]:
  val z = new ROps[TraitRDF.type] {
    override def auth(uri: Helpers.URIFun[TraitRDF.type]): String = ???
  }
end TraitRDF

object TraitTypes:
  trait UriImpl // doesn't compile
  //class UriImpl // compiles
```
Errors:
```
-- Error: tests/run/hello.scala:14:10 ------------------------------------------
14 |  val z = new ROps[TraitRDF.type] {
   |          ^
   |object creation impossible, since def auth(uri: Helpers.URIFun[R]): String in trait ROps is not defined 
   |(Note that
   | parameter Helpers.URIFun[R] in def auth(uri: Helpers.URIFun[R]): String in trait ROps does not match
   | parameter TraitTypes.UriImpl & Helpers.NodeFun[TraitRDF.type] in override def auth
   |  (uri: TraitTypes.UriImpl & Helpers.NodeFun[TraitRDF.type]): String in anonymous class Object with ROps[TraitRDF.type] {...} in object TraitRDF
   | )
-- [E038] Declaration Error: tests/run/hello.scala:15:17 -----------------------
15 |    override def auth(uri: Helpers.URIFun[TraitRDF.type]): String = ???
   |                 ^
   |   method auth has a different signature than the overridden declaration
   |
   | longer explanation available when compiling with `-explain`
2 errors found
```

**Comment by smarter** [comment]
If UriImpl is a trait, then `UriImpl & Object` erases to `Object` because intersection erasure prefers classes over traits, and only in case of ambiguity do we prefer subtypes over supertypes (always preferring classes is better for Java interoperability since it matches how Java intersection erasure works).

The problem is that match type reduction also performs some amount of simplification, so `UriImpl & NodeFun[TraitRDF.type]` gets simplified to `UriImpl`. I designed intersection type erasure with the assumption that we wouldn't be doing simplifications in method signatures since the simplification logic is implementation-defined, but it looks like match types violate that assumption.

**Comment by smarter** [comment]
Specifically, the culprit is the call to .simplified here:
https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L3152

**Comment by smarter** [comment]
The other piece of the puzzle here is that `.simplified` doesn't simplify intersections and unions when in Type mode: https://github.com/lampepfl/dotty/blob/b8d2966e2f45e21f2800cd125ac72d80e5f2cb2a/compiler/src/dotty/tools/dotc/core/TypeOps.scala#L158-L162

When we typecheck the `auth` override to figure out its type in Typer, `Type` is on and so we don't simplify the intersection, but when we check if its signature matches the overridden signature in RefChecks, `Type` is off and so when computing the overridden type we do simplify the intersection.

**Comment by smarter** [comment]
In other words, we might want to wrap `TypeErasure#sigName` in `withMode(Mode.Type)` to avoid simplifications that might change the signature, but we might still run into trouble if the match type reduction is cached since it doesn't look like the cache is invalidated based on modes, so it still seems like we should remove this .simplified call from the match type reduction logic.

**Comment by bblfish** [comment]
It would be great if the fix could make it into the next release, so that I can continue my work with banana-rdf. :-)

**Comment by smarter** [comment]
It's a bit awkward but you can probably work around the problem with some extra bounds and intersections with Object or Matchable, for example the following adapted from your original example compiles:
```scala
import scala.util.Try

trait RDF:
  rdf =>

  type R = rdf.type
  type Node <: Matchable
  type URI <: Node 

  given rops: ROps[R]
end RDF

object RDF:
  type Node[R <: RDF] = R match
    case GetNode[n] => Matchable //n & rNode[R]

  type URI[R <: RDF] <: Node[R] = R match
    case GetURI[u] => u & Node[R] 

  private type GetNode[N] = RDF { type Node = N }
  private type GetURI[U] = RDF { type URI = U }
end RDF

trait ROps[R <: RDF]:
  def mkUri(str: String): Try[RDF.URI[R]]
  def auth(uri: RDF.URI[R]): Try[String]

object TraitTypes:
  trait Node:
    def value: String

  trait Uri extends Node

  def mkUri(u: String): Uri =
    new Uri { def value = u }

object TraitRDF extends RDF:
  import TraitTypes as tz

  override opaque type Node <: Matchable = tz.Node
  override opaque type URI <: Node = tz.Uri

  given rops: ROps[R] with
    override def mkUri(str: String): Try[RDF.URI[R]] = Try(tz.mkUri(str))
    override def auth(uri: RDF.URI[R]): Try[String] =
      Try(java.net.URI.create(uri.value).getAuthority())

end TraitRDF

class Test[R <: RDF](using rops: ROps[R]):
  import rops.given
  lazy val uriT: Try[RDF.URI[R]] = rops.mkUri("https://bblfish.net/#i")
  lazy val x: String = "uri authority=" + uriT.map(u => rops.auth(u))

@main def run =
  val test = Test[TraitRDF.type]
  println(test.x)
```

**Comment by smarter** [comment]
(comment updated, I copy-pasted the wrong example before)

**Comment by bblfish** [comment]
The pattern that is being used here is incredibly useful to tie different libraries togeteher efficiently in a unified interface. It is needed as a replacement to type projections discussed here https://github.com/lampepfl/dotty/issues/16408

**Comment by bblfish** [comment]
It seems to be fixed now with the nightly version and I can compile the [DottyIssue16247 onepage branch](https://github.com/bblfish/DottyIssue16247/tree/onepage)
```bash
scala-cli compile -j 20 -S 3.nightly scala
```
and similarly with the [original java interface-based test](https://github.com/bblfish/DottyIssue16247/tree/main) now works with the nightly 
```bash
scala-cli --scala 3.nightly scala/RDF_Java_Interface.scala scala/RDF.scala java/testorg/*
```
and the trait based code also compiles with the nightly
```bash
scala-cli --scala 3.nightly scala/RDF_Traits.scala scala/RDF_UsingScalaTrait.scala scala/RDF.scala
```
