### ISSUE TITLE
Disallow having a value classe whose underlying value is itself

### ISSUE THREAD

**Issue by helloqirun** [lampepfl/dotty#1642]
dotc crashes when compiling the follow code. 

$ cat abc.scala

```
class Test2(val valueVal: Test2) extends AnyVal
```

$ dotc abc.scala
output:
https://gist.github.com/helloqirun/d09e36c276832140e7c74d1f26378a14

**Comment by smarter** [comment]
For very long output, you can paste them on https://gist.github.com/ and put a link in your issue.

**Comment by helloqirun** [comment]
Thanks, updated.
