### ISSUE TITLE
Scala 2 regression: False ambiguous implicit error when supertype companion includes a polymorphic instance

### ISSUE THREAD

**Issue by neko-kai** [lampepfl/dotty#16431]
## Compiler version

3.2.1 and 3.2.2-RC1

## Minimized code

https://scastie.scala-lang.org/rJ1TG8HeSgO8U2Amzt8aYg

```Scala
trait Supertype {
  def id: Int
}
object Supertype extends SupertypeLowPriorityInstances {
  implicit def supertype: Subtype = Subtype(1)
}
trait SupertypeLowPriorityInstances {
  // deleting this instance fixes the ambiguity error
  implicit def supertypeIfCondition(implicit impossible: Some[Nothing]): Supertype = Subtype(9)
}

final case class Subtype(id: Int) extends Supertype
object Subtype {
  implicit def subtype: Subtype = Subtype(2)
}

object App0 extends App {
  println(implicitly[Subtype])
}
```

## Output

```scala
Ambiguous given instances: both method subtype in object Subtype and method supertype in object Supertype match type Subtype of parameter e of method implicitly in object Predef
```

## Expectation

Expected to work, as in Scala 2: https://scastie.scala-lang.org/bwBH5zecS9OWSOwE1bfsJg

In absence of `Supertype.supertypeIfCondition` there is no ambiguity error, but it's unclear how could that instance interfere at all, given that `Subtype.subtype` is a more specific instance than both of the instances in `Supertype` companion no matter what.

The same bug also affects higher-kinded implicits.

This code is a minimized version of real library code in https://github.com/izumi/izumi which we're trying to port to Scala 3

**Comment by Kordyjan** [comment]
It is even worse. Any implicit definition in any trait that is a supertype of the `Supertype` will cause this false error.

```scala
trait Unrelated
trait Supertype

object Supertype extends SupertypeLowPriorityInstances {
  implicit def supertype: Subtype = Subtype(1)
}
trait SupertypeLowPriorityInstances {
  implicit def unrelated: Unrelated = ??? // removing this line fixes the snippet
}

final case class Subtype(id: Int) extends Supertype
object Subtype {
  implicit def subtype: Subtype = Subtype(2)
}

object App0 extends App {
  println(implicitly[Subtype])
}
```

This is not compiling now. What's even stranger is that this is a consistent behavior since 3.0.0.

**Comment by odersky** [comment]
This is actually as specified. It's a very tricky aspect of implicit inference. The previous Scala 2 rules did not produce a total order when comparing owners, which meant that the order in which implicits were considered influences results. 

The full discussion is in https://docs.scala-lang.org/scala3/reference/changed-features/implicit-resolution.html, point 8. 
The examples violate the last condition given there.

> - A and B are objects, B does not inherit any implicit members from base classes (*), and the companion class of A extends the companion class of B.
> Condition (*) is new. It is necessary to ensure that the defined relation is transitive.

As an alternative, one can base implicit prioritization on dummy implicit clauses. That's usually more robust.

**Comment by neko-kai** [comment]
@odersky 
I'm not sure I understand the example. Where the example says
```
But if we compare a with c first, we fail with an ambiguity error.
```
We would, if we compared `A.a` and `C#c`, but shouldn't we compare `A.a` and `B.c` here? Where B is a companion of a supertype, making B.c unambiguously lower in priority?

**Comment by neko-kai** [comment]
@odersky 
Ok, my understanding was wrong, we do compare `A.a` and `C#c` according to spec, since we compare owners, not prefixes. ("1 if A is *defined* in a class or object which is derived from the class or object *defining* B, 0 otherwise.")

Was there an attempt before to utilize prefixes in comparison? If we take prefixes into account, instead of just owners, then in implicit scope of `import A.*; import B.*` there are 3 implicits `A.a`, `B.b`, `B.super[C].c` where `A.a` < `B.b` due to the first clause in point (3) and `A.a` < `B.super[C].c` due to a new relative weight clause such as "1 if A is a selection p.x and the type of prefix p is a class or object derived from the type of the prefix of B". I understand that I'm not proposing a full SIP here, I won't be able to pursue a solution to this to that degree.

NOTE: We have an interesting mismatch now that prefixes contribute to the implicit scope, while owners don't (as per https://github.com/lampepfl/dotty/issues/9094), but owners contribute to the implicit priority, while prefixes don't.

**Comment by Kordyjan** [comment]
>A and B are objects, B does not inherit any implicit members from base classes (*), and the companion class of A extends the companion class of B.

I remembered this rule requiring B not to inherit implicit members with the type that we are searching for. Now I see that it literally requires B not to inherit ANY implicit members. 

I've learned something new.
