### ISSUE TITLE
Child class cannot access exported inline methods from parent class

### ISSUE THREAD

**Issue by mushtaq** [lampepfl/dotty#16469]
## Compiler version

3.2.1

## Minimized code

```Scala
//> using scala "3.2.1"

class Context {
  def normalMethod(): String = "normal"
  inline def inlineMethod(): String = "inline"
}

class Script(ctx: Context) {
  export ctx.*
  normalMethod() // works
  inlineMethod() // works
}

class MyScript(context: Context) extends Script(context) {
  normalMethod() // works
  inlineMethod() // error
}

```

## Output

```txt
Compiling project (Scala 3.2.1, JVM)
[error] ./scala/inline-export-inherit.sc:16:3: ctx cannot be accessed as a member of (Script_this : (MyScript.this : inline-export-inherit.MyScript)) from class MyScript.
[error]   inlineMethod() // error
[error]   ^^^^^^^^^^^^^^
```

## Expectation

It should compile unless the restriction is intentional. In that case, the reason should be mentioned in the docs.

Making `ctx` a `val` in `Script` constructor makes it compile.

**Comment by WojciechMazur** [comment]
It seemed to work until Scala 3.1.2
Bisect points to b3ab102ee7ee1ccf48d38345603926a2497bd372 - @bishabosha backported there changes made by @odersky in https://github.com/lampepfl/dotty/pull/14051

**Comment by nicolasstucki** [comment]
The export generates the `inlineMethod` in `Script`
```scala
fianl inline def inlineMethod(): String = Script.this.ctx.inlineMethod()
```
If we define this method manually we see that it becomes 
```scala
final inline def inlineMethod(): String = this.Script$$inline$ctx.inlineMethod():String
final def Script$$inline$ctx: Context = Script.this.ctx
```

This implies that when we generate the exports, we are not transforming the contents of the inline export accessor with `PrepareInlineable` or we are doing it wrong.

**Comment by nicolasstucki** [comment]
Half of the issue is that we need to call `registerInlineInfo` setting the `forwarder` as the context owner. The second thing is to add the inline accessors to the class.
