### ISSUE TITLE
Type inference after erasure uses package private type over public one leading to `java.lang.IllegalAccessError` at runtime

### ISSUE THREAD

**Issue by chungonn** [lampepfl/dotty#16474]
Below is a minimal code fragment to reproduce the problem. It works from Scala 3.0 to Scala 3.2.0 and it breaks with Scala 3.2.1 and Scala.3.2.2-RC1

With Scala 3.2.1, when the method jweEncrypt is invoked, it throws a java.lang.IllegalAccessError. With all versions prior to Scala 3.2.1, the method is able to be executed.

## Java Version 
Java 17

## Compiler version
Scala 3.2.1, Scala 3.2.2-RC1

## Minimized code
Change the scala3Version to 3.2.0 then run the test suite to see the expected output. 

### build.sbt
```scala
val scala3Version = "3.2.1"

lazy val root = project
  .in(file("."))
  .settings(
    name := "Test",
    version := "0.1.0-SNAPSHOT",

    scalaVersion := scala3Version,

    libraryDependencies ++= Seq(
      "com.nimbusds" % "nimbus-jose-jwt" % "9.25.6",
      "org.scalameta" %% "munit" % "0.7.29" % Test
    )
  )

```

### MySuite.scala
```scala
class MySuite extends munit.FunSuite {

  def jweEncrypter(publicJwk: JWK): Try[JWEEncrypter] = Try {
    publicJwk match
      case rsa: RSAKey => new RSAEncrypter(rsa)
      case ec: ECKey => new ECDHEncrypter(ec)
      case _ => throw new RuntimeException(s"Unsupported jwk ${publicJwk}")
  }

  test("JWS signing and verify using private cert pem file") {
    val jwkTry = jweEncrypter(null)
    println(s"jwkTry = ${jwkTry}")
  }
}
```

## Output

```scala
Testing started at 3:22 pm ...

Process finished with exit code 255

java.lang.IllegalAccessError: failed to access class com.nimbusds.jose.crypto.impl.BaseJWEProvider from class MySuite (com.nimbusds.jose.crypto.impl.BaseJWEProvider and MySuite are in unnamed module of loader 'app')

	at MySuite.jweEncrypter(MySuite.scala:14)
	at MySuite.$init$$$anonfun$1(MySuite.scala:17)
```

## Expectation
```scala
Testing started at 3:26 pm ...
jwkTry = Failure(java.lang.RuntimeException: Unsupported jwk null)

Process finished with exit code 0
```

**Comment by chungonn** [comment]
I have a simple test project for the above code, I can upload it if required.

**Comment by WojciechMazur** [comment]
Thank you for this report, I've managed to reproduce it locally. It seems to be a regression introduced since 3.2.0. I'll try to provide dependency free minimization soon

**Comment by WojciechMazur** [comment]
Reproducer


```java
// Encrypter.java
package repro;
public interface Encrypter{}
```

```java
// BaseProvider.java
package repro.impl;

import repro.*;
abstract class BaseProvider{}
```

```java
// Case1Provider.java
package repro.impl;

public abstract class Case1Provider extends BaseProvider {}
```

```java
// Case1.java
package repro;

import repro.impl.*;

public class Case1 extends Case1Provider implements Encrypter {
  public Case1(){}
}

**Comment by WojciechMazur** [comment]
One notable difference between 3.2.0 and 3.2.1 is the type infereded for anonymous function of method `get`  after erasure phase. 
In bytecode of 3.2.1 we have signature: 
```java
  private final repro.impl.BaseProvider get$$anonfun$1(java.lang.Object);
```

in 3.2.0 it was :
```java
  private final repro.Encrypter get$$anonfun$1(java.lang.Object);
```

In case if both classes `Case1` and `Case2` would not inherit from a common public ancestor then signature of `get$$anonfun$1` would be inferred to java package private `final repro.impl.BaseProvider` and though would always lead to IllegalAccessException in runtime. 

At the time of typer phase anonfun in inferred to be `(repro.impl.BaseProvider & repro.Encrypter`

**Comment by WojciechMazur** [comment]
Bisect points to 824496b805f31a9c8c2b20a8d375429b8f02ab75

**Comment by odersky** [comment]
I don't think https://github.com/lampepfl/dotty/commit/824496b805f31a9c8c2b20a8d375429b8f02ab75 introduced that problem  but maybe it was hidden by some obscure type inference difference before.
