### ISSUE TITLE
Singleton type of context function

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#16488]
## Compiler version

3.2.1

## Minimized code

```scala
trait Ctx
val f: Ctx ?=> Int = ???
def g: f.type = f
```

## Output

```scala
-- [E172] Type Error: ----------------------------------------------------------
3 |def g: f.type = f
  |        ^
  |    No given instance of type Ctx was found for parameter of (Ctx) ?=> Int
-- [E172] Type Error: ----------------------------------------------------------
3 |def g: f.type = f
  |                 ^
  |    No given instance of type Ctx was found for parameter of (Ctx) ?=> Int
```

## Expectation

This should compile as it does for non-singleton context function types, e.g.
```scala
trait Ctx
val f: Ctx ?=> Int = ???
def g: Ctx ?=> Int = f
```
and singleton non-contextual function types, e.g.
```scala
trait Ctx
val f: Ctx => Int = ???
def g: f.type = f
```

**Comment by odersky** [comment]
I think that's out of scope. We need an explicit `Ctx` context parameter.

**Comment by prolativ** [comment]
Then should at least this work?
```scala
trait Ctx
val f: Ctx ?=> Int = ???
def g: f.type = (ctx: Ctx) ?=> f
```
Because it doesn't. Although it raises one compiler error less

**Comment by odersky** [comment]
No that should not work either. You create a new closure, which is different from `f`.

**Comment by prolativ** [comment]
Is there any way to refer to the exact type of a given context function then?
It seems quite strange to me that a context function tries to get applied even if we refer to it only in the context of types
```scala
trait Ctx
val f: Ctx ?=> Int = ???
type Tpe = f.type
```

```scala
-- Error:
3 |type Tpe = f.type
  |            ^
  | no implicit argument of type Ctx was found for parameter of (Ctx) ?=> Int
```

```scala
trait Ctx
val f: Ctx ?=> Int = ???
given Ctx with {}
type Tpe = f.type
```

```scala
-- Error:
4 |type Tpe = f.type
  |           ^^^^^^
  |      Int is not a valid singleton type, since it is not an immutable path
```

**Comment by odersky** [comment]
> It seems quite strange to me that a context function tries to get applied even if we refer to it only in the context of types

Yes, that's a bug. Should be easy to fix.
