### ISSUE TITLE
Investigate making 'nextPhase' default period for Tree transformations

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#165]
If the phase is an info transformer in most cases it will transform the tree at 'nextPhase' in order to have info transformation already performed.
It feels like making all tree transformations run at  'nextPhase' a default should break phases that do not introduce info transformers. 
If so, than a bit of naming change would simplify that sheme a lot: we can just say that current 'nextPhase' should actually be a period of current phase, effectively shifting all periods by one.

**Comment by smarter** [comment]
This has been the case for a while now, unless I'm misunderstanding the issue.
