### ISSUE TITLE
StackOverflowError when compiling on a GitHub runner

### ISSUE THREAD

**Issue by OndrejSpanel** [lampepfl/dotty#16548]
## Compiler version

3.2.1

## Minimized code

Unfortunately I do not have a minimized code yet. The projects consists of 400 source files at the moment. The error does not happen on my computer, only on a GitHub runner, therefore reducing the project is not exactly easy, The project is working fine in Scala 2.13 and I am porting it to Scala 3.

## Output (click arrow to expand)

Error callstack is:
<details>
java.lang.StackOverflowError
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:79)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:149)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:61)
dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.loop$2(tpd.scala:1225)
dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformStats(tpd.scala:1225)
dotty.tools.dotc.ast.tpd$TreeMapWithPreciseStatContexts.transformBlock(tpd.scala:1230)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1426)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:49)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:79)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:132)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:61)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1446)
dotty.tools.dotc.ast.TreeMapWithImplicits.transform(TreeMapWithImplicits.scala:73)
dotty.tools.dotc.transform.TreeMapWithStages.mapOverTree$1(TreeMapWithStages.scala:79)
dotty.tools.dotc.transform.TreeMapWithStages.transform(TreeMapWithStages.scala:149)
dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:61)
dotty.tools.dotc.ast.Trees$Instance$TreeMap.transform(Trees.scala:1446)
</details>

If there is any hint about what kind of code could cause an issue like this, or what to look for, I will try to find more and post it here.

**Comment by OndrejSpanel** [comment]
Similar to #15845, what I find a concern is the fact I am not told anything useful about what is causing the error - what file, symbol or language construct is the error related to.

**Comment by nicolasstucki** [comment]
> dotty.tools.dotc.transform.PCPCheckAndHeal.transform(PCPCheckAndHeal.scala:61)

Based on the stack I can tell that this is happening when compiling a quote.  Or maybe the top level splice of an inline macro definition.

I would try to compile individually each `'{... ${ ...} ...}` to see which one triggers the issue.

**Comment by OndrejSpanel** [comment]
Thanks for the hint. It must be some library causing this then, as I do not use quotes or macros directly in my project.

**Comment by OndrejSpanel** [comment]
It seems Borer decoder derivation for one particular case class is triggering the issue. I will try to pinpoint the problem and hopefully I might be able to find an isolated repro.

**Comment by OndrejSpanel** [comment]
It seems the reason why it fails on GitHub runner and not on my Windows machine is a different stack size used by JVM by default. When I use `SBT_OPTS: -Xss1M` on the runner, it does not fail any more. On the other hand it fails on my Windows machine with the same call-stack when I specify `set SBT_OPTS="-Xss700k"`.

This probably means there is not really an infinite recursion, only a very deep one.

**Comment by OndrejSpanel** [comment]
With -Xss500k I was able to create a repro with about 60 lines, see https://github.com/OndrejSpanel/borerScala3Error/blob/master/src/main/scala/com/github/ondrejspanel/borer/S.scala

I have posted more details in https://github.com/sirthias/borer/issues/608, as I am not sure if this is more a Borer or Scala 3 issue. The function `PCPCheckAndHeal.transform` nesting depth is over 100, which seems a lot to me, given the classes seems quite simple.

Borer encoder derivation code can be seen at https://github.com/sirthias/borer/blob/master/derivation/src/main/scala/io/bullet/borer/derivation/MapBasedCodecs.scala

**Comment by nicolasstucki** [comment]
We need a self-contained version of the code that fails (even if it is not minimal).

**Comment by OndrejSpanel** [comment]
This is well out of area of my abilities.

@sirthias might have an opinion on whether this is something worth investigating on Scala 3 end, and if it is, what could the repro be.

**Comment by SethTisue** [comment]
Clarification question: does the problem go away if you give the compiler more stack? Because it's normal that the compiler may need more the default stack size (which varies and is sometimes rather small) to compile some kinds of code.

**Comment by OndrejSpanel** [comment]
Yes, if you give more stack, the problem goes away.

**Comment by sirthias** [comment]
As I already said in https://github.com/sirthias/borer/issues/608 I think this problem isn't a Scala issue but rather an artifact of how the _borer_ macros currently generate the derivation code.
Looking at the problem again today I had an idea of how to fix the issue on the _borer_ side.
I'll follow up on the thread of the https://github.com/sirthias/borer/issues/608 ticket.

From my perspective there is nothing to do here from the Scala compiler team...
