### ISSUE TITLE
Inlined implicit method arguments are no longer treated as an immutable path

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#16554]
## Compiler version
3.3.0-RC1-bin-20221215-ef653b6-NIGHTLY

Bisect points to 77a8902c52207a88d0c3cc452941b5781378d0e9

Regression found in the Open CB, list of affected projects: 
* argonaut-io/argonaut [Open CB #29520](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/29520/)
* armanbilge/circe [Open CB #29322](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/29322/)
* circe/circe [Open CB #29325](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/29325/)
* itv/quartz4s [Open CB #30010](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/30010/)
* y-yu/excel-reads [Open CB #29852](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/29852/)
* zio/zio  [Open CB #29174](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/29174/)
* giiita/refuel [Open CB #29705](https://scala3.westeurope.cloudapp.azure.com/job/buildCommunityProject/29705/)

## Minimized code

```scala
import scala.deriving.Mirror

inline def fails[A](using inline AP: Mirror.ProductOf[A]) =
  type X = AP.MirroredElemTypes
```

Works when AP is not inlined or in 
```scala
inline def fails[A](using inline AP: Mirror.ProductOf[A]) =
  inline val ap = summon[Mirror.ProductOf[A]]
  type X = ap.MirroredElemTypes
```

## Output

```scala
[error] test.scala:4:12: (AP : deriving.Mirror.ProductOf[A]) is not a valid type prefix, since it is not an immutable path
[error]   type X = AP.MirroredElemTypes
[error]            ^^
```

## Expectation
Should compile

**Comment by Adam-Vandervorst** [comment]
How can this be solved or circumvented? How was it handled in circe or zio? This prevents 3 of my clients' projects to move to 3.3.

**Comment by SethTisue** [comment]
(I'm not in a position to answer more generally, but:)

it appears that circe hasn't dealt with it at all: https://github.com/circe/circe/pull/2146

the zio/zio PR with the 3.3.0 upgrade is https://github.com/zio/zio/pull/8165 ; it isn't obvious to me at a glance which of the diffs might be relevant

the argonaut PR with the 3.3.0 upgrade is https://github.com/argonaut-io/argonaut/pull/739 which has no code changes at all, not sure what to make of that, maybe different branch?
