### ISSUE TITLE
Can't call `._1`  on values inferred by a GADT match to be a tuple

### ISSUE THREAD

**Issue by felher** [lampepfl/dotty#16590]
## Compiler version

3.2.1

## Minimized code

```scala
enum Tag[A]:
  case MyTuple extends Tag[(String, String)]

def printIt[A](t: Tag[A], a: A): Unit =
  t match
    case Tag.MyTuple => println(a._1)
```

## Output

```
value _1 is not a member of A
where:    A is a type in method printIt with bounds >: (String, String) and <: (String, String)
```

## Expectation

Should compile fine, since the compiler knows that it is ` <: (String, String)` and `(String, String)` should have `_1`. FWIW, annotating the type works. I.e. 

```scala
    case Tag.MyTuple => println((a: (String, String))._1)
```
compiles fine.

## Scastie Link:

https://scastie.scala-lang.org/4sovEbRjTJOlv0g5WNEUTw

**Comment by SethTisue** [comment]
Looking at this with Dale.

Both the case class representation and the generic representation of 2-tuple print as `(String, String)` – if you change that so they print differently, you find that the lower bound is the `Tuple2` case class but the upper bound is the generic version.
