### ISSUE TITLE
Extension methods don't get resolved on type inferred by GADT matching

### ISSUE THREAD

**Issue by felher** [lampepfl/dotty#16603]
## Compiler version

3.2.1

## Minimized code

```Scala
trait MyData

object MyData:
  extension (m: MyData)
    def printIt() = println("hey from my data")

enum MyTag[A]:
  case MyDataTag extends MyTag[MyData]


def callExtension[A](tag: MyTag[A], a:A): Unit =
  tag match
    case MyTag.MyDataTag => a.printIt()
```

## Output

Compiler error:
```
value printIt is not a member of A, but could be made available as an extension method.
```

## Expectation

Should compile fine. If you annotate the type it does compile. I.e. `(a: MyData).printIt()` works like a charm. 
Maybe related to #16590 ?

## Scastie Link

https://scastie.scala-lang.org/xUDIWg9zSje6JqPNbkiuHg

**Comment by SethTisue** [comment]
> Maybe related to https://github.com/lampepfl/dotty/issues/16590 ?

That one _looks_ tuple-specific, but after we fix this one, it'll be worth checking if that other one progresses.

**Comment by SethTisue** [comment]
> after we fix this one, it'll be worth checking if that other one progresses

no change
