### ISSUE TITLE
Wrong error message when instantiating a trait from scala 2.13 stdlib

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#16601]
## Compiler version

3.2.1 and before

## Minimized code

```scala
new concurrent.ExecutionContext
```

## Output

```scala
-- [E042] Type Error: ----------------------------------------------------------
1 |new concurrent.ExecutionContext
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |    Unit is abstract; it cannot be instantiated
  |
  | longer explanation available when compiling with `-explain`
```

With `-explain` enabled:

```scala
-- [E042] Type Error: ----------------------------------------------------------
1 |new concurrent.ExecutionContext
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |    Unit is abstract; it cannot be instantiated
  |-----------------------------------------------------------------------------
  | Explanation (enabled by `-explain`)
  |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  | Abstract classes and traits need to be extended by a concrete class or object
  | to make their functionality accessible.
  |
  | You may want to create an anonymous class extending Unit with
  |   class Unit { }
  |
  | or add a companion object with
  |   object Unit extends Unit
  |
  | You need to implement any abstract members in both cases.
   -----------------------------------------------------------------------------
```

## Expectation

The actual name of the instantiated trait (e.g. `ExecutionContext` in the example above) should be displayed instead of `Unit`.

**Comment by yzia2000** [comment]
Interesting. I haven't tried diagnosing a whole lot but so far I see this happening with Scala 2 traits while the Scala 3 traits I am creating are working fine. Can I take this up?

**Comment by yzia2000** [comment]
Hi I would like to tackle this issue. It seems that scala 2 symbols passed into `checkInstantiable` is `Unit` while scala 3 has the right symbol.

Since this is my first dotty issue, @prolativ may I know why this issue was marked as `good-first-issue`? Have we dealt with such cases in the past?

**Comment by nizhikov** [comment]
Hello. I prepared PR to fix this - https://github.com/lampepfl/dotty/pull/16635

**Comment by nizhikov** [comment]
@prolativ Can you, please, help me. What is the next steps to get this fix merged?

**Comment by yzia2000** [comment]
Hey @nizhikov, why is it that the symbol in `Apply` type (`tree.tpe`) has the right name for Scala 3 but not for Scala 2? While the symbol in `New` (nu.tpe) does have the right symbol in it?
