### ISSUE TITLE
Scaladoc: Package names do not nest in left panel

### ISSUE THREAD

**Issue by aschweig** [lampepfl/dotty#16620]
I think the list of packages in the left panel [should "nest" as seen here.](https://www.scala-lang.org/api/3.2.1/scala/collection/immutable.html) Instead I get a list of each package in the project:

![image](https://user-images.githubusercontent.com/958887/210800291-9b3828fe-229d-4159-974b-2051e8b053b6.png)

Here's the steps I took to generate the above:
```
echo "foo" | sbt new scala/scala3.g8
cd foo
rm src/main/scala/Main.scala # clean up stuff from g8
rm -rf src/test # ... so there's no confusion
# Maven source layout
mkdir -p src/main/scala/com/companyname/module1
mkdir -p src/main/scala/com/companyname/module2/sub
(echo "package com.companyname.module1"; echo "trait Module1 { def fooer():Unit }") > src/main/scala/com/companyname/module1/Module1.scala
(echo "package com.companyname.module2"; echo "trait Module2 { def fooer():Unit }") > src/main/scala/com/companyname/module2/Module2.scala
(echo "package com.companyname.module2.sub"; echo "trait Module2b { def fooer():Unit }") > src/main/scala/com/companyname/module2/sub/Module2b.scala
#sbt doc # same behavior as below
sbt compile
mkdir html
scaladoc -d html -skip-by-id:com.companyname `find target/ -type f -name '*.tasty'`
```

[There is a discussion on Scala users that explores this a bit further.](https://users.scala-lang.org/t/scaladoc-shortern-package-names/9057)

I am unclear if this scaladoc behavior is expected or not given the setup above.

I am running scaladoc version 3.2.1.

**Comment by prolativ** [comment]
You should get the new behaviour with nested packages with a newer version of the compiler (3.2.2-RC2 or a nightly release)
