### ISSUE TITLE
if else identation error (scala 3)

### ISSUE THREAD

**Issue by firephil** [lampepfl/dotty#16633]
## Minimized code

```Scala
def tailRecBig(n : BigInt) : BigInt = 
	  
	 @tailrec
        def aux(n : BigInt, acc :BigInt) :BigInt = 
	
            if(n == 0) acc
	    else aux(n-1, acc * n)
	     
	   aux(n,1)   
```

I get identation Error, if we ident the else expression to belong to the if expression error is gone.

```Scala
if(n == 0) acc
   else aux(n-1, acc * n)
```

Maybe it is a feature to empasize that the else belongs to the if expression but it is slightly confusing.
- I suspect it is a Metals bug. 
- The compiler doesnt like different styles of identation, tabs or spaces when i was trying to convert old scala2 code.

IT should't matter if it is 4 spaces or 1 tab etc

**Comment by som-snytt** [comment]
Adding spaces at the `else` does not change these errors:
```
-- Error: i16633.scala:7:8 ---------------------------------------------------------------------------------------------
7 |        def aux(n : BigInt, acc :BigInt) :BigInt =
  |        ^
  |        Incompatible combinations of tabs and spaces in indentation prefixes.
  |        Previous indent : 1 tab, 1 space
  |        Latest indent   : 8 spaces
-- Error: i16633.scala:9:12 --------------------------------------------------------------------------------------------
9 |            if(n == 0) acc
  |            ^
  |            Incompatible combinations of tabs and spaces in indentation prefixes.
  |            Previous indent : 1 tab, 1 space
  |            Latest indent   : 12 spaces
2 errors found
```
The compiler accepts common prefixes. 

https://dotty.epfl.ch/docs/reference/other-new-features/indentation.html#indentation-and-braces

**Comment by prolativ** [comment]
As mentioned in the docs tabs and spaces are incomparable so they cannot be mixed as in the snippet above
