### ISSUE TITLE
Compiler produces incorrect/incomplete coverage data

### ISSUE THREAD

**Issue by rolandtritsch** [lampepfl/dotty#16634]
See also - https://github.com/scoverage/sbt-scoverage-samples/issues/28

## Compiler version

3.2.2-RC2

## Minimised code

See issue above.

To reproduce run `sbt +clean +coverage +test +coverageReport` on `sbt-scoverage-samples`.

## Output

See issue above. Output for scala3 is incorrect.

![incorrect](https://user-images.githubusercontent.com/671381/210720187-4a54438d-9b20-4ba7-863f-c52b7f106692.png)

## Expectation

Generated scala3 `scoverage.coverage` data should (roughly) equal the scala2 coverage data.

## Next step(s)

* Can you verify/confirm that this is not a known issue
* (Optional; if needed) Make the test case smaller (@rolandtritsch)

**Comment by vijaykramesh** [comment]
Likely related to https://github.com/scoverage/sbt-scoverage/issues/382 as well as https://github.com/scoverage/sbt-scoverage/issues/458

**Comment by vijaykramesh** [comment]
https://github.com/vijaykramesh/dotty/pull/1 demonstrates the issue pretty clearly by adding an additional coverage test
