### ISSUE TITLE
`-Wunused:all` and nested type class derivation

### ISSUE THREAD

**Issue by amumurst** [lampepfl/dotty#16679]
I tried adding the new unused flag (from https://github.com/lampepfl/dotty/pull/16157) to my work codebase and was surprised that it warned about unused import when used with the json library `circe`s derivation of json Encoders from case classes. (` case class Foo(i: Int) derives Encoder.AsObject`). A minimal reproducer independent of circe is below. I see no error when trying to derive the "top level" typeclass and not a subtype.

## Compiler version
With nightly: `3.3.0-RC1-bin-20230112-be10bc6-NIGHTLY`

## Minimized code
```scala
//> using scala "3.3.0-RC1-bin-20230112-be10bc6-NIGHTLY"
//> using option "-Wunused:all"

object myPackage:
   trait CaseClassName[A]:
      def name: String

   object CaseClassName:
      trait CaseClassByStringName[A] extends CaseClassName[A]
      import scala.deriving.Mirror
      object CaseClassByStringName:
         inline final def derived[A](using inline A: Mirror.Of[A]): CaseClassByStringName[A] = 
            new CaseClassByStringName[A]:
               def name: String = A.toString

import myPackage.CaseClassName
case class CoolClass(i: Int) derives CaseClassName.CaseClassByStringName
println(summon[CaseClassName[CoolClass]].name)
```

## Output

```scala
[warn] ./unused-typeclass-derivation.sc:16:18: unused import
[warn] import myPackage.CaseClassName
[warn]                  ^^^^^^^^^^^^^
```

## Expectation
The import is needed and used 2 places (at the summon and at the derives), so no warn should be provided.

**Comment by PaulCoral** [comment]
Thanks for reporting all this `-Wunused` issue, @amumurst !

>  I see no error when trying to derive the "top level" typeclass and not a subtype.

Can you give me a code example of this. It would help me a lot debuging this. I do not really understand what you meant here.

**Comment by amumurst** [comment]
Just that this does not give a warning where there is no subtype.
```scala
object myPackage:
   trait CaseClassName[A]:
      def name: String

   object CaseClassName:
      import scala.deriving.Mirror
      inline final def derived[A](using inline A: Mirror.Of[A]): CaseClassName[A] = 
         new CaseClassName[A]:
            def name: String = A.toString

import myPackage.CaseClassName
case class CoolClass(i: Int) derives CaseClassName
println(summon[myPackage.CaseClassName[CoolClass]].name)
```

But I see now that its not really that relevant. This also fails, so its more about `derives X.Y` than anything specific.
## Re spec

```scala
object myPackage:
   object Foo:
      trait CaseClassName[A]:
         def name: String

      object CaseClassName:
         import scala.deriving.Mirror
         inline final def derived[A](using inline A: Mirror.Of[A]): CaseClassName[A] = 
            new CaseClassName[A]:
               def name: String = A.toString
```

With this setup

This fails
```scala
import myPackage.Foo
case class CoolClass(i: Int) derives Foo.CaseClassName
println(summon[Foo.CaseClassName[CoolClass]].name)
```

But this works
```scala
import myPackage.Foo.CaseClassName
case class CoolClass(i: Int) derives CaseClassName
println(summon[CaseClassName[CoolClass]].name)
```

**Comment by ivan-klass** [comment]
Nested term selection is not required to be after `derives` to reproduce, if import from an object directly, false-positive is still there:
```scala
package example

import io.circe.Encoder.{AsObject => ToJson}

case class Foo(bar: String, baz: Int) derives ToJson
```

```
[warn] 3 |import io.circe.Encoder.{AsObject => ToJson}
[warn]   |                         ^^^^^^^^^^^^^^^^^^
[warn]   |                         unused import

```

**Comment by amumurst** [comment]
Aha, my minimised example picked it up as used since it was used in the `summon` 🤦 @PaulCoral

**Comment by szymon-rd** [comment]
@ivan-klass thanks for your observations, I am looking into it right now.

**Comment by szymon-rd** [comment]
The reason behind this issue was the way the Indents were generated in the derived code. If you wrote:
```scala
object Foo:
   object Bar

Foo.Bar
```
Then, Indents for both `Foo` and `Bar` would appear in the AST. However, in the derived code, only `Foo$.Bar` appeared. What's more, the name had to be treated a bit differently (ignored) to accommodate for the usage of the module class (name with `$` sign).
