### ISSUE TITLE
`-Wunused:all` and private case class constructors

### ISSUE THREAD

**Issue by amumurst** [lampepfl/dotty#16675]
I tried adding the new unused flag (from https://github.com/lampepfl/dotty/pull/16157) to my work codebase and was surprised it hit places where private constructors were used to prevent creation of invalid case classes.

## Compiler version
With nightly: `3.3.0-RC1-bin-20230112-be10bc6-NIGHTLY`

## Minimized code

```scala
//> using scala "3.3.0-RC1-bin-20230112-be10bc6-NIGHTLY"
//> using option "-Wunused:all"

case class PositiveNumber private (i: Int)
object PositiveNumber:
  def make(i: Int): Option[PositiveNumber] = 
    Option.when(i >= 0)(PositiveNumber(i))

PositiveNumber.make(1).foreach(n => println(n.i))
```

## Output

```scala
[warn] ./unused-private-constructor.sc:4:1: unused private member
[warn] case class PositiveNumber private (i: Int)
[warn] ^
[warn] ./unused-private-constructor.sc:4:26: unused private member
[warn] case class PositiveNumber private (i: Int)
[warn]                          ^^^^
[warn] ./unused-private-constructor.sc:4:42: unused private member
[warn] case class PositiveNumber private (i: Int)
[warn]                                          ^
```

## Expectation
I would expect that the autogenerated private methods of a case class were not warned about since I have no way of removing that warning as an end user.

**Comment by szymon-rd** [comment]
@PaulCoral could you take a look? Do you know what is causing this?

**Comment by PaulCoral** [comment]
@szymon-rd I added a fix #16683.

**Comment by szymon-rd** [comment]
@PaulCoral have you seen all the other issues? It seems that there are a lot of edge cases. We are running the open cb on with this flag now, maybe we will find more.

**Comment by PaulCoral** [comment]
@szymon-rd Yes, I'm already on the next one.
