### ISSUE TITLE
Docs - html page have no encoding

### ISSUE THREAD

**Issue by dos65** [lampepfl/dotty#1668]
For example [here](http://dotty.epfl.ch/docs/internals/contexts.html) at bottom of context's internals list occurs invalid characters

**Comment by felixmulder** [comment]
You're more than welcome to fix this :)

**Comment by felixmulder** [comment]
Probably here somewhere: https://github.com/lampepfl/dotty/blob/master/docs/_layouts/default.html

**Comment by dos65** [comment]
Ok - will do
