### ISSUE TITLE
[cc] Wrong inferred type 

### ISSUE THREAD

**Issue by yawen-guan** [lampepfl/dotty#16686]
## Compiler version

3.2.2-RC1

## Minimized code

```Scala
class A (v: Int = 0) { self: {*} A => }

class B (a: {*} A) {}

val a = new A(0)
val b: {a} B = new B(a)
```

or an equivalent implementation:
```Scala
class A private (v: Int = 0) {}

object A {
  def apply(v: Int): {*} A = new A(v)
}

class B (a: {*} A) {}

val a = A(0)
val b: {a} B = new B(a)
```

## Output

In both implementation, an error is reported:

```scala
36 |    val b: {a} B = new B(a)
   |            ^^^^
   |         (a : ? Main.A) cannot be tracked since its capture set is empty
```

## Expectation

They're expected to pass.

**Comment by odersky** [comment]
Self-contained example:
```scala
import language.experimental.captureChecking
class A (v: Int = 0) { self: {*} A => }

class B (a: {*} A) {}

def test() =
  val a = new A(0)
  val b: {a} B = new B(a)
```
I believe the compiler is correct. `new A(0)` is of type `A`, with empty capture set. The self type `{ self: {*} A => }` only
determines what possible subclasses of `A` can capture. It does not add a capture set to instances of `A`.
