### ISSUE TITLE
scaladoc -no-link-warnings does not work

### ISSUE THREAD

**Issue by alanbur** [lampepfl/dotty#16694]
Scaladoc version 3.2.1 -- Copyright 2002-2022, LAMP/EPFL

If the `--no-link-warnings` flag is used, it does not suppress link warnings,

    [warn] -- Warning: static_site/_docs/index.md -----------------------------------------
    [warn] /home/foo/static_site/_docs/index.md: Unable to resolve link '../foo/bar/SomeClass.html

**Comment by ckipp01** [comment]
So I think there is a bit of confusion here. Looking at the actual [description](https://github.com/lampepfl/dotty/blob/cabfa68927445f5a1bf09167b2daeafb4e0bc701/scaladoc/src/dotty/tools/scaladoc/ScaladocSettings.scala#L99) you see:

>     "Avoid warnings for ambiguous and incorrect links in members look up. Doesn't affect warnings for incorrect links of assets etc.",

So it's actually not meant to be applied in this way. Although the overloading here is confusing. I see that #17028 does provide a fix for this, but probably not the way we want to do this. There is a few different things we could do here:

- Do we expand the meaning of this flag to also warn about actual dead links in assets/pages?
- Do we introduce another new flag to silence these?
