### ISSUE TITLE
Unqualified private in package object is accessible

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#16702]
## Compiler version

3.2.1

## Minimized code

```Scala
package com

package example {
  private object Test {
    def foobar: String = example.bar   // not a usage
    def detest = example.Detest        // not a usage
  }
}
package object example {
  private def bar: String = "bar"
  private[example] def barNone: String = "bar"   // not unqualified private

  private object Detest
}
```

## Output

Compiles in Scala 3.

Scala 2 says:
```scala
po.scala:5: error: object bar is not a member of package com.example
    def foobar: String = example.bar   // not a usage
                                 ^
po.scala:6: error: object Detest is not a member of package com.example
    def detest = example.Detest        // not a usage
                         ^
2 errors
```

## Expectation

Private member of package object is private to the object, not to the package.

This is Scala 2 test `test/files/neg/t11681.scala`.

**Comment by odersky** [comment]
Given that package objects have been superseded by toplevel definitions, there's probably no good reason to keep them around for much longer, except to support legacy code. And private in toplevel definitions does mean private to the whole package. So the question is whether we want to cause an incompatibility between the two versions of "package object" now, vs cause an incompatibility between Scala 2 and Scala 3.

**Comment by som-snytt** [comment]
Probably close this as documentary only.
