### ISSUE TITLE
Cannot summon `FromExpr[T]` in macro if `T` is generic in the macro definition

### ISSUE THREAD

**Issue by hmf** [lampepfl/dotty#16738]
## Compiler version

Version 3.2.1

## Minimized example

My goal is to process a constant data structure with a narrowed type. In this case an HList. I have been at this for some time now and tried to get an answer for the more simple case of a `Tuple2`. I have asked [here](https://users.scala-lang.org/t/scala-3-macros-how-can-i-use-a-fromexpr-in-a-macro/9074), [here](https://discord.com/channels/632150470000902164/875868146949554207/1063820304566198312) and [here](https://github.com/lampepfl/dotty/discussions/16726). I am using the following code for my tests (based on Scala's `FromExpr[Either[_,_]]]`):

```Scala
import scala.quoted.*
import scala.compiletime.*
import scala.annotation.showAsInfix

object From: 
  sealed trait IMap
  case object IEmpT extends IMap
  case class ICons[K, V, T <: IMap](key: K, value: V, tail: T) extends IMap

  type IEmpT = IEmpT.type
  
  @showAsInfix
  type -:[K,V,T<:IMap] = ICons[K,V,T] 

  extension [K,V,T <: IMap] (a: (K,V)) def -: (t: T): ICons[K,V,T] =
    ICons(a._1, a._2, t)

  object -: {
    def unapply[K, V, T <: IMap](x: -:[K,V,T]): (K, V, T) = (x.key, x.value, x.tail)
  }

  given IMapFromExpr[K, V, TL <: IMap](using Type[K], Type[V], Type[TL], FromExpr[K], FromExpr[V], FromExpr[TL]): 
                    FromExpr[IMap] with {
    def unapply(x: Expr[IMap])(using Quotes): Option[IMap] = x match {
      case '{ $x: IEmpT } => 
        x.value        
      case '{ ${Expr(x)}: ICons[K, V, TL] } => 
        Some(x)
      case _ => None
    }
  }

  
  given IEmpTFromExpr: FromExpr[IEmpT] with
    def unapply(x: Expr[IEmpT])(using Quotes): Option[IEmpT] = 
      x match
        case '{ IEmpT } => 
          Some[IEmpT](IEmpT)
        case _ => 
          None
    
  

  given IConsFromExpr[K: Type : FromExpr, V: Type : FromExpr, T <: IMap](using Type[T], FromExpr[T]): FromExpr[ICons[K,V,T]] with 

    def unapply(x: Expr[ICons[K,V,T]])(using Quotes): Option[ICons[K,V,T]] = 
      x match 
        case '{ICons[K,V,T](${Expr(k)}, ${Expr(v)}, ${Expr(tl)}) } => 
          Some(ICons(k,v,tl))
        case _ => 
          None

  inline def testT2M[T1 <: IMap](x: T1): Unit = ${testT2MImpl[T1]('x)}

  def testT2MImpl[T1: Type](x: Expr[T1])(using Quotes): Expr[Unit] = {
    val v = Expr.summon[FromExpr[T1]]
    println(s"v.isDefined = ${v.isDefined}")
    println(s"x.show = ${x.show}")
    '{()}
  } 

end From
```

Code [is in scastie](https://scastie.scala-lang.org/VehBpdIhQPiVBfIpBvA1ZQ).

## Output

I use the following test:

```scala
    From.testT2M(From.IEmpT)
    From.testT2M(From.ICons("5", "5", From.IEmpT))
```

and get the following output:

```
v.isDefined = true
x.show = From.IEmpT
v.isDefined = false
x.show = x$proxy43
```

And the test with the `Tuple2`:

```scala 
    From.testT2E((1,1))
```
also fails with:

```
v.isDefined = false
x.show = x$proxy41
```

## Expectation

I would expect ([if I understood correctly](https://github.com/lampepfl/dotty/discussions/16726)), to be able to access the  `HList` (or Tuple's) values. I have tried many variations and done many additional experiments, but cannot seem to crack it. Is this possible?

**Comment by hmf** [comment]
I would like to point out that the more fundamental issue of getting a usable `FromExpr[_]` may also have some bearing on this question. This issue has also been encountered by others. I have found [example 1](https://www.reddit.com/r/scala/comments/rkj8dh/ambiguous_implicit_arguments_when_using_fromexprt/) and [example 2](https://users.scala-lang.org/t/wrong-level-staging-when-quoting-in-macro/7469)  of such cases.

**Comment by nicolasstucki** [comment]
The first problem I see is that we are not looking at the input `IMap` argument in all cases. In some cases (when not pure) we have the by-value binding generated. The solution is to inline the argument.

```diff
-  inline def testT2M[T1 <: IMap](x: T1): Unit = ${testT2MImpl[T1]('x)}
+  inline def testT2M[T1 <: IMap](inline x: T1): Unit = ${testT2MImpl[T1]('x)}
```

**Comment by nicolasstucki** [comment]
The second issue is that in the macro implementation, we are attempting to get a statically known `FromExpr[T]` but at the same time we are trying to make `T` generic. We also can not get the `FromExpr[T]` from the signature of the macro because it would not be stage consistent.

This will not be supported in this form.

#### Alternative 1
Use a custom `IMap` extractor that only works for a subset of type of keys and values (for example only for constants).
```scala
  inline def testT2M(inline x: IMap): Unit = ${testT2MImpl('x)}

  def testT2MImpl(x: Expr[IMap])(using Quotes): Expr[Unit] = {
    println(x.show)
    println(valueOfIMap(x))

    println(s"x.show = ${x.show}")
    println(s"valueOfIMap(x) = ${valueOfIMap(x)}")
    '{()}
  }

  def valueOfIMap(x: Expr[IMap])(using Quotes): Option[IMap] =
    x match
      case '{ IEmpT } => Some(IEmpT)
      case '{ type t <: IMap; ICons[k, v, `t`](${Const(keyValue)}, ${Const(valueValue)}, $tail) } =>
        for tailValue <- valueOfIMap(tail)
        yield ICons(keyValue, valueValue, tailValue)
      case _ => None

  object Const:
    def unapply(x: Expr[Any])(using Quotes): Option[Any] =
      (x: Expr[Any]) match
        case '{ ${Expr(value)}: String } => Some(value)
        case '{ ${Expr(value)}: Int } => Some(value)
        // ...
        case _ => None
```
or
```scala
inline def testT2M[T1 <: IMap](inline x: T1): Unit = ${testT2MImpl[T1]('x)}

  def testT2MImpl[T1 <: IMap: Type](x: Expr[T1])(using Quotes): Expr[Unit] = {
    println(x.show)
    println(valueOfIMap(x))

    println(s"x.show = ${x.show}")
    println(s"valueOfIMap(x) = ${valueOfIMap(x)}")
    '{()}
  }

  def valueOfIMap[T <: IMap](x: Expr[T])(using Quotes): Option[T] =
    x match
      case '{ IEmpT } => Some(IEmpT.asInstanceOf[T])
      case '{ type t <: IMap; ICons[k, v, `t`](${Const(keyValue)}, ${Const(valueValue)}, $tail) } =>
        for tailValue <- valueOfIMap(tail)
        yield ICons(keyValue, valueValue, tailValue).asInstanceOf[T]
      case _ => None

  object Const:
    def unapply[T](x: Expr[T])(using Quotes): Option[T] =
      (x: Expr[Any]) match
        case '{ ${Expr(value)}: String } => Some(value.asInstanceOf[T])
        case '{ ${Expr(value)}: Int } => Some(value.asInstanceOf[T])
        // ...
        case _ => None
```
#### Alternative 2
Add support for something like 
```scala
inline def testT2M[T1 <: IMap](inline x: T1): Unit = 
  ${testT2MImpl[T1]('x)(using summonInline[FromExpr[T1]])}

def testT2MImpl[T1 <: IMap: Type](x: Expr[T1])(using FromExpr[T1])(using Quotes): Expr[Unit] = ..
```

There is a major issue with this approach. We would need to teach the interpreter how to interpret the summoned implicit which could contain an arbitrary call and arbitrary parameters.

Furthermore, we would have to check that this instance is statically known and does not violate any of the staging guarantees.

This could also interact poorly with other planned improvements such as allowing arbitrary code in macro `$`. This would require the compilation of the splice which we would not be able to do if `summonInline` is present.

**Comment by hmf** [comment]
@nicolasstucki Thank you very much for the explanation and examples. 

Interestingly, I had assumed something like your "Alternative 2" was the "correct" way to go. I tried `summonInline`, `summon` and even `Expr.summon`, and of-course these did not work :-)

My objective is to retain the narrowed full types within the structure (not the widened `IMap`), so I think your second example of "Alternative 1" is what I need. Irrespective, I will keep this open in case I have some related questions. 

If I don't have any more questions, should I close this or do you want it open for reference?

Thank you both for taking the time to process this.

**Comment by hmf** [comment]
@nicolasstucki with the information here, the use of transparent inline and explicitly narrowing the types, I was able to do what I wanted. Thank you.
