### ISSUE TITLE
Documentation needs "Getting started" for users

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1673]
Docs page has "Getting Started" for contributors (http://dotty.epfl.ch/docs/), but should have one for users

**Comment by Jentsch** [comment]
Should this page than mimic the content of the (homepage at the bottom)[http://dotty.epfl.ch/#getting-started]? May add some links to further material?

**Comment by felixmulder** [comment]
Sure and yes :)

**Comment by Varunram** [comment]
What could be some good sub-headings? SubHeadings what I had in mind were -  Getting Started, Creating Your own Project , Migrating code to dotty and Reporting Bugs. Your views? @felixmulder

**Comment by smarter** [comment]
This page now exists: http://dotty.epfl.ch/docs/usage/getting-started.html
