### ISSUE TITLE
Scaladoc generates broken method names for methods that include nested methods

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#16783]
## Compiler version

3.2.2

## Minimized code

```Scala
  override def foreach[U](f: A => U): Unit = {
    @inline def foreachNonHole(): Unit = {
      ...
    }
    ...
    foreachNonHole()
  }
```

https://github.com/ThoughtWorksInc/Binding.scala/blob/9d421faa498e07497d55a023c715b70638ebc5c5/SafeBuffer/shared/src/main/scala/com/thoughtworks/binding/SafeBuffer.scala#L40-L83

```
git clone https://github.com/ThoughtWorksInc/Binding.scala
cd Binding.scala
git switch 9d421faa498e07497d55a023c715b70638ebc5c5 --detach
sbt unidoc
```
## Output

Generated HTML:
![image](https://user-images.githubusercontent.com/601530/215290818-f22318cd-c164-4afc-9c7f-bfcef0cc9c15.png)

https://javadoc.io/static/com.thoughtworks.binding/binding_3/12.2.0+39-9d421faa/com/thoughtworks/binding/SafeBuffer.html

## Expectation

The method name should be `foreach`

**Comment by mbovel** [comment]
Removing the Spree label as @Florian3k is now assigned to this issue.

**Comment by Florian3k** [comment]
Seems to be working fine on latest `main`.
