### ISSUE TITLE
Top-level values cannot be final in Scala 3.3.x ?

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#16805]
## Compiler version

v3.3.0-RC2

## Minimized code

```Scala
package Foo
final val baz = 1 //error
```

## Output

```scala
'final' modifier is not allowed here
```

## Expectation
No error. If for some reason this change is intended, then this should go through a SIP.

**Comment by SethTisue** [comment]
I'm not able to reproduce the problem:

```
% cat Foo.scala 
package Foo
final val baz = 1 //error
% scala-cli compile -S 3.3.0-RC2 .
% 
```

**Comment by soronpo** [comment]
OK, it turns out this is an intellij bug and not a scalac bug. I just had several errors and I missed the fact that this was only displayed in the editor and not compiler.
