### ISSUE TITLE
Pattern-match under "-source future" requires Matchable to check an identical type

### ISSUE THREAD

**Issue by Odomontois** [lampepfl/dotty#16808]
## Compiler version

3.2.2
## Minimized code

```Scala
def collectKeys[A, B, C](xs: Map[A, B])(f: PartialFunction[A, C]): Map[C, B] = 
	xs.collect{ case (f(c) , b) => (c, b) }
```

## Output
With no flags produces no warnings.
With scalacOptions ++= Vector("-source", "future") produces warning

> pattern selector should be an instance of Matchable,,
> but it has unmatchable type A instead

**Comment by kyri-petrou** [comment]
I believe this is a similar issue. Minimized code:

```scala
final case class Foo(foo: String):
  override def canEqual(that: Any): Boolean = that match
    case f: Foo => ???
    case _      => ???
```

produces the following warning:
> pattern selector should be an instance of Matchable, but it has unmatchable type Any instead

This effectively makes the [example on multiversal equality](https://docs.scala-lang.org/scala3/book/ca-multiversal-equality.html) at the bottom of the page produce a warning

**Comment by ritschwumm** [comment]
@kyri-petrou https://docs.scala-lang.org/scala3/reference/other-new-features/matchable.html# explains what to do for universal equality (but does not mention the `asMatchable` extension method which might be better than using `.asInstanceOf[Matchable]`)

**Comment by bishabosha** [comment]
> I believe this is a similar issue. Minimized code:
> 
> ```scala
> final case class Foo(foo: String):
>   override def canEqual(that: Any): Boolean = that match
>     case f: Foo => ???
>     case _      => ???
> ```

This is a different case because here we are type testing if `Any` is a `Foo`, which breaks the assumption of the type not opting-into pattern matching. in the OP, `A` is already known to be `A` so even though A is not bound by `Matchable`, it is not uncovering new information with a type test.
