### ISSUE TITLE
-Wunused: False positive on parameterless enum member

### ISSUE THREAD

**Issue by kubukoz** [lampepfl/dotty#16822]
## Compiler version

3.3.0-RC2

## Minimized code

```Scala
//> using scala "3.3.0-RC2"
//> using option "-Wunused:all"

enum ExampleEnum {
  case Build(context: String)
  case List
}

@main def demo = {
  val x = ExampleEnum.List
  println(x)
}
```

## Output

```scala
Compiling project (Scala 3.3.0-RC2, JVM)
[warn] ./demo.scala:6:3: unused explicit parameter
[warn]   case List
[warn]   ^
Compiled project (Scala 3.3.0-RC2, JVM)
```

## Expectation

No warning is reported

**Comment by szymon-rd** [comment]
@PaulCoral Did you have a chance to look at this?

**Comment by PaulCoral** [comment]
> @PaulCoral Did you have a chance to look at this?
 @szymon-rd I couldn't work on the linter during past two weeks. I will try to fix the remaining warn-unused bugs.
