### ISSUE TITLE
Mobile menu has a very very small tap target

### ISSUE THREAD

**Issue by ckipp01** [lampepfl/dotty#16834]
## Describe the issue

When reading through accessibility guides you'll commonly see it mentioned that [accessible tap targets](https://web.dev/accessible-tap-targets/) are around 9mm. This ends up being more or less 45px by 45px. The current reference docs has a hit size of 16 x 16 making a user on mobile actually struggle to be able to hit it. I had to try multiple times to actually get this to work on a modern iPhone.

<img width="319" alt="Screenshot 2023-02-05 at 16 33 59" src="https://user-images.githubusercontent.com/13974112/216828924-860e5b5a-c002-4610-b130-3277bf69c2df.png">

**Comment by Dedelweiss** [comment]
I made a first proposal to increase the tap target. Instead of making a padding, I did a width for the close button because the left padding is different.
