### ISSUE TITLE
scaladoc3 social links cannot be custom

### ISSUE THREAD

**Issue by andrew-selvia** [lampepfl/dotty#16856]
[The *Overview of all available settings* section of the scaladoc3 settings page](https://docs.scala-lang.org/scala3/guides/scaladoc/settings.html#overview-of-all-available-settings) indicates that custom social links can be provided. This feature seems to have been [removed in May 2022](https://github.com/lampepfl/dotty/commit/b232f41721a56ace74cc90eda368b53bcdf616ac#diff-728e2ba8f21bb60ba2a7798d5aac7fe56800f8ec720dc8cc43b080ea3ea7cf1e). The change actually shows the documentation was updated to reflect this removal; however, [the currently visible settings page](https://docs.scala-lang.org/scala3/guides/scaladoc/settings.html#overview-of-all-available-settings) does not reflect this, thus misleading readers:
 
> ### -social-links
> Links to social sites. For example:
> 
> `-social-links:github::https://github.com/lampepfl/dotty,discord::https://discord.com/invite/scala,twitter::https://twitter.com/scala_lang`
>
> Valid values are of the form: `[github|twitter|gitter|discord]::link`. Scaladoc also supports `custom::link::white_icon_name::black_icon_name`. In this case icons must be present in `images/` directory.

This issue could be resolved by either:

1. Updating the Settings page to reflect the change
2. Re-introducing support for custom social links (possibly tracked via a separate *feature request* issue)

In the meantime, users may still achieve the effect of custom social links via a workaround. Assuming it is acceptable to sacrifice one of the officially-supported social link types (e.g., `github`, `twitter`, `gitter`, or `discord`), a user may provide a custom social link for one of the supported social link types. The icon for the chosen social link type can then be replaced in `api/images/icon-buttons/$replacedSocialLinkType` with the desired **custom** icon. I have wrapped up this workaround as an sbt task and appended it to the standard `Compile / doc` task. Unfortunately, I'm not at liberty to share my code at present; if that changes, I'll gladly provide it here.

**Comment by Dedelweiss** [comment]
Hello, Do we know why this feat was removed?
