### ISSUE TITLE
Scala 2 regression: type inference widens type too much for an overridden member

### ISSUE THREAD

**Issue by myazinn** [lampepfl/dotty#16868]
## Compiler version

3.0.0, 3.2.2 and 3.3.0-RC2

## Minimized code
https://scastie.scala-lang.org/VOJKBf5MSC6SRJAin3TrSA
```Scala
trait Resource
class MyResource() extends Resource {
  def something: String = "something"
}

trait Suite {
  def resource: Resource
}
class MySuite extends Suite {
  //  def resource: MyResource = MyResource() // works
  def resource = new MyResource()
  resource.something
}
```

## Output

```
value something is not a member of Playground.Resource
```

## Expectation
Expected to compile, as in [Scala 2](https://scastie.scala-lang.org/UoI2DRFYT6eEhj4dlRRZLQ).
Expected type inference to use `MyResource` type for `resource` method and not inherited `Resource`.

**Comment by smarter** [comment]
This is an intentional change in Scala 3, the inferred type of an override is always the type of the overridden definition (this is also the behavior of Scala 2 under -Xsource:3 I believe).
