### ISSUE TITLE
Unused explicit parameter warning on last member of enum

### ISSUE THREAD

**Issue by markehammons** [lampepfl/dotty#16878]
## Compiler version

3.3.0-RC2

## Minimized code

```Scala
enum A:
  case B
  case C
  case D
```

https://scastie.scala-lang.org/Amnc44icRuqsIoBP1tgQbg

## Output

Unused explicit parameter on case D

**Comment by PaulCoral** [comment]
@szymon-rd 
It seems to be fixed on `main`. I can't trigger the warning.
Probably by #16927

**Comment by szymon-rd** [comment]
Confirmed, fixed in nightly.
