### ISSUE TITLE
Reasoning with 'Option(null)' as a number 0 and type inference

### ISSUE THREAD

**Issue by FabioPinheiro** [lampepfl/dotty#16880]
## Compiler version
scala 3.2.1

`null.asInstanceOf[Long]` this is `0`
`null` seems to be treated as the unbox/primitive type and not as the instance of a class.

This isn't the best. Is hard to reason with the code.
I'm almost sure that this was already discussed many times. But it these hard to find documentation about it so if you point me out I would appreciate it. 

## Minimized example

For example:
The current recommendation (as far as I know) is to warp the return of java functions with Option.
Now I know this is no longer good enough.

```Scala
val t = m1.getCreatedTime() //final def getCreatedTime(): Long
val t1: Option[Long] = Option(t)
val t2 = Option(t)
println(s"t = $t")
println(s"t1 = $t1")
println(s"t2 = $t2")

val f = null.asInstanceOf[Long]
val f1: Option[Long] = Option(f)
val f2 = Option(f)
println(s"f = $f")
println(s"f1 = $f1")
println(s"f2 = $f2")
```

## Output

```scala
t = null
t1 = Some(0)
t2 = None
f = 0
f1 = Some(0)
f2 = Some(0)
```

## Expectation

From the point of view of `f1` and `f2`:
- They have the same code
- They have the same type
- They have different values (just because one of them has type inference)

**Maybe the problem is with the inference of the java (kotlin) method.**
My expectation is for the method to return the `java.lang.Long` instead of `scala.Long`

Note I came across this on code where the type inference comes from the case class.
```scala
case class Ex(value: Option[Long])
println(Ex(Option(m1.getCreatedTime())))
// Ex(Some(0))
```

**Comment by FabioPinheiro** [comment]
`null.asInstanceOf[java.lang.Long]` this is `null`

Maybe I need to report a bug on the type inference of the method.

**Comment by FabioPinheiro** [comment]
Also, saying that the type is `java.lang.Long` is not enough
`Ex(Option(m1.getCreatedTime(): java.lang.Long))`

I need to do the following to get a None
```
Ex(
  { Option(m1.getCreatedTime()): Option[java.lang.Long] }.map( i => i)
)
```

**Comment by FabioPinheiro** [comment]
But the Compiler must know the type because the following code compiles
```
Option(m1.getCreatedTime()).map {
  case null => ???
  case e    => e
}
```
and does not compiles
```
(Option(1L)).map {
  case null => ???
  case e    => e
}
```
error: `Values of types Null and Long cannot be compared with == or !=`


Maybe I should complain about the tooling.
I was even able to get the type inference off `Option[Long & Long]` 
I assume one is `scala.Long` and another `java.lang.Long`

**Comment by smarter** [comment]
> null.asInstanceOf[Long] this is 0

Yes, this is as specified: https://www.scala-lang.org/files/archive/spec/2.13/06-expressions.html#the-null-value

> Since this is a java/kotlin method the type MUST be a java.lang.Long

No, if a Java method returns a primitive `long`, then Scala will treat it as `scala.Long`, this is intentional and there can't be any confusion with `null` since it is not a valid value of type `long` in Java.

Closing this since there doesn't appear to be any actionable bug here, please use another venue like https://users.scala-lang.org/ to discuss language semantics.

**Comment by FabioPinheiro** [comment]
I would have to check the bytecode but it seems it returns a `java.lang.Long`. If not https://github.com/lampepfl/dotty/issues/16880#issuecomment-1426066141  would not happen.
But it seems that we are losing that information somewhere.

ok I can try to discuss the other place
