### ISSUE TITLE
coursier won't run on Debian stable (11, bullseye)

### ISSUE THREAD

**Issue by olhotak** [lampepfl/dotty#16886]
## Minimized code

```
curl -fL https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz | gzip -d > cs && chmod +x cs && ./cs setup
```

From the installation instructions at https://www.scala-lang.org/download/

## Output

```
./cs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./cs)
./cs: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./cs)
```

## Expectation

Coursier should run and install Scala.

Debian bullseye comes with glibc 2.31 but the version of cs recommended by the Scala installation instructions requires 2.32 or 2.34.

Coursier and the installation instructions are aimed at newcomers trying to get started with Scala, and this is a blocker for them.

**Comment by julienrf** [comment]
Hey, thank you for reporting! This issue is tracked here https://github.com/coursier/coursier/issues/2624 and I believe we fixed it (but we did not release the fix yet).
