### ISSUE TITLE
Issue when de-sugaring the += syntax when the update method's second argument is a context function

### ISSUE THREAD

**Issue by MewenCrespo** [lampepfl/dotty#16895]
## Compiler version

Using scala 3.2.2 (but the issue seems to appear in every scala 3.x.y)

## Minimized code

```Scala
type Authorization = Unit

class Foo():
    def apply(i : Int)(using Authorization) : Int = i //would read in a map in a real implementation

    def update(i : Int, f : Authorization ?=> Int) : Unit =
        println(s"The new value of #$i is now ${f(using ())}") //would write in a map in a real implementation
            

object Foo:
    def main(args : Array[String]) : Unit =
        val foo = new Foo()
        foo(42) = foo(42) + 1 //Ouputs: "The new value of #42 is now 43"
        foo(42) += 1 //Does not compile: No given instance of type Authorization was found for parameter x$2 of method apply in class Foo
```

## Output of ` foo(42) = foo(42) + 1`

```text
   The new value of #42 is now 43
```
## Output of `foo(42) += 1`

```text
   [compilation error] No given instance of type Authorization was found for parameter x$2 of method apply in class Foo
```

## Expectation of `foo(42) += 1`

```text
   The new value of #42 is now 43
```

## Analysis
As we can see ` foo(42) = foo(42) + 1` de-sugaries into `foo.update(42, foo.apply(42).+(1))` and  then into `foo.update(42, auth ?=> foo.apply(42)(using auth).+(1))`  and works as expected.

On the other hand `foo(42) += 1`, which should de-sugaries into ` foo(42) = foo(42).+(1)` fails as the second instance of `foo(42)` (the one on the right-hand side of the `=` sign) does not have access to the implicit `Authorization` instance, as attested by the compile-time error:

`No given instance of type Authorization was found for parameter x$2 of method apply in class Foo`

## Speculations
If I had to guess, I would say that when de-sugaring `foo bar= x` into `foo = foo.bar(x)`, the second foo is parsed by the compiler separately, therefore missing the implicit parameters. But this is just a guess that needs to be verified.

## Note
The issue disappeares when `apply` signature becomes
```Scala
   def apply(i : Int): Int
````
Also, the issue is independent of the `+=` syntax and also appears with `foo(42) *= 3`, `foo(42) -= 3` or even a more exotic `foo(42) +~= 5`, etc. (assuming we replace `Int` with a class having a method `+~`)

**Comment by odersky** [comment]
Unfortunately this requires circular reasoning. By the time we do the expansion, we have already type checked the LHS foo(42), which leads to the error.
