### ISSUE TITLE
different subtype shouldn't be equal in dependent typing

### ISSUE THREAD

**Issue by doofin** [lampepfl/dotty#16898]
## Compiler version
3.2.1

## Minimized example

```Scala
  enum Adt1 {
    case High, Low
  }
  def add[t <: Adt1](x: t, y: t) = {}

  add(Adt1.High, Adt1.Low)
```

## Output

It compiles

## Expectation
It shouldn't compile since x and y have different subtype,only code like  `add(Adt1.High, Adt1.High)` should compile.

**Comment by smarter** [comment]
This is working as intended. After type inference, we end up with:
```scala
add[Adt1](Adt1.High, Adt1.Low)
```
which type-checks since both `Adt1.High` and `Adt1.Low` can be typed with type `Adt1`.

In general, type inference will always do its best to find a type that fits to make your code compile.

**Comment by doofin** [comment]
Could you suggest some ways to achieve this more fine-grained control? thanks

**Comment by smarter** [comment]
There isn't a direct way to do this, so I encourage you to describe what you're trying to achieve on a forum such as https://users.scala-lang.org/ where you can go into details.
