### ISSUE TITLE
Merge queue is stuck waiting for workers

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#16921]
It seems that all tests in the queue are stuck waiting for workers. They also time out from the queue after 12 hours.

https://github.com/lampepfl/dotty/queue/main

See
* https://github.com/lampepfl/dotty/pull/16913
* https://github.com/lampepfl/dotty/pull/16862
* https://github.com/lampepfl/dotty/pull/16887
* https://github.com/lampepfl/dotty/pull/16838

**Comment by nicolasstucki** [comment]
Now merges are failing even if the tests are passing.

**Comment by Kordyjan** [comment]
I disabled the queue. It behaves unpredictably. I hope I soon will be able to experiment with it on other repository and enable it again.
