### ISSUE TITLE
Materialise types in compiletime.error

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#16933]
## Compiler version

3.2.2

## Minimized code

```Scala
inline def generateTypeClass[T] = compiletime.error(s"could not generate type class for ${T}")
@main def test = generateTypeClass[String]
```

## Output

```scala
error: could not generate type class for ${T}
```

## Expectation
I would like some mechanism to report an error about a specific type with compiletime operations. For example, we can not reuse `implicitNotFound` mechanism because failures in inline matches override that error.

**Comment by nicolasstucki** [comment]
We can easily do that using macros. I do not belive it would be worth the time and extra complexity in the compiler to implement this feature.

**Comment by bishabosha** [comment]
I've tested now and for anyone wondering, string concatenation works, so you can do something like

```scala
inline def generateTypeClass[T] =
  compiletime.error(
    "could not generate type class for class " + Macros.classNameOf[T])
```

**Comment by SethTisue** [comment]
> string concatenation works

Is it actually about concatenation vs interpolation? That seems implausible, but perhaps I'm missing something.

**Comment by bishabosha** [comment]
I didn't try :)

**Comment by nicolasstucki** [comment]
We do not constant fold string interpolations. `s"${Macros.classNameOf[T]}"` will not work by inline alone, but it would work with macros.
