### ISSUE TITLE
REPL crash when I try to tab complete on SortedMap.

### ISSUE THREAD

**Issue by sebposselt** [lampepfl/dotty#16934]
## Compiler version
2.12.16

## Minimized code

When i try tab completion on SortedMap, the REPL crashes
```Scala
import scala.collection.immutable.SortedMap                                                                                                                                  
scala> val x = SortedMap.
```

## Expectation
Exception in thread "main" java.lang.AssertionError: assertion failed: missing implicit parameter of type Ordering[K] after typer at phase parser

**Comment by WojciechMazur** [comment]
I can reproduce it using Scala 3.2.2, but not in 3.3.0-RC2, so it seems to be fixed already

**Comment by som-snytt** [comment]
That was https://github.com/lampepfl/dotty/pull/16559

Why does it say compiler 2.12.16?

For the record, I could not reproduce it anywhere, but then the weird exception rang a bell.
