### ISSUE TITLE
Trait parameters without `val` keyword can not be accessed in implementors

### ISSUE THREAD

**Issue by nikololiahim** [lampepfl/dotty#16971]
## Compiler version
3.2.2

## Minimized code
```scala
//> using scala "3.2.2"

trait Error(code: String)

case object FunnyError extends Error("haha funny")

@main def main: Unit = 
  println(FunnyError.code)

```

## Output

```scala
-- [E008] Not Found Error: unapply/src/main/scala/unapply/Main.scala:8:21 ------
8 |  println(FunnyError.code)
  |          ^^^^^^^^^^^^^^^
  |value code is not a member of object FunnyError - did you mean FunnyError.clone?
1 error found
```

## Expectation
The code should compile and print "haha funny" to console.

## Notes 
Sorry in advance if this is not a bug, I just thought that `(code: String)` and `(val code: String)` are supposed to be equivalent. Even though the [page](https://docs.scala-lang.org/scala3/reference/other-new-features/trait-parameters.html) mentions trait parameters with `val`, nothing is mentioned about the `val`-less parameters, and compiler doesn't reject it either. 

If I change the line from 
```scala
trait Error(code: String)
```
to

```scala
trait Error(val code: String)
```

the code works as expected.

**Comment by WojciechMazur** [comment]
The parametrized trait are behaving in the same manner as `class`. It  means that if `val` is ommited then the field is treated as `private val`. Only case classes have different behavior for their constructors arguments, which are by default treated as `<public> val` 

That means in your example you can do something like this, because code is a private field: 
```
trait Error(code: String){
  println(code)
}
```

**Comment by som-snytt** [comment]
hypothetical syntax `case object Funny(code: String = "haha") extends Error(code)`
