### ISSUE TITLE
Docs: ToC overlaps with wide image

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#16991]
The static page renderer does not have a good default for images that are too large

## Compiler version

3.2.2

## Minimized code

go to https://dotty.epfl.ch/blog/2019/06/11/16th-dotty-milestone-release.html

![Screenshot 2023-02-22 at 11 03 15](https://user-images.githubusercontent.com/13436592/220587721-cccf2687-7d88-499b-93c8-91999701663c.png)

## Expectation
either the image is scaled to fit the page, or the table of contents should have a background

**Comment by Dedelweiss** [comment]
I think this problem is related to PR #17016
