### ISSUE TITLE
Some givens ignore `@compileTimeOnly` annotation

### ISSUE THREAD

**Issue by pweisenburger** [lampepfl/dotty#17002]
## Compiler version

3.3.1-RC1-bin-20230216-2507577-NIGHTLY

## Minimized code

Some givens ignore their `@compileTimeOnly` annotation and let code compile when it should error. See comments in the code below:

```Scala
import scala.annotation.compileTimeOnly

sealed trait Test[T]

object Test:
  @compileTimeOnly("Error")
  given test0[T]: Test[T] = ???

  @compileTimeOnly("Error")
  given test1[T]: Test[T]()

  test0 // produces a compiler error, which is correct

  test1 // compiles but should not
```

----

EDIT: A further observation (that may be related): The following code fails to compile but should IMHO:

```Scala
import scala.annotation.compileTimeOnly

sealed trait Test

object Test:
  @compileTimeOnly("Error")
  given Test()
```
Error message:
```
[error] 35 |object Test:
[error]    |       ^
[error]    |       Error
[error] one error found
```

**Comment by odersky** [comment]
The second failing test is due to the method `ordinal` that's generated for the mirror of `Test`.
```scala
import scala.annotation.compileTimeOnly

sealed trait Test

object Test:
  @compileTimeOnly("Error")
  given Test()
```

**Comment by odersky** [comment]
The first example works as expected if `@compileTimeOnly` is replaced with `erased`. 

The reason it does not work with `compileTimeOnly` is that annotations are not copied from the class to the accessor. I believe it would be dangerous to copy all annotations, so we'd have to make a special case for `@compileTimeOnly`. Given that `compileTimeOnly` is meant to be replaced by `erased`, the problem will be solved eventually anyway.

**Comment by pweisenburger** [comment]
> The reason it does not work with `compileTimeOnly` is that annotations are not copied from the class to the accessor. I believe it would be dangerous to copy all annotations, so we'd have to make a special case for `@compileTimeOnly`.

This sounds to me like the more principled way to control where `compileTimeOnly` goes are the `scala.annotation.meta._` annotations. But maybe this is not possible in this case?

In any case, I would also advocate keeping the possibility to add a customized message to the compiler error.

**Comment by odersky** [comment]
We could use `scala.annotation.meta.companionClass` and `companionMethod` for that. Right now, these meta annotations are ignored in dotty. They don't work for implicit classes either.
