### ISSUE TITLE
`List(...)` builder missing Scala 2 optimization to avoid intermediate array

### ISSUE THREAD

**Issue by armanbilge** [lampepfl/dotty#17035]
## Compiler version

`3.3.1-RC1-bin-20230301-0df5ae2-NIGHTLY`

## Minimized code

```Scala
class Test {
  def foo = List("foo", "bar", "baz")
}
```

## Output

```java
/*
 * Decompiled with CFR 0.151.
 */
import scala.collection.immutable.List;
import scala.collection.immutable.Seq;
import scala.package$;
import scala.runtime.ScalaRunTime$;

public class Test {
    public List<String> foo() {
        return (List)package$.MODULE$.List().apply((Seq)ScalaRunTime$.MODULE$.wrapRefArray((Object[])new String[]{"foo", "bar", "baz"}));
    }
}
```

## Expectation

The `List` is built directly, without going through an intermediate varargs array.

Scala 2.13.10 decompiles to this:
```java
/*
 * Decompiled with CFR 0.151.
 */
import scala.collection.immutable.;
import scala.collection.immutable.List;
import scala.collection.immutable.Nil$;

public class Test {
    public List<String> foo() {
        return new .colon.colon((Object)"foo", (List)new .colon.colon((Object)"bar", (List)new .colon.colon((Object)"baz", (List)Nil$.MODULE$)));
    }
}
```

**Comment by smarter** [comment]
For anyone interested in giving this a try, this should probably be done done as a mini-phase similar to https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/transform/TupleOptimizations.scala.

**Comment by nicolasstucki** [comment]
It is better to do this one after erasure. The `Array.apply` transform seems to be more closely related to this optimization https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/transform/ArrayApply.scala.

**Comment by smarter** [comment]
For reference, the Scala 2 implementation is at https://github.com/scala/scala/blob/5ecdcf817d5084060734e5cb2f1b505472e7bda0/src/compiler/scala/tools/nsc/transform/CleanUp.scala#L555-L565
and https://github.com/scala/scala/blob/5ecdcf817d5084060734e5cb2f1b505472e7bda0/src/compiler/scala/tools/nsc/transform/CleanUp.scala#L630-L633
