### ISSUE TITLE
Inline does not propagate refinement without transparent

### ISSUE THREAD

**Issue by chuwy** [lampepfl/dotty#17043]
## Compiler version

3.2.2, 3.3.0-RC3

## Minimized code

Given the following trait:

```scala
trait A:
  type U
  def check(u: U): U = u
```

Following non-macro code works as expected:

```scala
val a = new A { type U = "foo" | "bar" }
a.check("foo")   // compiles just fine; fails on a.check("quiz")
```

And the following macro (which I expect to generate the same code) fails:

```scala
inline def umacro: A =
  ${ umacroImpl }

def umacroImpl(using Quotes): Expr[A] =
  import quotes.reflect.*
  val utype = OrType(ConstantType(StringConstant("foo")), ConstantType(StringConstant("bar")))

  utype.asType match
    case '[u] =>
      '{ new A { type U = u }}

val b = umacro
b.check("foo")   // doesn't compile
```

## Output

```scala
scala> b.check("foo")
-- [E007] Type Mismatch Error: -------------------------------------------------
1 |b.check("foo")
  |        ^^^^^
  |        Found:    ("foo" : String)
  |        Required: b.U
  |
  | longer explanation available when compiling with `-explain`
1 error found
```

## Expectation

I think the macro should generate the same code. And it's even proven by printing the `Expr`:

```scala
{
  final class $anon() extends A {
    type U = "foo" | "bar"
  }

  (new $anon(): A {
    type U >: "foo" | "bar" <: "foo" | "bar"
  })
}
```

Although not being exactly the same - this object works as expected if I just copy-paste it and use as non-macro.

**Comment by chuwy** [comment]
Same happens with tuple types, btw.

**Comment by nicolasstucki** [comment]
#### Minimized 

```scala
trait A:
  type U
  def check(u: U): U = u

inline def umacro: A = new A { type U = "foo" | "bar" }

def test =
  val b = umacro
  b.check("foo")   // doesn't compile
  b.check("bar")   // doesn't compile
```

**Comment by nicolasstucki** [comment]
This is the expected behaviour, `umacro` return an `A` without any refinements.

This is a bug in the implementation of the macro, to propagate the refinement it is necessary to have a `tanspartent inline`

```diff
- inline def umacro: A =
+ transparent inline def umacro: A =
```

**Comment by chuwy** [comment]
Aha! Thanks, @nicolasstucki! My mistake was actually very different. In my actual implementation I _did_ have `transparent`, but it had different problem. The problem was that I was defining the union type inside class definition:

```scala
(refinement.asType, union.asType) match
  case ('[refinementType], '[union]) =>
    '{ (new A { type U = union }).asInstanceOf[A & refinementType] }
```

So, my type was overridden by `Table & refinementType`. In fact I had to write it as:

```scala
(refinement.asType, union.asType) match
  case ('[refinementType], '[union]) =>
    '{ (new A()).asInstanceOf[A { type U = union } & refinementType] }
```

Thanks again and sorry for false alarm.
