### ISSUE TITLE
`private`-ness of trait constructor ignored

### ISSUE THREAD

**Issue by pweisenburger** [lampepfl/dotty#17089]
## Compiler version

3.3.0-RC3

## Minimized code

```Scala
object o:
  trait T private[o]()

def test = new o.T { }
```

## Output

The code compiles. I would expect it not to. My expectation was that `trait T private[o]()` scopes the constructor of `T` private in `o` (but maybe this is not the case?). I assume that the anonymous class created in `new o.T { }` calls the `T`'s constructor. If that is the case, then I think creating instances of `T` should only be possible within `o` (which was the intention here).

**Comment by som-snytt** [comment]
```
object o:
  trait T private[o]()
  trait U private[o] (i: Int)

def test = new o.T { }
def ouest = new o.U(42) { }

class C extends o.T
class D extends o.U(42) // constructor U cannot be accessed as a member of o.U from class D.
```
Error as expected with parameters.

**Comment by odersky** [comment]
@som-snytt Yes, that's the point here. We don't call the constructor of a trait unless we have to pass parameters. So declaring it as `private[o]` does not help.

**Comment by pweisenburger** [comment]
Makes sense that the constructor is not called if there are no parameters to pass. But this sounds more like an optimization that should not affect the surface language. I find it a bit concerning that `trait T private[o](...)` behaves differently depending on whether the argument list is empty or not, in particular that the `private` modifier is sometimes silently ignored by the compiler.

If the code is legal, `private` should not be a no-op IMO. Thus, I believe the compiler should issue a warning or even reject the program, or – as a much more useful semantics – `private` should prevent instances of the trait from being created/mixed-in out of scope (to this end, the compiler could check that the constructor is accessible, regardless of whether it is actually called or not).

Also, the statements in the trait's body _are_ executed during construction (either as part of the constructor or of some special mixin initialization method). I think a reasonable expectation is that `private[o]` makes construction private.

**Comment by odersky** [comment]
I agree this warrants further investigation.
