### ISSUE TITLE
Scaladoc: add tests for `extension` signatures

### ISSUE THREAD

**Issue by KacperFKorban** [lampepfl/dotty#17108]
Scaladoc should test signatures of `extension`s just like it's done for `def`s. This way we can prevent issues like https://github.com/lampepfl/dotty/issues/16647

The appropriate file for this is most likely:
https://github.com/lampepfl/dotty/blob/main/scaladoc/test/dotty/tools/scaladoc/signatures/SignatureTest.scala

**Comment by Dedelweiss** [comment]
Hello, I would like to work on this issue. From what I understand the [SignatureTest.scala](https://github.com/lampepfl/dotty/blob/main/scaladoc/test/dotty/tools/scaladoc/signatures/SignatureTest.scala) file, it is linked to the [TranslatableSignaturesTestCases.scala](https://github.com/lampepfl/dotty/blob/main/scaladoc/test/dotty/tools/scaladoc/signatures/TranslatableSignaturesTestCases.scala) file which allows to call different scala files such as [extensionParams.scala](https://github.com/lampepfl/dotty/blob/main/scaladoc-testcases/src/tests/extensionParams.scala) which contains examples of extension methods to test. So, is it enough to add new examples in this file (or another one), or do we need to modify the [SignatureTest.scala](https://github.com/lampepfl/dotty/blob/main/scaladoc/test/dotty/tools/scaladoc/signatures/SignatureTest.scala) file?
