### ISSUE TITLE
Unclear "... must be called with () argument" error message

### ISSUE THREAD

**Issue by dsbos** [lampepfl/dotty#17123]
## Compiler version

3.2.2

## Minimized example

```Scala
object ConfusingErrorMessage {
  def m()() = ()
  m()
}
```

## Output

```scala
.../ConfusingErrorMessage.scala:3:4
method m in object ConfusingErrorMessage must be called with () argument
  m()
```

Note how the error message says that the method needs to be called with an empty argument list, even though the method is called with an empty argument list.

(Yes, I know that the real problem is that it needs a _second_ empty argument list too, but the error message doesn't say or hint at that, and therefore is confusing.)

## Expectation
Better error message wording and/or structure. 

Maybe refer to the partial call `m()` instead of referring to just method `m` when saying that something must be called with a `()` argument list.  

Maybe say something like "call to `m` must be called with a(nother) `()` argument."

Also, report the column number consistently. When the first (empty) argument list is missing, the column number points to where the list is missing (the column after `m`), but when a second or later (argument) list is missing, the column number points into the _middle_ of the last present argument list, not pointing to where something it missing.

**Comment by som-snytt** [comment]
Scala 2 has the same issue, and also incorrectly predicts what Scala 3 would do.

Related Scala 3 ticket on position (for missing givens) and PR to avoid pointing the caret to outer space.
https://github.com/lampepfl/dotty/issues/15630
https://github.com/lampepfl/dotty/pull/15644

I like a message that shows me what to write, like this related Scala 2 message:
```
scala> def m(i: Int)(j: Int) = ()
def m(i: Int)(j: Int): Unit

scala> m(42)
        ^
       error: missing argument list for method m
       Unapplied methods are only converted to functions when a function type is expected.
       You can make this conversion explicit by writing `m _` or `m(_)(_)` instead of `m`.
```
