### ISSUE TITLE
`Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/jenkins/tmp` printed in partests

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#1712]
It looks like when executing `partest` all tests fail because of `Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/jenkins/tmp` being printed at the start of each one. I've seen it in #1711 and #1685.

```
% diff /home/jenkins/workspace/dotty-master-validate-partest-bootstrapped/tests/partest-generated/run/view-headoption-run.log /home/jenkins/workspace/dotty-master-validate-partest-bootstrapped/tests/partest-generated/run/view-headoption.check
% 
@@ -1,4 +1,3 @@
-Picked up _JAVA_OPTIONS: -Djava.io.tmpdir=/home/jenkins/tmp
 fail
 success
 f1: Some(5)
```

**Comment by nicolasstucki** [comment]
It has also affected #1700. All PRs that where updated this afternoon.

**Comment by smarter** [comment]
We have a disabled "filters" file for this, no clue how it's supposed to work: https://github.com/lampepfl/dotty/blob/master/tests/untried/filters#L6

**Comment by smarter** [comment]
Relevant: https://github.com/scala/scala-partest/blob/7c265b38352f146f941a873b153cbfc22d7b7afd/src/main/scala/scala/tools/partest/nest/Runner.scala#L352-L355

**Comment by smarter** [comment]
In our case `srcDir` is `tests/partest-generated/` so we have to put the `filters` file in there somehow

**Comment by nicolasstucki** [comment]
I still can't reproduce it locally.

**Comment by nicolasstucki** [comment]
Testing #1714 on CI to see if reverting the PRs merged today has some different results.

**Comment by liufengyun** [comment]
It also cause `test.TestDotc.buildAndRunHelloWorld` junit test fail.

**Comment by liufengyun** [comment]
It can be reproduced as follows:

```
set -x _JAVA_OPTIONS ""
sbt "testOnly -- test.TestDotc.buildAndRunHelloWorld"
```

A related post at SO [here](http://stackoverflow.com/questions/11683715/suppressing-the-picked-up-java-options-message).

I guess the settings on Jenkins have changed somehow.

**Comment by DarkDimius** [comment]
I have a fix available in https://github.com/lampepfl/dotty/pull/1715
