### ISSUE TITLE
Tailrec jammed by safer exceptions

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#17147]
## Compiler version

```
$head -1 build.sbt 
ThisBuild / scalaVersion := "3.3.1-RC1-bin-20230322-1f574e8-NIGHTLY"
```

## Minimized code

```Scala
object TestyFactorial:
  // minimal example
  import scala.annotation.tailrec
  import language.experimental.saferExceptions

  @tailrec
  final def fact(n: Int, acc: Int): Int throws Exception =
    if n < 0 then
      throw new Exception
    else if n == 0 then
      acc
    else
      fact(n - 1, acc * n)
```

## Output

```scala
$sbt clean compile
  ...
[error]  |    fact(n - 1, acc * n)
[error]  |    ^^^^^^^^^^^^^^^^^^^^
[error]  |    Cannot rewrite recursive call: it is not in tail position
```

**Comment by abgruszecki** [comment]
This seems like a reasonably simple issue. Maybe it's good for the issue spree?

**Comment by dwijnand** [comment]
Seems plausible to me too.  Let's label it and if anyone disagrees they can remove it.

**Comment by bishabosha** [comment]
it broke between `3.3.1-RC1-bin-20230302-8020c77-NIGHTLY` and `3.3.1-RC1-bin-20230303-6ad22aa-NIGHTLY`

**Comment by bishabosha** [comment]
most likely it seems that https://github.com/lampepfl/dotty/pull/16507 cause the issue

**Comment by bishabosha** [comment]
minimisation found by @Linyxus 
```scala
object TestyFactorial:
  import scala.annotation.tailrec
  import language.experimental.erasedDefinitions

  erased class Foo1
  class Foo2

  @tailrec
  final def test1(n: Int, acc: Int): () ?=> Int =
    if n <= 0 then acc
    else test1(n - 1, acc * n)

  @tailrec
  final def test2(n: Int, acc: Int): Foo2 ?=> Int =
    if n <= 0 then acc
    else test2(n - 1, acc * n)
```

**Comment by bishabosha** [comment]
It seems the problem is with erasure, as I noted in https://github.com/lampepfl/dotty/pull/16507#issuecomment-1513476400, before the change, the erasure of `test1` is `@ContextResultCount(1) @tailrec def test1(n: Int, acc: Int): Int`, but now it is `@tailrec final def test1(n: Int, acc: Int): Function0`
