### ISSUE TITLE
Match type bounded by type with argument(s) cannot be reduced to satisfy `=:=` check

### ISSUE THREAD

**Issue by tribbloid** [lampepfl/dotty#17149]
Pointed out by @DmytroMitin in the following post:

https://stackoverflow.com/questions/75837775/in-scala-2-or-3-is-there-a-higher-kind-argument-extractor-without-using-match-t/75842531#75842531

```
  type Ext[S <: Seq[_]] = S match {
    case Seq[t] => t
  }

implicitly[Ext[Seq[Int]] =:= Int] // e.scala: Cannot prove that e.Ext[Seq[Int]] =:= Int
```

If I change the definition of `Ext` as follow, the consequence will differ:

```
  type Ext[S] = S match {
    case Seq[t] => t
  } // success!

  type Ext[S <: Any] = S match {
    case Seq[t] => t
  } // success!

  type Ext[S <: Seq[Any]] = S match {
    case Seq[t] => t
  } // same error
```

**Comment by sjrd** [comment]
Also works in tasty-query :grin:

**Comment by dwijnand** [comment]
Yeah, not widening the abstract type `S` to its bounds `Seq[Int]` is what I meant by "my" original fix.  But it's really was to see whether reverting that part back to how Olivier had it fix that issue, which it did.  Seth did a good job attempting to narrate and crosslink this saga in https://github.com/lampepfl/dotty/issues/15926#issuecomment-1282638215.

**Comment by dwijnand** [comment]
> Disallowing it seems too restrictive

Going back to this comment, I think disallowing is correct: we don't want the match type to reduce to the upper bound, because then we lose the tie to the actually passed type.   We want the String in Seq[String], not Any, even though Any is String's upper bound.  The match type, as it's defined using an abstract type in the match alias's type lambda, should stay an unreduced match type (because reduction gets stuck).

**Comment by tribbloid** [comment]
I also have a simplified dual form:

```
    object Dual {

      trait SGen {

        type S <: Seq[_]

        type Ext = S match {
          case Seq[t] => t
        }
      }

      object SeqIntGen extends SGen {

        type S = Seq[Int]
      }

      implicitly[SeqIntGen.Ext =:= Int] // still broken
    }
```

The fix should theoretically work on both cases

**Comment by tribbloid** [comment]
I'm almost certain that the problem is caused by variance of Seq[_], as replacing Seq[_] with a custom trait:

```
    trait Vec[+T]

    object Primary {

      type Ext[S <: Vec[_]] = S match {
        case Vec[t] => t
      }

      implicitly[Ext[Vec[Int]] =:= Int] // broken
    }

    object Secondary {
      trait SGen {

        type S <: Vec[_]

        type Ext = S match {
          case Vec[t] => t
        }
      }

      object SeqIntGen extends SGen {

        type S = Vec[Int]
      }

      implicitly[SeqIntGen.Ext =:= Int] // still broken
    }
```

caused almost identical errors, yet if `[+T]` is replaced with `[T]` these errors disappear
