### ISSUE TITLE
Confusing error for constructor proxy shadowing

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#17153]
## Compiler version

3.3.0

## Minimized example

```Scala
class Number(n: Int)
val x = Number(3)
```

## Output

```scala
2 |val x = Number(3)
  |        ^^^^^^
  |        Reference to constructor proxy for class Number
  |        shadows outer reference to object Number in package java.lang
```

## Expectation

 1. `java.lang.Number` cannot possibly be applied, so one could avoid the error
 2. The error message could be better and could contain some suggestions how to fix the problem.

**Comment by piotrborek** [comment]
I just wanted to point out that this code compiles and run with no error

'class Number(n: Int)
val x = new Number(3)'
