### ISSUE TITLE
Exception while typechecking and compiling pattern matching with @

### ISSUE THREAD

**Issue by vuspenskiy** [lampepfl/dotty#1716]
```
object Fail {
  case class So[+T]()

  def main(args: Array[String]): Unit = {
    So[Int]() match {
      case p@So[_] => Console.println("Yep")
      case _       => Console.println("Nope")
    }
  }
}
```

Compiler says,

```
exception occurred while typechecking /path/to/Src.scala
exception occurred while compiling /path/to/Src.scala
```

Works well if underscore in pattern matching is replaced with a specific type.

**Comment by liufengyun** [comment]
@vuspenskiy Thanks for reporting, we'll investigate the crash and why there's no error message about syntax.

Regarding the syntax, we need to either use `p : So[_]` or `p @ So(_)` in the code example.

Following code has the same stack trace:

```Scala
object Fail {
  def f(m: Option[Int]): Unit = {
     m match {
      case x @ Some[_] =>
      case _       =>
    }
  }
}
```

**Comment by jvican** [comment]
I think I will take care of this, am I stepping on someone's toes?

**Comment by jvican** [comment]
I propose to follow scalac's behaviour here:
```scala
 found   : Some[_]
 required: Some[Int]
                  case p@Some[_] => println(
```

**Comment by liufengyun** [comment]
Thanks  @jvican  for help, please go ahead 👍

**Comment by jvican** [comment]
Sorry for the delay on this, will take care of this this weekend.

**Comment by jvican** [comment]
Sorry @liufengyun, I won't be able to do this any time soon. I unassign me just in case someone wants to give it a try.

**Comment by liufengyun** [comment]
No worry @jvican , I'll take care of it.
