### ISSUE TITLE
Scala3doc is too narrow on wider screens

### ISSUE THREAD

**Issue by kubukoz** [lampepfl/dotty#17217]
On the Scaladoc page, currently there seems to be a CSS script attached that results in very narrow pages once you reach a certain minimum width.

Example: Firefox says it's 1826px width. This is fine.

<img width="1889" alt="image" src="https://user-images.githubusercontent.com/894884/230471943-3dc68864-e495-427e-87f6-fae845757a5a.png">

Now when you reach ~1920px, it gets too narrow:

<img width="1984" alt="image" src="https://user-images.githubusercontent.com/894884/230472052-d0eec96b-5388-44c6-9296-169fa0e088e3.png">

here's what it looks like on my screen in fullscreen (my usual viewing experience. It's a bit of a waste of space 😅

<img width="3008" alt="image" src="https://user-images.githubusercontent.com/894884/230472411-f0bfe755-8cda-4939-b97d-529a018f174c.png">

**Comment by Florian3k** [comment]
This is fixed on latest main
