### ISSUE TITLE
Regression in match exhaustivity of higher-kinded types

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#17230]
## Compiler version
3.3.1-RC1-bin-20230407-bcaa1ca-NIGHTLY

## Minimized code
Based on Open CB failure https://github.com/VirtusLab/community-build3/actions/runs/4650721329/jobs/8230332752 for [rescala-lang/rescala](https://github.com/rescala-lang/rescala)

```Scala
import scala.util.* 

trait Transaction {
  type State[_]
}
object Transaction {
  type of[S[_]] = Transaction { type State[A] = S[A] }
}
trait DynamicScope[State[_]]

case class ScopeSearch[State[_]](self: Either[Transaction.of[State], DynamicScope[State]]) {

  def embedTransaction[T](f: Transaction.of[State] => T): T =
    self match {
      case Left(integrated) => ??? 
      case Right(ds)        => ???
    }
}

```

## Output

```scala
Compiling project (Scala 3.3.1-RC1-bin-20230407-bcaa1ca-NIGHTLY, JVM)
[warn] ./test.scala:13:5
[warn] match may not be exhaustive.
[warn] 
[warn] It would fail on pattern case: Left(_)
[warn]     self match {
[warn]     ^^^^
Compiled project (Scala 3.3.1-RC1-bin-20230407-bcaa1ca-NIGHTLY, JVM)
```

## Expectation
Should not give warning

**Comment by WojciechMazur** [comment]
Bisect points to a range of commits 0df5ae2 .. 8020c77 , but further bisect was failing due to some other issues: 
```
Last good release: 3.3.1-RC1-bin-20230301-0df5ae2-NIGHTLY
First bad release: 3.3.1-RC1-bin-20230302-8020c77-NIGHTLY
```

**Comment by dwijnand** [comment]
Minimised

```scala
trait Foo:
  type Bar[_]

object Foo:
  type Aux[B[_]] = Foo { type Bar[A] = B[A] }

class Test:
  def test[B[_]](self: Option[Foo.Aux[B]]) = self match
    case Some(b)             => 1
    case None                => 2
```

**Comment by mbovel** [comment]
> Guys, is anybody continue to work on this issue? How actually our workflow in Compiler Academy is should going?

I re-assigned you to work on this with Dale during next spree. Would that be okay for you?

**Comment by mbovel** [comment]
Please ignore the 2 previous message from the Scala Center bot. Teams for the next spree can be found here: https://airtable.com/shrSni1OItSuErosU/tblLEWc2ISeGHPbsc. Sorry for the spam!
