### ISSUE TITLE
Should Generate warnings when synchronized on `AnyVal`

### ISSUE THREAD

**Issue by He-Pin** [lampepfl/dotty#17284]
## Compiler version
3.2.2

## Minimized code

```Scala
1.synchronized{}
```

## Output
![image](https://user-images.githubusercontent.com/501740/232224274-abfa893a-64d5-439f-a4fa-a0591bfd3865.png)

## Expectation

generate some warning as https://openjdk.org/jeps/390

**Comment by liang3zy22** [comment]
This issue also exists with scala 2.13.10.
<img width="474" alt="Screenshot 2023-04-17 at 15 43 11" src="https://user-images.githubusercontent.com/35164941/232418545-119db8d9-14d5-44a4-bddd-befe80c4831c.png">

**Comment by som-snytt** [comment]
That is due to boxing conversion.

`g` does not compile in Scala 2, but in Scala 3 is accepted, as though written `A.synchronized`.
```
class A(val s: String) extends AnyVal {
  //def f = eq("hello, world")  // missing argument list for method eq in object Predef

  def g = synchronized { println("hello, world") }
}
```
The error on `f` is charming. I was expecting it to use `(Predef: AnyRef).eq` and was hoping for a warning.

**Comment by mbovel** [comment]
See [`synchronized` method documentation](https://scala-lang.org/api/3.x/scala/AnyRef.html#).

**Comment by mbovel** [comment]
I don't know good ressources about autoboxing in Scala, but the one for Java might be worth reading: https://docs.oracle.com/javase/tutorial/java/data/autoboxing.html.

**Comment by michaelpigg** [comment]
It's not clear to me what phase of the compiler is relevant to this issue. I was thinking initially the parser, but maybe it's at erasure after the tree shows it converted to a BoxedUnit?

**Comment by michaelpigg** [comment]
Thanks for the explanation, @mbovel !

**Comment by xuwei-k** [comment]
- https://github.com/scala/scala3/issues/27110
