### ISSUE TITLE
Regression from March: Incorrect quoted.Type instance required in quotes subclassing an inner trait

### ISSUE THREAD

**Issue by neko-kai** [lampepfl/dotty#17293]
## Compiler version

`3.3.1-RC1-bin-20230407-bcaa1ca-NIGHTLY` and `3.3.1-RC1-bin-20230416-2f4cc4c-NIGHTLY`

## Minimized code
https://scastie.scala-lang.org/E3WYTt73Ryqc3pzCY1xapQ
```Scala
import scala.quoted.{Expr, Quotes, Type, quotes}

trait OuterTrait {
  trait X
}

def exampleMacro[T <: OuterTrait: Type](expr: Expr[T])(using Quotes): Expr[OuterTrait#X] = {
  '{
    val prefix: T = ${ expr }
    new prefix.X {}
  }
}
```

## Output

```scala
[error] -- Error: exampleMacro.scala:12:19
[error] 12 |    new prefix.X {}
[error]    |                   ^
[error]    |Reference to T#X within quotes requires a given scala.quoted.Type[T#X] in scope.
```

## Expectation

Expected to compile as on commit `7262437` (version `3.3.1-RC1-bin-20230331-7262437-NIGHTLY`, https://scastie.scala-lang.org/y7mN6SA1REKvXAqIIEAbqw).

Constraint `Type[T#X]` is unwriteable since it's an abstract type projection and cannot be satisfied.

**Comment by neko-kai** [comment]
@nicolasstucki Could you please look into this regression when you have the time? It wouldn't let us update a Scala 3.2 project to 3.3, if 3.3 release includes it - I don't think there's a workaround for it.

**Comment by smarter** [comment]
You can work around this by replacing `val prefix: T = ...` by `val prefix: OuterTrait = ...`, does that work for your usecase?

**Comment by neko-kai** [comment]
@smarter 
Thanks for the suggestion! The real macro is structured like this:

```scala
import scala.quoted.{Expr, Quotes, Type, quotes}

trait OuterTrait { self =>
  trait X
  
  def exampleMacro[T <: self.type: Type](expr: Expr[T])(using Quotes): Expr[self.X] = {
    '{
      val prefix: T = ${ expr }
      new prefix.X {}
    }
  }
}
```

because of self.X return type, T cannot be replaced by OuterTrait, it must be self.type.

But it appears that this bug was fixed already in 3.3.0, neither variant of the snippet causes an error anymore:

https://scastie.scala-lang.org/7Qn2ZOBlTyaoUIPWwboSCA
https://scastie.scala-lang.org/4uZfLU78Q0ehKI4WehMCEQ

I'm closing this, although it might be prudent to add a test for this to the test suite.

**Comment by neko-kai** [comment]
It was reintroduced again in 3.3.1-RC1+ and still present in 3.3.1-RC4 ...

https://scastie.scala-lang.org/KcD6pkn4RhWHewJaSRtmuA
https://scastie.scala-lang.org/B8PHfwyQRvmOpVVYyl2V7w

**Comment by Kordyjan** [comment]
To be exact, 3.3.0 was branched out way before the commit that introduced the bug. Therefore, the bug is a regression introduced in 3.3.1.
It should be sorted out in 3.3.2.
