### ISSUE TITLE
Disallow Array[Nothing], Array[Null], ... to avoid ClassCastException in some cases

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#1730]
See also https://issues.scala-lang.org/browse/SI-7453

In `scalac`:
```scala
scala> if (false) Array("qwe") else Array()
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
```
In dotty, thankfully:
```scala
scala> if (false) Array("qwe") else Array() 
res1: Array[String] | Array[Nothing] = [Ljava.lang.Object;@1dd92fe2
```
But still in dotty:
```scala
scala> val x = if (false) Array("qwe") else Array() 
x: Array[String] | Array[Nothing] = [Ljava.lang.Object;@5454d35e
scala> val y: Array[_ <: String] = x 
java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [Ljava.lang.String;
```

We either need to disallow `Array[Nothing]`, `Array[Null]`, etc or we need to erase `Array[_ <: X]` to `Object` instead of `[X;`.

It would also be much nicer if we could infer the empty array above to have type `Array[String]` instead of `Array[Nothing]`, I don't know what prevents us from doing this currently.

**Comment by odersky** [comment]
Erasing Array to Object is very expensive computationally, and it would be surprising for users. So I am much in favor of disallowing Array[Nothing] and Array[Null].

**Comment by odersky** [comment]
One quite radical idea would be to treat `Nothing` and `Null` not as classes but as abstract types. That means we could not generate a `ClassTag` for them and therefore it would be impossible to create instances of `Array[Nothing] and `Array[Null]`

**Comment by sjrd** [comment]
If we disallow `classTag[Null]`, then we should also disallow `classOf[Null]`. This is extreme, as now we have concrete types we cannot a `classOf`/`classTag` of anymore. "Treating them as abstract types" seems completely unjustified, other than as a workaround for this implementation limitation related to arrays. This seems wrong to me.

**Comment by odersky** [comment]
Is `classOf[Null]` used anywhere?

I have my doubts because in the end there is no class `Null` on the JVM. We fake one, but it's a hack.

**Comment by retronym** [comment]
Here are a few usages I found in projects I've checked out. Seems fairly rare.

```
⚡ ack --scala 'classOf\[Null\]'

json4s/scalabeans/src/main/scala/org/scalastuff/scalabeans/sig/ScalaTypeCompiler.scala
117:    else if (clazz == "scala.Null") Some(classOf[Null])

scalatra/scalatra/swagger/src/main/scala/org/scalatra/swagger/reflect/Reflector.scala
26:  private[this] val defaultExcluded = Set(classOf[Nothing], classOf[Null])

twitter/util/util-reflect/src/main/scala/com/twitter/util/reflect/Proxy.scala
89:    (rt eq classOf[Unit]) || (rt eq classOf[Null]) || (rt eq java.lang.Void.TYPE)

```

**Comment by nicolasstucki** [comment]
Currently in Dotty we have 
```scala
scala> if (false) Array("qwe") else Array() 
-- Error: <console>:5:36 -------------------------------------------------------
5 |if (false) Array("qwe") else Array()
  |                                    ^
  |attempt to take ClassTag of undetermined type for parameter evidence$2 of method apply in object Array
```

@odersky can this issue be closed? This was probably fixed in e34555f69e7cdd6d19d0d1ed969127f4ee65c36e

**Comment by smarter** [comment]
@nicolasstucki No, as state in the PR that this commit comes from: https://github.com/lampepfl/dotty/pull/1921#issuecomment-276805294

**Comment by odersky** [comment]
The comment says that we might want to consider disallowing forming a `ClassTag[Null]` or `ClassTag[Nothing]` manually (they are not synthesized anymore). On the other hand, anyone who would do that in a sense does homegrown meta-programming, and it's not clear to what extent we want to give soundness guarantees for such code. So I think it's OK to close for now. If we feel like it, revisit the manual creation issue.
