### ISSUE TITLE
3.3.0-RC4 -Wunused:all compiler exception

### ISSUE THREAD

**Issue by ornicar** [lampepfl/dotty#17309]
When compiling [lila](github.com/lichess-org/lila) with:
- scala 3.3.0-RC4
- `-Wunused:all` flag
- openjdk version "17.0.6" 2023-01-17
- sbt 1.8.2

we get the following exception:

```
java.lang.AssertionError: NoDenotation.owner while running checkUnusedPostInlining on lila/modules/tree/src/main/Eval.scala
[info] exception occurred while compiling lila/modules/tree/src/main/Eval.scala, lila/modules/tree/src/main/package.scala, lila/modules/tree/src/main/tree.scala
java.lang.AssertionError: NoDenotation.owner while compiling lila/modules/tree/src/main/Eval.scala, lila/modules/tree/src/main/package.scala, lila/modules/tree/src/main/tree.scala
[error] ## Exception when compiling 3 sources to lila/modules/tree/target/scala-3.3.0-RC4/classes
[error] java.lang.AssertionError: NoDenotation.owner
```

Here's the [full compiler output](https://gist.githubusercontent.com/ornicar/ba67b8bc20d1e4c8cb9d439ef5f0246f/raw/d3627f48bc7afccab0fca98fc7a94b167a6fef5f/gistfile1.txt).

It works if we remove the `-Wunused:all` flag from [the build settings](https://github.com/lichess-org/lila/blob/scala-3.3.0-RC4/project/BuildSettings.scala#L59), or if we downgrade scala to 3.3.0-RC3.

How to reproduce:
```
git clone https://github.com/lichess-org/lila.git --branch scala-3.3.0-RC4
cd lila
sbt compile
```

**Comment by ornicar** [comment]
It can also be reproduced with [lila-ws](github.com/lichess-org/lila-ws), a much smaller project than lila is.

```
git clone https://github.com/lichess-org/lila-ws.git --branch Wunused-all
cd lila-ws
sbt compile
```

**Comment by KacperFKorban** [comment]
The common factor is `reactivemongo-bson-api`.
Partial minimization with just `reactivemongo-bson-api` as dependency:

```scala
//> using scala "3.3.0-RC4-bin-SNAPSHOT"
//> using options "-Wunused:all"
//> using lib "org.reactivemongo::reactivemongo-bson-api:1.1.0-RC9"

import reactivemongo.api.bson.*

case class Eval()

given BSONDocumentHandler[Eval] = Macros.handler

```
