### ISSUE TITLE
MethodHandle `@PolymorphicSignature` support.

### ISSUE THREAD

**Issue by scf37** [lampepfl/dotty#17343]
## Compiler version
3.2.2

## Minimized code

```Scala
import java.lang.invoke.{MethodHandles, MethodType}

object Main {
  def foo(i: Int): Int = i + 1

  def main(args: Array[String]): Unit = {
    val h = MethodHandles.lookup().findVirtual(classOf[Main.type], "foo", MethodType.methodType(classOf[Int], classOf[Int]))
    val r: Int = h.invokeExact(this, 42)
    println(r)
  }
}
```

## Output

```scala
Found:    Object
Required: Int
```

## Expectation
This code successfully compiles on `2.13.10`. `@PolymorphicSignature` methods require special treatment which is present in 2.x but seems to be missing in 3.x, see https://github.com/scala/bug/issues/7965

**Comment by bishabosha** [comment]
this is coming in 3.3.0

**Comment by SethTisue** [comment]
as in, you can already try it in 3.3.0-RC4 — please do try it, since the support is new!
