### ISSUE TITLE
Regression: Non-terminating compilation (fixed in NIGHTLY)

### ISSUE THREAD

**Issue by TomasMikula** [lampepfl/dotty#17368]
## Compiler version

3.3.0-RC5

## Reproduction steps

```
git clone https://github.com/TomasMikula/libretto.git
cd libretto
git checkout b042b14bc4162488f2ad36c3727272212380b295

# compiles with the configured Scala version 3.2.2
sbt lambda/compile

# Edit build.sbt, set
# ThisBuild / scalaVersion := "3.3.0-RC5"

# compilation hangs
sbt lambda/compile
```

Note: Non-termination does not occur with a nightly build (e.g. `3.3.1-RC1-bin-20230425-c9ca7ce-NIGHTLY`), most likely thanks to #16827. Thus, a backport will likely suffice to fix the regression.

**Comment by Kordyjan** [comment]
I will close the issue as it is already solved. If we decide to have another RC for 3.3.0, the fix should be available there. If not, expect it in the first patch to the 3.3.

**Comment by TomasMikula** [comment]
It's puzzling that you would rather introduce a regression in the release than backport an existing fix. Do you expect the backport to be particularly tricky?

**Comment by Kordyjan** [comment]
>  Do you expect the backport to be particularly tricky?

We are checking. I think the backport is doable.
