### ISSUE TITLE
constValueOpt doesn't work for class parameters

### ISSUE THREAD

**Issue by doofin** [lampepfl/dotty#17387]
## Compiler version
3.2.2
## Minimized code

```Scala
import scala.compiletime.*

class c2[i <: Int] { println("constValueOpt:" + constValueOpt[i]) }
new c2[2]
```

## Output

constValueOpt:None

## Expectation
should be constValueOpt:Some(2)

**Comment by soronpo** [comment]
This is not a bug. When the class is being compiled the compiler has no knowledge what `i` type is, and that is when the class body, along with `constValueOpt` is being compiled as well.

**Comment by soronpo** [comment]
Here is a better way:
```scala
import scala.compiletime.*

class c2[i <: Int]:
  inline def printme: Unit = println("constValueOpt:" + constValueOpt[i])
new c2[2].printme
```

**Comment by doofin** [comment]
thanks for the reply, I know inline def will work,but feel that this limitation is not necessary. could you point me to the LOC in the compiler ?

**Comment by doofin** [comment]
so according to the code, constValueOpt is only supported at inlinedMethod and it would be tricky to extend it ?

**Comment by soronpo** [comment]
Not part of the compiler team, but from what I understand, this is not something that is possible.

**Comment by doofin** [comment]
Just have an idea: why not get the value before compile time (maybe at macro expansion time ) and inline it when compiling ?

**Comment by smarter** [comment]
Another solution is to use the ValueOf typeclass:
```scala
class c2[i <: Int: ValueOf] { println("valueOf:" + valueOf[i]) }
```

**Comment by doofin** [comment]
@smarter thanks! this looks interesting and almost same as what I think

**Comment by smarter** [comment]
What does the use-site look like? If it's `new c2[2]` it should work, if it's a method parameter then you'll need to propagate the typeclass constraint:
```scala
def foo[i <: Int: ValueOf] = new c2[i]
```

**Comment by doofin** [comment]
@smarter thanks! this actually works, it's just my typo
