### ISSUE TITLE
JUnit doesn't work with dotty-bridge

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1741]
I have a Dotty project uses JUnit:

```Scala
libraryDependencies += "com.novocode" % "junit-interface" % "0.11" % "test"
testOptions += Tests.Argument(TestFrameworks.JUnit, "-q", "-v")
```

With the test file:

```Scala
import org.junit.Test
import org.junit.Assert._

class MacrosTest {
  @Test def hello = {
    assertTrue(true)
  }
}
```

When run `sbt test`, nothing happens.  When compile with scalac, everything works normally as confirmed by @smarter .

**Comment by felixmulder** [comment]
Might be a typo, but `object MacrosTest` does not get run by scalac, it has to be declared `class MacrosTest`.

**Comment by liufengyun** [comment]
@felixmulder , good catch, it's a typo.
