### ISSUE TITLE
Ambigious types errors by picking nested/derived type and type defined in the same package

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#17433]
## Compiler version
3.3.1-RC1-bin-20230504-0e00420-NIGHTLY

Found in Community Build in following projects: 

| Project | Version | Build URL | Notes |
| ------- | ------- | --------- | ----- |
| endpoints4s/endpoints4s | 1.9.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8747506002) |  |
| sangria-graphql/sangria | 4.0.0-RC4 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8749671624) |   |
| zio/zio-prelude | 1.0.0-RC18 -> 1.0.0-RC19 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8747625148) |  |

## Output

In this case Value is also defined as `sealed trait Value` in other file
```scala
Error:  -- [E049] Reference Error: /build/repo/modules/core/src/main/scala/sangria/ast/AstVisitorCommand.scala:6:30 
Error:  6 |  val Skip, Continue, Break = Value
Error:    |                              ^^^^^
Error:    |                    Reference to Value is ambiguous.
Error:    |                    It is both defined in package sangria.ast
Error:    |                    and inherited subsequently in object AstVisitorCommand
Error:    |
```

## Expectation
Should compile

**Comment by odersky** [comment]
I think it's due to #17033. Maybe revert that and check again?

**Comment by lrytz** [comment]
Seems to be a bug, the ambiguity should only show if `sangria.ast.Value` is defined in the same file, which doesn't seem to be the case. https://github.com/sangria-graphql/sangria/blob/main/modules/core/src/main/scala/sangria/ast/AstVisitorCommand.scala

**Comment by lrytz** [comment]
Probably best to revert it, I'll take a look to submit a fixed version.

**Comment by som-snytt** [comment]
@lrytz maybe just a tweak
```
@@ -438,7 +438,7 @@ class Typer(@constructorOnly nestingLevel: Int = 0) extends Namer
               val found =
                 if owner.is(Package) then
                   owner.denot.asClass.membersNamed(name)
-                    .filterWithPredicate(d => !d.symbol.is(Package) && d.symbol.source == denot.symbol.source)
+                    .filterWithPredicate(d => !d.symbol.is(Package) && d.symbol.source.ne(util.NoSource) && d.symbol.source == denot.symbol.source)
                 else
                   val scope = if owner.isClass then owner.info.decls else outer.scope
                   scope.denotsNamed(name)
```

I tried it with sangria. Yes, it "pairs well" with sangria!

**Comment by lrytz** [comment]
Thank you @som-snytt, that looks good to me. I'll PR it tomorrow if you didn't already.

**Comment by som-snytt** [comment]
I'll grant you the honors, like King Charles III, or I guess in Scala it's King Charless. Oh, the pun is also `Char-less` which I pronounce "care less" as in "I could care less".

`zio-prelude` is honest ambiguity. I added some `this.` but it is tiresome.

**Comment by som-snytt** [comment]
`endpoints4s` (https://github.com/endpoints4s/endpoints4s/blob/master/algebras/algebra/src/main/scala/endpoints4s/algebra/ChunkedEntities.scala#L57)

looks obscure to this reader. The intuition may have been that the type parameter is disambiguating.

Perhaps it's a good time to try out the [new meme](https://fosstodon.org/@jack@berlin.social/110311676636844603): “Borges thinks you should try a little harder.”

```
trait Chunks {

  /** A stream of chunks of type `A`.
    *
    * @tparam A Information carried by each chunk
    * @group types
    */
  type Chunks[A]
}

/** @group algebras */
trait ChunkedRequestEntities extends Chunks {
  this: EndpointsWithCustomErrors =>

  /** A request entity carrying chunks of `String` values
    *
    * @group operations
    */
  def textChunksRequest: RequestEntity[Chunks[String]]   // ambiguous Chunks
```

**Comment by som-snytt** [comment]
@lrytz I took another look, in case it helps. at https://github.com/lampepfl/dotty/pull/17439  Feel free to disregard. I was just staring at the spinning gears. I had not crafted a test yet, only trying it locally.
