### ISSUE TITLE
Compilation fails due to assertion in `scala.quoted.runtime.impl.QuotesImpl$reflect$Symbol$.newVal`

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#17432]
## Compiler version
3.3.1-RC1-bin-20230504-0e00420-NIGHTLY

Found in Open Community build in following projects: 

Projects with last successful builds using Scala <b>[1m3.3.1-RC1-bin-20230427-f128063-NIGHTLY[0m</b> [16]:
| Project | Version | Build URL | Notes |
| ------- | ------- | --------- | ----- |
| carlos-verdes/zio-arangodb | 0.2.2 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8750443957) |  |
| lambdaworks/zio-elasticsearch | 0.1.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8750070858) |  |
| vigoo/desert | 0.3.3 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8750846690) |  |
| yakivy/jam | 0.3.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8747413966) |  |
| zio/zio-openai | 0.2.0 -> 0.2.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/4897105783/jobs/8750444201) |  |

## Output

```scala
Error:  -- Error: /build/repo/arangodb-http/src/main/scala/io/funkode/arangodb/http/SchemaCodecs.scala:21:46 
Error:  21 |  given Schema[ArangoError] = DeriveSchema.gen[ArangoError]
Error:     |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error:     |Exception occurred while executing macro expansion.
Error:     |java.lang.AssertionError: assertion failed: privateWithin must be a type symbol or `Symbol.noSymbol`
Error:     |	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$Symbol$.newVal(QuotesImpl.scala:2547)
Error:     |	at scala.quoted.runtime.impl.QuotesImpl$reflect$Symbol$.newVal(QuotesImpl.scala:2546)
Error:     |	at zio.schema.DeriveSchema.deriveCaseClass(DeriveSchema.scala:153)
Error:     |	at zio.schema.DeriveSchema.deriveSchema(DeriveSchema.scala:94)
Error:     |	at zio.schema.DeriveSchema$.deriveSchema(DeriveSchema.scala:18)
Error:     |	at zio.schema.DeriveSchema$.inline$deriveSchema(DeriveSchema.scala:17)
Error:     |```

**Comment by sjrd** [comment]
That's an intentional big fix. The macros that try to use a term symbol there are wrong. And that has actually shown in published artifacts that contain invalid tasty that tasty-query cannot read.

**Comment by KacperFKorban** [comment]
I made a PR to `zio-schema` that should fix all the errors EXCEPT for `yakivy/jam`.
`zio-schema` PR: https://github.com/zio/zio-schema/pull/555
