### ISSUE TITLE
SemanticDB diagnostics missing

### ISSUE THREAD

**Issue by bjaglin** [lampepfl/dotty#17535]
## Compiler version

3.3.0-RC6 (but I believe this is not a regression, and is reproducible for any 3.x)

## Minimized code

```scala
//> using scala 3.3.0-RC6
//> using options -Wunused:all -Ysemanticdb

import java.util.List

object Test
```

## Output

```
➜  metap Test.scala.semanticdb
Test.scala
--------------

Summary:
Schema => SemanticDB v4
Uri => tmp/Test.scala
Text => empty
Language => Scala
Symbols => 1 entries
Occurrences => 4 entries

Symbols:
_empty_/Test. => final object Test extends Object { self: Test.type => +1 decls }

Occurrences:
[3:7..3:11) => java/
[3:12..3:16) => java/util/
[3:17..3:21) => java/util/List#
[5:7..5:11) <= _empty_/Test.
```

## Expected

```diff
 ➜  metap Test.scala.semanticdb
 Test.scala
 --------------

 Summary:
 Schema => SemanticDB v4
 Uri => tmp/Test.scala
 Text => empty
 Language => Scala
 Symbols => 1 entries
 Occurrences => 4 entries

 Symbols:
 _empty_/Test. => final object Test extends Object { self: Test.type => +1 decls }

 Occurrences:
 [3:7..3:11) => java/
 [3:12..3:16) => java/util/
 [3:17..3:21) => java/util/List#
 [5:7..5:11) <= _empty_/Test.

+Diagnostics:
+[3:17..3:21) [warning] Unused import
```

**Comment by tgodzik** [comment]
Now this seems to work if a StoreReporter is used, but any reporter that just prints the information right away will lose the info. What is the least hacky way to get all warnings even if they were already reported?

**Comment by WojciechMazur** [comment]
@tanishiking Can you look at that in your spare time? I think you had some experience with SemanticDB in the past

**Comment by tgodzik** [comment]
> @tanishiking Can you look at that in your spare time? I think you had some experience with SemanticDB in the past

I think we might need to some additional output from someone closer to the core compiler. If we have a ConsoleReporter there is no way to get the warnings from pending messages, so would be great to know if we can work around it. @szymon-rd had worked recently with unused warnings, maybe he knows something?

**Comment by tanishiking** [comment]
I can take a look on SemanticDB generation side, but it would be great if someone knows how can we retrieve the diagnostics via `ctx`

**Comment by szymon-rd** [comment]
We can change how we aggregate diagnostics in the CheckUnused and linting; that change could be introduced in a patch (3.3.1?). What I find interesting is that, if I understand correctly, the semanticdb file is extracted after the typer. We don't have the lining diagnostic information at that point yet. Maybe that's even the cause of it all?
