### ISSUE TITLE
An alias to an opaque type alias doesn't recognise function value application when called outside its defining scope

### ISSUE THREAD

**Issue by nmcb** [lampepfl/dotty#17552]
## Compiler version

Scala 3.2.2 (19.0.2, Java OpenJDK 64-Bit Server VM)

## Minimized code

The following example 1 works:

```Scala
object Test:
  opaque type F = Int => Int
  type G = F
  val test: G = (i: Int) => i + 1
  println(test(3))
```

While applying the aliased function value outside of scope doen't compile in example 2:

```Scala
object Def:
 opaque type F[A,B] = A => B
 type G[X] = F[X,X]
                                                                                                                                     
object Test:
  val test: Def.G[Int] = (i: Int) => i + 1
  println(test(3))
```

## Output

Working output on example 1:

```
scala> Test
4
```

Compilation error on example 2 - especially note the second error:

```
-- [E007] Type Mismatch Error: -------------------------------------------------
2 |  val test: Def.G[Int] = (i: Int) => i + 1
  |                         ^^^^^^^^^^^^^^^^^
  |                         Found:    Int => Int
  |                         Required: Def.G[Int]
  |-----------------------------------------------------------------------------
-- [E050] Type Error: ----------------------------------------------------------
3 |  println(test(3))
  |          ^^^^
  |          value test in object Test does not take parameters
  |-----------------------------------------------------------------------------
```

## Expectation example 2

Expected to work as the first example:

```
scala> Test
4
```

Note that example 2 _does_ work for non opaque type aliases

**Comment by sjrd** [comment]
That's the whole point of opaque type aliases. Outside of their defining scope, you *don't* know that they're equal to their right-hand-side. So from `Test`, even though you know `G[Int]` is an `F[Int, Int]`, you have no idea what `F[Int, Int]` is, and therefore you cannot assign a function to it.
