### ISSUE TITLE
Wrong linearization for super calls in case classes

### ISSUE THREAD

**Issue by ddtthh** [lampepfl/dotty#17555]
## Compiler version

3.2.2
3.3.0-RC3
Worked in 3.1.2

## Minimized code

```Scala
class Root {
  override def toString() = "Root"
}
trait A extends Root with B {  }
trait B {
   override def toString() = "B"
}
case class C() extends A {
  override def toString() = super.toString()
}

println(C())
```

## Output

```
Root
```

## Expectation
`toString` in trait `B` should be called and output should be B.
This works for normal classes, but the case class breaks that.

**Comment by szymon-rd** [comment]
Regression, behavior changed in 3.2.0-RC1

**Comment by szymon-rd** [comment]
Bisected to `16b8e07f189610fd620c1ab9f93f9e78643b36ca` - https://github.com/lampepfl/dotty/pull/15416
@anatoliykmetyuk

**Comment by odersky** [comment]
@szymon-rd Thanks for the bisect! That would have been much harder to diagnose otherwise.
