### ISSUE TITLE
Compile shows weird message: `assertion failed: asTerm called on not-a-Term val <none>`

### ISSUE THREAD

**Issue by lenguyenthanh** [lampepfl/dotty#17556]
## Compiler version

I tested on `3.2.2`, `3.3.0-RC6` and `3.nightly`

## Minimized code

```Scala
//> using scala 3.2.2

trait FromString[A]:
  def parse(s: String): Either[String, A]

sealed trait Uci:

  case class Move(from: String, to: String) extends Uci

object Uci extends FromString[Uci]:
	def parse(s: String): Either[String, Uci] = ???

```

or in [scastie](https://scastie.scala-lang.org/WBpQsaZNSzihXknB2WQsHQ)

## Output (click arrow to expand)
<details>
Compiling project (Scala 3.2.2, JVM)
exception occurred while compiling /Users/tle/git/lichess/scripts/DottyBroke.scala
Error compiling project (Scala 3.2.2, JVM)
Error: Unexpected error when compiling project_ed944f97cf-10493a1c22: 'assertion failed: asTerm called on not-a-Term val <none>'
Compilation failed
</details>

## Expect

I expect a better error message.

**Comment by s5bug** [comment]
Further minimized:
```scala
// must be sealed
// must be trait (not class)
sealed trait A {
  // must be `object` or `case class`
  case class X() extends A
}

// companion object must exist
object A
```

Note that the above should not throw an error, as the following does not:
```scala
sealed trait A {
  case class X() extends A
}

val a = new A {}

a.X()
a.X().X()
a.X().X().X()
```
