### ISSUE TITLE
Changed error message between patch versions

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#17596]
## Compiler version

3.3.1-RC1

## Minimized code

```Scala

type Structural = {
    def foo(): Int
}
class Foo { def foo(): Int = 42 }
new Foo().asInstanceOf[Structural].foo()
```

## Output

```
Found:    Structural
Required: Selectable | Dynamic
```

## Expectation

Previously (3.3.0) it was:

```
Found:    Structural
Required: Selectable
```

**Comment by tgodzik** [comment]
> Error messages are allowed to change in patch versions. Otherwise we would never be able to improve them to improve developer experience. Are you running into something specific?

I just wanted to make sure it's expected. Better safe than sorry and especially that we were discussing compatibility a lot recently. We can close it if it is the desired behaviour.

**Comment by odersky** [comment]
OK, closing it then.
