### ISSUE TITLE
Inconsistency when typing `Int | Char`

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1759]
Noticed that:

```scala
scala> List(1, 2, '3')
val res0: List[Int] = List(1, 2, 51)
scala> 1 | '3'
val res1: Int = 51

// whereas:
scala> List(1, 2, "three")
val res2: List[Int | String] = List(1, 2, three)
```

Since the type is erased to `java.lang.Integer` maybe this makes sense - but shouldn't the type be kept until erasure at least? Seems somewhat surprising...

**Comment by DarkDimius** [comment]
It's due to what previously was weak subtyping, that is now called 
harmonization, if I recall correctly. Look for 'harmonize'. It will convert 
primitive constants to simplify a type.

**Comment by felixmulder** [comment]
Interesting - thanks, I'll have a look :)

**Comment by smarter** [comment]
Closing since the behavior is expected.
