### ISSUE TITLE
PatDef desugaring problem

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1773]
Following code compiles fine in scalac but failed to compile in dotty. The cause is mostly like to be unmatched cases when desugaring patdef, as in #1748 .

```Scala
object Test {
  implicit class Foo(sc: StringContext) {
    object q {
      def unapply(arg: Any): Option[(Any, Any)] =
        Some((sc.parts(0), sc.parts(1)))
    }
  }

  def main(args: Array[String]): Unit = {
    val q"class ${name: String} extends ${parent: String}" = new Object
    println(name)
    println(parent)
  }
}
```

**Comment by DarkDimius** [comment]
Akaik quasiqote desugaring in scalac relies on non-specified details of 
desugaring.

**Comment by DarkDimius** [comment]
Cc @densh

**Comment by liufengyun** [comment]
@DarkDimius it seems that adding a case for `Block` in `Desugar#getVariables` fix the problem, though there's another problem in RefChecks.

**Comment by xeno-by** [comment]
@liufengyun What's the problem with RefChecks that you were referring to in the last comment?
