### ISSUE TITLE
Some `-Wnonunit-statement` can't be silenced with `@annotation.nowarn`

### ISSUE THREAD

**Issue by mrdziuban** [lampepfl/dotty#17741]
## Compiler version

3.3.1-RC1

## Minimized code

```scala
<foo>bar</foo>: @annotation.nowarn("msg=unused value")
```

## Output

```scala
-- [E176] Potential Issue Error: test.scala:1:5 --------------
1 |  <foo>bar</foo>: @annotation.nowarn("msg=unused value")
  |       ^
  |       unused value of type xml.NodeBuffer
```

## Expectation

The `nowarn` annotation should silence the warning. I've also tried using a `-Wconf` compiler option but still no luck.

I said "some" in the title because the issue doesn't happen for all non-Unit statements. I initially came across it with XML-literals in my code and found that it doesn't happen for other simple statements, e.g. this works properly

```scala
scala.util.Try(1): @annotation.nowarn("msg=unused value")
```

**Comment by jchyb** [comment]
This appears to be closely related to #17735 (`-Wnonunit-statements` reuses some `-Wvalue-discard` logic, as I understand it)

Here, the annotation also stops working only when `-Xfatal-warnings` is used, but works correctly otherwise. `scala-cli` minimization (with a dependency):

```scala
//> using scala "3.3.1-RC1"
//> using dep "org.scala-lang.modules::scala-xml:2.1.0"
//> using option "-Wnonunit-statement", "-Xfatal-warnings"
def example() = 
  <foo>bar</foo>: @annotation.nowarn("msg=unused value")
```

**Comment by amumurst** [comment]
Also ran into this with scala-xml. I don't really see why it should be giving a warning at all and would consider it a bug too.
