### ISSUE TITLE
Spec: Are blocks allowed in patterns?

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1774]
Scalac doesn't parse following programs syntactically, but support it if it's synthesized.

Dotty accepts the code syntactically, but the typer generates a typing error.

```Scala
object Test {
  val a = (3, 4) match {
    case ({name: Int}, {parent: Int}) => (name, parent)
  }

  val name = a._1
  val parent = a._2
}
```

Error message:

```
-- Error: examples/block.scala -------------------------------------------------
6 |  val name = a._1
  |             ^
  |             cyclic reference involving value a
-- Error: examples/block.scala -------------------------------------------------
7 |  val parent = a._2
  |               ^
  |               cyclic reference involving value a
-- Error: examples/block.scala -------------------------------------------------
3 |    case ({name: Int}, {parent: Int}) => (name, parent)
  |                                          ^^^^
  |                                        cyclic reference involving value a

three errors found
```

**Comment by julienrf** [comment]
Support could be useful for this kind of stuff:

~~~ scala
(3, 4) match {
  case { val single = MyTupleExtractor(Snd); single(4) } => …
}
~~~

(It makes it possible to manipulate extractors in rhs position, for instance to configure them)

**Comment by julienrf** [comment]
But I’m not sure it is worth it… :)

**Comment by liufengyun** [comment]
The implementation of Quasiquote in scala.meta ([link](https://github.com/scalameta/scalameta/blob/master/scalameta/quasiquotes/src/main/scala/scala/meta/internal/quasiquotes/ReificationMacros.scala#L411)) relies on anonymous extractors as follows:

```Scala
          new {
            def unapply(input: Joy) = {
              ..$preamble
              input match {
                case $lifted => $thenp
                case _       => $elsep
              }
            }
          }.unapply(..$args)
```

which gets expanded to a block:

```Scala
      {
          class $anon {
            def unapply(input: Joy) = {
              ..$preamble
              input match {
                case $lifted => $thenp
                case _       => $elsep
              }
            }
          }

         new $anon
      }.unapply(..$args)
```

**Comment by odersky** [comment]
I think it would be good to allow this! Needs a spec change, though.

**Comment by liufengyun** [comment]
As a side note, we don't need this feature in order to implement Quasiquote in dotty. The quasi quote in Dotty now pass all regression set in scalameta.

**Comment by liufengyun** [comment]
Close this for now, I don't think it's a good idea to have blocks in patterns, the code is not readable.

**Comment by propensive** [comment]
It seems like it would open up a lot of new and interesting possibilities, though I'm a little scared about what should and shouldn't be allowed...
