### ISSUE TITLE
Don't demand explicit types for local implicit vals

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#1784]
A local implicit val can be referred to only from text following the valdef. Therefore, it
does not need an explicit type for type inference reasons. By allowing to elide the type
we make porting from Scala 2.x easier and avoid busywork.

**Comment by odersky** [comment]
Here's what is currently rejected:

     def f() = {
        implicit val s: String = "x"
        implicitly[String]
     }

**Comment by olafurpg** [comment]
To further motivate this change, it appears to be quite common to define local implicit vals. Examples:

- Scala.js https://github.com/scala-js/scala-js/blob/2b34d36f4a698cb4916cdefd4bcb3e0a2eb5d91e/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L601
- Monix:
https://github.com/monix/monix/blob/07713b5179265022c795a1618d7d0af9b0c34a33/monix-cats/shared/src/test/scala/monix/cats/tests/BaseLawsSuite.scala#L195
- Akka: https://github.com/akka/akka/blob/b8e76586391fdf4c5013bde9198f032906f0b8c1/akka-stream-tests/src/test/scala/akka/stream/scaladsl/FlowMapAsyncSpec.scala#L50
