### ISSUE TITLE
Broken in-macro by-index access for tuples constructed with *:

### ISSUE THREAD

**Issue by chuwy** [lampepfl/dotty#17923]
## Compiler version

3.3.0

## Minimized code

I have the following macro, that is basically doing something with tuple elements based on their position:

```scala
  transparent inline def test[C <: NonEmptyTuple](c: C): Any =
    ${ testImpl[C]('c) }
  private def testImpl[C <: NonEmptyTuple : Type](using Quotes)(cExpr: Expr[C]): Expr[Any] =
    import quotes.reflect.*

    val parts = TypeRepr.of[C] match
      case AppliedType(TypeRef(_, _), ins) =>
        ins.zipWithIndex.map { (_, x) =>
          Select.unique(cExpr.asTerm, s"_${x + 1}").asExpr
        }

    Expr(42)  // I don't even use the above Exprs
```

And it works fine for tuples with arity >1:

```
scala> test((1,"foo"))
val res0: Int = 42
```

## Output

But broken for `Tuple1`:

```scala> test(1 *: EmptyTuple)
-- [E008] Not Found Error: -----------------------------------------------------
1 |test(1 *: EmptyTuple)
  |               ^^^^^^^^^^^^^^^
  |value _1 is not a member of Int *: EmptyTuple.type, but could be made available as an extension method.
  |
  |The following import might fix the problem:
  |
  |  import cats.Show.Shown.mat
  |
1 error found
```

## Expectation

I expect to have an index-based access in macro because I do have it in usual Scala code:

```
scala> (1 *: EmptyTuple)._1
val res1: Int = 1
```

**Comment by chuwy** [comment]
Ok, I was slightly wrong. It's not `Tuple1` to blame here, but `*:` constructor.

`test(Tuple1(1))` works, but `test("foo" *: 42 *: EmptyTuple)` doesn't.

**Comment by nicolasstucki** [comment]
This is a fundamental limitation of generic tuples. The type `Tuple1[T]` is a subtype of `T *: EmptyTuple` but not the other way around. Therefore `_1` is not a member of `T *: EmptyTuple`. There are situations while typing where the compiler does the conversion between the types to make the `_1` member available. 

The solution is to use `productElement(0)` on these tuples. This method gets optimized to `_1` if the tuple is of known size.

**Comment by chuwy** [comment]
Ok, if understood it right - there's some special step in the compiler that transforms `A *: EmptyTuple` into `Tuple1[A]`, but macro expands before this step and `_1` is unavailable at that moment.

Feel free to close the ticket if it's not a bug and not going to be changed, although I wish it was more obvious.
