### ISSUE TITLE
Nightly docs are missing Scala 3 parts of standard library

### ISSUE THREAD

**Issue by Florian3k** [lampepfl/dotty#17964]
Nightly docs https://dotty.epfl.ch/api/index.html are missing Scala 3 additions to stdlib (`compiletime`, `deriving`, `quoted`, `Tuple`, `CanEqual`, `CanThrow` etc)

Bisect points to https://github.com/lampepfl/dotty/pull/17526

**Comment by Florian3k** [comment]
Background:
Scaladoc (`generateScalaDocumentation` and `generateStableScala3Documentation` precisely) uses results of building `stdlib-bootstrapped` (and few others) to generate documentation:
Relevant fragments from `Build.scala`:
For `generateScalaDocumentation`:
https://github.com/lampepfl/dotty/blob/89de88126e19b31f7eb22a2bff22a7a780a6a973/project/Build.scala#L2016-L2020
For `generateStableScala3Documentation`:
https://github.com/lampepfl/dotty/blob/89de88126e19b31f7eb22a2bff22a7a780a6a973/project/Build.scala#L2075-L2079

After #17526 `stdlib-bootstrapped` no longer contains Scala 3 parts of stdlib, so we need another source of those.

**Comment by Florian3k** [comment]
I attempted to resolve this by adding `scala3-library-bootstrapped` to scaladoc input files:
```diff
val dottyJars: Seq[java.io.File] = Seq(
  (`stdlib-bootstrapped`/Compile/products).value,
  (`scala3-interfaces`/Compile/products).value,
  (`tasty-core-bootstrapped`/Compile/products).value,
+ (`scala3-library-bootstrapped`/Compile/products).value,
).flatten
```
```diff
Seq(
  s"out/bootstrap/stdlib-bootstrapped/scala-$version-bin-SNAPSHOT-nonbootstrapped/classes",
  s"tmp/interfaces/target/classes",
  s"out/bootstrap/tasty-core-bootstrapped/scala-$version-bin-SNAPSHOT-nonbootstrapped/classes",
+ s"out/bootstrap/scala3-library-bootstrapped/scala-$version-bin-SNAPSHOT-nonbootstrapped/classes",
)
```
But that fails with the following error after running scaladoc:
```
-- Error: library/src/scala/quoted/ToExpr.scala:425:27 -------------------------
425 |      '{ BigDecimal(${Expr(x.toString)}) }
    |                           ^^^^^^^^^^
    |          method toString in class BigDecimal does not take parameters
```

**Comment by nicolasstucki** [comment]
What I am working on is generating TASTy for the Scala 2 stdlib. What you seem to be missing the Scala 3 library. Adding `scala3-library-bootstrapped` seems to be the correct direction.

**Comment by nicolasstucki** [comment]
I see what happened. The docs are consuming the artifacts of `stdlib-bootstrapped` to get TASTy from the Scala 2 library. It used to compile all Scala 2 and Scala 3 sources together (before #17526). These TASTy were not supposed to be stable enough to be consumed by any tool. I guess that it was good enough for a first version of the docs. What I am currently working on is to make these TASTy stable (align perfectly with the Scala 2 signatures).

Now, to fix this issue we have two alternatives

1. (quick fix) we create a new version of `stdlib-bootstrapped` that [includes the Scala 3 sources](https://github.com/lampepfl/dotty/pull/17526/files#diff-539d15a8d5ba9a01a1724604b56cadf6851c57ec68dcf75a5073b6255d182de7L939) and compiles without [-Yscala2-stdlib](https://github.com/lampepfl/dotty/pull/17526/files#diff-539d15a8d5ba9a01a1724604b56cadf6851c57ec68dcf75a5073b6255d182de7R940) (signature patches).
2. Scaladoc depends on both `stdlib-bootstrapped` and `scala3-library-bootstrapped`

We need to get to (2) at some point. The question is if this is simple or if we should have a quick patch (1) to make the documentation work while we figure out the details. I will open a PR for (1) and we can merge it if needed.

**Comment by nicolasstucki** [comment]
```diff
- '{ BigDecimal(${Expr(x.toString)}) }
+ '{ BigDecimal(${Expr(x.toString())}) }
```
seems to workaround the issue in scaladoc
