### ISSUE TITLE
Whitelisting scala.Tuple1 fails to compile.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#1797]
The error message is:
```scala
19 |case class Tuple1[@specialized(Int, Long, Double) +T1](_1: T1)
   |                                                       ^
   |                                                       value _1 is already defined as method _1: => T1
```

The same happens with all the 22 tuples.

**Comment by odersky** [comment]
Yes, dotty will use _1, _2, automatically for getters. So one needs to use a different name for the field. Or else special case in case class desugarings.

**Comment by odersky** [comment]
I wonder why PR's don't change the status anymore.
