### ISSUE TITLE
fewerBraces example does not actually work

### ISSUE THREAD

**Issue by Sporarum** [lampepfl/dotty#18014]
## Compiler version

Scala 3.3.0

## Minimized code & Output

```Scala
List(1,2,3).map:
  x => // error: indented definitions expected, identifier x found
    val y = x - 1
    y * y
```
https://scastie.scala-lang.org/2v7yp07mQLicgj9PPuC46g

Taken from [optional braces for method arguments](https://docs.scala-lang.org/scala3/reference/other-new-features/indentation.html#optional-braces-for-method-arguments)

### More Minimised
```scala
List(1,2,3).map:
  x => // error: indented definitions expected, identifier x found
    x
```
https://scastie.scala-lang.org/uzRJEI6wTsCrQDAwucv8cg

## Expectation
Should not throw an error
(or reference should be updated)

**Comment by Sporarum** [comment]
@mbovel Potenitally small enough for a spree ?

**Comment by szymon-rd** [comment]
Should it actually work? The correct syntax right now is
```scala
List(1,2,3).map: x => 
    val y = x - 1
    y * y
```

**Comment by Sporarum** [comment]
That's why it's still "needs triage", no matter if it's a documentation or an implementation issue, both are on this repo ^^

**Comment by Sporarum** [comment]
In this case, the sip agrees with the reference:
https://docs.scala-lang.org/sips/fewer-braces.html

So I would consider this an implementation bug
(But I don't have a strong opinion on that)

**Comment by odersky** [comment]
I think it's an implementation bug

**Comment by odersky** [comment]
In fact, this works in 3.3.1 RC1.

**Comment by Sporarum** [comment]
Does it, here's what it gives me in scastie with 3.3.1-RC1:
```scala
List(1,2,3).map:
  x => // indented definitions expected, identifier x found
    x
```
https://scastie.scala-lang.org/1ke6Wbu5TYCLR9fwVuIShA

Note that some indent based things behave differently toplevel than they do nested in a block

**Comment by odersky** [comment]
It works in the REPL and in a standalone file. Maybe scastie is not on the latest version yet?

**Comment by som-snytt** [comment]
FWIW
```
➜  snips ~/projects/dotty/bin/scalac -d /tmp i18014.scala
➜  snips ~/projects/dotty/bin/scalac -version
Scala compiler version 3.3.2-RC1-bin-SNAPSHOT-git-8948092 -- Copyright 2002-2023, LAMP/EPFL
```
Just trying to keep up.

**Comment by Sporarum** [comment]
I could not replicate either, so I opened a PR adding relevant tests (which will automatically close this issue)

**Comment by szymon-rd** [comment]
@Sporarum Scastie has some more problems, even with basic examples: https://scastie.scala-lang.org/5B8ER9m9RWyec8LXSzLRow 
I reported it to @tgodzik , it should be fixed soon

**Comment by Sporarum** [comment]
I see, thank you !
