### ISSUE TITLE
Misleading compile error message in wildcard exports

### ISSUE THREAD

**Issue by antognini** [lampepfl/dotty#18031]
## Compiler version
3.3.0

## Minimized code
```Scala
object A:
  val x, y, z = 0

object B:
  export A.{*, x as _} // compile error at this line
```

## Output

```scala
named imports cannot follow wildcard imports
  export A.{*, x as _}
```

## Expectation
The compiler correctly stops, but there are no import statements involved; the error message should be

```scala
named exports cannot follow wildcard exports
  export A.{*, x as _}
```

**Comment by odersky** [comment]
This could be a good first issue for a someone joining a spree.

**Comment by mbovel** [comment]
This is where the error is emitted: https://github.com/lampepfl/dotty/blob/ed319e8a41ef46ea5d7db35f3608eb17d8bbe7d3/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L3522

`importExpr` is called from: https://github.com/lampepfl/dotty/blob/ed319e8a41ef46ea5d7db35f3608eb17d8bbe7d3/compiler/src/dotty/tools/dotc/parsing/Parsers.scala#L3422

**Comment by mbovel** [comment]
@clavigne as this is your first Spree, welcome!

To get started hacking on the Dotty codebase, you will need to clone it, compile it and open it in VS Code using the following commands:

```bash
git clone https://github.com/lampepfl/dotty.git
cd dotty
sbt compile
code .
```

Then you will need to setup Metals to use the SBT build server. To do it, run the "Switch Build Server" [VS Code command](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) (by default the shortcut to open the VS Code command palette is `control-⇧-P`):

<img width="500" alt="image" src="https://github.com/lampepfl/dotty/assets/777748/e11d9354-c723-49d8-b333-a41816852a08">

<img width="500" alt="image" src="https://github.com/lampepfl/dotty/assets/777748/0724ae74-0ebd-42ef-a1b7-4d17678992b4">

To learn more: https://dotty.epfl.ch/docs/contributing/getting-started.html.

**Comment by clavigne** [comment]
Hi @mbovel, thanks for the instructions! I'll be using Intellij if that's ok, I'm much more familiar with it than with VSCode. Talk to you soon!
