### ISSUE TITLE
Preventing double definition for anonymous givens

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#18034]
I'm not clear if this is indeed a bug, or a limitation that can be lifted with or without a SIP.

## Compiler version

v3.3.0

## Minimized code
https://scastie.scala-lang.org/7m7S5DcCQYeZioWaeM2Uqw
```Scala
object One:
  trait Config

object Two:
  trait Config

given One.Config = ???
given Two.Config = ???
```

## Output

```scala
Double definition:
final lazy given val given_Config: Playground.One.Config in object Playground at line 9 and
final lazy given val given_Config: Playground.Two.Config in object Playground at line 10
```

## Expectation
I expect that the compiler will notice that both givens come from different paths and use them as a full name to prevent the double definition from occurring. So the compiler should desugar to:
```scala
final lazy given val given_One_Config = ???
final lazy given val given_Two_Config = ???
```

**Comment by sjrd** [comment]
You can give them explicit names in user space. That's the disambiguation mechanism that is offered.

If the compiler did something automatic, the name would not be stable across two versions of a library where the second version adds the second definition. That would be very bad.

**Comment by som-snytt** [comment]
The compiler could offer a quick fix and rewrite. When you create a user name, they offer a disambiguating fresh name.

**Comment by soronpo** [comment]
> You can give them explicit names in user space.

Yeah, I'm aware.

> If the compiler did something automatic, the name would not be stable across two versions of a library where the second version adds the second definition. That would be very bad.

That's right, I haven't considered that. We could avoid that by always using the suggested desugaring for `given X.Y.Z`, but this will break backward compatibility.

**Comment by som-snytt** [comment]
The issue could be closed as "not planned".
