### ISSUE TITLE
Compiler is overly secretive when it fails to infer the type of parameters

### ISSUE THREAD

**Issue by Sporarum** [lampepfl/dotty#18042]
## Compiler version

Scala 3.3.0

## Minimized code & Output

```Scala
def foo(x: Int) = 0

foo(x => x) // error:
// Missing parameter type
// I could not infer the type of the parameter x.
```
https://scastie.scala-lang.org/Te6OUPEKTnmMn304qWsPew

## Expectation

The fact the inference fails hides a more essential issue: 

There is no type such that this succeeds.

(Except if there are implicit conversions, with the following, inferring `Int` would work:
```scala
given Conversion[Int => Int, Int] = f => f(42)
```
)

Even considering this point, a better error would be something like:
```scala
Found: T1 => T1
Expected: Int

Where T1 could not be inferred
```

It displays more information, naturally leading the user to realize `x => x` would not work in any case

**Comment by Sporarum** [comment]
I might tackle this myself, if not, it might be a good candidate for a Spree, as it leads through multiple parts of the compiler with a clear goal in mind ?
(At least for the first exploratory phase)

**Comment by Sporarum** [comment]
Thinking more about this, I believe this would be helpful even in cases where the type to be inferred is underdetermined (as opposed to overdetermined like in my example)

(Which is why I renamed this issue)

**Comment by Sporarum** [comment]
This also has the upside of making the solution much simpler: No need to wonder about this question of under- vs over-determination, just always be precise

**Comment by odersky** [comment]
This looks very hard, and it's not clear at all the wins are large enough to warrant any complication in the compiler's code base. For me, `Missing parameter type` is perfectly fine as an error.

**Comment by Sporarum** [comment]
There are actually two things being proposed, which are different in terms of scope:
1. Detect and warn when a type is over-contrained, and inform the user appropriately (Very hard, possibly impossible)
2. Add no checks and just include more information in the error message, similar to what is done with "an extension method was tried, but" (Hopefully easy)

From this moment on, this issue is about 2.
(I will not open another issue for 1. but anyone is free to do so)

**Comment by som-snytt** [comment]
https://github.com/scala/bug/issues/11517

which I apparently opened on tpolecat's behalf.

In 2021, already a long time past, I noted that the message was not improved in Scala 3.

**Comment by mbovel** [comment]
@sankalpgambhir as this is your first Spree, welcome!

To get started hacking on the Dotty codebase, you will need to clone it, compile it and open it in VS Code using the following commands:

```bash
git clone https://github.com/lampepfl/dotty.git
cd dotty
sbt compile
code .
```

Then you will need to setup Metals to use the SBT build server. To do it, run the "Switch Build Server" [VS Code command](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) (by default the shortcut to open the VS Code command palette is `control-⇧-P`):

<img width="500" alt="image" src="https://github.com/lampepfl/dotty/assets/777748/e11d9354-c723-49d8-b333-a41816852a08">

<img width="500" alt="image" src="https://github.com/lampepfl/dotty/assets/777748/0724ae74-0ebd-42ef-a1b7-4d17678992b4">

To learn more: https://dotty.epfl.ch/docs/contributing/getting-started.html.
