### ISSUE TITLE
Bug when overriding toString without the parentheses.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#1804]
```scala
class Foo {
  override def toString: String = super.toString
}
object Bar {
  (new Foo).toString()
}
```
fails with
```scala
6 |    (new Foo).toString()
  |    ^^^^^^^^^^^^^^^^^^^^
  |    missing argument for parameter index of method apply: (index: Int)Char
```
Note that this happens when the `toString` is overriden without parentheses and then called with parentheses.

**Comment by odersky** [comment]
I think that's intentional. Put in another way: If `toString` was some other parameterless function you'd get the same error. So why treat `toString` differently?

**Comment by nicolasstucki** [comment]
The issue is that the `toString` is overriden a lot of times in the stdlib without the parentheses and then it is used with them. The current error message will not help users to understand why the can't call the method `toString()` of `Object`.
