### ISSUE TITLE
Scaladoc3 does not render wiki syntax italics

### ISSUE THREAD

**Issue by j-mie6** [lampepfl/dotty#18051]
## Compiler version
3.3.0

The `--doc-syntax:wiki` flag, or alternatively `@syntax wiki` can be used to tell scaladoc3 to render with the old scaladoc2-style wiki syntax instead of markdown. However, while `*hi*` or `_hi_` works with markdown syntax, `''hi''` does nothing with wiki syntax: with markdown syntax turned on it will literally render as `''hi''`, and with wiki syntax on it will render as `hi` but without italics.

## Expectation
With wiki syntax enabled, `''hi''` should behave the same as `*hi*`, `_hi_` in markdown syntax.

**Comment by Dedelweiss** [comment]
Hi @j-mie6, thank you for the Issue. I did a PR on the problem but with the "-comment-syntax:wiki" flag because I couldn't find "-doc-syntax:wiki" and that's the one that's closest to what you want.

**Comment by j-mie6** [comment]
Ah yes, you're right about the flag name, my mistake! (To be clear, this is the one I was using just wrote it down wrong in the issue)

**Comment by j-mie6** [comment]
as an aside @Dedelweiss, any reason why this works for the markdown syntax but not the wiki one? I would have assumed they shared code

**Comment by Dedelweiss** [comment]
Hello @j-mie6, that's a good question. I don't want to say anything wrong, but it seems to me that in the [**DocRenderer.scala**](https://github.com/lampepfl/dotty/blob/588a0b1e2928967273f8b1e96cd97006fd64e6b8/scaladoc/src/dotty/tools/scaladoc/renderers/DocRenderer.scala) file the code provides for separate management of **Markdown** syntax and **Wiki** syntax during the rendering process.

The **renderMarkdown** function is responsible for rendering Markdown syntax. It takes an **MdNode** as input and uses the **DocFlexmarkRenderer** to render the Markdown content.

The **renderElement** function is responsible for rendering Wiki syntax. It takes a **WikiDocElement** as input and performs various rendering operations depending on the type of element.

In the **renderDocPart** function, the **renderMarkdown** function is called when the input document is an **MdNode**, while the **renderElement** function is called when the input document is a **WikiDocElement**.
