### ISSUE TITLE
Hygiene of _root_ in user definitions

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#18050]
## Compiler version

3.3.0

## Minimized code

```Scala
package p {
  package _root_ {
    object X
  }
}
```

## Output

```scala
4 |    object X
  |    ^
  |    Not found: type X
```

## Expectation

`_root_` is an ordinary identifier except in a selection `_root_.x`, so this should just work, especially since the example below works.

Example is from https://github.com/scala/scala/blob/2.13.x/test/files/neg/t6217c.scala

Dotty compiles the example in https://github.com/scala/bug/issues/12508 where the user packaging is top-level:

```scala
package _root_ {
  class C {
    val _root_ = 42
  }
}
package _root_.p {
  class C
}
```
That produces packages `_root_` and `_root_.p`.

The latter example is "harder" in the sense that user's `_root_` does clash with any possible selection; that is, `_root_._root_.C` is required to disambiguate.

Of course, no one writes code like this, but maybe it indicates an issue with lookups for the definition of `object X`.

**Comment by odersky** [comment]
It's because of this clause in `Typer.typedIdent`:

```scala
    // Shortcut for the root package, this is not just a performance
    // optimization, it also avoids forcing imports thus potentially avoiding
    // cyclic references.
    if (name == nme.ROOTPKG)
      return tree.withType(defn.RootPackage.termRef)
```
I am not sure it's worth to complicate the code to do something different for code that nobody writes anyway. @smarter WDYT?
