### ISSUE TITLE
LazyVal is using deprecated `staticFieldOffset`

### ISSUE THREAD

**Issue by He-Pin** [lampepfl/dotty#18060]
Which should be replaced with VarHandle.

**Comment by odersky** [comment]
Not sure we can do that as long as we still allow builds Java 8?

**Comment by He-Pin** [comment]
Start jdk 18, this method is deprecated.

**Comment by szymon-rd** [comment]
There is this issue already: https://github.com/lampepfl/dotty/issues/15387. We cannot get rid of Unsafe, as we support Java 8. We can utilize the -release flag and use VarHandle when java platform version > 8.

**Comment by odersky** [comment]
Closing as duplicate then.
