### ISSUE TITLE
Contextual vararg parameters

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#18090]
## Compiler version

3.3.2-RC1-bin-20230627-588a0b1-NIGHTLY and before

## Minimized code

```scala
def foo(using xs: Int*) = xs
val f = foo
```

## Output
```scala
[error] UsingVarargs.scala:2:12
[error] no implicit argument of type Int* was found for parameter xs of method foo
[error] val f = foo
[error]            ^
```

## Expectation

There seems to be no way to define an instance of a vararg type, e.g. `given Int* = 0` won't work.
Even if one defines a given instance of a corresponding non-vararg type or a type wrapped into a `Seq` (`given Int = 0` or `given Seq[Int] = Seq(0)`) it won't be picked by the implicits resolution. The only way to pass such parameter seems to be `foo(using 0)`.
Taking that into account it seems reasonable to raise a warning when a user defines a `using` parameter with a vararg type.

**Comment by nicolasstucki** [comment]
This should be an error. The signature is non-sensical as we could find no implicit or the same one and provide it an arbitrary number of times.

**Comment by nicolasstucki** [comment]
This should probably be checked while typing the `def`.

**Comment by Kordyjan** [comment]
What's funny is that this function is still usable:

```scala
foo(using 1, 2, 3)
```

works just fine. I agree that declarations like this are nonsensical and should be either a warning on an error.
