### ISSUE TITLE
Type of package

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#18109]
## Compiler version

3.3.0, 3.3.2-RC1-bin-20230629-90c59bd-NIGHTLY

## Minimized code

```scala
package foo {}

package bar {
  object Test {
    def qux[A] = 123
    def main(args: Array[String]): Unit = {
      val y = qux[foo.type]
      val x = valueOf[foo.type]
    }
  }
}
```

## Compilation output

```scala
Warning: mocking up superclass for module class foo
```

## Runtime output

```scala
Exception in thread "main" java.lang.NoClassDefFoundError: foo
        at bar.Test$.main(PackageType.scala:8)
        at bar.Test.main(PackageType.scala)
Caused by: java.lang.ClassNotFoundException: foo
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 2 more
```

## Expectation

Should it be possible to refer to the type of a package at all? It seems harmless if one treats it as a phantom type (the snippet doesn't crash at runtime if `val x = valueOf[foo.type]` gets commented out but still leaving the invocation of `qux[foo.type]`). On the other hand the compiler sees such types as subtypes of `Singleton` and tries to provide a given instance of `ValueOf` for them.
Neither scala 3.2.2 nor 2.13.11 allow referring to types of packages as shown below:
* scala 3.2.2
```scala
[error] ./PackageType.scala:7:19
[error] package foo is not a value
[error]       val y = qux[foo.type]
[error]                   ^^^
[error] ./PackageType.scala:8:23
[error] package foo is not a value
[error]       val x = valueOf[foo.type]
[error]                       ^^^
```
* scala 2.13.11
```scala
[error] ./PackageType.scala:7:15
[error] type arguments [foo.type] do not conform to method qux's type parameter bounds [A]
[error]       val y = qux[foo.type]
[error]               ^^^^^^^^^^^^^
[error] ./PackageType.scala:8:15
[error] type arguments [foo.type] do not conform to method valueOf's type parameter bounds [T]
[error]       val x = valueOf[foo.type]
[error]               ^^^^^^^^^^^^^^^^^
```

@odersky should we keep the possibility to refer to package types but make it safe at runtime or should this be disabled? Would allowing such references actually require a change in the language specification (introduced by a SIP)?

**Comment by odersky** [comment]
I think it should be forbidden. Packages are not values, so it makes no sense to define a singleton type for them. I wonder how it regressed from 3.2.2, though?

**Comment by prolativ** [comment]
Output from the bisect script:
```
Last good release: 3.3.0-RC1-bin-20221209-231f9ab-NIGHTLY
First bad release: 3.3.0-RC1-bin-20221213-5929a50-NIGHTLY

bisect found first bad commitPrevious HEAD position was ebb2b223ce Don't search implicit arguments in singleton type prefix
```
which seems to point here https://github.com/lampepfl/dotty/commit/ebb2b223ceee1eefc6789dc3c844a5361004d973
