### ISSUE TITLE
Regression in implicit resoultion for arguments passed by name

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18123]
Regression found in Open Communtiy Build in 2 projects:
- stryker-mutator/weapon-regex - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/5426571795/jobs/9870242097) - reproduced below
- typelevel/kittens	- [build logs](https://github.com/VirtusLab/community-build3/actions/runs/5426571795/jobs/9870054515)

## Compiler version
3.3.2-RC1-bin-20230622-9f15be2-NIGHTLY

Bisect points to eb38e1f0fc38313ab17969a74664618900ace2e9

## Minimized code

```Scala

trait P[+T]

extension [T](inline parse0: P[T]) {
  inline def |[V >: T](inline other: P[V]): P[V] = ???
}

// Works if: 
// - parse0 is passed by value or
// - when rep has empty argument list, i.e:  def rep[V]()(using repeater: Implicits.Repeater[T, V]): P[V]
extension [T](inline parse0: => P[T]) {
  inline def rep[V](inline min: Int = 0)(using repeater: Implicits.Repeater[T, V]): P[V] = ???
}

object Implicits {
  trait Repeater[-T, R]
  object Repeater {
    implicit def GenericRepeaterImplicit[T]: Repeater[T, Seq[T]] = ???
  }
}

sealed trait RegexTree
abstract class Node extends RegexTree
class CharClassIntersection() extends Node

def classItem: P[RegexTree] = ???
def charClassIntersection: P[CharClassIntersection] = ???

def x = {
  (charClassIntersection.rep() | classItem.rep())
}
```

## Output

```scala
-- [E172] Type Error: /Users/wmazur/projects/dotty/bisect/main.scala:31:33 -----
31 |  (charClassIntersection.rep() | classItem.rep())
   |                                 ^^^^^^^^^^^^^^^
   |No given instance of type Implicits.Repeater[RegexTree, V] was found.
   |I found:
   |
   |    Implicits.Repeater.GenericRepeaterImplicit[T]
   |
   |But method GenericRepeaterImplicit in object Repeater does not match type Implicits.Repeater[RegexTree, V]
   |
   |where:    V is a type variable with constraint <: Seq[CharClassIntersection]
```

## Expectation
Should compile

**Comment by julienrf** [comment]
@WojciechMazur I've submitted a possible fix in #18130. Is there an easy way to confirm that it fixes both projects weapon-regex and kittens?

**Comment by WojciechMazur** [comment]
@julienrf I've started a runs for them in Open CB using your PR:
- https://github.com/VirtusLab/community-build3/actions/runs/5454049792 
- https://github.com/VirtusLab/community-build3/actions/runs/5454057437

**Comment by julienrf** [comment]
Thank you! They both passed the CI
