### ISSUE TITLE
Protected top-level definition can no longer be referenced in other file

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18124]
Regression found in the Open Community Build in: 
- tinkoff/oolong - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/5426571795/jobs/9871305518) - reproduction below

## Compiler version
3.3.2-RC1-bin-20230629-90c59bd-NIGHTLY
Bisect points to 7c728bb3292e99668a01b167a66ba336d881ba66 from #18057

## Minimized code

```Scala
// definition.scala
package oolong.bson

trait BsonValue
protected def merge(
    base: BsonValue,
    patch: BsonValue,
    arraySubvalues: Boolean = false
): BsonValue = ???
```

```Scala
// usage.scala
package oolong.bson

extension (bv: BsonValue)
  def :+(other: BsonValue): BsonValue = merge(other, bv, false)

```

## Output

```scala
-- [E173] Reference Error: /Users/wmazur/projects/dotty/bisect/usage.scala:5:40 
5 |  def :+(other: BsonValue): BsonValue = merge(other, bv, false)
  |                                        ^^^^^
  |method merge in package oolong.bson cannot be accessed as a member of (oolong.bson: oolong.bson.type) from module class usage$package$.
```

## Expectation
Probably should compile

**Comment by odersky** [comment]
Yes, should compile as long as the reference is in the same package as the definition.

**Comment by dwijnand** [comment]
Looks like the specs2 failure is the same issue: trying to access protected `matcher.ResultChecks.checkResultFailure`, while in the matcher package.
