### ISSUE TITLE
Support for dummy macros.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#1814]
In the standard library we have a couple of `def xx(): YY = macro ???`. 

scala/reflect/package.scala has 
```scala
private[scala] def materializeClassTag[T](): ClassTag[T] = macro ???
```

and scala/StringContext.scala has
```scala
def f[A >: Any](args: A*): String = macro ??? 
```

We will probably need to support this specific use case of macro just to support the standard library.

**Comment by smarter** [comment]
Note that these macros are defined in https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/reflect/FastTrack.scala#L45, I don't know if we want to use the same approach in dotty.

**Comment by liufengyun** [comment]
This is what I see how it could be done potentially:

```Scala
inline def materializeClassTag[T](): ClassTag[T] = meta { (implicit ctx: Context) =>
    val tp = dotty.tools.dotc.typer.Inferencing.fullyDefinedType(T.tpe, "ClassTag argument", T.pos)
    val clazz = tpd.clsOf(tp)
    q"scala.reflect.ClassTag[T]($clazz)"
}
```

As current implementation of macros are based on scala.meta, we have two kinds of trees: `meta trees` and `dotty trees`. Thus a conversion from dotty trees to meta trees is needed:

```Scala
inline def materializeClassTag[T](): ClassTag[T] = meta { (implicit ctx: Context) =>
    val tp = dotty.tools.dotc.typer.Inferencing.fullyDefinedType(T.tpe, "ClassTag argument", T.pos)
    val clazz = scala.meta.eden.toMeta(tpd.clsOf(tp), isTerm = false)    // conversion to meta tree
    q"scala.reflect.ClassTag[T]($clazz)"
}
```

Unfortunately, currently in meta block we don't have access to `implicit ctx: Context`.  As I understand, providing `ctx` to meta block is not in accord with the goal of scala.meta to have portable macros among compiler implementations.

Ideas @xeno-by ?

**Comment by liufengyun** [comment]
A little problem with the code above: `T.tpe` and `T.pos` will not type check, as `T` is a meta tree, instead of a dotty tree.

**Comment by smarter** [comment]
I don't think supporting `materializeClassTag` is needed in dotty.

**Comment by liufengyun** [comment]
Ah, I see, I missed some words in your comments in #1899 . I'll investigate how to implement `def f[A >: Any](args: A*): String `.

**Comment by xeno-by** [comment]
@liufengyun I'd suggest that we try to keep meta blocks platform-independent. Implementing them otherwise would go against the primary purpose of scala.meta.

**Comment by xeno-by** [comment]
Speaking of classtag materialization, maybe we can intrinsify the `tpd.clsOf` call behind the standard `classOf[T]` method? So, instead of needing a dotty context, the meta block would just emit `q"_root_.scala.reflect.ClassTag[$T](_root_.scala.Predef.classOf[$T])"`?

**Comment by liufengyun** [comment]
Thanks @xeno-by , as @smarter commented, we don't need `materializeClassTag` in Dotty, it's already handled by the compiler. We only need to implement the `f` interpolator, I think it can be handled by syntactic def macros.
