### ISSUE TITLE
Don’t apply wildcard approximation to non-transparent inlines in 3.4

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#18174]
> I guess there would be another follow up to add the `3.4` source version and enable it there?

_Originally posted by @bishabosha in https://github.com/lampepfl/dotty/pull/18130#discussion_r1257922206_

Once we have a 3.4 branch, we should revert #18130.

**Comment by dwijnand** [comment]
Could you address this in time for 3.4.0-RC1 next week, please?
