### ISSUE TITLE
Error about Contextual function's parameter refer to its synthetic name without explantation

### ISSUE THREAD

**Issue by Sporarum** [lampepfl/dotty#18188]
## Compiler version

3.3.1-RC1

## Minimized code

```scala
class A1[T](action: A1[T] ?=> String = "")
```

## Output
```scala
-- [E081] Type Error: ----------------------------------------------------------
1 |class A1[T](action: A1[T] ?=> String = "")
  |                                       ^
  |                   Missing parameter type
  |
  |                   I could not infer the type of the parameter evidence$1.
  |                   What I could infer was: A1[<?>]
1 error found
```

## Expectation
The error mentions `evidence$1` which is not defined anywhere
(neither in user-facing code, nor in the error message)

This example was taken from `tests/neg/i11350.scala` in the compiler, but affects any `AnonymousFunctionMissingParamType` on contextual functions, and potentially other errors

**Comment by Sporarum** [comment]
It should be relatively straightforward to fix at least for `AnonymousFunctionMissingParamType`

**Comment by bishabosha** [comment]
as well as having a confusing error message, this seems to be a bug in inference because the following (obvious desugaring) is well typed:
```scala
class A1[T](action: A1[T] ?=> String = (a1: A1[T]) ?=> "")
```

**Comment by bishabosha** [comment]
perhaps we should make a separate issue about the infamous "I could not infer the type of the parameter foo$1"
