### ISSUE TITLE
Regression in `apache/incubator-pekko`

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18227]
Regression found in OpenCB for `apache/incubator-pekko` - build logs: https://github.com/VirtusLab/community-build3/actions/runs/5557868276/jobs/10152258051

## Compiler version
3.3.2-RC nightly
Works in 3.3.1-RC4

Bisect points to 607e4d59d93e4ceb0e46469923161516c4e04b60

## Minimized code
Error is present when referencing type with suffix `$` defined in different compilation unit.

```Scala
// repro_1.scala
object PekkoPduProtobufCodec$
```

```Scala
// repro_2.scala
@main def Test = {
  val x = PekkoPduProtobufCodec$
}
```

## Output

```scala
Loading Scala 3 binary from /Users/wmazur/projects/dotty/bisect/.scala-build/project_460e25f1fd-574c0e3b00/classes/main/PekkoPduProtobufCodec$.class. It should have been loaded from `.tasty` file. This `.tasty` file is missing. Try cleaning the project to fix this issue.
-- [E119] Type Error: /Users/wmazur/projects/dotty/bisect/main.test.scala:2:10 -
2 |  val x = PekkoPduProtobufCodec$
  |          ^^^^^^^^^^^^^^^^^^^^^^
  |          Java defined class PekkoPduProtobufCodec$ is not a value
2 errors found
```

## Expectation
Should compile

**Comment by nicolasstucki** [comment]
The Scala spec states that names in the source should not contain `$`.  These are reserved for code generation. Using a name with a `$` will have undefined behavior.

**Comment by nicolasstucki** [comment]
`PekkoPduProtobufCodec$` is probably breaking the assumption we need to be able to identify companion module names in https://github.com/lampepfl/dotty/commit/607e4d59d93e4ceb0e46469923161516c4e04b60#diff-4a6c49a16c6d9551222c4b7648eebeec96009ce5cb851c54fb13e94745a49a80R106-R114

**Comment by nicolasstucki** [comment]
This issue should be followed on https://github.com/apache/incubator-pekko/issues/491

**Comment by mdedetrich** [comment]
Does it make sense to create an issue so that scalac/doty actually refuses to compile identifiers that contain the `$` spec so we don't get such problems in the future (maybe with an added flag where you can override this for really exceptional cases)?

**Comment by nicolasstucki** [comment]
I would make it a warning.

**Comment by mdedetrich** [comment]
> I would make it a warning.

Should I file an issue?
