### ISSUE TITLE
Regression in tinkoff/oolong, missing type parameter in quotes

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18228]
## Compiler version
Works in 3.3.1-RC4 
Fails in 3.3.2-RC nightly 

Bisect points to 3c073792ba24d79c0adad2ad7534fbd0d6e390d0

## Minimized code

```Scala
import scala.quoted.*

case class QueryMeta[T](map: Map[String, String])

object QueryMeta:
  given [T]: FromExpr[QueryMeta[T]] = new FromExpr[QueryMeta[T]]:
    def unapply(expr: Expr[QueryMeta[T]])(using q: Quotes): Option[QueryMeta[T]] =
      import q.reflect.*
      expr match
        case '{ QueryMeta(${ map }: Map[String, String]) } =>
          map.value.map(QueryMeta[T].apply)
        case _ =>
          None
```

## Output

```scala
-- Error: /Users/wmazur/projects/dotty/bisect/main.scala:10:16 -----------------
10 |        case '{ QueryMeta(${ map }: Map[String, String]) } =>
   |                ^^^^^^^^^
   |Reference to T within quotes requires a given scala.quoted.Type[T] in scope.
   |
1 error found
```

## Workaround
```Scala
        case '{ QueryMeta[t](${ map }: Map[String, String]) } =>
```

## Expectation
It makes sense that quotes it fails when type parameter is failing, but the error message seems to not be very pricise here. It would make sense to make this code compile in 3.3.x for LTS source compatibility, and change semantics in 3.4.x

**Comment by nicolasstucki** [comment]
In https://github.com/lampepfl/dotty/commit/3c073792ba24d79c0adad2ad7534fbd0d6e390d0 we unintentionally fixed type inference for this pattern. Previously we wrongly inferred `'{ QueryMeta[Any](...) }` and now we infer `'{ QueryMeta[T](...) }`. Because we use this `T` in the quote pattern, we do need a given `Type[T]`. 

The correct fix for this code is
```diff
-  given [T]: FromExpr[QueryMeta[T]] = new FromExpr[QueryMeta[T]]:
+  given [T: Type]: FromExpr[QueryMeta[T]] = new FromExpr[QueryMeta[T]]:
```

Though the workaround is also fine
```scala
case '{ QueryMeta[t](${ map }: Map[String, String]) } =>
```
