### ISSUE TITLE
Type inference issues when using intersection types

### ISSUE THREAD

**Issue by IndiscriminateCoding** [lampepfl/dotty#18226]
## Compiler version

3.3.0

## Minimized code

```scala
trait F[-R]

trait Row[A]

def eliminateInt[R](f: F[R & Row[Int]]): F[R] = new F[R] {}

val x = new F[Row[Int] & Row[String]] {}

val _ = eliminateInt[Row[String]](x) // compiles OK when given explicit type
val _ = eliminateInt(x) // error!
```

## Output

```
Found:    (app.x : app.F[app.Row[Int] & app.Row[String]])
Required: app.F[app.Row[Int]]
```

## Expectation
I expect compiler to be able to infer `[R]` instantiation based on a type of a passed value.

**Comment by nicolasstucki** [comment]
I'm not sure if `eliminateInt` makes sense. Consider `eliminateInt[Row[Int] & Row[String]](x)` which is a correct type for `eliminateInt` but does not eliminate the Int.

**Comment by odersky** [comment]
I tried but #18235 got stuck with a zio problem, which someone else will need to debug.

**Comment by odersky** [comment]
@smarter unstuck #18235 with a minimization. So fixing efforts continue...
