### ISSUE TITLE
Backquoted `==` operator not treat as stable identifier during pattern match.

### ISSUE THREAD

**Issue by jilen** [lampepfl/dotty#18247]
## Compiler version

3.3.0

## Minimized code

```scala
sealed trait Op
object Op {
  case object `==` extends Op
}

def `is_==`(a: Op): true = {
  a match {
    case Op.`==` => true // won't compile
  }
}

```

Note other operators like `+`, `-` works just fine.

## Output

```
 Stable identifier required, but Playground.Op.== found
```

## Expectation
Should compile fine.

## Workaround
Bind it to a constant

**Comment by SethTisue** [comment]
It isn't obvious to me that we can just carve out an exception for this in the compiler unless we also change the spec?
