### ISSUE TITLE
Warning not issued for unused argument in function.

### ISSUE THREAD

**Issue by phrmoy** [lampepfl/dotty#18272]
## Compiler version

3.3.0

## Minimized code

```Scala
def func(x: Int) = 0

@main def runPlay = {
  println(func(1))
}
```

## Output

```scala
0
```

## Expectation

Having `-Wunused:all`, I would expect the compiler to warn about the unused argument `x:Int` in function `func`.

**Comment by jchyb** [comment]
Related (but different case): https://github.com/lampepfl/dotty/issues/17742

**Comment by Kordyjan** [comment]
Public methods are part of the API, so sometimes they require unused parameters to maintain binary compatibility.

**Comment by SethTisue** [comment]
> Public methods are part of the API, so sometimes they require unused parameters to maintain binary compatibility

Many codebases have no need to care about bincompat. Even for those that do, the situation of needing an unused parameter is probably fairly unusual, I think. So requiring a `@nowarn` in this case doesn't seem onerous to me.
