### ISSUE TITLE
Regression in alterationx10/opinionated-zio

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18277]
New regression found in the Open CB: https://github.com/VirtusLab/community-build3/actions/runs/5626149769/job/15249547099

## Compiler version
3.3.2-RC1-bin-20230720-98b452d-NIGHTLY 
Works in 3.3.1-RC4 
Bisect points to: 027923ce325ef1c4b487c2aeaf1c41a9771de5e3

## Minimized code

```Scala
import scala.deriving.*
import scala.deriving.Mirror.ProductOf

type UAnyType[T <: Tuple] = Tuple.Fold[T, Any, [x, y] =>> x | y]

inline def derived[A](using p: Mirror.ProductOf[A]) = {
    val deps: List[UAnyType[p.MirroredElemTypes]] = ???
    val a = deps.toArray
    // ctx: val a = p.fromProduct(Tuple.fromArray(deps.toArray))
    // In 3.3.0 uses ClassTag[Object]
}

```

## Output

```scala
-- [E172] Type Error: /Users/wmazur/projects/sandbox/main.scala:8:24 -----------
8 |    val a = deps.toArray
  |                        ^
  |No ClassTag available for B
  |
  |where:    B is a type variable with constraint >: UAnyType[p.MirroredElemTypes]
```

## Expectation
I'm not sure if this code should compile or should not.
In 3.3.0 this code was using `ClassTag[Object]` so if it worked user can potentially provide instance of `given ClassTag[UAnyType[p.MirroredElemTypes]] = ClassTag.AnyRef.asInstanceOf[...]` 
Alternatively the context of usage was to create an instance of `p` using `p.fromProduct`. Having a variant allowing to use List instead of Array should fix it (currently only Array, IArray and Product is allowed`

**Comment by odersky** [comment]
I think this code should not compile. There is no ClassTag.

**Comment by nicolasstucki** [comment]
The original code may be fixed with
```diff
- val a = p.fromProduct(Tuple.fromArray(deps.toArray))
+ val a = p.fromProduct(Tuple.fromArray((deps: List[Object]).toArray))
```
