### ISSUE TITLE
Missing unchecked warning when pattern matching on a type parameter

### ISSUE THREAD

**Issue by jedesah** [lampepfl/dotty#1828]
```
def remove[S](a: S | Int, f: Int => S):S = a match {
  case a: S => a
  case a: Int => f(a)
}

val t: Int | String = 5
val t1 = remove[String](t, _.toString)
```

This compiles fine, but at runtime, the call to `remove` will throw a `java.lang.ClassCastException` (Integer cannot be cast to String)

**Comment by jedesah** [comment]
It seems it has something to do with the use of a generic type because if I were to hardcode `remove` to `String` as follows:

```
def remove(a: String | Int):String = a match {
    case a: String => a
    case a: Int => a.toString
}

val t: Int | String = 5
val t1 = remove(t)
```

then no `ClassCastException`

**Comment by jedesah** [comment]
I may be able to have a look at this myself if someone can give a few pointers to where the problem might lie.

**Comment by senia-psm** [comment]
@jedesah in `scala 2.12.x` you'll get a warning:
```scala
scala> def unsafeCast[T](a: Any) = a match { case x: T => x; case _ => ??? }
<console>:11: warning: abstract type pattern T is unchecked since it is eliminated by erasure
       def unsafeCast[T](a: Any) = a match { case x: T => x; case _ => ??? }
                                                     ^
unsafeCast: [T](a: Any)T

scala> unsafeCast[String](1)
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
```
There is actually no typecheck here: `case a: S => a`.

**Comment by smarter** [comment]
Yes, pattern-matching on type parameters is unsafe and we're missing the warning, thanks for pointing that out

**Comment by jedesah** [comment]
@smarter Haha! Glad I could help!

**Comment by liufengyun** [comment]
This is the same issue as #3324, will be fixed together.
