### ISSUE TITLE
Type.of drops an opaque type info if macro called from the same level type type defined

### ISSUE THREAD

**Issue by chuwy** [lampepfl/dotty#18283]
## Compiler version
3.3.0, 3.3.1-RC4

## Minimized code
```scala
// Macro.scala
package test

import scala.quoted.*

object Macro:
  transparent inline def getType[T] =
    ${ getTypeImpl[T] }
  private def getTypeImpl[T: Type](using Quotes): Expr[Any] =
    import quotes.reflect.*
  
    val tpe = TypeRepr.of[T]
    val reprShow = tpe.show
    tpe.asType match
      case '[t] =>
        val typeShow = TypeRepr.of[t].show
        Expr((reprShow, typeShow))


// Aux.scala
package test

opaque type Id = Long

object Task:
  opaque type Title = String

def run =
  println((Macro.getType[Id], Macro.getType[Task.Title]))

// console
test.run
```

## Output

```scala
((test.Aux$package.Id,scala.Long),(test.Task.Title,test.Task.Title))
```

## Expectation

```scala
((test.Aux$package.Id,test.Aux$package.Id),(test.Task.Title,test.Task.Title))
```

I do expect to have the opaque type preserved in all situations. 

I still haven't managed to catch the exact conditions when it fails (not sure that "same level" is to blame). Here's another situation where the behavior doesn't match the expectation:

```scala
package test

opaque type Id = Long

object Task:
  opaque type Title = String

  def run =
    println((Macro.getType[Id], Macro.getType[Title]))
```

Output:

```
((test.Aux$package.Id,test.Aux$package.Id),(test.Task.Title,java.lang.String))
```

And with this `run` it has expected result:

```
println((Macro.getType[Id], Macro.getType[Task.Title]))   // Task.Title is better qualified
```

**Comment by nicolasstucki** [comment]
The [opaque type specification](https://docs.scala-lang.org/scala3/reference/other-new-features/opaques-details.html) states that for 

> ```scala
> opaque type T >: L <: U = R
> ```
> Inside the scope of the alias definition, the alias is transparent: T is treated as a normal alias of R.

This implies that in reference to an opaque type at the same level the is type defined, is seen as a type alias. Therefore it is fine if it is dealiased. 

Note that the dealiased only happens on the quoted pattern matching. In that case `t` is the a precise type that results on all the constraints found in the pattern itself. Which is clearly the dealiased type.

Furthermore, in both cases `Type.of[T]` and `TypeRepr.of[T]` return the reference to the opaque type. This implies that there is a way to see if the code referred to the opaque type (not guaranteed because of dealiassing).

**Comment by chuwy** [comment]
I think that would be an acceptable if there was no "not guaranteed" part at least. Because right now the outcome is just non-deterministic.

```
Macro.getType[Aux.Id]
```

and

```
Macro.getType[Id]
```

Provide different results (given that `Id` and `run` are defined at the same places and difference is just how we refer to the `Id` type) and just checked there's no reference to opaque type when I pass there `id`. 

Sorry if that sounds over-dramatic, but it's a huge letdown from opaque types - as result I cannot use them in my case classes at all, given that at any point the classes could be used in macros and compile-time error will be super hard (impossible for users) to debug.

**Comment by nicolasstucki** [comment]
What is the intended use case?

**Comment by chuwy** [comment]
[Example](https://github.com/foldables-io/skunk-tables/blob/08585c760f4dd441677a042f4496ef437c8b5998/core/src/test/scala/skunk/tables/Example.scala#L36) with [skunk-tables](https://github.com/foldables-io/skunk-tables) - if I define some member `id: Id` (with it being `opaque type Id = UUID`) and then try to do something with the member:

```
val x: Id = ???
table.get(_.id == id)
```

It complains that it expected `id` to be `UUID`, but it's in fact `Id`, so I was trying to use opaque types here as newtypes, but converting it back somewhere defeats the purpose. There are many places where I managed to fix it, e.g. I replaced in [quotidian](https://github.com/kitlangton/quotidian/blob/69cf59fb2dd6ae85bdd47e7fc4f3fc9e5988dadc/modules/core/src/main/scala/quotidian/syntax/package.scala#L141-L145):

```scala
  def tupleToList: List[quotes.reflect.TypeRepr] =
    import quotes.reflect.*
    self.asType match
      case '[t *: ts]    => TypeRepr.of[t] :: TypeRepr.of[ts].tupleToList
      case '[EmptyTuple] => Nil
```

To

```scala
def tupleToList: List[quotes.reflect.TypeRepr] =
  import quotes.reflect.*
  self match
    case AppliedType(TypeRef(ThisType(_),"*:"), List(head, tail)) if tail.show == "scala.Tuple$package.EmptyTuple" =>
      head :: Nil
    case AppliedType(TypeRef(ThisType(_),"*:"), List(head, tail @ AppliedType(_, _))) =>
      head :: tail.tupleToList
    case end if end.show == "scala.Tuple$package.EmptyTuple" =>
      Nil
```

But there are other places where I don't know how to get rid of `Type.of` and `asType`

**Comment by bishabosha** [comment]
> Sorry if that sounds over-dramatic, but it's a huge letdown from opaque types - as result I cannot use them in my case classes at all, given that at any point the classes could be used in macros and compile-time error will be super hard (impossible for users) to debug.

is it not really possible to define that opaque type somewhere else, (e.g. a nested object) and then re-export it from the scope where it was originally?

**Comment by chuwy** [comment]
> is it not really possible to define that opaque type somewhere else

This is what I did in the end, yes:

```scala
opaque type TaskId = UUID
object Task:
  type Id = TaskId
final case class Task(id: Task.Id)
```

It works, but my broader concern that other users (of skunk-tables, or generally any macro-heavy lib that reflects on product types and summons implicit for their members) will have hard times debugging that.

And even broader concern about opaque types in general. This is not the first time I hit a similar problem (https://github.com/lampepfl/dotty/issues/17211) and I'm wondering if my expectations of opaque types are wrong or nobody has raised this.

> Could you show a small self-contained example of where this goes wrong?

Do you mean without mentioned lib?

**Comment by nicolasstucki** [comment]
If you want to see the underlying type of `TaskId` anywhere, should you define it as `type TaskId` and just assume it is a `UUID`?

**Comment by bishabosha** [comment]
This would be more safe:
```scala
type TaskId = Task.Id
object Task:
  opaque type Id = UUID
final case class Task(id: Task.Id)
```
