### ISSUE TITLE
Regression in squeryl/squeryl, changed semantics of implicits import

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18316]
Regression found in Open Community Build for squeryl/squeryl, build logs - https://github.com/VirtusLab/community-build3/actions/runs/5695846723/job/15440936970

Double import of implicits excludes them from search path, or sets their priority to be lower then the inherited implicits.

## Compiler version
3.3.2-RC1-bin-20230724-ce1ce99-NIGHTLY 

Bisect points to 650f854ce0325b0090d0e8da10d53d4456f8d213

## Minimized code

```Scala
// squerel
import scala.language.implicitConversions
object squerel {
  trait EqualityExpression
  object PrimitiveTypeMode:
    implicit def intToTE(f: Int): TypedExpression[Int] = ???

  trait TypedExpression[A1]:
    def ===[A2](b: TypedExpression[A2]): EqualityExpression = ???
}

object scalactic {
  trait TripleEqualsSupport:
    class Equalizer[L](val leftSide: L):
      def ===(rightSide: Any): Boolean = ???

  trait TripleEquals extends TripleEqualsSupport:
    implicit def convertToEqualizer[T](left: T): Equalizer[T] = ???
}

import squerel.PrimitiveTypeMode._ // remove to make code compile
object Test extends scalactic.TripleEquals {
  import squerel.PrimitiveTypeMode._
  val fails: squerel.EqualityExpression = 1 === 1
}
```

## Output

```scala
-- [E007] Type Mismatch Error: /Users/wmazur/projects/dotty/bisect/main.scala:24:42 
24 |  val fails: squerel.EqualityExpression = 1 === 1
   |                                          ^^^^^^^
   |                                    Found:    Boolean
   |                                    Required: squerel.EqualityExpression
```

## Expectation
It should allow to compile the code. Change in order of implicits resolution should not be applied in 3.3.x releases.  

Additional feature requrest:
It would be great if we would be able to use both `def ===` methods - before regression it would only pick method from squerel, after the change only from scalactic. If possible it should  be able to compile following snippet: 
```
  val x: Boolean = 1 === 1
  val y: squerel.EqualityExpression = 1 === 1
```

**Comment by WojciechMazur** [comment]
Another project affected by the same issue (same bisect) is xuwei-k/optparse-applicative [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/5695846723/job/15441610788)

Reproduction, but not minimization
```Scala
//> using dep org.scalaz::scalaz-core:7.3.7
//> using options -Ykind-projector

import scala.language.implicitConversions
import scalaz.Monad

trait ParserM[R]

import scalaz.syntax.applicativePlus._ // remove or move to object ParserM import to compile
object ParserM {
  import scalaz.syntax.bind._
  def repro[A]: ParserM[List[A]] = {
    val x: ParserM[List[A]] = ???
    x.map(_ => ???)
  }

  implicit val parserMMonad: Monad[ParserM] = ???
} 
```

output: 
```Scala
[error] ./bisect/main.scala:14:5
[error] value map is not a member of ParserM[List[A]], but could be made available as an extension method.
[error] 
[error] The following import might make progress towards fixing the problem:
[error] 
[error]   import scalaz.Leibniz.subst
[error] 
[error]     x.map(_ => ???)
[error]     ^^^^^
```

**Comment by WojciechMazur** [comment]
Some project-wise bisects also points to the same feral commit. Here's the full list of affected projects: 
| Project | Version | Build URL | Notes |
| ------- | ------- | --------- | ----- |
| ghostdogpr/caliban | 2.2.1 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/5695846723/job/15445109908) |  |
| rssh/cps-async-connect | 0.9.17 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/5695846723/job/15444050764) |  |
| squeryl/squeryl | 0.10.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/5695846723/job/15440936970) | original issue  |
| thoughtworksinc/binding.scala | 12.2.0 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/5695846723/job/15440937919) |  Probably, bisect fails due to failing compiler build in one of commits, but it started to fail since the same nightly  |
| xuwei-k/optparse-applicative | 0.9.3 | [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/5695846723/job/15441610788) |  reproduced above |

**Comment by dwijnand** [comment]
Feral?
