### ISSUE TITLE
scala.compiletime.ops.long.S doesn't work

### ISSUE THREAD

**Issue by unkarjedy** [lampepfl/dotty#18342]
Related https://github.com/lampepfl/dotty/pull/13400

## Compiler version

3.3.1-RC4

## Minimized code
```Scala
@main def foo(): Unit =
  //This works:
  val value1: scala.compiletime.ops.int.S[0] = 1

  //This doesn't work:
  val value2: scala.compiletime.ops.long.S[0L] = 1L
```

## Output
Compiler generates error for `1L`:
<img width="758" alt="image" src="https://github.com/lampepfl/dotty/assets/3989292/53b9c644-f47c-4d82-aa7d-9eec110cf8fc">

## Expectation
No compilation error.
Type `scala.compiletime.ops.long.S[0L]` should be equal to `1L`

**Comment by unkarjedy** [comment]
JFTR previously found bug in a similar subsystem: https://github.com/lampepfl/dotty/issues/18340

**Comment by dwijnand** [comment]
Yeah, makes sense as https://github.com/lampepfl/dotty/blob/72f9d7afc3acfd8201e164da6608b99bb9218b64/compiler/src/dotty/tools/dotc/core/TypeComparer.scala#L1488

only considers ops.int, not also the equivalent in ops.long.  Seems like a simple fix.

**Comment by soronpo** [comment]
Is there a reason to keep `S[T]` as a special case instead of changing it to `S[T <: Int] = +[T, 1]` and `S[T <: Long] = +[T, 1L]` accordingly? We might get some performance penalty for something that relies solely on `S`, but it seems weird to have now that have such a wide variety of operations.

**Comment by sjrd** [comment]
`S[-1]` is not defined, but `+[-1, 1] =:= 0`. So `S` is *not* a special-case of `+[T, 1]`. Also I think `S[MaxValue]` is not defined but `+[MaxValue, 1]` would be `MinValue`.

And then `S` needs to special-cased for match types anyway.

**Comment by soronpo** [comment]
@unkarjedy what was your actual use-case for this? I'm thinking of issuing a PR deprecating it instead of fixing it, since it was a mistake to create is in the first place, IMO (my mistake).

**Comment by dwijnand** [comment]
What's the mistake?  Just unnecessary?

**Comment by soronpo** [comment]
Yeah, it does not make sense to have an incremental compiletime numbering until `2^64`.

**Comment by soronpo** [comment]
I issued a PR for deprecation. If it will be decided to keep and fix this feature I will complete that instead.

**Comment by unkarjedy** [comment]
>@unkarjedy what was your actual use-case for this? 
I'm thinking of issuing a PR deprecating it instead of fixing it, since it was a mistake to create, is in the first place, IMO (my mistake).

I don't have a real world use case for this.
I randomly stumbled on this new language feature when working with some other stuff with support of Scala 3 in IntelliJ.
