### ISSUE TITLE
Inconsistent results with function arguments and significant indentation

### ISSUE THREAD

**Issue by JD557** [lampepfl/dotty#18345]
## Compiler version

3.3.0

## Minimized code

Assuming the following definitions:

```scala
extension (vec: Seq[Int])
  def iterate[T](body: (() => Int) => T): T =
    val iterator = vec.iterator
    body(() => iterator.nextOption().getOrElse(0))

def withSequence[T](n: Int)(body: Seq[Int] => T): T =
  body((0 to n))
```

This code works fine with the old style:

```Scala
withSequence(2) {
  _.iterate { next =>
    next() + next() + next() + next()
  }
}
```

But converting it to significant indentation fails with cryptic problems

### Example 1
```scala
withSequence(2): _.iterate: next =>
  next() + next() + next() + next()
```

Fails with
```
; expected but . found

end of statement expected but '.' found

Found:    (Seq[Int] => Any) => Any
Required: 
```

### Example 2

```scala
withSequence(2):
  _.iterate:
    next =>
      next() + next() + next() + next()
```

Fails with

```indented definitions expected, _ found```

### Example 3

```scala
withSequence(2): x =>
  x.iterate:
    next =>
      next() + next() + next() + next()
```

Fails with

```Recursive value $t needs type```

### Example 4

Surprisingly, the last two examples work fine when stored in a variable

```scala
val foo = withSequence(2): x =>
  x.iterate:
    next =>
      next() + next() + next() + next()

val bar = withSequence(2):
  _.iterate:
    next =>
      next() + next() + next() + next()
```

## Expectation

I would expect at least examples 2 and 3 to behave the same when stored in a variable or not.

I would also argue that all examples should compile, although maybe I'm missing some precedence rules that would make some of them ambiguous.

**Comment by dwijnand** [comment]
I don't have a firm grip on the indentation syntax for method closures.  Can someone else triage this?

**Comment by odersky** [comment]
All examples compile on current nightly on my system.

**Comment by JD557** [comment]
For reference, I suspect there might still be something going on here.

Here's a gist with all examples ready for scala-cli: https://gist.github.com/JD557/2c7e4817660da73e7eaaca0228e8df42

I can still reproduce the first problem in nightly with `scala-cli https://gist.githubusercontent.com/JD557/2c7e4817660da73e7eaaca0228e8df42/raw/02eba9011520ecf9e93f99b6dc1fe80af768226f/example-1.sc` (although adding a new line like in https://github.com/lampepfl/dotty/pull/18349/files#diff-61e3395826536ea12dde7c2a261d47f4651bfd03d97737b418123c802b5307afR11-R12 fixes the problem).

Surprisingly, I cannot reproduce the problems from examples 2 and 3 with scala-cli (either with nightly or with the current version).

However, the problems still appear on Scastie, even on 3.3.1-RC1 ([example 2](https://scastie.scala-lang.org/90Jkpjl7SOG6aHRgK1F1Rg), [example 3](https://scastie.scala-lang.org/rfmfphn0Sbu47sAJml0JAg)).

Maybe the way scala-cli and scastie are converting scripts in a different way (e.g. wrapping it in an `object`) that is leading to the different behaviors... Unfortunately, I'm not sure how to get access to scastie's output `.scala` file.

**Comment by odersky** [comment]
The first example, is not supposed to work. The others should work.
