### ISSUE TITLE
Regression in ist-dsi/scala-keystone-client 

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18351]
Regression found in Open CB for ist-dsi/scala-keystone-client - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/5772754805/job/15648454243)

## Compiler version
3.3.1-RC1-bin-20230204-a356581-NIGHTLY 
3.3.1-RC4 
Bisect points to 11854bbf20d92b74fef82f19c4dcb7dd38f45f70

If you're not sure what version you're using, run `print scalaVersion` from sbt
(if you're running scalac manually, use `scalac -version` instead).

## Minimized code

```Scala
abstract class Service[F[_]](val name: String)
abstract class CrudService[F[_]](name: String) extends Service[F](name)

trait Foo[F[_]] { self: CrudService[?] =>
  val x = self.name
}
```

## Output

```scala
-- [E008] Not Found Error: /Users/wmazur/projects/dotty/bisect/main.scala:6:15 -
6 |  val x = self.name
  |          ^^^^^^^^^
  |value name is not a member of CrudService[?[_$2]] & Foo[F] - did you mean (Foo.this : CrudService[?[_$2]] & Foo[F]).name?
  ```

## Expectation
I'm not sure if it's a fix of corner case or real regression, it's only present when using at least 1 wildcard type. When defining `self: CrudService[F] =>` it fails with every stable Scala version  
```Scala
> scala-cli compile  --server=false bisect/main.scala -S 3.0 
-- [E008] Not Found Error: /Users/wmazur/projects/dotty/bisect/main.scala:6:15 -
6 |  val x = self.name
  |          ^^^^^^^^^
  |value name is not a member of CrudService[F] & Foo[F] - did you mean (Foo.this : CrudService[F] & Foo[F]).name?
```

**Comment by prolativ** [comment]
It looks like the type parameters were only hiding the original problem. The snippet below compiles in scala 2 but doesn't compile in any release of scala 3
```scala
class Service(val name: String)
class CrudService(name: String) extends Service(name)

trait Foo { self: CrudService =>
  val x = self.name
}
```
It seems like the problem is in the clash of names between the parameter `name: String` of the subclass `CrudService` and the parameter member `val name: String` of the superclass `Service`.
If we remove the clash, e.g.
```scala
class Service(val name: String)
class CrudService(name1: String) extends Service(name1)

trait Foo { self: CrudService =>
  val x = self.name
}
```
the code compiles successfully

**Comment by odersky** [comment]
@prolativ Great minimization! That helped me not going down some other rabbit holes.
