### ISSUE TITLE
Regression in  estrondo/farango

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18350]
Open CB regression found in estrondo/farango - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/5772754805/job/15648069603)

## Compiler version
3.3.1-RC1-bin-20230515-22b2259-NIGHTLY  
3.3.1-RC4 

Bisect points to d1d6c2e9536ce331316f741b9c1c4c0520cef787 

## Minimized code

```Scala
import scala.collection.Factory

trait EffectStream[S[_]]:
  def fromJavaStream[A]: S[A]

given [I[_] <: Iterable[_]](using Factory[Any, I[Any]]): EffectStream[I] with
  override def fromJavaStream[A]: I[A] = {
    val builder = summon[Factory[_, I[_]]].newBuilder
    ???
  }
 ```

## Output

```scala
-- [E043] Type Error: /Users/wmazur/projects/dotty/bisect/main.scala:8:36 ------
8 |    val builder = summon[Factory[_, I[_]]].newBuilder
  |                                    ^^^^
  |     unreducible application of higher-kinded type I to wildcard arguments
  |
  | longer explanation available when compiling with `-explain`
  ```

## Expectation
Probably should compile

**Comment by dwijnand** [comment]
Yeah, it's not a regression.  I'm not sure about the original, but to me it looks like it should be `summon[Factory[Any, I[Any]]].newBuilder`.

**Comment by odersky** [comment]
If I understood Dale correctly, it looks like an error in the program that is now correctly diagnosed.
