### ISSUE TITLE
False warning about unused import for local/relative import with Scala 3.3

### ISSUE THREAD

**Issue by cchantep** [lampepfl/dotty#18366]
## Compiler version

3.3.0 & 3.3.1-RC4

## Minimized code

```scala
  @SuppressWarnings(Array("UnusedMethodParameter"))
  private[api] def serializeWith[P <: SerializationPack](
      pack: P,
      collation: Collation
    )(builder: SerializationPack.Builder[pack.type]
    ): pack.Document = {

    import builder.{ elementProducer => element, int, string, boolean }

    val elements = Seq.newBuilder[pack.ElementProducer]

    elements += element("locale", string(collation.locale))
    ??? // ...
}
```

See: https://github.com/ReactiveMongo/ReactiveMongo/blob/master/driver/src/main/scala/api/Collation.scala#L166

## Output

```
[error] 166 |    import builder.{ elementProducer => element, int, string, boolean }
[error]     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]     |                     unused import
```

## Expectation

No warning

**Comment by szymon-rd** [comment]
Minimized repro:
```scala
trait Builder {
  def foo(): Unit
}

def repro =
  val builder: Builder = ???
  import builder.{foo => bar}
  bar()
```

**Comment by odersky** [comment]
I think this one can also be addressed by counting an import as used if some code refers to its imported symbols (under either name). Here, we would see a reference to `foo` in the code, and `foo` is the original name of an imported symbol, so we count the import as used.

It converts a false negative into a false positive (i.e. now we might fail to warn), but the false positive is a rare corner case, so is acceptable.
