### ISSUE TITLE
`-Wconf` options are processed incorrectly

### ISSUE THREAD

**Issue by coreywoodfield** [lampepfl/dotty#18367]
## Compiler version

3.3.0

## Minimized code

```Scala
object Main {
  def main(args: Array[String]): Unit = Deprecated.deprecated
}

object Deprecated {
  @deprecated("", "")
  def deprecated = ()
}
```
(anything that will produce a warning that can be configured with `-Wconf` will do)

## Output
scala 2.13.10
```bash
$ scala-2.13.10/bin/scalac -Wconf:cat=deprecation:e -Wconf:cat=deprecation:s Test.scala

$ scala-2.13.10/bin/scalac -Wconf:cat=deprecation:s -Wconf:cat=deprecation:e Test.scala
Test.scala:3: error: method deprecated in object Deprecated is deprecated:
  def main(args: Array[String]): Unit = Deprecated.deprecated
                                                   ^
1 error
```
scala 3.3.0
```bash
$ scala3-3.3.0/bin/scalac -Wconf:cat=deprecation:e -Wconf:cat=deprecation:s Test.scala
-- Error: Test.scala:3:51 -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
3 |  def main(args: Array[String]): Unit = Deprecated.deprecated
  |                                        ^^^^^^^^^^^^^^^^^^^^^
  |                                        method deprecated in object Deprecated is deprecated since : 
1 error found

$ scala3-3.3.0/bin/scalac -Wconf:cat=deprecation:s -Wconf:cat=deprecation:e Test.scala
```

## Expectation
In scala 2, passing `-Wconf:cat=deprecation:silent` after `-Wconf:cat=deprecation:error` would override the `error` setting, i.e. the last provided configuration wins. In scala 3, the opposite is true: the first provided configuration wins. The documentation for the behavior is the same for both: `scalac -Wconf:help` includes the following:
>User-defined configurations are added to the left. The leftmost rule matching
>a warning message defines the action.

I would expect that, having the same documentation, the -Wconf flags would be handled in the same order. The scala 2 behavior is useful for providing a general default (e.g. `-Wconf:any:error`) and then being able to append more specific options to the scalac options and have those override the general default. A bit more discussion can be found in https://github.com/lampepfl/dotty/discussions/18365

**Comment by Kordyjan** [comment]
`The leftmost rule matching a warning message defines the action.` suggests that if we provide two matching options, the first should be used and the second ignored. Do I understand it wrong?

**Comment by som-snytt** [comment]
Per the discussion, in Scala 2 the `-Wconf` option has a flag to prepend values, so command line `-Wconf:X -Wconf:Y` reverses to Y then X, so if Y matches, it wins. Various switches may tweak the config, such as `-Wopt` for optimizer warnings. Explicit `-Wconf` is processed as a final step IIRC to ensure "user conf" winds up at the head. So that is the meaning of leftmost for Scala 2.

Hopefully a judicious `list.reverse` suffices in Scala 3.

**Comment by SethTisue** [comment]
fyi @lrytz

**Comment by johnmatthiggins** [comment]
I'd like to work on this!
