### ISSUE TITLE
Cannot fallback to applicable syntax after attempting non-applicable syntax

### ISSUE THREAD

**Issue by armanbilge** [lampepfl/dotty#18395]
Not sure if this is a bug or a legit difference in Scala 3 vs Scala 2 implicit resolution.

## Compiler version

`3.4.0-RC1-bin-20230811-fed94f3-NIGHTLY`

## Minimized code

```Scala
package foo

trait Foo[A]

object syntax {
  implicit def fooOps[A](a: A): FooOps[A] = new FooOps(a)
  
  class FooOps[A](val a: A) {
    def product(implicit foo: Foo[A]) = ???
  }
}

import syntax._

object Test {
  def main(args: Array[String]): Unit = {
    val x: Array[Int] = Array(1, 2, 3)
    x.product
  }
}
```

## Output

```scala
[error] ./test.scala:18:14
[error] No given instance of type foo.Foo[Array[Int]] was found for parameter foo of method product in class FooOps
[error]     x.product
[error]              ^
```

## Expectation

It compiles with Scala 2.13

**Comment by Kordyjan** [comment]
This is an intended change in the behavior. You can add `import Predef.wrapIntArray`explicitely if you want to be sure that other imports do not override this implicit conversion.

In Scala 3, you cannot determine which implicit conversion will be applied based only on what implicit parameters are passed to the method used after the conversion.
