### ISSUE TITLE
Regression in arainko/ducktape: -Wunused:all false-positive in quotes

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18409]
## Compiler version
3.3.1-RC5
3.4.0-RC1-bin-20230815-ca6a80e-NIGHTLY 
Works in 3.3.0 -version` instead).

Bisect points to b7a7227e55558de2c483731d34b829d2d4018203

## Minimized code

```Scala
//> using options -Wunused:all
import scala.quoted.*

object model {
  trait Transformer[Source, Dest] {
    def transform(from: Source): Dest
  }
  object Transformer {
    trait ForProduct[A, B] extends Transformer[A, B]
  }
}

object Ops {
  import model.Transformer // unused import false-positive

  def unapply(using Quotes)(term: quotes.reflect.Term): Option[String] = {
    term.asExpr match {
      case '{
            ($transformer: Transformer.ForProduct[a, b]).transform($appliedTo)
          } =>
        Some("")
      case other => None
    }
  }
}
```

## Output

```scala
[warn] ./bisect/main.scala:14:16
[warn] unused import
[warn]   import model.Transformer // unused import false-positive
[warn]             
```

## Expectation
Should not mark this import as unused

**Comment by nicolasstucki** [comment]
The cause of this comes from an optimization in how we type quote splices in https://github.com/lampepfl/dotty/blob/main/compiler/src/dotty/tools/dotc/typer/QuotesAndSplices.scala#L263-L266. @szymon-rd I should take this over. Removing that case fixes the issue, but I need to see if there are other consequences.
