### ISSUE TITLE
Bad url link on `dotty.epfl.ch/index.html`

### ISSUE THREAD

**Issue by iusildra** [lampepfl/dotty#18444]
## Compiler version

Nightly build

## Minimized code

![image](https://github.com/lampepfl/dotty/assets/64749208/035deba6-4eb5-4d32-9455-5480655f0438)

There is a extra `_doc/` in the url of `Contributing` link

## Output

Nothing when clicking on the link

## Expectation

Should throw an error, and redirect to `https://dotty.epfl.ch/docs/contributing/index.html`

**Comment by nicolasstucki** [comment]
Duplicate of #18285
