### ISSUE TITLE
Java Annotation causing a E046 Cyclic reference involving val <import>

### ISSUE THREAD

**Issue by mdedetrich** [lampepfl/dotty#18441]
## Compiler version

Scala 3.3.0

## Minimized code

Minimizing this will take quite some effort but the context of this bug report can be seen at https://github.com/apache/incubator-pekko-persistence-jdbc/pull/44#pullrequestreview-1588948670

```Scala
@ApiMayChange
class JdbcDurableStateStore[A](
    db: JdbcBackend#Database,
    val profile: JdbcProfile,
    durableStateConfig: DurableStateTableConfiguration,
    serialization: Serialization)(implicit val system: ExtendedActorSystem)
    extends DurableStateUpdateStore[A]
    with DurableStateStoreQuery[A] {
```

## Output

```scala
[error] -- [E046] Cyclic Error: /Users/mdedetrich/github/incubator-pekko-persistence-jdbc/core/src/main/scala/org/apache/pekko/persistence/jdbc/state/scaladsl/JdbcDurableStateStore.scala:50:1 
[error] 50 |@ApiMayChange
[error]    | ^
[error]    | Cyclic reference involving val <import>
[error]    |----------------------------------------------------------------------------
[error]    | Explanation (enabled by `-explain`)
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    | import pekko.annotation.ApiMayChange is declared as part of a cycle which makes it impossible for the
[error]    | compiler to decide upon <import>'s type.
[error]    | To avoid this error, try giving <import> an explicit type.
[error]     ----------------------------------------------------------------------------
[error] Explanation
[error] ===========
[error] import pekko.annotation.ApiMayChange is declared as part of a cycle which makes it impossible for the
[error] compiler to decide upon <import>'s type.
[error] To avoid this error, try giving <import> an explicit type.
[error] -- [E046] Cyclic Error: /Users/mdedetrich/github/incubator-pekko-persistence-jdbc/core/src/main/scala/org/apache/pekko/persistence/jdbc/state/scaladsl/DurableStateSequenceActor.scala:91:16 
[error] 91 |    stateStore: JdbcDurableStateStore[A],
[error]    |                ^
[error]    |                Cyclic reference involving class JdbcDurableStateStore
[error]    |----------------------------------------------------------------------------
[error]    | Explanation (enabled by `-explain`)
[error]    |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]    | class JdbcDurableStateStore is declared as part of a cycle which makes it impossible for the
[error]    | compiler to decide upon JdbcDurableStateStore's type.
[error]    | To avoid this error, try giving JdbcDurableStateStore an explicit type.
[error]     ----------------------------------------------------------------------------
[error] Explanation
[error] ===========
[error] class JdbcDurableStateStore is declared as part of a cycle which makes it impossible for the
[error] compiler to decide upon JdbcDurableStateStore's type.
[error] To avoid this error, try giving JdbcDurableStateStore an explicit type.

```

## Expectation

That the code compiles. I also can't seem to be able to find a workaround for this compiler bug aside from just removing the annotation

**Comment by mdedetrich** [comment]
Closing the issue, it turns out that Scala 3 is a lot more strict when it comes to shadowing when you happen to have multiple classes of the same name but in different packages.

I managed to solve the issue by prefixing the imports with the package prefix so that its clear for the Scala 3 compiler from which package the import is coming from, see https://github.com/apache/incubator-pekko-persistence-jdbc/compare/6371edd675ee7b8b1ceb55d58d3db774fa978c69..2ca5f615a9e391ce19ba758d1103b399d4dc4cfe

**Comment by som-snytt** [comment]
I would not expect a name-binding difference.

**Comment by mdedetrich** [comment]
> I would not expect a name-binding difference.

My gut feeling is that the issue may be that the cyclic dependency checker which is new in Scala 3 isn't handling shadowing of classes correctly which causes it to incorrectly state there is a cyclic dependency when there isn't

**Comment by nafg** [comment]
So if it's indeed a bug shouldn't this be open?

**Comment by mdedetrich** [comment]
Possibly, I guess its hard for me to make that call because it would likely only become clear after minimization what the core issue is, i.e. it may just be a case in the order of which errors are detected (i.e. Scala 3 shoudn't have been erroring at `@InternalApi` since that made no sense, instead it should have errored in other places).
