### ISSUE TITLE
What exactly is "invariant position"? Is it ill-defined in compiler error message?

### ISSUE THREAD

**Issue by tribbloid** [lampepfl/dotty#18449]
## Compiler version

3.4.0-RC1-bin-20230822-3783220-NIGHTLY

## Minimized code

```Scala
object IllDefinedInvariantPosition {

  { // primary

    trait II[+T]

    trait JJ[+T] {

      type IJ = II[T]
    }
  }
}
```

## Output

```scala
[Error] XXX: covariant type T occurs in invariant position in type  = II[T] of type IJ
```

## Expectation

Given the definition `II[+T]`, type T should be in a covariant position, not an invariant one. But I have no clue, the concept of "invariant position" was never clearly defined in the language specification, what do you think?

(This is one of a few compiler issues that may be simplified by [CoC vs λP2 conjecture](https://stackoverflow.com/questions/75291778/in-intuitionistic-type-theory-can-any-proof-written-in-coc-be-rewritten-in-syst), the following dual form works properly)

```scala
object IllDefinedInvariantPosition {

  { // dual

    trait II_* { type _T }
    trait JJ_* { type _T; type IJ }
    trait TGen {
      type T_/\

      trait II extends II_* { type _T <: T_/\ }

      trait JJ extends JJ_* {
        type _T <: T_/\
        type IJ = II
      }
    }
  }
}

```

**Comment by SethTisue** [comment]
> the concept of "invariant position" was never clearly defined in the language specification, what do you think?

There is some spec language on this at https://scala-lang.org/files/archive/spec/2.13/04-basic-declarations-and-definitions.html#variance-annotations

**Comment by tribbloid** [comment]
Thanks a lot, you are right it is a false alarm, closing as "working as intended"

Tho I ignored that spec because it was for Scala 2.13, hope it can be reworded in Scala 3 spec soon
