### ISSUE TITLE
Top level opaque type not transparent inside class in definition scope

### ISSUE THREAD

**Issue by prolativ** [lampepfl/dotty#18469]
## Compiler version

3.4.0-RC1-bin-20230825-2616c8b-NIGHTLY and before

## Minimized code

```scala
opaque type Foo = String

class Bar:
  val foo: Foo = "abc"
```

## Output

```scala
[error] Opaque.scala:4:18
[error] Found:    ("abc" : String)
[error] Required: Foo
[error]   val foo: Foo = "abc"
[error]                  ^^^^^
```

## Expectation

This should compile. Because `Bar` is defined in the same scope as `Foo` the definition of Foo should be transparent inside the body of `Bar`.

**Comment by prolativ** [comment]
The problem doesn't occur if the snippet from above is moved to an object, e.g.
```scala
object Scope:
  opaque type Foo = String

  class Bar:
    val foo: Foo = "abc"
```
or if the opaque type is referenced from inside a top level method, e.g.
```scala
opaque type Foo = String

def bar =
  val foo: Foo = "abc"
```
so my assumption is that the problem is caused by the fact that the type gets moved to the synthetic package object but the scopes are compared for opaqueness/transparentness at a later point in the compilation pipeline

**Comment by prolativ** [comment]
Possibly related to https://github.com/lampepfl/dotty/issues/18097

**Comment by bishabosha** [comment]
this is not surprising, `Foo` is in the scope of the wrapping top-level-definition object for the file, and `Bar` is in its own top level scope. [see the docs](https://docs.scala-lang.org/scala3/reference/other-new-features/opaques-details.html#)
