### ISSUE TITLE
Incorrect target is chosen for right-associative extension method

### ISSUE THREAD

**Issue by dbingham695** [lampepfl/dotty#18494]
## Compiler version

3.3.0

## Minimized code

```Scala
extension (s: String)
  def %:(i: Int) = s"$i $s"

println(4 %: "cats")
```

## Output

```scala
value %: is not a member of String.
An extension method was tried, but could not be fully constructed:

    %:("cats")  failed with:

        Found:    ("cats" : String)
        Required: Int
```

## Expectation

Compiles successfully and when run outputs:
```
4 cats
```

When calling a right-associative operator defined in an `extension`, the target is the left operand (`Int` here).  But if the `extension` is changed to an `implicit class` the target of the method is the right operand, or the `String` here.  A right-associative operator on a `class` behaves the same as `implicit class`.

This causes identical syntax (infix operator ending in `:`) to have divergent behavior based on where the operator was defined.

**Comment by dbingham695** [comment]
A slightly less minimized version which clearly demonstrates the swapped target can be found on my [StackOverflow question](https://stackoverflow.com/questions/77010848) on the same issue.

**Comment by som-snytt** [comment]
This came up again the other day. I'm sorry I can't find the reference.

I can find [this topic](https://users.scala-lang.org/t/scala3-extension-drops-colons-right-associativity/7478), oh that was a couple of years ago. The answer includes doc links.

There are frequent [tickets](https://github.com/lampepfl/dotty/issues/15954).

**Comment by dbingham695** [comment]
Thanks.  I hadn't seen #15954 however, I have seen that topic and the included doc links several times.  While I see references to those documents by way of explanation of this behavior, I fail to see how either of those actually explains this issue.  In fact, I referenced both of those documents (and a related SO question) on my StackOverflow question I linked above.

However, none of this actually gets at what I'm attempting to address.  I can understand the (re-)swapping of arguments for the argument lists in the compiled form of an extension method.  But that alone isn't sufficient to explain why the _target_ needs to be opposite of how the rest of the language works.  Saying "well, you can just define it on Int" (for my example above) isn't really a solution or answer, just a workaround.

In terms of how right-associative operators work in Scala (that is, operators ending in `:`) the behavior of extension methods is wrong.  `class` and `implicit class` behavior predates and provides precedent for how developers expect such operators to behave.  To expect callers to even know which type of construct was used to define the operator seems like a stretch.  Never mind _readers_ of the code.  If you came across this in a code base:

```scala
a %: b
```

And `%:` wasn't defined locally, would you know which object would be the target and which the operand?  Prior to this issue, every Scala developer with sufficient experience would have said "b is the target and a is the operand" and been correct.  Now it is completely unknowable without seeing the source of the definition.

This seems like a serious bug in the language to me.  Maybe it isn't strictly a _compiler_ bug, I'm not sure about that.  But it is very much something broken in the Scala 3 language.

If the desire is to _change_ how right-associative methods are defined or work (like to restrict them to extensions and move definitions to the left operand's type) then a different pattern should be established (a new suffix, an annotation, or even just disallow operators ending in `:` on extensions) rather than confusingly breaking a well-established pattern in the language.

**Comment by som-snytt** [comment]
Thanks for clarifying. There is an old advertisement that claimed, "An educated consumer is our best customer."

I liked the other SO answer you linked to, but I would avoid suggesting, "Your mental model just needs some tweaking." It seems to me that "tweaking" used to be what older relations did to one's cheek.

I remember I, too, asked for further clarification of what they intended by this change of mental model.

**Comment by dbingham695** [comment]
That SO answer reads like "it is broken on purpose" which may be true, but sadly, that makes it no less broken.

**Comment by sjrd** [comment]
This is indeed behaving as designed.

Extension methods don't have a receiver, i.e., no "target", or at least neither its left-hand-side nor right-hand-side is the receiver. Both the left-hand-side and right-hand-side are arguments to the extension method. The arguments appear at the call site textually in the same order as they appear at the definition site. In other words, the left-hand-side is in the `extension` clause, and the right-hand-side is to the right of the method name.

**Comment by dbingham695** [comment]
Can someone point me in the direction of where to give feedback on the language design, then, if this isn't the place?  (@sjrd ?)  As I said, while I understand the argument lists and swapping as described in the docs, the extension syntax does not look at all like:

> Extension methods don't have a receiver ... the left-hand-side is in the extension clause, and the right-hand-side is to the right of the method name.

Textually, grammatically, as an english speaker, `extension (f: Foo)` looks like a clause that begins a construct defining extension methods for objects of type `Foo`.  Analogous to `implicit class` style extension.  That is to say, when later writing `f.myMethod` I expect that `f` is the target and `myMethod` behaves like a method on type `Foo`.  In fact, this understanding is reinforced by [the Scala 3 Book](https://docs.scala-lang.org/scala3/book/ca-extension-methods.html) which states:

> In Scala 2, a similar result could be achieved with implicit classes.
>...
> Extension methods let you add methods to a type after the type is defined, i.e., they let you add new methods to closed classes.
> ...
> In this code:
>
> * Circle is the type that the extension method circumference will be added to
> * The c: Circle syntax lets you reference the variable c in your extension method(s)
>  
> Then in your code you use circumference just as though it was originally defined in the Circle class:
> ...
> The extension keyword declares that you’re about to define one or more extension methods on the type that’s put in parentheses.

All of that sounds like exactly what I described above... that you are adding methods to a type.  And adding a right-associative method to a type ought to behave like any other right-associative method on the type.

Indeed, even in [the reference docs](https://dotty.epfl.ch/docs/reference/contextual/extension-methods.html) it says things like:

> Extension methods allow one to add methods to a type after the type is defined.

and

> ...if it is in the implicit scope of the receiver type...

Note `"receiver"` there.  Which is synonymous with my `"target"` above.

If the intended behavior / design was to simply have independent multi-parameter-list methods which offer some syntax sugar to blend with surrounding (calling) code better, I believe both the current design AND the documentation leave a LOT to be desired.  

And more to the point, changing right-associative methods from reading right to left to instead reading left to right (but parenthetically grouping right to left) is a monumental shift in an important part of the language and adds a ton of (imho) unnecessary conceptual complexity for authors, readers, and maintainers of Scala 3 code.

If there is a more appropriate forum for thoughts such as those in this comment, I would love to know where that is so that I can go contribute helpfully there.

**Comment by dbingham695** [comment]
Thank you.  [Posted](https://contributors.scala-lang.org/t/implementation-of-extensions-doesnt-match-expectation-or-documentation/6307)
