### ISSUE TITLE
Quotation of class extends T definion

### ISSUE THREAD

**Issue by kovalyovGA** [lampepfl/dotty#18504]
## Compiler version
3.3.0

## Minimized code

```Scala
//Macro.scala
object Macro:
  inline def mock[T] = ${MacroImpl.mock[T]}


//MacroImpl.scala
import scala.quoted.*

object MacroImpl:
  def mock[T: Type](using quotes: Quotes): Expr[T] =
    import quotes.reflect.*
    '{
      final class Whatever extends T
      (new Whatever {}).asInstanceOf[T]
    }

//Main.scala
trait X:


@main
def main(): Unit =
  val x = Macro.mock[X]



```

## Output
```scala
T is not a class type
```

## Expectation
Successfully compiled, when T is a trait or class

**Comment by kovalyovGA** [comment]
Found similar discussion from 2020. https://github.com/lampepfl/dotty-feature-requests/issues/153

**Comment by jchyb** [comment]
I fear that this is not something we can really "fix" - the quoted code is type checked before the macro expansion, meaning that at that point T is still only a type parameter, with no information of what it will contain when expanding. Unlike in the linked discussion however, now it is possible to create classes in the reflect API (I did see you created an issue for that as well (#18505) and I will do my absolute best to look at it closer tomorrow)

**Comment by kovalyovGA** [comment]
It seemed code I need to generate #18505 is quite simple, sad there is no simple way to do it(

**Comment by nicolasstucki** [comment]
The error message is correct. I'm not sure what else we can do on this front.
