### ISSUE TITLE
Macro class generation with method override fails with NoSuchElementException

### ISSUE THREAD

**Issue by kovalyovGA** [lampepfl/dotty#18505]
## Compiler version
3.3.0

## Description
Given any trait or class, for example X

```scala
trait X:
  def abc(x: Int): String
```

I need to generate:

```scala
new X:
  val mock$abc$0: MockFunction1[Int, String] = new MockFunction1[Int, String](context$proxy2, scala.Symbol("mock$abc$0"))
  override def abc(x: Int): String = mock$abc$0.apply(x)

```
Not sure if is is a bug, maybe I am doing something wrong.

## Minimized code
**Main.scala**
```scala
trait X:
  def abc(x: Int): String


@main
def main(): Unit =
  val x = Macro.mock[X](new MockContext {})

```
**MockFunction.scala**
```scala
trait MockContext

class MockFunction0[R](ctx: MockContext, sym: scala.Symbol) extends Function0[R] {
  override def apply(): R = null.asInstanceOf[R]
}

class MockFunction1[T1, R](ctx: MockContext, sym: scala.Symbol) extends Function1[T1, R] {
  override def apply(t1: T1): R = null.asInstanceOf[R]
}

class MockFunction2[T1, T2, R](ctx: MockContext, sym: scala.Symbol) extends Function2[T1, T2, R] {
  override def apply(t1: T1, t2: T2): R = null.asInstanceOf[R]
}
```

**Macro.scala**
```scala
object Macro:
  inline def mock[T](implicit context: MockContext) = ${MacroImpl.mock[T]('{context})}
 ```
 
**MacroImpl.scala**
```scala
import scala.annotation.experimental
import scala.quoted.*

object MacroImpl:
  @experimental
  def mock[T: Type](mockCtx: Expr[MockContext])(using quotes: Quotes): Expr[T] =
    import quotes.reflect.*
    val (tpe, objectTpe) = (TypeRepr.of[T], TypeRepr.of[Object])
    val (typeTree, objectTypeTree) = (TypeTree.of[T], TypeTree.of[Object])

    val methodsSymbols =
      (tpe.typeSymbol.methodMembers.toSet -- objectTpe.typeSymbol.methodMembers).toList

    val parents = List(objectTypeTree, typeTree)

    def buildDefinitionsSymbols(classSymbol: Symbol): List[Symbol] =
      methodsSymbols.zipWithIndex.map { (symbol, idx) =>
        val methodType = tpe.memberType(symbol) match
          case x: MethodType => x
          case _ => report.errorAndAbort("not a method")

        val methodSym: Symbol = Symbol.newMethod(
          parent = classSymbol,
          name = symbol.name,
          tpe = methodType,
          flags = Flags.Override,
          privateWithin = Symbol.noSymbol
        )

        val mockName = "mock$" + symbol.name + "$" + idx

        val valSym: Symbol = Symbol.newVal(
          parent = classSymbol,
          name = mockName,
          tpe = (methodType.resType.asType, methodType.paramTypes.map(_.asType)) match
            case ('[r], Nil) => TypeRepr.of[MockFunction0[r]]
            case ('[r], '[t1] :: Nil) => TypeRepr.of[MockFunction1[t1, r]]
            case ('[r], '[t1] :: '[t2] :: Nil) => TypeRepr.of[MockFunction2[t1, t2, r]]
            case _ =>
              report.errorAndAbort("unknown")
          ,
          flags = Flags.EmptyFlags,
          privateWithin = Symbol.noSymbol
        )

        List(methodSym, valSym)
      }.flatten


    val cls: Symbol = Symbol.newClass(
      parent = Symbol.spliceOwner,
      name = "anon",
      parents = parents.map(_.tpe),
      decls = buildDefinitionsSymbols,
      selfType = None
    )

    val body: List[Statement] = methodsSymbols.zipWithIndex.map { (symbol, idx) =>
      val methodType = tpe.memberType(symbol) match
        case x: MethodType => x
        case _ => report.errorAndAbort("not a method")

      val mockName = "mock$" + symbol.name + "$" + idx

      val function = (
        (methodType.resType.asType, methodType.paramTypes.map(_.asType)) match
          case ('[r], Nil) =>
            '{ new MockFunction0[r]($mockCtx, scala.Symbol(${ Expr(mockName) })) }
          case ('[r], '[t1] :: Nil) =>
            '{ new MockFunction1[t1, r]($mockCtx, scala.Symbol(${ Expr(mockName) })) }
          case ('[r], '[t1] :: '[t2] :: Nil) =>
            '{ new MockFunction2[t1, t2, r]($mockCtx, scala.Symbol(${ Expr(mockName) })) }
          case _ =>
            report.errorAndAbort("unknown")
        ).asTerm

      val valSym = cls.declaredField(mockName)
      val methodSym = cls.declaredMethod(symbol.name).head

      val valDef: ValDef = ValDef(valSym, Some(function))

      val defDef = DefDef(
        methodSym,
        { args =>
          Some(
            Apply(
              Select.unique(Ref(valDef.symbol), "apply"),
              args.flatten.collect { case t: Term => t }
            )
          )
        }
      )

      List(valDef, defDef)
    }.flatten

    report.info(body.map(_.show(using Printer.TreeCode)).mkString("\n"))

    val clsDef: ClassDef =
      ClassDef(
        cls = cls,
        parents = parents,
        body = body
      )

    Block(
      List(clsDef),
      Typed(Apply(Select(New(TypeIdent(cls)), cls.primaryConstructor), Nil), typeTree)
    ).asExprOf[T]
```

## Output
[error] ## Exception when compiling 17 sources to ***
[error] java.util.NoSuchElementException: val x
[error] dotty.tools.dotc.util.ReadOnlyMap.apply(ReadOnlyMap.scala:29)
[error] dotty.tools.dotc.transform.OverridingPairs$Cursor.isHandledByParent(OverridingPairs.scala:96)
[error] dotty.tools.dotc.transform.OverridingPairs$Cursor.next(OverridingPairs.scala:159)
[error] dotty.tools.dotc.transform.OverridingPairs$Cursor.<init>(OverridingPairs.scala:170)
[error] dotty.tools.dotc.typer.RefChecks$OverridingPairsChecker.<init>(RefChecks.scala:205)
[error] dotty.tools.dotc.typer.RefChecks$.checkAllOverrides(RefChecks.scala:551)
[error] dotty.tools.dotc.typer.RefChecks.transformTemplate(RefChecks.scala:1163)
[error] dotty.tools.dotc.transform.MegaPhase.goTemplate(MegaPhase.scala:1010)
[error] dotty.tools.dotc.transform.MegaPhase.goTemplate(MegaPhase.scala:1011)
[error] dotty.tools.dotc.transform.MegaPhase.goTemplate(MegaPhase.scala:1011)
[error] dotty.tools.dotc.transform.MegaPhase.goTemplate(MegaPhase.scala:1011)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:360)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:255)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:425)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:423)
[error] dotty.tools.dotc.transform.MegaPhase.loop$2(MegaPhase.scala:444)
[error] dotty.tools.dotc.transform.MegaPhase.transformBlock(MegaPhase.scala:449)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:298)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:394)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.loop$2(MegaPhase.scala:447)
[error] dotty.tools.dotc.transform.MegaPhase.transformBlock(MegaPhase.scala:449)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:298)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:394)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:423)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:320)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:423)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:394)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.mapValDef$1(MegaPhase.scala:234)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:239)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:425)
[error] dotty.tools.dotc.transform.MegaPhase.loop$2(MegaPhase.scala:444)
[error] dotty.tools.dotc.transform.MegaPhase.transformBlock(MegaPhase.scala:449)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:298)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.mapDefDef$1(MegaPhase.scala:248)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:251)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:425)
[error] dotty.tools.dotc.transform.MegaPhase.loop$1(MegaPhase.scala:438)
[error] dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:438)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:359)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.transformNamed$1(MegaPhase.scala:255)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:425)
[error] dotty.tools.dotc.transform.MegaPhase.loop$1(MegaPhase.scala:438)
[error] dotty.tools.dotc.transform.MegaPhase.transformStats(MegaPhase.scala:438)
[error] dotty.tools.dotc.transform.MegaPhase.mapPackage$1(MegaPhase.scala:379)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnnamed$1(MegaPhase.scala:382)
[error] dotty.tools.dotc.transform.MegaPhase.transformTree(MegaPhase.scala:427)
[error] dotty.tools.dotc.transform.MegaPhase.transformUnit(MegaPhase.scala:454)
[error] dotty.tools.dotc.transform.MegaPhase.run(MegaPhase.scala:466)
[error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:324)
[error] scala.collection.immutable.List.map(List.scala:246)
[error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:328)
[error] dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:247)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
[error] scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
[error] scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1321)
[error] dotty.tools.dotc.Run.runPhases$1(Run.scala:263)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:271)
[error] dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:280)
[error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:280)
[error] dotty.tools.dotc.Run.compileUnits(Run.scala:201)
[error] dotty.tools.dotc.Driver.finish(Driver.scala:56)
[error] dotty.tools.dotc.Driver.doCompile(Driver.scala:36)
[error] dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:88)
[error] dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:180)
[error] sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:178)
[error] sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:464)
[error] sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
[error] sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
[error] sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:419)
[error] sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
[error] sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:406)
[error] sbt.internal.inc.Incremental$.apply(Incremental.scala:172)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2369)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2319)
[error] sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:31)
[error] sbt.internal.io.Retry$.apply(Retry.scala:47)
[error] sbt.internal.io.Retry$.apply(Retry.scala:29)
[error] sbt.internal.io.Retry$.apply(Retry.scala:24)
[error] sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2317)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:69)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[error] sbt.Execute.work(Execute.scala:292)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] java.base/java.lang.Thread.run(Thread.java:833)
[error]            
[error] stack trace is suppressed; run last Compile / compileIncremental for the full output
[error] (Compile / compileIncremental) java.util.NoSuchElementException: val x
[error] Total time: 0 s, completed Sep 3, 2023, 11:29:03 AM

## Expectation
Successfully compiles and generates expected code

**Comment by kovalyovGA** [comment]
I googled a bit more and it looks like I am missing an **<init>** method. Don't know how to create one though.

**Comment by jchyb** [comment]
Hi @kovalyovGA, I believe part of your issue here are the incorrect Symbol owners set in method and val symbol constructors - instead of Symbol.spliceOwner, they should have the class symbol set as the owner (a standard practice related to that is included in [scaladoc](https://scala-lang.org/api/3.3.0/scala/quoted/Quotes$reflectModule$SymbolModule.html#), in the example usage of `Symbol.newClass`). I am unsure if this is the only issue here.

By any chance, looking at the contents of the minimization - are you trying to migrate ScalaMock to Scala 3? Or is this for an unrelated project?

**Comment by kovalyovGA** [comment]
Yes, I am trying to migrate ScalaMock to Scala 3, but I'am quite newbie to macro.
I will change owner to class. I think I did before, but something was wrong, probably not with it.

**Comment by kovalyovGA** [comment]
If I create *Symbol.newClass* before **Symbol.newMethod** or **Symbol.newVal**, I can't fulfill **decls** parameter

**Comment by jchyb** [comment]
That's right, so what you have to do instead is to reuse the symbols created in the decls parameter - either by accessing them from the class symbol by name (via the `classSymbol.declaredMethod` method), or saving them on-the-side after creation in the decls parameter function.

> Yes, I am trying to migrate ScalaMock to Scala 3, but I'am quite newbie to macro.

I asked as, coincidentally, I've also started to work on migrating ScalaMock (since the Scala community seem to need it) a few days ago (with very small part of the `MockMaker` class moved over). I worry about unnecessarily repeating work. With that in mind, if you want, I can take this over (although you seem to have made it far) and finish my work there and try to migrate and merge it. Alternatively, I would stop my work now, and possibly could act as a support for your endeavors there if you would want (answering your questions here, or in another communication channel). Which would you prefer?

**Comment by kovalyovGA** [comment]
Now it works, thank you so much.
I want to improve my metaprogramming skills, so I would really like if I finish it with your support

**Comment by jchyb** [comment]
Sure! You can reach me here, or on scala discord (where it is also @jchyb). I do have one request. Could you set up a GitHub repository, where you would push changes related to the migration? This way I would have an easy access to your changes, and could more easily offer help/suggestions, if needed

**Comment by goshacodes** [comment]
This is my another profile. I've forked the repo and added you on Discord. I'll open a PR with changes in a few days
https://github.com/goshacodes/ScalaMock
