### ISSUE TITLE
`Unreachable case` after update to 3.3.1

### ISSUE THREAD

**Issue by He-Pin** [lampepfl/dotty#18519]
## Compiler version

3.3.1

## Minimized code
Not minimized yet.

1. clone incubator-pekko
2. change the scala3 version to 3.3.1
3. compile the `multi-node-testkit` with scala 3.3.1

## Output

```scala
[error] -- [E030] Match case Unreachable Error: C:\Users\hepin\IdeaProjects\incubator-pekko\multi-node-testkit\src\main\scala\org\apache\pekko\remote\testconductor\Player.scala:218:14
[error] 218 |    case Event(_: ServerOp, _) =>
[error]     |         ^^^^^^^^^^^^^^^^^^^^^
[error]     |         Unreachable case
[error] one error found
```

## Expectation

![image](https://github.com/lampepfl/dotty/assets/501740/b13501f7-793d-4105-994e-ea348d4a44bf)
![image](https://github.com/lampepfl/dotty/assets/501740/1e601a80-94c0-47ec-bc50-9650247f239d)

I just check the code, the branches will be matched with 
```scala
    case Event(msg: NetworkOp, _) =>
```
first , so I think the compiler is right.

Better with an output:

```
[error] 218 |    case Event(_: ServerOp, _) =>
[error]     |         ^^^^^^^^^^^^^^^^^^^^^
[error]     |         Unreachable case, all case has been matched with `case Event(Done, _) =>` and `case Event(msg: NetworkOp, _)`
[error] one error found
```

**Comment by He-Pin** [comment]
@dwijnand I think the compiler is right, can you check it too, thanks.

**Comment by bishabosha** [comment]
I also checked this independently when I was testing pekko with pipelining support

**Comment by WojciechMazur** [comment]
I've tested it when investigating nightly failures in Open Community Build for akka/pekko and it's an improvement and not a regression.  As @bishabosha already mentioned all the cases for `ServerOp` have been already covered and this code is in fact unreachable.

**Comment by He-Pin** [comment]
That's true.

**Comment by He-Pin** [comment]
Thank you everyone.

**Comment by bishabosha** [comment]
to summarise, the error message for "unreachable case" could be expanded to possibly say which cases already cover the "unreachable" case mentioned. This could help the programmer re-order the code if they really need to do something different when that case matches

**Comment by bishabosha** [comment]
minimisation:
```scala
sealed trait ServerOp
sealed trait NetworkOp

case object Done extends ServerOp with NetworkOp
case class Foo() extends ServerOp with NetworkOp

def foo(x: Matchable) = x match
  case Done => ???
  case _: NetworkOp => ???
  case _: ServerOp => ??? // warning: Unreachable case 
```

**Comment by dwijnand** [comment]
> to summarise, the error message for "unreachable case" could be expanded to mention which cases already cover the "unreachable" case mentioned.

How?  By trying all the combinations of all the cases to find the smallest set of cases that make the case redundant?  Currently we don't compare the case to individual previous cases, we just take all previous cases and consider whether the current case is redundant.  I don't think we should spend the CPU time doing more, unless it's an opt-in option.

**Comment by odersky** [comment]
There's also the issue of inlining. For inlined code we don't even see the pattern and the match, so "unreachable case" is particularly unhelpful.
