### ISSUE TITLE
Broken markdown display in scaladoc 

### ISSUE THREAD

**Issue by jchyb** [lampepfl/dotty#18511]
## Compiler version

3.4.0-RC1-bin-20230901-89e8dba-NIGHTLY

## Problem
Markdown display or parser is broken in nightly Scaladoc. This makes some parts hard to read, like the [reflectModule](https://dotty.epfl.ch/api/scala/quoted/Quotes$reflectModule.html) (Mostly the fact that the type hierarchy is not shown as a code snippet)

## Expectation
For reference, this is what it should look like: [here](https://scala-lang.org/api/3.3.0/scala/quoted/Quotes$reflectModule.html)

**Comment by nicolasstucki** [comment]
Is the ```` ```none ```` still supported? It is the only instance of this in the stdlib. We also have a few in the compiler.

https://github.com/lampepfl/dotty/blob/main/library/src/scala/quoted/Quotes.scala#L130

**Comment by jchyb** [comment]
The issue seems unrelated to `none`, and also happens in other places (like in the newVal/newClass example usage sections https://dotty.epfl.ch/api/scala/quoted/Quotes$reflectModule$SymbolModule.html)
