### ISSUE TITLE
Java parser doesn't support JEP 409 sealed classes

### ISSUE THREAD

**Issue by andrew-boyarshin** [lampepfl/dotty#18533]
## Compiler version

3.3.1

## Minimized code

[Repo](https://github.com/andrew-boyarshin/ScalaJavaBug) (branch `5`)

```java
package bug.code;

public sealed class Pet permits Cat, Dog {
}
```

## Output

```text
-- Error: .\src\code\Cat.java:3:14 ---------------------------------------------
3 |public sealed abstract class Cat extends Pet {
  |              ^^^^^^^^
  |              illegal start of type declaration
-- Error: .\src\code\Pet.java:3:14 ---------------------------------------------
3 |public sealed class Pet permits Cat, Dog {
  |              ^^^^^
  |              illegal start of type declaration
-- [E006] Not Found Error: .\src\code\Dog.java:3:31 ----------------------------
3 |public final class Dog extends Pet {
  |                               ^^^
  |                               Not found: type Pet
  |
  | longer explanation available when compiling with `-explain`
3 errors found
```

## Expectation

Scala code compiles successfully in mixed mode, like in Scala 2.13.11. See also scala/bug#12171 for Scala 2 tracking issue.

**Comment by He-Pin** [comment]
Does Scala support pattern matching on record?

**Comment by He-Pin** [comment]
@Kordyjan I see, will this be backported to 3.3.4 ? thanks.

refs: https://github.com/davidB/scala-maven-plugin/issues/782
refs: https://github.com/He-Pin/scala3-maven-compile-demo

**Comment by kubukoz** [comment]
Bumping - would love to see this in LTS.

**Comment by He-Pin** [comment]
@WojciechMazur ping

**Comment by WojciechMazur** [comment]
Yes, it will be backported to the LTS. When backporting we try to follow the order of changes in the main branch to reduce the amount of conflicts. There is a long queue so please be patient, thank you

**Comment by kubukoz** [comment]
this was backported in https://github.com/scala/scala3/pull/20943, released in https://github.com/scala/scala3/releases/tag/3.3.4
