### ISSUE TITLE
Macro Apply instantiation doesn't appear to work for parameterized classes

### ISSUE THREAD

**Issue by gzoller** [lampepfl/dotty#18539]
## Compiler version
3.3.0

## Minimized code

```Scala
case class Thing[G](stuff: G)

// In a macro...
Apply(
  Select.unique(New(TypeTree.of[Thing[Int]]),"<init>"),  // also tried thingClassSym.primaryconstructor instead of "<init>"
  List(Expr(25).asTerm)
).asExprOf[Thing[Int]]
```

## Output

```scala
constructor Thing in class Thing does not take parameters
```

## Expectation
Clearly Thing does take parameters, both a type parameter and a constructor parameter, stuff.  Per the API this should work: select the constructor and apply using given parameters.  This actually does work exactly like this, if the class Thing is not parameterized, which just adds to the confusion.  If this is not the way to create an instance of a parameterized class using these primitives, then how?  (For my application I need this approach--splicing '{...} won't work because my code is recursive and splicing creates errors in the macro involving circular dependencies.)

**Comment by bishabosha** [comment]
You need to use a TypeApply with TypeRepr.of[Int], before you Apply, e.g. (new Foo[Int](23))

**Comment by gzoller** [comment]
Sorry--still confused.  How would I fix my example to incorporate this guidance?

**Comment by nicolasstucki** [comment]
@bishabosha, for completness could you show the full fixed code?

**Comment by bishabosha** [comment]
Should write this instead
```scala
Apply(
  TypeApply(
    Select.unique(New(TypeTree.of[Thing[Int]]),"<init>"),
    List(TypeRepr.of[Int])
  ),
  List(Expr(25).asTerm)
).asExprOf[Thing[Int]]
```
