### ISSUE TITLE
@BeanProperty not working

### ISSUE THREAD

**Issue by anjunar** [lampepfl/dotty#18553]
## Compiler version

3.3.1

## Minimized code

```Scala
import scala.beans.BeanProperty

class Person {

  @BeanProperty
  var firstName: String = _

  @BeanProperty
  var lastName: String = _

}

val person = new Person
person.setFirstName("Max")

```

## Expectation
It should compile

https://scastie.scala-lang.org/Q2yYFNqrQ8CCctfI1KIuSw

**Comment by som-snytt** [comment]
Perhaps more doc is desired. There is no "fixed in Scala 2" label.
