### ISSUE TITLE
Compiler should provide better error messages when using unsupported JDK version

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#18573]
Latest release of JDK 21 might be a time when more and more people might want to migrate to latest Java version. However, if we'd try to do so, we might get a very nasty error.

## Compiler version
3.3.0 (fixed in 3.3.1 for JDK 21, however the issue would still be present in future JDK's if more assumptions of classfile format are violated)

## Minimized code

```Scala 
import java.nio.file.StandardOpenOption

@main def Test = {
  val x =  StandardOpenOption.CREATE
}
``` 

## Output

```scala 
>scalac main.scala
error while loading StandardOpenOption,
class file /modules/java.base/java/nio/file/StandardOpenOption.class is broken, reading aborted with class java.lang.RuntimeException
bad constant pool index: 0 at pos: 1200
-- [E008] Not Found Error: main.scala:4:30 -------------------------------------
4 |  val x =  StandardOpenOption.CREATE
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   value CREATE is not a member of object java.nio.file.StandardOpenOption
2 errors found
```

## Expectation

Compiler should provide better error messages when using unsupported JDK version, eg. what is the latest supported version and which version was found in the classfile along with a possible way to mitigate this issue, eg. `please try to use the latest version the Scala compiler`

**Comment by SethTisue** [comment]
agree. a language newcomer on Discord was bitten by this today

**Comment by SethTisue** [comment]
another user bitten today

**Comment by bishabosha** [comment]
So we could add another constant in `ClassfileConstants`?

**Comment by bishabosha** [comment]
Alternatively only when there is an error from reading a classfile, then we add an addendum to say that the version was unexpected, so could be the reason?
