### ISSUE TITLE
selectDynamic not encodes given name

### ISSUE THREAD

**Issue by goshacodes** [lampepfl/dotty#18612]
## Compiler version
3.3.0

## Minimized code

```Scala
class X extends scala.reflect.Selectable:
  val `+` = "1"
  
 val x = X()
```

This one is not working:
```Scala
x.selectDynamic("+")
```

```Scala
Caused by: java.lang.NoSuchMethodException: Playground$X.+()
```

But this one works:

```Scala
x.selectDynamic("$plus")
```

## Expectation
This one works
```Scala
x.selectDynamic("+")
``` 

Also I wonder is there a way of encoding given name by hand? 
As I understood this blocks `scalamock` migration to Scala 3, since `MethodSymbol#name` returned encoded name, while `Symbol#name` gives raw name, so I can't use reflection to get a field, I need to encode it somehow.

**Comment by sjrd** [comment]
FYI: `scala.reflect.NameTransformer.encode(name)` encodes the given `name`.

**Comment by goshacodes** [comment]
Thank you! So it is not a bug I guess, if there is a thing for encoding names

**Comment by som-snytt** [comment]
Seems like a bug not to work with the decoded name. But should it also work with the encoded name?
