### ISSUE TITLE
Spurious `is not a class type` error when inheriting a class without call parentheses() through a type alias

### ISSUE THREAD

**Issue by neko-kai** [lampepfl/dotty#18623]
## Compiler version

3.3.1

## Minimized code

https://scastie.scala-lang.org/1OfTRArhRuKz5Kq59dUcHg
```Scala
final abstract class ForcedRecompilationToken[T]
object ForcedRecompilationToken {
  implicit def default: ForcedRecompilationToken["abc"] = null
}

class GoodNoParens[T](implicit ev: ForcedRecompilationToken[T])
type BadNoParens[T] = GoodNoParens[T]

// error
object A extends BadNoParens

// ok
object B extends BadNoParens()
object C extends GoodNoParens

object App extends App {
  println("compiled")
}
```

## Output

```scala
GoodNoParens is not a class type
```

## Expectation

Similar situation as in https://github.com/lampepfl/dotty/issues/15976, but this time merely using a type alias to refer to the class breaks the fix for the aforementioned issue and causes a spurious 'not a class type' error.

**Comment by odersky** [comment]
I think this is as it should be. `BadNoParens` is a higher kinded type, which is not a legal parent. `BadNoParens()` is a call to a constructor with inferred type parameters. `GoodNoParens` is a class type for which special rules apply (i.e. we infer parameters regardless).

I don't really see a strong reason for changing these rules.

**Comment by neko-kai** [comment]
@odersky `BadNoParens` is an alias to `GoodNoParens`, I believe that using it should not be materially different from using GoodNoParens directly, when at all possible. Otherwise some concepts, such as exports, stop working correctly. This bug also reproduces when using an `export` instead of a type alias - https://scastie.scala-lang.org/veWopnkESKO8aCdUPm352Q

```scala
final abstract class ForcedRecompilationToken[T]
object ForcedRecompilationToken {
  implicit def default: ForcedRecompilationToken["abc"] = null
}

object x {
class GoodNoParens[T](implicit ev: ForcedRecompilationToken[T])
}
export x.GoodNoParens as BadNoParens

// error
object A extends BadNoParens

// ok
object B extends BadNoParens()
object C extends x.GoodNoParens

object App extends App {
  println("compiled")
}
```

This worked correctly on Scala 2 and is currently blocking me from porting existing library code to Scala 3...

**Comment by odersky** [comment]
OK, trying a fix...

**Comment by neko-kai** [comment]
@odersky Thank you! :pray:
