### ISSUE TITLE
No warning when recursively initializing value

### ISSUE THREAD

**Issue by LightSystem** [lampepfl/dotty#18637]
## Compiler version

3.3.1

## Minimized example

```Scala
val test: String = test
```

## Output

```scala
val test: String = null
```

## Expectation

The compiler should give a warning by default. For example in Scala 2.13 this results in: `warning: value test does nothing other than call itself recursively`.

**Comment by LightSystem** [comment]
Originally posted in Reddit: https://www.reddit.com/r/scala/comments/16xt70l/source_of_null_pointers_in_scala_3

**Comment by som-snytt** [comment]
Originally posted in https://github.com/lampepfl/dotty/issues/14429
