### ISSUE TITLE
Tuple specialisation doesn't correctly see type 

### ISSUE THREAD

**Issue by klaeufer** [lampepfl/dotty#18638]
## Compiler version

Welcome to Scala 3.3.1 (17.0.8.1, Java OpenJDK 64-Bit Server VM).

## Minimized code

```Scala
type U[H, T] = (Unit, Unit)

(((), ()): U[Int, Int]) match
  case ((), ()) => println("ok")
```

## Output

```scala
java.lang.ClassCastException: class scala.runtime.BoxedUnit cannot be cast to class java.lang.Integer (scala.runtime.BoxedUnit is in unnamed module of loader java.net.URLClassLoader @5eefa415; java.lang.Integer is in module java.base of loader 'bootstrap')
```

## Expectation

- Should print "ok".
- Should behave the same as when unannotated or annotated with result of manually applying type alias to parameters:

```scala
(((), ()): (Unit, Unit)) match
  case ((), ()) => println("ok")
```

```scala
ok
```

## Additional observations

- This problem did not occur in Scala 3.1.x, and I first observed it in Scala 3.2.0.
- The problem seems to occur only for Tuple2 and 2-ary type aliases.
- The problem occurs for two, not necessary equal, integer-based actual type parameters: Boolean, Char, Int, Long
- It doesn't matter what the concrete tuple element types are, as long as at least one of them is different from the corresponding actual type parameter.
- It doesn't make a difference if the type parameters are actually used, e.g., 
   ```scala
   type ListNodeF[H, T] = (H, Option[T])
   ```

**Comment by bishabosha** [comment]
Looks like a problem in compiler/src/dotty/tools/dotc/transform/SpecializeTuples.scala:40

**Comment by nicolasstucki** [comment]
#### Minimization
```scala
type U[H, T] = (Unit, Unit)
def test1(u: U[Int, Int]) = u._1
def test2(u: (Unit, Unit)) = u._1
```

Compiled with `-Xprint:specializeTuples`:
```scala
package <empty> {
  final lazy module val Test$package: Test$package = new Test$package()
  @SourceFile("t/Test.scala") final module class Test$package() extends Object()
     {
    private def writeReplace(): AnyRef =
      new scala.runtime.ModuleSerializationProxy(classOf[Test$package.type])
    type U = [H, T] =>> (Unit, Unit)
    def test1(u: U[Int, Int]): Unit = u._1$mcI$sp // issue here
    def test2(u: (Unit, Unit)): Unit = u._1
  }
}
```
