### ISSUE TITLE
Not give up on compilation instantly when -Werror is on and warning appears

### ISSUE THREAD

**Issue by szymon-rd** [lampepfl/dotty#18634]
## Compiler version

3.3.1

## The problem

When warnings are reported in a phase and -Werror (XfatalWarnings) is on, they will be reported as errors and compilation will crash. Because of that, instead of reporting all warnings from linting in a unit, the compilation will exit with an error after just one phase - therefore it does not report warnings from future phases. it would make more sense to aggregate these warnings and report them as errors after the linting phases.

**Comment by szymon-rd** [comment]
It seems that the decision to report warnings differently than in Scala 2 was just made: https://github.com/lampepfl/dotty/pull/2341/files
It was a good decision at the time. I think we can just go back and change it if users don't have anything against it.

**Comment by som-snytt** [comment]
Conceptually, warnings filtering happens at the end of the run, as an operation on cached warnings.

Off the top of my head, I'm not sure what `-Werror` means if all warnings have been silenced, but I would guess compilation does not fail.
