### ISSUE TITLE
Compiler misses overloaded extension method

### ISSUE THREAD

**Issue by rjolly** [lampepfl/dotty#18660]
## Compiler version

3.x

## Minimized code

```Scala
class A:
  extension (n: Int)
    def foo (m: Int) = n+m

class B extends A:
  1.foo(2)
  extension (n: Int)
    def foo (m: Int, p: Int) = n+m+p
```

## Output

```scala
  1.foo(2)
  ^^^^^^^^
missing argument for parameter p of method foo in class B: (m: Int, p: Int): Int
```

## Workaround

```Scala
class A:
  extension (n: Int)
    def foo (m: Int) = n+m

class B extends A:
  1.foo(2)
  extension (n: Int)
    def foo (m: Int, p: Int) = n+m+p
    override def foo (m: Int) = super.foo(n)(m)
```

**Comment by odersky** [comment]
There's no overloading.The two parameter method is found in a scope inside the scope of A, so takes precedence. This is according to spec.

**Comment by som-snytt** [comment]
It is the `baz` case (not `bar`). Overloading resolution will consider the second param list only if there is ambiguity in the first param list; because of subclassing/nesting, there is no ambiguity. (Expressed another way, applicability considers only the "current" param list during resolution.) 

```
class A:
  def bar(n: Int, m: Int) = n+m
  def baz(n: Int)(m: Int) = n+m
  extension (n: Int)
    def foo (m: Int) = n+m

class B extends A:
  def bar(n: Int, m: Int, p: Int) = n+m+p
  def baz(n: Int)(m: Int, p: Int) = n+m+p
  //def test = 1.foo(2,3)
  def t0 = foo(1)(2)
  def t1 = bar(1, 2)
  def t2 = baz(1)(2)
  extension (n: Int)
    override def foo (m: Int) = n+m
    def foo (m: Int, p: Int) = n+m+p

```

**Comment by rjolly** [comment]
Ok. I thought `baz` ended up represented as `bar`, but of course it is not that simple - for one thing both can coexist, as your example shows, so obviously they aren't represented the same.
