### ISSUE TITLE
Can we have "did you mean..." for top-level names rather than just methods

### ISSUE THREAD

**Issue by lihaoyi** [lampepfl/dotty#18682]
## Compiler version

3.3.1

## Minimized example

Mis-typing a method results in a nice suggestion, presumably using Levenshtein distance or something:

<img width="624" alt="Screenshot 2023-10-12 at 10 51 10 PM" src="https://github.com/lampepfl/dotty/assets/934140/b0e26a5f-be78-49db-a457-46a45c3a5108">

But mis-typing a free variable name doesn't:

<img width="406" alt="Screenshot 2023-10-12 at 10 50 48 PM" src="https://github.com/lampepfl/dotty/assets/934140/b1658b6f-a7d1-4a86-a48c-7786d7cba3a8">

Could we make mis-typed top level names give nice suggestions too? Presumably we already know everything that is in scope, and can do a Levenshtein distance comparison to find any that look close enough to suggest

**Comment by som-snytt** [comment]
The related converse issue at https://github.com/lampepfl/dotty/issues/17067

Scala 2 reminder it's not just top-level https://github.com/scala/bug/issues/12023

```
scala> val hello = "hi"; hellx
-- [E006] Not Found Error: ---------------------------------------------------------------------------------------------
1 |val hello = "hi"; hellx
  |                  ^^^^^
  |                  Not found: hellx
  |
  | longer explanation available when compiling with `-explain`
1 error found

scala> val hello = "hi"; this.hellx
-- [E008] Not Found Error: ---------------------------------------------------------------------------------------------
1 |val hello = "hi"; this.hellx
  |                  ^^^^^^^^^^
  |                value hellx is not a member of object rs$line$1 - did you mean (rs$line$1 : rs$line$1.type).hello?
1 error found
```
