### ISSUE TITLE
Add test pass on CI with linting enabled

### ISSUE THREAD

**Issue by szymon-rd** [lampepfl/dotty#18709]
To prevent compiler crashes from happening, we should test all compiler flags on a complex and large set of code snippets. A good candidate for that is the `pos` test suite. However, to not make the local tests any longer, they should run only on CI.

**Comment by szymon-rd** [comment]
We could run `pos` tests with all linting flags locally and enable silent warnings (`nowarn`).

**Comment by nicolasstucki** [comment]
When running `pos` compilation tests (with `testCompilation`) we never see or check the warnings. I believe we can just add the flags [here](https://github.com/lampepfl/dotty/blob/89fa24707e4f681f06ac84c15693338f0b11b681/compiler/test/dotty/tools/dotc/CompilationTests.scala#L34C17-L34C17) and we will not notice the change.

**Comment by szymon-rd** [comment]
A lot of pos tests have Werror enabled. We could create a whitelist for those that we want to run with linting, and run the rest in a separate pass (so split pos tests in two).

**Comment by som-snytt** [comment]
Perhaps the number of ugly pos tests that necessarily trip a lint warning is small. They can get
```
//> using option -Xlint:false
```
or whatever the option is for turning off lints.

(Manual bookkeeping is a dreadful maintenance burden; I think vulpix's programmatic model was weak on that score.)
