### ISSUE TITLE
Overloaded assignment operators defined as extension methods across different objects fail to compile

### ISSUE THREAD

**Issue by ntnj** [lampepfl/dotty#18713]
## Compiler version

3.4.0-RC1-bin-20231006-b1ccc6a-NIGHTLY

## Minimized code

Scastie: https://scastie.scala-lang.org/cYHDxwGgQzm3VBWrIHYQhA

a.scala
```Scala
import language.experimental.relaxedExtensionImports
class A(var x: String = "a")
object AA:
    extension (a: A)
        def f = a.x
        def f_=(x: String) = a.x = x
```
b.scala
```Scala
import language.experimental.relaxedExtensionImports
class B(var x: String = "b")
object BB:
    extension (b: B)
        def f = b.x
        def f_=(x: String) = b.x = x
```
main.scala
```Scala
import language.experimental.relaxedExtensionImports
import AA.*
import BB.* 
@main def main() =
    val a = A()
    a.f = "aa"
    println(a.f)
```

## Output

```
sbt:tmp> run
[info] compiling 1 Scala source to /workspaces/tmp/target/scala-3.4.0-RC1-bin-20231006-b1ccc6a-NIGHTLY/classes ...
[error] -- [E052] Type Error: /workspaces/tmp/main.scala:7:8 --------
[error] 6 |    a.f = "aa"
[error]   |    ^^^^^^^^^^
[error]   |    Reassignment to val f
```

If I remove `def f_=(x: String) = b.x = x` from `B` extension, it runs successfully with `run` in sbt console.

When I then add it back, it runs successfully with `run` in sbt console, but fails again on `run` after `clean`, which is potentially a partial compilation bug.

## Expectation

``
aa
``

**Comment by nicolasstucki** [comment]
### Minimization

```scala
import language.experimental.relaxedExtensionImports

class A
object AA:
  extension (a: A)
    def f = ???
    def f_=(x: String) = ???

object BB:
  extension (b: Long)
    def f = ???
    def f_=(x: String) = ???

def test(a: A) =
  import AA.*
  import BB.*
  a.f = "aa"
```

**Comment by nicolasstucki** [comment]
It looks like the implementation of #9552 defaults to this error message [here](https://github.com/lampepfl/dotty/blob/af6a2efc80fb933ba79ce0ecd4b5268a1119adce/compiler/src/dotty/tools/dotc/typer/Typer.scala#L1146) when the reference is ambiguous.

**Comment by nicolasstucki** [comment]
When resolving the setter we get first type the prefix to `AA.f`, but then when we desugar it into the setter we use the Ident `f_=` which gets typed as `BB.f_=` instead of `AA.f_=`. We seem to lose the typed qualifier of the extension method.
