### ISSUE TITLE
Warning when assigning null to Unit

### ISSUE THREAD

**Issue by kavedaa** [lampepfl/dotty#18722]
## Compiler version

3.3.0

## Minimized example

```Scala
scala> val a: Unit = null
```

## Output Error/Warning message

```scala
1 warning found
-- [E129] Potential Issue Warning: ---------------------------------------------
1 |val a: Unit = null
  |              ^^^^
  |A pure expression does nothing in statement position; you may be omitting necessary parentheses
  |
  | longer explanation available when compiling with `-explain`
val a: Unit = ()
```

## Why this Error/Warning was not helpful

The message was unhelpful because...

...it's hard to understand why it is relevant in this scenario. I initially thought that it's perhaps not allowed to assign `null` to a value of `Unit` type, but since it's just a warning and not an error, then I guess it is. So I don't really understand at all why this warning appears here.

## Suggested improvement

It could be made more helpful by...

...not giving a warning at all, or at least changing the explanation if it's actually a legitimate warning.

**Comment by kavedaa** [comment]
Duh...I was clearly not thinking clearly when wrote this. Closing.

**Comment by som-snytt** [comment]
Warnings are designed for when we are not thinking clearly!

The error here is that it does not warn with `-Wvalue-discard`.

Scala 2 emits both warnings:
```
scala> val x: Unit = null
                     ^
       warning: discarded non-Unit value of type Null(null)
                     ^
       warning: a pure expression does nothing in statement position
val x: Unit = ()
```

I'll leave the ticket closed, but I think it is a bug.

**Comment by kavedaa** [comment]
Thanks for taking a look. I agree, it would be clearer with the "discarded" warning.

**Comment by bishabosha** [comment]
Thanks for opening the issue, I agree that it can be confusing, as assigning a value to Unit type acts in a special way, looks like #18723 will make the situation clearer
