### ISSUE TITLE
Every explanation is printed twice with `-explain` and sbt

### ISSUE THREAD

**Issue by mrdziuban** [lampepfl/dotty#18774]
## Compiler version

3.3.1

## Minimized code

I'm not sure if this is an issue with Scala or sbt, so please let me know if I should open an issue with sbt instead!

https://github.com/mrdziuban/dotty-explain-issue

```scala
val test = nonExistent
```

## Output

```
[error] -- [E006] Not Found Error: /Users/matt/dotty-explain-test/src/main/scala/example/Test.scala:3:11
[error] 3 |val test = nonExistent
[error]   |           ^^^^^^^^^^^
[error]   |           Not found: nonExistent
[error]   |-----------------------------------------------------------------------------
[error]   | Explanation (enabled by `-explain`)
[error]   |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]   | The identifier for `nonExistent` is not bound, that is,
[error]   | no declaration for this identifier can be found.
[error]   | That can happen, for example, if `nonExistent` or its declaration has either been
[error]   | misspelt or if an import is missing.
[error]    -----------------------------------------------------------------------------
[error] Explanation
[error] ===========
[error] The identifier for `nonExistent` is not bound, that is,
[error] no declaration for this identifier can be found.
[error] That can happen, for example, if `nonExistent` or its declaration has either been
[error] misspelt or if an import is missing.
```

## Expectation

The explanation should only be printed once

**Comment by som-snytt** [comment]
I have to repeat everything to my teenager, and more than twice. They should just call this parent mode.

**Comment by som-snytt** [comment]
There are a couple of dimensions of freedom -- a previous improvement plus something for metals -- but I think the improvement to render the explanation with the message is preferable to the old big blue explanations header, which is presumptively deprecated.

I don't know how to test if whatever API for metals is satisfied!

**Comment by som-snytt** [comment]
I see I accidentally deprecated the blue explanation; I'll revert that part.

I did not drill thru the API, but `Problem` distinguishes `message` and optional `rendered`, where `message` gets the blue explanation and `rendered` gets the boxed explanation. If clients are happy with this division or duplication of labor, then that seems fine to me.
