### ISSUE TITLE
default value for a function parameter - the compiler complains about the type, but the type is correct

### ISSUE THREAD

**Issue by yurique** [lampepfl/dotty#18795]
## Compiler version

```
3.3.1
```

## Minimized code

```Scala
package example

object Main extends App with Test {
  load("")()
}

trait Test {

  def load[T](
    doLoad: T
  )(
    description: T => Option[String] = (_: T) => None // <--- compile error here
  ): Unit = ???

}
```

(sbt project available here: https://github.com/yurique/scala3-weird)

## Output

```scala
[error] 12 |    description: T => Option[String] = (_: T) => None
[error]    |                                       ^^^^^^^^^^^^^^
[error]    |                        Found:    T => Option[String]
[error]    |                        Required: <? >: ("" : String)> => Option[String]
[error]    |
[error]    | longer explanation available when compiling with `-explain`
[error] one error found
```

## Expectation

The code should compile.

### Notes

* this code compiles if the `load` function is defined in an `object` (no in a `trait`)
* it compiles if I move the definition of the `Test` trait *below* the definition of the `Main` object
* It also fails to compile with the same error if the function is defined:
  * as a top-level definition 
  * inside a package object
  * as a trait in a separate file

*edit: smaller example - no custom case classes needed*

**Comment by nicolasstucki** [comment]
### Minimized

```scala
def test: Unit = load("")()
def load[T](doLoad: T)(description: T => Int = (x: T) => 3): Unit = ???
```

**Comment by nicolasstucki** [comment]
It works if we swap the order of the definitions. Some constraint might be leaking from `load("")()` into `def load[T]...`.
