### ISSUE TITLE
`?` in match type cases

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#18808]
## Compiler version

3.3.1

## Minimized code

```Scala
import language.future

type F[X] = X match
  case List[_] => Int // `_` is deprecated for wildcard arguments of types: use `?` instead

type G[X] = X match
  case List[?] => Int
```

as this is a type binding we should use `_` and not `?`. The issue seems to come from parsing the type of the case with `simpleType` which always emits the deprecation.

## Expectation

* The deprecation warning should not be emitted
* <del> It seems that `?` should not be allowed.</del> We also allow `?`

**Comment by dwijnand** [comment]
Is it a binding if it doesn't have a name?  I think what we have is right, like we have `case xs: Tuple2[?, ?]` for term matches.

**Comment by nicolasstucki** [comment]
Interesting. It under that notation, the following seems inconsistent.

```scala
type G[X] = X match
  case List[?] => Int
  case _ => Int
```

Or is that one of the things that will be disallowed with the new match type spec?

**Comment by sjrd** [comment]
Erf ... in theory we could assign two different theoretical meanings to these.

* `_` is a *capture* that is ignored (there is spec text for this in the SIP)
* `?` is not a capture; it is just a wildcard type argument to a normal type (there is no specific spec text, but it falls into all the cases of types without nested captures that appear as patterns)

That said, for all practical purposes, they will behave the same. Or at least I think so (there might be some really fun things with type constructors that have interdependent type parameters).

**Comment by sjrd** [comment]
To be perhaps clearer, I think both have their merits, but in most cases `_` should be encouraged, if only by analogy to `_` in term pattern matches. In the majority of match types where we want a wildcard, we mean "there's something here but I don't care", which is what `_` stands for. We rarely mean `?`.

**Comment by nicolasstucki** [comment]
@sjrd so we should not have the deprecation warning in that case?

**Comment by sjrd** [comment]
Indeed, IMO it shouldn't be deprecated there.

**Comment by odersky** [comment]
I agree. In type _patterns_, a `_` is pefectly natural, and we don't want to deprecate it.

**Comment by nicolasstucki** [comment]
We still need to remove the wrong deprecation warining on match cases.

```scala
type F[X] = X match
  case List[_] => Int // warn: `_` is deprecated for wildcard arguments of types: use `?` instead
```

This warning should not be shown.

**Comment by nicolasstucki** [comment]
We need to fix this bug to be able to emit the migration warning in 3.4 (#18869)
