### ISSUE TITLE
Proposal for a new language construct that combines `object`, `package` and `package object`

### ISSUE THREAD

**Issue by megri** [lampepfl/dotty#1882]
# Proposal for a new language construct that combines `object`, `package` and `package object`

#### Packages
Currently, both Scala and the upcoming Dotty treat *package*s as second class citizens: They are intangible, cannot be passed around and provides no more functionality than allowing code to be structured to fit the JVM model.
    
#### Objects
Scala *object*s allow the same structural organization as packages but lack the privilege of defining a package path.
  
#### Package objects
While packages cannot contain top level definitions, objects can. *Package object*s provide a place in which top-level definitions can exist and be allowed to import together with other package artifacts. I feel they add extra complexity by crudely mashing the two concepts together.

### Proposed state
This proposal aims at condensing `object`, `package` and `package object` into a single `module` concept.

#### The module
A module consists of two things:
* A path or module-path, consisting of path segments separated by '.' (just like a package path)
* An instance, from this point on simply refered to as 'module'

A module definition creates one or more paths and one or more modules. An empty module — that is, a module that doesn't contain any top level definitions — will not be reified during compilation.
  
For example, `module com.org` defines:
* the module 'com' with path '\_root_'
* the module 'org' with path '\_root_.com'

### Interoperability with current things

For a normal class definition
```
package com.org

class Foo
```

becomes

```
module com.org

class Foo
```
---
A package sequence such as 
```
package com.org
package communication

class HelloService(response: String)
```

becomes

```
module com.org
module communication

class HelloService(response: String)
```
---
A package object definition such as
```
package com.org

package object communication {
  def standardHello(response: String): HelloService = new HelloService(response)
}

```

becomes

```
module com.org

module communication {
  def standardHello(response: String): HelloService = new HelloService(response)
}
```
or even
```
module com.org.communication {
  def standardHello(response: String): HelloService = new HelloService(response)
}
```

### Implied syntactic pitfalls

Scala currently allows package members to be defined in blocks, like

```
package foo {
  class Bar
}
```

which would directly translate to

```
module foo {
  class Bar
}
```

which looks ambigous as to whether this declares a "path module" or a "package object module".

As this module contains no top level definitions it could be ignored during compilation and not generate bytecode  corresponding to today's package objects, allowing other module blocks to be declared without creating a collision between module instances.
  
However, in my experience this practice is not widely regarded as idiomatic or used in the wild. For this reason, I feel the better approach would be to disallow the package block syntax, or more specifically, always generate a module instance when a block is attached to the definition.

**Comment by odersky** [comment]
I think to be actionable, this would need a lot more details.

**Comment by megri** [comment]
Indeed. I'll extend the proposal and explore further

**Comment by mdedetrich** [comment]
btw, packages are still useful because it allows you to combine packages that have the exact same namespace without any name clashes.

I.e. if you have library X that has classes inside `some.package` and Library Y that also has classes inside `some.package`, if you depend on both library X and library Y you will have all of the available members.

This is also the reason they can't be passed around as runtime values, they aren't a runtime construct.

**Comment by megri** [comment]
@mdedetrich There is not inherent conflict between these concepts. Just like packages can always be extended/merged so can module paths.

Project-X and Project-Y could both declare artifacts under `module foo.bar` but if both declared top-level defs there'd be a compile time conflict — much like how two classes with the same name in the same package conflicts.

**Comment by acdenhartog** [comment]
Possible corner case from a silly pattern that I like to use:
```scala
trait Modifier 
object Modifier { //something like an enum
  val foo:Modifier = ???
  val bar:Modifier = ???
  type Select = Modifier.type=>Modifier
}
def method(int:Int,mods:Modifier.Select*) = ???
method(10,_.foo,_.bar) //autocomplete nirvana
```
The issue being: `Modifier.type` would start to look a lot like `package.type`. And in fact, if `Modifier` were a `package object` the above snippet does not compile. So then either the compiler has to throw an error whenever one uses `.type` on a module that is not reified, or *all* packages would have to be reified.

But throwing that error could be a strange inconsistency from the user point of view: why does a nested `def`/`val` enable `.type` but a nested `case class` or `module` does not? Especially given that in current Scala you can implement any abstract `def`/`val` with an `object` that either extends the return type or contains an `apply` method with matching signature.

To extend this even further, `method(param:Any)` would have to accept `method(scala.collection)` or the distinction between `object`/`package object`/`package` would just continue to exist, but now without any keyword to differentiate between them.

Although, if `.type` and passing as a parameter were undefined on all modules, then `module Modifier` could still extend some trait so that `type Select = Trait=>Modifier` can be defined; a kludge but at least it would be consistent.

**Comment by acdenhartog** [comment]
I want to suggest something slightly different:
`object` → `object`
`package` →  `module`
`package object` →  `module`
`@static` →  `module`
`nested object` →  `module`

So `object` continues to exist as normal; while a `module` has no type and cannot be passed into methods. The last part is most important: `nested object` →  `module`, it has to do with this pattern:
```scala
class SomeMassiveClass {
  private[foo.bar] object impl { ... }
  private[foo] object admin { ... }
  object view { ... }
  object debug { ... }
}
```
The idea is that sometimes a class becomes so huge that it is unwieldy to have all the methods available at the root level, and instead it is more convenient to categorize them into nested modules.

But these nested objects all require additional memory allocations. So it would be nice to have nested modules instead. These would exist only at compile time; and then get converted into methods on the outer class.

Another strange but convenient pattern I found recently:
```scala
trait Enumish[A]{
  def one:A
  def two:A
}
object Enum extends Enumish[Enum]{
  case object one extends Enum
  case object two extends Enum
}
sealed class Enum {
  object isBefore extends Enumish[Boolean]{
    def one:Boolean = false
    def two:Boolean = Enum.this eq Enum.one
  }
}
object EnumButtonTypeClass extends Enumish[Listener⇒Button[Enum]]{
  implicit def one = listener ⇒ new Button[Enum.one].bind(listener)
  implicit object two extends ( Listener⇒Button[Enum] ) {
    def apply(listener:Listener) = new Button[Enum.two].bind(listener)
  }
}
```
That is just a toy example, and it has quite a bit of boilerplate. But the point here is that adding anything to `Enum` lets the compiler tell you exactly where functionality needs to be extended. And there is a nice separation of concerns, all those button implementations go together.

The objects `Enum`, `isBefore`, and `EnumButtonTypeClass` could all be modules; there is no reason for them to have an associated runtime class. Especially `isBefore` could create significant overhead in some situations. But it is not clear if `two` inside `EnumButtonTypeClass` should then be a allowed as a module.

Intuitively this makes sense to me: a `module` is merely a place to put things and an `object` is a singleton. You could still implement traits on a `module`, but that would only be to ensure some methods are consistently implemented.

All that said, I am not convinced these changes could be worth the effort.

**Comment by ctongfei** [comment]
Why do we need the new keyword `module`? We can keep using `package`.

As @acdenhartog suggested, we could do
object → object
package → package
package object → package
@static → package
nested object → package

**Comment by megri** [comment]
@ctongfei 

The basic idea is to make packages first class members of the language.

The distinction between having an object, a package object and a package is already blurred and confusing:
* Packages can't have top level defs
* Objects are kinda like packages but have no defined package path of their own and are instantiated first time they're requested
* Package objects are objects tightly tied to a package

It seems to me that these concepts could potentially be merged into one, at which point I believe *module* is a better term since this is already a concept which people apply to both packages and objects.

The compiler would be responsible for creating the appropriate structures; a module defined at top level would represent both a package path and optionally a package object-like structure which allows top level defs. If nested within another module or class they would be scoped to that instance according to current object rules.

Modules would be allowed to extend other types according to object/package object rules: the code

```
module foo.bar extends FooDefs

def thing = "Scala"

trait FooDefs {
  def sayThing() = println(s"hello, $thing!")
}
```

would place `TopLevelDefs` at path foo.bar.TopLevelDefs and allow the invocation `foo.bar.sayThing()`. `foo.bar` would be, by today's definitions, a package and an object implementing the trait FooDefs.

@acdenhartog 

> The issue being: Modifier.type would start to look a lot like package.type. And in fact, if Modifier were a package object the above snippet does not compile. So then either the compiler has to throw an error whenever one uses .type on a module that is not reified, or all packages would have to be reified.

I'm not aware of the intricacies of package objects but I don't think there's anything odd with .type being a compile time error on a module that only defines a package path. You'd get the same issue if you were to were to change `package foo { object bar {} }; val x = foo.bar.type` to `package foo { package bar {} }; val x = foo.bar.type`.

I think package objects being confusing is just another reason to get rid of them. Can't define one in the REPL for one.

> The idea is that sometimes a class becomes so huge that it is unwieldy to have all the methods available at the root level, and instead it is more convenient to categorize them into nested modules.

> But these nested objects all require additional memory allocations. So it would be nice to have nested modules instead. These would exist only at compile time; and then get converted into methods on the outer class.

You can achieve something like this today using sealed traits self-typed to your class.

**Comment by smarter** [comment]
Closing since this proposal isn't concrete enough to be actionable, more discussion could go in http://contributors.scala-lang.org/ or https://github.com/scala/scala-dev/issues/441

**Comment by som-snytt** [comment]
Yoda would say there are no packages, only packagings.
