### ISSUE TITLE
Failed to derive mirror in trait with self type

### ISSUE THREAD

**Issue by Anghammar** [lampepfl/dotty#18918]
## Compiler version
3.3.0
## Minimized code

```Scala
trait SuperTrait {
  sealed trait InnerTrait
  case class Foo() extends InnerTrait
}

trait OtherTrait

trait TraitWithSelfType extends SuperTrait { this: OtherTrait =>
  summon[deriving.Mirror.Of[Foo]]
  summon[deriving.Mirror.Of[InnerTrait]]
}

object Implementation extends TraitWithSelfType, OtherTrait {
  summon[deriving.Mirror.Of[Foo]]
  summon[deriving.Mirror.Of[InnerTrait]]
}
```

## Output

```scala
-- [E172] Type Error: DerivingMirrorBug:10:40 ----------------------------------
10 |  summon[deriving.Mirror.Of[InnerTrait]]
   |                                        ^
   |No given instance of type deriving.Mirror.Of[TraitWithSelfType.this.InnerTrait] was found for parameter x of method summon in object Predef. Failed to synthesize an instance of type deriving.Mirror.Of[TraitWithSelfType.this.InnerTrait]:
   |	* trait InnerTrait is not a generic product because it is not a case class
   |	* trait InnerTrait is not a generic sum because its child class Foo is not accessible to call site value <local TraitWithSelfType>
1 error found
```

## Expectation
```summon[deriving.Mirror.Of[InnerTrait]]``` fails inside of TraitWithSelfType, but no of the other three summons fails. I'm not 100% sure this is actually a bug, but since ```OtherTrait``` does not actually do anything it sure seems like it. If it in fact works as intended, I would appreciate a short explanation why.

**Comment by bishabosha** [comment]
given that we can call `Foo()` from inside `TraitWithSelfType` it would seem that it is accessible, so maybe that check needs investigation

**Comment by Anghammar** [comment]
I just now realised I accidentally used the compiler version 3.3.0, but I have verified that the same issue exists on 3.3.1.

**Comment by EugeneFlesselle** [comment]
@bishabosha when checking if we have access through inheritance, we first get the classSymbol of the SingletonType. 
But in the case above, `(TraitWithSelfType.this : OtherTrait & TraitWithSelfType).parentSymbol == NoSymbol` because of the ambiguous superclasses.

I tried [this fix](https://github.com/EugeneFlesselle/dotty/commit/be90a9c0967eebb2c6c16ac38b9e9eee8fdba02f), but this [this neg test](https://github.com/lampepfl/dotty/blob/55c20020c24d9edcc8577e9b62c5935e358efbfa/tests/neg/anon-mirror-gen-local.scala#L26) also passes as a result:
```scala
class Outer2 {
  sealed trait Item
  case object A extends Item
}
def testOuter2 =
  // discussion point: should we allow this, or only allow singleton prefix?
  val m_Outer2_Item = summon[Mirror.Of[Outer2#Item]] // error: Item is not accessible from m_Outer2_Item
```

**Comment by bishabosha** [comment]
> should we allow this, or only allow singleton prefix?

Prefixes should only be valid paths so yeah all singleton types

**Comment by michelou** [comment]
@bishabosha Candidate for a backport ?
