### ISSUE TITLE
Need better info about error file names

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#1902]
I currently get an error like this:

    -- [E008] Member Not Found Error: Seq.scala ------------------------------------
    24 |  def iterator() = new Iterator[A] {
       |                       ^^^^^^^^
       |     type `Iterator` is not a member of strawman.collection.mutable.type

The problem is, I am compiling several files named `Seq.scala`, and I don't know in which one the error occurred. So we should give the full file name, starting with the current directory.

**Comment by felixmulder** [comment]
When running this on master for `local/scala/collection/Seq.scala`:

```scala
package local.scala.collection { class Seq { val xs: List[String] = List(1) } }
```

using `sbt dotc` and `./bin/dotc`, I get:

```scala
-- [E007] Type Mismatch Error: local/scala/collection/Seq.scala ----------------
4 |  val xs: List[String] = List(1)
  |                              ^
  |                              found:    Int(1)
  |                              required: String
  |

```

How are you running this? I couldn't reproduce it.

**Comment by odersky** [comment]
I just verified. The `Seq` in question was indeed in the current directory. So all is OK.
