### ISSUE TITLE
Staging code example raises compiler warning

### ISSUE THREAD

**Issue by Bersier** [lampepfl/dotty#19211]
## Compiler version

3.3.1

## Minimized example
From the [Scala 3 Reference](https://docs.scala-lang.org/scala3/reference/metaprogramming/staging.html#example-9)

```Scala
// libraryDependencies += "org.scala-lang" %% "scala3-staging" % scalaVersion.value
import scala.quoted.staging

given staging.Compiler = staging.Compiler.make(getClass.getClassLoader)
```

## Compiler output

```scala
Suspicious top-level unqualified call to getClass
given staging.Compiler = staging.Compiler.make(getClass.getClassLoader)
```

## Expectation
Code examples from the Scala 3 Reference shouldn't raise compiler warnings.

**Comment by nicolasstucki** [comment]
Using Predef is the wrong fix.

This would work
```scala
given staging.Compiler =
  object Dummy
  staging.Compiler.make(Dummy.getClass.getClassLoader)
```

**Comment by Bersier** [comment]
@nicolasstucki [Your change](https://github.com/lampepfl/dotty/pull/19428/files) to `docs/_spec/TODOreference/metaprogramming/staging.md` has not propagated to

- https://docs.scala-lang.org/scala3/reference/metaprogramming/staging.html#example-9
- https://dotty.epfl.ch/docs/reference/metaprogramming/staging.html#example-10

Should I create pull requests to apply the change there?
