### ISSUE TITLE
Crash on sequence-match if Product is inherited and intermediary _X is not defined

### ISSUE THREAD

**Issue by SrTobi** [lampepfl/dotty#19220]
## Compiler version

`3.3.1`

## Minimized code

```Scala
object Test:
  class Custom extends scala.Product1[String]:
    def length: Int = ???
    def apply(i: Int): Boolean = ???
    def drop(n: Int): scala.Seq[Boolean] = ???
    def toSeq: scala.Seq[Boolean] = ???

    def canEqual(that: Any): Boolean = ???

    val _1: String = ???
    val _3: Seq[String] = ???

  class Unapplied:
    def isEmpty: Boolean = ???
    def get: Custom = ???

  object A:
    def unapplySeq(i: Int): Unapplied = ???

  val A(a, rest*) = 1
```

## Output (click arrow to expand)

```scala
scala: undefined: x9.<none> # -1: TermRef(TermRef(NoPrefix,val x9),<none>) at preRecheck
```

**Comment by odersky** [comment]
This is carefully engineered to confuse the compiler on multiple levels. Fixing it will be quite a challenge. Is there a real world example where this happened? Is there a workaround?

**Comment by SrTobi** [comment]
I came up with these test cases by looking at the specification and coming up with edge cases to test our own implementation of the unapply/unapplySeq match semantics in the intellij-scala plugin. So no, these are not real world examples, just what the specification allows.

**Comment by odersky** [comment]
Thanks for the info. We need to have a closer look at this and compare it with the spec.
