### ISSUE TITLE
Bound deduction of simple existential type doesn't work

### ISSUE THREAD

**Issue by tribbloid** [lampepfl/dotty#19280]
## Compiler version

3.4.0-RC1-bin-20231213-9dce045-NIGHTLY

## Minimized code

```Scala
  object Primary {

    trait IUB

    type TT[I <: IUB] = I

    val v: IUB = ??? : TT[?]
    summon[TT[?] <:< IUB]
  }
```

## Output

```
[Error] /home/peng/git/dottyspike/src/main/scala/com/tribbloids/spike/dotty/conjecture/SimpleBoundDeduction.scala:11:18: Found:    Any
Required: com.tribbloids.spike.dotty.conjecture.SimpleBoundDeduction.Primary.IUB

Explanation
===========

Tree: ??? :
  com.tribbloids.spike.dotty.conjecture.SimpleBoundDeduction.Primary.TT[?
     >: Nothing <: Any]
I tried to show that
  Any
conforms to
  com.tribbloids.spike.dotty.conjecture.SimpleBoundDeduction.Primary.IUB
but none of the attempts shown below succeeded:

  ==> Any  <:  com.tribbloids.spike.dotty.conjecture.SimpleBoundDeduction.Primary.IUB class dotty.tools.dotc.core.Types$CachedTypeRef class dotty.tools.dotc.core.Types$CachedTypeRef  = false

The tests were made under the empty constraint

[Error] /home/peng/git/dottyspike/src/main/scala/com/tribbloids/spike/dotty/conjecture/SimpleBoundDeduction.scala:12:26: Cannot prove that Any <:< com.tribbloids.spike.dotty.conjecture.SimpleBoundDeduction.Primary.IUB.
```

## Expectation

The program should be completely normal.

If the λP2-λC conjecture (https://stackoverflow.com/questions/75291778/in-intuitionistic-type-theory-can-any-proof-written-in-coc-be-rewritten-in-syst) can be proven, the program could be converted to a dual form:

```Scala
  object Dual {

    trait IUB

    trait IGen {
      type I <: IUB
      type TT = I
    }

    summon[IGen#TT <:< IUB]
  }
```

which compiles successfully. But that's an if

**Comment by odersky** [comment]
`TT[?]` is already not a legal type in Scala 3, but that would have only been flagged as an error after the error that was given. Scala 3 simply does not support existential types, in any variation or disguise. Sorry.

**Comment by tribbloid** [comment]
thanks a lot professor, but should it be converted to a refinement type?

> Existential types that can be expressed using only wildcards (but not forSome) are still supported, but are treated as refined types.

For the record, the issue was opened on @Kordyjan 's suggestion

**Comment by odersky** [comment]
Right. You can use a refined type of a class type, but not of some other type.
