### ISSUE TITLE
how could a covariant type parameter be an upper bound of an abstract type, but not another invariant type parameter?

### ISSUE THREAD

**Issue by tribbloid** [lampepfl/dotty#19319]
(original post: https://stackoverflow.com/questions/65944627/in-scala-how-could-a-covariant-type-parameter-be-an-upper-bound-of-an-abstract)

(haven't received an answer, only upvotes)

## Compiler version

3.3.0

## Minimized code

Here is a simple example

```Scala

    trait Poly1Group[+OUB] {

      trait Case1 {
        type Out <: OUB // <------------------------------- success
      }
      type Case1Aux[O <: OUB] = Case1 { type Out = O } // <------------------------------------- fail

      trait Case2[
          O <: OUB // <------------------------------------- fail
      ] extends Case1 {

        final type Out = O
      }
    }
```

## Output

```scala
[Error] Poly1Group.scala:12:12: covariant type OUB occurs in invariant position in type [O <: OUB] = Poly1Group.this.Case1{type Out = O} of type Case1Aux
[Error] Poly1Group.scala:15:11: covariant type OUB occurs in contravariant position in type  <: OUB of type O
```

## Expectation

Case1 & Case2 should be functionally identical, but Case2 cannot be defined because OUB has to be in a contravariant in expression `O <: OUB`, but `Out <: OUB` doesn't have this limitation? If this is part of the typer rule for variance check, then it may need some revision.

**Comment by odersky** [comment]
Not sure I understand the question. That's what the rules are. If one wants to design different rules, one would have to make a proposal and prove it sound. I will not have the bandwidth to engage unless there is a fully worked out and proven proposal.
