### ISSUE TITLE
`private[this]` doesn't work

### ISSUE THREAD

**Issue by Bersier** [lampepfl/dotty#19339]
## Compiler version

3.3.1

## Minimized code

```Scala
class A:
  private[this] def foo: Int = 1

  def bar(other: A): Int = other.foo
```

## Compiler output

Compiles fine.

## Expectation

Compiler warning or error, either

1. about `foo` not being visible on `other` (as in Scala 2).
2. about `private[this]` being deprecated/[dropped in Scala 3](https://docs.scala-lang.org/scala3/reference/dropped-features/this-qualifier.html), **and having the same meaning as** `private`.

In Scala 3.4.0 Nightly, the compiler warning _still does not mention the unexpected semantics of_ `[this]` in this context, which doesn't seem documented anywhere. Being deprecated is not the same as being ignored.

**Comment by hamzaremmal** [comment]
Related to #18819

**Comment by nicolasstucki** [comment]
The migration warning was added in 3.4. 

The current warning is 
```
-- Warning: t/Test.scala:2:16 --------------------------------------------------
2 |  private[this] def foo: Int = 1
  |                ^
  |The [this] qualifier will be deprecated in the future; it should be dropped.
  |See: https://docs.scala-lang.org/scala3/reference/dropped-features/this-qualifier.html
  |This construct can be rewritten automatically under -rewrite -source 3.4-migration.
```
