### ISSUE TITLE
master breaks the CI

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#1934]
Prima facie it's related to the recent dotty doc merge.

http://dotty-ci.epfl.ch/lampepfl/dotty/761/1

**Comment by felixmulder** [comment]
Not really, the script is reporting an error because it couldn't push.

**Comment by liufengyun** [comment]
@felixmulder see log line 3202, there are some compiler internal exceptions.

**Comment by felixmulder** [comment]
@liufengyun, it's missing the dotty-library on the classpath. Not really a big deal since the affected tests don't test compiler internals.

**Comment by liufengyun** [comment]
Thanks a lot @felixmulder , it seems to be fixed, I close now.

**Comment by smarter** [comment]
> @liufengyun, it's missing the dotty-library on the classpath. Not really a big deal since the affected tests don't test compiler internals.

But it makes it much harder to read the logs when searching for an issue, it's even misleading.

**Comment by felixmulder** [comment]
Definitely, will fix in the morning :)
