### ISSUE TITLE
Unable to call Scala 3 inline methods from within Java

### ISSUE THREAD

**Issue by mdedetrich** [lampepfl/dotty#19346]
## Compiler version

3.3.1

## Minimized code

See https://github.com/mdedetrich/call-scala3-inline-from-java-source for a reproducible example

```scala
object Inline {
  inline def myMethod: String = ""
}
```

```java
public class CallInline {
    public void callInline() {
        Inline$.MODULE$.myMethod();
        return;
    }
}
```

## Output

```
[error] /Users/mdedetrich/github/call-scala3-inline-from-java-source/src/main/java/CallInline.java:4:1: cannot find symbol
[error]   symbol:   method myMethod()
[error]   location: variable MODULE$ of type Inline$
[error] Inline$.MODULE$.myMethod
[error] (Compile / compileIncremental) javac returned non-zero exit code
[error] Total time: 0 s, completed 30 Dec 2023, 15:29:54
```

## Expectation

For the Java source to compile. It appears that unlike Scala 2 with the `@inline` annotation, Scala 3 will strip the necessary symbols in the produced bytecode when using `inline` keyword which means its not callable from within Java sources.

For obvious reasons its not expected that Java is actually able to inline the method but rather that it can call it as a standard method without any inlining.

**Comment by sjrd** [comment]
This is by design. `inline` *requires* inlining. Since Java cannot inline the method, it's not allowed to call it at all.

**Comment by He-Pin** [comment]
@sjrd can we do inlining on the scala calls idempotent but still generate method for java usage ？
