### ISSUE TITLE
Apply insertion precedes conversion

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#19352]
## Compiler version

3.4.0-RC1-bin-SNAPSHOT-git-bff12be

## Minimized code

```Scala
import language.implicitConversions

case class C(i: Int)
object C // no function parent

class Test {
  implicit def cv(c: C.type): Function[Int, C] = C(_)
  def f(xs: List[Int]): List[C] = xs.map(C)
}
```

## Output

```scala
-- Warning: test/files/neg/t3664c.scala:15:41 --------------------------------------------------------------------------
15 |  def f(xs: List[Int]): List[C] = xs.map(C)
   |                                         ^
   |       The method `apply` is inserted. The auto insertion will be deprecated, please write `C.apply` explicitly.
1 warning found
```

## Expectation

No warning and use the conversion (like 2.13.12).

This may or may not be "as expected". I expected "apply insertion" to be a "last chance" adaptation.

Noticed while backporting apply insertion to `-Xsource:3cross`.

**Comment by odersky** [comment]
No `apply` insertion comes before implicit conversions. Implicit conversions are the last resort, if nothing else works.

Maybe it's that Scala 2 does not have the warning that shows here?

AN easy workaround is to make `cv` explicit.
