### ISSUE TITLE
summonFrom not finding implicits/givens (?)

### ISSUE THREAD

**Issue by yurique** [lampepfl/dotty#19391]
## Compiler version

I tried this with `3.3.1`, `3.3.2-RC1` and `3.4.0-RC1`.

## Minimized code

Unfortunately for now I only have a piece that depends on circe (and it's derivation):

https://scastie.scala-lang.org/KS7WJy7zQX2IaYVe2HsGWw

```Scala
import io.circe.*
import io.circe.syntax.*

case class Inner[A](
  field: A,
) derives Decoder, Encoder.AsObject

case class Outer(
  a: Option[Inner[String]],
) derives Decoder, Encoder.AsObject

println(
  Outer(
    a = Some(Inner("c"))
  ).asJson.spaces2 
)
```

## Output

```
{
  "a" : {
    "Some" : {
      "value" : {
        "field" : "c"
      }
    }
  }
}
```

## Expectation

Here, the `Encoder[Outer]` is being derived. It involves a call to `summonFrom` here:
https://github.com/circe/circe/blob/series/0.14.x/modules/core/shared/src/main/scala-3/io/circe/derivation/package.scala#L35

So for field `a`, the expectation is for it to be able to "see" the pre-defined `Encoder[Option[A]]` defined here:
https://github.com/circe/circe/blob/series/0.14.x/modules/core/shared/src/main/scala/io/circe/Encoder.scala#L347

```scala
implicit final def encodeOption[A](implicit e: Encoder[A]): Encoder[Option[A]]
```

it would have to provide an `Encoder[Inner[String]]` in order to get the `Encoder[Option[Inner[String]]]` using the `implicit def encodeOption`.

The expectation is for the `derives Encoder.AsObject` to be executed for the `Inner[String]`, but it doesn't happen - so the circe derivation falls back to auto-deriving an `Encoder` for the `Option` (the `case _: Mirror.Of[A]     => ConfiguredEncoder.derived[A]` path is selected inside the `summonFrom`).

I'm not very familiar with scala3 macros and derivations, or with the circe derivation code. But I did put a `println` inside that `summonFrom` to confirm :).

**Comment by yurique** [comment]
I might be having wrong expectations regarding how inlining+derivation works.

For example, if I replace this:
```scala
case class Box[A](a: A) derives Decoder, Encoder.AsObject
```

with this:
```scala
  case class Box[A](a: A)
  object Box {
    implicit def codec[A: Encoder: Decoder]: Codec[Box[A]] = Codec.AsObject.derived // Codec.AsObject implements both Decoder and Encoder.AsObject
  }
```

everything seems to be working fine.

**Comment by yurique** [comment]
I am trying to come up with a minimized example. So far I got this:
https://scastie.scala-lang.org/IgpItBpAQraQDm0PlUHvvA

The structure of the example resembles the (simplified) structure of circe's `Encoder` and `ConfiguredEncoder`.


* `DerivedTypeClass[A]` extends `MyTypeClass[A]`
* there is a derivation defined for `DerivedTypeClass[A]`
* within derivation, we look for instances of `MyTypeClass[A]` (!) for all the fields of a product:
  ```scala
  inline def summonEncoders[T <: Tuple]: List[MyTypeClass[_]] =
    inline erasedValue[T] match
      case _: EmptyTuple => Nil
      case a: (t *: ts)  => summonEncoder[t] :: summonEncoders[ts]

  inline def summonEncoder[A]: MyTypeClass[A] =
    summonFrom {
      case tc: MyTypeClass[A] => tc
      case given Mirror.Of[A] => DerivedTypeClass.derived[A]
    }
  ```
  * if a given `MyTypeClass` for the field is found - it is used
  * if not - the derivation is invoked recursively

The I summon `MyTypeClass` for some sample case classes and print the result.

In this example, it seems to work fine - because the givens for the sample case classes are defined "explicitly":
```scala
object DataInner {
  given tc[A: MyTypeClass]: DerivedTypeClass[DataInner[A]] = DerivedTypeClass.derived
}

object DataOuter {
  given tc[A: MyTypeClass]: DerivedTypeClass[DataOuter[A]] = DerivedTypeClass.derived
}
```

But if, instead, I use the derivation for those case classes (and remove the "explicit" givens in the companion objects) - things stop working, and are behaving differently from circe's derivation (I haven't found why, yet):
```scala
case class DataInner[A](field: A) derives DerivedTypeClass
case class DataOuter[Inner](inner: Inner) derives DerivedTypeClass
```

So in this example, it fails to compile:
```
[error]    |No given instance of type MyTypeClass[DataOuter[String]] was found for parameter x of method summon in object Predef.
[error]    |I found:
[error]    |
[error]    |    DataOuter.derived$DerivedTypeClass[String](
[error]    |      /* missing */summon[DerivedTypeClass[String]])
```

and I can't figure out why/where it is trying to summon a `DerivedTypeClass[String]` - the derivation code only looks for `MyTypeClass[A]` (not `DerivedTypeClass[A]`).

And in circe, somehow this works, but the existing instances are being "ignored" as described in the initial message of this issue.

Note: if I drop the `DerivedTypeClass` and describe everything in terms of `MyTypeClass` (including the derivation) - the whole thing seems to work, both with `derives MyTypeClass` on sample case classes, and "explicit" givens in the companion objects:

* https://scastie.scala-lang.org/sK7s3Oj8RVOSZnluvUw3rg (`derives MyTypeClass`)
* https://scastie.scala-lang.org/JYhUzZH6TEW35M5BfXty4g ("explicit" givens)

**Comment by joroKr21** [comment]
You should check how `case class DataInner[A](field: A) derives DerivedTypeClass` translates:
```scala
case class DataInner[A](field: A) derives DerivedTypeClass
object DataInner:
  given [A: DerivedTypeClass]: DerivedTypeClass = DerivedTypeClass.derived
```

**Comment by joroKr21** [comment]
For a scheme that can both derive recursively and respects existing instances, see `kittens`:
https://github.com/typelevel/kittens/blob/master/core/src/main/scala-3/cats/derived/Derived.scala

**Comment by yurique** [comment]
> You should check how `derives` is translated:

Aha! This totally makes sense. Thank you! 

I got myself confused by adding the `ConfiguredCodec` into the mix, even though it was not part of the initial post here.

`case class DataInner[A](field: A) derives ConfiguredCodec` does fail to compile the same way `derives DerivedTypeClass` fails (as expected).

So I guess the problem has to be somewhere in the circe derivation, since in my example (the last one, with `MyTypeClass` only) it seems to be picking up existing givens.

**Comment by joroKr21** [comment]
> So I guess the problem has to be somewhere in the circe derivation, since in my example (the last one, with MyTypeClass only) it seems to be picking up existing givens.

You can try the same reasoning
```scala
case class Inner[A](
  field: A,
) derives Decoder, Encoder.AsObject
object Inner:
  given [A: Encoder.AsObject]: Encoder.AsObject[Inner[A]] = Encoder.AsObject.derived
```

Do you see the problem? `String` is not a JSON object so there is no `Encoder.AsObject[String]`.

**Comment by joroKr21** [comment]
This should be reported in Circe instead

**Comment by yurique** [comment]
Yes, I'm currently trying to pin it down in circe. Thank you for your help! :)

**Comment by joroKr21** [comment]
The simplest thing Circe could do is let you say `derives Encoder` - that makes much more sense to me.

**Comment by yurique** [comment]
That would be beautiful, indeed! 

Not sure if it's possible to pull it off, since there are many things like 
`Encoder`, `Encoder.AsObject`, `Encoder.AsArray`, `Encoder.AsRoot`, `ConfiguredEncoder`, and then the same set of for `Codec` (which combines `Encoder` + `Decoder`), and on top of it we have `ConfiguredEncoder` and `ConfiguredCodec`, etc. And the corresponding derivations derive instances that do extend the base `Encoder` (and `Decoder`), but as we've seen here - it doesn't always play nice with derivation.

**Comment by joroKr21** [comment]
`Encoder.AsObject` extends `Encoder` so even just a forwarder `Encoder.derived` would work

**Comment by yurique** [comment]
Yeah, the best way would be to "collapse" all those derivations into a single place (inside `Encoder`).
