### ISSUE TITLE
Compiler should not allow to define `@volatile val` 

### ISSUE THREAD

**Issue by WojciechMazur** [lampepfl/dotty#19416]
`@volatile` annotation only makes sense on variables. The compiler should not allow to use this annotation on immutable `val` field.

## Compiler version
All Scala 3 versions

## Minimized code

```Scala
class Foo:
  @volatile val x: Int = ???
```

## Output

No warnings

## Expectation
Give the same error as Scala 2: 
```scala
./main.scala:2: error: values cannot be volatile
  @volatile val x: Int = ???
                ^
```

**Comment by mbovel** [comment]
We can probably check it from `RefChecks.transformValDef`.
