### ISSUE TITLE
Overloaded function must explicitly declared an empty param  list.

### ISSUE THREAD

**Issue by chungonn** [lampepfl/dotty#19440]
I encountered a strange problem with using context function for overloaded functions. An extra empty param list is required for overloaded functions for a successful compilation.

## Compiler version
Scala 3.3.1

## Minimized code
```scala
def foobaz(using s: String): String = s + "!"

def bar: String = ???

def bar(s: String): String = ???

def baz(ctxFn: String => String): String = ???

def baz(s: Int)(ctxFn: String => String) : String = ???

def foo(ctxFn: String ?=> String): String = ??? //This function will cause the compiler to emit error when used
//def foo()(ctxFn: String ?=> String): String = ??? //This function will fix the above problem

def foo(s: Int)(ctxFn: String ?=> String) : String = ???


@main def contextFuctionMain =
  val barName = bar
  val bazName = baz(implicit s => foobaz)
  val fooName = foo(foobaz) //Compilation error - No given instance of type String was found for parameter s of method foobaz
  //val fooName = foo()(foobaz) //Compiler will be happy
```

## Expectation
val fooName  = foo(foobaz) // should compile

**Comment by odersky** [comment]
The compiler needs have determined the overloaded alternative before it can successfully typecheck a context function argument. Otherwise, how would it know how to compiler `foobaz`? If you add a `()` the alternative is determined by matching the first argument list and then the context function in the second argument list can be typed correctly.

**Comment by chungonn** [comment]
> The compiler needs have determined the overloaded alternative before it can successfully typecheck a context function argument. Otherwise, how would it know how to type check `foobaz`? If you add a `()` the alternative is determined by matching the first argument list and then the context function in the second argument list can be typed correctly.
> 
> Not sure whether anything can be done to give better diagnostics or to explain this better in the docs. Looks like it's best handled with a Stackoverflow question.

Thanks for shedding light into the issue. I wonder, wouldn't the signature of foobaz provide enough hint to the compiler to select the correct function?

After understanding the issue, i  tried using ```scala val fooName = foo(using foobaz) ```. Unfortunately I still can't coax the compiler to accept it.

Just a suggestion regarding better diagnostic, in order to prevent one from tripping over the above situation, the compiler should warn or forbid the use of any overloaded method with context function without minimally having an empty param list in the signature.

Anyway, thanks for helping me to understand the issue. And I would close this ticket.
