### ISSUE TITLE
`MarkdownLinkVisitor` mismatch on member named `md`

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1944]
In [MarkdownLinkVisitor.scala](https://github.com/lampepfl/dotty/blob/master/doc-tool/src/dotty/tools/dottydoc/staticsite/MarkdownLinkVisitor.scala) we do two things:

1. Replace `relative/path/to/markdown.md` with `relative/path/to/markdown.html`
2. Member lookup on `[isEmpty](scala.collection.immutable.Seq.isEmpty)`

The first one is simply caught with `.endsWith(".md")`, which means you cannot call a package member `md`.

**Comment by Varunram** [comment]
@felixmulder What are your suggestions? Maybe read the whole string and do something?

**Comment by felixmulder** [comment]
Well, we need to be able to distinguish between links that are part of the site as markdown templates ending in `.md` (later transformed to HTML) and actual source code in a package like:

```scala
package blabla

object md {
}
```
Where the object will have the path `blabla.md` and as such if referred to in another markdown file with: `[md](blabla.md)`; that link will be transformed to `<a href="{{ site.baseurl}}/api/blabla/md.html">md</a>` or something similar.

**Comment by Varunram** [comment]
Thanks for clarifying. What I thought was maybe we could add a try catch loop with Reflection and see if there exists a package. Would this be the right approach?

**Comment by felixmulder** [comment]
You won't know via reflection, as there is no loading of the compiled sources into the classloaders. You could do:

```scala
ctx.getClassIfDefined(str).exists
```

To see if the class exists in the current compilation unit or on the classpath.

**Comment by Varunram** [comment]
Thanks! I'll test it up front and put in a PR later today

**Comment by Varunram** [comment]
Okay, so I worked on this and get the error `required: dotty.tools.dotc.core.Names.PreName`. What I did was I cut the last three characters off the URL (after using lastIndexOf obviously) and placed them in str. What am I doing wrong here?

**Comment by felixmulder** [comment]
Could you show me the code snippet? I'm not sure I follow.

**Comment by Varunram** [comment]
```
          val url = node.getUrl
          if(url.endsWith(".md")) {
            val x = new URI(url.toString)
            val path = x.getPath()
            val meth = path.substring(path.lastIndexOf('/')+1).dropRight(3);
            implicit ctx: Context => ctx.getClassIfDefined(meth).isExists
```
I think I'm not handling the last line properly

**Comment by felixmulder** [comment]
well the last line produces a function from `Context => Boolean`, where the `Context` is marked implicit, but the function is not applied.

The function which contains this code should take a second parameter list `(implicit ctx: Context)`

**Comment by Varunram** [comment]
Oh, but still, how would I pass a string? The type required is `required: dotty.tools.dotc.core.Names.PreName` right? I went through `Names.scala` but I didn't see a function for that :/ Thanks!

**Comment by Varunram** [comment]
The error statement : `Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to dotty.tools.dotc.core.Names$PreName`. Why can't I cast to `Name.preName`?

**Comment by felixmulder** [comment]
you should do `meth.toTypeName`, strings aren't names :)

**Comment by Varunram** [comment]
Thanks for the heads up! But if I'm not wrong, `String` doesn't have `toTypeName` right? `Names` had `toTypeName`, so I'd be casting `String` to `dotc.core.Name.PreName` with `toInstanceOf, but `toTypeName`? And thanks a ton for bearing up with all these noobish questions, really appreciate your help and time!

**Comment by felixmulder** [comment]
There are decorators for adding these methods. Have a look in other files
where `".toTypeName` is used :)
