### ISSUE TITLE
`@static val`s on Scala.js are not initialized

### ISSUE THREAD

**Issue by armanbilge** [lampepfl/dotty#19441]
## Compiler version

`3.4.0-RC1-bin-20240112-c50f2ff-NIGHTLY`

## Minimized code

```Scala
//> using scala 3.4.0-RC1-bin-20240112-c50f2ff-NIGHTLY
//> using platform js

import scala.annotation.static
class Foo
object Foo {
  @static val bar: String = "bar"

  @main def main() = println(bar)
}
```

## Output

```
undefined
```

## Expectation

```
bar
```

**Comment by sjrd** [comment]
`@static` never made it into the language spec. It's a dotc "compiler feature" for the JVM, not a language feature. Use at your own risk.

That said, PR welcome to make it work on Scala.js anyway. Expect hard problems near initialization semantics, indeed.

**Comment by armanbilge** [comment]
> It's a dotc "compiler feature" for the JVM, not a language feature.

Could an SJS-specific miniphase (or something) just drop the annotation?

**Comment by sjrd** [comment]
Maybe, if it doesn't affect observable semantics?

**Comment by dwijnand** [comment]
Duplicate of #14710
