### ISSUE TITLE
Anonymous given with the same higher-kinded type have a name collision

### ISSUE THREAD

**Issue by geirolz** [lampepfl/dotty#19486]
## Compiler version
3.3.1

## Minimized code
```scala
given Show[List[String]] = Show.fromToString
given Show[List[Int]]    = Show.fromToString
```

## Output
```scala
[error] -- [E120] Naming Error: .../Test.scala:6:6 
[error] 6 |given Show[List[Int]]    = Show.fromToString
[error]   |      ^
[error]   |Double definition:
[error]   |final lazy given val given_Show_List: cats.Show[List[String]] in package object Test$package at line 5 and
[error]   |final lazy given val given_Show_List: cats.Show[List[Int]] in package object Test$package at line 6
[error] one error found
[error] (core / Compile / compileIncremental) Compilation failed
```

## Expectation
The generated name under the hood is something like `given_$instanceType_$className` it would be great if this name had the full type signature. I don't know if this is due the type erasure but I think these names are generated at compile time where you have all types information. This is quite annoying because force you to use dumb names in these cases like Scala 2, not fully using this Scala 3 powerful feature.

Something like this would be great

```scala
given Show[List[String]] = Show.fromToString
// given_Show_List_String

given Show[Option[List[String]]] = Show.fromToString
// given_Show_Option_List_String
```

**Comment by sjrd** [comment]
The name encoding is what it is. We cannot change it for binary and TASTy compatibility reasons. When it clashes, it is up to you to explicitly provide different names.
