### ISSUE TITLE
Consolidate entity serialization into one implicit class

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1950]
The templating engine only works on `java.util.Map[String, AnyRef]` (buuh). This means that for each entity, we must convert it to this format. This is done in: [dottydoc.model.JavaConverters](https://github.com/lampepfl/dotty/blob/master/doc-tool/src/dotty/tools/dottydoc/model/JavaConverters.scala).

This file is unnecessarily large, since it contains an implicit class for each subtype of `Entity`. But! It could be made to just contain one implicit class for all subtypes of `Entity`. Namely:

```scala
implicit class JavaEntity(val ent: Entity) extends AnyVal {
  def asJava: JMap[String, _] = ...
}
```

The `asJava` function would return a map with all possible fields of subtypes of `Entity` with `null` for value if the field does not exist in the current subtype.

Yes, we hate `null` in Scala land - but here we are on the border between Java and Scala and as such we have to make some concessions to please the great Java Templating engine gods.

**Added bonus points for:** getting rid of the `_root_` imports, no longer needed

**Comment by wutongy** [comment]
Hi, @felixmulder. I would like to solve this issue. It would be a good chance for me to familiar with Scala code since I would like to apply for GSOC this year and contribute to Scala community.

**Comment by wutongy** [comment]
Hi @felixmulder. 

Just want to confirm with you if what I try to do is right. Does the one implicit class you suggested look like that? :
```scala
implicit class JavaEntity(val ent: Entity) extends AnyVal {
  def asJava(extras: Map[String, _] = Map.empty): JMap[String, _] = ent match {
    case link: MaterializableLink => link match ...
    case ref: Reference =>  ref match ...
    ...
    case _ => null
  }
}
```

Also, may I ask how to test the code so that I can know my modification is correct and does not break anything by accident? Thanks!

**Comment by felixmulder** [comment]
This is what I'm suggesting, and the easiest way to test it would be to create an anonymous instance of each entity type. E.g:

```scala
val df = new Def { ... }
val vl = new Val { ... }

// all of the testsssss
```

A test like this would be unable to compile if the interface changed.
