### ISSUE TITLE
Macro-annotated class with expressions (not defintions) in their body produces compilation error

### ISSUE THREAD

**Issue by pweisenburger** [lampepfl/dotty#19539]
## Compiler version

3.4.0-RC2
3.4.1-RC1-bin-20240125-453658b-NIGHTLY

## Minimized code

```scala
import scala.annotation.{experimental, MacroAnnotation}
import scala.quoted.*

@experimental
class annotation extends MacroAnnotation:
  def transform(using Quotes)(tree: quotes.reflect.Definition) = List(tree)
```

```scala
@scala.annotation.experimental
@annotation
class Test:
  println()
```

## Output

The code produces the following compilation error:

```
[error] -- Error: ~/test/src/main/scala/Test.scala:17:9 
[error] 17 |  println()
[error]    |  ^^^^^^^^^
[error]    |Macro added a definition with the wrong owner - object Predef - class Test in ~/test/src/main/scala/Test.scala
[error] one error found
```

The macro annotation just returns the input tree without any modification.

The tested class only contains a single `println()` statement, which triggers the issue. Both Scala 3.3.1 and 3.3.2-RC1 compile without an error. It would be nice if the issue would not make it into 3.4.

## Expectation

The code should compile without errors.

The term `println` indeed has the owner `Predef` and not `Test` (as the error message says). Yet, this is expected, not an error.

**Comment by WojciechMazur** [comment]
Related to #19537, bisect points to the same commit 038b51e99d2068f4ef17864148619dcf047244b5

**Comment by nicolasstucki** [comment]
https://github.com/lampepfl/dotty/commit/038b51e99d2068f4ef17864148619dcf047244b5#diff-2c923586bb8925d78528093e0f6e404948e4c9c0c8417612e513a536141a144dR144

Here we seem to be checking every statement, but we should only check definitions.
