### ISSUE TITLE
`-Wconf:origin=` unimplemented

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#19582]
## Compiler version

3.4.x

## Minimized code

```Scala
scala -Xlint -Wconf:origin='scala.collection.JavaConverters.*':s
Welcome to Scala 2.13.12 (OpenJDK 64-Bit Server VM, Java 21.0.2).
Type in expressions for evaluation. Or try :help.

scala> class C { import scala.collection.JavaConverters._ }
class C

scala> class C { import collection.JavaConverters._; def f(xs: java.util.List[String]) = xs.asScala }
class C
```

## Output

Warning suppression of unused import and deprecated usage.

## Expectation

Parity in Scala 3.

The `origin` filter is especially handy because import clauses do not receive annotations such as `nowarn`.

https://discord.com/channels/632277896739946517/839243149745455174/1202305289479528478

**Comment by SethTisue** [comment]
Duplicate of #17538?

**Comment by som-snytt** [comment]
@SethTisue thanks I only saw `src` fsr.
