### ISSUE TITLE
Java TASTy doesn't contain default values in annotations

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#19596]
## Compiler version

3.4.0-RC3

## Minimized code

compile this with `-Yjava-tasty` and `-Yjava-tasty-output` flags

```java
package lib;

public @interface SomeAnnotation {
  String value();
  int year() default 2024;
  Class<?>[] classes() default {int.class, String.class};
}
```

## Output

decompile with `-decompile`, `-Yjava-tasty` and `-Yallow-outline-from-tasty` flags

```scala
/** Decompiled from ../../sandbox/outJ/lib/SomeAnnotation.tasty */
package lib {
  object SomeAnnotation extends <special-ops>.<FromJavaObject>
  trait SomeAnnotation(x$1: scala.Unit) extends <special-ops>.<FromJavaObject> with _root_.java.lang.annotation.Annotation {
    def this(value: java.lang.String, year: scala.Int, classes: _root_.scala.Array[java.lang.Class[_ >: scala.Nothing <: <special-ops>.<FromJavaObject>]])
    def value(): java.lang.String
    @_root_.scala.annotation.internal.AnnotationDefault def year(): scala.Int = _
    @_root_.scala.annotation.internal.AnnotationDefault def classes(): _root_.scala.Array[java.lang.Class[_ >: scala.Nothing <: <special-ops>.<FromJavaObject>]] = _
  }
}
```

## Expectation
the default values should not be elided

**Comment by bishabosha** [comment]
this should be a blocker for 3.4

**Comment by bishabosha** [comment]
@sjrd it seems scala code is fine to compile even though the constants aren't there, so is it not actually a problem?

**Comment by sjrd** [comment]
I think the only thing we care about for compilation is that it `HasDefault`, but not the actual value.

(that said, it would be better if it were there)

**Comment by bishabosha** [comment]
Looking in the compiler itself, both scala 2 and scala 3 do not fill in default arguments for java annotations, and even in the classfile they are not filled in.

Macro libraries such as shapeless also seems to only reify annotations that are case classes (or classes with a mirror), this seems to be not needed
