### ISSUE TITLE
Star `*` infix type fails compilation

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#1961]
```
object InfixType {
  trait *[N1, N2]
  type Result = Int * Int
}
```
Gives
```
[error]   |  type Result = Int * Int
[error]   |                    ^
[error]   |                    ';' expected but identifier found
```

**Comment by smarter** [comment]
Backquoting doesn't help, same error when writing ``Int `*` Int`` instead

**Comment by smarter** [comment]
@som-snytt on Gitter mentioned that this was also the case before 2.11, then it got fixed and the spec updated: https://issues.scala-lang.org/browse/SI-8325

**Comment by odersky** [comment]
I am not sure this is a good fix. The problem is that it clashes with postfix `*' in varargs parameters. This would not be a problem if postfix `*' was a real postfix type op. But it isn't. Types don't have postfix ops at all. So I am not really sure how to fix this without major contortions in the parser. I would rather backout of the spec change here.

**Comment by smarter** [comment]
The parser change in scalac doesn't seem to bad: https://github.com/scala/scala/pull/3576/files

**Comment by odersky** [comment]
It requires lookahead, which is a big deal because it widens the Scanner/Parser interface. Dotty's parser does not need lookahead.

**Comment by smarter** [comment]
IIRC, lookahead is also needed to get the `inline` keyword to work under `-language:Scala2`: https://github.com/lampepfl/dotty/pull/1492#discussion_r81396243 which is something I wanted to implement.

**Comment by jozi-k** [comment]
This is probably resolved.

**Comment by soronpo** [comment]
>This is probably resolved.

In which version? I tried it on Scastie now and still produces the same compilation error.

**Comment by allanrenucci** [comment]
I can still reproduce on mater
