### ISSUE TITLE
Illegal cyclic reference - regression from Scala 2

### ISSUE THREAD

**Issue by errt** [lampepfl/dotty#19618]
## Compiler version

3.3.1

## Minimized code

```Scala
trait A {
  type T1
  type T2 <: T1
}

trait B extends A {
  final override type T1 = T2
  final override type T2 = Int
}

trait C extends A

trait D extends B with C { self => }

class E extends D
```

## Output

```scala
[error] 15 |class E extends D
[error]    |      ^
[error]    |Recursion limit exceeded.
[error]    |Maybe there is an illegal cyclic reference?
[error]    |If that's not the case, you could also try to increase the stacksize using the -Xss JVM option.
[error]    |For the unprocessed stack trace, compile with -Yno-decode-stacktraces.
[error]    |A recurring operation is (inner to outer):
[error]    |
[error]    |  find-member .T1
[error]    |  find-member .T2
[error]    |  ...
[error]    |
[error]    |  find-member .T2
[error]    |  find-member .T1
```

## Expectation

The code compiles with Scala 2, but not with Dotty.

Removing `C` fixes it in the MWE above, but is not possible in the original code where C has actual members.
Changing `T1` in `B` to `final override type T1 = Int` prevents the bug, but was not necessary with Scala 2.

**Comment by odersky** [comment]
Workaround
```scala
trait A {
  type T1
  type T2 <: T1
}

trait B extends A {
  final override type T1 = Int // was T2
  final override type T2 = Int
}

trait C extends A

trait D extends B with C { self => }

class E extends D
```

In a sense the message makes sense. If we overlay what is defined in `A` and `B` we get `T1 = T2` and `T2 <: T1`, hence `T2 <: T2`. That's a cycle. I don't think it's worth fixing in particular because the workaround is trivial. @dwijnand do you agree?

**Comment by dwijnand** [comment]
> That's a cycle.

Actually, yes, I agree.  I would even suggest the workaround that's perhaps closer to the intent is:

```scala
  final override type T1 = Int
  final override type T2 = T1
```

which works.  I think we would need to see some slightly less minimised, more real-world example that can demonstrate why this should be made to work.
