### ISSUE TITLE
Match on opaque type produces a warning "cannot be checked at runtime"

### ISSUE THREAD

**Issue by strelec** [lampepfl/dotty#19632]
## Compiler version

Both:
3.3.1
3.4.0-RC4

## Minimized code

```Scala
object Pkg {
  opaque type OpaqueInt = Int
}

def m(obj: Any): Unit =
  obj match {
    case _: Pkg.OpaqueInt => println("matches")
    case _ => println("no match")
  }
```

## Output

Produces a warning `the type test for Pkg.OpaqueInt cannot be checked at runtime`

## Expectation

No warning

**Comment by sjrd** [comment]
That is correct. In `m`, the alias is not visible and there `Pkg.OpaqueInt` is nothing but a `>: Nothing <: Any`, which clearly cannot be checked at run-time.
