### ISSUE TITLE
Improve error messages tests by providing unit test support

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1965]
Currently, testing error messages is done by using check files in the `./tests/repl/` dir. This has several drawbacks, one of the largest being that these are hard to keep in sync since they are only tested by diffing.

It would be great to have a unit test that would work along the lines of:

```scala
@Test def typeMismatch =
  checkErrors (
    """|class Foo {
       |  def bar: Int = "IIEK"
       |}""".stripMargin,
  )
  .expect { implicit ctx =>
    val defn = ctx.definitions
    TypeMismatch(defn.StringType, defn.IntType) :: Nil
  }
```

To do this, we need to extend `DottyTest` and provide the context with a custom reporter that aggregates the errors instead of rendering them to stdout.

**Comment by ennru** [comment]
@felixmulder Trying out your test infrastructure, but I'd like to change to `checkErrorsAfter(phaseName: String)(source: String)` to add test cases for later compiler phases than frontend ("refchecks" in my case). What do you think?

**Comment by felixmulder** [comment]
@ennru: yes that's fine :) potentially we'll have to push it all the way back to erasure to cover all messages...But the further down the hole, the slower the tests will be.
