### ISSUE TITLE
Scala 3.4.0 can't load `$` symbol classfile

### ISSUE THREAD

**Issue by rochala** [lampepfl/dotty#19702]
## Compiler version
3.4.0

## Minimized code

file: Test.scala
```scala
//> using scala 3.4.0

package test

object $ {
  def test(): Int = 1
}
```

into:
`scala-cli package --library Test.scala`

into:

file: TestTest.scala

```scala
//> using jar "Test.jar"
//> using scala 3.4

@main def hello =
  test.$.test()

  println("?")
```

## Output (click arrow to expand)
```scala
❯ scala-cli run TestTest.scala
Compiling project (Scala 3.4.0, JVM (17))
Error: Loading Scala 3 binary from /Users/jrochala/Projects/scala-cli-telemetry-test/Test.jar(test/$.class). It should have been loaded from `.tasty` file. This `.tasty` file is missing. Try cleaning the project to fix this issue.
Error compiling project (Scala 3.4.0, JVM (17))
Compilation failed
```

## Additional info:

I'm not sure whether we should count this as regression as dollar is reserved for compiler-synthesized identifiers. User programs should not define identifiers which contain ‘$’ characters.

Even tho it affected ammonite:
https://github.com/com-lihaoyi/Ammonite/actions/runs/7914125865/job/21603222806?pr=1394#step:4:3164

Probably caused by changes in https://github.com/lampepfl/dotty/commit/f9e8b366fb8ddb516c08f9b19f4220a0deb20d47

**Comment by nicolasstucki** [comment]
As pointed out, the specification states that `object $` is not allowed and therefore has undefined behavior. This object must be deprecated as soon as possible because it will be impossible to guarantee it works. 

We might be able to patch the current failure. I will try it. But this would only be a temporary patch.

What is the status of the lining rule that detects names containing `$`?

**Comment by nicolasstucki** [comment]
Opened https://github.com/com-lihaoyi/Ammonite/issues/1395 to track progress on Ammonite side.

**Comment by rochala** [comment]
This is the PR that is supposed to add this warning https://github.com/lampepfl/dotty/pull/18563
