### ISSUE TITLE
Bring back behavior of -Xfatal-warnings

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#19713]
## Compiler version

Since #19245, -Xfatal-warning became completely useless to me. I critically rely on -Xfatal-warnings in connection with -Xprompt to stop the compilation at the point where a warning was given. I need this every other day. But with the new behavior, -Xfatal-warnings has become useless for this task, since it waits until the very end of the compilation run before anything is reported.

I don't see what the point of these disruptive things to the toolchain is. This change causes me to lose lots of time, and probably will cause problems for others relying on the old behavior as well. 

We can institute new behavior for -Werror. But please, let's leave -Xfatal-warnings alone!

**Comment by dwijnand** [comment]
I can understand how it impedes your -Xprompt workflow (interesting to learn!).  I definitely don't think we should diverge on behaviour between -Werror and -Xfatal-warnings.  Ideally we can make -Xprompt react eagerly on a warning, while under fatal warnings.

**Comment by lrytz** [comment]
Workaround until then is using `-Wconf:any:e` instead of `-Xfatal-warning`.

**Comment by nicolasstucki** [comment]
It might be simpler to make -Werror and -Xfatal-warinings behave differently. -Werror could emmit the single error on warning, while  -Xfatal-warinings could make every warning an error.

**Comment by lrytz** [comment]
I think that's what `-Wconf:any:e` is for. `-Xfatal-warinings` is the deprecated alias for `-Werror`.

But a bit of magic to turn `-Werror` into `-Wconf:any:e` when `-Xprompt` is enabled also seems reasonable.
