### ISSUE TITLE
Bad symbol is selected leading to ClassCastException. Regression from scala 2.13

### ISSUE THREAD

**Issue by jtjeferreira** [lampepfl/dotty#19711]
## Compiler version

Scala 3.3.2 (3.4.0 also affected)

## Minimized code

https://scastie.scala-lang.org/YdGomTp2S0Sc48M47mXLEA
```Scala
case class Config(_config: String)

abstract class Foo(val config: Config) {
  def this(config: String) = {
    this(Config(config))
  }
}

class Bar(config: String) extends Foo(config) {
  def foo(): Unit = {
    config.getClass()
  }
}

new Bar("").foo() //This line will crash in prod
```

## Output

```
Caused by: java.lang.ClassCastException: class Playground$Config cannot be cast to class java.lang.String (Playground$Config is in unnamed module of loader sbt.internal.BottomClassLoader @11415fc3; java.lang.String is in module java.base of loader 'bootstrap')
at Playground$Bar.config$accessor(main.scala:11)
	at Playground$Bar.foo(main.scala:13)
	at Playground$.&lt;clinit&gt;(main.scala:17)
```

## Expectation
That code compiles and runs without crashing (like in scala 2.13)

**Comment by SethTisue** [comment]
minimized a bit further,

```scala
class Foo(val s: Any):
  def this(s: String) =
    this(0)
class Bar(s: String) extends Foo(s):
  def foo = s
Bar("").foo

java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String
```

**Comment by som-snytt** [comment]
Reminiscent of https://github.com/lampepfl/dotty/issues/16092

1692 was the year of the Salem witch trials.

**Comment by odersky** [comment]
### How I fixed it.

I suspected from the bug description that something in the scheme of super parameter aliases went wrong. This scheme  optimizes away duplicates of parameter fields in subclasses if they can be shown to be always aliases of a val parameter in a superclass. But I did not know anymore where that scheme was implemented. So I looked at the output at various phases. Typer and PostTyper and FirstTransform all looked OK, but at Erasure I saw that an accessor `s$accessor` was generated where it should  not have been. I then searched for the `$accessor` in the codebase and found that it was the suffix of the semantic name category `ParamAccessorName`. I then searched for occurrences of that name and found phase `ParamForwarding` which implemented the faulty transform. ParamForwarding relied on info provided by method `forwardParamAccessors` in PostTyper. That method was clearly missing the condition that forwarders have to go throigh the primary constructor. Secondary constructors can call super with anything they choose, so without looking at their code we cannot assume anything.
