### ISSUE TITLE
Indentation behaviour in braces not conformant to the specification?

### ISSUE THREAD

**Issue by SrTobi** [lampepfl/dotty#19736]
Hi,

we recently re-implemented indentation parsing in Intellij to bring it closer/exactly to the [specification](https://docs.scala-lang.org/scala3/reference/other-new-features/indentation.html) and this has fixed many corner case problems for us.

Now I am faced with this example here, however:

```scala
@main
def test(): Unit = {
    def value = 1     // indented by 4 spaces

  List(1, 2).map: value =>
    println(value)    // indented by 4 spaces
}
```

The scala compiler compiles this just fine and prints out 1 and 2.
In our new implementation parsing the braceless-lambda fails
![image](https://github.com/lampepfl/dotty/assets/4148534/c3099a6c-f7d0-465c-a15a-7757a0706258)

When I look into the specs, I think the scala compiler should give an error here too. Afaics the following rules are applicable here:

```
ColonArgument    ::=  colon [LambdaStart]
                      indent (CaseClauses | Block) outdent
```

First, the definition of `ColonArgument` requires there to be an indent before the lambda-body (here `CaseClauses | Block`).
For the indent to be generated we have 

```
2.1) An <indent> is inserted at a line break, if

    2.1.1) An indentation region can start at the current position in the source, and
    2.1.2) the first token on the next line has an indentation width strictly greater than the current indentation width
```

`2.1.1` is true because the indentation is after a `=>` and

```
An indentation region can start [...]

  2.1.4) after one of the following tokens:

      =  =>  ?=>  <-  catch  do  else  finally  for
      if  match  return  then  throw  try  while  yield
```

But `2.1.2` is not true, because for that the indentation width before the `println` (`4 spaces`) must be strictly greater than the current indentation width. The problem is that as far as I understand it the current indentation width is already `4 spaces`, because of 

```
# Indentation and Braces

[...]

2.1) The assumed indentation width of a multiline region enclosed in braces is the indentation width
     of the first token that starts a new line after the opening brace.
```

Note that this can be observed in the following example
```scala
@main
def test(): Unit = {
    def value = 1 // indented by 4 spaces

  def blub =
    println("in blub")  // also indented by 4 spaces
    println("not in blub") // this is not part of blub, because there was no indent after `=`, because the indentation width was not strictly greater than the current 4 spaces
}
```
When `def value = 1` is moved one space to the left, `println("not in blub")` becomes part of `blub`.

In my opinion the compiler does the right thing here, though I think it is wrongly documented in the reference... Could you suggest to me what the real semantics are here? Thanks

**Comment by unkarjedy** [comment]
I would like to mention that, even though the example looks synthetic and "nobody writes such code", in practice, it matters during code editing, code generation, formatting, etc...

**Comment by odersky** [comment]
I turned on
```
    in.debugTokenStream = true    // uncomment to see the token stream of the standard scanner, but not syntax highlighting
```
At line 192 in dotty/tools/dotc/parsing/Parsers.scala. That's useful to see how the program tokenizes. Here is what we get:
```scala
def test(): Unit = {
    def value = 1     // indented by 4 spaces
 <;;>
  List(1, 2).map: value =>
    println(value)    // indented by 4 spaces
}
```
Indeed, no indent is inserted. The last expression is simply equivalent to 
```scala
  List(1, 2).map(value => println(value))
}
```
As another test I added another println:
```scala
@main
def test(): Unit = {
    def value = 1     // indented by 4 spaces

  List(1, 2).map: value =>
    println(value)    // indented by 4 spaces
    println(value)
}
```
That prints `1 2 1`,  not `1 2 1 2` as one might expect. Indeed printing after parser shows:
```scala
package <empty> {
  @main def test(): Unit =
    {
      def value = 1
      List(1, 2).map(value => println(value))
      println(value)
    }
}
```
So it is according to spec, even though this might look fishy. However, dotc also complains about both of these programs with:
```
-- Warning: test.scala:5:2 -----------------------------------------------------
5 |  List(1, 2).map: value =>
  |  ^
  |  Line is indented too far to the left, or a `}` is missing
1 warning found
```
That warning is important. Basically if you ignore it you are on your own.

**Comment by SrTobi** [comment]
Ok, I see. If the warning indicates an error that the compiler recovered from, then it's ok, I guess. Thx for the help.
Then I think the issue can be closed
