### ISSUE TITLE
Capitalized identifiers break `for` assumptions

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1975]
```scala
object Test {
  val X = Seq(1, 2)

  for (X <- Seq(3, 4)) yield println(X)
}
```

```
3 |  for (X <- Seq(3, 4)) yield println(X)
  |       ^
  |     missing parameter type for parameter x$1 of expanded function x$1 =>
  |       x$1 @unchecked match
  |         {
  |           case Foo.X => true
  |           case _ => false
  |         }, expected = ?
```

Surprisingly, changing the letter to be lowercase works. Tried this for a bunch of different letters, as well as longer identifiers beginning with a capitalized letter.

**Comment by propensive** [comment]
This probably arises from the LHS of the `<-` being a pattern, so extractors apply. In a case clause, an initial capital letter (or alternatively wrapping in backticks) denotes a reference to a predefined identifier, whereas an initial lower-case letter indicates the introduction of, and binding to, a new identifier. I guess Dotty is reusing logic here, where NSC doesn't...
