### ISSUE TITLE
XML typing issue - not sure if valid

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#1976]
```scala
object Test {
  import scala.xml._
  val node = <node>{ "whatever " }</node>
}
```

```
-- [E006] Unbound Identifier Error: local/xml.scala ----------------------------
3 |  val nodes: Node = <node>{ "whatever" }</node>
  |                     ^
  |                     not found: $scope
```

**Comment by propensive** [comment]
That looks like it ought to be valid, to the extent that XML ever ought to be valid in Dotty.

Is there the intention for XML literals to be supported in Dotty?

**Comment by felixmulder** [comment]
@propensive - Martin's fixing this as I type this. The plan is to support the "legacy" scala-xml now, but we're always looking to improve things for the future...

**Comment by propensive** [comment]
Ok, great. ;)
