### ISSUE TITLE
No flags in reflect to differentiate public java method from 'default visibility' java method

### ISSUE THREAD

**Issue by goshacodes** [lampepfl/dotty#19779]
## Compiler version

3.3.0

## Minimized code
Can't distinguish public java method from 'default visibility one'.
Sorry, it is not self contained, but I think idea is clear
```java
public class File {
  private final transient int prefixLength;

  int getPrefixLength() {
      return prefixLength;
   }
}
```
## Output
```scala
Flags.JavaDefined | Flags.Method
```

## Expectation
```scala
Flags.JavaDefined | Flags.Method | Flags.JavaNoModifier
```

**Comment by sjrd** [comment]
You need to look at [`privateWithin`](https://www.scala-lang.org/api/3.3.1/scala/quoted/Quotes$reflectModule$SymbolMethods.html#privateWithin-fffffb50). A default-visibility Java method is actually package-private to its enclosing package, and that is represented in the reflect API as having `privateWithin.isDefined`.

**Comment by goshacodes** [comment]
Thank you!
