### ISSUE TITLE
Missing cyclic reference on simple val.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2005]
```scala
object Test {
  val a = 42
  def main(args: Array[String]) = {
    val a: Int = a
  }
}
```

Fails at runtime with

```
java.lang.VerifyError: Bad local variable type
Exception Details:
  Location:
    Test$.main([Ljava/lang/String;)V @0: iload_2
  Reason:
    Type top (current frame, locals[2]) is not assignable to integer
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'Test$', '[Ljava/lang/String;' }
    stack: { }
  Bytecode:
    0x0000000: 1c3d b1    
```

We should not only detect the cyclic reference and check why was this illegal bytecode generated in the backend.

**Comment by nicolasstucki** [comment]
@DarkDimius should have a look at this one.

**Comment by DarkDimius** [comment]
@nicolasstucki, backend doesn't do checks to protect from this kind of tree.
It assumes it won't see forward references. 
It's entirely up for middleend to ensure such trees don't reach the backend.

**Comment by odersky** [comment]
Can you try this with #1997? It looks like this should fix the problem.

**Comment by nicolasstucki** [comment]
#1997 fixes it.
