### ISSUE TITLE
Timings for phases

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2016]
As of e8513e1a465810d965ec41668794e71e0b1c690b, on compilation of stdlib.

| **Phase-ID** 	| **Running time, ms** 	| **Phase name**                                                                                                                                                             	|
|----------	|--------------	|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| 1        	| 20015        	| frontend                                                                                                                                                                	|
| 2        	| 366          	| sbt-deps                                                                                                                                                                	|
| 3        	| 1155         	| posttyper                                                                                                                                                               	|
| 4        	| 2482         	| sbt-api                                                                                                                                                                 	|
| 5        	| 1026         	| pickler                                                                                                                                                                 	|
| 6        	| 300          	| {firstTransform, checkReentrant}                                                                                                                                        	|
| 7        	| 2177         	| Ycheck                                                                                                                                                                  	|
| 8        	| 897          	| {tryCatchPatterns, patternMatcher, explicitOuter, explicitSelf, shortcutImplicits, crossCast, splitter}                                                                 	|
| 9        	| 6316         	| vcInlineMethods, isInstanceOfEvaluator, seqLiterals, intercepted, getters, elimByName, augmentScala2Traits, resolveSuper, primitiveForwarders, arrayConstructors        	|
| 10       	| 1393         	| Ycheck                                                                                                                                                                  	|
| 11       	| 2090         	| erasure                                                                                                                                                                 	|
| 12       	| 992          	| {elimErasedValueType, vcElideAllocations, mixin, LazyVals, memoize, linkScala2ImplClasses, nonLocalReturns, capturedVars, constructors, functionalInterfaces, getClass} 	|
| 13       	| 1717         	| Ycheck                                                                                                                                                                  	|
| 14       	| 564          	| {lambdaLift, elimStaticThis, flatten, restoreScopes}                                                                                                                    	|
| 15       	| 386          	| {expandPrivate, selectStatic, collectEntryPoints, collectSuperCalls, dropInlined, moveStatic, labelDef}                                                                 	|
| 16       	| 1637         	| Ycheck                                                                                                                                                                  	|
| 17       	| 6417         	| genBCode                                                                                                                                                                	|

**Comment by DarkDimius** [comment]
block 9 takes suspiciously long time.

**Comment by DarkDimius** [comment]
Note that Ychecks trigger info-transformers so the actual running time is slightly less.

**Comment by DarkDimius** [comment]
Here's are relative running times without Ycheck:


| **Phase-ID** | **Phase name**                                                                                                                                                              | **%**     |
|----------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------|
| 1        | frontend                                                                                                                                                                | 46.54% |
| 2        | sbt-deps                                                                                                                                                                | 0.85%  |
| 3        | posttyper                                                                                                                                                               | 2.69%  |
| 4        | sbt-api                                                                                                                                                                 | 5.77%  |
| 5        | pickler                                                                                                                                                                 | 2.39%  |
| 6        | {firstTransform, checkReentrant}                                                                                                                                        | 0.70%  |
| 8        | {tryCatchPatterns, patternMatcher, explicitOuter, explicitSelf, shortcutImplicits, crossCast, splitter}                                                                 | 2.09%  |
| 9        | vcInlineMethods, isInstanceOfEvaluator, seqLiterals, intercepted, getters, elimByName, augmentScala2Traits, resolveSuper, primitiveForwarders, arrayConstructors        | 14.69% |
| 11       | erasure                                                                                                                                                                 | 4.86%  |
| 12       | {elimErasedValueType, vcElideAllocations, mixin, LazyVals, memoize, linkScala2ImplClasses, nonLocalReturns, capturedVars, constructors, functionalInterfaces, getClass} | 2.31%  |
| 14       | {lambdaLift, elimStaticThis, flatten, restoreScopes}                                                                                                                    | 1.31%  |
| 15       | {expandPrivate, selectStatic, collectEntryPoints, collectSuperCalls, dropInlined, moveStatic, labelDef}                                                                 | 0.90%  |
| 17       | genBCode                                                                                                                                                                | 14.92% |

**Comment by DarkDimius** [comment]
Digging deeper into the strage block `9`. After splitting the phases it becomes apparent that `resolveSuper` is very slow
```
[TreeTransform:{tryCatchPatterns, patternMatcher, explicitOuter, explicitSelf, shortcutImplicits, crossCast, splitter}  in 1274ms]

[TreeTransform:{vcInlineMethods, isInstanceOfEvaluator, seqLiterals, intercepted, getters}  in 307ms]

[TreeTransform:{elimByName, augmentScala2Traits}  in 250ms]

[resolveSuper  in 4214ms]
```

**Comment by smarter** [comment]
How did you collect these timings exactly, do you have a branch somewhere to do that?

**Comment by DarkDimius** [comment]
@smarter -verbose and local modifications + jvisualvm for guidance.
Most of the time of resolveSuper is spend in those two lines:
https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/MixinOps.scala#L41

apparently, memberCache hit rate is very low and we recompute members all the time.
Working on it now with @odersky

**Comment by smarter** [comment]
Would be good if you could push these local modifications to a branch for future benchmarking

**Comment by DarkDimius** [comment]
@smarter https://github.com/dotty-staging/dotty/tree/resolve-super-diagnosis

**Comment by nicolasstucki** [comment]
This is not really an issue and numbers are outdated.
