### ISSUE TITLE
Difference in semantics of case classes with Scala 2

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2020]
```scala
case class Foo(a: Int)(b: Int)
```

In Scala2, the `Foo` get `equals` and `hashCode` based on only `a` (parameters in first `()`). In Dotty, the methods use on `a` and `b`.

Is this intended? Is this specified?

**Comment by odersky** [comment]
No, I think this is not intended.

**Comment by smarter** [comment]
This is as specified though I personally find it pretty surprising: http://www.scala-lang.org/files/archive/spec/2.11/05-classes-and-objects.html#case-classes
> Method equals: (Any)Boolean is structural equality, where two instances are equal if they both belong to the case class in question and they have equal (with respect to equals) constructor arguments (restricted to the class's elements, i.e., the first parameter section).
