### ISSUE TITLE
Type mismatch for union types is slow

### ISSUE THREAD

**Issue by olafurpg** [lampepfl/dotty#2030]
To reproduce, running from commit db24246e90f4b8afcaf1fc66df99d38d9a2cb736

```scala
$ cat target/union.scala
object a {
   val x: String | Int = 'a
}
$ time ./bin/dotc target/union.scala
-- [E007] Type Mismatch Error: target/union.scala ------------------------------
2 |   val x: String | Int = 'a
  |                         ^^
  |                         found:    Symbol
  |                         required: String | Int
  |

one error found
./bin/dotc target/union.scala  30.37s user 1.44s system 262% cpu 12.094 total
```

I ran jprofiler on a repl session to see what was happening and got these results 
[union-typeerror.zip](https://github.com/lampepfl/dotty/files/799287/union-typeerror.zip)
 I don't know much about Dotty's typer to make sense of the report.

My understanding from @DarkDimius's comment on Gitter is that union types put a strain on the type-checker for several fundamental reasons. However, 12s to report a type-error on a minimal example sounds like a bug to me.

**Comment by DarkDimius** [comment]
> However, 12s to report a type-error on a minimal example sounds like a bug to me.

12s is indeed unreasonable.

**Comment by odersky** [comment]
It's a diverging implicit search involving `Any2ArrowAssoc` and `Ensuring` and other fundamental Predef decorators. They should not try to form nested implicit conversions but for some reason they do. I have to find out why.

**Comment by olafurpg** [comment]
Thank you! I can confirm that the type error is now reported instantaneously for the example above.
