### ISSUE TITLE
Type Inference for Algebraic Subtyping

### ISSUE THREAD

**Issue by saosebastiao** [lampepfl/dotty#2048]
Sorry this is such an unimaginative issue, but this potentially is huge for those of us that merely tolerate type annotations as a tradeoff for the ability to occasionally use inheritance.

https://www.cl.cam.ac.uk/~sd601/thesis.pdf

Don't consider this a feature request, but maybe a point of discussion. Since many aspects of the scala language are being changed in Dotty, it would be amazing to consider the elimination of the method type annotation requirement as well. 

Also, forgive me if I'm missing something basic like this idea not even being compatible with the DOT Calculus. I'm well aware that I'm out of my element here.

**Comment by odersky** [comment]
Quite to the contrary. I think this is a very interesting and important work to discuss! I first wanted to respond here, but on second thought it's better we move this to https://contributors.scala-lang.org/
Do you want to start a topic there?
