### ISSUE TITLE
TreeTransform should allow miniphases to run fully at group end

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#208]
I currently cannot merge privateToStatic with Flatten because I get a "denotation demanded before it is defined" error. The problem is the error does not appear in Flatten, in fact Flatten is nowhere on the stacktrace. The error is produced by a treecopier invoked from the standard TreeTransform.

The error could be avoided if there is some way we could run the whole phase at group end, not just some operations from it.

**Comment by smarter** [comment]
This has been the default for a few months now.
