### ISSUE TITLE
Erasure incorrectly rewrites isInstanceOf[X & Y] as isInstanceOf[X]

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2084]
It should be rewritten as `isInstanceOf[X] && isInstanceOf[Y]` of course.
Test case that should run without asserting:
```scala
trait X
trait Y

object Test {
  def main(args: Array[String]): Unit = {
    val x: Any = new X {}
    assert(!x.isInstanceOf[X & Y])
  }
}
```

**Comment by DarkDimius** [comment]
AFAIK this should be handled in splitter.

**Comment by smarter** [comment]
No, I think this should be handled by TypeTestCasts which already handles rewriting `isInstanceOf[A | B]`

**Comment by DarkDimius** [comment]
@smarter, I guess you're right. I remembered that there was a phase before easure that did it.
Apparently I was the one to roll it into erasure 2 years ago.

**Comment by DarkDimius** [comment]
Please don't spam "prio:high" this bug doesn't block anything and shouldn't have high priority.

**Comment by smarter** [comment]
1. I don't think I "spam" anything, besides this one, there are only two other open issues I've marked prio:high. I've been basically the only person triaging issues for the past few months, but I'll stop if it's not appreciated.
2. prio:high doesn't mean "blocker" to me, here's the classification I use:
   - high: This is important to fix soon and should not be forgotten.
   - low: It's okay to not fix it now, we'll get to it eventually.
   - medium: everything else.
   - If something was a blocker, I would use a "blocker" or "prio:critical" tag.
3. We can discuss the priority levels and their meaning at the next dotty meeting so that everyone agrees on them.

**Comment by felixmulder** [comment]
Let's do that, also - we should choose a person for triaging for meeting
day + 1 month.

Cheers,
Felix
