### ISSUE TITLE
sbt-bridge: Broken display of reported messages

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2092]
If you run `sbt dotty-compiler-bootstrapped/compile` you'll see things like:
![2017-03-13-235341_3840x2160_scrot](https://cloud.githubusercontent.com/assets/63430/23878567/65034f3c-0848-11e7-9a2a-1fca5e56419d.png)

Two things are wrong:
- The filename and line number is displayed twice
- The caret is displayed twice, the second time in an extremely long line

/cc @felixmulder @MasseGuillaume

**Comment by smarter** [comment]
A few methods of `xsbti.Position` have been incorrectly implemented in `DelegatingReporter`, compare:
- https://github.com/sbt/sbt/blob/0.13/compile/interface/src/main/scala/xsbt/DelegatingReporter.scala#L55-L66
- https://github.com/lampepfl/dotty/blob/b3194406d8e1a28690faee12257b53f9dcf49506/sbt-bridge/src/xsbt/DelegatingReporter.scala#L30-L38

**Comment by MasseGuillaume** [comment]
@smarter 

I just ran `sbt dotty-compiler-bootstrapped/compile` from a fresh build. I saw some resolving error, so I assumed I need to publish dotty locally. I ran `sbt publishLocal`. This is what I get:

```

-- [E029] Match case Unreachable Warning: /tmp/sbt_398dc0a0/dotty/tools/dottydoc/model/comment/CommentParser.scala 
114 |      case line :: ls if (lastTagKey.isDefined) => {
    |                                                ^
    |                                                unreachable code
115 |        val newtags = if (!line.isEmpty) {
116 |          val key = lastTagKey.get
117 |          val value =
118 |            ((tags get key): @unchecked) match {
119 |              case Some(b :: bs) => (b + endOfLine + line) :: bs
120 |              case None => oops("lastTagKey set when no tag exists for key")
121 |            }
122 |          tags + (key -> value)
123 |        } else tags
124 |        parseComment(docBody, newtags, lastTagKey, ls, inCodeBlock)
125 |      }
-- [E029] Match case Unreachable Warning: /tmp/sbt_398dc0a0/dotty/tools/dottydoc/model/comment/CommentParser.scala 
127 |      case line :: ls => {
    |                      ^
    |                      unreachable code
128 |        if (docBody.length > 0) docBody append endOfLine
129 |        docBody append line
130 |        parseComment(docBody, tags, lastTagKey, ls, inCodeBlock)
131 |      }

16 warnings found
there were 32 deprecation warning(s); re-run with -deprecation for details
[info]   Compilation completed in 70.392 s
[trace] Stack trace suppressed: run last dotty-library-bootstrapped/compile:compileIncremental for the full output.
[error] (dotty-library-bootstrapped/compile:compileIncremental) java.lang.NoSuchMethodError: dotty.tools.dotc.reporting.UniqueMessagePositions.initial$dotty$tools$dotc$reporting$UniqueMessagePositions$$positions()Lscala/collection/mutable/HashMap;
[error] Total time: 89 s, completed Mar 13, 2017 9:55:26 PM
```

**Comment by smarter** [comment]
@MasseGuillaume Something is probably wrong with your setup, try doing sbt clean first. Also instead of compiling dotty itself you can just grab https://github.com/smarter/dotty-example-project and add a few errors in there.
