### ISSUE TITLE
Warn about missing back-ticks in pattern matching

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#2105]
In codes like the following, it would be nice to warn the user that he probably meant to write case \`x\` instead:

```scala
val x = 1
List(1) match {
  case x :: Nil => 1
  case _        => 0
}
```

**Comment by DarkDimius** [comment]
IDEs already do this. I'm not sure if we should try to replace inspections in IDEs.

**Comment by smarter** [comment]
The Dotty IDE doesn't, and the only way to implement it in the IDE would be to add it to the compiler. The alternative would be to have a separate tool to do code inspections that could be reused by various IDEs like https://github.com/scala/scala-abide but that seems like more work than just adding a warning to the compiler.

**Comment by odersky** [comment]
I believe the details would be tricky. E.g. the following should certainly not produce a warning.

    val x: Any = 1
    x match {
       case x: Int => 1
       case _        => 0
    }

How about this one:

   object NonNull {
      def unapply[T <: AnyRef](x: T): Option[T] = Option(x)
   }

   x = "abc"
   x match {
     case NonNull(x) => ...
     ...
   }

So, I think changing this would require more thought and an evaluation of the tradeoffs.
