### ISSUE TITLE
Add timestamp to generated docs

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#2115]
We should add a timestamp like

```html
<!-- generated on: 2017-03-17 18:31:20 -->
```

Somewhere in the html so that we can know when the docs were last generated.

**Comment by trancynn** [comment]
Looks like that information should be more accessible (it's inconvenient to look through the HTML source just to find out when docs were generated). How about adding it somewhere else (e.g. sidebar)?

**Comment by felixmulder** [comment]
I'd rather not - in the 2.12 docs we opted for adding the version number to the top-left corner. When they do nightlies, it gets the git hash and date.

That's fine - but I'd rather not bloat the UI by adding a timestamp by default.

For our purposes, we can just look at the `gh-pages` branch to see that the docs were last generated a while ago.

**Comment by Varunram** [comment]
@felixmulder Is it nice if we add it at the top? Or are you looking for a more specific location?

**Comment by felixmulder** [comment]
Sure, this is fine - it could be done in combination with adding the project title somewhere :)
