### ISSUE TITLE
Add intellij import checking to our CI

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2130]

**Comment by OlivierBlanvillain** [comment]
Issue created for standalone versions of

- [IntelliJ type checker](https://youtrack.jetbrains.com/issue/SCL-11572)
- [IntelliJ sbt project import](https://youtrack.jetbrains.com/issue/SCL-11573)

Until then, I guess the best bet would be `xvfb` + `xdotool`?

**Comment by OlivierBlanvillain** [comment]
Actually there is [JetBrains/sbt-structure](https://github.com/JetBrains/sbt-structure): it's supposed to be what's used by the IDE to import sbt project. Problem is, the plugin succeeds to import the build as it was before #2129 :unamused:

**Comment by smarter** [comment]
Has anyone actually tried to iport the build before #2129 using IntelliJ 2017.1 ?

**Comment by OlivierBlanvillain** [comment]
Yes, I tried that yesterday during @DarkDimius presentation, the process fail in the last step with an unresponsive "OK" button.

**Comment by smarter** [comment]
Closing because there's no easy way to do this, and we'll obsolete IntelliJ sooner or later :).
