### ISSUE TITLE
Make dotty more newcomer friendly

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2131]
Newcomers currently face multiple issues with Dotty,
- not being able to import to IDE
- getting strange error messages, eg. I currently see null pointer exceptions when running tests on a clean clone. I suspect those are triggered by absence of `./scala-scala/` but this is the most unfriendly way to report it.
- our "test" output is ~50k lines of code, most of those are start with "error:" but they are not errors! this is just output of tests and we expect users to ignore it.

Additionally, I believe our build has much magic, that requires the system to be set-up in a very specific way. Tools that try to understand the build(eg IntelliJ) frequently can't figure it out and report unhelpful errors. 

We should make Dotty more newcomer friendly by reducing amount of various magic happening in the build & the ci. I'd prefer to get rid of this magic, but another alternative will be to hide it even deeper.

**Comment by felixmulder** [comment]
Are you still having an issue with the first one post #2129 ?

**Comment by DarkDimius** [comment]
> Are you still having an issue with the first one post #2129 ?

I do have non-fatal issues, which still may disctract people. In particular from time to time intellij shows error in events and log complains that it can't get structure of dotty-bootstrapped.

**Comment by nicolasstucki** [comment]
Now the newcomers use VS Code, which has it's own set of issues.
