### ISSUE TITLE
patmat selector gets widened too much

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2143]
```scala
object Test {
  type T <: AnyRef

  def test(x: T): Unit = {
    x match {
      case foo =>
        val z: T = foo
    }
  }
}
```
This compiles with scalac but fails in dotty with:
```scala
-- [E007] Type Mismatch Error: try/collect.scala -------------------------------
7 |        val z: T = foo
  |                   ^^^
  |                   found:    Object(foo)
  |                   required: Test.T
```
This happens because we aggressively widen the selector in `typedMatch`:
```scala
        val selType = widenForMatchSelector(
            fullyDefinedType(sel1.tpe, "pattern selector", tree.pos))
```
Replacing `widenForMatchSelector` for by a call to `.widen` fixes the issue, but breaks one test:  `tests/patmat/for.scala` which is run with `-Ycheck-all-patmat` and should not report any exhaustivity warning, I'm not sure why there's a difference here. A possible solution would be to call `widenForMatchSelector` inside the exhaustivity checker, but I don't know if that gives the correct semantics.

**Comment by liufengyun** [comment]
Closely related #1330 ,  related #1710

**Comment by liufengyun** [comment]
The following change also solves the problem, I'm not sure if it's the correct way to do it.

```Scala
   def widenForMatchSelector(tp: Type)(implicit ctx: Context): Type = tp.widen match {
-    case tp: TypeRef if !tp.symbol.isClass =>
+    case tp: TypeRef if !tp.symbol.is(Deferred) =>
         widenForMatchSelector(tp.superType)
      case tp: HKApply =>
        widenForMatchSelector(tp.superType)
      case tp: AnnotatedType =>
        tp.derivedAnnotatedType(widenForMatchSelector(tp.tpe), tp.annot)
      case tp => tp
    }
```

**Comment by odersky** [comment]
I can't remember why we introduced widenForMatchSelector. I'd replace with `widen` and maybe Fengyun can have a look at the exhaustivity problem in for.scala?

**Comment by liufengyun** [comment]
OK, I'll replace it just with `widen` and fix the problem with exhaustivity check.
