### ISSUE TITLE
Annotations not extending scala.annotation.Annotation

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#2145]
scalac accepts this, dotty requires `A` to extend `scala.annotation.Annotation`:

```scala
class A

object O {
  @A def f = 1
}
```

**Comment by nicolasstucki** [comment]
Why does scalac accept this?

**Comment by DarkDimius** [comment]
May be related:
https://github.com/lampepfl/dotty/issues/389

**Comment by odersky** [comment]
> Why does scalac accept this?

I would have answered: So that we can use Java annotations, but I see that these are already treated as subclasses of annotations. So indeed, I don't see why we should follow `scalac` here.

**Comment by Varunram** [comment]
Guys, what's the final conclusion here? Do we follow `scalac`? Thanks!

**Comment by odersky** [comment]
I think it's better to require that annotations extends Annotation. Unless we see convincing use cases that do not do this. What are Java's rules?

**Comment by Varunram** [comment]
In Java, As far as I know, we can not extend `Annotation` types (since `Annotation` extends `annotation.Annotation`)

**Comment by odersky** [comment]
Yes, but I think Java requires annotations to come from an annotation class (i.e. an `@interface`), no?

**Comment by Varunram** [comment]
Yes, sir

**Comment by jozi-k** [comment]
Probably resolved.

**Comment by smarter** [comment]
Yup.
