### ISSUE TITLE
Compiler dies somewhere in the middle of typechecking

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#2151]
https://gist.github.com/alexknvl/0a4af0baeb6ff49a850fe6e9a9765c8a

**Comment by felixmulder** [comment]
Thank you for reporting - it does indeed crash the compiler when `ys` is `Nil` in [Decorators.scala](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/Decorators.scala#L108)
