### ISSUE TITLE
Orphan PolyParam

### ISSUE THREAD

**Issue by propensive** [lampepfl/dotty#2152]
The following causes the compiler to crash when trying to pickle some trees.

```scala
class Contra[-D](task: AnyRef)
object Test {
  def narrow(task: AnyRef): Contra[task.type] = new Contra(task)
  def ident[Before](elems: Contra[Before]): Contra[Before] = elems
  val foo = null
  ident(narrow(foo))
}
```

The output from the compiler is [here](https://github.com/lampepfl/dotty/files/881600/output.txt).

**Comment by DarkDimius** [comment]
> Exception in thread "main" java.lang.AssertionError: assertion failed: orphan poly parameter: PolyParam($param$1)


That's an actual error, unrelated to pickling. Likely from typer.
