### ISSUE TITLE
`@unchecked` fails to compile when annotation.unchecked package imported

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#2170]
```scala 
import annotation.unchecked

@unchecked
class Test
```
Compiles with scalac but not with dotty
```scala
-- Error: tests/tmp/Test.scala -------------------------------------------------
3 |@unchecked
  |^^^^^^^^^^
  |annotation.unchecked does not have a constructor
```
Removing the import fixes the problem

**Comment by smarter** [comment]
To clarify what's going on here: `@unchecked` should refer to `scala.unchecked`, `annotation.unchecked` is an unrelated package: http://www.scala-lang.org/api/2.11.8/#scala.annotation.unchecked.package

Even when the package is imported, scalac seems to be able to determine that we want `@unchecked` to refer to `scala.unchecked` but dotty doesn't.

**Comment by amanjpro** [comment]
I like the dotty behavior more. An annotation is technically a class, and when you explicitly import a name, it should take precedence over the the default imports.

If we "fix" this, we should also make `import scala.collection.mutable.Map` not hide the immutable counterpart.
