### ISSUE TITLE
Rewrite REPL based on Language Server

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#2195]
Rewrite the REPL based on the Language Server protocol implemented in #2179.

The current REPL does adhoc things - scary things. And it should therefore be rewritten using the language server as a base. This will give us proper information on types and allow for tab-completion etc.

**Comment by abeln** [comment]
@felixmulder if I can help with this in any way, please let me know. I'd be quite interested in contributing regularly to the REPL. Plus, I now have more time to work on dotty since it's the topic for my masters (which I just started).

**Comment by felixmulder** [comment]
That's great @abeln - would love to cut you in on this. First, however, we must get the IDE into the repo. I'll ping you once I have a clear grasp on this.

Cheers,
F
