### ISSUE TITLE
aliasing gets less precise type than Scala

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#2198]
In Scala, `Nil` gets the type `collection.immutable.Nil.type`, but in Dotty it gets `scala.collection.immutable.Nil$`.

```Scala
object Test {
  val Nil = scala.collection.immutable.Nil
}
```

**Comment by smarter** [comment]
Is this an issue for anything in practice?

**Comment by DarkDimius** [comment]
In Dotty, `scala.collection.immutable.Nil$` will have a self-type `collection.immutable.Nil.type`. Do you have an example where you'll be able to see a distinction?

**Comment by smarter** [comment]
There's also a special case in subtyping: https://github.com/lampepfl/dotty/pull/1448, I wasn't sure if that special-casing was the right way to go, so feel free to propose a better solution if this one doesn't work in some cases.

**Comment by liufengyun** [comment]
The problem I have is the exhaustivity of the following program:
```Scala
object Test {
  val Nil = scala.Nil
  val X = 5

  def foo1b[T](l: List[T]) = l match {
    case Nil => true
    case x::xs => false
  }
}
```
The checker will report that `Nil` is not matched, because:

```Scala
scala.collection.immutable.Nil.type <:< scala.collection.immutable.Nil$(Test.Nil) = false
```

The checker can special case, but given that now we also have `case val` for enum, but it would be nice that the checker only rely on the type system.

**Comment by smarter** [comment]
Ah indeed, that seems like a good reason for changing the inference rule (and reverting #1448).

**Comment by liufengyun** [comment]
The following code can serve as test case, which is accepted by Scala but rejected by Dotty:

```Scala
object Test {
  val nil = scala.collection.immutable.Nil
  def f(x: nil.type): Int = 3

  f(scala.collection.immutable.Nil)
}
```

**Comment by smarter** [comment]
If you want to try to fix it, it should probably be done in `inferredType` in `Namer`: https://github.com/lampepfl/dotty/blob/586113dab51d95f2a606c83b2cd31563ac47a6cf/compiler/src/dotty/tools/dotc/typer/Namer.scala#L971

**Comment by liufengyun** [comment]
Thanks @smarter for the pointer, I'll play with it .

**Comment by smarter** [comment]
> The justification is that code that avoids widening is very rare, maybe 1/10000, it doesn't make sense to make a rarity a rule in the language.

It's not actually that rare, it's a common pattern to alias objects in a different package, e.g. https://github.com/scala/scala/blob/2.12.x/src/library/scala/Predef.scala#L150, https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/io/package.scala#L16, etc.
