### ISSUE TITLE
Missing information in Vulpix test logs

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2210]
There is currently no way to inspect compiler logs after a failure or success of a test. This will become a blocker when we remove partest.

**Comment by felixmulder** [comment]
Gathering some more precise information in this issue:

- On failure, the logs are dumped for all failed tests by the summary report: [SummaryReport.java](https://github.com/dotty-staging/dotty/blob/a44d8f853bc912f361b3a5d02efc4c55dd452d5b/compiler/test/dotty/tools/vulpix/SummaryReport.java#L77-L111)
- The things that are dumped is everything from the test reporter's `messageBuf` courtesy of [TestReporter#flushToFile](https://github.com/dotty-staging/dotty/blob/a44d8f853bc912f361b3a5d02efc4c55dd452d5b/compiler/test/dotty/tools/dotc/reporting/TestReporter.scala#L27-L31)
- All compiler errors and messages are added to the buffer here: [TestReporter#printMessageAndPos](https://github.com/dotty-staging/dotty/blob/a44d8f853bc912f361b3a5d02efc4c55dd452d5b/compiler/test/dotty/tools/dotc/reporting/TestReporter.scala#L60-L61)

Things that are not dumped to file:

- Other prints to stderr

When things are not dumped to log:

- Zero failed tests

In #2194 we need to make sure of the following the fix these issues:

- Tests should all be using the reporter from `TestSummary` (everything printed to a single file by a single reporter)
- Should add some way to always dump all logs
