### ISSUE TITLE
Named import shadows underscore value import

### ISSUE THREAD

**Issue by olafurpg** [lampepfl/dotty#2212]
I am not sure if this is a bug or intentional behavior. I bumped into this while compiling [squants](https://github.com/typelevel/squants) with Dotty.
 
The following snippet compiles with scalac but not Dotty
```scala
package object squants {
  type Time = squants.time.Time
}
package squants.time {
  class Time
  object Time { def x = 2 }
}
package squants.velocity {
  import squants.Time // <-- imports  type alias
  import squants.time._  // <-- imports `Time` value
  object Velocity { Time.x }
}
```

Dotty reports "E008 member not found":

```scala
-- [E008] Member Not Found Error: package.scala --------------------------------
11 |  object Velocity { Time.x }
   |                    ^^^^
   |value `Time` is not a member of squants.type - did you mean `squants.time`?

one error found
```
It seems that the import on the `Time` type alias shadows the underscore import on the `Time` companion object. Commenting out `import squants.Time` (import on type alias) removes the error.

Commit to reproduce issue in the dotty repo: https://github.com/lampepfl/dotty/commit/2487e7837f3aa8760a12aa2dcacc0afae8d17203

FWIW, the Dotty behavior feels somewhat more intuitive to me since named imports have a higher precedence.

**Comment by smarter** [comment]
This doesn't answer your question, but it seems like the package object for squants should also alias the object, not just the class:
```scala
package object squants {
  type Time = squants.time.Time
  val Time = squants.time.Time
}
```

**Comment by propensive** [comment]
Regarding the example, I notice that although `squants.Time` is imported explicitly, it's actually already in the enclosing scope of the `squants.velocity` package because it's in the `squants` package object. I'm not sure if that's part of the issue, or if it just means there's a further slight minimization opportunity.

**Comment by olafurpg** [comment]
Here is another example that I'm not sure is related but also involves types and values being imported separately

```scala
import scala.math.BigDecimal.RoundingMode
import scala.math.BigDecimal.RoundingMode.RoundingMode

object Money {
  def foo(round: RoundingMode = RoundingMode.HALF_EVEN): Int = ???
}
```

Dotty reports the following errors

```ruby
-- [E008] Member Not Found Error: RoundingMode.scala ---------------------------
6 |  def foo(round: RoundingMode = RoundingMode.HALF_EVEN): Int = ???
  |                 ^^^^^^^^^^^^
  |type `RoundingMode` is not a member of math.BigDecimal.type - did you mean `BigDecimal.RoundingMode`?
-- [E008] Member Not Found Error: RoundingMode.scala ---------------------------
6 |  def foo(round: RoundingMode = RoundingMode.HALF_EVEN): Int = ???
  |                                ^^^^^^^^^^^^
  |value `RoundingMode` is not a member of math.BigDecimal.RoundingMode.type - did you mean `RoundingMode.RoundingMode`?

two errors found
```
while scalac compiles OK.

I can open a separate ticket, but thought I might add it here first to see if it's a duplicate.
