### ISSUE TITLE
REPL crash on typeless method definitions

### ISSUE THREAD

**Issue by propensive** [lampepfl/dotty#2213]
The following is sufficient to cause the REPL to crash with an `ArrayIndexOutOfBoundsException`:
```
scala> def x
```
Including an additional space character at the end gives the expected error message, and hence changing `code` to `(code+" ")` on [this line](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/repl/CompilingInterpreter.scala#L173) seems to fix the problem, but it seems like there should be a less hacky fix.

Full output from the above example is [here](https://github.com/lampepfl/dotty/files/910168/stack.txt).

**Comment by DougAshton** [comment]
Should the REPL show a syntax error  like:

```
scala> def 
-- [E018] Syntax Error: <console>:1:3 ------------------------------------------
1 |def
  |       ^
  |       missing return type
```

or should it prompt for more input like :

```
scala> def x
          |
```

**Comment by propensive** [comment]
@DougAshton Yes, I'd expect something like that.
