### ISSUE TITLE
Missing requirement: self type does not conform to self type A

### ISSUE THREAD

**Issue by olafurpg** [lampepfl/dotty#2214]
The following code snippet compiles with scalac but not with dotc

```scala
package squants
trait Quantity[A <: Quantity[A]] { self: A => }
trait TimeDerivative[A <: Quantity[A]] { self: Quantity[_] => }
```

Dotty reports the error message

```
-- Error: tests/pos/missing-requirement/Quantity.scala -------------------------
3 |trait TimeDerivative[A <: Quantity[A]] { self: Quantity[_] => }
  |      ^
  |missing requirement: self type squants.Quantity[_] & squants.TimeDerivative[A] of trait TimeDerivative does not conform to self type A' of required trait Quantity
  |
  |where:    A  is a type in trait TimeDerivative with bounds <: squants.Quantity[LazyRef(A)]
  |          A' is a type in trait Quantity with bounds <: squants.Quantity[LazyRef(A)]
```

Removing the `self: Quantity[_]` annotation on `TimeDerivative` removes the error, and makes the rest of the `squants` project compile with Dotty 🎉

**Comment by odersky** [comment]
We now check that the self type is closed. See 175499537c87c78d0b926d84b7a9030011e42c00
in https://github.com/lampepfl/dotty/pull/702. We should still spec this.

**Comment by olafurpg** [comment]
What is the recommended migration path for code like `TimeDerivative ` above? Could the error message provide more details?

**Comment by odersky** [comment]
@olafurpg Let's worry about this if we see several errors of this type. For know I am hoping this is quite a rare case.

**Comment by smarter** [comment]
@olafurpg I think you should be able to replace `self: Quantity[_]` by `self: A`

**Comment by Blaisorblade** [comment]
For what it's worth: I'm not sure I understand https://github.com/lampepfl/dotty/pull/702/files#diff-ca3386647f5386b6f70e99f1a9e188cdR3196, but certainly the error "missing requirement" is misleading.

**Comment by SethTisue** [comment]
A simpler example that Scala 2 accepts but 3 does not came up on Gitter yesterday:

```
trait A
trait B { self: A => }
trait C { self: B => }
```

**Comment by dwijnand** [comment]
That's the example in 175499537c87c78d0b926d84b7a9030011e42c00 (in reverse line order and alphabet letter order) so I take it as expected and intentional.
