### ISSUE TITLE
Move bridge generation from erasure into a MiniPhase

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2221]
Bridge generation seems to only need to erase type signatures of methods. 
This can be done in a mini-phase before erasure that will use TypeErasure to generate bridges.
This will be a good step in splitting erasure.

**Comment by nicolasstucki** [comment]
Briges where extracted from Erasure in 92fe2a50a91b22c3efa0f1b5746378d987966429.
They are still being created in erasure.

**Comment by nicolasstucki** [comment]
@odersky @smarter DYT there is value in further extraction of the bridge generation.

**Comment by odersky** [comment]
I think we are good now.
