### ISSUE TITLE
Implicit search of views ignores implicit functions

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#2223]
The following code compiles in Scalac, but fails in Dotty:
```Scala
class QuickSort[Coll](a: Coll) {
  def size[T](implicit ev: Coll => List[T]): Int = a.size
}
```

**Comment by smarter** [comment]
This is an intentional change, see https://github.com/lampepfl/dotty/pull/2065 You need to either use `-language:Scala2` or use `ImplicitConverter` (it's unfortunate that this won't compile with Scala 2)
