### ISSUE TITLE
Update CI to kill ongoing tests on new commit

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#2226]
For example in #2224 I just amended and forced pushed a commit with, but because Drone is still running the tests for the previous commit that's 15 min of CI time wasted.

To be a good CI citizen I need to open the web interface and cancel every job of the matrix commit by hand...

**Comment by felixmulder** [comment]
We should probably have the bot do this, I'm not sure drone supports this.

You can also:

```bash
 for i in $(seq 6); do drone build stop lampepfl/dotty <build-nbr> $i done
```

**Comment by smarter** [comment]
Would be even better if we could cancel all jobs at the same time in the web UI. It's pretty dumb that you cannot do that, but when you restart one job it restarts all the jobs for the current PR :/

**Comment by felixmulder** [comment]
agreed

**Comment by OlivierBlanvillain** [comment]
Looks like neither of these are gonna be implemented anytime soon :unamused: 

- https://github.com/travis-ci/travis-ci/issues/964
- https://github.com/travis-ci/travis-ci/issues/961

**Comment by nicolasstucki** [comment]
This is currently happening
