### ISSUE TITLE
Test logs sometimes contain color codes

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2245]
This doesn't happen with all tests, but I've seen it happen with "dotty1$1".

**Comment by felixmulder** [comment]
I can't reproduce this - can you do this post #2248?

**Comment by smarter** [comment]
You can reproduce it by running `tastyBootstrap`, if you look at the options passed to `tastyBootstrap#dotty1` you'll see that they don't include the option to disable colors.
