### ISSUE TITLE
Semantic names not used in LambdaLift

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2246]
The semantic name PR broke compilation of scalatest, see https://github.com/lampepfl/dotty/issues/2233, the stacktrace is at https://gist.github.com/smarter/2b03b8fc57f7b8e4a027affe39b4426b and fails in LambdaLift. I'm not sure why, but I've noticed that LambdaLift defines the following method:
```scala
    private def newName(sym: Symbol)(implicit ctx: Context): Name =
      if (sym.isAnonymousFunction && sym.owner.is(Method, butNot = Label))
        (sym.name ++ NJ ++ sym.owner.name).freshened
      else sym.name.freshened
```
Which seems like it should be creating a semantic qualified name instead.

**Comment by odersky** [comment]
I don't think that's what it is. I think it rather has to do with #2216
