### ISSUE TITLE
Stop depending on scala-reflect

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2271]
After the [hyper bootstrap](https://github.com/lampepfl/dotty/pull/2260) and https://github.com/lampepfl/dotty/pull/2062, the remaining uses of scala-reflect are:
- `scala.reflect.io.*`, should be replaced by our own abstraction layer (@felixmulder is working on one).
- `scala.reflect.internal.util.WeakHashSet` used only in the backend, should be copy-pasted into the dotty sources.

**Comment by smarter** [comment]
Fixed a while ago.

**Comment by allanrenucci** [comment]
Do you mean it can be removed from: https://github.com/lampepfl/dotty/blob/211cc8f1d0d06a45a70e6b7b4c6e5a9468abb5d4/project/Build.scala#L1167

**Comment by smarter** [comment]
This one is just a dummy we create in our build, not the real scala-reflect that we used to depend on.
