### ISSUE TITLE
lazy val locking

### ISSUE THREAD

**Issue by baszo** [lampepfl/dotty#2275]
I wrote a comment on SIP-20. And I think problem is also with dotty because it is based on same concept.

I found a problem with implementation of lazy val. When one thread will initialize lazy val and other check that val is already initializing then call wait4Notification and set flag to 2. Then it is possibility that first thread finished initializing and checked that flag which is set to 2 and do notifyAll on monitor. After that second thread will call wait and it will lock forever. Problem is with time between setting flag and wait on monitor.

My solution is :

```scala
@inline def wait4Notification(t: Object, offset: Long, cur: Long, ord: Int) = {
  println(s"${Thread.currentThread().getId()}-wait4Notification($t, $offset, $cur, $ord)")
  var retry = true
  while (retry) {
    val cur = get(t, offset)
    val state = STATE(cur, ord)
    if (state == 1) {
      val monitor = getMonitor(t, ord)
      //make sure that thread will wait on monitor
      monitor.synchronized {
        if(CAS(t, offset, cur, 2, ord))
          monitor.wait()
      }
    }
    else if (state == 2) {
      val monitor = getMonitor(t, ord)
      monitor.synchronized {
        println(s"${Thread.currentThread().getId} -$monitor - wait")
        monitor.wait()
      }
    }
    else retry = false
  }
}
```

**Comment by DarkDimius** [comment]
Hi Andrzej,

Thanks for writing. You are right that the implementation has a formal bug. Strange that we haven't seen it ever occur in hours and hours of benchmarking the implementation both done by me and Alex.

Unfortunately your fix is both inefficient and incorrect:
 - inefficient in making CAS inside the first synchchronized block. it's a very pessimistic act that is rarely needed;
 - incorrect in that the second synchronized block still has the same issue and can lead to a thread waiting forever.

Could you please come to https://github.com/lampepfl/dotty/pull/2276 and review my proposed fix?

Thank you,
Dmitry

**Comment by DarkDimius** [comment]
// I've modified your comment to fix github formatting.

**Comment by nicolasstucki** [comment]
What is the status of this fix?

**Comment by Blaisorblade** [comment]
The issue is still there, see #2276 (and #2535).

**Comment by smarter** [comment]
Just hit this again in `dotty.tools.io.FileZipArchive.$1$` while compiling https://github.com/PDBP/pdbp. I'm raising the priority of this because this is really a critical bug we need to fix somehow.

**Comment by allanrenucci** [comment]
Since we have concerns about the size of the generated code and the correctness of the new implementation, I propose we revert to the Scala 2 implementation for thread safe lazy fields. One can always revive [SIP-20](https://docs.scala-lang.org/sips/improved-lazy-val-initialization.html#performance) in the future.
