### ISSUE TITLE
Compiler crash when type argument constrained by an implicit function type

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#2278]
Let's assume we have a `trait Foo` parameterized by a unary tyco `C[_]`. `CC` represents a concrete case. Trying to reconstruct a "fluent" api out of this trait (or algebra) we create a `meth` that takes `foo` implicitly, as in the following code, and compiles successfully:

```scala
object Fluent {
  trait Foo[C[_]] {
    def meth1[T]() : C[T]
  }
  trait CC[T]

  def meth1[E, Alg[x[_]] <: Foo[x]](implicit alg : Alg[CC]) : CC[E] = {
    implicitly[Foo[CC]].meth1()
  }
}
```

However, if we try to use implicit function types, it doesn't, as in the code below. Note that `meth1` is parameterized. In the previous example the type is inferred (through the instantiation `CC[E]`), but not in the code below, and it crashes ([stacktrace](https://gist.github.com/biboudis/f01f76ca03ec7c00c0c68fb22279bbd0)). By passing the type parameter explicitly, `meth1()[T]` , it compiles.

```scala
object Fluent {
  trait Foo[C[_]] {
    def meth1[T]() : C[T]
  }
  trait CC[T]

  type Context[Alg[x[_]] <: Foo[x], E] = implicit Alg[CC] => CC[E]

  def meth1[T]() : Context[Foo, T] = {
    implicitly[Foo[CC]].meth1()
  }
}
```

In the parameterless case, typer tries to `adapt to subtype implicit Fluent.Foo[[=Fluent$CC$$T] => Fluent.CC[=T]] => Fluent.CC[Nothing] !<:< Fluent.Context[[=Fluent$Foo$$C <: [=_$1] => Any] => Fluent.Foo[=C], T]` and crashes later on, during the folding of class types in method `liftToClasses` while doing implicit resolution.

Maybe #2232 is related!

**Comment by odersky** [comment]
I believe the nested implicits fix fixed this one as well. Could not reproduce on master.

**Comment by biboudis** [comment]
@odersky: the following type checks
```scala
object Test {
  trait Foo[C[_]] {
    def meth1[T]() : C[T]
  }
  trait CC[T]

  type Context[Alg[x[_]] <: Foo[x], E] = implicit Alg[CC] => CC[E]

  trait Test[T]{

    def meth1() : Context[Foo, T] = {
      implicitly[Foo[CC]].meth1()
    }
  }
}
```

while the following does not:

```scala
object Test {
  trait Foo[C[_]] {
    def meth1[T]() : C[T]
  }
  trait CC[T]

  type Context[Alg[x[_]] <: Foo[x], E] = implicit Alg[CC] => CC[E]

  trait Test[T]{
    def ev: Context[Foo, T] = implicitly[Foo[CC]]

    def meth1() : Context[Foo, T] = {
      ev.meth1()
    }
  }
}
```
is that correct?

**Comment by OlivierBlanvillain** [comment]
That's correct, the reported error shows the problem:

```scala
9 |  def ev: Context[Foo, Int] = implicitly[Foo[CC]]
  |                              ^^^^^^^^^^^^^^^^^^^
  |                          found:    Test.Foo[[=Test$CC$$T] => Test.CC[=T]]
  |                          required: Test.CC[Int]
```

**Comment by biboudis** [comment]
Indeed. For the record I was messing up HKT + Implicit Function Types. Things are more clear now

https://gist.github.com/biboudis/9d1ec05229cc06fd6f9ccc5ac012594d

Thanks!
