### ISSUE TITLE
Need updates in "Getting Started"

### ISSUE THREAD

**Issue by helloqirun** [lampepfl/dotty#2284]
It might be good to add
```
git submodule update --init
```
to the "getting started" section to reflect the recent "scala-backend" changes.

Otherwise, the dotty simply could not compile.

**Comment by OlivierBlanvillain** [comment]
Hi! Instructions in both getting-started and workflow pages have `git clone --recursive`, so I think they are up to date with the use of a submodule. What would you like to add?

**Comment by helloqirun** [comment]
Hi, I am referring to this page: http://dotty.epfl.ch/docs/contributing/getting-started.html

**Comment by helloqirun** [comment]
Hi, I am referring to this page: http://dotty.epfl.ch/docs/contributing/getting-started.html
It's simply ```git clone``` there.

**Comment by OlivierBlanvillain** [comment]
Oh I see, it looks like the website didn't get updated in a while ([the markdown](https://github.com/lampepfl/dotty/blob/master/docs/docs/contributing/getting-started.md#compiling-and-running) is up to date).

/cc @felixmulder

**Comment by felixmulder** [comment]
The CI pushes to this branch: https://github.com/lampepfl/dotty/tree/gh-pages

Last update is 9 days ago.

**Comment by dwijnand** [comment]
If possible I'd advise a fail-fast check for those (like myself) that clone first and look at instructions after and would've missed the `--recursive` anyways.

**Comment by smarter** [comment]
@dwijnand If you can come up with a nice check we could add to our sbt compile task, please make a PR ;).

**Comment by MasseGuillaume** [comment]
This can be done in sbt: https://github.com/scala-native/scala-native/blob/master/build.sbt#L307

**Comment by biboudis** [comment]
dottydoc now reflects the changes to the scala-backend!

Thanks!

**Comment by dwijnand** [comment]
Are the 3 submodules defined in master no longer required to build dotty?

https://github.com/lampepfl/dotty/blob/d97d35d1249b25090a635643394bd3bc42795139/.gitmodules

If so I'd say this is still an easy trap to fall in. This should be reopened and fixed, imho.

**Comment by OlivierBlanvillain** [comment]
@dwijnand the docs are up to date (see `git clone --recursive` [here](http://dotty.epfl.ch/docs/contributing/getting-started.html)), and we also have [this](https://github.com/lampepfl/dotty/blob/d97d35d1249b25090a635643394bd3bc42795139/project/Build.scala#L1032-L1042) in the build. What else could be added?

**Comment by biboudis** [comment]
Yeap, the documented `git clone --recursive https://github.com/lampepfl/dotty.git` is recursively checking submodules (there was a commit 20 days ago IIRC).

@dwijnand let us know if this doesn't work for you! 👍

**Comment by dwijnand** [comment]
Ah, that build change is exactly the kind of thing I was looking for (added in response to https://github.com/lampepfl/dotty/issues/2132). Excellent. :+1:
