### ISSUE TITLE
Show the real git hash in the REPL welcome message, when running `repl` or `bin/dotr`

### ISSUE THREAD

**Issue by dwijnand** [lampepfl/dotty#2291]
Currently when running `repl` or `bin/dotr` the REPL shows:

```
Welcome to Scala.next (pre-alpha, git-hash: unknown)  (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
```

The reason is that the git hash is defined in terms of the JAR manifest, which isn't present.

Possible solutions include:
* moving to a generated properties file instead of the manifest (what Scala does)
* package the jar and run the REPL from the jar instead
* some other solution involving a temporarily generated MANIFEST.MF

**Comment by felixmulder** [comment]
Thanks for reporting Dale!

Currently not at work, but quick answer: this was solved already. There's a PR by an external contributor that solved this.

We should find out why it's no longer working.

**Comment by dwijnand** [comment]
Do you mean https://github.com/lampepfl/dotty/pull/1571 ?

**Comment by felixmulder** [comment]
Yes! :)

**Comment by dwijnand** [comment]
That's still the current implementation, and that works fine from JAR (I assume).

This issue is an enhancement request that it does better than "git-hash: unknown" when running `repl` or `bin/dotr`.

**Comment by felixmulder** [comment]
Then `bin/dotr` should be working, since it uses the jar...hmm. Will have to investigate.

**Comment by dwijnand** [comment]
You're right, the problem is only in `repl`.

```
$ bin/dotr
The script is going to build the required jar files
Building dotty-interfaces...done
Building dotty-compiler...done
Building dotty library...done
Building tests...done
Starting dotty REPL...
Welcome to Scala.next (pre-alpha, git-hash: 9195e91)  (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121).
Type in expressions to have them evaluated.
Type :help for more information.
scala>
```

**Comment by felixmulder** [comment]
Then perhaps it is fine since `repl` is only a task used locally in the Dotty project. All projects using the Dotty compiler and bridge will get a console task via sbt that should say the correct thing...But I guess you're the expert on that.

WDYT?

**Comment by dwijnand** [comment]
The need to run the REPL straight out of the dotty repo will certainly decrease after the initial official releases of Dotty. But for both now and later I think this feature would be convenient, mostly when sharing REPL snippets.
