### ISSUE TITLE
Cannot import project to Intellij IDEA after the backend integration as a submodule

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#2299]
This is probably related to IntelliJ as it re-appears every now and then in IDEA's [track](https://youtrack.jetbrains.com/issues?q=project:%20%7BIntelliJ%20IDEA%7D). Although I haven't found a solution (apart from `git reset --hard <previous commit>` and then git merging with dotty's master) I am putting it here as a reminder to update our _Building Dotty with Intellij IDEA_ doc (in case we don't find one).

![screen shot 2017-04-24 at 14 43 50](https://cloud.githubusercontent.com/assets/765983/25337567/ae1508ee-28fc-11e7-8fe8-508f0248c901.png)

**Comment by smarter** [comment]
Ping @jastice: There seems to be an issue with IntelliJ importing sbt projects which use `unmanagedSourceDirectories`, I've tried to minimize it before, but my minimized projects always succeed the import. Could you help us diagnose what's going on here?

**Comment by smarter** [comment]
To reproduce the issue:
1. git clone --recursive https://github.com/lampepfl/dotty.git
2. Try to import the project in IntelliJ
