### ISSUE TITLE
Tests: Have a way to "freeze" the code used when compiling the compiler

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2303]
Some of the tests compile (part of) the compiler's code. When debugging an issue this can be problematic because debugging might involving changing the compiler code, and thus affective the issue we're trying to fix. It would be nice if we could temporarily freeze the code used in the tests to avoid this. One way to do that would be to make a fresh git clone of dotty somewhere else and run the tests with some option like `--tests-src=../dotty-upstream`.

**Comment by SethTisue** [comment]
> Some of the tests compile (part of) the compiler's code

They do? What's an example? Not sure what this means.

**Comment by smarter** [comment]
Nowadays it looks like it's just https://github.com/lampepfl/dotty/blob/1292246c9646db12391cb7e42ce951722ac7fd03/compiler/test/dotty/tools/dotc/CompilationTests.scala#L233-L237

**Comment by dwijnand** [comment]
Ah.  That one looks more of a comprehensive integration test than asserting some specific behaviour.  What do you think if we move that to a new file?  Or maybe move it into FromTastyTests.

**Comment by smarter** [comment]
I'm happy if anyone looks into our test infrastructure at all no matter what they do 😄

**Comment by SethTisue** [comment]
lolcry
