### ISSUE TITLE
Dotty benchmarks

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#2307]
- [ ] Compilation speed
- [ ] Run speed
- [ ] Community build benchmarks
- [ ] Collection Strawman
- [ ] Graphs, numbers, website, such wow
- [ ] Get a stable environment, ask Fabien for a machine (where nothing's allowed to run on it concurrently)
- [x] scala/compiler-benchmark for comparison with Scala 2.x (https://github.com/scala/compiler-benchmark/pull/31)

**Comment by smarter** [comment]
See also https://github.com/scala/compiler-benchmark/ and the dotty port by @jvican : https://github.com/jvican/compiler-benchmark

**Comment by biboudis** [comment]
@jvican's port seems neat! 

I prefer JMH but I also agree with @DarkDimius points in favor of ScalaMeter which Dotty currently uses. A small [WIP](https://github.com/biboudis/dotty/commit/3d688bcf144b0b8a0c146a7cba2e4a999c7aba51) from me is to enable JMH on dotty. For Scala the results are browsable with graphana [here](https://scala-ci.typesafe.com/grafana/dashboard/db/scala-benchmark) which seems super nice.

So for the next steps I would propose:

1. to decide on the microbenchmarking tool that we will adopt (its going to stick with us for a long time hopefully)
1. set up a linux-based, commodity machine that we can set up clock frequency and all that
1. set up graphana-based reporting
1. decide the dependency scheme (git submodule, sonatype?)
1. decide the triggering strategy (e.g., in [compiler-benchq](https://github.com/scala/compiler-benchq) for scala)
1. pull in existing dotty benchmarks (@felixmulder already separated the benchmarks from tests #2220
1. pull in existing scalac benchmarks (@jvican)
1. pull in existing collection-strawman benchmarks (and all those we are going to develop according to #54)
1. clean up dotty/strawman of independent attempts and have a central point of reporting for our projects

**Comment by jvican** [comment]
> For Scala the results are browsable with graphana here which seems super nice.
  
You just blew up my mind, didn't know that. It's really great.
  
> I prefer JMH but I also agree with @DarkDimius points in favor of ScalaMeter which Dotty currently uses.
  
What are the arguments? I missed that discussion.

**Comment by biboudis** [comment]
>What are the arguments? I missed that discussion.

This discussion was comprehensive regarding this https://github.com/scala/collection-strawman/pull/19#discussion_r96680720

**Comment by biboudis** [comment]
A unified dotc/scalac suite is developed on olafurpg/compiler-benchmark#1

**Comment by felixmulder** [comment]
@biboudis - update on this? Do things then close plz.

**Comment by biboudis** [comment]
We are waiting scala/compiler-benchmark#31 to be merged.

**Comment by olafurpg** [comment]
What about https://github.com/liufengyun/bench @liufengyun?

**Comment by biboudis** [comment]
It is good to have both and testing scalac and dotc side by side, on the same stable infrastructure will increase the confidence on either of these! Consequently, it would be good!

**Comment by olafurpg** [comment]
https://github.com/scala/compiler-benchmark/pull/31 is now merged. The fancy website and wow numbers for open PRs seem to be solved by Fengyun's awesome bench project, I think this issue can be closed.
