### ISSUE TITLE
[REPL only] runtime error after failed type calculation

### ISSUE THREAD

**Issue by scalasolist** [lampepfl/dotty#2309]
#2300 displayed misbehaviour in type level calculation. If you skip checking types and invoke REPL, you could get runtime error.

    object hlists {
      sealed abstract class HList {
        type Merge[L <: HList] <: HList
    
        def merge[L <: HList](l: L): Merge[L]
      }
      final case class HCons[H, T <: HList](head : H, tail : T) extends HList {
        type Merge[L <: HList] = HCons[H, tail.Merge[L]]
    
        def merge[L <: HList](l: L): Merge[L] = HCons(head, tail.merge(l))
      }
      sealed trait HNil extends HList {
        type Merge[L <: HList] = L
    
        def merge[L <: HList](l: L): Merge[L] = l
      }
      final val HNil: HNil = { case object HNil extends HNil; HNil }
    }

    import hlists._

    val x = HCons(42, HNil) merge HCons("foo", HNil)
    val y = HCons(false, HNil) merge HCons(9.3, HNil)
    val z = x merge y

It would fail with following error:

    -- Error: <console> ------------------------------------------------------------
      |z
      |^
      |unsafe instantiation of type x.Merge[
      |  hlists.HCons[Boolean,
      |    hlists.HCons[Boolean, hlists.HNil] @UnsafeNonvariant#tail.Merge'[
      |      hlists.HCons[Double, hlists.HNil]
      |    ]
      |  ]
      |](z)where:    Merge  is a type in class HCons which is an alias of [L <: hlists.HList] => hlists.HCons[H, HCons.this.tail.Merge[L]]
      |          Merge' is a type in trait HNil which is an alias of [L <: hlists.HList] => L

I could not reproduce it in standalone application, only in REPL.

**Comment by smarter** [comment]
The code snippet in this issue now works both in and outside off the REPL.
