### ISSUE TITLE
Implicits defined with patdef don't need explicit type annotation

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#2315]
It's possible to get type-inferred implicit with the patdef syntax:

```scala
implicit val (a, b) = (1, "")
```

Should that be disallowed?

**Comment by odersky** [comment]
If it's a field definition (as opposed to a local one) it should be disallowed.

**Comment by OlivierBlanvillain** [comment]
dotty complains if it's a field so this is fine
