### ISSUE TITLE
Reassignment to var considered mistaken for reassignment to val

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#2345]
```scala
package dotty.tools.util

import scala.collection.mutable

class Whatever[A] extends mutable.Set[A] {
  private[this] var count = 0
  count = 0
}
```

Fails with:

```
-- Error: local/set.scala:7:8 --------------------------------------------------
7 |  count = 0
  |  ^^^^^^^^^
  |  reassignment to val
```

**Comment by DarkDimius** [comment]
My guess: 
- desugar has an ad-hoc optimization to not generate setter if field is private in class;
- something later in pipeline isn't aware of this optimization and gets screwed. 

If it is the case, I propose to remove this adhoc optimization.

**Comment by smarter** [comment]
Scala never generates setters for `private[this] var`, I think this is an important optimization that shouldn't be dropped.

**Comment by felixmulder** [comment]
```scala
def setterNeeded =
  (mods is Mutable) && ctx.owner.isClass //&& (!(mods is PrivateLocal) || (ctx.owner is Trait))
```
This change does indeed "solve" it.

**Comment by odersky** [comment]
The problem is in fact hat we have an overloaded occurrence of the private[this] val `count` and an inherited `count` method. The assignment logic was not prepared to handle this case. I am on it.
