### ISSUE TITLE
Should warn when ignoring command line flags.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2369]
Currently if we do `dotc -Xprint:foo -Xprint:bar -classpath pathA -classpath pathB A.scala` we ignore silently `-Xprint:foo` and `-classpath pathA`. This is true in general for all flags. We should warn or fail when we have one of these inputs.

**Comment by felixmulder** [comment]
Relevant file to look at is the parsing of arguments in [Settings.scala](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/config/Settings.scala).

All arguments are registered with a default value and then the state is evolved as each setting is registered from the parsing of the commandline input. One solution would be:

- to add a field to the `Setting` class that indicates if the state has changed
- in the [update](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/config/Settings.scala#L57) make sure that the state has not changed before setting the value
- `if (changed) fail(...) else <old logic>`
