### ISSUE TITLE
GADT & upper bounds

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#2381]
```scala
object GADTs {
  trait Foo[A, B]
  case class A() extends Foo[Int, Int]
  case class B[X]() extends Foo[X, X]
  case class C[X]() extends Foo[X => String, X]
  case class D[X <: Int]() extends Foo[X, X]
  case class E[X <: Int]() extends Foo[X, (X, X)]

  def test[X, Y](foo: Foo[X, Y]): Unit = foo match {
    case A() =>
      implicitly[X =:= Int]
      implicitly[Y =:= Int]
    case B() =>
      implicitly[X =:= Y]
    case C() =>
      implicitly[X =:= (Y => String)]
    // case D() =>
    //   implicitly[X =:= Y]
    //   implicitly[X <:< Int]
    //   implicitly[Y <:< Int]
    // case E() =>
    //   implicitly[Y =:= (X, X)]
    //   implicitly[X <:< Int]
    //   implicitly[Y <:< (Int, Int)]
    case _ => ()
  }
}
```

Commented out lines fail to compile with:
```
340 |    case D() =>
    |         ^
    |         Type argument Y does not conform to upper bound Int
```

Is it intentional? It seems like a useful feature, being able to infer type constraints from GADT match.

They do compile in Scala 2.12, but subsequent checks in `D`(and `B`) fail.

**Comment by smarter** [comment]
Thanks for the bug report, this indeed seems like something we could do better.

**Comment by odersky** [comment]
I think this is out of reach with the current GADT scheme. GADTness does not take bounds into account, and I believe both the spec and the implementation scheme would be significantly more complicated if they did.

**Comment by odersky** [comment]
I believe it could be an interesting project to pursue this if someone wants to put effort into it.
