### ISSUE TITLE
value euqueue is not a member of scala.collection.immutable.Queue[Int]

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#2385]
Copy from https://github.com/scala/bug/issues/10301

``` scala
import scala.collection.immutable.Queue
Queue.empty.enqueue(0).euqueue(1)
```

```
value `euqueue` is not a member of scala.collection.immutable.Queue[Int] - did you mean `scala.collection.immutable.Queue[Int].enqueue`?
```

https://scastie.scala-lang.org/Atry/02Z4TzflQ7qJqEGTEAdNXw

The error message is wrong.

I'm pretty sure `euqueue` is a member of `scala.collection.immutable.Queue[Int] `.

**Comment by felixmulder** [comment]
You mispelled the second "enqueue":

```scala
import scala.collection.immutable.Queue
Queue.empty.enqueue(0).enqueue(1)
```

compiles fine in dotty.

**Comment by Atry** [comment]
My fault

**Comment by felixmulder** [comment]
No worries (=
