### ISSUE TITLE
CI should cache submodules?

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2387]
The first thing the CI does on every build is `git submodule update --init`, this takes 23 seconds, most of that time is spent checking out `lampepfl/scala` twice (it's dumb that git doesn't realize it's doing the same thing twice here). It would be nice if we could cache this. It may also be worth merging `scala-backend` and `scala2-library` in a single submodule just to make it easier on everyone trying out dotty (on a bad connection a recursive clone might take a looong time).

**Comment by smarter** [comment]
@allanrenucci Do you think this is doable or should we close?

**Comment by allanrenucci** [comment]
I'll will experiment with this over the next week. I think there are simple optimisations I can try such as cloning the submodules in parallel.

Regarding caching, I don't see an easy solution

**Comment by allanrenucci** [comment]
Closing as I don't plan to implement caching for submodules since I minimised the time spent cloning submodules by doing it in parallel. (ref/ #3850)
