### ISSUE TITLE
Regression: Ambiguous reference error

### ISSUE THREAD

**Issue by olafurpg** [lampepfl/dotty#2403]
I am upgrading the community build to use the bootstrapped Dotty version and I'm hitting on an ambiguous reference error in the squants project, see https://travis-ci.org/dotty-staging/squants/builds/230324795#L561

```scala
-- [E048] Reference Error: /Users/ollie/dev/squants/shared/src/main/scala/squants/energy/Power.scala:29:24
29 |    with TimeDerivative[Energy]
   |                        ^^^^^^
   |                        reference to `Energy` is ambiguous
   |                        it is both imported by import squants._
   |                        and defined subsequently in module class energ
```

I had similar errors when upgrading scalatest to use the bootstrapped dotty version. Changing `import squants._` to `import squants.{Energy => _, _}` does fix the error. However, `squants.Energy` is a type alias to `squants.energy.Energy` so I think the ambiguous reference error should not be reported. The original code compiles with dotty 20170412 as well as scalac 2.x. 

I tried to find a minimal repro in https://github.com/dotty-staging/squants/pull/4/commits/d459a3b8842cdff844ff3a5ed63af45ce2c29592 but with no luck. There must be something I'm missing, help would be very much appreciated. To reproduce 

```
git clone https://github.com/olafurpg/squants.git
cd squants
git checkout d459a3b8842cdff844ff3a5ed63af45ce2c29592
sbt squantsJVM/compile
```

My efforts to minimize the example are in the `shared/src/main/scala/foo/` directory.

**Comment by felixmulder** [comment]
Tried to minimize this as well, but ended up crashing the compiler:

```scala
// pack.scala
package foo

package object bar {
  type Foo = foo.bar.Foo
}
```
```scala
// Foo.scala
package foo.bar

class Foo
```
```scala
// usage.scala
package boobar

import foo.bar._

object Test {
  val x: Foo = ???
}
```

**Comment by odersky** [comment]
@olafurpg I am trying to find my way here. I did not find module class "energ". Did you mean package "energy" maybe?

**Comment by smarter** [comment]
Yes, it's energy.

**Comment by olafurpg** [comment]
@odersky Yes, I accidentally cut out the last `rgy` part.

Note. The dotty_0.1 branch has been updated to unimport the ambiguous references, the commit hash to reproduce is   https://github.com/dotty-staging/squants/commit/d459a3b8842cdff844ff3a5ed63af45ce2c29592

**Comment by olafurpg** [comment]
The main branch `dotty` compiles OK, I added a new commit to reproduce the error here https://github.com/olafurpg/squants/commit/e2340f2af8b4dce06a98e32f2166e807c254e125

```diff
--- a/shared/src/main/scala/squants/energy/Power.scala
+++ b/shared/src/main/scala/squants/energy/Power.scala
@@ -8,7 +8,7 @@

 package squants.energy

-import squants.{Energy =>_, _}
+import squants._
```

That produces the error

```scala
[error] -- [E048] Reference Error: /Users/ollie/dev/squants/shared/src/main/scala/squants/energy/Power.scala:29:24
[error] 29 |    with TimeDerivative[Energy]
[error]    |                        ^^^^^^
[error]    |                        reference to `Energy` is ambiguous
[error]    |                        it is both imported by import squants._
[error]    |                        and defined subsequently in module class energy
[error] one error found
[error] (squantsJVM/compile:compileIncremental) Compilation failed
```

**Comment by olafurpg** [comment]
PS. The sbt-dotty integration is not necessary to compile squants. I sometimes compile the project with the `dotc` command line tool directly

```
dotc -d /tmp/foo $(find shared/src/main/scala -name "*.scala" | paste -sd " " -)
```

**Comment by odersky** [comment]
Should be fixed by now. Please re-open if this is not the case.
