### ISSUE TITLE
sbt-dotty: dependsOn & withDottyCompat

### ISSUE THREAD

**Issue by MasseGuillaume** [lampepfl/dotty#2409]
it would be great to be able to write:

```scala
lazy val runtimeDotty = project.in(file("runtime-dotty")).dependsOn(api211JVM.withDottyCompat())
```

this way I can depend on api211JVM a Scala 2.11.11 project.

**Comment by smarter** [comment]
As far as I can tell, using `dependsOn` will set `projectDependencies`, so you should be able to do:
```scala
  projectDependencies ~= (_.map(_.withDottyCompat())
```

**Comment by MasseGuillaume** [comment]
@smarter 

correct! Maybe you can include this in the sbt plugin by default?

**Comment by smarter** [comment]
It shouldn't be by default because you might want to depend on a dotty project and not a Scala 2 project, but the doc could be improved.
