### ISSUE TITLE
Missing errors for `inline var`, `inline object`, `inline class` and `inline type`.

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2421]
* [x] `inline var foo`: Should not be allowed, it will break after the first assignment. Possibly for `lazy val` too.
* [x] `inline class Foo`: Should not be allowed.
* [x] `inline object Foo`: Should have a better error message. Currently _right-hand side of inline object Foo must be a constant expression or a function_.
* [x] `inline type Foo`: Should not be allowed, it makes not sense.

**Comment by DarkDimius** [comment]
For the record: We discussed an idea that inline class may be a new syntax 
for value class.
