### ISSUE TITLE
Impossible to annotate public primary constructor and keep Scala 2 compatibility

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2426]
This doesn't compile with dotty:
```scala
class Foo @deprecated("foo", "2.11.0") (x: Int)
```
```scala
1 |class Foo @deprecated("foo", "2.11.0") (x: Int)
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |    private, protected, or this expected for annotated primary constructor
```

Adding `this` does indeed fix it, but doesn't compile with Scala 2:
```scala
class Foo @deprecated("foo", "2.11.0") this(x: Int)
```

- Is this an intentional difference?
- If yes, we should at least support the old syntax under `-language:Scala2`

**Comment by smarter** [comment]
If the `this` syntax is intended, then I suggest we also allow it when no annotation is present for consistency, currently this does not compile with dotty:
```scala
class Foo this("foo", "2.11.0") (x: Int)
```

**Comment by odersky** [comment]
The tricky bit for the parser is that the syntax without `this` is ambiguous. Consider:

    class Foo @annot(x: Int)() { ... }|

Is this a class `Foo()` with annotation `@annot(x: Int)` or a class with parameters `(x: Int)()` and annotation `annot`? Even worse is this:

    class Foo @annot()()() { ... }

What is a parameter for `annot` and what is a parameter for `Foo`? We'd need a disambiguation rule for this. Not sure what `scalac` does?

**Comment by smarter** [comment]
Based on experimentation, it seems that scalac only allows one parameter list in primary constructor annotations. And while annotations with multiple parameter lists typecheck in other situations, you get an ominous warning:
```scala
scala> class Foo(x: Int)(y: String)
defined class Foo

scala> @Foo(1)("foo") class Bar(x: Int)
<console>:12: warning: Implementation limitation: multiple argument lists on annotations are
currently not supported; ignoring arguments List("foo")
       @Foo(1)("foo") class Bar(x: Int)
        ^
defined class Bar
```

**Comment by smarter** [comment]
I suggest formally specifying that annotations constructors can only have one parameter list. That seems to be the status quo in Scala 2 and no one complains about it, and it removes the ambiguity without introducing new syntax.
