### ISSUE TITLE
Methods with pattern-matching and dependent types

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#2496]
Given:
```scala
  sealed trait F { type A }
  case object FI extends F { type A = Int }
  case object FS extends F { type A = String }
```

This snippet:
```scala
  def test1a(f: F): f.A =
    f match {
      case FI => 1
      case _: FS.type => ""
    }
```
fails with:
```
-- [E007] Type Mismatch Error: <console>:9:19 ----------------------------------
9 |        case FI => 1
  |                   ^
  |                   found:    Int(1)
  |                   required: f.A
-- [E007] Type Mismatch Error: <console>:10:27 ---------------------------------
10 |        case _: FS.type => ""
   |                           ^^
   |                           found:    String("")
   |                           required: f.A
```

But I can prove it works with a little hacky workaround:
```scala
  def test1b(f: F): f.A = {
    def dirtyHack[B](f: F { type A = B }): B =
      f match {
        case FI => 1
        case _: FS.type => ""
      }
    dirtyHack[f.A](f)
  }
```

Notice that the `f match { ... }` is the original implementation verbatim.
It would be great if the first snippet worked.

**Comment by odersky** [comment]
The workaround uses GADT matching but the original does not. It is currently not clear what the rules for such extended GADT matching should be. This would be a worthwhile research problem for somebody to take on. But I don't see an immediate fix.

**Comment by julienrf** [comment]
I think we should re-open this issue, especially because the “little hacky workaround” doesn’t work anymore: https://scastie.scala-lang.org/l21lZJfsThiUMJlBeSuSsg

**Comment by julienrf** [comment]
Would the problem be fixed by changing the typing rules of the typed patterns like the following?

~~~
e match {
  case t: T => summon[t.type <:< (T & e.type)]
}
~~~

~~~ diff
  A typed pattern `x: T` consists of a pattern variable `x` and a type pattern `T`.
- The type of `x` is the type pattern `T`
+ The type of `x` is `T & e.type` (where `e` is the scrutinee expression)
~~~

Of course, this formulation works only for “outer” patterns, but not in the following case:

~~~ scala
e match {
  case Some(t: T) => ...
  case None => ...
~~~

**Comment by Blaisorblade** [comment]
I think that's what @AleksanderBG plans, but this is not enough here.

- It’s important that the type of `e` is not implicitly widened; the translation might need to use SkolemType internally — that is, `z.type` where `z` is a fresh variable containing the result of `e` (assume that `e match ...` is rewritten to `val z = e; z match ...`), and where `z.type` is an actual singleton type.
- BTW, if you want to propose this for the spec, please keep `.type` as syntax for actual singleton types.
- In this case, I’m not sure that spec is enough. No variables are actually bound by the original program — maybe we should apply this spec also to dummy variables introduced implicitly; so `case FI => ` becomes `case x @ FI => `.
- And even if you have a variable `x : FI.type & f.type` in scope, does that affect whether `Int <: f.type`? That might need additional effort.

**Comment by Blaisorblade** [comment]
@AleksanderBG can you reopen this, if you find it interesting/appropriate?

**Comment by AleksanderBG** [comment]
I looked into making this work a few months ago, but the combination of self-recursive types + type members with only upper/lower bound proved very non-trivial to handle correctly, so I abandoned the effort. @japgolly if you were to provide some good motivating example of code that needs to infer GADT constraints based on types like this, I'd look into making them work.

**Comment by AleksanderBG** [comment]
I'll be looking into extending GADT constraints to also work on singleton types. I'll keep this issue on my radar.
