### ISSUE TITLE
incorrect exhaustiveness warning in dotty build

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2502]
Running `sbt dotty-compiler-bootstrapped/compile` we get:
```scala
[warn] -- [E028] Pattern Match Exhaustivity Warning: compiler/../out/bootstrap/dotty-compiler-bootstrapped/scala-0.1/src_managed/main/scala/tools/nsc/backend/jvm/BTypes.scala:337:35 
[warn] 337 |    def classOrArrayType: String = this match {
[warn]     |                                   ^^^^
[warn]     |                                   match may not be exhaustive.
[warn]     |                                   
[warn]     |                                   It would fail on: ClassBType(_)
```

But the match will not fail on `ClassBType(_)`, the first case takes care of it:
```scala
    def classOrArrayType: String = this match {
      case ClassBType(internalName) => internalName
      case a: ArrayBType            => a.descriptor
    }
```

/cc @liufengyun

**Comment by liufengyun** [comment]
@smarter This is a problem in the backend, I already made a PR, could you review it?

https://github.com/lampepfl/scala/pull/19

**Comment by liufengyun** [comment]
The problem is that it defines an extractor `ClassBType` which returns `Option[String]`, thus it's taken as inexhaustive.

**Comment by smarter** [comment]
I see, but in this case the warning is incorrect, no? The misssing case is `_: ClassBType`, not `ClassBType(_)`. It would also be good if the message contained a hint that you can make the unapply method irrefutable by return `Some[X]` instead of `Option[X]`

**Comment by liufengyun** [comment]
@smarter Yes, you are right, I'll update the warning message for extractors.

The suggestion is very good. We can add an explanation message: tell the programmers to either to have a wildcard or make the extractor irrefutable by returning `Some[T]`.
