### ISSUE TITLE
Check all usages of lazy val in fields in the codebase

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2507]
https://github.com/lampepfl/dotty/pull/2506 fixes race conditions in dotty recently introduced when we copied files from scala-reflect, but it does not attempt to look at all usages of lazy val in these files or other files imported before that. We should do a review of all our lazy val fields and decide for each one of them:
- Keep them as-is, but clearly mark the class as not thread-safe
- Make the class thread-safe by adding `@volatile`
- Use a val or a def instead.

**Comment by odersky** [comment]
lazy vals are now thread-safe, so this is no longer an issue.
