### ISSUE TITLE
dottydoc: Support two space indent for code blocks, or fix all the existing code blocks

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2544]
See http://dotty.epfl.ch/api/dotty/tools/dotc/transform/ExtensionMethods.html for example, the code blocks are not rendered because they're indented two spaces. This is quite common in our documentation.

**Comment by felixmulder** [comment]
Does it work with four? Anyway - I'm all for rewriting to ` ``` `, but maybe that's just me.

**Comment by smarter** [comment]
Yes, it works with four spaces. I'm very much against rewriting with ```` ``` ````, it makes the doc a lot less clean in the source code. I'm fine with rewriting using four spaces if we can't support two spaces for some reason.

**Comment by felixmulder** [comment]
But it also allows you to specify the language :bulb:

Four spaces is the markdown standard AFAICT - where are you are getting two from?

**Comment by smarter** [comment]
My personal preferences :). If the default language is scala, then it should be good enough 99% of the time.

**Comment by smarter** [comment]
Let's use four spaces everywhere.
