### ISSUE TITLE
Docs code snippets for compiler internal representation

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2548]
We currently use the same scala code snippets in the documentation when writing valid scala code and writing compiler internal representation of the code. The latter one should be formatted in such a way that users will not try to use it in the source code.

**Comment by nicolasstucki** [comment]
@felixmulder do you have some suggestion for this?

**Comment by felixmulder** [comment]
Yes, don't do this.

**Comment by Varunram** [comment]
@nicolasstucki @felixmulder May I know the scale of difficulty for this issue? If its novice, I could work on it. Thanks!

**Comment by felixmulder** [comment]
This is just a decision on the Dotty team level TBH. We need to say how we should indicate that something is compiler trees and not Scala code. I'd spend your energy on cooler issues :)
