### ISSUE TITLE
PrivateToStatic does not pass Ycheck on dotc

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#255]
It assumes that by rewriting calls Apply(Select(qual,name), args) and This nodes it has fixed the references to lifted defs. 
That is not true as Apply(Ident, args) as well as plain Ident's that can also refer to lifted methods.

**Comment by nicolasstucki** [comment]
@DarkDimius can we close this one? `PrivateToStatic` was removed a while ago.

**Comment by Blaisorblade** [comment]
Bankrupting this based on @nicolasstucki comment.
