### ISSUE TITLE
Spurious cyclic reference error with package objects and separate compilation

### ISSUE THREAD

**Issue by xeno-by** [lampepfl/dotty#2551]
```scala
// Library.scala
package scala {
  package meta {
    package config {
      case class Version()

      trait Aliases {
        type Version = scala.meta.config.Version
        val Version = scala.meta.config.Version
      }
    }
  }

  package object meta extends scala.meta.config.Aliases
}
```

```scala
// Test.scala
import scala.meta._

object Test {
  val v = Version()
}
```

```
17:46 ~/Projects/dotty/sandbox $ ../bin/dotc Library.scala
17:46 ~/Projects/dotty/sandbox $ ../bin/dotc Test.scala
exception caught when loading class Aliases: dotty.tools.dotc.core.Types$CyclicReference: cyclic reference involving class Aliases
-- [E044] Syntax Error: Test.scala:4:10 ----------------------------------------
4 |  val v = Version()
  |          ^^^^^^^
  |          recursive value v needs type

longer explanation available when compiling with `-explain`

one error found
```

Notes:
  * When Library.scala is compiled with scalac, we get the same error (so it's not a ScalaSignature vs TASTY problem). upd: I was wrong - when Library.scala is compiled with scalac, compilation succeeds.
  * When both Library.scala and Test.scala are compiled with scalac, compilation succeeds.
  * When there's just one file that merges these two files together, compilation succeeds.

**Comment by xeno-by** [comment]
This prevents scalameta from crosscompiling to Dotty, so I'd appreciate if someone could take a look at this issue. I can do that myself, but probably only after ScalaDays Copenhagen.

**Comment by liufengyun** [comment]
If the library is compiled with `scalac`, everything works fine to me:
```
scalac examples/library.scala
dotc examples/test.scala
```

It is only a problem if both are compiled with `dotc`. I guess you only need to compile `test.scala` with `dotc`, thus avoid the problem.

**Comment by xeno-by** [comment]
@liufengyun Thank you for double-checking. Indeed, I was incorrect (that was called by a mixup in my `scalac` and `dotc` scripts). If Library.scala is compiled by `scalac`, Test.scala can then be correctly compiled by `dotc`.

This means that only Scalameta itself can't be crosscompiled by Dotty (well, it can, but it will be unusable). Scalameta metaprograms can and indeed are successfully crosscompiled.

**Comment by liufengyun** [comment]
@xeno-by If you are doing a fork of Dotty, you can try the solution in #2555 .

**Comment by xeno-by** [comment]
@liufengyun Thanks a lot! I'll keep this in mind.
