### ISSUE TITLE
Regression in #2465: blog pages get wrong date

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#2560]
With the merge of timestamps, this broke something in the file parsing logic (haven't looked too close at it). But the result is:

<img width="744" alt="screen shot 2017-05-29 at 11 21 41" src="https://cloud.githubusercontent.com/assets/1530049/26544158/049be97e-4461-11e7-9a4d-13b5f43e387b.png">

All files now get the generated page's timestamp instead of the filename's.

cc: @Varunram

**Comment by Varunram** [comment]
Oh no! I'll have a look at it. Sorry for the late response!

**Comment by nicolasstucki** [comment]
Hint: the only thing that is missing is the date in the layout section of the .md files in `docs/blog/_posts/`.

Example:
```
---
layout: blog-page
....
date: 2016-02-03
---
```

**Comment by Varunram** [comment]
@nicolasstucki Thanks a ton! Patch incoming!

**Comment by felixmulder** [comment]
Also note that the blog posts have a specific name to resolve dates, this
is Jekyll's model

**Comment by Varunram** [comment]
Okay, I just got time to revisit this in detail. I couldn't quite get you when you said "Also note that the blog posts have a specific name to resolve dates, this is Jekyll's model". As in, should I look into the parsing in `Site.scala`?

**Comment by felixmulder** [comment]
Yes, that sounds reasonable - should be somewhere in that general area :+1:

**Comment by Varunram** [comment]
@felixmulder Done! Turned out to be a simple hack in the end :) Should've spotted it earlier. Sorry

**Comment by smarter** [comment]
Looks like this got fixed, but I don't know when: http://dotty.epfl.ch/blog/index.html
