### ISSUE TITLE
Dotty infers inexpressible type

### ISSUE THREAD

**Issue by Jasper-M** [lampepfl/dotty#2612]
Given:
```
trait Bippy 
trait Boppy extends Bippy
trait Foo[B <: Bippy, C] 
def bar[B <: Bippy, C](u1: Foo[_ <: B, C]): Foo[B, C] = ??? 
def foo: Foo[_ <: Boppy, _] = null
```
Evaluating the following in the REPL yields a method with an inferred type that cannot be expressed in user code.
```
scala> def baz = bar(foo) 
def baz: Foo[Boppy, foo.C]
```

`foo` is not a stable value.
```
scala> def baz: Foo[Boppy, foo.C] = ??? 
-- Error: <console>:8:20 -------------------------------------------------------
8 |def baz: Foo[Boppy, foo.C] = ???
  |                    ^^^
  |                    => Foo[_ <: Boppy, _](foo) is not stable
```

If I make `foo` a `val`, `baz` gets the same type but it is still not expressible.
```
scala> def baz: Foo[Boppy, foo.C] = ??? 
-- Error: <console>:8:24 -------------------------------------------------------
8 |def baz: Foo[Boppy, foo.C] = ???
  |                    ^^^^^
  |type C in class Foo cannot be accessed as a member of Foo[_ <: Boppy, _](foo) from module class $iw$.
```

I don't know if this is caused by the REPL itself, because I don't know of another way in which a mere mortal can currently inspect an inferred type in Dotty.

**Comment by smarter** [comment]
>  I don't know of another way in which a mere mortal can currently inspect an inferred type in Dotty

Try compiling with `-Xprint:frontend`.

**Comment by Jasper-M** [comment]
FWIW it's not only in the REPL.

**Comment by odersky** [comment]
We now get:

    def baz: Test.Foo[Test.Boppy, Test.Foo[_ <: Test.Boppy, _]#C] = 
      Test.bar[Test.Boppy, Test.Foo[_ <: Test.Boppy, _]#C](Test.foo)

This is still not expressible however. If we try to use that type explicitly, we get:

    9 |  def baz2: Test.Foo[Test.Boppy, Test.Foo[_ <: Test.Boppy, _]#C] = baz
      |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      |type C cannot be accessed as a member of Test.Foo[_ <: Test.Boppy, _] from object Test.

The error message makes sense, since `C` is a type parameter, not a member. But we need to 
be able to refer to such types anyway. I don't see there's anything we could do that would not invalidate a lot of programs.

So the summary is: Yes there are inferred types that cannot be expressed in source.

**Comment by smarter** [comment]
Couldn't the type be widened away by an approximatingtypemap?

**Comment by Jasper-M** [comment]
If referring to such types is important, perhaps it should be possible to also express them in source?

**Comment by Atry** [comment]
Why not simply disable stability check for a prefix?
