### ISSUE TITLE
ValueOf typeclass to inhabit singleton types

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#2616]
Currently there is no way to obtain the runtime value corresponding to a singleton type. [SIP-23 - Literal-based singleton types](http://docs.scala-lang.org/sips/pending/42.type.html) mentions a `ValueOf` (or `SingleInhabitant`) type class that is currently missing from Dotty.

For reference, a `ValueOf` type class was implemented in Typelevel Scala in this commit:
https://github.com/typelevel/scala/commit/d777d40bbacec01f2f94531cd2db933f8c8cd4c9

**Comment by OlivierBlanvillain** [comment]
It should probably be implemented as [another fallback case](https://github.com/lampepfl/dotty/blob/be6ae0e95af357205c91b1b5d63b2cd9d82e7f46/compiler/src/dotty/tools/dotc/typer/Implicits.scala#L664-L666) in implicit search. @Glavo I think it could be a good first issue if you want to give it a shot!

**Comment by smarter** [comment]
I have an implementation, but I haven't made a pr for it yet

**Comment by milessabin** [comment]
I'll pick this up if nobody else wants it.

**Comment by milessabin** [comment]
PR here: https://github.com/lampepfl/dotty/pull/5647.

**Comment by Swoorup** [comment]
Shouldn't this also work for Tuple Singletons?

```scala
scala> valueOf[("orders", "trades")];;
1 |valueOf[("orders", "trades")];;
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |cannot reduce summonFrom with
  | patterns :  case ev @ _:ValueOf[(("orders" : String), ("trades" : String))]
  | This location contains code that was inlined from Predef.scala:25
```

**Comment by bishabosha** [comment]
@Swoorup A proposal could be made to expand the types that `ValueOf` can be synthesised for. For now, you can make a similar abstraction that works for tuples also:
```scala
final class ReflectType[T](val asValue: T) extends AnyVal {
  type Refl = T
  def refl: Refl = asValue
}

def reflectType[T](using refl: ReflectType[T]): refl.Refl = refl.refl

// forces bounds to be fixed in pattern match
final abstract class TypeBox[T]()

transparent inline given genReflectType[T]: ReflectType[T] = inline compiletime.erasedValue[TypeBox[T]] match {
  case _: TypeBox[t *: ts]    => ReflectType(compiletime.constValueTuple[t *: ts])
  case _: TypeBox[EmptyTuple] => ReflectType(EmptyTuple)
  case _: TypeBox[T]          => ReflectType(valueOf[T])
}
```
