### ISSUE TITLE
Publish Nightlies to Bintray

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#2621]
Or other host, it looks confusing if nightlies with newer versions than RC/stable are available on maven.

**Comment by DarkDimius** [comment]
I think it's perfectly fine if there are SNAPSHOT or NIGTHLY builds that are newer.
Publishing some stuff to bintray and some stuff to maven will only create more confusion.

**Comment by smarter** [comment]
Nightlies are published to maven and everyone is happy :).
