### ISSUE TITLE
update brew release

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2623]
It's not updated

**Comment by liufengyun** [comment]
@DarkDimius I just check, @felixmulder hasn't done a release yet, I think he'll do it together with the release notes.

https://github.com/lampepfl/dotty/releases

**Comment by DarkDimius** [comment]
The jar is up on maven: http://repo1.maven.org/maven2/ch/epfl/lamp/dotty_0.1/0.1.2-RC1/
what's missing?

**Comment by liufengyun** [comment]
@DarkDimius The release of `zip` and `tar.gz` that package the scripts and jars is not done -- not uploaded to Github.

**Comment by DarkDimius** [comment]
@liufengyun, what commands should I run to generate those?

**Comment by liufengyun** [comment]
I'll sync with @felixmulder to see if that's intentional for waiting some other stuff.

**Comment by DarkDimius** [comment]
Got an ACK from @felixmulder, doing release.

**Comment by liufengyun** [comment]
This is done now. `brew install lampepfl/brew/dotty` will install the `0.1.2-RC1` release.
