### ISSUE TITLE
update scastie to 0.1.2-RC1

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2624]
Hi @MasseGuillaume,

the release is on maven now

would you kindly update scastie to use it?

**Comment by MasseGuillaume** [comment]
doing it now, thanks for reminding!

**Comment by smarter** [comment]
@MasseGuillaume I think it would be really nice if the Scastie interface let you choose the Dotty version: either "0.1.2-RC1" or "Latest nightly build"

**Comment by DarkDimius** [comment]
@MasseGuillaume Thanks!
