### ISSUE TITLE
brew ignores RC1 in the name

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2625]
It doesn't want to upgrade to new RC1. It seems it has its own understanding of version ordering

**Comment by liufengyun** [comment]
As long as the package name is `dotty-0.1.2-RC1.zip` or `dotty-0.1.2-RC1.tar.gz`, everything works fine.

If install from local `tar.gz` or `zip`, the version will be ignored -- I guess that's intentional by Brew to alert developers that's already installed.

**Comment by DarkDimius** [comment]
Reproduced with github release togather

**Comment by liufengyun** [comment]
Let me update the formula first: https://github.com/lampepfl/homebrew-brew/pull/3 .

On my local everything works just fine.

**Comment by liufengyun** [comment]
OK, just figured out. @DarkDimius is using Homebrew 0.9, while the latest is 1.2. It only happens to old versions of brew.

For new comers, this is not a problem at all.

**Comment by DarkDimius** [comment]
@liufengyun, thanks for figuring it out!
