### ISSUE TITLE
Cyclic references in 0.1.2-RC1 lib dependencies

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2626]
When fetching the dependencies for `0.1.2-RC1` sbt warns about a cyclic dependency between `scala-library` and `dotty-library`
```scala
[info] Resolving ch.epfl.lamp#dotty-library_0.1;0.1.2-RC1 ...
[warn] circular dependency found: ch.epfl.lamp#scala-library;0.1.2-RC1->ch.epfl.lamp#dotty-library_0.1;0.1.2-RC1->...
[warn] circular dependency found: ch.epfl.lamp#dotty-library_0.1;0.1.2-RC1->ch.epfl.lamp#scala-library;0.1.2-RC1->...
```

Is this just an artifact of our packaging? Or do they really depend on each other?

cc @smarter

**Comment by smarter** [comment]
It has to do with the weird rewriting of dependencies that sbt does. It doesn't break anything so I don't consider it a big. In the future we can fix this by merging scala-library and dotty-library in a single package that is called scala-library

**Comment by nicolasstucki** [comment]
This is not really an issue. The only effect is to print a warning when resolving the dependencies.
