### ISSUE TITLE
Clarrify what "is Trait" and what isClass 

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#263]
I guess we need to either rename those methods or give them a reasonable doc.

`Symbol.isClass` actually checks if Symbol is ClassSymbol, eg he returns `true` for traits, which is misleading.

`sym is Trait` is also true for abstract classes. Which makes it even more misleading.

**Comment by smarter** [comment]
I don't think we're going to change terminology at this point, the current one seems to have worked well so far :).
