### ISSUE TITLE
Assert in Run.scala is inefficient

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2636]
Run.scala contains:
```scala
assert(comp.phases.last.last.id <= Periods.MaxPossiblePhaseId)
```

But `phases` is a def in `Compiler` that will allocate every phase. This is pretty wasteful since we then throw away the result. We could probably move this assert inside the definition of `phases`, or at the point where we actually use `phases`.

**Comment by abeln** [comment]
In https://github.com/lampepfl/dotty/pull/2640#discussion_r119485182, Dmitry said this assert isn't on a hot path, so is it worth moving it?

**Comment by smarter** [comment]
Yes I think so. I've seen a concrete example of people storing information in a phase and trying to retrieve it later, except the phase was overwritten by this assert, which was pretty difficult to figure out.

**Comment by smarter** [comment]
Also, it's untrue that new runs are rarely created in the IDE: everytime you press a keystroke a new run will be created.

**Comment by DarkDimius** [comment]
FTR: making phases a def was done intentionally, so that every run has new phases and phases don't have to carefully manage state between runs.
