### ISSUE TITLE
Language Server: Odd word wrapping on hover

### ISSUE THREAD

**Issue by ShaneDelmore** [lampepfl/dotty#2665]
In the error generated by 1 / "foo" the word types is split on two lines.

![screenshot](https://s3.amazonaws.com/uploads.hipchat.com/74723/531326/35THk0l5DLWQ7iX/upload.png)

**Comment by smarter** [comment]
Thanks for the report! This appears to be a known issue in vscode: https://github.com/Microsoft/vscode/issues/22239, the proposed fix is to change the interface for reporting diagnostic to take markdown-formatted messages. Until this is implemented in vscode and in the Language Server Protocol, there's nothing we can do on our side, so closing this here.
