### ISSUE TITLE
Super-call in intersection type not type safe

### ISSUE THREAD

**Issue by freddie-freeloader** [lampepfl/dotty#2677]
Consider:
```scala
> trait A { def x = "foo" }
> trait B { def x = 42 }
> val AB = new A with B { override def x = super.x }
> AB.x
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
```

I would expect the overriding method to be rejected, since it has type `String` and it is expected to be `Int & String`.

**Comment by amanjpro** [comment]
I will be working on this

**Comment by smarter** [comment]
@amanjpro there is already a fix at: https://github.com/lampepfl/dotty/pull/2768

**Comment by amanjpro** [comment]
Ah, thanks for informing me.
