### ISSUE TITLE
non-private method referring to private type is overeager

### ISSUE THREAD

**Issue by rkuhn** [lampepfl/dotty#2678]
~~~
[error] non-private method doCollected refers to private trait Collected
[error]  in its type signature [org$scalatest$Matchers$doCollected$$T]
[error]   (collected: Matchers.this.Collected, xs: scala.collection.GenTraversable[T], 
[error]     original
[error]   : Any, prettifier: org.scalactic.Prettifier, pos: 
[error]     org.scalactic.source.Position
[error]   )(fun: T => org.scalatest.Assertion)org.scalatest.Assertion
[error] one error found
~~~

Looking at [the Scalatest source](https://github.com/scalatest/scalatest/blob/3.0.1/scalatest/src/main/scala/org/scalatest/Matchers.scala#L3066), doCollected is `private[scalatest]`, which means that compiling my own project against this code should not result in an error—I can see why it should be an error when building scalatest itself, though.

**Comment by odersky** [comment]
Qualified private simply does not figure in privacy testing. So I am not sure we can do something here.

**Comment by smarter** [comment]
When unpickling from Scala 2, we could simply silence errors from checkNoPrivateLeaks by default.

**Comment by kelebra** [comment]
This issue looks like a show-stopper for using scalatest with dotty. Reproduces for both scalatest `3.0.5` and `3.2.0-SNAP10` and latest dotty on tiny project.

**Comment by odersky** [comment]
OK, let's not check

**Comment by smarter** [comment]
Should be fixed by https://github.com/lampepfl/dotty/pull/4133, let us know if you find more problems using scalatest with dotty.

**Comment by rkuhn** [comment]
Thanks!
