### ISSUE TITLE
Backend generates useless companion class for inner objects

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2680]
The following code:
```scala
object Outer {
  object Inner
}
```
generates the following files with scalac:
```scala
Outer.class  Outer$.class  Outer$Inner$.class
```
and the following files with Dotty:
```scala
Outer.class  Outer.hasTasty  Outer$.class  Outer$Inner.class  Outer$Inner$.class
```
The `Outer.hasTasty` is expected but the `Outer$Inner.class` isn't, it doesn't seem to contain much:
```java
% cfr 'Outer$Inner.class'
/*
 * Decompiled with CFR 0_120.
 */
public final class Outer$Inner {
}
```
Could we avoid generating these companions? On case-insenstive filesystems they can be harmful: https://github.com/lampepfl/dotty/issues/2673#issuecomment-306032190

**Comment by DarkDimius** [comment]
The class contains TASTY, that's why it's created.

**Comment by DarkDimius** [comment]
And that's what your "Outer.hasTasty" indicates ;-)

**Comment by DarkDimius** [comment]
Ahh, you mean inner class. Yep, actual issue

**Comment by smarter** [comment]
No, it doesn't ?  Outer.class has a tasty, but not Outer$Inner.class, we only emit tasty for top-level classes.

**Comment by smarter** [comment]
Yes :)

**Comment by smarter** [comment]
>  DarkDimius added exp:novice and removed exp:expert labels 9 minutes ago

I think for something to be novice-level it needs to be obvious how to fix, or you need to give some instructions on how someone could fix it ;).

**Comment by abeln** [comment]
I'd be happy to take a look at this if given some pointers.

**Comment by DarkDimius** [comment]
@abeln, backend has a single entry-point to decide where to output files: method `getFileForClassfile`. I'd intercept this method in debugger and see when is it called for the generated class and why.

**Comment by smarter** [comment]
Also we have some docs on the backend you might find helpful: http://dotty.epfl.ch/docs/contributing/backend.html and http://dotty.epfl.ch/docs/internals/backend.html
