### ISSUE TITLE
Move `Eq` instances into scala.Eq companion object?

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#2698]
Discussion after https://www.reddit.com/r/programming/comments/6elim6/announcing_dotty_012rc1_a_major_step_towards/ points out that the extra implicit instances of `Eq` infect the global namespace and that's undesirable — those instances are currently available for autocompletion when typing `e`.

Could one move them to `Eq`'s companion object?

That might require using a different object as default instance, and maybe patching compiler special cases—such changes are included in the scope of this issue.

**Comment by odersky** [comment]
I think we could well move them to the companion object. Who wants to try that? Happy to review a PR.

**Comment by Blaisorblade** [comment]
To be sure: I can't volunteer to send PRs till I graduate.

**Comment by Blaisorblade** [comment]
Downside of moving the instances: they can't be disabled. `eqAny` was moved to `Predef` exactly so that it could be disabled, so it seems it should stay there (not sure about the name though, but I won't bikeshed over that).

https://github.com/lampepfl/dotty/issues/1247
