### ISSUE TITLE
Eq should extend AnyVal until Phantom types (now Erased terms) are ready

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#2717]
That way, at least you can't pass `null` as an instance. The suggestion is not mine, it comes from https://www.reddit.com/r/programming/comments/6elim6/announcing_dotty_012rc1_a_major_step_towards/dimg0nz/.

```scala
import dotty.DottyPredef.{eqAny => _, _}
class Foo
object Main {
  def bar[T](value: T)(implicit teq: Eq[T,T]) = value == value
  def main(args: Array[String]): Unit = bar(new Foo)(null) //<--
}
```

@nicolasstucki , can `Eq` be made a phantom type, now or later? I'm asking this at the design level for now.

**Comment by nicolasstucki** [comment]
@Blaisorblade it should be possible. https://github.com/lampepfl/dotty/blob/master/tests/pos/phantom-Eq.scala

**Comment by nicolasstucki** [comment]
We could think of making them phantom as soon as all phantom optimizations are in (currently in PRs).

**Comment by Blaisorblade** [comment]
Cool 👍 

I wonder if `==` could also take `Eq` then, but Martin pointed out that calls to `==` are emitted by the pattern matcher, which comes after typing and apparently can't do implicit search. Not sure what to do there.

**Comment by smarter** [comment]
> which comes after typing and apparently can't do implicit search.

I think it's a design decision to never do implicit search after typing, not a restriction of the implementation.

**Comment by odersky** [comment]
Hi Paolo, I am scanning the issues and thought maybe you want to take over some of the `Eq` stuff when you are here. So I am assigning issues as I see them.

**Comment by nicolasstucki** [comment]
Phantom types do not exist anymore.

With `erased`, now we can just do
```scala
def bar[T](value: T)(erased implicit teq: Eq[T,T]) = value == value
```
