### ISSUE TITLE
Ambiguous implicits when using map method of scala.collection.immutable.TreeSet

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#2724]
See this snippet: https://scastie.scala-lang.org/03bIFlNRSyuoRM3tVqlGig

The same code compiles fine with scalac.

**Comment by odersky** [comment]
This has to do with the fact that dotty is "contrarivant" :wink: - it universally prefers subtypes as solutions for type variables over supertypes, independent of variance. So implicit preferences change. The example compiles OK under -language:Scala2, which turns off the variance feature. 

One can discuss whether the variance feature is the right thing, but probably not on this issue.
