### ISSUE TITLE
Infix syntax should be supported only for methods taking exactly one argument

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#2734]
Consider the following definition:

~~~ scala
object Foo {
  def op1[A](tuple: (A, A)): Unit = ()
  def op2[A](a1: A, a2: A): Unit = ()
  def op3[A](tuples: (A, A)*): Unit = ()
  def op4[A](as: A*): Unit = ()
}
~~~

Then, the following compiles:

~~~ scala
Foo op1 (1, 2) // “(1, 2)” is promoted to one tuple argument
Foo op2 (1, 2) // Here we supply two parameters, “1“ and “2”
~~~

What happens with the last two definitions?

~~~ scala
Foo op3 (1, 2)
Foo op4 (1, 2)
~~~

These cases are ambiguous: are we supplying one single parameter (of type `(Int, Int)`) or two parameters (of type `Int` each)?

The compiler rejects the `op3` call but accepts the `op4` call: in both cases it assumes that we are supplying two parameters (of type `Int` each). If we want to tell the compiler that we supply one parameter we have to use extra parenthesis or the `->` syntax:

~~~ scala
Foo op3 ((1, 2)) // OK
Foo op4 ((1, 2)) // OK
Foo op3 (1 -> 2) // OK
Foo op4 (1 -> 2) // OK
~~~

It seems that the `x op (y, z)` syntax assumes that `(y, z)` is a tuple *only* if `op` takes one parameter. In my opinion it should work the other way around: the `(y, z)` expression, alone, is a tuple, it should stay a tuple when supplied using the infix syntax.

As a consequence, I think that infix syntax should be supported only for methods taking exactly one argument.

**Comment by odersky** [comment]
That's how it used to be in Scala (up to 2.6/7 maybe?). It got changed, and now lots of code relies on the change with calls like

    buf += (1, 2, 3)

where

    def += (x: T*): this.type

So we'd need a "back to the future" migration strategy.

**Comment by olafurpg** [comment]
@odersky what was the change in 2.6/7?

- allow infix application for varags
- allow infix application for multiple arguments in general

It is possible to rewrite back into regular application in either case.

**Comment by odersky** [comment]
@olafurpg I think it was "allow infix application for multiple arguments in general". We can rewrite it, but the result would be weird, i.e.

    xs.+= (1, 2, 3)

instead of

    xs += (1, 2, 3)

**Comment by olafurpg** [comment]
@odersky I agree it looks weird for symbolic operators, but it might be a small price to pay for the nice simplification around adapted arguments. I did a survey to check how common symbolic infix operators with multiple arguments are https://github.com/olafurpg/syntax-experiments/issues/7. Many of those rely on adapted arguments. If I understand correctly, then those cases would not have to be rewritten.

**Comment by julienrf** [comment]
@olafurpg Indeed, `(1, 2) == (1, 2)` desugars to `(1, 2).==((1, 2))`. You should distinguish between arity adaptation and several parameters (but you can not do it with a syntactic only API…)

**Comment by ritschwumm** [comment]
personally, i use dotless method calls whereever i can - imho they read a lot easier than having superfluous dots and parens all over the place. now, i (and i'm probably not alone in this) have _a lot_ more methods taking two or more parameters than methods taking tuples, so this change would break every third line in my code, and force me to revert to a style i don't really like.

**Comment by odersky** [comment]
I think we should to leave it as is. There are good reasons either way, but backwards compatibility trumps everything.
