### ISSUE TITLE
Make CI into a matrix test

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#2753]
Our CI currently tests bootstrapped\non-bootstrapped,
after https://github.com/lampepfl/dotty/pull/2685 it also makes sense to test against both 2.11 and 2.12 stdlib.
It would be also nice to test `-optimize` and without it.

**Comment by felixmulder** [comment]
For clarity: the CI does use the matrix testing feature from drone. But
2.11 / 2.11 is not one of the axes :)

**Comment by Varunram** [comment]
Is this issue reserved for core members only? Cause editing `drone.yml` requires a signature right?

**Comment by felixmulder** [comment]
Correct :)

**Comment by allanrenucci** [comment]
@OlivierBlanvillain I am not aware of any work being to make the CI build with the 2.11 stdlib. Can we close this?
