### ISSUE TITLE
Support multi implicit parameter list

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#2774]
Implicit function type can be curried just fine:

```scala
object Test {
  trait T; trait Q
  val a: implicit T => implicit Q => Int = 1

  implicit val q: Q = new Q {}
  val i1: Int = a(new T{})
  implicit val t: T = new T {}
  val i2: Int =  a
}
```

It would be nice to be able to define `a` as a def!:

```scala
def a(implicit t: T)(implicit q: Q): Int = 1
```

**Comment by odersky** [comment]
It's coming, but we need `explicitly` first.

**Comment by Atry** [comment]
A duplicate to https://github.com/lampepfl/dotty/issues/1260 ?

**Comment by odersky** [comment]
On hold until `explicitly` is added.

**Comment by propensive** [comment]
@odersky Is there anything particularly difficult about implementing `explicitly`? It is (I think) the one thing holding me back from migrating a couple of libraries to Dotty (and which would give them better syntax in the process)!

**Comment by propensive** [comment]
Any news on when `explicitly` may be included in dotc?
