### ISSUE TITLE
Cyclic error involving @deprecated in Predef when compiling compileStdLib

### ISSUE THREAD

**Issue by abeln** [lampepfl/dotty#2792]
`vulpix tests/pos` fails on some systems while compiling the standard library:

```
sbt vulpix "tests/pos"
info] Test dotty.tools.dotc.CompilationTests.compileNeg started
[=======================================] completed (281/281, 37s)  
[info] Test dotty.tools.dotc.CompilationTests.compilePos started
-- [E045] Syntax Error: /u4/anietoro/src/dotty/compiler/../scala2-library/src/library/scala/Predef.scala:101:3 ---------
101 |  @deprecated("Use `scala.reflect.ClassTag` instead", "2.10.0")
```

@smarter mentioned a recent [PR](https://github.com/lampepfl/dotty/pull/2193/files) that normalizes the list of files in a test by sorting them. Looking at `compileList` in `ParallelTesting.scala`, it does no such sorting.

Once I sorted the files, the test now passes.

**Comment by smarter** [comment]
Could you attach the log file from the test failure?

**Comment by abeln** [comment]
Test run logs. The failure is on line 7383.

[tests-2017-06-22-15:17:23.txt](https://github.com/lampepfl/dotty/files/1096219/tests-2017-06-22-15.17.23.txt)

**Comment by abeln** [comment]
Actually, I'm able to repro this in more than one machine, with a fresh checkout.

**Comment by abeln** [comment]
To better repro the problem, sort `StdLibSources.whitelisted`, as in https://github.com/abeln/dotty/commit/ddf98890eb4fd7932bae98785e94517ecb7d4b16

**Comment by smarter** [comment]
Duplicate of https://github.com/lampepfl/dotty/issues/2633
