### ISSUE TITLE
Latest version of dotty should be written down in a fixed place

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2806]
sbt-dotty currently has some complicated logic to try to guess the latest nightly build of dotty based on maven xml, but it's hardcoded to `dotty_0.2` (and was previously hardcoded to `dotty_0.1`). Users that want to  know what the latest version of dotty is also have to look at maven and scroll through a bunch of versions. It would be easier for everyone if we had something like:
Fetching http://dotty.epfl.ch/last-stable returns the string "0.1.2-RC1" (until we have a real stable release).
Fetching http://dotty.epfl.ch/last-rc returns the string "0.1.2-RC1".
Fetching http://dotty.epfl.ch/last-nightly returns the string "0.2.0-bin-20170622-7381e9d-NIGHTLY".

This could be done by the CI when the site is generated.

**Comment by olafurpg** [comment]
This would be nice to avoid having to upgrade sbt-dotty every 6 weeks for the community build.

**Comment by DarkDimius** [comment]
@smarter @olafurpg I actually prefer it when we need to explicitly update the hardcoded version in the repo. This makes it easy to reproduce historical results as you know exactly what version was used.

**Comment by olafurpg** [comment]
@DarkDimius  the `dottyLatestNightlyBuild` helper returns a new version with every new nightly build. The inferred `dottyLatestNightlyBuild` is printed out in the console (https://github.com/lampepfl/dotty/blob/775e3dbb282ba0e6da78895d3325357008cf7cd3/sbt-dotty/src/dotty/tools/sbtplugin/DottyPlugin.scala#L25) so it's still possible to reproduce historical results. This proposal is to extend `dottyLatestNightlyBuild` to infer the base series, which should not hurt reproducibility of historical builds.

**Comment by olafurpg** [comment]
Keeping the community build in sync with the latest nightly release continues to be a struggle https://github.com/lampepfl/dotty-community-build/pull/15 It would be an improvement if the latest binary version (0.2/0.3/...) was written down somewhere in a fixed place, the full version number can be fetched from Maven Central.

**Comment by Blaisorblade** [comment]
This was (meant to be) fixed by #2806, and the fix seems to still work: http://dotty.epfl.ch/versions/latest-nightly-base returns 0.8 and http://repo1.maven.org/maven2/ch/epfl/lamp/dotty_0.8/maven-metadata.xml lists nightlies until yesterday's. Hence closing.
