### ISSUE TITLE
By-name arguments do not behave as expected with right-associative operators

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2808]
This is the same bug as https://github.com/scala/bug/issues/1980:
```scala
class C {
  def m2_:(f: => Int) = ()
}

object Test {
  def foo() = { println("foo") ; 5 }

  def main(args: Array[String]): Unit = {
    val c = new C
    foo() m2_: c
  }
}
```
This should print nothing but ends up printing foo because we desugar:
```scala
foo() m2_: c
```
into:
```scala
val $1$: Int = Test.foo()
c.m2_:($1$)
```
In scalac this was basically unfixable because this desugaring is done during parsing, but in dotty we should have the type of `m2_:` during desugaring which tells us that its argument is by-name and thus we could simply do:
```scala
lazy val $1$: Int = Test.foo()
c.m2_:($1$)
```

Whether or not this is fixed might influence the design of the collection strawman: https://github.com/scala/collection-strawman/issues/127

**Comment by szeiger** [comment]
While playing around with a possible solution for 2.13 I realized that `lazy val` may not be ideal in this case because it caches the result whereas a by-name parameter does not. For true by-name semantics we should translate `a :: b` where the parameter to b is by-name to `b.::(a)`, i.e. the same as for left-associative operators, except for the reversed operands.

**Comment by szeiger** [comment]
Here's my implementation of this scheme for 2.13: https://github.com/scala/scala/pull/5969

**Comment by lrytz** [comment]
I agree the transformation to `b.::(a)` is nice here. For names / defaults, we de-sugar to `() => a`:

```
scala> def f(x: => Int, y: Int) = 0
f: (x: => Int, y: Int)Int

scala> f(y = 1, x = { println(""); 2}) // print

{
  val x$1: Int = 1;
  val x$2: () => Int @scala.reflect.internal.annotations.uncheckedBounds = (() => {
    scala.Predef.println("");
    2
  });
  $line16.$read.$iw.$iw.f(x$2.apply(), x$1)
} // : Int
```
