### ISSUE TITLE
Styling of Blogs landing page

### ISSUE THREAD

**Issue by Varunram** [lampepfl/dotty#2818]
<img width="1280" alt="screen shot 2017-06-28 at 11 18 49 am" src="https://user-images.githubusercontent.com/18598959/27626106-6d3ab7e8-5c04-11e7-87ce-bda94491532f.png">
Increasing space between the date and the blog would make it look a bit better. What are your views?

**Comment by felixmulder** [comment]
I don't think the blog landing page is supposed to have a date up there by the title :)

**Comment by Varunram** [comment]
Closed via `e52095aa6981b055eead1b96b841ac60d5892d01`
