### ISSUE TITLE
Better error message when failing to launch Visual Studio Code

### ISSUE THREAD

**Issue by ssanj** [lampepfl/dotty#2828]
When using **launchIDE** to launch Visual Studio Code on Macos without either installing it or having it on the path I get the following error:

> [error] ({.}/*:runCode) java.io.IOException: Cannot run program "code": error=2, No such file or directory

It might be nice to have a more friendly error message like:

> Could not find Visual Studio Code on your system. Please [download](https://code.visualstudio.com/) it and add it to your path (for [linux](https://code.visualstudio.com/docs/setup/linux), [windows](https://code.visualstudio.com/docs/setup/windows) or [mac](https://code.visualstudio.com/docs/setup/mac)) and then rerun *launchIDE*.

**Comment by smarter** [comment]
For anyone wanting to try fixing this, you can do it around here: https://github.com/lampepfl/dotty/blob/34ea263a65dd56db948e94ea19a4ecd9f29e742f/sbt-dotty/src/dotty/tools/sbtplugin/DottyIDEPlugin.scala#L236-L239

**Comment by smarter** [comment]
The main annoying thing here is that `IOException` can be thrown in various situations, so you can't just catch `IOException` and always print this, you would have to check the string `IOException#message` I guess.

**Comment by amanjpro** [comment]
I will be willing to work on this, maybe tomorrow I will have time to push something

**Comment by amanjpro** [comment]
I believe I have fixed this, but not sure how to test it. sbt-dotty/scripted runs a bunch of long tests, is there an easier way to test it?

**Comment by amanjpro** [comment]
I guess this issue should be closed now, as PR #2841 is now merged

**Comment by smarter** [comment]
Yes, thanks
