### ISSUE TITLE
Parsing: `extends` with 0 parents compiles

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#2853]
Following bug is discovered by @nicolasstucki during a discussion.

The compiler should produce an error message, but it accepts the code below:

```Scala
class A extends { }
object A extends { }
```

**Comment by nicolasstucki** [comment]
Note that it compiles with an empty list of parents for the class A.

The check needs to be done in the parser.

**Comment by Idyllei** [comment]
This seems like it *should* be allowed, given that anonymous declarations are allowed in the bounds of a type parameter:

```scala
class Foo[A <: { def bar: Bar }]
```

If anonymous types are allowed here, it makes sense that the anonymous declaration after `extends` is valid:

```scala
class A extends {
    def meth: Unit = ???
}
```

In this case, `A` is subclassing an anonymous (non-abstract) type. This also allows one to provide an anonymous abstract type with early initializers (which were dropped in 0.3.0-bin-SNAPSHOT).

Why should one be allowed to use an anonymous type declaration in one place (parameter bounds), but not in others (subclassing)?

**Comment by nicolasstucki** [comment]
We missed that use case.
It seems like this PR should not be merged.

**Comment by smarter** [comment]
> In this case, A is subclassing an anonymous (non-abstract) type. This also allows one to provide an anonymous abstract type with early initializers (which were dropped in 0.3.0-bin-SNAPSHOT).

I'm not sure what you mean, `class A extends { ... }` and `class A { ... }` compile down to the exact same bytecode, and early initializers have never been supported by dotty and are not planned to be supported: http://dotty.epfl.ch/docs/reference/dropped/early-initializers.html

**Comment by liufengyun** [comment]
Decided not to fix this issue. See #2918.
