### ISSUE TITLE
Add `ValueOf` equivalent of SIP23 (TLS) to dotty

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#2857]
SIP23 will be merged into Scala 2.xx sometime in the future (currently merged into TLS).
Its implementation has a `ValueOf` type class that enables us to request the literal values from literal types. E.g.:
```
def foo[T](implicit i : ValueOf[T]) : T = valueOf[T]
```
Since we want to have Scala 2.xx and Scala 3.xx to be the same in the future, it is important to keep this feature.

**Comment by propensive** [comment]
I would find this potentially very useful.

**Comment by smarter** [comment]
Duplicate of https://github.com/lampepfl/dotty/issues/2616 (I'll fix it soon!)
