### ISSUE TITLE
Failure in shape-based overload resolution for PartialFunction

### ISSUE THREAD

**Issue by szeiger** [lampepfl/dotty#2866]
This was discovered in https://github.com/scala/collection-strawman/pull/117#discussion_r122973565. Simplified test case using the current Dotty master:

```scala
scala> trait SortedMap[K, V] {
           def collect[B](pf: PartialFunction[(K, V), B]): Int = 0
           def collect[K2 : Ordering, V2](pf: PartialFunction[(K, V), (K2, V2)]): Int = 0
           def foo(xs: SortedMap[String, scala.Int]) = xs.collect { case (k, v) => 1 }
         }
-- [E080] Syntax Error: <console>:7:61 -----------------------------------------
7 |    def foo(xs: SortedMap[String, scala.Int]) = xs.collect { case (k, v) => 1 }
  |                                                             ^
  |     missing parameter type for parameter x$1 of expanded function x$1 =>
  |       x$1 @unchecked match
  |         {
  |           case (k, v) =>
  |             1
  |         }, expected = ?
```

This should have been enabled by https://github.com/lampepfl/dotty/pull/2015. My original implementation for Scala 2.13 in https://github.com/scala/scala/pull/5698 had bugs which are fixed by https://github.com/scala/scala/pull/5975. It could be a similar problem in Dotty.

**Comment by julienrf** [comment]
I’m not sure this issue has been fixed. If I uncomment the type annotation [here](https://github.com/scala/collection-strawman/pull/117#discussion_r122973565) the code still doesn’t compile with Dotty 0.3.0-bin-20170721-d7faafa-NIGHTLY.

**Comment by smarter** [comment]
@julienrf The original example in this issue now compiles, so I think it'd makes sense to open another issue for the problem you're seeing.

**Comment by odersky** [comment]
@julienrf The fix was merged two hours ago. So let's wait for the next nightly.

**Comment by odersky** [comment]
I just checked on the strawman itself, and verified that it works now without the type annotation for xs12.
