### ISSUE TITLE
Ignore `tests/partest-generated` in vscode search

### ISSUE THREAD

**Issue by jvican** [lampepfl/dotty#2873]
Looking for any class brings results from generated sources by partest. Adding this to the "search.exclude" option in vscode should be enough to remove them from the search results:
``` 
    "tests/partest-generated/**/*.scala": true,
```

**Comment by smarter** [comment]
Partest isn't used anymore, so if you just remove this directory you should be good :).

**Comment by smarter** [comment]
But if you find other stuff that needs to be excluded, feel free to add it to https://github.com/lampepfl/dotty/blob/master/.vscode-template/settings.json and make a PR!

**Comment by jvican** [comment]
Nice, thanks!
