### ISSUE TITLE
Re-do bench project

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#2878]
I'm redoing a general benchmark framework for Dotty using JMH in the following two projects:

- https://github.com/liufengyun/bench-web
- https://github.com/liufengyun/bench

Note: Separation of `Bench` from `Dotty` can be justified if we want to benchmark history of `Dotty`.

The basic concept works, as the following graph shows (for last 2 months):

https://liufengyun.github.io/bench/

The graph show PR number, PR date, also links to the tested file/project, PRs. It tests performance for each PR.

I'm now polishing details and add more tests/projects. It takes a while to benchmark all 287 PRs since last two months.

**Comment by liufengyun** [comment]
I just added another micro-test, it confirms in shape with the first micro-test: https://liufengyun.github.io/bench/

**Comment by smarter** [comment]
It would be useful to benchmark both the non-bootstrapped and bootstrapped dotty to compare performance.

**Comment by liufengyun** [comment]
It seems we can only do this temporarily, given that we are going fully bootstrapped in the future and we only have the unbootstrapped version several months ago.

**Comment by smarter** [comment]
The non-bootstrapped dotty still exists for now it's just not published

**Comment by smarter** [comment]
We don't need very precise data points for the non-bootstrapped compiler, we could have one point every month or so

**Comment by liufengyun** [comment]
Already done and implemented in http://dotty-bench.epfl.ch .
