### ISSUE TITLE
Support "sbt launchIDE" with VS Code Insiders (executable is called "code-insiders" instead of "code")

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#2881]
vscode offers nightly builds called "Insiders": https://code.visualstudio.com/insiders. `sbt launchIDE` won't succeed if you only have Insiders installed because the executable is called `code-insiders` instead of `code`. We should try to fallback on `code-insiders` when `code` is not found.

**Comment by rami3l** [comment]
Encountered the same problem today when trying out dotty. Although a workaround is quite feasible, I still want to see this fixed :)

**Comment by smarter** [comment]
We're in the process of deprecating vscode-dotty and `launchIDE` in favor of metals, which does not require any sbt command to start the IDE: https://scalameta.org/metals/, so I'll be closing this issue. (Note: to switch from vscode-dotty to metals, you'll need to delete the generated .dotty-ide.json and .dotty-ide-artifact files in the root of the project)
