### ISSUE TITLE
Syntax error with Enums

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#2906]
This fails to compile
```scala
enum Foo {
  case Bar
  private case Bat
}
```
```scala
-- [E039] Syntax Error: <console>:3:2 ------------------------------------------
3 |  private case Bat
  |  ^^^^^^^
  |  ';' expected, but 'private' found
```
It can be reproduced with any modifier.

**Comment by biboudis** [comment]
Thanks @allanrenucci. Modifiers are currently not supported with Enums.

Enums are discussed [here](http://dotty.epfl.ch/docs/reference/enums/desugarEnums.html).

I am marking it as a bug as the error needs to be adjusted.

**Comment by allanrenucci** [comment]
Note that dotc is fine with both
```scala
enum Foo {
  case Bar;
  private case Bat
}
```
and 
```scala
enum Foo {
  private case Bar
} 
```
So the reported error is not the only issue here.

**Comment by nicolasstucki** [comment]
Is it actually making `Bar`/`Bat` private? or is the modifier ignored.
What is the use case for a private enum?

**Comment by allanrenucci** [comment]
This is what I get in the repl
```scala
scala> enum Foo { case Bar; private case Bat } 
defined class Foo
defined module Foo
scala> Foo.Bar 
val res1: Foo = Bar
scala> Foo.Bat 
-- Error: <console>:6:4 --------------------------------------------------------
6 |Foo.Bat
  |^^^^^^^
  |value Bat in object Foo cannot be accessed as a member of Foo.type from module class $iw$.
```
I used `private` to showcase the issue. It can be reproduced with any modifier. I can see use cases for annotations (e.g. `@deprecated`)

**Comment by biboudis** [comment]
I wonder what happens in the case of pattern matching over mixed enum cases.

ping @odersky
