### ISSUE TITLE
Difference in erasure between dotc and scalac

### ISSUE THREAD

**Issue by Jasper-M** [lampepfl/dotty#2920]
```
sealed trait Foo
object Foo { type A }
```
Scalac erases the type `Foo.A with Foo` to `Object`. Dotc erases it to `Foo`.

I'm not sure if that would be considered a bug, but I was told differences in behavior between scala and dotty should be documented regardless.

**Comment by odersky** [comment]
I believe at some point `scalac` behaved like Dotty. Maybe @retronym can reconstruct why that got changed. It would be important to use the same algorithm for binary compatibility.

**Comment by smarter** [comment]
scalac algorithm: https://github.com/scala/scala/blob/cac6383e6658dc5956540b76b9b46c3b664774ac/src/reflect/scala/reflect/internal/transform/Erasure.scala#L290-L323
dotty algorithm: https://github.com/lampepfl/dotty/blob/1ab60276f5684ec7c80f3fed3c0f52ab491ecca6/compiler/src/dotty/tools/dotc/core/TypeErasure.scala#L285-L310

**Comment by smarter** [comment]
https://github.com/lampepfl/dotty/issues/4619 is a duplicate but has a bit more details so closing this one.
