### ISSUE TITLE
Difference in variance checks between dotc and scalac

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#2923]
The following snippet does not compile in Dotty but compiles fine in Scala: https://scastie.scala-lang.org/UbSw8tokR1msWK25p390xQ

I think Scala is right.

**Comment by julienrf** [comment]
This one compiles fine on both: https://scastie.scala-lang.org/Ik5iBkgiSJalUZYmhY70FA (note that in `Bar`, `A` is contravariant).

**Comment by nicolasstucki** [comment]
```scala
trait Foo[+A] {
  class Quux(b: Bar[A])
}

trait Bar[+A]
```

should probably not be correct the following fails
```scala
trait Foo[+A] {
  def quux(b: Bar[A]) = ()
}

trait Bar[+A]
```

I would say it is a bug in scalac.

**Comment by julienrf** [comment]
Indeed, that code is not correct and should be rejected by the compiler, which is what dotc does.
