### ISSUE TITLE
Unsound type widening for setters with wildcard types

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#2928]
This might be a known problem. The following code compiles in `dotc` and produces run-time exception. Scalac compiler rejects the code.

```Scala
class Box[T](var v: T)

object Test {
 def main(args: Array[String]): Unit = {
   val s = new Box[String]("")
   val i = new Box[Int](3)

   var box: Box[_] = s
   val sv = box.v
   box = i
   box.v = sv

   val c: Int = i.v
 }
}
```

**Comment by smarter** [comment]
This seems to be an issue with unsound type widening somewhere, and it's specific to var setters, e.g. the following fails to typecheck as expected:
```scala
class Box[T](private[this] var x: T) {
  def get: T = x
  def put(elem: T) = x = elem
}

object Test {
 def main(args: Array[String]): Unit = {
   val s = new Box[String]("")
   val i = new Box[Int](3)

   var box: Box[_] = s
   val sv = box.get
   box = i
   box.put(sv)

   val c: Int = i.get
 }
}
```
```scala
14 |   box.put(sv)
   |           ^^
   |           found:    Box[_]#T(sv)
   |           required: ?1.T
   |           
   |           where:    ?1 is an unknown value of type Box[_]
```

The same thing should happen for `box.v = sv` in your example, but doesn't currently.

**Comment by smarter** [comment]
See https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/core/TypeOps.scala#L21-L50 for an explanation of how skolemization is done, for some reason this seems to not be done correctly for var setters.
