### ISSUE TITLE
Allow implicit modifier in for comprehension

### ISSUE THREAD

**Issue by mdedetrich** [lampepfl/dotty#2930]
The original issue can be found some time ago here https://issues.scala-lang.org/browse/SI-2823

The idea is to allow using the implicit modifier in for comprehensions, so you can do something like this

```scala
for {
  implicit requestId <- retrieveRequestId
  result <- Http.makeRequest("http://someuri.com")
} yield result
```
Currently you are forced to manually make a block, i.e.

```scala
for {
  requestId <- retrieveRequestId
  result <- {
     implicit val rId = requestId
     Http.makeRequest("http://someuri.com")
  }
} yield result
```

Which yields quite a lot of boilerplate

**Comment by nicolasstucki** [comment]
For this particular pattern we firs need #1982.

**Comment by biboudis** [comment]
Hello @mdedetrich! 

Thanks for bringing that up! This enhancement indeed seems useful and your code illustrates how boilerplate is added. 

As per the original ticket (and the subsequent discussions [1], SLIP proposal [2, 3] and a WIP PR [4], we still need a good story on the spec side (pattern matching, behavior of implicits inside and outside of the for-comprehension). Also the corresponding PR didn't move forward. Also a feature like that would need careful laying out of the rules in the presence of Dotty's implicit function types. On the other hand Dotty is able to do `implicit val (a, b) = ...` so there would be an interesting interaction of features but most importantly in needs spec changes.

Closing this as the same concerns are applicable in the Dotty-side as well. If someones studies the PR [4] and provides a good rework of the spec, this could definitely trigger a fruitful discussion around this enhancement.

1. https://contributors.scala-lang.org/t/implicit-keyword-in-lhs-of-for-comprehension/725
2. scala/scala.github.com#417
3. scala/slip#6 
4. scala/scala#4730
