### ISSUE TITLE
Exhaustivity check slowdown after enum exhaustivity added

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2940]
In the [benchmarks](https://liufengyun.github.io/bench/) for [exhaustivity V](https://github.com/liufengyun/bench/blob/master/tests/exhaustivity-V.scala) we can see that the performance went from 1.5 to 2.3 in https://github.com/lampepfl/dotty/pull/2197.

We should explore if this slowdown is justified and see if we can improve it.

**Comment by nicolasstucki** [comment]
Issue found in https://github.com/liufengyun/bench/issues/11

**Comment by nicolasstucki** [comment]
@liufengyun do you have some more insight?

**Comment by allanrenucci** [comment]
@nicolasstucki Can we close this? The performance are back to 1.5
