### ISSUE TITLE
The slogan can not be seen in the default zoom ratio on the home page

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#2961]
Default:
![image](https://user-images.githubusercontent.com/20694662/29032922-dc826912-7bc5-11e7-83ca-c5f0cf3aa3b0.png)

80%:
![image](https://user-images.githubusercontent.com/20694662/29032969-02d200a0-7bc6-11e7-9f2f-b3adb8dfbdd6.png)

50:
![image](https://user-images.githubusercontent.com/20694662/29032976-09d34544-7bc6-11e7-9ded-169eedfac98a.png)

**Comment by nicolasstucki** [comment]
What screen resolution do you have?

**Comment by Glavo** [comment]
@nicolasstucki 1366 x 768, maybe I need to change a new computer?

**Comment by nicolasstucki** [comment]
We should probably adapt the size of the logo if the height of the window falls below some threshold. This is also an issue for portrait mode on phones.

![screenshot_20170808-120108](https://user-images.githubusercontent.com/3648029/29067069-9349b00e-7c31-11e7-84f6-499dbb7d851f.png)
