### ISSUE TITLE
Anonymous classes indices should not be global

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#2964]
Currently fresh names for anonymous classes follow this pattern 
```scala
class Foo {
  new Object {} // will be named Foo$$anon$1
}
class Bar {
  new Object {} // will be named Bar$$anon$2
  new Object {} // will be named Bar$$anon$3
}
class Baz {
  new Object {} // will be named Baz$$anon$4
}
```
which will depend on the compilation order.

We need to change it to give fresh names per owner class like:

```scala
class Foo {
  new Object {} // will be named Foo$$anon$1
}
class Bar {
  new Object {} // will be named Bar$$anon$1
  new Object {} // will be named Bar$$anon$2
}
class Baz {
  new Object {} // will be named Baz$$anon$1
}
```

**Comment by DarkDimius** [comment]
I propose we do renaming late in pipeline(near the backend) but initially still create unique names fro lambdas:

 - It helps tremendously with debugging;
 - you don't know how are lambdas going to be lifted until very late.
