### ISSUE TITLE
Add `.exceptionally` to pool submission in Vulpix

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#2966]
Vulpix submits runnables to a thread pool in [ParallelTesting.scala](https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/tools/vulpix/ParallelTesting.scala#L424-L426). These submissions generate futures which do not have an exception handler.

By doing `.exceptionally` we could add handlers for these. This would be useful for not foregoing any stacktraces that might be lost.

**Comment by allanrenucci** [comment]
`.exceptionally ` is only available on `CompletableFuture` and not `Future`. I don't think it is possible to register an exception handler. @felixmulder Did you have something else in mind?

**Comment by smarter** [comment]
I outlined a possible solution here: https://gitter.im/lampepfl/dotty?at=59c14f031081499f1f4eb663

**Comment by felixmulder** [comment]
Guillaume's solution sounds a bit hacky TBH :)

What `workStealingPool` is doing is creating a `ForkJoinPool` and supplying a specific thread factory. The thread is created with a default exception handler. Should be possible to give the `ForkJoinPool` a different factory which has a better handler :)

**Comment by felixmulder** [comment]
But I haven't looked into it further than that...

**Comment by allanrenucci** [comment]
Indeed, one could do:
```scala
val pool = new ForkJoinPool()
val tasks = filteredSources.map(s => pool.submit(...))
// wait for termination
...
val errors = tasks.map(_.getException).filter(_ != null)
```
or
```scala
val futures = filteredSources
  .map(s => CompletableFuture.supplyAsync(..., pool))
  .map(_.exceptionally(...))
```

**Comment by allanrenucci** [comment]
Keeping this open as the current solution can be improved

**Comment by SzymonPajzert** [comment]
How would you like to improve current solution? Is didFail returning true if any exception is called during `eventualResults.foreach(_.get)`?
