### ISSUE TITLE
Adapt vulpix to SAM types

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#2967]
When moving to >= 2.12 after #2827 is merged, we can make vulpix use SAM types instead of doing things like:

`new Runnable { ... }` we can do `() => { ... }`.

**Comment by Rajesh-Veeranki** [comment]
I can work on this. So, only the files under the package `dotty.tools.vulpix` should be affected right?

**Comment by felixmulder** [comment]
That is correct, but if you want, you can also adapt the things in the `dotty.tools.dotc.interactive` package IIRC :)

**Comment by Rajesh-Veeranki** [comment]
Raised a PR [here](https://github.com/lampepfl/dotty/pull/3010) 
I found only two places where `() => {...}` it can be used. Please have a look and let me know if its fine.
