### ISSUE TITLE
Type inference issue

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#2972]
I had to add the following type ascription to get things compile with Dotty: https://github.com/scala/collection-strawman/pull/188/commits/1bc58a571719641899da2ab49d7ce71da5ed43c1

Prior to this commit, I got the following error: https://travis-ci.org/scala/collection-strawman/builds/264300323#L1366-L1383

**Comment by allanrenucci** [comment]
Closing this. Dotty does not need the type ascription anymore (tested as part of the community build): https://travis-ci.org/dotty-staging/collection-strawman/builds/325136456?utm_source=github_status&utm_medium=notification
