### ISSUE TITLE
Purpose of the Makefile in the binary release

### ISSUE THREAD

**Issue by Jendrik3** [lampepfl/dotty#2996]
What's the purpose of the Makefile in the binary release? `./bin/dotr` worked fine without running `make`. When should you run make?

**Comment by liufengyun** [comment]
That `Makefile` provides some convenience for some Linux users, but it is not required to run `bin/dotr` and `bin/dotc`. We are going to remove it in our next release to avoid confusion.

**Comment by Jendrik3** [comment]
Alright, thank you for clarifying.
