### ISSUE TITLE
Special handling in the typer of scala.Singleton is missing

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#2997]
```scala
  case class Foo[T <: Int with Singleton](t : T)
  val one = 1
  final val final_one = 1
  val a : 1 = Foo(1).t //Type Mismatch Error
  val b : Int = Foo(one).t //OK, but unexpected
  val c : 1 = Foo(final_one).t //Type Mismatch Error
```
Scastie link: https://scastie.scala-lang.org/DcDeG4eYQTG17exjb2FigQ

**Comment by smarter** [comment]
I don't think this has anything to do with class fields, it's just that Dotty doesn't know anything about the`Singleton` trait.

**Comment by soronpo** [comment]
Even without the `Singleton` the behavior differs between a function argument and a class field.
```scala
  object Test {
    val one = 1
    final val final_one = 1

    object OK {
      def foo[T <: Int](t : T) : T = t
      val a : 1 = foo(1)
      val b : Int = foo(one)
      val c : 1 = foo(final_one)
    }

    object Fail {
      case class Foo[T <: Int](t : T)
      val a : 1 = Foo(1).t //Error: Type mismatch
      val b : Int = Foo(one).t
      val c : 1 = Foo(final_one).t //Error: Type mismatch
    }
  }
```

**Comment by smarter** [comment]
Ah, that's interesting, still not specific to class field though :). `val a: 1 = Foo(1).t` becomes `val a: 1 = Foo.apply(1).t`, when inferencing the type parameter of `apply` we first pick up `>: 1` from the argument, we should pick up `<: 1` from the return type of `a` but we don't for some reason, I'll open a separate issue for that.

**Comment by smarter** [comment]
See https://github.com/lampepfl/dotty/issues/2998

**Comment by soronpo** [comment]
OK, thanks!
