### ISSUE TITLE
Tuples are not pretty printed in REPL

### ISSUE THREAD

**Issue by newca12** [lampepfl/dotty#3025]
```scala
scala> def foo[T](f: T => T, b: T) = f(b)
def foo[T](f: Function1[T, T], b: T): T
scala> def pairself[T](a:T) = (a,a)
def pairself[T](a: T): Tuple2[T, T]
scala> pairself(("ouch",2.0))
val res0: Tuple2[Tuple2[String, Double], Tuple2[String, Double]] = ((ouch,2.0),(ouch,2.0))
```

**Comment by felixmulder** [comment]
Thanks for reporting, we haven't implemented these desugarings in `UserFacingPrinter`, should be trivial :+1:

**Comment by smarter** [comment]
RefinedPrinter already has code to deal with this: https://github.com/lampepfl/dotty/blob/9f5711f0e1a1c5fac33dc21bb555c37ba26ed946//compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala#L116-L126
