### ISSUE TITLE
Lifted anonymous classes clash with non anonymous ones

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3051]
```scala
class Foo {
  class $anon$1
  new Object { }
}
```
As the unique name generator does not know about the name on `class $anon$1`, it will give the same name to the class for `new Object { }`. The result is a corrupted scope where both names refer to the same symbol and get stuck in an infinite loop.

Same for methods
```scala
class Foo {
  def foo = {
    def f() = ()
    f()
  }
  def f$1() = ()
}
```

There are two possible solutions
 * Disallow names 
 * Register all relevant names for classes and methods in the map of the `FreshNameCreator`

Which one should we choose? I am more inclined to the first one as it simplifies the interaction with #2999

`scalac` has the same issue https://github.com/scala/bug/issues/10492

**Comment by nicolasstucki** [comment]
As mentioned in the language specifications the `$` are reserved by the compiler (http://scala-lang.org/files/archive/spec/2.12/01-lexical-syntax.html). We should add warnings/errors when using such identifiers.

**Comment by odersky** [comment]
The current wording in the spec is something like this: "Names with $'s in them are reserved, and should not be used in programs. If a program does use such names the results are unspecified". I think we should not try to change this.
