### ISSUE TITLE
Benchmark on Dotty bootstraped

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3055]
We currently benchmark the performance on Dotty compiled by `scalac`, for each benchmark that we have. We need to add on top of this the performance of Dotty compiled by Dotty and if possible display them in the same plot.

This is orthogonal to #3052.

**Comment by smarter** [comment]
The benchmarks are now bootstrapped: https://github.com/liufengyun/bench/commit/357b792ec7af41a3fab8b45dd95b4a78581f0e2e
