### ISSUE TITLE
IntelliJ fails to import SBT project: Can't register given path of type 'TEST' because it's out of content root

### ISSUE THREAD

**Issue by TheReturningVoid** [lampepfl/dotty#3090]
Attempting to import the dotty SBT project into IntelliJ 2017.3 EAP gives the following error:

```
Can't register given path of type 'TEST' because it's out of content root. Content root: '/home/retvoid/usr/Development/Dotty/repl/test-resources' Given path: '/home/retvoid/usr/Development/Dotty/repl/test'
```

**Steps to reproduce:**
1. Clone this repository (or an up-to-date fork) recursively
2. Run `sbt managedDependencies`
3. Open the project in IntelliJ

**Comment by smarter** [comment]
I have opened https://github.com/lampepfl/dotty/pull/3093 which should fix the issue. Could you check if it works for you?

**Comment by TheReturningVoid** [comment]
Yep, that fixes it.
