### ISSUE TITLE
IDE: Need to double-check before renaming

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#3096]
I did a rename from Name#isTypeName to Name#isType on the dotty codebase. In most files some of the renames were off by some small number of characters mI.e. I got "iisType" instead of "isType)". Not sure why that happened, but we should be more defensive when renaming, double checking that the renamed region is indeed the right string.

**Comment by OlivierBlanvillain** [comment]
Not reproduce with that rename on master, closing.
