### ISSUE TITLE
Wildcard invalid as backquoted identifier

### ISSUE THREAD

**Issue by olafurpg** [lampepfl/dotty#3104]
```scala
object `_`
// scalac: compiles OK
// dotc: error:  wildcard invalid as backquoted identifier
```

If this is expected, can it be added to the "Dropped section" in the docs? I'm happy to add a migration rewrite to change `_` into something like `__` in scalafix.

**Comment by odersky** [comment]
This is as expected. Yes, we need to spec this somewhere, but the change is so tiny that it seems overkill to include it in the "dropped" section.
