### ISSUE TITLE
IDE does not start if the project does not compile

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3114]
When launching the IDE with `sbt launchIDE` and the project sources do not compile, the IDE simply does not start. 

This can be reproduced by creating a new project with `sbt new lampepfl/dotty.g8`, adding some code that does not compile in the main class and `sbt launchIDE`.

**Comment by smarter** [comment]
This is intentional, the IDE won't work right if up-to-date classfiles are not present. The alternative is loading all source files with out-of-date or non-existent classfiles in the IDE, but this requires communication with the build tool, which is hard to do until sbt gets a working server mode.

**Comment by Blaisorblade** [comment]
FWIW in #4469 @smarter has a (seemingly different) suggestion here.

**Comment by Duhemm** [comment]
@smarter improved Dotty IDE so that it starts with the old configuration if the projects doesn't compile here: #5128
