### ISSUE TITLE
Application of HKTs in path-dependent types doesn't work as expected

### ISSUE THREAD

**Issue by Jacoby6000** [lampepfl/dotty#3139]
The code below fails to compile (but should work)
```scala
  trait Foo[T] {
    type Base[A]
  }
  
  def foo[T](ev: Foo[T]): Foo[T] { type Base[A] = ev.Base[A] } = ev
```

However this works, but (based on some gitter discussion) should not.
```scala
  trait Foo[T] {
    type Base[A]
  }
  
  def foo[T](ev: Foo[T]): Foo[T] { type Base = ev.Base } = ev
```

**Comment by odersky** [comment]
I don't see why the second example should not work?

**Comment by smarter** [comment]
I think I argued we should require eta-expansion in type bounds so that the kindinhmg of a type is always obvious.
