### ISSUE TITLE
sbt-dotty plugin fails to aggregate multiple projects

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3172]
Consider the following scenario:

I have a project structure like this
```
.
├── bar
│   └── src
│       └── main
│           └── scala
│               └── Bar.scala
│
├── foo
│   └── src
│       └── main
│           └── scala
│               └── Foo.scala
│
├── build.sbt
│
└── project
    ├── build.properties
    └── plugins.sbt
```

and a `build.sbt` as follow:
```scala
lazy val foo = project
  .in(file("foo"))

lazy val bar = project
  .in(file("bar"))

lazy val root = project
  .in(file("."))
  .aggregate(foo, bar)
```
If `plugin.sbt` is empty, then I can type `sbt compile` and it will compile `Foo.scala` and `Bar.scala`. However, if `plugin.sbt` contains
```scala
addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.1.5")
```
then when I type `sbt compile`, it will do nothing. I can still do `sbt bar/compile` or `sbt foo/compile`

**Comment by smarter** [comment]
This has something to do with the use of `Def.derive` in `DottyIDEPlugin` but I don't understand what. As a workaround you can add:
```scala
  .disablePlugins(dotty.tools.sbtplugin.DottyIDEPlugin)
```
to every sbt project in the build.

**Comment by smarter** [comment]
Opened an issue on sbt because I'm baffled: https://github.com/sbt/sbt/issues/3580
