### ISSUE TITLE
Can't bump major TASTY version

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#3211]
The bootstrap currently does not allow for a bumping of the TASTY major version because it mixes 
different generation of TASTY files. Here's what I get if I change TastyFormat.majorVersion to 1:

info] ExtractAPISpecification
[info] 
[info] Existential types in method signatures should
[warn] there were three unchecked warnings; re-run with -unchecked for details
[warn] one warning found
[warn] there were two unchecked warnings; re-run with -unchecked for details
[warn] three warnings found
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[info] Compiling 14 Scala sources to /Users/odersky/workspace/dotty/doc-tool/target/scala-2.12/test-classes...
[info] Packaging /Users/odersky/workspace/dotty/compiler/target/scala-2.12/dotty-compiler_2.12-0.4.0-bin-SNAPSHOT-nonbootstrapped-tests.jar ...
[info] Done packaging.
exception caught when loading module class DottyPredef$: dotty.tools.dotc.core.tasty.TastyUnpickler$UnpickleException: TASTy signature has wrong version.
 expected: 1.0
 found   : 0.5
[info]

**Comment by smarter** [comment]
Does that happen even if you do dotty-example-project/clean ?

**Comment by smarter** [comment]
Oops, I mean dotty-bootstrapped/clean

**Comment by odersky** [comment]
Indeed dotty-bootstraped/clean fixed the problem. I though I had done that, but seemingly not.
