### ISSUE TITLE
Option parsing is broken

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#323]
`dotc -target:jvm-1.7` doesn't work, it seems that one needs to type `dotc -target jvm-1.7` which is different from scalac

**Comment by DarkDimius** [comment]
fyi: java1.7 target is NOT supported by dotty. Backend assumes at least java 1.8(encoding of traits assumes presence of default methods, closures are always compiled to java 1.7 lambdas).

**Comment by smarter** [comment]
Right, it's just the first example I found :)

**Comment by felixmulder** [comment]
@smarter: is this still broken?

```bash
$ ./bin/dotc -target:jvm-1.7 file.scala
```

Works fine (even if it doesn't do anything with the java 7 choice).

**Comment by smarter** [comment]
Fixed by https://github.com/lampepfl/dotty/pull/1180
