### ISSUE TITLE
Move Dotty documentation to a separate repository

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3236]

**Comment by Blaisorblade** [comment]
We figured out the `gh-pages` branch might slow down cloning this repo. `git init; git remote add origin https://github.com/lampepfl/dotty.git; git pull origin master` seems a workaround for now.

**Comment by SzymonPajzert** [comment]
Is this issue still requested given that we can clone just single branch?

**Comment by Blaisorblade** [comment]
It’s still low priority. You can usually clone a repo without special instructions. But I fear this can’t be fixed externally since some of the code involved with publishing docs isn’t available externally.

**Comment by allanrenucci** [comment]
Fixed in #5264
