### ISSUE TITLE
Don't publish the same nightly twice

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3243]
We publish nightly on a daily basis. The nightly version is based on the latest commit on master:
```scala
val version = baseVersion + "-bin-" + VersionUtil.commitDate + "-" + VersionUtil.gitHash + "-NIGHTLY"
```
If there is no new commit since the previous nightly, we fill fail to publish a new artirfact because one with the same version already exists.

We can either change the version to reflect the publishing date, or don't do anything if there is no new commit since the previous nightly. @smarter WDYT?

**Comment by allanrenucci** [comment]
One side effect of failing to publish the same version twice is to require manual removal of the staging repository on [sonatype](https://oss.sonatype.org/).

**Comment by smarter** [comment]
Don't publish anything if there's nothing new :)

**Comment by Swilvan** [comment]
Hoping this is the sort of solution you're looking for.
Anyone I can assign for review?

**Comment by allanrenucci** [comment]
I am closing this issue since it appears that this is no longer a problem: publishing the same nightly twice will still fail but it does not require manual removal of a staging repository on sonatype.
