### ISSUE TITLE
Some[(A, Seq[B])] is not a valid result type of an unapplySeq

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3248]
This code snippet fails to compile with Dotty
```scala
class Test {
  class Foo(val name: String, val children: Int *)
  object Foo {
    def unapplySeq(f: Foo) = Some((f.name, f.children))
  }

  def foo(f: Foo) = f match {
    case Foo(name, ns @ _*) => 1
  }
}
```

```scala
[info] Running dotty.tools.dotc.Main -d out -language:Scala2 tests/allan/Test.scala -classpath dotty-library_2.12-0.4.0-bin-SNAPSHOT-nonbootstrapped.jar
-- Error: tests/allan/Test.scala:8:12 ------------------------------------------
8 |    case Foo(name, ns: _*) => 1
  |         ^^^^^^^^^^^^^^^^^
  |Some[(String, scala.collection.Seq[Int] @Repeated)] is not a valid result type of an unapplySeq method of an extractor
```

**Comment by odersky** [comment]
The code snippet now compiles with #3747 if the `unapplySeq` definition is replaced by `unapply`. Furthermore, the error message for the `unapplySeq` version suggests that one should use an `unapply` instead.

**Comment by Blaisorblade** [comment]
Given that the API in #3747 can't be used if you write the return type explicitly, I'm reopening this issue.

And given that we want cross-version Tasty to exist (at least for 3.0), and Tasty can't say that a method has a version-dependent user-written name (thankfully!), we must support `unapplySeq` at least for 3.0.
