### ISSUE TITLE
conflict between type annotations and type variables

### ISSUE THREAD

**Issue by olhotak** [lampepfl/dotty#325]
Consider the following code:

```
  type T = Int @a
  val x: T @b
```

What should be the effective annotation of the type of `x`? `@a`, `@b`, or both?

The first thing that `Type.hasAnnotation(ClassSymbol)` does is call `stripTypeVar`, so that loses `@b`. The current implementation of `stripTypeVar` throws away all annotations (so that it can find a typevar inside an `AnnotatedType`), so that loses `@a` as well. This implementation is clearly wrong (`hasAnnotation` ends up always returning false for every type), but what is the right (expected) behaviour? Should a typevar just accumulate all of the annotations of the types that it is instantiated with (`@a @b` in this example)?

**Comment by liufengyun** [comment]
It is mentioned in #397 that this is fixed in #394.
