### ISSUE TITLE
Type alias not followed in type checking

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#3259]
The following program compiles with `scalac`, but Dotty fails to compile.

```Scala
trait Universe {
  def Term: TermImpl
  trait TermImpl {
    type Name
  }
}

class Dotty extends Universe {
  val Term = TermImpl
  object TermImpl extends TermImpl {
    type Name = String
  }

  def f(x: String): Term.Name = x
}
```

The error message is as follows:

```Scala
14 |  def f(x: String): Term.Name = x
   |                                ^
   |                                found:    String(x)
   |                                required: Dotty.this.Term.Name
   |
```

**Comment by smarter** [comment]
This is not a bug, it's a feature :). When a def is overriden in Dotty by a val or a def without an explicit result type, the result type of the overriden def is used instead of inferring a result type from the rhs. Your example works if you give an explicit return type to `Term`:
```scala
   val Term: TermImpl.type = TermImpl
```

**Comment by liufengyun** [comment]
Thanks for the tip @smarter !
