### ISSUE TITLE
Dotty profiling results with hyperthreading turned off

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3260]
Using [async-profiler](https://github.com/jvm-profiling-tools/async-profiler), with the following settings from its README:
```shell
echo 1 > /proc/sys/kernel/perf_event_paranoid
echo 0 > /proc/sys/kernel/kptr_restrict
echo 10000 > /proc/sys/kernel/perf_event_max_stack
```

In one terminal:
```shell
./bench/scripts/compiler.sh
```
in another, once warmups are done:
```scala
PID=$(jps|grep ForkedMain|cut -f1 -d' ')
./profiler.sh -d 120 -b 500000000  -o flat=1000 -f ~/tmp/dotty-noht.txt $PID
```
Top methods: https://gist.github.com/smarter/bf610b5bea8085c5296b97c303f74b63
Flamegraph: http://martres.me/tmp/dotty-noht-120.svg

Incidentally, turning off HT on my machine seems to help dotty performances quite a bit: it becomes about ~6% faster.

/cc @odersky

**Comment by odersky** [comment]
This is super interesting!  After seeing the previous profile with HT on, I was already wondering whether turning HT off could actually help performance because GC ops seemed to crowd out compiler work. So this is confirmed now.

The hot method graph is also very interesting, in particular wrt to the previous graph. The new winners in the hot methods contest are `Symbol#denot` and `NamedType#denotAt`. They have in common that they both select a denotation field `validFor` for the first time. My guess is that this will frequently miss the cache and cause a stall. So, denotations seem to be responsible for a large portion of cache misses.

The other interesting bit is the high number of `itable stub` entries in the hot method list. I tried to google them and found this: https://wiki.openjdk.java.net/display/HotSpot/InterfaceCalls
It seems they are compiler generated snippets that do interface method dispatch.

**Comment by odersky** [comment]
Another interesting observation is how flat the distribution now is. The 100'th most frequent method takes roughly 1/30 of the time of the most frequent method and the 1000'th most frequent methopd tales roughtly 1/300 of the time. So it's flatter than a 1/x distribution. Which means, so much harder to optimize...

**Comment by retronym** [comment]
> Another interesting observation is how flat the distribution now is

That has been my overwhelming experience with optimizing scalac, too. Compilers seem not to conform to the hotspot hypothesis.

There are of course still many opportunities when stepping back from the game of playing whack-a-mole with the hotspots. Did we need to call this method as often as we do, or at all?

The `itable` stubs can be linked to to particular call sites when viewed in the context of stack traces (or visuallly, in the flame graph when generated with `--reverse`. Here's an [example](https://www.dropbox.com/s/6x2ymbfws3bc5g1/flamegraph-reverse.svg?dl=0) of a reverse-stack trace flame graph from scalac.)

Here's a zoomed in section of the reversed flamegraph that shows which itable stubs are hot:

![image](https://user-images.githubusercontent.com/65551/31256726-b37088c0-aa77-11e7-8e65-36e9162f3de8.png)

I'm hovering over a call to `nonEmpty` in `PolyType.<init>`.

```scala
  case class PolyType(override val typeParams: List[Symbol], override val resultType: Type)
       extends Type with PolyTypeApi {
    //assert(!(typeParams contains NoSymbol), this)
    assert(typeParams.nonEmpty, this) // used to be a marker for nullary method type, illegal now (see @NullaryMethodType)
```

We also incur some overhead from `LinkedHashMap`, as it uses the inherited implementation of `findEntry` etc from `MapLike`. `HashMap` has been changed to manually inline ( 😢 ) some of this implementation. The JVM has trouble devirtualizing calls to default methods in interfaces (whether or not we add the trait forwarders in subclasses or not). Tight loops, such as those in `Map` queries, should still be written in classes.

Re the flamegraphs, @smarter I've found using `--min-width 1` is needed to avoid killing the SVG renderer. I usually generate a wider graph overall of around 2000px.

A word of warning: the stack traces used by `async-profiler` and Flight Recorder are occasionally non-sensical. I'm looking at a stack trace that shows `BoxesRuntime.unboxToBoolean` calling an `itable stub`. But it contains no `invokeinterface`! I think this is an instance of https://github.com/jvm-profiling-tools/async-profiler/issues/51 / https://bugs.openjdk.java.net/browse/JDK-8022893

**Comment by nicolasstucki** [comment]
Some other results obtained with Oracle Developer Studio
https://gist.github.com/nicolasstucki/4349f2f3db77d509ec0f89c3c422770a

**Comment by smarter** [comment]
> Re the flamegraphs, @smarter I've found using --min-width 1 is needed to avoid killing the SVG renderer. I usually generate a wider graph overall of around 2000px.

Using Firefox, the default min-width produces SVGs that can be reasonably browsed for me.

**Comment by nicolasstucki** [comment]
More results obtained with Oracle Developer Studio
https://gist.github.com/nicolasstucki/e35efb3fc70f8b200438ac243d7abc06

**Comment by nicolasstucki** [comment]
Not really an issue and profiles are outdated.
