### ISSUE TITLE
Subtyping error involving higher-kinded types and covariance

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#3264]
Consider the following code:

~~~ scala
trait Foo[+F[_]] {
  def bar: Bar[F]
}

trait Bar[+F[_]]

trait Base[+A]
trait Sub[A] extends Base[A]

object Main {
  def main(args: Array[String]): Unit = {
    def makeFoo(barSub: Bar[Sub]): Foo[Base] =
      new Foo[Base] {
        def bar/*: Bar[Base]*/ = barSub
      }
  }
}
~~~

We get the following type error (with 0.3.0-RC2):

~~~
-- [E007] Type Mismatch Error: /tmp/scastie1099504913399535263/src/main/scala/main.scala:14:33 
14 |        def bar/*: Bar[Base]*/ = barSub
   |                                 ^^^^^^
   |                                 found:    Bar[Sub](barSub)
   |                                 required: Bar[Base]
   |                                 
~~~

Try it in Scastie: https://scastie.scala-lang.org/julienrf/ijDLJLEPRRqt4FpHCpPRwg/1

If we uncomment the explicit type annotation, it compiles fine. Also, if make the type parameter `A` non-variant in `Base` it compiles fine even without the explicit type annotation.

(Discovered here: https://github.com/scala/collection-strawman/pull/262)

**Comment by allanrenucci** [comment]
I cannot reproduce on master

**Comment by julienrf** [comment]
OK, I should have tried that first ;)
