### ISSUE TITLE
Optimise AnyVal case class companion apply

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3269]
```scala
case class Foo(val a: Int) extends AnyVal
Foo(42)
```

will generate code like
```scala
case class Foo(val a: Int) extends AnyVal
object Foo {
  def apply(x: Int): Int = x
}
Foo.apply(42)
```

but the `apply` could be optimised away as it will always be the identity.

**Comment by smarter** [comment]
This is probably not very important to optimize, the JVM should have no problem inlining it.

**Comment by nicolasstucki** [comment]
It might enable more of our local optimizations. I would do with `-optimise` only.

Yes, the JVM is inlining it without any problems.

**Comment by odersky** [comment]
I'd say it's not worth optimizing this. It creates more special cases for no obvious gain.
