### ISSUE TITLE
Dotty generates suboptimal bytecode, even for simple code snippets

### ISSUE THREAD

**Issue by gan74** [lampepfl/dotty#3271]
For

```scala
  var x = 0
  while(x <= 5) {
    println(x)
    x += 1
  }
```

Dotty generates bytecode like this: (even with `-optimise`)

```
iconst_0
istore_2
goto 20
iload_2
iconst_5
if_icmpgt 19
getstatic scala/Predef$/MODULE$ Lscala/Predef$;
iload_2
invokestatic scala/runtime/BoxesRunTime/boxToInteger(I)Ljava/lang/Integer;
invokevirtual scala/Predef$/println(Ljava/lang/Object;)V
iconst_1
iload_2
iadd
istore_2
goto 4
nop
nop
athrow
goto 21
goto 4
return
```
while scalac 2.12.3 generates:

```
iconst_0
istore_2
iload_2
iconst_5
if_icmpgt 15
getstatic scala/Predef$/MODULE$ Lscala/Predef$;
iload_2
invokestatic scala/runtime/BoxesRunTime/boxToInteger(I)Ljava/lang/Integer;
invokevirtual scala/Predef$/println(Ljava/lang/Object;)V
iload_2
iconst_1
iadd
istore_2
goto 3
return
```

**Comment by smarter** [comment]
scalac always does some DCE, even when the optimizer is off: https://github.com/scala/scala-dev/issues/322#issuecomment-323345961. But this has a performance cost, there has been some work recently to improve this: https://github.com/scala/scala/pull/6075.

**Comment by odersky** [comment]
I wonder where the 

    nop
    nop
    athrow

is coming from. I also observed that in code and it seems to have no purpose.

**Comment by smarter** [comment]
the nop nop athrow pattern is mentioned in https://github.com/scala/scala-dev/issues/322#issuecomment-323345961 which points to https://github.com/scala/scala/blob/v2.12.3/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala#L830-L872
