### ISSUE TITLE
Importing implicit values

### ISSUE THREAD

**Issue by lavrov** [lampepfl/dotty#3284]
It is quite common practice for library authors to provide special object with implicit values. In many cases those are just implicit value definitions pointing to original non-implicit value. 
Example:
`scala.concurrent.ExecutionContext.global` 
`scala.concurrent.ExecutionContext.Implicits.global`

It would be useful if import statement could also introduce implicit values.
Example:
`import implicit scala.concurrent.ExecutionContext.global`

This of course would imply certain limitations on `import` statement because only vals, defs and objects can be imported as implicits.

**Comment by odersky** [comment]
I am not sure what exactly is proposed. Can you elaborate?

**Comment by lavrov** [comment]
With `import` statement one can introduce values into the scope (as well as classes and packages). If a regular value is imported then it becomes visible in the scope as a regular one. If a value has `implicit` modifier then it is imported as an implicit one and will participate in implicit resolution process. The proposal is about the possibility of turning regular values into implicit ones in the scope where they are imported by means of `import` statement itself.
```scala
object Bar {
  val foo: FooBar
  val baz: BazBar
}
```
`foo` is not declared as an implicit value but I want it to be implicit on use site. What if I could import it as implicit?
```scala
import implicit Bar.foo
```
or like this
```scala
import Bar.{implicit foo, baz} // only foo imported as implicit
```
This is just inquiry if this syntax could make sense at all.

**Comment by odersky** [comment]
Ah I see. Yes, that would be doable. The question is whether it's high enough priority to warrant the additional syntax. Not sure about that. It probably would need a SIP to be discussed thoroughly.

**Comment by odersky** [comment]
On reflection, I believe we should not make it easier to introduce implicit values. The benefits are debatable and even if one concludes there is a benefit the added language complexity is not worth it.
