### ISSUE TITLE
Improve error reporting when compiler infers the type of an overridden value/method

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3294]
```scala
trait WebDriver

class HtmlUnitDriver extends WebDriver {
  def setJavascriptEnabled(bool: Boolean): Unit = ()
}

trait Driver {
  val webDriver: WebDriver
}

class HtmlUnit extends Driver {
  val webDriver = new HtmlUnitDriver()
  webDriver.setJavascriptEnabled(true)
}
```
Dotty cannot compiles this code snippet. With Dotty, `HtmlUnit.webDriver` has type `WebDriver` and not `HtmlUnitDriver`.
```scala
-- [E008] Member Not Found Error: tests/allan/Test.scala:13:12 -----------------
13 |  webDriver.setJavascriptEnabled(true)
   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |  value `setJavascriptEnabled` is not a member of WebDriver
```

This is expected, `webDriver` inherits the type of its overridden parent. It is confusing however. We should improve our error reporting.

**Comment by allanrenucci** [comment]
This is a breaking change with Scalac. Our migration tool should add explicit types to overridden values and methods. cc/ @olafurpg

**Comment by OlivierBlanvillain** [comment]
To me it's unclear how to improve the error, special casing when a type in *not* inferred because of an override sounds really overkill...
