### ISSUE TITLE
Generate checksum files for archives released on GitHub

### ISSUE THREAD

**Issue by bbarker** [lampepfl/dotty#3310]
This might be added to the archive building script (located where?). Supported checksums should include:
* md5sum
* sha256sum (used by NixPkgs)
* others?

I'll be happy to do this at some point, if someone doesn't get to it first.

**Comment by smarter** [comment]
I think just sha256sum should be enough

**Comment by allanrenucci** [comment]
We use [sbt-pack](https://github.com/xerial/sbt-pack) to generate the archive on GitHub:
```
sbt dist-bootstrapped/pack-archive
```
I wanted to automate the process with the CI and the [GitHub Release Plugin for Drone](http://plugins.drone.io/drone-plugins/drone-github-release/). The plugin can generate the checksum for you.
