### ISSUE TITLE
Can't run console via sbt scritped tests in Drone

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3322]
As shown in #3315, we currently cannot run the console from sbt scripted tests in Drone. Error:
```
bash: /dev/tty: No such device or address
```

**Comment by allanrenucci** [comment]
This seems to be the same issue as #2648. WDYT @liufengyun?

**Comment by OlivierBlanvillain** [comment]
Should be fixed now that our docker image is based on Ubuntu instead of Alpine.
