### ISSUE TITLE
Missing unchecked warning for isInstanceOf checks

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3324]
This code snippet emits a warning with scalac but not with Dotty
```scala
class Foo {
  def foo(x: Any): Boolean =
    x.isInstanceOf[List[String]]
}
```
```scala
Foo.scala:3: warning: non-variable type argument String in type List[String] (the underlying of List[String]) is unchecked since it is eliminated by erasure
    x.isInstanceOf[List[String]]
                  ^
one warning found
```

**Comment by odersky** [comment]
I am not sure what we want to spec here, yet.

**Comment by odersky** [comment]
I now think we should do the same as scalac.

**Comment by allanrenucci** [comment]
For `(x: X).isInstanceOf[P]`, scalac emits an unchecked warning when:

>We designate another type, XR, which is essentially the intersection of X and |P|, where |P| is the erasure of P.  If XR <: P, then no warning is emitted.

ref: https://github.com/scala/scala/blob/94cee79eb63b4449d21dc74cb9175d6412cc8a55/src/compiler/scala/tools/nsc/typechecker/Checkable.scala#L12-L64

**Comment by odersky** [comment]
It's actually a wider problem: Consider:

    class C[T] {
      val x: Any = ???
      if (x.isInstanceOf[List[String]]) // error: unchecked
        if (x.isInstanceOf[T])          // error: unchecked
          x match {
            case x: List[String] =>     // error: unchecked
            case x: T =>                // error: unchecked
          }
    }

scalac will issue an unchecked warning at each line. Dotty remains silent.
