### ISSUE TITLE
Is Dotty ready for 2.12?

### ISSUE THREAD

**Issue by LoranceChen** [lampepfl/dotty#3363]
The announce of 0.4.0-RC1 write [Scala 2.12 has supported](http://dotty.epfl.ch/blog/2017/10/16/fourth-dotty-milestone-release.html#scala-212-support-2827) but the homepage said `Dotty currently interops with libraries compiled with Scala 2.11 - but not 2.12`.  
Is there some limit for 2.12?

**Comment by allanrenucci** [comment]
We don't support Scala 2.11, only Scala 2.12. The documentation on the Dotty website need to be updated
