### ISSUE TITLE
java version 1.8 rejected in cygwin/windows-java due to carriage return

### ISSUE THREAD

**Issue by philwalk** [lampepfl/dotty#3367]
Calling dotd with windows java 1.8 in a cygwin terminal session fails with the following message:

> Error: Java 8 is required, actual 1.8

When setting the value of JAVA_VERSION in file bin/common line 65, a fix is to convert '\r' to '\n':

JAVA_VERSION=$("$JAVACMD" -version 2>&1 | tr '\r' '\n' | grep ' version "' | sed 's/.*version "\([0-9]*\)\(\.[0-9]*\)\{0,1\}\(.*\)*"/\1\2/; 1q')

**Comment by liufengyun** [comment]
Thanks for diagnosing the problem @philwalk !  We noticed the problem, there's a PR for it: https://github.com/lampepfl/dotty/pull/3331

**Comment by allanrenucci** [comment]
I like this fix better than the one we currently have. @liufengyun can you try it out and confirm it works?
