### ISSUE TITLE
creating file paths with embedded colons illegal under windows

### ISSUE THREAD

**Issue by philwalk** [lampepfl/dotty#3373]
The following code sequence in compile/test/dotty/tools/dotc/reporting/TestReporter.scala, lines 89 through 92 attempts to create a file with multiple embedded colons, throwing an exception in Windows:

```
    val df1 = new SimpleDateFormat("yyyy-MM-dd-HH:mm:ss")
    val folder = s"../testlogs/tests-${df0.format(date)}"
    new JFile(folder).mkdirs()
    outFile = new JFile(s"$folder/tests-${df1.format(date)}.log")
    outFile.createNewFile // added to trigger java.io.IOException locally, not in TestReporter.scala
```

Here's the exception:
`java.io.FileNotFoundException: ..\testlogs\tests-2017-10-23\tests-2017-10-23-10:18:51.log (The filename, directory name, or volume label syntax is incorrect)
`

replacing colons with hyphens (or other legal path characters) in the SimpleDateFormat seems to fix the problem.

**Comment by allanrenucci** [comment]
Could you give a fully compilable code snippet with which we can reproduce the issue?

**Comment by rsoeldner** [comment]
isn't this related to #3349 ?

**Comment by philwalk** [comment]
I'm happy to provide a compilable code snippet (it will have to wait until I return to the office in a few hours).   In the interim, you can reproduce it via "sbt test" under Windows.   Also, the last line of the code I provided is not needed, since I presume the exception is thrown on the ".mkdirs()" call.

**Comment by philwalk** [comment]
I'm working on a minimal source file that reproduces the problem, but in the meantime, I added one more line to the end of the sequence of code above, which is needed to trigger the exception.   More info shortly ...

**Comment by philwalk** [comment]
Judging by the path /mnt/c/Users/... I'm guessing that #3349 occurs on
Windows Subsystem for Linux, which permits colons in filenames, so it would
seem to be unrelated.

**Comment by philwalk** [comment]
Following up on the previous comment (I was unable to edit it without losing code formatting):

The relevant difference between the two cases is that a cygwin test uses the Windows JVM, but in WSL, it would be an Ubuntu/Linux .deb JVM distribution installed by apt, etc.   Here's a scala script that fails under cygwin and passes under WSL:
```
object ColonFilename extends App {
  val file = new java.io.File("1:2:3")
  file.createNewFile
}
```

**Comment by allanrenucci** [comment]
It doesn't look like an issue with Dotty issue nor an issue with Scala. I suppose it doesn't work either with Java. If so, there is nothing we can do about it

**Comment by smarter** [comment]
Of course there is something we can do about it.  Just change the generated file name to not use `:`

**Comment by allanrenucci** [comment]
My bad, I didn't realise it was in our code base...
