### ISSUE TITLE
Consider using a different directory for scripts

### ISSUE THREAD

**Issue by benmccann** [lampepfl/dotty#3401]
Eclipse by default uses the `bin` directory to put compiled code. The [dotty instructions](http://dotty.epfl.ch/docs/contributing/eclipse.html) recommend changing this from `bin` to `classes`. I maintain sbteclipse and was hoping that we could avoid this extra setup step for our mutual users. I think that `bin` is a fairly generic and vague name that doesn't indicate that you intend for just scripts to be in that directory. Would calling it something like `scripts` make its intended usage clearer?

**Comment by smarter** [comment]
I don't know if this is worth changing considering the future of IDE support in Dotty is the [Dotty Language Server](http://dotty.epfl.ch/docs/usage/ide-support.html) (which currently doesn't handle building your project but will soon be enhanced to do so by delegating to the [sbt server](https://github.com/sbt/sbt/pull/2737)). Eclipse users should be able to work on Dotty projects (including Dotty itself) using [LSP4E](https://projects.eclipse.org/projects/technology.lsp4e) although I don't think anyone has attempted to do this so far.

**Comment by allanrenucci** [comment]
I don't see why we should not do that. I also believe that `scripts` is a better name than `bin`

**Comment by smarter** [comment]
We could change it, but then we'd have to change paths in various places and let people know what the new name is. Doesn't seem worth the effort to me, but feel free to reopen the issue if it's something you want to tackle :).

**Comment by allanrenucci** [comment]
It's not something I plan to do, but I am sure this can be contributed by the community

**Comment by OlivierBlanvillain** [comment]
Given that Dotty will stop being cross compiled with scalac in the very near future, this issue is obsolete util Eclipse implements Dotty support.
