### ISSUE TITLE
Implement SIP-27: Trailing Commas

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3408]
Accepted SIP: http://docs.scala-lang.org/sips/completed/trailing-commas.html
Scala 2 implementation: https://github.com/scala/scala/pull/5245

**Comment by CucumisSativus** [comment]
Hey @smarter I'd like to work on this.

**Comment by smarter** [comment]
Go for it! :smile:

**Comment by CucumisSativus** [comment]
One thing i'm not sure @smarter , where should I place tests for this?

**Comment by smarter** [comment]
Tests that should compile go in `./tests/pos/`, tests that shouldn't compile go in `./tests/neg`, tests that should compile and run go in `./tests/run/`. You should be able to port the tests from https://github.com/scala/scala/pull/5245, the only difference is that we do not use check files for neg tests, instead we put `// error` in the source files on each line containing a compiler error.

**Comment by smarter** [comment]
Here's something that may be useful during development: you can pass the `-Xprint:parser` flag to the compiler to pretty-print the output of the parser, and If you add `-Yplain-printer` you'll see raw trees instead of pretty-printed output.

**Comment by CucumisSativus** [comment]
Thanks!

**Comment by rsoeldner** [comment]
Can someone help with the `tests/neg` cases. Starting with the this simple case (from [here](https://github.com/dwijnand/scala/blob/d55bad83108d030ef214d4a2477df66fffbbb8f5/test/files/neg/trailing-commas.scala#L10)):
```scala
package foo

trait ArgumentExprs1 { f(23, "bar", )(Ev0, Ev1) } // error

//// Test utilities
object `package` {
  sealed trait Ev0; implicit object Ev0 extends Ev0
  sealed trait Ev1; implicit object Ev1 extends Ev1
}
```
and `> dotty-compiler/testOnly dotty.tools.dotc.CompilationTests`
I receive:
```
...
Wrong number of errors encountered when compiling ../out/optimised/testOptimised/neg/trailing-comma, expected: 1, actual: 2
```

**Comment by smarter** [comment]
If it's normal to have two errors on this line, you can put the error  marker twice on the same line: `// error // error`.

**Comment by rsoeldner** [comment]
@smarter Thank you.

Currently i struggle with a few tests. Maybe the syntax/ gramma has changed and now the tests are ok ?

`pos` tests
```scala
  // test ': _*' syntax in patterns
List(1, 2, 3) match {
   case List(1, 2, _ @ _*,
   ) => 1
}

  // test varargs in patterns
val List(x, y, _*,
) = 42 :: 17 :: Nil
```
 which fail with:
```
- [E030] Syntax Error: bla.scala:4:23 -----------------------------------------
4 |   case List(1, 2, _ @ _*,
  |                       ^
  |                       `_*' can be used only for last argument

longer explanation available when compiling with `-explain`
-- Error: bla.scala:4:19 -------------------------------------------------------
4 |   case List(1, 2, _ @ _*,
  |                   ^
  |          The syntax `x @ _*' is no longer supported; use `x : _*' instead
-- [E031] Syntax Error: bla.scala:5:3 ------------------------------------------
5 |   ) => 1
  |   ^
  |   illegal start of simple pattern

longer explanation available when compiling with `-explain`
-- [E030] Syntax Error: bla.scala:9:17 -----------------------------------------
9 |  val List(x, y, _*,
  |                 ^
  |                 `_*' can be used only for last argument

longer explanation available when compiling with `-explain`
-- [E031] Syntax Error: bla.scala:10:2 -----------------------------------------
10 |  ) = 42 :: 17 :: Nil
   |  ^
   |  illegal start of simple pattern

longer explanation available when compiling with `-explain`

5 errors found
```

And one `neg` test that doesn't fail:
```scala
package foo

trait Import { import foo.Ev0, foo.Ev1, }

object `package` {
  sealed trait Ev0; implicit object Ev0 extends Ev0
  sealed trait Ev1; implicit object Ev1 extends Ev1
}
```

**Comment by smarter** [comment]
The only change in syntax compared to Scala 2 is that `@ _*` in pattern match has been replaced by `: _*`, the rest look like issues in your implementation. If you can't get all tests to pass you could still open a PR with the failing tests included and we may be able to help.
