### ISSUE TITLE
SymDenotation.annotations fails to complete annotations of DefDef

### ISSUE THREAD

**Issue by olhotak** [lampepfl/dotty#341]
The annotations of a `DefDef` are added to its `SymDenotation` at the beginning of `typedDefDef` by `addTypedModifiersAnnotations(ddef, sym)`.

The code of `SymDenotation.annotations` is `ensureCompleted(); myAnnotations`.

However, the completer for a DefDef does **not** trigger a call to `typedDefDef`. The completer types only the `tpt` and the `rhs` of the `DefDef`, but not the `DefDef` itself. Therefore, `ensureCompleted()` does not actually complete the annotations.

`SymDenotation.annotations` therefore returns either no annotations or the correct annotations, dependent only on whether a call to `typedDefDef` happens to have already been triggered by something else.

**Comment by olhotak** [comment]
At yesterday's Dotty meeting, it was suggested that completion of annotations (`addTypedModifiersAnnotations`) should be done not in `typedDefDef`, but at the beginning of the completer of the DefDef (and similarly for ValDef, TypeDef, and ClassDef).

Doing this introduces a cyclic reference error in `tests/pos/java-interop/t1782/Test_1.scala`, which contains the following code:

```scala
@ImplementedBy(classOf[Provider]) trait Service {
  // ...
}

class Provider extends Service {
  // ...
}
```

To complete Provider, we must complete Service. To complete Service, we now must complete its annotation. To complete the annotation of Service, we must complete Provider, hence the cycle.

**Comment by smarter** [comment]
Annotations are entered before completing definitions since https://github.com/lampepfl/dotty/pull/1693 which should take care of this.
