### ISSUE TITLE
Spurious CI failures when cloning

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3415]
Drone sometime fails to clone on PR because of a bug with GitHub.

A workaround is described in this [discussion](https://discourse.drone.io/t/solved-issues-when-cloning-github-pr/482/11)

**Comment by CucumisSativus** [comment]
@allanrenucci on my way with fixing it

**Comment by CucumisSativus** [comment]
@allanrenucci according to https://discourse.drone.io/t/solved-issues-when-cloning-github-pr/482/15 looks like the issue is solved on plugin level, probably after plugin update the issue does not need a workaround

**Comment by allanrenucci** [comment]
I have restarted the CI, hopefully it will pick up the latest version of the git plugin
