### ISSUE TITLE
Instability in dottydoc output

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3418]
Apparently, given the same code, dottydoc will not always produce the exact same output, this can be seen in some commits in https://github.com/lampepfl/dotty/tree/gh-pages where the only difference is the ordering of some members, e.g. https://github.com/lampepfl/dotty/commit/79d651cdc54590866203a0a77a9fc7ae2eebb143, https://github.com/lampepfl/dotty/commit/6bfb93acefc6846e1b805d3a7cad6e30b277af11

**Comment by Blaisorblade** [comment]
This might also be a reason why cloning `gh-pages` is so slow.

**Comment by romanowski** [comment]
Version, that changes daily is part of doc so we update the whole documentation everyday.
