### ISSUE TITLE
@unchecked annotation propagated to return type of the pattern match expression

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3427]
```scala
scala> val foo = List(1) match { case x: List[Int] @unchecked => x } 
val foo: List[Int] @unchecked = List(1)
```
`@unchecked` shouldn't show up here, the unchecked annotation on a pattern match expression is meant to be seen only by the pattern match checker and shouldn't be propagated to the return type of the pattern match

**Comment by odersky** [comment]
Will be fixed when #3723 is in.
