### ISSUE TITLE
Nothing inferred when class type parameter is missing

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3434]
```scala
class A[T]
class B extends A
```
```scala
> dotc Test.scala -Xprint:frontend
result of Test.scala after frontend:

package <empty> {
  class A[T]() extends Object() { 
    T
  }
  class B() extends A[Nothing]() {}
}
```
Both dotty and scalac infer `B extends A[Nothing]`. Should we require the type parameter to be specified? Or at least emit a warning?

**Comment by smarter** [comment]
I don't think we should require the type parameter to be specified since in general we do want it to be inferrable, e.g.:
```scala
class A[T](x: T)
class B extends A(1)
```
Though I guess we could refuse to infer `Nothing` for class type parameters by default and force the user to write it explicitly.

**Comment by allanrenucci** [comment]
Are there cases where inferred `Nothing` or `Any` are not code smell?

**Comment by edmundnoble** [comment]
Inferred `Nothing` is fine for implicits, in a lot of cases it's necessary (for example, see https://github.com/milessabin/shapeless/blob/wip/smc/core/src/main/scala/shapeless/smc.scala#L305) but I don't think it makes sense for `extends` to even have type inference here.

**Comment by odersky** [comment]
I am reluctant to change it, as it might have valid uses, and introduces an irregularity.
