### ISSUE TITLE
Patmat exhaustivity checks sometimes don't consider path-dependant children

### ISSUE THREAD

**Issue by AleksanderBG** [lampepfl/dotty#3455]
The following code compiles without any warnings:

```scala
trait AxisCompanion {
   sealed trait Format
   object Format {
      case object Decimal extends Format
      case object Integer extends Format
   }
}
object Axis extends AxisCompanion
class Axis {
   import Axis._
   def test( f: Format ) = f match {
      case Format.Integer => "Int"
   }
}
```

Note that `Axis#test` is inexhaustive. The underlying problem is that when children of `Format` are to be located, symbols for `AxisCompanion.Format.Decimal` and `.Integer` are obtained and are subsequently ousted in `refine`, as they are not subtypes of `Axis.Format`. The paths of `.Decimal` and `.Format` should be adapted to the path of their parent type.

@liufengyun - this was discovered when implementing intersection-based useless pattern checks in #3454. I found the cause for it, but as I'm running out of time and I'd prefer to focus on typechecker integration, I'm simply raising the issue here.

**Comment by liufengyun** [comment]
@AleksanderBG Thanks for reporting, it has to do with _prefix inference_ in _child instantiation_. I'll have a look.

**Comment by liufengyun** [comment]
Fixed in https://github.com/lampepfl/dotty/pull/3475
