### ISSUE TITLE
Overriding final members with abstract ones

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3468]
Consider the following code snippet
```scala
trait Foo { def foo: Int = 1 }
trait Test extends Foo { def foo: Int }
```
With scalac:
```scala
scala> new Test{}
res0: Test = $anon$1@6735f210
```
With Dotty:
```scala
scala> new Test{} 
1 |new Test{}
  |^
  |object creation impossible, since def foo: => Int is not defined

scala> (new Test { override def foo = 2 }).foo 
val res0: Int = 2
```

**Comment by allanrenucci** [comment]
As a side note Dotty and scalac behave the same for `abstract class`:
```scala
trait Foo { def foo: Int = 1 }
abstract class Test extends Foo { def foo: Int }
```
```scala
scala> new Test{} 
1 |new Test{}
  |^
  |object creation impossible, since def foo: => Int is not defined
```
So Dotty's behavior is consistent between `trait` and `abstract class` and maybe less puzzling

**Comment by allanrenucci** [comment]
Another interesting case is when the method is `final`. It is still possible to override it with an abstract method:
```scala
trait Foo { final def foo: Int = 1 }

trait Test extends Foo { def foo: Int } // OK
trait Test extends Foo { override def foo: Int } // OK
trait Test extends Foo { def foo: Int = 1 } // error
```
It is however not possible to use this pattern to override final method defined in `AnyRef` due to scala/bug/issues/4431.

**Comment by allanrenucci** [comment]
Should we simplify this and make it less puzzling in Dotty?

**Comment by odersky** [comment]
I don't see any immediate action we could take here. Revisit later?
