### ISSUE TITLE
Generic signature of lambda missing method parameters

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3476]
I haven't managed to minimize it, but if you compile [scalacheck](http://github.com/dotty-staging/scalacheck) with `sbt jvm/compile` and then do `javap -p -v jvm/target/scala-0.5/classes/org/scalacheck/ArbitraryArities.class` there's something fishy:
```java
private static org.scalacheck.Gen<scala.Function1<T1, Z>> arbFunction1$$anonfun$1();
  descriptor: (Lorg/scalacheck/Arbitrary;Lorg/scalacheck/Cogen;)Lorg/scalacheck/Gen;
  // body skipped ...
  Signature: #1286                        // ()Lorg/scalacheck/Gen<Lscala/Function1<TT1;TZ;>;>;
```
The generic signature is missing the method parameters that can be seen in the descriptor. I noticed this because it crashes the [cfr decompiler](http://www.benf.org/other/cfr/).

**Comment by smarter** [comment]
This bug is not detected by `-Xverify-signature`.

**Comment by Duhemm** [comment]
Thanks for the report @smarter, I'm on it. In the meantime and in case that's blocking you, you can use `-Yno-generic-signatures` to disable generic signatures altogether.
