### ISSUE TITLE
Type binding cannot be read from TASTY

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3500]
When compiling from tasty (tests in tests/posFromTasty/)
```scala
trait Map2[K] {
  def get(k: K): K = k
  def foo: K = {
    this match {
      case that: Map2[b] => that.get(3.asInstanceOf[b])
      case that: Map2[b] => that.get(3.asInstanceOf[K])
      case _ => get(5.asInstanceOf[K])
    }
  }
}
```

When recompiling the code loaded from tasty, the references of `b` become redefinitions of `b`. There are also positions missing from.

**Comment by smarter** [comment]
This was previously discussed but not fully resolved in https://github.com/lampepfl/dotty/pull/2958

**Comment by nicolasstucki** [comment]
https://github.com/dotty-staging/dotty/tree/fix-bind-ambiguity has a first step that @DarkDimius implemented back then and some work I made on top to finish it. Unfortunately I currently a bit blocked on this one. 

@DarkDimius do you still remember this issue and do you have some useful pointers?

**Comment by nicolasstucki** [comment]
After that file is compiled, we can reproduce the issue with `dotc -tasty -classpath . Map2 -Ycheck:all`
