### ISSUE TITLE
-Yinfer-argument-types is not rejected as bad option but code using it causes the typechecker to crash

### ISSUE THREAD

**Issue by rcano** [lampepfl/dotty#3532]
Trying to compile in dotty some code that compiles fine in scalac I found this issue. Dottyc does warn about other invalid settings but not this one, and code like

 ```scala
new EventHandler[Evt] {
  override def handle(evt) = ???
}
```

causes the typechecker to crash.

**Comment by allanrenucci** [comment]
Could you give an example file that makes the typechecker crash, I cannot reproduce your issue

**Comment by rcano** [comment]
@allanrenucci here you go 

```scala
class crash extends java.util.concurrent.ThreadFactory {
  override def newThread(r) = new Thread(r)
}
```

compile with `scalacOptions ++= Seq("-Yinfer-argument-types")`

**Comment by rcano** [comment]
> However -Y settings are private settings. We should definitely fix the crash but I can't guaranty we will ever support this feature.

Naturally, I reported it because unlike other scalac options which dottyc rejected, this was not (and also a crash looks is bad).
Support for this feature would be something I'd like (obviously) since it's so good for refactoring and staying DRY.
