### ISSUE TITLE
Using identifiers starting with "res" in the REPL can lead to issues

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3536]
For example:
```scala
scala> val res0 = 1 
val res0: Int = 1
scala> res0 
1 |res0
  |^^^^
  |recursive value res0 needs type
```

Similar issues exist in the Scala 2.12.4 REPL and in Ammonite so there's probably no easy solution here :).

**Comment by dwijnand** [comment]
No easy solution?  What about using `$res`?  Or even just a mangled name of some form?  Security by obscurity, sure, but there's value in just making it harder to do the wrong thing.

**Comment by smarter** [comment]
I wouldn't want to encourage users to type identifiers with dollars in them when they want to refer to a previous line in the repl

**Comment by dwijnand** [comment]
Sorry, for some reason I thought this was about accidentally name clashing, not about referring to existing results.

**Comment by SethTisue** [comment]
as you might expect, `def res0` and `object res0` and `var res0` are also affected
