### ISSUE TITLE
NPE during type inference with HKT + type function

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#3544]
```scala
object Test {
  case class Tuple2K[F[_], G[_], A](f: F[A], g: G[A])

  val p0: Tuple2K[[X] => Int, [X] => String, Any] = Tuple2K(1, "s")
  p0 == Tuple2K(List(1), Option("s"))
}
```

**Comment by allanrenucci** [comment]
I think it is a duplicate of #3470

**Comment by nerush** [comment]
PR [3472](https://github.com/lampepfl/dotty/pull/3472) fixes this problem, but I am not sure whether that fix is the most appropriate one.

**Comment by nerush** [comment]
@olafurpg Do not you mind if I add your example to positive tests ?
