### ISSUE TITLE
Merge ZipArchive and JarArchive

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3552]
We have two implementations that abstract over archives (e.g. jar, zip). `ZipArchive` is a legacy from scalac. `JarArchive` is a new implementation based on `java.nio`.

We should replace the current `ZipArchive` by a new implementation based on `java.nio`. `JarArchive` is a good starting point.

**Comment by dwijnand** [comment]
There's a lot of tweaked behaviour in the old implementation so we should just leave things as they are until there's a real upside in switching (or a real downside in not switching).
