### ISSUE TITLE
Dead code in RefCheck for "forward reference in constructor error"

### ISSUE THREAD

**Issue by vitorsvieira** [lampepfl/dotty#3559]
Scalac issues "forward reference not allowed from self constructor invocation" while dotc issues a different message. (RefCheck:874).

With scalac:
```
class A(a: Any) {
  def this() = {
    this(b)             //forward reference not allowed from self constructor invocation
    def b = new {}
  }
}
```

With dotty:
```
Starting dotty REPL...
scala> class A(a: Any) {
           def this() = {
             this(b)
             def b = new {}
           }
         }
3 |      this(b)
  |           ^
  |           not found: b
```

Ev: https://scastie.scala-lang.org/lnrxIGq3SUCpoCXpUw3yGA

**Comment by allanrenucci** [comment]
Not really an issue since we do emit an error. Not the same error as scalac.

This seems to be dead code:
https://github.com/lampepfl/dotty/blob/7fa8a93694839b58b783128c2d8ae6098893a42f/compiler/src/dotty/tools/dotc/typer/RefChecks.scala#L874
