### ISSUE TITLE
Out of bits for phases in Periods

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#356]
We have 30 + 1 phases in Dotty
https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/Compiler.scala
And we have 5 bits for phase in period. We are out of bits.
We have such possibilities:
 - take bits from 21-ones reserved for runId
 - start merging phases
 - use Longs for Peiods.

I'd go with the last.
@odersky WDYT? If you agree on Longs I'd implement.

**Comment by odersky** [comment]
I already changed the bits to 64 in the phases (in the seriiaization
branch).

4616b65
<https://github.com/dotty-staging/dotty/commit/4616b6536436ef6af6c03a2c65c71b79873c3e9c>

Feel free to cherrypick! We can revisit the decision when we run out of the
new phases.

 - Martin

On Tue, Feb 10, 2015 at 5:49 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> We have 30 phases + 1 commented out in Dotty
>
> https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/Compiler.scala
> And we have 5 bits for phase in period. We are out of bits.
> We have such possibilities:
>
>    - take bits from 21-ones reserved for runId
>    - start merging phases
>    - use Longs for Peiods.
>
> I'd go with the last.
> @odersky <https://github.com/odersky> WDYT? If you agree on Longs I'd
> implement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/356>.
>



-- 
Martin Odersky
EPFL

**Comment by DarkDimius** [comment]
fixed in f0853873bd2a0294d9c32ec732b67172178a339e
