### ISSUE TITLE
Tuples in pattern match not completely removed by -optimise

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3595]
```
class Foo {
  def foo(xs: List[Int]): String = {
    val tup0 = new Tuple2(xs, xs)
    (xs, xs) match {
      case (Nil, _) => "bbb"
    }
  }
}
```

compiled with `-optimise` produces the following code in the backend. Note the ` case val x1: Tuple2 = ...` that should not be there, while `val tup0 = new Tuple2(xs, xs)` was completely removed.
```scala
      def foo( xs: scala.collection.immutable.List): String = 
      {
        case val x1: Tuple2 = new Tuple2(xs, xs)
        if Nil().==(xs) then "bbb" else 
          {
             def case1(): String = throw new MatchError(x1)
            case1()
          }
      }
```

**Comment by sjrd** [comment]
It's because of the `throw new MatchError(x1)` which escapes `x1` to the heap. The Scala.js optimizer has the same limitation.

**Comment by nicolasstucki** [comment]
But the tuple2 could be moved inside the match error.

**Comment by sjrd** [comment]
Yes, but it is not easy for an optimizer to prove that in the general case.
