### ISSUE TITLE
Make it easier to create Dotty sbt projects and depend on 2.12 projects

### ISSUE THREAD

**Issue by jvican** [lampepfl/dotty#3615]
The `sbt-dotty` plugin does not allow you to create a new sbt subproject and depend on another subproject that uses Scala 2.12. This makes it difficult for people that want to quickly try out Dotty (like me) with the less changes to their projects as possible.
  
The reason why it doesn't work is because of the inner behaviour of `projectDependenciesTask`, which cross versions the project dependencies with the same binary scala version than the dependent project. `sbt-dotty` could override this implementation and special case it to allow this use case.

**Comment by bishabosha** [comment]
I believe that this usecase is covered by sbt 1.4, its zero config to mix scala versions between dependencies
