### ISSUE TITLE
Dotty emits procedure syntax warning when it lacks return type in method

### ISSUE THREAD

**Issue by jvican** [lampepfl/dotty#3618]
```scala
abstract class DottyError {
  def foo(x: String)
  def bar(xs: List[String]): List[String] = xs
}
```
  
I get:
```
[warn] -- Migration Warning: /data/rw/code/scala/loop/rework/src/mai
n/scala/bloop/State.scala:25:0
[warn] 25 |  def bar(xs: List[String]): List[String] = xs
[warn]    |^
[warn]    |Procedure syntax no longer supported; `: Unit ' should be
 inserted here
```
  
Scala2 mode is enabled.

**Comment by odersky** [comment]
I think the message is accurate. In Scala-2 `def foo(x: String)` is a shorthand for `def foo(x: String): Unit`, which is one aspect of procedure syntax.

**Comment by jvican** [comment]
I thought procedure syntax was only considered when implementing the method, not defining it. Good to know this is procedure syntax too.
  
In any case, I think that the error message here is off (it points to `bar`, when it should point to `foo`). It would also help users that didn't know this was another case of procedure syntax (like me) to reword the error message in the following way: "Procedure syntax of abstract method is no longer supported: `: Unit` should be inserted here".

**Comment by allanrenucci** [comment]
The error emitted without Scala2 mode is:
```scala
-- [E018] Syntax Error: tests/allan/Test.scala:24:17 ---------------------------
24 |  def foo(x: Int)
   |                 ^
   |                 missing return type for abstract declaration
```
It should probably be a migration warning under Scala2. I agree the procedure syntax warning could be improved.
