### ISSUE TITLE
Functions params syntax is confusing

### ISSUE THREAD

**Issue by bs76** [lampepfl/dotty#3620]
It's possible to pass a tuple as function param without enclosing the tuple in parenthesis. It is confusnig.
(val dottyVersion = "0.5.0-RC1")

Example:
```
scala> List(1,2,3).foldLeft(7,8,9,10){ case (a,b) => a } 
val res1: (Int, Int, Int, Int) = (7,8,9,10)
 
```
Another example:

```
 scala> Option("abc").fold(-1,"hello",123L) 
val res5: String => (Int, String, Long) => (Int, String, Long) = Lambda$3317/21098686
```

Confusing, as `Option.fold` has signature of `fold: (ifEmpty: => B)(f: String => B): B` but it lookes like I cram up more args .

Writing:
```
Option("abc").fold(-1,{s:String => s.length}) 
val res6: String => (Int, String => Int) => (Int, String => Int) = Lambda$3318/1972520442@392dcdc3
```
is totally confusing as I made a typo instead of 
```
Option("abc").fold(-1){s:String => s.length}
val res7: Int = 3

```

**Comment by allanrenucci** [comment]
Note that this is not new to Dotty.

Your first example also compiles with scalac. Regarding the other two examples, they compile with Dotty due to [improved eta-expansion](http://dotty.epfl.ch/docs/reference/changed/eta-expansion.html). You can also make them compile with scalac:
```scala
scala> Option("abc").fold(-1,"hello",123L)  _
res0: (String => (Int, String, Long)) => (Int, String, Long) = $$Lambda$1264/598183031@4119346d

scala> Option("abc").fold(-1,{s:String => s.length}) _
res1: (String => (Int, String => Int)) => (Int, String => Int) = $$Lambda$1266/389226553@776e7dfb
```

**Comment by bs76** [comment]
Well, true to the extent that with scalac you must add underscore to make it unapplied method -- so it's intended. 

For dotty it looks confusing to me.

**Comment by bs76** [comment]
Thanks for pointing that out, I did no realize I was able to pass tuple this way as arg to a function using scalac.
