### ISSUE TITLE
The outer reference in this type test cannot be checked at run time.

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3652]
```scala
class Test {
  final case class Foo(x: Int)
}
```
When compiled with scalac a warning is emitted:
```
$ scalac -d out tests/allan/Test.scala -unchecked
tests/allan/Test.scala:2: warning: The outer reference in this type test cannot be checked at run time.
  final case class Foo(x: Int)
```
The warning is only emitted if the class is final. Dotty does not emit a warning. Is the warning legitimate? Should we also emit a warning?

**Comment by smarter** [comment]
No, we shouldn't. This warns about a bug in scalac (https://github.com/scala/bug/issues/4440) that does not exist in Dotty (https://github.com/lampepfl/dotty/issues/2156)
