### ISSUE TITLE
Implicit class naming restrictions

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3654]
The [scala documentation](https://docs.scala-lang.org/overviews/core/implicit-classes.html) imposes restrictions for naming of implicit classes:
> There may not be any method, member or object in scope with the same name as the implicit class.
```scala
object Bar
implicit class Bar(x: Int) // BAD!

val x = 5
implicit class x(y: Int) // BAD!
```
However these restrictions don't seem to be enforced, the following code snipped compiles with scalac:
```scala
class Test {
  object Bar
  implicit class Bar(x: Int) // OK
}

class Test2 {
  val x = 5
  implicit class x(y: Int) // OK
}
```
What do we want to do in Dotty? I think it is related to #2464

**Comment by odersky** [comment]
I think just being explicit about which method gets generated is enough. The spec wording seems to be too restrictive.

**Comment by dwijnand** [comment]
This looks like a fairly simple spec edit.  Volunteer?

**Comment by odersky** [comment]
It's already mentioned in https://dotty.epfl.ch/docs/reference/changed-features/implicit-resolution.html:

> The previous possibility of an implicit search failure due to shadowing (where an implicit is hidden by a nested definition) no longer applies.

**Comment by som-snytt** [comment]
The linked doc was not spec but overview, which I'll PR to tweak.

Also I'll see about moving SIPS into SPEC, not for historical purposes, but for folks comparing Scala 3 with 2, either for migration or evaluation. I know interpolation was already speckified by someone.
