### ISSUE TITLE
Rework hl interpolator

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3655]
We are currently having issues with the `hl` interpolator.

After adding syntax highlighting to `Showable`, we now sometime leaks colors in error messages (e.g. #3614). The reason is because we sometime try to syntax highlight twice (first by calling `show` and then splicing the result within the `hl` interpolator).

I propose we change the API of the `hl` interpolator as follow:
```scala
def hl(args: Showable*)(implicit ctx: Context): String
```
A user of the interpolator will now need to be explicit when splicing `String`s with the `hl` interpolator. It is a bit cumbersome, but will prevent re-coloring. We can provide helper function (or interpolator) to go from `String` to `Showable`. 

@felixmulder WDYT?

**Comment by felixmulder** [comment]
Sounds pretty good, looking forward to seeing where this will lead.

One thing that has been missing is some form of best-effort line splitting. We have the width as a compiler setting, so we should be able to reflow text. If this covers that - all the better :)

**Comment by smarter** [comment]
I think we should go further and get rid of the`hl` interpolator completely, just use `em`/`ex` which should be calling `.show` which should do the coloring when needed, and we can always have a regular `hl` method when we want to do highlighting explicitly, e.g.
```scala
em"No explicit ${hl("return")} allowed here."
```
