### ISSUE TITLE
Dotty unnecessarily wraps arrays used in place of java repeated

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#3675]
```scala
import java.nio.file._
class Test {
  def test(xs: Array[String]) = {
    val p4 = Paths.get("Hello", xs: _*)
  }
}
```
The code above is compiled by Dotty to:
```scala
public class Test {
    public void test(String[] xs) {
        Path p4 = Paths.get("Hello", (String[])Arrays$.MODULE$.seqToArray((Seq)Predef$.MODULE$.wrapRefArray((Object[])xs), String.class));
    }
}
```
And scalac:
```scala
public class Test {
    public void test(String[] xs) {
        Path p4 = Paths.get("Hello", xs);
    }
}
```

**Comment by allanrenucci** [comment]
This can be implemented as an optimisation in `ElimRepeated`.

**Comment by vitorsvieira** [comment]
Hi Allan,

I'd like to work on it.

-V

**Comment by allanrenucci** [comment]
Sure! The code you need to change is: https://github.com/lampepfl/dotty/blob/c515e7e6eb93bbfe491596c3d2cbe1672685ad60/compiler/src/dotty/tools/dotc/transform/ElimRepeated.scala#L94
If `tree` is a method call to `Predef.wrap{Ref, Int, Double...}Array`, you need to replace the call by its argument
