### ISSUE TITLE
dotc and dotr (repl) scripts leak compiler API

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3689]
When executing  `dotc` or `dotr` (as repl) the compiler is on the classpath. For example it is possible to compile:
```scala
class Foo {
  dotty.tools.FatalError("foo")
}
```

But with `sbt dotc` and `sbt repl` the behavoir is as expected, the ` dotty.tools.FatalError` is not found on the classpath.

**Comment by OlivierBlanvillain** [comment]
scalac does the same

**Comment by liufengyun** [comment]
@nicolasstucki May we close this one? If Scalac does the same, maybe it is a wanted feature.
