### ISSUE TITLE
Fix syntax highlighting for quoted expressions and types

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3699]
- [x] Add fix to VS code
- [x] Add fix to GitHub (https://github.com/github/linguist/pull/4044)

We are currently using the first kind of quote to avoid formatting issues as shown below. Currently `'` assumes that it contains a single `Char` or an encoded `Char` such as `'\n'`.

It would be good to make it an alias to allow users to copy-paste code from the documentation. I have already had this issue and the error message is not that helpful.

```scala
val expr1 = ’{ 1 + x }
val expr2 = ’{ y - 9 }
```

```scala
val expr1 = '{ 1 + x }
val expr2 = '{ y - 9 }
```

```scala
'[Int]
'[List[Int]]
```
 Screenshot:
<img width="746" alt="screen shot 2018-02-22 at 14 38 43" src="https://user-images.githubusercontent.com/3648029/36836284-385ffd48-1d39-11e8-94c2-582c2dc8bede.png">

**Comment by smarter** [comment]
According to https://github.com/github/linguist/blob/master/vendor/README.md, syntax highligthing for Scala in Github is done using https://github.com/mads-hartmann/scala.tmbundle/tree/master/Syntaxes. The grammar could be fixed there.

**Comment by smarter** [comment]
In fact, the syntax highlighting of `'` is already broken in some cases: https://github.com/mads-hartmann/scala.tmbundle/issues/59

**Comment by nicolasstucki** [comment]
For the record, the same issue exists in the IDE.

**Comment by smarter** [comment]
Yes, because the IDE syntax highlighting file is based on the one from https://github.com/mads-hartmann/scala.tmbundle/tree/master/Syntaxes :).

**Comment by nicolasstucki** [comment]
Perfect, we only need to fix one highlighter :)

**Comment by odersky** [comment]
I would say, let's do both: Fix the syntax highlighting and introduce the alias.

**Comment by nicolasstucki** [comment]
https://github.com/mads-hartmann/scala.tmbundle/pull/63 fixes the highlighting issue with the quoted symbols. We should try to enhance that fix to also fix quoted expressions and types.

**Comment by smarter** [comment]
The PR you link to has been open for 16 days with zero response. If the repo owner is unresponsive we should consider forking it and somehow making Github switch to using our version.

**Comment by nicolasstucki** [comment]
Yes, a saw that we should look at https://github.com/daltonjorge/vscode-scala and maybe fork it

**Comment by nicolasstucki** [comment]
I managed to edit that template and fix the issue.

**Comment by nicolasstucki** [comment]
I created a copy of the VS code extension [Scala (Dotty) Syntax](https://marketplace.visualstudio.com/items?itemName=nicolasstucki.scala).

<img width="209" alt="screen shot 2018-01-19 at 21 28 40 1" src="https://user-images.githubusercontent.com/3648029/35170238-c24fd3ec-fd5f-11e7-8afd-0bf288eef6fb.png">

@smarter the Dotty Language server should depend on this extension now. How do we do this?

**Comment by smarter** [comment]
The simplest thing to do would be to just inline the content of this extension in vscode-dotty and not depend on anything. However we need to check what happens if multiple extensions for Scala syntax are installed together. Do they conflict with each other in some way? If so, the best thing to do would indeed be to make a separate extension but also to get every other Scala vscode extension to depend on this one. Grep for `daltonjorge.scala` to see how vscode-dotty currently depends on this extension.

**Comment by nicolasstucki** [comment]
FInally fixed
