### ISSUE TITLE
Slight performance regressions in recent PRs

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3721]
Looking at http://dotty-bench.epfl.ch/ it looks like we've become about ~2% slower on some of the tests recently. It's hard to see due the variance but I think the following PRs are responsible for this:
- [#3634:  A symmetric meta programming framework](https://github.com/lampepfl/dotty/pull/3634) by @odersky 
- [#3575: Reduce the depth of trees generated in PatternMatcher](https://github.com/lampepfl/dotty/pull/3575) by @nicolasstucki 

I'm opening this issue because I think it would be nice to know why these PRs had a performance impact and whether this can be mitigated in some way. 2% isn't a big deal so if we can't figure it out we can just close the issue.

**Comment by odersky** [comment]
This will be fixed by #3866.
