### ISSUE TITLE
Missing error for double import renames

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3745]
`scalac` emits the following error messages but `dotc` does not.

```scala
error: Seq is renamed twice
import scala.collection.{ Seq, Seq => _ }
       ^
one error found
```

```scala
error: Seq is renamed twice
import scala.collection.{ Seq, Seq }
       ^
one error found
```

```scala
error: Seq is renamed twice
import scala.collection.{ Seq => A, Seq => B }
       ^
one error found
```

The first one should be an error because it could lead to ambiguities depending how we look at the imports. 

I am not sure if the second and third should be an error or a warning.

**Comment by odersky** [comment]
I guess they should be an error. That's easiest to specify and implement, for sure.
