### ISSUE TITLE
Changing the way how isInstanceOf[T] and asIntanceOf[T] work

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#379]
Both those calls are special cased by too many parts of compiler.(eg they remain polymorphic after Erasure)

Instead I propose to rewrite 
`x.isInstanceOf[T]`              --> `T.$companionModule.$isInstance(x)`,
`x.isInstanceOf[Array[T]]`   --> `T.$companionModule.$isArrayInstance(x, 1)`
This will allow to treat this methods in uniform maner by most of compiler, only backend will need to treat them specially(it already does this, so no disadvantage).

By using this we'll need to synthesize symbols for $isInstance and $isArrayInstance, so the only thing that we loose is 2 symbols per-class.

There's no need to synthesize those methods for anonymous classes.

**Comment by smarter** [comment]
Closing since it doesn't seem likely this will be implemented in the future, unless a very good usecase is found.
