### ISSUE TITLE
Make it possible to generate documentation for uncompilable classes like scala.Any

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3795]
https://github.com/scala/scala/tree/2.13.x/src/library-aux contains source files that cannot be compiled but from which documentation needs to be generated. This is handled by the `-doc-no-compile` of scaladoc. Dottydoc will need something similar.

**Comment by romanowski** [comment]
Scala3doc is now based on .tasty rather then sources so I think this issue is not longer valid (please reopen if I am wrong).

**Comment by bishabosha** [comment]
This issue is now replaced by https://github.com/lampepfl/dotty/issues/10899
