### ISSUE TITLE
Incorrect highlight color in REPL

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#3814]
![snapshot](https://user-images.githubusercontent.com/601530/34862314-c16771da-f7a4-11e7-8e99-9c6bc08494cf.png)

**Comment by benkobalog** [comment]
I think I found another case: ![image:](https://i.imgur.com/YqWdTEC.png)

**Comment by benkobalog** [comment]
Can I do this? I have a fix for the first case and for two other cases. (```def fn(a:Int) = 1``` and ```print("Hello");def fn = 1```)

However for the case in my comment above, I don't have a simple fix yet. One solution would be removing the colour change after "case"-es, so in "case A(a, b, c)" a, b and c would all be just white.

Also I haven't found any tests for highlighting. If there's none is there a plan to add them?

**Comment by allanrenucci** [comment]
>Can I do this?

Sure! 😃 

>Also I haven't found any tests for highlighting. If there's none is there a plan to add them?

We don't have any. It would be nice to add some, however there is no plan at the moment. It is low priority.

**Comment by benkobalog** [comment]
I submitted a PR, but currently it only solves the original case and the type coloring after ':' characters. 
For the case in my first comment here, it would be easy to remove the cyan coloring, but I don't know how to fix it properly yet. Should I leave the bug in or remove the coloring or try to fix it?
