### ISSUE TITLE
ImplicitConverter and implicit def

### ISSUE THREAD

**Issue by drdozer** [lampepfl/dotty#3831]
In Dotty, what's the trick for building chains of implicit conversions? The `ImplicitConverter[A, B]` specialisation of Function1[A, B] is great, but are `implicit def foo(a: A): B` automatically boxed into instances of `ImplicitConverter`, or are there extra steps?

**Comment by odersky** [comment]
Yes, since `ImplicitConverter` a SAM method, closures are automatically converted to it.
