### ISSUE TITLE
Dottydoc crashes when upgrading liqp to 0.7.2

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#3859]
Dottydoc currently uses liqp 0.6.7, when upgrading to 0.7.2 (see branch https://github.com/dotty-staging/dotty/commits/upgrade/liqp-0.7.2) and running `genDocs` we get:
```scala
java.lang.ArrayIndexOutOfBoundsException: 1
        at scala.collection.mutable.WrappedArray$ofRef.apply(WrappedArray.scala:130)
        at dotty.tools.dottydoc.staticsite.tags$RenderTitle.render(tags.scala:189)
        at dotty.tools.dottydoc.staticsite.tags$RenderTitle.render(tags.scala:166)
        at liqp.nodes.TagNode.render(TagNode.java:32)
        at liqp.tags.For.renderArray(For.java:112)
        at liqp.tags.For.render(For.java:56)
        at liqp.nodes.TagNode.render(TagNode.java:32)
        at liqp.nodes.BlockNode.render(BlockNode.java:38)
        at liqp.Template$1.call(Template.java:266)
        ... 5 more
```
The crash happens here: https://github.com/lampepfl/dotty/blob/517ba8cbd7c4c0cd5058a4dd1bdfce2c0fe441cf/doc-tool/src/dotty/tools/dottydoc/staticsite/tags.scala#L189 maybe @felixmulder can give some context on what this does? :)

**Comment by felixmulder** [comment]
Looks like functionality to implement a custom tag like:

~~~
{ renderTitle | "someArg" }
~~~

**Comment by felixmulder** [comment]
Yes, the syntax in my previous response was wrong - but the sentiment the same. It's using liqp to add some custom tags to the markup language.

It tries to get the arguments from "nodes" but I guess there has been some changes to liqp

**Comment by felixmulder** [comment]
I'd say most likely someone is calling the tag with the wrong number of args - or liqp changed in some unexpected way

**Comment by smarter** [comment]
Apparently all params are parsed as one string now: https://github.com/bkiers/Liqp/pull/46, I'll try to make a PR.

**Comment by felixmulder** [comment]
Interesting, I wonder what prompted that changerge.

**Comment by smarter** [comment]
Apparently it's to confirm with the spec of Liquid.

**Comment by smarter** [comment]
Alright, I give up for now, in 0.7.2 when we want to handle `{% renderRef member.alias %}`, we get just the string `"member.alias"` and there's no way to automatically parse that, so you have to split on `"."`, lookup `"member"` in the context, then `"alias"` in the resulting map, that's super annoying to do and probably not even correct if the grammar of the language allows more complicated things. We should open an issue against liqp I think.

**Comment by bkiers** [comment]
> Interesting, I wonder what prompted that changerge.
> ...
> Apparently it's to conform with the spec of Liquid.

True: it's the specs of Liquid that say all parameters to tags are to be treated as a single string. Me implementing them as expressions was wrong.

> ... and there's no way to automatically parse that

No need to parse it; evaluating is all that's needed. I posted a possible workaround how to evaluate the string/expression `member.alias`: https://github.com/bkiers/Liqp/issues/70

**Comment by nicolasstucki** [comment]
@abgruszecki is this issue still relevant?

**Comment by smarter** [comment]
The new scaladoc still uses liqp and it's still an old version so I'd say yes: https://github.com/lampepfl/dotty/blob/3d85473ee9706b00882f2a1419575b8f0d88487e/project/Build.scala#L1486 /cc @romanowski
