### ISSUE TITLE
Spec followup to #3747

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#3861]
#3747 changes pattern matching to allow "Pattern Sequences" to be used on `unapply` (where `unapplySeq` was previously required). This needs a spec change, [this page](http://dotty.epfl.ch/docs/reference/changed/vararg-patterns.html) would probably be a good place to do that.

**Comment by odersky** [comment]
I have too much on my plate. I need someone else to take over the pattern matching chapter. This could be a good thing to start with!

**Comment by Blaisorblade** [comment]
Adding to my queue — with no time estimate yet.

**Comment by odersky** [comment]
We should not let things linger like that. The more open PRs we have the more everyone's productivity suffers.
