### ISSUE TITLE
repl crashes when using quotation syntax 

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#3875]
When I used the Quotation syntax in repl, it crashed:
![image](https://user-images.githubusercontent.com/20694662/35178682-53a4d240-fdc7-11e7-9a2d-5d8227454c12.png)

**Comment by newca12** [comment]
FYI in a fresh repl without any import, just enter '( and then press TAB lead to the same stacktrace.

**Comment by nicolasstucki** [comment]
Same for `'{` and `'[`.
