### ISSUE TITLE
inline val class parameter in backend

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3900]
```scala
class Foo(inline val i: Int)
```

emits the following error
```
Concrete method has no definition: Concrete method has no definition: DefDef(i,List(),List(List()),TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Int)],EmptyTree)
one error found
```

**Comment by smarter** [comment]
I don't think this should compile at all.

**Comment by nicolasstucki** [comment]
I assume that `inline` should never be used in a class parameter as we cannot ensure that accesses to those field are inlined. @odersky is that the correct semantics.

**Comment by allanrenucci** [comment]
Should `class Foo(inline i: Int)` be allowed?

**Comment by biboudis** [comment]
I think not. It is not allowed [either](https://github.com/lampepfl/dotty/pull/3915/files#diff-58bd3c1c2442adffcb620cf0744579fcL10). WDYT?

**Comment by nicolasstucki** [comment]
They should not. There is no way to inline the value of `i` in any of the references of `i`.

**Comment by allanrenucci** [comment]
Should `inline` on secondary constructor parameters be rejected too?

**Comment by nicolasstucki** [comment]
Yes, unless the secondary constructor is inlinable. Can it?

**Comment by allanrenucci** [comment]
I don't see why a secondary constructor could not be inlined, although I imagine it is not the same mechanism as inlining a normal function call:
```scala
class Foo() {
  def this(x: Int) = this()
}

new Foo(1) // inlined to new Foo() ?
```

**Comment by smarter** [comment]
I don't think we should support inlining secondary constructors. It's going to be complicated to implement and offers no value.
