### ISSUE TITLE
Macro with Unit type splicing non Unit fails with `splice outside quotes`

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#3912]
```
import scala.quoted._
object Macros {
  inline def foo(): Unit = ~impl()
  def impl(): Expr[Int] = '(1)
}
```
```
import scala.quoted._
import Macros._
class Test {
  val a: Unit = foo()
}
```

fails with 
```
5 |    ~impl()
  |    ^^^^^^^
  |    splice outside quotes
```

because `inline def foo(): Unit = ~impl()` is transformed to 
`inline def foo(): Unit = { ~impl(); () }`, which is correct.

We need a better error message for this.

**Comment by nicolasstucki** [comment]
This should probably be done in `ReifyQuotes`.

**Comment by odersky** [comment]
Why is this not expanded to a macro?

**Comment by nicolasstucki** [comment]
We could expand it to a macro. We would need to not insert the explicit `()` or to recognise that shape of tree as a macro body.

**Comment by biboudis** [comment]
Where is it best to transform the shape of the tree? In `transform` of `ReifyQuotes` right ([link](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala#L315-L339))?

**Comment by nicolasstucki** [comment]
Not sure, maybe it should be before. We should probably have it marked as a macro before that to make it take [this branch](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala#L331)

**Comment by nicolasstucki** [comment]
The following macro has a similar issue
```
import scala.quoted._
object Macros {
  inline def foo(): Int = { ~impl() }
  def impl(): Expr[Int] = '(1)
}
```

In both cases the code that is splices is found in a block as statement or expression position. We probably handle these as part of the [Inlined branch](https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/ReifyQuotes.scala#L324-L328) conditions.
