### ISSUE TITLE
Improvements to the IntelliJ IDEA getting started guide

### ISSUE THREAD

**Issue by expz** [lampepfl/dotty#3933]
I would like to create a pull request to update the IDEA getting started guide (https://github.com/lampepfl/dotty/blob/master/docs/docs/contributing/intellij-idea.md), so this is an associated issue.

Current weaknesses:

* The last step of setup seems out of date. Using the newest version of the community version of IDEA, it does not ask which modules to load. You have to manually unload unnecessary ones after the project loads.
* It is confused at one point. At the beginning of the running section, it says it is presenting an sbt command and instead there is a shell command which incidentally will not run as written. Then it neglects how to run dotty using a shell command (granted, it's easy enough to guess it's in the bin directory).
* The ending is vague. It does not specify that the `dotc` command has to be run from within `sbt` to work, and for me who had not used remote debugging, it took googling and experimenting to understand.
* There are grammatical errors.

**Comment by biboudis** [comment]
Excellent points @expz!
