### ISSUE TITLE
Frontpage minor issues

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#3952]
Getting started with Dotty again, the homepage looks pretty cool and instructions mostly work, with two small exceptions:

- The link to “Dotty Example Project” doesn’t work, unlike other links, under either OS X Chrome or Safari on iPad. Clicking on “Inspect” leads me to the HTML for the downward arrow (which actually goes upward for some reason).
- (Even more minor) there’s no link to edit the webpage, unlike on the docs folder. @smarter mentioned on Gitter it’s unclear where to add that.

Ticket filed after some discussion on Gitter around https://gitter.im/lampepfl/dotty?at=5a71ede136de78850cd37253

**Comment by smarter** [comment]
> The link to “Dotty Example Project” doesn’t work, unlike other links, under either OS X Chrome or Safari on iPad. Clicking on “Inspect” leads me to the HTML for the downward arrow (which actually goes upward for some reason).

I think we should just remove the arrows. They're not very useful and cause issues like this.

**Comment by Blaisorblade** [comment]
👍 Also, if somebody really wanted the feature, there might be simpler designs to achieve it, since apparently website maintenance falls on Dotty hackers?
