### ISSUE TITLE
ElimByName creates Selects that have NoDenotation after copying

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#396]
```
def foo(c: => Int): Int = c
```

After `ElimByName` rhs will by `c.apply()` with the denotation to `Select` node assigned by hand.  But `c` is still an `ExprType`, not a subtype of `Funtion0`. If tree gets duplicated, changing the `c` symbol, the `Select` node will have no denotation, as `c` doesn't have a member `apply`.
@AlexSikia that's the error we've been seeing. Try to move your phase before the whole `ElimByName` group.

**Comment by AlexSikia** [comment]
@DarkDimius That seems to do the trick - it solves the `t6891.scala` test in the `pos_tailcall` suite at least.

**Comment by odersky** [comment]
Closing because there is a workaround
