### ISSUE TITLE
Can't define an enum with higher kinded types

### ISSUE THREAD

**Issue by halcat0x15a** [lampepfl/dotty#3976]
I get an error in Dotty 0.6.0-RC1.

```scala
scala> enum class Hoge[F[_]]
1 |enum class Hoge[F[_]]
  |^
  |Type argument F$1 has not the same kind as its bound
```

I guessed that it failed to derive an Eq instance.

**Comment by halcat0x15a** [comment]
I think that will be fixed if #3970 is implemented.

**Comment by smarter** [comment]
The error comes from an incorrectly generated implicit instance of `Eq`:
```scala
  final module class Hoge$() extends Object() { this: Hoge.type => 
    implicit def eqInstance[F$1 <: [_$1] => Any, F$2 <: [_$1] => Any](
      implicit evidence$1: Eq[F$1, F$2]
    ): Eq[Hoge[F$1], Hoge[F$2]] = Eq
  }
```

`Eq[F$1, F$2]` does not typecheck since `F$1` and `F$2` are type constructors. Maybe replacing this by `Eq[F$1[_], F$2[_]]` is good enough, not sure.

**Comment by halcat0x15a** [comment]
@odersky did a great works!
Should I close this issue?
