### ISSUE TITLE
IDE: Find references should work across projects

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#3980]
Example: In `InteractiveDriver.scala`, doing a Find All References query on the definition of `allTrees` does not bring up the usages in DottyLanguageServer. That's because `DottyLanguageServer` is defined in a different project than `InteractiveDriver`.

We should also find references in external projects. At least in projects that have currently open buffers in the IDE. Finding references in ALL projects begs the question how to find these projects
in the first place. And then there's the question how to make this efficient. That's probably where SemanticDB can help. But for the moment we should at least find references in projects that are currently open.

**Comment by Duhemm** [comment]
Fixed in #5209
