### ISSUE TITLE
Overloading resolution could take advantage of union types

### ISSUE THREAD

**Issue by propensive** [lampepfl/dotty#3992]
The following does not compile on Dotty 0.5.0-RC1:
```scala
def foo(i: Int) = 1
def foo(i: String) = 2
val x: Int | String
foo(x)
```
Whilst this is not surprising, it seems like a missed opportunity when a lot of (particularly Java) APIs exist with a single method name overloaded for several parameter types. Scala wrappers around such APIs tend to involve the same line of code copy/pasted several times, with minimal differences between them.

In the event that a union type (originating from a pattern match, or a resolved implicit) does not exactly match any of the expected types of an overloaded method, it would be nice if the compiler could automatically deconstruct the union type and reattempt the application on each of the parts of the union, and succeed if every part can be resolved.

**Comment by smarter** [comment]
Honestly, this seems pretty far-fetched. We've already decided to not treat method dispatch specially for union types (i.e.,  `val x: A | B; x.foo` will only succeed if `foo` is a member of the common supertype of `A` and `B`, it won't work if both `A` and `B` define `foo` separately). This is similar but even more peculiar. Not to mention that overloading is also already a beast to typecheck, I don't really want to add backtrackable tree generation to the mix.

**Comment by propensive** [comment]
It just seemed like union types do seem to be lacking a few good use cases, and this could be one.

I think that rather than a peculiar mismatch between different concepts, overloaded unary methods literally *are* methods which take a union type as a parameter, albeit expressed in a different way. And they represent by far the broadest set of examples of existing uses of union types in Java/Scala at the moment...

Anyway, I'm no fan of overloading in general, and even if there were a nice solution for unary methods, it couldn't extend to other arities, so I'll close.
