### ISSUE TITLE
Disallow type Null  in a type pattern or isInstanceOf test

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4004]
Should we disallow type `Null`  in a type pattern or `isInstanceOf` test like scalac does to avoid surprising behaviors?

Dotty:
```scala
scala> null.isInstanceOf[Null]
val res0: Boolean = false
```
Scalac:
```scala
scala> null.isInstanceOf[Null]
<console>:12: error: type Null cannot be used in a type pattern or isInstanceOf test
       null.isInstanceOf[Null]
                        ^
```

**Comment by smarter** [comment]
I would say yes, same with Singleton.

**Comment by nicolasstucki** [comment]
Maybe we should translate `null.isInstanceOf[Null]` into `null eq null`. Like we currently do with singleton types, we translate `val o = ""; "".isInstanceOf[o.type]` becomes `val o = ""; "" eq o`.

**Comment by smarter** [comment]
But what's the usecase? :)

**Comment by nicolasstucki** [comment]
This can only be done if the callee is a subtype of `AnyRef`. Otherwise, it should be disallowed or `0.isInstanceOf[Null]` might say true.

**Comment by nicolasstucki** [comment]
The main point is that we should at least not do it for singletons. The one with `Null` might be useful in cases where an `isInstanceOf` check is inserted by the compiler for some reason (not sure if it ever happens).

**Comment by Blaisorblade** [comment]
> The one with Null might be useful in cases where an isInstanceOf check is inserted by the compiler for some reason (not sure if it ever happens).

So somebody could just forbid isInstanceOf[Null] and see if something breaks. Volunteers? @liufengyun maybe in your PR when you have time?

Pattern matching with singleton types (which is equivalent to `isInstanceOf`, IIUC) is useful (at least a bit) with GADTs:
```scala
def f[T, U](t: Foo[T], u: Foo[U]) =
  t match { case _: u.type => // Here T and U are equal
  }
```
An actual use case is in ECOOP'07 Burak Emir's paper on case classes, and that code still works today in Scala (though IIRC not yet in Dotty).

**Comment by odersky** [comment]
I also think we should try to disallow `asInstanceOf[Null]`

**Comment by odersky** [comment]
One then also needs to check that
```scala
e match
  case x: Null => ...
```
is rejected.

**Comment by bishabosha** [comment]
Scala 2.13.6 also rejects `isInstanceOf[Nothing]`
