### ISSUE TITLE
Command-line options help is incomplete

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4005]
The option help text doesn't document correctly special options
```
$ dotc -help
...
-color             Colored output
...
$ ./bin/dotc -color /Users/pgiarrusso/git/dotty-example-project/src/main/scala/TestGADT.scala
missing argument for option -color
  dotc -help  gives more information
```

The culprit is https://github.com/lampepfl/dotty/blob/36cc65ad12ce809f7a9cd08d6ba3ba5432b75eed/compiler/src/dotty/tools/dotc/config/CompilerCommand.scala#L74

That code just prints name and description of the `Setting`, ignoring choices, default and other fields.

**Comment by ioganegambaputifonguser** [comment]
https://github.com/lampepfl/dotty/pull/4018
