### ISSUE TITLE
Parenthesis highlighting broken in IDE

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#4011]
Some weeks ago we seemed to have disabled highlighting of parentheses (i.e. highlight the matching parenthesis or brace when cursor is on the other one). 

I thought it might have been a global setting, but now find that this works fine when I am not in scala-mode. So I assume it's the changes to Scala syntax highlighting that broke it.

**Comment by nicolasstucki** [comment]
Fixed on https://marketplace.visualstudio.com/items?itemName=nicolasstucki.scala

**Comment by nicolasstucki** [comment]
This issue was fixed by the PRs above.
