### ISSUE TITLE
Finish "core data structures" documentation, review internal docs

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4015]
@smarter notes in #3405 that 

> There's also a bunch of weird/outdated things in https://github.com/lampepfl/dotty/tree/master/docs/docs/internals that should just be removed since they just add confusion.

[Core data structures](https://github.com/lampepfl/dotty/blob/master/docs/docs/internals/core-data-structures.md) qualifies; git blame points to @odersky in 2016. I'd prefer to read the updated version. If there's no chance, let's maybe drop it soon?

**Comment by odersky** [comment]
I think it would be excellent if someone else went through this and updated the description. I have already way too much on my plate. I believe it would be very instructive to make a report of what has changed since then and summarize that in a writeup.

**Comment by odersky** [comment]
I had a look at it, I think we should just drop core-data-structures. There's nothing that's still valuable to know today.

**Comment by Blaisorblade** [comment]
Will do!
