### ISSUE TITLE
Collections: counting

### ISSUE THREAD

**Issue by k0ala** [lampepfl/dotty#4021]
I often run up against issues of the following kind. I have a large collection `xs`, and I would like to do one of the following:

1) for each distinct value, get a count of how often it appears in `xs`.
2) more generally, get a count of how often each value `f(x)` appears in `xs.map(f)` (point 1 is a special case with `f` == `identity`).
3) obtain the subset of values in `xs` that occur more than once.
4) more generally, obtain the subset of `xs` for which `f(x)` occurs more than once (point 3 is a special case with `f` == `identity`).

I know that these can all be achieved using `groupBy`, however that seems quite wasteful, because it can potentially build as many new collections as there are elements in `xs`... and counting seems like a common enough use case to warrant some specific methods.

I was thinking of adding something like the following to collection `Coll[A]`:
```
def countByValue: Map[A, Int]             // point 1
def countBy[B](f: A => B): Map[B, Int]    // point 2
def duplicates: Coll[A]                   // point 3
def duplicatesBy[B](f: A => B): Coll[A]   // point 4
```

Is there any interest in this, and if yes, any pointers on where to begin? Presumably it could be written in terms of `aggregate`, but that may be inefficient?

Apache Spark has some functions like this on its RDD collections, see e.g. [countByValue](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.rdd.RDD@countByValue()(implicitord:Ordering[T]):scala.collection.Map[T,Long]) or [countByKey](https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.rdd.PairRDDFunctions@countByKey():scala.collection.Map[K,Long]). There are also some useful approximate algorithms in addition to exact counts.

**Comment by allanrenucci** [comment]
Hi @k0ala! Dotty is using the Scala standard collections. You can open an issue at https://github.com/scala/collection-strawman/ to discuss new operations on collections.
