### ISSUE TITLE
Eta-expansion of structural types under Scala2 mode

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4026]
Under Scala2 mode this does not compile:
```scala
import scala.reflect.Selectable.reflectiveSelectable

class Test {
  def test(x: { def get(): Int }): Int = x.get
                                      // ^
                                      // found:    () => Int
                                      // required: Int
}
```
This is inconsistent with non structural types and a breaking change with respect to Scala2
```scala
def foo(): Int = 1
val x: Int = foo // OK under Scala2 mode
```

**Comment by allanrenucci** [comment]
We will not fix this in Dotty.

Ping @olafurpg.  It would be nice if Scalafix could add parenthesis to to nullary method calls.

**Comment by olafurpg** [comment]
@allanrenucci I made some progress a while ago (https://github.com/scalacenter/scalafix/issues/204) but I'm currently blocked by the fact that scalac signatures don't distinguish between non-nullary methods and nullary methods that override non-nullary methods (includes any 0-arg java method). 

```scala
trait A {
  def overridesNonNullary(): String
}
object B extends A {
  override def overridesNonNullary: String = "" // inherits non-nullary signature
  def isNonNullary() = ???
}
```

According to the SLS:

> A special rule concerns parameterless methods. If a parameterless method defined as def f: T = ... or def f = ... overrides a method of type ()T′ which has an empty parameter list, then f is also assumed to have an empty parameter list.

See https://github.com/scala/bug/issues/10480#issuecomment-325091265 for discussion. As a workaround the rewrite should maybe skip methods that override non-nullary methods.

**Comment by allanrenucci** [comment]
Dotty will emit a warning under Scala2 mode for nullary methods that inherit non-nullary methods. So I guess that's fine, you could have another rewrite based on the warning emitted by dotc.

However can you rewrite the call site when the receiver type is a structural type (as shown in the example above)?

**Comment by olafurpg** [comment]
> However can you rewrite the call site when the receiver type is a structural type (as shown in the example above)?

That should be doable, noted.
