### ISSUE TITLE
Breaking changes between Scalac and Dotty -language:Scala2

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4027]
This is a meta issue aimed at listing all the breaking changes there are between Scalac and Dotty under Scala2 mode. This should make migration easier.
- Structural types need an [explicit import](http://dotty.epfl.ch/docs/reference/changed/structural-types.html) in Dotty
```scala
val o: { def foo: Int } = new Object { def foo = 1 } 
o.foo // Error in Dotty

import scala.reflect.Selectable.reflectiveSelectable
o.foo // OK
```

- Scalac infers structural types
```scala
val o = new Object { def foo = 1 } 
o.foo // OK in Scalac

import scala.reflect.Selectable.reflectiveSelectable
o.foo // Error in Dotty
```

- Overridden members without explicit type inherit type from parent in Dotty
```scala
class A { def opt: Option[Int] = None }
class B extends A { override def opt = Some(1) }
val some: Some[Int] = (new B).opt // Error in Dotty
```
- See #4026
- Macros are not supported in Dotty
- Introduced new keyword: `unused`, `enum`, `opaque`, `augment`

**Comment by Blaisorblade** [comment]
New changes under discussion: https://github.com/lampepfl/dotty/pull/4490#discussion_r187173022 (lest I forget to add it here later).

**Comment by OlivierBlanvillain** [comment]
Merge into https://github.com/lampepfl/dotty/wiki/Known-incompatibilities-with-scalac
