### ISSUE TITLE
Good old unsoundness, CCE

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#4031]
http://io.livecode.ch/learn/namin/unsound/scala

```scala
object App {
  trait A { type L >: Any}
  def upcast(a: A, x: Any): a.L = x
  lazy val p: A { type L <: Nothing } = p
  def coerce(x: Any): Int = upcast(p, x)

  def main(args: Array[String]): Unit = {
    println(coerce("Uh oh!"))
  }
}
```
`lazy` above is not necessary

```scala
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
	at App$.coerce(HelloWorld.scala:5)
	at App$.main(HelloWorld.scala:8)
	at App.main(HelloWorld.scala)
```

**Comment by odersky** [comment]
I believe the lazy val

    lazy val p: A { type L <: Nothing } = p

should not be realizable. We miss a check here.

**Comment by Blaisorblade** [comment]
Was only marked as “fixed” by mistake!

**Comment by Blaisorblade** [comment]
Been puzzling again over this, and had to (re)discover that `lazy val p: A { type L <: Nothing } = p` will initialize `p` to `null` as discussed in #1856.

**Comment by odersky** [comment]
This was all a red herring I am afraid. You *need* null. The code as given produces an infinite loop (for `p`), not a class cast exception.  So do the variants developed in #4036.

So since you need `null` to produce the error the right answer is "wait for null-safety in the type system".

**Comment by odersky** [comment]
Revisit once we have null-safety. Then it will make a good test case, with the change:

    lazy val p: A { type L <: Nothing } = null

**Comment by odersky** [comment]
[Props to Adriaan for putting me on the right track here]
