### ISSUE TITLE
Regression in Community Build: ScalaPB

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4033]
https://travis-ci.org/lampepfl/dotty-community-build/jobs/344732706

#3342 seems to be the cause of the regression

**Comment by nicolasstucki** [comment]
Fixed with #4145

**Comment by nicolasstucki** [comment]
In that PR I stop forcing types on scala2 classes. One of which contained a macro in ScalaPB.

**Comment by liufengyun** [comment]
So we can enable ScalaPB benchmarks again? I'll do it now.

**Comment by nicolasstucki** [comment]
We should be able to re-enable them
