### ISSUE TITLE
launchIDE doesn't work in the example project

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4055]
In dotty-example-project (using Dotty 0.6.0-RC1), `launchIDE` starts VSCode and returns quickly to SBT, while on Dotty with current master SBT gets stuck and one must start a new session. Since sbt-dotty didn't change since 0.6.0-RC1, maybe this bug depends on the project and isn't a regression.

**Comment by smarter** [comment]
No, this is intentional. In the Dotty project launchIDE is handled specially. We use the sbt output to display the language server output to make debugging more convenient, whereas in user projects the output goes to the logs inside vscode

**Comment by Blaisorblade** [comment]
Thanks, sorry for the noise!

In the end, the main actual issue I had (and why `launchIDE` wasn't working well in the example project for me) was that I tried using `launchIDE` on both dotty and other projects at the same time, and *that* doesn't work (both apparently, and according to Nicholas).
