### ISSUE TITLE
dotty REPL shows the Array hexcode instead of actual elements

### ISSUE THREAD

**Issue by prayagupd** [lampepfl/dotty#4067]
Minor issue that dotty REPL shows "hex representation of hashcode" of the array instead of showing elements in it.

```scala
scala> val data = Array(1, 3, 5, 7, 11).map(x => x * x) 
val data: Array[Int] = [I@6eda012b
scala> data.toString 
val res11: String = "[I@6eda012b"
```

_while "scalac REPL" shows the elements which I think is expected in REPL._

```scala
scala> val data = Array(1, 3, 5, 7, 11).map(x => x * x)
data: Array[Int] = Array(1, 9, 25, 49, 121)

scala> data.toString
res11: String = [I@3071d086
```

`Seq` works fine in dotty REPL.

```scala
scala> Seq(1, 3, 5, 7, 11).map(x => x * x) 
val res12: Seq[Int] = List(1, 9, 25, 49, 121)
```

Solution probably is to use `java.lang.Arrays.toString` or different toString.

```scala
scala> java.util.Arrays.toString(Array(1, 3, 5, 7, 11)) 
val res19: String = "[1, 3, 5, 7, 11]"
```

environment

```bash
$ dotc -version
Dotty compiler version 0.6.0-RC1 -- Copyright 2002-2018, LAMP/EPFL

$ dotr -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```

**Comment by allanrenucci** [comment]
A simple solution would be to add an implicit `Show` instance for `Array` in https://github.com/lampepfl/dotty/blob/master/library/src/dotty/Show.scala

**Comment by jendrikw** [comment]
I want to try this in the next few days.

**Comment by bhop** [comment]
Hi @jendrikw. 

Sorry but I missed your update. I hope you did not start work on it yet. 
Cheers!
