### ISSUE TITLE
Dependent function types do not play well with type inference

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#4130]
```scala
object Test {
  val f: (x: Int) => Int = x => x

  def id[A, B](x: (y: A) => B) = x

  id(f)
    // -- [E007] Type Mismatch Error: try/dep.scala:6:5 -------------------------------
    // 6 |  id(f)
    //   |     ^
    //   |     found:    (x: Int) => Int(Test.f)
    //   |     required: (y: Nothing) => Any
    //   |     

  id[Int, Int](f) // OK
}
```

**Comment by b-studios** [comment]
@smarter Here is another example that gives "unspecified error" in the latest nightly (0.11.0-bin-20181119-0a1aed2-NIGHTLY)

```scala
trait A
  
def foo[E](f: (a: A) => (a.type, E)): E = {
  val a = new A {}
  f(a)._2
}

foo { a => (a, ()) }
```

**Comment by b-studios** [comment]
@smarter I tried to understand the problem a bit better and learnt the following things:
- the unspecified error is raised [here in Typer](https://github.com/lampepfl/dotty/blob/92bbb6ef3ae5ef36caf38db2a3128486c935640b/compiler/src/dotty/tools/dotc/typer/Typer.scala#L1218)
- The check has been introduced [long before](https://github.com/lampepfl/dotty/commit/775b2a1857290f5e83036148dbbfcdc3a29a12d2) path-dependent function types existed
- [checking](https://github.com/lampepfl/dotty/blob/92bbb6ef3ae5ef36caf38db2a3128486c935640b/compiler/src/dotty/tools/dotc/typer/Inferencing.scala#L31-L36) whether the following tree is fully defined fails:
    ```scala
    AppliedType(TypeRef(...,class Tuple2),List(TermRef(NoPrefix,val a), TypeVar(TypeParamRef(E))))
    ```
    However, this is not a problem when replacing `a.type` in `(a: A) => (a.type, E)` by `A` to yield `(a: A) => (A, E)`.

That said, I guess the check might need to be improved, but I am not in the position to do that right now. :(
