### ISSUE TITLE
Meta tests should test timeout

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4140]
@allanrenucci says dotty.tools.vulpix.VulpixMetaTests should test the Vulpix timeout feature by trying to run an infinite loop, but that doesn't currently happen.

**Comment by OlivierBlanvillain** [comment]
I don't see what this would need to be a meta test, we already have [dotty.tools.vulpix.VulpixUnitTests.runTimeout](https://github.com/lampepfl/dotty/blob/b44adf721f2537211373cf69f2e673a6ff1d3ac6/compiler/test/dotty/tools/vulpix/VulpixUnitTests.scala#L89-L100) to ensure that timing out tests fail like any other failing test...
