### ISSUE TITLE
No ClassTag available for Nothing

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4163]
```scala
class Test {
  Array()
}
```
```
-- Error: tests/allan/Test.scala:2:9 -------------------------------------------
2 |  Array()
  |         ^
  |         No ClassTag available for Nothing
```
It compiles with Scalac

**Comment by smarter** [comment]
ClassTag[Nothing] can be used manually if you really want it but is not found by implicit search anymore because it's unsound, see https://github.com/lampepfl/dotty/issues/1730
