### ISSUE TITLE
Member defined in REPL should shadow previously imported member

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4230]
Below an (un)reproducible transcript of the REPL not handling shadowing correctly. After both importing and defining `f`, only the imported one is in scope.

```scala
> repl
[...]
scala> object A { def f = 1 }
// defined object A
scala> import A._
scala> def f = "hi"
def f: String
scala> f
val res0: Int = 1
```

**Comment by smarter** [comment]
Can you turn this into a simple, minimal example?

**Comment by Blaisorblade** [comment]
```scala
> repl
[...]
scala> object A {def f = 1}
// defined object A
scala> import A._
scala> def f = "hi"
def f: String
scala> f
val res0: Int = 1
```

**Comment by Blaisorblade** [comment]
@smarter can I replace the original example (and clean this issue up)?

**Comment by smarter** [comment]
Yes.

**Comment by allanrenucci** [comment]
This has to do with the way we handle imports. When compiling an expression, we first import the previous wrapper objects and then the user defined imports. So currently, a definition imported with an import will always take precedence over one defined in a previous run
