### ISSUE TITLE
Classes can't have an unfulfilled self type with unimplemented methods

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4252]
```scala
trait Bar { def bar: Int }
class Foo { self : Bar => }
```
```scala
2 |class Foo { self : Bar => }
  |      ^
  |   class Foo needs to be abstract, since def bar: => Int is not defined 
one error found
```
It is allowed in Scalac

**Comment by Blaisorblade** [comment]
Indeed, instantiating such classes is forbidden later by the [spec](https://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#instance-creation-expressions) on `new c` where `c` is a constructor of class `T`:

>  Then `T` must denote a (a type instance of) a non-abstract subclass of `scala.AnyRef`. Furthermore, the concrete self type of the expression must conform to the self type of the class denoted by `T`.

```scala
scala> trait Bar { def bar: Int }
defined trait Bar

scala> class Foo { self : Bar => }
defined class Foo

scala> new Foo
<console>:13: error: class Foo cannot be instantiated because it does not conform to its self-type Foo with Bar
       new Foo
       ^
```

Not that I see the point of this behavior, but I'd default to following Scalac.

**Comment by allanrenucci** [comment]
But you can instantiate it as an anonymous class or extend it:
```scala
scala> new Foo with Bar { def bar: Int = 1 }
res0: Foo with Bar = $anon$1@6002e944

scala> class Bat extends Foo with Bar { def bar: Int = 1 }
defined class Bat

scala> new Bat
res1: Bat = Bat@5dcf0772
```
So there is a real use case

**Comment by Blaisorblade** [comment]
> So there is a real use case

To clarify: I mean, one could just require that the class is marked abstract and support the same use cases.

**Comment by Blaisorblade** [comment]
Gitter isn't sure either, but it seems this might have been discussed and left as-is: https://gitter.im/scala/contributors?at=5ac65cac27c509a774df5374

**Comment by smarter** [comment]
After discussion in the meeting, we decided to support the Scala 2 behavior under -language:Scala2, and keep the current behavior otherwise.

**Comment by griggt** [comment]
FWIW, this compiles without error since #8332, both with and without -language:Scala2.
