### ISSUE TITLE
Eta-expansion doesn't insert default arguments

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4275]
This fails in Scalac and Dotty, but seems a bit silly, especially because `f _` doesn't get defaults but `f(_)` does:
```scala
scala> def f(a: Int, b: Boolean = true): Int = a
f: (a: Int, b: Boolean)Int

scala> f: (Int => Int)
<console>:13: error: type mismatch;
 found   : (Int, Boolean) => Int
 required: Int => Int
       f: (Int => Int)
       ^
cala> (f _): (Int => Int)
1 |(f _): (Int => Int)
  |  ^
  |  found:    (Int, Boolean) => Int
  |  required: Int => Int
  |
scala> (f(_)): (Int => Int)
val res0: Int => Int = Lambda$1550/925936450@537c8c7e
```

This came up in https://github.com/lampepfl/dotty/pull/4276/commits/23464fd64e3a4d1e3c2c2635c289543690d70a5e#diff-b59d25461c7203c18a90d6373be182cdL541

**Comment by SethTisue** [comment]
fwiw, I don't find the existing behavior clearly wrong. `f(_)` is an application, `f _` is not, so I don't find it especially surprising that default arguments kick in for the former but not the latter.

**Comment by Blaisorblade** [comment]
@SethTisue Are you suggesting to reclassify this as language enhancement? That it warrants a SIP? That might all be.
Or are you suggesting the behavior shouldn't be modified? Because I'm not sure I can follow right now, but rather than explaining it to me, think of explaining it while first teaching default methods.

Tho in this logic, I'm not sure we can justify _any_ difference between `f _` and "`f(_)` with the right number of `_` depending on f's arity", so I should probably review what are the specified semantics for both.

**Comment by LPTK** [comment]
Following TypeScript, the type of expression `f` (or `f _` for that matter) should be `(a: Int, b?: Boolean) => Int` where the `?` in `b?` means the parameter is optional; and this would be a subtype of `Int => Int`.

In TypeScript:

```ts
function f(a: number, b: boolean = true): number { return a }
let g: (x: number, y?: boolean) => number = f
let h: (_:number) => number = true ? f : g
```

IMHO this is yet another example of how full-featured function types – which can properly reflect all method types – would make everything easier and more regular in Scala, the same way they do in TypeScript.

**Comment by MateuszKowalewski** [comment]
> Following TypeScript, the type of expression `f` (or `f _` for that matter) should be `(a: Int, b?: Boolean) => Int` where the `?` in `b?` means the parameter is optional; and this would be a subtype of `Int => Int`.

I don't get it. What type would `b` (oder `b?` for that matter) have? It's stated that it's a `Boolean`. But it isn't really. It's some type that can be a "`Boolean or not there at all`". But "`not there at all`" isn't a valid _value_ for a Boolean (it even isn't a value at all). So `b` can't have the type `Boolean`. So you just invented a new kind of types: "`Optional Types`". But how would one encode this "`Optional Types`"? What would be the implications of this new "`Optional Types`"?

I think a more logical (out of my perspective) type for `f` would be `(Int, true.type|Boolean) => Int`. It would encode the fact that there was an default parameter involved in the type of that method. It does not need that new "`Optional Typ`" kind of typs. Does this make sense? Would it be good for anything?

Regarding that alleged weirdness with eta-expansion: I'm with SethTisue here. This behavior seams correct. Eta-expansions is not the same as function application. Furthermore functions opposed to methods don't support default parameters at all. So what should eta-expansion do in such a case anyway? Both, silently applying the default parameter or silently discarding it seems wrong.

On the other hand it's true and a really pity that there is a visible difference between methods and functions. Especially for newcomers that's a great source of confusion! I would be happy if that difference would be completely hidden away somehow.

**Comment by LPTK** [comment]
@MateuszKowalewski
> What type would b (oder b? for that matter) have? It's stated that it's a Boolean. But it isn't really. It's some type that can be a "Boolean or not there at all".

No, it _actually is_ of type boolean. Notice that the question mark is not on the type, but on the parameter name. All it does is indicate that this parameter is optional. That is all.


Conceptually (and I'm not suggesting this is how it should actually be implemented), you could view the type `(a: Int, b?: Boolean) => Int` as meaning:

```scala
{ def apply(a: Int, b: Boolean): Int; def apply(a: Int): Int }
```

The implementation of the function will know how to call the method if no value is provided for the optional parameter – by using the method's default parameter value. No need for encoding terms in types as you propose with `(Int, true.type|Boolean) => Int`, which seems quite ugly and unnecessary to me (not to mention: how does it scale to more complex default terms? and effectful ones?).

> On the other hand it's true and a really pity that there is a visible difference between methods and functions. Especially for newcomers that's a great source of confusion! I would be happy if that difference would be completely hidden away somehow.

👍

**Comment by OlivierBlanvillain** [comment]
I will close this as it's non actionable in it's current state. It sounds like it would require non trivial changes (the addition of default-parameterized function types?) and would likely be a breaking change.
