### ISSUE TITLE
`TreeCopier` doesn't preserve attachments

### ISSUE THREAD

**Issue by Duhemm** [lampepfl/dotty#4291]
While working on embedding the doc in Tasty, I noticed that the `TreeCopier` subclasses don't copy over the attachments of the trees.

Is this on purpose?

Doc comments are stored as attachments on `MemberDef` trees, and cannot be recovered in the REPL for instance, because they're discarded when the trees are modified.

**Comment by Duhemm** [comment]
It looks like they're not copied over on purpose: it appears that copying them breaks a lot of things.

Should the docs be stored somewhere else that will not be lost down the line? Should we only copy the  doc comment in `TreeCopier`?

**Comment by smarter** [comment]
> It looks like they're not copied over on purpose: it appears that copying them breaks a lot of things.

What kind of failures are you getting?

> Should the docs be stored somewhere else that will not be lost down the line? Should we only copy the doc comment in TreeCopier?

Maybe we need to kind of attachments: sticky and non-sticky.

**Comment by Duhemm** [comment]
@smarter Here's sbt's log for `dotty-compiler/testOnly dotty.tools.dotc.CompilationTests -- --tests=compilePos`:
https://gist.github.com/Duhemm/5eff50bcf9981aa941773d252e22e8eb

> Maybe we need two kinds of attachments: sticky and non-sticky.

Sounds good! I'll look into that.
