### ISSUE TITLE
Spurious is instanceOf warning

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#4297]
As reported by @allanrenucci  in #4245, the following code will get a warning saying `Some[Int]` cannot be checked at runtime.

```Scala
class Test {
  def test[X <: Option[Int]](x: X) = x.isInstanceOf[Some[Int]]
}
```

Initial diagnosis shows that type inference somehow failed to infer `a <: Int`, given `Some[a] <: X` and `X <: Option[Int]`.

**Comment by Blaisorblade** [comment]
> Initial diagnosis shows that type inference somehow failed to infer a <: Int, given Some[a] <: X and X <: Some[Int].

But `X <: Some[Int]` should be `X <: Option[Int]`, since that's what we know, no?

**Comment by liufengyun** [comment]
> But `X <: Some[Int]` should be `X <: Option[Int]`, since that's what we know, no?
Yes, good catch, I updated the description.
