### ISSUE TITLE
REPL doesn't work on Windows: Consider directly using JLine 3 for the REPL

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#4309]
The REPL UI code in Dotty comes from ammonite-terminal and lives in https://github.com/lampepfl/dotty/tree/master/compiler/src/dotty/tools/repl/terminal, it works well enough but does not support Windows. This has been recently fixed in Ammonite by using [JLine 3](https://github.com/jline/jline3) under Windows. We could merge these changes in our version of ammonite-terminal, but if we're going to depend on JLine anyway we could also drop our version of ammonite-terminal and just use JLine directly (unless there's some features of ammonite-terminal we really need).

**Comment by allanrenucci** [comment]
Here is the Ammonite PR for reference: lihaoyi/Ammonite#775

**Comment by Glavo** [comment]
I'm looking forward to using jline3 to implement dotty repl, because jline3's complement is really [cool](https://1drv.ms/v/s!Aj9QXHXa1Zz7jCkofHEeCMVyyv8h)

**Comment by djx314** [comment]
+1 to use jline3 to support colourful output and mutiply lines coding.

**Comment by Blaisorblade** [comment]
Renamed to help GitHub search find this: https://github.com/lampepfl/dotty/search?utf8=%E2%9C%93&q=repl+windows&type=Issues

**Comment by Glavo** [comment]
The current Dotty REPL has problems with Chinese character:
![image](https://user-images.githubusercontent.com/20694662/40578693-e41ace42-614a-11e8-92a3-8041c9232ce0.png)
And jline 3 can help us solve this problem:
![image](https://user-images.githubusercontent.com/20694662/40578733-d7d997ca-614b-11e8-9948-b3b052b0e7ab.png)

**Comment by Blaisorblade** [comment]
@Glavo Ah, so those are two characters but our REPL shows the cursor one character before it should be, as if they were one?

**Comment by Glavo** [comment]
@Blaisorblade Yes, and Ammonite also has this problem when not using the jline 3 front end.

**Comment by W4anD0eR96** [comment]
As for the issue of  Chinese characters, note that JLine's output transfer “你好” to its codepoint

**Comment by Blaisorblade** [comment]
> As for the issue of Chinese characters, note that JLine's output transfer “你好” to its codepoint

@W4anD0eR96 Yes but I think that's a separate difference, independent from JLine and due to Ammonite's and Dotty's approaches at printing values — Dotty prints strings with toString (so `"hi"` prints `hi`, hence just print the actual content). Ammonite instead prints strings using PPrint, hence `"hi"` prints as `"hi"` and Unicode characters _can_ be quoted.

**Comment by allanrenucci** [comment]
Fixed in #4680
