### ISSUE TITLE
Add a miniphase to replace calls to case class factory methods by new

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#433]
This was done in `RefChecks` in Scala 2.
Example:
```scala
case class A(val x: Int)
def test() = {
  A(1)
}
```
Becomes:
```scala
case class A(val x: Int)
def test() = {
  new A(1)
}
```

**Comment by DarkDimius** [comment]
Why would you need this? 
```
case class A(a: Int) extends Object() with Product1[Int] {
    val a: Int
    def copy(a: Int): A = new A(a)
    def copy$default$1: Int @uncheckedVariance =
      A.this.a: Int @uncheckedVariance
    def isDefined: Boolean = true
    def _1: Int = this.a
  }
  final lazy module val A: A$ = new A$()
  final module class A$() extends Object() with Function1[Int, A] {
    this: A.type =>

    def apply(a: Int): A = new A(a)
    def unapply(x$1: A): A = x$1
  }

```
As you see, `A$` companion class has an `apply` method.
I would actually prefer to still be able to see, were user wrote actual `new` and were user used `companion.apply` to create it.

**Comment by sjrd** [comment]
This is mostly supposed to be a performance thingy. If you leave the call to `apply`, you need to keep the loading of `A$.MODULE$` even if you inline stuff. (Unless the inliner is sufficiently smart to know that this particular module's constructor is side-effect-free.)

**Comment by smarter** [comment]
Yes, it's an optimization, it's useful in general for case classes but it seems especially useful for case classes which are also value classes, for example if you have:
```scala
case class Foo(val underlying: Int) extends AnyVal
```
Then this:
```scala
val x: Foo = Foo(3)
```
becomes:
```scala
val x: Double = Foo.apply(3)
```
where `Foo.apply` is the identity.

I could add a specific peephole optimization for this case, but replacing all calls to case class factory is a more general optimization that wouldn't be harder to do.

**Comment by DarkDimius** [comment]
@smarter @sjrd yes, we are speaking about side effects here, removing them changes semantics.

And I'd better leave this to general inliner, as this is pretty basic optimization that we want to be applied everywhere.
As far as I understood @lrytz optimizer should be able to do it, otherwise the one that I'm working one is expected to be able to.

**Comment by DarkDimius** [comment]
by `basic optimization` I mean inlining of static calls. Even more, if they are identity.
Also, I'm pretty sure that VM is smart enough to do it ;-)

**Comment by lrytz** [comment]
> If you leave the call to apply, you need to keep the loading of A$.MODULE$ even if you inline stuff

Even if you replace the factory call by `new`, you still need to load the module to preserve semantics, no?

**Comment by DarkDimius** [comment]
Yes, I would say so. But either I'm wrong or this semantics is violated by scalac:
```
scala> case class A(s: Int); object A{println("foo")}
defined class A
defined object A

scala> A(1)
res0: A = A(1)
```

**Comment by lrytz** [comment]
That's a bug, then, i would say. You can still do it if the companion is known to have no side effects, such as compiler-generated case class companions.

**Comment by lrytz** [comment]
https://issues.scala-lang.org/browse/SI-5304
