### ISSUE TITLE
license pollution for the language-server

### ISSUE THREAD

**Issue by fommil** [lampepfl/dotty#4338]
please be careful that the language-server dependencies, i.e. https://github.com/eclipse/lsp4j/blob/master/LICENSE, do not creep into the compiler, library or tools transitive dependency list. The Eclipse Public License is explicitly incompatible with the GPL. (In fact it was designed to be hostile against SUN Microsystems --- OpenJDK uses the GPLv2)

It is also not a very nice license, you should read it sometime. I hope you like the courts of New York :wink: 

If you want to keep lsp4j on the classpath, it would be impossible for ENSIME (or any of my libraries or hobby applications) to be legally compatible with dotty. I'm not sure if you (@smarter) were fully aware of the consequences when we last discussed this https://github.com/lampepfl/dotty/issues/1523#issuecomment-253165177

**Comment by smarter** [comment]
FWIW, lsp4j is now dual-licensed under the Eclipse Public License 2.0 and BSD 3 clauses which should make everyone happy (except Sam of course because it's not GPLv3 :)) See https://github.com/eclipse/lsp4j/issues/233 and https://www.eclipse.org/legal/epl-2.0/faq.php#h.a0eux401qus

**Comment by fommil** [comment]
BSD 3 is GPL compatible, so I'm fine with your pushover license :laughing:
