### ISSUE TITLE
Wrong staging level when accessing type from class

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#4350]
When:
```
class F[T: Type] { '(null.asInstanceOf[T]) }
```

access to T from the class F is reported as a wrong level:
```
4 |  '(null.asInstanceOf[T])
  |                      ^
  |                      access to F.this from wrong staging level:
  |                       - the definition is at level 0,
  |                       - but the access is at level 1.
```

SImilarly:
```
class F {
  type T
  '(null.asInstanceOf[T])
}
```

**Comment by Blaisorblade** [comment]
Isn't that correct in the absence of lifting for types? Introducing it makes sense, but last time this came up (while talking to @nicolasstucki during a meeting) there weren't rules for it.

**Comment by nicolasstucki** [comment]
The problem is that it is the prefix of the type that gets the error. If we add the implicit `Type[T]` we still get this error. The code snippet should probably have the implicit type evidence.

**Comment by nicolasstucki** [comment]
With prefix I referred to `Foo.this` in `Foo.this.T` which is the type of `T`.

**Comment by biboudis** [comment]
Yes, I updated it to avoid any misconceptions.

**Comment by Blaisorblade** [comment]
Oh dear. That's because references to type params are still `TypeRef`s rather than `TypeParamRef`s? I am fine with that encoding, but that suggests that (for the theory) that classes need to exist in multiple phases?

**Comment by biboudis** [comment]
Yeap. 😏
