### ISSUE TITLE
Provide Eclipse tooling based on Language Server Protocol

### ISSUE THREAD

**Issue by vogella** [lampepfl/dotty#4352]
According to http://www.scala-lang.org/blog/2018/04/19/scala-3.html you provide Visual Studio Code tooling based on the  Language Server Protocol.

Please adapt that also for the Eclipse IDE, so that he have also good scale support and you have less effort support different tools. See https://www.eclipse.org/community/eclipse_newsletter/2017/may/article1.php

For example the new Spring tooling uses the same approach to support both Code and Eclipse.

**Comment by smarter** [comment]
Yes, the plan is to support as many IDEs as possible, but this requires users of these IDEs to work on doing the integration, right now I don't think anyone has tried to make LSP4E work with the Dotty Language Server, but it shouldn't take too much effort. The status of clients for the Dotty IDE is tracked at https://github.com/lampepfl/dotty/issues/3360
