### ISSUE TITLE
Dotty IDE errors when searching for a symbol

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4362]
I got this while searching for symbols, that is, typing Cmd-P `#Types` or `#RecType` in VSCode. I've seen similar errors at other times.

https://gist.github.com/Blaisorblade/3c599adbebd2858a578d464641e7c37d

I'm not sure how to reproduce them though, and I'm not sure if the project was clean or not. For all I know, the tasty could have been corrupted by incremental compilation or not be up-to-date or miss members that the loaded file depended on.

But even otherwise, I've never seen symbol search work in DottyIDE.

**Comment by OlivierBlanvillain** [comment]
I'll close this for now as it doesn't seem reproducible...
