### ISSUE TITLE
SAM types + Overloading + Eta-expansion

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4364]
The following code snippet fails to compile with Dotty. (Works with scalac)
```scala
class Test {
  def println(): Unit = ()
  def println(x: String): Unit = ()

  def foo(x: java.util.function.Consumer[String]) = 1
  foo(println(_))      // ok
  foo(x => println(x)) // ok
  foo(println)         // error
}
```
```scala
-- [E007] Type Mismatch Error: tests/allan/Test.scala:26:6 ---------------------
26 |  foo(println)
   |      ^^^^^^^
   |      found:    Unit
   |      required: java.util.function.Consumer[String]
   |      
one error found
```

**Comment by odersky** [comment]
I tried out some things. The problem is, if we allow that, the following also compiles:

    new java.io.ObjectPutputStream(println)

`println` replaces the abstract `write` method of `ObjectOutputStream`. I find this too surprising. It would be better to always demand that the argument to a SAM is an explicit closure, i.e. to forbid eta-expansion in this case.

**Comment by allanrenucci** [comment]
I agree. This currently compiles:
```scala
class Test {
  def foo(x: Any): Unit = ()
  def test = {
    new java.io.ObjectOutputStream(foo)
  }
}

```

**Comment by Glavo** [comment]
@odersky I think this problem stems from the functional interface, not Eta-expansion. We should check the functional interface and warn when the interface is not annotated with @FunctionalInterface.

**Comment by smarter** [comment]
This would add a lot of unnecessary warnings. Java doesn't emit any warning when using a SAM type that is not annotated with @FunctionalInterface.

**Comment by Glavo** [comment]
But Java's behavior creates a lot of unexpected functional interfaces, and lambda expressions and method reference expressions in Java can only be used in scenes where SAM conversion occurs without any confusion, different from Scala's lambda expression and eta-expansion.
I think that in any case, the author of the library or the user of the library should clearly know which interfaces will be used as functional interfaces, users should know what they are doing, and use @unchecked to prevent triggering compiler warnings.

**Comment by Glavo** [comment]
In fact, most of the commonly used functional interfaces in the JDK have been annotated as @FunctionalInterface. It may not be so common for users to actually disable warnings.

**Comment by allanrenucci** [comment]
I guess it worth doing the experiment and see how many warnings we get in our build and the community build
