### ISSUE TITLE
x == y fails with a NullPointerException when x is null

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#439]
`InterceptedMethods` now rewrite `x == y` into `x.equals(y)` but this means that if x is null, there will be a NullPointerException, surely that's not the intended behaviour?

**Comment by smarter** [comment]
I guess the backend should replace `equals` by calls to `BoxesRunTime.equals` instead?

**Comment by DarkDimius** [comment]
No, == needs to be intercepted by backend. It generates code on its own which is slightly more optimized.
