### ISSUE TITLE
Auto-completion on '.' with no prefix

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4397]
Consider the following file:
```scala
class Foo {
  .
}
```
If you have your cursor after `.` and auto-complete, you get everything in scope

**Comment by smarter** [comment]
What would you expect to get?

**Comment by allanrenucci** [comment]
Nothing

**Comment by SethTisue** [comment]
this is very Zen

**Comment by Duhemm** [comment]
Fixed in #5476
