### ISSUE TITLE
Abnormal behavior when completing infix calls in REPL

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4407]
![image](https://user-images.githubusercontent.com/20694662/39399285-c522b1fc-4b4d-11e8-9920-a15176c27629.png)

**Comment by Glavo** [comment]
![image](https://user-images.githubusercontent.com/20694662/42130643-5a6edee2-7d1d-11e8-9333-8f8dbf52e83d.png)
I think this issue may have been fixed by #4680. Can this issue be closed?

**Comment by allanrenucci** [comment]
Fixed in #4680
