### ISSUE TITLE
Display the blog posts on the frontpage of the Dotty website

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#4409]
It'd be nice if http://dotty.epfl.ch/ showcased the latest blog posts from http://dotty.epfl.ch/blog/, a bit like http://scala-lang.org/ does for https://scala-lang.org/blog/

**Comment by OlivierBlanvillain** [comment]
I'll close this for now since the front page is mostly outdated and has much lower hanging fruits that displaying blog posts...
