### ISSUE TITLE
Confusing error due to mixup between WildcardType and TypeBounds

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4421]
After recent fixes, the following code doesn't crash but gives an error message worth improving:
```scala
scala> class A1 extends _
1 |class A1 extends _
  |                 ^
  |                  is not a class type
```
That error comes from `ctx.error(ex"$tp is not a class type", pos)`, but `$tp` is being pretty-printed to the empty string. This happens because `$tp` is `TypeBounds(q"Nothing", q"Any")` (where `q"Nothing"` is just informal quasiquote notation) instead of being `WildcardType(TypeBounds(q"Nothing", q"Any"))`, and such type bounds are correctly pretty-printed to the empty string.

**Comment by smarter** [comment]
In that particular case, I think we should just emit an error about unbound wildcard in the parser, like for everything else in https://github.com/lampepfl/dotty/issues/4373

**Comment by odersky** [comment]
I actually think the error message is fine. The pointed to `_` is indeed not a class type. Since this error is very unlikely to occur in the wild, I would not spend time and code lines to improve it.
