### ISSUE TITLE
Work out operations we want from semantic layer for macros

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#4427]
Some draft operations in the following. What else do we need?

On trees: 

  - map 
  - fold
  - substitute symbols
  - change owners
  - map all types 
     (the last three are essentially what a TreeTypeMap does)

On types:

  - typeMember(name: String): List[Denotation]
  - termMember(name: String): List[Denotation]
  - allMembers: List[Symbol]
  - baseType(cls: Symbol): Type
  - signature: Signature
  -  <:< (other: Type): Boolean

On class symbols:

  - baseClasses: List[Symbol]

On method and val symbols:
  
  - overriddenSymbol(inCls: Symbol): Option[Symbol]
  - allOverriddenSymbols: List[Symbol]

Denotations:

    case class Denotation(name: String, info: Option[Type | TypeBounds], symbol: Option[Symbol])
       // at least one of `info` and `symbol` is defined.

**Comment by liufengyun** [comment]
I've been using the following as well (but may not want to support them all initially):

1. create new symbols
2. constructors/extractors/ops for `AppliedType` , `MethodType`, `ByNameType`, etc
3. lub of types
4. create TypeRef from a fully qualified string
5. create TermRef from a fully qualified string
6. `Type.widen`
7. get companion object/class
8. wrap a type into a type tree

**Comment by OlivierBlanvillain** [comment]
Is this still relevant after all the recent work on Tasty reflect?
