### ISSUE TITLE
Serializable objects should have a "readResolve" method synthesized

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#4440]
See explanation in https://github.com/scala/scala/blob/a9275b50e425d29c0b7fd45c10317953d5bf7804/src/compiler/scala/tools/nsc/typechecker/SyntheticMethods.scala#L319-L324
In Dotty this should be done in https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/SyntheticMethods.scala

**Comment by ingarabr** [comment]
I have started working on this one.
