### ISSUE TITLE
Lazy vals initialisation can be retried after exception

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4451]
```scala
class Foo(x: Int) {
  private[this] var init = false;
  lazy val foo = {
    if (!init) {
      init = true
      assert(false)
    }
    x
  }
}

object Test {
  def main(args: Array[String]): Unit = {
    val foo = new Foo(42)
    try foo.foo
    catch {
      case _: AssertionError =>
        println(foo.foo) // prints 0, should be 42
    }
  }
}
```

**Comment by smarter** [comment]
Do we really want to do this? Is this a documented/specified behavior of scalac?

**Comment by allanrenucci** [comment]
I don't know if it is documented but it is for sure relied upon: https://github.com/scala/scala/blob/02776afa797fdf320dfefbaeb4b70431ee085b25/test/junit/scala/collection/immutable/LazyListTest.scala#L71

**Comment by allanrenucci** [comment]
I found [this](https://docs.scala-lang.org/sips/improved-lazy-val-initialization.html#version-5---retry-in-case-of-failure) that says:
>The current Scala semantics demand retrying the initialization in case of failure.

**Comment by smarter** [comment]
@DarkDimius Is it intentional that the Dotty implementation of lazy val does not allow re-initialization after an exception?

**Comment by allanrenucci** [comment]
The lazy val is retried if it is annotated `@volatile`
