### ISSUE TITLE
'.' after Int literal should not be highlighted

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4454]
![image](https://user-images.githubusercontent.com/20694662/39589708-8c3023ce-4f31-11e8-8eee-66fe49573560.png)

**Comment by Yyukan** [comment]
I think this behavior is related to double literals which uses point (".") as decimal separator:

![screen shot 2018-05-08 at 11 26 48](https://user-images.githubusercontent.com/5247135/39749338-b6b14504-52b2-11e8-977e-1403f8c0e87d.png)

**Comment by Glavo** [comment]
@Yyukan I also think so, but I think Ammonite's behavior is more reasonable: 
![image](https://user-images.githubusercontent.com/20694662/39761279-46d3dd98-530a-11e8-820e-a23dc2a4121f.png)
![image](https://user-images.githubusercontent.com/20694662/39761288-4a628b62-530a-11e8-969c-491f8e6990e4.png)
![image](https://user-images.githubusercontent.com/20694662/39761296-4e68da22-530a-11e8-8422-f21fe3120cd1.png)
