### ISSUE TITLE
Improve parser error recovery for the IDE

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#4463]
Our parser is able to recover from errors, but the way it does that is fairly conservative, from `Parser#skip`:
```scala
    /** Skip on error to next safe point.
     *  Safe points are:
     *   - Closing braces, provided they match an opening brace before the error point.
     *   - Closing parens and brackets, provided they match an opening parent or bracket
     *     before the error point and there are no intervening other kinds of parens.
     *   - Semicolons and newlines, provided there are no intervening braces.
     *   - Definite statement starts on new lines, provided they are not more indented
     *     than the last known statement start before the error point.
     */
```
This makes a lot of sense in batch mode where we'd prefer to avoid cascading confusing errors, but in the IDE it means that a lot of code can end up without type information because it happens to be after a parser error and before the next safe point, for example in:
```scala
class Test {
  val x = 1
  while false) {
    x + 1
  }
}
```
The parser outputs:
```scala
class Test { 
  val x = 1
  while false do null
}
```
so hovering over `x` in the while body won't do anything.

I'm not sure what the best solution is here, but I'd like to avoid a special parser mode for the IDE. One possibility would be to still parse the code before the next safepoint but mark it in some way (by wrapping it in a magic synthetic tree?) to let the typer know that it should typecheck it but not report any errors it finds while typechecking it.

**Comment by Blaisorblade** [comment]
> to let the typer know that it should typecheck it but not report any errors it finds while typechecking it.

But also have an even more resilient `try ... catch { case t: Throwable => ... }` around it, after all the exceptions that invalid parser outputs can trigger.
