### ISSUE TITLE
Allows the user to prevent the generation of class files for objects whose members are all annotated with @static

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4497]
Currently, when an object member is all annotated with @static, the compiler still generates a corresponding class file for it.These objects have no practical use in most cases, and I think we should allow users to somehow prevent the compiler from generating them.For example, we can add new usage for @static:
```scala
class Test 

@static
object Test {
  @static
  def f: Int = 100
}
```
Or we can go one step further. When an object is annotated with @static , all its members are treated as being annotated with @static , which may help us reduce a lot of duplicate work.
Preventing the compiler from generating useless objects can help us reduce the output file size, make Dotty-generated bytecode more controllable, and be more friendly to other JVM languages.

**Comment by smarter** [comment]
Closing with stat:revisit, because this would require more work on @static and I cannot guarantee that this will happen. Someone needs to be responsible for the SIP (https://docs.scala-lang.org/sips/static-members.html) and the implementation in Dotty.
