### ISSUE TITLE
Improvements in Using AnyKind for Improved Missing Compiler Arguments

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4505]
Currently using Kind Polymorphism in the absence of compiler arguments, the compiler only prompts us that the AnyKind type cannot be found:
<pre>sbt:dotty-simple<font color="#06989A">&gt; </font>compile
[info] Compiling 1 Scala source to /home/glavo/Projects/dotty-projects/test/target/scala-0.8/classes ...
[<font color="#CC0000">error</font>] <font color="#3465A4">-- [E006] Unbound Identifier Error: /home/glavo/Projects/dotty-projects/test/src/main/scala/Main.scala:10:13 </font>
[<font color="#CC0000">error</font>] <font color="#CC0000">10 |</font>  <font color="#C4A000">def</font> <font color="#06989A">f</font>[<font color="#75507B">T</font> &lt;: <font color="#75507B">AnyKind</font>] = <span style="background-color:#CC0000">???</span>
[<font color="#CC0000">error</font>]    |             <font color="#CC0000">^^^^^^^</font>
[<font color="#CC0000">error</font>]    |             not found: type AnyKind
[<font color="#CC0000">error</font>] one error found
[<font color="#CC0000">error</font>] (Compile / <font color="#CC0000">compileIncremental</font>) Compilation failed
[<font color="#CC0000">error</font>] Total time: 0 s, completed 2018-5-11 0:32:29</pre>

I think that the behavior of the compiler now will cause users to be confused, we should prompt the user to add compiler parameters in the error.

**Comment by Glavo** [comment]
Oh, I don't seem to find this tip in the [documentation](http://dotty.epfl.ch/docs/reference/kind-polymorphism.html), I think we should join the tips in the [blog](http://dotty.epfl.ch/blog/2018/04/27/eighth-dotty-milestone-release.html#kind-polymorphism-4108) here.Can this simple fix of the document allow me to handle it?

**Comment by Blaisorblade** [comment]
@Glavo fair point, the docs should mention `-Ykind-polymorphism` as long as it's in. Opened #4510, you're welcome to take a look.

> Can this simple fix of the document allow me to handle it?

If you're asking if your example works with that flag, yes it does work.

> I think that the behavior of the compiler now will cause users to be confused, we should prompt the user to add compiler parameters in the error.

I agree that we should also suggest adding the flag, but the medium-term plan is to decide what to do with this feature and let it either in or out, without a flag. I'm not against a PR if it's easy but it seems overkill for now, so I'd close the rest with the `stat:revisit` label.

What looks easy is to make the explanation in the `MissingIdent` class conditional, and say more if the identifier name is `AnyKind`, tho this isn't scope-aware. Or one could reimplement `-Ykind-polymorphism` by making `AnyKind` always visible but rejecting it in some phase if the flag is disabled, but that's more complex.

**Comment by Blaisorblade** [comment]
Closing for now as mentioned, can be reopened if there's new info.
