### ISSUE TITLE
Eta-expansion working for implicit fails on implicit erased

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4509]
Trying to compile this code will cause a compilation error
```scala
object Main {
  def fun(op: implicit erased (Int) => Unit) = op(0)
  fun { }
}
```
<pre>sbt:dotty-simple<font color="#06989A">&gt; </font>compile
[info] Compiling 1 Scala source to /home/glavo/Projects/dotty-projects/test/target/scala-0.8/classes ...
[<font color="#CC0000">error</font>] <font color="#3465A4">-- [E007] Type Mismatch Error: /home/glavo/Projects/dotty-projects/test/src/main/scala/org/glavo/Main.scala:5:9 </font>
[<font color="#CC0000">error</font>] <font color="#CC0000">5 |</font>  fun { }
[<font color="#CC0000">error</font>]   |         <font color="#CC0000">^</font>
[<font color="#CC0000">error</font>]   |         found:    Unit
[<font color="#CC0000">error</font>]   |         required: <font color="#C4A000">erased implicit </font>Int =&gt; Unit
[<font color="#CC0000">error</font>]   |         
[<font color="#CC0000">error</font>] one error found
[<font color="#CC0000">error</font>] (Compile / <font color="#CC0000">compileIncremental</font>) Compilation failed
[<font color="#CC0000">error</font>] Total time: 0 s, completed 2018-5-11 2:05:16
</pre>

But this code can be compiled:
```scala
object Main {
  def fun(op: implicit (Int) => Unit) = op(0)
  fun { }
}
```

**Comment by Blaisorblade** [comment]
@nicolasstucki can assign to you?

**Comment by b-studios** [comment]
👍 I also ran into this issue :)
