### ISSUE TITLE
Infix function does not work well with SAM conversions

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4513]
<pre><font color="#3465A4">scala&gt; </font><font color="#75507B">Stream</font>.of(<font color="#CC0000">1</font>, <font color="#CC0000">2</font>, <font color="#CC0000">3</font>) forEach println(_) 
<font color="#CC0000">1 |</font><font color="#75507B">Stream</font>.of(<font color="#CC0000">1</font>, <font color="#CC0000">2</font>, <font color="#CC0000">3</font>) forEach println(_)
  |                                   <font color="#CC0000">^</font>
  |missing parameter type
  |
  |The argument types of an anonymous function must be fully known. (SLS 8.5)
  |Expected type: ?
  |Missing type for parameter _$2
<font color="#3465A4">scala&gt; </font><font color="#75507B">Stream</font>.of(<font color="#CC0000">1</font>, <font color="#CC0000">2</font>, <font color="#CC0000">3</font>).forEach(println(_)) 
1
2
3</pre>

**Comment by smarter** [comment]
Same behavior as Scala 2, when you write:
```scala
Stream.of(1, 2, 3) forEach println(_) 
```
it gets expanded to:
```scala
x => Stream.of(1, 2, 3) forEach println(x) 
```

We can't change this without breaking a lot of existing code.
