### ISSUE TITLE
Non-local return will result in extra athrow after being inlined

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4521]
```scala
object C {
  inline def f(arg: => Unit) = arg

  def fun: Int = {
    f {
      return 10
    }
    0
  }
}
```
Bytecode for fun: 
![image](https://user-images.githubusercontent.com/20694662/39954330-2f36124e-55f0-11e8-898b-8e6bbc13724b.png)

**Comment by smarter** [comment]
This is a known behavior of the backend which is unlikely to change since it doesn't really cost anything: see https://github.com/scala/scala/blob/v2.12.3/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala#L830-L872 and https://github.com/lampepfl/dotty/issues/3271
