### ISSUE TITLE
Nested inline functions should not generate bytecodes

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4523]
Because nested functions are only called in external functions, it is meaningless to generate bytecode for nested inline functions.

**Comment by nicolasstucki** [comment]
I guess it is in functions like `bar` in
```scala
object Foo {
  def foo: Unit = {
    inline def bar(): Unit = ()
    bar()
  }
}
```
where we should not generate the code for `bar`.

Note that the code at backend is 
```scala
package <empty> {
  @scala.annotation.internal.SourceFile("Foo.scala") final module class Foo$
     extends
   Object { 
    def <init>(): Unit = 
      {
        super()
        ()
      }
    def foo(): Unit = 
      {
        println("aa")
      }
    private inline def bar$1(): Unit = println("aa")
  }
  final lazy module val Foo: Foo$ = new Foo$()
}
```

We should be able to juts drop inline method while lifting.

**Comment by nicolasstucki** [comment]
Actually, with `-optimise` this `bar$1` is removed.

**Comment by smarter** [comment]
In scalac, it looks like unused inner methods are eliminated by typer:
```scala
object Test {
  def foo: Int = {
    def bar: Int = 3
    2
  }
}
```
```scala
[[syntax trees at end of                     typer]] // dce.scala
package <empty> {
  object Test extends scala.AnyRef {
    def <init>(): Test.type = {
      Test.super.<init>();
      ()
    };
    def foo: Int = 2
  }
}
```
But I can't find the logic reponsible for this (any idea @retronym ?).  In any case, if we did something like that in Dotty it should be done after pickler for the IDE sake.

**Comment by retronym** [comment]
@smarter It is in constant folding. The behaviour could be seen as a bug IMO.

See https://github.com/scala/bug/issues/7173#issuecomment-332036501 / https://github.com/scala/bug/issues/10340

**Comment by smarter** [comment]
Oh I see, that's a very weird and inconsistent behavior of scalac then, since it means that nothing is def is eliminated if the block expression is not "safe to inline":
```scala
object Test {
  def foo: Int = {
    def bar: Int = 3
    println("")
  }
}
```

**Comment by AleksanderBG** [comment]
@nicolasstucki Right now, we emit no bytecode for local inline methods.

<details><summary>See decompilation output</summary>
<pre>
$ cat Test.scala 
class Test {
  def test = {
    inline def five = 5
    five
  }
}
$ ../bin/dotc Test.scala
$ javap -verbose Test.class 
Classfile /home/gruszecki/code/dotty/play/Test.class
  Last modified Apr 4, 2019; size 353 bytes
  MD5 checksum 37b4ed17a682f4aac43de007a8070f84
  Compiled from "Test.scala"
public class Test
  minor version: 0
  major version: 52
  flags: ACC_PUBLIC, ACC_SUPER
Constant pool:
   #1 = Utf8               Test
   #2 = Class              #1             // Test
   #3 = Utf8               java/lang/Object
   #4 = Class              #3             // java/lang/Object
   #5 = Utf8               Test.scala
   #6 = Utf8               <init>
   #7 = Utf8               ()V
   #8 = NameAndType        #6:#7          // "<init>":()V
   #9 = Methodref          #4.#8          // java/lang/Object."<init>":()V
  #10 = Utf8               this
  #11 = Utf8               LTest;
  #12 = Utf8               test
  #13 = Utf8               ()I
  #14 = Utf8               Code
  #15 = Utf8               LocalVariableTable
  #16 = Utf8               LineNumberTable
  #17 = Utf8               SourceFile
  #18 = Utf8               TASTY
  #19 = Utf8               Scala
{
  public Test();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #9                  // Method java/lang/Object."<init>":()V
         4: return
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   LTest;
      LineNumberTable:
        line 1: 0

  public int test();
    descriptor: ()I
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: iconst_5
         1: ireturn
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       2     0  this   LTest;
      LineNumberTable:
        line 2: 0
}
SourceFile: "Test.scala"
Error: unknown attribute
  TASTY: length = 0x10
   00 BD FD 67 CD 78 4F 00 00 94 8D 87 A0 90 A3 00

Error: unknown attribute
  Scala: length = 0x0
</pre>
</details>

Do we want to test for this in any way, or do we want to just close this issue outright?

**Comment by smarter** [comment]
We should test it if there's no test for it yet, you can just do a run-test that lists all the members of the current class using Java reflection.
