### ISSUE TITLE
Problems with recognizing '[] syntax

### ISSUE THREAD

**Issue by Glavo** [lampepfl/dotty#4539]
<pre><font color="#3465A4">scala&gt; </font><font color="#C4A000">val</font> <font color="#06989A">a</font> = <font color="#CC0000">&apos;</font>[<font color="#75507B">Int</font>] 
<font color="#C4A000">val</font> <font color="#06989A">a</font>: <font color="#06989A">scala</font>.quoted.<font color="#75507B">Type</font>[<font color="#75507B">Int</font>] = <font color="#75507B">Type</font>(<font color="#75507B">Int</font>)

<font color="#3465A4">scala&gt; </font><font color="#CC0000">&apos;</font>[<font color="#75507B">Int</font>] 
<font color="#CC0000">1 |&apos;</font>[<font color="#75507B">Int</font>]
  |<font color="#CC0000">^</font>
  |Illegal start of statement

</pre>

**Comment by nicolasstucki** [comment]
Same happens for 
```scala
object Foo {
  val q = '[String]
  '[String] // error
}
```
