### ISSUE TITLE
Dotty IDE - sbt file get falsely red squiggly marks

### ISSUE THREAD

**Issue by NetanelRabinowitz** [lampepfl/dotty#4542]
The issue seems to be [reproducible](https://gitter.im/lampepfl/dotty?at=5afd88129ad18967b9f27329) with the sample project
`sbt new lampepfl/dotty.g8 `
followed the instructions at
http://dotty.epfl.ch/docs/usage/ide-support.html

vscode is yielding the folwing:

> expected class or object definition
> expected start of definition

referring to the sbt file.

**Comment by Blaisorblade** [comment]
I guess we should at least not try handling sbt files, until we add support for them, rather than give false errors for them. @Duhemm WDYT ?
