### ISSUE TITLE
Dotty uses SIP-12 syntax in output and input

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4599]
I noticed in a #4563 comment that `RefinedPrinter` only uses [SIP-12](https://docs.scala-lang.org/sips/uncluttering-control.html) syntax in output, even tho that SIP was rejected. That syntax is also accepted in input, which would still be a problem for tool authors trying to support Dotty. I couldn't dig any mention of SIP-12 in the commit logs (but only tried `git log -S SIP-12`  and `git log -G SIP-12`).

Apparently the SIP was born in 2011 and only rejected in 2016 (https://docs.scala-lang.org/sips/minutes/2016-08-16-sip-10th-august-minutes.html), so it shouldn't be surprising this is still in.

Example using `while...do`:
```scala
sbt:dotty> repl
scala> var i = 0; while i < 5 do { i += 1; println(i) }
1
2
3
4
5
var i: Int = 5
```

**Comment by vaartis** [comment]
Hey, i'd like to try to work on this. Any suggestions on where to start?

**Comment by SzymonPajzert** [comment]
What is the status of this ticket? I've seen in [syntax doc](https://dotty.epfl.ch/docs/internals/syntax.html) that `‘if’ Expr ‘then’ Expr [[semi] ‘else’ Expr]` is allowed syntax. Should it be removed as well, since it was proposed in SIP-12?

**Comment by Blaisorblade** [comment]
@SzymonPajzert Exactly. We have been busy, but we should certainly remove the syntax (both from the pretty-printer and the parser) to honor the SIP decision.

**Comment by allanrenucci** [comment]
I'll would ask @odersky first, before we removing anything. I've seen him use the syntax in some of our tests

**Comment by Blaisorblade** [comment]
So while SIP-12 was rejected for Scala 2, Martin would still like to revive it.

**Comment by Blaisorblade** [comment]
So I'm putting the issue on hold with `stat:revisit`. Sorry @SzymonPajzert for the noise!

**Comment by SzymonPajzert** [comment]
No problem, 356 to go
