### ISSUE TITLE
Clarify migration path from Scala2 for "Structural Types"

### ISSUE THREAD

**Issue by newca12** [lampepfl/dotty#4615]
This is a followup of a discussion on gitter with @Blaisorblade and @smarter regarding the documentation of "Structural Types".
The two main issue with the documentation are : 

1. to be a bit misleading regarding the fact that current implementation still "reflection-based". dotty structural types allow for other implementations but right now we only have the reflection-based one
1. not  emphasize enough that in most cases importing scala.reflect.Selectable.reflectiveSelectable is sufficient for Scala2 code.

Regarding point 2 @smarter suggested to make the reflective stuff enabled by default with -language:Scala2 to allow cross-compilation.
That seemed to be fine but they are issues with Scala 2 code : 
```scala
//import is not enought to make Scala2 code compile with dotty
import scala.reflect.Selectable.reflectiveSelectable
object Structural {
  class Example1 {
     def text(): String = "example"
  }
  val example1: Example1 = new Example1
  val example3: { def text(): String } = example1
  val res : String = example3.text
}
```
example3.text has not the same type with Scala 2 "String" and with dotty "() => String"
This is easy to fix manually using def text instead of def text()

I would have been happy to open a PR to improve the documentation but too many uncertainties still remain in order to do so.

**Comment by smarter** [comment]
> example3.text has not the same type with Scala 2 "String" and with dotty "() => String"

It shouldn't compile at all with Dotty: http://dotty.epfl.ch/docs/reference/dropped/auto-apply.html

**Comment by newca12** [comment]
OK so that mean that this minimized example code should not compile with dotty and deserve is own issue. Right ?
```scala
import scala.reflect.Selectable.reflectiveSelectable
class Test {
  def test(x: { def get(): Int }) = x.get
}
```
and that the example in this issue should compile with -language:Scala2,rewrite.
We can minimize it like in #4026
```scala
import scala.reflect.Selectable.reflectiveSelectable //should not be needed in Scala2 mode
class Test {
  def test(x: { def get(): Int }): Int = x.get
}
```
Is this also an other issue or just not implemented yet ?

Clarify migration path from Scala2 for "Structural Types" would be summed up then by : will the reflective stuff will be enabled by default in Scala 2 mode ?

**Comment by smarter** [comment]
It should be a separate issue yes.

**Comment by abgruszecki** [comment]
Given the age of the issue, documentation changes and the presence of new migration guide, I think it's safe to close this issue. If there's a problem with the migration guide, please open a new issue.
