### ISSUE TITLE
Type inference failure (and crash with  -Yno-deep-subtype) when using SeqLike

### ISSUE THREAD

**Issue by thesamet** [lampepfl/dotty#4647]
I am trying to get ScalaPB to compile with Dotty. It looks like `SeqLike` has been changed such that the original code doesn't compile with Dotty. I then found a signature that works with Dotty only, but not with ScalaPB. And finally one that works on both:

```scala
import scala.collection._
import scala.language.higherKinds

class F[A]

// Compiles with Scala 2, but not with dotty.
object Scala2Only {
  def func[A, C[A] <: SeqLike[A, C[A]]](x: F[C[A]]) = {}

  func(new F[Seq[Int]])
}

// Compiles with Dotty, but not with Scala 2
object DottyOnly {
  def func[A, CA <: SeqLike[A, CA]](x: F[CA]) = {}

  func(new F[Seq[Int]])
}

// Compiles on both
object Both {
  def func[A, C[_] <: SeqLike[_, C[_]]](a: F[C[A]]) = {}

  func(new F[Seq[Int]])
}
```

I am not sure if these incompatibilities is a bug or a known breaking change.

**Comment by smarter** [comment]
Looks like a bug in type inference, the compiler crashes when compiling `Scala2Only` with `-Yno-deep-subtypes` (which means there's an infinite loop in subtyping).

As a workaround, writing the type arguments by hand works:
```scala
func[Int, Seq](new F[Seq[Int]])
```

**Comment by smarter** [comment]
The chain of infinite subtype checks looks like this:
```scala
Seq[A] <:< C[A]
Seq <:< [A] => collection.SeqLike[A, LazyRef(C[A])]
Seq[A] <:< collection.SeqLike[A, LazyRef(C[A])]
scala.collection.SeqLike[A, Seq[A]] <:< collection.SeqLike[A, LazyRef(C[A])]
Seq[A] <:< LazyRef(C[A])
Seq[A] <:< C[A]
```

**Comment by thesamet** [comment]
Thanks for looking into this @smarter. I should have provided more context: in my use case the `func` depicted above is actually an implicit conversion function that is meant to add methods such as `:++=` to a `Lens[Seq[T]]`. Since the goal was to introduce a nice syntax, the workaround of calling the conversion method explicitly (with the actual types) is not applicable.

The actual code in question is https://github.com/scalapb/ScalaPB/blob/17effd8fe0ab8b837e56d5fbbc9f32e68ec86198/lenses/shared/src/main/scala/scalapb/lenses/Lenses.scala#L66 the code shown works for Dotty but not for Scala 2.12 (the tests `lensesJVM/test` will not compile.

**Comment by smarter** [comment]
Looks like it works now.
