### ISSUE TITLE
Unused special case for `AnnotatedType` in `RefinedPrinter`

### ISSUE THREAD

**Issue by gsps** [lampepfl/dotty#4657]
Looking through RefinedPrinter https://github.com/lampepfl/dotty/blob/76b110b5bb029a6607f517304dd2fa9c58547a88/compiler/src/dotty/tools/dotc/printing/RefinedPrinter.scala#L204 I noticed a case that ostensibly overrides the printing of `AnnotatedType` when testing the pickler (`homogenizedView`). In reality, that case just computes `withoutPos(super.toText(tp))` without returning it and eventually falls through to `super.toText(tp)`. Considering that pickling tests do work, it seems that the special case is not needed anymore, so I suggest we remove it.

**Comment by nicolasstucki** [comment]
Should test this after #5713 is merged.
