### ISSUE TITLE
Compiler crashes when output directory doesn't exist

### ISSUE THREAD

**Issue by vsalvis** [lampepfl/dotty#466]
To reproduce, delete dotty/out and run the JUnit tests with `test-only dotc.tests`

The first few pos tests fail with `java.io.IOException: No such file or directory`. Then dotc.tests.dotc_core somehow creates the output directory again, from which point the tests pass.

**Comment by DarkDimius** [comment]
scalac doesn't. Should Dotty?
```
dark@reco /tmp/t $ ls -la
total 4
drwxr-xr-x  3 dark wheel 102 Apr 16 19:04 ./
drwxrwxrwt 14 root wheel 476 Apr 16 19:04 ../
-rw-r--r--  1 dark wheel  10 Apr 16 19:04 A.scala
dark@reco /tmp/t $ scalac A.scala -d out
scalac error: out does not exist or is not a directory
  scalac -help  gives more information
dark@reco /tmp/t $ scalac -version
Scala compiler version 2.11.6 -- Copyright 2002-2013, LAMP/EPFL
```

**Comment by odersky** [comment]
I misunderstood before. Greed this need not be required for dotty.

On Thu, Apr 16, 2015 at 7:06 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> scalac doesn't. Should Dotty?
>
> dark@reco /tmp/t $ ls -la
> total 4
> drwxr-xr-x  3 dark wheel 102 Apr 16 19:04 ./
> drwxrwxrwt 14 root wheel 476 Apr 16 19:04 ../
> -rw-r--r--  1 dark wheel  10 Apr 16 19:04 A.scala
> dark@reco /tmp/t $ scalac A.scala -d out
> scalac error: out does not exist or is not a directory
>   scalac -help  gives more information
> dark@reco /tmp/t $ scalac -version
> Scala compiler version 2.11.6 -- Copyright 2002-2013, LAMP/EPFL
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/466#issuecomment-93786361>.
>



-- 
Martin Odersky
EPFL
