### ISSUE TITLE
Missing unreachable case warnings

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#4661]
Given:
```scala
trait Foo
class One extends Foo
class Two extends Foo
class Three extends Foo

object Test {
  def test(f: Foo) = f match {
    case f: Foo =>
    case f: One =>
    case f: Two =>
    case f: Three =>
  }
}
```
We should get three warnings since the three last cases are not reachable, but we only get one for the last case:
```scala
-- [E120] Only null matched Warning: try/caseun.scala:11:9 ---------------------
11 |    case f: Three =>
   |         ^^^^^^^^
   |         Only null is matched. Consider using `case null =>` instead.
```
(The warning itself is a bit confusing but that's a separate issue: https://github.com/lampepfl/dotty/issues/4660)

**Comment by liufengyun** [comment]
@smarter Current implementation only check for the last case because the computation is a little expensive (much more than unreachable case analysis). We can still do the analysis for all cases, and see how it impacts performance.

**Comment by liufengyun** [comment]
Thanks a lot for the in-depth diagnosis @abeln , I think that is the right fix. Could you please make a PR?
