### ISSUE TITLE
specifying a type in pattern matching results in a spurious warning

### ISSUE THREAD

**Issue by thesamet** [lampepfl/dotty#4674]
```
val x: String = "something"
x.foreach {
  case 's' => println("s")
  case c: Char => println(c)
} 
```

Results in:
```
[warn] 154 |        case c: Char                   => println(c)
[warn]     |             ^
[warn]     |this will always yield true, since `class Char` is a subclass of `class Char`
```

While it's true that I can just omit the `: Char`, the intent here was to increase readability by specifying the type. Feel free to close if this is not a bug but an intended change.

**Comment by allanrenucci** [comment]
It is an intended change. Since we cannot know the intent of the author, I think we should always emit a warning for fruitless type tests

**Comment by odersky** [comment]
This leads to spurious warnings for compiler-generated pattern matches. I believe it's better to revert the decision and check only explicit `isInstanceOf`, never patterns. 

Note the scalac does not check patterns either.
