### ISSUE TITLE
Support .sbt files in vscode ide / language server

### ISSUE THREAD

**Issue by fahrradflucht** [lampepfl/dotty#4716]
Currently when opening `build.sbt` or `.sbt` files in `project` vscode gives squiggly red lines all over the place since it detects the file as scala but doesn't now how to handle it (the lsp doesn't find a configuration).

I'm not sure if it is feasible to generate a configuration for those files with the current language servers capabilities since they also have some differences to normal files in that they neither contain object nor class definitions.

~In the mean time it would maybe be a first step to just discard language server errors in `.sbt` files.~

**Edit:**
I just saw that 2ce96aef2ebbc14b8c0e89df20b3b2f7781447b3 does what I proposed as an intermediary fix. - @smarter would you mind releasing this? It doesn't look like vscode-dotty follows a particular release schedule.

**Comment by Blaisorblade** [comment]
Relates to #4542. I think vscode-dotty is released with Dotty, and I expect that this was fixed in 0.9.0-RC1. Don't know about any better plans.

**Comment by fahrradflucht** [comment]
Is vscode-dotty is released with dotty? The [last version commit](https://github.com/lampepfl/dotty/commit/eeb967ea3dec353546ff5880b652fc7e374dd8e4) was on the 19th of april and dotty [was released](https://github.com/lampepfl/dotty/commit/0f9b5fa56d8eadf226c37239fb3f2414d900e5f0) on the 12th of june. Or do I miss something here?

**Comment by smarter** [comment]
PR to upgrade dependencies and make a release: https://github.com/lampepfl/dotty/pull/4828

**Comment by allanrenucci** [comment]
`.sbt` files won't be supported by the Dotty language server. Future releases of VSCode plugin ignore them
