### ISSUE TITLE
typedClosure rule for adding type ascription is inconsistent

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#472]
This code:

``` scala
class O {
  val ss: String => String = _
  val oo: Object => Object = _
}
```

Becomes after ResolveSuper:

``` scala
class O() extends Object() { 
  <accessor> def ss: String => String = {
    def $anonfun(s: String): String = s
    closure($anonfun)
  }
  <accessor> def oo: Object => Object = {
    def $anonfun(o: Object): Object = o
    closure($anonfun)
  }
}
```

And after Erasure:

``` scala
class O() extends Object() { 
  <accessor> def ss(): Function1 = {
    def $anonfun(s: String): String = s
    closure($anonfun)
  }
  <accessor> def oo(): Function1 = {
    def $anonfun(o: Object): Object = o
    closure($anonfun:Function1)
  }
}
```

Notice that a type ascription `:Function1` is added to `oo` but not to `ss`, I'm not sure what the purpose of this annotation is or when it should be there, but this seems inconsistent. The rule for adding the annotation is in `typedClosure`:

``` scala
pt match {
  case SAMType(meth) if !defn.isFunctionType(pt) && mt <:< meth.info =>
```

Note that `isFunctionType` always return `false` in Erasure, because `pt` has been erased from `Function1[Foo, Bar]` to `Function1`, I don't know if this is intentional.

**Comment by odersky** [comment]
The idea is the type of a closure is a function type unless a type is given explicitly. The logic makes not much sense after erasure, but seems to do no harm either.
