### ISSUE TITLE
Failing to resolve to correct StringContext

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4732]
```scala
object StringContext {
  s"Hello"
}
```
fails to compile with Dotty and Scalac:
```scala
-- [E050] Reference Error: tests/allan/Test.scala:49:3 -------------------------
49 |  s"Hello"
   |   ^
   |   object StringContext does not take parameters
```

This is because the code snippet desugars to
```scala
StringContext("Hello").s()
```

Is this on purpose? An easy fix would be to desugar to `scala.StringContext("Hello").s()`

**Comment by SethTisue** [comment]
or `_root_.scala.StringContext` if you want to be really paranoid

**Comment by smarter** [comment]
This is intentional in scalac, but I agree that it's not a feature worth preserving: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/ast/parser/Parsers.scala#L1374-L1376
