### ISSUE TITLE
Unable to inline tailrec methods

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4737]
```scala
import annotation.tailrec
class Test {
  @inline @tailrec def rec(x: Int): Int = {
    if (x > 0) rec(x - 1)
    else 0
  }

  def bar = rec(100)
}
```

fails to compile with Dotty
```scala
-- Error: tests/allan/Test.scala:25:18 -----------------------------------------
25 |    if (x > 0) rec(x - 1)
   |               ^^^^^^^^^^
   |               Maximal number of successive inlines (32) exceeded,
   |               Maybe this is caused by a recursive inline method?
   |               You can use -Xmax:inlines to change the limit.
   | This location is in code that was inlined at tests/allan/Test.scala:25
```
Scalac does not have this limitation because inlining happens after the tailrec optimisation.

I believe this change of behavior might break a lot of code, and we should turn the error into a warning.

**Comment by smarter** [comment]
I think we should just not interpret `@inline` as it was equivalent to `inline` in Dotty. The latter has its own semantics that users need to be aware of when writing code.

**Comment by Blaisorblade** [comment]
New plan from weekly meeting: cross-compiling code should use a new `@forceInline` annotation, added to dotty-library, ignored by Scala 2 but supported by Dotty meaning `inline` (code that wants inlining cross-compiler could use `@inline @forceInline`).
