### ISSUE TITLE
dotr should exec scripts

### ISSUE THREAD

**Issue by TisonKun** [lampepfl/dotty#4747]
Consider script below

```scala
// script.scala
def truth(): Int = 42
println(truth())
```

In Scala, we can use command `scala` to exec it directly.

```
$ scala script.scala 
42
$ 
```

But `dotr` could not identify bare script, and it complains

```
$ dotr script.scala 
Error: Could not find or load main class script.scala
$ 
```

**Comment by TisonKun** [comment]
@smarter reminded of this issue, I wonder if dotty plans to support scripting. Sure it could be a compiled lang, but for wide use it would be awesome if support scripting. However, it would introduce extra complexity. What is the trade off dev team think of?

**Comment by liufengyun** [comment]
@TisonKun Initially, we plan to support features existent in Scalac. If you are looking for a scripting solution for Scala (e.g. handles dependencies), you can have a look like [Ammonite](https://github.com/lihaoyi/Ammonite).

**Comment by philwalk** [comment]
FWIW:
I just started playing with dotty after several years of scala scripting, and I hope the existing scripting behavior can be added back in at some point.

**Comment by TisonKun** [comment]
@liufengyun how's it going? Is it planned to be implemented in the future or we just reject it?

**Comment by liufengyun** [comment]
@TisonKun This is definitely to be supported. There are also some thoughts to make the scripts more powerful by standardizing some features in Ammonite:

- [ ] express source file dependencies
- [ ] express lib dependencies
- [x] @main functions https://github.com/lampepfl/dotty/pull/6898

However, we are currently focusing on other priorities. External contributions are welcome.

/cc : @AleksanderBG

**Comment by deanwampler** [comment]
+1 for fixing this. It's a major pain for us book writers who have most examples in script form.

**Comment by philwalk** [comment]
I have never been able to get ammonite to work in windows, whereas generic scala scripting works just fine, and I use it quite a bit.   My preference would be for script syntax to be 100% scalac compatible without special "script-only" syntax, which implies (among other things) that the compiler ignore a hash-bang line, and that scripts be permitted to declare a package.    I would be willing to contribute to this, fwiw.

**Comment by liufengyun** [comment]
@philwalk I think initially 100% scalac compatibility makes perfect sense. Contributions on this  will be much appreciated.

**Comment by bishabosha** [comment]
bump this issue
