### ISSUE TITLE
How to define Concat? (quantified TypeOf?)

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#4749]
After having made progress in well-typing `concat` in #4616, let's consider what we can do for its type. We want to be able to complete the definition

    type Concat[Xs <: HList, Ys <: HList] = ???

The requirement is that, for any `Xs, Ys, xs: Xs, ys: Ys`:

    concat(xs, ys) : Concat[Xs, Ys]

For concreteness, here's the definition of `concat`:

    transparent def concat(xs: HList, ys: HList): HList = xs match {
       case HNil => ys
       case HCons(x, xs1) => HCons(x, concat(xs1, ys))
    }

Here are some example typings, assuming

    as: HCons[Int, HNil]
    bs: HCons[String, HNil]
    cs: HList
:
  
     concat(as, bs) : HCons[Int, HCons[String, HNil]]
     concat(as, cs) : HCons[Int, HList]
     concat(cs, bs) : HList

The last typing demonstrates a case where the transparent `concat` method does not have enough information to proceed statically.

OK, so what about `Concat`? One possible way to define it would be through a new form of type pattern matching. Something along the lines of

    type Concat[Xs <: HList, Ys <: HList] = type Xs match {
      case HNil => Ys
      case HCons[type X, type Xs1] => HCons[X, Concat[Xs1, Ys]]
    }

That's OK as far as it goes, but raises the problem that `concat` and `Concat` are defined separately, using different techniques. That's an annoying duplication, and moreover raises the thorny issue how to convince the typechecker that the two different matches yield equivalent results. I don't really see a way to solve this. One might be tempted to define the term-level `concat` also using type matches, like this:

    transparent def concat[Xs, Ys](xs: Xs, ys: Ys): HList = type Xs match {
       case HNil => ys
       case HCons[_, type Xs1] => HCons(xs.head, concat(xs.tail, ys))
    }

But then `concat(cs, bs)` would have to be illegal, since it would rely on type information at runtime.

Here's another approach, which would rely on a generalized TypeOf. The most direct way to describe `Concat[Xs, Ys]` is: _the type of `concat(xs, ys)` if `xs: Xs` and `ys: Ys`_. So this is `TypeOf`, but under a set of assumptions, which can be expressed as an environment. Here's a potential way to express this idea directly in code:

    type Concat[Xs <: HList, Ys <: HList] = typeof { 
       val xs: Xs
       val ys: Ys
       concat(xs, ys) 
    }

The syntax is very provisional, there are lots of other choices. A shorter alternative, which pays for concision by being more syntactically confusing would be:

    { concat(xs, ys) | xs: Xs, ys: Ys }

What's important is that we are _quantifying_ TypeOf by introducing typed variables `xs`, `ys` without giving them values. The resulting type may not refer to the newly introduced variables, but this is already handled by Scala's avoidance rules which prevent a block's type from referring to its local definitions. 

Using the last definition of `Concat`, we'd get the following equalities:

    Concat[HCons[Int, HNil], HCons[String, HNil]]  =  HCons[Int, HCons[String, HNil]]
    Concat[HCons[Int, HNil], HList]                =  HCons[Int, HList]
    Concat[HList, HCons[String, HNil]]             =  HList

*Questions:* 

 - What do you think of quantified TypeOf?
 - What syntax should be used to express it?
 - Are there other ways writing `Concat` that we should explore?
 - Should there still be a place for pattern matching on types, or can we always go via the term level?

**Comment by odersky** [comment]
> Would { concat(xs, ys) | xs: Xs, ys: Ys } be any different from typing the body of concat(xs, ys) precisely and avoiding not only local bindings but also all the term-level parameters of concat?

Not sure I understand. Do you propose another way to define `Concat`? If yes, it would be good to write this down in detail.

**Comment by gsps** [comment]
I'm just trying to understand the semantics of the new solution. So what I meant to ask was: Would the resulting type `tp` of `{ concat(xs, ys) | xs: Xs, ys: Ys }` under the new scheme correspond to `concat`'s body typed dependently under the "old" scheme, followed by some extra type avoidance? That is, assuming `bodyTp` is the fully-dependently-typed body (à la `TypeOf`) of `concat[Xs, Ys](xs, ys)` and `termParams` are the term-param symbols of concat (`xs` and `ys`), would `tp` equal  `avoid(bodyTp, termParams)`?

**Comment by odersky** [comment]
@gsps Yes, that's the case. I believe it's implied by:

> The requirement is that, for any Xs, Ys, xs: Xs, ys: Ys:

>        concat(xs, ys) : Concat[Xs, Ys]

**Comment by OlivierBlanvillain** [comment]
As discussed offline, it's possible do to type only computation using a transparent def by "summoning fake values":

```scala
transparent def concat(xs: HList, ys: HList): HList = xs match {
   case HNil => ys
   case HCons(x, xs1) => HCons(x, concat(xs1, ys))
}

erased transparent def anyValue[T]: T = ??? : T

type AS = HCons[Int, HNil]
type BS = HCons[String, HNil]
type CS = { concat(anyValue[AS], anyValue[BS]) }

implicitly[CS <:< HCons[Int, HCons[String, HNil]]]
```
