### ISSUE TITLE
inline modifier rejected under Scala2 mode

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4762]
The following code snippet fails to compile under Scala2 mode:
```scala
class Foo {
  inline def foo = 1
}
```
```scala
dotc Foo.scala -language:Scala2
-- [E040] Syntax Error: Foo.scala:41:13 ---------------------------
41 |  inline def foo = 1
   |             ^^^
   |             ';' expected, but identifier found
-- [E006] Unbound Identifier Error: Foo.scala:41:2 ----------------
41 |  inline def foo = 1
   |  ^^^^^^
   |  not found: inline
```
The issue is that the scanner treats the `inline` keyword as an ident under Scala2 mode.

**Comment by allanrenucci** [comment]
We don't have the issue with enums:
```scala
enum Foo { case F0, F1 }
```
To fix this issue, one could have a look at how we handle enums and replicate the behavior to `inline`

**Comment by lightyang** [comment]
@allanrenucci this is due to [Scanner.scala:199](https://github.com/lampepfl/dotty/blame/master/compiler/src/dotty/tools/dotc/parsing/Scanners.scala#L199). And the commit(https://github.com/lampepfl/dotty/commit/d575e585389b025d7b8056bcb43fea67dddd15d0) says this was done intentionally.
What should be the expected behavior?

**Comment by allanrenucci** [comment]
Hum, indeed `inline` is treated as an identifier under `Scala2` mode as opposed to `enum` which is always treated as keyword. For instance under `Scala2` mode you cannot write:
```scala
class Foo {
  val enum = 1
}
```
@smarter What do you think? Should we treat `enum` like `inline` and parse it as an identifier under `Scala2` mode? But that would mean we can't write enums under this mode...

**Comment by smarter** [comment]
No, requiring users to put backquotes around enum is not a big deal. For inline, we should be able to support both @inline and inline since they can be distinguished by checking if there's an at or not.
