### ISSUE TITLE
Unsound optimization for disjunctions?

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#4784]
#4616 failed in test-optimized, until commit 91ca4ba50790b15

My conjecture is that the optimizer rewrites `E || true` to `true` even if `E` is side-effecting. This caused several tests under test-optimized to fail. once I changed the code to { E; true } everything compiles fine.

**Comment by allanrenucci** [comment]
We said we would remove these optimisations since they have no measurable effects on performance and consume a lot of CI time.

cc/ @OlivierBlanvillain
