### ISSUE TITLE
LambdaLift doesn't mark to-be static methods as such

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#480]
```
object O {
  val x: Function1[String, String] = a => a
  val x2: Function1[String, String] = a => "1"
}
```
After LambdaLift anonymous function for `x` isn't static, but for `x2` is static.

**Comment by DarkDimius** [comment]
`Ident(a)` is considered free in `x`

**Comment by DarkDimius** [comment]
I fixed this bug in https://github.com/dotty-staging/dotty/commit/f9dcaafbfb57f7ea57531b1b4a251ae5ac827ffc, by making `markFree` follow it's own contract.

Unfortunatelly but this seems to reveal a bug in `ExplicitOuter`: it ignores that closure invocation can capture something. https://github.com/dotty-staging/dotty/commit/287fd1a2044838654146568561d74543a2f0b761 shows this bug.

 
@odersky can you have a look? Am I missing something?

**Comment by odersky** [comment]
Yes, I saw that. Unfortunately the obvious fix breaks something else (might be an independent problem covered by this one). Will investigate.
