### ISSUE TITLE
Allow multiple splices in macros

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#4801]
We want to be able to write macros that have several top level splices such as

```scala
inline def foo(b: Boolean): Int = {
  if (b) ${bar(true)}
  else ${bar(false)}
}
def bar(b: Boolean)(using QuoteContext): Expr[Int] = if (b) '{1} else '{0}
```

**Comment by nicolasstucki** [comment]
To allow macros in classes and any non-static location this is a compromise we have to do.

**Comment by Blaisorblade** [comment]
Is the restriction documented?

**Comment by nicolasstucki** [comment]
Woking on it

**Comment by nicolasstucki** [comment]
This might actually be possible dot do.
