### ISSUE TITLE
Imprecise type inference on pattern

### ISSUE THREAD

**Issue by Medowhill** [lampepfl/dotty#4816]
```scala
import annotation.unchecked.uncheckedVariance

abstract class Type {
  def dealias: Type
}

object Trees {
  abstract class Tree[-T >: Null] {
    def tpe: T @uncheckedVariance = ???
  }

  case class AppliedTypeTree[-T >: Null]() extends Tree[T]
}

abstract class Instance[T >: Null <: Type] {
  type Tree = Trees.Tree[T]
  type AppliedTypeTree = Trees.AppliedTypeTree[T]
}

object untpd extends Instance[Null] {
  case class TypedSplice(tree: tpd.Tree) extends Tree

  def New(tpt: Tree): Type = tpt match {
    case TypedSplice(tpt1: AppliedTypeTree) => tpt1.tpe.dealias
    case _ => ???
  }
}

object tpd extends Instance[Type]
```
When I compiled the above code by scalac, it succeeded. However, when I used dotc, it failed with the following error message:
```scala
-- [E008] Member Not Found Error: Test.scala:24:56 -----------------------------
24 |    case TypedSplice(tpt1: AppliedTypeTree) => tpt1.tpe.dealias
   |                                               ^^^^^^^^^^^^^^^^
   |              value `dealias` is not a member of Null @uncheckedVariance
one error found
```
When I changed `tpt1: AppliedTypeTree` into `tpt1: tpd.AppliedTypeTree` in line 24, it was compiled successfully on both scalac and dotc.
Changing `tpt1: AppliedTypeTree` into `tpt1 @ Trees.AppliedTypeTree()` also worked.

I found this issue while working on issue #4557. Related PR can be found at #4798.

**Comment by Blaisorblade** [comment]
My initial analysis is that `tpt1` should be typed as `tpd.Tree & AppliedTypeTree`, that this simplifies to `Trees. AppliedTypeTree[Type]`, and that then `tpt1.tpe` should have type `Type` and not `Null`, so Scalac is right. Haven't verified what happens in Dotty.

**Comment by Medowhill** [comment]
A more simplified version:
```scala
trait A
trait B

object X {
  def unapply(x: Any): Option[A] = ???
}

trait T {
  0 match {
    case X(a: B) => a: A
    case _ =>
  }
}
```
Compiled in scalac, but failed in dotc with the following:
```scala
-- [E007] Type Mismatch Error: ../C1.scala:10:20 -------------------------------
10 |    case X(a: B) => a: A
   |                    ^
   |                    found:    B(a)
   |                    required: A
```
It looks like dotc infers `a` as `B` rather than `A & B`.

**Comment by smarter** [comment]
This is a known issue: https://github.com/lampepfl/dotty/issues/3208
