### ISSUE TITLE
Support Scala 2.13 standard library

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4843]
- [x] Compile the library
- [ ] Compile and run the library tests
- [x] Add it to the community build (and to our tests?)
- [x] Upstream changes to [scala/scala](https://github.com/scala/scala)

**Comment by allanrenucci** [comment]
Here is a list of incompatibilities between the 2.12 and 2.13 that will make cross compiling (without warning) with the 2.12 and 2.13 std lib difficult:
- `Stream` is deprecated in favor of `LazyList` which does not exist in 2.12. Most usages can probably be replaced by a strict collection or an `Iterator`
- `.zipped` is deprecated in favor `.lazyZip` which does not exist in 2.12.
- On `Map`, `mapValues` is deprecated in favor of `view.mapValues` which does not work in 2.12
- `mutable.SeqOps::transform` is deprecated in favor of `mapInPlace`  which does not exist in 2.12

Will update this comment when I find more.

**Comment by allanrenucci** [comment]
@sjrd since you're compiling Scala.js without warning on both 2.12 and 2.13, I would be happy to know if you had to workaround some of these issues

**Comment by sjrd** [comment]
* Don't use `Stream` nor `LazyList`. Use iterators.
* You can pimp `.lazyZip` on relevant collections. On 2.13 the "native" one will be used, and on 2.12 your pimp will be used.
* Use `map` instead of `mapValues`.
* Pimp `mapInPlace` on the old collections.
