### ISSUE TITLE
LambdaLift could capture less

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#487]
This is a proposal of optimization:

```
class F {
  val a = 1
  def f: Int => Int = _ + a
}
```

after lambdaLift becomes

```
class F extends Object {
    def <init>(): F = {
      super()
      this.a$$local = 1
      ()
    }
    private val a$$local: Int
    <accessor> def a(): Int = this.a$$local
    def f(): Function1 = {
      closure(this.$anonfun$f$1)
    }
    private def $anonfun$f$1(_$1: Int): Int = _$1.+(F.this.a())
  }
```

Instead of making `$anonfun$f$1` non-static, it could instead capture only `val a`, as it is immutable.

**Comment by DarkDimius** [comment]
This would also be an improvement over current state in scalac.

**Comment by retronym** [comment]
Watch out for uninitialized values:

```scala
class F extends G{
  val a = 1
  def f: Int => Int = {
    // {val aa = a; (x: Int) => x + aa} // proposed
    (x: Int) => x + a                   // current
  }
}
trait G {
  def f: Int => Int
  var g: Int => Int = null
  g = f
}

object Test {
  def main(args: Array[String]): Unit = {
    println(new F().g(0)) // current: 1, proposed: 0
  }
}
```

**Comment by retronym** [comment]
You'd also need to avoid premature initialization of lazy vals.

**Comment by liufengyun** [comment]
In addition to the pitfall pointed out by @retronym , there is another challenge -- a field access is actually a _method call_, which could be overriden in a child class:

```Scala
class F {
  val a = 1
  def f: Int => Int = _ + a
}

class G extends F {
  override val a = 2
}
```

Also note that inlining for literal types is already implemented. In the following code, the lambda becomes a static method:

```Scala
class F {
  final val a = 1
  def f: Int => Int = _ + a
}
```

The proposed optimization is difficult to implement safely. Close for now, revisit later.
