### ISSUE TITLE
Overriding a method with a inline method is inconstant

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#4892]
```scala
class Foo extends Bar {
  inline override def bar: Int = 2
}

class Bar {
  def bar: Int = 1
}

object Test {
  def main(args: Array[String]): Unit = {
    val a: Foo = new Foo
    val b: Bar = new Foo
    println(a.bar) // prints 2
    println(b.bar) // prints 1 but should print 2
  }
}
```

**Comment by Blaisorblade** [comment]
This isn't a "bug", only questionable semantics, since currently transparent methods aren't meant to be dispatches at runtime. And without runtime dispatch, we have no choice here:
```scala
def baz(b: Bar) = println(b.bar)
baz(new Foo) // must give 1
```

So here I'll abuse "stat:needs spec" for "we must pick our poison".

**Comment by nicolasstucki** [comment]
Then I would consider it `buggy semantics`. I would argue that either we have runtime semantics or we disallow overrides. #4860 gives the correct runtime semantics.

**Comment by nicolasstucki** [comment]
As discussed these are the semantics we want.
