### ISSUE TITLE
Parser accepts invalid input

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#4934]
```scala
object Foo {
  val a = "");
}
```

**Comment by Blaisorblade** [comment]
Apparently `acceptStatSepUnlessAtEnd` will swallow a token without reporting it, but most tokens I can think get swallowed by `expr()` first. There obvious fix seems to work (see 8fd36a6dd6fbf095a3d1ab8c91193bb4e8897ca0), but has cascade effects (and the code seems a bit fishy anyway).

```scala
object Test {
  val a = ""); // error

  val b = 1;

  val c = b); // error
}
```
