### ISSUE TITLE
sealed final abstract case object Foo

### ISSUE THREAD

**Issue by alexknvl** [lampepfl/dotty#4936]
Lots of modifiers are allowed on `object`s, but they do not seem to have any semantics.

In fact, you can have a
```scala
sealed final abstract case object Foo
```

But *sadly*
```scala
abstract object Foo {
  def x : String
}
```
doesn't compile, haha.

Perhaps those modifiers should be reported as errors?

**Comment by nafg** [comment]
I guess you meant does or shouldn't?

**Comment by alexknvl** [comment]
Updated the description :+1:

**Comment by nicolasstucki** [comment]
We should just add a warning on the redundant modifier.

**Comment by Blaisorblade** [comment]
@nicolasstucki Can you review #4973?

**Comment by nicolasstucki** [comment]
Yes
