### ISSUE TITLE
Inline methods with by-name arguments break debugging information

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#4947]
In the snippet below, setting breakpoints in `isSubType` is hard if it's compiled by Dotty, because all of isSubType appears written on line 100.

```scala
transparent def track(f: => T): T = { ... f ... }

def isSubType(...) = track { // line 100
  body
]
```

Probably should be addressed before bootstrap, hence tentatively targeting milestone 0.10.

**Comment by Blaisorblade** [comment]
@odersky can you take a look?

**Comment by nicolasstucki** [comment]
The same issue happens at runtime with the stack trace

```scala
object Foo {
  transparent def track[T](f: => T): T = f

  def main(args: Array[String]): Unit = {
    track {
      val a = 9
      ???
    }
  }

}
```

```
Exception in thread "main" scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:284)
	at Foo$.main(Foo.scala:5)
	at Foo.main(Foo.scala)
```

**Comment by smarter** [comment]
@nicolasstucki  That's a separate (and much harder to solve) issue, if your code is inlined in a method, you can't have the stacktrace show the methods that have been inlined. [JSR-45](https://jcp.org/en/jsr/detail?id=45)  (that the [Scala Center was supposed to implemented](https://github.com/scala/scala.epfl.ch/issues/47)) should help in theory but I don't think it's used for stacktraces.

**Comment by smarter** [comment]
Actually JSR-45 is relevant for the original issue from @Blaisorblade too: without implementing it, there is no way to preserve line information for debugging when inlining across files.

**Comment by nicolasstucki** [comment]
No, in this case we lose the position of code that was in the current method (not inlined code). The position of the tree of `???` should not be lost while inlining it in the code of `track`.
