### ISSUE TITLE
URL to the intro paper on DOT is broken

### ISSUE THREAD

**Issue by npdeep** [lampepfl/dotty#4981]
In `README.md` the URL to [DOT](http://www.cs.uwm.edu/~boyland/fool2012/papers/fool2012_submission_3.pdf) is broken. Should be replaced by [DOT](http://www.cs.uwm.edu/faculty/boyland/fool2012/papers/fool2012_submission_3.pdf).

**Comment by npdeep** [comment]
My bad. I was looking at the older https://github.com/odersky/dotty

**Comment by Blaisorblade** [comment]
No problem, thanks for taking interest; later papers are linked [here](https://github.com/TiarkRompf/minidot/blob/5d8a895119711f3992ec189903848ee818cc5b02/README.md), maybe we should cite some of those.
