### ISSUE TITLE
Parsing issue with do while loops

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#4989]
```scala
class Test {
  def test = {
    var rest: List[Int] = ???
    do {}
    while (rest ne Nil)
    {println("Hello")}
  }
}
```
```scala
-- [E050] Reference Error: Test.scala:59:11 ------------------------
59 |    while (rest ne Nil)
   |           ^^^^^^^^^^^
   |           method ne in class Object does not take more parameters
```

**Comment by odersky** [comment]
It's an interesting interaction between SIP 12 and semicolon inference. Scala parses e.g.
```
   f(x)
   {y}
```
as one expression. I.e. it does swallow the inferred line end between the `)` and the `{`. Both `scalac` and `dotc` do that. The difference is that `dotc` implements SIP 12, so tries to parse
```scala 
    (rest ne Nil)
    {println("Hello")}
```
as one expression, and succeeds with that. We should think of a tweak to avoid that.

**Comment by nicolasstucki** [comment]
`do { <body> } while (<cond>)` is no longer supported. Use `while ({<body> ; <cond>}) ()`.
