### ISSUE TITLE
Replace hardcoded uses of ":" by File.pathSeparator

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5000]
":" is used in various places in the codebase, this is wrong (it doesn't work on Windows) and should be replaced by [File.pathSeparator](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#pathSeparator)

**Comment by Blaisorblade** [comment]
Some progress in #5085 by @martijnhoekstra, but they suggest we shouldn’t be closing this yet.

**Comment by martijnhoekstra** [comment]
@Blaisorblade I would suggest closing this for now -- I can't promise there are absolutely no hardcoded strings containing `:` remaining, though I reviewed all strings `":"` and chars `':'`, there may still be `"foo:bar"`'s that are harder to find -- but this issue isn't actionable anymore I think

**Comment by martijnhoekstra** [comment]
in scala, the platform-dependency issues tend to be

* Classpath separators (like here)
* checking for path separators '/' (though using '/' is fine)
* line endings. the difference between `\r\n` and `\n` represents a semantic difference if the line end is part of a multiline string, and println will emit `\r\n` on windows. Adding insult to injury, if windows users have git autocrlf set (out of dubious claims of compatibility) they may have crlf in their local repos where there is no such \r present in the original source.

Ironically, many issues occur when one part of some system attempts to do platform compatibility for unneeded reasons (java println, git autoclrf, auto-conversion of /), and other parts don't, and then suddenly you have situations where you're checking for \r\n on windows while there is a \n which is working just fine, leading to errors or test failures.

**Comment by Blaisorblade** [comment]
Closing on @martijnhoekstra’s recommendation.
