### ISSUE TITLE
Empty enum bodies are accepted

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#5015]
After `enum A extends AnyRef` the REPL thinks the line is not over and requires braces. The REPL should instead do the same it does for classes:
```scala
scala> class A extends AnyRef
// defined class A

scala> enum A extends AnyRef
     | {}
// defined class A
```
(noticed while testing #5008).

EDIT: `enum A extends AnyRef {}` is forbidden by the grammar, see below.

**Comment by allanrenucci** [comment]
This is a parser issue:
```scala
enum Foo extends AnyRef
```
```scala
-- [E040] Syntax Error: tests/allan/Test.scala:99:23 ---------------------------
99 |enum Foo extends AnyRef
   |                       ^
   |                       '{' expected, but eof found
```

**Comment by allanrenucci** [comment]
Shouldn't we require enum to be non empty anyway?

**Comment by Blaisorblade** [comment]
Oh right, that's actually required by the [grammar](http://dotty.epfl.ch/docs/internals/syntax.html):
```
EnumDef           ::=  id ClassConstr [‘extends’ [ConstrApps]] EnumBody
EnumBody          ::=  [nl] ‘{’ [SelfType] EnumStat {semi EnumStat} ‘}’
EnumStat          ::=  TemplateStat
                    |  {Annotation [nl]} {Modifier} EnumCase
EnumCase          ::=  ‘case’ (id ClassConstr [‘extends’ ConstrApps]] | ids)
```

We should additionally require at least one EnumCase (in either Parser or Desugar), lest people write

```scala
enum Root {
  case class Foo()
}
```

Defining case classes inside enums is legal but is most likely a typo. It seems hard to forbid (for consistency reasons) since enums can have arbitrary members, tho maybe we should anyway — this looks very much likely a future wart.

**Comment by odersky** [comment]
I think there are a number of issues to work out:

 - Parsing `enum Foo` as `enum Foo {}`, this was the essence of #5015, which got fixed in a differnt way.
 - Removing the error message
 - Fixing all code that depends on enumCases being non-empty. For instance, I see this in `Desugar.scala`

   ```scala
             enumCases.last.pushAttachment(DesugarEnums.DefinesEnumLookupMethods, ())
   ```
