### ISSUE TITLE
Is PartialFunction a SAM?

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#504]
In order to implement a `PartialFunction` one needs to define both 

```
def isDefinedAt(x: T)
def apply(x: T)
```
 so there are two abstract methods. 

`PartialFunction` currently is treated specially,
https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/core/Types.scala#L2723-L2730
forcing it to be treated as a SAM.

The comment says that 
```     
// In the future it would be better to merge
// Function and PartialFunction, have Function1 contain a isDefinedAt method
//     def isDefinedAt(x: T) = true
// and overwrite that method whenever the function body is a sequence of
// case clauses.
```
The comment means that `Function1` instances which are `PartialFunctions` could not be `SAMs` as they need to override a method.

**Comment by odersky** [comment]
Yes, I think that's the consequence. Need to evaluate implementation
complexity of this approach.

On Tue, Apr 28, 2015 at 10:28 AM, Dmitry Petrashko <notifications@github.com
> wrote:

> In order to implement a PartialFunction one needs to define both
>
> def isDefinedAt(x: T)
> def apply(x: T)
>
> so there are two abstract methods.
>
> PartialFunction currently is treated specially,
>
> https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/core/Types.scala#L2723-L2730
> forcing it to be treated as a SAM.
>
> The comment says that
>
> // In the future it would be better to merge
> // Function and PartialFunction, have Function1 contain a isDefinedAt method
> //     def isDefinedAt(x: T) = true
> // and overwrite that method whenever the function body is a sequence of
> // case clauses.
>
> The comment means that Function1 instances which are PartialFunctions
> could not be SAMs as they need to override a method.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/504>.
>



-- 
Martin Odersky
EPFL

**Comment by odersky** [comment]
I'll take a look at this now. Will try to write a phase that converts partial functions (and some other "false" SAMs) to anonymous classes.

**Comment by retronym** [comment]
I think that's a good tool to have; we fall back to this translation in `indylambda` when the delambdafy transform would be lift the lambda body into a method in a way that leads to `VerifyError`. This is done for lambdas in super-contructor call position: https://github.com/scala/scala/pull/3616

**Comment by odersky** [comment]
Jason,

I thought at first we could just restrict SAM lambdas not to use super
accessors (or fields, or outer pointers). But it would indeed be nicer to
the user and easier to specify to deal with it in the translations.

 - Martin

On Wed, Apr 29, 2015 at 6:35 AM, Jason Zaugg <notifications@github.com>
wrote:

> I think that's a good tool to have; we fall back to this translation in
> indylambda when the delambdafy transform would be lift the lambda body
> into a method in a way that leads to VerifyError. This is done for
> lambdas in super-contructor call position: scala/scala#3616
> <https://github.com/scala/scala/pull/3616>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/504#issuecomment-97301246>.
>



-- 
Martin Odersky
EPFL

**Comment by retronym** [comment]
We envision adding support for Java's `@FunctionalInterface` annotation to help the programmer to opt in to those restrictions when defining a trait.

**Comment by DarkDimius** [comment]
#509. PartialFunction is not a Sam for JVM, we silently expand it to anonymous class.
