### ISSUE TITLE
Remove unnececary boxing in  `a.synchronized(1)`

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#505]
Both Scalac and Dotty assume that `synchronized` takes and returns an Object after erasure. 
Actually it doesn't so there's no need to box.
We could potentially leave synchronized as a polymorphic method after erasure and save a bit on GC pressure and bytecode size.

**Comment by smarter** [comment]
Fixed in scalac: https://github.com/scala/scala/commit/92d1af11b04b4f7c8aafd4ff911bf747eb1029aa

**Comment by allanrenucci** [comment]
Raising the priority since it affects thread safe lazy vals. For example:
```scala
def test = {
  lazy val foo = 1
  ...
}
```
compiles to:
```scala
def test = {
  lazy var foo$lzy1: dotty.runtime.LazyInt = new dotty.runtime.LazyInt()
  def foo$lzyINIT1(): Int =
    Int.unbox(
      foo$lzy1.synchronized(
        Int.box(
          if foo$lzy1.initialized() then foo$lzy1.value() else
            {
              foo$lzy1.value_=(1)
              foo$lzy1.initialized_=(true)
              foo$lzy1.value()
            }
        )
      )
    )
  def foo(): Int =
    if (foo$lzy1.initialized()) foo$lzy1.value() else foo$lzyINIT1()
  ...
}
```
