### ISSUE TITLE
option to not erase during test phase

### ISSUE THREAD

**Issue by drdozer** [lampepfl/dotty#5087]
re: https://gitter.im/lampepfl/dotty?at=5b91842ecff55e5617b9578f

While the erasure functionality will have a big positive impact upon run-time performance and API design, erasing the defs that supply 'proofs' potentially allows broken or un-implemented code through to production. Consider:

```scala
implicit erased def [T] oddIsEven(implicitly isOdd: IsOdd[T]): IsEven[T] = ???
```

This is clearly a broken assumption, but the implementor has taken advantage of the implementation being erased to stub it in with `???` so that there's no run-time symptom.

There are related corner cases where a recursive proof lacks a termination state. Where it loops endlessly or in some fancy explosive fashion. As we move more of the soundness checks of programs into erased implicits, this gap in the run-time semantics may lead to a tendency to have apparently sound code fail because the proofs of soundness via the erased implicits were actually not proving anything.

The fix for this is to have erased code not erased in certain phases of deployment. For example, it would make sense not to erase values during testing. Tests would be run with non-erased code-paths, meaning that the proofs are constructed at that stage. Then in run-time, the erased version would be used.

There is a possible cascade here, as there was for scala-2-style specialisation, where for testing across artifact boundaries, you'd need the non-erased artifacts for all the erasure pathways that the code being tested uses. This potentially means publishing an `-erased` version of each artifact.

Alternatively, perhaps the non-erased code and types can be packaged into the tasty, and then some linker phase or class loader trickery can let us deploy one set of artifacts that are erased, but load them in an environment that unerases them when running tests or debugging.

I don't want to provide an implementation strategy, but the requirement is to be able to choose to run code (and the code it depends upon) with and without erasure, and for this choice to be fairly dynamic e.g. chosen differently in different sbt phases.

**Comment by OlivierBlanvillain** [comment]
That's an interesting idea but would require a complete redesign of `erased`. I'm going to close it for now in the interest of keeping the issue queue manageable. @drdozer (or anyone else) feel free to reopen of you intend to work on an implementation.
