### ISSUE TITLE
Allow overloads in imports

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#5088]
Fundamentally, the reason why Scala FP has gone down the route of using implicit classes for syntax is because it is not possible to import two symbols from different import statements, that have the same name. Consider:

```scala
trait Applicative[F[_]]
object Applicative {
  def map[F[_]: Applicative, A, B](fa: F[A])(f: A => B): F[B]
}

trait Monad[F[_]]
object Monad {
  def map[F[_]: Monad, A, B](fa: F[A])(f: A => B): F[B]
}

import Monad.map
import Applicative.map
```

bang, symbol shadowing.

But it is possible to explicitly define 

```scala
  def map[F[_]: Applicative, A, B](fa: F[A])(f: A => B): F[B]
  def map[F[_]: Monad, A, B](fa: F[A])(f: A => B): F[B]
```

and use them within the same compilation unit.

I think it would be very beneficial if imports allowed method overloading and shadowing only occurs for **exact** matches.

------

I commented there:
> FWIW, there should be a scalac issue (that I can't find sadly) about the same proposal for scalac where this was rejected because. But this might be feasible in Dotty's design maybe? At least, it seems a MultiDenotation can represent an overload of symbols from different prefixes.

----

Context: Reopened from #4374 (it's a fresh ticket for special reasons given there, feel free to ignore). And discussed briefly with @smarter at scalasphere.

**Comment by odersky** [comment]
This looks really hard. The danger is that it will combine concerns that should be separate into a big ball of mud. The ramifications for spec, compiler complexity and compiler speed are very hard to estimate, but likely to be significant.

**Comment by odersky** [comment]
So, this would require a SIP with a prototype implementation. Greatly exceeds the scope of an issue.
