### ISSUE TITLE
Macro based string interpolation

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5095]
The goal of this issue is to discuss how one could implement a macro based string interpolator similar to [densh/joyquote](https://github.com/densh/joyquote):

Let's consider an hypothetical xml interpolator.

In Scala 2, one can write:
```scala
implicit class XmlQuote(val sc: StringContext) {
  def xml(args: Any*): Xml = macro QuoteImpl.apply
}

class QuoteImpl(val c: blackbox.Context) {
  import c.universe._
  def apply(args: Tree*): Tree = ???
}
```

Let's see how this could translate to Dotty macros. A naive translation would be:
```scala
import scala.quoted._
import scala.tasty.Tasty

implicit class XmlQuote(val sc: StringContext) {
  rewrite def xml(args: Any*): Xml = ~QuoteImpl.apply('(ctx), '(args))
}

object QuoteImpl {
  def apply(ctx: Expr[StringContext], args: Expr[Seq[Any]])(implicit tasty: Tasty): Expr[Xml] = ???
}
```
The issue with this approach is that the `apply` macro doesn't see the tree for `ctx` and `args` as they are lifted out by the compiler and we only see references to the lifted values. To prevent parameters from being lifted out, one needs to make them by name:
```scala
import scala.quoted._
import scala.tasty.Tasty

implicit rewrite def XmlQuote(ctx: => StringContext): XmlQuote = new XmlQuote(ctx)

class XmlQuote(val sc: StringContext) {
  rewrite def xml(args: => Any*): Xml = ~QuoteImpl.apply('(ctx), '(args))
}

object QuoteImpl {
  def apply(ctx: Expr[StringContext], args: Expr[Seq[Any]])(implicit tasty: Tasty): Expr[Xml] = ???
}
```

**Comment by odersky** [comment]
That looks like a good solution to me!

**Comment by allanrenucci** [comment]
#5096 implements the proposed solution. However, one should not need to make arguments by name to be able inspect the argument trees. So the proper solution should be:
```scala
import scala.quoted._
import scala.tasty.Tasty

implicit class XmlQuote(val sc: StringContext) {
  rewrite def xml(args: Any*): Xml = ~QuoteImpl.apply('(ctx), '(args))
}

object QuoteImpl {
  def apply(ctx: Expr[StringContext], args: Expr[Seq[Any]])(implicit tasty: Tasty): Expr[Xml] = ???
}
```
Closing in favor of #5132
