### ISSUE TITLE
Memory analisys. Not a bug but a discussion and a record of data

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#510]
Interesting moments that I want to share:

[Definition of retained size](https://www.yourkit.com/docs/java/help/sizes.jsp)

After compiling dotty by dotty:
Total size of input source files: 3M 
Total retained size of InitialContext: 25M
Total retained size of `ContextBase` object: 70M, amoug those:
- dotty.tools.dotc.core.Uniques$RefinedUniques: 13M
- dotty.tools.dotc.core.Contexts$ContextState$$anon$1 12M
- dotty.tools.dotc.core.Uniques$TypeAliasUniques 5M

Average size of compilation unit: 2.5M <-- will fix this in next commit.

Total size of name table: 10M

Objects allocated in phase: 
- 48% of allocated objects are allocated in TreeChecker(I ran with "-Ycheck:tailrec,resolveSuper,mixin,restoreScopes"). But they constitute only 4% of total allocated size.
- 25% by all miniphases in total. Hard to get which mini-phase ones actually did the allocation, as many are allocated by the framework itself.
- 16% in Typer;
- 3% in Erasure;
- 2% in parser;
- <1% in namer;
- <1% in GenBCode

Trees allocated by frontend(parser + typer):

| Node | % of all trees |
| --- | --- |
| dotty.tools.dotc.ast.Trees$Ident | 0.3146870081 |
| dotty.tools.dotc.ast.Trees$Apply | 0.2194938855 |
| dotty.tools.dotc.ast.Trees$Select | 0.1940912943 |
| dotty.tools.dotc.ast.Trees$TypeTree | 0.1101586148 |
| dotty.tools.dotc.ast.Trees$ValDef | 0.0763772854 |
| dotty.tools.dotc.ast.Trees$Modifiers | 0.0691124834 |
| dotty.tools.dotc.ast.Trees$This | 0.0564959438 |
| dotty.tools.dotc.ast.Trees$Block | 0.046567381 |
| dotty.tools.dotc.ast.Trees$DefDef | 0.0409008355 |
| dotty.tools.dotc.ast.Trees$Literal | 0.0294950963 |
| dotty.tools.dotc.ast.Trees$CaseDef | 0.0217459741 |
| dotty.tools.dotc.ast.Trees$Typed | 0.017798765 |
| dotty.tools.dotc.ast.Trees$If | 0.0163942366 |
| dotty.tools.dotc.ast.Trees$TypeApply | 0.0131735077 |
| dotty.tools.dotc.ast.Trees$Bind | 0.0123743795 |
| dotty.tools.dotc.ast.Trees$TypeDef | 0.0096379707 |
| dotty.tools.dotc.ast.Trees$New | 0.0083060903 |
| dotty.tools.dotc.ast.Trees$Assign | 0.0079428502 |
| dotty.tools.dotc.ast.Trees$AppliedTypeTree | 0.0075069621 |
| dotty.tools.dotc.ast.Trees$Match | 0.0067078339 |
| dotty.tools.dotc.ast.Trees$Closure | 0.0062235137 |
| dotty.tools.dotc.ast.Trees$Template | 0.0059813537 |
| dotty.tools.dotc.ast.Trees$SeqLiteral | 0.0059571377 |
| dotty.tools.dotc.ast.Trees$Import | 0.0050611454 |
| dotty.tools.dotc.ast.Trees$UnApply | 0.003583969 |
| dotty.tools.dotc.ast.Trees$PackageDef | 0.0017677685 |
| dotty.tools.dotc.ast.Trees$NamedArg | 0.0015982564 |
| dotty.tools.dotc.ast.Trees$TypeBoundsTree | 0.0011139363 |
| dotty.tools.dotc.ast.Trees$SingletonTypeTree | 0.0009928563 |
| dotty.tools.dotc.ast.Trees$Return | 0.0008475602 |
| dotty.tools.dotc.ast.Trees$Thicket | 0.0007022642 |
| dotty.tools.dotc.ast.Trees$Alternative | 0.0004843201 |
| dotty.tools.dotc.ast.Trees$Annotated | 0.0004843201 |
| dotty.tools.dotc.ast.Trees$Super | 0.0002905921 |
| dotty.tools.dotc.ast.Trees$ByNameTypeTree | 0.0002663761 |
| dotty.tools.dotc.ast.Trees$Try | 0.0002663761 |
| dotty.tools.dotc.ast.Trees$RefinedTypeTree | 0.000048432 |
| dotty.tools.dotc.ast.Trees$AndTypeTree | 0.000024216 |
| dotty.tools.dotc.ast.Trees$Pair | 0.000024216 |

**Comment by DarkDimius** [comment]
Interestingly, the picture changes a bit by backend. Here are the retained stats by GenBCode:

| Class                                         |      % of all trees                 | Objects |
|-----------------------------------------------|-----------------------|---------|
| dotty.tools.dotc.ast.Trees$Apply              | 0.1927567893          | 320372  |
| dotty.tools.dotc.ast.Trees$Ident              | 0.1820314996          | 302546  |
| dotty.tools.dotc.ast.Trees$Select             | 0.1412722699          | 234802  |
| dotty.tools.dotc.ast.Trees$TypeTree           | 0.1101812036          | 183127  |
| dotty.tools.dotc.ast.Trees$ValDef             | 0.0727395576          | 120897  |
| dotty.tools.dotc.ast.Trees$Block              | 0.050510423           | 83951   |
| dotty.tools.dotc.ast.Trees$DefDef             | 0.0433421798          | 72037   |
| dotty.tools.dotc.ast.Trees$This               | 0.0322655174          | 53627   |
| dotty.tools.dotc.ast.Trees$Modifiers          | 0.0320146229          | 53210   |
| dotty.tools.dotc.ast.Trees$Literal            | 0.0213296447          | 35451   |
| dotty.tools.dotc.ast.Trees$TypeApply          | 0.0210637086          | 35009   |
| dotty.tools.dotc.ast.Trees$If                 | 0.0171029444          | 28426   |
| dotty.tools.dotc.ast.Trees$CaseDef            | 0.0152768895          | 25391   |
| dotty.tools.dotc.ast.Trees$Typed              | 0.0097951148          | 16280   |
| dotty.tools.dotc.ast.Trees$TypeDef            | 0.0076014423          | 12634   |
| dotty.tools.dotc.ast.Trees$New                | 0.0067699405          | 11252   |
| dotty.tools.dotc.ast.Trees$Assign             | 0.0063692313          | 10586   |
| dotty.tools.dotc.ast.Trees$Bind               | 0.0055997011          | 9307    |
| dotty.tools.dotc.ast.Trees$Template           | 0.0055858628          | 9284    |
| dotty.tools.dotc.ast.Trees$Match              | 0.0055299079          | 9191    |
| dotty.tools.dotc.ast.Trees$Closure            | 0.0036701597          | 6100    |
| dotty.tools.dotc.ast.Trees$AppliedTypeTree    | 0.0030564609          | 5080    |
| dotty.tools.dotc.ast.Trees$UnApply            | 0.0024439654          | 4062    |
| dotty.tools.dotc.ast.Trees$Import             | 0.0023693589          | 3938    |
| dotty.tools.dotc.ast.Trees$SeqLiteral         | 0.0021888592          | 3638    |
| dotty.tools.dotc.ast.Trees$PackageDef         | 0.0017622783          | 2929    |
| dotty.tools.dotc.ast.Trees$Super              | 0.0015288321          | 2541    |
| dotty.tools.dotc.ast.Trees$JavaSeqLiteral     | 0.0009897398          | 1645    |
| dotty.tools.dotc.ast.Trees$NamedArg           | 0.0005806072          | 965     |
| dotty.tools.dotc.ast.Trees$TypeBoundsTree     | 0.000525254           | 873     |
| dotty.tools.dotc.ast.Trees$Return             | 0.0003712276          | 617     |
| dotty.tools.dotc.ast.Trees$Try                | 0.000347161           | 577     |
| dotty.tools.dotc.ast.Trees$SingletonTypeTree  | 0.0003038411          | 505     |
| dotty.tools.dotc.ast.Trees$Alternative        | 0.0002220146          | 369     |
| dotty.tools.dotc.ast.Trees$Thicket            | 0.000192533           | 320     |
| dotty.tools.dotc.ast.Trees$ByNameTypeTree     | 0.0001347731          | 224     |
| dotty.tools.dotc.ast.Trees$Annotated          | 0.0001239431          | 206     |
| dotty.tools.dotc.ast.Trees$BackquotedIdent    | 0.00002166            | 36      |
| dotty.tools.dotc.ast.Trees$RefinedTypeTree    | 1.20333106104318E-005 | 20      |
| dotty.tools.dotc.ast.Trees$Pair               | 9.62664848834544E-006 | 16      |
| dotty.tools.dotc.ast.Trees$SelectFromTypeTree | 6.0166553052159E-006  | 10      |
| dotty.tools.dotc.ast.Trees$AndTypeTree        | 1.20333106104318E-006 | 2       |

**Comment by DarkDimius** [comment]
Biggest used size of a TreeBuffer: `58221`

**Comment by retronym** [comment]
Great to see you measuring. You might be interested in my [notes](https://gist.github.com/retronym/86ec6ad9ccd2c22f6148) about benchmark tooling and tuning possibilities here in a Scalac context.

**Comment by DarkDimius** [comment]
@retronym Nice document, and I have some answers for questions that you have here:

> Intel VTune
> TODO: what can we learn from hardware counters?

Answer: measure saturation of memory channels, measure cache hits\misses, measure how many memory barriers you have.
That's actually my tool-of-choice for low-level profiling. For high-level I use YourKit.

I have no experience with JFR. Was it worth time? where you able to actually find anything interesting with it?

FYI:
> Run suite against each tag of Scala, persist and visualize the results

In dotty, we make each unit-test into a benchmark. This doesn't show much but should allow us to discover regressions.  http://goo.gl/Zspor0

**Comment by retronym** [comment]
I started using Linux's `perf` to get an look at hardware counters (haven't managed to get VTune installed yet, and probably can't rely on it long term without purchasing it.) I used Javac as a benchmark for efficient use of hardware for a compiler and looked for glaring differences with Scalac. My first pass didn't reveal too much, but it will be worth repeating.

JMH has nice integration with `perf`, it can automatically gather profile data for a given benchmark.

JFR seems quite useful, even if only to cross-check what you are seeing with YourKit. I explored it after a recommendation of a member of Oracle's Java performance team. It was pretty straight forward to enable (and I've documented the parts that took me some time to figure out.) The visualization of results through Java Mission Control is not as powerful as YourKit.

AFAIU, YourKit still suffers from the safepoint biasing, whereas JFR can (cheaply)capture its thread dumps at any moment by using internal data structures of the JVM. It also offers interesting insights into allocation behaviour, differentiating allocations that use the TLAB vs ones that go directly to the eden space. And importantly, these allocation stats can be gathered without impacting performance too much.

**Comment by jvican** [comment]
Very useful information here. Just tried to use some of it to further optimize dotty by changing the order of the pattern match in `TreeTraverser`. Unfortunately, it's not worth it--the HotSpot JVM performs branch reordering in C2. While I knew this from the beginning, I was hoping that the JVM would give up to optimize `traverse` for highly-nested if branches. It seems that's not the case, though.
  
I used JMH to check this inside Dotty (but it failed because of [SI-2034](https://issues.scala-lang.org/browse/SI-2034)). I created my own benchmarks in an isolated environment simulating the traverser and the tree structure. For different loads of cpu consumption, the results are:
```
[info] # Run complete. Total time: 00:07:27
[info] 
[info] Benchmark                              (tokens)  Mode  Cnt        Score        Error  Units
[info] JmhControlBenchmark.baselineBranching         0  avgt    5   732769.022 ±  10264.314  ns/op
[info] JmhControlBenchmark.baselineBranching         1  avgt    5   743108.330 ±  16008.120  ns/op
[info] JmhControlBenchmark.baselineBranching         2  avgt    5   747955.970 ±  21499.842  ns/op
[info] JmhControlBenchmark.baselineBranching         3  avgt    5   767308.354 ±  13159.772  ns/op
[info] JmhControlBenchmark.baselineBranching         4  avgt    5   749743.133 ±  17810.649  ns/op
[info] JmhControlBenchmark.baselineBranching         5  avgt    5   752648.458 ±  10091.876  ns/op
[info] JmhControlBenchmark.baselineBranching         6  avgt    5   773102.983 ±  15028.148  ns/op
[info] JmhControlBenchmark.baselineBranching         7  avgt    5   787853.559 ±  16339.609  ns/op
[info] JmhControlBenchmark.baselineBranching         8  avgt    5   798662.334 ±  16877.735  ns/op
[info] JmhControlBenchmark.baselineBranching         9  avgt    5   720786.471 ±  17524.017  ns/op
[info] JmhControlBenchmark.baselineBranching        10  avgt    5   792037.957 ±  14490.942  ns/op
[info] JmhControlBenchmark.baselineBranching        11  avgt    5   813794.592 ±  17022.414  ns/op
[info] JmhControlBenchmark.baselineBranching        12  avgt    5   850145.028 ±  49212.391  ns/op
[info] JmhControlBenchmark.baselineBranching        13  avgt    5   855073.694 ± 114171.722  ns/op
[info] JmhControlBenchmark.baselineBranching        14  avgt    5   839173.536 ±  14797.595  ns/op
[info] JmhControlBenchmark.baselineBranching        15  avgt    5   890053.747 ±  74672.020  ns/op
[info] JmhControlBenchmark.baselineBranching        16  avgt    5   902397.821 ±  30988.518  ns/op
[info] JmhControlBenchmark.baselineBranching        17  avgt    5   906300.848 ±   8305.676  ns/op
[info] JmhControlBenchmark.baselineBranching        18  avgt    5   925920.306 ±  17716.849  ns/op
[info] JmhControlBenchmark.baselineBranching        19  avgt    5   962990.291 ±  17204.715  ns/op
[info] JmhControlBenchmark.baselineBranching        20  avgt    5   989585.441 ±  25488.349  ns/op
[info] JmhControlBenchmark.branching                 0  avgt    5   725317.946 ±   7490.305  ns/op
[info] JmhControlBenchmark.branching                 1  avgt    5   766277.793 ±  69998.017  ns/op
[info] JmhControlBenchmark.branching                 2  avgt    5   739225.373 ±   8431.428  ns/op
[info] JmhControlBenchmark.branching                 3  avgt    5   766302.204 ±  13754.987  ns/op
[info] JmhControlBenchmark.branching                 4  avgt    5   765012.481 ±  21640.310  ns/op
[info] JmhControlBenchmark.branching                 5  avgt    5   771277.334 ±  17007.720  ns/op
[info] JmhControlBenchmark.branching                 6  avgt    5   799573.045 ±  47252.057  ns/op
[info] JmhControlBenchmark.branching                 7  avgt    5   793847.477 ±   9049.100  ns/op
[info] JmhControlBenchmark.branching                 8  avgt    5   809854.907 ±   9313.775  ns/op
[info] JmhControlBenchmark.branching                 9  avgt    5   807319.708 ±  14209.984  ns/op
[info] JmhControlBenchmark.branching                10  avgt    5   862227.507 ±  21593.662  ns/op
[info] JmhControlBenchmark.branching                11  avgt    5   847191.602 ±  27205.998  ns/op
[info] JmhControlBenchmark.branching                12  avgt    5   853538.026 ±  36371.974  ns/op
[info] JmhControlBenchmark.branching                13  avgt    5   870946.283 ±  32586.544  ns/op
[info] JmhControlBenchmark.branching                14  avgt    5   883153.977 ±   9581.862  ns/op
[info] JmhControlBenchmark.branching                15  avgt    5   905447.680 ±  14705.452  ns/op
[info] JmhControlBenchmark.branching                16  avgt    5   913426.087 ±  13505.457  ns/op
[info] JmhControlBenchmark.branching                17  avgt    5   953519.280 ±  16234.717  ns/op
[info] JmhControlBenchmark.branching                18  avgt    5   955978.704 ±  32029.223  ns/op
[info] JmhControlBenchmark.branching                19  avgt    5   976908.466 ±  32900.328  ns/op
[info] JmhControlBenchmark.branching                20  avgt    5  1013681.986 ±   8531.338  ns/op

```
In `branching`, the order of the pattern match ensures that the last `case` succeeds. Conversely, the baseline succeds in the first `case`. Every of them runs the pattern match 10000 times. The results, as you see, are the same.
  
I leave this report here just for the record.
