### ISSUE TITLE
Macro does not always elide its receiver

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5110]
Let's consider the following macro based string interpolator
```scala
import scala.quoted._
import scala.tasty.Tasty

object Macro {
  class StringContextOps(sc: StringContext) {
    rewrite def ff(args: => Any*): String = ~Macro.impl('(sc), '(args))
  }
  implicit rewrite def XmlQuote(sc: => StringContext): StringContextOps = new StringContextOps(sc)
  def impl(sc: Expr[StringContext], args: Expr[Seq[Any]])(implicit tasty: Tasty): Expr[String] = '("")
}
```
And the following use case:
```scala
class Test {
  import Macro._
  def test = ff"Hello World"
}
```
which expands to:
```scala
class Test {
  def test: String = {
    // start dead code
    val $1$: Macro.Macro$StringContextOps =
      new Macro.Macro$StringContextOps(
        _root_.scala.StringContext.apply(
          Predef.wrapRefArray(["Hello World" : String])
        )
      )
    // end dead code

    // expansion
    ""
  }
}
```
My expectation (and how it works in Scala 2) is that the receiver of the macro gets elided

**Comment by sjrd** [comment]
The receiver is not by-name, so it cannot be elided.

**Comment by nicolasstucki** [comment]
In general we must not elide the receiver or else we would change the semantics function application.

**Comment by nicolasstucki** [comment]
`StringContextOps` should probably also be a value class to avoid the allocation. Though previously we did rely on the optimizer to remove the remaining unused `val` with no side effects on the RHS. I will have a look at those details. Maybe we should have a minimal DCE optimization for inlined methods.
