### ISSUE TITLE
Infinite loop with by name value classes

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#5121]
```scala
class Foo(sc: => Int) extends AnyVal
```

emits the error 
```scala
2 |  class Foo(sc: => Int) extends AnyVal
  |        ^
  |        value sc in class Foo does not take parameters
```

but then stays in an infinite loop.

In scalac it fails with 
```
Foo.scala:2: error: value class parameter must be a val and not be private[this]
```

In both scalac and dotty 
```scala
class Foo(val sc: => Int) extends AnyVal
```
fails correctly with `val parameters may not be call-by-name`

**Comment by allanrenucci** [comment]
Do we want to forbid this? `dotc` does not require value class parameter to be a `val` as opposed to `scalac`

**Comment by nicolasstucki** [comment]
Forbid what exactly?

**Comment by allanrenucci** [comment]
Something like this:
```scala
class Foo(sc: => Int) extends AnyVal
```
The following of course should be forbidden:
```scala
class Foo(val sc: => Int) extends AnyVal
```
But that's already the case

**Comment by nicolasstucki** [comment]
Then yes because the first one is a shorthand of the second

**Comment by nicolasstucki** [comment]
You are right. It feels like it should not be allowed because it would not have value semantics.

**Comment by nicolasstucki** [comment]
I asked @sjrd and he said "just don't, disallow it".
