### ISSUE TITLE
private abstract method on class after Mixin.

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#513]
```
Exception in thread "main" java.lang.ClassFormatError: Method cachedPhases in class dotty/tools/dotc/core/Phases$$PhasesBase has illegal modifiers: 0x402
```

The flags are the same that Mixin has set. 

@odersky can you have a look?

**Comment by odersky** [comment]
The field should have a flag `NotJavaPrivate` set. Somebody has to expand these so that the name is expanded and the private flag is reset. It could be the backend or a miniphase before it.

**Comment by DarkDimius** [comment]
I was able to solve this in backend. But this revealed #514.
