### ISSUE TITLE
Numeric harmonisation

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5173]
```scala
class Test {
  def test(cond: Boolean, x: Int, y: Long) = {
    val z = if (cond) x else y
    z: Long
  }
}
```
`dotc` rejects this program:
```scala
-- [E007] Type Mismatch Error: Test.scala:4:4 ----------------------
4 |    z: Long
  |    ^
  |    found:    AnyVal(z)
  |    required: Long
  |    
one error found
```
`scalac` types `z` as a `Long`. Should we conform to what `scalac` does?

**Comment by Jasper-M** [comment]
This is [documented](http://dotty.epfl.ch/docs/reference/dropped/weak-conformance.html), though.

**Comment by allanrenucci** [comment]
> This is documented, though.

I was surprised that `if (cond) 1L else 2` types to `Long` but `if (cond) x else y` to `AnyVal`. Closing then since it is indeed documented
