### ISSUE TITLE
Decide when the REPL should enter multi-line mode

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5183]
Right now when pressing Enter, the REPL will add a new line instead of running the current input if:
- the input is incomplete (eg. "class Foo {")
- the cursor is in the middle of a line

But after experimenting with it, I think that usually when pressing enter in the middle of a line, I expect the input to be run. I suggest adding another shortcut (maybe Shift+Enter, Ctrl+Enter is not technically possible on most terminals) to signify "I want to add a new line and not run this command". (We might also need a shortcut for the opposite problem: "I want to run this command and not add a new line")

**Comment by allanrenucci** [comment]
I asked for this in the JLine [mailing list](https://groups.google.com/forum/#!topic/jline-users/oLMNASB4g8Q)

**Comment by smarter** [comment]
Looks like we can just use alt+enter to make a newline so we should just change enter to only check if the input is incomplete.

**Comment by smarter** [comment]
Yes, I think so, as a fallback we can always implement Ammonite's behavior where you can force multi-line by wrapping your code in `{ ... }`

**Comment by allanrenucci** [comment]
I played a bit with ammonite and it seems it submit the buffer, only if the cursor is on the last line. It think it makes sense and is a good compromise. Always submitting would make multi-line editing cumbersome

**Comment by smarter** [comment]
Sounds reasonable to me
