### ISSUE TITLE
.flags files in tests aren't used and should be deleted

### ISSUE THREAD

**Issue by milessabin** [lampepfl/dotty#5194]
Gitter discussion [here](https://gitter.im/lampepfl/dotty?at=5bb4afc4bbdc0b2505dcc29a).

**Comment by nicolasstucki** [comment]
The only `.flags` that are left are in `tests/untried` and `tests/disabled`. We should keep those until we re-enable them or we will not know if they needed some flags.

**Comment by nicolasstucki** [comment]
@milessabin is it ok if I close this issue?

**Comment by milessabin** [comment]
Happy to close.

FWIW, I think that the new Scala 2 approach of having flags in magic comments at the top of the source file would be worth following.
