### ISSUE TITLE
A tail recursive extension method gets two "$this" parameters

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#521]
The Issue is that `FullParameterization#fullyParameterizedDef` is called twice:

``` scala
import scala.annotation.tailrec

class M(val underlying: Int) extends AnyVal {
  @tailrec def foo: Unit = foo
}
```

`ExtensionMethods` creates a method `foo$extension` using `fullyParameterizedDef`:

``` scala
@annotation.tailrec() final def foo$extension($this: M): Unit = 
  M.foo$extension($this)
```

and `TailRec` creates a label method using `fullyParameterizedDef` too:

``` scala
@annotation.tailrec() final def foo$extension($this: M): Unit = {
  def tailLabel1($this: M.type)($this: M): Unit = tailLabel1($this)($this)
  tailLabel1(this)($this)
}
```

This seems to actually work at runtime, but having two parameters with the same name does not sound like a good thing, I think that:
- `FullParameterization` should use fresh parameter names when needed
- `-Ycheck` should warn about this sort of thing.

**Comment by DarkDimius** [comment]
>The Issue is that FullParameterization#fullyParameterizedDef is called twice:

@smarter, thats intentional. This method is both tail-recursive and an extension method. Both of those transformations abstract over `this`.

**Comment by smarter** [comment]
Yes, I mean "The issue happens because ...", I understand why it's done that way :).

**Comment by DarkDimius** [comment]
So the issue is that you see two parameters with the same name? `Symbols` could have same name in compiler. If you are worried about debugging,  both of those symbols are `synthetic` and will not show up in debugger.

**Comment by smarter** [comment]
Debugging also means looking at the output of `-Xprint`, when I look at:
```scala
def tailLabel1($this: M$, $this: Int): Unit = tailLabel1($this, $this)
```
I cannot know which `$this` is used when.

**Comment by odersky** [comment]
This would be solved if tailrec ran after extension methods. The problem
with that is that then tailrec has to deal with blocks generated  by the
pattern matcher.

On Sat, May 2, 2015 at 8:18 PM, Guillaume Martres <notifications@github.com>
wrote:

> Debugging also means looking at the output of -Xprint, when I look at:
>
> def tailLabel1($this: M$, $this: Int): Unit = tailLabel1($this, $this)
>
> I cannot know which $this is used when.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/521#issuecomment-98383959>.
>



-- 
Martin Odersky
EPFL

**Comment by DarkDimius** [comment]
@smarter try `-uniqid`. That's why it exists.
Those methods intentionally have special name. In scalac that is `this` and is handled by backend specially: it uses local variable `0` to store it, which is normally used to store `this` reference inside of the method call.

**Comment by DarkDimius** [comment]
@odersky what would be solved?

Running tailrec after extension methods will simply change order of `$this` parameters inside `tailLabel1`.
I do not see any problem here to solve.

**Comment by odersky** [comment]
I was thinking: because it then runs in a static object, so the `this` can be elided. But that brings us to another possibility: Can we not track whether a tailrec method uses `this` and, if it does not, drop
the `$this` parameter?

**Comment by DarkDimius** [comment]
@odersky, We could potentially. It would save us 2 instructions: 1 load and 1 store. Performance-wise, I believe, difference would be negligible even in interpreter.  

I am not sure if it is worth the effort. We already have a lot of places, where we have symbols with same name, either introduced by user or by compiler.

**Comment by odersky** [comment]
Agree, not a priority.

On Sat, May 2, 2015 at 8:51 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> @odersky <https://github.com/odersky>, We could potentially. It would
> save us 2 instructions: 1 load and 1 store. Performance-wise, I believe,
> difference would be negligible even in interpreter.
>
> I am not sure if it is worth the effort. We already have a lot of places,
> where we have symbols with same name, either introduced by user or by
> compiler.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/521#issuecomment-98386099>.
>



-- 
Martin Odersky
EPFL

**Comment by nicolasstucki** [comment]
With the new label def encoding we do not get this anymore.

```scala
  @annotation.tailrec() final def foo$extension($this: Int): Unit = 
      {
        while <empty> do tailLabel1[Unit]: return (return[tailLabel1] ()):Unit
      }
```
with the bytecode 
```
  public final void foo$extension(int);
    Code:
       0: goto          4
       3: athrow
       4: goto          0
       7: nop
       8: athrow
```

which could potentially be optimized further. Possibly already available in the backend optimizer.

The original issue with the double `this` is clearly fixed.

**Comment by nicolasstucki** [comment]
See #5784
