### ISSUE TITLE
Worksheet affecting .scala files

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#5242]
@tuvior noticed that now on each save action on VS Code (from the dotty project) the worksheet mode starts and inserts whitespaces in the file.

**Comment by nicolasstucki** [comment]
I tried it on the published version from `lampepfl/dotty.g8` and this is not an issue under that setup. It is only an internal issue.

**Comment by Duhemm** [comment]
@nicolasstucki I don't think that worksheets have been published anywhere at the moment?

Here's a fix: #5244

**Comment by nicolasstucki** [comment]
You are right. Already tested the fix. It works as expected.
