### ISSUE TITLE
Is TupleN for N > 22 a Product at runtime?

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#5270]
`tests/pending/tuple-erased.scala` fails assertions at runtime about the erased classes. It fails because `Tuple23` is not a `Product`.

Should `TupleN` for `N>22` be a `Product`?

**Comment by OlivierBlanvillain** [comment]
Why not?

**Comment by nicolasstucki** [comment]
Yes, it should. Did not think it through.
