### ISSUE TITLE
vscode-dotty: auto-configuration doesn't work when a file is opened outside a workspace

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5281]
- Launch code
- File -> Close Folder
- File -> New File
- Save as foo.scala
- Get a notification "This looks like an unconfigured Scala project. Would you like to start the Dotty IDE?", answer yes.

Then nothing happens, the root cause can be shown by doing:
- Help -> Toggle Developer Tools
- Click on the "Console" tab in the panel that appeared
- See the error message `lampepfl.dotty]ENOENT: no such file or directory, mkdir 'undefined/project'`

We should either support running the extension outside of a workspace (is there an API to create our own workspace ?) or not try to run the extension when the workspace is undefined.

**Comment by Duhemm** [comment]
I have a possible fix in #5285, but I'm a bit worried by the reloading that gets triggered, because I haven't seen that documented anywhere.
