### ISSUE TITLE
IDE: issues with auto-configuration

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5324]
Two issues that I've observed:
- When I open Code, close all workspaces, create a new file, then save it as "foo.sc", vscode-dotty kicks in and tries to find a suitable workspace path, but it seems that the uri it gets for vscode.window.activeTextEditor.document is "untitled:/Untitled-1", so .fsPath is empty and we try to set the root of the filesystem as the workspace directory. We should at least check `if (documentPath)` in `setWorkspaceAndReload` to avoid this, but we should also see if we can get the real url somehow (or maybe this is a VSCode bug we should report ?)
- When a file ending in .sc is opened outside a folder, vscode-dotty immediately calls setWorkspaceAndReload, then ask the user if the Dotty IDE should be started. But setting the workspace can be problematic: in a big directory you're likely to get warnings from vscode about maximum number of file watches reached, etc. It would be better to ask the user before changing the workspace.

**Comment by Duhemm** [comment]
> When a file ending in .sc is opened outside a folder, vscode-dotty immediately calls setWorkspaceAndReload, then ask the user if the Dotty IDE should be started. But setting the workspace can be problematic: in a big directory you're likely to get warnings from vscode about maximum number of file watches reached, etc. It would be better to ask the user before changing the workspace.

Is that specific to `.sc` files? Doesn't the same happen with `.scala` files?

**Comment by smarter** [comment]
I haven't checked but I assume it happens with .scala files too.
