### ISSUE TITLE
SIP: Enums

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#5373]
1. It should be possible that an enum trait extends java.lang.Enum. The compiler should check in this case that the restrictions imposed by Java are followed and generate the necessary code.

2. We should harmonize the method names between Scala and Java enums:
```
  enumTag --> ordinal
  enumValueNamed --> valueOf
  enumValues --> values
```

`values` has to be a field to work with Java reflection (static valueOf method in java.lang.Enum).

**Comment by dwijnand** [comment]
https://dotty.epfl.ch/docs/reference/enums/desugarEnums.html done?

**Comment by smarter** [comment]
Yep.
