### ISSUE TITLE
Drop Type Projections

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#5374]
We need to clarify exactly what abstract types are illegal.

**Comment by odersky** [comment]
In fact, the spec says exactly what is implemented: `T # A` is an error is `T` is an abstract type, no matter what `A` is.

**Comment by odersky** [comment]
See https://github.com/lampepfl/dotty/pull/5375 for a test case.

**Comment by odersky** [comment]
The precise semantics is: In `T # A`, `T` must be _realizable_. Actually, this would be a good place to add a spec of realizability, which is currently missing.

**Comment by ckipp01** [comment]
Hey @odersky is this still something needed or something you plan on doing? If not, is this something that can be closed? I also removed the SIP from the title just to avoid any confusion.

**Comment by odersky** [comment]
As far as I am concerned this can be closed. Not sure anymore why it was re-opened.
