### ISSUE TITLE
Member type does not conform to type projection on supertype

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#538]
Can be reproduced here:
dotty-staging@82cdf60
```
./src/dotty/tools/backend/jvm/DottyBackendInterface.scala:789: error: type mismatch:
 found   : DottyBackendInterface.this.Symbol(in DottyBackendInterface)(sym)
 required: scala.tools.nsc.backend.jvm.BackendInterface#Symbol(in BackendInterface)
        primitiveTypeMap.getOrElse(sym, storage.getClassBTypeAndRegisterInnerClass(sym.asInstanceOf[ct.int.Symbol]))
```

**Comment by DarkDimius** [comment]
I can workaround this.

**Comment by samuelgruetter** [comment]
Minimal example:

```scala

trait A {
  type X
}

class B extends A {
  def x: X = ???
}

object test {
  def f(): Unit = {
    val b = new B
    val a: A#X = b.x
  }
}
```

Compiles with `scalac`, dotty says

```
[error] examples/hash1.scala:13: error: type mismatch:
[error]  found   : b.X
[error]  required: A#X
[error]     val a: A#X = b.x
[error]                    ^
[error] one error found
```

**Comment by samuelgruetter** [comment]
But dotty seems to be right, because `b.X` is not  a subtype of `ex(y: A)y.X`.

**Comment by DarkDimius** [comment]
@samuelgruetter thanks :+1:

**Comment by smarter** [comment]
The rules for type projections in Dotty have changed and this actually compiles now, @DarkDimius  you might be able to get rid of your workaround.

**Comment by samuelgruetter** [comment]
That's good, and it's also compatible with the [rules that I've typeset last summer](https://github.com/samuelgruetter/dot-calculus/blob/d860019ec4ae73f532c523300cfa5a94557a8267/doc/exDOT/exDOT_rules.pdf): By `<:-∃-R` on page 4, we get `b.X <: ∃(b: A)b.X`, and by alpha-renaming, `b.X <: ∃(y: A)y.X`.
