### ISSUE TITLE
@tailrec not properly enforced

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5397]
```scala
class Test {
  def cond: Boolean = ???
  def foo(x: => Int) = ???

  @annotation.tailrec
  final def bar: Int =
    if (cond) foo(bar) // should be an error
    else bar
}
```

[t4649](https://github.com/lampepfl/dotty/blob/master/tests/pos/tailcall/t4649.scala) is a pending test case

**Comment by odersky** [comment]
What is tail recursion? I'd argue this is not a violation of it. What we have is really analogous to
```
class Test {
  def cond: Boolean = ???
  def foo(x: Test) = x.bar

  @annotation.tailrec
  final def bar: Int =
    if (cond) foo(this) 
    else bar
}
```
and that one is regarded as tailrecursive as well.

**Comment by allanrenucci** [comment]
We decided to report @tailrec failure within local methods as well.

It should cover this example, since by-name expends to closures which expends to local methods
