### ISSUE TITLE
Decompilation tests sometimes cannot be compiled on Windows due to unicode escapes in comments

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5414]
As reported on Gitter by @michelou, the decompilation tests fail on Windows:
```scala
-- Error: C:\dotty\out\posTestFromTasty\pos_decompiled\clsrefine\decompiled.scala:28:63 -
28 |/** Decompiled from out\posTestFromTasty\pos\clsrefine\scalac\util\test.class */
   |                                                               ^
   |                                                               error in unicode escape
```

It's very weird, but Scala will try to interpret a unicode escape `\uXXXX` when it sees it in a comment. And since Windows paths are separated using `\`, this means we run into trouble as soon as a directory name starts with `u`. We can avoid this issue by always using `/` when printing filenames in comments, even on Windows.

**Comment by nicolasstucki** [comment]
Always using `/` seems like a good compromise.

**Comment by smarter** [comment]
Note that there's a WIP PR to change this behavior in scalac: https://github.com/scala/scala/pull/6661
