### ISSUE TITLE
Flesh Out Match Types

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#5417]
The docs on match types contains several aspects that are not implemented yet. In particular:

 - The "cannot possibly match rule". See https://github.com/lampepfl/dotty/pull/5300#issuecomment-437316539 for an interaction with opaque types.
 - Detection of overlapping patterns in general
 - Typing rules for match terms that allow a match term to have a match type without having to cast.

**Comment by smarter** [comment]
@OlivierBlanvillain can thsi be closed ?
