### ISSUE TITLE
Consider reverting to Scala 2 implementation for @volatile lazy fields

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5448]
We have concerns about the size of the generated code, the performance characteristics  and the correctness of the new implementation.

Should we revert to the Scala 2 implementation for thread safe lazy fields? One can always revive  [SIP-20](https://docs.scala-lang.org/sips/improved-lazy-val-initialization.html)  in the future.

**Comment by allanrenucci** [comment]
I'll do an implementation of Scala 2 lazy vals for Dotty and try to benchmark them against our current lazy vals

**Comment by smarter** [comment]
Closing in favor of https://github.com/lampepfl/dotty/issues/7140 which is also on the theme of changing lazy val implementation.
