### ISSUE TITLE
Intersection of implicit function types is not an implicit function type

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5473]
E.g.:
```scala
trait A
trait B

object Test {
  val x: (implicit A => Int) & (implicit B => Int) = 42
    // error: found: 42, required: (implicit A => Int) & (implicit B => Int)
}
```

We probably should treat this as an implicit function type, otherwise distributing an intersection (something that the compiler will do in some situations) would change the semantics. But then should we allow this too ?

```scala
trait A
trait Foo extends ImplicitFunction[A, Int]

object Test {
  val x: Foo = 42
}
```

@odersky WDYT ?

**Comment by odersky** [comment]
Maybe `ImplicitFunction` should be final?

**Comment by smarter** [comment]
It can't be final since implicit function literals are desugared to anonymous subclasses of ImplicitFunctionN, at best we could disallow non-anonymous subclasses of it ?

**Comment by odersky** [comment]
I think the answer is: intersections are not function types whether implicit or not. So far I have not seen that distributing an intersection will cause problems. Let's re-open if there is a case. In that case we shyould probably restrict the distribution itself to avoid a change in semantics.
