### ISSUE TITLE
Follow Scala 2.13's lead and make postfixOps syntax an error (not just a warning) unless the feature is explicitly enabled

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5498]
See https://github.com/scala/scala/pull/6831

**Comment by som-snytt** [comment]
I've wanted something easy to relearn how to build dotty with all the submodule stuff. I'm always scared off by the smart people posting how they have build errors, and it's always some combination of cleans and updates. Also, it's a Monk marathon on "Heroes and Icons".

**Comment by smarter** [comment]
> Also, assuming support for ancient sbt is not required, per scala/scala#7319

No, we only support sbt 1, and the sbt bridge is in this repository anyway (https://github.com/lampepfl/dotty/tree/master/sbt-bridge)

**Comment by som-snytt** [comment]
@som-snytt I'd forgotten that, thanks, that was so funny.

**Comment by SethTisue** [comment]
or perhaps just don't support it at all?

**Comment by robstoll** [comment]
I work on this but need some input -- i.a. if I shall enable the feature for dotty itself or rewrite code. See #8388 for the other questions
