### ISSUE TITLE
IDE: Consider fuzzy-search in completion

### ISSUE THREAD

**Issue by Duhemm** [lampepfl/dotty#5507]
Currently, we filter completion candidates that match the prefix that the user has written. We should try to do fuzzy search.

> Note for later: we should consider doing fuzzy search instead (like what we do in https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/reporting/diagnostic/messages.scala#L338 (scalac implementation: https://github.com/scala/scala/pull/6711))

_Originally posted by @smarter in https://github.com/lampepfl/dotty/pull/5476_

**Comment by kubukoz** [comment]
@abgruszecki hey, I found this issue while looking at https://github.com/scalameta/metals/issues/4656 - I believe the completions are still limited in their fuzziness:

https://github.com/lampepfl/dotty/blob/a356581964813ad19b6f8380cac4344790ff5a72/compiler/src/dotty/tools/dotc/interactive/Completion.scala?rgh-link-date=2022-11-21T14%3A57%3A14Z#L452-L456

Can you share more info about why this was closed? Maybe it was a little bit premature 😅 thanks!
