### ISSUE TITLE
sourcecode port to dotty

### ISSUE THREAD

**Issue by alexarchambault** [lampepfl/dotty#5524]
PR: https://github.com/lihaoyi/sourcecode/pull/60

**Comment by alexarchambault** [comment]
It mostly works, but for a few issues…

- `scala.util.Properties.versionNumberString` still like `"2.12.…"`
  - convenient and portable way to know (at runtime) that we're running in dotty?
- needed to adjust a few `Symbol.name` to match `decodedName` from 2.x, for singletons in particular (maybe not that big a problem, this kind of things isn't uncommon even in 2.x version bumps)
  - stripped extra `$` suffixes or `_$` prefixes
    - https://github.com/lihaoyi/sourcecode/pull/60/files#diff-36af375568f72c76cd17b84810577edfR71
    - https://github.com/lihaoyi/sourcecode/pull/60/files#diff-36af375568f72c76cd17b84810577edfR96
    - https://github.com/lihaoyi/sourcecode/pull/60/files#diff-36af375568f72c76cd17b84810577edfR115
    - https://github.com/lihaoyi/sourcecode/pull/60/files#diff-36af375568f72c76cd17b84810577edfR125
- had to use extractors as a substitute for a few `is*` methods on `Symbol` (e.g. `isPackage`, `isClass`, `isMethod`, `isTerm`, …)
- convenient way to go from `List[Expr[T]]` to `Expr[List[T]]`? (one can always manually fold, but it may be nice to have that along `Expr` itself)
- !!! some lazy values, expected to be evaluated… were not!
  - https://github.com/lihaoyi/sourcecode/pull/60/files#diff-c92dac38359489a589e42c3e0cf2cff0R45
  - https://github.com/lihaoyi/sourcecode/pull/60/files#diff-b2bb7ff43a342b4959c342b026eebc99R45
- macro to get the arguments of ~the root context (like in `def foo(a: Int, b: String)(implicit foo: Foo)` with the implicit materialization of `Foo` backed by a macro - how can the macro get `2` and `"a"` in `f(2, "a")`?). Prevents to have `sourcecode.Args` work fine.
- macro to get the ~raw code of arguments of the root context (in `def foo(s: Seq[Int])(implicit foo: Foo)`, with the implicit materialization of `Foo` backed by a macro - how can the macro get a String `"(1 to 10).sum"` in `f((1 to 10).sum)`?). Prevents to have `sourcecode.Text` work fine.

**Comment by smarter** [comment]
> !!! some lazy values, expected to be evaluated… were not! 

@allanrenucci could you take a look at this? ^

**Comment by allanrenucci** [comment]
> !!! some lazy values, expected to be evaluated… were not!

Looks like #5350

**Comment by nicolasstucki** [comment]
@alexarchambault could you add the link of the implementation and close this issue

**Comment by alexarchambault** [comment]
@nicolasstucki It's [here](https://github.com/lihaoyi/sourcecode/tree/dotty), but still misses a few features, the last two points above:
- macro to get the arguments of ~the root context (like in `def foo(a: Int, b: String)(implicit foo: Foo)` with the implicit materialization of `Foo` backed by a macro - how can the macro get `Expr`s for `2` and `"a"` in `f(2, "a")`?). Prevents to have `sourcecode.Args` work fine.
- macro to get the ~raw code of arguments of the root context (in `def foo(s: Seq[Int])(implicit foo: Foo)`, with the implicit materialization of `Foo` backed by a macro - how can the macro get a String `"(1 to 10).sum"` in `f((1 to 10).sum)`?). Prevents to have `sourcecode.Text` work fine.

**Comment by alexarchambault** [comment]
Or do you prefer to close the issue in spite of them?

**Comment by alexarchambault** [comment]
Done here: https://github.com/lampepfl/dotty/issues/5782.
