### ISSUE TITLE
The worksheet should not trim leading whitespaces in its output

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5544]
Currently, these two expressions are displayed with the same output in the worksheet:
```scala
println("hi")
println(" hi")
```

This is problematic, because leading whitespace characters might be used to produce an indented output, for example to debug nested method calls while keeping track of the nested level.

**Comment by Ulydev** [comment]
I have tried removing the call to `trim` in _Evaluator.java:105_, but the problems persists.

It seems like the spaces get removed during the Json RPC notification between the server and the VSCode.

The simplest fix for now would be to add non-breakable spaces (e.g. replace `processOutput.next().trim` with `processOutput.next().replace(" ", "\u00a0")`). Should I open a PR?

**Comment by smarter** [comment]
That seems like a hack that could have unintended consequences, I think we should try to find and fix the root cause instead.

**Comment by Ulydev** [comment]
Sure thing. I’ll keep trying!

**Comment by smarter** [comment]
Looks like we also trim the output before displaying it in vscode: https://github.com/lampepfl/dotty/blob/909f10aa1b5880588a20fa03b1672303c20cbd94/vscode-dotty/src/worksheet.ts#L190

**Comment by Ulydev** [comment]
Yes, unfortunately printing runResult shows it is already trimmed. Also, wouldn’t the call to trim() only remove spaces around it, which means only the first spaces of the first line, and the last spaces of the last line (since it has line breaks)?

**Comment by smarter** [comment]
> Also, wouldn’t the call to trim() only remove spaces around it, which means only the first spaces of the first line, and the last spaces of the last line (since it has line breaks)?

Yes, I just wanted to note that this was one place where we probably shouldn't be trimming, but apparently there's others :).

**Comment by Ulydev** [comment]
In the end, I don't think the problem is linked to Json RPC, but rather a weird behaviour in Javascript itself.

I've noticed a very strange behaviour: the first space is taken into account, but consecutive spaces are in fact trimmed when printed, while its length stays correct. In this example, we end with an incoherent string length:
```scala
println("    B")
```
<img width="154" alt="2018-12-07 17 04 24" src="https://user-images.githubusercontent.com/9826683/49658500-84f16c00-fa42-11e8-9161-81265423dace.png">

**Comment by bishabosha** [comment]
I believe this will be a do not fix given we have metals worksheets now - which does preserve leading whitespace of console output in the hover text box
