### ISSUE TITLE
Worksheet mode: sealed traits cannot be extended

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5545]
Running the following worksheet fails with "Cannot extend sealed trait A in a different source file" (whereas the same code in the REPL works fine):
```scala
sealed trait A
class B extends A
```

**Comment by unkarjedy** [comment]
it doesn't work in REPL if you use two separate inputs (0.24.x)
![image](https://user-images.githubusercontent.com/3989292/78012749-1da1ae80-734e-11ea-95bd-d85db9fda4e4.png)

**Comment by unkarjedy** [comment]
related: https://youtrack.jetbrains.com/issue/SCL-17300

**Comment by bishabosha** [comment]
not an issue with Metals worksheets

**Comment by unkarjedy** [comment]
@bishabosha 
But there IS an issue with Metals as well.
And there IS still the issue with raw REPL.
I tested with dotty `0.27.0-RC1` and Metals `1.9.4`

![image](https://user-images.githubusercontent.com/3989292/97847313-7c724080-1d00-11eb-9c9a-a206cd7b4d3d.png)

**Comment by bishabosha** [comment]
the file should be named with a suffix `.worksheet.sc`, for example I can do the following in a worksheet:
```scala
def foo = 23

foo

enum Color { case R }

Color.R

sealed abstract class Foo

class Bar extends Foo

Bar()
```

**Comment by bishabosha** [comment]
the issue with the repl can be opened separately

**Comment by unkarjedy** [comment]
@bishabosha 
The same result with your example with `.worksheet.sc` suffix.
What dotty and Metals versions are you using?

![image](https://user-images.githubusercontent.com/3989292/97862302-24decf80-1d16-11eb-97b4-3e7554014b60.png)
![image](https://user-images.githubusercontent.com/3989292/97862425-5fe10300-1d16-11eb-8620-f993c616d82c.png)

**Comment by bishabosha** [comment]
I am using metals 1.9.4 with dotty 0.27.0-RC1 - if you have problems I recommend asking in https://gitter.im/scalameta/metals

**Comment by bishabosha** [comment]
it is possible that there is a conflict between dotty language server and metals, so you should check for any files that begin `.dotty-ide` and remove them, or i think you can add `.dotty-ide-disabled` as a blank file

**Comment by unkarjedy** [comment]
Indeed there were some conflicts, I remoted the file and it works now.

Looks like Dotty Worksheet in Metals now just reevaluates all the worksheet from the beginning, dropping all the state and reevaluating long computations?
Am I correct?

**Comment by bishabosha** [comment]
> Looks like Dotty Worksheet in Metals now just reevaluates all the worksheet from the beginning, dropping all the state and reevaluating long computations?
> Am I correct?

I would recommend asking in the gitter room  https://gitter.im/scalameta/metals
