### ISSUE TITLE
Is the meta programming allowed in REPL?

### ISSUE THREAD

**Issue by plokhotnyuk** [lampepfl/dotty#5551]
I have tried to run an example from the [Principled Meta Programming](https://dotty.epfl.ch/docs/reference/principled-meta-programming.html) doc page.
1. It seems that some import is missing to compile with the `showExpr` call.
2. Even after successful compilation without that call I cannot use the `assert` macro:
```
andriy@notebook:~/Downloads/dotty-0.10.0/bin$ ./dotr
Starting dotty REPL...
scala> import scala.quoted._                                                                                                                                                                                       
     | 
     | inline def assert(expr: => Boolean): Unit =
     |   ~ assertImpl('(expr))
     | 
     | def assertImpl(expr: Expr[Boolean]) =
     |   '{ if !(~expr) then throw new AssertionError("failed assertion")}
def assert(expr: => Boolean): Unit
def assertImpl(expr: quoted.Expr[Boolean]): quoted.Expr[Unit]

scala> assert(0 == 0)
1 |assert(0 == 0)
  |^^^^^^^^^^^^^^
  |Could not find macro class rs$line$1$ in classpath. The most common reason for that is that you apply macros in the compilation run that defines them
```

**Comment by nicolasstucki** [comment]
1. `showExpr` is actually defined below in the document. Though its definition is also wrong (outdated).
2. As far as I can see it should be possible to define macros in the REPL. Most likely the macro classloader gets confused by the special classloader that the REPL uses.
