### ISSUE TITLE
Remove dependency on scala-xml

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#5597]
We still[ bring in](https://github.com/lampepfl/dotty/blob/b826bf48ae4368508aa2a2bec2614502f16e17e7/project/Build.scala#L560) `scala-xml` to run our tests. We should:
- Report an error when compiling xml literals and `scala-xml` is not on the classpath similarly to [scalac](https://github.com/scala/scala/blob/1bf19cd2f9ec14e863e0730eaf02d1a62db21b49/src/compiler/scala/tools/nsc/typechecker/Contexts.scala#L144-L145). 
- `-Ystop-after:parser` for tests that parse xml
- And then completely remove the dependency

**Comment by smarter** [comment]
> -Ystop-after:parser for tests that parse xml

but there could be issues related to xml support that only manifest themselves after parsing (e.g. I think https://github.com/lampepfl/dotty/pull/3235 fixed a crash in Typer#assertPositioned)

**Comment by allanrenucci** [comment]
> but there could be issues related to xml support that only manifest themselves after parsing

True. But is seems to be the `scalac` approach ([to be confirmed](https://gitter.im/scala/contributors?at=5c12264a8336e22a7d2685b8)) so I wouldn't try harder than `scalac` to have good test coverage for xml literals

> e.g. I think #3235 fixed a crash in Typer#assertPositioned

I can only find calls to `checkPos` from: https://github.com/lampepfl/dotty/blob/7c8dee571d936433925befc56edffd00834654dc/compiler/src/dotty/tools/dotc/typer/FrontEnd.scala#L49

Nothing prevent us to keep checking this after parsing

**Comment by smarter** [comment]
>so I wouldn't try harder than scalac

scalac has the advantage that scala-xml is built using it and has its own test suite, if we add scala-xml to our community build and run its tests then I guess that would be good enough too.

**Comment by SethTisue** [comment]
scala-xml would probably accept a pull request adding Dotty to their `.travis.yml`. (IMO this would complement, not replace, adding scala-xml to the Dotty community build.)
