### ISSUE TITLE
Meta-programming: runtime reflection support?

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#5639]
ScalaTest depends on runtime reflection in several places:

- [ObjectMeta](https://github.com/scalatest/scalatest/blob/3.1.x/scalactic/src/main/scala/org/scalactic/source/ObjectMeta.scala) is used to better diff two values
- Used in [Framework.scala](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/tools/Framework.scala#L1006-L1012) to get instance of object

The question is: should tasty reflection provide similar support at run-time? What is the story for cross-platform support?

**Comment by ritschwumm** [comment]
at least at first glance ObjectMeta looks like it what it does could (and maybe even should) be done at compiletime. Framework.scala like it could easily be implemented with plain java runtime reflection.

**Comment by liufengyun** [comment]
Indeed, actually in [Framework.scala](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/tools/Framework.scala#L998-L1013), the implementation is based on Java reflection for Scala 2.10. I don't know what use scala-reflect for > 2.10.

Regarding ObjectMeta, more generally, can we conjecture that _run-time reflection_ can always be implemented by _compile-time reflection_ ? It seems possible to me, only the meta-information has to be materialized at compile-time when the value is created and propagate along with the value to where the meta-information is required. However, to which extent it affects usability is another issues, at least in ScalaTest, big refactoring is required.

**Comment by liufengyun** [comment]
Close now, run-time reflection is out of scope, given the portability problem it causes. We will evaluate the impact on the ScalaTest project.
