### ISSUE TITLE
Create sizeCompare and lengthIs methods

### ISSUE THREAD

**Issue by Kobenko** [lampepfl/dotty#5649]
As far as I understand, we don’t have `lenghtIs` and `sizeCompare` methods by analogy with the work of the same methods from the standard library in Seq and Iterable. if we have already implemented it, can you show where? If not, can I implement them?

**Comment by OlivierBlanvillain** [comment]
On what class would like to add these methods? Note that dotty reuses the Scala standards library so anything you would like to change there doesn't belong to this repo.

**Comment by allanrenucci** [comment]
`sizeIs` and `sizeCompare` are part of the 2.13 collection redesign. We are currently using the 2.12 standard library. Once we switch to the 2.13 standard library, you will be able tu use these methods with Dotty. I don't believe there is any plan to backport these methods to the 2.12 collection library
