### ISSUE TITLE
sbt-dotty does not load on sbt 1.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by eed3si9n** [lampepfl/dotty#5671]
## steps

1. Use `addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.2.6")` with sbt 1.3.0-SNAPSHOT.

## problem

```
[error] java.lang.RuntimeException: The sbt-dotty plugin cannot work with this version of sbt (1.3.0-SNAPSHOT), sbt >= 1.1.5 is required.
```

## expectation

sbt-dotty works with any sbt 1.x >= 1.1.5.

## notes

https://github.com/lampepfl/dotty/blob/bcccb2f3ce83bb6bf12559c7ae018e0f12042d32/sbt-dotty/src/dotty/tools/sbtplugin/DottyPlugin.scala#L92-L104

`NonReleaseV` requires z to be > 0.

**Comment by eed3si9n** [comment]
Where I actually saw this was in scripted test. I figured it was anything above sbt 1.1.x, but maybe the problem is with `-SNAPSHOT`?

**Comment by smarter** [comment]
ah indeed, looks like `sbtFullVersion` will return `None` for `1.3.0-SNAPSHOT`, the error should not be emitted if we couldn't parse the version number.

**Comment by smarter** [comment]
By the way it'd be nice if sbt provided something like `sbtFullVersion` so that I wouldn't have to implement it myself badly :).

**Comment by smarter** [comment]
Or maybe just a high-level mechanism to enforce that this plugin requires a particular minimum version of sbt.

**Comment by eed3si9n** [comment]
I think https://github.com/sbt/librarymanagement/blob/develop/core/src/main/scala/sbt/librarymanagement/VersionNumber.scala has semver check.

```scala
scala> import sbt.librarymanagement.{ VersionNumber, SemanticSelector }
import sbt.librarymanagement.{VersionNumber, SemanticSelector}

scala> VersionNumber("2.12.5").matchesSemVer(SemanticSelector(">=2.12"))
res1: Boolean = true
```

**Comment by eed3si9n** [comment]
```scala
scala> import sbt.librarymanagement.{ VersionNumber, SemanticSelector }
import sbt.librarymanagement.{VersionNumber, SemanticSelector}

scala> VersionNumber("1.3.0-SNAPSHOT").matchesSemVer(SemanticSelector(">=1.1.5"))
res0: Boolean = true

scala> VersionNumber("1.1.0").matchesSemVer(SemanticSelector(">=1.1.5"))
res1: Boolean = false
```

**Comment by changhe626** [comment]
please do not use sbt any more .please change to gradle or maven .it will be better than stb....
