### ISSUE TITLE
Autogenerated methods enumValue and enumValueNamed should return Options

### ISSUE THREAD

**Issue by LukaJCB** [lampepfl/dotty#5684]
These two methods sound a bit like ticking timebombs to me. 
I suspect these methods won't ever called using literals, so they're primarily used for turning unvalidated input into structured data. This is dangerous IMO, as it can subtly break when changing the ADT in question.
For example, changing the name of one of the cases in an enum can now lead to a runtime exception when using these methods.
Even worse, enumValue can break when we remove a completely unrelated case, akin to an out of bound index.

`Enum`s are a great feature to make code more type safe, but having these methods falsely giving the impression that they're total when they're actually partial discards some of the type safety we just gained. WDYT? :)

**Comment by ivanopagano** [comment]
Totally unfamiliar with how the compiler does it, but can the call site to those methods check the `EnumValues[E]` for the name/value map to contain the values (using `requiring` or similar), hence at compile time?

[this method](https://github.com/lampepfl/dotty/blob/786e6da4927b68dc50356aad251dd5f55b8bafed/compiler/src/dotty/tools/dotc/ast/DesugarEnums.scala#L88) looks like the candidate for such compile-time check...

**Comment by LukaJCB** [comment]
AFAIK, the only way to do it at compile time would be to have a compile-time value, i.e. a literal. If you're using literals for constructing an Enum, you might as well use one of the Enum's constructors. AFAICT these methods are meant mostly for run time values, so IMO it's important that they return an Option :)

**Comment by odersky** [comment]
@LukaJCB `enumValues` and `enumValuesNamed` return immutable maps, which means calling `get` on them returns an `Option`. 

In light of #5698 we want to disentangle enum translation from the standard library so we will probably end up with a different API. I completely agree that this new API will also need a way to get the value of an enum by index or name without causing an RTE.
