### ISSUE TITLE
Incompatible overload resolution

### ISSUE THREAD

**Issue by AleksanderBG** [lampepfl/dotty#5711]
Dotty fails to infer argument type for a lambda argument to overloaded method call where Scalac succeded.

~See https://github.com/lampepfl/dotty/pull/5710 for an unminimised example (tests fail on boostrap).~

Minimised example:
```scala
 object trace {
    def apply[T](a: String, showOp: Any => String) = 0
    def apply[T](a: Int, log: String => Unit) = 0

    apply("", res => res.toString)
  }
```

Dotty error is:
```
7 |  apply("", res => res.toString)
  |            ^^^
  |Missing parameter type
  |
  |The argument types of an anonymous function must be fully known. (SLS 8.5)
  |Expected type: ? => ?
  |Missing type for parameter res
```

**Comment by biboudis** [comment]
When you have some time can you add a minimized test on the description of this issue? 🥇

**Comment by AleksanderBG** [comment]
@biboudis that's why this is self-assigned :P

**Comment by biboudis** [comment]
Is this a yes or a no? 😆 (if you paste the test here as well it makes the issue self-contained it makes it easier for the future review-er)

**Comment by AleksanderBG** [comment]
What I mean is that I put this up here as a reminder for myself to minimise this later on, when I have the time - so yes :P
