### ISSUE TITLE
Illegal signature for higher kinded type with AnyVal upper bound

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#5720]
While testing another patch, I got this output:
```
[info] Test dotty.tools.dotc.CompilationTests.fuzzyAll started
<B:J>Ljava/lang/Object;: ':' expected at index 4ted (115/146, 0 failed, 2s)
<B:J>()V: ':' expected at index 4
[=======================================] completed (146/146, 0 failed, 3s)
```

Grep suggests that might be coming from https://github.com/lampepfl/scala/blob/9ef70dd9b9eeec11cfb72dabb57c61198fa18a20/src/asm/scala/tools/asm/util/CheckClassAdapter.java#L993.

Noting this for future usage, can't investigate right now...

**Comment by nicolasstucki** [comment]
`tests/fuzzy/IAE-4a69457e1319217c3bac170110ea4ba58dca11a6.scala` with the code
```scala
class A[B[_] <: Long]
```
is generating the waring

**Comment by nicolasstucki** [comment]
Can be replicated with `dotc tests/fuzzy/IAE-4a69457e1319217c3bac170110ea4ba58dca11a6.scala -Xverify-signatures`

**Comment by nicolasstucki** [comment]
It seams to happen for any `C <: AnyVal`  in `class A[B[_] <: C]`. It seams impossible to provide a `B` satisfying this bounds, hence this could be rejected at definition site. @Blaisorblade WDYT?

**Comment by Blaisorblade** [comment]
@nicolasstucki Multiple such `Bs` exist, so it's a valid bug. The fix seems a one-liner.

I guess your point is that you can't extend `Long`, but you can still satisfy it in multiple ways — at least `[x] => Long` and `[x] => Nothing` are valid arguments (see below). And values classes aren't that special — we could forbid all bounds `X <: T` where `T` is a final class, but I don't like it.

Glancing at https://docs.oracle.com/javase/specs/jvms/se11/html/jvms-4.html#jvms-4.7.9.1 reveals that `<B:J>()V` means, literally, `<B <: Long>()void`, which is illegal.
For `class A[B <: Long]`, the upper bounds becomes `java.lang.Object`; but apparently the responsible code (in erasure?) misses higher kinds.

I found the responsible code and how to fix it for these cases. Thinking it through and testing a bit.

```scala
scala> class A[B[_] <: Long]
// defined class A

scala> type C = A[[x] => Long]
// defined alias type C = A[[x] => Long]

scala> type C = A[[x] => Nothing]
// defined alias type C = A[[x] => Nothing]
```

**Comment by Blaisorblade** [comment]
@nicolasstucki Also, somehow this error does not fail the test in #5708 (which seems to use `-Xverify-signatures`). Should that be fixed? I can't investigate that now...

**Comment by nicolasstucki** [comment]
@Blaisorblade move the test to `tests/neg`

**Comment by Blaisorblade** [comment]
> Also, somehow this error does not fail the test in #5708 (which seems to use `-Xverify-signatures`).

Ah, that's because it's a normal error and we check for crashes, so I'd want `-Xverify-signatures` to crash there... or to move all those tests in `neg` as discussed... Well up to you.
