### ISSUE TITLE
IDE: do not force settings onto users

### ISSUE THREAD

**Issue by LPTK** [lampepfl/dotty#5772]
I am not sure why that happens, but when opening the IDE with `launchIDE` (and subsequently, even without going through `launchIDE`), the editor automatically trims spaces on save at the end of lines, even though the corresponding vscode settings is turned off (in Code > Preferences > Settings).

In some formats like markdown, spaces at the end of lines are semantically meaningful (two spaces make a break), so that's a problem.

**Comment by nicolasstucki** [comment]
That happens in VS code even without the Dotty plugin

**Comment by nicolasstucki** [comment]
Also, the plugin ignores markdown files.

**Comment by nicolasstucki** [comment]
@LPTK this should be reported to VS Code directly.

**Comment by LPTK** [comment]
@nicolasstucki 
> That happens in VS code even without the Dotty plugin

No, that's the thing! Opening non-Dotty projects or folders does _not_ exhibit this behavior.

**Comment by smarter** [comment]
In the Dotty project itself, if you don't have a .vscode folder, we make sbt copy .vscode-template to .vscode: https://github.com/lampepfl/dotty/blob/master/.vscode-template/settings.json
If you look for workspace settings in vscode you can edit those (or just edit the files by hand). We can also change the template so that trimming only happens for Scala files.

**Comment by LPTK** [comment]
Why have the setting for trimming in the first place? If the user wants trimming for Scala files (they may not), they will already have that in their own vscode options.

**Comment by smarter** [comment]
To enforce it in the project

**Comment by smarter** [comment]
To elaborate: in a given project, I think it's fine to enforce some constraints using editor settings, like the coding style
