### ISSUE TITLE
Proposal: add type inequality proving to standard library

### ISSUE THREAD

**Issue by vitaliihonta** [lampepfl/dotty#5778]
I would like to propose and contribute type inequality proving to dotty's standard library.
I hope that `=:!=` implicit may be useful for library authors (at least I'm using it frequently).
`shapeless` implementation looks nice so it may be the starting point.
We can improve it using `implicitAmbiguous` annotation so that compiler error will be more verbose

**Comment by smarter** [comment]
Dotty already provides `Not` which combined with `=:=` should give you everything you need: https://github.com/lampepfl/dotty/blob/master/library/src/scala/implicits/Not.scala
It might still be nice to add `=:!=` to the standard library, but you should open an issue in https://github.com/scala/bug/ for this (or start a discussion on https://contributors.scala-lang.org/), development of the standard library are out of scope for dotty itself.
