### ISSUE TITLE
Missing macros to get Expr and raw source code of method arguments

### ISSUE THREAD

**Issue by alexarchambault** [lampepfl/dotty#5782]
It's the main issue I ran into when porting [sourcecode](https://github.com/lihaoyi/sourcecode) to dotty. It needs macros to
- get the arguments of ~the root context (like in `def foo(a: Int, b: String)(implicit foo: Foo)` with the implicit materialization of `Foo` backed by a macro - how can the macro get `Expr`s for `2` and `"a"` in `f(2, "a")`?). Prevents to have `sourcecode.Args` work fine.
- get the ~raw code of arguments of the root context (in `def foo(s: Seq[Int])(implicit foo: Foo)`, with the implicit materialization of `Foo` backed by a macro - how can the macro get a String `"(1 to 10).sum"` in `f((1 to 10).sum)`?). Prevents to have `sourcecode.Text` work fine.

**Comment by nicolasstucki** [comment]
@alexarchambault is the addition in #5870 enough to implement this macro?

**Comment by alexarchambault** [comment]
@nicolasstucki I guess it is for the second point. Don't know about the first.

**Comment by alexarchambault** [comment]
Checking right now for the second point.

**Comment by nicolasstucki** [comment]
For the first one you should try with `(args: Expr[T]).unseal.underlyingArgument`

**Comment by alexarchambault** [comment]
So using `sourceCode` fails [like this](https://travis-ci.org/lihaoyi/sourcecode/jobs/505682251) ([PR](https://github.com/lihaoyi/sourcecode/pull/69)).

About `Args`, I'm not sure how I'm supposed to recover the `Expr[_]` of the arguments [from the root context](https://github.com/lihaoyi/sourcecode/blob/417b07c8432f06ea29723ff9c44400cf5bb24b50/sourcecode/shared/src/main/dotty/sourcecode/Macros.scala#L166).

**Comment by nicolasstucki** [comment]
@alexarchambault could you create a self contained example that shows the desired result?

**Comment by nicolasstucki** [comment]
This might be used to implement it https://github.com/lampepfl/dotty/blob/master/library/src/scala/compiletime/package.scala#L34
