### ISSUE TITLE
classOf/getClass are not implemented

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#579]
- `classOf[Int]` is erased to `classOf()` which is wrong. In `scalac` it is not erased but is replaced by `java.lang.Integer.TYPE` in `cleanup`.
- `2.getClass()` causes a crash in the backend, in `scalac` it is erased to `runtime.this.ScalaRunTime.anyValClass(scala.Int.box(2), (ClassTag.Int(): scala.reflect.ClassTag))`

**Comment by DarkDimius** [comment]
we have a test for this: `run/classof.scala`
