### ISSUE TITLE
Regression: Lifted inner method tries to use this

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#580]
This is exactly the same issue than #545, it was fixed in https://github.com/lampepfl/dotty/commit/b0856feefb90d1c0647bb3725ed9797fc76e0603 but in the same pull request https://github.com/lampepfl/dotty/commit/32a70042fc8a0338e093dba0424c98d25fb3a754 caused a regression.
In the example from #545, the enclosing class is the module class `Test$` and the top class is also the module class `Test$`, so the test `encClass.isProperlyContainedIn(topClass)` fails.

Assigned to @DarkDimius .

**Comment by odersky** [comment]
The fix causes the build to fail. ClassPath does not compile anymore. This is what I have been seeing all along. It shows the value of a test infrastructure we can rely on. Without it we are flying blind.
