### ISSUE TITLE
Run community build on every PR

### ISSUE THREAD

**Issue by OlivierBlanvillain** [lampepfl/dotty#5809]
The way we currently use the community build is quite inefficient because of the asynchronous reporting of errors. The build has now been broken for more than a month, and is now broken from (at last) 4 different PRs.

I would like to propose an alternative approach to make things more efficient: compile the community build on every PR as part of the CI.

I think the best way to do that would be to merge `dotty-staging/sourcecode` with `lampepfl/dotty`, that is:

- Add all the `dotty-staging/community-project-X` as submodules to the dotty repo. We already do that for the collection strawman, also for testing purposes.

- Create a sbt task in dotty's build to compile the community build with the current compiler. It will take about 10 minutes to run can be parallelized with everything else on the CI.

Is anyone opposed to this?

**Comment by SethTisue** [comment]
when the Dotty community build starts taking 15 hours to run like the Scala 2 one, you might need to make a different decision :-)
