### ISSUE TITLE
Cyclic reference with annotation on hk type parameter

### ISSUE THREAD

**Issue by panacekcz** [lampepfl/dotty#5811]
When a type parameter `X` with a type parameter `Y` is used in a self type, then putting any annotation on `Y` causes a cyclic reference error:
```scala
class ann extends scala.annotation.Annotation
class A[X[Y]]
class B[X[@ann Y]]{this: A[X] => }  
```
Output:
```
-- [E046] Cyclic Error: cyclic.scala:3:27 ---------
3 |class B[X[@ann Y]]{this: A[X] => }  
  |                           ^
  |                           Cyclic reference involving type X
```

It seems that when completing `X`, it tries to look up the identifier `ann` in `this`, and trying to complete the self reference it refers back to `X`.

Fortunately there is a workaround, writing an explicit lambda type:
```scala
class ann extends scala.annotation.Annotation
class A[X[Y]]
class B[X <: [@ann Y] => Any]{this: A[X] => }
```

**Comment by odersky** [comment]
You can't define an annotation in the same scope as it is accessed. If `ann` was separately compiled, or `B ` was in a local object, it would work. That scheme would be very hard to change, it would complicate a lot of things and the win does not seem to be worth it.

**Comment by panacekcz** [comment]
Sorry that I didn't realize that restriction(*), but the scope of `ann` is not relevant for this issue (I put it there just for the minimized example). The cyclic error happens before any annotation is found.
I get the same error with separate compilation and library annotations, for example:
```scala
class A[X[Y]]
class B[X[@scala.deprecated Y]]{this: A[X] => }  
```

(*) But I don't understand it, because putting `@ann` on `X` or `B` seems to work fine.

**Comment by odersky** [comment]
The second example compiles without errors on master.
