### ISSUE TITLE
colon `:` ordering special-case rules not required any more

### ISSUE THREAD

**Issue by drdozer** [lampepfl/dotty#5829]
I find the rules about operators with leading `:` confusing each and every time I hit them. They make various rules more complicated than required. Now that we can declare extension methods, so in effect declare infix operators, is this even required any more?

```scala
def (e: E)[E] +: (l: List[E]): List[E] = ...
def (l: List[E])[E] :+ (e: E): List[E] = ...
def (lhs: List[E])[E] ::: (rhs: List[E]) = ...
```

**Comment by smarter** [comment]
The Dotty issue tracker is not the place for open-ended discussions like this, please use http://contributors.scala-lang.org/
