### ISSUE TITLE
Multi Project Incremental compilation Issue (implicit functions related)

### ISSUE THREAD

**Issue by PDBP** [lampepfl/dotty#5842]
Hello,

https://github.com/PDBP/pdbp/tree/implicitPrompt

contains a project with a README.md that explains the issue

Luc Duponcheel

**Comment by AleksanderBG** [comment]
Hi and thanks for creating an issue! I understand that you have an issue that may be difficult to isolate, but it'd be very helpful if you could minimize it as much as possible - start by cutting off files that the "special" files don't depend on, shave off content from the other files, then shave off content from the special files etc. Thanks for your help!

**Comment by PDBP** [comment]
Hi Aleksander (and Guillaume),

Thanks for replying.

I agree that `PDBP` is becoming a big library.

But I have pinned down the issue to just two files

`./programSyntaxInstances/src/main/scala/pdbp/program/instances/active/delimiting/bigint/implicits.scala` 
and
`./programSyntaxInstances/src/main/scala/pdbp/program/instances/active/reading/bigint/delimiting/bigint/implicits.scala`

 Forget about other files.

If you compile all other files and then compile them *one after the other*, then everything is ok.

If you compile all other files and then compile them *together* then there is a problem.

Do not hesitate to ask any questions

Luc

**Comment by griggt** [comment]
The link from the first post:

> https://github.com/PDBP/pdbp/tree/implicitPrompt

gives a 404 error, and the only publicly visible repo for that GitHub account is [https://github.com/PDBP/pdbp](https://github.com/PDBP/pdbp), which is a library written in Haskell?  😕

**Comment by abgruszecki** [comment]
Right, it seems this issue is somewhat outdated and safe to close.

**Comment by bishabosha** [comment]
this project still exists in the community build so the issue may exist in that code

**Comment by abgruszecki** [comment]
If we reencounter the problem and we have a way to easily replicate it, we can open a separate issue to track that.
