### ISSUE TITLE
Remove or update typelevel.md ?

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5955]
https://github.com/lampepfl/dotty/blob/master/docs/docs/typelevel.md is outdated and is therefore misleading, can we delete it because it's subsumed by other doc pages or should it be updated ?

**Comment by rjolly** [comment]
In this file there was a description of code specialization. Do you know where I can find it now, as AFAICT it still works.

Code Specialization

Inline methods are a convenient means to achieve code specialization. As an example, consider implementing a math library that implements (among others) a dotProduct method. Here is a possible implementation of MathLib with some user code.

```scala
abstract class MathLib[N : Numeric] {
  def dotProduct(xs: Array[N], ys: Array[N]): N
}
object MathLib {
  inline def apply[N : Numeric] = new MathLib[N] {
    def n = Numeric[N]
    def dotProduct(xs: Array[N], ys: Array[N]): N = {
      require(xs.length == ys.length)
      var i = 0
      var s = n.zero
      while (i < xs.length) {
        s = s + xs(i) * ys(i)
        i += 1
      }
      s
    }
  }
}
```
