### ISSUE TITLE
No documentation for inline match ?

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#5956]
The `inline <ident> match` syntax is used in many examples but we don't seem to have any documentation for it, or am I overlooking it ?

**Comment by odersky** [comment]
Indeed there's nothing yet, but inline match is also not fully baked yet. It might go away and be replaced by staging. We need to prioritize progress in staging macros first. Then, we need to work on a meta programming subsection of the reference docs similar in scope to the contextual abstraction subsection. This should combine all aspects of meta programming, inluding

 - inline
 - staging
 - macros
 - tasty reflection

**Comment by biboudis** [comment]
Fixed via #6261
