### ISSUE TITLE
Local test failure

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#596]
I get (in both local sbt test and Eclipse)

[error] Test dotc.tests.tools_io failed: java.lang.AssertionError: assertion failed: asTerm called on not-a-Term val <none>, took 0.807 sec
exception occurred while compiling ./src/dotty/tools/io/ClassPath.scala, ./src/dotty/tools/io/DaemonThreadFactory.scala, ./src/dotty/tools/io/Fileish.scala, ./src/dotty/tools/io/Jar.scala, ./src/dotty/tools/io/package.scala
[error]     at scala.Predef$.assert(Predef.scala:165)
[error]     at dotty.tools.dotc.core.Symbols$Symbol.asTerm(Symbols.scala:417)
[error]     at dotty.tools.dotc.core.Types$TermRef$.withSigAndDenot(Types.scala:1654)
[error]     at dotty.tools.dotc.ast.tpd$TreeOps$.select$extension2(tpd.scala:657)
[error]     at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.loop$1(ExplicitOuter.scala:304)
[error]     at dotty.tools.dotc.transform.ExplicitOuter$OuterOps$.path$extension(ExplicitOuter.scala:307)
[error]     at dotty.tools.dotc.transform.LambdaLift$LambdaLifter.memberRef(LambdaLift.scala:363)
[error]     at dotty.tools.dotc.transform.LambdaLift$LambdaLifter.transformIdent(LambdaLift.scala:408)

This makes me wonder why the builds pass? What test file is run here?

**Comment by DarkDimius** [comment]
>What test file is run here?

`dotc.tests.tools_io` is https://github.com/lampepfl/dotty/blob/master/test/dotc/tests.scala#L170

I've just checked, on clean clone of master this test succeeds. I guess you have either some files modified or non-clean environment.

**Comment by odersky** [comment]
I double checked. My master is the same as upstream. And I have no local modifications.

**Comment by odersky** [comment]
What do you mean by non-clean environment?

**Comment by DarkDimius** [comment]
>  What do you mean by non-clean environment?

To name few: something on the classpath, additional files not tracked by git, something with environment variables.


@odersky are you running this on `lampsrv10`? If yes, I can try to get to your environment and see.

**Comment by smarter** [comment]
You could try getting rid of all the classfiles in your repository: `find . -name '*.class' | xargs rm`

**Comment by odersky** [comment]
The issue went away after I deleted all local .class files. Some pollution of my class path into sbt maybe?
