### ISSUE TITLE
Phase consistency involving higher-kinded types

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#5962]
When a higher-kinded type `S` is used in quote/splice, do we need  an evidence of `Type[S]` or `Type[S[X]]`? Neither type checks.

```Scala
import scala.quoted._
import scala.tasty._

class MatchFactory1[T, S[_]]

object MatcherFactory1 {
  def impl[T: Type, S[_]](self: Expr[MatchFactory1[T, S]])(implicit refl: Reflection, tpS: Type[S[T]]) =
    '{ ~self }
}
```

**Comment by liufengyun** [comment]
Related: phase consistency for path-dependent types https://github.com/lampepfl/dotty/pull/5961#discussion_r258832984

**Comment by nicolasstucki** [comment]
You can encode the missing type tag with `M >: MatchFactory1[T, S] <: MatchFactory1[T, S] : Type`

```scala
import scala.quoted._
import scala.tasty._

class MatchFactory1[T, S[_]] {
  def f: Int = 2
}

object MatcherFactory1 {

  def impl[T: Type, S[_], M >: MatchFactory1[T, S] <: MatchFactory1[T, S] : Type](self: Expr[M])(implicit refl: Reflection, tpS: Type[S[T]]) =
    '{ val a = ~self; a.f }

}
```

**Comment by liufengyun** [comment]
@nicolasstucki The encoding does not compile when there is inner class, type projection only allowed on non-concrete types under `Scala2` mode:

```Scala
import scala.quoted._
import scala.tasty._

class MatchFactory1[T, S[_]] { outer =>
  class Inner {
    val owner = outer
  }
}

object MatcherFactory1 {

  def impl[T: Type, S[_], M >: MatchFactory1[T, S] <: MatchFactory1[T, S] : Type](self: Expr[M#Inner])(implicit refl: Reflection, tpS: Type[S[T]]): Expr[M] =
    '{ (~self).owner }

}
```

We could move `#Inner` to the bounds as well, but it becomes a little verbose.

**Comment by liufengyun** [comment]
@odersky Mentioned we could change the parameter of `Type` to poly-kinded:

```Scala
sealed abstract class Type[T <: AnyKind] {
  type unary_~ = T
}

class Test {
  def foo(ev: Type[List]): Int = ???
}
```

However, this requires enable the flag `-Ykind-polymorphism`.
