### ISSUE TITLE
Matching on union crashes compiler.

### ISSUE THREAD

**Issue by elfprince13** [lampepfl/dotty#5969]
Hi! I'm trying to match on a union, and the compiler dumps stack with the following:

> [error] ## Exception when compiling 56 sources to /Users/thomas/Documents/sc2.12_eclipse_workspace/scala-cbheaps/target/scala-0.12/classes
> [error] dotty.tools.dotc.core.Types$CachedTypeRef cannot be cast to dotty.tools.dotc.core.Types$TypeLambda
> [error] dotty.tools.dotc.transform.TypeTestsCasts$.isClassDetermined$6(TypeTestsCasts.scala:95)
> [error] dotty.tools.dotc.transform.TypeTestsCasts$.recur$1(TypeTestsCasts.scala:126)
> [error] dotty.tools.dotc.transform.TypeTestsCasts$.checkable(TypeTestsCasts.scala:135)
> [error] dotty.tools.dotc.transform.TypeTestsCasts$.interceptTypeApply(TypeTestsCasts.scala:276)
> [error] dotty.tools.dotc.transform.Erasure$Typer.typedTypeApply(Erasure.scala:483)
> [error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1959)
> [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1996)
> [error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] dotty.tools.dotc.typer.Typer.typedIf(Typer.scala:729)
> [error] dotty.tools.dotc.transform.Erasure$Typer.typedIf(Erasure.scala:537)
> [error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1950)
> [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1996)
> [error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2078)
> [error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2089)
> [error] dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:704)
> [error] dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:680)
> [error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:683)
> [error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1949)
> [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1996)
> [error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] dotty.tools.dotc.typer.Typer.typedLabeled(Typer.scala:1097)
> [error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1935)
> [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1995)
> [error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2100)
> [error] dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:684)
> [error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1949)
> [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1996)
> [error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2100)
> [error] dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1530)
> [error] dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:597)
> [error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1929)
> [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1995)
> [error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2058)
> [error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2089)
> [error] dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:704)
> [error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1639)
> [error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1932)
> [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1995)
> [error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2058)
> [error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2089)
> [error] dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:704)
> [error] dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1639)
> [error] dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1932)
> [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1995)
> [error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2058)
> [error] dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2089)
> [error] dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:704)
> [error] dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1757)
> [error] dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1974)
> [error] dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1996)
> [error] dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2100)
> [error] dotty.tools.dotc.transform.Erasure.run(Erasure.scala:97)
> [error] dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:297)
> [error] scala.collection.immutable.List.map(List.scala:286)
> [error] dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:299)
> [error] dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:172)
> [error] scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
> [error] scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
> [error] scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
> [error] scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
> [error] scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
> [error] dotty.tools.dotc.Run.runPhases$5(Run.scala:184)
> [error] dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:192)
> [error] scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
> [error] dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:90)
> [error] dotty.tools.dotc.Run.compileUnits(Run.scala:199)
> [error] dotty.tools.dotc.Run.compileSources(Run.scala:134)
> [error] dotty.tools.dotc.Run.compile(Run.scala:118)
> [error] dotty.tools.dotc.Driver.doCompile(Driver.scala:33)
> [error] dotty.tools.dotc.Driver.process(Driver.scala:166)
> [error] xsbt.CachedCompilerImpl.run(CompilerInterface.scala:61)
> [error] xsbt.CachedCompilerImpl.run(CompilerInterface.scala:51)
> [error] xsbt.CompilerInterface.run(CompilerInterface.scala:35)
> [error] sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [error] sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [error] sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [error] java.lang.reflect.Method.invoke(Method.java:498)
> [error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
> [error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
> [error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
> [error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
> [error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
> [error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
> [error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
> [error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
> [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
> [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
> [error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
> [error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
> [error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
> [error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
> [error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
> [error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
> [error] sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
> [error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
> [error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
> [error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
> [error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
> [error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
> [error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
> [error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1544)
> [error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1518)
> [error] scala.Function1.$anonfun$compose$1(Function1.scala:44)
> [error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
> [error] sbt.std.Transform$$anon$4.work(System.scala:67)
> [error] sbt.Execute.$anonfun$submit$2(Execute.scala:269)
> [error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] sbt.Execute.work(Execute.scala:278)
> [error] sbt.Execute.$anonfun$submit$1(Execute.scala:269)
> [error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
> [error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
> [error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error] java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [error] java.lang.Thread.run(Thread.java:745)
> [error]
> [error] java.lang.ClassCastException: dotty.tools.dotc.core.Types$CachedTypeRef cannot be cast to dotty.tools.dotc.core.Types$TypeLambda
> [error] 	at dotty.tools.dotc.transform.TypeTestsCasts$.isClassDetermined$6(TypeTestsCasts.scala:95)
> [error] 	at dotty.tools.dotc.transform.TypeTestsCasts$.recur$1(TypeTestsCasts.scala:126)
> [error] 	at dotty.tools.dotc.transform.TypeTestsCasts$.checkable(TypeTestsCasts.scala:135)
> [error] 	at dotty.tools.dotc.transform.TypeTestsCasts$.interceptTypeApply(TypeTestsCasts.scala:276)
> [error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedTypeApply(Erasure.scala:483)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1959)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1996)
> [error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] 	at dotty.tools.dotc.typer.Typer.typedIf(Typer.scala:729)
> [error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedIf(Erasure.scala:537)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1950)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1996)
> [error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2078)
> [error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2089)
> [error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:704)
> [error] 	at dotty.tools.dotc.typer.Typer.typedBlockStats(Typer.scala:680)
> [error] 	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:683)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1949)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1996)
> [error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] 	at dotty.tools.dotc.typer.Typer.typedLabeled(Typer.scala:1097)
> [error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1935)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1995)
> [error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2100)
> [error] 	at dotty.tools.dotc.typer.Typer.typedBlock(Typer.scala:684)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1949)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1996)
> [error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2100)
> [error] 	at dotty.tools.dotc.typer.Typer.typedDefDef(Typer.scala:1530)
> [error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedDefDef(Erasure.scala:597)
> [error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1929)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1995)
> [error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2058)
> [error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2089)
> [error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:704)
> [error] 	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1639)
> [error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1932)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1995)
> [error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2058)
> [error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2089)
> [error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:704)
> [error] 	at dotty.tools.dotc.typer.Typer.typedClassDef(Typer.scala:1639)
> [error] 	at dotty.tools.dotc.typer.Typer.typedNamed$1(Typer.scala:1932)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1995)
> [error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] 	at dotty.tools.dotc.typer.Typer.traverse$1(Typer.scala:2058)
> [error] 	at dotty.tools.dotc.typer.Typer.typedStats(Typer.scala:2089)
> [error] 	at dotty.tools.dotc.transform.Erasure$Typer.typedStats(Erasure.scala:704)
> [error] 	at dotty.tools.dotc.typer.Typer.typedPackageDef(Typer.scala:1757)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:1974)
> [error] 	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:1996)
> [error] 	at dotty.tools.dotc.typer.ReTyper.typedUnadapted(ReTyper.scala:110)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2027)
> [error] 	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2039)
> [error] 	at dotty.tools.dotc.typer.Typer.typedExpr(Typer.scala:2100)
> [error] 	at dotty.tools.dotc.transform.Erasure.run(Erasure.scala:97)
> [error] 	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:297)
> [error] 	at scala.collection.immutable.List.map(List.scala:286)
> [error] 	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:299)
> [error] 	at dotty.tools.dotc.Run.runPhases$4$$anonfun$4(Run.scala:172)
> [error] 	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:18)
> [error] 	at scala.compat.java8.JProcedure1.apply(JProcedure1.java:10)
> [error] 	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
> [error] 	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
> [error] 	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
> [error] 	at dotty.tools.dotc.Run.runPhases$5(Run.scala:184)
> [error] 	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:192)
> [error] 	at scala.compat.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
> [error] 	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:90)
> [error] 	at dotty.tools.dotc.Run.compileUnits(Run.scala:199)
> [error] 	at dotty.tools.dotc.Run.compileSources(Run.scala:134)
> [error] 	at dotty.tools.dotc.Run.compile(Run.scala:118)
> [error] 	at dotty.tools.dotc.Driver.doCompile(Driver.scala:33)
> [error] 	at dotty.tools.dotc.Driver.process(Driver.scala:166)
> [error] 	at xsbt.CachedCompilerImpl.run(CompilerInterface.scala:61)
> [error] 	at xsbt.CachedCompilerImpl.run(CompilerInterface.scala:51)
> [error] 	at xsbt.CompilerInterface.run(CompilerInterface.scala:35)
> [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [error] 	at java.lang.reflect.Method.invoke(Method.java:498)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
> [error] 	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
> [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
> [error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
> [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
> [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
> [error] 	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
> [error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
> [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
> [error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
> [error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
> [error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
> [error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
> [error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
> [error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
> [error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
> [error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1544)
> [error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1518)
> [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
> [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
> [error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
> [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
> [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
> [error] 	at sbt.Execute.work(Execute.scala:278)
> [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
> [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
> [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [error] 	at java.lang.Thread.run(Thread.java:745)
> [error] (Compile / compileIncremental) java.lang.ClassCastException: dotty.tools.dotc.core.Types$CachedTypeRef cannot be cast to dotty.tools.dotc.core.Types$TypeLambda
> [error] Total time: 6 s, completed Feb 21, 2019 7:35:12 PM

My `build.sbt` contains:  `scalaVersion := "0.12.0-RC1" //,`

**Comment by smarter** [comment]
Please post the actual code you wrote that caused the crash, not just the stack trace.

**Comment by elfprince13** [comment]
I'll see if I can extricate a minimum (not-)working example.

**Comment by odersky** [comment]
@elfprince13 Please open a new issue once minimized.
