### ISSUE TITLE
type aliases for opaque types break

### ISSUE THREAD

**Issue by drdozer** [lampepfl/dotty#6003]
SO ...

```scala
opaque type T = String
object T {
  def unwrap(t: T): String = t
}

opaque type U = String
type W = U
object U {
  def unwrap(w: W): String = w
}
```

The `unwrap` in T works fine, as advertised. However, `unwrap` for U fails because it's defined in terms of the type alias `W` for `U`.

```
error]      |  def unwrap(w: W): String = w
[error]     |                             ^
[error]     |                             Found:    W(w)
[error]     |                             Required: String
```

I would expect W to de-alias to V, and then work.

**Comment by drdozer** [comment]
Thanks. Can this be added to the docs for opaque types as a gotcha+fix? I hit it quite quickly, so it's possible other people will stumble over it.

**Comment by odersky** [comment]
Yes, we should make a more detailed spec for opaque types.

**Comment by nafg** [comment]
That's interesting, I didn't realize that it worked by locally shadowing
the opaque type with an inner type that conforms to both the opaque type
and its right hand side.

Why does it use subtype though, couldn't it be U.U = U & String ?
