### ISSUE TITLE
Unexpected level-correctness interaction with type alias

### ISSUE THREAD

**Issue by fhackett** [lampepfl/dotty#6008]
```scala
class C {
    type T = Int
    def fn(e : Expr[T]) : Expr[T] = '{ ~e }
}
```

This fails to compile under Dotty 0.13.0-RC1 (specifically; 0.12.0 accepts this) with the following error:
```
3 |    def fn(e : Expr[T]) : Expr[T] = '{ ~e }
  |                                       ^^
  |                                access to C.this from wrong staging level:
  |                                 - the definition is at level 0,
  |                                 - but the access is at level 1.
```

Changing the code like this acts as a workaround:
```scala
class C {
    type T = Int
    def fn(e : Expr[Int]) : Expr[T] = '{ ~e }
}
```

The weird part is that this suddenly started happening in version 0.13.0-RC1. So, either I was taking advantage of a bug that is now fixed, or there is a new bug.

At least, it doesn't make sense to me how adding this layer of indirection changes the meaning of the program. Since it's a plain `=` alias, there's no chance of `T` ever not being an `Int`. In turn, there should be no reason for `'{ ~e }` to be looking up `C.this`.

**Comment by biboudis** [comment]
Thanks for reporting @fhackett 

This code works in the master branch (note the syntax change due to #5918:

```scala
import scala.quoted._

class C {
    type T = Int
    def fn(e : Expr[T]) : Expr[T] = '{ $e }
}
```

**Comment by fhackett** [comment]
Hello again - as per our discussion on #6007, I moved my project over to track nightly and found that this issue persists with one tiny difference:

```scala
import scala.quoted._

class C {
    type T = Int
    def fn(e : Expr[T]) : Expr[T] = '{ (); $e }
} 
```

Moving the `()` to the right of the `$e` shows the same issue (though `fn` returns `Expr[Unit]` then).

**Comment by biboudis** [comment]
Thx for reporting!
