### ISSUE TITLE
Erased terms can't be passed to erased lambda argument

### ISSUE THREAD

**Issue by Odomontois** [lampepfl/dotty#6009]
```scala
def foo(f: (erased Int) => Int): Int = {
  erased val ctx = 1
  f(ctx)
}
```
gives compilation error
> value ctx is declared as erased, but is in fact used

dotty version : 0.13-RC1

**Comment by nicolasstucki** [comment]
With the introduction of `given` the syntax changed. Now this version should be rejected and the correct code would be
```scala
def foo(f: erased Int => Int): Int = ...
```
or
```scala
def foo(f: erased (Int, ...) => Int): Int = ...
```
