### ISSUE TITLE
Function5.curried not implemented

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#6109]
The following code fails at runt-time:

```Scala
object Test extends App {
  val f = (x1: Int, x2: Int, x3: Int, x4: Int, x5: Int) => x1 + x2 + x3 + x4 + x5
  println(f.curried(1)(2)(3)(4)(5))
}
```

`curried` in Function5 up to Function22 are not implemented.

**Comment by odersky** [comment]
That's already the case for Scala 2, right?

**Comment by liufengyun** [comment]
@odersky This is a bug encountered in running ScalaTest test suite -- Scala2 works perfectly without runtime errors.
