### ISSUE TITLE
Support of vararg-function type

### ISSUE THREAD

**Issue by buzden** [lampepfl/dotty#6110]
Dotty does not support vararg function type. For example, this piece of code

```scala
def f(g: (String*) => String) = g("a", "b", "c") ++ g("1")
```

results in

```
[error] -- [E040] Syntax Error: Main.scala:3:19 
[error] 3 |  def ex(f: (String*) => String) = f("a", "b", "c") ++ f("1")
[error]   |                   ^
[error]   |                   ')' expected, but identifier found
```

This code compiles with 2.12 and 2.13. Both scala2-compatibility and default modes of dotty give an error above.

An archive with the smallest example project can be found [here](https://github.com/lampepfl/dotty/files/2978186/vararg-function-bug-example.zip).

**Comment by smarter** [comment]
This feature was removed from 2.13 so I don't think we should support it: https://github.com/scala/scala/pull/7399

**Comment by buzden** [comment]
Ok
