### ISSUE TITLE
partest: running a single test

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#613]
Either I'm doing it wrong, or it does not work

```
sbt "partest-only run/t261.scala"
...
info] Welcome to Partest for Dotty! Partest version:
[info] Compiler under test: dotty.tools.dotc.Bench or dotty.tools.dotc.Main
[info] Generated test sources: /Users/dark/workspace/dotty/tests/partest-generated/
[info] Test directories: neg, pos, run
[info] Debugging: failed tests have compiler output in test-kind.clog, run output in test-kind.log, class files in test-kind.obj
[info] Parallel: false
[info] Options: (use partest --help for usage information) run/t261.scala
[info]
[info] Selected 999 tests drawn from 10 named test categories
[info]
[info] # starting 505 tests in pos
[info] ok   1 - pos/A.scala
[info] ok   2 - pos/Arrays.scala
```

**Comment by felixmulder** [comment]
@nicolasstucki - you reported success with this. How was it done?

**Comment by nicolasstucki** [comment]
The issue seems to be a missing prefix. I'm using `> partest-only-no-bootstrap --show-diff --verbose tests/partest-generated/run/dynamicDynamicTests.scala` to execute only `dynamicDynamicTests`.

Therefore you should try `sbt "partest-only tests/partest-generated/run/t261.scala"`.

**Comment by felixmulder** [comment]
Correct command is: `runPartestRunner --verbose tests/run/t261.scala`

**Comment by smarter** [comment]
Do not use `runPartestRunner`, it will not update the tests that `partest` copies to `tests/partest-generated/`, so you won't be testing what you think you're testing, use `partest-only-no-bootstrap`

**Comment by smarter** [comment]
Partest is dead and vulpix can sucessfully run a single test with `testCompilation nameOfTheTest`
