### ISSUE TITLE
Port ClassfileParser improvements from Scala 2

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#6136]
Our version of ClassfileParser was copied from Scala 2 a long time ago, since then we've ported some of the improvements made there but not all of them, in particular the recently merged https://github.com/scala/scala/pull/6653#issuecomment-475101748 looks interesting.

**Comment by anatoliykmetyuk** [comment]
After talking to @adriaanm, I opened the scala/scala-dev#625 issue to see if we can address the problem of code sharing in a more generalised way.
