### ISSUE TITLE
Distinguish pattern bound symbol vs. case class flag usage

### ISSUE THREAD

**Issue by milessabin** [lampepfl/dotty#6178]
Follow on from #6172.

See comment by @smarter [here](https://github.com/lampepfl/dotty/pull/6172#issuecomment-477055574).

See also, https://github.com/lampepfl/dotty/blob/7bcaa97bd98aa2e039fb90aba81c3fde98ec65fe/compiler/src/dotty/tools/dotc/transform/PatternMatcher.scala#L88-L91

Which suggests that maybe we shouldn't be using `Case` here at all?

**Comment by milessabin** [comment]
I had a quick look at using `isPatmatGenerated` in the inliner (where the missing unpickled `Case` caused #6157) but that doesn't work because the symbol name doesn't conform to the expected pattern. I don't know whether or not this means TODO quoted above can be resolved.

**Comment by AleksanderBG** [comment]
@milessabin I'm uncertain if using `isPatmatGenerated` in the inliner makes sense - there, we're looking for results of `newPatternBoundSymbol`, which only sets `Case` flag. `newPatternBoundSymbol` also seems to be the counterpart of `createBindSymbol`, which you needed to adjust in #6172.

**Comment by liufengyun** [comment]
#7036 Fixes and checks flags of pattern bound symbols: 

```Scala
    /** Is the symbol a pattern bound symbol?
     */
    final def isPatternBound(implicit ctx: Context): Boolean =
      !isClass && this.is(Case, butNot = Enum | Module)
```
