### ISSUE TITLE
param accessors should drop `@ Repeated` from the type.

### ISSUE THREAD

**Issue by retronym** [lampepfl/dotty#619]
```scala
cat sandbox/test.scala
class C(val f: Any*) {
  def g = f
}

class Test {
  def test1(c: C): Nothing = c.f
  def test2(c: C): Nothing = c.g
}
```

```
% scalac sandbox/test.scala
sandbox/test.scala:6: error: type mismatch;
 found   : c.f.type (with underlying type Any*)
 required: Nothing
  def test1(c: C): Nothing = c.f
                               ^
sandbox/test.scala:7: error: type mismatch;
 found   : Seq[Any]
 required: Nothing
  def test2(c: C): Nothing = c.g
                               ^
two errors found

% ./bin/dotc sandbox/test.scala
sandbox/test.scala:6: error: type mismatch:
 found   : scala.collection.Seq[Any] @Repeated(c.f)
 required: Nothing
  def test1(c: C): Nothing = c.f
                               ^
sandbox/test.scala:7: error: type mismatch:
 found   : scala.collection.Seq[Any] @Repeated
 required: Nothing
  def test2(c: C): Nothing = c.g
                               ^
two errors found
```

I believe that both dotc and scalac are wrong here to give the param accessor the type `Any*`/ `Any @Repeated`. Instead, the repeated-ness of the type should be dropped, in the same way that it is when computing the type of the explicity defined accessor `g`.

Followup from #617, /cc @smarter

**Comment by retronym** [comment]
Note: By name constructor parameters are not allowed to to have the `val` modifier (or, equivalently, be used as case class params), otherwise we would need to test that out as well.

**Comment by odersky** [comment]
I don't see why. @Repeated is an annotation. The type for @Repeated method parameters gets transformed into an ExprType. But I see nothing wrong with leaving the annotation on the Seq type.

**Comment by retronym** [comment]
Fair enough. I can't really remember raising this ticket :).

What's the meaning of the `Repeated` annotation? It isn't documented in the dotty codebase AFAICS. Does it have an analog in scalac?

**Comment by odersky** [comment]
#1080 adds some documentation to Repeated and other classes.
