### ISSUE TITLE
Should we continue to generate function parents for case companions?

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#6190]
We currently generate a function type parent type for case class companions like this. Given:
```scala
case class C(a: A)
```
the companion is
```scala
object C extends (A => C) { ... }
```
However, there are many restrictions. We do not generate a function type for the companion, if

 - the companion is already written
 - the case class is polymorphic
 - the case class has more than one parameter list
 - the constructor of the class is private or qualified private
 - the class is an enum case, see: 7ccc244 of #6154.

The question is, given all these restrictions, should we stop generating function parents altogether? It would mean one has to write `C(_)` instead of `C` to convert `C` to a function, but that's probably not such a big deal.

**Comment by nafg** [comment]
It's useful for Slick: You do (colA, colB) <> (C.tupled, C.unapply), or
(colA, colB).mapT[C] (a macro that generates the former).
Once you add a companion you have to write (C.apply _).tupled (and if you
overload apply it's much worse).

Of course, Slick could be changed to not need a unary tupled function...

**Comment by ritschwumm** [comment]
i'd remove it:

it's frustrating when you try to use C as a function and the compiler tells you "no, that works elsewhere but not in _this_ case, please try again differently". it's frustrating when you add a type parameter to your case class and suddenly you have to change every place that was relying on the companion being a function.

personally, i made it a habit to _always_ write `C.apply` to avoid these (small) frustrations so i won't miss it at all.

**Comment by nafg** [comment]
How about we remove it in Scala 3.2

**Comment by odersky** [comment]
Maybe one can compensate for the loss by upgrading automatic conversions. Specifically, try to insert `apply` if an expression is not compatible with its expected function type.

**Comment by hrhino** [comment]
I've never liked this, so :+1: to its removal.

I don't know how the auto-apply could help slick: in `C.tupled` the expected type of `C` (as I understand it) is `? { def tupled: ? }` (maybe not in dotty?), so you'd need to be willing to treat that auto-apply similarly to an implicit conversion: there's no function type expected.

That said, Slick is how I first ran into this irregularly way back when. Is there a reason why `(C.apply.tupled, C.unapply)` isn't any good (other than its relative verbosity)? I don't think it works in Scala 2, but IIRC dotty is a bit more willing to eta-expand... would that work?
