### ISSUE TITLE
Unary methods should not have parenthesis

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#6192]
Unarry methods cannot be called with parenthesis, hence a unary method defined with parenthesis will never be callable.

```scala
class Foo {
  def unary_- : Int = 1
  def unary_!(): Int = 2 // error should be identified here

  def foo = {
    -this
    !this // error: method unary_! must be called with () argument
  }
}
```

**Comment by nicolasstucki** [comment]
This came from the community build
```scala
[warn] -- [E100] Syntax Migration Warning: /tmp/3/community-build/community-projects/squants/shared/src/main/scala/squants/AbstractQuantityNumeric.scala:33:21 
[warn] 33 |  def negate(x: A) = -x
[warn]    |                     ^^
[warn]    |                     method unary_- must be called with () argument
```

**Comment by odersky** [comment]
I think we are good as is for this. The error message looks fine to me. I don't think we need to add furher checks.

**Comment by som-snytt** [comment]
This disposition preserves [a puzzler](http://scalapuzzlers.com/#pzzlr-060)!

Someone had grumbled that no one would ever define a unary with parens, so it's gratifying to see the real-world example. If Scala is the real world.
