### ISSUE TITLE
Dotty version should not be hardcoded in dependencies

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#6207]
The dotty version should not be hardcoded. I think this should work:
```scala
"ch.epfl.lamp" %% "dotty" % scalaVersion.value,
```

_Originally posted by @allanrenucci in https://github.com/lampepfl/dotty/pull/6017_

**Comment by nicolasstucki** [comment]
This should be fixed also in https://github.com/lampepfl/dotty-quoted.g8/blob/master/src/main/g8/build.sbt#L13

**Comment by smarter** [comment]
Use "dotty-compiler" instead of "dotty", the latter is a meta-project that we should stop publishing eventually (we still need it because I hardcoded it into sbt, but I fixed this for sbt >= 1.3)
