### ISSUE TITLE
Double vision of toplevel definition in VSCode

### ISSUE THREAD

**Issue by AleksanderBG** [lampepfl/dotty#6208]
Opening VSCode on https://github.com/BryanAbate/dotty/commit/da2e2fa0572c75a1a570f10dd795b44764cd84b9 and navigating to `tastydoc/src/dotty/tastydoc/printer.scala` will show a bunch of errors like the one below:

```
cannot merge
  method formatToMarkdown in package tastydoc of type (container: dotty.tastydoc.Container, level: Int): String  and
  method formatToMarkdown in package tastydoc of type (container: dotty.tastydoc.Container, level: Int): String
they are both defined in package tastydoc but have matching signatures
  (container: dotty.tastydoc.Container, level: Int): String and
  (container: dotty.tastydoc.Container, level: Int): String
as members of package tastydoc
```

However, the code compiles w/o issues in SBT.
IDE LSP communication logs show nothing out of the ordinary, neither does anything appear in SBT.

**Comment by AleksanderBG** [comment]
Potentially related to #6201.

**Comment by benhutchison** [comment]
FWIW I hit the same issue on my first try of Dotty in VSCode:
```
package dottytest

import scala.language.implicitConversions
import cats.effect._
import implied cats.implicits._

val msg = "Im using Dotty!"
object DottyApp extends IOApp {
    def run(args: List[String]): IO[ExitCode] = IO(println(msg)) >> IO(ExitCode.Success)
}
```

IO in `IO(println(msg))` gets annotated with strange message:
```
cannot merge
  value msg in package dottytest of type String  and
  value msg in package dottytest of type String
they are both defined in package dottytest but have matching signatures
  String and
  String
as members of package dottytest
```

I noticed #6201 is marked as Fixed by a commit that only includes test code. Was it actually fixed by an earlier change, and the test is to prevent regression?

**Comment by odersky** [comment]
This could be a case where `msg` has migrated from a different source file and old class file is still around. We can try to make the error message more informative to find out more.

**Comment by kfish610** [comment]
I made a very simple program that gives these errors
```scala
trait Test
implied for Test
```
Which gives
```
cannot merge
  object Test_instance of type object Test_instance  and
  object Test_instance of type object Test_instance
as members of package <empty>    
```
and
```
cannot merge
  object Test_instance of type Test_instance  and
  object Test_instance of type file:///home/kfish/Documents/Projects/dotty-testing/src/main/scala/Test$package.
  Test_instance
they are both defined in package <empty> but have matching signatures
  Test_instance and
  file:///home/kfish/Documents/Projects/dotty-testing/src/main/scala/Test$package.
  Test_instance
as members of package <empty>
```
Interestingly I didn't get any errors when I just defined a top level value like `msg` in benhutchison's example
Hopefully this helps in narrowing it down
