### ISSUE TITLE
`@Repeated` can leak as method result type

### ISSUE THREAD

**Issue by AleksanderBG** [lampepfl/dotty#6236]
We probably should drop the `@Repeated` annotation when inferring the result type of a method:

```scala
scala> def foo(s: String*) = s
def foo(s: String*): Seq[String] @Repeated

scala> def foo(s: String*) = { val s1 = s; s1 }
def foo(s: String*): Seq[String]
```

**Comment by AleksanderBG** [comment]
Further problems:

```scala
scala> def foo(s: String*) = Option(s)
def foo(s: String*): Option[Seq[String] @Repeated]

scala> def foo(s: String*) = {val o = Option(s); o }
def foo(s: String*): Option[Seq[String] @Repeated]
```

Note that in the second case we also infer a type containing `@Repeated` for a local variable.

**Comment by AleksanderBG** [comment]
This may be fixed in `avoid` at basically no cost - since we already traverse the type, we might as well strip the annotation while we're at it (we do use `ApproximatingTypeMap` there, but I don't think it matters). This does mean that local variables can have `@Repeated` inferred, but I'm uncertain if that matters.

A cleaner fix might be simply to make the body of the method see vararg arguments w/o the annotation, but I'm unsure if that can be easily accomplished.

**Comment by smarter** [comment]
My hunch would be that https://github.com/lampepfl/dotty/blob/54fb992e81e580b47614674c3d2eea4a6a4a7a85/compiler/src/dotty/tools/dotc/core/ConstraintHandling.scala#L281 should handle this.
