### ISSUE TITLE
valueOf does not work in inlined code

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#6241]

**Comment by odersky** [comment]
```scala
object Test extends App {
  inline def v[T] = valueOf[T]

  println(v[String])
}
```
leads to
```
Unexpected tree in genLoad: TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class String)]/class dotty.tools.dotc.ast.Trees$TypeTree at: <56..56>
java.lang.RuntimeException: Unexpected tree in genLoad: TypeTree[TypeRef(ThisType(TypeRef(NoPrefix,module class lang)),class String)]/class dotty.tools.dotc.ast.Trees$TypeTree at: <56..56>
	at dotty.tools.backend.jvm.DottyBackendInterface.abort(DottyBackendInterface.scala:390)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:431)
```
The culprit is that `synthesizeValueOf` will succeed also if the argument is a non-singleton TypeRef but of course that can't. This is fixed in #6218. 

With the fix we get:
```
2 |  inline def v[T] = valueOf[T]  // error
  |                              ^
  |no implicit argument of type ValueOf[T] was found for parameter vt of method valueOf in object DottyPredef
```

That's still unsatisfactory. `valueOf` should work in inlined code. Its sibling `constValue` does, but we should have the functionality of both.

The underlying problem is that `valueOf` demands an implicit unconditionally, so it can't work in inlined code, where the implicit is not yet available since the type is not yet specialized.

**Comment by odersky** [comment]
Here's a workaround:
```scala
      inline def valueOf2 = implicit match {
        case ev: ValueOf[T] => ev.value
      }
```
Question: Should `valueOf` be defined like this?

**Comment by milessabin** [comment]
@odersky That looks OK to me ... I'm happy to test and PR that change.

**Comment by milessabin** [comment]
No problem with that change, though it might be better to roll it in to #6218 so that a neg test can be added.

**Comment by odersky** [comment]
@milessabin OK, please go ahead!

**Comment by milessabin** [comment]
@odersky as a separate PR?
