### ISSUE TITLE
Unability to use objects with name `eq` when compiled with Scala 2

### ISSUE THREAD

**Issue by buzden** [lampepfl/dotty#6242]
Dotty thinks that every package compiled by Scala 2 has the `eq` method in it. This gives two consequences.

---

First, **strange code compiles**. Considering as an example, you have `cats` library in dependencies, you have
```scala
val z = cats.eq(new Object) // Compiles!
```

---

Second, all `object`s that have name `eq` in such packages, **become unavailable**. Considering, for example, you have `cats-laws` library in dependencies, this code
```scala
import cats.laws.discipline.eq._
```

fails with

```
[error] -- Error: dotty-eq-bug/src/main/scala/dottyeq/tst-pos.scala:4:28 
[error] 4 |import cats.laws.discipline.eq._
[error]   |       ^^^^^^^^^^^^^^^^^^^^^^^
[error]   |       Object => Boolean is not stable
```

---

This error appears both in pure dotty mode and in dotty's scala 2 compatibility mode.

---

The minimal project showing both errors can be found [here](https://github.com/lampepfl/dotty/files/3047681/dotty-eq-bug.zip).

**Comment by smarter** [comment]
Both `cats` and `cats.laws.discipline` contain a package object, and objects always have an `eq` method, so Dotty's behavior isn't completely unreasonable here but we should still align with Scala 2. @adriaanm do you happen to know if scalac has some logic somewhere to skip members of Any when looking into package objects ?

**Comment by adriaanm** [comment]
Don't know, sorry. I poked around a bit, but didn't see anything obvious...

**Comment by smarter** [comment]
Found it: https://github.com/scala/scala/blob/8f3a05a802aa3cc28212fc5501db31e6f1d499d6/src/reflect/scala/reflect/internal/SymbolTable.scala#L358
