### ISSUE TITLE
Wildcard idents should not need to be eliminated.

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#627]
The whole elimWildcard business is still not right:

    var x = _

means "leave out the initializer". So no default value should be generated. This means that 

(1) where we need to generate a default value we should use tpd.defaultValue, not tpd.Underscore.
(2) _ should never be on the rhs of an assignment; the assignment should be simply left out.

Sure, we can clean all of this up in the ElimWIldardIdents phase, as we do now. But it seems much better to not generate this illegal code in the first place. In particular because ElimWildardIdents produces initializers which are redundant.

**Comment by DarkDimius** [comment]
> But it seems much better to not generate this illegal code in the first place

Why is it illegal? It's the code that user could write on his own.

> In particular because ElimWildardIdents produces initializers which are redundant.

If the default value isn't generated by ElimWildardIdents it's still going to be generated by GenBCode. 
By having this as phase, we have the ability to add a postcondition, that makes sure that no ValDef was unintentionally left uninitialized. We used to have those problems with mixin: it wasn't running for all the trees.

**Comment by odersky** [comment]
Why generate an initializer in GenBCode? None is needed, it's a zero anyway.

**Comment by DarkDimius** [comment]
If a ValDef with an EmptyTree as rhs hearches backend, it needs to zero out the local variable, as they can potentially be reused:
https://github.com/DarkDimius/scala/blob/sharing-backend/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala#L290

That's true that this reuse isn't implemented in GenBCode currently, but it could be worth implementing one day, as AFAIK JVM has some heuristics based on number of used local variables.

**Comment by odersky** [comment]
OK. But that's then a thing for the backend to initialize re-used
variables. No need to always do it in a transformer.

 - Martin

On Sat, Jun 6, 2015 at 5:56 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> If a ValDef with an EmptyTree as rhs hearches backend, it needs to zero
> out the local variable, as they can potentially be reused:
>
> https://github.com/DarkDimius/scala/blob/sharing-backend/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala#L290
>
> That's true that this reuse isn't implemented in GenBCode currently, but
> it could be worth implementing one day, as AFAIK JVM has some heuristics
> based on number of used local variables.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/627#issuecomment-109607524>.
>



-- 
Martin Odersky
EPFL

**Comment by odersky** [comment]
ElimWildcards is not longer part of the pipeline.
