### ISSUE TITLE
Expr[T].show should not show color

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#6270]
The following code, when compiled manually, will result in runtime exception due to the ASCII-colored output from `Expr[T].show`:

```Scala
// assert_1.scala
object api {
  inline def (x: => String) reflect : String =
    ${ reflImpl('x) }

  private def reflImpl(x: Expr[String])(implicit refl: Reflection): Expr[String] = {
    import refl._
    x.show.toExpr
  }
}

// test_2.scala
import api._

object Test {
  def main(args: Array[String]): Unit = {
    println(args(0).reflect)
    assert(args(0).reflect == "args.apply(0)")
  }
}
```

Command to compile:

```
dotc -d out tests/run-with-compiler/reflect-color/assert_1.scala
dotc -d out -classpath out tests/run-with-compiler/reflect-color/test_2.scala
dotr -classpath out Test
```

It compiles with `dotty-bootstrapped/testCompilation reflect-color`, because the test set by default disables color.

**Comment by nicolasstucki** [comment]
We should set the color setting to `false` in https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/Splicer.scala#L109

**Comment by liufengyun** [comment]
As discussed with @nicolasstucki , the change above does not work, as it changes the color setting for error reporting. A refactoring of Tasty reflect for `Context` and `Settings` is needed.
