### ISSUE TITLE
Unable to write abstract implied definitions

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#6282]
In Scala the following is valid:

~~~ scala
trait Bar { def f(): Unit }
trait Foo {
  implicit def bar: Bar
}
~~~

It is also valid in Dotty, but the following isn’t:

~~~ scala
trait Bar { def f(): Unit }
trait Foo {
  implied bar for Bar
//        ^
//       object creation impossible, since def f(): Unit is not defined 
}
~~~

Are abstract implied definitions planned to be supported?

Also, note that if `Bar` has no abstract method, then the following compiles:

~~~ scala
trait Bar
trait Foo {
  implied bar for Bar
}
~~~

**Comment by odersky** [comment]
> Are abstract implied definitions planned to be supported?

No. But there's a workaround:

```scala
trait Bar { def f(): Unit }
trait Foo {
  def bar: Bar
  implied for Bar = bar
}
```
The idea is that all "non-standard" forms of definitions are done on the normal, non-implied level.
Then a single `implied` will pull such definitions into the implied set.
