### ISSUE TITLE
Generated API documentation does not list implied operations

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#6283]
Given the following code:

~~~ scala
trait Foo[A] {
  def (a1: A)combine(a2: A): A
}

trait Bar

given as Foo[Bar] {
  def (a1: Bar)combine(a2: Bar): Bar = a1
}
~~~

The documentation for type `Bar` generated by the `doc` sbt task does not mention the implied operation `combine`.

**Comment by pikinier20** [comment]
This issue is outdated since extension methods are already supported.
