### ISSUE TITLE
Rename language.Scala2

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#6291]
The `Scala2` language option is misleading. On several occasions I met people who had the impression that it would be a mode where Scala 2 is fully supported but none of the Scala 3 features would be accepted. This is not what it is, of course. So I propose to rename to
`s2compat`. I.e.

     -language:s2compat

as a command line option and 

    import language.s2compat

as an import.

**Comment by OlivierBlanvillain** [comment]
I agree that the current name is misleading but I think I would prefer `scala2compat` over `s2compat`.

Also I have a feeling that we should put this under a dedicated flag instead of it being a language feature. For instance, its quite surprising that `-language:_` enables the compatibility mode.

**Comment by odersky** [comment]
I believe anybody using `-language:_` gets what they asked for :-)

**Comment by smarter** [comment]
We should just remove support for `-language:_`, it doesn't mean anything useful. But even then, I think it's strange that some `-language` flags just turn off warnings whereas others change the semantics of the language (and are therefore much more dangerous), I think we should clearly separate these two sets of options, in particular turning off language warnings should look like turning off any other kind of warning (something like the `-Wno-xxx` options in clang/gcc ?)

**Comment by som-snytt** [comment]
My newly teenaged child advises me that `-language:_` means "leave me alone!" Also, if you put underscore on both ends, you get _leave me alone!_ That is, don't hassle me about features, or in pipe organ lingo, "pull out all the stops."
