### ISSUE TITLE
MatchTypes are not supported in dotty doc

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#6295]
Currently, dotty doc crashes when documenting a member that contains a match type.

**Comment by nicolasstucki** [comment]
See #5499

**Comment by smarter** [comment]
Changed from a crash to printing a dummy output in https://github.com/lampepfl/dotty/pull/6348

**Comment by nicolasstucki** [comment]
We are going to replace this doc tool with scala3doc
