### ISSUE TITLE
Benchmark regressions

### ISSUE THREAD

**Issue by allanrenucci** [lampepfl/dotty#6300]
- "inductive implicits" significantly regressed in #6163
- "exhaustivity S" and "exhaustivity T" significantly regressed in #4253

**Comment by milessabin** [comment]
The inductive implicits regression is on my TODO list.

**Comment by liufengyun** [comment]
The benchmark regression in #4253 is intended behavior, it's explained here https://github.com/lampepfl/dotty/pull/4253#issuecomment-379222011 .

**Comment by smarter** [comment]
Looks like all fixable regressions have been fixed.
