### ISSUE TITLE
Use export to reduce opaque type boilerplate

### ISSUE THREAD

**Issue by japgolly** [lampepfl/dotty#6313]
I was having a look at https://github.com/lampepfl/dotty/commit/af2a0e66eb4b1204eac5dcb1d979486b92ef93d7 and saw:

```scala
object IArray {
  implied arrayOps {
    inline def (arr: IArray[T]) apply[T] (n: Int): T = (arr: Array[T]).apply(n)
    inline def (arr: IArray[T]) length[T] : Int = (arr: Array[T]).length
  }
```

The boilerplate here could be simplified if `export` were to be granted some additional power. It could potentially be something like:

```scala
object IArray {
  implied arrayOps {
    export (IArray[T]).{apply, length}
  }
```

What do you think?

**Comment by odersky** [comment]
My first reaction would be "too much magic". The only way to convince me otherwise is to come with a full spec that is simple enough.

**Comment by smarter** [comment]
Please use https://contributors.scala-lang.org/ to brainstorm new proposals so that we can keep this issue tracker actionable.
