### ISSUE TITLE
REPL and package statements

### ISSUE THREAD

**Issue by michelou** [lampepfl/dotty#6367]
REPL in Dotty 0.1x and Scala 2.1x behave differently in the presence of a top-level **`package`** statement.

Given the following Scala source file:
```scala
> cat myexamples/HelloWorld/src/main/scala/HelloWorld.scala
package myexamples

object HelloWorld {
  def main(args: Array[String]): Unit = {
    println("Hello world!")
  }
}
```
The Dotty 0.14-RC1 REPL gives the error message `"Illegal start of statement"` and goes back to the prompt:
```Scala
> dotc -version
Dotty compiler version 0.14.0-RC1 -- Copyright 2002-2019, LAMP/EPFL

> dotr

scala> :load myexamples/HelloWorld/src/main/scala/HelloWorld.scala
1 |package myexamples
  |^^^^^^^
  |Illegal start of statement

scala> :quit
```

The Scala 2.13-0-RC1 REPL also displays the error message `"Illegal start of statement"` **but** object `HelloWorld` is defined anyway :
```scala
> scala -version
Scala code runner version 2.13.0-RC1 -- Copyright 2002-2019, LAMP/EPFL and Lightbend, Inc.

> scala
Welcome to Scala 2.13.0-RC1 (OpenJDK 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> :load myexamples/HelloWorld/src/main/scala/HelloWorld.scala
args: Array[String] = Array()
Loading myexamples\HelloWorld\src\main\scala\HelloWorld.scala...

       package myexamples
       ^
myexamples/HelloWorld/src/main/scala/HelloWorld.scala:1: error: illegal start of definition
defined object HelloWorld

scala> HelloWorld.main(Array())
Hello world!

scala> :quit
```
As a reminder Java 11 does support the following behavior:
```java
> cat HelloWorld.java
package myexamples;

public class HelloWorld {
    public static void main(String[] args) {
         System.out.println("Hello world!");
    }
}

> c:\opt\jdk-11.0.2\bin\java HelloWorld.java
Hello world!
```
While direct comparison with Java is not applicable, Scala could provide a way to achieve a similar result; for instance:
```scala
> dotr

scala> :load myexamples/HelloWorld/src/main/scala/HelloWorld.scala
defined object myexamples.HelloWorld

scala> myexamples.HelloWorld.main(Array())
Hello world!

scala> :quit
```

**Comment by fabianhjr** [comment]
Hit this issue while trying toplevel enums and packaging.

https://gist.github.com/fabianhjr/458e61c3cb4e3007525f0667e0a8e04b

**Comment by som-snytt** [comment]
Scala 2 REPL has `:paste hello.scala` command; in addition, `:paste` detects opening `package` statement to automatically use `:paste -raw` to mean no embedding in a template.

`:load` implies line-by-line interpretation, and erroneous lines don't interrupt reading the file.

**Comment by dwijnand** [comment]
That `:load` vs `:paste` difference is really subtle and makes me want to try to unify them.

I'm thinking: should we allow `package` statements and make them affect the template?  I have a PR in flight to change the template back to the empty package (currently the template sticks the snippets in the `repl$` package).  So let's say that's merged, should `package foo` change the package from empty to `foo`?  That way reading in file that starts with `package myexamples` has the desired effect and we don't need two commands.  Note, the `package myexample` reverts at the end of `:load` and doesn't affect the rest of the session.  And `:load` should probably start from the root package, also ignoring the package in the repl session, so things don't accidentally nest.  Finally in the repl session `package foo` and then `package bar` makes the repl session's package `foo.bar`.  The only thing left is there isn't an obvious way to go back to the empty package.  The closest is `package _root_` which is a little confusing, but maybe it's fine as a solution?

**Comment by som-snytt** [comment]
The difference is between a script that is line-by-line REPL input, including colon commands, and plain Scala source. The mnemonic is that paste was originally just a way to paste companions in a single compilation unit.

**Comment by dwijnand** [comment]
OK, and that pasting we can now do with Alt-Enter (if memory serves), so we don't need to reintroduce `:paste`.  So if we keep the understanding that `:load` is for loading REPL scripts not for loading scala source files, I don't see Scala 2's behaviour of ignoring the package statement and keeping on going as that much better behaviour than Scala 3's hard failure.  Which leaves this to kind of a feature request to run main classes defined in a file, from the REPL, which seems a little strange?

**Comment by som-snytt** [comment]
The original issue, to compile and run a main not in the empty package, is already supported in 3.1.

I thought it was supported in 2.13 but apparently not.

**Comment by dwijnand** [comment]
Oh good.  So let's close this, as we support loading repl scripts, not loading Scala source files.
