### ISSUE TITLE
Double eta-expansion when ascribing contextual types

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#6375]
When we use a contextual type as a return type
```scala
class Test  {
   def f(): given Int => Boolean = true
}
```

it η-expands once ->

```scala
def f(): ImplicitFunction1[Int, Boolean] =  {
   def $anonfun(implicit evidence$1: Int): Boolean = true
   closure($anonfun)
}
```

However, if we provide an explicit ascription:

```scala
class Test  {
   def f(): given Int => Boolean = true : (given Int => Boolean)
}
```

it expands unnecessarily twice: 

```scala
def f(): ImplicitFunction1[Int, Boolean] =  {
   def $anonfun(implicit evidence$1: Int): Boolean =  (
      {
         def $anonfun(implicit evidence$2: Int): Boolean = true
         closure($anonfun)
      }:ImplicitFunction1[Int, Boolean]).apply(evidence$1)
   closure($anonfun)
}
```

**Comment by nicolasstucki** [comment]
Note that this affects all `inline` methods that return a contextual function.

**Comment by anatoliykmetyuk** [comment]
This one's moved to a new milestone for the third time already...

**Comment by biboudis** [comment]
Will get back to it.

**Comment by anatoliykmetyuk** [comment]
I'll remove it from the milestones FTTB

**Comment by odersky** [comment]
This is hard to avoid, since there are a number of ways how we could close over a context parameter twice. I think it's easiest to detect and drop these patterns later in a miniphase.
