### ISSUE TITLE
Wildcards disallowed in extends clauses?

### ISSUE THREAD

**Issue by AleksanderBG** [lampepfl/dotty#6406]
Apparently we disallow wildcards in `extends` clauses:

```scala
scala> class C[T]
// defined class C

scala> class D extends C[_]
1 |class D extends C[_]
  |                  ^
  |                  Type argument must be fully defined
```

This seems inconsistent, since the following is functionally identical and compiles:

```scala
scala> object O {
     |   type D = D0[_]
     |   class D0[T] extends C[T]
     | }
// defined object O
```

Is there anything we want to do about this?

**Comment by smarter** [comment]
I don't think we need to do anything, I don't want to have to think about the semantics of a parent with wildcard type parameters, and Java does not support them either.

**Comment by AleksanderBG** [comment]
Huh, I was under the impression that Java does allow that. I must have confused `extends A<?>` with `extends A`.
