### ISSUE TITLE
Compatibility issue with Scala at runtime

### ISSUE THREAD

**Issue by newca12** [lampepfl/dotty#6450]
This was initially reported [on the dotty gitter channel](https://gitter.im/lampepfl/dotty?at=5c740b5c5df86a456891486f)  by @Jasper-M but I did not find an open issue for that.
The behaviour is the same with -language:Scala2

Scala
```scala
scala> class Foo { def A(i: Double) = i; object A{ def apply(i: Int) = i+1 }; def foo = A(0) }
defined class Foo

scala> new Foo().foo
res6: Int = 1
```
Dotty
```scala
scala> class Foo { def A(i: Double) = i; object A{ def apply(i: Int) = i+1 }; def foo = A(0) }
// defined class Foo

scala> new Foo().foo
val res0: Double = 0.0
```

**Comment by anatoliykmetyuk** [comment]
I believe this is a duplicate of #5074. What do you think @smarter?

**Comment by anatoliykmetyuk** [comment]
@newca12 does it reproduce outside the repl?

**Comment by newca12** [comment]
Yes we got the same behaviour outside the repl.

**Comment by smarter** [comment]
Yeah this is a different issue.
