### ISSUE TITLE
Compiler error on Eff code compiled with 2.12 

### ISSUE THREAD

**Issue by benhutchison** [lampepfl/dotty#6484]
Scastie 1: Uses the [Scala 2.12 version of Eff](https://github.com/atnos-org/eff) library under Scala 2.12. Compiles OK
https://scastie.scala-lang.org/aINnRnZOTBas6SrzWRBmfQ

Scastie 2: Uses the [Scala 2.12 version of Eff](https://github.com/atnos-org/eff) library under Dotty. Doesn't compile
https://scastie.scala-lang.org/vTzj2G33SEqO1WtRBUo8oA

The sample code `runReader` makes use of implicits to compute the output type, and it seems that the semantics of implicit resolution varies in some way between Dotty and Scala 2.12, resulting in different behavior.

**Comment by OlivierBlanvillain** [comment]
Might be working as intended, see [changed-features/implicit-resolution.md](http://dotty.epfl.ch/docs/reference/changed-features/implicit-resolution.html)

I think there is higher chance of having someone looking into this if the issue comes with a minimized example.

**Comment by benhutchison** [comment]
On further investigation and some advice from Eric Torreborre, I dont think the problem is implicit resolution.  It has actually resolved the correct implicit.

Rather, I wonder if it may be related to how Dotty resolves the equality of two types...

In the Scastie below, Ive manually invoked the correct implicit with the correct type params. It still fails, but the error message is revealing. There's a lot going on in the types, type-lambdas, aliases and the Aux pattern, but to my reading the two types do look equal ([`Reader` is `Kleisli`](https://github.com/typelevel/cats/blob/5b6278cd820eec1785/core/src/main/scala/cats/data/package.scala#L31)). But the compiler doesnt agree:
```
Found:    org.atnos.eff.Member.Aux[org.atnos.eff.Fx1[[X] => cats.data.Reader[String, X]], 
  org.atnos.eff.Fx1[org.atnos.eff.Fx1[[X] => cats.data.Reader[String, X]]]
, org.atnos.eff.NoFx]
Required: org.atnos.eff.Member'[[β$0$] => cats.data.Kleisli[[A] => A, C, β$0$], 
  org.atnos.eff.Fx1[[X] => cats.data.Reader[String, X]]
]

where:    C       is a type variable with constraint >: String(g)
          Member  is a object in package eff
          Member' is a trait in package eff
```

https://scastie.scala-lang.org/zHGKYMWkTQWzHA3YoLCCjA

On thing I don't understand is why it'd say `C is a type variable with constraint >: String(g)` - what is this `String(g)` type?

**Comment by OlivierBlanvillain** [comment]
`String(g)` is `g.type`, we need to fix that in the pretty printer...

**Comment by benhutchison** [comment]
Another experiment: Here's a related example, but with no compiled Eff binaries, and the stripped down, relevant parts of Eff moved into the Scastie example.

https://scastie.scala-lang.org/osccD4TmQEGfCnvMR63r9g

This compiles OK! Whereas when the same code is loaded from an Eff binary compiled with Scala 2.12, it gets the type error in the previous comment above.

So it seems the Dotty compiler can resolve the code when it compiles it directly with Dotty. But when it reconstructs the types from the 2.12 binary file using `withDottyCompat`, something is a little different and the compiler can't see the Found type == the Expected type.

**Comment by smarter** [comment]
Running the code from https://github.com/lampepfl/dotty/issues/6484#issuecomment-491229193 with `explain-types` to get the compiler to tell me why it thinks these types are not equal, I see:
```scala
   |                  ==> cats.Id <:< [A] => A
   |                    ==> cats.Id <:< [A] => A recur
   |                      ==> [A] => A <:< [A] => A recur
   |                      <== [A] => A <:< [A] => A recur  = false
   |                    <== cats.Id <:< [A] => A recur  = false
   |                  <== cats.Id <:< [A] => A   = false
```
So something weird is definitely going on. Further debugging reveals that one of the `[A] => A` is an `HKTypeLambda` (used to represent type lambdas) and the other one is a `PolyType` (used to represent polymorphic methods). So we're confusing the two somehow when unpickling symbols from Scala 2, and this piece of code looks suspiciously related: https://github.com/lampepfl/dotty/blob/cdd844f3794910410482ffb2da449b86623e5248/compiler/src/dotty/tools/dotc/core/unpickleScala2/Scala2Unpickler.scala#L49

**Comment by benhutchison** [comment]
Thanks for the rapid diagnosis and fix @smarter, much appreciated! 

It has certainly helped build my trust in the Dotty migration to see these sort of early stage compatibility bugs vigorously investigated & resolved.

**Comment by benhutchison** [comment]
I notice these commits went to dotty-staging, but they didnt seem to publish a binary that I could retest with... is there a way I can test the fix in my own project?
http://dotty-ci.epfl.ch/lampepfl/dotty/12728

**Comment by smarter** [comment]
`dotty-staging` is just the remote we use to push branches for each PR to facilitate collaboration (only one remote that everyone can push to). In this case the PR is at https://github.com/lampepfl/dotty/pull/6494.

> is there a way I can test the fix in my own project?

We don't [yet](https://github.com/lampepfl/dotty/issues/6145) publish binaries for every open PR. But since https://github.com/lampepfl/dotty/pull/6494 has been merged it will be part of the next nightly build. So tomorrow you'll be able to test it by setting `scalaVersion` to the latest nightly version from https://repo1.maven.org/maven2/ch/epfl/lamp/dotty_0.15/ (or alternatively by setting `scalaVersion := dottyLatestNightlyBuild.get` to automatically fetch the latest one).
