### ISSUE TITLE
Errors and warnings hard to distinguish in the repl

### ISSUE THREAD

**Issue by lrytz** [lampepfl/dotty#6485]
It's not easy to see if a message was a warning or an error. The only difference is the missing result line.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/119636/57452867-26d0eb00-7265-11e9-97c8-1c490ea5cf44.png">

**Comment by newca12** [comment]
This is what we see with Dotty 0.14.0-RC1 but with Dotty HEAD the line number does have a distinct color to distinguish errors and warnings.

**Comment by smarter** [comment]
Yes, see https://github.com/lampepfl/dotty/pull/6293, so closing this, but feel free to discuss other improvements on https://contributors.scala-lang.org/ for example.
