### ISSUE TITLE
Tasty-reflect: misleading subtyping between `TypeBoundsTree` and `TypeTree`.

### ISSUE THREAD

**Issue by AleksanderBG** [lampepfl/dotty#6519]
`TypeDef#rhs` is a `Tree`, with a comment saying it should be `TypeTree | TypeBoundsTree`. Currently, `TypeBoundsTree` is a subtype of `TypeTree`. `TypeBoundsTree#tpe` produces `TypeBounds`. However, `TypeTree#tpe` returns a `Type`, not a `Type | TypeBounds`.

The cleanest solution may be to make `TypeBoundsTree` not a subtype of `TypeTree`.

**Comment by nicolasstucki** [comment]
To fix this we need to wait until we stop bootstrapping with Scala 2.

Actually `TypeBoundsTree` and `TypeTree` are direct subtypes of `Tree`. Therefore `TypeBoundsTree#tpe` and `TypeTree#tpe` do produce the intended result.

**Comment by AleksanderBG** [comment]
You're correct, it seems I have misidentified the issue my student was hitting. I'll try to investigate deeper (and try to be more careful w/ opening issues in the future :smile:). Since the opening post of this issue makes no sense (there in fact is no subtyping relationship between TypeBoundsTree and TypeTree), I'm closing it.
