### ISSUE TITLE
opaque type aliases broken in Worksheets

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#6566]
In 0.15.0-RC1 the type `Foo` can't be found within the `Foo` object in worksheet mode.

```scala
opaque type Foo = String

object Foo {
  def apply(s: String): Foo = s
}
```

**Comment by smarter** [comment]
Let's wait for https://github.com/lampepfl/dotty/pull/6567 to be done before investigating since it might solve end up solving this.

**Comment by bishabosha** [comment]
This is now redundant as it looks like opaque types are not allowed at the top level in a worksheet
