### ISSUE TITLE
enum branches can extend any class

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#6601]
Noticed by accident that enum cases might extend the wrong enum. That is, `Z` below is accepted and should probably be rejected. I also confirmed that `Z` indeed extends `Expr` and not `Var`.

```scala
object GADTs2 {
  enum Var[G, A] {
    case Z[A, G] extends Expr[(A, G), A]
  }
  enum Expr[G, A] {
    case Lit[G](n: Int) extends Expr[G, Int]
        // case S[A, G](x:
  }
}
```

**Comment by bishabosha** [comment]
well it now appears that simple enum values extend only Object, so this is another weird syntax irregularity

**Comment by bishabosha** [comment]
Actually you can extend anything at all

**Comment by bishabosha** [comment]
```scala
class Foo

enum Var[G, A] with
  case Z[A, G]() extends Foo

val isVar = Var.Z().isInstanceOf[Var[?,?]] // false
val isEnum = Var.Z().isInstanceOf[scala.Enum] // false
```
