### ISSUE TITLE
Compile-time successor of negative numbers 

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#6606]
Should `S[-1]` work and if yes (as it currently is) how should we handle the following? (now it doesn't type check).

```scala
val t1: scala.compiletime.S[-1] = 0 // OK
val t2: scala.compiletime.S[Int] = 1 // OK
val t3: scala.compiletime.S[Int] = 0 // this is an error now
```

**Comment by nicolasstucki** [comment]
As discussed offline `scala.compiletime.S[-1]` is not intended to have a valid successor.
