### ISSUE TITLE
Dotty dependency on Flexmark conflict with sbt test frameworks

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#6607]
This problem is encountered in the latest 3.1.x ScalaTest (https://github.com/scalatest/scalatest/tree/3.1.x).

Run
```
sbt ";scalatestDotty/clean;scalatestTestDotty/test"
```

We get the following runtime exception:

<details>
<summary>java.lang.NoSuchMethodError
com.vladsch.flexmark.html.HtmlRenderer$Builder.isRendererType(Ljava/lang/String;)Z
</summary>
<pre>
[error] java.lang.NoSuchMethodError: com.vladsch.flexmark.html.HtmlRenderer$Builder.isRendererType(Ljava/lang/String;)Z
[error] 	at com.vladsch.flexmark.ext.escaped.character.EscapedCharacterExtension.extend(EscapedCharacterExtension.java:46)
[error] 	at com.vladsch.flexmark.html.HtmlRenderer$Builder.extensions(HtmlRenderer.java:395)
[error] 	at com.vladsch.flexmark.html.HtmlRenderer$Builder.<init>(HtmlRenderer.java:211)
[error] 	at com.vladsch.flexmark.html.HtmlRenderer.builder(HtmlRenderer.java:150)
[error] 	at org.scalatest.tools.HtmlReporter.<init>(HtmlReporter.scala:119)
[error] 	at org.scalatest.tools.ReporterFactory.createHtmlReporter(ReporterFactory.scala:198)
[error] 	at org.scalatest.tools.ReporterFactory.getReporterFromConfiguration(ReporterFactory.scala:245)
[error] 	at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations$$anonfun$1(ReporterFactory.scala:254)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.Iterator.foreach(Iterator.scala:941)
[error] 	at scala.collection.Iterator.foreach$(Iterator.scala:941)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[error] 	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[error] 	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[error] 	at org.scalatest.tools.ReporterConfigurations.foreach(ReporterConfiguration.scala:42)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at org.scalatest.tools.ReporterConfigurations.map(ReporterConfiguration.scala:42)
[error] 	at org.scalatest.tools.ReporterFactory.createReportersFromConfigurations(ReporterFactory.scala:254)
[error] 	at org.scalatest.tools.ReporterFactory.getDispatchReporter(ReporterFactory.scala:257)
[error] 	at org.scalatest.tools.Framework$ScalaTestRunner.<init>(Framework.scala:670)
[error] 	at org.scalatest.tools.Framework.runner(Framework.scala:1123)
[error] 	at sbt.Defaults$.$anonfun$createTestRunners$1(Defaults.scala:944)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:233)
[error] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:125)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:233)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:226)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at sbt.Defaults$.createTestRunners(Defaults.scala:938)
[error] 	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1000)
[error] 	at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:756)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
</pre>
</details>

The problem is that `dotty-doc` depends on `flexmark-0.28.32` (which is required by ScalaInstance), and ScalaTest depends on `flexmark-0.35.10`, when SBT runs ScalaTest as a test framework to run the test set for ScalaTest, things go wrong.

https://github.com/lampepfl/dotty/blob/9116ecbb954d6a3b211b3d9c83a2684e72cea632/sbt-dotty/src/dotty/tools/sbtplugin/DottyPlugin.scala#L203-L207

Change the version in ScalaTest to be the same in Dotty, everything works fine.

/cc: @bvenners  @cheeseng

**Comment by smarter** [comment]
I fixed this in https://github.com/lampepfl/dotty/commit/28a64a84e9a9a4d73d3d5553cc5c19de8719ef0b which is part of sbt-dotty 0.3.3 which will get in scalatest once https://github.com/scalatest/scalatest/pull/1599 is merged :).
