### ISSUE TITLE
Missing inline whitebox functionality for the singleton-ops library

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#6633]
I'm experimenting with whitebox inline defs to try and replicate the singleton-ops library functionality in dotty. I've hit a dead-end:
```scala
  trait Op {
    type Out
    val value : Out
  }
  trait +[A, B] extends Op
  object + {
    implicit inline def ev[A, B] <: +[A, B] = inline (constValue[A], constValue[B]) match {
      case (a : Int with Singleton, b : Int with Singleton) =>
        val res = a + b
        new +[A, B]{
          type Out = res.type
          val value : Out = res
        }
      case _ => error("unsupported op + arguments")
    }
  }

  val res : 3 = implicitly[1 + 2].value
```
```
[error]    |  val res : 3 = implicitly[1 + 2].value
[error]    |                ^^^^^^^^^^^^^^^^^^^^^^^
[error]    |Found:    (Int(1) + Int(2)){Out <: Int}#Out((Int(1) + Int(2)){Out <: Int}#value)
[error]    |Required: Int(3)
```

**Comment by Blaisorblade** [comment]
We tried improving this at https://gitter.im/lampepfl/dotty?at=5cfaae29cea82952790cfc49, but it didn't help...

**Comment by smarter** [comment]
I don't think this can be made to work without built-in support in the compiler for `+` and other operators at the type-level, which would require someone to come up with a design and an implementation first. Meanwhile, tasty reflect might do what you want: https://github.com/lampepfl/dotty/pull/6279/files
