### ISSUE TITLE
Invite users to scroll down on dotty.epfl.ch

### ISSUE THREAD

**Issue by dwijnand** [lampepfl/dotty#6637]
Maybe I'm just a monkey but I only just realised (seeing someone else do it) that there's lots of lovely, useful information if you scroll down in https://dotty.epfl.ch/.  Perhaps there could be some visual cue.

**Comment by smarter** [comment]
IMHO we should change the design so that all the useful information is present above the fold and no scrolling is necessary (kind of like https://golang.org/)

**Comment by Blaisorblade** [comment]
We indeed used to have a visual cue (a down-arrow), but dropped them in #4020 because the implementation was too clever and fragile (#3952), and LAMP doesn't have dedicated frontend engineers. Until the design is changed, I expect something lower-tech could be welcome?

**Comment by dwijnand** [comment]
![image](https://user-images.githubusercontent.com/344610/60197830-29e56200-9838-11e9-88fa-3c5859af9c63.png)

🎉
