### ISSUE TITLE
Compiling code with Enums in without doing a clean compile causes runtime VerifyError

### ISSUE THREAD

**Issue by J-mie6** [lampepfl/dotty#6664]
When compiling code with Enums, unless a clean compile is done, then at runtime when an Enum is encountered (for example, here I have an `enum Operator ...`) an error like the following is triggered:

```
[error] (run-main-b) java.lang.VerifyError: Bad type on operand stack
[error] Exception Details:
[error]   Location:
[error]     compiler/Parser.createTable()Lscala/collection/immutable/List; @10: invokevirtual
[error]   Reason:
[error]     Type 'compiler/expr/Operator$' (current frame, stack[3]) is not assignable to 'compiler/expr/Operator'
[error]   Current Frame:
[error]     bci: @10
[error]     flags: { }
[error]     locals: { 'compiler/ChimeraParser' }
[error]     stack: { uninitialized 0, uninitialized 0, 'scala/Predef$', 'compiler/expr/Operator$' }
[error]   Bytecode:
[error]     0000000: bb00 4a59 b200 b3b2 02bf b602 c3b6 02c7
[error]     0000010: b702 cab9 02cf 0100 b202 d2b9 02d8 0200
[error]     0000020: c002 da2a ba02 e300 00b2 02e8 b602 ecb6
[error]     0000030: 02ef c002 dab0
```

This is running 0.16.0-RC3 cross compiling with a 2.12.8 library.

**Comment by smarter** [comment]
Can you provide a minimal project that reproduces the problem ?

**Comment by J-mie6** [comment]
Here you go!

[minimal-bug2.zip](https://github.com/lampepfl/dotty/files/3282852/minimal-bug2.zip)

This is a fun one! Two files are necessary, no cross-compilation necessary. `valueOf` is at fault! Run the following commands:

bash> sbt
sbt> ;clean;compile
sbt> runMain foo.Detonator

This should run fine and produce "ok!". Now edit Detonator.scala by adding whitespace or something. Run the following:

sbt> compile
sbt> runMain foo.Detonator

And boom!

**Comment by bishabosha** [comment]
Ok so I found that under incremental compilation, Detonator.boom is rewritten as shown by this diff:

```java
@@ -114,10 +114,10 @@ public final class foo.Detonator$ implements scala.Serializable
public void boom();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=2, locals=1, args_size=1
         0: getstatic     #31                 // Field foo/Bomb$.MODULE$:Lfoo/Bomb$;
         3: ldc           #33                 // String Kaboom
-        5: invokevirtual #39                 // Method foo/Bomb$.valueOf:(Ljava/lang/String;)Lfoo/Bomb;
+        5: invokevirtual #39                 // Method foo/Bomb.valueOf:(Ljava/lang/String;)Lfoo/Bomb;
         8: pop
         9: return
```

The rewritten code tries to `invokevirtual` the static method `foo/Bomb.valueOf`, instead of the virtual method `foo/Bomb$.valueOf`

**Comment by ekrich** [comment]
Any progress on this issue? This should fix my issue with serialization and allow all my tests to pass.
Reference as above: https://github.com/ekrich/sconfig/issues/55
