### ISSUE TITLE
[Doc] explain Annotation in type lambdas 

### ISSUE THREAD

**Issue by robstoll** [lampepfl/dotty#6667]
I am referring to this site: https://dotty.epfl.ch/docs/reference/new-types/type-lambdas-spec.html

I don't see an explanation of `{Annotation}`. I assume things like `@inline` but it would be nice to see that confirmed. Last but not least, an example would be helpful to understand applicable use cases.

**Comment by robstoll** [comment]
Found it below in `Subtyping Rules`. In this case I would recommend to define `Annotation` in the grammar. Also, it is defined as `{Annotation}` how is it posdible to use repetition?

**Comment by smarter** [comment]
The spec pages only list fragments of the grammar, see https://dotty.epfl.ch/docs/internals/syntax.html for the full thing.

> Also, it is defined as {Annotation} how is it possible to use repetition?

Pass them one after the other: `@foo @bla`

> And another question, is it possible to use both, a variance placeholder and +/- ?

What's a variance placeholder ?

**Comment by smarter** [comment]
> Last but not least, an example would be helpful to understand applicable use cases.

Annotations on symbols like this are typically used by compiler plugins as a marker to apply some kind of transformation.

**Comment by robstoll** [comment]
- ✓ repetition (sorry, forgot about white space as separator :D)
- ✓ example
- ✓ variance placeholder => forget about that confusion on my part
Thanks for clearing things ups :+1:
