### ISSUE TITLE
Opaque type is not respected while looking for delegates

### ISSUE THREAD

**Issue by weihsiu** [lampepfl/dotty#6680]
The following code failed to compile (dotty 0.16.0-RC3):
```
object OpaqueTypeBug {
  opaque type ProdInt = Int
  object ProdInt {
    def apply(x: Int): ProdInt = x
    def value(x: ProdInt): Int = x
  }

  trait Monoid[A] {
    def empty: A
    def (x: A) combine (y: A): A
  }

  delegate for Monoid[Int] {
    def empty = 0
    def (x: Int) combine (y: Int) = x + y
  }

  delegate for Monoid[ProdInt] {
    def empty = ProdInt(1)
    def (x: ProdInt) combine (y: ProdInt) = ProdInt(ProdInt.value(x) + ProdInt.value(y))
  }

  1 combine 2 // failed to compile
  ProdInt(1) combine ProdInt(2)  // failed to compile
}
```

compiler error:
```
[error] /examples/OpaqueTypeBug.scala:24:3: Found:    Int(1)
[error] Required: ?{ combine: ? }
[error] Note that implicit extension methods cannot be applied because they are ambiguous;
[error] both object Monoid_Int_instance in object OpaqueTypeBug and object Monoid_ProdInt_instance in object OpaqueTypeBug provide an extension method `combine` on
 Int(1)
[error]   1 combine 2
[error]   ^
[error] /examples/OpaqueTypeBug.scala:25:10: Found:    bengal.examples.OpaqueTypeBug.ProdInt
[error] Required: ?{ combine: ? }
[error] Note that implicit extension methods cannot be applied because they are ambiguous;
[error] both object Monoid_Int_instance in object OpaqueTypeBug and object Monoid_ProdInt_instance in object OpaqueTypeBug provide an extension method `combine` on
 bengal.examples.OpaqueTypeBug.ProdInt
[error]   ProdInt(1) combine ProdInt(2)
[error]          ^
[error] two errors found
```

It is my understanding that opaque type should be treated as its own unique type outside of its companion object.  But it looks to me that the compiler, while looking for delegates, is treating both the opaque type and the wrapped type as the same type.

**Comment by odersky** [comment]
The spec of opaque types has changed recently. The alias is now known in the scope where the opaque type is defined. Here's the link to the new docs.

https://dotty.epfl.ch/docs/reference/other-new-features/opaques.html

**Comment by weihsiu** [comment]
thanks for the explanation.  but i found that the import rule for delegate in the scope where the opaque type is defined has changed as well.  i normally need to "import delegate XXX._" to import the delegates defined in XXX but, in the case of opaque type, when i "import XXX._" where XXX is the scope where i defined both the opaque type and delegate, both the opaque type and delegate are imported.
