### ISSUE TITLE
Set().map dangerous behavior due to information loss from return value

### ISSUE THREAD

**Issue by IDoCodingStuffs** [lampepfl/dotty#6711]
```
val elements = Set(1,2,3)
val weights = Map(1 -> 1.0, 2 -> 1.0, 3 -> 1.0)
val values = Map(1 -> 0.2, 2 -> 0.6, 3 -> 0.4)
 
val wSum = elements.map(element=>
        weights(element) * values(element))
      .sum

wSum == 1.2 //True
```

Looks good so far

```
val elements = Set(1,2,3)
val weights = Map(1 -> 1.0, 2 -> 1.0, 3 -> 1.0)
val values = Map(1 -> 0.5, 2 -> 0.5, 3 -> 0.5)
 
val wSum = elements.map(element=>
        weights(element) * values(element))
      .sum

wSum == 1.5 //False, wSum = 0.5
```

Making elements a Seq fixes this since the result of the .map will be a Vector(3) instead of Set(1)

The wrong behavior here is discarding duplicate values in the return from .map() does not make any sense.

![image](https://user-images.githubusercontent.com/43346404/59793010-80382b00-92a3-11e9-8091-2df9c21c56bb.png)

See how the image below can have different x map to same y. So by making the return type a Set, we are discarding this information. And in practice, this breaks my pretty common use case when Java HashMaps are involved.

This clones https://github.com/scala/bug/issues/11580, brought to discussion here

**Comment by SethTisue** [comment]
Dotty shares Scala 2's standard library and will continue to do so at least until Scala 3.0, so it's not necessary to open  standard library tickets in both repos, the scala/bug ticket is sufficient.

**Comment by IDoCodingStuffs** [comment]
I see the other ticket just got marked "won't fix" after your explanation on legacy design concerns. So I guess this is where discussion on how it can be improved so that intuitive implementations are not causing faulty behavior can take place

**Comment by smarter** [comment]
> So I guess this is where new discussion should take place

I'm afraid that's not the case, dotty development is only concerned about producing a compiler, and not about changing the standard library. In fact, the plan is for Scala 2.14 and 3.0 to use the exact same standard library to ease migration. A good place for open-ended discussion that don't fit in any particular tracker is https://contributors.scala-lang.org/.
