### ISSUE TITLE
implicit conversion reported as ambiguous when clearly unambiguous

### ISSUE THREAD

**Issue by joshlemer** [lampepfl/dotty#6713]
Scastie sample: https://scastie.scala-lang.org/4cGVbhlZSQyvHBRnTeQkFQ

## minimized code

```Scala
import scala.language.implicitConversions

trait A[B[_]] 

delegate [X, Y[_]] for Conversion[X, A[Y]] given Y[X] = _ => new A[Y] {}

trait C[T]

delegate for C[Int] = new C[Int] {}
delegate for C[String] = new C[String] {}


val ac: A[C] = 1  // error! 
/*
Found:    Int(1)
Required: A[C]
Note that implicit conversions cannot be applied because they are ambiguous;
both method C_Int_instance and method C_String_instance match type ([_$2] => Any)[Any]
*/
```
### Edit (2019-11-25): 
Update after delegates replaced with givens (https://scastie.scala-lang.org/BgPA2unPSa6f8p6kCoI6CQ):
```scala
trait A[B[_]]

given c[X, Y[_]](given y: Y[X]): Conversion[X, A[Y]]  = _ => new A[Y] {}

trait C[T]

given ic: C[Int] = new C{}
given sc: C[String] = new C{}

val ac1: A[C] = c.apply(1)  // OK
val ac2: A[C] = c(1)        // error
val ac3: A[C] = 1   // error

@main def main(): Unit = {()}
```

## expectation

since this compiles fine:
```scala
the[Conversion[Int,A[C]]]
```

It seems that the compiler doesn't have an issue in finding an unambiguous conversion from Int to A[C]. However, when implicit conversion is relied upon in the line `val ac: A[C] = 1`, the conversion is considered ambiguous. My expectation would be that the correct conversion is found and applied to `1` to convert to an `A[C]`

**Comment by odersky** [comment]
This looks like it stresses Scala's type inference capabilities one step to much. I tried some variants:
```scala
trait A[B[_]]

object Test1 {

  delegate c[X, Y[_]] for Conversion[X, A[Y]] given (y: Y[X]) = _ => new A[Y] {}

  trait C[T]

  delegate ic for C[Int]
  delegate sc for C[String]

  val ac1: A[C] = c.apply(1)  // OK
  val ac2: A[C] = c(1)        // error
  val ac3: A[C] = 1           // error
}
```
So, writing the conversion `c` alone does not work either. You have to write `c.apply` then it works OK. This looks like a tricky combination of HK type inference and apply insertion. Not sure we can do anything about it in the short run.

**Comment by joshlemer** [comment]
Actually, not this seems okay

https://scastie.scala-lang.org/8IHXG7ezQoqIvk4cv1Xpzw

Only thing is the warning about implicit conversions. 

```scala
trait A[B[_]]

given c[X, Y[_]](given y: Y[X]): Conversion[X, A[Y]] = {_ => new A[Y] {}}

trait C[T]

given ic: C[Int] = new C{}
given sc: C[String] = new C{}


val ac3: A[C] = 1   // now this seems ok

@main def main(): Unit = {()}
```
