### ISSUE TITLE
Ergonomics of opaque types and delegates

### ISSUE THREAD

**Issue by milessabin** [lampepfl/dotty#6716]
An opaque type and its underlying type have exactly the same representation, so it should be possible to opt to directly reuse delegates for the underlying as delegates for the opaque type. This is pretty much the gist of Andres Loh's [Deriving Via](https://www.kosmikus.org/DerivingVia/deriving-via-paper.pdf) paper.

Ideally we'd be able to write something like,

```scala
trait Monad[T]
class Foo
object Foo {
  delegate for Monad[Foo]
}

opaque type Bar = Foo
object Bar {
  delegate for Monad[Bar] = the[Monad[Foo]]
}

object Test {
  val mf = the[Monad[Foo]]
  val mb = the[Monad[Bar]]
}
```

But this doesn't work currently, at least in part because recent changes to opaque types mean they no longer have an implicit scope of their own. The closest I think we can get right now is something like,

```scala
trait Monad[T]
class Foo
object Foo {
  delegate for Monad[Foo]
}

opaque type Bar = Foo
delegate for Monad[Bar] = the[Monad[Foo]].asInstanceOf

object Test {
  val mf = the[Monad[Foo]]
  val mb = the[Monad[Bar]]
}
```
which has an ugly (and surely unnecessary?) cast and an untidy top-level delegate definition.

Can we do any better?

**Comment by SystemFw** [comment]
Again, super quick comment (sorry for butting in without a lot of context, just had a quick discussion with Miles).
It seems a bit counterintuitive that opaque types won't have a companion object and therefore a convenient implicit scope of their own, given that one of the primary ways to add semantics to add is via typeclass instances.

**Comment by AleksanderBG** [comment]
Since the surrounding object still forms an implicit scope, is there any problem with moving the type inside the object?

```scala
trait Monad[T]
class Foo
object Foo {
  delegate for Monad[Foo]
}

object Bar {
  opaque type Bar = Foo
  delegate for Monad[Bar] = the[Monad[Foo]]
}

object Test {
  import Bar.Bar
  val mf = the[Monad[Foo]]
  val mb = the[Monad[Bar]]
}
```

**Comment by odersky** [comment]
We agreed that we should being companion objects for opaque types back, as far as implicit scope is concerned.

**Comment by SystemFw** [comment]
nice :)

**Comment by dwijnand** [comment]
@AleksanderBG seeing as type aliases can be top level, you can type alias the opaque alias and avoid the import... :-P

Or actually, you can export it (possibly pending https://github.com/lampepfl/dotty/pull/6729 ?).
