### ISSUE TITLE
Missing extractor for closures in Tasty Reflect

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#6720]
Currently we don't have extractors for closures in Tasty Reflect, nor do we have extractors for function literals.

**Comment by nicolasstucki** [comment]
We do have the closure extractor [`Lambda. unapply`](https://github.com/lampepfl/dotty/blob/master/library/src/scala/tasty/reflect/TreeOps.scala#L568).

What do you mean exactly by function literal extractors?

**Comment by liufengyun** [comment]
Thanks @nicolasstucki . Currently we have the extractor for closures, which could be used to implement the extractor for function literals. We need to add the extractor for function literals.

For this case, we encounter a problem:

- what is compiler internal, what is language spec?

If portability is the design goal of Tasty Reflect (among different Scala compilers, different versions of Scala compilers), then it seems better to not expose extractor for closures, but only extractor for function literals. The existence of _closures_ and its desugaring seems to be compiler-specific.
