### ISSUE TITLE
Dependent function types: self.type and this.type not the same

### ISSUE THREAD

**Issue by b-studios** [lampepfl/dotty#6745]
## minimized code

```Scala
trait Foo { self =>
  type M
  def apply(prog: (h: self.type) => h.M): M = prog(this)
}
```

## expectation
The above code example type checks. When replacing `self.type` with `this.type` I am getting the following error:

```
type M is not a member of <refinement>
```
However,  I expect `self.type` and `this.type` to be the same.

**Comment by AleksanderBG** [comment]
See also the potentially-related #6635.

**Comment by b-studios** [comment]
The issue still occurs with 0.18.0-bin-20190812-0ebbcff-NIGHTLY
