### ISSUE TITLE
Inline methods clash after erasure

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#6750]
## minimized code

```Scala
inline def foo(i: => Int)  = ???
inline def foo(l: => Long) = ???
```

## expectation
These should be able to exist in the same scope as `Function0[Int]` and `Function0[Long]` are only required at compiletime.

## result

error [erasure]:
```
Double definition:
inline def foo(i: => Int): Nothing in package object package$package at line 1 and
inline def foo(l: => Long): Nothing in package object package$package at line 2
have the same type after erasure.
```

**Comment by nicolasstucki** [comment]
Should the following also be accepted? And any other non erased type? Or should it be only an exception for by-name parameters?
```scala
inline def foo(i: () => Int)  = ???
inline def foo(l: () => Long) = ???
```

**Comment by nicolasstucki** [comment]
With the new inline parameter semantics, we should use `inline` instead of by name. This fixed the issue.
```
inline def foo(inline i: Int)  = ???
inline def foo(inline l: Long) = ???
```
