### ISSUE TITLE
Misleading error message for extension methods with implicits

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#6762]
## minimized code

```Scala
import scala.quoted._
import delegate scala.quoted._

type G[X]
case class Foo[T](x: T)
def f(word: String): Expr[Foo[G[String]]] = '{Foo(${word.toExpr})}
```

## expectation
An error message saying that the type of ` '{Foo(${word.toExpr})}` is incorrect: it is `Expr[Foo[String]]` whereas `Expr[Foo[G[String]]]` is expected. Instead, the error message is as follows:

```
[error] -- [E008] Member Not Found Error: /Users/anatolii/Projects/dotty/playground/macros/src/main/scala/playground/macros.scala:45:59
[error] 45 |  def f(word: String): Expr[Foo[G[String]]] = '{Foo(${word.toExpr})}
[error]    |                                                      ^^^^^^^^^^^
[error]    |      value toExpr is not a member of String.
[error]    |      An extension method was tried, but could not be fully constructed:
[error]    |
[error]    |          quoted.ExprOps.toExpr[T](word)
[error] one error found
```

**Comment by anatoliykmetyuk** [comment]
Also:

```scala
def f(word: String): Expr[Foo[G[String]]] = '{Foo(${word.toExpr given the[Liftable[String]]})}
```

The above modification changes the error message, yet it is still unrelated:

```
[error] -- [E050] Reference Error: /Users/anatolii/Projects/dotty/playground/macros/src/main/scala/playground/macros.scala:45:54
[error] 45 |  def f(word: String): Expr[Foo[G[String]]] = '{Foo(${word.toExpr given the[Liftable[String]]})}
[error]    |                                                      ^^^^
[error]    |           method toExpr in object ExprOps does not take more parameters
[error] one error found
```

**Comment by nicolasstucki** [comment]
Here is a self contained minimization:

```scala
type Expr[T]
type G[X]

def f(word: String): Expr[G[String]] = word.toExpr

def splice[T](e: Expr[T]): T = ???

type Liftable
delegate for Liftable = ???

implicit object ExprOps {
  def (x: T) toExpr[T] given Liftable: Expr[T] = ???
}
```

It has to do with extension methods with implicit parameters

**Comment by anatoliykmetyuk** [comment]
> Also:
> 
> ```scala
> def f(word: String): Expr[Foo[G[String]]] = '{Foo(${word.toExpr given the[Liftable[String]]})}
> ```
> 
> The above modification changes the error message, yet it is still unrelated:
> 
> ```
> [error] -- [E050] Reference Error: /Users/anatolii/Projects/dotty/playground/macros/src/main/scala/playground/macros.scala:45:54
> [error] 45 |  def f(word: String): Expr[Foo[G[String]]] = '{Foo(${word.toExpr given the[Liftable[String]]})}
> [error]    |                                                      ^^^^
> [error]    |           method toExpr in object ExprOps does not take more parameters
> [error] one error found
> ```

For this one I've created a separate issue, #6779. It has nothing to do with the metaprogramming framework, the cause is in the extension methods with implicit parameters.
