### ISSUE TITLE
Too technical error message when using `erased` with `class`

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#6795]
## minimized code

```Scala
scala> erased class Foo
1 |erased class Foo
  |^^^^^^^^^^^^^^^^
  |modifier(s) `4398046511105' incompatible with type definition
```

## expectation
`modifier(s) "erased" incompatible with type definition`

**Comment by nicolasstucki** [comment]
We have a general problem with the `toString` of flags

**Comment by anatoliykmetyuk** [comment]
Do we already have an issue for that?

**Comment by nicolasstucki** [comment]
No. It is something new that arose from the refactoring of flags. I noticed it while debugging.
