### ISSUE TITLE
Inline code leads to a lot of Unit load + discard bytecode

### ISSUE THREAD

**Issue by jsuereth** [lampepfl/dotty#6800]
I've been using a lot of inline lately and I'm seeing the following bytecode in a lot of places:

```
N: getstatic     #54  // Field scala/runtime/BoxedUnit.UNIT:Lscala/runtime/BoxedUnit;
N+1: pop
```

This stems from doing Tuple-pair-wise-peel-off(tm), basically:
```scala
inline def doNextThing[Elems](idx: Int, p: Product): Unit =
   inline erasedValue match {
       case _: (a *: b) =>  doThing[a](p.productElement(idx).asInstanceOf)
       case _: Unit => () // Base case
   }
```

I had thought the empty `()` would get removed from the AST/generated code, but it seems to show up in bytecode.  Additionally, when doing nested Product types with the same technique, I see BoxedUnit accessed and discarded at every nested-product boundary.

**Comment by nicolasstucki** [comment]
Those where supposed to be handled by the local optimizer which was removed in #4799

**Comment by nicolasstucki** [comment]
@jsuereth could you give a self contained snippet of code that reproduces the issue?

**Comment by jsuereth** [comment]
@nicolasstucki I'll be a bit, but I can.

**Comment by nicolasstucki** [comment]
It is possible that the new backend already optimizes those. Maybe we should wait until we upgrade the backend and see if it is still a problem.

**Comment by TheElectronWill** [comment]
Hello, has the backend been upgraded? It seems that some `BoxedUnit`s are still there.
Here is a minimal example:
```scala
class SpuriousUnits {
  inline def inlined(f: => Unit): Unit = f
  def use: Unit = inlined { println("") }
}
```
The `use` method gets compiled to:
```scala
getstatic scala/Predef$.MODULE$:scala.Predef$
ldc "" (java.lang.String)
invokevirtual scala/Predef$.println(Ljava/lang/Object;)V
getstatic scala/runtime/BoxedUnit.UNIT:scala.runtime.BoxedUnit
pop
```

Inline conditionals and matches are also affected:
```scala
  inline def printIfZero(x: Int): Unit = inline x match {
    case 0 => println("zero")
    case _ => ()
  }
  
  def useMatch: Unit = printIfZero(0) // contains getstatic BoxedUnit.UNIT at the end
```
  
  
Interestingly, if we do
```scala
def noop: Unit = inlined { () }
def useMatch2: Unit = printIfZero(2) // case _ => ()
```
then `BoxedUnit` doesn't show up like it seemed to do with jsuereth's code.

**Comment by nicolasstucki** [comment]
No, the backend has not been upgraded. This is something that will need some time.
