### ISSUE TITLE
anonymous given parse error

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#6864]
## minimized code

```Scala
trait Foo
trait Bar

given as Foo 
given as Bar
//    ^
//    not found: type as

trait C
trait Baz[A]

given as C
given [A] as Baz[A]
//    ^
//    an identifier expected, but '[' found
```

## expectation

These should parse and are fixed by adding brackets to the above given, e.g. `given as Foo {}` or a newline in between.

**Comment by liufengyun** [comment]
I'm not sure if this is a bug, as the following code is valid, and we need to support `given` params specified in a new line:

```Scala
class C
class D()
  given C
```

**Comment by bishabosha** [comment]
Ah, I hadn't thought of that, I found this issue through code that used to work with the previous keywords.

**Comment by nicolasstucki** [comment]
The current new line scheme supports 
```scala
given as Foo 
  given Bar
```

which is equivalent to 

```scala
given as Foo given Bar
```

This is a consequence of having renamed `delegate` to `given`. Now we do not know if the next `given` is the start of a definition or a `given` parameter.
