### ISSUE TITLE
Move typing of quotes and splices into its own trait

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#6873]
The code dealing with typing quotes and splices is 320 loc, about 10% of Typer as a whole. We want avoid Typer becoming excessively long. That's why I think it would be a good idea to move 
this code into its own trait, inherited by Typer, similarly to what we did with `Applications`, `Inferencing` or `Implicits`.

**Comment by nicolasstucki** [comment]
Fixed by #6875
