### ISSUE TITLE
No nightly build since 12/7/2019

### ISSUE THREAD

**Issue by milessabin** [lampepfl/dotty#6878]
The last available nightly build was published on 12/7/2019,

http://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.17/

which I think coincides with the CI upgrade ... did the nightly build job disappear during the switchover?

**Comment by smarter** [comment]
@Fnux can you investigate ? ^

**Comment by allanrenucci** [comment]
It used to be a cron job that lives on of the LAMP machine (ask @fsalvi). The cron job used to run the drone CLI. Something along the line of `drone deploy nightly ...`.

> there is a built-in cron-like system in Drone 1.x which should do the job.

Yes, I believe you should migrate to that and disable the old cron job.

**Comment by fsalvi** [comment]
There is a cron job on lampsrv43 (drone user) which was used for the nightly builds at 3am, using drone deploy.

**Comment by liufengyun** [comment]
We should make the bot create an issue when the nightly failed.  [ghi](https://github.com/stephencelis/ghi) is convenient for the purpose.

**Comment by milessabin** [comment]
Is there anything I can do to help move this along?

**Comment by smarter** [comment]
Meanwhile, I've started a nightly build manually: https://dotty-ci.epfl.ch/lampepfl/dotty/266 FYI, the syntax to do that has changed, using the binary from https://github.com/drone/drone-cli/releases, one needs to run:
```shell
drone build promote lampepfl/dotty 263 nightly
```
where "263" is the id of a successful build.

**Comment by smarter** [comment]
...actually that didn't work, but I think I have a fix: https://github.com/lampepfl/dotty/pull/6921

**Comment by Fnux** [comment]
I patched the cronjob on lampsrv43 a few days ago but did not take/find the time to update the `drone-ci.yml` file earlier as I am traveling. A build should be promoted every day at 3 AM (I suspect it happened for https://dotty-ci.epfl.ch/lampepfl/dotty/272/1/8).

**Comment by nicolasstucki** [comment]
It looks like we had a nightly build published for 0.18 just after the release of 0.17.0-RC1 http://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.18

**Comment by milessabin** [comment]
Is that the one that @smarter triggered by hand but apparently failed?

**Comment by smarter** [comment]
It's a different one i triggered by hand that worked.

**Comment by nicolasstucki** [comment]
Nightlies have been published every day since 2019-07-25
