### ISSUE TITLE
t8087.scala: Trait-defined volatile fields aren't volatile

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#688]

**Comment by odersky** [comment]
The fields are all volatile after traitConstructors. Does the backend not generate the annotation for some reason?

**Comment by DarkDimius** [comment]
Yes, that's a bug somewhere in backend. I guess it's due to not complete handling of annotations.

**Comment by odersky** [comment]
In Dotty, the annotations are only stored on symbols, not in typed trees.
This might be a reason for them being dropped.


On Fri, Jun 26, 2015 at 3:49 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> Yes, that's a bug somewhere in backend. I guess it's due to not complete
> handling of annotations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/688#issuecomment-115696906>.
>



-- 
Martin Odersky
EPFL
