### ISSUE TITLE
Dotty 0.16.0 was not released completely because of the CI resources problem

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#6922]
The release CI task encountered the same problem as #6832 multiple times. Namely the CI task was terminating abruptly at a random point, without an error message or apparent reason to do so. One time it happened [on test_java11](https://dotty-ci.epfl.ch/lampepfl/dotty/241) task. Another time it happened [on publish_release](https://dotty-ci.epfl.ch/lampepfl/dotty/252) task which wrote some artefacts (but not all) to Sonatype. When I tried to re-run the task, it now [terminated](https://dotty-ci.epfl.ch/lampepfl/dotty/264) with a proper error once it tried to publish artefacts that were already published.

[This diff](https://www.diffchecker.com/ssqfKcTi) shows which artefacts were not published (to the left, an example of a correct publish of 0.17.0-RC1, to the right, the broken publish of 0.16.0; versions replaced with a placeholder for clear diff). Precisely, the following artefacts were not published:

```
dotty-sbt-bridge to https://oss.sonatype.org/service/local/staging/deploy/maven2/ch/epfl/lamp/dotty-sbt-bridge/version-number/dotty-sbt-bridge-version-number-javadoc.jar 
dotty-sbt-bridge to https://oss.sonatype.org/service/local/staging/deploy/maven2/ch/epfl/lamp/dotty-sbt-bridge/version-number/dotty-sbt-bridge-version-number-sources.jar 
dotty-sbt-bridge to https://oss.sonatype.org/service/local/staging/deploy/maven2/ch/epfl/lamp/dotty-sbt-bridge/version-number/dotty-sbt-bridge-version-number.jar   
dotty-sbt-bridge to https://oss.sonatype.org/service/local/staging/deploy/maven2/ch/epfl/lamp/dotty-sbt-bridge/version-number/dotty-sbt-bridge-version-number.jar.asc   
dotty-sbt-bridge to https://oss.sonatype.org/service/local/staging/deploy/maven2/ch/epfl/lamp/dotty-sbt-bridge/version-number/dotty-sbt-bridge-version-number.pom   
dotty-sbt-bridge to https://oss.sonatype.org/service/local/staging/deploy/maven2/ch/epfl/lamp/dotty-sbt-bridge/version-number/dotty-sbt-bridge-version-number.pom.asc 
```

Hence, [here](https://repo1.maven.org/maven2/ch/epfl/lamp/dotty-sbt-bridge/), the `0.16.0` folder is absent at all.

So we need to manually publish the missing artefacts, and to investigate these CI failures. Unfortunately, I can't do it since I don't have access to the CI machine.

**Comment by anatoliykmetyuk** [comment]
By the way, the CI failure in question happened more for that release, but for a different commit: [one](https://dotty-ci.epfl.ch/lampepfl/dotty/218/1/7) [two](https://dotty-ci.epfl.ch/lampepfl/dotty/203/1/6). The first time failed on `test_scala212`, the second time – on `test_sbt`. After talking to @nicolasstucki, I cherry-picked his commit that dropped `test_scala212` since it is now not crucial to have (even though 0.16.0 should in principle compile against 2.12). The failures in the post above are what happened after the test was removed.

Another observation: the CI managed to reach the publish task at the time the load was small (I remember one-two tasks running together with mine). It failed earlier when there were many tasks running in parallel (4-5), which leads me to believe the reason is that the CI machine suffers from bad resource management.

**Comment by smarter** [comment]
Related: https://github.com/lampepfl/dotty/issues/6641

**Comment by OlivierBlanvillain** [comment]
Did this happen again? Does it make sense to keep the issue open?

**Comment by anatoliykmetyuk** [comment]
No, 0.18.1-RC1 and 0.17.0 were released properly. We should keep this open however since 0.16.0 is corrupted and we must fix it at some point.

**Comment by liufengyun** [comment]
Close now, I think no users will care about 0.16.0 anymore.
