### ISSUE TITLE
More `Liftable` instances are needed.

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#6933]
So far, we only have instances for primitive types and `String`. This is not enough. We should have at the very least instances for

 - Bigint, BigDecimal
 - all kinds of arrays
 - Seq, Set, Map

**Comment by nicolasstucki** [comment]
* Arrays
  - [ ] Array
  - [ ] IArray (#6928)
* Collections
 - [ ] immutable.Set (hashset only?)
 - [ ] immutable.Seq
 - [ ] immutable.List (#6928)
 - [ ] immutable.Map (hashmap only?)
* Numeric
  - [x] Primitives
  - [ ] BigInt
  - [ ] BigDecimal
* Other
 - [ ] Option (#6928)
 - [ ] util.Either (#6928)
 - [ ] reflect.ClassTag (#6928)
