### ISSUE TITLE
Anonymous given name clash for tuples

### ISSUE THREAD

**Issue by milessabin** [lampepfl/dotty#6938]
I _think_ this is only an issue for tuple types with arity > 1 ...

Given,
```scala
trait Foo[T]
object Foo {
  given [T] as Foo[Tuple1[T]] {}
  given [T, U] as Foo[(T, U)] {}
  given [T, U, V] as Foo[(T, U, V)] {}
}
```
The compiler will name the `Tuple1` instance as `Foo_Tuple1_given`, but both the `Tuple2` and `Tuple3` instances are named `Foo_Tuple_given` which results in the above failing with,

```
-- Error: local/given-tuples.scala:6:8 -----------------------------------------
6 |  given [T, U, V] as Foo[(T, U, V)] {}
  |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |  Foo_Tuple_given is already defined as class Foo_Tuple_given
one error found
```

**Comment by travisbrown** [comment]
FWIW I have a feature request for this here: https://github.com/lampepfl/dotty-feature-requests/issues/59

`(Int, Int)` and `(Int, String)` will also collide, as will `List[Int]` and `List[String]`, etc.

**Comment by milessabin** [comment]
Oh, right. I'd say that was a bug rather than a feature request. Synthetic names should never clash.

**Comment by aappddeevv** [comment]
I just hit this and its a real error. All the tuples get crunched down to the same name (in the same package).

The work around is to wrap it or put it in another package, etc.

**Comment by smarter** [comment]
> The work around is to wrap it or put it in another package, etc.

The simpler workaround is to give an explicit name to your givenq.

**Comment by aappddeevv** [comment]
Oh, that's much simpler. Did not think of that.
