### ISSUE TITLE
Quote pattern spliced expression has wrong type

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#6999]
## minimized code

```Scala
def expr(e: Expr[Any]) = {
  val '{ $x: $t } = e
  '{
    val a: $t = $x
   }
}
```

```
30 |        val a: $t = $x
   |                     ^
   |                     Found:    scala.quoted.Expr[Any](x)
   |                     Required: quoted.Expr[t.T]
```

## expectation
`x` should have type `quoted.Expr[t.T]`

**Comment by anatoliykmetyuk** [comment]
Also note the compiler crash described in #6997 when trying to cast, I think these two can be different issues

**Comment by nicolasstucki** [comment]
Actually the issue is type avoidance which seems to do exactly what it should.

```scala
val $1$: (scala.quoted.Expr[Any], scala.quoted.Type[_]) = e:quoted.Expr[Any](e) @unchecked match {  ...  }
val x: scala.quoted.Expr[Any] = $1$._1
val t: scala.quoted.Type[_] = $1$._2
'{ ... }
```

The correct way to express this is to write the complete pattern match 

```scala
e match {
  case '{ $x: $t } => 
    '{ val a: $t = $x }
}
```

**Comment by nicolasstucki** [comment]
Meeting up with type avoidance to make this pattern work is dangerous and probably fragile.

**Comment by nicolasstucki** [comment]
With new syntax it is possible to unpack on one line
```scala
e match case '{ $x: $t } =>
'{ val a: $t = $x }
```

**Comment by nicolasstucki** [comment]
The best we can do is to emit an error if a `val` pattern used type splices and guide the user to rewrite it as a `match`.
