### ISSUE TITLE
Export Java Annotation as value

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7033]
## minimized code

```Scala
export org.junit.{Test => test}
```

## expectation

This compiled in 0.16.0-RC3, but failed since 0.17.0-RC1

<details>
<summary>build error</summary>
<pre>
[error] -- [E119] Type Mismatch Error: /Users/jamie/Workspace/EEC/eec/src/test/scala/eec/compiler/types/bootstraps.scala:26:7 
[error] 26 |export org.junit.{Test => test}
[error]    |       ^^^^^^^^^
[error]    |       Java defined class Test is not a value
</pre>
</details>

**Comment by smarter** [comment]
I had to move this check in https://github.com/lampepfl/dotty/commit/bdc5b6fac70d537047e61a44b055a9c244152b50 but that shouldn't have affected anything, I guess an extra check to not emit an error when the Java class appear in an import statement is needed.

**Comment by bishabosha** [comment]
closing for #9415
