### ISSUE TITLE
Neg tests could  infer `//error` and `// error` as the same thing 

### ISSUE THREAD

**Issue by ashwinbhaskar** [lampepfl/dotty#7051]
When writing tests in `neg` package we have the option of giving `// error` at the end of a line to indicate a compilation error on that line. The space between `//` and `error` is strictly required and I have spent a lot of time figuring out why my tests in the `neg` folder did not work. Apparently I missed the space. 

Can we simplify this by treating both `//error` and `// error` as the same?

**Comment by nicolasstucki** [comment]
It would be better to have a single and homogeneous format.

What we could do is to identify `//error` in the test framework an emit a warning. This way if the test fail because the error tag was wrong, there will be a warning just before the test failure.

**Comment by ashwinbhaskar** [comment]
> It would be better to have a single and homogeneous format.
> 
> What we could do is to identify `//error` in the test framework an emit a warning. This way if the test fail because the error tag was wrong, there will be a warning just before the test failure.

@nicolasstucki Makes sense. Where should I start from if I am going to do this enhancement?

**Comment by nicolasstucki** [comment]
Probably here

https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/tools/vulpix/ParallelTesting.scala#L657

**Comment by ashwinbhaskar** [comment]
Can you assign this to me?

**Comment by ashwinbhaskar** [comment]
@nicolasstucki Is there any logger that I can use to print a warning? Or can I just go ahead with a `println`?

**Comment by nicolasstucki** [comment]
Try `echo` like in

https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/tools/vulpix/ParallelTesting.scala#L609

**Comment by ashwinbhaskar** [comment]
> Try `echo` like in
> 
> https://github.com/lampepfl/dotty/blob/master/compiler/test/dotty/tools/vulpix/ParallelTesting.scala#L609

Thank you. Does the PR look okay? https://github.com/lampepfl/dotty/pull/7062
