### ISSUE TITLE
Traits with a single abstract extension method are not treated as SAM types

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#7079]
The following compiles:

~~~ scala
trait Cmp[A] {
  def lt(lhs: A, rhs: A): Boolean
}

object Cmp {
  given as Cmp[Int] = (x, y) => x < y
  // Note the use of a lambda expression, which is expanded to the following:
  // new Cmp[Int] { def lt(x: Int, y: Int) = x < y }
}
~~~

However, changing the `lt` method to an infix method fails:

~~~ scala
trait Cmp[A] {
  def (lhs: A) lt (rhs: A): Boolean
}

object Cmp {  
  given as Cmp[Int] = (x, y) => x < y
  // error: Wrong number of parameters, expected: 1
}
~~~

Lambda syntax should support infix methods. In my example, `(x, y) => x < y` should expand to `new Cmp[Int] { def (x: A) lt (y: A) = x < y }`

**Comment by odersky** [comment]
Extension methods are curried, so a binary lambda will not work. 
I tried this instead:
```scala
object Cmp {
  given as Cmp[Int] = (x) => y => x < y
}
```
But that complains with
```
6 |  given as Cmp[Int] = (x) => (y) => x < y
  |                              ^
  |                            Missing parameter type
  |                            
  |                            I could not infer the type of the parameter y.
one error found
```
OK. Let's add the parameter type. Now we get:
```scala
6 |  given as Cmp[Int] = (x) => (y: Int) => x < y
  |                              ^^^^^^^^^^^^^^^^
  |                              Found:    Int => Boolean
  |                              Required: (rhs: Int): Boolean
one error found
```
So, to make this work, we'd need a recursive lifting of method types to function types in SAM types, and a corresponding unlifting for the actual implementation of the abstract method. This looks too hard. So I recommend we don't try to support this and demand the workaround instead.
