### ISSUE TITLE
Soft keywords are parsed greedy?

### ISSUE THREAD

**Issue by SrTobi** [lampepfl/dotty#7102]
## minimized code

```Scala
class X
object X extends X
given as as X = X
```

## expectation
A new given instance of name `as`

## actual
![image](https://user-images.githubusercontent.com/4148534/63697167-a38bd300-c81c-11e9-95a5-8285b160916f.png)

**Comment by SrTobi** [comment]
This might be correct behavior but then #7103 should work.

**Comment by odersky** [comment]
Yes, this is indeed the correct behavior. #7103 is about to be fixed instead.
