### ISSUE TITLE
scala.util.chaining appears to be missing (0.17)

### ISSUE THREAD

**Issue by aappddeevv** [lampepfl/dotty#7104]
I'm not sure if this was intentional or not. It's small package of course and easily reproduced, but I did not see any docs mentioning it.

**Comment by smarter** [comment]
Do you mean scala.util.ChainingOps ? That was added in the 2.13 standard library, but Dotty 0.17.0-RC1 still uses the 2.12 stdlib, the next Dotty release will be based on the 2.13 stdlib.
