### ISSUE TITLE
Advance the support for Scala.js

### ISSUE THREAD

**Issue by sjrd** [lampepfl/dotty#7113]
Dotty contains preliminary support for Scala.js under the flag `-scalajs`. Or rather, it contains the infrastructure for preliminary support. It is far from being actually usable, but this is where you can help!

I have written a tutorial that walks you through a few steps that you can do to further the support of Scala.js in Dotty. Even if you do not typically contribute to a compiler, this can be your chance. It is not very difficult, given that there already exists an extensive test suite, as well as a working implementation for scalac.

[Read the tutorial](https://gist.github.com/sjrd/e0823a5bddbcef43999cdaa032b1220c), and get going!

**Comment by neshkeev** [comment]
The following two tests from [`javalib.lang`](https://github.com/scala-js/scala-js/tree/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/lang) fail without `dotty` alteration (the rest of the tests from the package are added in #7255):

1. [`javalib/lang/ClassTest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/lang/ClassTest.scala): [error log link](https://gist.github.com/neshkeev/4416744cb8488a6947acc17e272b58bd)
2. [`javalib/lang/StringTest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/lang/StringTest.scala): [error log link](https://gist.github.com/neshkeev/86d7a3b624418c3cd6b149c0ff9c23ae)

**Comment by neshkeev** [comment]
The following tests from [`javalib.io`](https://github.com/scala-js/scala-js/tree/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/lib) fail without `dotty` alteration (only three tests from [`javalib.io`](https://github.com/scala-js/scala-js/tree/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/lib) are successful so far)

1. [`javalib/io/ByteArrayInputStreamTest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/io/ByteArrayInputStreamTest.scala): [error log link](https://gist.github.com/neshkeev/fa7da49d3758016ed1daf1906d3b3275)
2. [`javalib/io/ByteArrayOutputStreamTest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/io/ByteArrayOutputStreamTest.scala): [error log link](https://gist.github.com/neshkeev/27b1ef3afe94b11ed2b2cd6a669b4089)
3. [`javalib/io/DataInputStreamTest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/io/DataInputStreamTest.scala): [error log link](https://gist.github.com/neshkeev/dd449ccbebf24f73a3eee21614832a83)
4. [`javalib/io/DataOutputStreamTest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/io/DataOutputStreamTest.scala): [error log link](https://gist.github.com/neshkeev/579b58eddcf0fc33efecbcf05adfcc78)
5. [`javalib/io/InputStreamTest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/io/InputStreamTest.scala): [error log link](https://gist.github.com/neshkeev/e2ddb229930e51f325f28cfcd9c00eb8)
6. [`javalib/io/OutputStreamWriterTest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/io/OutputStreamWriterTest.scala): [error log link](https://gist.github.com/neshkeev/5f81679bb378d09a40f6729d9d787605)
7. [`javalib/io/PrintStreamTest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/io/PrintStreamTest.scala): [error log link](https://gist.github.com/neshkeev/03be2f101183fea8150d01db6dad34ce)
8. [`javalib/io/ReadersTest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/io/ReadersTest.scala): [error log link](https://gist.github.com/neshkeev/401bd70b6708a9d9dc2152aced2e1173)

**Comment by neshkeev** [comment]
All the tests from [`javalib`](https://github.com/scala-js/scala-js/tree/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/math) have been enabled, no failing tests were discovered #7272

**Comment by neshkeev** [comment]
The following test from the [`javalib.net`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/net/) fails:
1. [`javalib/net/URITest.scala`](https://github.com/scala-js/scala-js/blob/v1.0.0-M8/test-suite/shared/src/test/scala/org/scalajs/testsuite/javalib/net/URITest.scala): [error log link](https://gist.github.com/neshkeev/d19a8d368b88c81a3916496fb250b430)

**Comment by Lacaranian** [comment]
I may dig into that URITTest failure.

**Comment by neshkeev** [comment]
@Lacaranian , good, please do it

**Comment by sjrd** [comment]
Thanks to all of you who have contributed to the support of Scala.js in Dotty.

Since I've been allocated time at the Scala Center to finish it, it is now almost done, and so I think this issue can be closed.
