### ISSUE TITLE
Quoted expression in annotations are not reified

### ISSUE THREAD

**Issue by liufengyun** [lampepfl/dotty#7123]
## minimized code

```Scala
import scala.quoted._

class annot[T: Type](x: Expr[T]) extends scala.annotation.Annotation

class Test()(implicit qtx: QuoteContext) {
  @annot('{4})
  def foo(str: String) = '{4}
}
```

The code `'{4}` stays unchanged until the backend, as can be seen from `-Xprint:all`.

## expectation

I'm not sure if this is a bug, as annotations do not have runtime semantics.

Founded from #7053.

**Comment by nicolasstucki** [comment]
Duplicate of #7121
