### ISSUE TITLE
Context bounds are not added as dedicated given clause

### ISSUE THREAD

**Issue by SrTobi** [lampepfl/dotty#7127]
(I'm on `0.18.1-bin-20190827-2bbfd17-NIGHTLY`)

According to https://dotty.epfl.ch/docs/reference/contextual/context-bounds.html, context bounds are added to the function signature as their own given clause. But Apparently they are __prepended__ to the last given clause

## minimized code

```Scala
class Somethingable[T]
def fun[T: Somethingable](t: T) given Int given String = ()

fun(1) given 3 given "test" given Somethingable()
```

## expectation
Code compiles

## actual
```
[error] -- [E007] Type Mismatch Error: /[...]/src/main/scala/Main.scala:58:21 
[error] 58 |fun(1) given 3 given "test" given Somethingable()
[error]    |                     ^^^^^^
[error]    |                     Found:    String("test")
[error]    |                     Required: Somethingable[Int]
[error] one error found
```

## note

Following works:
```scala
class Somethingable[T]

def fun[T: Somethingable](t: T) given Int given String = ()


fun(true) given (3) given (Somethingable(), "test")
```
As you can see, `Somethingable()` has to be supplied as first parameter of the last given clause.

**Comment by SrTobi** [comment]
Ok, I found https://dotty.epfl.ch/docs/reference/contextual/relationship-implicits.html#context-bounds but I still think if you are using given clauses the context bounds should be added as a new clause.

And if not that then at least appended to the end of the last given clause and not be prepended.

**Comment by SrTobi** [comment]
I think this is done here:
https://github.com/lampepfl/dotty/blob/c3233d2eed02a9777fac3f68c6bc15d7faa0d441/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L362

I think that `evidenceParams` and `vparams` must be swapped. Or check if one of the present clauses is a given clause and just add a new one

**Comment by nicolasstucki** [comment]
Updated syntax
```scala
object Test {
  class Somethingable[T]
  def fun[T: Somethingable](t: T)(given Int)(given String) = ()
  fun(1)(given 3)(given "test")(given Somethingable())
}
```

**Comment by nicolasstucki** [comment]
Note that the current desugaring adds the contexts bounds at the start of the last given/implicit parameter list. Desugaring to the previous example to
```scala
def fun[T](t: T)(given Int)(given Somethingable[T], String) = ()
```

This seems to be necessary for Scala2 compat.

**Comment by odersky** [comment]
Yes, it's necessary for Scala-2 compat.
