### ISSUE TITLE
Implement kind projector's functionality directly

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#7139]
We already accept both `_` and `?` as a wildcard. Following kind projector, we should now accept `*` as a parameter placeholder for a type lambda.

**Comment by smarter** [comment]
Note that this should be guarded by the (already existing) `-Ykind-projector`, which I think should also support the other syntaxes for type lambdas implemented by kind-projector to ease cross-compilation:
```scala
Lambda[A => (A, A)]
λ[A => (A, A)]
λ[(+[A], +[B]) => Either[A, B]]
λ[(`+A`, `+B`) => Either[A, B]]
```
See https://github.com/typelevel/kind-projector

**Comment by travisbrown** [comment]
For what it's worth we could very easily live without kind-projector's variance syntax in Cats (see [this PR](https://github.com/typelevel/cats/pull/3207) for the change), and in all of the other Typelevel or Typelevel-adjacent projects I just checked.

I currently have a `-Ykind-projector` implementation for `*` and am working on `λ[A => ...]`, and am hoping to have a PR ready early next week, but I personally don't see supporting kind-projector's `-*` or the backticked variance stuff as a priority.
