### ISSUE TITLE
Missing JAR file in Dotty release 0.18.1-RC1 ?!

### ISSUE THREAD

**Issue by michelou** [lampepfl/dotty#7146]
The following JAR file is missing in Dotty release 0.18.1-RC1:
```
lib/dotty-staging_0.18-0.18.1-RC1.jar
```
but is available from the Maven Central Repository:
```
https://search.maven.org/artifact/ch.epfl.lamp/dotty-staging_0.18/0.18.1-RC1/jar
```
Indeed, one can read the following in shell script `bin/common`:
```
110: DOTTY_STAGING=$(find_lib "*dotty-staging*")
```
and a variable `$PSEP` is missing on line 105 in shell script `bin/dotr` (before variable `$DOTTY_STAGING`):
```
105:    cp_arg+="$PSEP$DOTTY_COMP$PSEP$DOTTY_INTF$PSEP$SCALA_ASM$DOTTY_STAGING"
                                                                ^^^^^^
```

**Comment by bishabosha** [comment]
dotty staging is now a separate module as of #7080, just add it to your dependencies

`libraryDependencies += "ch.epfl.lamp" %% "dotty-staging" % scalaVersion.value`

**Comment by michelou** [comment]
@bishabosha And what about the reference to $DOTTY_STAGING in the two shell scripts `bin/common` and `bin/dotr` ??!!
