### ISSUE TITLE
Member of derived typeclass becomes Nothing

### ISSUE THREAD

**Issue by fhackett** [lampepfl/dotty#7196]
## minimized code

```scala
package towers.computes

sealed trait RuleMagic[R] {
  type ComputesMembers
}

object RuleMagic {
  inline def derived[R] <: RuleMagic[R] = new RuleMagic[R] {
    type ComputesMembers = Int
  }
}

object Computes {
  inline def constructor[R] given (magic : RuleMagic[R]) : (magic.ComputesMembers)=>Int =
    (members : magic.ComputesMembers) =>
      ???
}

case class AddInts(rhs : Int) derives RuleMagic

// test

def test = Computes.constructor[AddInts](0)

```

Trying to compile this yields the following error:
```
[error] 23 |def test = Computes.constructor[AddInts](0)
[error]    |                                         ^
[error]    |                                         Found:    Int(0)
[error]    |                                         Required: Nothing
[error] one error found
```

## expectation

`Computes.constructor[AddInts]` should typecheck when passed an Int.

This is heavily minimised so I might have broken something else in the process, but that error at least makes no sense.

In case it's useful, the complete code makes several other uses of that same type member, in which case it has the correct type. It is specifically inside `constructor` that problems occur.

**Comment by milessabin** [comment]
The issue is that the derived instance is typed as exactly `RuleMagic[AddInt]`, ie. without the refinement `type ComputesMembers = Int`.

You can get the effect you intended by defining the instance manually with the refinement explicitly included, like so,

```scala
case class AddInts(rhs : Int) //derives RuleMagic
object AddInts {
  given as (RuleMagic[AddInts] { type ComputesMembers = Int}) =
    RuleMagic.derived[AddInts]
}
```

But clearly this is undesirably long-winded.

We could arrange for derived instances to be typed as precisely as possible, including all refinements implied by their RHS ... @odersky, what do you think?

**Comment by fhackett** [comment]
@milessabin Thanks for explaining. I have a follow-up question though: notice how I defined `derived` as a whitebox macro - why was that not taken into account? I would understand your explanation if I wrote `: RuleMagic[R]`, but to me `<: RuleMagic[R]` is pretty explicit about the intention to expand to the RHS type...

Did I just misunderstand something, suggest a way to write the feature you asked @odersky about, or some other thing? (inclusive or)

**Comment by milessabin** [comment]
@fhackett your definition of `derived` is just fine, and the result type of that method is refined in just the way you expect.

The problem isn't with your `derived`, it's with the (invisible) instance definition generated by the `derives` clause. It's typed as `RuleMagic[AddInts]` (ie. without the refinement) rather than the `RuleMagic[AddInts] { type ComputesMembers = Int}` that you want.

**Comment by fhackett** [comment]
@milessabin Ah thanks, I see what you're getting at now.

[rest I was typing before you responded, it's probably still relevant]

On a different note, here is some context of what I was trying to do pre-minimised example, since this isn't just a bug report anymore. (and to avoid asking for Y when I want X, but Y isn't even how to get X)

I am trying to create a compile-time rewrite engine / optimising compiler for combinator-like DSLs. The idea is for the actual engine to know as little as possible about the language being rewritten (except that it generally follows lambda calculus), and for the user to get the same kind of typechecking as if they were writing normal case classes. The most advanced user will define their own AST types, along with methods that define rules like what patterns can be optimised, how to lower their AST types to a small set of primitive ASTs, and any other hints they might want to provide to the engine. Your everyday user would import that user's AST library and write code in it, also fully typechecked (and get a domain-specific optimising compiler for free).

Anyway, what I'm actually trying to do with my typeclass derivation is to get Dotty to generate glue code and types that I can use to link the AST author's types / rule definitions both to the rewrite engine's internals and the end-user's usage.

Below I've included specific definitions of parts described above, so you can see how I'm trying to achieve this (explains and contextualises the original minimised code). I think typeclass derivation is currently my best / only shot at getting this to work. Let me know if you'd like me to explain something, would like the full codebase to mess with, or if I'm "doing it wrong" somehow.

Unabridged RuleMagic, to show all the kinds of stuff I expect the typeclass to fill in:
```scala
sealed trait RuleMagic[R <: Rule[_]] {
  type T = R match { case Rule[t] => t } // typeclass can't have 2 params
  val handles : List[AnyRef] // list of case class member handles
  def makeInstance : R // make an instance of the specific Rule case class (not the AST node)
  def membersToList(members : ComputesMembers) : List[Computes[_]]
  def tType given QuoteContext : Type[T] // encapsulate all the QuoteContext manipulation for types
  type ComputesMembers <: Tuple // type accepted by end-user level AST constructor
}
```

Example `Rule[_]` case class fragment:
```scala
case class AddInts(lhs : CHandle[Int], rhs : CHandle[Int]) extends Rule[Int] derives RuleMagic {
[...]
```
`lhs` and `rhs` are handles for the class body to use in a type-safe way. They can be used in the right context to get the actual "members" of the AST node being operated on (wrapping access to untyped rewrite engine internals).

Fully generic constructor for an AST node defined by a `Rule[_]` (the actual thing I reported a bug on):
```scala
inline def constructor[R <: Rule[_]] given (magic : RuleMagic[R]) : (magic.ComputesMembers)=>Computes[magic.T] =
    (members : magic.ComputesMembers) =>
      ComputesComposite[magic.T,R](magic.makeInstance, magic.membersToList(members))
```
`ComputesComposite` is an engine detail, holding untyped references to the actual data for processing.

**Comment by dwijnand** [comment]
Seems like a niche case to make it so typing derived instance make `new RuleMagic[R] { type ComputesMembers = Int }` type as `RuleMagic[R] { type ComputesMembers = Int }`.  We can reopen if there turn out the be more cases or uses to do this.
