### ISSUE TITLE
Is this a bug? Interaction between `export` and pattern match

### ISSUE THREAD

**Issue by ryanberckmans** [lampepfl/dotty#7219]
## minimized code

Please see this issue https://github.com/ryanberckmans/noric-bot/issues/1

Minimal repro https://scastie.scala-lang.org/MKy4rSaLSdKhSmuH7uALQA

Screenshot of this issue

![image](https://user-images.githubusercontent.com/299324/64873400-950c2c80-d60e-11e9-80b5-a4b1e086db57.png)

## expectation

No compile warning.

**Comment by liufengyun** [comment]
Thanks for reporting @ryanberckmans , it looks like to be a bug. It helps a lot if the code can be minimized to a small snippet.

**Comment by ryanberckmans** [comment]
I'll work on a minimal repro and update

**Comment by ryanberckmans** [comment]
@liufengyun minimal repro https://scastie.scala-lang.org/yf4rBiWxQXeVmdRUA1XDWQ

Please note the "Related Issue" in the Scastie snippet. I may have some confusion around the semantics of `type X = Foo.X` vs `export Foo.X`.

**Comment by liufengyun** [comment]
Thanks @ryanberckmans , it helps a lot.

It seems we miss some dealiasing in subtype checking (the same for the problem in your comment):

```Scala
object Foo {
  enum MyEnum {
    case Red
    case Blue(msg: String)
  }
  export MyEnum._

  val a: Foo.MyEnum.Blue = ???
  a : Foo.Blue   // error:  Found: Foo.MyEnum.Blue(Foo.a), Required: Foo.Blue
}
```
