### ISSUE TITLE
Trivial Scastie snippet fails due to "Expected a toplevel definition"

### ISSUE THREAD

**Issue by ryanberckmans** [lampepfl/dotty#7221]
https://scastie.scala-lang.org/hQRmWshCQeiGirP0cs1JgA using dotty 0.18.1-RC1

**Comment by liufengyun** [comment]
The following works:

```Scala
@main def test = println("hi")
```

Note that Scastie is not a repl, thus it follows Scala syntax: currently Dotty only supports top-level definitions.

**Comment by ryanberckmans** [comment]
Makes sense. I'd classify this is a minor ergonomic issue. The linked snippet works if you change build settings to Scala 2.13, thus it should work with dotty, in my opinion.

**Comment by liufengyun** [comment]
If it works in 2.13, then it should work for Dotty.

To facilitate the fix, we need to open an issue here:
https://github.com/scalacenter/scastie

**Comment by ryanberckmans** [comment]
@liufengyun you got it https://github.com/scalacenter/scastie/issues/446 . Closing this.

**Comment by liufengyun** [comment]
Thanks @ryanberckmans 👍
