### ISSUE TITLE
Significant indentation error when not trying to use significant indentation

### ISSUE THREAD

**Issue by ryanberckmans** [lampepfl/dotty#7222]
## minimized code

https://scastie.scala-lang.org/fZwbtgGhTdy94SWV3BaXDQ
![image](https://user-images.githubusercontent.com/299324/64881439-68f9a700-d620-11e9-809d-89f568b591bd.png)

## expectation

Whitespace ignored like Scala 2. My understanding is that significant indentation is opt-in and I don't think that Scastie snippet's build settings has opted in.

**Comment by odersky** [comment]
The current version of dotty has indentation on by default. We will make a decision at the end of the experiment whether it stays that way.
