### ISSUE TITLE
CI is down

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#7229]
https://dotty-ci.epfl.ch/lampepfl/dotty

![image](https://user-images.githubusercontent.com/3648029/64919117-71301e80-d7a7-11e9-9eb3-6c1ce3a535ef.png)

**Comment by smarter** [comment]
CI is back up after restarting docker on the servers, it was stuck on some moocs jobs /cc @Fnux

**Comment by odersky** [comment]
It would be good to have a timeout for every job running on the CI.

**Comment by Fnux** [comment]
That was a bug in drone, not long-running jobs. The UI reported inconsistent informations and even swapped logs between pipelines...
