### ISSUE TITLE
No nightly build published since 12/9/2019

### ISSUE THREAD

**Issue by milessabin** [lampepfl/dotty#7231]
See the [repo contents](http://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.19/).

Also there's something not quite right with the published version numbers ... up until the 4th they were being published as 0.19.1, then from the 5th onwards as 0.19.0. This means that `dottyLatestNightlyBuild` is currently returning `0.19.1-bin-20190904-beba63a-NIGHTLY` despite that not being the most recent.

The more recent failures are in [test_sbt](https://dotty-ci.epfl.ch/lampepfl/dotty/1305/1/6).

**Comment by smarter** [comment]
> Also there's something not quite right with the published version numbers ... up until the 4th they were being published as 0.19.1, then from the 5th onwards as 0.19.0.

The 0.19.1 was a mistake, 0.19.0 is correct, the fact that dottyLatestNightlyBuild is unfortunate, but there's no easy way to fix this.

**Comment by smarter** [comment]
Fixed by https://github.com/lampepfl/dotty/pull/7232, new nightly is up: https://repo1.maven.org/maven2/ch/epfl/lamp/dotty_0.19/0.19.0-bin-20190915-6f6d973-NIGHTLY/

**Comment by milessabin** [comment]
Just seen it ... thanks!
