### ISSUE TITLE
VSCode does not highlight given in import list

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#7233]
The new given import is like this:
```scala
import a.b.given
import a.b.{_, given}
import a.b.{given X}
```
Currently VSCode does not syntax-highlight the `given` in these positions.

**Comment by nicolasstucki** [comment]
![image](https://user-images.githubusercontent.com/3648029/65050180-4260a680-d967-11e9-899a-3ed7dcf8d71e.png)

**Comment by nicolasstucki** [comment]
@odersky could you have a look at https://github.com/scala/vscode-scala-syntax/pull/56
