### ISSUE TITLE
Dotty Website Sidebar Scrolling on Safari Desktop

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7275]
`Version 13.0 (14608.1.49)` for Safari
`Release 92 (Safari 13.1, WebKit 14609.1.4)` for Safari Technology Preview

If you expand options enough to go below the end of the window, then the sidebar does not become scrollable, as it does on Firefox and Chrome.

**Comment by anatoliykmetyuk** [comment]
Not only on Safari. Chrome Version 76.0.3809.132 – completely defaced & mouse wheel is not working :(

<img width="1392" alt="Screen Shot 2019-09-21 at 00 06 00" src="https://user-images.githubusercontent.com/2614813/65361436-d5b60800-dc03-11e9-8e40-0082b00a387c.png">
<img width="1392" alt="Screen Shot 2019-09-21 at 00 06 09" src="https://user-images.githubusercontent.com/2614813/65361451-de0e4300-dc03-11e9-9973-af0cd25e1c0c.png">

**Comment by anatoliykmetyuk** [comment]
BTW: such website failures are a good argument against publishing the website on releases only. We need the ability to react to such failures quicker than the release cycle.

**Comment by bishabosha** [comment]
@anatoliykmetyuk try clearing the cache, idk its a weird trick

**Comment by anatoliykmetyuk** [comment]
@bishabosha, ok, thanks, it worked.

**Comment by anatoliykmetyuk** [comment]
Why does it behave that way though? Not the best user experience

**Comment by smarter** [comment]
Our server might be sending incorrect HTTP caching headers which prevent proper cache invalidation.

**Comment by TheElectronWill** [comment]
Regarding the sidebar, it seems that the `overflow` property doesn't work with Safari as I've written it. It shouldn't be hard to fix, I'll do it tomorrow.

As for the rest, it looks like the server sent the new HTML file but the old CSS files.

**Comment by TheElectronWill** [comment]
Fixed in #7288
