### ISSUE TITLE
setter generation for var in class generates wrong code

### ISSUE THREAD

**Issue by aappddeevv** [lampepfl/dotty#7296]
https://gitter.im/lampepfl/dotty?at=5d88c6115d24375b3e075ca0

I'm claiming this generates the wrong code because it gives a warning under "-strict".

It appears that this warning pops up alot when -strict is set. I'm also getting these warnings on given instance declarations.

**Comment by smarter** [comment]
I think `-strict` should just not emit warnings for `def foo_=`, setters should be writable without using `@alpha`.
