### ISSUE TITLE
0.19: scala2 libraries are getting @infix warning and should not.

### ISSUE THREAD

**Issue by aappddeevv** [lampepfl/dotty#7304]

**Comment by aappddeevv** [comment]
Do you need a repo for this as well? It's pretty consistently warning on this for me on scala2 libs.

**Comment by bishabosha** [comment]
Is this still an issue @aappddeevv ?

**Comment by aappddeevv** [comment]
I'll have to check.

**Comment by julienrf** [comment]
I don’t see a warning here: https://scastie.scala-lang.org/2XeavB1aSRqtrnVLSO5kbw
