### ISSUE TITLE
Inconsistent behaviour of singleton types

### ISSUE THREAD

**Issue by tkroman** [lampepfl/dotty#7371]
## dotty version
"0.20.0-bin-20191004-736af36-NIGHTLY"

## minimized code

```Scala
@main
def run(): Unit = {
  enum X {
    case A, B
  }
  println(valueOf[X.A.type])
  val a = X.A
  println(valueOf[a.type])
  println(valueOf[X.A.type])
}
```

output:

```
null
A
A
```

Commenting out `val a = X.A`:

```
null
null
```

Running with just
```
val a = X.A
println(valueOf[X.A.type])
```

```
A
```

If this is something a beginner can fix, I'd appreciate some pointers on how to approach this to try and fix myself.

**Comment by OlivierBlanvillain** [comment]
This seems to be an enum only problem related to the static vals emited for the fields of "simple enums".

**Comment by tkroman** [comment]
seems to work correctly on 0.21.0-RC1
