### ISSUE TITLE
Unsoundness with Mirrors: it is possible to summon a mirror with an incorrect MirrorElemTypes of your choice

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#7380]
# Example
```scala
import scala.deriving.Mirror

@main def Test =
  val mrr = summon[Mirror.Of[(Int, String)] { type MirroredElemTypes = (Int, Int, Int) }]
  val ev1 = summon[(Int, Int, Int) =:= mrr.MirroredElemTypes]
  val ev2 = summon[(Int, String) =:= mrr.MirroredElemTypes]
  // val ev3 = summon[(Int, String) =:= (Int, Int, Int)]  // Implicit not found (correct, but breaks transitivity)

  val tup: (Int, String) = (1, "foo")
  val res: mrr.MirroredElemTypes = tup
```

Run it:

```scala
Exception in thread "main" java.lang.ClassCastException: scala.Tuple2 cannot be cast to scala.Tuple3
	at Test$package$.Test(Test.scala:10)
	at Test.main(Test.scala:3)
```

# Expectation
I would expect `mrr` to be impossible to summon because of the bad refinement type.

**Comment by milessabin** [comment]
Typically `MirroredElemTypes` would be unconstrained and computed by the summoning. Here it's been constrained with an incompatible type.

The fix for this is to verify that if `MirroredElemTypes` has been constrained then the computed type is compatible with the constraint.

**Comment by mpilquist** [comment]
BTW, I ran in to this issue in scodec when porting it to Dotty. I thought I had commented on this issue then but apparently not. I've been working around this limitation but not constraining `MirrorElemTypes` and taking a separate type equality, like here:

https://github.com/scodec/scodec/blob/main/shared/src/main/scala/scodec/Iso.scala#L61

I'd prefer to be able to write that as `protected def toTuple[A, B <: Tuple](a: A)(using m: Mirror.ProductOf[A] { type MirroredElemTypes = B }): B`
