### ISSUE TITLE
Trait members become Deferred during Mixin

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#740]
I was chasing the AbstractMethodError that I'm seeing while bootstrapping dotty, and I found a place that causes it:

https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/transform/Mixin.scala#L102

Here, all the successors that were non-abstract become abstract, making them not emitted in backend.

@odersky, could you please explain what this code was intended to do?

**Comment by odersky** [comment]
Getters and setters can't be implemented in a trait; they have to be implemented in the inheriting class. That's why they become abstract in the trait.

**Comment by odersky** [comment]
But of course the backend should emit a method even for an abstract method.

**Comment by DarkDimius** [comment]
Thanks for explaining. I'll fix the code to make sure it only applies to getters and setters.

I'm my case the bug was that this code made all the trait-defined modules became abstract.

> But of course the backend should emit a method even for an abstract method.

I guess you mean it should emit method signature, but not the method body?

**Comment by odersky** [comment]
Yes Emir the Signaturen
