### ISSUE TITLE
Non-local returns are not implemented

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#743]
```scala
object NonLocalReturn {
 def foo(a: List[Int]): Int = {
   a.foreach(x => return x)
   0
  }
}
```

Return will reach backend as part of 
```scala
    private def $anonfun$foo$1(x: Int): Nothing = return x
```

triggering an error: 
```
assertion failed: Expected primitive types I - Lscala/runtime/Nothing$;
```

**Comment by DarkDimius** [comment]
This phase is substantially easier to implement before `ExpandSAMs` has run, as after some functions will become anonymous classes.

**Comment by odersky** [comment]
@darkdimius I would have thought the opposite is true. To find out whether a non-local return is needed it would be good if SAMs and bu-name parameters were already expanded. Or am I missing something here?

**Comment by odersky** [comment]
Currently we are blocked on this by #746.
