### ISSUE TITLE
Colon after class or object signatures is not optional

### ISSUE THREAD

**Issue by provegard** [lampepfl/dotty#7432]
## minimized code

```Scala
object Main:
  def main(args: Array[String]): Int =
    println("it works")
    0
```

## expectation

0.19.0-RC1 changes colon after class/object signatures to not be required, which I interpret as "colon is optional", which in turn I interpret as "colon is ok".

Thus, the code above should compile (based on my interpretation of the changelog statement, which I realize may be incorrect).

Using `-Yindent-colons` doesn't change anything.

## actual

```
[error] C:\kod\projects\dotty-test\src\main\scala\Main.scala:1:12: end of statement expected but : found
[error] object Main:
[error]            ^
[error] C:\kod\projects\dotty-test\src\main\scala\Main.scala:2:3: ';' expected, but 'def' found
[error]   def main(args: Array[String]): Int =
[error]   ^
[error] C:\kod\projects\dotty-test\src\main\scala\Main.scala:4:5: Expected a toplevel definition
[error]     0
[error]     ^
[error] three errors found
[error] (Compile / compileIncremental) Compilation failed
```

## Use case

I have a project that uses 0.18.1-RC and significant indentation syntax with colons. Upgrading to 0.19.0-RC is problematic since the editor (VS Code with sbt-dotty) doesn't understand the absence of colons. So:

* With colons => the code doesn't compile
* Without colons => the editor marks basically all code as incorrect

**Comment by provegard** [comment]
Actually, both the compiler and editor accept this:

```
object Main
  def main(args: Array[String]): Int =
    println("it works")
    0
```

However, for this:

```
trait Foo
  def bar(s: String): String
```

* The compiler accepts it
* The editor underlines `bar` with: "Declaration of method bar not allowed here: only classes can have declared but undefined members"

And for this:

```
trait Foo:
  def bar(s: String): String
```

* The editor accepts it
* The compiler emits the errors in the issue description.

I use SBT 1.3.2 and have this in plugins.sbt:

    addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "0.3.4")

**Comment by bishabosha** [comment]
I have recreated everything and I see no error in the VSCode, do you use launchIDE to load the editor?

**Comment by provegard** [comment]
@bishabosha yes. However, I think I just managed to fix it. I tried to disable the "Scala Syntax (official)" extension (I thought it might interfere). It didn't work - I got an error stating that the Dotty LS extension depends on it - but all of a sudden the editor behaves consistently with the compiler. 

Just to be sure, I uninstalled Dotty LS and then Scala Syntax, and then re-installed Scala Syntax and used `launchIDE` to reinstall Dotty LS. Still works.

However strange that was, I won't complain. :)

About the other part of the issue - the interpretation of making colons non-required. It appears they now are forbidden (after object/class/trait) rather than not required. Is this correct?

**Comment by bishabosha** [comment]
@provegard yes, colons are only for function arguments now, I opened a PR for you - https://github.com/factor10/intent/pull/34

**Comment by provegard** [comment]
Ok, thanks for the clarification! And thank you for the PR!

**Comment by bishabosha** [comment]
I think the issue is that launchIDE does not force a clean when you change the scala version, so it leads to a mismatch in settings until you get a build that compiles,
