### ISSUE TITLE
trait setters do nothing

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#744]
```
javap -c dotty.tools.dotc.typer.FrontEnd

  public void dotty$tools$dotc$core$Phases$Phase$$myBase_$eq(dotty.tools.dotc.core.Contexts$ContextBase);
    Code:
       0: return
```

**Comment by odersky** [comment]
@darkdimius I'll have a look at lifted try's and non-local returns next.

On Tue, Aug 4, 2015 at 11:18 AM, Dmitry Petrashko <notifications@github.com>
wrote:

> Closed #744 <https://github.com/lampepfl/dotty/issues/744> via 7cfa2e1
> <https://github.com/lampepfl/dotty/commit/7cfa2e1e0ac3703161e33227d5729ddd81983f99>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/744#event-373347766>.
>



-- 
Martin Odersky
EPFL
