### ISSUE TITLE
Prevent extending java.lang.Enum except from an enum

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7499]
as detailed in https://github.com/lampepfl/dotty-feature-requests/issues/73, extending `java.lang.Enum` from a class is forbidden in Java, as Java enums are only guaranteed typesafe when created from its enum construct, additionally, the `super` call to `java/lang/Enum."<init>":(Ljava/lang/String;I)V` is synthesised by `javac` and the constructor is not exposed to Java source programs.

We should do the same in Dotty - extending `java.lang.Enum` should not be permitted apart from in an `enum`.

We should also support the old scala 2 way of extending `java.lang.Enum` with `3.0-migration`

**Comment by ekrich** [comment]
Linking for reference - https://github.com/lampepfl/dotty/issues/7174
