### ISSUE TITLE
lazy val in companion and private var in class do not play with reentrant checks

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7550]
## minimized code

compile with `-Ycheck-reentrant` on a dotty with `private[this]` inference:

**EDIT: added `@transient`**

```Scala
case class Range(start: Int, end: Int) with
  @transient private var __cache: Int = 0 // in scalapb code this is computed in another def

object Range with
  lazy val defaultInstance: Range = Range(0,0)
```

error:
```scala
possible data race involving globally reachable variable __cache in class Range: Int
  use -Ylog:checkReentrant+ to find out more about why the variable is reachable.
one error found
```

if we change to the following, the error does not appear
```scala
def defaultInstance: Range = Range(0,0)
```

In either case, the bytecode has a private field `__cache` and no accessors

**Comment by smarter** [comment]
Is it really wrong ? If two theads call Range.defaultInstance, and if one of them then calls some method on Range that causes __cache to be mutated, the other thread may not see that mutation.

**Comment by bishabosha** [comment]
I get the same error if I add `@transient`

**Comment by bishabosha** [comment]
I realise I mistook @transient for @volatile but neither makes a difference, but if nothing accesses `__cache` then surely there should be no problem?

**Comment by bishabosha** [comment]
I've found that this isnt really intended to be a public feature yet so ill close
