### ISSUE TITLE
Remove support for `-language:_`

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#7575]
We should just remove support for `-language:_`, it doesn't mean anything useful. But even then, I think it's strange that some `-language` flags just turn off warnings whereas others change the semantics of the language (and are therefore much more dangerous), I think we should clearly separate these two sets of options, in particular turning off language warnings should look like turning off any other kind of warning (something like the `-Wno-xxx` options in clang/gcc ?)

_Originally posted by @smarter in https://github.com/lampepfl/dotty/issues/6291#issuecomment-555031768_

**Comment by som-snytt** [comment]
I don't get this. `-language:_` means don't mess with me. If I use postfix ops, I intend it. Don't hassle me with so-called options.

I see scala 3 intends it to introduce `-source` as imports. Is that the issue? In that case, I would just take the latest available source level under "underscore". It would be cool if you could just specify on the command line _-source_ note that it is in underscores, a formatting pun.

"Don't mess with me!"

Other than the "progressive" nature of "language version" options, which induce warnings or errors, I don't see an ambiguity about what `language` features are for.

With `-Wconf`, one could re-imagine language features as aliases for `-Wconf`. There is a sense in which `-Wconf` is more expensive than the language feature look-up, so there could be a cost. Maybe that's an implementation detail.
