### ISSUE TITLE
documentation is missing polymorphic functions

### ISSUE THREAD

**Issue by SethTisue** [lampepfl/dotty#7594]
https://dotty.epfl.ch/docs/reference/overview.html says

> Polymorphic Function Types generalize polymorphic methods to dependent function values and types. Current status: There is a proposal, and a prototype implementation, but the implementation has not been finalized or merged yet.

but the implementation has been merged (#4672)

and the outline at https://dotty.epfl.ch/docs/index.html doesn't mention them

cc @milessabin

**Comment by smarter** [comment]
This is intentional, they won't be documented until they're fully implemented (I still haven't implemented type inference for them).

**Comment by griggt** [comment]
Should we close since #10663 was merged?
