### ISSUE TITLE
Please Revert Dotty Doc Style

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#7595]
Can we please revert the CSS for the Dotty Docs to what it was before? I find the new style visually galling compared to what we had before. It's a clear regression. Everything is worse, from insensitive contrasts to bad fonts.

**Comment by smarter** [comment]
It's not a simple matter of reverting something, it was significantly reworked to make it more maintainable and especially to make it responsive (it was pretty inconvenient to use on a phone before that): https://github.com/lampepfl/dotty/pull/7153. Concrete examples of what could be improved would help drive improvements.

**Comment by odersky** [comment]
Just come back to the same color schemes and fonts as before! It really is a difference like night and day. What looked tasteful and professional before now looks crude and amateurish. I am sorry to be so harsh but that's what I am seeing.

**Comment by smarter** [comment]
So, just switch the sidebar back to a white background, switch the top bar to a grey background and switch back the title font ? Not much else changed if I look at https://user-images.githubusercontent.com/10965722/64079352-d7686c00-cce6-11e9-8391-4a17674921d9.png

**Comment by smarter** [comment]
It's also worth noting that most of these design elements come from the front page which has always used these colors and this cursive font: http://dotty.epfl.ch/, the dotty-doc style changes just bring the doc pages in line with the front page; maybe the problem is with the front page but no one complained about that one until now.

**Comment by odersky** [comment]
Yes, I much preferred the style in the body pages over the front page, so adopting the frontpagse style for the bodies makes things worse for me. The other thing I noted was that the fonts in the old format were nicer, in particular the code font. The new one looks too wide.

**Comment by odersky** [comment]
Oh, and the left side bar is also too wide, compared to the previous design

**Comment by smarter** [comment]
> The other thing I noted was that the fonts in the old format were nicer, in particular the code font. The new one looks too wide.

We're currently using Adobe's [Source Code Pro](https://fonts.adobe.com/fonts/source-code-pro) (and the complementary Source Sans Pro for the text). I had a look at the old dotty-doc and it looks like we were using... nothing, or more precisely bootstrap's default font choices:
```css
font-family: Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
```
Menlo is a Mac OS X only font and I guess is what you were seeing. It doesn't appear to be open source, but it appear to be [a tweaked version of the open source DejaVu Sans Mono](https://9-bits.com/post/123940811/menlo-font-macosx) which we could use.

**Comment by bishabosha** [comment]
Fira font family is what I use everyday https://mozilla.github.io/Fira/

**Comment by odersky** [comment]
I find Fira much better than the Adobe fonts.

**Comment by TheElectronWill** [comment]
Allow me to step in as the author of #7153 :sweat_smile: 

As @smarter said, I've not pulled a new theme out of a hat but reused the front page's style.

> Just come back to the same color schemes and fonts as before! It really is a difference like night and day. What looked tasteful and professional before now looks crude and amateurish. I am sorry to be so harsh but that's what I am seeing.

Sorry about that. No one complained about the theme when I opened the PR; I assumed everyone was happy with the front page, it was wrong.

Fortunately, it's now much easier to change the colors and the fonts! So let's do this.
I'll make a PR to:
- make the sidebar more narrow
- (re)set the colors to a light palette
- replace Source Code Pro by Fira
- replace Lobster (the curvy script font used in the navbar) by a more "normal" font like Roboto

Is there anything else I should improve?

**Comment by bishabosha** [comment]
I believe the sidebar font should not be Source Sans Pro either, for me, it's too thick and rounded to be used with all caps at that size.
