### ISSUE TITLE
Certain community tests never run on the CI

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#7607]
Specifically these:

- scalacheck
- semanticdb
- xml-interpolator
- betterfiles

If you take a random's commit CI output for the `community_test` task, e.g. [this](https://dotty-ci.epfl.ch/lampepfl/dotty/2531/1/5), and look for these tests in this output, you will find each one or two times (where the submodule is checked out).

These tests work fine locally though, e.g. with the `community-build/testOnly dotty.communitybuild.CommunityBuildTest -- *scalacheck` command.

Also if you comment all the other tests but these four, these four also work on the CI: see #7606 and its [output](https://dotty-ci.epfl.ch/lampepfl/dotty/2646/1/3).

/cc @smarter

**Comment by smarter** [comment]
The last line of the logs is:
> warning: maximum output exceeded

Isn't it likely that these tests are run and the output is just not recorded ? I suggest fixing the million warnings output.
