### ISSUE TITLE
Outdated API in docs for macros

### ISSUE THREAD

**Issue by Blaisorblade** [lampepfl/dotty#7608]
1. `docs/docs/reference/metaprogramming/macros.md` uses sometimes `toExpr` for `Expr()`:
https://github.com/lampepfl/dotty/commit/4b732cef0741dc303ed2c34a3ceb123c080d2156#r36100940

2. `macros.md` doesn't say where to get `QuoteContext`. Today two people asked questions on this point on Gitter.

**Comment by nicolasstucki** [comment]
The QuoteContex is given within a top level $ in an online method. Or if using staging, the run or withQuoteContext provides it.

**Comment by machisuji** [comment]
There were some other issues I stumbled upon. I created another PR to (#7611) point those out. Not sure if that was the right thing to do. Please let me how else to do this in the future if it wasn't.
