### ISSUE TITLE
sbt runMain fails to recognize entry points

### ISSUE THREAD

**Issue by mslinn** [lampepfl/dotty#7614]
I find that `sbt runMain` does not work with dotty because none of the entry points are recognized. `sbt run` is currently the only way to run an entry point. For example, `dotty-example-project` exhibits this behavior.

**Comment by smarter** [comment]
`runMain` takes a class name as argument, if you run `runMain Main` from sbt in the dotty-example-project it works fine, so it seems that everything is in order. It doesn't work if you pass any other class from the dotty-example-project because there is only one main method defined in the project.

**Comment by mslinn** [comment]
@smarter I know this. Please try https://github.com/mslinn/dotty-example-project/

**Comment by smarter** [comment]
What's the issue exactly ? I tried `runMain ExtensionClasses` in your project and it displayed `circumference = 3.141592653589793` as expected.

**Comment by mslinn** [comment]
I ran on Windows Subsystem for Linux (Ubuntu), and on native Ubuntu. What OS did you test with?

**Comment by smarter** [comment]
I'm on Ubuntu.

**Comment by mslinn** [comment]
This is what I get:

```
sbt:dotty-example-project> runMain EnumTypes
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/mslinn/.sbt/boot/scala-2.12.7/org.scala-sbt/sbt/1.2.8/protobuf-java-3.3.1.ja
r) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list
[success] Total time: 14 s, completed Nov 25, 2019, 4:16:48 PM
```

**Comment by smarter** [comment]
> OK, so the problems are actually that no output is displayed as per my other reported issue,

There's no println statement in the body of EnumTypes: https://github.com/mslinn/dotty-example-project/blob/master/src/main/scala/EnumTypes.scala so that's why nothing is printed (there are println statements in the method test, but that won't be executed automatically when you run the main method).

> The warning should not appear when runMain is invoked on a valid entry point.

Agreed, but that's a bug in sbt, not in dotty as far as I can tell.

**Comment by mslinn** [comment]
Ugh, you are right :)
