### ISSUE TITLE
Dotty println no output under sbt

### ISSUE THREAD

**Issue by mslinn** [lampepfl/dotty#7615]
No output from `println` appears if an entry point is executed via `sbt run`. The only way to get output from `println` is to perform an evaluation in the console, for example `Typeclasses.test`. Try testing with https://github.com/mslinn/dotty-example-project/

**Comment by smarter** [comment]
I've tried it and I can't reproduce the issue, however I've noticed that the output is corrupted under sbt 1.3, so I've reported a bug against sbt: https://github.com/sbt/sbt/issues/5246. Try setting sbt back to 1.2.8 in project/build.properties and see if you still have the same problem. If so, please explain it in more details.

**Comment by mslinn** [comment]
Sbt 1.2.8 works ok.
