### ISSUE TITLE
DefDef.copy does not allow changing anything other than function body

### ISSUE THREAD

**Issue by fhackett** [lampepfl/dotty#7626]
## minimized code

```Scala
import quoted._

def fooImpl(given qctx : QuoteContext) : Expr[Int] = {
  import qctx.tasty.{_,given}
  val fn = '{
    def shouldBeHidden = ???
  }.unseal match {
    case Inlined(_, _, Block(List(theDefDef), _)) =>
      DefDef.copy(theDefDef)("realName", Nil, Nil, '[Int].unseal, Some('{1}.unseal))
  }
  Block(List(fn), Ref(fn.symbol)).seal.asInstanceOf[Expr[Int]]
}

inline def foo = ${fooImpl}
```

## expectation

Referencing `foo` should produce the value `1` by generating both the definition of and a call to an inner function named `realName` that returns the corresponding value.

Instead, we get a ClassCastError at runtime because Dotty's codegen keeps using shouldBeHidden's return type of `Nothing` instead of the copy's updated `Int` type. Inspecting the bytecode shows that the name of the generated method is `shouldBeHidden`, not `realName`.

Similarly, attempting to change anything else (other than the definition body) about `shouldBeHidden` has little or no effect, leading to either compiler errors or incorrect codegen.

`DefDef.copy` seems like the easiest way to generate computed-arity (local) functions, so it's unfortunate that transforming things other than the function body does not work.

**Comment by peykaz** [comment]
hello guys. I need your help. in my website every time I fix a problem with my friend’s mobile. What can I do to prevent these errors? my site is for [news](https://peyk.az/en) . and already tired of struggling with etomi errors .

**Comment by fhackett** [comment]
I have some follow-up thoughts from trying to work around this issue.

To properly generate a function with arbitrary arity you also need to make the parameters. If not, more internal compiler errors happen (Tasty pickler sees same symbol twice, is unhappy...).

If you have a function you want to replicate, I figured out you can call `DefDef.apply` instead and get fresh parameter symbols. That's nice and fixes half the problem.

The remaining problem is: how do we ask for a fresh function symbol? There are some useful transformations / refactors (think domain-specific inlining) you just can't write if macros are not allowed to properly make local copies of existing definitions.

That is, if we just had a variant of `DefDef.apply` that also generated a new `Symbol` (for local use only) then a lot of this issue would be resolved.

**Comment by nicolasstucki** [comment]
Copy should not change the symbol. Indeed, what we need is `DefDef.apply` which requires the creation of a new symbol. This will be possible after #8090

**Comment by fhackett** [comment]
@nicolasstucki Since this is evolving into more "making an API for generating new symbols", I've posted a new "Other" issue #8114 for discussing that and tracking further efforts.

Let me know what you think of the ideas going forward.

**Comment by nicolasstucki** [comment]
Replaced by #8114. Now possible using `DefDef.apply` and `Symbol.newMethod`
