### ISSUE TITLE
org.scalacheck.SeedSpecification failed in the community build

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7627]
Specifically the `Seed.longs` test 
![F16450C1-0166-47E4-8187-9E1D4FD7442A](https://user-images.githubusercontent.com/13436592/69709500-ca002980-10fd-11ea-9a54-3ec0f8661f8d.jpeg)

**Comment by smarter** [comment]
@ashawley, @non: have you seen this sort of test failure before ^ ? In any case we should try to upgrade the version of scalacheck in our community build to master I guess.

**Comment by ashawley** [comment]
It doesn't ring a bell, but Erik is the seed expert.  How far behind master are you?

**Comment by bishabosha** [comment]
150 commits behind

**Comment by smarter** [comment]
We're based on https://github.com/dotty-staging/scalacheck/commit/fea563b341ff7554d019ae0fff27b69b4cade259

**Comment by bishabosha** [comment]
maybe this? https://github.com/dotty-staging/scalacheck/commit/05a437ca7f99a9eab7a37cd0c4c21e494f586a62

**Comment by ashawley** [comment]
It's possible.  We don't have that change in ScalaCheck upstream.  I thought it was suggested in https://github.com/typelevel/scalacheck/pull/423, but I'm not seeing it.  I don't think it was included in the end.
