### ISSUE TITLE
`@alpha` conflicts with user-defined aliases

### ISSUE THREAD

**Issue by lrytz** [lampepfl/dotty#7629]
The 2.13 collections define aliases for certain symbolic operators, for example [`addOne` for `+=`](https://github.com/scala/scala/blob/v2.13.1/src/library/scala/collection/mutable/Growable.scala#L30-L38).

This conflicts with the requirements of the Scala 3 deprecation warning, currently under `-strict`

```scala
$> dotr -strict
scala> trait Growable[-A] { def addOne(elem: A): this.type; final def += (elem: A): this.type = addOne(elem) }
1 |trait Growable[-A] { def addOne(elem: A): this.type; final def += (elem: A): this.type = addOne(elem) }
  |                                                               ^
  |  method += has an operator name; it should come with an @alpha annotation
// defined trait Growable

scala> trait Growable[-A] { def addOne(elem: A): this.type; @annotation.alpha("addOne") final def += (elem: A): this.type = addOne(elem) }
1 |trait Growable[-A] { def addOne(elem: A): this.type; @annotation.alpha("addOne") final def += (elem: A): this.type = addOne(elem) }
  |                                                                                           ^
  |        Double definition:
  |        def addOne(elem: Object): Growable in trait Growable at line 1 and
  |        final def +=(elem: Object): Growable in trait Growable at line 1
  |        have the same type after erasure.
```

Note that the `@alpha` name cannot be used in Scala (this is by design, according to @sjrd):

```scala
scala> trait Growable[-A] { @annotation.alpha("addOne") def += (elem: A): this.type }
// defined trait Growable

scala> (null: Growable[Int]).addOne(1)
1 |(null: Growable[Int]).addOne(1)
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |value addOne is not a member of Growable[Int]
```

I'm opening this issue so people can chime in and a decision can be reached. See also https://gitter.im/lampepfl/dotty?at=5dde72175ac7f22fb51a3c82.

**Comment by odersky** [comment]
I believe the intention is that @alpha should only be for docs and Java interop. The 2.13 collection aliases are true aliases, that can be used interchangeably with the symbolic operations. If we keep this design (which personally I find reasonable)  this means:

 - The @alpha name should be something different from the alias name
 - The alphabetic 2.13 aliases should be deprecated at some point, since the underlying philosophy is to have only one way to do things

**Comment by odersky** [comment]
One way we might be able to make this work is to make the alias methods `inline`. Then they don't exist anymore after erasure and we should not get a conflict (maybe we do get one right now, but in that case we could easily change the criterion for the warning to avoid the conflict). But I can't see how to do that while maintaining bincompat with 2.13.

**Comment by odersky** [comment]
Since @alpha's replacement `@targetName` is optional for symbolic operators, we do not seem to have a problem anymore. Just leave things as they are.
