### ISSUE TITLE
Wrong overload resolution: picks Any over Long with an Int argument

### ISSUE THREAD

**Issue by sjrd** [lampepfl/dotty#7630]
## minimized code

```scala
object Asserts {
  def assertEquals(expected: Any, actual: Any): Unit = {
    println(1)
    assert(expected.equals(actual), s"expected $expected but got $actual")
  }

  def assertEquals(expected: Long, actual: Long): Unit = {
    println(2)
    assert(expected == actual, s"expected $expected but got $actual")
  }
}

object Test {
  def main(args: Array[String]): Unit = {
    def foo(): Long = 42L

    Asserts.assertEquals(42, foo()) // an Int and a Long
  }
}
```

## observed behavior

The first overload, taking `Any`s, is selected over the second one.

```
1
Exception in thread "main" java.lang.AssertionError: assertion failed: expected 42 but got 42
        at dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
        at Asserts$.assertEquals(hello.scala:4)
        at Test$.main(hello.scala:17)
        at Test.main(hello.scala)
```

## expectation

Like in Scala 2, the second overload, taking `Long`s, should be selected, so that it prints:
```
2
```

## note

The API of `Asserts` above is defined in JUnit; it cannot be changed.

## workaround

We can work around the issue by making sure that both arguments truly are `Long`s:
```scala
object Test {
  def main(args: Array[String]): Unit = {
    def foo(): Long = 42L

    Asserts.assertEquals(42L, foo()) // Long and Long
  }
}
```

**Comment by odersky** [comment]
I believe this is a consequence that weak conformance is gone. In Dotty an `Int` is converted to a `Long` by a standard implicit conversion. If I translate the examples to classes and conversions:
```
object X {
  case class Int1()
  case class Long1()
  implicit def i2l(x: Int1): Long1 = Long1()

  def ae(expected: Any, actual: Any): Unit = {
    println(1)
    assert(expected.equals(actual), s"expected $expected but got $actual")
  }

  def ae(expected: Long1, actual: Long1): Unit = {
    println(2)
    assert(expected == actual, s"expected $expected but got $actual")
  }
}

object Test {
  def main(args: Array[String]): Unit = {
    import X._
    ae(Int1(), Long1())
  }
}
```
I get this output for both scalac and dotc.
```
1
Exception in thread "main" java.lang.AssertionError: assertion failed: expected Int1() but got Long1()
```

**Comment by odersky** [comment]
Since I guess we do not want to bring weak conformance back, I see no way to fix this. Close?

**Comment by sjrd** [comment]
Can it not be fixed directly in overload resolution?

If not fixed, we risk breaking quite a lot of testing code using JUnit, with runtime assertions. That's not a good migration story. :(

**Comment by smarter** [comment]
Yeah, isn't Scala overloading resolution supposed to always match Java ?

**Comment by odersky** [comment]
> Yeah, isn't Scala overloading resolution supposed to always match Java ?

There's no such requirement. But we try to come close, for compatibilities sake. 

So, we'd have to bring weak conformance back? That would be unfortunate.
