### ISSUE TITLE
Confusing `C(x)` in error message

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#7634]
## minimized code

```Scala
$ dotr
Starting dotty REPL...
scala> class C { protected val c = 42 }
// defined class C

scala> val x = C() ; x.c
1 |val x = C() ; x.c
  |              ^^^
  |value c in class C cannot be accessed as a member of C(x) from module class rs$line$2$.
  | Access to protected value c not permitted because enclosing object rs$line$2
  | is not a subclass of class C where target is defined
```
## expectation
As a confused beginner, instead of `as a member of C(x)`, I expect a phrase such as, `as a member of type C referenced as value x`. Obviously, that is unwieldy.

With the new `new`-less style, `C(x)` really looks like a constructor invocation.

**Comment by odersky** [comment]
Can we write `(x: C)` instead? Or any other idea how to express this in a concise way?

**Comment by AleksanderBG** [comment]
I think for error messages, it makes sense to just print `C` and disregard that we're actually dealing with a singleton subtype of that type. I don't think I ever saw an error message where the fact that the type was a singleton was relevant.

**Comment by som-snytt** [comment]
I was less confused when I understood that it was actually the familiar `Int(42)` notation. But people also ask for diagnostics or REPL output printed in a form they can paste. This change looks good. Of course, all dotty diagnostics look good compared side-by-side with scala 2.
