### ISSUE TITLE
unexpandedName needs hardening.

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#765]
Unexpanded name currently fails for names that have two consecutive '$'s in them. For instance, the super accessor of += in trait `T` would be encoded as "T$$super$$plus$eq". Its `unexpandedName` 
will then be "plus$eq", where "super$$plus$eq" would have been correct.

**Comment by smarter** [comment]
Somewhat related to #30.

**Comment by smarter** [comment]
Hopefully fixed by the semantic name PR: https://github.com/lampepfl/dotty/pull/2128
