### ISSUE TITLE
Replace Dottydoc with Tastydoc

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#7668]
This is an issue to discuss replacing Scaladoc with Tastydoc.

Tastydoc has a similar intermediate reprentation of code as Dottydoc, so the remaining work is to copy over the HTML "backend" from Dottydoc to Tastydoc, and to change the plumbing so that we use Tastydoc to generate dotty.epfl.ch. @BryanAbate any corrections/additions to the above are welcome.

@TheElectronWill If I understand correctly, you'd be interested in contributing the above? If so, this issue would be the place to keep us updated on the status of your work and ask us questions. IIRC, @BryanAbate has offered to help you in understanding Tastydoc internals (thanks Bryan!).

**Comment by BryanAbate** [comment]
I confirm that the intermediate representation of Tastydoc is pretty similar to Scaladoc and that I offer my help to understand Tastydoc if needed.
If anyone need a particular change/addition to the API, I can work on that as well.

**Comment by TheElectronWill** [comment]
Thank you to both of you!
I confirm my interest in contributing to this. I'll keep you updated.
To be sure: when you say `Scaladoc` here, do you actually mean `Dottydoc` (and not Scala 2's scaladoc)?

**Comment by AleksanderBG** [comment]
You're completely correct @TheElectronWill, there's too many *Docs here :) Fix'd the original post.

**Comment by TheElectronWill** [comment]
I've started to work on this :smiley:
I've updated the paths in tastydoc tests and got a failure for dotty library (see #9259). I'll probably fix those bugs first and then integrate the html generation.

**Comment by AleksanderBG** [comment]
@TheElectronWill unfortunately we've decided to enlist a developer to fully develop a documentation tool for Dotty - a documentation tool is a pretty important thing for a language, after all. Thanks for your offer of help!

**Comment by TheElectronWill** [comment]
np! A dedicated developer will lead to a better tool in the end, so that’s good news.

**Comment by AleksanderBG** [comment]
@TheElectronWill In order to keep you updated, we will be starting work on the doctool around July 20th. After initial period of quick development (2-3 weeks), we're likely to have a good picture of the remaining work and we may have precise issues where your help could be handy. One area where you probably could lend us a hand is styling the output of the tool, since you already know HTML/CSS. Let me know if you'd still be willing to help us out around the beginning of August and I'll keep you updated.

**Comment by TheElectronWill** [comment]
Thanks for the update!
I'm willing to help at the beginning of August :-)

**Comment by AleksanderBG** [comment]
@TheElectronWill could you send me your email address? We're going to send an introductory email to all the people who'd potentially be interested in contributing to the doc-tool (which also includes you Bryan, in case you're reading this :) ).

**Comment by TheElectronWill** [comment]
@AleksanderBG I've just sent you an email

**Comment by bishabosha** [comment]
@abgruszecki is there some other task before we can close this?

**Comment by abgruszecki** [comment]
@bishabosha well, I believe we still need to replace Dottydoc with Tastydoc (:P), afterwards I guess this one can be closed.

**Comment by bishabosha** [comment]
@abgruszecki how about now?
