### ISSUE TITLE
Lazy Val named "_" Is Not Actually Lazy

### ISSUE THREAD

**Issue by adamgfraser** [lampepfl/dotty#7675]
```Scala
object Example extends App {
  lazy val _ = ??? // throws an exception
  println("Hello, World!")
}
```

**Comment by odersky** [comment]
Cute, but it would help everyone even more if you explained why it does not work. If you had pointed out that the val must be `_` for it to fail you would have saved people valuable time in which they could fix bugs instead of solving puzzles.

**Comment by adamgfraser** [comment]
@odersky I'm really sorry. You're totally right. I was busy and just posted the failing example but I could have shared more context to help with diagnosing and resolving the issue. Please accept my apologies. I will keep that in mind for next time. Really appreciate all the work that you and everyone else on the team are doing.

**Comment by odersky** [comment]
@adamgfraser  No worries! I was a bit stressed out myself and should have worded my response better. Your feedback and contributions are very important for us.
