### ISSUE TITLE
ZIO Does Not Compile Against Latest Nightly Version of Dotty

### ISSUE THREAD

**Issue by adamgfraser** [lampepfl/dotty#7683]
Following up discussion in zio/zio#2412 we are not able to compile ZIO against the latest nightly version of Dotty. We are testing all PRs against Dotty 0.20 as part of our CI process so it appears that the issue relates to a change since then. Specifically, I am getting the following error:

```
[error] not found: /drone/src/library/src/scala/internal/Quoted.scala
[error] not found: /drone/src/library/src/scala/internal/Quoted.scala
[error] not found: /drone/src/library/src/scala/internal/Quoted.scala
[error] not found: /drone/src/library/src/scala/quoted/QuoteContext.scala
[error] not found: /drone/src/library/src/scala/quoted/QuoteContext.scala
[error] not found: /drone/src/library/src/scala/quoted/QuoteContext.scala
```

To reproduce, you can change [this](https://github.com/zio/zio/blob/4c081ae1835b5c60a7fd14227a6da905d918d517/project/BuildHelper.scala#L59) line in ZIO to use the latest Dotty nightly and then attempt to compile after setting the version to Dotty or do the same thing with my local branch [here](https://github.com/adamgfraser/zio/tree/dotty).

Sorry I don't have a more detailed diagnosis. Copying @smarter and @neko-kai.

**Comment by nicolasstucki** [comment]
@adamgfraser which `sbt` commands should I use to reproduce it?

**Comment by adamgfraser** [comment]
@nicolasstucki See below.

```
./sbt
++ 0.21.0-bin-20191202-ccb7b13-NIGHTLY
project stacktracerJVM
compile
```

**Comment by nicolasstucki** [comment]
If I publish the latest version of dotty locally it works. Maybe something is missing when publishing the artifacts. In which case https://github.com/lampepfl/dotty/commit/9e4ee9f96ec0a82677287c75296d74b34e9fb0e2 looks like a likely suspect.

**Comment by smarter** [comment]
> If I publish the latest version of dotty locally it works

If you publish it locally then then path to Quoted.scala will be a real file on your filesystem, so it makes sense that it would work and not emit a "not found" error.

**Comment by nicolasstucki** [comment]
true

**Comment by nicolasstucki** [comment]
I bisected it and it started in 718568065e97521fcf02afc854f6fb0c25111885

**Comment by nicolasstucki** [comment]
@smarter could you have a look? Revering 59ea176b30fbb7af725707a64fe90574c8f47f33 fixes the issue

**Comment by smarter** [comment]
That looks completely unrelated, no idea.

**Comment by nicolasstucki** [comment]
Double-checking it I saw that reverting it did not help

**Comment by nicolasstucki** [comment]
It is actually 718568065e97521fcf02afc854f6fb0c25111885

**Comment by nicolasstucki** [comment]
@adamgfraser could you try to minimize it in a self-contained example? Debugging this on the full ZIO project will be too complex and will not allow us to add a good regression test.

**Comment by bishabosha** [comment]
so if you unzip the jar file for the artifact `ch.epfl.lamp:dotty-library_0.21-0.21.0-bin-20191202-ccb7b13-NIGHTLY`, these strings can be found in the raw tasty files `scala/quoted/QuoteContext.tasty` and `scala/internal/Quoted.tasty`, but not in the contents if you do `-print-tasty` or `-decompile` on them

**Comment by smarter** [comment]
The error comes from this check: https://github.com/lampepfl/dotty/blob/0a33ad34e212d3eba2ecd41fac07dddc172e149d/compiler/src/dotty/tools/dotc/CompilationUnit.scala#L92-L95 which I don't think is actually useful.

**Comment by adamgfraser** [comment]
Yes. I was trying to minimize the example, at one point got a version with code commented out that compiled, and now I am able to compile the entire project successfully with no code commented out. So it seems like maybe there is some check for a missing file that is occurring too early, so we're not getting to the point where that file can be generated?

**Comment by adamgfraser** [comment]
Thank you!
