### ISSUE TITLE
Dotty pickles type trees of | and & to applied type tree of fictional symbols

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7688]
## minimized code

Because intersection types and union types are pickled in TASTy to applied type trees of imaginary types `scala.&` and `scala.|`, all implementations must intercept these names, when they could be reified as the intrinsic types that they are.

```Scala
trait A
trait B

type AwithB = A with B // pickles to scala.&[A,B]
type AandB  = A & B    // pickles to scala.&[A,B]

type AorB = A | B      // pickles to scala.|[A,B]
```

## expectation

maybe new tags `ANDtpt` and `ORtpt`

**Comment by smarter** [comment]
These tags were actually removed in https://github.com/lampepfl/dotty/pull/5935 but it might make sense to bring them back, the main benefit of https://github.com/lampepfl/dotty/pull/5935 is that it simplifies dotty internals, but that doesn't mean we can't represent & and | explicitly in Tasty itself. Also I think that this PR removed all the logic in tasty-reflect for constructing & and | types which is something people actually want to do in macros (cf. https://contributors.scala-lang.org/t/union-types-and-generalisations/3820/6?u=smarter) /cc @nicolasstucki

**Comment by bishabosha** [comment]
I took a stab at this, but preserving the positions for the idempotency test seems hard

**Comment by smarter** [comment]
do you mean that the positions are lost somewhere ?

**Comment by bishabosha** [comment]
So I pickled just the arguments of the AppliedTypeTree, with ANDtpt length tag, then when I reconstruct an AppliedTypeTree from the args and a ref(def.andType), the range was off by one

**Comment by bishabosha** [comment]
so I need to preserve the position of the tycon that is thrown away

**Comment by smarter** [comment]
Right, the typetree itself should have a position, but I don't think that's any different from other type trees.

**Comment by smarter** [comment]
Or do you mean the position of `&` itself in `A & B` ? I don't think that one matters for anything (you can't rename `&` to something else) so preserving it is not important.

**Comment by bishabosha** [comment]
```scala
$ diff before-pickling.txt after-pickling.txt
53c53
<                 ):scala.quoted.Expr[$t0 & T2@tests/pos/i7264c.scala<113..116>]@tests/pos/i7264c.scala<113..116>@
---
>                 ):scala.quoted.Expr[$t0 & T2@tests/pos/i7264c.scala<114..116>]@tests/pos/i7264c.scala<113..116>@
```

**Comment by bishabosha** [comment]
closing because we discussed in a meeting about tasty format that `scala.|` and `scala.&` are legitimate members of the scala package
