### ISSUE TITLE
Ambiguous implicits (works in Scala 2)

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#7695]
## minimized code

```Scala
trait Member {
  protected implicit def __anyContext[T] : Context[T] = ???
}
trait Context[T]
class Foo(implicit ctx : Context[_]) extends Member
class FooTop(implicit ctx : Context[_]) extends Foo {
  val foo = new Foo
}
```

## expectation
Scala 2 compiles this. It looks like Scala 2 is correct to have a better priority for the `ctx` argument instead of the internal `__anyContext` definition.

**Comment by odersky** [comment]
It seems to me that if anything, the member should have a higher priority since it is more closely nestd than the parameter. But since this is really splitting hairs I believe that raising an ambiguity is actually better.
