### ISSUE TITLE
REPL: directory under current directory shadows REPL-defined identifier

### ISSUE THREAD

**Issue by SethTisue** [lampepfl/dotty#7699]
this seems surprising and wrong, and quite difficult to troubleshoot if you don't think to look in the filesystem for an explanation:

```scala
% mkdir foo
% dotr
Starting dotty REPL...
scala> def foo = 3
def foo: Int

scala> foo                                                                                                              
1 |foo
  |^^^
  |package foo is not a value
```

whereas in Scala 2:

```
scala 2.13.1> foo
              ^
              error: package foo is not a value

scala 2.13.1> def foo = 3
foo: Int

scala 2.13.1> foo
res1: Int = 3
```

(aside: I mentioned to Martin that I remembered a similar Scala 2 ticket or PR, but after about 10 minutes of digging just now I failed to find it and gave up)

**Comment by SethTisue** [comment]
gah! duplicate of #7635

**Comment by som-snytt** [comment]
You have to get up pretty early in the morning to beat Seth to the old random directory in current directory results in surprising behavior ticket.
