### ISSUE TITLE
LaunchIDE has stopped working

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#7754]
LaunchIDE cannot run anymore since it gets hundreds of errors when trying to compile TastyDoc. I am surprised that TastyDoc is not compiled during the build, it seems that it's just launchIDE that compiles it on demand.

The TastyDoc version in the repo is badly outdated. So, it's not wonder it compiles with lots of errors. I am just mystified how this could have been merged without the problems being detected.

**Comment by odersky** [comment]
See #7755 For some of the fixes but there are other problems having to do with missing methods (137 of them). The problem is, without a working IDE I have a hard time following links etc for diagnosing these problems.

**Comment by AleksanderBG** [comment]
Fixed in #7686.
