### ISSUE TITLE
Fix class hierarchy diagram and docs for explicit nulls

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#7760]
http://dotty.epfl.ch/docs/reference/other-new-features/explicit-nulls.html

currently the link for the class hierarchy image is broken, and there are no links in the sidebar

**Comment by odersky** [comment]
Actually, the type hierarchy image still does not show.

**Comment by odersky** [comment]
In fact the diagram is outdated, and the surrounding text as well. `Null` is now a value type, not a subtype of Any. The docs and the diagram need to be fixed.

**Comment by odersky** [comment]
The link is good now, but the text and diagram need to be fixed.

**Comment by noti0na1** [comment]
@odersky Currently, `Null` is still a subtype of `Any`. 

I tried to simply change the parent of `NullClass` to `AnyValType`, but this doesn't work. There are some errors in the Erasure phase.

Should we also add it to `ScalaValueTypes`?

**Comment by milessabin** [comment]
I'm a little concerned that code which matches against `AnyVal` scrutinees now has to be prepared to handle `null`. Granted, `AnyVal` isn't sealed, and yes, `Null` is no different from any other non-primitive subtype of `AnyVal`, which also need to be handled, but I can see this causing some surprises.

**Comment by sjrd** [comment]
@milessabin Honestly that sounds like a totally made up concern to me. I've never seen any code trying to exhaustively match on an `AnyVal`. And if there was, either it was already broken because it didn't handle custom value classes; or it was in fact correct because only some specific subtypes reached that match, but in that case there would be no new `null` reaching such code and hence it would stay correct.

**Comment by milessabin** [comment]
Well, maybe, but here's something that isn't all _that_ far fetched,

``` scala
def handle[T](ot: Option[T]) = ot match {
  case Some(r: AnyRef) => handleAnyRef(r)
  case Some(v: AnyVal) => handleAnyVal(v)
}
def handleAnyRef(r: AnyRef) ...
def handleAnyVal(v: AnyVal) ...
```
Here `Some(null)` will go down different branches depending on how `-Yexplicit-nulls` is set. Or have I misunderstood?

**Comment by bishabosha** [comment]
This issue was about the diagram not showing, and maybe not being consistent with the implemented solution. However the diagram does show and it is consistent with the current state of things. Another issue should be opened for the status of where Null should go
