### ISSUE TITLE
Anonymous given name clash for classes within objects

### ISSUE THREAD

**Issue by arthurp** [lampepfl/dotty#7762]
```Scala
package A {
  class G
}

package B {
  class G
}

def m() = {
  given A.G = A.G()
  given B.G = B.G() // Error: given_G is already defined as method given_G
}
```

The second given produces the error: given_G is already defined as method given_G. This issue also appears if A and B are `object`s or are `class`es and the givens have path dependent types on instances of A and B.

## Expectation

Since the two givens have different types, they would be inferred for different given arguments to calls. As such they should both be able to exists at the same time and should be given different names by the compiler.

(I encountered this issue in real code where I had a convention of having an `SQL` class within the companion object for each of my data types.)

**Comment by odersky** [comment]
The purpose of synthesizing names is to synthesize short names that can be remembered and recognized easily and be used in debugging. There is not guarantee that synthesized names will never clash. If there is a name clash, one should simply use explicit names.
