### ISSUE TITLE
Eta-expanded methods never get a SAM type

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#777]
```scala
trait II {
  def apply(x: Int): Int
}

object Test {
  def ii(x: Int): Int = x
  def test = {
    val ii1: II = x => ii(x) // works

    val ii2: II = ii // error: missing arguments for method ii in object Test$
    // follow this method with `_' if you want to treat it as a partially applied function

    val ii3: II = ii _ // error:
    // found   : Int => Int
    // required: II
  }
}
```
`ii1` and `ii2` work with `scalac -Xexperimental` but `ii3` doesn't, see [SI-9449](https://issues.scala-lang.org/browse/SI-9449)

**Comment by odersky** [comment]
We don't have a spec for SAM types yet. I would actually argue that eta expansion should not create SAM types. That would follow the philosophy that we do the minimum to be Java compatible but not more.

**Comment by smarter** [comment]
>  That would follow the philosophy that we do the minimum to be Java compatible but not more.

Well, we already have https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/transform/ExpandSAMs.scala which allows SAM types to be used even when they're not SAMs according to Java

**Comment by odersky** [comment]
I think we want to keep things simple. This looks not like a priority.
