### ISSUE TITLE
Check bootstrapping issue with `quoted.Expr`

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#7781]
Check bootstrapping issue with `quoted.Expr`.

**Comment by nicolasstucki** [comment]
The idea is to remove the following pattern to avoid confusion with source file locations

```scala
package scala
package quoted {
  ...
}
package internal {
  package quoted {
    ...
  }
}
```

**Comment by odersky** [comment]
Is it not rather 
```
package internal {
  package quoted {
    ...
```
? I am still not sure what happened. Where do classes `...` end up when compiled? It should be `internal.quoted`. Then why does the compiler find the class in `internal`? Is it the class file or the source file that is to blame? is it the outline parser? It would be good to have a test to verify what goes wrong.
