### ISSUE TITLE
Pattern matching with an `AnyVal` scrutinee fails with unreachable case error

### ISSUE THREAD

**Issue by milessabin** [lampepfl/dotty#7783]
Compiling this,

```scala
object Test {
  def foo(t: AnyVal): Unit = t match {
    case _: Int =>
  }
}
```

gives me the following unreachable case error rather than the non-exhaustivity warning I was hoping for,
```
-- Error: local/nulls.scala:3:9 ------------------------------------------------
3 |    case _: Int =>
  |         ^
  |this case is unreachable since class AnyVal and class Integer are unrelated
1 error found
```

Assuming this _is_ a bug and that this _should_ instead give us a warning about a non-exhaustive match, then does this make the introduction of `Null` as a subtype of `AnyVal` with `-Yexplict-nulls` in https://github.com/lampepfl/dotty/pull/7546 problematic? Presumably the extra case would make previously exhaustive matches over existing `AnyVals` non-exhaustive?

**Comment by odersky** [comment]
This was indeed a bug. But you still won't get exhaustivity warnings since `AnyVal` is not sealed (it can have user-defined value classes besides the primitive value classes as children).

**Comment by milessabin** [comment]
> But you still won't get exhaustivity warnings since AnyVal is not sealed (it can have user-defined value classes besides the primitive value classes as children).

Nevertheless, should we be concerned that code which previously matched `AnyVal` scrutinees now has to be concerned about `null`?
