### ISSUE TITLE
Overloading doesn't work with function types

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#7792]
## minimized code

```Scala
trait Foo {
  def g(f: Int => Int): Int = 1
  def g(f: String => String): String = "2"
}

@main def Test =
  val m: Foo = new Foo {}
  m.g(a => 1)
```

```scala
-- [E051] Reference Error: /Users/kmetiuk/Projects/scala3/pg/sandbox/iss4.scala:8:4
8 |  m.g(a => 1)
  |  ^^^
  |Ambiguous overload. The overloaded alternatives of method g in trait Foo with types
  | (f: String => String): String
  | (f: Int => Int): Int
  |both match arguments (? => ?)
```

It works in Scala 2. If you explicitly specify the type of the lambda argument, `m.g((x: Int) => 1)`, it also works.

## expectation
The code should correctly resolve the overload alternative.

**Comment by anatoliykmetyuk** [comment]
Not sure if that's a real issue since we are working with untyped trees of arguments on overload resolution time, so we may not have a way to precisely resolve the type of `? => ?`...

**Comment by anatoliykmetyuk** [comment]
Though it works with

```scala
trait Foo {
  def g(f: Int => Int): Int = 1
  def g(f: Int => String): String = "2"
}
```

(Second `g`'s lambda accepts an `Int`) for some reason. Hence should also work in the original case.

**Comment by odersky** [comment]
I think that's precisely where Scala 2 and Dotty differ when dealing with overloaded functions taking lambda arguments. The Dotty version is simpler but also a bit more restrictive. We need to decide what the right spec is.

**Comment by sjrd** [comment]
Handling this kind of situation was added in Scala 2.13, because the new Scala collections basically rely on this working. They use overloading much more, whereas previously things were handled with complicated `CanBuildFrom` instances.

**Comment by odersky** [comment]
I don't think we will change this, after all.
