### ISSUE TITLE
Nothing inferred in polymorphic, inlined method 

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#7798]
## minimized code

```Scala
object Test {
  inline def meth[R <: Int]: R = 3.asInstanceOf[R] // inferred type is Nothing
  def main(args: Array[String]): Unit = {
    val t: Int = meth
  }
}

```

## expectation

It should work as in the normal case.

**Comment by biboudis** [comment]
There is something weird in inferencing when instantiation is occurring (in Inferencing.scala when `Inferencing.isFullyDefined` is called from inliner 🤷‍♂) :

```
committing TS[8, 1, 0] to TS[1, 0], fromConstr = Constraint(
 uninstVars = ;
 constrained types = [R <: Int] => R
 bounds = 
     R := Nothing
 ordering = 
), toConstr = Constraint(
 uninstVars = R;
 constrained types = [R <: Int] => R
 bounds = 
     R <: Int
 ordering = 
)
```

**Comment by odersky** [comment]
Inlining instantiates type arguments to the call. You can try to leave out the `isFullyDefined` call in the Inliner, but I guess bad things would happen. It seems like a scary feature interaction to inline code that references type variables that are not yet instantiated.
