### ISSUE TITLE
[new indented syntax] Confusing handling of yield indented blocs (following a for)

### ISSUE THREAD

**Issue by rom1dep** [lampepfl/dotty#7800]
On 0.20.0-RC1, considering the following code:

```Scala
    for x <- y
        […]
        z <- t
    yield something
          somethingElse
```
, one could be tempted to think that `something` and `somethingElse` are both part of the same `yield` bloc (and executed together), as they share the same indentation (which moreover echoes the one of the `for` above).

This isn't the case, and in fact, a valid syntax for this intent seems to be:

```Scala
    for x <- y
        […]
        z <- t
    yield
      something
      somethingElse
```

## expectation
It could perhaps be good to be able to use both interchangeably to mean the latter, or as a minimum, to have the compiler emit an indentation warning in the first case.

**Comment by odersky** [comment]
Indentation only looks at whitespace. So according to the rules, `somethingElse` is indented more than `yield`. The rules allow that, and there are in fact common use cases where some statements in a sequence are indented to the right of others (typically to indicate some nesting structure that is not reflected in the scoping structure). 

So I believe people will just to have to get used to the fact that indentation in Scala is tied to whitespace. That's different from Haskell, which has (IMO) far more complicated indentation rules.
