### ISSUE TITLE
Nothing inferred in polymorphic, method with empty parameter list

### ISSUE THREAD

**Issue by biboudis** [lampepfl/dotty#7805]
Nothing inferred in polymorphic, method with empty parameter list but `Int` inferred when method is parameterless.

## minimized code

```Scala
object Test {
  def meth[R <: Int]() : R = ???
  def main(args: Array[String]): Unit = {
    val person: Int = meth()
  }
}
```

## expectation
It should work the same either with or without a parameter list. 

```scala
object Test {
  def meth[R <: Int]: R = ???
  def main(args: Array[String]): Unit = {
    val person: Int = meth
  }
}
```

**Comment by odersky** [comment]
This is fixed by now, probably my one of the earlier type inference fixes.
