### ISSUE TITLE
ParamForwarding: questions

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#783]
https://github.com/lampepfl/dotty/blob/master/src/dotty/tools/dotc/transform/ParamForwarding.scala#L22
```scala
/** For all parameter accessors
 *
 *      val x: T = ...
 *
 *  if
 *  (1) x is forwarded in the supercall to a parameter that's also named `x`
 *  (2) the superclass parameter accessor for `x` is accessible from the current class
 *  change the accessor to
 *
 *    def x: T = super.x.asInstanceOf[T]
 *
 *  Do the same also if there are intermediate inaccessible parameter accessor forwarders.
 *  The aim of this transformation is to avoid redundant parameter accessor fields.
 */
```

I have several questions to what this phase does:

1. Why do names matter?
2. if indeed name has not changed, is not it better to remove def entirely? Than virtual dispatch will do the same that `def x: T = super.x.asInstanceOf[T]` does. (I guess the answer is that types could be different, but I want to make sure that there are no other reasons)

**Comment by odersky** [comment]
> Why do names matter?

To limit the search space, and make it more predictable.

> if indeed name has not changed, is not it better to remove def entirely? Than virtual dispatch will do the same that def x: T = super.x.asInstanceOf[T] does. (I guess the answer is that types could be different, but I want to make sure that there are no other reasons)

And we also need a witness for the parameter accessor later on (that's something pickling/unpickling needs, for instance)

**Comment by DarkDimius** [comment]
> And we also need a witness for the parameter accessor later on (that's something pickling/unpickling needs, for instance)


@odersky following examples from https://github.com/lampepfl/dotty/issues/776 scalac does not create such method. The examples in #776 also suggest that we cannot create `def x`, as either `private` or `protected` or `public` or `default`. We either need to remove the method(as scalac does) or to name mangle it.
