### ISSUE TITLE
Dotty adheres too strictly to SLS 4.7

### ISSUE THREAD

**Issue by hrhino** [lampepfl/dotty#7854]
> An import clause has the form `import p.I` where `p` is a stable identifier and `I` is an import expression.

So you say, but not always:

## minimized code
```java
// A.java
package x;
public class A {
  public class Inner {}
}
```
```java
// B.java
package x;
import x.A.Inner;
public class B {
  public static Inner test() { return null; }
}
```
```scala
// C.scala
package x;
object Test { B.test() }
```

```
[nix-shell:/code/scala/sandbox]$ dotc *.java *.scala
-- [E006] Unbound Identifier Error: B.java:4:16 --------------------------------
4 |  public static Inner test() { return null; }
  |                ^^^^^
  |                Not found: type Inner

longer explanation available when compiling with `-explain`
one error found
```

## expectation
javac likes it; dotc should too.

**Comment by odersky** [comment]
Can you please re-open this as a feature request? Also to consider this, we'd need spec language incorporating the proposed change.

**Comment by hrhino** [comment]
I don't think this is a feature request. I'm not asking that Scala's semantics be changed like this; the issue is only that I can't compile legal Java code together with legal Scala code (with either nsc or dotc, although I've got a bug fix for the former).
