### ISSUE TITLE
unable to create a quoted.Liftable

### ISSUE THREAD

**Issue by johnynek** [lampepfl/dotty#7858]
## minimized code

```Scala
object Foo {
  given Liftable[Boolean] {
    def toExpr(b: Boolean)(given QuoteContext): Expr[Boolean] =
      if (b) '{ true } else '{ false }
  }
}
```
I get:

```
[error] -- Error: /home/oscar/oss/olelo/src/main/scala/Olelo.scala:7:8 -----------------
[error] 7 |  given Liftable[Boolean] {
[error]   |        ^
[error]   |object creation impossible, since def toExpr(x: Boolean): (given quoted.QuoteContext) => quoted.Expr[Boolean] is not defined
[error]   |(Note that T does not match Boolean)
[error] one error found
[error] (Compile / compileIncremental) Compilation failed

```

## expectation
The error message is confusing to me. What is `T`? I don't mention that in my code. Also, it seems I have the method it is complaining about.

since this example is listed: https://dotty.epfl.ch/docs/reference/metaprogramming/macros.html

I thought this would work.

**Comment by johnynek** [comment]
This is with `0.21.0-RC1` set up using the giter8 template.

**Comment by johnynek** [comment]
Oh, I guess the issue is the docs are wrong. The signature needs to be:
```
def toExpr(b: Boolean): (given QuoteContext) => Expr[Boolean]
```
It would be really nice if the error message were more helpful here given how close my code was.

**Comment by nicolasstucki** [comment]
Yes, the docs are wrong.

**Comment by nicolasstucki** [comment]
You can also not use add the result type to make it shorter
```scala
def toExpr(b: Boolean) = ...
```
