### ISSUE TITLE
Inconsistent visibility behavior between normal methods and extension methods

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#7860]
## minimized code

```Scala
object Main extends App {
  
  given AnyRef {
    def foo(x: Any) = println(x)
    def (x: Any)bar = println(x)
  }
  
  foo(42)  // Compiler time error: Not found: foo
  42.bar  // Compiles
}
```

## expectation

Both `foo(42)` and `42.bar` compile, or neither compiles.

**Comment by Atry** [comment]
I think it would make sense if members in named instances / parameters require manual import, but members in anonymous instances / parameters are imported automatically. After all, its hard to manually import them without a instance name.

**Comment by odersky** [comment]
extension methods are visible if their enclosing object is in the implicit scope. The spec is quite clear about this.
