### ISSUE TITLE
Compiler error when using wildcard opaque type

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#7864]
## minimized code

```Scala
opaque type F[A] = Int
type G = F[_] // Error: unreducible application of higher-kinded type main$package.F to wildcard arguments
```

## expectation
It should compile.

**Comment by odersky** [comment]
Do still think it should compile if `F` was an abstract type?
```
type F[_]
type G = F[_]
```

**Comment by odersky** [comment]
To answer my own question: It should not compile. Allowing it to compile is equivalent to re-introducing existential types, which are dropped in Dotty. Since opaque types are treated like abstract types at the interface I believe that the example should not compile either.

**Comment by Jasper-M** [comment]
Isn't the error wrong, at the very least? I don't see any higher-kinded type.
