### ISSUE TITLE
Fails to infer correct type for parameter with type Array[String | Null] | Null

### ISSUE THREAD

**Issue by Katrix** [lampepfl/dotty#7870]
When creating array as a parameter to a method where both the array element, and the array itself can be null, dotc fails to infer the correct type for the array.

## minimized code

```Scala
def takesNullArray1(arr: Array[String | Null] | Null) = ???
def foo = takesNullArray1(Array("Foo", "Bar"))
```

Error
```
Found:    Array[String]
Required: Array[String | Null] | Null
```

This works
```scala
def foo2 = takesNullArray1(Array[String | Null]("Foo", "Bar"))
```

Both of these also work
```scala
def takesNullArray2(arr: Array[String | Null]) = ???
def bar = takesNullArray2(Array("Foo", "Bar"))

def takesNullArray3(arr: Array[String] | Null) = ???
def baz = takesNullArray3(Array("Foo", "Bar"))
```

**Comment by odersky** [comment]
I assume this is under -Yexplicit-nulls? In that case this is as expected. Arrays are non-variant, so an 
`Array[String | Null]` is incompatible (in both directions) with an `Array[String]`.

**Comment by Katrix** [comment]
Yes it's under explicit nulls. I don't understand why the compiler can't infer the correct type for the array here though. One place I've seen this so far is with java annotations taking arrays.

**Comment by olhotak** [comment]
The cause of this is that `adapt` ignores the prototype when it is a union type.

`Array("Foo") : ( Array[AnyRef] )`
compiles. The type is inferred to `Array[AnyRef]`.

`Array("Foo") : ( Array[AnyRef] | Int )`
fails with
```
  |  Found:    Array[String]
  |  Required: Array[AnyRef] | Int
```

I understand that it would be too inefficient to do a backtracking search whenever the prototype is a union type, but could we make a special case for when it is a union with `Null`?

I would like to try to implement this, but I can't figure out where within `adapt1` it would be best to add it. Any suggestions?
