### ISSUE TITLE
Method calls on union types do not honor overridden return types

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#7880]
## minimized code

```Scala
class OptimizedDrop[A](
  underlying: collection.SeqOps[A, [x] =>> Any, _],
  n: Int
) extends collection.SeqView.Drop[A](
  underlying,
  n
) {
  override def drop(n: Int): OptimizedDrop[A] = new OptimizedDrop(underlying, this.n + n)
}

type SeqOrDrop[A] = OptimizedDrop[A] | Seq[A]

// Found:    scala.collection.View[A @uncheckedVariance] | Seq[A @uncheckedVariance]
// Required: SeqOrDrop[A]
def drop1[A](a: SeqOrDrop[A]): SeqOrDrop[A] = a.drop(1)
```

## expectation
It should compile

**Comment by odersky** [comment]
No that won't work. The method `drop` has to exist in the least common class type that contains `drop` and `optimizedDrop`. See the section "Join of a union type" in the docs.

**Comment by Atry** [comment]
I understand the backend will call the method on least common type, but why does it affect the typer? IIRC, the typer works according to DOT Calculus. It seems that the union type resolution in DOT Calculus is not limited to method defined in the common super class.
