### ISSUE TITLE
The code in the "Unsoundness" subsection of the "Explicit Nulls" page doesn't compile

### ISSUE THREAD

**Issue by ShapelessCat** [lampepfl/dotty#7881]
The provided code doesn't compile when there is a `-Yexplicit-nulls` flag.
With _explicit nulls_, we can't compile code like `stringValue == null`, which is mentioned in the subsection "Equality" that just after the "Unsoundness" subsection.

I think this piece of code can be  corrected and simplified as
```
class C {
  val f: String = foo(f)
  def foo(f2: String): String = f2

val c = new C()
// c.f is null

```

**Comment by nicolasstucki** [comment]
This should be caught by #7789
