### ISSUE TITLE
Problems in erasure

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#789]
./out/dotty/tools/dotc/core/Phases.class

```java
    default public Object atPhase(Phase phase, Function1 op) {
        return this.atPhase((Phase)BoxesRunTime.boxToInteger((int)phase.id()), op);
    }
```

is obviously going to fail with java.lang.Integer cannot be cast to dotty.tools.dotc.core.Phases$Phase.

Unfortunatelly, running dotty with `isDerivedValueClass` set to false does not work, so this blocks bootstrap.

**Comment by odersky** [comment]
Here's a minimized test case:

    trait Periods { self: Context =>

      def atPhase(id: Int): Unit = println(s"atPhase: $id")

    }

    trait Phases { self: Context =>
      case class Phase(id: Int)
      def atPhase(phase: Phase): Unit = atPhase(phase.id)
    }

    trait Context extends Phases with Periods

    object Test extends Context {

      def main(args: Array[String]) = atPhase(new Phase(2))

    }

**Comment by odersky** [comment]
As the test case shows it has actually nothing to do with value classes. I found the real problem. Fix coming shortly.
