### ISSUE TITLE
Unary identifier has undue expectation of subsequent expression

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#7910]
## minimized code

```Scala
  def k = {
    object + extends Function1[Int, Int] { def apply(i: Int): Int = i + 1 }
    val g: Int => Int = +
    g(1)
  }

13 |    val g: Int => Int = +
   |                         ^
   |                         expression expected but end of statement found
```

@hrhino said his tests for https://github.com/scala/scala/pull/8617 worked, so I tried [mine](https://github.com/scala/scala/pull/8627), too.

```Scala
  final val x = 42
  def f = {
    import x._
    val g: Int => Int = +
    g(1)
  }
```

## expectation

[Unary ids are ordinary identifiers](https://github.com/scala/scala/pull/4301).

**Comment by odersky** [comment]
I don't think I will fix this, after all. If someone wants to take this over, please reopen.
