### ISSUE TITLE
Top-level package objects are incorrectly inserted in the empty package

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#7932]
The empty package should only be used for definitions which have no parent package, so this is clearly incorrect, but I don't know what kind of problems this may cause:

```scala
package object foo
```
dotty:
```scala
result of try/tl.scala after typer:
package <empty> {
  package foo {
    final lazy module val package: foo.package$ = new foo.package$()
    final module class package$() extends Object(), _root_.scala.Serializable {
      this: foo.package.type =>
    }
  }
}
```
scalac:
```scala
[[syntax trees at end of                     typer]] // tl.scala
package foo {
  object `package` extends scala.AnyRef {
    def <init>(): foo.package.type = {
      `package`.super.<init>();
      ()
    };
    <empty>
  }
}
```

This is important to get right since the standard library defines the top-level `package object scala` /cc @odersky

**Comment by som-snytt** [comment]
FWIW, dotty correctly handles separate compilation of toplevel empty package object
```
object `package`
```
but scala 2 requires an anomalous
```
import `package`._
```
https://github.com/scala/bug/issues/10927

**Comment by odersky** [comment]
This would be messy to change. If a source file has no package clause, it is wrapped in the empty package. If there are then local package clauses that's where they go. I'd like to see whether this causes some actual problems before complicating this scheme.
