### ISSUE TITLE
@alpha has no effect over double definition error

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#7942]
## minimized code

```Scala
import scala.annotation.alpha
@alpha("fooString") def foo(ps: String*) : Unit = ???
@alpha("fooInt") def foo(ps: Int*) : Unit = ???
@alpha("fooAny") def foo(ps: Any*) : Unit = ???
```

<details>
<summary>Compilation output</summary>

```scala
Double definition:
def foo(ps: String*): Unit in package object main$package at line 4 and
def foo(ps: Int*): Unit in package object main$package at line 5
have the same type after erasure.
@alpha("fooAny") def foo(ps: Any*) : Unit = ???

Double definition:
def foo(ps: Int*): Unit in package object main$package at line 5 and
def foo(ps: Any*): Unit in package object main$package at line 6
have the same type after erasure.
```
</details>

see scastie: https://scastie.scala-lang.org/owQEIEShQayiRjUJ6Esk2w

## expectation
Currently `DummyImplicit` is used as a workaround to create unique signatures after erasure. 
@odersky [mentioned](https://contributors.scala-lang.org/t/principles-for-implicits-in-scala-3/3072/126?u=soronpo) that `@alpha` annotation could be used to avoid double definition error, however it does not seem to affect the compiler when it checks for double definitions.

**Comment by odersky** [comment]
I tried to just remove the error condition but then we run into more trouble:
```
-- Error: i7942.scala:2:0 ------------------------------------------------------
2 |@alpha("fooString") def foo(ps: String*) : Unit = ???
  |^
  |cannot merge
  |  method foo of type (ps: Seq[Any]): Unit  and
  |  method foo of type (ps: Seq[Int]): Unit
  |they are both defined in package <empty> but have matching signatures
  |  (ps: Seq[Any]): Unit and
  |  (ps: Seq[Int]): Unit
  |as members of package object i7942$package
  |       
3 |@alpha("fooInt") def foo(ps: Int*) : Unit = ???
4 |@alpha("fooAny") def foo(ps: Any*) : Unit = ???
```
To fix this we need to change our way how we treat signatures. Since signatures are used for many different things this will require a lot of thought.
