### ISSUE TITLE
Cannot pass enum values as inline parameters

### ISSUE THREAD

**Issue by flomebul** [lampepfl/dotty#7964]
## minimized code

```Scala
enum Nums { case One }

def fok(that: Nums) = ???
val ok = fok(Nums.One)

inline def fko(inline that: Nums) = ???
val ko = fko(Nums.One)
```

<details>
<summary>The compiler rejects the use of `One` as an inline parameter.</summary>

```scala
-- Error: ABug.scala:7:18 ------------------------------------------------------
7 |val ko = fko(Nums.One)
  |             ^^^^^^^^
  |             argument to inline parameter must be a known value
1 error found
```
</details>

**Comment by TheElectronWill** [comment]
In fact the compiler finds the enum value but the typer rejects it, I've updated the issue to reflect this :-)

The documentation reads:
> Right-hand sides of inline values and of arguments for inline parameters must be constant expressions in the sense defined by the SLS § 6.24.

Which doesn't include Dotty enums, for they didn't exist in Scala 2. However it mentions `enumeration from the underlying platform`, and I wonder if enums could/should be compiled to their platform-specific representation when possible.

**Comment by odersky** [comment]
I think it would be good if we could support enum values. @nicolasstucki can you tell whether that would lead to problems for inlining?

**Comment by nicolasstucki** [comment]
At first glance it seems it should work. We already support equivalent instances of case classes and objects. I will try it out.
