### ISSUE TITLE
Add information about debugging to "IDE support for Dotty" webpage

### ISSUE THREAD

**Issue by unoexperto** [lampepfl/dotty#7966]
I've asked extensively in dotty's gitter channel, stackoverflow and other places but oddly couldn't find clear answer.

What are options today to debug Scala 3 apps in IDE ? I tried VSCode per documentation but it asks to set environment in order to debug/run the application.

**Comment by odersky** [comment]
We will migrate in the coming months to a Metals based language server. I believe debugging support is in the works for metals. So you could inquire on the Metals channel about progress.
