### ISSUE TITLE
Chaining try-catch-match is not possible

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#7996]
## minimized code

```Scala
@main def Test =
  try "foo"
  catch
    case _: Throwable => ???
  match
    case "foo" => println("I'm foo")
```

<details>
<summary>Compilation output</summary>

```scala
-- [E081] Type Error: /Users/kmetiuk/Projects/scala3/pg/sandbox/iss6.scala:4:4 -
4 |    case _: Throwable => ???
  |    ^
  |    Missing parameter type
  |
  |    I could not infer the type of the parameter x$1 of expanded function:
  |    x$1 =>
  |      x$1 match
  |        {
  |          case _:Throwable =>
  |            ???
  |        }.
```
</details>

<details><summary>-Xprint:typer output</summary>

```scala
package <empty> {
  final lazy module val iss6$package: iss6$package$ = new iss6$package$()
  final module class iss6$package$() extends Object(), _root_.scala.Serializable
     {
   this: iss6$package.type =>
    @main() def Test: <error expression does not take parameters> =
      try "foo" catch
        {
          case ex$ @ _ =>
            (
              {
                def $anonfun(
                  x$1:

                      <error Missing parameter type

I could not infer the type of the parameter x$1 of expanded function:
x$1 =>
  x$1 match
    {
      case _:Throwable =>
        ???
    }.>

                ): Nothing =
                  x$1 match
                    {
                      case _:Throwable =>
                        ???
                    }
                closure($anonfun)
              }
             match
              {
                case "foo" =>
                  println("I\'m foo")
              }
            )(ex$)
        }
  }
}
```
</details>

## expectation
`((try x catch y) match z)` rather than `(try x catch (y match z))`. I don't see why `match` should be right-associative in that context.

The following is possible and `match` is left-associative in this context:

```scala
@main def Test =
  "foo"
  match
    case "foo" => "bar"
  match
    case "bar" => println("I'm bar")
```

Hence I would expect `try-catch-match` to also be possible.

**Comment by odersky** [comment]
This is intentional. `match` binds stronger than `try`. `try` is its own toplevel statement whereas `match` is treated by the Parser analogous to an infix method. It's not clear whether this should or can be changed, but in any case this would need a feature request with a detailed spec, including a changed grammar.

**Comment by anatoliykmetyuk** [comment]
`try-catch` is an atomic construct in the sense that you cannot tear `catch` out of it and treat it as an independent statement. I don't think there is a valid use case for a user having the intention to do that with an infix method under any circumstances.

Also if you look at a simple example:

```scala
@main def Test =
  try 1
  catch
    case _: Throwable => 2
  match
    case 3 => 4
```

And its representation after typer:

```scala
      try 1 catch
        {
          case ex$ @ _ =>
            (
              {
                def $anonfun(x$1: <error>): Int =
                  x$1 match
                    {
                      case _:Throwable =>
                        2
                    }
                closure($anonfun)
              }
             match
              {
                case 3 =>
                  4
              }
            )(ex$)
        }
```

What the compiler does doesn't make much sense to me. This is because it tries to create another `catch` statement from `(catch(x).match(y))`. It seems it thinks that the way to match on a `catch` is to turn that `catch` in a `match`, wrap it into a closure, and match on that closure:

```scala
              {
                def $anonfun(x$1: <error>): Int =
                  x$1 match
                    {
                      case _:Throwable =>
                        2
                    }
                closure($anonfun)
              }
             match
              {
                case 3 =>
                  4
              }
```

Then it wraps the whole thing in a `catch`, treats the result of  `match` as a closure and passes the intercepted exception from that synthetic `catch` to it.

This logic doesn't make much sense to me and seems like a pathological corner case rather than an intended behavior.

**Comment by som-snytt** [comment]
It would be nice to `try e1 catch e2 match e3`.

The analysis in the previous comment isn't quite right -- a case block is a "pattern matching anonymous function", so that is natural (if odd) as a scrutinee for the match.

I would expect the example to "embrace" as "orig", which both 2 and 3 accept. I thought maybe 3 is leaking an unbound `_`, but maybe it's just taking the case block as `x match { case p(x) }`. It errors twice on Test. (2 errors once.)

I had a scala 2 PR to expect a `PartialFunction[Throwable, Any]` for the catch expr and invoke `applyOrElse` for some local optimum of efficiency and type inference, but it was tricky and didn't take. One test was the error for `try ??? catch 22`. 

```
object Main {
  def Test =
    try 1
    catch _ => {
      case _: Throwable => 2
    match {
      case 3 => 4
    }}
  def orig =
    try 1
    catch {
      case _: Throwable => 2
    match {
      case 3 => 4
    }}
}
```
