### ISSUE TITLE
Bridge method clash with value class

### ISSUE THREAD

**Issue by travisbrown** [lampepfl/dotty#8001]
## minimized code

```Scala
trait TC[A] {
  def apply(a: A): Unit
}

class Foo[A](val value: A) extends AnyVal
object Foo {
  val tc = new TC[Foo[String]] {
    def apply(a: Foo[String]): Unit = ()
  }
}
```

<details>
<summary>Compilation output</summary>

```scala
-- Error: TC.scala:8:8 ---------------------------------------------------------
8 |    def apply(a: Foo[String]): Unit = ()
  |        ^
  |bridge generated for member method apply(a: Foo[String]): Unit in anonymous class Object with TC {...}
  |which overrides method apply(a: A): Unit in trait TC
  |clashes with definition of the member itself; both have erased type (a: Object): Unit."
1 error found

```
</details>

## expectation

Another minimization from the Cats tests. Scala 2 is fine with this.

**Comment by odersky** [comment]
There's a long history about this bug which is really a shortcoming of the value class encoding. Given that value classes are not pursued further, and the bug would likely cost a person several weeks to fix, I am not sure we will ever fix it. I do hope there is a workaround.

**Comment by travisbrown** [comment]
@odersky We can easily work around this, thanks.

**Comment by odersky** [comment]
@travisbrown Good to know, thanks!

**Comment by bishabosha** [comment]
minimise to this
```scala
case class Box(a: Any) extends AnyVal
```

**Comment by Jasper-M** [comment]
@bishabosha The code that Travis posted compiles fine in Scala 2, while yours will error in Scala 2 as well.

I think the bug here is that dotc thinks that `Foo[String]` or `Foo[Int]` erases to `Object` instead of `String` or `Int` respectively.

**Comment by smarter** [comment]
> I think the bug (or just difference from scala 2, don't know...) here is that dotc thinks that Foo[String] or Foo[Int] erase to Object instead of String or Int respectively.

Yes, exactly. I'm working on a fix.

**Comment by larsrh** [comment]
This is marked as fixed in M3, but there's another situation where this happens: https://scastie.scala-lang.org/g5dE8K7wT5aCPYTYFETtLA

**Comment by smarter** [comment]
Hmm, interesting, if I replace the anonymous instantiation by:
```scala
object Foo extends Monad[Dual] {
  def flatMap[A,B](fa: Dual[A])(f: A => Dual[B]): Dual[B] = f(fa.getDual)
}
```
Then Scala 2 emits the same error as Dotty. It looks like Scala 2 has some extra magic to deal with the special-case of value class bridge clashes in anonymous classes where it can get away with renaming one of the method to avoid the clash: https://github.com/scala/scala/pull/3428, feel free to open an issue about this, but I don't know if we have the bandwidth to port this in time for 3.0.

**Comment by larsrh** [comment]
I have to admit I don't understand at all what's going on, and what a possible workaround could be.

Having said that, I found this problem while minimizing another problem found by @fmsbeekmans while porting [https://github.com/typelevel/semigroups](semigroups) to Dotty. A similar instantiation produced the following message:

```
[error]    |bad parameter reference io.chrisdavenport.semigroups.Dual#A at elimOpaque
[error]    |the parameter is type A in class Dual but the prefix io.chrisdavenport.semigroups.Dual
[error]    |does not define any corresponding arguments.
```

... and I haven't yet minimized it in a satisfactory way, nor can I tell whether or not this is an internal error. The error goes away when removing `extends AnyVal`.

**Comment by smarter** [comment]
That `bad parameter reference` is definitely a bug, but I don't think it's related to the bridge issue. I've gone ahead and opened https://github.com/lampepfl/dotty/issues/11264 to keep track of the bridge issue.
