### ISSUE TITLE
Dotty fails to to infer type params for Java Stream API

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#801]
``` scala

object T{
  import java.util.ArrayList, java.util.stream.{Stream => JStream}
  new java.util.ArrayList[String]().stream.map(_.toInt).map(_.toString): JStream[String]
}
```

```
Streams.scala:3: error: toInt is not a member of <unknown instance of type java.util.function.Function[_ >: String, _ = Nothing]>
  .
java$util$function$Function$$T(_$1)
  new java.util.ArrayList[String]().stream.map(_.toInt).map(_.toString): JStream[String]
                                                 ^
Streams.scala:3: error: type mismatch:
 found   : <unknown instance of type java.util.function.Function[_ >: String, _ = Nothing]>
  .
java$util$function$Function$$T =>
  <unknown instance of type
    java.util.function.Function[_ >: String, _ = Nothing]
  >.java$util$function$Function$$R
 required: java.util.function.Function[_ >: String, _ <: Nothing']
  new java.util.ArrayList[String]().stream.map(_.toInt).map(_.toString): JStream[String]
                                               ^
Streams.scala:3: error: type mismatch:
 found   : String
 required: <unknown instance of type java.util.function.Function[_, _ <: String]>.
  java$util$function$Function$$R
  new java.util.ArrayList[String]().stream.map(_.toInt).map(_.toString): JStream[String]
                                                            ^
three errors found
```

see also https://groups.google.com/forum/#!msg/scala-language/Xy29pcRE04c/rwCvztHjsP8J for same issue for scalac

**Comment by adriaanm** [comment]
Mostly related to mismatch between use site and definition site variance. How about inferring variance for Java interfaces? http://www.lirmm.fr/~ducour/Doc-objets/ECOOP2012/ECOOP/ecoop/509.pdf

**Comment by odersky** [comment]
@adriaanm What's the status of this issue for scalac?

**Comment by adriaanm** [comment]
I haven't made any progress on this. My original idea was to infer variance annotations for Java interfaces to feed that to type inference, so it can replace bounded wildcards by their upper/lower bounds depending on the variance position they occur in.

**Comment by odersky** [comment]
@adriaanm Thanks or the update! I was hoping I could lift some code from you guys there.

**Comment by adriaanm** [comment]
me too -- alas :)

**Comment by adriaanm** [comment]
(I did do some work this week on our SAM expansion: https://github.com/scala/scala/pull/4945 -- ideally, I'd like to generalize Function ASTs to have any function/sam type, and emit the corresponding invokedynamic+LambdaMetaFactory calls in the back-end. Right now, we expand SAM types like PartialFunction ones)

**Comment by sjrd** [comment]
> I'd like to generalize Function ASTs to have any function/sam type, and emit the corresponding invokedynamic+LambdaMetaFactory calls in the back-end.

That would be awesome! We could get rid of all [the awful hacks in Scala.js to recover anonymous functions from classes](https://github.com/scala-js/scala-js/blob/84b6ccb40a95979e1eb2a383970b536528f8beab/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L4031-L4311) (at least, once we drop support for 2.10 and 2.11 ...)
