### ISSUE TITLE
Default Singleton-type parameters are not set as Singleton type

### ISSUE THREAD

**Issue by MaximeKjaer** [lampepfl/dotty#8010]
## Minimized code

```Scala
def oneByDefault(x: Int & Singleton = 1): Unit = ???
oneByDefault(1) // type-checks
oneByDefault()  // does not type-check
```

<details>
<summary>Compilation output</summary>

```scala
[error] -- [E007] Type Mismatch Error: /home/maxime/code/default-param-inference/src/main/scala/DefaultParamInference.scala:5:4 
[error] 5 |    oneByDefault()  // does not type-check
[error]   |    ^^^^^^^^^^^^
[error]   |    Found:    Int
[error]   |    Required: Int & Singleton
```
</details>

## Expectation
I would expect this to type-check

**Comment by MaximeKjaer** [comment]
Compiling with `-Xprint:typer` gives a little more information on what is happening:

```scala
def oneByDefault(x: Int & Singleton): Unit = ???
def oneByDefault$default$1: Int = 1
Test.oneByDefault(1)
Test.oneByDefault(oneByDefault$default$1)
```

The default parameter `x` has been compiled to `oneByDefault$default$1` of type `Int`. I would expect it to be compiled to type `Int & Singleton`:

```scala
def oneByDefault(x: Int & Singleton): Unit = ???
def oneByDefault$default$1: Int & Singleton = 1
Test.oneByDefault(1)
Test.oneByDefault(oneByDefault$default$1)
```

**Comment by odersky** [comment]
We are considering a complete redesign of default parameters that would also avoid that. Basically, default arguments would be inline expressions, and they could not be overridden in subclasses. That would solve a number of issues, including this one. I am closing for now since I don't think we will tackle this issue in isolation.
