### ISSUE TITLE
Nightly builds not appearing on Maven Central

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#8023]
No idea what's going on since the upload logs look fine, so I opened an issue upstream: https://issues.sonatype.org/browse/OSSRH-54549

**Comment by anatoliykmetyuk** [comment]
May or may not be related: https://support.sonatype.com/hc/en-us/articles/360041287334
This broke a nightly of a project of ours two days ago: #8014.

**Comment by anatoliykmetyuk** [comment]
They are having troubles on their end apparently, according to the issue on their tracker
