### ISSUE TITLE
Type class instance for type alias in package object isn't found

### ISSUE THREAD

**Issue by travisbrown** [lampepfl/dotty#8048]
## minimized code

```Scala
package tc {
  trait Functor[F[_]]
}

package object tc {
  trait Foo[A]
  type Id[A] = A

  implicit val fooFunctor: Functor[Foo] = new Functor[Foo] {}
  implicit val idFunctor: Functor[Id] = new Functor[Id] {}
}

package test {
  object Test {
    val functor1 = implicitly[tc.Functor[tc.Foo]]
    val functor2 = implicitly[tc.Functor[tc.Id]]
  }
}
```

<details>
<summary>Compilation output</summary>

```scala
-- Error: Id.scala:16:48 -------------------------------------------------------
16 |    val functor2 = implicitly[tc.Functor[tc.Id]]
   |                                                ^
   |no implicit argument of type tc.Functor[tc.Id] was found for parameter ev of method implicitly in object DottyPredef
   |
   |The following import might fix the problem:
   |
   |  import tc.idFunctor
   |         
1 error found
```
</details>

## expectation

This compiles fine on Scala 2, and we rely on that extensively in Cats. Importing `tc._` or `tc.idFunctor` is a workaround, but not really very pleasant for our case.

If you move the definitions in the package object directly into `package tc`, neither val in `Test` compiles.

**Comment by odersky** [comment]
That one is also intentional. See point 3 of https://dotty.epfl.ch/docs/reference/changed-features/implicit-resolution.html. Package prefixes are no longer part of the implicit scope of a type.  I believe with the import suggestions the breakage should be manageable.
