### ISSUE TITLE
Suggested import clauses should not include paths that are already part of the implicit scope

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#8051]
## minimized code

```scala
class Foo

List(new Foo).sorted
```

https://scastie.scala-lang.org/K9udu0oDRJCTdURWhocs4w

~~~ text
One of the following imports might make progress towards fixing the problem:

  import math.Ordering.comparatorToOrdering
  import math.Ordering.ordered
~~~

The suggested import clauses wouldn’t change anything because they are already part of the implicit scope (because they refer to definitions that live inside the `Ordering` companion object).

## expectation

Import clauses that are already part of the implicit scope should not appear.

**Comment by odersky** [comment]
But they are not part of the implicit scope here! Or are you saying that `Ordering` is part of the implicit scope of `List`?

I agree with the principle (and there's no code yet to address it), but this test does not demonstrate the failure.

**Comment by julienrf** [comment]
> But they are not part of the implicit scope here! Or are you saying that `Ordering` is part of the implicit scope of `List`?

The `sorted` method takes an implicit parameter of type `Ordering[A]`. So, the members of the companion object `Ordering` are part of the implicit scope here, right?
