### ISSUE TITLE
Local implicit definition is not part of the import suggestions

### ISSUE THREAD

**Issue by julienrf** [lampepfl/dotty#8054]
## minimized code

```scala
import Ordering.Implicits.seqOrdering

class Foo

object OrderingInstances {
  implicit def orderingFoo: Ordering[Foo] = ???
}

@main def main = {
  List(List(new Foo)).sorted
}
```

https://scastie.scala-lang.org/pTrUrhhzTHiHE4yx0yie0Q

The error message does not suggest to `import OrderingInstances.orderingFoo`.

```text
One of the following imports might make progress towards fixing the problem:

  import Ordering.Implicits.seqOrdering
  import Ordering.Iterable
  import math.Ordering.Implicits.seqOrdering
  import math.Ordering.Iterable
  import Ordering.comparatorToOrdering
  import Ordering.ordered
  import math.Ordering.comparatorToOrdering
  import math.Ordering.ordered
```
</details>

## expectation

Local definitions should be included in the suggestions.

**Comment by odersky** [comment]
So far this is not done since it is obvious to the reader what local implicits exist to be imported. But we might reconsider that aspect.

**Comment by julienrf** [comment]
Actually, local definitions *are* included in the suggestions. In the introductory example, the reason why we don’t get a suggestion is because our definitions live in the empty package. If we put our definitions in a non empty package it works as expected: https://scastie.scala-lang.org/nIjwAQaCQVi1dN4ujsdtng

As a consequenc, I’m closing this issue.
