### ISSUE TITLE
Worksheet in VSCode  unable to find closing parenthesis

### ISSUE THREAD

**Issue by datMaffin** [lampepfl/dotty#8093]
## minimized code

```Scala
import scala.collection.mutable.HashMap
val test = HashMap[Int, Int]()
test += (10 -> 10)
```

### description
Error occurs when using the code in a worksheet in visual studio code started with `sbt launchIDE`. The project was created with `sbt new lampepfl/dotty.g8` (https://github.com/lampepfl/dotty.g8/tree/0b346745e20ab4dd934e7f1d13427069d9cf4c56)

<img width="904" alt="Screenshot 2020-01-26 at 19 42 15" src="https://user-images.githubusercontent.com/29998721/73140080-44551780-4075-11ea-8da9-7b9f28cc8b55.png">

<img width="904" alt="Screenshot 2020-01-26 at 19 42 37" src="https://user-images.githubusercontent.com/29998721/73140083-4c14bc00-4075-11ea-8540-7659a0d5c9c0.png">

### error output
```scala
')' expected, but eof found
```
(I do not know where to find the complete compilation printout)

### other
* Compiles when removing parenthesis or when executing the code in a `locally` block:
<img width="989" alt="Screenshot 2020-01-26 at 19 44 51" src="https://user-images.githubusercontent.com/29998721/73140171-1fad6f80-4076-11ea-9546-08234972c02b.png">

* I was **unable** to reproduce the bug in the worksheet mode of https://scastie.scala-lang.org/?target=dotty

## expectation
Should compile and execute without any errors.

**Comment by megri** [comment]
This also happens with imports. A line like `import scala.collection.immutable.{:: => Cons}` fails with 
```
1 |import scala.collection.immutable.{:: => Cons
  |                                             ^
  |                                             '}' expected, but eof found
scala.collection.immutable
```

**Comment by bishabosha** [comment]
this example works in Metals worksheets (https://scalameta.org/metals/docs/editors/vscode.html#worksheets) which is recommended instead
