### ISSUE TITLE
REPL runner command line options weakly parsed

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#8095]
## minimized code
I was tripped up by `-cp` not meaning `-classpath`. Also by `-help` not offering any.

```Scala
➜  dotr -classpath /tmp/stuff f
OK
➜  dotr -cp /tmp/stuff f       
Error: Unable to initialize main class f
Caused by: java.lang.NoClassDefFoundError: scala/util/CommandLineParser$ParseError
➜  dotr -help
Starting dotty REPL...
scala>                                                                                                                     
➜  dotr -version
Starting dotty REPL...
Dotty compiler version 0.21.0-RC1 -- Copyright 2002-2019, LAMP/EPFL
scala>                 
```
Or maybe it does mean some kind of classpath, because that looks like it found the entry point but nothing else. This is finding nothing, or not finding anything:
```
➜  dotr -classpath junk nada
Error: Could not find or load main class nada
Caused by: java.lang.ClassNotFoundException: nada
```

<details>
<summary>Compilation output</summary>

```scala
As per transcript.
```
</details>

## expectation

Common options explained by `dotr -help`. Most people won't use it at the shell or sbt prompt anyway.

OK, it just completed in sbt, where it looks like options are passed on to java. So `-cp` must be fielded by java, explaining the result above.

**Comment by retronym** [comment]
I just ran into this. The runner passes options other than `{-repl, -run, -classpath, -with-compiler, -d, -J*, directly to the JVM as `residual_args`. The JVM accepts `-cp` as alias for `-cp` and this ovewrwrites the setting of `"-classpath \"$cp_arg\""` which includes the standard library.

**Comment by retronym** [comment]
Taking the step of accepting the `-cp` alias in https://github.com/lampepfl/dotty/pull/11366
