### ISSUE TITLE
Worksheet extension method result not shown

### ISSUE THREAD

**Issue by msinton** [lampepfl/dotty#8104]
## minimized code

```Scala
case class Circle(x: Double, y: Double, radius: Double)
def (c: Circle).circumference: Double = c.radius * math.Pi * 2

val circle = Circle(0, 0, 1)
circle.circumference
```

The worksheet result is just that of circle, so the last 2 output lines are:
```
val circle: Circle = Circle(0.0,0.0,1.0)
val res0: Circle = Circle(0.0,0.0,1.0)
```

<details>
Executed in a VS worksheet against 0.22.0-bin-20200125-c8371e4-NIGHTLY

I can get the true result by doing:

```scala
val r = circle.circumference
```
</details>

## expectation
I expect to see in the output:
```
val res0: Double = 6.283185307179586
```

**Comment by bishabosha** [comment]
this example works in Metals worksheets (https://scalameta.org/metals/docs/editors/vscode.html#worksheets) which is recommended instead
