### ISSUE TITLE
Tasty API support for generating local symbols

### ISSUE THREAD

**Issue by fhackett** [lampepfl/dotty#8114]
This issue is a generalisation of recent PR #8090, aiming to cover gaps in symbol generation that are not immediately relevant to that change. That change enables the generation of method symbols, including method parameters as consequence.

Remaining symbols the Tasty API should be able to generate are:
- symbols for local `val`s (including `var`s, etc)
- symbols for pattern binds
- symbols for local classes / objects / etc

Several of these kinds of symbols can be hacked into existence by stealing them from quotes, but this means we can't directly control things like names, flags (and location information?). Especially since we now have `Symbol.newMethod`, it would be strange not to at least support `val`s and pattern binds. Local classes may be more complicated, so I will be experimenting with those last.

I'll be writing up any ideas / progress here for comment.

**Comment by nicolasstucki** [comment]
Adding `Symbol.newVal` in #8291

**Comment by bishabosha** [comment]
How many other parts are missing?

**Comment by fhackett** [comment]
@bishabosha since #8291 covers local vals and #8090 covers local methods, the other main item is pattern binds.

That is the introduction of the name `x` in the following code, and other things like it:
```scala
??? match {
  case x => ???
}
```

After that we've covered most of the local definitions that make sense.

The remaining more "out there" items are local classes/objects, which would then need all the different kinds of class-level symbol for the fields. At that point you'd be able to synthesize essentially any kind of sub-program you like from a Tasty macro.
