### ISSUE TITLE
Matching on a type involving an F-bound throws provablyEmpty for a loop

### ISSUE THREAD

**Issue by howtonotwin** [lampepfl/dotty#8169]
## Code

```scala
trait Bound[T]
def oops[T <: Bound[T]]: T match { case Unit => Unit case _ => Unit } = ???
```

## Compilation output

```
2 |def oops[T <: Bound[T]]: T match { case Unit => Unit case _ => Unit } = ???
  |                           ^
  |Recursion limit exceeded.
  |Maybe there is an illegal cyclic reference?
  |If that's not the case, you could also try to increase the stacksize using the -Xss JVM option.
  |A recurring operation is (inner to outer):
  |
  |  reduce type  T match ...
```

NB: This error isn't the most helpful. The actual recursion is in `provablyEmpty`. `matchCases` starts checking whether `T` is empty, and then that checks whether `Bound[T]` is empty, which checks whether `T` is empty, etc.

## Expectation

I would expect this to go through. There's a note about why the `provablyEmpty` check is needed that casts some doubt on that, however. If it *has* to not work, then a nicer error would be nice. Or, maybe some kind of `@nonempty` annotation can be put on the parameter to defer the check.

As an aside, this came up while working on natural numbers:

```scala
sealed trait Nat[N <: Nat[N]] // F-bounding fuses type-level nats and their singletons into one
case object Z extends Nat[Z.type]
case class S[N <: Nat[N]](pred: N) extends Nat[S[N]]

def injS[N <: Nat[N], M <: Nat[M]](prf: S[N] =:= S[M]): N =:= M
= prf.liftCo[[N] =>> N match {
      case S[n] => n
    }]
```

**Comment by odersky** [comment]
Not sure there's anything that can be done here. I leave it to @OlivierBlanvillain to decide to close the ticket if no improvement is feasible.

**Comment by OlivierBlanvillain** [comment]
I guess it would be possible to detect the loop and return false in `provablyEmpty`, but if the only use case is to support F-bound in match types, then that would definly be at the very bottom of the priority list...

**Comment by odersky** [comment]
Revisit when we have a volunteer to tackle this and a design how to do it.
