### ISSUE TITLE
Opaque type constructors can't discriminate between other opaque types due to erasure

### ISSUE THREAD

**Issue by ryanberckmans** [lampepfl/dotty#8174]
Perhaps this is not a bug. It would be useful functionality (as described below). Is there some way to achieve the same outcome?

## minimized code

https://scastie.scala-lang.org/vbyjSbmNSWaeHn4KiAo8fw

```Scala
opaque type Cents = Long
object Cents
  def apply(l: Long): Cents = l

opaque type Dollars = Cents
object Dollars
  private val CentsPerDollar = 100
  def apply(l: Long): Dollars = Cents(l*CentsPerDollar)
  // def apply(c: Cents): Dollars = c // Error: Double definition ... same type after erasure

object Main extends App
  val fiveDollars: Dollars = Dollars(5) // --> this value is $5 
  // val fiveCentsAsDollars: Dollars = Dollars(Cents(5)) // --> this value is $0.05
```

## Compilation output

When uncommenting `def apply(c: Cents): Dollars`:

```scala
Double definition:
def apply(l: Long): main$package.Dollars in object Dollars at line 8 and
def apply(c: main$package.Cents): main$package.Dollars in object Dollars at line 9
have the same type after erasure.
```
## expectation

The strategy here for `opaque type Dollars = Cents` to implement Dollars as a "view" into cents to avoid loss of precision. While it may seem a bit silly with dollars and cents, this approach is ideal for an Ethereum financial library, because the ETH currency is an integral type, where `ETH = 10^18 * WEI` and WEI is an indivisible currency unit. See https://gwei.io/

In this example we want
* `Dollars(5)` represents $5
* `Dollars(Cents(5))` represents $0.05
* but this is currently impossible because the constructor `Dollars.apply(v: Long)` is the same for both `Long` and `Cents` after erasure.

Is there some way to achieve a similar outcome without loss of opaque type ergonomics or introducing annoyance for the user?

**Comment by odersky** [comment]
This is indeed not a bug. The current behavior is mandated by the way opaque types are specified. You could propose an enhancement, but without a new and convincing insight how to implement this this would not be likely to be picked up.

**Comment by ryanberckmans** [comment]
Thanks, Martin!
