### ISSUE TITLE
Defining an implicit class should emit a warning unless the import scala.language.implicitConversions

### ISSUE THREAD

**Issue by Alexey-NM** [lampepfl/dotty#8197]
It is confusing that `implicit class` can be imported in both way:
```
import ConvertibleOps.given
```
or
```
import ConvertibleOps._
```
(https://contributors.scala-lang.org/t/updated-proposal-revisiting-implicits/3821/357)
If I understand correctly it is to simplify migration. 
But if it is so, why is there  no warning similar to implicit conversion. 
http://dotty.epfl.ch/docs/reference/changed-features/implicit-conversions.html
_Defining an implicit conversion will emit a warning unless the import scala.language.implicitConversions_ 

I have tested it with dottyVersion "0.21.0-RC1"

**Comment by odersky** [comment]
The implicit conversion warning is from Scala 2. Implicit classes were explicitly excluded from that warning since they were the only way to do extension methods. In the interest of warning-free cross-compilation between Scala 2 and 3, we'll keep it that way.
