### ISSUE TITLE
Bad indentation parsing at code misalignment

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#8256]
## minimized code

Important! Keep the indentation as set in this example.
```Scala
val a = 1

  trait Test[A]
  object Test {
    implicit def ev[A] : Test[A] = new Test[A]{}
  }

  val fetch = implicitly[Test[1]]

@main def main() : Unit = {}
```
See scastie: https://scastie.scala-lang.org/Ixn7YUAZSjSCPgKbNQR5Wg

## Compilation output

```scala
no implicit argument of type Test[(1 : Int)] was found for parameter ev of method implicitly in object DottyPredef

The following import might fix the problem:

  import Test.this.Test.ev
```

## expectation
No error.

**Comment by smarter** [comment]
`-Xprint:parser` says:
```scala
package <empty> {
  import collection.immutable._
  trait Test[A] {
    <empty>
  }
  module object Test {
    implicit def ev[A]: Test[A] =
      new Test[A] {
        <empty>
      }
  }
  val fetch = implicitly[Test[1.type]]
  @main() def main(): Unit =
    {
      <empty>
    }
}
```
Notice the object Test appears inside the trait Test, that's unexpected to say the least /cc @odersky

**Comment by odersky** [comment]
This is a nice example to illustrate why we should not just observe indentation without a specific leading token. This will be fixed once we allow only the currently specced indentation syntax, and drop supporting the old experiments.
