### ISSUE TITLE
Literal-type operation signature should produce a `Singleton` upper-bounded type

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#8257]
## minimized code

```Scala
import scala.compiletime.ops.int._

class Foo[LW <: Int with Singleton] {
  def + [RW <: Int with Singleton](that : Foo[RW]) : Foo[LW + RW] = new Foo[LW + RW]
}
```

## Compilation output

```scala
Type argument LW + RW does not conform to upper bound Int & Singleton
```

## expectation
A type operation should produce a `Singleton` type. This is useful for covariant type operations, which require the upper-bound to avoid eager widening by scalac.

cc @MaximeKjaer

**Comment by soronpo** [comment]
From experimentation, I think this is problematic. My goal was to use the `Singleton` upper-bound to protect from eager widening when covariance is used. I no longer think this is required.

**Comment by mbovel** [comment]
From https://github.com/lampepfl/dotty/pull/15268/commits/16fa9571c7ad5ef1d318759ce5560b32d3bfaf3f, we consider type-level operation stable if their arguments are stable.
