### ISSUE TITLE
Drone CI license limit exceeded

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#8272]
https://dotty-ci.epfl.ch/lampepfl/dotty

<img width="1075" alt="Screenshot 2020-02-10 at 09 39 22" src="https://user-images.githubusercontent.com/3648029/74133619-41b3ff80-4be9-11ea-9de9-1202bae3034d.png">

**Comment by michelou** [comment]
Following the link [Learn More](https://docs.drone.io/enterprise/errors/license-is-exceeded/) I can read "*[..] this warning message indicates you exceeded your user or repository limits.*". Which limit has been reached ?

**Comment by anatoliykmetyuk** [comment]
That's for commercial license holders. It seems we don't have such a license.

**Comment by nafg** [comment]
You might consider using GitLab CI

**Comment by smarter** [comment]
I would consider github actions first: https://github.com/olafurpg/setup-scala
