### ISSUE TITLE
Companion object single extension methods not available without import 

### ISSUE THREAD

**Issue by soronpo** [lampepfl/dotty#8275]
## minimized code

```Scala
class Foo
object Foo {
  extension on (left : Foo) {
    def + (right : Foo) : Foo = new Foo
  }
  def (left : Foo) ++ (right : Foo) : Foo = new Foo
}

val f = new Foo
val g1 = f + f
val g2 = f ++ f //error here
```

## Compilation output

```scala
value ++ is not a member of Foo
```

## expectation
Behaviors of single extension methods and collective extension methods should be the same.

**Comment by odersky** [comment]
> Behaviors of single extension methods and collective extension methods should be the same.

That's not how it is specified, so it would be a language change, and it does not look like an easy one to me. If you think it's worth pursuing this (knowing it will take significant effort) then please open a feature request.

**Comment by soronpo** [comment]
I'll just comment on the extension methods contributors thread instead since extension methods are not yet approved by the SIP committee.
