### ISSUE TITLE
Given conversion loosing type, when inlined

### ISSUE THREAD

**Issue by edolgy** [lampepfl/dotty#8276]
The code does not compile, but would compile if 'inline' is removed.

Introduced in 0.22, was fine in 0.21

```scala
object NOTHING

inline given [A]: Conversion[NOTHING.type, Option[A]] = _ => None

def apply[A](p: Vector[A], o: Option[A] = NOTHING): Unit = ???

apply[String](Vector.empty)
```

```
[error]  Found: Option[Any],  Required: Option[String]
```

**Comment by odersky** [comment]
It works fine if I give the default argument explicitly:
```
apply[String](Vector.empty)
```
There's a little too much going on here at the same time. To rely on an implicit conversion to make a default argument conform to the indicated type is a bit crazy. The problem might go away by itself if we redesign default arguments. Until then it's better to wait.

**Comment by nicolasstucki** [comment]
Workaround 

```scala
object NOTHING

inline given [A] as Conversion[NOTHING.type, Option[A]] = _ => None

def apply[A](p: Vector[A], o: Option[A] = NOTHING:  Option[A]): Unit = ???

def test = apply[String](Vector.empty)

```
