### ISSUE TITLE
The union type of any pair of singleton types is equivalent to their supertype

### ISSUE THREAD

**Issue by propensive** [lampepfl/dotty#829]
There are a couple of ways of demonstrating this. The following does not produce a type error when it should:
```
def foo: 1 | 2 = 1
def bar: 3 | 4 = foo
```
whereas this does (correctly):
```
def foo: 1 | 2 = 1
def bar: 1 = foo
```

Intersection types do, however, appear to work correctly. This produces the expected type error:
```
trait X {
  def foo: 1 & 2
  def bar: 2 & 3 = foo
}
```

**Comment by propensive** [comment]
Another useful test is to check whether this compiles:

```
implicitly[1 & (2 | 3) =:= (1 & 2) | (1 & 3)]
```

**Comment by smarter** [comment]
It does if you add a few parentheses to avoid precedence issues:
```scala
implicitly[1 & (2 | 3) =:= (1 & 2) | (1 & 3)]
```

**Comment by propensive** [comment]
Great!

Do you have any thoughts on the precedence rules for type operators, in light of `|` and `&` becoming more widely used at the type-level, @odersky?

**Comment by smarter** [comment]
Yes, it's especially confusing for pattern matching:
```scala
x match {
  case x: 1 | 2 => // means case (x: 1) | 2, but is likely to be interpreted as case x: (1 | 2)
  case x @ 1 | 2 => // means case (x @ 1) | 2, but is likely to be interpreted as case x @ (1 | 2)
}
```

**Comment by odersky** [comment]
The idea to take precedence from Java is still valid I think. Tweaking here
else risks becoming bikeshedding.

 - Martin

On Thu, Oct 22, 2015 at 9:45 PM, Guillaume Martres <notifications@github.com
> wrote:

> Yes, it's especially confusing for pattern matching:
>
> x match {
>   case x: 1 | 2 => // means case (x: 1) | 2, but is likely to be interpreted as case x: (1 | 2)
>   case x @ 1 | 2 => // means case (x @ 1) | 2, but is likely to be interpreted as case x @ (1 | 2)
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/829#issuecomment-150335480>.
>



-- 
Martin Odersky
EPFL

**Comment by smarter** [comment]
Fair enough, but note that this means that porting uses of intersection types from scalac to dotty is not trivial because `with` and `&` do not have the same precedence:
```scala
trait A
trait B
object Test {
  (new A with B) match { case x: A with B => x } // OK
  (new A with B) match { case x: A & B => x } // error
  (new A with B) match { case x: (A & B) => x } // OK
}
`

**Comment by odersky** [comment]
Superseded by #1551
