### ISSUE TITLE
given instance parameters cannot appear in the type of a member of the instance

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#8397]
## minimized code

```Scala
given foo(using x: Int) as AnyRef:
  type T = x.type
```

## Compilation output

```scala
non-private type T in class foo refers to private value x
in its type signature  = (foo.this.x : Int)
```

## expectation

This could compile if `x` was desugared to a public val in `foo`.

**Comment by neko-kai** [comment]
@smarter 
The equivalent code using anonymous classes compiles fine without having to make the val public, maybe `given` encoding could be changed to just a `def` without a companion public class?

```scala
implicit def foo(implicit x: Int): { type T = x.type } = new {
  type T = x.type
}
```

**Comment by odersky** [comment]
> This could compile if x was desugared to a public val in foo.

Yes, but then `x` would be itself available as a given, which is probably not what is intended.

**Comment by odersky** [comment]
@neko-kai Unfortunately, "lifting out" the necessary type constraints into a refinement is a rats nest of complexity.

**Comment by neko-kai** [comment]
@odersky This type is currently inferred automatically if you omit the signature, so it appears the mechanisms are already present, although I may not be aware of more complex cases

**Comment by smarter** [comment]
> Yes, but then x would be itself available as a given

I'm not sure I follow, available as a given in what context ?

**Comment by odersky** [comment]
@smarter As a field of the class. OK, maybe that's not so much of a problem since the class would usually not be referred to by name. But then there's the issue that we'd create a field that's typically not used at runtime.

**Comment by odersky** [comment]
@neko-kai We'd have to try it out the anonymous class encoding to see whether it would work in all cases.

**Comment by neko-kai** [comment]
@odersky `summon` exposes the most precise type, so you could have a situation where a field `x` is chosen over a `.x` extension method for specific instances only if `x` is public.

**Comment by odersky** [comment]
@neko-kai The anonymous class encoding infers the right type only if there are no parents at all. Once you put in the `AnyRef` (or any other parent) it does not infer a refinement.

**Comment by smarter** [comment]
> But then there's the issue that we'd create a field that's typically not used at runtime.

If the given parameter is used in any method of the given instance, then we need a field anyway. So this is only sub-optimal when the parameter is used purely as a witness (in which case ideally you'd want the ability to mark it `erased` anyway).

> summon exposes the most precise type, so you could have a situation where a field x is chosen over a .x extension method for specific instances only if x is public.

Good point. Instead of making it public, we could make it protected, Dotty would still be OK with having it appear in the type of a public member.

**Comment by odersky** [comment]
@smarter Good idea. Let's try with protected.

**Comment by neko-kai** [comment]
@odersky 
> value refinements require reflection at runtime.

Scala 2 can avoid reflection for refinements that are 'local enough', e.g.

```scala
def makeResource[A](acquire: => A)(release: A => Unit): Unit = makeResource(acquire)(release)

makeResource {
  object x {
    def close(): Unit = ()
  }
  x
}(_.close()) // no reflective access, even though there's no expressible type parameter for makeResource
```

This ability could be extended to public refinements coming from anonymous instances (i.e. the type stores the anonymous class also).

To be honest, what I'm irked about is the sudden and inconsistent namespace polution from given instances. This causes an error[1]():

```scala
case class A[B](b: B)
given A[B: Show] as Show[A] {
  def show(a: A) = "A(${Show(B)})"
}
// A is already defined as class A
```

But this doesn't:

```scala
case class A[B](b: B)
given A as Show[A[Int]]
```

Because only a parameterized given takes up **two** public names, the rest of the givens only take up a value name!
