### ISSUE TITLE
Eliminate overloaded methods before typeclass resolution

### ISSUE THREAD

**Issue by julien-truffaut** [lampepfl/dotty#8418]
## minimized example

I created a repo to minimise the issue: https://github.com/julien-truffaut/OpticsTypeclass

Two optics: `Optional` and `Traversal`. You can compose (`andThen`):
- an `Optional` with an `Optional`  producing an `Optional`
- an `Optional` with a `Traversal` producing a `Traversal`

```scala
trait Optional[From, To] {
  def andThen[Next](other: Optional[To, Next]): Optional[From, Next] = ???
  def andThen[Next](other: Traversal[To, Next]): Traversal[From, Next] = ???

  // non-overloaded alias for andThen
  def andThenOptional[Next](other: Optional[To, Next]): Optional[From, Next] = ???
}

object Optional {
  def apply[From, To](): Optional[From, To] = new Optional[From, To] {}
}

trait Traversal[From, To]
```

One typeclass with an instance for `List` and one for `Map`:

```scala
trait Index[From, -Key, To] {
  def index(key: Key): Optional[From, To]
}

object Index {
  def index[From, Key, To](key: Key)(implicit ev: Index[From, Key, To]): Optional[From, To] = ev.index(key)

  implicit def mapIndex[K, V]: Index[Map[K, V], K, V] = ???
  implicit def listIndex[A]: Index[List[A], Int, A] = ???
}
```

Example:

```scala
val list: Optional[Int, List[String]] = Optional()
val map: Optional[Int, Map[String, Int]] = Optional()

// compile
list.andThen(Index.index(2): Optional[List[String], String])
list.andThenOptional(Index.index(2))

// does not compile
list.andThen(Index.index(2)) 
```

It compiles if I specify the return type of `index` or if I use a non-overloaded method. 

## Compilation output

```scala
[error] -- Error: /Users/trufj/project/OpticsTypeclass/src/main/scala/Main.scala:11:32 -
[error] 11 |     list.andThen(Index.index(2)) // does not compile
[error]    |                                ^
[error]    |ambiguous implicit arguments: both method mapIndex in object Index and method listIndex in object Index match type optics.mono.Index[From, Int, To] of parameter ev of method index in object Index
[error] one error found
```

## expectation

The following should compile:

```scala
list.andThen(Index.index(2)) 
```

I would expect the compiler to check the return type of `Index.index` (an `Optional`) to discard the overloaded `andThen` that takes a `Traversal`. Then resolve the implicit.

**Comment by odersky** [comment]
The problem is that the result might itself undergo an implicit conversion, so discarding alternatives on return type can produce failures for code that should go through. Example:
```scala
class A
class B
given Conversion[A, B] = ???
def f(x: Int): A = ???
def f(x: String): B = ???
f(1): B
```

**Comment by julien-truffaut** [comment]
@odersky I thought conversions only quick in if no value is available for the right type.

In your example, if I add:
```scala
def g(a: A): String = ???
def g(b: B): String = ???

g(f(1))
```

I would expect the conversion not to be triggered because there is a `g` that accepts an `A`.

**Comment by odersky** [comment]
> I would expect the conversion not to be triggered because there is a g that accepts an A.

That's correct. But I don't see how it invalidates my example.

**Comment by julien-truffaut** [comment]
It doesn't invalidate your example, but I don't think it is applicable to the original example I posted. Maybe the title of this ticket should be updated. I used "Eliminate overloaded ..." as a wild guess at a solution.

To come back to my example:
- there are 2 overloaded `andThen` functions, one that accepts an `Optional`, the other a `Traversal`
- `Index.index` returns an `Optional`

Therefore, I would have expected the type inference to try first the `andThen` that accept an `Optional`. Now, I don't know if there is such a notion of "try first".

**Comment by odersky** [comment]
Yes, that's precisely the problem: "try first" sometimes requires foresight. The type checker does already a very elaborate dance here. For instance, in overloading resolution, it first tries
without expected result, because of the scenario I showed. If that still gives ambiguities it iteratively considers subsequent argument lists and larger parts of the result type, until either all known parts are accounted for, or the ambiguity goes away. 

This does not work with the problem at hand, because the observed problem is not an ambiguous overload but an ambiguous implicit. Now, the problem is how to combine the two without turning the compiler into a bigger ball of mud with more tangled dependencies.

**Comment by odersky** [comment]
Let's re-open the issue when someone has a fleshed out scheme and a prototype implementation to do this.
