### ISSUE TITLE
Failed nightly test with Java 11

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#8501]
Nightly build failed `tests/run/context-functions.scala` with Java 11.

https://dotty-ci.epfl.ch/lampepfl/dotty/4916/1/7

Restarted test: https://dotty-ci.epfl.ch/lampepfl/dotty/4918

**Comment by nicolasstucki** [comment]
@anatoliykmetyuk this might be a blocker for #8496

**Comment by nicolasstucki** [comment]
Actually it first failed in https://dotty-ci.epfl.ch/lampepfl/dotty/4887

**Comment by smarter** [comment]
probably caused by https://github.com/lampepfl/dotty/pull/8452. Not sure what's going on but I don't really understand why a mini-phase is a better fix than not doing an expansion when the expected type of an implicit function type is the same function type.

**Comment by anatoliykmetyuk** [comment]
> Actually it first failed in https://dotty-ci.epfl.ch/lampepfl/dotty/4798

Yeah, no nightlies have been published since 6th March: https://repo1.maven.org/maven2/ch/epfl/lamp/dotty-compiler_0.23/

**Comment by anatoliykmetyuk** [comment]
It seems that it is caused by #8386. The failing test in question was added in that PR and was failing on Java 11 from the very time it was introduced. The first commit where `testCompilation context-functions` fails under Java 11 is cbd21a0fbfd0c566f55649dc1dcfcb054529f18b.

**Comment by smarter** [comment]
Note that the this test runs correctly under Java 11 with a nightly from before #8386 so it is a regression.

**Comment by anatoliykmetyuk** [comment]
This test did not exist before #8386, it never worked under Java 11.

**Comment by smarter** [comment]
>  If you run it manually before #8386 though, it does work properly.

Yes, that's what I meant.
