### ISSUE TITLE
TASTY: no way to access `baseClasses` of `AppliedType`

### ISSUE THREAD

**Issue by pshirshov** [lampepfl/dotty#8514]
I'm working on re-implementation of izumi-reflect for Dotty.

So far I made some substantial progress but seems like there is a blocker.

The primary problem is: seems like there is no way to get access to `baseClasses` of a type:

Let's assume that we have the following definitions:

```scala
trait X[A, B]
trait A[F[_]]
trait B extends A[X[Int, *]]
```

On scala2 I can call `.baseClasses` method on a type of `B` and get a list containing `A[[T] => X[Int, T]]`.

In dotty `AppliedType` has only `tycon` method which does not allow me to inspect applied parents. 

See also: https://github.com/7mind/dotty-typetag-research/issues/2

**Comment by pshirshov** [comment]
@nicolasstucki could you check this issue please?

**Comment by Blaisorblade** [comment]
> On scala2 I can call .baseClasses method on a type of A

I assume you mean the type of B, or do I miss something? Can you maybe clarify?
(On the actual issue, I’m aware the API is incomplete and extensions are being considered, and things like this should be fine, but I cannot say more).

**Comment by pshirshov** [comment]
Yeah, fixed.

**Comment by Blaisorblade** [comment]
(On the actual issue, I’m aware the API is incomplete and extensions are being considered, and things like this should be fine, but I cannot say more).

**Comment by jdegoes** [comment]
This seems like a useful improvement regardless, but speaking as a ZIO contributor, I know we are relying on this functionality (or its equivalent) for the new environment encoding, which has proven to be a smash hit among ZIO users, but which only has partial support in Dotty.

Thanks for reporting!

**Comment by pshirshov** [comment]
Seem like this is not enough. Seems like just this method does not allow to get *applied* supertype:

```
trait Super[X]
trait Sub extends Super[X]
```

I can get `Super` from `.baseClasses` output but not `Super[X]`.

Seems like `TypeApi#baseClass` would solve my problem, but it's not exposed.
Could you expose it as well?

```
    /** The least type instance of given class which is a super-type
     *  of this type.  Example:
     *  {{{
     *    class D[T]
     *    class C extends p.D[Int]
     *    ThisType(C).baseType(D) = p.D[Int]
     * }}}
     */
    def baseType(clazz: Symbol): Type
```

**Comment by smarter** [comment]
If you need some API to be exposed, I encourage you to make a PR to do so yourself.

**Comment by pshirshov** [comment]
Yup, trying to do that.

**Comment by pshirshov** [comment]
@smarter : https://github.com/lampepfl/dotty/pull/9481 - what would you say?
