### ISSUE TITLE
TASTY: no way to access type constructor of an `AppliedType` and explore its argument variance

### ISSUE THREAD

**Issue by pshirshov** [lampepfl/dotty#8520]
This is another problem which blocks `izumi-reflect` reimplementation for Dotty.

Let's assume that we have the following definitions:

```scala
trait X[+_]
trait A[+F[+_]]
```

Having `AppliedType` for ` A[X[Int]]` I need to be able to access it's type constructor, enumerate parameters and obtain variance flags. Essentially I need to get something like `List(TypeParameter(F, Covariant))`

So far I've found the only (insane) way to access something which looks like a type constructor:

```scala
val tycontree = a.tycon.asInstanceOf[TypeRef].typeSymbol.tree.asInstanceOf[TypeDef].rhs.asInstanceOf[TypeTree]

            val params = try {
              tycontree match {
                case d: {def constr: DefDef} =>
                  d.constr.typeParams
                case o =>
              }
            } catch {
              case t: Throwable =>
            }
```

Though this way I cannot extract type parameter declarations - all the values returned by `typeParams` are instances of `TypeBounds` with no variance information attached.

See also: 7mind/dotty-typetag-research#2

**Comment by pshirshov** [comment]
@nicolasstucki could you check this issue please? :)

**Comment by nicolasstucki** [comment]
@smarter how would we do this properly within the compiler?

**Comment by smarter** [comment]
@nicolasstucki  If I have a symbol for `trait A[+F[+_]]`, I can call `SymDenotation#typeParams` to get the symbol of `F`, then check the `.is(Covariant)` / `.is(Contravariant)` flags on that symbol. 

(If I want the variance of the parameter of `F` itself, then I need to get the `info` of `F` which should be a `TypeBounds` whose upper-bound is an `HKTypeLambda`, once I get that I can finally call `HKTypeLambda#declaredVariances` on it.)

**Comment by jdegoes** [comment]
As for #8514, big 👍 on this from me and other ZIO contributors / users eager to fully utilize the new environment encoding on Scala 3.
