### ISSUE TITLE
Inline unapply patterns

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#8530]
We want to be able to support the following kind of use case

```scala
object MyPattern {
  inline def unapply(x: T): Option[U] = Some(x)
}
```

```scala
x match 
  case MyPattern(y) => ....
```

where the call to `MyPattern.unapply` will get inline and possibly be a macro.

Technically, this would mean generating a new instance with a compatible definition of the unapply and then inline the code in it's body. The return type would be inferred from the expansion of the unapply (whiteboxity). The anonymous class could be optimized away when the pattern matching compiled to labeled blocks.
```scala
x match 
  case <new { def unapply(x: T) = MyPattern.unnaply(x) }>(y) => ....
```

**Comment by smarter** [comment]
> Technically, this would mean generating a new instance with a compatible definition of the unapply and then inline the code in it's body. 

Couldn't we generate a lambda that corresponds to the unapply instead ?

**Comment by nicolasstucki** [comment]
The lambda was my first thought. But it might be hard to distinguish unapply from unapplySeq.

**Comment by fhackett** [comment]
Just a thought - if this works with `inline match`, it might have a really interesting interaction with #8348 .
