### ISSUE TITLE
No ability to get top-level type parameters from Tasty Inspection

### ISSUE THREAD

**Issue by gzoller** [lampepfl/dotty#8532]
## minimized code

```Scala
case class Foo[U]

def reflectOn[T](implicit ct: ClassTag[T]): ConcreteType = 
    val clazz = ct.runtimeClass
    val className = clazz.getName
    val tc = new MyClassInspector(clazz)
    tc.inspect("", List(className))

class MyClassInspector(clazz: Class[_]) extends TastyInspector:
  protected def processCompilationUnit(reflect: Reflection)(root: reflect.Tree): Unit = 
    import reflect.{given _}
    // Point 1 (see below)

// ------ Usage:
reflectOn[Foo[Boolean]]
```

## The Problem
The code above works well to dive into a class and  inspect it using Tasty Inspection.... with one gap.
Inside MyClassInspector.processCompilationUnit() one can noodle around and see that our target's class is Foo, and dig further to learn that it has 1 type parameter.  Now the gap: It sees the parameter as U, not the actual type of Boolean.

If you're reflecting on a complex class having fields, some of which are themselves parameterized types, Tasty Inspection does the right thing and can see the resolved types of those parameters if available/specified by the programmer.  Just the top-level seems to be missing.

My theory for this gap is that once inside Tasty Inspection's context it can see everything it needs to, but the initial call is outside that context.  Outside a TastyInspector.  So it can't see the actual types specified in the original call.

## expectation
At some point we need to capture this "outer" type, including its type parameters.  They're given by the programmer (Boolean, in this example), and the compiler should see it before erasure happens.  This information needs to be propagated to something visible in the Reflection class for Tasty Inspection.

Query:  Does the thing that "runs" TastyInspector (i.e. calls processCompilationUnit()) have a QuotedContext, or more specifically a scala.quoted.Type?  If so all the needed info should be in there, as it is in a macro-based implementation:

```scala
// Macro-based works:  getParams[Foo[Boolean]] returns List(scala.Boolean)
// (We probably want something other than Strings here, but this shows the needed
// information is indeed in the Type)
inline def getParams[T]: List[String] = ${ getParamsImpl[T]() }

def getParamsImpl[T]()(implicit qctx: QuoteContext, ttype:scala.quoted.Type[T]): Expr[List[String]] = 
  import qctx.tasty.{_, given _}
  val AppliedType(_,tob) = typeOf[T]
  val res = tob.map(_.asInstanceOf[TypeRef].classSymbol.get.fullName)
  Expr(res)
```
We're golden if we can do the same thing in for Inspection.

**Comment by nicolasstucki** [comment]
Now the TastyInspector takes as input a `.tasty` file. This kind of interaction will not be possible.

On the other side, using a `ClassTag` is the wrong approach we need to know the type parameters.

Here is an outline of how I would start rewriting this
```scala
inline def reflectOn[T]: ConcreteType = 
  ${ reflectOnExpr[T] }

def reflectOnExpr[T: Type](using Quotes): Expr[ConcreteType] = {
  Type.of[T] // contains the full type (`Foo[Boolean]` in the example above)

  import quotes.reflect._
  TypeRepr.of[T].typeSymbol.tree // gets the tree of the definition of `class Foo`, might need `-Yretain-trees`
  
}
```
