### ISSUE TITLE
function types in combination with `var` need parentheses

### ISSUE THREAD

**Issue by robstoll** [lampepfl/dotty#8537]
## minimized code
```scala
val f: Int => String = _ => "b"
var g: Int => String = (_) => "b"  // workaround
var h: Int => String = _ => "b"    // end of statement expected but '=>' found
```

Following the link to scastie:
https://scastie.scala-lang.org/rMQP1D6bQRODka5UcUP43g

## expectation
Should work the same way it works for `val`

**Comment by odersky** [comment]
I cannot reproduce this standalone in current master.
