### ISSUE TITLE
Replace meaningless warning in ReadTasty with something actionable for already-loaded classes

### ISSUE THREAD

**Issue by gzoller** [lampepfl/dotty#8558]
## The Problem
Today when reading a Tasty file (Tasty Inspection via ReadTasty), if you happen to inspect a class that is already loaded (e.g. a Scala primitive type, or collection) you get a warning printed to the console and nothing returned (i.e. no CompilationUnit).  This is not useful because the consumer of ReadTasty doesn't know what happened--and the user's console is cluttered with a low-level/internal message that likely has little meaning to them.

## Expectation
Have ReadTasty.readTASTY() return a special CompilationUnit when it encounters a class that is already loaded, containing the class name of the class.  The upstream consumer of ReadTasty can then either handle or ignore as appropriate, but at least they know about it.

Likewise expose this information through the Reflection API following established patterns.

(PR for this in-progress)

**Comment by nicolasstucki** [comment]
At some point, we should be able to load the trees for those classes regardless of them already been loaded.

**Comment by gzoller** [comment]
Agreed.  I tried poking at this in ReadTasty to see if any CompilationUnit or tree made sense to return, but I wasn't able to find anything meaningful.  Either I didn't look in the right place or it has to be found upstream of ReadTasty.  In any event, this fix (PR #8559) will work for now, and it follows the existing pattern--in other words it is better that a console warning message.

**Comment by nicolasstucki** [comment]
Does this fix actually unblocks you or only removes the annoying messages? If it does not block you, I would propose to print this message on some loggers that can be silenced by default.

**Comment by gzoller** [comment]
It currently blocks me--its actually my final feature before I release v0.0.1 of my reflection library.  Here's my use case:  If my top level code (that instantiates the TastyInspector) looks like this:
```scala
readMyThing[List[Thingy]]
```
Then I'll Tasty inspect List[Thingy].  In ReadTasty, List is already loaded.  So today I'd get the error message and nothing is propagated up to the caller that it's loaded.  My system would interpret that as UnknownInfo("scala.collection.immutable.List") and that's it.  Not what is needed.

My fix creates AlreadyLoadedCompilationUnit, holding the class name, which the caller can intercept.  In my case I create a holder object for the already-loaded thing, continue inspecting the type params (Thingy), then "sew" them together for a final result.  Without that knowledge--just the error msg--I'd never know what happened in ReadTasty, and reflecting on top-level things like containers wouldn't be possible.

Like this:
* Reflect on List --> Detects AlreadyLoadedCompilationUnit and creates ContainerInfo("scala.collection.immutable.List, "A")
* Reflect on Thingy --> Produces ClassInfo("my.org.Thingy",...)
* Sew together to produce ContainerInfo("scala.collection.immutable.List, ClassInfo("my.org.Thingy",...))

That's my desired result.

**Comment by gzoller** [comment]
Do you have a concern with the fix?  I was hoping this might make 0.23.0, if it's not too late, so my library doesn't need to depend on a Nightly build.

**Comment by smarter** [comment]
> I was hoping this might make 0.23.0

Too late, it's been tagged already: https://github.com/lampepfl/dotty/tree/0.23.0-RC1

**Comment by smarter** [comment]
> I would propose to print this message on some loggers that can be silenced by default.

In general, libraries should not print messages (unless they're crashing). They should return enough information to the caller to let it decide what to do.

**Comment by gzoller** [comment]
nicolasstucki, do you have any concerns about the PR?  (#8559)  It's otherwise tested and ready pending review.

**Comment by nicolasstucki** [comment]
I'm only concerned about adding more stuff to the interface that is only there to workaround some limitations of the inspector.

**Comment by gzoller** [comment]
Thank you, sir.  I can appreciate this concern, and yes the inspector probably needs a version 2 at some point to smooth out the gaps, but this fix does expose some of the mysteries going on in there.  Ideally if a class is already loaded the inspector could just return the CompilationUnit wrapping the symbol or tree that's loaded, so from the caller's perspective its nothing special.  I didn't find that in ReadTasty but its gotta be in there--somewhere the compiler knows about it.
