### ISSUE TITLE
QuoteContext show can show code that does not compile 

### ISSUE THREAD

**Issue by valencik** [lampepfl/dotty#8585]
The following code is based of the [dotty-staging.g8](https://github.com/lampepfl/dotty-staging.g8/blob/e23f43825a8acf8210085e348e3dd03e53a71399/src/main/g8/src/main/scala/Main.scala) project.

```scala
import scala.quoted._
import scala.quoted.staging.{run, withQuoteContext, Toolbox}

object Main {
  given Toolbox = Toolbox.make(getClass.getClassLoader)

  def main(args: Array[String]): Unit = {
    val toTheEighth = stagedPower(8)
    println("3^8 = " + toTheEighth(3))
  }

  def stagedPower(n: Int): Double => Double = {
    def code(using QuoteContext) = '{ (x: Double) => ${ powerCode(n, 'x) } }
    println("The following would not compile:")
    println(withQuoteContext(code.show))
    run(code)
  }

  def powerCode(n: Int, x: Expr[Double])(using ctx: QuoteContext): Expr[Double] =
    if (n == 1) x
    else if (n == 2) '{ $x * $x }
    else if (n % 2 == 1)  '{ $x * ${ powerCode(n - 1, x) } }
    else '{ val y = $x * $x; ${ powerCode(n / 2, 'y) } }
}
```

It has been slightly trimmed and modified such that `powerCode` recursively calls itself twice.
This results in generating two lines starting `val y: scala.Double =`.

## Output

Running this yields the following output:
```
The following would not compile:
((x: scala.Double) => {
  val y: scala.Double = x.*(x)
  val y: scala.Double = y.*(y)
  y.*(y)
})
3^8 = 6561.0
```

Attempting to compile that source code yields an error:
```
[error] 4 |  val y: scala.Double = y.*(y)
[error]   |  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |  y is already defined as value y
```

## Expectation

`code.show` should produce a source code representation that compiles.
We can, however, see that the staging works and we get our answer `3^8 = 6561`

**Comment by odersky** [comment]
That looks like a rather tall order. Macro-generated code might not compile when printed as source in a myriad different ways. I agree it would be useful to have this, but it looks like a sizeable project on its own to get there.

**Comment by valencik** [comment]
@odersky thanks for the insight. Is there a way to see more directly what code was generated/run by the staging process?
i.e. What is the difference between the code that was able to evaluate 3^8 and the code that was printed as source?

**Comment by odersky** [comment]
The staged code uses internal symbols instead of printable names. That's what makes it hard to print correctly in the first place.
