### ISSUE TITLE
Subtype not accepted

### ISSUE THREAD

**Issue by maximeb-uber** [lampepfl/dotty#8592]
## minimized example

```Scala
object Problem extends App {
    trait ~>[F[_],G[_]]{
        def apply[A](fa: F[A]):G[A]
    }

    enum Expr[R[_],I] {
        case Const(v:Int) extends Expr[R,Int]
        case Add(l:R[Int],r:R[Int]) extends Expr[R,Int]
    }

    import Expr._

    case class Id[T](unId:T)

    val squish = new (([X]=>>Expr[Id,X]) ~> Id) {
    def apply[T](t : Expr[Id,T]): Id[T] = {
        t match {
            case  Const(v) => Id(v)
            case Add(Id(l),Id(r)) => Id(l+r)
        }   
        }
    }

    val unsquishKO = new (Id ~> ([X]=>>Expr[Id,X])) {
    def apply[T](t : Id[T]): Expr[Id,T] = {
        t match {
            case Id(1) => Const(1)
            case Id(n:Int) => Add(Id(1),Id(n-1))
        }
    }
    }
}
```

Hi, 
I am trying to implement HFunctors using GADTs in Dotty. In the example above, the compiler doesn't accept Const(1) and Add(Id(1),Id(n-1)) in the last pattern matching because it types them as Expr[Nothing, Int] and Expr[Id,Int]. These types are subtypes of Expr[Id,T] so they could be accepted. Is Dotty expected to reject them ?

**Comment by AleksanderBG** [comment]
@maximeb-uber these types are not, in fact, subtypes. The problem is that we can't really figure out what `T` of `Id[T]` is just by pattern matching on a value of type `T` - consider, for instance, that the first pattern in:

```scala
        (t: Id[T]) match {
            case Id(1) => Const(1)
            case Id(n:Int) => Add(Id(1),Id(n-1))
        }
```

can match if if `T` is `1` or `Any` or anything in between.

**Comment by AleksanderBG** [comment]
You might be able to get further along if you pass an additional parameter that constrains `T` somehow, for instance:

```scala
enum Typ[T] {
  case Int extends Typ[Int]
  …
}
```

**Comment by AleksanderBG** [comment]
Closing as a non-issue due to lack of activity. @maximeb-uber, if you have any more questions, feel free to ask them!
