### ISSUE TITLE
Change syntax of given whitebox macros

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#8619]
### Status quo

```Scala
inline def whiteBox1 <: T = ...
inline given whiteBox2 as _ <: T = ...
```
### Critique

 - Syntax is not consistent
 - You could argue that the first syntax is too quiet and also misleading since at first glance `whiteBox1` is in the position where you would expect to see a type.
 - `_ <: T` is technically wrong (or, rather, old style) since it suggests a lambda. We are after an existential instead.

### Proposal

Write `? <: T` (analogous to a wildcard type argument) to express both forms of whitebox macros. I.e.

```Scala
inline def whiteBox1: ? <: T = ...
inline given whiteBox2 as ? <: T = ...
```

Opinions?

**Comment by smarter** [comment]
`? <: T` makes me think I can put something other than `?` on the left which is not the case. If we need to change the syntax I would rather use an extra keyword to denote whiteboxity (I think `whitebox` is fine since it's well-established Scala jargon).

**Comment by odersky** [comment]
Or `transparent`?

**Comment by AleksanderBG** [comment]
I actually like the `? <: T` syntax - it expresses the "unknown subtype of `T`" concept well.

Reg. trying to replace `?` with another type - to me doing that would result in something that reads like nonsense, so I'm not sure if very many people will try to do that. Consider:

`inline def foo : ? <: String` === "define an inline `foo` that returns some subtype of String"
`inline def foo : "a" <: String` == "define an inline `foo` that returns `"a"`, which is a subtype of String"

**Comment by smarter** [comment]
The problem is that:
```scala
inline def foo : ? <: String
```
is very different semantically:
```scala
inline def foo : List[? <: String]
```
The latter is not whitebox at all, even though it uses a very similar syntax.

**Comment by AleksanderBG** [comment]
Hm, you may be right and it may be too cute. How would the keyword syntax look? Like this?

```scala
inline whitebox def foo : String = …
```

**Comment by smarter** [comment]
`whitebox inline def` I'd say, `whitebox` is a modifier of `inline`.

**Comment by AleksanderBG** [comment]
The part that I am slightly miffed about is that we would lose the "this is not an actual type annotation" suggestion that the current syntax `foo <: String` expresses. Might not be a big loss, all things considered.

**Comment by odersky** [comment]
I'd go for `transparent inline`. `whitebox` is too much expert speak. Also, it works better in conjunction with `blackbox` but we do not have that one as a modifier.

**Comment by amsayk** [comment]
How about ?

```scala
inline def whiteBox1 : ?String
inline given whiteBox2 as ?T = ...

```

This was propose and rejected for `null`able types.

**Comment by nicolasstucki** [comment]
Finally, I have always thought that this feature deserved a flag. We currently have no way to know if an inline method is whitebox or not after it is typed.

**Comment by milessabin** [comment]
Scala 2 accidentally treats an empty refinement as "do not widen" indicator. Could we make that official and use it here,
```scala
inline def foo : String {} ...
```

**Comment by nicolasstucki** [comment]
We should have a syntax where not widening would not happen by mistake.

**Comment by odersky** [comment]
I am not sure about the flag. We are currently trying hard to reduce the number of flags that we pickle. Even without a flag., there could be a robust predicate on symbols indicating whether an inline function is blackbox or whitebox  Namely, an inline function `f` such as
```scala
inline def f(): T = rhs
```
is blackbox if `rhs` is of the form `E: T1` where `T =:= T1` (we only need to test `T <:< T1`, the other direction holds anyway). If that's the case, the expansion of `f` cannot change the type, which is what 
characterizes a blackbox macro. Now it's true that if someone writes
```scala
transparent inline def f(): T = E: T
```
that also gives a blackbox macro according to our definition, despite the `transparent`. But I'd argue that's OK, and even desirable: we capture that way the semantics of a blackbox macro, not the syntactic representation.

**Comment by sjrd** [comment]
> We are currently trying hard to reduce the number of flags that we pickle.

Why though? That sounds like a useless target metric. What's important is to pickle the semantics of the language, and not a particular encoding of the language. It should add simple as possible, sure, but not simpler.

You can argue that the semantics of blackbox macros is a whitebox macro with an ascription. But then that's also how you have to specify the language. And that means that you cannot explain blackbox macros without explaining whitebox macros. That doesn't seem like a good deal to me.

**Comment by nicolasstucki** [comment]
Note that we will need as a flag (or at least in the TASTy file) for  #7825.

**Comment by odersky** [comment]
> Note that we will need as a flag (or at least in the TASTy file) for #7825.

What I had in mind was a method `isBlackboxInline` on symbols that implements the logic I outlined before.  That method should give valid results for methods coming from Tasty as well. So we would not need a flag.

**Comment by odersky** [comment]
Here's the ruleset:

 - A blackbox macro is a macro that on inline expansion keeps its type
 - A normal inline method always keeps its type since its inline expansion is ascripted with its result type. That's a desugaring step, not relevant for Tasty.
 - A `transparent` inline does not get ascripted, so it _might be_ a whitebox macro (and probably will be, in most cases).
