### ISSUE TITLE
inline and -Yexplicit-nulls do not interact well

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#8643]
Using `-Yexplicit-nulls`, this works:
```scala
def test(x: Int | Null): Unit = {
  assert(x != null)
  val y: Int = x
}
```
But if we add inline, then typechecking fails:
```scala
inline def test2(x: Int | Null): Unit = {
  assert(x != null)
  val y: Int = x // error: Found: Int | Null, expected: Int
}
```
The problem is that `assert` is an inline method, and inline methods appearing in the body of an inline method are not inlined when typechecking the inline method itself. I don't know if this is considered acceptable ? If it isn't, then the only solution I can think of involves reflecting the nullability information in the type of the method somehow. /cc @odersky @noti0na1

**Comment by noti0na1** [comment]
I think it would be great if the both two functions are typechecked. I'm worry about we may go too far in terms of flow typing, if we want to extract nullability information from method calls.

I don't think this is an importent issue, as a user can replace the `assert` by a `if(x != null) throw` to achieve the same effect.

**Comment by bishabosha** [comment]
This should be discussed

**Comment by odersky** [comment]
Is there a practical way to do flow typing without inline expansion? I doubt it. If nobody comes up with a scheme we should close the issue.

**Comment by bishabosha** [comment]
Is there any update on this?

**Comment by odersky** [comment]
No update.
