### ISSUE TITLE
Pattern-matching on higher kinded cases fails to reduce in type functions

### ISSUE THREAD

**Issue by felixmulder** [lampepfl/dotty#8644]
## Minimized code

```Scala
  case class :>[+A, +B]()

  type Foo[X] = X match
    case Int =>
      Int
    case Boolean :> rest =>
      Boolean
    case String :> rest =>
      Foo[rest]

  def test: Foo["foo" :> Int] = 1

```

## Output

```scala
[error] -- [E007] Type Mismatch Error: /Users/fixel/.src/serviteur/src/main/scala/Main.scala:37:32
[error] 37 |  def fixMeOlivier: Foo["foo" :> Int] = 1
[error]    |                                ^
[error]    |                             Found:    (1 : Int)
[error]    |                             Required: Main.Foo[("foo" : String) :> Int]
```

**Comment by OlivierBlanvillain** [comment]
This is working as indented: reducing to `Int` here would be unsound because of `:>[Nothing, Nothing]()` that matches both `case Boolean :> rest` and `case String :> rest`. The semantics of match types follow the ones of match expression, such that the following should typecheck:

```scala
def foo[X](x: X): Foo[X] = x match {
    // ClassTag/TypeTag would be needed to actually implement this at runtime...
    case _: Int =>
      1
    case _: (Boolean :> rest) =>
      true
    case _: (String :> rest) =>
      foo(null.asInstanceOf[rest])
}
```

But now if `Foo["foo" :> Int]` reduces to `Int` stuff goes wrong when calling `foo[Nothing :> Nothing](:>[Nothing, Nothing])` which would reduce to `true` at runtime but be typed as `Int`.

**Comment by OlivierBlanvillain** [comment]
I should probably add that you can get what you want by either:

- Making `A` and `B` invariant, in which case subtyping doesn't come into the picture.

- Adding fields of type `A` and `B` in `<:`, if you write `case class :>[+A, +B](a: A, b: B)` then the compiler knows that `A` and `B` are not phantom types, meaning that it should be impossible to construct a value of type `:>[Nothing, Nothing]` at runtime and it's fine to reduce.

**Comment by felixmulder** [comment]
> * Making `A` and `B` invariant,...

I had to make things covariant due to being able to match on string literals. I would rather keep it invariant. Is there a way to match on string literals without specifying the exact literal?

> * Adding fields...

Will try this in the interim!

**Comment by neko-kai** [comment]
> Is there a way to match on string literals without specifying the exact literal?
String literals conform to `String with Singleton` if that's what you mean

**Comment by felixmulder** [comment]
@neko-kai - already did that actually, but this issue was actually: https://github.com/lampepfl/dotty/issues/8647 in disguise.

Making everything invariant works amazingly for getting the full reduction :)
