### ISSUE TITLE
Can't access dotty classes

### ISSUE THREAD

**Issue by ysthakur** [lampepfl/dotty#8658]
I'm trying to follow this tutorial on how to debug Dotty programs (https://dotty.epfl.ch/docs/contributing/debugging.html). For that, I need to be able to access untpd.scala but when I try to import ```tools.dotc.ast.untpd```, the ```tools``` package cannot be found. I can't find a Dotty standard library anywhere; it seems Dotty uses Scala 2.13's library. Is there a dependency I need to add or do I have to clone this repository and build it?

**Comment by bishabosha** [comment]
Hello, this tutorial assumes that you are testing the dotty project itself, and have access to the source code of the compiler, `dotc` in this case is an sbt task that runs the compiler main method, and not the bash script. You may be able to get a quicker response if you use the gitter room instead: https://gitter.im/lampepfl/dotty
