### ISSUE TITLE
REPL: output lines order doesn't match input definitions order

### ISSUE THREAD

**Issue by unkarjedy** [lampepfl/dotty#8677]
## Minimized code
1. open dotty REPL e.g. in dotty-example-project via `sbt console`
2. paste following multiline content
```Scala
sealed trait T1
case class X() extends T1
case class Y() extends T1
case object O extends T1
```

## Output
```
// defined case class Y
// defined case object O
// defined trait T1
// defined case class X
```

## Expectation
```
// defined trait T1
// defined case class X
// defined case class Y
// defined case object O
```

![image](https://user-images.githubusercontent.com/3989292/78548634-c5652380-7809-11ea-9ef7-f5ca4e6288c2.png)

**Comment by unkarjedy** [comment]
https://youtrack.jetbrains.com/issue/SCL-17300
https://github.com/lampepfl/dotty/issues/5545

**Comment by odersky** [comment]
Is there a requirement that the order matches?

**Comment by unkarjedy** [comment]
Hm, actually I'm not aware of such requirement in any specification.
(neither I am aware of any requirement to provide some meaningful output at all 😊)
That's just a thing that used to work in Scala 2 (11, 12, 13).
In Scala Plugin Worksheets we use Scala / Dotty REPL under the hood, and with the current Dotty REPL implementation the output looks quite weird:

![image](https://user-images.githubusercontent.com/3989292/78684467-2ae40d80-78f9-11ea-8377-f77996d6989a.png)
Some more details: https://youtrack.jetbrains.com/issue/SCL-17300#focus=streamItem-27-4064653.0-0
It's not something critical, just visually unsatisfying.

If a "feature"/"task" or any other tag is more appropriate here, please feel free to change it.
