### ISSUE TITLE
Given Shape is not found, when in context with another implicit

### ISSUE THREAD

**Issue by edolgy** [lampepfl/dotty#8683]
Fails to compile:

```Scala
    class C1
    class C2
    class C3

    trait Shape[A,B]

    given Shape[C1,C2]
    given Conversion[C2,C3] = _ => ???

    def make[A,B](v: A)(using Shape[A,B]) : B = ???

    val v1: C3  = make(new C1) // Does not compile: no implicit argument of type Shape[C1, B] was found

    val x = make(new C1)       // Compiles  
    val v2: C3 = x             // fine 
```
Is it a bug or intended behaviour? It is important to know as it changes the way libraries designed

It is understood that implicits are not applied twice, but this is the case when the first implicit happens before the 'make' method executed and second on its result, so technically it is not a straight double conversion. 

The call to 'make' is very deterministic as the last two lines indicate

**Comment by OlivierBlanvillain** [comment]
I would say "working as intended". This is a type inference issue, when typing make with expected type `C3` it's natural to look for an implicit `Shape[C1,C3]`. Things work as expected when you instantiate `B` to what you want:

```scala
scala> val v1: C3  = make[C1, C2](new C1)                                                                         
1 |val v1: C3  = make[C1, C2](new C1)
  |              ^^^^^^^^^^^^^^^^^^^^
  |Use of implicit conversion trait Function1 in package scala should be enabled
  |by adding the import clause 'import scala.language.implicitConversions'
  |or by setting the compiler option -language:implicitConversions.
  |See the Scala docs for value scala.language.implicitConversions for a discussion
  |why the feature should be explicitly enabled.
scala.NotImplementedError: an implementation is missing
```
