### ISSUE TITLE
REPL with JDK 14 "failure to convert Constant(true) to TypeRef..."

### ISSUE THREAD

**Issue by unkarjedy** [lampepfl/dotty#8688]
I am trying Dotty REPL (via `sbt console`) with JDK 14 and get some failure message on the first input statement:
```
failure to convert Constant(true) to TypeRef(ThisType(TypeRef(NoPrefix,module class scala)),class Byte)
Caught: dotty.tools.dotc.core.CyclicReference:  while parsing annotations in /modules/java.base/java/lang/annotation/ElementType.class
val res0: Int = 42
```
![image](https://user-images.githubusercontent.com/3989292/78689148-ad230080-78fe-11ea-979e-a5449fbac758.png)

**Comment by smarter** [comment]
Fixed in master by https://github.com/lampepfl/dotty/pull/8655 (try `scalaVersion := "0.24.0-bin-20200406-eff5496-NIGHTLY"` to get the latest nightly).
