### ISSUE TITLE
Redo lazy vals benchmarks after JDK-8140483 gets fixed

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#870]
https://bugs.openjdk.java.net/browse/JDK-8140483

starting point: 
https://github.com/DarkDimius/lazy-val-bench/tree/CallSites

**Comment by DarkDimius** [comment]
If benchmarks show no difference, it would be worth to use Atomic*FieldUpdaters instead of Unsafe to not depend on Unsafe.

**Comment by liufengyun** [comment]
superseded by #7140
