### ISSUE TITLE
.zip release missing execute bits on /bin/*

### ISSUE THREAD

**Issue by timw** [lampepfl/dotty#8703]
The .zip release distribution of dotty doesn't retain executable bits on `/bin/dotc` et al.
(Compared with the Scala releases, and the dotty .tar.gz releases which do).

This is an issue for some package managers (e.g. [sdkman](https://sdkman.io/)) that use the .zip release for cross platform binaries.

**Comment by smarter** [comment]
Interestingly, the .tar.gz archive does have the executable bit set on the binaries, and they're both generated by https://github.com/lampepfl/dotty/blob/f64e879ae33cd66eb6fd0b04670e75c743170303/.drone.yml#L188-L190, so maybe that drone plugin does something differently for zips ? Something to look into when we switch to using github workflows for doing releases too.

**Comment by anatoliykmetyuk** [comment]
Looks like `sbt-pack` issue, see xerial/sbt-pack#189.
