### ISSUE TITLE
Missing exhaustivity warning when pattern has a guard

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#8708]
The following code compiles without warning, even though the pattern isn't exhaustive:

```Scala
object Main {
  def foo(x: Option[Int]): Int = x match {
    case Some(n) if n % 2 == 0 => n
    case None => 0
  }
  
  def main(args: Array[String]): Unit = println(foo(Some(1)))
}
```

It looks like we special cases guards for redundancy checks but not for exhaustivity checks (https://github.com/lampepfl/dotty/blob/85ab20fd874994634b909f0883760413f6e2ef12/compiler/src/dotty/tools/dotc/transform/patmat/Space.scala#L812), but we need to do both to be safe.

See also previous discussions in https://github.com/scala/bug/issues/5365

**Comment by liufengyun** [comment]
This is now fixed in https://github.com/lampepfl/dotty/pull/8698/commits/d5f9047e48943bd232d9e9e3a04ded7d419a4ba3 .

I agree with Richard Bradley:

https://github.com/scala/bug/issues/5365#issuecomment-292401642

> Richard Bradley (richard.bradley) said:
> I don't think that example stands up to scrutiny. If  `g1 || g2` really is constant true, then rewrite your proposed:
> ```scala
> x match {
>   case p if g1 => ...
>   case p if g2 => ...
> }
> ```
> to just:
> ```scala
> x match {
>   case p if g1 => ...
>   case p => ...
> }
> ```
> This will a) allow the compiler to verify exhaustiveness and b) will help the reader to understand the code.
>
