### ISSUE TITLE
Spurious tailrec error "Cannot rewrite recursive call: it is not in tail position" because of asInstanceOf cast inserted by typer

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#8712]
## Minimized code

```Scala
import scala.annotation.tailrec

sealed trait Foo[+A]
case class Bar[A](f: Foo[A]) extends Foo[A]
case class Done[A](a: A) extends Foo[A]

object Test {
  @tailrec
  def runT[A](c: Foo[A]): A = c match {
    case Bar(f) => runT(f)
    case Done(a) => a
  }
}
```

## Output

```scala
-- Error: try/tr.scala:10:23 ---------------------------------------------------
10 |    case Bar(f) => runT(f)
   |                   ^^^^^^^
   |               Cannot rewrite recursive call: it is not in tail position
```

The problem comes from the tree we get after erasure:

```scala
          if x9.isInstanceOf[Bar] then
            {
              case val x14: Bar = Bar.unapply(x9.asInstanceOf[Bar])
              case val x15: Foo = x14._1()
              case val f: Foo = x15
              return[matchResult7]
                {
                  Test.runT(f.asInstanceOf[Foo]).asInstanceOf[Object]
                }
            }
           else ()
```
`runT` is indeed not in tail position since it's followed by an `asInstanceOf` cast, but that shouldn't prevent tailrec from working. However, I don't know/remember enough about labelled blocks to be sure of the correct way to handle this.

**Comment by sjrd** [comment]
It *should* prevent tailrec from working. An `asInstanceOf` is a real operation that requires something to happen.

However, in this case the `asInstanceOf[Object]` is completely useless. Obviously because everything is an `Object`, but in general `expr.asInstanceOf[T]` is useless if the type of expr is `<: T` according to the JVM type system.

Erasure is to blame here for inserting this useless cast. If it didn't insert that cast, tailrec would be able to do its job.

**Comment by smarter** [comment]
The cast is actually introduced by typer (I think because in general anything vaguely GADT-related gets a cast since GADT constraints are not known in phases after typer). But it could be removed by Erasure indeed. The cast-elision logic is:
https://github.com/lampepfl/dotty/blob/bd1fff257ca66156e555e782647588b4aad90365/compiler/src/dotty/tools/dotc/transform/TypeTestsCasts.scala#L243-L244
If I replace the check by `erasure(expr.tpe) <:< testType` the cast is elided as expected, but I haven't thought through whether that could break something else.
