### ISSUE TITLE
Cannot create case class with members like _1 or _2

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#872]
``` scala
case class Foo(_1: Int)
```

Fails with:

``` scala
 error: value _1 is already defined as method _1: => Int
case class Foo(_1: Int)
                 ^
```

Yes, people actually do this: https://github.com/molecule-labs/molecule/blob/master/molecule-core/src/main/scala/molecule/Tilt.scala#L26 Not sure if there's anything we can do here without a good rewriting tool.

**Comment by odersky** [comment]
I think this could be a case for the rewrite tool. Nothing we should change in the language.

**Comment by smarter** [comment]
Fixed in https://github.com/lampepfl/dotty/pull/1815
