### ISSUE TITLE
Extension clause position

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#8725]
The first definition in extension clauses has a wrong position. This may be an issue with semanticdb or the parser.

https://github.com/lampepfl/dotty/blob/master/tests/semanticdb/expect/Givens.expect.scala#L10

**Comment by nicolasstucki** [comment]
This was not fixed in the PR mentioned above. It was found in it.

**Comment by bishabosha** [comment]
This is just an issue with formatting that if some positions overlap then one is printed after the other, what is the real issue is that the position of the extension wrapper class is on the following line

**Comment by nicolasstucki** [comment]
This has been fixed. It is tested with https://github.com/lampepfl/dotty/blob/master/tests/semanticdb/expect/Givens.expect.scala#L10
