### ISSUE TITLE
Compiler hang forever when arbitrary type in arrow closure

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#8746]
## Minimized code

When attempting a quoted match an arrow closure with arbitrary types in a macro:
```Scala
tree.unseal.underlyingArgument.seal match {
    case '{ ($in: $tpe1) => ($out: $tpe2) } => Expr(out.toString)
}
```
E.g. when matching the following expression:
```
mac((x: String) => "anything")
```

The compiler hangs forever. It does not seem to be doing anything.

## Expectation
The expression should match and compile property.

## Code Sample
Code sample is available here:
https://github.com/deusaquilus/arrow_forever_bug

**Comment by nicolasstucki** [comment]
You should be using `inline` parameters rather than `underlyingArgument`.

**Comment by nicolasstucki** [comment]
Minimized to

```scala
import scala.quoted._

object Macro {
  inline def mac(): String = ${ macImpl() }
  def macImpl()(using qctx: QuoteContext): Expr[String] =
    '{(x: String) => "anything"} match
      case '{ (in: String) => ($out: $tpe2) } => Expr(out.toString)
      case _ => ???

}
import scala.quoted._

object Macro {
  inline def mac(): String = ${ macImpl() }
  def macImpl()(using qctx: QuoteContext): Expr[String] =
    '{(x: String) => "anything"} match
      case '{ (in: String) => ($out: $tpe2) } => Expr(out.toString)
      case _ => ???

}
```

```scala
import Macro._

@main def testOtherstuff() = { // hello
  mac()
}

```

**Comment by nicolasstucki** [comment]
Some side notes to improve the code
* `import qctx.tasty.{given _, _}` now can be `import qctx.tasty._`
* Use `inline` parameters instead of `underlyingArgument `

**Comment by deusaquilus** [comment]
> You should be using `inline` parameters rather than `underlyingArgument`.

@nicolasstucki Like I mentioned before, we really, really, need to use `underlyingArgument` to get rid of the `Inline` nodes for the sake of our parser. I think many other macro framework authors will come to the same conclusion when they start writing complex pattern-matching code on tasty-reflect trees.
