### ISSUE TITLE
Allow synthetic "default"methods to violate variance requirements

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#875]
This compiles with scala2 but not dotty:
```scala
class Foo[+A] {
  def foo(a: A => Int = _ => 1): Unit = ()
}
```
The issue is that after desugaring we get:
```scala
package <empty> {
  class Foo[+A] extends scala.AnyRef {
    def <init>(): Foo[A] = {
      Foo.super.<init>();
      ()
    };
    def foo(a: A => Int = ((x$1: A) => 1)): Unit = ();
    <synthetic> def foo$default$1: A => Int = ((x$1: A) => 1)
  }
}
```
So `foo$default$1` violates the variance requirements:
```scala
error: covariant type Foo$$A occurs in contravariant position in type => Foo$$A => Int of method foo$default$1
```
But since the user is not supposed to call default methods and since they're just an implementation detail, I think we should allow them to break these requirements.
Seen in the wild at https://github.com/molecule-labs/molecule/blob/master/molecule-core/src/main/scala/molecule/stream/IChan.scala#L152

**Comment by odersky** [comment]
Have a look at neg/variances.scala. It shows why we need to check default methods after all. scalac compiles the file and the code dies with a ClassCastException.
