### ISSUE TITLE
Parent{M[T] = CC[T]} is not a class type

### ISSUE THREAD

**Issue by letalvoj** [lampepfl/dotty#8759]
## Minimized code

```scala
case class CC[T](t:T, i:Int)

trait Parent{ type M[_] }
trait ChildTrait[T[_]] extends Parent { type M = T } 
type  ChildType[T[_]] = Parent { type M = T }

given ChildTrait[CC]{ } // compiles
given ChildType[CC]{ } // fails
```

## Output

```scala
31 |  given ChildType[CC]{ }
   |        ^^^^^^^^^^^^^
   |        Parent{M[T] = CC[T]} is not a class type
```
## Expectation
I'd hope that both statements should compile, allowing `given` definitions of `Parent { ... } `.

## Question
If I am mistaken and there is some major semantical difference in the two cases which prohibits the compiler to be written a way that provides `ChildType[CC]` please tell me why. Thx.

**Comment by letalvoj** [comment]
I acutally sumbled upon this while messing around `Mirror` implementation, which is actually able to provide such `given` instance, since it is a special case in the compiler itself.

https://github.com/lampepfl/dotty/blob/fe03ee22f107a745dd3a25b4e5bbd35856188206/library/src/scala/deriving.scala#L51-L53

https://github.com/lampepfl/dotty/blob/3d26c53f65d6967cc368f16a7899947d593cf08e/compiler/src/dotty/tools/dotc/typer/Synthesizer.scala#L379-L388

**Comment by letalvoj** [comment]
Close pls  🙏explained to me on Gitter. Thx @Blaisorblade

**Comment by Blaisorblade** [comment]
Welcome! FWIW my reply is on https://gitter.im/lampepfl/dotty?at=5e9ed37aa1284c4f20ab001d.

I think what happens (here and elsewhere) is that givens sometimes give errors in terms of their desugaring, which are obscure to users.

Anyway, I'm fine with closing for now.
