### ISSUE TITLE
Semanticdb source-like representation of top level definitions

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#8760]
## Minimized example

```Scala
// toplevel.scala
package foo

def bar: Int = 0
```

## Output

```scala
// generated symbol
foo/toplevel$package.bar().
```

## Expectation

```scala
// generated symbol
foo/bar().
```

Tooling that consumes semanticdb can deal with collisions from multiple files without requiring the package object prefix.

Additionally, the package object should not appear in semanticdb except if we support the synthetic section

**Comment by bishabosha** [comment]
@tgodzik

**Comment by bishabosha** [comment]
@olafurpg @tgodzik if this were done, would overloads need to be tracked across files, or is it fine for each file to have its own overload index?

**Comment by olafurpg** [comment]
It's important that global symbols are unique across source files. We want to avoid the following scenario
```scala
//toplevel1.scala
package bar
def foo = 42         // bar/foo().
//toplevel2.scala
package bar
def foo(n: Int) = n  // bar/foo().
```

It's only OK for local symbols to have conflicts across files. Can you elaborate on the problem with the current scheme?

**Comment by bishabosha** [comment]
it appears that currently, dotty disallows overloads across files

**Comment by bishabosha** [comment]
The problem was only of aesthetics, due to `toplevel$package` not appearing in source code

**Comment by bishabosha** [comment]
The issue that prompted this is really how to link a `@main` def with the generated jvm level main method, so I will close in favour of that
