### ISSUE TITLE
There is something special about how Mirror instances handle inner types

### ISSUE THREAD

**Issue by letalvoj** [lampepfl/dotty#8775]
I tried to mimic the `Mirror` behaviour inlining everything and I am not still getting the results I'd expect. 

## Minimized code

```Scala
import scala.reflect.ClassTag, scala.deriving._, scala.compiletime._

trait MyMirror
object MyMirror:
  type Of[T<:Tuple] = MyMirror { type MirroredElemTypes <: Tuple }
  inline given myMirror[T<:Tuple] as MyMirror.Of[T] = new MyMirror{ type MirroredElemTypes = T }

object Test:
  inline def tupleClasses[T<:Tuple]:List[_] = inline erasedValue[T] match
    case _: (t *: ts) => summonInline[ClassTag[t]] :: tupleClasses[ts]
    case _:Unit => Nil

  inline def builtin[T<:Tuple](using m: Mirror.Of[T]) = println(tupleClasses[m.MirroredElemTypes])
  inline def recreat[T<:Tuple](using m: MyMirror.Of[T]) = println(tupleClasses[m.MirroredElemTypes])

  def main(args: Array[String]): Unit =
    builtin[(Int,String)]
    recreat[(Int,String)]
```

## Output

```scala
18 |    recreat[(Int,String)]
   |    ^^^^^^^^^^^^^^^^^^^^^
   |cannot reduce inline match with
   | scrutinee:  scala.compiletime.erasedValue[m.MirroredElemTypes] : m.MirroredElemTypes
   | patterns :  case _:*:[t @ _, ts @ _]
   |             case _:Unit
   | This location contains code that was inlined from lol.scala:9
   | This location contains code that was inlined from lol.scala:14
```

or if the `Unit` type gets ommitted from the last `case _:Unit => Nil` then

```
List(Int, java.lang.String)
List()
```

## Expectation
```scala
List(Int, java.lang.String)
List(Int, java.lang.String)
```

## Additional info
https://gitter.im/lampepfl/dotty?at=5ea06b33989acc6ab7a8a4cb

**Comment by smarter** [comment]
@milessabin: do you have any insight here?

**Comment by milessabin** [comment]
Sorry, afraid not.

My gut feeling would be that in the `MyMirror` case a refinement is being lost somewhere, but I can't see anything obvious.

**Comment by neko-kai** [comment]
@letalvoj
There's a typo
```scala
object MyMirror:
  type Of[T<:Tuple] = MyMirror { type MirroredElemTypes <: Tuple }
```
This looks like it should be 
```scala
object MyMirror:
  type Of[T<:Tuple] = MyMirror { type MirroredElemTypes <: T }
```
Maybe that's the problem?

**Comment by letalvoj** [comment]
Not a typo. That is how it is defined in `Mirror`. `MirroredElemTypes` can not be `<: T` in general, only if `T` is itself a `Tuple`. I added there the `[T<:Tuple]` while minimizing the example.

https://github.com/lampepfl/dotty/blob/fe03ee22f107a745dd3a25b4e5bbd35856188206/library/src/scala/deriving.scala#L51-L53

**Comment by neko-kai** [comment]
@letalvoj But the right hand side should refer to `T` otherwise the type of T is lost outside. Maybe the alias should be:

```scala
type Of[T <: Tuple] = MyMirror { type MirroredElemTypes = T }
```

**Comment by letalvoj** [comment]
@neko-kai if you check out the `scala.deriving.Mirror` implementation, which I quoted in the previous comment, you can see that it is also defined as.

```scala
Mirror { ... type MirroredElemTypes <: Tuple } 
```

Moreover, there is no way for the right hand side to depend on `T` since it has to be a `Tuple`, like `(String, Int)` for `case class SI(s:String, i:Int)`.

**Comment by neko-kai** [comment]
@letalvoj 

https://scastie.scala-lang.org/q1Ij55QMRhOvTsCFxIYbgg

```scala
import scala.reflect.ClassTag, scala.deriving._, scala.compiletime._

trait MyMirror { type MirroredElemTypes <: Tuple }
object MyMirror:
  type Of[T<:Tuple] = MyMirror { type MirroredElemTypes = T }
  inline given myMirror[T<:Tuple] as MyMirror.Of[T] = new MyMirror{ type MirroredElemTypes = T }

object Test:
  inline def tupleClasses[T<:Tuple]:List[_] = inline erasedValue[T] match
    case _: (t *: ts) => summonInline[ClassTag[t]] :: tupleClasses[ts]
    case _:Unit => Nil

  inline def builtin[T<:Tuple](using m: Mirror.Of[T]) = println(tupleClasses[m.MirroredElemTypes])
  inline def recreat[T<:Tuple](using m: MyMirror.Of[T]) = println(tupleClasses[m.MirroredElemTypes])

  def main(args: Array[String]): Unit =
    builtin[(Int,String)]
    recreat[(Int,String)]
```

This compiles and outputs:

```
List(Int, java.lang.String)
List(Int, java.lang.String)
```

Seems like the problem was with your example

**Comment by letalvoj** [comment]
Yes it compiles. No it _does not follow the definition of `Mirror`_ in the dotty core library. Please just see the following line.

https://github.com/lampepfl/dotty/blob/fe03ee22f107a745dd3a25b4e5bbd35856188206/library/src/scala/deriving.scala#L51

**Comment by neko-kai** [comment]
@letalvoj Right, sorry. The gist of the issue is still in the type of the given instance i think; the Mirror synthesized by the compiler does not have the type `Mirror.Of[T]`, it has the precise type of the generated expression. However, I **couldn't** replicate the same whitebox-ity with a transparent inline:

```scala
object MyMirror:
  type Of[T<:Tuple] = MyMirror { type MirroredMonoType = T; type MirroredElemTypes <: Tuple }
  transparent inline given myMirror[T<:Tuple] as MyMirror.Of[T] = new MyMirror {
    type MirroredMonoType = T 
    type MirroredElemTypes = T
  }
```

The match was still failing with a transparent instance (/cc @milessabin again)

I could make it work by fully annotating the given type AND including the `type MirroredMonoType = T` in the refinement as well. Without it the match was still not reducing:

```scala
trait MyMirror
object MyMirror:
  type Of[T<:Tuple] = MyMirror { type MirroredMonoType = T; type MirroredElemTypes <: Tuple }
  inline given myMirror[T<:Tuple] as (MyMirror { type MirroredMonoType = T; type MirroredElemTypes = T }) = new MyMirror {
    type MirroredMonoType = T 
    type MirroredElemTypes = T
  }
```

scastie: https://scastie.scala-lang.org/dimIaUotRiqN5oUw4uidmQ

**Comment by milessabin** [comment]
@neko-kai there's nothing special about `Mirror` types in this respect.

Given that you can make this work with the explicit refinement does that suggest that there might be an issue with `transparent inline` for types of this form?

**Comment by neko-kai** [comment]
@milessabin It does suggest that something's not right with path-dependency on transparent inlines, I'm fairly sure the same will work fine with Scala 2's whitebox implicit macros.
