### ISSUE TITLE
Do not maximize unconstrained tvars which appear only contravariantly in implicit parameter types

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#878]
Currently, the rules for instantiation are (from https://github.com/lampepfl/dotty/blob/c1facd5c40fa7208d7549e6727e6e7498d4d3f34/src/dotty/tools/dotc/typer/Inferencing.scala#L54):

``` scala
   *   1. T is minimized if the constraint over T is only from below (i.e.
   *      constrained lower bound != given lower bound and
   *      constrained upper bound == given upper bound).
   *   2. T is maximized if the constraint over T is only from above (i.e.
   *      constrained upper bound != given upper bound and
   *      constrained lower bound == given lower bound).
   *  If (1) and (2) do not apply:
   *   3. T is maximized if it appears only contravariantly in the given type.
   *   4. T is minimized in all other cases.
```

This is not enough to get some innocent-looking code to compile, consider:

``` scala
class X

class Message[-A]
class Seg[+A]
class IChan[A] {
  def add[B >: A](x: Seg[B])(implicit ev: Message[B]): IChan[B] = ???
}

class Test {
  def test: Unit = {
    implicit val mx: Message[X] = ???
    val fx: IChan[X] = ???
    val sx: Seg[X] = ???
    fx.add(sx)
  }
}
```

(minimized from https://github.com/molecule-labs/molecule/blob/master/molecule-core/src/main/scala/molecule/stream/ichan/immutable/SpanT.scala#L60)

The implicit parameter to `fx.add(sx)` is not found because `B` is instantiated to `Any` instead of `X`, this happens because `B` is not constrained by `sx` (so case 2 does not apply) and `B` only appear contravariantly in `Message[B]` (so case 3 applies). I think that when instantiating tvars before doing an implicit search, it makes sense to ignore case 3 and minimize them.

@odersky : What do you think?

**Comment by odersky** [comment]
I think we should try to do this. But when doing this we should probably
also change the comparison function on implicits so that smaller always
wins independent of variance. I have a branch somewhere that does this;
have to dig it out.



On Tue, Oct 27, 2015 at 9:09 PM, Guillaume Martres <notifications@github.com
> wrote:

> Currently, the rules for instantiation are (from
> https://github.com/lampepfl/dotty/blob/c1facd5c40fa7208d7549e6727e6e7498d4d3f34/src/dotty/tools/dotc/typer/Inferencing.scala#L54
> ):
>
>    *   1. T is minimized if the constraint over T is only from below (i.e.
>    *      constrained lower bound != given lower bound and
>    *      constrained upper bound == given upper bound).
>    *   2. T is maximized if the constraint over T is only from above (i.e.
>    *      constrained upper bound != given upper bound and
>    *      constrained lower bound == given lower bound).
>    *  If (1) and (2) do not apply:
>    *   3. T is maximized if it appears only contravariantly in the given type.
>    *   4. T is minimized in all other cases.
>
> This is not enough to get some innocent-looking code to compile, consider:
>
> class X
> class Message[-A]class Seg[+A]class IChan[A] {
>   def add[B >: A](x: Seg[B])(implicit ev: Message[B]): IChan[B] = ???
> }
> class Test {
>   def test: Unit = {
>     implicit val mx: Message[X] = ???
>     val fx: IChan[X] = ???
>     val sx: Seg[X] = ???
>     fx.add(sx)
>   }
> }
>
> (minimized from
> https://github.com/molecule-labs/molecule/blob/master/molecule-core/src/main/scala/molecule/stream/ichan/immutable/SpanT.scala#L60
> )
>
> The implicit parameter to fx.add(sx) is not found because B is
> instantiated to Any instead of X, this happens because B is not
> constrained by sx (so case 2 does not apply) and B only appear
> contravariantly in Message[B] (so case 3 applies). I think that when
> instantiating tvars before doing an implicit search, it makes sense to
> ignore case 3 and minimize them.
>
> @odersky <https://github.com/odersky> : What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/878>.
>



-- 
Martin Odersky
EPFL

**Comment by smarter** [comment]
> I have a branch somewhere that does this; have to dig it out.

Did you find this branch? I'd be interested in fixing this to get more Scala code to compile.

**Comment by odersky** [comment]
I did not find the branch. I am preparing a PR which will just do the variable interpolation.

**Comment by odersky** [comment]
This seems to be fixed by now. i878.scala is a test case in pos.
