### ISSUE TITLE
Recursive macro looses elements in a constructed tuple

### ISSUE THREAD

**Issue by letalvoj** [lampepfl/dotty#8780]
Related to https://github.com/lampepfl/dotty/issues/8779, as pointed out by further exploration by @Blaisorblade

## Minimized code

```Scala
import scala.compiletime._, scala.annotation.tailrec, scala.deriving.productElement

@tailrec inline def mapRec[T <: Tuple, A, B](p:Product)(i:Int)(f: A => B) <: Tuple = inline erasedValue[T] match
  case _: (A *: tt) => (f(productElement[A](p,i)) *: mapRec[tt,A,B](p)(i+1)(f)).asInstanceOf[tt]
  case _: (t *: tt) => (productElement[t](p,i) *: mapRec[tt,A,B](p)(i+1)(f)).asInstanceOf[tt]
  case _: Unit => () : Unit

mapRec[(Int, Int, String),Int,String]((1,2,"lol"))(0)(_.toString)                                                                                                                                                      
```

## Output

```scala
val res4: (Int, String) = (1,2)
```

## Expectation
It should fail, since the tail of type `(String,String)` is being casted to `(Int,String)`.

**Comment by odersky** [comment]
That's just a cast from Tuple2 to Tuple2 which succeeds at runtime

**Comment by Blaisorblade** [comment]
Why does dropping the casts change the return value? That was part of the intended bug report.

```scala
scala> @tailrec inline def mapRec[T <: Tuple, A, B](p:Product)(i:Int)(f: A => B) <: Tuple = inline erasedValue[T] match
     |   case _: (A *: tt) => (f(productElement[A](p,i)) *: mapRec[tt,A,B](p)(i+1)(f))
     |   case _: (t *: tt) => (productElement[t](p,i) *: mapRec[tt,A,B](p)(i+1)(f))
     |   case _: Unit => () : Unit
def mapRec[T <: Tuple, A, B](p: Product)(i: Int)(f: A => B): Tuple

scala> mapRec[(Int, Int, String),Int,String]((1,2,"lol"))(0)(_.toString)
val res0: String *: Tuple = (1,2,lol)
```

**Comment by odersky** [comment]
I don't know and don't have the time to look into it, but I would guess it's a consequence of #8739. If you can rule this out and find a different specific problem, then please re-open. But as it stand I do not see anyone taking this up, and in that case it's better to leave it closed.

**Comment by letalvoj** [comment]
@Blaisorblade oh I overlooked a bracket. You were casting `(t *: tt)` to `tt`. I thought that it was just the updated tail.

So the issue in this case is that the last element `t *: Unit` was _ereased_ by casting it to `Unit`. Which is a valid behaviour, right? So this issue is closed correctly.

**Comment by Blaisorblade** [comment]
🤦 okay, that'll teach me to hurry, sorry everybody; I was trying to do something else first. The fixed code indeed works correctly.

```
scala> @tailrec inline def mapRec[T <: Tuple, A, B](p:Product)(i:Int)(f: A => B) <: Tuple = inline erasedValue[T] match
     |   case _: (A *: tt) => f(productElement[A](p,i)) *: mapRec[tt,A,B](p)(i+1)(f).asInstanceOf[tt]
     |   case _: (t *: tt) => productElement[t](p,i) *: mapRec[tt,A,B](p)(i+1)(f).asInstanceOf[tt]
     |   case _: Unit => () : Unit
def mapRec[T <: Tuple, A, B](p: Product)(i: Int)(f: A => B): Tuple

scala> mapRec[(Int, Int, String),Int,String]((1,2,"lol"))(0)(_.toString)
val res0: String *: Tuple = (1,2,lol)
```
