### ISSUE TITLE
Support discovery of generated `@main` method from SemanticDB

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#8790]
## Minimized example

Aim is to better support in Metals discovery of main methods for code lenses.

```Scala
// foo.scala
package example

@main def add(x: Int, y: Int): Unit = println(s"$x + $y = ${x + y}")
```

## Output

```scala
// metap foo.semanticdb
...
example/foo$package.add(). => method add
...
```

## Expectation

```scala
// metap foo.semanticdb
...
example/foo$package.add(). => @main method add
...
```

if a semanticdb method is annotated with `@scala.main` then following the present rules and invariants, it is a simple map back to `Class.forName("example.add").getMethod("main")` to find the generated main method

**Comment by bishabosha** [comment]
@tgodzik

**Comment by smarter** [comment]
I don't get it, why is `@scala.main` special ? There might be other macros that generate main methods. Semantically, all the information should already be there: we have a synthetic main method whose position is a subset of some user-defined method.

**Comment by bishabosha** [comment]
so what it looks like currently, is that running a scan for main methods on the position of the def gives the class symbol `example/add#`. Looking at the other symbols, the position of the method the user wrote, `example/foo$package.add().`, is actually after `example/foo#` and not within it

**Comment by tgodzik** [comment]
So the current situation is this:
1. When code is compiled via Bloop it gives us a list of the main classes and test classes that it detected.
2. We get a string like `foo/mainMethod`
3. Currently when @main annotation is used it generates a bunch of occurrences and definitions:
```scala
 Vector(
  SymbolOccurrence(Some(Range(0, 8, 0, 11)), "foo/", DEFINITION),
  SymbolOccurrence(Some(Range(2, 0, 2, 11)), "foo/Foo$package.", DEFINITION),
  SymbolOccurrence(Some(Range(2, 1, 2, 5)), "scala/main#", REFERENCE),
  SymbolOccurrence(Some(Range(2, 10, 2, 20)), "foo/Foo$package.mainMethod().", DEFINITION),
  SymbolOccurrence(Some(Range(2, 24, 2, 28)), "scala/Unit#", REFERENCE),
  SymbolOccurrence(Some(Range(3, 2, 3, 9)), "scala/Predef.println(+1).", REFERENCE),
  SymbolOccurrence(Some(Range(2, 0, 2, 10)), "foo/mainMethod#", DEFINITION),
  SymbolOccurrence(Some(Range(2, 0, 2, 0)), "foo/mainMethod#`<init>`().", DEFINITION),
  SymbolOccurrence(Some(Range(2, 0, 2, 0)), "foo/Foo$package.mainMethod().", REFERENCE),
  SymbolOccurrence(Some(Range(2, 0, 2, 0)), "scala/util/CommandLineParser.showError().", REFERENCE),
  SymbolOccurrence(Some(Range(2, 0, 2, 0)), "local0", REFERENCE)
)
```
4. I decided to check for class, hence using `mainMethod#` 

This works ok, but semanticDB should ideally represent a the code as is. A lot of the things here are generated and do not exist in the code itself. Most likely they should be in the synthetics section. And actual occurences we should have would be:
```scala
 Vector(
  SymbolOccurrence(Some(Range(0, 8, 0, 11)), "foo/", DEFINITION),
  SymbolOccurrence(Some(Range(2, 1, 2, 5)), "scala/main#", REFERENCE),
  SymbolOccurrence(Some(Range(2, 10, 2, 20)), "foo/mainMethod().", DEFINITION),
  SymbolOccurrence(Some(Range(2, 24, 2, 28)), "scala/Unit#", REFERENCE),
  SymbolOccurrence(Some(Range(3, 2, 3, 9)), "scala/Predef.println(+1).", REFERENCE),
  SymbolOccurrence(Some(Range(2, 0, 2, 0)), "local0", REFERENCE)
)
```
Code lenses would not work in this case. To solve it we could use main class if it were in the sythetics section or we could find `mainMethod()` that has annotations. We're still checking if it's possible to put class trees inside the sythetics section.

This is not super important, but it would be good to standardize both the representation of outer methods and main annotated methods in the SemanticDB

**Comment by tgodzik** [comment]
Actually coming to think of it we should make sure that no synthetic occurrences make it to occurrences - when looking for reference we might sometime look for something that doesn't exists and overlaps with a real existing symbol. This might be more important in that case.

**Comment by bishabosha** [comment]
so all you get from bloop is the class name `foo/mainMethod`, and then you need to reverse map that to a symbol and a position, or do you get a position as well?

**Comment by tgodzik** [comment]
> so all you get from bloop is the class name `foo/mainMethod`, and then you need to reverse map that to a symbol and a position, or are you given a position as well?

No position, just the class name.

**Comment by bishabosha** [comment]
this just sounds like an expensive search will always be necessary, e.g.

```scala
package example

@main def add(x: Int, y: Int): Unit = println(s"$x + $y = ${x + y}")

object foo {
  @main def add2(x: Int, y: Int): Unit = println(s"$x + $y = ${x + y}")
}
```

generates (abbreviated)

```
Symbols:
example/add# => final class add
example/add#main(). => static method main
example/add2# => final class add2
example/add2#main(). => static method main
example/foo$package. => final package object example
example/foo$package.add(). => method add
example/foo. => final object foo
example/foo.add2(). => method add2

Occurrences:
[3:0..3:11): @main def a <- example/foo$package.
[3:0..3:3): @ma <- example/add#
[3:0..3:0): -> example/foo$package.add().
[3:10..3:13): add <- example/foo$package.add().
[5:7..5:10): foo <- example/foo.
[7:2..7:6): @mai <- example/add2#
[7:2..7:2): -> example/foo.add2().
[7:12..7:16): add2 <- example/foo.add2().
```

here the main methods are in classes `foo/add` and `foo/add2`, but you must search through all objects to find the first method that matches each: `example/foo$package.add().` and `example/foo.add2().`

**Comment by tgodzik** [comment]
The biggest problem here is that we are generating overlapping symbols and while reading semanticDB it's a major issue, since we do have a lot of logic that calculates a symbol from the occurences inside a semanticDB files.

If the cursor is at 3:10 we will find `example/foo$package.`, but at 3:12 it is ` example/foo$package.add().`, which mean that for example when finding references we will look for one symbol or the other based on where in `add` the cursor will be located.

That's why I would rather remove those symbol occurences and search by annotation. We can do it by some other heuristic if needed. Just using the annotation seemed like a plausible solution. We don't really have to generate code lenses for every macro out there. They can still run via json configuration.

**Comment by tgodzik** [comment]
Or alternatively we could have all the generated symbol occurences at `2:0..2:0`, which would basically mean that they are in that line, but not at any real position.

**Comment by tgodzik** [comment]
It is working currently, although I don't think it's a solution we would want to stick with. I am basing everything on the fact that an additional class occurrence is being generated for @main annotated methods. In reality semanticdb should not contain anything that is no really in the code. The additional generated class should most likely be in the synthetic section.

But, for now I would stay with this approach, as fixing all this will require time.

**Comment by tgodzik** [comment]
In the most recent versions we switched to discovering the main annotation, which seems to work well. Closing this one.
