### ISSUE TITLE
Context functions have inconsistent import magic

### ISSUE THREAD

**Issue by acdenhartog** [lampepfl/dotty#8807]
## Code

```Scala
  class BeeKeeper(h:Hive) {
    def feedTheBees:Unit = { h }
    def (shadow:Hive) feedTheBeesExt:Unit = { h }
  }
  class Hive {
    def beeKeeping[T](f: BeeKeeper ?=> T):T = {
      given bk as BeeKeeper = new BeeKeeper(this)
      f.apply
    }
  }

  val h = new Hive()
  
  h.beeKeeping { bk ?=> import bk._
    h.feedTheBeesExt
    feedTheBees        //everything works as expected
  }

//h.feedTheBeesExt //as required this does not compile
//feedTheBees     //ditto obviously
  
  h.beeKeeping(h.feedTheBeesExt) //this does compile
                                //so extension methods are imported
  h.beeKeeping(feedTheBees)    //but this !!does not compile!!
```

## Output

`Error: Not Found: feedTheBees`

## Expectation

Both `feedTheBeesExt` and `feedTheBees` should be in scope.
If this is not a bug, why are extension methods scoped differently?

## Why this happens

Extension methods are scoped differently in general, because they are implicits.
Context functions just make it obvious how arbitrary that is.

**Comment by odersky** [comment]
I believe the only possible solution is to _disable all imports of extension methods_. Extension methods would only be available if they are defined in an available object in the implicit scope. That's the right way to think about them. But are we prepared to go this far? This would be a different issue to raise.
