### ISSUE TITLE
Some tests are Locale dependent

### ISSUE THREAD

**Issue by radeusgd** [lampepfl/dotty#8809]
I have a default locale on my PC set to `pl_PL`, in this locale floating-point numbers are comma-separated instead of being dot-separated as in `en_US` locale.

At least one of the tests fails because of this, namely `tests/run-macros/f-interpolator-tests.scala`, because it relies on a check file generated on an `en_US` locale containing amongst others number `10.00`.

## Expectation
The tests should work on all locales (for example by forcing sbt to use the supported `en_US` locale) or at least emit a warning which locale is required for a correct test run.

**Comment by radeusgd** [comment]
Interestingly, I tried a quick workaround by running `export LANG=C` before launching sbt, and while in the REPL `Locale.getDefault()` returns `en_US`, the test (run by `dotty-bootstrapped/testCompilation f-interpolator`) still seems to be using my `pl_PL` locale.

**Comment by radeusgd** [comment]
The following patch fixes the issue:
```
diff --git a/compiler/test/dotty/tools/vulpix/RunnerOrchestration.scala b/compiler/test/dotty/tools/vulpix/RunnerOrchestration.scala
index bec8b83b4..779df71b7 100644
--- a/compiler/test/dotty/tools/vulpix/RunnerOrchestration.scala
+++ b/compiler/test/dotty/tools/vulpix/RunnerOrchestration.scala
@@ -159,7 +159,7 @@ trait RunnerOrchestration {
       val url = classOf[ChildJVMMain].getProtectionDomain.getCodeSource.getLocation
       val cp = Paths.get(url.toURI).toString + JFile.pathSeparator + Properties.scalaLibrary
       val javaBin = Paths.get(sys.props("java.home"), "bin", "java").toString
-      new ProcessBuilder(javaBin, "-Dfile.encoding=UTF-8", "-Xmx1g", "-cp", cp, "dotty.tools.vulpix.ChildJVMMain")
+      new ProcessBuilder(javaBin, "-Dfile.encoding=UTF-8", "-Duser.language=en", "-Duser.country=US", "-Xmx1g", "-cp", cp, "dotty.tools.vulpix.ChildJVMMain")
         .redirectErrorStream(true)
         .redirectInput(ProcessBuilder.Redirect.PIPE)
         .redirectOutput(ProcessBuilder.Redirect.PIPE)
```

I force the locale settings when spawning the JVM process that is executing the compiled tests before checking them with the checkfile.

**Comment by som-snytt** [comment]
The f-interpolator tests were updated on scala2 for this reason at some point.
