### ISSUE TITLE
links between companions are missing after pickling/unpickling

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#881]
`A_1.scala`:
```scala
class A
object A {
  implicit val theA: A = new A
}
```
`B_2.scala`:
```scala
class B {
  def getA(implicit a: A): A = a
  def test = {
    getA
  }
}
```
If you compile `A_1.scala`, then try to compile `B_2.scala`, it will fail because the implicit was not found, this happens because when we call `companionModule` on `A` in `collectCompanions`, we get back `NoSymbol`, because `COMPANION_MODULE_METHOD` is missing from `A`.
@DarkDimius : Should we pickle `COMPANION_MODULE_METHOD` and `COMPANION_CLASS_METHOD`, or should we recreate them after unpickling?

**Comment by DarkDimius** [comment]
> Should we pickle COMPANION_MODULE_METHOD and COMPANION_CLASS_METHOD, or should we recreate them after unpickling?

If they would be pickled, they shouldn't be upicked into trees.
I would say it's better to recreate them during unpickling, as the information available there should be enough.

**Comment by odersky** [comment]
I also think it's better to recreate.

**Comment by odersky** [comment]
I don't see @VladimirNik show up in the gitter
