### ISSUE TITLE
dotty.epfl.ch/docs has been accidentally reverted to 0.23

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#8831]
Currently, the version number at the top of http://dotty.epfl.ch/docs/ is "0.23.0". I guess what happened is that the website was overwritten when 0.23.0 was published.

**Comment by anatoliykmetyuk** [comment]
I've republished the website

**Comment by smarter** [comment]
We should keep this issue open until we've fixed the release publishing to not do this.

**Comment by smarter** [comment]
Reopening because the issue isn't fixed, when a release is published, the website is reverted to the state it was in the branch corresponding to that release, this fixes itself when the next nightly is published but that can take a while (especially if nightly builds are broken), and meanwhile people are confused: https://gitter.im/lampepfl/dotty?at=5f19033c9360cb1f46634284 https://gitter.im/lampepfl/dotty?at=5f193486273e723b7ffc325d
Ideally, the documentation for a particular release should go in a subdirectory, e.g. https://dotty.epfl.ch/docs/0.25.0/, but we could also live with just never publishing documentation for anything which is not on master.

**Comment by smarter** [comment]
@anatoliykmetyuk It seems that the fix could be as simple as removing the release_documentation task job and just relying on the nightly_documentation job in https://github.com/lampepfl/dotty/blob/master/.github/workflows/ci.yaml, but is there a reason we need the release_documentation job?
