### ISSUE TITLE
Inline val does not allow explicit type

### ISSUE THREAD

**Issue by edolgy** [lampepfl/dotty#8841]
```Scala
inline val log1 : Boolean = false // Fails with: type of inline must be a known value

inline val log2  = false // Works fine
```

May be there is a reason for this, but from usage prospective it is very confusing

**Comment by nicolasstucki** [comment]
Yes, there is a good reason for this. Inline values need a constant type because they are inlined by constant folding on literal constant types.

Previously we used `final val` for this purpose.
```scala
final val log1 : Boolean = false // Does not inline
final val log2  = false // Is inlined, equivalent to log3
final val log3: false = false // Is inlined
```

With inline vals we ensure that they can be inlined
```scala
inline val log1 : Boolean = false // error
inline val log2  = false // Is inlined, equivalent to log3
inline val log3: false = false // Is inlined
```

**Comment by edolgy** [comment]
From language prospective a type like "false.type" makes perfect sense, but from usage prospective it  does not

One would think of it as a Boolean, use it where Boolean is applicable.

Yes, the "true type" must be a constant expression, whatever it is, but the usage type might be more general-useful definition

Just an opinion, I am happy with either outcome

**Comment by nicolasstucki** [comment]
Now that we are aligning the inline vals with the inline def it might be possible to do so. Though we should carefully analyse if that would be sound in general, which seems to be the case.

Also, this would help us with some other usability issues. I will open another issue for this possible usability enhancement.

**Comment by nicolasstucki** [comment]
See #8850
