### ISSUE TITLE
Need not require @alpha Annotation, when it can be derived without conflict

### ISSUE THREAD

**Issue by edolgy** [lampepfl/dotty#8886]
I suggest not requiring @alpha Annotation, when an existing overridden method already annotated and there are no other conflicts

I design a library and want to globally use '_?' name ending to indicate Option
```Scala
  @alpha("codeOption") def code_? : Option[String]
```
For library design the annotation is not a problem, it is welcome.

But if the annotated methods have to be massively implemented by library users, the promising idea will fail

```Scala
import scala.annotation.alpha

trait Source:
  @alpha("codeOption") def code_? : Option[String]

// Current way
def getCode1: Source = new Source{ @alpha("codeOption") def code_? = Some("ABC") }

// Desired way, currently not possible
def getCode2: Source = new Source{ def code_? = Some("ABC") }
```

**Comment by TheElectronWill** [comment]
I’m closing this (see comments on the PR), but feel free to open an issue at [dotty-feature-requests](https://github.com/lampepfl/dotty-feature-requests/issues) to keep track of your suggestion for a future release 😃
