### ISSUE TITLE
Cannot Refer to Path Dependent Type inside of type-quote 

### ISSUE THREAD

**Issue by deusaquilus** [lampepfl/dotty#8887]
## Minimized code

Let's say we want to create a class with a PDT for example:
```scala
trait Context {
  type RowType
}
```
Then inside of a macro, I want to be able to use this PDT (i.e. `RowType`) inside of a type-quote 
```scala
val tpe = '[$context.RowType]
```
I would want to do this for many reasons... for example to summon an object with it:
```scala
val decodeOpt = Expr.summon(using '[Decoder[$context.RowType, T]])
```
Only it doesn't work...

## Output
The compiler fails with the following error:
```
[error] 34 |    val tpe = '[$context.RowType]
[error]    |                        ^
[error]    |                        ']' expected, but '.' found
```

## Expectation
The code should compile and run properly. Statements like `'[$foo.Bar]` should be possible.

## Code
A full code sample of this issue and a minimized version of my use-case is available here:
https://github.com/deusaquilus/pdt_typesummon

**Comment by deusaquilus** [comment]
FYI, I was using this functionality to implement Quill's `QueryMeta` functionality in a type-safe way. Going to look for workarounds.

**Comment by LPTK** [comment]
How would this work? `context` could be an arbitrary expression which is not a stable path, which would probably result in generating a program with an [illegal](https://github.com/lampepfl/dotty/issues/5374) type projection.

Maybe the macro API could provide a `Stable[T] <: Expr[T]` type for such use cases.

**Comment by odersky** [comment]
Could you do `'[${context.RowType}]` instead?

**Comment by nicolasstucki** [comment]
@deusaquilus could you provide a small self contained example that show from where you get the context in those cases?

**Comment by deusaquilus** [comment]
@nicolasstucki The attached code sums it up. I have removed everything extraneous.
https://github.com/deusaquilus/pdt_typesummon/blob/master/src/main/scala/bug/Macro.scala

The idea is:
1) Create a object with a type member used in internal implicit defs:
```scala
trait Context {
  type RowType
  implicit def stringDecoder: Decoder[RowType, String]
  def serve[T](decoder: Decoder[RowType, T]): T
}
```

2) Summon one of these implicit defs inside of a macro. Then pass it back into the object.
```scala
  val tpe = '[Decoder[$context.RowType, T]]
  val decoderExpr = 
    Expr.summon(using tpe) match {
      case Some(decoder) => decoder
      case None => qctx.throwError(s"Cannot find decoder for: ${tpe.show}")
    }
  
  '{ $context.serve[T]($decoderExpr) }
```
That's basically it!

**Comment by nicolasstucki** [comment]
@deusaquilus it looks like this can be encoded as
```scala
import scala.quoted._
import scala.quoted.matching._

trait Decoder[RowType, T] {
  def decode(row:RowType): T
}

trait Context {
  type RowType
  implicit def stringDecoder: Decoder[RowType, String]
  def serve[T](decoder: Decoder[RowType, T]): T
}

object Macro {

  inline def serveDecoder[T](context: Context): T = ${ serveDecoderImpl('context) }
  def serveDecoderImpl[T: Type, U: Type, C <: Context { type RowType = U }: Type](context: Expr[C])(using qctx: QuoteContext): Expr[T] = {
    import qctx.tasty._

    val tpe = '[Decoder[U, T]]
    val decoderExpr =
      Expr.summon(using tpe) match {
        case Some(decoder) => decoder
        case None => qctx.throwError(s"Cannot find decoder for: ${tpe.show}")
      }

    '{ $context.serve[T]($decoderExpr) }
  }
}
```

I have not tried to expand the macro.

**Comment by deusaquilus** [comment]
@nicolasstucki I'll give that a try. My context itself has parameters. Should I encode that like this?
```scala
def serveDecoderImpl[T: Type, U: Type, CN <: Naming, C <: Context[CN] { type RowType = U }: Type](context: Expr[C])(using qctx: QuoteContext): Expr[T]
```
Or like this?
```scala
def serveDecoderImpl[T: Type, U: Type, CN <: Naming, C <: Context[_] { type RowType = U }: Type](context: Expr[C[CN]])(using qctx: QuoteContext): Expr[T]
```

**Comment by nicolasstucki** [comment]
The first one looks better

**Comment by deusaquilus** [comment]
@nicolasstucki Actually this encoding does not work, even in the example code. This:
```scala
def serveDecoderImpl[T: Type, U: Type, C <: Context { type RowType = U }: Type](context: Expr[Context])(using qctx: QuoteContext): Expr[T] = {
```

Causes this:
```
[error] -- [E007] Type Mismatch Error: /home/alexander/git/dotty/pdt_typesummon/src/main/scala/bug/Macro.scala:29:26 
[error] 29 |    '{ $context.serve[T]($decoderExpr) }
[error]    |                          ^^^^^^^^^^^
[error]    |                Found:    (decoderExpr : quoted.Expr[bug.Decoder[U, T]])
[error]    |                Required: quoted.Expr[bug.Decoder[?1.RowType, T]]
```

That is because the compiler does not know that in the signature of the `serve` method, `context.RowType` is equal to `U`.

**Comment by deusaquilus** [comment]
I tried it out in a branch here:
https://github.com/deusaquilus/pdt_typesummon/tree/extract_encoding_not_working

**Comment by deusaquilus** [comment]
Whoops, I didn't do it right. Ignore my previous comments for a minute.

**Comment by deusaquilus** [comment]
@nicolasstucki Okay, so your example above does not actually work because you need the type T in order to know type of `T` to be able to summon a decoder.
```scala
[error] 20 |  println( serveDecoder[String](ctx) )
[error]    |           ^^^^^^^^^^^^^^^^^^^^^^^^^
[error]    |        Cannot find decoder for: bug.Decoder[ctx.RowType, scala.Nothing]
[error]    | This location contains code that was inlined from Test.scala:20
```
You can have a look at that here:
https://github.com/deusaquilus/pdt_typesummon/tree/decoder_type_is_nothing

**Comment by deusaquilus** [comment]
However, if I add a parameter to specify T as a specific type (e.g. via `Class[T]`), it will work:
This works:
```scala
inline def serveDecoder[T](context: Context, cls: Class[T]): T = ${ serveDecoderImpl('context, 'cls) }
def serveDecoderImpl[T: Type, U: Type, C <: Context { type RowType = U }: Type](context: Expr[C], cls: Expr[Class[T]])(using qctx: QuoteContext): Expr[T] = {
```
You can see it in this branch:
https://github.com/deusaquilus/pdt_typesummon/tree/working_with_inferred_types

**Comment by deusaquilus** [comment]
If I want to manually type the inline `serveDecoder` method how do I do that?
I tried this:
```scala
inline def serveDecoder[T](context: Context): T = ${ serveDecoderImpl[T, context.RowType, Context]('context) }
```
... and I get:
```scala
[error] -- [E057] Type Mismatch Error: /home/alexander/git/dotty/pdt_typesummon/src/main/scala/bug/Macro.scala:18:92 
[error] 18 |  inline def serveDecoder[T](context: Context): T = ${ serveDecoderImpl[T, context.RowType, Context]('context) }
[error]    |                                                                                            ^
[error]    |Type argument bug.Context does not conform to upper bound bug.Context{RowType = context.RowType}
```
I tried adding `Context { type RowType = context.RowType }` like this:
```scala
inline def serveDecoder[T](context: Context): T = ${ serveDecoderImpl[T, context.RowType, Context { type RowType = context.RowType }]('context) }
```
... but then this error happens:
```
[error] Cyclic macro dependencies in /home/alexander/git/dotty/pdt_typesummon/src/main/scala/bug/Test.scala.
[error] Compilation stopped since no further progress can be made.
```
Code here:
https://github.com/deusaquilus/pdt_typesummon/tree/manual_typing_not_working

**Comment by nicolasstucki** [comment]
That seems to be another bug. I will investigate it.

The context type parameter should probably be `context.type`.

**Comment by deusaquilus** [comment]
Just tried that. That causes this error:
```scala
[error] 21 |  inline def serveDecoder[T](context: Context): T = ${ serveDecoderImpl[T, context.RowType, context.type]('context) }
[error]    |                                                                                            ^^^^^^^
[error]    |                       access to value context from wrong staging level:
[error]    |                        - the definition is at level 0,
[error]    |                        - but the access is at level -1.
```

**Comment by nicolasstucki** [comment]
That should be allowed.

**Comment by nicolasstucki** [comment]
Minimized to

```scala
import scala.quoted._
inline def foo(x: Any): Any = ${ expr[x.type] }
def expr[X](using Quotes): Expr[Any] = ???
```

```
3 |inline def foo(x: Any): Any = ${ expr[x.type] }
  |                                      ^
  |                           access to parameter x from wrong staging level:
  |                            - the definition is at level 0,
  |                            - but the access is at level -1.
```
