### ISSUE TITLE
Boost binding precedence vs infix in patterns

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#8895]
This transfers https://github.com/scala/bug/issues/10821

Take
```
case head @ P(x) :: Nil =>
```
as
```
case (head @ P(x)) :: Nil =>
```
instead of as
```
case head @ (P(x) :: Nil) =>
```
by analogy to pattern alternatives
```
case matched @ (X | Y | Z) =>
```
Current usage suggests that parens are rarely omitted:
```
case alts @ (hd :: _) =>
case (t @ ValFrom(pat, rhs)) :: (rest @ (ValFrom(_, _) :: _)) =>
```
is written instead of currently legal
```
case alts @ hd :: _ =>
case (t @ ValFrom(pat, rhs)) :: (rest @ ValFrom(_, _) :: _) =>
```
which suggests that the current precedence is not natural or intuitive or easy to scan.

For reasons of compatibility and migration, this change would be enabled under `-strict` language rules for 3.1/3.2. Fully parenthesized patterns are not affected.

**Comment by odersky** [comment]
That should be a feature request instead. Can you send it there and close this one?

**Comment by som-snytt** [comment]
Resubmitted on dotty-feature-requests issue tracker, which TIL.

**Comment by som-snytt** [comment]
https://github.com/lampepfl/dotty-feature-requests/issues/120 was closed because they invented `as`.
