### ISSUE TITLE
No equivalency between context bounds and using

### ISSUE THREAD

**Issue by yilinwei** [lampepfl/dotty#8896]
## Minimized code

```Scala
trait Foo[A]

object Example {

  given as Foo[Int] {
  }

  def foo[A : Foo]: A => A = identity 

  def foo2[A](using Foo[A]): A => A = identity // this definition works!

  def test(): Unit = {
    foo(32) // fails to compile because it thinks `32` is an implicit parameter
  }

}

```

## Output

```scala
[error] 107 |    foo(32)
[error]     |        ^^
[error]     |        Found:    (32 : Int)
[error]     |        Required: profunctor.optics.core.Foo[A]
[error]     |
[error]     |        where:    A is a type variable
```

## Expectation

Both of these expressions should be equivalent ideally.

**Comment by odersky** [comment]
That's intentional. The doc page says:

> To ease migration, context bounds in Dotty map in Scala 3.0 to old-style implicit parameters
for which arguments can be passed either with a `(using ...)` clause or with a normal application. From Scala 3.1 on, they will map to context parameters instead, as is described above.

**Comment by nicolasstucki** [comment]
This only fails under language `3.0` as we need to creating Scala 2 semantics of implicits. Under `3.1` this works as expected.  See https://dotty.epfl.ch/docs/reference/contextual/context-bounds.html#migration

**Comment by nicolasstucki** [comment]
Regression test in #8911

**Comment by yilinwei** [comment]
Thank you! Apologies for raising the issue.
