### ISSUE TITLE
Extending class from scala stdlib without explicitly providing default argument fails

### ISSUE THREAD

**Issue by martijnhoekstra** [lampepfl/dotty#8920]
## Minimized code
```scala
class Q[A] extends scala.collection.mutable.Queue[A]
```

## Output

```scala
None of the overloaded alternatives of constructor Queue in class Queue with types
 [A](initialSize: Int): scala.collection.mutable.Queue[A]
 [A]
  (array: Array[AnyRef], start: Int, end: Int): 
    scala.collection.mutable.Queue[A]
match type arguments [A] and arguments ()
```

## Expectation

Compiles like in scala 2

`s.c.m.Queue[A]` has a constructor with a default argument (the one with initialSize). It looks like this default argument isn't picked up and used from the jar.

This doesn't happen with the base and derived class compiled in a single compilation unit in dotty. Untested whether it also happens if both are compiled by dotty in separate compilation units.

**Comment by odersky** [comment]
It does happen if they are compiled by dotty in separate compilation units. Investigating...
