### ISSUE TITLE
The reference ambiguous checking is too broad in dotty 0.24 

### ISSUE THREAD

**Issue by esse-byte** [lampepfl/dotty#8930]
## Minimized code

```Scala
class A(val i: Int)

def a(i: Int): A = new A(i) { println(i) }
```

## Output

```scala
Reference to i is ambiguous,
it is both defined in method a
and inherited subsequently in anonymous class A {...}
```

## Expectation

The code compiles in both dotty 0.23 and scala 2.3.1

**Comment by smarter** [comment]
The stricter checks are intentional: https://github.com/lampepfl/dotty/pull/8622, not sure if we could relax them in this particular case.

**Comment by odersky** [comment]
The only way to relax them would be to somehow detect that the parameter to `A` ends up as the initializer of the field `a`. But we could detect that only after type checking. So, I don't think that would be practical.

**Comment by som-snytt** [comment]
Even if the aliasing were detected, it's not obvious that the usage is intended without more explicit syntax.

This belongs to the class of "pass-thru" init, `class X(_) extends Y(_)`. Whatever the hypothetical syntax, "apply incoming params directly to a thing." (Without danger of alias.)

**Comment by som-snytt** [comment]
Fixing code in Scala 2 project, similar example with `tree`, which is assumed to mean the only possible tree under consideration. Hypothetical syntax `new C(tree' = tree)` to mean the arg must be aliased to member of that name, and refchecked.
