### ISSUE TITLE
Improve disjointness checking for abstract type in object?

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#8937]
Someone posted this on gitter:

```Scala
import scala.compiletime._

type Field[K <: String, +V]

type ISB = Field["i", Int] *: Field["s", String] *: Field["b", Boolean] *: Unit

object TypeFunctions:
  type Select[r <: Tuple, n <: String] = r match
    case Field[`n`, v] *: _ => v
    case h *: t             => Select[t, n]

import TypeFunctions._

object Proofs:
  summon[Select[ISB, "i"]  =:= Int] // OK
  summon[Select[ISB, "s"]  =:= String] // KO
```

The last line can be made to compile by replacing `type Field[K <: String, +V]` by `class Field[K <: String, +V]`, but since the abstract type is defined in an object, maybe this is enough to establish disjointness with the scrutinee and we could allow the original code to compile? I'm not sure.

**Comment by Blaisorblade** [comment]
As I wrote on Gitter: IMHO the compiler should not handle this — if you declare an abstract type in an object, the semantics should still treat it as abstract and make no assumption — in particular, modifying that declaration to type `Field[K <: String, +V] = Int` should keep everything compiling (this property is an instance of narrowing in the DOT papers).

**Comment by OlivierBlanvillain** [comment]
I would also find it surprising to give special meaning to abstract types inside objects...

**Comment by smarter** [comment]
OK, let's keep it as is then.
