### ISSUE TITLE
Need @postfix annotation

### ISSUE THREAD

**Issue by edolgy** [lampepfl/dotty#8965]
@infix annotation is an excellent feature bringing sense and order in which cases methods can be used as infix operations by default

Similar logic seems to be applicable to "postfix"

Truly, very few methods are naturally postfix applicable, but the ones which are natural, need this feature badly.

For example, lets consider a functional style printing facility like

```Scala
  @postfix def (x: Any) print = System.out.println(x.toString)

  "Foo" + "Bar" print;
  // vs.
  ("Foo" + "Bar").print
```
Few parenthesis are saved, making code clearer. 

This seems to be important while debugging and in documentation examples. But this will not fly if people need to explicitly enable "postfix" each time to run the example.

**Comment by SethTisue** [comment]
postfix is in the process of being removed from the language entirely; it only still exists at all as a concession to backwards compatibility

**Comment by edolgy** [comment]
Understood

I will have to learn to live without it
