### ISSUE TITLE
Type diff in tuples is wrongly colored

### ISSUE THREAD

**Issue by rethab** [lampepfl/dotty#8980]
When printing the below type diff, the closing square bracket is red, but it should not.
## Minimized code

```Scala
println(DiffUtil.mkColoredTypeDiff("(Foo, Seq[Bar])", "Seq[Bar]")._1)
```

## Output
![square-brakcet](https://user-images.githubusercontent.com/2222044/81858741-79be3c00-9564-11ea-8c01-df173d5c166e.png)

## Expectation
that square bracket should not be red, because it is part of expected parameter.

## Notes
I'd like to fix this (unless this turns out to be a duplicate). I noticed there are no tests for this function. Would it be ok to create some DiffUtil tests? Anything else to consider?

**Comment by nicolasstucki** [comment]
It would be great if we have tests for this. You should add the tests to `tests/run-with-compiler` and run them with `sbt dotty-bootstrapped/testCompilation tests/run-with-compiler`.

 It is all yours, thx.

**Comment by smarter** [comment]
> You should add the tests to tests/run-with-compiler and run them with sbt dotty-bootstrapped/testCompilation tests/run-with-compiler.

That's one way to do it, but we could also have simple JUnit unit tests in compiler/test that check that DiffUtil behaves appropriately.
