### ISSUE TITLE
@uncheckedVariance leaks into inferred types at use site

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#8988]
```scala
scala> List(1)
val res0: List[Int] = List(1)

scala> res0.tail
val res1: List[Int @uncheckedVariance] = List()
```

We could drop `@uncheckedVariance` in asSeenFrom but that breaks overrides which rely on the inferred type coming from the overridden definition containing the annotation, for example https://github.com/lampepfl/dotty/blob/9450bf2c9725c3616743e9617844e6c55c86c67a/tests/run/CollectionTests.scala#L168

Maybe we can drop them when inferring a result type (that does not come from overriding something), in the same way we drop skolems: https://github.com/lampepfl/dotty/blob/9450bf2c9725c3616743e9617844e6c55c86c67a/compiler/src/dotty/tools/dotc/typer/Namer.scala#L1463 but that doesn't help with chained expressions

**Comment by smarter** [comment]
Even more concerning:
```scala
scala> List(1,2,3)
val res3: List[Int] = List(1, 2, 3)

scala> res2.tail
val res4: List[Int @uncheckedVariance] = List(2, 3)

scala> res4.tail
val res5: List[Int @uncheckedVariance @uncheckedVariance] = List(3)

scala> res5.tail
val res6: List[Int @uncheckedVariance @uncheckedVariance @uncheckedVariance] = List()
```

**Comment by odersky** [comment]
Maybe @uncheckedVariance should be an annotation on symbols instead.

**Comment by joroKr21** [comment]
I recently learned in Scala 2 `@uncheckedVariance` can be used on any type to prevent the variance check from descending deeper. But it feels more natural to associate the annotation with the type parameter. But that would not be backwards compatible.

```scala
    def impl2[G[_, _]] = new UncheckedHKT {
      type F[+A, -B] = G[A, B] @uncheckedVariance
    }
```
