### ISSUE TITLE
given swallows inline errors

### ISSUE THREAD

**Issue by yilinwei** [lampepfl/dotty#9014]
## Minimized example

```Scala
trait Bar[T]

object Bar {

  import scala.quoted._

  inline given [T] as Bar[T] = ${ impl[T] }

  def impl[T](using qctx: QuoteContext, t: Type[T]): Expr[Bar[T]] = {
    import qctx.tasty._
    import util._

    t.unseal match {
      case _ =>
        qctx.error("Failed to expand!")
        '{ ??? }
    }
  }
}

object Foo {
  summon[Bar[String]]
}


```

## Output

```scala
ala:9:21                                                                            
[error] 9 |  summon[Bar[String]]
[error]   |                     ^
[error]   |no implicit argument of type pprint.Bar[String] was found for parameter x 
of method summon in object DottyPredef.                                             
[error]   |I found:
[error]   |
[error]   |    {
[error]   |      {
[error]   |        ???
[error]   |      }:pprint.Bar[String]
[error]   |    }
[error]   |
[error]   |But method given_Bar_T in object Bar does not match type pprint.Bar[String
].                                                                                  

```

## Expectation

Ideally, the macro expansion should show the `qctx.error`.

**Comment by yilinwei** [comment]
I would like to give this a go if at all possible?

I think the part which needs to be changed is [Implicits.scala](https://github.com/lampepfl/dotty/blob/38272aa21440fc39f893abab6c3d68c75be901e0/compiler/src/dotty/tools/dotc/typer/Implicits.scala#L970), where the error is dropped.

**Comment by nicolasstucki** [comment]
Minimized to
```scala
trait Bar[T]
inline given [T] as Bar[T] = compiletime.error("Failed to expand!")
val tests = summon[Bar[String]]
```

The issue is that when looking for implicits, if an error is reported then implicit disregard this implicit and tries to find another one.

This leads to some interaction between error reporting in the `Inliner` and implicit search. It is not clear what the behavior should be in such cases.

**Comment by yilinwei** [comment]
I see. Something I didn't quite understand is that the tree created by the macro appears in the error message (so I actually used that for debugging purposes). If there was another implicit it could try would that still be the case or does the implicit search just stop there?

**Comment by nicolasstucki** [comment]
Interesting. Then it looks like this issue is mostly about reporting. The first step should be to track and understand which reporter receives the macro error and which prints the actual error.

**Comment by nicolasstucki** [comment]
```scala
import scala.quoted._
trait Bar
inline given as Bar = ${ impl }
def impl(using qctx: QuoteContext): Expr[Bar] = qctx.throwError("Failed to expand!")
```
```scala
val tests = summon[Bar]
```
