### ISSUE TITLE
Allow soft keywords as case class parameters

### ISSUE THREAD

**Issue by Arthurm1** [lampepfl/dotty#9041]
I have code that uses case class parameters that are now soft keywords so it won't compile in Dotty.

Rather than refactor the names it would nice if soft keywords were allowed as case class parameters.

Currently these compile...
```Scala
case class Foo1(as: Double)
case class Foo2(derives: Double)
case class Foo3(end: Double)
case class Foo4(extension: Double)
case class Foo5(on: Double)
case class Foo6(* : Double)
case class Foo7(+ : Double)
case class Foo8(- : Double)
```
But these do not...
```Scala
case class Foo1(open: Double)
case class Foo2(using: Double)
case class Foo3(inline: Double)
case class Foo4(transparent: Double)
case class Foo5(opaque: Double)
```

**Comment by odersky** [comment]
The difference is that the second class are all modifiers. Modifiers can appear in parameter lists, so they are not available as normal identifiers in this situation. We could split this further into modifiers that are allowed for parameters (such as `inline` and `using`) and other modifiers, but I think that would be too much hair splitting.
