### ISSUE TITLE
class parameter wrongly treated as soft keyword 'inline'

### ISSUE THREAD

**Issue by kpbochenek** [lampepfl/dotty#9046]
Example from dotr built from master:
```scala
scala> class C(x: String)
// defined class C

scala> class C(inline: String)
1 |class C(inline: String)
  |              ^
  |              an identifier expected, but ':' found
```

inline as I understand is soft keyword only allowed in inlined methods, here it should be treated as normal identifier?

**Comment by nicolasstucki** [comment]
`inline` is also  allowed for parameters of inline methods

```scala
inline def pow(x: Double, inline n: Int) = ....
```
Not sure if parameters named inline this should be allowed.

**Comment by kpbochenek** [comment]
Yes, especially this works:
`inline def pow(x: Double, inline: Int) = ???`
which is totally inconsistent with `class C(inline: String)` not working.
