### ISSUE TITLE
Mirror.SumOf fails to summon in the context of multiple files

### ISSUE THREAD

**Issue by anatoliykmetyuk** [lampepfl/dotty#9069]
Test.scala:
```scala
def Test =
  summon[deriving.Mirror.SumOf[Foo]]
```

Wrapper.scala:
```scala
sealed trait Foo
case class Bar(x: Int) extends Foo
```

Compile together while specifying `Test.scala` first in the compiler command: `dotty-bootstrapped/dotc -d out Test.scala Wrapper.scala`.

Output:

```scala
-- Error: /Users/kmetiuk/Projects/scala3/playground/upickle-pg/Test.scala:2:36 -
2 |  summon[deriving.Mirror.SumOf[Foo]]
  |                                    ^
  |no implicit argument of type deriving.Mirror.SumOf[Foo] was found for parameter x of method summon in object DottyPredef
-- Error: /Users/kmetiuk/Projects/scala3/playground/upickle-pg/Wrapper.scala:2:11
2 |case class Bar(x: Int) extends Foo
  |           ^
  |children of trait Foo were already queried before class Bar was discovered.
  |As a remedy, you could move class Bar on the same nesting level as trait Foo.
2 errors found
```

If you flip the order of the files in the command (`dotty-bootstrapped/dotc -d out Wrapper.scala Test.scala`) or compile them as a single file:

```scala
sealed trait Foo
case class Bar(x: Int) extends Foo
def Test =
  summon[deriving.Mirror.SumOf[Foo]]
```

The compilation succeeds.

You can reproduce the issue with [Dotty Issues Workspace](https://github.com/anatoliykmetyuk/dotty-issue-workspace) using the following `launch.iss` script:

<details><summary>launch.iss</summary>

```bash
$ (rm -rv out || true) && mkdir out  # Cleanup

dotty-bootstrapped/dotc -d out
  $here/Test.scala $here/Wrapper.scala
```
</details>

/cc @milessabin

**Comment by smarter** [comment]
Same issue as https://github.com/lampepfl/dotty/issues/9064 ?

**Comment by anatoliykmetyuk** [comment]
Could be. I discovered it in upickle, and it also kept blowing up with `java.lang.OutOfMemoryError`.
