### ISSUE TITLE
Classes in `scala` package have 2 symbols when compiled by dotty

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#909]
```scala
# no sig for NoType
#  no sig for ErasedValueType(class RichShort,NoType)
#  no sig for TypeRef(TermRef(ThisType(TypeRef(NoPrefix,scala)),runtime),RichShort)
#  failure while taking result signture of (x: Short)runtime.RichShort: runtime.RichShort
#  cannot take signature of (x: Short)runtime.RichShort
#  exception occurred while typechecking ./scala-scala/src/library/scala/Array.scala
```

**Comment by odersky** [comment]
Looks like it could not compute the underlying type of a value type.

**Comment by smarter** [comment]
Can you give me the exact source file(s) needed to reproduce that? Trying to compile Array.scala from scalac here results in `exception while transforming classTag[Array[_ = Array[_ = Array[_ = T]]]'] of class class dotty.tools.dotc.ast.Trees$TypeApply # 7443`

**Comment by DarkDimius** [comment]
I'll make a PR soon that indicates those errors.

**Comment by smarter** [comment]
I tried uncommenting the lines starting with `./scala-scala/src/library/scala/runtime/Rich` in `test/dotc/scala-collections.whitelist` and the `compileStdLib` test still pass, I cannot fix this until you tell me how to reproduce it exactly.

**Comment by DarkDimius** [comment]
> I tried uncommenting the lines starting with ./scala-scala/src/library/scala/runtime/Rich in test/dotc/scala-collections.whitelist and the compileStdLib test still pass, I cannot fix this until you tell me how to reproduce it exactly.

Strange, it fails for me. If e13b181 is reverted I can steadily reproduce the bug locally.

could you please try 
```scala
dotc ./scala-scala/src/library/scala/Array.scala ./scala-scala/src/library/scala/runtime/RichShort.scala  ./scala-scala/src/library/scala/Short.scala
```

**Comment by smarter** [comment]
OK, can reproduce that way.

**Comment by smarter** [comment]
The shorter way to reproduce is to just try to compile `./scala-scala/src/library/scala/Short.scala`, this should **not** compile because it contains an abstract value class (it should issue an error and not crash, but the error checking is not done yet, see https://github.com/lampepfl/dotty/issues/826), apparently scalac contains hack to make `scala.Short` compile, it does not compile if you rename the class or the package in `Short.scala`.

**Comment by DarkDimius** [comment]
@smarter `isDerivedValueClass` has a test that should filter out primitive value classes.
Primitive value classes are allowed to be abstract and are not subject to value class transformation.

**Comment by DarkDimius** [comment]
If primitive classes are being compiled, we have 2 class symbols for them. One is loaded from classpath and the other is the one being compiled.

**Comment by DarkDimius** [comment]
This problem is quite deep.
Currently, even before checking the command line, we create an `InitialContext` and we `init` the definitions to synthesize `syntheticCoreClasses`. Those `syntheticCoreClasses` are entered into `scala` package and that forces reading of `scala` package from classpath, including `scala.Short`.

As suggested by @odersky, I've tried(https://github.com/lampepfl/dotty/commit/42282b84bf24004e18b98b107184516f37bc7901) not to enter those classes eagerly and enter them when `scala` package is forced instead. Unfortunately both synthesizing `RepeatedParamClass` class and `syntheticCoreMethods` already forces `scala`.

**Comment by DarkDimius** [comment]
fixed.
