### ISSUE TITLE
infix methods accept type parameters in multiple positions

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#9091]
http://dotty.epfl.ch/docs/reference/contextual/extension-methods.html says:
> If an extension method has type parameters, they come immediately after the def and are followed by the extended parameter. 

But in fact they're also accepted after the method name:

```Scala
scala> def (x: A) foo[A]: A = x
def foo[A](x: A): A

scala> def [A] (x: A) foo: A = x
def foo[A](x: A): A
```

@odersky: I assume this is a remnant of a previous syntax and not intentional?

**Comment by odersky** [comment]
yes indeed. We need to drop that syntax
