### ISSUE TITLE
scala.Byte & other primitives override getClass

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#910]
`getClass` is marked as a final method. Do we want to include a hack in compiler to allow to "compile" primitive classes in scala.*?

**Comment by odersky** [comment]
How does scalac do it?

**Comment by SethTisue** [comment]
> How does scalac do it?

https://github.com/scala/scala/blob/a24ca7fa617cabada82c43d2d6ac354db698d181/src/compiler/scala/tools/nsc/transform/Erasure.scala#L1026-L1042

**Comment by DarkDimius** [comment]
fixed.
