### ISSUE TITLE
Run Java 14 on our CI

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#9104]
Now that https://github.com/lampepfl/dotty/issues/8838 is fixed, we should be able to run Java 14. Since it tends to catch more things than Java 8 and 11 I propose dropping Java 11, making Java 14 the default, and keeping Java 8 only for merges/nightlies/releases (in particular published jars should always be produced using Java 8 to make sure no Java 9+ only dependency slips in).

**Comment by liufengyun** [comment]
This is partly done for #9181, but only on Java 11. We need to update the docker image to switch to Java 14.

- Due to #9500, we still need to run bootstrapped tests on Java 8
- Due to API compat (27f94f8), we need to run community projects on Java 8

**Comment by smarter** [comment]
We replaced Java 11 by 14 in https://github.com/lampepfl/dotty/pull/10135/commits/9dc145d51cb13fe681f4ee6f6562ba15d6eba17e
