### ISSUE TITLE
Should we allow polymorphic overloads with the same number of type parameters?

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#9109]
These two overloads are considered valid by Dotty, because their signatures are different:
```scala
class A {
  def foo[T <: Serializable](x: T): Unit = {}
  def foo[T <: Cloneable](x: T): Unit = {}
}
```
... but trying to override one of them fails, because refchecks uses `Types#matches` to find overrides which does not take signatures into account (it calls `TypeComparer#matchesType` which in turns does `matchesType(tp1.resultType, tp2.resultType.subst(tp2, tp1))`, therefore comparing `(x: T): Unit` to `(x: T): Unit`):
```scala
class B extends A {
  override def foo[T <: Serializable](x: T): Unit = {}
}
```
```scala
-- Error: try/B.scala:21:15 ----------------------------------------------------
21 |  override def foo[T <: Serializable](x: T): Unit = {}
   |               ^
   |  error overriding method foo in class A of type [T <: Cloneable](x: T): Unit;
   |    method foo of type [T <: Serializable](x: T): Unit has incompatible type
```

So the question is: should we disallow these overloads, or should we strive to support them? The answer is not clear cut to me because Scala 2 never supported them:
```scala
try/B.scala:16: error: method foo is defined twice;
  the conflicting method foo was defined at line 15:7
  def foo[S <: Cloneable](x: S): Unit = {}
      ^
```
... but Java does support them, so if we don't support them we're still in trouble when trying to override them (and in fact scala 2 cannot override them):
```java
public class A {
  public <T extends java.io.Serializable> void foo(T x) {}
  public <T extends Cloneable> void foo(T x) {}
}
```

I would be in favor of supporting them for better interoperability and because it doesn't seem too hard (require matching param signatures for Types#matches to bring it in line with Denotation#matches)

WDYT @odersky ?

**Comment by odersky** [comment]
I agree, it seems to be more useful and also more consistent to support them.

**Comment by bishabosha** [comment]
should a new issue for this be made in feature requests or here?

**Comment by smarter** [comment]
We should keep this open since the current situation is inconsistent (adding an overload can break overriding)

**Comment by smarter** [comment]
Thinking about this more, I'm not so sure anymore if we should allow this or not. I think it comes down to what we want to do with https://github.com/lampepfl/dotty/issues/8929:
```scala
class A {
  def foo[T <: Serializable](x: T): Unit = {}
}
class B extends A {
  override def foo[T](x: T): Unit = {}
}
```
These are valid overrides for scalac but not for dotty, that is: scalac allows not only covariant result type overriding but contravariant type parameter bounds overriding, dotty refuses them because their signatures are different. If we were to support this, then it would make sense to ban overloads with the same number of type parameters, because overriding relationships would become very confusing to figure out, both for the compiler and for users, who cannot rely on just counting the number of type parameters to see what overrides what.

**Comment by soronpo** [comment]
What happens if we mix `@alpha` into this?

**Comment by smarter** [comment]
It doesn't change anything, why would it? overrides must have matching uses of `@alpha`
