### ISSUE TITLE
Question about method '+=' on ArrayBuilder[Unit]

### ISSUE THREAD

**Issue by FabioPinheiro** [lampepfl/dotty#9132]
## Minimized example

```Scala
scala.collection.mutable.ArrayBuilder.make[Unit] += ()
```

## Output

Compiles on Scala 2.13.2 but not on Dotty
```scala
scala> scala.collection.mutable.ArrayBuilder.make[Unit] += ()                                                         
1 |scala.collection.mutable.ArrayBuilder.make[Unit] += ()
  |^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |None of the overloaded alternatives of method += in trait Growable with types
  | (elem1: Unit, elem2: Unit, elems: Unit*): 
  |  scala.collection.mutable.ArrayBuilder[Unit]
  | (elem: Unit): scala.collection.mutable.ArrayBuilder[Unit]
  |match arguments ()
```

## Expectation
Created this issue so we can officialize if this is the intended behavior or not. In order to see what to do on https://github.com/scala-js/scala-js/pull/4071

The discussion starts Gitter where @smarter and @sjrd participated
https://gitter.im/lampepfl/dotty?at=5ede17109da05a060a5b9b14

**Comment by smarter** [comment]
Scala 2 parses `a += ()` as `a.+=(())` whereas dotty parses it as `a.+=()`, is this intended @odersky ?

**Comment by som-snytt** [comment]
This ticket may be used to forward-port the improvement at https://github.com/scala/scala/pull/7684 which is in 2.13.0.

**Comment by FabioPinheiro** [comment]
The code `a += ()` is creating an ast Tree like `InfixOp(Ident(a),Ident(+=),Tuple(List()))`

After filling the Parsers.scala file with prints I added the line `case Nil => unitLiteral` before https://github.com/lampepfl/dotty/blob/3ea2841db764bef11871a168e8d669bdd68d5ee7/compiler/src/dotty/tools/dotc/ast/untpd.scala#L469

After this change the previous tree is replaced with  `InfixOp(Ident(b),Ident(+=),Parens(Literal(Constant(()))))`

I probably broke a lot of stuff. But for this particular case, I got the result that I was expecting after the typer phase.
Now `dotc -Xprint:type MyTest.scala` prints:
```
package <empty> {
  final lazy module val MyTest: MyTest$ = new MyTest$()
  final module class MyTest$() extends Object(), _root_.scala.Serializable { 
    this: MyTest.type =>
    def main(): Unit = 
      {
        val a: scala.collection.mutable.ArrayBuilder[Unit] = 
          scala.collection.mutable.ArrayBuilder.make[Unit](
            scala.reflect.ClassTag.Unit
          )
        {
          a.+=(())
          ()
        }
      }
  }
}
```
instead
```
package <empty> {
  final lazy module val MyTest: MyTest$ = new MyTest$()
  final module class MyTest$() extends Object(), _root_.scala.Serializable { 
    this: MyTest.type =>
    def main(): Unit = 
      {
        val a: scala.collection.mutable.ArrayBuilder[Unit] = 
          scala.collection.mutable.ArrayBuilder.make[Unit](
            scala.reflect.ClassTag.Unit
          )
        a.+=()
      }
  }
}
```

**Comment by FabioPinheiro** [comment]
ya `List(() => 1)` does not compile now XD

**Comment by odersky** [comment]
> Scala 2 parses a += () as a.+=(()) whereas dotty parses it as a.+=(), is this intended @odersky ?

I am surprised at Scala 2's behavior here. Here is another example:
```scala
  Console.println ()
  Console println ()
```
parses as 
```scala
    Console.println();
    Console.println(())
```
and prints one `()`, not two or none. So it seems that infix applications are no longer equivalent to dotted applications. Maybe this was part of the changes to eta expansion in 2.12?

But with the changes intended for auto-tupling in mind we should parse it the same way as Scala 2.

**Comment by som-snytt** [comment]
The Scala 2 PR refers to an earlier PR https://github.com/scala/scala/pull/6974 that says "Remove adaptation of 0-arg methods under -Xsource:3.0", so that was the context. Two years ago, we weren't yet comparing Dotty behavior as carefully as now. In fact,
```
scala> () == ()
1 |() == ()
  |^^^^^
  |not enough arguments for method ==: (x$0: Any): Boolean
```

**Comment by odersky** [comment]
@som-snytt Thanks for giving the context. Things goes in the right direction. 

In fact it turns out that Dotty does parse the argument as an empty tuple, but then the pretty printer fooled us in dropping the extra pair of parentheses. The Tuple gets replaced with an empty argument list in desugaring.
