### ISSUE TITLE
SBT gets stuck in compileIncremental

### ISSUE THREAD

**Issue by letalvoj** [lampepfl/dotty#9149]
## Issue

When I simply run VSCode using `sbt launchIDE` after one of first save files the SBT hangs on `compileIncremental`. It's enough to shut it down and start it again, yet that partially breaks the state of IDE and few statements get underlined as errors, even though the `compile` passes just fine.

I checked out the Visual VM and it seems that `dotty` / `sbt` processes get hang on some remote-procedure-call. They spend most of the time there and utilize the CPU to just a few percent.

## Screenshots

![image](https://user-images.githubusercontent.com/5262321/84187341-320ecf80-aa92-11ea-8f77-c3d7c8a20377.png)
![image](https://user-images.githubusercontent.com/5262321/84187352-3509c000-aa92-11ea-9c02-a14a75035160.png)
![image](https://user-images.githubusercontent.com/5262321/84187331-2f13df00-aa92-11ea-806f-f28b6d5c0fb8.png)

## JVM
It happens on all JDKs I have installed: Oracle JDK 1.8, OpenJDK 11 and OpenJDK 14.
I am not sure how to report this better than pointing you to the project which is affected.

**Comment by smarter** [comment]
sbt compile task has nothing to do with the dotty language server, the language server is launched from a separate process by the vscode extension so it seems that you're looking at the wrong process if you want to find out why sbt is getting stuck.

> I am not sure how to report this better than pointing you to the project which is affected.

To make this bug report actionable, we would need both a link to such a project and an exact series of step that can be used to reproduce the problem.

**Comment by letalvoj** [comment]
Sorry, send it without the link...

## Steps
-  check out https://github.com/letalvoj/loonyssh/
-  after few arbitrary code modifications, usually after saving a file - which triggers automatical incremental build - the compilation hangs

<img width="311" alt="Screenshot 2020-06-09 at 20 33 26" src="https://user-images.githubusercontent.com/5262321/84207675-321ec780-aab2-11ea-9d28-53ffbc76fa5f.png">

**Comment by smarter** [comment]
It would be really helpful to use if you could be more precise:
- which commands are you running in sbt exactly? Just `compile` or maybe `~compile`?
- can you give a set of modifications to apply that reliably reproduce the issue?

**Comment by letalvoj** [comment]
- no commands, it is enough to trigger a few automatic compiles and it just hangs
- not sure what you mean by modifications, but I can hardly give exact steps to trigger, check out the followin video: I just do a few super random changes, which do not change any logic - just whitespaces and after like sixth save compilation hangs:

https://youtu.be/WLP-EidLrYg
_(looks pretty bad now, it takes some time since youtube publishes the HD formats)_

**Comment by smarter** [comment]
> no commands, it is enough to trigger a few automatic compiles and it just hangs

I don't understand,, sbt will not automatically compile anything for you so you must be running some command, usually that is "~compile", or maybe you're using some other vscode extension to trigger sbt compilation from vscode? (the dotty extension does not do this)

**Comment by letalvoj** [comment]
@smarter ah, I had a SBT plugin enabled as well and that's causing the problems. I'll move this issue to the appropriate repo - sorry 🙏
