### ISSUE TITLE
No static check for pattern match on Identifiers

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9166]
## Minimized code

```Scala
object UnitTest extends App {
  def foo(m: Unit) = m match {
    case runtime.BoxedUnit.UNIT => println("ok")
  }
  foo(())
}
```

## Output

compiles and prints "ok"

## Expectation

error like in Scala 2
```scala
UnitTest.scala:4: error: type mismatch;
 found   : scala.runtime.BoxedUnit
 required: Unit
    case runtime.BoxedUnit.UNIT => println("ok")
                           ^
1 error
```

**Comment by nicolasstucki** [comment]
The code seems to be technically correct. `runtime.BoxedUnit.UNIT` is the only value of type `Unit`. Not sure if we should disallow this.

**Comment by nicolasstucki** [comment]
Scala 2 compact issues are for those that scala 2 supports but scala 3.0 does not. Here it is the opposite.

**Comment by bishabosha** [comment]
ok I guess it is philosophical whether or not to allow a case that is a supertype because potentially it could match but maybe its a useless branch 
```scala
trait Trait

object UnitTest extends App {
  val Foo: AnyRef = ""
  def foo(m: Trait) = m match {
    case Foo => println("ok")
  }
  foo(Foo)
}
```
but Scala 2 has the same behaviour

**Comment by nicolasstucki** [comment]
That should not compile. There should be an error in `foo(Foo)`.

**Comment by bishabosha** [comment]
Sorry yeah the confusion comes from if it is a type error to pass `Foo` to expected type `Trait` then why can you match on the value `Foo`

**Comment by dwijnand** [comment]
I think this can be closed.  The BoxedUnit.Unit specific example isn't worth considering, as it's scala.runtime.  The more general `trait Trait; val Foo: AnyVal; (m: Trait) match { case Foo => }` example is fine as there's nothing to suggest that m isn't `<: Trait & Foo.type`.  I learnt this week that that check is called `isPopulated` in nsc.
