### ISSUE TITLE
SortedMap#empty Fails At Runtime With NoSuchMethodError

### ISSUE THREAD

**Issue by adamgfraser** [lampepfl/dotty#9175]
## Minimized code

```Scala
import scala.collection.immutable.SortedMap

object Example extends App {
  
  val sortedMap = SortedMap("a" -> 1, "b" -> 2, "c" -> 3)
  val empty     = sortedMap.empty
  println(empty)
}
```

## Output

```scala
java.lang.NoSuchMethodError: scala.collection.immutable.SortedMap.empty()Lscala/collection/Map;
	at Example$.<init>(main.scala:6)
	at Example$.<clinit>(main.scala)
	at Example.main(main.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:115)
	at sbt.Run.execute$1(Run.scala:79)
	at sbt.Run.$anonfun$runWithLoader$4(Run.scala:92)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.lang.Thread.run(Thread.java:748)
```

## Expectation
I would expect that since this method is in the API of the latest Scala collections it would work correctly. At the minimum if it did not work I would expect to get a compilation failure with a helpful error message.

**Comment by smarter** [comment]
> java.lang.NoSuchMethodError: scala.collection.immutable.SortedMap.empty()Lscala/collection/Map;

The correct signature appears to be `scala/collection/immutable/SortedMap.empty:()Lscala/collection/SortedMapOps;`

The empty method in question is defined in SortedMapFactoryDefaults:
```scala
override def empty: CC[K, V @uncheckedVariance] = sortedMapFactory.empty(ordering)
``
where CC is defined as:
```scala
CC[x, y] <:  Map[x, y] with SortedMapOps[x, y, CC, CC[x, y]] with UnsortedCC[x, y]
```

Dotty and Scala 2 do not erase intersection types in the same way (scala 2 does some really weird stuff), I'm working on a PR to take that into account when calling into scala 2 code which should hopefully fix that.

**Comment by adamgfraser** [comment]
Thanks! For what it is worth I also tried to use parentheses like `empty()` but that resulted in a compilation error `missing argument for parameter key of method apply: (key: String): Int @uncheckedVariance`. So there doesn't seem to be a way to call this method from Dotty right now.

**Comment by smarter** [comment]
Indeed, but you should be able to call `SortedMap.empty[String, Int]`

**Comment by adamgfraser** [comment]
Yes but if I am working with polymorphic types I may not have an implicit `Ordering` in scope and need to reuse whatever `Ordering` is underlying the original map which is why I want to call `sortedMap.empty` as opposed to `SortedMap.empty`.
