### ISSUE TITLE
Initialization checker doesn't catch uninitialized object call

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#9176]
When running the following code with `-Ycheck-init`, no warning or error is emitted:

```Scala
class Foo(val opposite: Foo)
case object A extends Foo(B)
case object B extends Foo(A)
object Test {
  def main(args: Array[String]): Unit = {
    println(A.opposite)
    println(B.opposite)
  }
}
```
But A ends being used when it's uninitialized:

```scala
B
null
```

I'm not sure if this is a bug or outside the scope of safe initialization?

**Comment by liufengyun** [comment]
Generally, static fields are out of the scope of the checker, as that would require global analysis. However, in this special case, there is room to improve the checker, if it treats the compilation unit as inside a class.

For example, if we wrap the code in a class, the checker will be able to detect initialization problems:

```Scala
class CompilationUnit {
  class Foo(val opposite: Foo)
  case object A extends Foo(B)
  case object B extends Foo(A)
  A
}
```

Given the code above, the code `new CompilationUnit` will run forever, thus it's correct for the checker to not issue any warning. There are several possible enhancement:

- treats the compilation unit as inside a class
- check possible non-termination in the initialization of lazy fields

Another subtle issue is with the following code: accessing `CompilationUnit` will not run forever, 
 and an uninitialized field is accessed.

```Scala
object CompilationUnit {
  class Foo(val opposite: Foo)
  case object A extends Foo(B)
  case object B extends Foo(A)
  A
}
```

I think it will be more consistent to make the initialization behavior of `object CompilationUnit` and `class CompilationUnit` consistent in language semantics and compiler implementation.

**Comment by liufengyun** [comment]
This can now be checked with the experimental option: `-Ysafe-init-global`.

**Comment by smarter** [comment]
Would it make sense to combine -Ysafe-init and -Ysafe-init-global into one flag eventually?

**Comment by liufengyun** [comment]
> Would it make sense to combine -Ysafe-init and -Ysafe-init-global into one flag eventually?

From the end-user perspective, it makes sense to have an umbrella option to cover `-Ysafe-init` and `-Ysafe-init-global` (maybe `-Yexplicit-nulls` as well). Internally, as well know they are different features, having different flags makes testing easier.
