### ISSUE TITLE
Useful Tuple type matches

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#9212]
We already have a type match `Tuple.Map`.

We could also have:
- [x]  `Tuple.Fold` (#9217)
- [x]  `Tuple.Filter` (#9235)
- [x]  `Tuple.FlatMap` (#9217)

We can take inspiration for the type matches we already have in [Tuple](https://github.com/lampepfl/dotty/blob/master/library/src/scala/Tuple.scala#L73). For example `Size` is just a fold.

**Comment by nicolasstucki** [comment]
Fold prototype:
```scala
type Fold[Z, F[_, _], T <: Tuple] = T match
  case EmptyTuple => Z
  case h *: t => F[h, Fold[Z, t]]

type Size[T <: Tuple] = Fold[0, [X, Y] => S[X], T]
```

**Comment by nicolasstucki** [comment]
FlatMap prototype :
```scala
  type FlatMap[Tup <: Tuple, F[_]] <: Tuple = Tup match
    case EmptyTuple => EmptyTuple
    case h *: t => F[h] ++ FlatMap[t, F]
```

**Comment by nicolasstucki** [comment]
Not sure how the predicate of a Filter should look like. It could be a type `P[_]` that returns the type `true` or the type `false`.

**Comment by nicolasstucki** [comment]
Does anyone have other suggestions for the `Filter`?

**Comment by julienrf** [comment]
> Not sure how the predicate of a Filter should look like. It could be a type `P[_]` that returns the type `true` or the type `false`.

That sounds reasonable. How could we filter all the elements of a tuple that have type `Foo` with such a predicate type?

~~~ scala
[X] => X match { case Foo => true case _ => false }
~~~

?

**Comment by anatoliykmetyuk** [comment]
I came up with the following implementation of the `Filter` type: #9235.
