### ISSUE TITLE
constructor's param cannot be open

### ISSUE THREAD

**Issue by ohze** [lampepfl/dotty#9226]
## Minimized code

```Scala
class C(open: Int)
```

## Output

```scala
[error] 1 |class C(open: Int)
[error]   |            ^
[error]   |             values cannot be open
```

## Expectation
I know that `open` is a [soft modifier](https://dotty.epfl.ch/docs/reference/other-new-features/open-classes.html#details)
> open is a soft modifier. It is treated as a normal identifier unless it is in modifier position.

But should it be treated as a normal identifier in this case?

**Comment by nicolasstucki** [comment]
Solution might be related to #9127

**Comment by nicolasstucki** [comment]
Actually  it looks like #9127 already fixed it
