### ISSUE TITLE
metaprogramming / meta-programming / meta programming?

### ISSUE THREAD

**Issue by ShapelessCat** [lampepfl/dotty#9242]
When I read the macros.md, I notice that this file uses all these three words metaprogramming / meta-programming / meta programming. Do you guys think we should pick one and keep using it in the whole document? If it is, which one is the preferred one? 

I can include this change in a PR I'm creating to fix some example code in the macros.md.

**Comment by nicolasstucki** [comment]
Use `metaprogramming`. That is the one used by the original literature and mostly used today.
