### ISSUE TITLE
Path-dependent type inference problem

### ISSUE THREAD

**Issue by adamw** [lampepfl/dotty#9247]
## Minimized code

```Scala
trait Z {
  type V
  def v: V
}

case class C[T](v: T) 

abstract class Test(val z1: Z) {
  def r[U](c: C[U]): C[U] = c
  def c1(z: Z): C[z.V] = C(z.v)
  r(c1(z1)) // : C[z1.V]
}
```

## Output

```scala
[error] -- [E007] Type Mismatch Error: Test.scala:13:6
[error] 13 |  r(c1(z1)) // : C[z1.V]
[error]    |    ^^^^^^
[error]    |Found:    C[Test.this.z1.V]
[error]    |Required: C[(Z & Singleton)#V]
[error] one error found
```

## Expectation

The above code works fine on Scala 2.11-2.13. Adding an explicit type annotation: `r(c1(z1): C[z1.V])` makes the code compile on Dotty as well. 

Tested using 0.25.0-RC2, as well as 0.24.0.

That's as much as I can minimize the code :)

**Comment by adamw** [comment]
Now I see that the error is actually flipped wrt the original (non-minimized example). In the original problem, the type that gets inferred is of the shape `C[(Z & Singleton)#V]`, while it should be `C[Test.this.z1.V]`. Again, adding type annotations helps.

Here's another variant of the code above, which causes the error to be flipped (notice the variance annotation):

```scala
trait Z {
  type V
  def v: V
}

case class C[+T](v: T)

class Test1(val z1: Z) {
  def r[U](c: C[U]): C[U] = c
  def c1(z: Z): C[z.V] = C(z.v)
  val c2: z1.V = r(c1(z1)).v // error
  val c3: z1.V = r(c1(z1): C[z1.V]).v // ok
}
```

Error message:

```scala
[error] -- [E007] Type Mismatch Error: Test.scala:13:27
[error] 13 |  val c2: z1.V = r(c1(z1)).v
[error]    |                 ^^^^^^^^^^^
[error]    |Found:    (C[(Z & Singleton)#V]#v :
[error]    |  (Z & Singleton)#V
[error]    |)
[error]    |Required: Test1.this.z1.V
```

**Comment by odersky** [comment]
This looks like the general problem that we cannot infer path dependent types through class fields. A principled solution would put us on the way to dependent types. So this would be very promising, but it's also hard. Not sure how scalac infers this.

**Comment by odersky** [comment]
This is not a bug to fix short-term. Re-visit when we generalize dependent types.
