### ISSUE TITLE
Typer: failure to type usages of `tupple.zipped` with Predef compiled by Dotty

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#925]
```
$ dotc scala-scala/src/library/scala/Predef.scala  ./src/dotty/./tools/dotc/ast/Desugar.scala


warning: encountered F-bounded higher-kinded type parameters for type CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type CC; assuming they are invariant
./src/dotty/./tools/dotc/ast/Desugar.scala:771: error: no implicit argument of type runtime.Tuple2Zipped.Ops#T1 =>
  scala.collection.TraversableLike[Nothing', Nothing'] found for parameter w1 of method zipped in class Ops
          val pdefs = (defpats, rhss).zipped map (makePatDef(Modifiers(), _, _))
                                            ^
```

**Comment by DarkDimius** [comment]
@odersky could you please have a look at this issue?

**Comment by odersky** [comment]
It's fixed in #950 and, I assume, in master.

**Comment by DarkDimius** [comment]
@odersky I can reproduce this on 661da00

**Comment by DarkDimius** [comment]
```
dark@tsf-452-wpa-2-017 ~/workspace/dotty ((661da00...)) $ dotc scala-scala/src/library/scala/Predef.scala  ./src/dotty/./tools/dotc/ast/Desugar.scala
warning: encountered F-bounded higher-kinded type parameters for type CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type CC; assuming they are invariant
warning: encountered F-bounded higher-kinded type parameters for type CC; assuming they are invariant
./src/dotty/./tools/dotc/ast/Desugar.scala:771: error: no implicit argument of type runtime.Tuple2Zipped.Ops#T1 =>
  scala.collection.TraversableLike[Nothing', Nothing'] found for parameter w1 of method zipped in class Ops
          val pdefs = (defpats, rhss).zipped map (makePatDef(Modifiers(), _, _))
                                            ^
./src/dotty/./tools/dotc/ast/Desugar.scala:771: error: map is not a member of (implicit w1: runtime.Tuple2Zipped.Ops#T1 =>
  scala.collection.TraversableLike[Nothing', Nothing']
, w2: runtime.Tuple2Zipped.Ops#T2 =>
  scala.collection.IterableLike[Nothing', Nothing']
)scala.runtime.Tuple2Zipped[Nothing', Nothing', Nothing', Nothing']
          val pdefs = (defpats, rhss).zipped map (makePatDef(Modifiers(), _, _))
                      ^
./src/dotty/./tools/dotc/ast/Desugar.scala:772: error: Ambiguous overload. The overloaded alternatives of method Block in object untpd$ with types
 (stat: dotty.tools.dotc.ast.untpd.Tree, expr: dotty.tools.dotc.ast.untpd.Tree)
  dotty.tools.dotc.ast.untpd.Block
 (stats: scala.collection.immutable.List[dotty.tools.dotc.ast.untpd.Tree], expr:
  dotty.tools.dotc.ast.untpd.Tree
)dotty.tools.dotc.ast.untpd.Block
both match arguments (<error>(pdefs), dotty.tools.dotc.ast.untpd.Tree)
          val rhs1 = makeFor(nme.map, nme.flatMap, GenFrom(defpat0, rhs) :: Nil, Block(pdefs, makeTuple(id0 :: ids)))
                                                                                 ^
four warnings found
three errors found
```

**Comment by odersky** [comment]
Weird. That's what I get:

*/Users/odersky/workspace/dotty>* dotc
scala-scala/src/library/scala/Predef.scala
src/dotty/tools/dotc/ast/Desugar.scala

warning: encountered F-bounded higher-kinded type parameters for type CC;
assuming they are invariant

warning: encountered F-bounded higher-kinded type parameters for type CC;
assuming they are invariant

warning: encountered F-bounded higher-kinded type parameters for type CC;
assuming they are invariant

warning: encountered F-bounded higher-kinded type parameters for type CC;
assuming they are invariant

warning: encountered F-bounded higher-kinded type parameters for type CC;
assuming they are invariant

warning: encountered F-bounded higher-kinded type parameters for type CC;
assuming they are invariant

6 warnings found

there were 10 deprecation warning(s); re-run with -deprecation for details

On Wed, Nov 11, 2015 at 9:22 PM, Dmitry Petrashko <notifications@github.com>
wrote:

> @odersky <https://github.com/odersky> I can reproduce this on 661da00
> <https://github.com/lampepfl/dotty/commit/661da0065050e639df20f847d1921a777fbbd285>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lampepfl/dotty/issues/925#issuecomment-155899709>.
>



-- 
Martin Odersky
EPFL

**Comment by DarkDimius** [comment]
@odersky I've tried on a different machine(lamppc34) with a clean environment and was able to reproduce it there.

I'll try to help you reproducing it tomorrow, If you'll be in the office.

**Comment by DarkDimius** [comment]
reproduced on jenkins: #951 https://scala-ci.typesafe.com/job/dotty-master-validate-junit/667/consoleFull

**Comment by odersky** [comment]
It was a missing type parameter in Predef. Dotty does not require type parameters to be always given, so it did not issue an error message.
