### ISSUE TITLE
Type aliases can be used as unapply patterns

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9282]
## Minimized code

```Scala
scala> case class Foo(x: Int)
// defined case class Foo

scala> object inst:
     |   type FooAlias = Foo
     | 
// defined object inst

scala> def foo(t: inst.FooAlias) = t match
     |   case inst.FooAlias(x) => x
     | 
def foo(t: inst.FooAlias): Int
```

## Expectation

I would expect that the identifier of an unapply pattern can only refer to a term, not a type, as with Scala 2.

**Comment by smarter** [comment]
This looks like it's intentional to me: https://github.com/lampepfl/dotty/blob/7723864d3669cea8bba7481d3b62eaf7e560c2bf/compiler/src/dotty/tools/dotc/typer/Applications.scala#L1198-L1200
