### ISSUE TITLE
partest should implement --failed correctly

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#930]
It would be really helpful to have a mode where partest runs only failed tests.

**Comment by odersky** [comment]
More items on the partest wishlist:

 - Provide a log per test, instead of piping everything into one output stream
 - Honor xxx.flags files when performing junit tests
 - Have a cleaned up output like the original partest

**Comment by DarkDimius** [comment]
> Honor xxx.flags files when performing junit tests

AFAIK this is implemented. Flags are generated from junit config.

**Comment by odersky** [comment]
It would be good to have a test for this. I tried something with -language:Scala2 and it did not work.

**Comment by DarkDimius** [comment]
We do have tests for this. For example compileStdLib test https://scala-ci.typesafe.com/job/dotty-master-validate-partest/708/consoleFull .
Here the excerpt from log:

```
/home/jenkins/workspace/dotty-master-validate-partest/tests/partest-generated/pos/compileStdLib/Signalling.scala:89: migration warning: Procedure syntax no longer supported; `=' should be inserted here
 def setIndexFlagIfGreater(f: Int)
 ^
```

This would have been an error if partest did not pass `-language:Scala2`

**Comment by odersky** [comment]
Ah, then it was probably the junit test that failed. But given that junit cannot honor the flags, maybe we should stop using it? I would switch tomorrow if partest's test output was acceptably nice.

**Comment by DarkDimius** [comment]
@odersky junit also honors the flags, otherwise the same tests would fail in junit.

I'd like to continue with being able to choose to run tests either in partest or junit. 
My workflow is based around attaching debugger to junit tests.

**Comment by smarter** [comment]
> junit also honors the flags, otherwise the same tests would fail in junit.

Are you sure? Doesn't junit work because we explicitly pass the scala2 mode flag in `tests.scala`:
```scala
@Test def compileStdLib = compileList("compileStdLib", stdlibFiles, "-migration" :: scala2mode)
```

**Comment by DarkDimius** [comment]
@smarter partest flags are generated from ones that you explicitly pass. Not the reverse.

**Comment by smarter** [comment]
Partest is dead, but let's open an issue for having this feature in vulpix: https://github.com/lampepfl/dotty/issues/3798
