### ISSUE TITLE
adding GenSeq.scala and GenSeqLike.scala to whitelist causes cyclic reference error

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#935]
I have tried to minimize, but without luck.

**Comment by odersky** [comment]
Minimization was: scala.Predef, scala.package, GenSeqLike. Obvious, no ;-)

**Comment by DarkDimius** [comment]
I wasn't including `scala.package`. I forgot about that it exists.

**Comment by DarkDimius** [comment]
Fixed
