### ISSUE TITLE
Trait 'self=>' type inheritance problem

### ISSUE THREAD

**Issue by edolgy** [lampepfl/dotty#9352]
```Scala
abstract class Foo[A] extends Bar[A]

trait Bar[A]:
  self: Foo[A] =>
  def foo             : Unit   = bar(null)
  def bar(f: Type[A]) : Unit

trait Type[A]
```
 Ambiguous overload. The overloaded alternatives of method bar in trait Bar with types
[error]  (f: Type[A]): Unit
[error]  (f: Type[A]): Unit
[error] both match arguments (Null)
[error]     def foo             : Unit   = bar(null)

PS. Couple of months ago this would compile with no problem

**Comment by griggt** [comment]
#9063 (dbc1e95) caused the regression.
