### ISSUE TITLE
 type argument ignored in certain situations

### ISSUE THREAD

**Issue by robstoll** [lampepfl/dotty#9367]
## Minimized code

```Scala
object Main {
  
  def a[A,B](a : A) : B = a.asInstanceOf[B]
  
  def main(args: Array[String]): Unit = {
    a[B=String](1)               // compiles, does not fail at runtime but should IMO
    val s = a[B=String](1)       // compiles, fails at runtime with ClassCastException => correct behaviour
    val i: Int = a[B=String](1)  // does not compile => correct behaviour
  }
}
```
I guess the type argument in the first line is ignored and `Nothing` is inferred for `B` and that is the reason why no cast is applied.

**Comment by LPTK** [comment]
I don't think this is related to named type arguments. The same happens without them, and it's consistent with Scalac. BTW, inferring `Nothing` is never going to prevent `ClassCastException`s, as you can't cast to `Nothing` at runtime either.

**Comment by robstoll** [comment]
You are right, it seems like it is a general bug: 
```
a[Int, String](1) // compiles, does not fail at runtime but should IMO
```
IMO the user has always right and not `Nothing` should be inferred but `String` -- otherwise, what is the point of allowing to specify it in the first place?

**Comment by LPTK** [comment]
I don't understand. What makes you think Scala infers `Nothing` when `B=String` is specified? This was originally a guess you formulated to explain the absence of `ClassCastExceptions`, but as I've shown you it was not the correct explanation.

**Comment by robstoll** [comment]
Sorry, did not get your description apparently. You are of course right. The cast is absent, otherwise it would have failed as well.

**Comment by odersky** [comment]
The behavior follows from the erasure model of computation. Nothing to be done here.

**Comment by robstoll** [comment]
@odersky could you enlighten me, what are the erased types for the following two statements:
```
a[B=String](1)              // compiles, does not fail at runtime but should IMO
val s = a[B=String](1)      // compiles, fails at runtime with ClassCastException => correct behaviour
```
I still don't get why a different behaviour results just because of an assignment.

**Comment by odersky** [comment]
I don't quite understand the question. The second statement fails because it inserts a cast to the inferred type. The first statement succeeds since its result is discarded. This is the standard erasure model. I am afraid I don't have the time to explain everything in detail.

**Comment by som-snytt** [comment]
This FAQ "Where is my CCE?" has a long history in Scala 2 issues (and presumably also in various forums).

Example
https://github.com/scala/bug/issues/9385

There are also tickets which ask for linting support of `asInstanceOf`, such as for impossible casts, and IDEs can do that. Another IDE feature proposal would be "reveal casts" (similar to reveal implicits or showing tab characters).

**Comment by odersky** [comment]
Here's a rough summary what the standard erasure model is: 

 - Erase all types according to the erasure function
 - Insert casts _as needed_ to make it work in the underlying non-generic type system.

The _as needed_ is key here.

**Comment by robstoll** [comment]
I see thanks for your time :+1:

**Comment by odersky** [comment]
Ah, yes, that's a common misconception. I think it would be theoretically sound to always insert the casts if the erased types change, but details would have to be worked out. Anyway, that's not how it works in any of the languages that use erasure.
