### ISSUE TITLE
Wrong collective method docs example

### ISSUE THREAD

**Issue by kpbochenek** [lampepfl/dotty#9368]
![2020-07-15-113800_616x354_scrot](https://user-images.githubusercontent.com/10478402/87529709-a9d2aa00-c68f-11ea-8d2f-ad851397c7da.png)

There is a lack of ":" after `extension (ss: Seq[String])` in given example

**Comment by TheElectronWill** [comment]
Pasting this example in the repl actually works, I'm not sure it should.

**Comment by smarter** [comment]
This is intentional, see the end of the discussion in https://github.com/lampepfl/dotty/pull/9255, if you want to debate whether this is a good idea or not, I suggest opening a thread on https://contributors.scala-lang.org.
