### ISSUE TITLE
migrate old extension syntax to a new one

### ISSUE THREAD

**Issue by kpbochenek** [lampepfl/dotty#9369]
Old syntax is still present in those places:

https://github.com/lampepfl/dotty/blob/1516b0672cce419bf7c4855e612c02a3c10d2c4a/library/src/dotty/DottyPredef.scala#L85

https://github.com/lampepfl/dotty/blob/aa64078d9defe1df6856158a16c1f236792231f2/compiler/src/dotty/tools/dotc/core/Contexts.scala#L606

https://github.com/lampepfl/dotty/blob/aa64078d9defe1df6856158a16c1f236792231f2/compiler/src/dotty/tools/dotc/core/Comments.scala#L18

https://github.com/lampepfl/dotty/blob/aa64078d9defe1df6856158a16c1f236792231f2/compiler/src/dotty/tools/dotc/core/Decorators.scala#L164

https://github.com/lampepfl/dotty/blob/9f43ede9c6e627e4460d94726a165c2558334168/compiler/src/dotty/tools/dotc/typer/Nullables.scala#L164

https://github.com/lampepfl/dotty/blob/9f43ede9c6e627e4460d94726a165c2558334168/compiler/src/dotty/tools/dotc/typer/Nullables.scala#L195

Unless `on` is still soft keyword and extension can be named?

**Comment by nicolasstucki** [comment]
No, `on` does not exist in the new syntax.
