### ISSUE TITLE
Value class equality boxes

### ISSUE THREAD

**Issue by odersky** [lampepfl/dotty#9413]
## Minimized example

Compile the following with -Xprint:elimErasedValueType

```Scala
class ApproxState(private val bits: Int) extends AnyVal

object Main {
  val FreshApprox: ApproxState = new ApproxState(4)
  var approx: ApproxState = FreshApprox
  println(approx == FreshApprox)
}
```

## Output

The last statement compiles to:

```scala
    println(
      scala.Boolean.box(
        new ApproxState(Main.approx()).==(new ApproxState(Main.FreshApprox()))
      )
    )
```

## Expectation

No boxing

**Comment by smarter** [comment]
The culprit is this line in VCElideAllocations:
> !defn.Any_equals.overridingSymbol(tp1.typeSymbol.asClass).exist

Which is as documented:
> new V(u1) == new V(u2) => u1 == u2   provided V does not redefine `equals`

But value classes of course have to define equals, I think this is supposed to check that the equals in question is not synthetic.

**Comment by odersky** [comment]
Yes, I think that's right. Fix forthcoming...
