### ISSUE TITLE
Java classes cannot be exported

### ISSUE THREAD

**Issue by abgruszecki** [lampepfl/dotty#9415]
It seems that no Java class can be exported:

```
scala> object o { export java.lang.String }
object o { export java.lang.String }
1 |object o { export java.lang.String }
  |                  ^^^^^^^^^
  |                  Java defined class String is not a value
```

The same error happens for `java.lang.Appendable`, which doesn't have static members, so it does not seem like the issue is connected to that.

If we do not want to allow exporting Java classes, then at least we should explicitly say so in the error message. This'd be sad though, as exporting Java classes is a neat way to create "namespaces" that expose members of multiple packages under a unified prefix.

**Comment by smarter** [comment]
You can't export a Java class, because `someJavaClass.someStaticMethod` is a special construct for the typer, and the prefix of that construct is not a value (that's what the error is trying to say).

**Comment by AleksanderBG** [comment]
It shouldn't be impossible to effectively allow exporting Java classes though, right? We could just create a type alias and an object that holds forwarders to the static methods.

**Comment by bishabosha** [comment]
how does this relate to #7033 @smarter ?

**Comment by smarter** [comment]
Those are the same issue

**Comment by bishabosha** [comment]
ok will close the earlier one

**Comment by odersky** [comment]
I think the proposed solutions would be too complicated in relation to the insignificant gain.
