### ISSUE TITLE
releaseFence needs to be added at the end of constructors of classes that contain mixin fields

### ISSUE THREAD

**Issue by smarter** [lampepfl/dotty#9424]
Since https://github.com/lampepfl/dotty/pull/8652, fields in classes coming from traits are no longer marked `final` because they're set outside of the class constructor. When this was changed in scalac, they also had to add calls to releaseFence at the end of these constructors, this is justified with a comment:
```scala
              // If the field is mutable, it won't be final, so we can write to it in a setter.
              // If it's not, we still need to initialize it, and make sure it's safely published.
              // Since initialization is performed (lexically) outside of the constructor (in the trait setter),
              // we have to make the field mutable starting with classfile format 53
              // (it was never allowed, but the verifier enforces this now).
```
from https://github.com/scala/scala/pull/7028, which we should port.

Tentatively assigning to @sjrd since unfortunately for him he has become our resident mixin expert :).

**Comment by smarter** [comment]
Also relevant is https://github.com/scala/scala/commit/5e109ff7f0d39c9df250ad1498120b1b454374e9, but tha's only an optimization (if I understand correctly) and one that depends on https://github.com/lampepfl/dotty/pull/9181

**Comment by sjrd** [comment]
I won't have time to do that in the three weeks. If someone else wants to pick it up, I suggest to that in Mixin. In `transformTemplate`, for a non-trait class, if we process any trait setter in that class, then add an additional statement at the end of the new `Template`'s `body` that calls `releaseFence()`. Then `Constructors` will naturally move that statement to the body of the constructor.

**Comment by anatoliykmetyuk** [comment]
Is it still a blocker for 3.0.0-M1? @smarter ?

**Comment by smarter** [comment]
We can move it to M2
