### ISSUE TITLE
Infix TypeApply is a syntax error 

### ISSUE THREAD

**Issue by adamgfraser** [lampepfl/dotty#9453]
## Minimized code

```Scala
object Example extends App {
  
  trait Foo {
    def bar[A](baz: Int): Int =
      baz
  }
  
  val a = new Foo {}
  a bar[Int] 1
}
```

## Output

```scala
 expression expected but '[' found
```

## Expectation

I would have expected that when I called a method with infix notation I would be able to specify type parameters. This compiles on Scala 2.

**Comment by som-snytt** [comment]
The Scala 2 addition or edition is at https://github.com/scala/scala/pull/3283 which includes a link to the ancient discussion and official sanction.

Sadly, someone asked for `null asInstanceOf [String]` abbreviated to `null as [String]` (Ed. brackets added).

**Comment by odersky** [comment]
This was never allowed in the syntax in the spec. The original use case, to allow method names being written infix, is now discouraged. The use case of being able to pass type arguments to symbolic operators is also dubious, IMO.
Compare
```scala
    xs ++[Int] ys
```
with
```scala
    xs.++[Int](ys)
```
The first looks weird; it does not look like an infix operator. The second, might be a bit more clunky, but it's clear what it is.

So, dubious use cases, never specced. I think we'll close that one.
