### ISSUE TITLE
inline def with inline function parameter not inlining the function

### ISSUE THREAD

**Issue by rcano** [lampepfl/dotty#9456]
## Minimized code

```Scala
object inlinetest:
  def test: Int =
    inline2(inline1(2.+))

  inline def inline1(inline f: Int => Int): Int => Int =
    i => f(1)

  inline def inline2(inline f: Int => Int): Int =
    f(2) + 3

```

## Output
Disassemblied (via CFR) output of test
```java
    public int test() {
        return BoxesRunTime.unboxToInt((Object)((JFunction1.mcII.sp & Serializable)(JFunction1.mcII.sp & Serializable)i -> {
            int x = 1;
            return 2 + x;
        }).apply((Object)BoxesRunTime.boxToInteger((int)2))) + 3;
    }
```

## Expectation
The result should not contain any lambda.

## Notes
 Manually inlining `inline1` produces the intended result
```scala
 def test: Int =
    inline2(i => 2 + 1)
```
it gets properly inlined
```java
    public int test() {
        return 6;
    }
```

**Comment by nicolasstucki** [comment]
I noticed this as well. We only inline TermRefs but not constants.

https://github.com/lampepfl/dotty/blob/master/compiler/src/dotty/tools/dotc/transform/BetaReduce.scala#L63-L70

**Comment by nicolasstucki** [comment]
Actually it is this one

https://github.com/lampepfl/dotty/blob/a6acaa9f95ffa59dd736f22dbb839759f7c85c63/compiler/src/dotty/tools/dotc/typer/Inliner.scala#L919
