### ISSUE TITLE
Reflective calls aren't cross compatible with scala 2

### ISSUE THREAD

**Issue by martijnhoekstra** [lampepfl/dotty#9459]
Reflective calls need language import `import scala.reflect.Selectable.reflectiveSelectable` in dotty. But that's not cross-compatible with scala 2 without a shim. At https://contributors.scala-lang.org/t/scala-3-migration-guide/4237/7 @smarter suggested making `import scala.language.reflectiveCalls` make scala 3 behave the same as scala 2.

**Comment by sjrd** [comment]
This was already implemented in #9420.
