### ISSUE TITLE
inline method stops inlining function when called naming the parameter

### ISSUE THREAD

**Issue by rcano** [lampepfl/dotty#9466]
## Minimized code

```Scala
object inlinefail:
  inline def i(inline f: Int => Boolean): String =
    if f(34) then "a"
    else "b"

  def test: String = i(f = _ == 34)
```

## Output
disassemblied (via CFR) test method:
```java
    public String test() {
        return BoxesRunTime.unboxToBoolean((Object)((JFunction1.mcZI.sp & Serializable)(JFunction1.mcZI.sp & Serializable)_$1 -> _$1 == 34).apply((Object)BoxesRunTime.boxToInteger((int)34))) ? "a" : "b";
    }

```

## Expectation

Bytecode should be the same as for the code 
```scala
  def test: String = i(_ == 34) //not naming the parameter
```
which yields
```java
    public String test() {
        int _$1 = 34;
        return _$1 == 34 ? "a" : "b";
    }
```

**Comment by bishabosha** [comment]
i would have thought this could be constant folded to "a"

**Comment by nicolasstucki** [comment]
That binding should not be generated. It is probably generate in

https://github.com/lampepfl/dotty/blob/0e42cd838cbce7d929ea3c9e8de3c2f34d4ec1d2/compiler/src/dotty/tools/dotc/typer/EtaExpansion.scala#L46

**Comment by rcano** [comment]
> i would have thought this could be constant folded to "a"

it doesn't because the if is not an inlined if. In the snippet that is on purpose because I wanted to show that it wasn't inlining the lambda when naming the parameter
