### ISSUE TITLE
Overload resolution issues with non ambiguous methods

### ISSUE THREAD

**Issue by rcano** [lampepfl/dotty#9467]
## Minimized code

```Scala
trait Pointer
class CustomBuffer[Self <: CustomBuffer[Self]] extends Pointer:
  def put(self: Self): Self = ???
class PointerBuffer extends CustomBuffer[PointerBuffer]:
  def put(pointer: Pointer): PointerBuffer = ???

@main def test = 
  val pb = PointerBuffer()
  pb.put(PointerBuffer()) 
```

## Output

```scala
  pb.put(PointerBuffer())
  ^^^^^^
Ambiguous overload. The overloaded alternatives of method put in class PointerBuffer with types
 (pointer: Pointer): PointerBuffer
 (self: PointerBuffer): PointerBuffer
both match arguments (PointerBuffer)
```

## Expectation
It should compile fine

**Comment by bishabosha** [comment]
This is also ambiguous in Scala 2, it isn't in Java, which could be interesting:
```java
jshell> interface Pointer {}
|  created interface Pointer

jshell> class CustomBuffer<Self extends CustomBuffer<Self>> implements Pointer {
   ...>   public Self put(Self self) { return self; }
   ...> }
|  created class CustomBuffer

jshell> class PointerBuffer extends CustomBuffer<PointerBuffer> {
   ...>   public PointerBuffer put(Pointer pointer) { throw new IllegalStateException("?"); }
   ...> }
|  created class PointerBuffer

jshell> var pb = new PointerBuffer()
pb ==> PointerBuffer@3d646c37

jshell> pb.put(new PointerBuffer())
$5 ==> PointerBuffer@5a10411
```

**Comment by rcano** [comment]
The api is an excerpt of the highly popular LWJGL library, it's not a hidden corner that's not worth it I think

**Comment by som-snytt** [comment]
This is pretty straightforward with respect to overloading resolution as currently defined. It's the "derived class" rule for "relative weight." Normally, if I introduce the new method, I intend it and not the super method. I expect it to be either an override or more specific, and this rule helps ensure I didn't make a terrible mistake. (This is my rationale; not speaking from experience.)

Scala 2 has tickets where it's acknowledged that the rules are different for Java, which has the weird 3-phase algorithm (strict invocation, then loose (with boxing), then varargs).

Possible workarounds are adding an override, or using an overload result type to select the method, or using a shim for java api.

**Comment by rcano** [comment]
If both methods were to take a type that would be a valid super type, I'd understand the ambiguity, but one method is an exact match and the other isn't, I'd think this triumphs having to weigh them against each other. In fact if both methods were declared in the same class, it doesn't fail to resolve them.

Not sure what you find weird about java's resolution rules, they seem pretty intuitive to me.

**Comment by som-snytt** [comment]
I was re-reading the Java rules again last year because someone was confused by how overloading worked in their test api, with overloads of `assertSomething`. IIRC varargs was implicated.

The old example from a ticket is:
```
class X; class Y extends X; def f(x: X): Unit; def f(y: Y*): Unit; f(new Y)
```
where Java picks `f(x: X)`.

Maybe a tweak is possible for Java-defined methods, similar to the rule for whether to require parens in applications. Or a series of tweaks.

**Comment by odersky** [comment]
This is already as specified. There is not precise match rule in Scala. The best fix is to duplicate the `put` method in `PointerBuffer` with a `super.put` forwarder.
