### ISSUE TITLE
Compilation loop when companion object is in other file than class

### ISSUE THREAD

**Issue by pikinier20** [lampepfl/dotty#9472]
## Minimized code

One file:
```Scala
package example.reproduction

class Reproduction
```
Second file:
```Scala
package example.reproduction

object Reproduction
```

## Output

Looped compilation - repeated message about compiling 2 sources from ...

## Expectation

I think this code is correct and should compile correctly

**Comment by AleksanderBG** [comment]
I retested this on `master` - it seems that instead of looping, we emit a mysterious error message:

```
-- [E006] Not Found Error: A2.scala:3:0 ----------------------------------------
3 |object Reproduction
  |^
  |Not found: type Reproduction$

longer explanation available when compiling with `-explain`
1 error found
```

We should fix this to be explicit about why we refuse to compile the above definitions.
