### ISSUE TITLE
Self-type indentation is unexpectedly significant

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#9515]
## Minimized code

```Scala
trait C {
self =>

  class D

  class E
}
```

## Output

```scala
-- Warning: badindent.scala:9:2 ------------------------------------------------
9 |  class E
  |  ^
  |  Line is indented too far to the right, or a `{` or `:` is missing
1 warning found
```
IRL, source had a few indentation quirks, so it can be tricky-to-impossible to locate the offender 800 lines back.
```
[info] Compiling 61 Scala sources to .../target/scala-0.26/classes ...
[warn] -- Warning: .../src/main/scala/scala/collection/parallel/ParIterableLike.scala:888:2 
[warn] 888 |  protected[this] abstract class Composite[FR, SR, R, First <: StrictSplitterCheckTask[FR, _], Second <: StrictSplitterCheckTask[SR, _]]
[warn]     |  ^
[warn]     |  Line is indented too far to the right, or a `{` or `:` is missing
```

## Expectation

The problem is the indentation of the self type.

It is not obvious whether the indentation of the self type should matter.

The warning should tell me why it thinks my indentation is wrong, i.e., which previous line established the expected indentation.

The warning is due to the template `class D` checking the indentation of the following line, which is `class E`.

Maybe the extra help, e.g., mentioning `is misaligned with line 3`, should be enabled under a flag.

**Comment by odersky** [comment]
> It is not obvious whether the indentation of the self type should matter.

I fixed it so that it does not matter.
