### ISSUE TITLE
Cannot retypecheck after frontend phase

### ISSUE THREAD

**Issue by Atry** [lampepfl/dotty#9520]
## Minimized code

```bash
git clone https://github.com/Atry/dotty-retypecheck.git && cd dotty-retypecheck && sbt Test/compile
```

## Output

```
Cloning into 'dotty-retypecheck'...
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 22 (delta 0), reused 19 (delta 0), pack-reused 0
Unpacking objects: 100% (22/22), done.
[info] welcome to sbt 1.3.13 (Oracle Corporation Java 10.0.1)
[info] loading settings for project global-plugins from console.sbt ...
[info] loading global plugins from /Users/atry/.sbt/1.0/plugins
[info] loading settings for project dotty-retypecheck-build from plugins.sbt ...
[info] loading project definition from /private/tmp/dotty-retypecheck/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] loading settings for project dotty-retypecheck from build.sbt ...
[info] set current project to dotty-retypecheck (in build file:/private/tmp/dotty-retypecheck/)
[info] Compiling 2 Scala sources to /private/tmp/dotty-retypecheck/target/scala-0.26/classes ...
[info] Compiling 1 Scala source to /private/tmp/dotty-retypecheck/target/scala-0.26/test-classes ...
[info] result of /private/tmp/dotty-retypecheck/src/test/scala/mypackage/Main.scala after typer:
[info] package mypackage {
[info]   final lazy module val Main: mypackage.Main$ = new mypackage.Main$()
[info]   final module class Main$() extends Object(), _root_.scala.Serializable { 
[info]     this: mypackage.Main.type =>
[info]     def main(args: Array[String]): Unit = 
[info]       if math.random().>(0.5) then 
[info]         {
[info]           println(identity[String]("then"))
[info]         }
[info]        else 
[info]         {
[info]           println(identity[String]("else"))
[info]         }
[info]   }
[info] }
[info] result of /private/tmp/dotty-retypecheck/src/test/scala/mypackage/Main.scala after inlinedPositions:
[info]   Unchanged since typer
[error] -- Error: /private/tmp/dotty-retypecheck/src/test/scala/mypackage/Main.scala:4:12 
[error] 4 |    println(identity("then"))
[error]   |            ^^^^^^^^
[error]   |            cannot infer type; expected type <?> is not fully defined
[info] result of /private/tmp/dotty-retypecheck/src/test/scala/mypackage/Main.scala after MyCompilerPlugin:
[info] package mypackage {
[info]   final lazy module val Main: mypackage.Main$ = new mypackage.Main$()
[info]   final module class Main$() extends Object(), _root_.scala.Serializable { 
[info]     this: mypackage.Main.type =>
[info]     def main(args: Array[String]): Unit = 
[info]       mypackage.MyHooks.ifThenElse[Unit](math.random().>(0.5), 
[info]         {
[info]           println(
[info]             identity[
[info]               <error cannot infer type; expected type <?> is not fully defined>
[info]             ]("then")
[info]           )
[info]         }
[info]       , 
[info]         {
[info]           println(identity[<error unspecified error>]("else"))
[info]         }
[info]       )
[info]   }
[info] }
[error] one error found
[error] (Test / compileIncremental) Compilation failed
[error] Total time: 4 s, completed Aug 8, 2020, 10:31:48 PM
```

## Expectation

It should compile.

**Comment by Atry** [comment]
Originally, I should dotty does not support retypecheck by design. However, as @odersky said at [this post](https://contributors.scala-lang.org/t/pre-sip-for-with-control-flow-an-alternative-to-scala-async-scala-continuations-and-scala-virtualized/4423/34?u=yangbo), retypechecking is supposed to be supported.

**Comment by smarter** [comment]
Retypechecking doesn't mean that you can simply reuse the original typer on already-typed tree. One has to use an instance of ReTyper for that. You can use `-Ycheck:nameOfPhase` (or `-Ycheck:all`) to verify that the retyper works correctly on some specific input after some phase (or all phases). Also I'm not sure what you're trying to do with this compiler plugin, but I would advise agaisnt trying to do retyping. The only compiler phase in Dotty that does that is Erasure, but everything else is done by manipulating typed trees (using the convenience method in `tpd.scala`)

**Comment by Atry** [comment]
I don't understand. If I am implementing something like `scala.Dynamic`, e.g. replacing regular calls to `applyDynamic` calls. I cannot use `tpd.Apply` because I don't know how to construct `TypeApply`s as the exact type signature of `applyDynamic` is unknown. What should I do?

**Comment by Atry** [comment]
> I don't understand. If I am implementing something like `scala.Dynamic`, e.g. replacing regular calls to `applyDynamic` calls. I cannot use `tpd.Apply` because I don't know how to construct `TypeApply`s as the exact type signature of `applyDynamic` is unknown. What should I do?

Currently, `Dynamic` is implemented inside the dotty typer. I wonder if it is possible to implement it as a separate phase.

**Comment by smarter** [comment]
> Currently, Dynamic is implemented inside the dotty typer. I wonder if it is possible to implement it as a separate phase.

No, because we need to assign a type to every expression, and that type can in turn influences the typechecking of subsequent expressions.
