### ISSUE TITLE
Document extension methods make members available without selection

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9562]
## Minimized example

```Scala
class Foo:
  def foo = 23

object Unrelated:                                                                                                
  extension (f: Foo)
    def bar: Int = foo // ok
```

## Output

compiles ok. In `0.25.x` and earlier you would have to explicitly select `f.foo`.

**Comment by liufengyun** [comment]
While this provides convenience, a little concern I have is that it complicates program understanding. It takes just a few keystrokes to write a much easy to understand program.

**Comment by liufengyun** [comment]
Discussed in the team meeting, we should restrict the feature to extension methods of the same extension block.
