### ISSUE TITLE
Export syntax for extension methods is different from import syntax for extension methods

### ISSUE THREAD

**Issue by neko-kai** [lampepfl/dotty#9702]
## Minimized code

```Scala
abstract class WordSpec {
  export inner.in
  
  object inner {
    extension(s: String) def in(f: => Any): Unit = {
      println(s)
      f
    }
  }

}

object test extends WordSpec {
  "should add numbers" in {
    assert(1 + 1 == 2)
  }
}
```

https://scastie.scala-lang.org/7ig3Te0zT3e5D4vEVnlIbA

## Output

```scala
value in is not a member of String, but could be made available as an extension method.

The following import might fix the problem:

  import test.inner.in
```

## Expectation

Adding `import inner.in` as the error suggests [_WILL_](https://scastie.scala-lang.org/lpdayJcxSnuzxBAncNPRqQ) fix the issue, however the `export inner.in` directive should have fixed the error by itself as well. It doesn't because the correct syntax was `export inner.extension_in`, if that is written the code works, however that means that the same symbol must be referred by two different names in export and import clauses which is very inconsistent:

```
import inner.in
export inner.extension_in
```

**Comment by odersky** [comment]
I believe this issue is now moot, since we don't use the `extension_` encoding anymore.
