### ISSUE TITLE
No error when exporting members that do not exist

### ISSUE THREAD

**Issue by neko-kai** [lampepfl/dotty#9703]
## Minimized code

```Scala
abstract class WordSpec {
  export inner.in
  
  object inner {
    extension(s: String) def in(f: => Any): Unit = {
      println(s)
      f
    }
  }

}

object test extends WordSpec {
  "should add numbers" in {
    assert(1 + 1 == 2)
  }
}
```

https://scastie.scala-lang.org/7ig3Te0zT3e5D4vEVnlIbA

## Output

```scala
value in is not a member of String, but could be made available as an extension method.

The following import might fix the problem:

  import test.inner.in
```

## Expectation

The reason the above code doesn't compile is because the export statement is [(arguably)](https://github.com/lampepfl/dotty/issues/9702) incorrect. When changed to:

```scala
export inner.extension_in
```

the code works. However, there's no error to suggest that member `inner.in` doesn't actually exist when trying to export it, instead of the correct member `inner.extension_in`

**Comment by odersky** [comment]
No longer an issue since we don't use `extension_` anymore.
