### ISSUE TITLE
Cannot create renamed copies of members of `this` using `export` 

### ISSUE THREAD

**Issue by neko-kai** [lampepfl/dotty#9704]
## Minimized code

```Scala
abstract class WordSpec {
  export this.{extension_in => extension_should}
  
  extension(s: String) def in(f: => Any): Unit = {
    println(s)
    f
  }
}

object test extends WordSpec {  
  "X" should {
    "add numbers" in {
     assert(1 + 1 == 2)
    }
  }
}
```

## Output

```scala
no eligible member extension_in at this
this.extension_in cannot be exported because it is already a member of class AnyWordSpec
  export this.{extension_in => extension_should}
```

## Expectation

Seems like the check for duplicates is over-eager and happens before renames are taken into account, making it illegal to rename symbols in `this`, but legal otherwise.  Workaround is to create a proxy object and re-export from it:

```scala
abstract class WordSpec {
  export inner.{extension_in => extension_should}
  export inner.extension_in
  
  object inner {
    extension(s: String) def in(f: => Any): Unit = {
      println(s)
      f
    }
  }
}
```

**Comment by odersky** [comment]
The behavior corresponds to what the spec says:

> A member is _eligible_ if all of the following holds:
>  - its owner is not a base class of the class[(\*)](#note_class) containing the export clause, ...

If we want to change this we'd need a feature request, and a discussion in depth. I personally think that a change would not be simple at all. There would be many things to specify, what constutes a clash and what doesn't.

**Comment by som-snytt** [comment]
Existing feature request at https://github.com/lampepfl/dotty-feature-requests/issues/148
