### ISSUE TITLE
Multiple language features in scalacOptions not recognized

### ISSUE THREAD

**Issue by oyvindberg** [lampepfl/dotty#9719]
Apologies if this is a duplicate, but I couldnt find anything right away.

With 0.27.0-RC1 and sbt-dotty 0.4.2, my project had these scalacOptions

```
sbt:std> show scalacOptions
[info] * -bootclasspath
[info] * ...
[info] * -language:implicitConversions
[info] * -language:higherKinds
[info] * -language:existentials
```

This triggered the warnings about implicit conversions:
```
[warn] Flag -language set repeatedly
[warn] Flag -language set repeatedly
...
[warn] 42 |    def deleteType: Self = this.set("type", js.undefined)
[warn]    |                                            ^^^^^^^^^^^^
[warn]    |Use of implicit conversion method undefOr2jsAny in object | should be enabled
[warn]    |by adding the import clause 'import scala.language.implicitConversions'
[warn]    |or by setting the compiler option -language:implicitConversions.
[warn]    |See the Scala docs for value scala.language.implicitConversions for a discussion
[warn]    |why the feature should be explicitly enabled.
```

I eventually discovered the warnings about multiple language flags and tried the following:
```
sbt:std> show scalacOptions
[info] * -bootclasspath
[info] * ...
[info] * -language:implicitConversions,higherKinds,existentials
```

So that worked, but we might want to support the former way of passing multiple language feature flags as well

**Comment by som-snytt** [comment]
This ticket is duplicated by https://github.com/lampepfl/dotty-feature-requests/issues/126

**Comment by oyvindberg** [comment]
Sure you got that link right @som-snytt ? It's true that part of my issue here was a few kilometers of implicit conversion warnings in the terminal during compilation, but it doesn't otherwise seem like the same issue.

**Comment by som-snytt** [comment]
Sorry about that, corrected!
