### ISSUE TITLE
Ycheck that java classes are not used as objects

### ISSUE THREAD

**Issue by DarkDimius** [lampepfl/dotty#972]
This passes Ycheck, bu it should not:

```
import java.lang.Math

val myMath: Math.type = Math
myMath.sqrt(3.0)
```

**Comment by liufengyun** [comment]
@DarkDimius when I run the code on my machine, it generates compiling errors. It seems this issue is already fixed.

```
tests/neg/i972.scala:4: error: object Math is not a value
  val myMath: Math.type = Math
              ^
tests/neg/i972.scala:4: error: object Math is not a value
  val myMath: Math.type = Math
                          ^
two errors found
```

The code for `tests/neg/i972.scala`:

``` Scala
import java.lang.Math

object Foo {
  val myMath: Math.type = Math
  myMath.sqrt(3.0)
}
```

**Comment by DarkDimius** [comment]
@liufengyun, the errors you are showing are Typer errors. 
The issue that I was talking about is that if phases generate such code, it will pass Ycheck and trigger an exception in GenBCode.

**Comment by liufengyun** [comment]
@DarkDimius thanks for explanation. If I were to work this issue, how can I reproduce the error?

**Comment by DarkDimius** [comment]
You need to create a phase, that does something similar to:

```scala
val JLMath = ctx.requiredModule("java.lang.Math")
SyntheticValDef("myMath".toTermName, ref(JLMath)) // this tree should not pass Ycheck
Apply(ref(idFunction), ref(JLMath)) // this tree should not pass Ycheck
```

I believe that the best way to check is: if there is an `Ident` or `Select` that refers to java module, it needs to be wrapped with a `Select` around it.

**Comment by liufengyun** [comment]
Thanks @DarkDimius for the tip.

The thing I'm still unclear is, if the code can't pass the front-end type checking, does it mean it can never happen, thus we can save the check?

**Comment by DarkDimius** [comment]
> if the code can't pass the front-end type checking, does it mean it can never happen, thus we can save the check?

Ycheck exists not to check user. It exists to verify correctness of phases and tress transformed by them.
This could happen if one writes a phases, that treats all `modules` equally, even those coming from Java. I had a master student fall in this trap.
