### ISSUE TITLE
REPL imports not overriding predef

### ISSUE THREAD

**Issue by mpilquist** [lampepfl/dotty#9720]
## Minimized code

Using the `develop` branch of the [fs2 repository](https://github.com/typelevel/fs2) and running `sbt ;project coreJVM;console`:

```Scala
scala> import fs2.Stream

scala> Stream(1)                                                                                                                                                                
1 |Stream(1)
  |^^^^^^
  |getter Stream in package scala is deprecated since 2.13.0: Use LazyList instead of Stream
val res0: Stream[Int] = Stream(1, <not computed>)

scala> fs2.Stream(1)                                                                                                                                                            
val res1: fs2.Stream[fs2.Pure, Int] = Stream(..)
```

Despite the explicit import of `fs2.Stream`, the call to `Stream(1)` is resolved as a call to `scala.Stream(1)` instead of `fs2.Stream(1)`.

**Comment by som-snytt** [comment]
Related to https://github.com/lampepfl/dotty/issues/7635 where resolution is against the class path before repl history.
