### ISSUE TITLE
Improve error messages for match types

### ISSUE THREAD

**Issue by IndiscriminateCoding** [lampepfl/dotty#9734]
## Minimized code

```Scala
trait Nil
trait ::[A, T]

type Snoc[A, T] = T match {
  case Nil => A :: Nil
  case h :: t => h :: (A Snoc t)
}

object Error {
  def snoc[A, T]: Snoc[A, T] = ???
  def typeError: Nothing = snoc[Int, String :: Nil]
}
```

## Output

```scala
Found:    pkg.Snoc[Int, String :: pkg.Nil]
Required: Nothing
```

## Expectation

Not sure if I should report this as a bug (sorry if not).

Match types could be made more user-friendly if this error message was printed as:
```scala
Found:    String :: Int :: pkg.Nil
Required: Nothing
```
Looks like reduction depth for recursive match types is limited, would it be possible to increase it?

**Comment by smarter** [comment]
> Looks like reduction depth for recursive match types is limited, would it be possible to increase it?

Sure, but this might not be a good idea: if you're using a match type to generate a really complicated type with lots of implementation details, expanding it might make the error message a lot less readable. I don't know what the correct thing to do is, but it doesn't seem like there's one easy fix here and more discussion is needed. As such, I'll close this issue and recommend either starting a discussion in https://contributors.scala-lang.org/ or posting on https://github.com/lampepfl/dotty-feature-requests which is more open-ended.
