### ISSUE TITLE
No warning/error when matching unrelated object types

### ISSUE THREAD

**Issue by olofwalker** [lampepfl/dotty#9740]
## Minimized code

Dotty 0.27-RC1

```Scala
object Main:

  abstract class RecoveryCompleted
  case object RecoveryCompleted extends RecoveryCompleted
  
  abstract class TypedRecoveryCompleted 
  case object TypedRecoveryCompleted extends TypedRecoveryCompleted

  TypedRecoveryCompleted match {
    case RecoveryCompleted => println("Recovery completed")
    case TypedRecoveryCompleted => println("Typed recovery completed")
  }
```

## Output

Nothing

## Expectation

Something like:

```
pattern type is incompatible with expected type;
 found   : ammonite.$sess.cmd5.RecoveryCompleted.type
 required: ammonite.$sess.cmd7.TypedRecoveryCompleted.type
    case RecoveryCompleted => println("Recovery completed")
```

**Comment by liufengyun** [comment]
This seems to be the correct behavior. See the following example:

```Scala
class Error {
  abstract class RecoveryCompleted
  case object RecoveryCompleted extends RecoveryCompleted {
    override def equals(that: Any): Boolean = that == TypedRecoveryCompleted
  }

  abstract class TypedRecoveryCompleted
  case object TypedRecoveryCompleted extends TypedRecoveryCompleted


  TypedRecoveryCompleted match {
    case RecoveryCompleted => println("Recovery completed")
    case TypedRecoveryCompleted => println("Typed recovery completed")
  }
}

object Test {
  def main(args: Array[String]): Unit = new Error
}
```

The first branch matches.

**Comment by liufengyun** [comment]
Related: #3200 https://github.com/scala/bug/issues/1503

**Comment by olofwalker** [comment]
@liufengyun 

This fails in 2.13, I just assumed this would also fail in Dotty.

```
pattern type is incompatible with expected type
[error]  found   : Error.this.RecoveryCompleted.type
[error]  required: Error.this.TypedRecoveryCompleted.type
```

The context for this is that I never got a `RecoveryCompleted` signal to fire in an Akka persistent actor, it turned out there are two of those classes, one for `classic` actors and one for `typed`, and I had imported and used the wrong one.

**Comment by liufengyun** [comment]
@olofwalker Thanks for clarifying the context. It's a difference between Scala 2 and Scala 3.

Maybe Scala 3 should be more conservative here to pretend such mistakes.

**Comment by som-snytt** [comment]
I thought `case X =>` was equals and `case _: X.type =>` was eq, but scala 2 gives different results depending on scrutinee:
```
  def f(): Unit =
    TypedRecoveryCompleted match {
      case _: RecoveryCompleted.type => println("Recovery completed")
      case TypedRecoveryCompleted => println("Typed recovery completed")
    }
  def g(): Unit =
    (TypedRecoveryCompleted: Any) match {
      case _: RecoveryCompleted.type => println("Recovery completed")
      case TypedRecoveryCompleted => println("Typed recovery completed")
    }
```
It's the middle of the night here, I was just taking a break, so maybe my brain stopped working.

Maybe the identifiers are too long. Is it a typo?

Actually repl 2 won't even compile it.

```
scala 2.13.3> X match { case _: Y.type => 1 case _ => 2 }
                                 ^
              warning: fruitless type test: a value of type X.type cannot also be a Y.type (the underlying of Y.type)
error: Error while emitting <console>
assertion failed:
  Trying to access the this of another class: tree.symbol = class $read, class symbol = class iw compilation unit: <console>
     while compiling: <console>
        during phase: jvm
     library version: version 2.13.3
    compiler version: version 2.13.3
  reconstructed args: -deprecation -feature -Wconf:cat=feature:w -Wconf:cat=deprecation:w -Wconf:cat=deprecation:ws -Wconf:cat=feature:ws -Wconf:cat=optimizer:ws

  last tree to typer: Literal(Constant(type))
       tree position: <unknown>
            tree tpe: Class(classOf[])
              symbol: null
           call site: constructor $iw in package $line4

== Source file context for tree position ==
```

**Comment by olofwalker** [comment]
@liufengyun I think I would have been helped by a warning, its a bit like Scala 2, you unknowingly import an implicit, and all of a sudden things work differently.

**Comment by smarter** [comment]
We can't just copy what 2.13 is doing here as demonstrated by Fengyun's example in https://github.com/lampepfl/dotty/issues/9740#issuecomment-688157605, scalac wrongly emits an error even though this code is correct. We would have to check if `equals` in `RecoveryCompleted` is compiler-generated first

**Comment by liufengyun** [comment]
> We can't just copy what 2.13 is doing here as demonstrated by Fengyun's example in [#9740 (comment)](https://github.com/lampepfl/dotty/issues/9740#issuecomment-688157605), scalac wrongly emits an error even though this code is correct. We would have to check if `equals` in `RecoveryCompleted` is compiler-generated first

It is incomplete, but it seems sound/safe to reject the code. The additional expressiveness seems to be not useful in practice, and usually implies something goes wrong.

**Comment by smarter** [comment]
It's safe but it might be annoying to someone :). But I think if we only emit the warning if `scrutinee.is(Case) && scrutineeEqualsMethod.is(Synthetic)` then it's fine and catch the cases we're interested in.

**Comment by smarter** [comment]
Oops actually we want check the symbol of the case, not the symbol of the scrutinee.

**Comment by liufengyun** [comment]
After reflection, I think the correct thing to do is either (1) disallow all such cases; or (2) allow all such cases. Anything in the middle (like checking whether the member `equals` is overridden) only complicates the protocol.

Disallowing all such usage would align with Scala 2 and prevent accidental errors in practice. It's safe and sound -- incompleteness is fine, as static checks are all incomplete for good reasons. 

Are there valid use cases that justify allowing such usage?

**Comment by dwijnand** [comment]
I agree.  Can always make it more complicated if that proves too annoying - which hasn't appeared to be the case for Scala 2 users so far.

The argument around Fengyun's example to me seems to revolve around the fact that any scrutinee type (e.g. `TypedRecoveryCompleted.type`) is a subtype of Any and that any class can redefine its equals to be true for that singleton.  But (1) that's unlawful for equals (though the type system can't rely on that) and (2) (more importantly) making that concession undermines the reachability checking/safety of all matches.
