### ISSUE TITLE
No completions from standard library symbols

### ISSUE THREAD

**Issue by tgodzik** [lampepfl/dotty#9760]
## Minimized code

In Metals we are reusing the Dotty language server code in the form of:

```Scala
 val uri = params.uri
      val sourceFile = CompilerInterfaces.toSource(params.uri, params.text)
      driver.run(uri, sourceFile)

      given ctx as Context = driver.currentCtx
      val pos = sourcePosition(driver, params, uri)
      val items = driver.compilationUnits.get(uri) match {
        case Some(unit) =>
          Completion.completions(pos)(using ctx.fresh.setCompilationUnit(unit))._2
        case None => Nil
      }
```

Currently though when trying to complete for example:
```
object A
  prin
```

we are not getting any completions. This regressed in 0.27.0-RC1.

Expected would for example `print` or `println`. This seems to have happened to anything that is not in a local scope.

**Comment by prolativ** [comment]
This issue was fixed by https://github.com/lampepfl/dotty/pull/9805 and should be closed

**Comment by tgodzik** [comment]
I can confirm, let's close it! :tada:
