### ISSUE TITLE
dotty scalajs: @JSImport has no effect

### ISSUE THREAD

**Issue by aappddeevv** [lampepfl/dotty#9762]
##  Problem

I have the working project here: https://github.com/aappddeevv/dotty-scalajs

The import of a node package is in https://github.com/aappddeevv/dotty-scalajs/blob/master/src/main/scala/fetch.scala.

The issue is that @JSImport does not seem to cause the js import (require for a node application) to be issued into the linked file.

## Expectation
`@JSImport` should generate the equivalent js import in the link file.

**Comment by sjrd** [comment]
I believe this will be fixed by #9725.

**Comment by aappddeevv** [comment]
I tried the nightly build which I think included #9725 but it did not seem to fix it.

**Comment by aappddeevv** [comment]
I think this is fixed.
