### ISSUE TITLE
Extension method can be extension_foo

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9766]
## Minimized code

```Scala
extension (x: Any) def extension_foo: String = "foo"
```

## Output

compiles ok

## Expectation

any other definition can not start with `extension_`, so I would expect this not to work.

the desugared method is `extension_extension_foo`, should there be an extra check in Desugar for the unexpanded extension method name beginning like that?

**Comment by odersky** [comment]
> the desugared method is extension_extension_foo, should there be an extra check in Desugar for the unexpanded extension method name beginning like that?

I think so, yes.
