### ISSUE TITLE
DottyJS doesn't understand -P flag

### ISSUE THREAD

**Issue by djspiewak** [lampepfl/dotty#9783]
It's standard practice to add a JavaScript sourcemap to ScalaJS-generated output files. For example:

```
-P:scalajs:mapSourceURI:file:/Users/daniel/Development/Scala/coop/->https://raw.githubusercontent.com/djspiewak/coop/b82b37f4da7b1cb831f32a2fda1150162e5b29d8/
```

This works just fine on Scala 2, but Dotty currently rejects this compiler option. It would be nice if some equivalent could be restored so that we avoid regressing functionality for users of JavaScript debuggers.

**Comment by sjrd** [comment]
Third has now been implemented and will be part of the next release. However, the option name is slightly different:
* In Scala 2: `-P:scalajs:mapSourceURI:...`
* In Scala 3: `-scalajs-mapSourceURI:...`

The name had to be different. The `-P` option prefix is to give options to a compiler plugin, but in Scala 3, Scala.js is not a compiler plugin.
