### ISSUE TITLE
Preserve type at assignment operator

### ISSUE THREAD

**Issue by oofp** [lampepfl/dotty#9808]
## Minimized example

```Scala
val intOrString:Int|String = 1
val intOrString2 = intOrString
```

## Output

```scala
val intOrString2: Any = 1
```

## Expectation
```scala
val intOrString2: Int|String = 1
```

**Comment by odersky** [comment]
The rules currently say that union types are widened for type inference unless a union type is explicitly specified. So this behavior is as specified. Changing it would be potential upset a lot of other things. Note the analogy to singleton types
here:

```scala
val x: 1 = 1
val y = x
```
`y` has type `Int`, not `1`. So I think this should be re-filed as a feature request. It has to be thought through from the ground up and needs careful evaluation.
