### ISSUE TITLE
Problem compiling enum on Scala.js

### ISSUE THREAD

**Issue by ekrich** [lampepfl/dotty#9809]
## Minimized code
Scala.js `1.2.0`
Dotty `0.27.0-RC1`

```Scala
enum ConfigSyntax extends jl.Enum[ConfigSyntax] {
  case JSON
  case CONF
  case PROPERTIES
}
```

## Output

```scala
[error] Assignment to static member org.ekrich.config.ConfigSyntax.JSON not supported
```

## Expectation

This works fine compiling for JVM so I would expect it to work for Scala.js as well.

## Repo
https://github.com/ekrich/sconfig/tree/topic/dotty-js

**Comment by djneades** [comment]
I ran into this as well with the current nightly (0.28.0-bin-20200920-e99793e-NIGHTLY). The problem also occurs with the basic enum example in the [Dotty documentation](http://dotty.epfl.ch/docs/reference/enums/enums.html):

```
enum Color(val rgb: Int) {
  case Red   extends Color(0xFF0000)
  case Green extends Color(0x00FF00)
  case Blue  extends Color(0x0000FF)
}
```

Compiler output:

```
[error] Assignment to static member com.araxis.test.Color$.Red not supported
[error] (Compile / compileIncremental) Compilation failed
```
