### ISSUE TITLE
Given value not found when imported

### ISSUE THREAD

**Issue by etorreborre** [lampepfl/dotty#9810]
## Minimized code

The following code declares an implicit value inherited in an object definition:
```Scala
trait ImplicitValue:
  given value as Int = 0

object ImplicitValue extends ImplicitValue

trait UseIt:
  import ImplicitValue._

  def function(v: Int = value): Int = v
```

## Output

When compiling
```scala
60 |  def function(v: Int = value): Int = v
[error]    |                        ^^^^^
[error]    |                        Not found: value
```

## Expectation

The expectations is that the `given` clause translates as `final implicit lazy val` as mentioned in the documentation and that `value` is found when the object members are imported. The work-around is to qualify the `value`:
```scala
  def function(v: Int = ImplicitValue.value): Int = v
```

**Comment by etorreborre** [comment]
My bad I should learn to read all the doc :-) https://dotty.epfl.ch/docs/reference/contextual/given-imports.html

**Comment by etorreborre** [comment]
Maybe in retrospect this could have use a message like:
```
Note: given instance value in trait ImplicitValue was not considered because it was not imported with `import given`.
```
(and `import given` is a bit confusing since the syntax is not `import given` but `import object.{given _}`?)

**Comment by som-snytt** [comment]
Someone just did the converse on gitter. This may be an ongoing source of friction. Maybe this is a job for an IDE, or maybe the messaging could be a feature request.

I'm going to google the old thread where I can vote for `given import x._` syntax.

**Comment by symbiont-eric-torreborre** [comment]
The syntax is fine with me. What is a bit troubling is that there is not a strict equivalence between using `implicit lazy val` and `given`. A proper message giving a better clue about the import syntax would have really helped me.
