### ISSUE TITLE
var reassignment fails when implementing a trait that defines getter only (List cons)

### ISSUE THREAD

**Issue by Sciss** [lampepfl/dotty#9820]
## Minimized code

```Scala
trait ControlBuilder[P] {
  def +=(p: P): Unit
  def result: Seq[P]  // getter only!
}

object AudioControl {
  case class Proxy(name: String)
  
  class Factory extends ControlBuilder[Proxy] {
    var result = List.empty[Proxy]  // var now!

    def +=(p: Proxy): Unit = result ::= p  // fails
  }
}
```

## Output

```scala
value ::= is not a member of Seq[AudioControl.Proxy]
```

## Expectation

it should figure out that `result ::= p` means `result = p :: result` here.

Might have to do with the special inverted order behaviour of colon methods?

**Comment by Sciss** [comment]
Actually the problem seems to be that the trait defines `Seq` not `List` and `var result: List` doesn't seem to make the type more specific. Not sure if this is a bug or a more restrictive type inheritance in Dotty.

**Comment by Sciss** [comment]
Adding a type `var result: List[Proxy] = List.empty[Proxy]` solves it. Should the issue be closed?

**Comment by smarter** [comment]
Yes this is intentional, when an override is defined without an explicit result type, its type is now set to the type of the overridden definition (to avoid accidentally leaking types too precise in public APIs).
