### ISSUE TITLE
Confusing error message value not found when wrong indentation is used within a case definition

### ISSUE THREAD

**Issue by Sciss** [lampepfl/dotty#9822]
## Minimized code

```Scala
trait Test {
  case class XOut(index: Int, sig: Any, ok: Boolean)
  
  def run(xs: Seq[(Int, Any)], numOut: Int): Unit =
    xs.foreach {
      case (index, sig) =>
        val ok = index <= numOut
// comment
      XOut(index, sig, ok)  // produces error
    }
}
```

## Output

The compiler says

> Not found: ok

So it interprets the `XOut` line to be in an outer context, although technicially there can't be one here, as braces are used.

## Expectation

Should probably warn that the indentation is wrong.

**Comment by smarter** [comment]
The parser interprets this as:
```scala
package <empty> {
  trait Test {
    case class XOut(val index: Int, val sig: Any, val ok: Boolean) {}
    def run(xs: Seq[(Int, Any)], numOut: Int): Unit =
      xs.foreach(
        {
          case (index, sig) =>
            {
              val ok = index <= numOut
              <empty>
            }
            XOut(index, sig, ok)
        }
      )
  }
}
```
Which is pretty weird indeed.

**Comment by odersky** [comment]
> Which is pretty weird indeed.

I argue it's not weird at all. `=>` opens an indentation region, and the line with `XOut` closes it. 

> So it interprets the XOut line to be in an outer context, although technicially there can't be one here, as braces are used.

Indentation is also valid inside outer braces.

**Comment by smarter** [comment]
> I argue it's not weird at all. => opens an indentation region, and the line with XOut closes it.

Sure, but can't we emit an error on the XOut line anyway? After case .. => I expect to see one indentation region, not one indentation region and some stray unindented expression at the end
