### ISSUE TITLE
No deprecation warnings for type references

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9825]
## Minimized code

```Scala
object Module {
  @deprecated("Module.Foo is deprecated")
  type Foo[+A] = scala.List[A]
}

object Test {
  val m: Module.Foo[String] = List("wow")
}

```

## Output

```scala
// it compiles
```

## Expectation

in scala 2.13.4 we see

```scala
Deprecated.scala:7: warning: type Foo in object Module is deprecated: Module.Foo is deprecated
  val m: Module.Foo[String] = List("wow")
                ^
1 warning
```

**Comment by bishabosha** [comment]
so looks like the relevant code exists but is just in the the huge commented out section of RefChecks

**Comment by bishabosha** [comment]
it is currently impossible for refchecks to see this alias - as it is dealiased by the time refchecks occurs:

```scala
// with -Xprint:firstTransform
package <empty> {
  final lazy module val Module: Module$ = new Module$()
  @scala.annotation.internal.SourceFile("tests/neg/i9825.scala") final module 
    class
   Module$() extends Object() {
    private def writeReplace(): AnyRef = 
      new scala.runtime.ModuleSerializationProxy(classOf[Module.type])
    @deprecated("Module.Foo is deprecated", 
      deprecated.$lessinit$greater$default$2
    ) type Foo = List
  }
  final lazy module val Test: Test$ = new Test$()
  @scala.annotation.internal.SourceFile("tests/neg/i9825.scala") final module 
    class
   Test$() extends Object() {
    private def writeReplace(): AnyRef = 
      new scala.runtime.ModuleSerializationProxy(classOf[Test.type])
    val m: List[String] = List.apply[String](["wow" : String]:String*)
  }
}
```

**Comment by smarter** [comment]
In some situation we don't dealias type applications because it changes type inference, you could try expanding that set of conditions to include situations where the type has annotations:
https://github.com/lampepfl/dotty/blob/8e9ac7519b56a452348b878979f56ff01308cc8e/compiler/src/dotty/tools/dotc/core/TypeApplications.scala#L319-L325

**Comment by bishabosha** [comment]
@smarter that doesn't take into account type aliases without arguments, such as `type Foo = String` which are also widened at firstTransform - perhaps this is not meant to happen?

**Comment by smarter** [comment]
I don't know why those get dealiased at that point.

**Comment by bishabosha** [comment]
yes that was my mistake, it seems that the type of an Type tree referencing `type Foo = String` is `String`, so I would have to check that the symbol info is also not dealiased

**Comment by ckipp01** [comment]
Maybe it's implied, but is it expected to see the deprecation warning even when not using `-deprecation`? Because testing with it I do see it when using the flag.

**Comment by smarter** [comment]
This got fixed by moving deprecation checks before FirstTransform in https://github.com/lampepfl/dotty/pull/17301
