### ISSUE TITLE
Cannot write an abstract given declaration

### ISSUE THREAD

**Issue by nicolasstucki** [lampepfl/dotty#9848]
It is currently impossible to write an abstract given

```Scala
trait Bar:
  def doSomething: Unit

trait Foo:
  given Bar

class Baz extends Foo:
  given Bar = ...
```
The problem is that as `given Bar` has no implementation, it will automatically try to instantiate it but it cannot.

**Comment by nicolasstucki** [comment]
We can work around it by introducing an indirection like this
```scala
trait Bar:
  def doSomething: Unit

trait Foo:
  given Bar = BarImpl
  protected val BarImpl: Bar

class Baz extends Foo:
  protected def BarImpl: Bar = ...
```

**Comment by odersky** [comment]
The intention is to do it like this. There are no plans to introduce abstract given instances. A given instance brings something you define into implicit scope.

**Comment by odersky** [comment]
So if we want to pursue this it should be a feature request.
