### ISSUE TITLE
[match types] ill-formed recursion causes compiler to hang

### ISSUE THREAD

**Issue by IndiscriminateCoding** [lampepfl/dotty#9849]
## Minimized code

```Scala
type *:[A, B] = A match
  case (B *: x) => A
  case (x *: y) => x *: (B *: y)
  case _ => A *: B
```

## Output (click arrow to expand)
<details>
Well, not actually crash, but it hangs indefinitely
</details>

**Comment by griggt** [comment]
This no longer hangs after #7389.
