### ISSUE TITLE
Document type inference changes from Scala 2 regarding `Nothing`

### ISSUE THREAD

**Issue by griggt** [lampepfl/dotty#9855]
See https://github.com/lampepfl/dotty/issues/9842#issuecomment-697280687

The [current documentation on changes in type inference](http://dotty.epfl.ch/docs/reference/changed-features/type-inference.html) is empty.

**Comment by smarter** [comment]
It's described in my talk, which could be linked from that page: https://www.youtube.com/watch?v=lMvOykNQ4zs
