### ISSUE TITLE
Error message for using/given resolution failure

### ISSUE THREAD

**Issue by vincenzobaz** [lampepfl/dotty#9874]
Although new keywords have been introduced to replace `implicit`, the compiler still uses this term when it fails to find a `given` instance for a `using` paramenter.

## Minimized example

```Scala
def x(using y: Int): Int = y

trait A
given loop(using a: A) as A = a

@main def main() = {
  x
  summon[A]
}
```

## Output

```
no implicit argument of type Int was found for parameter y of method x

no implicit argument of type A was found for parameter x of method summon in object DottyPredef.
I found:

    main$package.loop(/* missing */summon[A])

But method loop produces a diverging implicit search when trying to match type A.
```

## Expectation
I suggest to use the new terminology, for example:

```
no given instance of type Int was found for context parameter y of method x
no given instance of type A was found for context parameter x of method summon
```

**Comment by som-snytt** [comment]
Duplicates https://github.com/lampepfl/dotty/issues/7710 where a comment mentions "cohesion enhancements".

**Comment by bishabosha** [comment]
This one is a duplicate, but the proposed correction looks good
