### ISSUE TITLE
REPL input of extension methods using whitespace syntax incorrectly stops parsing after first newline

### ISSUE THREAD

**Issue by mpilquist** [lampepfl/dotty#9878]
## Minimized code

```Scala
➜  dotr -version
Starting dotty REPL...
Dotty compiler version 0.27.0-RC1 -- Copyright 2002-2020, LAMP/EPFL
scala> extension (self: Int):
1 |extension (self: Int):
  |                      ^
  |                      Extension without extension methods
scala> trait Foo:
     |   def foo: Int
     |
// defined trait Foo
```

## Expectation

The REPL stops parsing after first newline and reports that no extension methods are defined. Instead, it should only stop parsing input after a subsequent newline, like in the case of the `trait Foo:` example.

**Comment by som-snytt** [comment]
Duplicates https://github.com/lampepfl/dotty/issues/9374
