### ISSUE TITLE
REPL Trying to highlight erroneous position

### ISSUE THREAD

**Issue by som-snytt** [lampepfl/dotty#9885]
## Minimized code

```Scala
Starting dotty REPL...
scala> def (
```

## Output

```scala
Starting dotty REPL...
scala> def Trying to highlight erroneous position [4..21]. Input size: 5
(
```

## Expectation

Good position for bad code.

Noticed at https://gitter.im/lampepfl/dotty?at=5f6eab495b75b305ddc6bde3

**Comment by izhangzhihao** [comment]
Confirm fixed in 3.0-M3:

```
scala> def (
1 |def (
  |    ^
  |    an identifier expected, but '(' found
1 |def (
  |     ^
  |     '=' expected, but eof found
```

**Comment by som-snytt** [comment]
Fixed in M1 by https://github.com/lampepfl/dotty/commit/3bb85e53024023fa139aa78b8bced9c40a419eae

in updated extension syntax 
https://github.com/lampepfl/dotty/pull/9845

**Comment by som-snytt** [comment]
Misc regression tests were added in https://github.com/lampepfl/dotty/pull/10007 but the bad pos issue needs a pos-checking test.
