### ISSUE TITLE
Breaking change: removal of dotty.tools.dotc.quoted.reflect.ReflectionCompilerInterface

### ISSUE THREAD

**Issue by gzoller** [lampepfl/dotty#9924]
A recent Dotty build removed dotty.tools.dotc.quoted.reflect.ReflectionCompilerInterface, which is a breaking change and I haven't yet found a workaround.

My use case:

I have a compiler plugin where I want to do some reflection in order to modify code generation.
```scala
class ReflectionWorkerPhase extends PluginPhase {
  import tpd._

  val phaseName = "reflectionWorker"

  override val runsAfter = Set(Pickler.name)

  override def transformTypeDef(tree: TypeDef)(implicit ctx: Context): Tree = 
    if tree.isClassDef && !tree.rhs.symbol.isStatic then  // only look at classes & traits, not objects
      val reflect = new dotty.tools.dotc.quoted.reflect.ReflectionCompilerInterface(ctx) with scala.tasty.Reflection

      // perform reflection and modify tree...
    tree
}
```
This class has been removed and its replacement QuoteContextImpl has a private constructor.

I'd be happy with a workaround where I can get a QuoteContextImpl.tasty instance inside transformTypeDef() to use for reflection, but I haven't found one yet.

**Comment by bishabosha** [comment]
can you use `QuoteContextImpl.apply`?

**Comment by gzoller** [comment]
I'll try but I don't think so.  I tried apply (without the cast) and the compiler complained... said I couldn't access the constructor from my class.  Not 100% sure but I'm wondering if it's because under the covers of apply() it's calling a private constructor.  Will try again w/cast to see if that shakes anything up.  If not, I'll post the compiler error I get.

**Comment by gzoller** [comment]
That did the trick.  All good--thank you!
