### ISSUE TITLE
Cannot implement setter method for `var extension`

### ISSUE THREAD

**Issue by Sciss** [lampepfl/dotty#9926]
## Minimized code

https://scastie.scala-lang.org/vtB4qDpEQWKhpRfRKpmfTQ

```Scala
trait Config {
  def extension: String
}
trait ConfigBuilder extends Config {
  override var extension: String
}
class ConfigBuilderImpl extends ConfigBuilder {
  private var _ext = "cache"
  private var _extSet = false
  
  def extension: String = _ext
  
  def extension_=(value: String): Unit = {  // !
    _extSet = true
    _ext = value
  }
}
```

## Output

```none
illegal method name: extension_= may not start with `extension_`
```

## Expectation

It seems counter-intuitive that you can define a `var extension` but not implement a setter method.

**Comment by bishabosha** [comment]
PR https://github.com/lampepfl/dotty/pull/9836 should be updated to deal with this and block var extension

**Comment by bishabosha** [comment]
or should we allow `extension_=` if it overrides a method with setter flag?

**Comment by b-studios** [comment]
I think it might end up more consistent if we disallow it altogether.

**Comment by bishabosha** [comment]
decision was made to forbid this

**Comment by nicolasstucki** [comment]
We could maybe try to use an `_extension` suffix instead of `extension_` prefix for extension methods. At first glance it looks like it would have fewer conflicting names.

**Comment by griggt** [comment]
Would that require `+_extension` to be written as `` `+_extension` `` by the user in an explicit reference?

**Comment by Sciss** [comment]
is there a reason no special characters such as `$` are used, as happens for example in specialization, default values, etc. ?

**Comment by bishabosha** [comment]
I would assume because it is intended to be used by the user, as opposed to those other constructs that should not be called explicitly

**Comment by TheElectronWill** [comment]
Isn't it a bit too "strong" to disallow `var extension`? Since `extension` is a relatively common name, newcomers might find surprising that `val extension` is allowed but if we use `var` and if the variable is non-local then it's forbidden.
