### ISSUE TITLE
Opaque types and implicit specificity

### ISSUE THREAD

**Issue by vincenzobaz** [lampepfl/dotty#9928]
## Minimized code

```Scala
trait Magic[F]:
  extension (x: Int) def read: F

object Magic:
  given Magic[String]:
    extension(x: Int) def read: String = 
      println("In string")      
      s"$x"

opaque type Foo = String
object Foo:
  import Magic.{given _}
  def apply(s: String): Foo = s

  given Magic[Foo]:
    extension (x: Int) def read: Foo =
      println("In foo")
      Foo(s"$x")
  
  def test: Unit =
    (3.read: Foo)
  

@main def test = {
  Foo.test
}
```

## Output
`In string`

## Expectation
`In foo`

## Remarks 
 - If `import Magic.{given _}` is removed, the output is as expected. The question is: should this import change the behavior? `given Magic[Foo]` should be more specific and preferred to `given Magic[String]`

## Snippet
https://scastie.scala-lang.org/vincenzobaz/tGQhSpQ8TQyiOeTNAvSGbA/104

**Comment by b-studios** [comment]
I would not expect `Foo` to be more specific than `String` in the context of the companion object, since there the equality `Foo = String` holds.

However,  I understand that it is confusing that the (preceding) import shadows the local definition.

Ergonomically, this is related to #9880.

**Comment by som-snytt** [comment]
I was also confused https://github.com/lampepfl/dotty/issues/8092

In fact, I'm still confused.

**Comment by b-studios** [comment]
Thanks for reminding me of that issue @som-snytt. There is indeed three different behaviors that would be justifiable.

1. Local definition shadows (what's described here)
2. Implicits are stacked as currently implemented and described by @odersky in #8092.
3. Implicits are in the same scope and trigger an ambiguity.

**Comment by som-snytt** [comment]
Thanks, I'll have to put some time aside over the weekend to study up!

**Comment by odersky** [comment]
6a898ad implements

> 3. Implicits are in the same scope and trigger an ambiguity.

#8092 is unaffected since there the import is properly nested wrt the definition.
