### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by michelou** [lampepfl/dotty#9931]
***Environment*** : MS Windows 10, OpenJDK 11.0.8+10, Scala 2.13.3, Dotty 0.27.0-RC1 (or nightly builds).

## Minimized code in Java

The minimized code in **Java** (2 source files) relies on [`JavaFX 14`](https://gluonhq.com/products/javafx/).

```Java
// File : JavaFXHelloWorld.java
package hello;

import javafx.application.Application;

class JavaFXHelloWorld {
    public static void main(String[] args) {
        Application.launch(JavaFXApplication.class, args);
    }
}
```

```Java
// File : JavaFXApplication.java
package hello;

import javafx.application.Application;
import javafx.stage.Stage;

// Class must be declared public (accessed via reflection).
public class JavaFXApplication extends Application {
    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("JavaFX Hello World");
        // (more)
        primaryStage.show();
    }
}
```

## Minimized code in Scala 2 / Scala 3 (Dotty):

The minimized code in **Scala** (1 source file) relies on [`ScalaFX 14-R19`](http://www.scalafx.org/news/releases/) (and indirectly on [`JavaFX 14`](https://gluonhq.com/products/javafx/)).

```Scala
package hello

import scalafx.application.JFXApp
import scalafx.application.JFXApp.PrimaryStage

object ScalaFXHelloWorld extends JFXApp {
  stage = new PrimaryStage {
    title = "ScalaFX Hello World"
    // (more)
  }
}
```

## Output

1. Build/run of the **Java** code example with *Java 11* produces the following result:

   ![Image](https://raw.githubusercontent.com/michelou/shared-resources/master/images/JavaFX_Hello_World.png)

   **Details**:
   - See file [scalafx-java-commands.txt](https://raw.githubusercontent.com/michelou/shared-resources/master/scala/scalafx-java-commands.txt) for the commands executed from the Windows prompt.
    <div>&nbsp;</div>

2. Build/run the **Scala** example with *Scala 2.13.3* produces the following result:

   ![Image](https://raw.githubusercontent.com/michelou/shared-resources/master/images/ScalaFX_Hello_World.png)

    **Details**:
   - See file [scalafx-scala2-commands.txt](https://raw.githubusercontent.com/michelou/shared-resources/master/scala/scalafx-scala2-commands.txt) for the commands executed from the Windows prompt.
   - See file [scalac-print_scala2_2.13.3_MINI.scala](https://raw.githubusercontent.com/michelou/shared-resources/master/scala/scalac-print_scala2_2.13.3_MINI.scala) for IR output generated by `scalac -print`.
    <div>&nbsp;</div>

3. Build/run the **Scala** example with *Dotty 0.27.0-RC1* (and *0.28.0-NIGHTLY*) produces the following result:

```
"C:\opt\dotty-0.27.0-RC1\bin\dotr.bat" -classpath "%LOCALAPPDATA%\Temp\lib\scalafx_2.13-14-R19.jar;C:\opt\javafx-sdk-14.0.2.1\lib\javafx-swt.jar;C:\opt\javafx-sdk-14.0.2.1\lib\javafx.base.jar;C:\opt\javafx-sdk-14.0.2.1\lib\javafx.controls.jar;C:\opt\javafx-sdk-14.0.2.1\lib\javafx.fxml.jar;C:\opt\javafx-sdk-14.0.2.1\lib\javafx.graphics.jar;C:\opt\javafx-sdk-14.0.2.1\lib\javafx.media.jar;C:\opt\javafx-sdk-14.0.2.1\lib\javafx.swing.jar;C:\opt\javafx-sdk-14.0.2.1\lib\javafx.web.jar;W:\scalafx-examples\scalafx-hello-world\target\classes" hello.ScalaFXHelloWorld
Exception in thread "main" java.lang.ExceptionInInitializerError
        at hello.ScalaFXHelloWorld.main(ScalaFXHelloWorld.scala)
Caused by: java.lang.NullPointerException
        at scalafx.stage.Stage.title(Stage.scala:115)
        at scalafx.stage.Stage.title_$eq(Stage.scala:118)
        at hello.ScalaFXHelloWorld$$anon$1.<init>(ScalaFXHelloWorld.scala:32)
        at hello.ScalaFXHelloWorld$.<clinit>(ScalaFXHelloWorld.scala:61)
        ... 1 more
```
   **Details**:
   - See file [scalafx-scala3-commands.txt](https://raw.githubusercontent.com/michelou/shared-resources/master/scala/scalafx-scala3-commands.txt) for the commands executed from the Windows prompt.
   - See file [scalac-print_scala3_0.27.0-RC1_MINI.scala](https://raw.githubusercontent.com/michelou/shared-resources/master/scala/scalac-print_scala3_0.27.0-RC1_MINI.scala) for IR output generated by `dotc -pagewidth 256 -color never -Xprint:lambdaLift`.

## Expectation

The Scala code example executes successfully with Scala 2 and Scala 3 (Dotty).

**Comment by smarter** [comment]
`JFXApp` extends `DelayedInit` which is not supported by Dotty (https://dotty.epfl.ch/docs/reference/dropped-features/delayed-init.html), see also https://contributors.scala-lang.org/t/scala-3-delayedinit/1902, https://contributors.scala-lang.org/t/delayedinit-or-oncreate-any-solution/1748

**Comment by michelou** [comment]
@smarter Thanks for the feedback.
