### ISSUE TITLE
using is treated wrongly as keyword?

### ISSUE THREAD

**Issue by kpbochenek** [lampepfl/dotty#9943]
```scala
val x = 1
(x + 1) // => 2

val using = 1
(using + 1)  // ')' expected, but integer literal found
```

**Comment by odersky** [comment]
`(` `using` `id` is treated as an explicit argument list. I don't think we want to refine that.

**Comment by kpbochenek** [comment]
```scala
def fx(): Unit = (using + 1)   // ')' expected, but integer literal found
```
Here it cannot be treated as parameter list as there is no id in front.

Another thing:
```scala
(using i: Int) => 1 + 2   // ok
(using Int) => 1 + 2   // error
```

**Comment by odersky** [comment]
`syntax.md` defines what is legal grammar, and the examples are covered by it. 

The only thing it does not define is when `using` is interpreted as a soft keyword. Here, the answer is: when following an open parenthesis, `using`  is treated as starting a `using` parameter or argument clause.
