### ISSUE TITLE
No Mirror.SumOf available for case with secondary parameter list

### ISSUE THREAD

**Issue by bishabosha** [lampepfl/dotty#9985]
## Minimized code

```Scala
enum Foo:
  case Branch()(i: Int)

def m = summon[deriving.Mirror.SumOf[Foo]] 
```

## Output

```scala
1 |def m = summon[deriving.Mirror.SumOf[Foo]]
  |                                          ^
  |no implicit argument of type deriving.Mirror.SumOf[Foo] was found for parameter x of method summon in object DottyPredef
```

## Expectation

It seems limiting that Mirror is only defined for classes with state purely represented by their extractors. This also means there is no generic API for enum companions as `summon[Mirror.SumOf[MyEnum]].ordinal(foo)` is not always defined

**Comment by odersky** [comment]
We discussed this and decided to leave things as they are
